kafka/datadog_checks/kafka/data/metrics.yaml
kafka/metadata.csv
kafka/tests/common.py

Add a metric about the number of partitions whose in-sync replicas count is less than minIsr.
We'd need to monitor that metric to be alerted when some producers with `acks=all` config are not able to produce to a given topic.
Since the cardinality is pretty low, it shouldn't be a problem regarding the number of metrics collected by the check.

[kafka-check] add under min ISR partition count metric

---

arangodb/CHANGELOG.md
arangodb/datadog_checks/arangodb/__about__.py
requirements-agent-release.txt

Port metadata from arangodb release off of the release branch for RC4
release from: https://github.com/DataDog/integrations-core/pull/12097
mysql metadata is added in https://github.com/DataDog/integrations-core/pull/12100

Port metadata from arangodb release

---

haproxy/README.md

The parameter for "use_openmetrics" in the HAProxy configuration should be `"true"` not `True`. It throws an error reading the annotation due to bad syntax.
There are also no examples in any of the docs for how to use the annotations on a k8s Deployment type, so I added one.
The doc has a wrong value in it, which was not clear. 
There also are no examples in any of the docs for using a k8s deployment template with autodiscovery. It is briefly alluded to in: https://docs.datadoghq.com/agent/kubernetes/integrations/?tab=kubernetes#configuration however there are no examples shown anywhere. The examples are all use `Pod`, so it would be nice to show what a `Deployment` is supposed to look like.

Fix Typo in HAProxy Params, Add Deployment Example

---

kafka_consumer/CHANGELOG.md
kafka_consumer/datadog_checks/kafka_consumer/__about__.py
requirements-agent-release.txt

Ports release metadata from the release branch from https://github.com/DataDog/integrations-core/pull/12113/files

Port kafka consumer release metadata for RC4

---

datadog_checks_dev/tests/test_conditions.py
datadog_checks_dev/tests/test_subprocess.py

A few tests would break when the python executable was on a path with spaces in it (which happens when running the tests with `ddev test` on a mac), because we were passing a command as a string, which is split by spaces. This changes those to use the list form, which has spaces escaped automatically.

Fix dev package tests for executables with spaces

---

.gitattributes

Ensure Unix line feeds for all tracked non-binary files

---

sqlserver/datadog_checks/sqlserver/statements.py
sqlserver/tests/compose-ha/sql/aoag_primary.sql
sqlserver/tests/compose-high-cardinality-windows/setup.sql
sqlserver/tests/compose-high-cardinality/setup.sql
sqlserver/tests/compose-windows/setup.sql
sqlserver/tests/compose/setup.sql
sqlserver/tests/conftest.py
sqlserver/tests/test_statements.py

Include query stats & plan samples for encrypted plan cache entires:
* read out the `encrypted` field from both `sys.dm_exec_sql_text` and `sys.dm_exec_query_plan`
* allow `None` values for `query_signature`, `statement`, `obfuscated_statement`, `db.plan.definition` when we know it's encrypted
This also fixes the `collection_errors` message which used to say `can only parse strings` because it used to try to obfuscate a NULL plan. Now there will be no collection error as encrypted plans are expected to be NULL, and the `is_encrypted` field will make it clear that the plan or statement are missing because it's encrypted.
* Fix missing stats in case of encrypted procs. 
* Fix incorrect plan collection_error message in case of encrypted procs.

improve handling of encrypted stored procedures

---

datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/common/validator.py
datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/v2/migration.py

Example migration:
```json
"tile": {
"overview": "README.md#Overview",
"configuration": "README.md#Setup",
"support": "README.md#Support",
"changelog": "CHANGELOG.md",
"description": "Forward your Cacti RRDs to Datadog for richer alerting and beautiful graphing.",
"title": "Datadog-Cacti Integration",
"media": [],
"classifier_tags": [
"Supported OS::Linux",
"Category::Monitoring",
"Category::Log Collection"
]
},
"author": {
```

Move v2 manifest field `classifier_tags` under `tile`

---

varnish/tests/test_varnish.py

Add a test for invalid varnishadm
QA for https://github.com/DataDog/integrations-core/pull/11908
Note: you may be prompted to enter your password for this test when running locally:
`tests/test_varnish.py::test_check_invalid_varnishadm Password:`

Add test for invalid varnishadm

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/package.py
datadog_checks_dev/tests/tooling/commands/validate/test_package.py

Adds email validation to `ddev validate package`
[AI-2350](https://datadoghq.atlassian.net/browse/AI-2350)
The test I added is more indirect than I wanted, but currently importing anything from under `datadog_checks.dev.tooling.commands` makes an unrelated test fail, so this will have to do until that gets solved separately.

Validate emails when running `ddev validate package`

---

datadog_checks_dev/tests/tooling/manifest_validator/input_constants.py

Finish the classifier_tag migration by updating the test fixtures to properly be in the right location
Tests were failing since classifier_tags were at the root instead of the new proper location (under tile)

Move classifier_tags in test fixtures

---

mysql/CHANGELOG.md
mysql/datadog_checks/mysql/__about__.py
requirements-agent-release.txt

Backport mysql 7.37.x releases
[releasing the integration for RC6](https://github.com/DataDog/integrations-core/pull/12346)

Backport mysql 7.37.x release info

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/readmes.py

Fix validation for readme images
Validation is failing for this PR but giving a misleading message: https://github.com/DataDog/integrations-extras/pull/1339/files
```
image: https://raw.githubusercontent.com/RoadieHQ/roadie-backstage-plugins/main/plugins/frontend/backstage-plugin-datadog/docs/datadog-widget.png is linked in its readme but does not exist
```
Since the image is from github, right now we attempt to look for it in integrations-extras, but it is not there. This updates the validation to only check for images that live in the repo, and otherwise fail validation. Now the error will look like:
```
All images must be checked into the repo under the `backstage/images` folder. This image path must be in the form: https://raw.githubusercontent.com/DataDog/integrations-extras/master/ba …
```

Fix validation for readme images

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/config.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/saved_views.py

Saved views validations didn't report failures when a file in the manifest is not found, as opposed to most of the other asset validation, and this fixes that.
This also adds a warning when the config spec is not found.
[AI-2334](https://datadoghq.atlassian.net/browse/AI-2334)
This is currently hard to write tests for, so it was tested manually.

Check for missing assets on validation (saved views and config)

---

elastic/assets/service_checks.json

Fix an external link to the Elasticsearch Cluster Health API section of the official guide in the cluster health service check description from the Elasticsearch integration.
External doc link to the Elasticsearch website was outdated.

Fix the elasticsearch guide URL in the `cluster_health` service check

---

datadog_checks_dev/datadog_checks/dev/plugin/pytest.py

Noticed while working on a new integration, ddev uses Hatch envs but no e2e tests so was not caught

Properly support E2E testing for Hatch envs

---

snowflake/datadog_checks/snowflake/check.py
snowflake/tests/keys/token
snowflake/tests/test_unit.py

The `open` method with `binary` mode, does not accept an `encoding` argument. Removes the unnecessary `encoding` argument.
Support case
Fixes the error: `ValueError: binary mode doesn't take an encoding argument`

Fix reading of `token_path` option

---

datadog_checks_dev/datadog_checks/dev/plugin/pytest.py

Some checks need to clean up resources like long running threads

Emulate an Agent shutdown after every test that uses the `dd_run_check` fixture by default

---

envoy/datadog_checks/envoy/metrics.py

I've observed we are missing metrics from envoy ext_authz http filters. [Documentation](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter#statistics)
Also the `failure_mode_allowed` is missing for the rate limit filter even the other metrics are present [Documentation](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/rate_limit_filter#statistics)
Gathering a broader set of metrics

Add ext_authz metrics to envoy integration

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/test.py

Adds a new `--debug` option that gets passed to the test command and has the same behaviour as that for `ddev test`.
I wanted to be able to see output from prints while running tests.

Add a `--debug` (`-d`) flag to `ddev env test`

---

elastic/README.md

Deletes a statement from the Readme that is not accurate, as we don't require the `xpack.monitoring.collection.enabled` setting for any of the metrics we collect, there's nothing in the official docs that points to such a thing and I empirically double checked that it doesn't have an effect.
[AI-2464](https://datadoghq.atlassian.net/browse/AI-2464) (see the comments)

Delete inaccurate statement from Elastic integration readme

---

php_fpm/datadog_checks/php_fpm/vendor/fcgi_app.py

This PR fixes the PHP-FPM status read out using FastCGI. `sys` is used in determining the default encoding when retrieving the data on `FCGI_STDERR` in Python 3. Failing to import it causes the plugin to crash.
We'd like to collect metrics from & monitor our PHP-FPM instances using DataDog, but we don't want to expose those metrics using HTTP.
There are no tests for handling the UNIX path case, but we configured our instances such that they are only accessible by a UNIX socket. I'm unsure as to how to add those tests. If you _need_ tests, I'd like to give a try adding them.
I've also searched the issue list before creating this PR, and it seems #11480 was already created but closed, due to the fact that the bug report was incomplete.

Fix missing import in PHP-FPM's check

---

postgres/datadog_checks/postgres/postgres.py
postgres/datadog_checks/postgres/statements.py
postgres/metadata.csv
postgres/tests/compose/etc/postgresql/postgresql.conf
postgres/tests/test_statements.py

This adds support for tracking `blk_read_time` and `blk_write_time` data in Postgres databases if the configuration value which enables their usage is set.
This PR is an extension of #11618.

Track blk_read_time and blk_write_time for Postgres databases if track_io_timing is enabled

---

datadog_checks_base/CHANGELOG.md

Follow-up to https://github.com/DataDog/integrations-core/pull/11815. Changelog must be manually updated in case of a patch release for an older version.

Manually update `datadog_checks_base` changelog for `23.7.7`

---

datadog_checks_dev/datadog_checks/dev/tooling/trello.py

Agent-Metrics-Logs and Agent-Shared-Components teams were added to the QA board for agent release testing - proper fields and IDs were added to the trello class. This is related to the Agent Core team split. We want to keep the Agent-Core related entries for some time.
Motivation
Update to the changes in the agent release process.

Add new agent core teams to the QA board

---

datadog_checks_dev/datadog_checks/dev/tooling/trello.py

https://github.com/DataDog/integrations-core/pull/11924 broke ddev release trello status command - new 'Triage' label was added with the same id as 'Platform' - this made dictionaries built on top of those maps to overwrite key 'Platform' with 'Triage' and break QA cards count. I just swapped the position of the entries, so when the dict is built it ends up with 'Platform' being used.
Right now ddev release trello status command does now work. This PR fixes it.

QA status ddev fix

---

postgres/datadog_checks/postgres/statements.py
postgres/tests/test_statements.py

This marks `blk_read_time` and `blk_write_time` as metrics columns so they are computed as derivative values.

Fix Postgres calculation of blk_read_time and blk_write_time metrics

---

mysql/datadog_checks/mysql/activity.py

Updates MySQL's query activity query.
Query author and expert: @kyle-hailey 
The previous iteration of this query included rows without SQL text due to an incorrect outer `JOIN` statement in conjunction with the inner `SELECT` statement.
Behavior from the previous iteration of the query:
- Notice we receive many rows without SQL text
New query:

Fix rows with empty SQL text in DBM Activity Query

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/agent/changelog.py

Fixes ddev agent changelog command for manifest V2
Creating changelogs for 7.37.0
The old implementation returned a display name of "None" for teamcity since the logic did not handle manifest V2s

Fix agent changelog command for manifest v2

---

datadog_checks_dev/datadog_checks/dev/tooling/trello.py

Fix team assignment for `agent-metrics-logs` and `agent-shared-component`

Use the correct team when using `ddev -a release trello testable`

---

.azure-pipelines/scripts/marklogic/linux/55_docker_login.sh
marklogic/tests/compose/cluster/docker-compose.yml
marklogic/tests/compose/standalone/docker-compose.yml

Seems the log in on the private registry was not working anymore but these images are now available on the public dockerhub anyway so let's use those which makes it easier to run locally too.
```
E   datadog_checks.dev.errors.SubprocessError: Command: ['docker', 'compose', '--compatibility', '-f', '/home/vsts/work/1/s/marklogic/tests/compose/standalone/docker-compose.yml', 'up', '-d']
E   Exit code: 18
E   Captured Output:
---------------------------- Captured stderr setup -----------------------------
bootstrap Pulling 
bootstrap Error 
Error response from daemon: pull access denied for store/marklogicdb/marklogic-server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
standalone  Warning: No resource found to remove
```

Use dockerhub instead of private registry

---

vsphere/assets/dashboards/vsphere_overview.json

Had to change the group by portion of the widget "check_status" as it was grouping by the template variable and not vcenter_server. Noticed this was an issue with a particular customer (https://datadog.zendesk.com/agent/tickets/836725)
This properly displays the amount of vcenters by changing the group by option in the "check_status" widget. 
This ticket (https://datadog.zendesk.com/agent/tickets/834591) in which the customer reached out saying that they are being shown the incorrect amount of vcenters. They've isolated the issue to be the above fix.

Updated vsphere_overview.json

---

datadog_checks_dev/datadog_checks/dev/docker.py
redisdb/metadata.csv
redisdb/tests/test_e2e.py
redisdb/tox.ini

Ensure that the integration works well with 7.0. Ensure version comments on metadata.csv are right.
Refactor e2e test to have a single test instead of per-redis-version tests
Remove old versions from testing, since they are not supported anymore by redis.
> The latest stable release is always fully supported and maintained.
>
> Two additional versions receive maintenance only, meaning that only fixes for critical bugs and major security issues are committed and released as patches:
> 
> * The previous minor version of the latest stable release.
> * The previous stable major release.
Source: https://redis.io/docs/about/releases/#support

Update tested versions

---

datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/v2/validator.py

This error message was displaying the wrong char limit and also we were initialising validators with the parameters in the wrong order so the limit was incorrectly set

Fix validation error message and wrong parameters

---

tcp_check/tests/common.py
tcp_check/tests/test_tcp_check.py

Change the DNS hostname used to test IPv6 support of the `tcp_check` test to use a more stable one.
The number of IPs behind the `app.datad0g.com` hostname changed.

Fix the `tcp_check` IPv6 tests by using a more stable DNS hostname

---

vertica/datadog_checks/vertica/utils.py
vertica/datadog_checks/vertica/vertica.py
vertica/tests/README.md
vertica/tests/common.py
vertica/tests/conftest.py
vertica/tests/docker/Dockerfile_custom
vertica/tests/docker/custom-entrypoint.sh
vertica/tests/docker/docker-compose-9.yaml
vertica/tests/docker/docker-compose.yaml
vertica/tests/test_unit.py
vertica/tests/test_vertica.py
vertica/tox.ini

- It adds Vertica versions 10 and 11 to the testing environments.
- For Vertica 11, it skips the portion of the check that is currently incompatible with it to avoid having the check crash resulting in no metrics at all.
[AI-2467](https://datadoghq.atlassian.net/browse/AI-2467) (and [original GitHub issue](https://github.com/DataDog/integrations-core/issues/11565))
Vertica 11 dropped some columns that the integration relies on for some metrics, involving the distinction between WOS and ROS, see https://www.vertica.com/docs/ReleaseNotes/11.0.x/Vertica_11.0.x_Release_Notes.htm#Removed11.0.2.
- I plan to implement the support for the _incompatible_ metrics for v11 in a follow-up PR to keep this focused. I tried to get the minimum here so that we have something that's an improvement over the …

Make integration compatible with Vertica 11

---

kafka_consumer/metadata.csv

Change integration name to `kafka_consumer` in the metadata.csv file.
It came to our attention that the kafka_consumer tile didn't show any metrics, which led us to find that the integration name was incorrect in the metadata.csv for `kafka_consumer`.

Fix integration name in metadata.csv

---

boundary/README.md
boundary/tests/test_unit.py

QA for https://github.com/DataDog/integrations-core/pull/12410

Assert more in boundary tests

---

disk/metadata.csv

Updates metadata.csv to change the disk metric 'system.disk.in_use' to a percent instead of a fraction.
[Disk Documentation](https://docs.datadoghq.com/integrations/disk/#pagetitle)
I noticed that the metric 'system.disk.in_use'  is displayed as a percent in the DD UI instead of a fraction.  See UI screenshot below.
[UI Screenshot](https://a.cl.ly/5zuLr7YB)

[doc]jonathan.mcintyre-update-metadata.csv

---

snowflake/tests/snowflake_connector_patch/pyproject.toml

fixes snowflake e2e tests by using only-include: https://github.com/pypa/hatch/pull/299 
the tests were not using the mock properly due to https://github.com/pypa/hatch/releases/tag/hatchling-v1.4.1

Update mock targets

---

sqlserver/datadog_checks/sqlserver/connection.py

Fixes error we are seeing on SQL Server integration startup
```
Invalid database connector adodbapi, defaulting to adodbapi
```
this error doesn't make sense as we are incorrectly not adding `adodbapi` to the `valid_connectors` array. This list can just be hardcoded instead.

Remove confusing error message on sqlserver integration start up

---

proxysql/tests/conftest.py

ProxySQL is failing to start up on master, changing the log line to check fixes the issue
* https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=103983&view=logs&j=56a8e754-1e17-5104-e044-29b3f48df9b2&t=7c40731b-9272-5842-3e5b-5abe040374e8
* https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=103980&view=logs&j=56a8e754-1e17-5104-e044-29b3f48df9b2&t=7c40731b-9272-5842-3e5b-5abe040374e8
* https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=103974&view=logs&j=56a8e754-1e17-5104-e044-29b3f48df9b2&t=7c40731b-9272-5842-3e5b-5abe040374e8&l=1852

Change proxysql env log to check

---

elastic/assets/configuration/spec.yaml
elastic/datadog_checks/elastic/data/conf.yaml.example

The datadog agent shouldn't need `manage_slm` to emit SLM metrics for elasticsearch clusters since the [`read_slm` privilege](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-privileges.html#:~:text=pipline%20(get%2C%20simulate).-,read_slm,-All%20read%2Donly) exists. This PR updates the docs for `slm_stats` to reflect this.

elastic docs: change slm_stats privilege to read_slm

---

docs/dev/check_references.md

We can update the wording of the curated metrics description under the [Metrics metadata file](https://docs.datadoghq.com/developers/integrations/check_references/?tab=manifestversion2#metrics-metadata-file) section to be more descriptive.

Update the wording for the curated_metrics metadata.csv column

---

mysql/datadog_checks/mysql/config.py
mysql/datadog_checks/mysql/mysql.py
mysql/datadog_checks/mysql/queries.py
mysql/metadata.csv

Follow up to this PR https://github.com/DataDog/integrations-core/pull/11043
Updates metadata.csv to reflect correct metric name, `mysql.info.table.rows.changed` and fixes the `table_rows_stats_metrics` config option look up, so metrics are properly reported

Fix bug where mysql table row stats were not being collected

---

datadog_checks_base/datadog_checks/base/utils/http.py
datadog_checks_base/tests/base/utils/test_http.py

Allows configuring the username and the password to be empty strings for basic auth.
The user still has to explicitly add the empty string as a config value so that the original intent of checking for presence of the config values is maintained.
[AI-2469](https://datadoghq.atlassian.net/browse/AI-2469)
A user reported in #12390 that they have a valid use case for having an empty password when using basic auth.
We disable auth if either `username` or `password` are not set in the config, but we check for truthy value, which means that an empty string is interpreted as the value not being set, too. This disallowed the aforementioned use case.
`requests` seems to allow empty username and password for basic auth too, so I think it's safe to allow the same in our wrapper too.

Allow empty username and password for basic auth

---

datadog_checks_base/datadog_checks/base/checks/windows/perf_counters/base.py
datadog_checks_base/datadog_checks/base/checks/windows/perf_counters/refresh.py
datadog_checks_base/tests/base/checks/windows/perf_counters/test_health.py

With many check instances configured, on certain versions of Windows, the internal lock contention of Windows APIs significantly increases execution times

[PerfCountersBaseCheck] Refresh performance objects in a separate thread

---

openmetrics/assets/configuration/spec.yaml
openmetrics/datadog_checks/openmetrics/data/conf.yaml.example

Hides `extra_metrics` configuration option in example config for the generic openmetrics check
Users will only ever need to use the `metrics` option in the  openmetrics check, `extra_metrics` is the option for the integrations based off of it.

Hide `extra_metrics` in example config

---

airflow/README.md

Separates metric names into separate backticked words.
Question raised by translators

properly apply monospace tagging to metric names

---

mysql/tests/conftest.py
mysql/tests/test_mysql.py
mysql/tests/variables.py

These metrics had no test coverage before this. This asserts that the metrics are properly emitted. Based on this https://github.com/DataDog/integrations-core/pull/11043

Add tests for table_row_stats_metrics collection

---

ibm_db2/tests/conftest.py

Docker compose command failed on CI
```
Network docker_default  Creating
Network docker_default  Created
Container ibm_db2  Creating
Container ibm_db2  Created
Container ibm_db2  Starting
Error response from daemon: driver failed programming external connectivity on endpoint ibm_db2 (22646172ce50b087ad4b0a782e72c45101e60b723ef4f17e97f66054c73f1c4b): Error starting userland proxy: listen tcp4 0.0.0.0:50000: bind: address already in use
Container ibm_db2  Stopping
Container ibm_db2  Stopping
Container ibm_db2  Stopped
Container ibm_db2  Removing
Container ibm_db2  Removed
Network docker_default  Removing
Network docker_default  Removed
```
So let's add a second attempt to retry in this case

Add attempts to IBM DB2 environment

---

datadog_checks_base/datadog_checks/base/checks/base.py
datadog_checks_base/tests/base/checks/test_agent_check.py

- Take the aliases when looking for typos in the config options
- Update the test case to check the return value
- Update the test case to also verify aliases are taken into account
https://datadoghq.atlassian.net/browse/AI-2362

Fix typo detection for config field aliases

---

sqlserver/datadog_checks/sqlserver/queries.py
sqlserver/datadog_checks/sqlserver/sqlserver.py

Adds support for handling older versions of SQL Server which may lack columns used for AlwaysOn metrics.
Issue was surfaced via logs
```
Error querying sys.availability_groups: ('42S22', "[42S22] [FreeTDS][SQL Server]Invalid column name 'secondary_lag_seconds'. (207) (SQLExecDirectW)")
```

Support version specific AlwaysOn metrics

---

snmp/tests/test_e2e_core.py

Fix test_e2e_core_discovery test by adding some pause to let enough time to SNMP check discovery devices.
The test_e2e_core_discovery is testing SNMP corecheck autodiscovery.
SNMP corecheck autodiscovery goal is to discovery SNMP devices, it is started directly from SNMP corecheck integration and is run in background.
The the test broke after this change https://github.com/DataDog/datadog-agent/pull/12408 that possibly made the autodiscovery slower to discover devices. Hence adding some `pause` is mitigating the issue.
Fix e2e test failure for `test_e2e_core_discovery`. Example:
https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=104462&view=logs&j=475ea3e3-a9fc-55a6-2e22-b5a67273560a&t=1a1f47dd-bcf6-5ffb-3d85-8c5dbec3db65&l=106
```
___________________________ …
```

Fix test_e2e_core_discovery test

---

docs/developer/tutorials/snmp/profile-format.md

Expands on our current documentation surrounding applying the index of an OID as a metric tag.  Adds additional detail regarding the syntax of metric collection from a table.
conversation with customer on [this ticket](https://datadog.zendesk.com/agent/tickets/843365) and ENG on [this thread](https://dd.slack.com/archives/C0245LJKD5F/p1656361398792919)

expand upon example of using an index as a metric_tag

---

kong/datadog_checks/kong/metrics.py

It updates the metrics URL for reference purposes.
Ofek and I were reviewing the kong integration and he noticed that the URL was pointing to an archived repository.

update the metrics url

---

win32_event_log/README.md

this change adds an example containing a regex pattern that many customers have found useful in filtering their win32 logs
this doc update was requested by the customer in this ticket: https://datadog.zendesk.com/agent/tickets/787828
related internal wiki: https://datadoghq.atlassian.net/wiki/spaces/TS/pages/328631826/Send+Windows+Event+Logs+to+DD+Logs

add log filtering by eventID example

---

ecs_fargate/README.md

Several changes are being made here for general cleanup purposes of the ECS Fargate docs.
- Moved the 3 deployment methods (Web UI, AWS CLI, CloudFormation) into selectable tabs to cleanup the instructions
- Added indented bullets to web ui for easier reading
- Bringing more consistency between the examples. Such as: same image repo/name (`public.ecr.aws/datadog/agent:latest`) for each, same CPU/Memory for the Task, `datadog-agent` container now doesn't have container specific CPU/Memory listed
- Cleaned up CloudFormation examples to properly list env vars and use nicer resource names (`ECSTDNJH3` -> `ECSTaskDefinition`)
- Added generic CloudFormation examples for Replica Service
- Changed the log collection from tabs of "Fluent Bit & Firelens" vs "logDriver" to not use tabs, as to not …

ECS Fargate cleanup for deployment tabs, instructions, and samples

---

postgres/datadog_checks/postgres/statement_samples.py

Fixes a bug in log message formatting.
If the postgres user the agent is connecting with isn't allowed to read
all queries in pg_stat_activity, a warning is logged. But the log
message can't be formatted due to missing arguments, resulting in:
```
pkg/collector/python/datadog_agent.go:122 in LogMessage) [...] Job loop crash
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/utils/db/utils.py", line 289, in _job_loop
self._run_job_rate_limited()
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/utils/db/utils.py", line 328, in _run_job_rate_limited
self._run_job_traced()
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/utils/db/utils.py", line 333, in …
```

add missing arguments to log statement

---

datadog_checks_dev/tests/tooling/commands/validate/test_models.py

Updates a ddev test to not directly modify a user's `repo` settings
We recently added a test that modifies a user's ddev configuration, and we don't want to have to always update our ddev config after running tests.

Don't modify a user's config on ddev tests

---

redisdb/datadog_checks/redisdb/redisdb.py

Measure real latency in redisdb.
The method used by the Redis integration to calculate latency can be influenced by the load of the agent since it counts the time it takes from the agent not only from the result of redis info command side.
https://datadoghq.atlassian.net/browse/AI-2489

[redisdb] Latency measurement not impacted by agent load

---

sqlserver/tox.ini

SQL Server version 2016 and 2017 are failing in CI resulting in blocked PRs. Temporarily disable these envs until a fix for these versions is found.

Disable SQL Server 2016 and 2017 test envs

---

datadog_checks_dev/datadog_checks/dev/plugin/hatch/environment_collector.py
datadog_checks_dev/hatch.toml
datadog_checks_dev/pyproject.toml

1. Bump version
2. Properly require check dependencies
3. Tie verbosity of pip commands to invoked verbosity
4. Don't show availability of internal scripts by default
5. Support upcoming `ddev` CLI directory

Update Hatch plugin

---

ibm_db2/requirements-dev.txt
ibm_db2/tests/docker/requirements.txt

In https://github.com/DataDog/integrations-core/pull/12449 we set up an env var to download the clidriver from azure instead of IBM site, but it turns out this variable was not used in the version of the library we are using so the tests for this integration are still being hit by rate limiting and this flaking.
This PR bumps the dependency to the version that introduced the env var.

Bump IBM DB dependency

---

mysql/datadog_checks/mysql/statement_samples.py
mysql/datadog_checks/mysql/util.py

Logs a check warning if DBM's statement samples job detects a missing `event_statements_*` consumer.
Surface database configuration errors in the UI
Database configuration errors we're checking for:
https://github.com/DataDog/integrations-core/blob/9f758cd9615d5d05ec069caaee3b0a9d1f9a554c/mysql/datadog_checks/mysql/util.py#L11-L15

Log check warning for missing event statements consumer

---

elastic/README.md

Complete documentation about the permissions in Elasticsearch that the DataDog Agent needs.
Missing documentation about required permissions and/or roles for the Elasticsearch user that is configured for use by the DataDog Agent elastic integration.
https://github.com/DataDog/integrations-core/issues/12466

[elastic] Added documentation missing description of required user roles permissions

---

postgres/README.md

Fixes a minor typo in the documentation for Postgres.
Text in "Overview" section mentioned "Received notifications about PostgreSQL failovers and events." "Received" should be "Receive".

Fix simple typo

---

datadog_checks_dev/datadog_checks/dev/docker.py
datadog_checks_dev/datadog_checks/dev/env.py
datadog_checks_dev/tests/test__env.py
datadog_checks_dev/tests/test_docker.py

The `docker_run` helper has a `attempts` option to retry in case of failure. The retry does include the conditions. This PR include the conditions in the retries.
AI-2550
At first I wanted to add the `retry` decorator to the `environment_run` or directly the `docker_run` functions, but it's not working with generators, so I decided to include the conditions in the retry using the set up function.

Include the conditions in the retry for the `docker_run` function

---

mongo/assets/configuration/spec.yaml
mongo/datadog_checks/mongo/config.py
mongo/datadog_checks/mongo/config_models/defaults.py
mongo/datadog_checks/mongo/config_models/instance.py
mongo/datadog_checks/mongo/data/conf.yaml.example

Restore connection_scheme to config: spec.yaml, etc...

[mongo] Restore connection_scheme to config

---

confluent_platform/tests/conftest.py
confluent_platform/tests/metrics.py

This metric was missing on this build https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=105167&view=logs&j=83bb99ea-9ab1-5c8c-b843-8f48234d7592&t=41342080-6d4d-5b33-e141-ae960dd7d738&l=84 so I'm moving it to optional
On this build the environment failed two start even with a second attempt so adding another one https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=105159&view=logs&j=83bb99ea-9ab1-5c8c-b843-8f48234d7592&t=41342080-6d4d-5b33-e141-ae960dd7d738&l=76
```
self = <Retrying object at 0x7feb36e6f940 (stop=<tenacity.stop.stop_after_attempt object at 0x7feb36e6f880>, wait=<tenacity.w...0x7feb39e25190>, before=<function before_nothing at 0x7feb39e20310>, after=<function after_nothing at 0x7feb39e20550>)>
fn = <function …
```

Move metric from always present to optional, increase attempts

---

pgbouncer/assets/configuration/spec.yaml
pgbouncer/datadog_checks/pgbouncer/config_models/defaults.py
pgbouncer/datadog_checks/pgbouncer/config_models/instance.py
pgbouncer/datadog_checks/pgbouncer/data/conf.yaml.example
pgbouncer/datadog_checks/pgbouncer/metrics.py
pgbouncer/datadog_checks/pgbouncer/pgbouncer.py
pgbouncer/metadata.csv
pgbouncer/tests/test_pgbouncer_integration_e2e.py

Because this could potentially bump up the level of data collected a
good bit, we've made these new metrics optionally collected.
Co-authored-by: Lisa Cicatello <cicatello.lisa@gmail.com>
Add optional per-client and per-server connection metrics to the pgbouncer integration.
The pre-summarized metrics provided by pgbouncer are missing critical
information. For example, the `pgbouncer.stats.total_wait_time` metric
only increases when a backend connection is assigned to a client
connection. But that means that currently waiting client connections
aren't included in this metric. There is `pgbouncer.pools.maxwait`, but
there's no way to get more granular information (e.g., average or P95)
or even total currently accumulated wait time.
N/A

Add per-client/server metrics

---

envoy/tests/common.py
envoy/tests/conftest.py
envoy/tests/legacy/common.py
envoy/tests/legacy/test_bench.py
envoy/tests/legacy/test_e2e.py
envoy/tests/legacy/test_envoy.py
envoy/tests/legacy/test_metrics.py
envoy/tests/legacy/test_parser.py
envoy/tests/legacy/test_utils.py
envoy/tests/test_check.py
envoy/tox.ini

It removes legacy variants from test (tox) environments with the necessary adjustments.
I didn't see a good reason to have `legacy` as a variant, since the envoy environment remains the same regardless of that. This was prompted by realizing a test I added recently looked out of place (was testing legacy only in a supposedly non-legacy env).
My assumption here is that api_v2 doesn't support Prometheus, though I haven't checked yet whether that's the case. This assumption is supported by the fact that in our tox envs, api_v2 was only combined with the legacy variant.

Remove legacy variants from tests environments

---

proxysql/tests/conftest.py

Environment failed to start on https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=105159&view=logs&j=56a8e754-1e17-5104-e044-29b3f48df9b2&t=e53b82b6-1546-51f5-6ef5-3e8d1c16a61b&l=301

Add attempts to proxysql

---

ceph/tests/conftest.py

On https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=105245&view=logs&j=155efd4a-3db6-57a2-0ce3-7e8c157a4e0a&t=4ad84dea-efb9-5139-10ad-4c7a65d30c32&l=4112
Environment failed after two attempts with
```
E           dd-test-ceph  |     An unexpected error has occurred.
E           dd-test-ceph  |   Please try reproducing the error using
E           dd-test-ceph  |   the latest s3cmd code from the git master
E           dd-test-ceph  |   branch found at:
E           dd-test-ceph  |     https://github.com/s3tools/s3cmd
E           dd-test-ceph  |   and have a look at the known issues list:
E           dd-test-ceph  |     https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
E           dd-test-ceph  |   If the error persists, please report the
E …
```

Increase attempts

---

datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py
datadog_checks_dev/datadog_checks/dev/utils.py

* Add `DD_HOSTNAME` environment variable to the docker E2E `start_agent` command. 
* Add `get_hostname` util to return the host's socket hostname. 
Fix CI: Latest windows agent container dev builds are unable to determine the Windows VM hostname automatically. 
I initially tried using the `self.container_name` as the hostname, but the name's underscores make it non-compliant with RFC 1123 as a hostname.

Add hostname to docker agent start command for windows

---

openmetrics/tests/test_openmetrics.py
openmetrics/tests/test_openmetrics_strict.py

Add additional header assertions to openmetrics v2 tests to validate that the scraper http header is properly getting updated when `use_latest_spec: True`.
QA https://github.com/DataDog/integrations-core/pull/11899

Add additional header assertions 

---

datadog_checks_downloader/datadog_checks/downloader/download.py

Verbose mode is confusing when multiple -v flags are supplied. -vvvvv means debug mode, but -vvvvvv means no verbosity at all (and cycles to higher log levels when additional -v flags are added). This change makes sure only debug mode is set if 5 or more -v flags are supplied.

Adjust logging setup when multiple -v flags are supplied

---

datadog_checks_downloader/datadog_checks/downloader/download.py
datadog_checks_downloader/datadog_checks/downloader/exceptions.py

Do not use assert statements in the code. Instead, create UpdatedTargetsError
exception to report any issues.
Related: #12557

Avoid using assert statement by creating UpdatedTargetsError exception

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/pyproject.toml

https://github.com/psf/requests/pull/6057 to fix https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=105561&view=logs&j=918144f8-7a9b-57ab-9d4d-7700df3d4745&t=a59da3b3-a5df-5321-8288-a128b4ac33fd&l=310

Upgrade `requests` dependency to 2.28.1

---

oracle/tests/scripts/install_instant_client.sh

Related to https://github.com/DataDog/integrations-core/pull/12578
Set -x prints the commands and its arguments as they're executed.
The goal is to have more visibility of what fails when something fails.

[Oracle] Print commands of install script

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py

Print which command failed also indent the output of that command

Better print the error on extra startup commands for e2e tests on agent image set up

---

tcp_check/datadog_checks/tcp_check/tcp_check.py
tcp_check/tests/common.py
tcp_check/tests/test_tcp_check.py

* Refactors and fixes the logic for determining the socket address family (IPv4 vs IPv6) for an instance host's corresponding IP address(es). 
* Fixes IP resolution for hostnames that resolve to both IPv4 and IPv6 addresses
Support case.
This [PR](https://github.com/DataDog/integrations-core/pull/11740) added IPv6 support, however it did not consistently [resolve hostnames to the correct IP address format](https://github.com/DataDog/integrations-core/pull/11740/files#diff-e1afdae3cf81bdf12d2888a230f697bfd8eda2d5ab2e8d7267e30183986a636bR108) with respect to `self.socket_type`. In one reported case, `localhost` sometimes resolved to the IPv4 format `127.0.0.1` and other times to the IPv6 format `::1`, while `self.socket_type` was always `socket.AF_INET` (IPv4). 
In addition, …

Fix IPv4/IPv6 address resolution

---

pgbouncer/tests/test_pgbouncer_integration_e2e.py

On https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=105651&view=logs&j=4fa091e2-3df8-50fa-51e5-b414abd4c247&t=533523c5-01ca-59b0-b401-3818cb8b6f7d&l=207
No database metrics were emitted:
```
E   AssertionError: Needed at least 1 candidates for 'pgbouncer.databases.pool_size', got 0
E     Expected:
E             MetricStub(name='pgbouncer.databases.pool_size', type=None, value=None, tags=None, hostname=None, device=None, flush_first_value=None)
E     Similar submitted:
E     Score   Most similar
E     0.65    MetricStub(name='pgbouncer.pools.sv_used', type=0, value=1, tags=['db:datadog_test', 'optional:tag1', 'user:postgres'], hostname='fv-az101-223', device=None, flush_first_value=False)
E     0.65    MetricStub(name='pgbouncer.pools.sv_used', type=0, value=1, …
```

Mark database metrics as optional

---

datadog_checks_base/datadog_checks/base/stubs/aggregator.py

When `assert_metric_has_tag` fails because the metric has not been submitted at all we do not print other similar metrics that have been submitted

Print similar metrics when asserting metric has tag

---

wmi_check/README.md

Fixes the broken `WMI Explorer` link in the `wmi_check` `README.md`
Have a working link again.

Fix WMI Explorer link in the wmi_check README.md

---

docker_daemon/manifest.json
kong/manifest.json
teamcity/manifest.json
varnish/manifest.json

Adds back `process_signatures` that were lost when we began migrations to manifest V2
The original specification of manifest V2 did not account for `process_signatures`. The V2 manifest now supports this under the `assets->integration` key. We've merged 4 migration PRs that unfortunately lost process_signatures during this time, `kong`, `docker_daemon`, `teamcity`, `varnish`. 
This PR re-introduces them. While this never impacted customers (the backend kept its own version of these), we want to re-introduce them before any issues were to arise.

Add back process signatures lost during the V2 migration

---

oracle/tests/scripts/install_instant_client.sh

After printing more information on https://github.com/DataDog/integrations-core/pull/12577 and https://github.com/DataDog/integrations-core/pull/12578
On https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=105743&view=logs&j=c3a06451-088b-587c-b2b9-012b146267bb&t=8b8da6bd-8c7d-5c16-284a-eb82cfe91ae0&l=155
we see:
```
+ apt-get install unzip
debconf: delaying package configuration, since apt-utils is not installed
```
Listing the contents of the unzipped directory for debugging purposes
Adding explicit `exit 0` since I don't see any actual errors on the script that could have made it fail.
EDIT: It seems unzip can return non 0 exit code even if extraction is "ok" https://linux.die.net/man/1/unzip

Avoid warnings on apt-get install, exit 0

---

sidekiq/README.md

This PR adds info about an alternative option to configure dogstatsd mapper profiles by mentioning the `DD_DOGSTATSD_MAPPER_PROFILES` environment variable.  This should hopefully cut down on confusion in setting these parameters without directly editing the `datadog.yaml` file.
A few customers have reached out about not understanding how to add these configs to containerized environments (https://datadog.zendesk.com/agent/tickets/801720).
"I didn’t know that the `DD_DOGSTATSD_MAPPER_PROFILES` env var existed. That will totally solve my problem!"

Update Sidekiq integration docs

---

postgres/datadog_checks/postgres/postgres.py

We don't need the agent to perform writes, so we should connect to postgres via read-only connections.

postgres: use readonly connections

---

ibm_db2/README.md
sap_hana/README.md

Prevent user installation when `/opt/datadog-agent/embedded/lib/python3.8/site-packages` is not writable by current user.
```
vagrant@ubuntu:~$ /opt/datadog-agent/embedded/bin/pip install hdbcli==2.10.15
Defaulting to user installation because normal site-packages is not writeable
Collecting hdbcli==2.10.15
Downloading hdbcli-2.10.15-cp34-abi3-manylinux1_x86_64.whl (11.7 MB)
|████████████████████████████████| 11.7 MB 7.8 MB/s            
Installing collected packages: hdbcli
Successfully installed hdbcli-2.10.15
vagrant@ubuntu:~$ /opt/datadog-agent/embedded/bin/pip show hdbcli
Name: hdbcli
Version: 2.10.15
Summary: SAP HANA Python Client
Home-page: https://www.sap.com/
Author: SAP SE
Author-email: 
License: SAP DEVELOPER LICENSE AGREEMENT
Location: …
```

Nathan.pezzotti/change install user

---

datadog_checks_base/datadog_checks/base/stubs/datadog_agent.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py

Print a more comprehensive assertion message on metadata count failure.
Print return code when running additional startup commands on agent image fails

Better failed assertion message, print return code

---

voltdb/tests/conftest.py

On https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=105973&view=logs&j=b3462493-d129-5a01-f515-8697d319257d&t=5a721fe0-efeb-5b46-79a9-8f4941179cfe the environment failed to start

Add attempts to voltdb environment

---

avi_vantage/tests/test_avi_vantage.py

[This agent PR](https://github.com/DataDog/datadog-agent/pull/12732) includes instance_config and init_config in the metadata (inventories) submission, so we need to account for it.

Increase expected metadata count

---

oracle/tests/conftest.py
oracle/tests/scripts/install_instant_client.sh

Datadog agent set up on oracle e2e test is often failing with error code 129, 129 is the typical exit code of a process being killed with SIGHUP. SIGHUP is sent when the tty a process is connected to is closing.
This PR moves all `apt-get install` commands for the CLI environment inside the shell script and makes them non interactive.

Run apt commands in non interactive mode

---

vault/tests/metrics.py

Metric was missing on https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=106024&view=logs&j=70a237a0-2c52-52f8-23f1-657d682c7ecf&t=d85edea3-9fa0-5bee-ebb0-f3a77200749a&l=543 and https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=106049&view=logs&j=70a237a0-2c52-52f8-23f1-657d682c7ecf&t=d85edea3-9fa0-5bee-ebb0-f3a77200749a&l=543

[Vault] Mark metric as optional

---

cacti/pyproject.toml
datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/pyproject.toml
mysql/pyproject.toml
proxysql/pyproject.toml
singlestore/pyproject.toml

We are currently shipping pymysql version `1.0.2`, but there is a [bug](https://github.com/PyMySQL/PyMySQL/issues/981) in this version, and there is no release with the fix yet. We have to revert this update until there is a new release of the library.

Pin `pymysql` to `0.10.1`

---

couchbase/tox.ini

Remove legacy compose from E2E

Remove legacy compose from E2E

---

glusterfs/tests/docker/docker-compose.yaml

The environment is failing to start in the last 8 master builds and seems updating the compose version fixes it
- https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=106095&view=results
- https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=106094&view=results
- https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=106093&view=results
- https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=106092&view=results
- https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=106091&view=results
- https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=106090&view=results
- https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=106089&view=results
- …

[gluster] Update compose version

---

cassandra_nodetool/tests/conftest.py

log_patterns only requires to match 1 of the provided patterns (changing on https://github.com/DataDog/integrations-core/pull/12623).
This PR makes it so all patterns are required and adapts which ones to the cassandra version

Match all log patterns

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/dep.py

Adds `pymysql` to the exclude list when updating dependencies 
There is an unfixed bug in pymysql and we do not want to accidentally update it in the future.
https://github.com/DataDog/integrations-core/pull/12612/s

Add pymysql to dependency update exclude list

---

proxysql/datadog_checks/proxysql/queries.py
proxysql/tests/test_integration.py

This PR will change the query for the `proxysql.backends.count` metric from a query in a [runtime table](https://proxysql.com/documentation/main-runtime/) (`admin-admin_credentials` required) to a query in a [stats table](https://proxysql.com/documentation/stats-statistics/) (allowing `admin-stats_credentials` only)
Query in the `runtime_mysql_servers` table require admin credential by default. Runtime tables such as `runtime_mysql_users` contains sensitive data so it is not recommended to use `admin-admin_credentials` nor grant permissions.
While we can get the relevant data about backends count from the stats table `stats_mysql_connection_pool` we can update the query to this table instead.

Use stats database for proxysql backends count

---

kubelet/datadog_checks/kubelet/kubelet.py
kubelet/datadog_checks/kubelet/probes.py
kubelet/tests/test_kubelet.py

Propagate kubelet creds parameters when making the discovery call for `/metrics/probes`
Fix `2022-07-29 10:04:48 UTC | CORE | DEBUG | (pkg/collector/python/datadog_agent.go:128 in LogMessage) | - | (probes.py:57) | Unable to collect query probes endpoint: HTTPSConnectionPool(host='10.50.189.37', port=10250): Max retries exceeded with url: /metrics/probes (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))`

Fix probe metrics not reported when creds required

---

datadog_checks_downloader/datadog_checks/downloader/download.py

With this change, the temporary directory will be removed if there would be any
exception within the with block. The temporary directory would be
properly removed on any error raised.

Use context manager when creating temporary directory

---

tls/assets/configuration/spec.yaml
tls/datadog_checks/tls/config_models/defaults.py
tls/datadog_checks/tls/config_models/instance.py
tls/datadog_checks/tls/data/conf.yaml.example
tls/datadog_checks/tls/tls.py
tls/datadog_checks/tls/tls_remote.py
tls/tests/compose/Dockerfile
tls/tests/compose/docker-compose.yml
tls/tests/conftest.py
tls/tests/test_remote.py

This PR adds support for StartTLS implementation of postgresql protocol within `TLS` check.
There are few protocols that works with StartTLS protocol. This is a way to handle both encrypted and unencrypted traffic on the same port. The client needs to send some protocol specific packets to switch the connection to encrypted format. Before that TLS handshake is not possible. Due to that `TLS` check is currently not able to detect certs on these protocols.
Protocols implementing StartTLS: smtp, pop3, imap, ftp, xmpp, xmpp-server, irc, postgres, mysql, lmtp, nntp. sieve and ldap.
This PR adds support only for `postgresql` however with the general idea of extension.

TLS check: implement StartTLS protocol for postgres

---

avi_vantage/tests/test_avi_vantage.py

Now these metadata are not enabled by default https://github.com/DataDog/datadog-agent/pull/12912
Reverts DataDog/integrations-core#12618

Revert "Increase expected metadata count"

---

clickhouse/tests/test_clickhouse.py

On https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=106296&view=logs&j=8e96ab15-72b0-549c-5ab8-f9fece94b017&t=ec9b40f1-a5eb-523c-a2d7-f48a83ba2f0c&l=893
The value of the metric was 1 and not 2. Since we cannot enforce the value from the test set up and otherwise the environment seems healthy it's better not to assert it. The metric is already checkd for with the right tags in the loop of the test.
```
__________________________________ test_check __________________________________
tests/test_clickhouse.py:36: in test_check
aggregator.assert_metric('clickhouse.table.replicated.total', 2)
../datadog_checks_base/datadog_checks/base/stubs/aggregator.py:368: in assert_metric …
```

Do not assert metric value

---

postgres/datadog_checks/postgres/relationsmanager.py
postgres/tests/test_relationsmanager.py

In the `postgres` integration, add parentheses around the "relations filter" SQL clause to ensure proper operator precedence.
When multiple entries are added in the `relations` config, the precedence of `AND`/`OR`  conditions may give unexpected results, because [AND takes precedence over OR](https://www.postgresql.org/docs/14/sql-syntax-lexical.html#SQL-PRECEDENCE-TABLE).
For instance with the `SIZE_METRICS` query of the form `SELECT [...] WHERE <cond1> AND {relations}`, with multiple relations it becomes:
* Currently: `SELECT [...] WHERE <cond1> AND <rel1> OR <rel2>`
* Expected: `SELECT [...] WHERE <cond1> AND (<rel1> OR <rel2>)`.

[postgres] Fix operator precedence in relation filter

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/generate_traps_db.py

This PR processes the `BITS` field in MIBs as enums and adds those mappings to the traps database.
The team wants to parse BITS enums so that customers are able to more easily understand the data being sent as part of traps directly in the Datadog UI.

[SNMP Traps] Include BITS enums in traps DB 

---

kafka_consumer/datadog_checks/kafka_consumer/new_kafka_consumer.py

if there is an error fetching broker offsets, like:
`NoLeaderForPartition` for eg, then, this line:
https://github.com/DataDog/integrations-core/blob/9455227913fd402a012396610d88647cb93ec445/kafka_consumer/datadog_checks/kafka_consumer/new_kafka_consumer.py#L199
is not called, and there is no producer offset, and it can cause: https://github.com/DataDog/integrations-core/issues/12587

[kafka check] Handle errors getting producer offset

---

datadog_checks_downloader/pyproject.toml

This PR adds a classifier that makes sure the download-checks-downloader is not published on PyPI.

Prevent from publishing datadog-checks-downloader to PyPI

---

datadog_checks_dev/datadog_checks/dev/tooling/trello.py

This PR adds Windows-Agent team to the trello scripts, so they can be included in the next Agent release QA automatically.
Motivation
Update to the changes in the agent release process.

Windows-agent team added to trello QA scripts

---

kubernetes/assets/dashboards/kubernetes_nodes.json

Fixes the query to get the "not ready" nodes in the Kubernetes nodes dashboard.
We were counting all the nodes with condition != ready. Checking that condition:ready is false seems more accurate.

Fix dashboard widget with "not ready" nodes

---

kubernetes/assets/dashboards/kubernetes_pods.json

Fixes a chart in the "Kubernetes Pods Overview" dashboard. The number of pods in bad state was incorrect because it was including pods in "succeeded" state too.

Fix dashboard widget with pods in bad state

---

postgres/datadog_checks/postgres/relationsmanager.py
postgres/tests/compose/resources/03_load_data.sh
postgres/tests/test_relations.py

We should escape the `_` character in our LOCK_METRICS query.

postgres...relationsmanager: escape underscore in LOCK_METRICS query

---

sqlserver/datadog_checks/sqlserver/connection.py
sqlserver/tests/test_connection.py

Currently, we read the port from the end of the `host` string for sqlserver connections. Let's allow users to pass an explicit `port` config for sqlserver connections, as we do with other databases.

sqlserver...connection: check for port provided in config

---

kube_scheduler/datadog_checks/kube_scheduler/kube_scheduler.py
kube_scheduler/tests/test_kube_scheduler_1_23.py

It changes the metric called `scheduler_total_preemption_attempts` to `scheduler_preemption_attempts_total`, from 1.19.
This metric changed its name in 1.19 and the integration was never changed, so the metric `pod_preemption.attempts` was missing in newer versions of Kubernetes
Details in the K8s changelog: https://www-1.muraena.okta-security-dev.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#other-cleanup-or-flake-7

Re-add missing metric: pod_preemption.attempts

---

cacti/tox.ini

The docker image we rely on has been removed. This PR disables the e2e tests while we create a new one.

Disable cacti e2e

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
ibm_was/pyproject.toml
sqlserver/pyproject.toml

Bump `lxml` version for [CVE-2022-2309](https://avd.aquasec.com/nvd/cve-2022-2309).
Fix DataDog/image-vuln-scans#502.

Bump `lxml` package

---

datadog_checks_downloader/README.md

No dev extras provided by the package. Only deps -- adjust README accordingly.

datadog-checks-downloader does not provide dev extras

---

snmp/datadog_checks/snmp/data/profiles/_fortinet-fortigate-vpn-tunnel.yaml
snmp/datadog_checks/snmp/data/profiles/fortinet-fortigate.yaml

This PR adds metrics for VPN Tunnels in the Fortinet Fortigate-integration.
We developed this feature as we needed to monitor the VPN Tunnel state.
n/a
- [] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [] PR title must be written as a CHANGELOG entry [(see why)](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title)
- [] Files changes must correspond to the primary purpose of the PR as described in the title (small unrelated changes should have their own PR)
- [] PR must have `changelog/` and `integration/` labels attached

Fortinet Fortigate: Add metrics for VPN Tunnels

---

couch/assets/dashboards/CouchDB-overview_dashboard.json
couch/assets/dashboards/CouchDBv1-overview_dashboard.json
couch/manifest.json

Adds a new CouchDB dashboard with updated CouchDB v3 metric names.
Renames the old dashboard to `CouchDB (v1) - Overview` to be kept for backwards compatibility
AGENT-7731
This is pretty much a copy of the old Dashboard but with corrected/updated metric names that no longer exists in CouchDB v2/v3

Update CouchDB dashboard

---

tcp_check/assets/configuration/spec.yaml
tcp_check/datadog_checks/tcp_check/config_models/defaults.py
tcp_check/datadog_checks/tcp_check/config_models/instance.py
tcp_check/datadog_checks/tcp_check/data/conf.yaml.example
tcp_check/datadog_checks/tcp_check/tcp_check.py
tcp_check/tests/common.py
tcp_check/tests/test_tcp_check.py

Adds option to only check IPv4 addresses. 
A hostname may resolve to both IPv4 and IPv6 addresses despite the host lacking IPv6 connectivity. Enabling this option will check only IPv4 addresses and prevent false alerts from IPv6 addresses returning CRITICAL status due to "Network is unreachable" error returned from the socket. 
Also fixes the `has_ipv6_connectivity()` helper function in the tests, which was silently failing in the CI due to an exception from `socket.gethostname()` not getting caught.

Add IPv4-only configuration option

---

aerospike/tests/conftest.py

Add attempts to the aerospike test environment.
The env failed to start here https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=106629&view=logs&j=e6fbf30e-778c-5f2e-ae39-62f4185f213c&t=2ad36f8a-d643-5acc-ca1e-41af5b904a40

Add attempts to aerospike environment

---

mapreduce/tests/conftest.py

Add attempts to the mapreduce test environment. It's not great but I don't have a better solution right now.
https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=106629&view=logs&jobId=44f80fa8-59b4-5eac-d564-3b72739a148c&j=44f80fa8-59b4-5eac-d564-3b72739a148c&t=b3f261fd-6b58-549b-d68a-62dbdf5aafc4

Add attempts to mapreduce environment

---

kube_scheduler/datadog_checks/kube_scheduler/kube_scheduler.py
kube_scheduler/metadata.csv
kube_scheduler/tests/test_kube_scheduler_1_23.py

This PR adds the `queue.incoming_pods` metric
The `scheduler_queue_incoming_pods` metric was added in Kubernetes 1.17, but was never added to the integration.
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#scheduling-1

Add queue.incoming_pods metric

---

mysql/datadog_checks/mysql/activity.py
mysql/datadog_checks/mysql/const.py
mysql/datadog_checks/mysql/mysql.py
mysql/datadog_checks/mysql/queries.py
mysql/metadata.csv
mysql/tests/test_mysql.py
mysql/tests/test_query_activity.py
mysql/tests/variables.py

Adds a new user connections metric `mysql.performance.user_connections` in the standard integration.
- The new metric is emitted using the new `QueryExecutor` API
- Removes user connections rows from DBM's activity payload because we concluded that it is not necessary to send these to our back-end to be emitted. This provides the additional benefit of reducing the overall payload size.

Add MySQL user connections metric

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py

Fixes metadata validation so it does not break when finding missing columns 
metadata validation currently breaks when displaying errors for integrations extras (error fixed in https://github.com/DataDog/integrations-extras/pull/1384):
```
/integrations-core/datadog_checks_dev/datadog_checks/dev/tooling/commands/console.py", line 35, in annotate_display_queue
for func, message in display_queue:
TypeError: cannot unpack non-iterable NoneType object
```

Prevent metadata validation from crashing on missing columns

---

clickhouse/tests/docker/init.sql

Do not recreate the tables if they already exists during the container initialisation. 
The clickhouse tests are flaky. Examples:
- https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=106857&view=logs&jobId=8e96ab15-72b0-549c-5ab8-f9fece94b017&j=8e96ab15-72b0-549c-5ab8-f9fece94b017&t=ec9b40f1-a5eb-523c-a2d7-f48a83ba2f0c
- https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=106829&view=logs&jobId=8e96ab15-72b0-549c-5ab8-f9fece94b017&j=8e96ab15-72b0-549c-5ab8-f9fece94b017&t=ec9b40f1-a5eb-523c-a2d7-f48a83ba2f0c
- https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=106713&view=logs&jobId=8e96ab15-72b0-549c-5ab8-f9fece94b017&j=8e96ab15-72b0-549c-5ab8-f9fece94b017&t=ec9b40f1-a5eb-523c-a2d7-f48a83ba2f0c
The error says:
``` …
```

Do not recreate the tables if they already exists

---

requirements-agent-release.txt

The cluster v2.3.0 was released in [this PR](https://github.com/DataDog/integrations-core/pull/12699/files), although a subsequent [PR](https://github.com/DataDog/integrations-core/pull/12701/files) changed back the version number in `requirements-agent-release.txt`.
Failing job: https://github.com/DataDog/integrations-core/runs/7693754240?check_suite_focus=true

Fix cluster agent version in requirements-agent-release.txt

---

.azure-pipelines/templates/install-deps.yml

Reverts a change made by a recent PR to use a standalone ddev package. Right now pypi only has a 0.0.1 version of `ddev` that is over a month old - https://pypi.org/project/ddev/#history
Right now, marketplace (and seems extras as well) tries to install this, and then fails to configure with:
```
/bin/bash --noprofile --norc /home/vsts/work/_temp/742379f6-5935-4320-9e99-2278a8da5422.sh
File "/opt/hostedtoolcache/Python/3.8.13/x64/bin/ddev", line 8, in <module>
sys.exit(main())
File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/ddev/cli/__init__.py", line 8, in main
from datadog_checks.dev.tooling.cli import ddev
File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/datadog_checks/dev/tooling/cli.py", line 7, in …
```

Install `datadog_checks_dev[cli]` from pypi instead of `ddev`

---

consul/datadog_checks/consul/consul.py
consul/tests/compose/compose.yaml
consul/tests/test_e2e.py
consul/tests/test_unit.py

Resolves #12609 
Implements the tag `consul_node` with data from `ConsulCheck["Node"]` from response data `consul_request('/v1/health/state/any')` for Service Check `consul.check` (health check).
See #12609 
I was unsuccessful at getting a tox test env setup with `ddev` after 1-hour spent trying.
I recommend that y'all quickly run the test `ddev test consul` to ensure that I copied the right node names such as `consul_node:node-1` vs. `consul_node:node-2` between the tests and mocks.

Add tag consul_node to consul service check consul.check from ConsulCheck.Node

---

mcache/datadog_checks/mcache/mcache.py
mcache/metadata.csv
mcache/tests/metrics.py
mcache/tests/test_integration_e2e.py

Add the `max_connections` metric to the `mcache` integration.
Resolves https://github.com/DataDog/integrations-core/issues/12684

Add the `max_connections` metric

---

twistlock/README.md

Fixes (?) the yaml example where the in-app docs are breaking 
noticed it was breaking

Fixing in-app display of twistlock integration docs

---

datadog_checks_downloader/datadog_checks/downloader/download.py
datadog_checks_downloader/pyproject.toml

datadog-checks-downloader should use packaging to parse Python package versions.

Use packaging instead of pkg_resources for parsing version

---

teradata/manifest.json

Re-enable public docs. It was mistakenly disabled during the manifest v2 migration.

Re-enable public docs

---

.gitlab/validate-logs-intgs/validate_log_intgs.py

The weekly logs integration validation gitlab job broke after manifest.json files migrated to v2. Now that V2 migration has completed, we need to update the validation script to reference the updated manifest fields. 
Broken CI validation

Fix logs integration validation

---

openmetrics/pyproject.toml

Bumps base check requirement to v25.4.0
Fix CI
Fix incorrect OpenMetrics V2 check exposition format HTTP header: https://github.com/DataDog/integrations-core/pull/11899
https://github.com/DataDog/integrations-core/blob/master/datadog_checks_base/CHANGELOG.md#2540--2022-05-10

Bumps base check requirement to v25.4.0

---

gitlab/assets/configuration/spec.yaml
gitlab/datadog_checks/gitlab/data/conf.yaml.example

Update the gitlab documentation with correct instructions for specifying the gitlab url with authentication. 
Per the GitLab documentation, the token url format is supported for all tiers including EE and CE: 
* https://docs.gitlab.com/ee/api/
* https://docs.gitlab.com/ee/api/#authentication

Updates GitLab URL documentation

---

mapreduce/tests/test_mapreduce_integration_e2e.py

Add an assert to the mapreduce `test_e2e`.
This test is failing sometimes. Example:
- https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=106873&view=logs&jobId=44f80fa8-59b4-5eac-d564-3b72739a148c&j=44f80fa8-59b4-5eac-d564-3b72739a148c&t=37cf5e0d-a62f-5d05-e6eb-b5df035c1060
I'm not sure if this is because the `mapreduce.job.elapsed_time.max` is optional or if it's because the job is not running. I think it is the latter. Adding an assert will let us know if the job is running or not before running the check and assert the metrics are well collected.

Assert the job is running in the test_e2e

---

LICENSE-3rdparty.csv
datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_downloader/pyproject.toml

https://github.com/DataDog/integrations-core/pull/12560

Add `packaging` to dependencies

---

docs/dev/new_check_howto.md

We don't allow outside contributors to directly push to the integrations-extras repo. If they would like to contribute to it, they would have to fork the repo and then make a PR using the fork.
Was a bit unclear

Update instructions to include Fork

---

airflow/README.md

Update the statsd config example so the comments are not on the same line as the properties. 
Support case. Running airflow using this config:
```
File "/usr/local/bin/airflow", line 25, in <module>
from airflow.configuration import conf
File "/usr/local/lib/python3.8/site-packages/airflow/__init__.py", line 31, in <module>
from airflow.utils.log.logging_mixin import LoggingMixin
File "/usr/local/lib/python3.8/site-packages/airflow/utils/__init__.py", line 24, in <module>
from .decorators import apply_defaults as _apply_defaults
File "/usr/local/lib/python3.8/site-packages/airflow/utils/decorators.py", line 36, in <module>
from airflow import settings
File "/usr/local/lib/python3.8/site-packages/airflow/settings.py", line 121, in <module> …
```

Update the statsd config example

---

cassandra/datadog_checks/cassandra/data/metrics.yaml
cassandra/metadata.csv
cassandra/tests/common.py

This PR adds back 3 previously deleted metrics
Escalation/requested by customer

Add back previously deleted `active_tasks` and `timeouts` metrics for the Cassandra integration

---

datadog_checks_dev/datadog_checks/dev/plugin/hatch/environment_collector.py

- Properly default to plugin config for `base-package-features`
- Can't cache mutable objects

Fix Hatch environment plugin

---

ibm_ace/tests/conftest.py

Default log patterns behaviour is `wait=1, attempts=60`
Set up failed on https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=107538&view=logs&j=dd4b56be-071e-57b4-2a5e-8eda93907f10&t=de2bf97c-09ab-578d-74d6-50a77c38a36d&l=1784
```
E   datadog_checks.dev.errors.RetryError: Command: ['docker', 'compose', '-f', '/home/vsts/work/1/s/ibm_ace/tests/docker/docker-compose.yaml', 'logs']
E   Failed to match `2` of the patterns.
E   Provided patterns: 	- re.compile('Integration server is ready', re.MULTILINE)	- re.compile('Started web server', re.MULTILINE)
E   Missing patterns: 	- re.compile('Started web server', re.MULTILINE)
```

Add attempts, increase waiting time for docker logs

---

ibm_was/tests/conftest.py

Environment failed to start on https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=107537&view=logs&j=203178a3-a7e8-53ac-1b4d-4f9b986b112a&t=3703a3cd-697a-5590-dc54-67db3e8cff7a&l=1072
```
datadog_checks.dev.errors.RetryError: Command: ['docker', 'compose', '-f', '/home/vsts/work/1/s/ibm_was/tests/docker/docker-compose.yaml', 'logs']
E   Failed to match `1` of the patterns.
E   Provided patterns: 	- re.compile('Server server1 open for e-business', re.MULTILINE)
E   Missing patterns: 	- re.compile('Server server1 open for e-business', re.MULTILINE)
```

[IBM WAS] Add attempts, increase logs waiting time

---

datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/v2/migration.py

Make sure that `process_signatures` gets migrated to the manifest V2 format when running the `ddev meta manifest migrate` command
Final piece to fully support `process_signatures` in manifest V2
I confirmed this works locally by running `ddev -x meta manifest migrate activemq 2.0.0`
and confirming the manifest included this section at the bottom of the `integration` asset:
```
...
"process_signatures": [
"activemq"
]
...
```

Make sure process_signatures gets migrated during V2 migrations

---

marklogic/tests/common.py
marklogic/tests/metrics.py
marklogic/tests/test_e2e.py
marklogic/tests/test_marklogic.py

Move e2e tests to a separate file.
Move assertions to `common`
Added assertion for optional metrics as this build was failing because of that 
https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=107820&view=logs&j=71710f82-a700-5025-04de-9315f9265e29&t=60755dd0-fa1f-5e19-668b-97bd6488bfaf&l=211
```
E   Found metrics that are not asserted:
E   	- marklogic.hosts.memory-process-huge-pages-size
E   	- marklogic.hosts.memory-process-rss
E   	- marklogic.hosts.memory-system-free
E   	- marklogic.hosts.memory-system-total
E   	- marklogic.hosts.total-cpu-stat-system
E   	- marklogic.hosts.total-cpu-stat-user
```

Refactor e2e tests, add missing assertions

---

vault/datadog_checks/vault/check.py
vault/datadog_checks/vault/vault.py
vault/tests/conftest.py
vault/tests/test_e2e.py
vault/tests/test_integration.py
vault/tests/utils.py

Use the `client_token` option and set the `X-Vault-Request` header to the scrapers' request wrappers instead of the check request wrapper. 
Update the tests.
Support case. The `client_token` option and the `X-Vault-Request` header are set to the `http` attribute of the check itself. However, it is not used because another request wrapper is created in each scraper, so the `client_token` option is not working and the client gets an error 400. 
- I did not find a way to set the header through the `super().configure_scrapers()` method. If you have any idea, let me know :)
- We missed this case because we have no test using the `client_token` option, we only have tests with the `client_token_path`. I added some tests that read the token from this file and add it as the `client_token` option …

Use the `client_token` option with the openmetrics v2 implementation

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/requirements-dev.txt

Remove the `requirements-dev.txt` files from the `ddev create` integration template
We now use `hatch` by default. This is not used

Remove the `requirements-dev.txt` files from the `ddev create` integration template

---

vault/datadog_checks/vault/vault.py
vault/tests/test_vault.py

Do not use the `client_token` if `no_token` is true with the openmetrics v1 implementation.
Found this issue working on https://github.com/DataDog/integrations-core/pull/12764 and updating the `test_auth_needed_but_no_token` tests. The `client_token` was used even though the `no_token` option was set and no exceptions were raised. 
- This PR is based on https://github.com/DataDog/integrations-core/pull/12764. I do not target master yet so you can review the changes without being polluted by the other one. I will merge this one to master after.
- Tested locally building the wheel

Do not use the `client_token` if `no_token` is true with the openmetrics v1 implementation

---

sqlserver/tests/test_connection.py

Also categorise tests independently since not all tests in the file are unit tests.
Example failures:
* [https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=109408&vie[…]fd3-e4d77a183e2d&t=69858a7d-83bd-5a0d-66ce-9165e8b8a6f9&l=1204](https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=109408&view=logs&j=8d9df12f-f2bb-5103-9fd3-e4d77a183e2d&t=69858a7d-83bd-5a0d-66ce-9165e8b8a6f9&l=1204)
* [https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=109333&vie[…]fd3-e4d77a183e2d&t=69858a7d-83bd-5a0d-66ce-9165e8b8a6f9&l=1221](https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=109333&view=logs&j=8d9df12f-f2bb-5103-9fd3-e4d77a183e2d&t=69858a7d-83bd-5a0d-66ce-9165e8b8a6f9&l=1221)
* …

Skip test_query_timeout on 2019 windows

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/manifest.py

Fail the manifest validation if the manifest file is not found.
I was not on the correct branch and ran the validation. Took me a few minutes to understand why the command succeeded locally but did not on the CI.
Example:
```
╰─❯ ddev validate manifest check                                                                                                                                                                                                                                                                                        ─╯
Validating manifest.json files for 1 checks ...
check/manifest.json does not exist.
1 invalid files
```

Make the manifest validation fail if the file is not found

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/create.py
datadog_checks_dev/datadog_checks/dev/tooling/create.py

Remove the `tox_base_dep` variable from the create command.
We now use `hatch` by default. This is not used

Remove the `tox_base_dep` variable from the create command

---

ibm_ace/tests/conftest.py

IBM Ace still fails to start some times after two attempts.
In [this case](https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=109601&view=logs&j=dd4b56be-071e-57b4-2a5e-8eda93907f10&t=65ab01fd-ee8f-59be-a115-14b63bafca8a&l=602) it is failing because it reaches a bad state
```
ibm-ace-mq  | 2022-08-22T11:27:46.657Z Error -1 starting web server: 
```
So the only solution is to try again.

Increase docker start attempts

---

sqlserver/tests/conftest.py

Docker compose failed after two attempts https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=109662&view=logs&j=1844037c-5a79-57cd-fd15-36c50f4dfdba&t=c5ebbd8d-d13a-587b-7a74-3442ff24c769&l=1505. It seems to be in a bad state `[HADR TRANSPORT] AR[39E3BAD5-39E9-489F-AD00-8B7BBD061A67]->[93B6F4E5-BB41-46B8-985E-A1C1AD672A8F] Transport is not in a connected state, unable to send packet
`

Increase SQL Server docker start attempts

---

.gitlab-ci.yml

Changes the channel where agent build notifications are sent to
The messages are noisy

Change agent build notification channel

---

iam_access_analyzer/CHANGELOG.md
iam_access_analyzer/README.md
iam_access_analyzer/manifest.json

Move the IAM Access Analyzer Integration from the private repo - https://github.com/DataDog/integrations-internal/pull/35/files to this repo. 
Also migrates it to Manifest V2
Trying to get everything onto Manifest V2 (that has a tile)

Initial pass at moving the IAM Access Analyzer Integration to this repo

---

mysql/metadata.csv

These metrics were missing from the metadata file.
Detected on https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=109477&view=logs&j=d74967ea-228d-5634-fe5f-5bd874cd0575&t=41dabac0-8a87-53de-65b2-c4ce3c459938&l=185
```
___________________________________ test_e2e ___________________________________
tests/test_mysql.py:84: in test_e2e
aggregator.assert_metrics_using_metadata(
../datadog_checks_base/datadog_checks/base/stubs/aggregator.py:477: in assert_metrics_using_metadata
assert not errors, "Metadata assertion errors using metadata.csv:" + "\n\t- ".join([''] + sorted(errors))
E   AssertionError: Metadata assertion errors using metadata.csv:
E   	- Expect `mysql.innodb.locked_tables` to …
```

Add missing metadata

---

ddev/src/ddev/cli/application.py

```
│ C:\Users\ofek\Desktop\code\integrations-core\ddev\src\ddev\cli\application.py:82 in              │
│ initialize_old_cli                                                                               │
│                                                                                                  │
│   79 │   │   self.__config['dd_app_key'] = self.config.orgs.get('default', {}).get('app_key',    │
│   80 │   │                                                                                       │
│   81 │   │   kwargs = {'here' if self.config.repo.name == 'local' else self.repo.name: True}     │
│ ❱ 82 │   │   initialize_root(self.__config, **kwargs)                                            │
│   83 │ …
```

Fix legacy tooling initialization when using the --here flag

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/manifest.py
datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/__init__.py
datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/common/validator.py

Stop running the v2 validators for manifest v1 files and add a validator for the version.
We are only running v2 validators: https://github.com/DataDog/integrations-core/blob/2d86725d7ec6b83719c82ec40ab74dc45f9e0e64/datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/__init__.py#L8
Because of that, I got the following trying to validate a v1 file (that was created a few weeks ago on a [branch](https://github.com/DataDog/integrations-core/pull/12548)):
```
File "/Users/florent.clarret/go/src/github.com/DataDog/integrations-core/datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/common/validator.py", line 102, in validate
if not maintainer.isascii():
AttributeError: 'NoneType' object has no attribute 'isascii'
```
With this fix, we have:
```
╰─❯ ddev validate …
```

Add a validator for the manifest version

---

citrix_hypervisor/README.md

Adds the Citrix Hypervisor blog link to its doc page.
Docs team Tuesday task. Improves the SEO of the blog.

Add Citrix Hypervisor link to integration README

---

.azure-pipelines/scripts/sap_hana/linux/50_set_up_sysctl.sh

Use the actual recommended memory.
Seems atm is timing out some times
```
ERROR    datadog_checks.base.checks.base.sap_hana:sap_hana.py:109 Error querying SYS_DATABASES.M_DISK_USAGE: (-10807, 'Connection down: [89012] Socket recv timeout (recv took longer than 10000 ms; timeout configured by communicationTimeout or heartbeat)')
ERROR    datadog_checks.base.checks.base.sap_hana:sap_hana.py:109 Error querying SYS_DATABASES.M_SERVICE_MEMORY: (-10807, 'Connection down: [89012] Socket recv timeout (recv took longer than 10000 ms; timeout configured by communicationTimeout or heartbeat)')
- generated xml file: /home/vsts/work/1/s/sap_hana/.junit/test-unit-$HATCH_ENV_ACTIVEpy38-2.xml -
```

Increase memory

---

datadog_checks_base/tests/base/checks/test_agent_check.py
http_check/assets/configuration/spec.yaml
http_check/datadog_checks/http_check/data/conf.yaml.example

The `http_check`'s `instance` tag is being normalized, and therefore all `instance:test-instance` is converted into `instance:test_instance`, even though the [public docs](https://docs.datadoghq.com/getting_started/tagging/#define-tags) mention that `-` are valid for tags. 
This PR adds a note in the `name` config option to mention that this is happening, since this is where `instance` tag pulls its data.
Support case

Mention that `instance` tag is normalized

---

datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/v2/validator.py
datadog_checks_dev/tests/tooling/manifest_validator/test_v2_validator.py

Validate the `changelog` field references an existing file if provided in the manifest file.
AI-2388
- I don't think we should create a separate command for this validation because we are not validating the content of the changelog file, but that the manifest contains valid data.

Validate the `changelog` field in the manifest file

---

snmp/datadog_checks/snmp/data/profiles/fortinet-fortigate.yaml
snmp/tests/test_profiles.py

snmpwalk extract:
```
.1.3.6.1.4.1.12356.101.5.1.2.1.1.3.1.0,Counter32,0
.1.3.6.1.4.1.12356.101.5.1.2.1.1.3.1.1,Counter32,0
.1.3.6.1.4.1.12356.101.5.1.2.1.1.3.2.0,Counter32,12345
.1.3.6.1.4.1.12356.101.5.1.2.1.1.3.2.2,Counter32,2591
.1.3.6.1.4.1.12356.101.5.1.2.1.1.3.2.3,Counter32,25822
.1.3.6.1.4.1.12356.101.5.1.2.1.1.3.2.6,Counter32,201
.1.3.6.1.4.1.12356.101.5.1.2.1.1.3.2.7,Counter32,0
.1.3.6.1.4.1.12356.101.5.1.2.1.1.3.2.8,Counter32,0
```
Each row is `1.3.6.1.4.1.12356.101.5.1.2.1.1.3.X.Y` where `X` is the `virtualdomain_index` and `Y` is the `policy_index`.
The latter can be found under the OID `1.3.6.1.4.1.12356.101.5.1.2.1.1.1` but not the former. Because both are simple numerical ID, we can instead directly extract the value from each row OID using `index`.
This change is required …

Add virtualdomain_index tag to fgFwPolStatsTable

---

kong/assets/dashboards/kong_overview.json
kong/datadog_checks/kong/kong.py
kong/metadata.csv
kong/tests/test_integration_e2e.py

`kong.table.*` metrics are calculated by counting the number of entries under `database` in the `/status` endpoint. However, the `database` value only contains 1 entry every time, so both `kong.table.count` and `kong.table.items` return a constant of 1 regardless of actual number of databases.
This PR deprecates this metric since it is not accurate and always returns 1.
Note: the `kong_overview.json` dashboard has been updated from
to 
due to the removed table metrics.
Stg: https://dd.datad0g.com/screen/integration/30262/kong-overview-legacy?from_ts=1661450084896&to_ts=1661453684896&live=true

Deprecate Kong table metrics

---

ibm_db2/datadog_checks/ibm_db2/ibm_db2.py

This PR changes the Db2 check to get a valid connection in each check run. Originally, the check would call `get_connection()` only if `self._conn` was `None`. However, this only happened the first check run, so all subsequent runs would always return an `OK` for `can_connect` service check, even if the connection itself was disabled.
Support case
Another option could be to add a connection refresh option (similar to [VSphere check](https://github.com/DataDog/integrations-core/pull/11507)) so you only need to get a new connection after a certain timeout.

Get a connection every check run

---

sqlserver/datadog_checks/sqlserver/activity.py
sqlserver/datadog_checks/sqlserver/statements.py
sqlserver/datadog_checks/sqlserver/utils.py
sqlserver/tests/test_activity.py
sqlserver/tests/test_statements.py

Instead of looking up if the text comes from a procedure via `sys.dm_exec_procedure_stats`, we can simply check if the full text contains `CREATE PROCEDURE/PROC` as per the [sql server docs](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-procedure-transact-sql?view=sql-server-ver16). Note: this doesn't work for encrypted stored procedures (obviously), but in order to prevent extra plan lookups for encrypted stored procedures, we can use the `plan_handle` as the plan key in our RL cache. 
The result of this is a negligible change in performance  between the updated metrics/activity queries and the 7.38 agent version:

Perf improvement for `is_proc` lookup in sql server metrics query

---

snowflake/README.md
snowflake/assets/configuration/spec.yaml
snowflake/datadog_checks/snowflake/data/conf.yaml.example

Updates readme and configuration docs to make it more clear that `min_collection_interval` needs to be explicitly set to `3600` in the `conf.yaml` and that the default is 15s.

Update wording around collection interval

---

apache/README.md
coredns/README.md
elastic/README.md
haproxy/README.md
mongo/README.md
mysql/README.md
nginx/README.md
postgres/README.md
redisdb/README.md

As of Agent 7.36, there's a new way to configure Autodiscovery. This pull request adds v2-style annotation examples.

Adding AD Annotations v2 examples where relevant

---

docs/dev/check_references.md

Removing outdated information about manifest version 1, as now all integration tiles are using manifest version 2. Also clarified some phrasing around which types of files include a manifest.json file. 
Keeping the docs up-to-date

Documentation: Updating manifest.json information in integrations asset reference

---

datadog_checks_dev/datadog_checks/dev/tooling/create.py
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/pyproject.toml
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/pyproject.toml
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/pyproject.toml
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/requirements-dev.txt

- Remove `requirements-dev.txt` from the `pyproject.toml` template file
- Remove `tox.ini` from the `pyproject.toml` template file
- Remove the `requirements-dev.txt` from the log template files
- Remove the `test_dev_dep` template variable since it's not used anymore
We do not use tox anymore.

Remove tox related references from the `ddev create` template files

---

.azure-pipelines/scripts/sap_hana/linux/50_set_up_sysctl.sh
sap_hana/datadog_checks/sap_hana/sap_hana.py

Although all recent changes to HANA have made it more stable on CI it is still failing quite often.
Recent changes:
https://github.com/DataDog/integrations-core/pull/12848
https://github.com/DataDog/integrations-core/pull/12826
https://github.com/DataDog/integrations-core/pull/12528

Increase memory for hana

---

datadog_checks_base/tests/base/utils/http/test_socks5_proxy.py

These tests often fail on py2 with `ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))` or `ConnectionError: SOCKSHTTPConnectionPool(host='nginx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7f844f302090>: Failed to establish a new connection: 0x05: Connection refused',))`
Examples:
* https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=111441&view=logs&j=762a2123-1c7c-5bf0-0e62-04885c3ecd74&t=e42a329a-2791-53f4-67fc-ce0c85b45aed&l=1251
* https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=111116&view=logs&j=762a2123-1c7c-5bf0-0e62-04885c3ecd74&t=e42a329a-2791-53f4-67fc-ce0c85b45aed&l=1253
* …

Skip sock5 tests on py2

---

sqlserver/datadog_checks/sqlserver/activity.py
sqlserver/datadog_checks/sqlserver/statements.py
sqlserver/datadog_checks/sqlserver/utils.py
sqlserver/tests/compose-ha/sql/aoag_primary.sql
sqlserver/tests/compose-high-cardinality-windows/setup.sql
sqlserver/tests/compose-high-cardinality/setup.sql
sqlserver/tests/compose-windows/setup.sql
sqlserver/tests/compose/setup.sql
sqlserver/tests/test_activity.py
sqlserver/tests/test_statements.py

Updates both the sqlserver activity and metrics queries to use statement offsets when grabbing the sql text output from `sys.dm_exec_requests`/`sys.dm_exec_query_stats` 
Note: this results in the query signatures changing because we are only taking the actual query text. For example, we lose the types for queries that are executed with parameters
Text before: `(@P1 int,@P2 nvarchar(10))SELECT * FROM ϑings where id = @P1 and name = @P2`
... now results in `SELECT * FROM ϑings where id = @P1 and name = @P2`. The execution plan will still contain types so this seems OK.
This means this is a **breaking change** as it will effect our ability to link queries that are reported from existing agent versions. 
This change fixes a bug, where we are reporting SQL stored procedure stats incorrectly, …

SQL Server: Use statement_start_offset to extract SQL text being run from Procedure text

---

.github/workflows/config/labeler.yml

Fixes the PR labeler config to use glob patterns instead of regex patterns. The official labeler GH action does not support regex patterns.

Convert regex patterns to glob patterns in PR labeler config

---

impala/assets/dashboards/impala_catalog_overview.json
impala/assets/dashboards/impala_daemon_overview.json
impala/assets/dashboards/impala_statestore_overview.json
impala/manifest.json

Add default dashboard to the new Impala integration. 
I have 4 different dashboards:
- A global dashboard with information about the three different processes
- One dashboard for the daemon processes
- One dashboard for the statestore processes
- One dashboard for the catalog processes
I saw that some metrics do not have units. I'm working on it.
https://github.com/DataDog/integrations-core/pull/12548

Add the dashboards

---

avi_vantage/tests/test_avi_vantage.py
proxysql/tests/test_e2e.py
singlestore/tests/test_e2e.py
snowflake/tests/test_e2e.py

Remove the assertions on metadata in the e2e test.
Following [this PR](https://github.com/DataDog/datadog-agent/pull/13376), the metadata are not sent by the agent if the check is not scheduled, which is our case in our tests. Since we are getting the data from the agent, the metadata are gone. 
I took a look at the unit/integration and made sure they still validate the metadata (because they are not using the agent so we have the data).

Stop asserting metadata during e2e tests

---

.gitlab/validate-logs-intgs/validate_log_intgs.py

Now that we've [migrated](https://github.com/DataDog/integrations-core/pull/12745) to manifest v2 there is no notion of integration name, so the exceptions we have defined in the validation need to correspond to `app_id`s. This PR updates the exception map to use the `app_id`s so these integrations don't fail validation anymore

Update app id exceptions in logs validation

---

sqlserver/assets/configuration/spec.yaml

If client is using version 19 of the Microsoft OLE DB Driver the adoprovider: parameter needs to be set to "MSOLEDBSQL19" instead of "MSOLEDBSQL".
Adds additional setting for adoprovider: parameter
Zendesk ticket:
https://datadog.zendesk.com/agent/tickets/906248
Change was suggested under different PR:
https://github.com/DataDog/integrations-core/pull/12916

Updating adoprovider parameter details 2

---

.github/workflows/config/labeler.yml

Changes the `any` match condition for paths in `*/!(datadog_checks)/**` to `all` so that if any of the changed paths are in an integration, then the `no-changelog` label should not be applied. Same if the `pyproject.toml` file has been changed. 
https://github.com/actions/labeler#match-object

Do not apply no-changelog label if any changed paths are in `*/datadog_checks/**` or `pyproject.toml`

---

datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/v2/validator.py
datadog_checks_dev/tests/tooling/manifest_validator/test_v2_validator.py

Make changelog validation case sensitive
Changelog validation was not failing with a file named CHANGELOG.MD
We may want to do this case sensitive validation in more places

Add case sensitive changelog validation

---

sqlserver/assets/configuration/spec.yaml
sqlserver/datadog_checks/sqlserver/data/conf.yaml.example

If client is using version 19 of the Microsoft OLE DB Driver the adoprovider: parameter needs to be set to "MSOLEDBSQL19" instead of "MSOLEDBSQL".
Adds additional setting for adoprovider: parameter
Zendesk ticket:
https://datadog.zendesk.com/agent/tickets/906248

Updating adoprovider parameter details

---

datadog_checks_dev/datadog_checks/dev/tooling/create.py

This PR changes the template path for generating the README of a contributor tile-only integration.
There is no directory called `tile_v2`, so generating a tile-only contributor integration will fail.

Fix tile-only README template generation

---

rabbitmq/datadog_checks/rabbitmq/const.py
rabbitmq/metadata.csv
rabbitmq/tests/metrics.py

Adds new metric to track number of bytes of each queue in rabbitmq.

[rabbitmq] Add new metric to track size of queues in bytes

---

pivotal_pks/README.md

Add information to the Pivotal PKS documentation setup section, which was removed from the main Pivotal Platform documentation in the following documentation repo PR:
https://github.com/DataDog/documentation/pull/14955
DOCS-3777
Preview link:
https://docs-staging.datadoghq.com/docs3777/update-pull-config-preview/integrations/pivotal_pks/#setup

(DOCS-3777) Update Pivotal PKS setup

---

aerospike/pyproject.toml
amazon_msk/pyproject.toml
datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/pyproject.toml
datadog_checks_dev/datadog_checks/dev/plugin/tox.py
kafka_consumer/pyproject.toml
snowflake/pyproject.toml

Bump the dependencies before the freeze 
```
╰─❯ ddev dep updates --sync --batch-size 10                                                                                                                                                                                                                                                                             ─╯
Files updated: 5
Updated 8 dependencies
```
Only one batch is needed this time.
Freeze at the end of the week.
- https://github.com/globality-corp/flake8-logging-format/pull/33 has been shipped with the 0.7.0

Bump dependencies for 7.40

---

win32_event_log/tests/conftest.py

Add dd_environment metadata to use windows containers.

Add docker_platform windows to win32_event_log env

---

datadog_checks_dev/datadog_checks/dev/tooling/constants.py
datadog_checks_dev/datadog_checks/dev/tooling/create.py

Update the default README links to include a `repository` variable. 
Before, `integrations-core` was hardcoded and we had to update it. 
A part of the job was done in this PR https://github.com/DataDog/integrations-core/pull/12742

Templatize the repository in the README links

---

docker_daemon/README.md

Amends documentation to:
- match the corresponding field name (collect_exit_codes:)
- link to the correct line where field can be found within our github page (https://github.com/DataDog/integrations-core/blob/master/docker_daemon/datadog_checks/docker_daemon/data/conf.yaml.example#L154)
https://datadog.zendesk.com/agent/tickets/690625 
Customer was unable to find correct field due to outdated names/links

Update docker.exit field name & github link

---

vertica/assets/monitors/vertica_replication_safety.json
vertica/manifest.json

Add a recommended monitor for Vertica. This monitor warns about when the database may become unsafe due to the number of failed nodes exceeding the k-safety value. See [official docs](https://www.vertica.com/docs/12.0.x/HTML/Content/Authoring/ConceptsGuide/Components/K-Safety.htm).
[AI-2670](https://datadoghq.atlassian.net/browse/AI-2670)

Add recommended monitor for Vertica

---

datadog_cluster_agent/datadog_checks/datadog_cluster_agent/check.py
datadog_cluster_agent/metadata.csv
datadog_cluster_agent/tests/fixtures/metrics.txt
datadog_cluster_agent/tests/test_datadog_cluster_agent.py

Adds the following metrics to the `datadog_cluster_agent` integration:
* kubernetes_apiserver.kube_events
* kubernetes_apiserver.emitted_events
These metrics were introduced in https://github.com/DataDog/datadog-agent/pull/13158

[datadog_cluster_agent] Add kubernetes_apiserver metrics

---

calico/metadata.csv
calico/tests/common.py
calico/tests/conftest.py
calico/tox.ini

Fix calico e2e test by updating calico version used in tests to v3.24.
[AI-2676](https://datadoghq.atlassian.net/browse/AI-2676), Calico e2e test was failing.

Update calico to v3.24 for tests and reactivate e2e tests

---

activemq/pyproject.toml
activemq_xml/pyproject.toml
ambari/pyproject.toml
apache/pyproject.toml
avi_vantage/pyproject.toml
datadog_checks_dev/pyproject.toml
gitlab_runner/pyproject.toml
openmetrics/pyproject.toml
vault/pyproject.toml

Remove tox files references in some pyproject.toml files.
Those integrations do not have those files anymore because they have been migrated to hatch. We forgot to update this file. 
Spotted by @yzhan289 [here](https://github.com/DataDog/integrations-core/pull/12928#pullrequestreview-1107884199)

Remove tox files references in some pyproject.toml files

---

win32_event_log/datadog_checks/win32_event_log/check.py
win32_event_log/tests/conftest.py
win32_event_log/tests/test_check.py

If `EvtNext` fails due to an issue with the `EvtSubsribe` handle the check will recreate the subscription and allow events to continue to be collected.
This can happen when an event publisher is removed while we are subscribed to it. This sometimes happens during software updates.
xref https://datadoghq.atlassian.net/browse/WA-71

Recover from EvtNext error when EvtSubscribe handle fails

---

windows_service/assets/configuration/spec.yaml
windows_service/datadog_checks/windows_service/config_models/defaults.py
windows_service/datadog_checks/windows_service/config_models/instance.py
windows_service/datadog_checks/windows_service/data/conf.yaml.example
windows_service/datadog_checks/windows_service/windows_service.py
windows_service/tests/test_bench.py
windows_service/tests/test_windows_service.py

Add a new tag to each windows_service service check that indicates that service's startup type.
Add a `windows_service_startup_type_tag` option to control presence/absence of the tag.
customer requests https://datadoghq.atlassian.net/browse/WA-77

Add optional windows_service_startup_type tag

---

cert_manager/manifest.json

Update the Supported OS classifier to `macOS`
`Mac OS` is not supported by the `ddev agent requirements` command https://github.com/DataDog/integrations-core/blob/34767476bae373ef8778ce46b64b34458ea618bf/datadog_checks_dev/datadog_checks/dev/tooling/release.py#L93-L94. Because of that, we append `; sys_platform != 'darwin'` to the dep, which should not be
We should add a validation in the `ddev validate manifest` command, adding a [card](https://datadoghq.atlassian.net/browse/AI-2687) to our board.

Update the classifier for macOS

---

kafka_consumer/assets/configuration/spec.yaml
kafka_consumer/datadog_checks/kafka_consumer/config_models/defaults.py
kafka_consumer/datadog_checks/kafka_consumer/config_models/instance.py
kafka_consumer/datadog_checks/kafka_consumer/data/conf.yaml.example
kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
kafka_consumer/datadog_checks/kafka_consumer/new_kafka_consumer.py
kafka_consumer/metadata.csv
kafka_consumer/tests/test_kafka_consumer.py

Puts the lag in seconds metric behind a feature flag.

[kafka consumer integration] Put lag in seconds behind a feature flag

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/ci.py

Do not fail the validation if the `pr_labels_config_relative_path` key is not defined for the repository.
CI is failing in -extras:
- https://github.com/DataDog/integrations-extras/pull/1539
- https://github.com/DataDog/integrations-extras/actions/runs/3080683701/jobs/4978322219
We will probably have this error for marketplace too

Do not fail the validation if `pr_labels_config_relative_path` is not defined

---

impala/assets/configuration/spec.yaml
impala/datadog_checks/impala/data/conf.yaml.example

Update the impala log default location
Pair QAing the new Impala integration with @yzhan289. `/opt/impala/logs` is used only in the test docker image. Default log location is `/var/log/impala`. More info [here](https://impala.apache.org/docs/build/html/topics/impala_logging.html)
Already updated the RFC accordingly
Should be shipped with 7.40

Change the path to the default log folder

---

ibm_db2/datadog_checks/ibm_db2/ibm_db2.py
ibm_db2/tests/test_unit.py

QA for https://github.com/DataDog/integrations-core/pull/12736
The original PR addressed a customer concern about the integration keeping emitting an OK service check even if the integration was failing to connect and showing errors in the agent status. It did so by stopping to cache the connection all toghether.
There are two instances where this integration attempts to create a new connection:
* At the beginning of the check run
* In case of an error on the middle of the check run. In this case we were failing to both reassign the connection and emit a critical service check and this is the bug that is being fixed here.
This PR fixes the bug mentioned before and reverts the changes about connection caching done in the original PR.
Aside from that the metadata method was missing the …

Emit critical service check when connection is lost

---

mysql/datadog_checks/mysql/mysql.py

https://github.com/DataDog/integrations-core/pull/12343 introduced a method to validate that `events_waits_current` is an enabled consumer by doing a query on `performance_schema.setup_consumers`. This is fine for dbm users or the core integration users that have had to `grant select` on the performance_schema for core metrics collection but some users don't need to grant select on the performance schema because they don't use any features that require it otherwise. 
For those users, the mysql integration would break if that grant was missing. This PR addresses this by limiting the execution of that SELECT to find if `events_waits_current` is enabled only to users of dbm activity collection.
For reference, here's an example of the error users would have been getting before:
```
[ERROR]: …
```

Fix check failing when missing unnecessary SELECT grant on perf schema

---

postgres/datadog_checks/postgres/statements.py
postgres/tests/test_statements.py

This PR aims to address confusion that comes up related to inconsistent treatment the `ignore_databases` configuration: 
* Query samples/activity and core metrics honored the `ignore_databases` while query metrics collection ignored it.
I validated the performance and impact of this on our integration environment. Note that I tested this change along with https://github.com/DataDog/integrations-core/pull/12999 because they are both related to the same goal of reducing confusion regarding our data collection, going out at the same time. The material impact is that prior to both changes, query samples/activity was not collected on the default `postgres` database. With the two changes, they now are. And because query metric collection didn't honor the `ignore_databases` configuration before, …

Honor ignore_databases in query metrics collection

---

ibm_mq/assets/configuration/spec.yaml
ibm_mq/datadog_checks/ibm_mq/config.py
ibm_mq/datadog_checks/ibm_mq/config_models/defaults.py
ibm_mq/datadog_checks/ibm_mq/data/conf.yaml.example

None is desirable if TLS is not required, see https://github.com/dsuch/pymqi/blob/3c5453200ff5a3c2b1476e4fbb56b979eb378cf4/code/pymqi/__init__.py#L1604-L1608

Don't set any default algorithm for `ssl_cipher_spec`

---

.github/workflows/labeler-reusable.yml

Sets config `sync-labels` to `""` in order to workaround bug in the labeler action.
https://github.com/actions/labeler/issues/112#issuecomment-1000491676
Fix PR labeler action from removing manually added labels.

Use workaround for labeler `sync-labels` bug

---

ecs_fargate/tests/conftest.py
ecs_fargate/tests/test_e2e.py
ecs_fargate/tox.ini

Adds an e2e test to `ecs_fargate` that asserts that a critical check is emitted, as there's no service running.
[AI-2508](https://datadoghq.atlassian.net/browse/AI-2508)

Add minimal e2e test for ecs_fargate integration

---

vault/datadog_checks/vault/vault.py

Removes `poll` method as it's redundant.
QA for #12776.
The headers are already being set on `parse_config` which also includes the logic to add the token to the header only if the `no_token` config is set to `false`. `poll` was overwriting the headers and therefore has duplicate logic.

Remove unnecessary `poll` method

---

windows_service/assets/configuration/spec.yaml
windows_service/datadog_checks/windows_service/config_models/instance.py
windows_service/datadog_checks/windows_service/data/conf.yaml.example
windows_service/datadog_checks/windows_service/windows_service.py
windows_service/tests/common.py
windows_service/tests/conftest.py
windows_service/tests/test_windows_service.py

Adds a new `startup_type` pattern to the windows_service `services` config entry that enables users to filter services by their startup type at the agent.
This new pattern combines with the existing patterns
```
services:
- EventLog
services:
- name: EventLog
services:
- startup_type: automatic
services:
- name: EventLog
startup_type: automatic
```
https://datadoghq.atlassian.net/browse/WA-77
builds upon https://github.com/DataDog/integrations-core/pull/12932 by providing a way to filter the startup type at the agent to reduce bandwidth usage and unwanted service checks from showing in the dashboard.
Combining this with the `windows_service_startup_type` tag can be useful for separating service checks by their startup type in Monitors, for an example like the following
```
services:
- …
```

Add Windows service `startup_type` filter to config

---

impala/tests/compose/docker-compose.yaml
impala/tests/conftest.py

Mount and collect the logs in the agent container to collect them.
The impala integration collects logs but the e2e was not configured to do so.
This needs some explanations:
1. Impala is composed of three different services: daemon, catalog and statestore
2. Each of those services generate 4 file, one per log level. For instance `impalad.c38ed8616270.invalid-user.log.ERROR.20220922-100840.1` and we can not predict the name of this file. Impala provide a symlink, `impalad.ERROR` in this case which references the latest log file. 
3. Impala writes directly to the destination log file and does not use the symlink. Because of that, if I use the `mount_logs=True` option, a 'impalad.INFO' file is created and we can not collect the logs, because the file is never opened by Impala.
4. Here what …

Collect logs in the e2e environment

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/testable.py
datadog_checks_dev/datadog_checks/dev/tooling/github.py
datadog_checks_dev/tests/tooling/test_github.py

Update the `trello testable` command to:
1. Get the main reviewers of a PR. By main, I pick only the one who approved.
2. Avoid assigning the trello cards to the main reviewers.
Ideally, we should not QA a PR we already reviewed.
Not sure if `approvers` actually means something. Also, we could update the condition if you think we should not filter on the review status

Avoid assigning QA cards to the main reviewers

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/agent/requirements.py

Avoid adding the `ddev` check to the requirements-agent-release.txt file, just like `datadog_checks_dev`
No need ton include this in the current release, we can wait for the mergefreeze to be lifted

Do not include `ddev` in the `requirements-agent-release.txt` file

---

mysql/datadog_checks/mysql/statement_samples.py

These debug tags are expected to be present for all internal integration performance metrics. They were missing from this specific metric only.
Improve tagging of internal performance metrics.

add missing debug tags for internal mysql run_explain metric

---

.github/CODEOWNERS

Team `infrastructure-integrations` is being renamed to Network Device Monitoring

Rename infra-intgs team to NDM

---

mongo/datadog_checks/mongo/collectors/fsynclock.py
mongo/datadog_checks/mongo/mongo.py
mongo/tests/mocked_api.py
mongo/tests/test_e2e.py

It forces `db.aggregate([{"$currentOp": {}}])` to be always called on the `admin` database regardless of what's configured. This is required as per [mongo's docs](https://www.mongodb.com/docs/manual/reference/operator/aggregation/currentOp/) (and also appears on the error message when you call it on an arbitrary database). This also matches the behavior that we had when we were using pymongo 3.x (as [that ran against `admin` under the hood](https://github.com/mongodb/mongo-python-driver/blob/ee262d680fc4ea369a4a982cf5a8f15a3aa9cddf/pymongo/database.py#L1129-L1131)).
Support case. An unexpected behavior change coming from updating from pymongo 3.x to 4.x.

Fix collection of `fsyncLocked` metric when configured database is not `admin`

---

mysql/assets/configuration/spec.yaml
mysql/datadog_checks/mysql/activity.py
mysql/datadog_checks/mysql/config.py
mysql/datadog_checks/mysql/config_models/defaults.py
mysql/datadog_checks/mysql/config_models/instance.py
mysql/datadog_checks/mysql/statement_samples.py
mysql/datadog_checks/mysql/statements.py

Adds two hidden options `log_unobfuscated_queries` and `log_unobfuscated_plans` which will log the original unobfuscated SQL queries and plans respectively if an obfuscation error occurs. These options will simplify the debugging process when dealing with obfuscation errors.

[MySQL] Added Agent settings to log original unobfuscated strings

---

postgres/assets/configuration/spec.yaml
postgres/datadog_checks/postgres/config.py
postgres/datadog_checks/postgres/config_models/defaults.py
postgres/datadog_checks/postgres/config_models/instance.py
postgres/datadog_checks/postgres/statement_samples.py
postgres/datadog_checks/postgres/statements.py

Adds two hidden options `log_unobfuscated_queries` and `log_unobfuscated_plans` which will log the original unobfuscated SQL queries and plans respectively if an obfuscation error occurs. These options will simplify the debugging process when dealing with obfuscation errors.
The original code in `postgres/datadog_checks/postgres/statements.py` already had a [logging line that logs the original unobfuscated query](https://github.com/DataDog/integrations-core/blob/a5e1ce3d8bda06018f6ecd3876c1005f9c5c2bd6/postgres/datadog_checks/postgres/statements.py#L363), with no configuration parameter required. This PR changes the code to only log the query when the `log_unobfuscated_queries` parameter is enabled.

[Postgres] Added Agent settings to log original unobfuscated strings

---

sqlserver/assets/configuration/spec.yaml
sqlserver/datadog_checks/sqlserver/activity.py
sqlserver/datadog_checks/sqlserver/config_models/defaults.py
sqlserver/datadog_checks/sqlserver/config_models/instance.py
sqlserver/datadog_checks/sqlserver/sqlserver.py
sqlserver/datadog_checks/sqlserver/statements.py

Adds two hidden options `log_unobfuscated_queries` and `log_unobfuscated_plans` which will log the original unobfuscated SQL queries and plans respectively if an obfuscation error occurs. These options will simplify the debugging process when dealing with obfuscation errors.

[SQL Server] Added Agent settings to log original unobfuscated strings

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/create.py
datadog_checks_dev/datadog_checks/dev/tooling/create.py

It enables the creation of new integrations in arbitrary locations, by ensuring that all necessary fields are prompted for in a catch-all case.
It was reported internally that running `ddev --here create <INTEGRATION-NAME>` was failing, which I could confirm happens when running it in an arbitrary folder.
Was only tested manually.

Allow creating integrations with `--here` in an arbitrary folder

---

vault/datadog_checks/vault/check.py
vault/tests/test_vault.py

Simplifies code by setting up the scraper configurator to pick up the header instead of setting it ad-hoc after configuration.
Found while QA'ing #12764.

Ensure X-Vault-Request header is set to `true` on all requests

---

cockroachdb/tests/conftest.py
cockroachdb/tests/test_cockroachdb.py

It looks like the integration hits the default limit of 2000 metrics which results in not always getting the `cockroach.build.timestamp` metric that's used in a test to dynamically get the version.
Tests failing in CI.

[cockroachdb] Increase `max_returned_metrics` in test to get expected metric

---

cockroachdb/datadog_checks/cockroachdb/cockroachdb.py
cockroachdb/tests/conftest.py

Core integrations shouldn't have a limit.

Remove metrics limit from legacy version of the integration

---

network/assets/configuration/spec.yaml
network/datadog_checks/network/data/conf.yaml.default
network/datadog_checks/network/network.py

Loopback interfaces don't support ethtool ioctl call and they are not gonna expose driver specific informations. 
Exclude them so that we don't generate error logs.
We want to avoid error logs. While they don't have an impact, they certainly are noisy.

Exclude loopback interface from ethtool

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/testable.py

Add the Windows-Agent team to the `testable` command
This team was missing, I manually moved the card to the right column

Add the Windows-Agent team to the `trello testable` command

---

win32_event_log/README.md

Fix the regex in the documentation for the win32_event_log integration. Also add a section with a specific regex for matching EventID's from legacy providers.
The example regex included wildcards that resulted in undesired matches. There were also three different regex provided for filtering by EventID.
https://datadoghq.atlassian.net/browse/WA-90
The inconsistent EventID type introduced by legacy providers is documented in [WA-91](https://datadoghq.atlassian.net/browse/WA-91) and the fix should be delivered in agent version 7.41.

Fix win32_event_log documentation example regex

---

ibm_mq/datadog_checks/ibm_mq/config.py
ibm_mq/tests/test_config.py

This PR does two things:
- Refactors the code determining if SSL should be enabled for the IBM MQ check.
- Adds `ssl_certificate_label` as an SSL config option used when determining SSL auth status.
Clarify when SSL is enabled.

Update SSL connection configs used for determining SSL auth

---

.github/PULL_REQUEST_TEMPLATE.md

Update the Github PR template to include using the `qa/skip-qa` label.
This label lets the release script directly skip labeled PRs from having trello cards generated rather than having a prompt.
Credit to @FlorentClarret for finding this in the script

Add entry for skipping QA in PR template

---

datadog_checks_downloader/setup.py

Fix keywords in setup.py, see [keywords section](https://setuptools.pypa.io/en/latest/references/keywords.html). Originally spotted by @cedricvanrompay-datadog.

Fix setup.py keywords in datadog-checks-downloader

---

sqlserver/datadog_checks/sqlserver/connection.py
sqlserver/tests/test_connection.py

We received a [bug report](https://github.com/DataDog/integrations-core/issues/13051) that we are not properly casting customer-provided ports to a string. This fixes the issue by always casting the port to a string during string concatenation.

sqlserver/connection: always cast provided port to str

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py
datadog_checks_dev/tests/tooling/commands/validate/test_metadata.py

- Return an error code if the prefix is invalid in the `metadata.csv` file.
- Add tests
I was working on AI-2500, did not find the bug mentioned so I wrote a test to make sure and spotted this one instead.

Make the `validate metadata` command fail if the metric prefix is invalid

---

sqlserver/datadog_checks/sqlserver/connection.py
sqlserver/tests/test_connection.py

We received a https://github.com/DataDog/integrations-core/issues/13051 that we are not properly casting customer-provided ports to a string. This fixes the issue by always casting the port to a string during string concatenation.

sqlserver/connection: always cast port to str

---

.github/CODEOWNERS

Updates the owners of integrations previously owned by Agent Platform in the `CODEOWNERS` file:
- System integrations (process, disk and network) are now owned by Agent Integrations. The Windows Agent team is listed as a secondary owner, to help with the Windows bits of these checks.
- The IBM i integration is now owned by Agent Integrations.
- The OTel integration is now owned by the OpenTelemetry team.
To be merged on October 10th, 2022.
Ownership updates.

Update codeowners for Agent Platform-owned integrations

---

.azure-pipelines/agent.yml
.azure-pipelines/all_comment.yml
.azure-pipelines/all_master.yml
.azure-pipelines/all_pr.yml
.azure-pipelines/changes.yml
.azure-pipelines/latest.yml
.azure-pipelines/nightly_latest_base.yml
.azure-pipelines/nightly_py2.yml
.azure-pipelines/templates/common-variables.yml

Adds a reference to the `core-variables` variable group on Azure Pipelines to all of our pipelines so that we don't need to maintain secrets and variables individually for every pipeline. In the process, it also factors out all variables that are used in all pipelines to a separate template for reuse.
[AI-2094](https://datadoghq.atlassian.net/browse/AI-2094)
This change will only have an effect once the aforementioned variable group is properly populated and corresponding variables deleted from individual pipelines (needs to be done on the az's UI).
Reference:
- https://learn.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml

Use variable groups on azure pipelines

---

spark/tests/test_spark.py

Add unit tests in case no running apps are found.
Saw the test were missing working on https://github.com/DataDog/integrations-core/pull/13067
@alopezz: The service check is submitted during the `_get_running_apps` call. For example https://github.com/DataDog/integrations-core/blob/master/spark/datadog_checks/spark/spark.py#L263-L268

Add unit tests in case no running apps are found

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/tester_selector/github_trello_user_matcher.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/tester_selector/tester_selector.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/tester_selector/trello_users.py
datadog_checks_dev/datadog_checks/dev/tooling/trello.py
datadog_checks_dev/tests/tooling/test_trello.py

Replaces the existing member-by-member fetching strategy with the use of [an endpoint](https://developer.atlassian.com/cloud/trello/rest/api-group-boards/#api-boards-id-members-get) that returns the same data in a single call.
[AITOOLS-66](https://datadoghq.atlassian.net/browse/AITOOLS-66). Would also close https://github.com/DataDog/integrations-core/pull/13024.
I haven't been able to test this thoroughly, an attempt at a dry run at least shows it's not completely broken.

Use specific endpoint to get all members from trello board at once

---

datadog_checks_dev/datadog_checks/dev/conditions.py
datadog_checks_dev/datadog_checks/dev/docker.py
datadog_checks_dev/datadog_checks/dev/utils.py

Remove the legacy docker-compose.
https://datadoghq.atlassian.net/browse/AITOOLS-65
We do not use `docker-compose` anymore.

Remove the legacy docker-compose

---

.gitlab-ci.yml

This reverts commit 99ab510798257730b1a2b0373f32a21bc0afec65
After https://github.com/DataDog/integrations-core/pull/12956, we can rely on the latest tagger image since we know the dependencies are pinned to the correct ones

Revert "pin tagger image (#12943)"

---

datadog_checks_base/datadog_checks/base/utils/replay/execute.py

Fixes fork bomb and CPU overconsumption when using `process_isolation: true` in the init_config.
QA https://github.com/DataDog/integrations-core/pull/12986

Prevent fork bomb when defining the experimental `process_isolation` option globally in the `init_config` section

---

datadog_checks_base/datadog_checks/base/utils/replay/execute.py

Backport https://github.com/DataDog/integrations-core/pull/13091 to 7.40

Prevent fork bomb when defining the experimental process_isolation option globally in the init_config section

---

confluent_platform/assets/dashboards/overview.json

* Updates the default dashboard to use `confluent.can_connect` instead of `confluentplatform.can_connect` to align with the service check provided by Confluent Platform
* Customer mentioning the widget is empty despite having connected hosts
* The service check is `confluent.can_connect` as shown in https://github.com/DataDog/integrations-core/blob/master/confluent_platform/assets/service_checks.json which I confirmed on the customer's account as well

Updates Confluent Platform dashboard to use the correct service check

---

snmp/metadata.csv

Add missing closing bracket (`]`)
Typo originally mentioned here: https://github.com/DataDog/documentation/pull/15450

[DOCS] Fix typo in SNMP metrics

---

network/datadog_checks/network/check_linux.py
network/datadog_checks/network/network.py
network/tests/test_ethtool.py
network/tests/test_network.py

split of https://github.com/DataDog/integrations-core/pull/13102 only extracting the linux check for easier review
Extract check linux into a different class
Rename methods that will remain in the parent class
Noticed that some parts of the linux check have no coverage, working on it on a separate PR https://github.com/DataDog/integrations-core/pull/13117

[network] Refactor: split check_linux methods into different class

---

sqlserver/datadog_checks/sqlserver/statements.py
sqlserver/tests/test_statements.py

This PR updates the query the agent runs to produce DD Query Metrics for sqlserver (e.g.: `sqlserver.queries.count`) in the following way:
1. Moves the filter `where last_execution_time > dateadd(second, -?, getdate())` from the pre-aggregation part of the query to post aggregation (`qstats` CTE -> `qstats_aggr_split` CTE) 
2. Moves the `TOP 10000` limit to the `qstats_aggr_split` CTE
By doing this, we are able to accurately calculate sums for each of the relevant rows in `sys.dm_exec_query_stats` (e.g.: `execution_count`)
Prior to this change, a bug existed in which we could sometimes inaccurately calculate sqlserver query metrics. This would result in certain metrics looking wrong in our UI. For example, for a query with constant throughput, the `sqlserver.queries.count` metric looked …

Fix Query Metrics query to correct for over-inflated / incorrect SQL Server metrics 

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/codeowners.py

Allow the 1e tile to have an email-based codeowner.
https://github.com/DataDog/integrations-extras/pull/1569

Allow 1e to have email-based codeowners

---

.azure-pipelines/templates/install-deps.yml
.azure-pipelines/templates/run-tests.yml
.azure-pipelines/templates/test-single-linux.yml
.azure-pipelines/templates/test-single-windows.yml
datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py

Replaces installation of unsupported python uploader fork with new binary uploader.
It also moves the invocation of `codecov` outside of `ddev` and into a CI step, next to the step where the codecov uploader is installed, so that it's easier to track the dependency of this step on the binary. It also moves the installation of the codecov uploader to after tests have run (saves time in case tests fail).
[AITOOLS-1](https://datadoghq.atlassian.net/browse/AITOOLS-1)
I've pinned the version of the uploader to the current latest version (0.3.2), so that I could add SHASUM based verification. That should be good enough to be confident that we get the right binary.

Migrate to new codecov uploader

---

directory/datadog_checks/directory/directory.py
directory/datadog_checks/directory/traverse.py

Improve the error handling when Agent tries to read the not allowed directory.
Suppose we have the following directory and `conf.yaml`.
```
vagrant@vagrant:~$ whoami
vagrant
vagrant@vagrant:~$ mkdir -p test/foo
vagrant@vagrant:~$ mkdir -p test/bar
vagrant@vagrant:~$ chmod 700 test
vagrant@vagrant:~$ ls -la test
total 16
drwx------  4 vagrant vagrant 4096 Oct 12 04:38 .
drwxr-x--- 15 vagrant vagrant 4096 Oct 12 04:38 ..
drwxrwxr-x  2 vagrant vagrant 4096 Oct 12 04:38 bar
drwxrwxr-x  2 vagrant vagrant 4096 Oct 12 04:38 foo
```
```yaml
init_config:
instances:
- directory: /home/vagrant/test
```
When we run this command,
```bash
sudo -u dd-agent datadog-agent check directory -l error
```
We have the non-actionable message.
```
directory (1.13.1)
------------------
Instance ID: …
```

directory: Improve error message

---

datadog_checks_dev/datadog_checks/dev/env.py
datadog_checks_dev/datadog_checks/dev/kind.py
datadog_checks_dev/tests/test_kind.py

Add the ability to retry `kind` environments
https://datadoghq.atlassian.net/browse/AITOOLS-37
I get this error on windows:
```
failed to pull image "kindest/node:v1.25.2@sha256:9be91e9e9cdf116809841fc77ebdb8845443c4c72fe5218f3ae9eb57fdb4bace": command "docker pull kindest/node:v1.25.2@sha256:9be91e9e9cdf116809841fc77ebdb8845443c4c72fe5218f3ae9eb57fdb4bace" failed with error: exit status 1\n\nCommand Output: docker.io/kindest/node@sha256:9be91e9e9cdf116809841fc77ebdb8845443c4c72fe5218f3ae9eb57fdb4bace: Pulling from kindest/node\nno matching manifest for windows/amd64 10.0.17763 in the manifest list entries
```

Add the ability to retry kind environments

---

datadog_checks_base/datadog_checks/base/utils/subprocess_output.py

Clarifies subprocess documentation about command name in the `get_subprocess_output` command
Documenting potentially surprising behavior.
N/A

Updated subprocess docs with clarification for command name

---

process/datadog_checks/process/process.py

Changes the log level for when a process isn't found.
This is a very noisy log. In our environment, we wish to monitor some specific process which exists in kubernetes masters only, but since there's no way to target this check to a specific nodes, this log spams on thousands of nodes where it is expected that the process doesn't exist. This should be a debug level log.
None.

Change log level to debug

---

.github/workflows/validations.yaml

Allow `Comment PR on failure` to fail
https://datadoghq.atlassian.net/browse/AITOOLS-45
More info here https://github.com/DataDog/integrations-extras/pull/1573

Allow `Comment PR on failure` to fail

---

network/datadog_checks/network/check_windows.py
network/datadog_checks/network/network.py
network/tests/test_network.py
network/tests/test_windows.py

Split of https://github.com/DataDog/integrations-core/pull/13102
* Moves all windows related code to a separate class.
* Creates a new test module with a single test that asserts the right class is instantiated.
* The remaining tests will be moved in a followup PR.
* Small fix on main module asserts to include a more descriptive error message
* Splitting tests on a separate PR: https://github.com/DataDog/integrations-core/pull/13145

Extract windows check to separate class

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/codeowners.py

Add f5-distributed-cloud as tile without github team or username
https://github.com/DataDog/integrations-extras/pull/1561

Add f5-distributed-cloud as tile without github team or username

---

docs/developer/.scripts/33_render_status.py

Drop the manifest v2 migration status
Migration done and the validations do not allow manifests v1 anymore

Remove the manifest v2 progress

---

docs/developer/.scripts/33_render_status.py

Do not include non-python migration in the hatch migration progress.
They do not have a `tox` file to migrate. Some example:
- agent_metrics
- databricks

Exclude non-python checks from the hatch migration status

---

sqlserver/assets/configuration/spec.yaml
sqlserver/datadog_checks/sqlserver/data/conf.yaml.example

We no longer recommend using stored procedures to collect custom metrics. However, some users currently use stored procedures, so we don't want to vanish the examples all at once. 
Instead, we are updating documentation to remove mention of stored procedures; once that has deployed, we will merge this deprecation notice.

sqlserver: mark stored_procedure as deprecated

---

silk/assets/dashboards/silk_overview.json
silk/tests/docker/silk_metrics/metrics

This updates the Silk dashboard in a few ways:
- Allow filtering by template variables `silk_host`, `system_name`, and `system_id`
- Show the top 500 volumes instead of top 10

Update silk dashboard

---

kubernetes/assets/dashboards/kubernetes_jobs.json

change the aggregator function to `avg` instead of `sum` to get the proper number of pods attached to jobs or cronjobs.
fix the `Successful Job Pods` widget in the OOTB dashboard "Kubernetes Jobs and CronJobs Overview" linked to the `kubernetes` integration.

fix(kubernetes): return the proper number of job's pod

---

datadog_checks_dev/datadog_checks/dev/tooling/trello.py

This PR adds Open Telemetry team to the trello scripts, so they can be included in the next Agent release QA automatically.
Motivation
Update to the changes in the agent release process.

Add opentelemetry team to trello class

---

datadog_checks_downloader/tests/test_downloader.py

Temporarily skip offline downloader tests since they are failing after the v10 ceremony.
When the downloader executes, it also updates the `root.json` in `downloader/data/repo/metadata/current`. This also happens in tests for the downloader. After running the recent v10 ceremony, the `root.json` file has been updated on the S3 repository. However, the offline tests rely on a zipped file with dummy metadata generated during the v9 ceremony and expects the `root.json` to still be v9. For now, we will skip the offline tests until we can fix this behavior.
To fix the behavior, these two conditions should be met:
- Do not modify the state of `root.json` in tests in the first place. We should implement a way to change the `root.json` to the original value after a test is conducted, or some …

Skip offline downloader tests for now

---

datadog_checks_dev/pyproject.toml

Adds an upper bound to prevent tests from running under a pytest version that is currently broken for us.
pytest not running properly after update to 7.2.0 ([example](https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=116478&view=logs&jobId=e68def02-528b-569b-6f8b-ee3f97480a3a&j=8157d5c0-6574-55bb-ebb7-ea0affeefc23&t=576db4fb-ad6e-58ed-028c-734dacbb6401)).

Force pytest<7.2.0 to avoid test breakage

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py
datadog_checks_dev/datadog_checks/dev/tooling/testing.py
datadog_checks_dev/pyproject.toml

Add memray to the test suite. 
- https://github.com/bloomberg/memray
- https://github.com/bloomberg/pytest-memray
Note: only works on linux and MacOs and with py3
https://datadoghq.atlassian.net/browse/AITOOLS-26
First step for memory testing in the CI. 
Output example: 
```
ddev test --memray impala 
...
============================================================================================================================================================================ MEMRAY REPORT =============================================================================================================================================================================
Allocations results for tests/daemon/test_integration.py::test_daemon_check_integration_assert_metrics
📦 Total memory allocated: …
```

Add the memray option to the `test` command

---

.gitlab-ci.yml

Rebuild all images when the `.gitlab-ci.yaml` file is updated
We want to pick up changes to the jobs that happen in the 'script' section of the `.gitlab-ci.yaml` file
This change was never applied because of this limitation: https://github.com/DataDog/integrations-core/pull/12806

Rebuild images when ci file is updated

---

sqlserver/datadog_checks/sqlserver/connection.py

Fixes a type check error:
```
error: sqlserver:6342f67680de647e | (sqlserver.py:316) | Initialization exception 'NoneType' object has no attribute 'lower'
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/sqlserver/sqlserver.py", line 289, in initialize_connection
db_exists, context = self.connection.check_database()
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/sqlserver/connection.py", line 261, in check_database
db_exists, context = self._check_db_exists()
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/sqlserver/connection.py", line 397, in _check_db_exists
if database.lower() in self.existing_databases:
AttributeError: 'NoneType' object has no attribute 'lower' …
```

Fix exception thrown when database is null in config

---

ibm_i/datadog_checks/ibm_i/check.py
ibm_i/tests/conftest.py
ibm_i/tests/test_e2e.py
ibm_i/tox.ini

As part of adding e2e tests for the ibm_i integration, we change it to emit a CRITICAL service check in case we cannot connect to an IBM-I machine.
Part of work on this:
https://datadoghq.atlassian.net/browse/AI-1760

ibm_i integration produces CRITICAL service check if it cannot connect

---

linkerd/README.md

I added more information, that we only collect what is exposed by linkerd, since it is confusing some customers.
I also added that all the metrics ending with "_total" are appended by "count" by datadog : https://github.com/DataDog/integrations-core/blob/7585dad4f622339f87eed87ad15e2986d9025bde/linkerd/datadog_checks/linkerd/metrics.py#L123-L125 , since it can also lead to confusion.
https://datadog.zendesk.com/agent/tickets/835258
no

Update to the metric part

---

kubelet/datadog_checks/kubelet/prometheus.py

Ignore aberrant values (close to 18 EiB) for `kubernetes.memory.rss`.
Under some circumstances, the `memory.stat` cgroup file shows super high value for `total_rss` like for ex.:
```
/host/sys/fs/cgroup/memory/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod1cbe9fde_6ee9_445f_8f59_7298e66618f5.slice/cri-containerd-38fe097c37a933d8d2f5d3fe50e751bb64d3001e07217529349a9446a2944946.scope/memory.stat
```
```
cache 1622016
rss 1409024
rss_huge 0
shmem 0
mapped_file 159744
dirty 0
writeback 0
swap 0
pgpgin 231327950
pgpgout 231327210
pgfault 347344261
pgmajfault 75
inactive_anon 1404928
active_anon 4096
inactive_file 204800
active_file 1417216
unevictable 0
hierarchical_memory_limit 268435456
hierarchical_memsw_limit 9223372036854771712
total_cache 1622016
total_rss …
```

Ignore aberrant values for `kubernetes.memory.rss`

---

gunicorn/tests/compose/Dockerfile
gunicorn/tox.ini

- Remove old gunicorn environment and replace it with a more current one.
- Remove sources of unreproducibility (pinned Docker base image, removed `latest` env).
Failing tests in CI.
The reason for the failure on gunicorn 19.2 was the release of Python 3.11, which has deprecated `inspect.getargspec`, which apparently that version of gunicorn was using. Since we weren't pinning the Docker base image, we got Python 3.11 there as soon as it was released, causing the error.

Fix gunicorn test environments

---

postgres/datadog_checks/postgres/statements.py
postgres/tests/test_statements.py

We're moving the logic to the backend, and metrics is also allowing us to make tag lengths longer.

Remove postgres tag truncation for metrics

---

sqlserver/datadog_checks/sqlserver/statements.py

We're moving the logic to the backend, and metrics is also allowing us to make tag lengths longer.

Remove sqlserver tag truncation for metrics

---

mysql/datadog_checks/mysql/statements.py
mysql/tests/test_statements.py

We're moving the logic to the backend, and metrics is also allowing us to make tag lengths longer.

Remove mysql tag truncation for metrics

---

mysql/datadog_checks/mysql/activity.py

For known configuration issues, we want troubleshooting links to be the code-specific permanent URLs but I found one warning that had a generic troubleshooting url even though the specific permanent link exists: https://docs.datadoghq.com/database_monitoring/setup_mysql/troubleshooting#events-waits-current-not-enabled
This updates the message to include the correct specific link.

Fix non-specific troubleshooting link on explain_plan_procedure_missing configuration error

---

kafka_consumer/datadog_checks/kafka_consumer/new_kafka_consumer.py

Re-implements the kafka-python `_list_consumer_groups_send_request` [method](https://github.com/dpkp/kafka-python/blob/4d598055dab7da99e41bfcceffa8462b32931cdd/kafka/admin/client.py#L1107-L1120) to use the patched `_send_request_to_node` method to disable socket wakeup.
Support case
Adding onto https://github.com/DataDog/integrations-core/pull/13221

Disable socket wakeup when listing consumer groups and send request

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/snmp_tile/snmp_{check_name}/CHANGELOG.md
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/tile/{check_name}/CHANGELOG.md

Make sure that the CHANGELOG.md file is present when running `ddev create` against _all_ types of integrations
This was missing for SNMP and TILE type integrations but its required for all integrations to have a CHANGELOG.

Add the CHANGELOG.md template file to the new integration scaffolds

---

win32_event_log/README.md
win32_event_log/manifest.json

Updates the documentation to make it clear that config under `instances:` (collected as DD Events) are mutually exclusive to config under `logs:` (collected as DD Logs)
Users often confuse the 2 thinking both configs are needed or certain filter parameters get mixed in irrelevant sections of the configuration.
- Not sure how to preview the doc with tabs so I was not able to check how this would render

improve win32_event_log docs

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/pyproject.toml
gitlab/pyproject.toml
gitlab_runner/pyproject.toml
kube_dns/pyproject.toml
kubernetes_state/pyproject.toml

Backport of https://github.com/DataDog/integrations-core/pull/13262
https://github.com/DataDog/image-vuln-scans/issues/547
Will be shipped with the agent 7.40.1 as discussed with Brian (Kacper being OOO)

Bump protobuf version to 3.20.1

---

kafka/datadog_checks/kafka/data/metrics.yaml
kafka/metadata.csv
kafka/tests/common.py

In [KIP-272](https://cwiki.apache.org/confluence/display/KAFKA/KIP-272%3A+Add+API+version+tag+to+broker%27s+RequestsPerSec+metric), all `RequestsPerSec` metric bean names were changed from 
`kafka.network:type=RequestMetrics,name=RequestsPerSec,request={Produce|FetchConsumer|FetchFollower|...}` 
to 
`kafka.network:type=RequestMetrics,name=RequestsPerSec,request={Produce|FetchConsumer|FetchFollower|...},version=INTEGER`
This caused our current `RequestsPerSec` metrics to no longer be collected. This wasn't discovered until recently because our current e2e environment doesn't collect the missing metrics in the first place. 
This PR updates the bean name to be a regex and allow it to collect the version number if it exists, but retains backwards compatibility with the original style.
Support …

Fix kafka request metrics due to KIP 272

---

gitlab/CHANGELOG.md
gitlab/datadog_checks/gitlab/__about__.py
gitlab_runner/CHANGELOG.md
gitlab_runner/datadog_checks/gitlab_runner/__about__.py
kube_dns/CHANGELOG.md
kube_dns/datadog_checks/kube_dns/__about__.py
kubernetes_state/CHANGELOG.md
kubernetes_state/datadog_checks/kubernetes_state/__about__.py
requirements-agent-release.txt

Update the changelogs for gitlab, gitlab_runner, kube_dns and kubernetes_state
Those integrations were released for agent 7.40 and 7.41. See: 
- https://github.com/DataDog/integrations-core/pull/13269
- https://github.com/DataDog/integrations-core/pull/13270
- https://github.com/DataDog/integrations-core/pull/13271
- https://github.com/DataDog/integrations-core/pull/13275

Update the changelogs

---

.azure-pipelines/scripts/sap_hana/linux/55_docker_login.sh
sap_hana/datadog_checks/sap_hana/queries.py

Stop using the password and use an access token to log in docker hub.
I added the token to our variable group.
Password authentication is now disabled. 
We have to be logged in to get sap hana images. More info [here](https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html)
Worked here https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=117732&view=logs&j=b9b61b1e-e7ad-5a75-8bb3-f1445ef55317&t=4df15724-c42a-51be-f807-8fc596bf2a13

Use an access token to log in dockerhub

---

.azure-pipelines/templates/set-up-integrations.yml
sap_hana/tests/common.py

Set the DOCKER_ACCESS_TOKEN as a secret.
Seems like I forgot to set it back to a secret in our config and add it in this file. 
Worked [here](https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=117799&view=logs&j=910f82a4-622d-5ace-f877-8b75c045486c&t=8eb50bb1-e140-5af2-ec58-7d4b906239a3)

Set the DOCKER_ACCESS_TOKEN as a secret

---

.github/workflows/validations.yaml

Run the manifest validation before the dashboards validation.
[Dashboards are retrieved](https://github.com/DataDog/integrations-core/blob/master/datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/dashboards.py#L95) from the manifest file. If the manifest is broken, the dashboards validation will fail with a cryptic and misleading message. Example [here](https://github.com/DataDog/integrations-extras/actions/runs/3395812713/jobs/5646160209)

Validate the manifest file before the dashboards in the CI

---

zk/datadog_checks/zk/zk.py

This PR changes METADATA_VERSION_PATTERN in a way that it will be compatible with alternative zookeeper implementations with their own versioning.
For example with clickhouse-keeper line that contains version information differs a bit with original zookeeper:
```
ClickHouse Keeper version: v22.9.1.15416-testing-6156f9cd99b5efd5fe1eeab391571deb4176e2af
```
vs
```
Zookeeper version: 3.2.2--1, built on 03/16/2010 07:31 GMT
```
Desire to use this integration with alternative zookeeper implementations, for example https://clickhouse.com/docs/en/operations/clickhouse-keeper

Make version parsing more flexible to increase compatibility

---

datadog_checks_dev/datadog_checks/dev/tooling/constants.py
sonarqube/hatch.toml

Sonarqube is listed as py2 compatible but does not have py2 tests.
Consider hatch.toml file in testable files for PR tests to run

Add py2 tests for sonarqube

---

.github/workflows/release-ddev.yml

Use a specific token to upload ddev to Pypi
https://datadoghq.atlassian.net/browse/AITOOLS-86
We were using the same token for datadog_checks_dev: https://github.com/DataDog/integrations-core/blob/master/.github/workflows/release-dev.yml
I've already added the token to the secrets

Use the ddev token to publish ddev to PyPi

---

disk/datadog_checks/disk/disk.py
disk/tests/test_unit.py

This PR allows device-specific tags declared in `device_tag_re` to apply to all metrics that already tag by `device_name` or `device`. 
Originally this was skipped for latency metrics (`read_time`, `write_time`, `read_time_pct`, and `write_time_pct`).
Customer request.

Allow device-specific tags for all device-specific metrics

---

databricks/README.md

We're deprecating the install_script.sh Linux install script in favor of install_script_agent6.sh and install_script_agent7.sh which are published from https://github.com/DataDog/agent-linux-install-script. This PR reflects this change for the Databricks integration README.

[databricks] Use the new install_script_agent7.sh in README

---

datadog_checks_dev/datadog_checks/dev/tooling/testing.py

Allow `bench` test env as a benchmark env using hatch.
- Bench tests are not running for integrations migrated to hatch 🙈. Example [here](https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=118518&view=logs&jobId=70a237a0-2c52-52f8-23f1-657d682c7ecf&j=70a237a0-2c52-52f8-23f1-657d682c7ecf&t=24c0e73f-1122-5cb1-40ea-3a63edc6dac8) with vault on master 
- `bench` is also the bench env name used with [tox](https://github.com/DataDog/integrations-core/blob/master/datadog_checks_dev/datadog_checks/dev/tooling/testing.py#L211-L212)

Allow `bench` as an env name for running benchmarks with hatch

---

mysql/README.md

One step was out of order and mysql versions needed to be clearer.  New steps were tested on MySQL 8.0.30 on Mac (m1) and Datadog Agent status collector is green afterwards.

Clarify mysql config steps

---

kubernetes/assets/dashboards/kubernetes_clusters.json
kubernetes/assets/dashboards/kubernetes_pods.json

* Replaces `kubernetes_cluster` tag with `kube_cluster_name` tag as the former does not exist, while the latter is the now official Cluster tag for aggregation
* Customer reached out to mention that our OOTB dashboards are using `kubernetes_cluster` which is a deprecated/removed tag

Replaces kubernetes_cluster tag by kube_cluster_name

---

oracle/datadog_checks/oracle/oracle.py
oracle/tests/test_custom_queries.py
oracle/tests/test_unit.py

`metric_prefix` is a deprecated config option that would attach a metric prefix to custom queries. In these custom queries, specific columns may be skipped, although currently any custom metric prefix will still be attempted to be added to the skipped columns. This PR will stop attempting to append a custom metric prefix to skipped columns.
Example where this may happen:
```
init_config:
instances:
...
custom_queries:
- metric_prefix: custom_metric_prefix
query: |
select foo, bar, baz, etc;
columns:
- {}
- name: metric1
type: gauge
- name: tag1
type: tag
- name: metric2
type: count
tags:
- tester:oracle
```
This will result in the error message:
```
Check Initialization Errors
===========================
oracle (3.5.0)
--------------
instance 0:
could not invoke 'oracle' …
```

Skip empty columns when metric_prefix is used for custom queries

---

.gitlab-ci.yml

This PR modifies the bash script to send slack messages to depend on the `codesync` username and not the `gitsync` username. This is because the repo is now synchronised with CodeSync.

[CIREL] Migrate repo synchronisation from gitsync to codesync

---

oracle/tests/test_custom_queries.py

This PR rewrites some tests for Oracle integration's custom query behavior to be less dependent on private functions.
🧹 🧹

Refactor oracle tests

---

kafka_consumer/datadog_checks/kafka_consumer/new_kafka_consumer.py

This PR disables socket wakeup when sending requests to the kafka-python library we use for the kafka_consumer check. Since our check runs in a single thread, it doesn't need to do a socket wakeup. This was also causing issues for set ups with high number of brokers per cluster:
```
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/kafka_consumer/new_kafka_consumer.py", line 64, in check
self._get_consumer_offsets()
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/kafka_consumer/new_kafka_consumer.py", line 363, in _get_consumer_offsets
list_groups_future = self.kafka_client._list_consumer_groups_send_request(broker.nodeId)
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/kafka/admin/client.py", line 1116, in …
```

Disable socket wakeup when sending requests

---

.github/CODEOWNERS

This updates the CODEOWNERS file to remove `@DataDog/agent-core` from `/datadog_checks_base`, and updates the owner of `conf.yaml.default` to  `@DataDog/agent-metrics-logs`.
`@DataDog/agent-core`  no longer exists.

Updated CODEOWNERS to remove agent-core.

---

spark/datadog_checks/spark/constants.py

Updates regex used for extracting spark structured streaming metrics to allow punctuation characters in the query name.

Allow punctuation marks in query name when publishing spark structured streaming metrics

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py
datadog_checks_dev/datadog_checks/dev/tooling/testing.py

Add a new option to the `test` command to show the memray report. By default, hide them.
The memray reports can be quite verbose (see [this PR description](https://github.com/DataDog/integrations-core/pull/13160) with an example) and are displayed by default. This is a lot of text if we have lots of tests to run. 
This does not prevent memray to run. If a memory test fail, you will still get the info about this specific test.

Add an option to show the memray report

---

datadog_checks_dev/datadog_checks/dev/plugin/pytest.py

Add a new dummy `--memray` option to the pytest plugin.
- Memray does not support python 2
- In [this PR](https://github.com/DataDog/integrations-core/pull/13350), I'm enabling memray on the CI. The problem is that the pytest options we define are used for each environment, including the py2 ones, which makes the CI fail because the option is not know for py2 environments.
- I'm adding a fake option that just throws a warning so the tests do not fail. This way we can run memray on py3 environments.
Thanks to @alopezz for this idea!
Output:
```
╰─❯ ddev test --memray eks_fargate                                                                                                                                                                   ─╯
Running tests for `eks_fargate` …
```

Add a dummy --memray option to the pytest plugin

---

datadog_checks_dev/datadog_checks/dev/plugin/pytest.py

Same as https://github.com/DataDog/integrations-core/pull/13352, but for the `--hide-memray-summary` option.
Same as https://github.com/DataDog/integrations-core/pull/13352 and relates to https://github.com/DataDog/integrations-core/pull/13351
Demo without the summary: 
```
╰─❯ ddev test --memray eks_fargate                                                                                                                                                                   ─╯
Running tests for `eks_fargate`
-------------------------------
───────────────────────────────────────────────────────────────────────────────────────────────── py27 ─────────────────────────────────────────────────────────────────────────────────────────────────
Finished checking dependencies
cmd [1] | pytest -v …
```

Add a dummy --hide-memray-summary option to the pytest plugin

---

eks_fargate/README.md

This PR adds the `shareProcessNamespace` parameter to the spec for the agent container. Running in the host's or the application's pid namespace is required for origin detection to work with cgroup v2.
Cgroup v2 support for origin detection has been merged into the Trace Agent, but it is necessary for the trace agent to be run in the host's or the application's PID namespace for it to work. We want this to be working by default, so this change is necessary.

README.md: add shareProcessNamespace parameter to agent container spec

---

ibm_was/metadata.csv
ibm_was/tests/common.py
ibm_was/tests/test_unit.py

It turns out we already collect a metric from IBM WAS but it's not in `metadata.csv`. This PR adds it.
I noticed there are a couple more such metrics, I could add them in a follow-up PR if we decide that's a good idea.
https://datadoghq.atlassian.net/browse/AI-2672

Add thread_pools.percent_used to metadata.csv

---

ibm_was/datadog_checks/ibm_was/ibm_was.py

Log that we collect stats only when we in fact do collect them.
Small follow-up to #13323

Log that we collect stats only when we in fact do collect them.

---

vault/hatch.toml

Fixes vault benchmark test by setting `DDEV_SKIP_GENERIC_TAGS_CHECK` on the benchmark environment.
Tests have been failing on master for a bit.

Fix vault benchmark test

---

.github/workflows/config/labeler.yml

Updates labeler filter to label release PRs with `changelog/no-changelog` and `release`.
bugfix

Fix labeler for releases

---

cisco_aci/datadog_checks/cisco_aci/api.py
datadog_checks_base/datadog_checks/base/utils/http.py
snowflake/datadog_checks/snowflake/check.py
tls/datadog_checks/tls/tls_local.py
tls/datadog_checks/tls/tls_remote.py
vault/tests/docker/provider/run/main.py

Remove parameter that will be soon deprecated by cryptography.

Remove default_backend parameter from cryptography calls.

---

datadog_checks_dev/datadog_checks/dev/tooling/git.py
datadog_checks_dev/tests/tooling/test_git.py

Makes `git_show_file` (used to get the contents of a file on an arbitrary git ref) raise when the git command fails, which is normally because:
- The file doesn't exist on the given ref.
- The given ref doesn't exist.
This function was returning an empty string on failure, which means we can't tell whether the file contents can't be retrieved (e.g. if it doesn't exist) or whether the file was empty originally.
I wanted to use this function for [AITOOLS-60](https://datadoghq.atlassian.net/browse/AITOOLS-60), and this behavior would help.

Make `git_show_file` raise when git fails

---

datadog_checks_dev/datadog_checks/dev/tooling/trello.py

This PR fixes typo in the platform-integrations label name, which caused QA card generation script to be unable to properly create cards.

Fix typo in platfrom-integrations team name

---

.github/CODEOWNERS

remove SIT ownership of workflows and CI files.
SIT review does not seem necessary for every PR touching any of these files.
See https://datadoghq.atlassian.net/browse/SINT-878

remove SIT ownership of workflows and CI files

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/licenses.py

Adds the ability to parse `' and/or '` seperator for license validator
https://github.com/DataDog/integrations-core/pull/13298/files
License Format: (Apache and/or UPL)
https://pypi.org/project/oracledb/

add licences for python-oracledb

---

kube_proxy/datadog_checks/__init__.py

Add the `__path__` variable to the kube_proxy integration. 
- It should be there, see https://github.com/DataDog/integrations-core/blob/master/datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/%7Bcheck_name%7D/datadog_checks/__init__.py
- Revealed by [this PR](https://github.com/DataDog/integrations-core/pull/13366)
- CI is failing, example [here](https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=119742&view=logs&jobId=026f262d-50fd-5ef9-347c-fe645c0b84ea&j=026f262d-50fd-5ef9-347c-fe645c0b84ea&t=2becebdc-a330-5bc4-f5a3-595047c5e91b)

Add the missing `__path__` variable

---

kubernetes/assets/dashboards/kubernetes_nodes.json

Replace deprecated requests and capacity metrics with cluster-agent metrics.
Cluster-agent have moved metrics names and deprecates kubernetes.* so dashboards needs to be updated accordingly.

Fix requests/capacity widgets on kubernetes nodes dashboard

---

kube_apiserver_metrics/hatch.toml
kube_apiserver_metrics/tests/conftest.py
kube_apiserver_metrics/tests/test_e2e.py

Add a minimal `kube_apiserver_metrics` E2E test to ensure the check is able to run.
Motivation
Review checklist (to be filled by reviewers)
Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
PR title must be written as a CHANGELOG entry [(see why)](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title)
Files changes must correspond to the primary purpose of the PR as described in the title (small unrelated changes should have their own PR)
PR must have changelog/ and integration/ labels attached

minimal e2e test kube_apiserver_metrics

---

kube_dns/hatch.toml
kube_dns/tests/conftest.py
kube_dns/tests/test_e2e.py

Add a minimal `kube_dns` E2E test to ensure the check is able to run.
Motivation
Review checklist (to be filled by reviewers)
Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
PR title must be written as a CHANGELOG entry [(see why)](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title)
Files changes must correspond to the primary purpose of the PR as described in the title (small unrelated changes should have their own PR)
PR must have changelog/ and integration/ labels attached

minimal e2e test kube_dns

---

argocd/datadog_checks/argocd/check.py
argocd/tests/common.py
argocd/tests/test_argocd.py

Fix an issue in which when other params are being passed into the instance, the check would throw an error. I originally iterated over the instances expecting there to be endpoints only when setting up custom transformers. Also added a more robust test instance that would reflect what people would use if they would use this check to the tests.

Fix logic when other params are passed into instances

---

postgres/assets/configuration/spec.yaml
postgres/datadog_checks/postgres/config_models/instance.py
postgres/datadog_checks/postgres/data/conf.yaml.example
postgres/datadog_checks/postgres/statements.py
postgres/datadog_checks/postgres/util.py
postgres/tests/test_statements.py

Before this change, we had a hardcoded limit of 10000 rows on the query we used to retrieve query stats from `pg_stat_statements`. This is fine in most cases as our [setup docs](https://docs.datadoghq.com/database_monitoring/setup_postgres/selfhosted?tab=postgres10) recommend setting `pg_stat_statements.max` to 10000 in the postgres configuration. However, that setting is optional and it's possible for customers to have a higher value for `pg_stat_statements.max`. In such cases, the integration's assumption that the full set of queries was captured on every check execution was broken as some queries could fall in and out of the "window" of 10000 rows imposed by the `LIMIT 10000`. When this would happen, a query having fallen out of the window and coming back in would be reported as if the …

Fix inflated query metrics when pg_stat_statements.max is set above 10k

---

sqlserver/datadog_checks/sqlserver/connection.py

Reverts DataDog/integrations-core#12882
While the original fix addresses the warning, it actually breaks the integration for customers using autodiscovery. This is because it changes the initialization behavior from a log to an initialization error.
On this line, the DB will never exist: https://github.com/DataDog/integrations-core/blob/d64e5bb0128a024d139f7a1021d8521a36650baf/sqlserver/datadog_checks/sqlserver/sqlserver.py#L287 because `self.connection.check_database()` called with no database configured results in a database of `None`. The exception is caught here and ignored: https://github.com/DataDog/integrations-core/blob/d64e5bb0128a024d139f7a1021d8521a36650baf/sqlserver/datadog_checks/sqlserver/sqlserver.py#L313-L314
With my change in the original PR, the DB `None` does not exist, …

Revert "Fix exception thrown when database is null in config"

---

mysql/datadog_checks/mysql/statement_samples.py

Adds to debug logging in mysql statement samples job:
- adds the checkpoint we are using to filter statements
- adds a log just before we fetch all rows, with datapoint about window function usage
We have a curious [support issue](https://datadoghq.atlassian.net/browse/SDBM-296) for MySQL running on Aurora. After a failover, we report no rows available in the events statements tables, which prevents us from collecting any query samples. Restarting the agent resolves this. It's clear that we are getting into the `_get_new_events_statements` function, and incorrectly reporting that the events statements tables have no rows; but it's not clear what is causing the incorrect row counts to be reported.

Add to debug logging in mysql statement samples job

---

snmp/assets/configuration/spec.yaml
snmp/datadog_checks/snmp/data/conf.yaml.example

`service` was added in this [PR](https://github.com/DataDog/integrations-core/pull/9766) but it's not a valid field of the snmp integration

Remove invalid 'service' field in snmp example config

---

ddev/src/ddev/cli/config/__init__.py
ddev/src/ddev/cli/status/__init__.py
ddev/src/ddev/cli/terminal.py

https://clig.dev/#the-basics
> **Send output to `stdout`.** The primary output for your command should go to `stdout`. Anything that is machine readable should also go to `stdout`—this is where piping sends things by default.
>
> **Send messaging to `stderr`.** Log messages, errors, and so on should all be sent to `stderr`. This means that when commands are piped together, these messages are displayed to the user and not fed into the next command.

Output non-critical information to stderr

---

datadog_checks_dev/pyproject.toml

Stop forcing pytest version to <7.2.0.
- pytest 7.2.0 dropped the `py` dependency
- pytest-benchmark required this dependency but they forgot to add it to their requirements. They added it back in the version 4.0.0, which dropped py2 so we do not use it so the tests fail because of this missing library
- We opened a PR to force the version https://github.com/DataDog/integrations-core/pull/13198
I need pytest>=7.2.0 to update the pytest-memray plugin to 1.4.0 (changelog [here](https://pytest-memray.readthedocs.io/en/latest/news.html#v1-4-0-2022-12-02)) that requires it because they added a way to run memray only on tests that really use it. It will allow us to speed up the test suite and get rid of [this PR](https://github.com/DataDog/integrations-core/pull/13350)

Do not force pytest version

---

kubernetes/assets/dashboards/kubernetes_clusters.json

Remove comparaison between disk info and replicaset_ready state to display disk read/write per replicaset
Fix graph metadata to correct title disk and not network.
Doesn't makes sens to substract disk informations and number of ready replicaset.
And title metadata was mentioning network while widget and metric is related to disk.

Fix disk read/write widgets on kubernetes cluster dashboard

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py
datadog_checks_dev/pyproject.toml

Bump pytest-memray version to >= 1.4.0
- pytest-memray 1.4.0 now starts the memray tracker only on tests that require it (that use the memray fixtures) by default. Changelog [here](https://github.com/bloomberg/pytest-memray/releases/tag/1.4.0)
- To run memray on all the tests, we need to explicitely pass the `--memray` option. This mean that memray will be enabled by default on the CI, only for the tests that require it, without any modification in the pipeline itself.
This PR requires [this one](https://github.com/DataDog/integrations-core/pull/13461) to be merged first
Thanks to this, we can get rid of [this PR](https://github.com/DataDog/integrations-core/pull/13350). Also, we do not have a global overhead anymore. Only tests that require memray are slightly slower than they would be …

Bump pytest-memray version

---

mongo/datadog_checks/mongo/mongo.py
redisdb/tests/test_default.py
varnish/datadog_checks/varnish/varnish.py
varnish/tests/test_unit.py
zk/datadog_checks/zk/zk.py
zk/tests/common.py

Move from `distuils.version` to `packaging.version`.
- `distuils.version` classes are deprectaed
- https://datadoghq.atlassian.net/browse/AITOOLS-95

Stop using deprecated distutils.version classes

---

active_directory/datadog_checks/active_directory/data/conf.yaml.example
aspdotnet/datadog_checks/aspdotnet/data/conf.yaml.example
datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/common/perf_counters.yaml
dotnetclr/datadog_checks/dotnetclr/data/conf.yaml.example
exchange_server/datadog_checks/exchange_server/data/conf.yaml.example
hyperv/datadog_checks/hyperv/data/conf.yaml.example
iis/datadog_checks/iis/data/conf.yaml.example
windows_performance_counters/datadog_checks/windows_performance_counters/data/conf.yaml.example

Provides and documents `include_fast` as new multi-instance counter configuration. It is complimentary to https://github.com/DataDog/integrations-core/pull/13243 PR.

Add supporting configuration template for Multi-instance performance counters

---

datadog_checks_dev/datadog_checks/dev/plugin/pytest.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py
datadog_checks_dev/datadog_checks/dev/tooling/testing.py

Drop the --memray-show-report option
Following [this PR](https://github.com/DataDog/integrations-core/pull/13462) and the new pytest-memray version, we do not need to explicitly enable memray for the unit tests and the report will be hidden by default. Manually running them and get the reports can still be useful though. To do that we would run `ddev test impala --memray` for instance to get the reports, but in this case there's no need to keep the old `--hide-memray-summary`.

Remove the --memray-show-report option

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/test.py

Re-raise the exception if we do not skip the failed environments.
- [This PR](https://github.com/DataDog/integrations-core/pull/13443) broke the sqlserver tests: https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=120923&view=logs&jobId=1844037c-5a79-57cd-fd15-36c50f4dfdba&j=1844037c-5a79-57cd-fd15-36c50f4dfdba&t=67bd1e36-418d-51b1-65b1-619a0984e1b6
- It fails because I forgot to stop the program in case of an error and the `stop` method fails with docker environments. I tested it with the `iis` integration on my laptop, which does not do anything in the `stop` method.
It also means that the `sqlserver` tests are not running completely because we have some linux tests after the windows one that stops the execution. Example here: …

Re-raise the exception when the environment failed to start

---

docs/developer/guidelines/dashboards.md

Add a tip in the doc to mention OOTB dashboards have a stable URL without their ID.
I did not know this was a thing and this is very useful when we have several dashboards in the same integration and we would like to mention and link them in the dashboard. 
For instance, those two links lead to the same OOTB dashboard for us1:
- https://app.datadoghq.com/dash/integration/15/redis---overview
- https://app.datadoghq.com/dash/integration/redis
For eu:
- https://app.datadoghq.eu/dash/integration/2/redis---overview
- https://app.datadoghq.eu/dash/integration/redis
With the manifest: 
```
"dashboards": {
"redis": "assets/dashboards/overview.json"
},
```
Thanks to that, we can have this kind of link in our dashboard:
```md
More info on [this dashboard](/dash/integration/redis)
```
This is going …

Mention the stable URLs of OOTB dashboards

---

istio/assets/configuration/spec.yaml
istio/datadog_checks/istio/data/auto_conf.yaml
istio/datadog_checks/istio/data/conf.yaml.example

Updates the port in the Istio auto_conf.yaml to port 15020, the merged telemetry endpoint: [Istio docs ](https://istio.io/latest/docs/ops/deployment/requirements/#server-first-protocols:~:text=No-,15020,-HTTP)
Customer request: https://github.com/DataDog/integrations-core/issues/13047
N/A

Add port for merged telemetry endpoint in Istio auto_conf

---

datadog_checks_dev/pyproject.toml

Force the semver version to >=2.13.0
Attempt to fix https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=121079&view=logs&j=40b3f23d-1644-5d89-acd8-67daa1a59c69&t=5f83278f-38f4-50d4-bb3f-a8d7354c3b39&l=460, it happens sometimes, not always and this seems to work consistently on my machine.

Force the semver version to >=2.13.0

---

system_core/datadog_checks/system_core/system_core.py
system_core/metadata.csv
system_core/tests/common.py
system_core/tests/test_system_core.py

Adds CPU Core frequency aka ClockSpeed metric.
AGENT-8778

Adds `system.core.frequency` metric

---

system_core/datadog_checks/system_core/system_core.py
system_core/tests/common.py
system_core/tests/test_system_core.py

Small change in logic in how we collect number of cpu cores. We used to count the length of CPU times, but there's a built in function in psutil that returns the count.
Was initially part of #[13349](https://github.com/DataDog/integrations-core/pull/13349) but it was better to split them up.

Collect the number of cpu cores using `psutil.cpu_count()`

---

postgres/tests/test_deadlock.py

Excludes flaky E2E tests for Postgres' deadlock metrics which is blocking PRs.

Exclude flaky E2E deadlock tests 

---

sqlserver/datadog_checks/sqlserver/activity.py
sqlserver/datadog_checks/sqlserver/statements.py
sqlserver/datadog_checks/sqlserver/utils.py
sqlserver/tests/test_activity.py
sqlserver/tests/test_statements.py

Adds support to collect a `procedure_name` for query metrics (and events) so we can tie query execution statistics for particular queries that execute in the context of a procedure back to said stored proc. 
This was requested by a customer who after upgrading to 7.40, which contained this fix https://github.com/DataDog/integrations-core/pull/12613, was unable to easily lookup from which stored procedure a particular query was executing within

Add procedure name on query metrics/events

---

sqlserver/datadog_checks/sqlserver/connection.py
sqlserver/datadog_checks/sqlserver/connection_errors.py
sqlserver/datadog_checks/sqlserver/metrics.py
sqlserver/datadog_checks/sqlserver/sqlserver.py
sqlserver/tests/test_connection.py
sqlserver/tests/test_integration.py

Adds the following:
1. Support for reporting agent errors on common sqlserver connection issues. This should help reduce integration setup friction for customers.
2. Updates the default drivers for each connectors so customers will no longer use old/out dated drivers by default
`adoprovider` connector -> `'MSOLEDBSQL'`
`odbc` connector -> `'{ODBC Driver 18 for SQL Server}'`
The updated agent error formatting results in this error messages like this showing up in the agent status when there are connection issues.
```
Error: Unable to connect to SQL Server, see https://docs.datadoghq.com/database_monitoring/setup_sql_server/troubleshooting#login-failed-for-user for more details on how to debug this issue. TCP-connection(OK), Exception: ProgrammingError('42000', "[42000] [FreeTDS][SQL …
```

Add well formatted agent errors on common connection issues for SQL Server

---

datadog_checks_dev/datadog_checks/dev/tooling/trello.py

agent-core team does not exist any more and current QA generation script fails on trying to pull team members from GH. This PR addresses the problem by removing the core team from QA scripting.

core team removed from trello class

---

kubernetes_state_core/assets/configuration/spec.yaml
kubernetes_state_core/datadog_checks/kubernetes_state_core/data/conf.yaml.example

Document the new `annotations_as_tags` parameter introduced in the KSM core check by DataDog/datadog-agent#14327.
Keep doc up-to-date.

Document the new `annotations_as_tags` parameter of the KSM core check

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/create.py
datadog_checks_dev/datadog_checks/dev/tooling/config.py
datadog_checks_dev/datadog_checks/dev/tooling/constants.py
datadog_checks_dev/datadog_checks/dev/tooling/create.py

Update the name of the integrations repo to reflect its new name.

Update integrations repo name

---

datadog_checks_dev/datadog_checks/dev/plugin/hatch/environment_collector.py

Match https://github.com/DataDog/integrations-core/blob/master/datadog_checks_dev/datadog_checks/dev/plugin/tox.py (which will soon be removed)

Fix style deps

---

cloudera/assets/configuration/spec.yaml
cloudera/datadog_checks/cloudera/api_client_factory.py
cloudera/datadog_checks/cloudera/api_client_v7.py
cloudera/datadog_checks/cloudera/config_models/defaults.py
cloudera/datadog_checks/cloudera/config_models/instance.py
cloudera/tests/conftest.py
cloudera/tests/test_integration.py

Run cloudera manager requests in parallel

---

journald/README.md

Document new advanced feature now that 7.41 is available: using `config_id` to identify multiple instances of the same tailer.  
Docs update

Update journald readme to include `config_id`

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/license_headers.py
datadog_checks_dev/datadog_checks/dev/tooling/license_headers.py
datadog_checks_dev/pyproject.toml
datadog_checks_dev/tests/tooling/test_license_headers.py

Makes `ddev validate license-header` honor gitignore files.
https://github.com/DataDog/integrations-core/pull/13417#discussion_r1035095161
The implementation doesn't support all possible combinations of gitignore files that may appear at different levels. In particular, a negation (`!`) pattern won't re-include patterns excluded by gitignore files found in parents. Implementing this functionality properly would add significant complexity, which is not worth it since we barely use that pattern at all, and the places where I've found it used, it doesn't concern files that would require license header validation.

Make `ddev validate license-header` honor gitignore files

---

terraform/README.md

Adds a header and section for the example monitor that's provided.
This is to make the section more easily discoverable, and linkable from other pages in the docs. See DOCS-3364 for more details.

(DOCS-3364) Add header for monitor example in docs

---

mongo/datadog_checks/mongo/mongo.py
mongo/tests/test_unit.py

When a replica state is in the [recovering state](https://www.mongodb.com/docs/manual/reference/replica-states/#mongodb-replstate-replstate.RECOVERING), it should not be ready to accept any reads. Originally, we would try to get the [list of databases](https://github.com/mongodb/mongo-python-driver/blob/4.2.0/pymongo/mongo_client.py#L1821-L1839), which would result the following error in the Agent:
```
Error: node is recovering, full error: {'ok': 0.0, 'errmsg': 'node is recovering', 'code': 13436, 'codeName': 'NotPrimaryOrSecondary'}
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 1116, in run
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/mongo/mon …
```

Skip checking database names when replica is recovering

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/license_headers.py
datadog_checks_dev/datadog_checks/dev/tooling/license_headers.py
datadog_checks_dev/tests/tooling/test_license_headers.py

Adds autofix functionality to `ddev validate license-headers`.
Part of [AITOOLS-60](https://datadoghq.atlassian.net/browse/AITOOLS-60).
This required changing how we deal with the case where the license header is missing in the original file:
- _Any_ header added to an existing file that didn't have a header is fine and passes validation.
- I decided against trying to auto-fix for this case. We can't just stamp the current license header (with the current year) because the year must match the year the file was first created. I didn't think it was worth going down the rabbit hole of figuring out the original year from git and generate a license dynamically from that.

Add `--fix` flag to `ddev validate license-headers` for automatically fixing errors

---

postgres/assets/configuration/spec.yaml
postgres/datadog_checks/postgres/config_models/instance.py
postgres/datadog_checks/postgres/data/conf.yaml.example
postgres/datadog_checks/postgres/statements.py

Adds an option (hidden) to enable distribution metrics for query text length from pg_stat_statements. 
The purpose of this metric was to bring greater visibility into our integration to help with support cases. However, we found that there was a significant jump in agent CPU usage in the latest release candidate (7.42) from ~11% to ~40%.
We utilized APM's profiler to narrow down CPU time and found that the histogram was the clear outlier, roughly spending ~30-40% of it's time just emitting these metrics for **each** row, which can be in the 1000s.
Afterwards, we created an agent build without these metrics and the CPU utilization decreased.

Add option to enable distribution metrics for query text length from pg_stat_statements

---

vsphere/README.md

Fixes the list of events the integration collects in the readme.
The docs were incorrect regarding the events the integration collects. We do have an event [filter](https://github.com/DataDog/integrations-core/blob/master/vsphere/datadog_checks/vsphere/event.py#L16-L34) but the specific event messages listed are actually [excluded](https://github.com/DataDog/integrations-core/blob/master/vsphere/datadog_checks/vsphere/event.py#L66-L70) instead of included. For example, we collect all TaskEvents but filter out some such as `"Initialize powering On"` since we already collect `VmPoweredOnEvent`.

Fix collected event docs

---

kube_dns/datadog_checks/kube_dns/kube_dns.py
kube_metrics_server/datadog_checks/kube_metrics_server/kube_metrics_server.py
kube_proxy/datadog_checks/kube_proxy/kube_proxy.py

Attempts to fix a bug from https://github.com/DataDog/integrations-core/pull/10668; the default health check urls for `kube_dns`, `kube_proxy`, and `kube_metrics_server` weren't being set so the `<integration>.up` service checks were missing unless the health url was manually specified.
Example yaml config
```yaml
ad_identifiers:
- kube-proxy
init_config:
instances:
- prometheus_url: http://%%host%%:10249/metrics
```
Example check run
```
=== Service Checks ===
[
...
{
"check": "kubeproxy.up",
"host_name": "xxx",
"timestamp": 1671742559,
"status": 0,
"message": "",
"tags": [
"image_id:<image-id>,
"image_name:k8s.gcr.io/kube-proxy",
"image_tag:v1.24.0",
"kube_container_name:kube-proxy",
"kube_daemon_set:kube-proxy",
"kube_namespace:kube-system",
"kube_ownerref_kind:daemonset", …
```

Fix setting of default health URL for kube_dns, kube_proxy, kube_metrics_server health checks

---

datadog_checks_base/datadog_checks/base/utils/__init__.py

Add new config option `integration_profiling` which enables [profiling](https://docs.datadoghq.com/profiler/enabling/python/#usage) of python integrations.
This has proven valuable several times already while troubleshooting performance issues so we're adding it as an option to have it available by default without requiring a custom build.

Add option to enable profiling of Python integrations

---

ibm_mq/datadog_checks/ibm_mq/config.py
ibm_mq/tests/test_ibm_mq_unit.py

Customer noticed some connection errors over time, but they enabled the `queue_manager_process` option and thus are relatively immune to IBM MQ's memory leak

Prevent unnecessary non-SSL connection attempts

---

datadog_checks_base/tests/base/utils/test_tracing.py
openstack_controller/datadog_checks/openstack_controller/openstack_controller.py

Remove the `@traced` decorator as it was redundant and used only by the openstack integration. All integrations already have optional tracing by default via the `@traced_class` decorator on the common base class `AgentCheck`.
Simplify integration tracing. This is part of an effort to improve integration tracing instrumentation. See https://github.com/DataDog/integrations-core/pull/13579.

openstack remove redundant tracing

---

datadog_checks_base/datadog_checks/base/utils/db/utils.py
datadog_checks_base/datadog_checks/base/utils/tracing.py
datadog_checks_base/tests/base/utils/test_tracing.py

Follow-up to https://github.com/DataDog/integrations-core/pull/13576, update the integrations tracing naming scheme to ensure all integrations appear under a single service, matching the name of the service used for profiling. This enables better linking between APM & profiling data, specifically the "Code Hotspots" feature. 
Since all integrations are now reporting under a single service, the resource name is updated to refer only to the integration name in order to enable us to differentiate reporting from the different integrations. They are all visible in the resource list:
Improve the tracing & profiling experience for python integrations.

Update integration tracing naming scheme

---

datadog_checks_base/datadog_checks/base/utils/db/utils.py
datadog_checks_base/datadog_checks/base/utils/tracing.py
datadog_checks_base/tests/base/utils/test_tracing.py

When `integration_tracing: true` we will now trace only each integration's `run` method instead of tracing all methods. All methods are traced only when the new `integration_tracing_exhaustive: true` option is set.
When the `DDEV_TRACE_ENABLED` env var is set it turns on both `integration_tracing` and `integration_tracing_exhaustive`.
We do this in order to reduce the overhead of tracing when running continuously in production. Some integrations make 1000s of calls to various internal methods, leading to 1000s of spans being recorded. 
Many of these methods are so fast that the overhead added by tracing exceeds the execution time of the methods themselves. Here is a recent example where a new `self.histogram` call was added to an integration and a significant fraction of time was spent …

reduce overhead of integration tracing

---

vault/assets/service_checks.json

* Clarifies that `vault.prometheus.health` and `vault.openmetrics.health` checks depend on the Openmetrics version used.
* Customer reached out as they did not understand why `vault.openmetrics.health` was not available for their Vault integration.

Clarifies that Prometheus and Openmetrics checks are mutually exclusive

---

win32_event_log/README.md

Updates the regex to match EventIDs of either legacy or non-legacy providers.
It is not always obvious which Windows Events use the Legacy provider.

Update regex to match legacy provider

---

kubernetes/assets/dashboards/kubernetes_nodes.json

Corrects an invalid query by removing an extraneous curly brace
customer pointed out they are unable to clone this dashboard -- the following error is reflected in the network request:
```
{"errors":["Invalid query in widget at position 32 of type timeseries. Error: unable to parse sum:kubernetes_state.container.cpu_requested{{$cluster,$host} by {kube_cluster_name}/sum:kubernetes_state.node.cpu_capacity{$cluster,$host} by {kube_cluster_name}*100: Rule 'scope_or' didn't match at '{$cluster,$host} by ' (line 1, column 46)."]}
```

correct CPU allocation widget metric query

---

ddev/src/ddev/repo/core.py
ddev/tests/repo/test_core.py

For commands that take an optional `INTEGRATIONS` argument:
- not specifying any will target every integration that has changed in Git
- selecting `all` will target every integration

Standardize integration selection

---

postgres/tests/test_deadlock.py

The deadlock test generates a deadlock and verifies that deadlock count metric increased. Since the deadlock counter doesn't increase synchronously, the test must wait until the deadlock counter increases. The deadlock test checks in a loop every 100 ms if the deadlock counter increased. This normally lasts no longer than a second or two, but it can take longer on a busy system. To reduce the likelihood of a failed tests, I increased the maximum wait time from 10 s to 30 s. Besides that, I excluded the deadlock test from e2e tests.
This change was done after the integrations tests for the new agent release started failing. @alexbarksdale quickly commented out the deadlock test. 
There's no guarantee that the deadlock counter is increased within a time limit. So, there's still some risk …

pg excluded deadlock test from e2e tests & increase wait time

---

ddev/tests/conftest.py

Update the `valid_integrations` to return all the valid integrations we have in the repo. 
Since https://github.com/DataDog/integrations-core/pull/13570, `iter_all` only returns the modified integrations by default. When there's no modification between your branch and master, it now returns an empty list, hence [this error](https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=123924&view=logs&j=16e22227-8deb-5530-dfc3-e3f564238956&t=dc8e9a3b-87f0-5140-ccd3-47aec2a819b1&l=895) on master. 
I modified the fixture to return all of them, no matter what, so the list is never empty.

Fix the valid_integrations fixture

---

datadog_checks_dev/datadog_checks/dev/tooling/testing.py

Modify the way we select environments when we are using hatch to mirror what we were doing with tox.
- The `latest` weekly pipeline is all red since we migrated to hatch https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=123628&view=logs&j=762a2123-1c7c-5bf0-0e62-04885c3ecd74&t=e42a329a-2791-53f4-67fc-ce0c85b45aed
- The `select_hatch_envs` also returns non-existing envs, which was not the case with the tox version: https://github.com/DataDog/integrations-core/blob/24983f216abb20f6487eed6a9b300a0e3ccc3385/datadog_checks_dev/datadog_checks/dev/tooling/testing.py#L194-L237
- To reproduce, run `ddev -v env test --base --new-env --junit --ddtrace datadog_checks_base:latest`, it should generate a warn and not an error
- I know we are not going to use tox in the future so …

Update the hatch env selection to act as the tox one

---

postgres/pyproject.toml

Bump the base check dependency
- The nightly ci build that uses the minimal base check version defined by the integration fails https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=124039&view=logs&j=5ba36005-b42a-55ea-a600-e8154d8d1b6b&t=fc8845e1-5f01-5ab3-fa2b-f094edac31cf
- The query executor was added in this PR https://github.com/DataDog/integrations-core/pull/11869 and got shipped with the base check `25.4.0`: https://github.com/DataDog/integrations-core/blob/master/datadog_checks_base/CHANGELOG.md#2540--2022-05-10
- This PR https://github.com/DataDog/integrations-core/pull/13374 started to use the executor, but forgot to bump the minimal version of the base check 
- To reproduce, run `ddev test --force-base-min --force-env-rebuild --junit postgres`

Bump the base check dependency

---

datadog_checks_base/datadog_checks/base/log.py
datadog_checks_base/datadog_checks/base/utils/__init__.py
datadog_checks_base/tests/test_log.py

When `integration_tracing: true` inject `trace_id` and `span_id` into integration logs, enabling easy correlation from traces to logs and vice versa.
We'll update the agent's default log parsing rules as a follow-up to ensure the trace_id is correctly parsed and remapped. 
Enable easy correlation between traces & logs.

Inject trace context into logs when integration_tracing is enabled

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/dep.py
datadog_checks_dev/pyproject.toml
datadog_checks_dev/tests/tooling/commands/test_dep.py

Skip yanked artifacts from PyPi when using `ddev dep updates --sync`.
https://datadoghq.atlassian.net/browse/AITOOLS-61
- Full PyPi payload example https://pypi.org/pypi/protobuf/json

Skip yanked artifacts from PyPi

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/dep.py

Stop ignoring the `protobuf` dependency when updating them with the `ddev dep updates --sync` command.
- Follow-up PR of https://github.com/DataDog/integrations-core/pull/13632
- Recommended by @jose-manuel-almaza in https://datadoghq.atlassian.net/browse/AITOOLS-61
I'll merge this one after https://github.com/DataDog/integrations-core/pull/13632

Stop ignoring the `protobuf` dependency when updating them

---

ddev/tests/conftest.py

Do not sign commits during tests
My setup requires to sign my commits with my yubikey. When I run the tests, it waits for me to touch my Yubikey 😅 I was wondering why the tests took so long, until it timed out.

Do not sign commits in tests

---

aerospike/tests/test_unit.py

Migrate from `called_with` to `assert_called_with`
- CI is failing on master https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=124396&view=logs&jobId=e6fbf30e-778c-5f2e-ae39-62f4185f213c&j=e6fbf30e-778c-5f2e-ae39-62f4185f213c&t=0e9729ef-3bcb-570e-bbdc-63508c8af0c7
- A new version of the `mock` lib got released [yesterday](https://pypi.org/project/mock/) and now throws an error when using `called_*` instead of `assert_called_*`: https://mock.readthedocs.io/en/latest/changelog.html#id1

Migrate from `called_with` to `assert_called_with`

---

active_directory/hatch.toml
aspdotnet/hatch.toml
dotnetclr/hatch.toml
exchange_server/hatch.toml
hyperv/hatch.toml
iis/hatch.toml
pdh_check/hatch.toml
win32_event_log/hatch.toml
windows_performance_counters/hatch.toml
windows_service/hatch.toml
wmi_check/hatch.toml

Switch from `win32` to `windows` platform in the hatch file. I also fixed the win32_event_log test command to run only the py2 tests with py2
`win32` seems to not be correctly taken into account. Tests are not running on master: 
- https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=124511&view=logs&jobId=07e99708-ce69-5454-a6f3-c9c372405ab5&j=d65fd6b8-c63e-5a4e-97a3-9b85857d5129&t=10847e51-470b-5c5e-9d8a-e8ee2f0656bd
- https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=124511&view=logs&jobId=07e99708-ce69-5454-a6f3-c9c372405ab5&j=07e99708-ce69-5454-a6f3-c9c372405ab5&t=7d431cc5-8a3c-54a5-b88c-fa79e094c778
I'm not an hatch expert, but it seems like hatch is using https://docs.python.org/3/library/platform.html#platform.system: …

Update the platform to `windows`

---

.azure-pipelines/templates/run-validations.yml
.github/workflows/validations.yaml
vertica/datadog_checks/vertica/vertica.py

Adds license header validation to CI
[AITOOLS-60](https://datadoghq.atlassian.net/browse/AITOOLS-60)
See d5717a076533e3a4308f10f6bbacba549ac7f10b and associated https://github.com/DataDog/integrations-core/pull/13674#issuecomment-1378750339 for an example of detected license change, not allowed by the validation.
[AITOOLS-60]: https://datadoghq.atlassian.net/browse/AITOOLS-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add `ddev validate license-headers` to validations run on CI

---

datadog_checks_dev/datadog_checks/dev/tooling/license_headers.py
datadog_checks_dev/tests/tooling/test_license_headers.py

Allows the license header validation to ignore the utf8 bom mark when deciding whether a file starts with the license header.
https://github.com/DataDog/integrations-core/pull/13511#issuecomment-1363886945. I was able to get rid of the magic comment on those few files that needed it by encoding the necessary files using the [utf8 bom](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8) that Python supports. Alas, I forgot to check if those files which seemed to start with the license header actually passed validation, which I only found out after adding the validation to our CI (#13674).
In theory we could come up with alternatives that would make the validator less strict towards having the license header at the _actual_ beginning of the file, but this solution patches the only special …

Support license header validation for files encoded with utf8 with bom

---

amazon_msk/assets/service_checks.json

The `broker_id` tag is not supposed to be collected on `aws.msk.prometheus.health`, although this was listed in the `service_checks.json`. This service check didn't have `broker_id` as a tag even in the [original implementation of the check](https://github.com/DataDog/integrations-core/pull/5127/files#diff-141423149133df2d7b8fe69c88c1e72a284c0c808714c440392b2f1d83a645cfR54).
Support

Remove broker_id tag from service_check.json

---

datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py

Automatically delete the agent container when the container is stopped
- First step to resolve https://datadoghq.atlassian.net/browse/AITOOLS-71. It only solves the issue mentioned for tests that do not run docker containers locally to run the tests (except the agent) such as vsphere.
- I'll work on the integration env itself in another PR
Steps to reproduce/test:
1. Run `ddev env start vsphere py3.8-7.0`
2. Run `docker stop dd_vsphere_py3.8-7.0` or reboot the docker daemon/your computer
3. Run `ddev env start vsphere py3.8-7.0` again -> it should work
Note: the other agent container are already using this option: [here](https://github.com/DataDog/integrations-core/blob/bdebedadb675c7f74a037bd0745a1d478515f9bc/datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py#L222) and …

Automatically delete the agent container when the container is stopped

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/make.py
datadog_checks_dev/tests/tooling/commands/release/test_make.py

Validate the new release version when provided for the `ddev release make` command
https://datadoghq.atlassian.net/browse/AITOOLS-55
- There's currently no tests to validate the whole command works. It will be easier to do that once we will migrate the command to the new ddev cli. 
- The tests that use an incorrect version can call directly the command since click will validate them before calling the function itself. It also validate that our option correctly defines the callback function to validate the value.
- I added a couple of tests to validate the function allows valid values, but calling the function directly. This should be refactored to a test that calls directly the command and make sure it works well as a whole, but let's do that in another PR.

Validate the new release version when provided

---

ddev/hatch.toml
ddev/tests/conftest.py

Mask the env variables used in the config file during the tests
The following tests are failing in my local environment: 
- tests/cli/config/test_show.py::test_default_scrubbed
- tests/cli/config/test_show.py::test_reveal
I have the `DD_GITHUB_USER` env variable configured. It is read during the `ddev config show` tests and modifies the output the tests are asserting, which makes them fail.

Mask the env variables used in the config file during the tests

---

postgres/datadog_checks/postgres/postgres.py
postgres/tests/test_unit.py

- Bug fix for the missing `replication_role` tag. 
- Unit test cases added for checking the correctness of the `replication_role` tag before and after a switchover. 
In the course of implementing `deadlock.count` metric in https://github.com/DataDog/integrations-core/pull/13374 I refactored the code that prunes `db` tag from the instance metrics. In doing so, I considered all but `replication_role` tag. Unlike most of the tags that are loaded from the static configuration, `replication_role` is read from the database and  changes after a switchover. Since the unit tests for this tag weren't implemented the bug remained unnoticed.

replication role tag bug fix

---

clickhouse/tests/conftest.py

Increase wait between attempts to check conditions when setting up the test environment. This should increase the total waiting time and greatly increase the chance of the setup succeeding.
These tests have been flaking for a while ([example](https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=125028&view=logs&jobId=8e96ab15-72b0-549c-5ab8-f9fece94b017&j=8e96ab15-72b0-549c-5ab8-f9fece94b017&t=3fa80c11-d62b-5625-9d93-4d60cdfd2103)).

Increase waiting time when setting up environent for integration tests

---

couchbase/tests/common.py
couchbase/tests/test_e2e.py
couchbase/tests/test_integration.py

Split the couchbase test files by test type. This PR does not change anything else, it just moves code.
Part of https://datadoghq.atlassian.net/browse/AI-2561, follow-up PR of https://github.com/DataDog/integrations-core/pull/13708

Split tests by type

---

powerdns_recursor/hatch.toml

Remove the latest env
- This was a mistake in https://github.com/DataDog/integrations-core/pull/13405, there's no latest env. Moreover we are building these images and we do not provide a latest one
- Spotted here: https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=124988&view=logs&j=1c9fd5d6-a258-5519-419c-101bcd1e02f2&t=eeb4971e-e545-5e41-1be7-4ec8036a8a1b
- No, it was not a copy/paste from the `postgres` integration, I have no idea what you're talking about. I'm not saying a word without my lawyer.

Remove the latest env

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/make.py
datadog_checks_dev/tests/tooling/commands/release/test_make.py

Fix `ddev make release` when the `version` parameter is not provided
- 🤦 [Here](https://github.com/DataDog/integrations-core/pull/13687), I forgot the most basic use case to test... Even if the option is not provided by the user, the callback function is called with `None`. In that case, the code raises an error: 
```
File "/Users/florent.clarret/go/src/github.com/DataDog/integrations-core/datadog_checks_dev/datadog_checks/dev/tooling/commands/release/make.py", line 21, in validate_version
if re.match("^\\d+\\.\\d+\\.\\d+(-(rc|pre|alpha|beta)\\.\\d+)?$", value):
File "/Users/florent.clarret/.pyenv/versions/3.9.9/lib/python3.9/re.py", line 191, in match
return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```
Spotted when the integrations-extras …

Fix `ddev make release` when the `version` parameter is not provided

---

mysql/datadog_checks/mysql/mysql.py
mysql/tests/test_statements.py

Adds a notice for the deprecation of the `extra_performance_metrics` option

Add deprecation notice for `extra_performance_metrics` option

---

clickhouse/tests/conftest.py

Reverts #13709 and ~~reorders conditions when setting up environment. I'm not confident that this would help, but it makes sense to reorder the conditions like this.~~
EDIT: Reordering actually caused tests to consistently fail on CI (I couldn't get them to work even after retrying multiple times). Therefore, I'm simply reverting this to the state before #13709. I think the problem is only with version 21.8 of Clickhouse, but more investigation would be needed to see how to solve this flake; in the meantime, we should keep the statu quo.
#13709 didn't help and it actually failed when merged; it simply took more time.

Revert increased waiting time

---

kafka_consumer/datadog_checks/kafka_consumer/new_kafka_consumer.py

Add kafka consumer logs for more visibility

---

rabbitmq/tests/common.py
rabbitmq/tests/fixtures/per-object.txt
rabbitmq/tests/metrics.py
rabbitmq/tests/test_openmetrics.py

extend and refactor tests

---

disk/assets/configuration/spec.yaml
disk/datadog_checks/disk/data/conf.yaml.default
disk/datadog_checks/disk/disk.py
disk/tests/test_filter.py
disk/tests/test_filter_deprecated.py
disk/tests/test_unit.py

Attempting to include tracefs volumes causes a spammy WARN-level log message by default.
Adds tracefs to the default `file_system_exclude`
This causes a spammy log message every time disk checks run
Issues where this was reported:
https://github.com/DataDog/integrations-core/issues/5675 
https://github.com/DataDog/dd-agent/issues/3875

Exclude tracefs by default from disk checks

---

journald/README.md
journald/assets/configuration/spec.yaml
journald/datadog_checks/journald/data/conf.yaml.example

Document feature in introduced in [#11398](https://github.com/DataDog/datadog-agent/pull/11398)
- AGENT-7627
- FRAGENT-1752
Same as #13701 13701

Document feature in journald user-level filtering

---

varnish/datadog_checks/varnish/varnish.py

Header row not being skipped due to different format for Varnish 6; results in UNKNOWN service check with `backend:name`

Fix UNKNOWN service check with backend:name

---

datadog_checks_dev/datadog_checks/dev/tooling/configuration/consumers/example.py
datadog_checks_dev/tests/tooling/configuration/consumers/test_example.py

Handle instances that have `options` when using `multiple_instances_defined` in the spec.yaml. 
When the first instance option also has `options` configured, this instance does not get defined with a `-` in the conf.yaml.example, thus breaking the configuration. I found that this was due to the nested `options` in the spec.yaml:
```
multiple_instances_defined: true
options:  ## <== 
- name: OpenMetrics
description: RabbitMQ Prometheus Plugin Example
options:  ## <==
- name: prometheus_plugin
description: |
Settings for talking to the Prometheus plugin of RabbitMQ.
Specify this section to trigger metric collection from the Prometheus plugin endpoints.
enabled: true
options: ## <==
- name: url
...
```
Which produces a misconfigured instance in the conf.yaml.example:
```
instances:
# …
```

Handle nested options in multi-instances-defined

---

clickhouse/datadog_checks/clickhouse/clickhouse.py
clickhouse/tests/test_clickhouse.py
clickhouse/tests/test_unit.py

This test is very flaky and it can be an unit test, this PR does that and also splits it into three different tests.
Also I noticed the metadata entrypoint annotation was missing, so I added it (also so I could disable metadata collection on the unit tests)

Make service check tests unitary. Add metadata entrypoint

---

snmp/tests/test_e2e_core_metadata.py

Assert id and source_type for Topology Links
https://github.com/DataDog/datadog-agent/pull/15184

Assert id and source_type for Topology Links

---

argocd/assets/recommended_monitors/application_sync_status.json
argocd/manifest.json

This PRs add a recommended monitor for Argo CD integration. The monitor is designed to look at the metric for `argocd.app_controller.app.info`. This metric returns a static value of one and has the status as a tag. 
The monitor is intended to monitor `argocd.app_controller.app.info` and looks for groups that are not synced (`!sync_status:synced`) and breaks it down by `sync_status` and `name`. 
Trigger: if any group reports with `!sync_status:synced` for 30 minutes.
Recovery: I don't think that's possible because the group disappears when it becomes synced
Note: I added a default_zero to this because monitor looks for a metric with a group that isn't `synced`. If the group becomes synced, it will disappear. But because gauge are interpolated with their last value for 5 mins after they …

Add recommended monitor

---

rabbitmq/assets/configuration/spec.yaml
rabbitmq/datadog_checks/rabbitmq/config_models/validators.py
rabbitmq/datadog_checks/rabbitmq/data/conf.yaml.example
rabbitmq/tests/test_openmetrics.py

This PR adds validation for `include_aggregated_endpoint` requiring it to be true when `unaggregated_endpoint` is unspecified. Otherwise, the check will run and collect nothing:
```
andrew.zhang@COMP-C02F513WML87 integrations-core % ddev env check rabbitmq          
=========
Collector
=========
Running Checks
==============
rabbitmq (3.3.0)
----------------
Instance ID: rabbitmq:1f8a86b67a8bf2a9 [OK]
Configuration Source: file:/etc/datadog-agent/conf.d/rabbitmq.d/rabbitmq.yaml
Total Runs: 1
Service Checks: Last Run: 0, Total: 0
Average Execution Time : 31ms
Last Execution Date : 2023-01-24 21:12:23 UTC (1674594743000)
Last Successful Execution Date : 2023-01-24 21:12:23 UTC (1674594743000)
Check has run only once, if …
```

Add validation for `include_aggregated_endpoint`

---

ddev/pyproject.toml

Pin the datadog_checks_dev version
We faced various issues related to the fact that `datadog_checks_dev` was not pinned and some people were using an outdated `datadog_checks_dev` (but that still satisfied the requirements). This lead us to have different errors using the new `ddev` cli, even if we were using the exact same `ddev` version, because we were in fact not using the same `datadog_checks_dev` version. 
I know that fixing this issue is easy (once you know where it comes from) for us, and we just need to `pip install datadog_checks_dev[cli]` to bring the latest version and `ddev` will start working again as expected.  However, I do think some of our users may also get these kind of errors and that will not be that easy for them to fix. 
My opinion is that it will be easier for …

Pin and bump the datadog_checks_dev version

---

ibm_mq/assets/configuration/spec.yaml
ibm_mq/datadog_checks/ibm_mq/config.py
ibm_mq/datadog_checks/ibm_mq/data/conf.yaml.example

On https://github.com/DataDog/integrations-core/pull/13559 we made it so `try_basic_auth` is False when `queue_manager_process` is used. This PR makes it so it is *default* False, but can still be configured

Allow setting the try basic auth value from config in all cases

---

LICENSE-3rdparty.csv

Remove an extra `'` at the end that is causing license validation to fail.

remove extra '

---

envoy/tests/legacy/test_envoy.py
envoy/tests/test_check.py
envoy/tests/test_e2e.py

- Assert all metrics are covered in the e2e tests
- Assert metrics using the metadata
- Use pytest.param where relevant
Noticed they were missing QAing https://github.com/DataDog/integrations-core/pull/13573

Assert all metrics are covered in the e2e tests

---

sqlserver/datadog_checks/sqlserver/metrics.py
sqlserver/tests/test_connection.py
sqlserver/tests/test_unit.py

The metric `sqlserver.database.state` wasn't being sent in certain agent configurations, see Additional Notes for details. This PR fixes the problem.
In addition, I created a unit test which reproduces the conditions leading to the problem and verifies that the metric is correctly emitted.
Last but not least, some of the tests were failing on EC2. This problem isn't related to the aforementioned bug. The reason for the failed tests is that newer versions of the ODBC/TDS drivers were generating slightly different error messages which weren't matched with the existing regular expressions in tests. I adapted the regular expressions so that they are working correctly also with the new versions of the drivers.  
The problem was noticed while resolving the following escalation: …

sqlserver.database.state not sent for all databases

---

LICENSE-3rdparty.csv
datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/datadog_checks/base/utils/agent/packages.py
datadog_checks_base/pyproject.toml
datadog_checks_downloader/datadog_checks/downloader/download.py
datadog_checks_downloader/datadog_checks/downloader/parameters.py
mcache/datadog_checks/mcache/mcache.py

This package is also used in a few test suites but that will be a separate PR so changelogs don't get affected

Remove the use of the deprecated `pkg_resources` package

---

cockroachdb/tests/conftest.py
ignite/tests/common.py
mysql/tests/common.py
mysql/tests/test_mysql.py
mysql/tests/test_query_activity.py
mysql/tests/test_statements.py

This is part two of https://github.com/DataDog/integrations-core/pull/13842
https://github.com/DataDog/integrations-core/pull/12560/files

Remove test usage of the deprecated `pkg_resources` package

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/hatch.toml

Remove py2 from the default template.
We no longer supports py2 by default for new integrations: https://github.com/DataDog/integrations-core/blob/master/datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/%7Bcheck_name%7D/pyproject.toml#L13

Remove py2 from the default template

---

LICENSE-3rdparty.csv
datadog_checks_base/datadog_checks/base/data/agent_requirements.in
sqlserver/pyproject.toml

Removes the dependency on `adodbapi` from the `sqlserver` integration.
The `adodbapi` module is already provided by `pywin32`, since version `211` (see [documentation page](https://adodbapi.sourceforge.net/)).
The `adodbapi` package isn't maintained separately anymore (since it is part of `pywin32`), hasn't been updated since 2019, and isn't compatible with `setuptools` >= 58.0.0. Its presence prevents us from updating the `setuptools` version used in the Agent.
n/a

Remove dependency on adodbapi (already included in pywin32)

---

snmp/tests/test_e2e_core_metadata.py

Fix e2e test for topology links to use dd_id
https://github.com/DataDog/datadog-agent/pull/15265

Fix e2e test for topology links to use dd_id

---

datadog_checks_downloader/datadog_checks/downloader/download.py
datadog_checks_downloader/tests/test_unit.py

The current logic of the checks downloader will look at the newest version of the check. This sometimes can be an alpha, beta or an rc version of the check. This PR aims to only install the officially released version of the check unless it's specified to install an alpha, beta or rc version.
https://datadoghq.atlassian.net/browse/AITOOLS-31

Prevent Alphas, Betas and RC versions of checks from being installed unless specified

---

rabbitmq/assets/configuration/spec.yaml
rabbitmq/datadog_checks/rabbitmq/config_models/validators.py
rabbitmq/datadog_checks/rabbitmq/data/conf.yaml.example
rabbitmq/datadog_checks/rabbitmq/openmetrics/metrics.py
rabbitmq/tests/test_openmetrics.py

Remove support for scraping the `/metrics/per-object` endpoint. 
We decided the danger of cardinality explosion was too high with this endpoint. Customers should be able to get what they need from the `/metrics/detailed` endpoint.
**Question for reviewers: should we document this in the integration readme or in the config?**

Remove support for /metrics/per-object endpoint.

---

argocd/manifest.json

Add the process signature for the 3 main components of ArgoCD
```
argocd@argocd-application-controller-0:~$ ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
argocd         1  0.0  0.7 807096 32096 ?        Ssl  Jan11  30:51 argocd-application-controller --redis argocd-redis-ha-haproxy:6379
```
```
argocd@argocd-repo-server-6f58577bf4-2drsc:~$ ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
argocd         1  0.0  0.0   2788    96 ?        Ss   Jan11   1:16 tini -- argocd-repo-server --redis argocd-redis-ha-haproxy:6379
argocd         7  0.0  0.6 807352 28000 ?        Sl   Jan11  16:29 argocd-repo-server --redis argocd-redis-ha-haproxy:6379
```
```
argocd@argocd-server-7c6b84847c-s75vn:~$ ps aux
USER         PID %CPU %MEM …
```

Add Process signature for ArgoCD

---

cockroachdb/README.md
cockroachdb/assets/configuration/spec.yaml
cockroachdb/datadog_checks/cockroachdb/data/conf.yaml.example
cockroachdb/hatch.toml
cockroachdb/tests/conftest.py

Updates the E2E environment to enable `histogram_buckets_as_distributions` and add `node` and `cluster` tags to the E2E instance config. 
Also corrects the readme to use `openmetrics` instead of `prometheus_url`

Update E2E environment

---

ibm_mq/README.md

Removes references to the `C_INCLUDE_PATH` variable on the readme's setup section.
From what I can tell, that variable points at header files that would only be necessary when building the C extension, and it's not really needed at runtime. The hatch.toml file and some manual tests confirm this.
Removing it from the setup instructions is one thing less to care about.

Remove references to `C_INCLUDE_PATH` variable on setup

---

istio/tests/conftest.py

Remove the istio archive during the test setup
During the e2e env setup, a tar file is created in the repository and not deleted afterwards.

Remove the istio archive during the test setup

---

http_check/datadog_checks/http_check/config.py
http_check/datadog_checks/http_check/http_check.py
http_check/tests/test_http_integration.py

Support case-insensitive custom header fields.
This change was initially brought about when a customer configured a custom header for a `POST` method.
Instances that have a non-GET method specified automatically get the `"Content-Type": "application/x-www-form-urlencoded"` header applied if a custom `Content-Type` header is not supplied. Previously, if the custom `Content-Type` header is specified with different cases (lowercase, uppercase, etc.), this header is ignored and the default header is applied.
Per RFC 9110, [RFC 9110: HTTP Semantics](https://www.rfc-editor.org/rfc/rfc9110.html#section-5.1-3) header fields are case-insensitive.
Support case

Support case-insensitive header fields

---

iis/datadog_checks/iis/check.py
iis/datadog_checks/iis/iis.py
iis/datadog_checks/iis/service_check.py
iis/hatch.toml
iis/tests/common.py
iis/tests/conftest.py
iis/tests/test_e2e.py
iis/tests/test_iis.py
iis/tests/test_unit.py

Change the performance counter the `iis.app_pool_up` service check is based on to the `\APP_POOL_WAS(<INSTANCE>)\Current Application Pool State` counter.
The `iis.app_pool_up` service check was based on the `\APP_POOL_WAS(<INSTANCE>)\Current Application Pool Uptime` performance counter, but this counter does not reset to zero when the app pool is stopped. It only resets to zero once the app pool is started again. This meant our `iis.app_pool_up` would incorrectly report the app pool as OK. This behavior is different from sites, whose uptime counter does reset to zero when the site is stopped.
https://datadoghq.atlassian.net/browse/WA-181

Change the performance counter used by the iis.app_pool_up service check so it can tell when the app pool is down.

---

mongo/datadog_checks/mongo/collectors/custom_queries.py
mongo/tests/common.py
mongo/tests/test_mongo.py

Fixed the exception that is thrown when a custom query contains non-iterable elements (eg strings) inside a list.
Example:
```
query: {
'find': 'orders',
'filter': {'amount': {'$gt': 25}},
'sort': {'amount': -1},
'projection': {'result': {'$subtract': ['$amount', 1]}},
},
```
You can check that the `$subtract` function receives a list with a string and a number.
The following exception is thrown before the fix:
`"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/mongo/collectors/custom_queries.py", line 30, in replace_datetime for k, v in obj.items(): AttributeError: 'str' object has no attribute 'items'`
In addition to the code that fixes the problem, a test will be added (`test_mongo_custom_query_with_string_list`) that will check that the previously described query …

Exception is thrown when items of a list in a custom query are not iterable

---

kubernetes/assets/dashboards/kubernetes_jobs.json

* Updates widgets `Top Cronjobs by Job count` and `Cronjobs by Job count` to use the tags provided by the KSM Core integration, which is the default enabled
* Customer reached out as after moving to our chart 3.x, some widgets do not show data anymore.
* After investigating, these widgets rely on `owner_kind/name`, tags that are no longer being collected by the KSM core check for the metric `kubernetes_state.job.count` which uses `kube_cronjob` instead : 
* Quick demo/sample showing this behaviour :

[KSM Core] Updates job widgets to use kube_cronjob instead of owner

---

postgres/datadog_checks/postgres/statement_samples.py
postgres/tests/test_statements.py

- Adds the collection of non `client backend` backend type rows from pg_stat_activity
- Some active connections sometimes come back with blocking PIDs that are nowhere to be found in the sampling batch. The assumption is that a background process is the matching blocking PID.

Collect pg_stat_activity rows for non-"client backend" backend types

---

datadog_checks_base/datadog_checks/base/checks/windows/perf_counters/utils.py
iis/datadog_checks/iis/check.py

Removed optimization which trigger using "leaky" library function used in IIS Check
To fix memory leaked introduced in 7.42.
Test is relatively simple. Assuming you have setup actual IIS and DD default IIS Check. Set min_collection_interval on iis config to 1 (to speed up memory grows). Without the fix in Perfmon ort Task Manager agent.exe memory will steadily climbing up (~20 Mb per hour) and with the fix it will not happen.

[7.43.0 Release] Fix IIS Check memory leaked due to a bug in win32pdh.GetFormattedCounterArray()

---

iis/datadog_checks/iis/check.py

Removed optimization which trigger using "leaky" library function used in IIS Check
To fix memory leaked introduced in 7.42.
Test is relatively simple. Assuming you have setup actual IIS and DD default IIS Check. Set min_collection_interval on iis config to 1 (to speed up memory grows). Without the fix in Perfmon ort Task Manager agent.exe memory will steadily climbing up (~20 Mb per hour) and with the fix it will not happen.

Fix IIS Check memory leaked due to a bug in win32pdh.GetFormattedCouterArray()

---

iis/CHANGELOG.md
iis/datadog_checks/iis/__about__.py
requirements-agent-release.txt

Updating the version to match 7.43.x release:
https://github.com/DataDog/integrations-core/pull/13902

Bump IIS to 2.18.1

---

cassandra/README.md
varnish/README.md

removes containers tab from Varnish and Cassandra docs as it isn't applicable

DOCS-4550 - remove container instructions on varnish and cassandra

---

cassandra_nodetool/README.md

We had a customer ask about how to collect metrics from Cassandra Nodetool in a containerized environment. Since Cassandra Nodetool is one of the integrations that doesn't work with standard Autodiscovery, you need to use the Prometheus exporter. We won't have very detailed instructions on how to use Prometheus exporter, but we can call out that getting metrics from Cassandra Nodetool in a containerized environment is possible with this workaround.

DOCS-4559 containerized instructions for cassandra nodetool

---

haproxy/datadog_checks/haproxy/metrics.py
haproxy/hatch.toml
haproxy/metadata.csv
haproxy/tests/conftest.py

- remove legacy versions no longer supported (v1.8.x, 2.3.x) from test matrix
- add support for v2.6.x and v2.7.x
- update list of metrics:
* `haproxy_backend_agg_server_check_status` is being deprecated
in favour of:
* `haproxy_backend_agg_check_status`
* `haproxy_backend_agg_server_status`
(backported in all versions from >= v2.4.21)
keep haproxy integration up to date

haproxy: bump versions and update metrics

---

zk/datadog_checks/zk/zk.py

This PR adds a newline character (`\n`) to the end of the 4wl commands needed for Zookeeper. It appears as though using an Istio proxy causes them to be dropped, resulting in timeout errors for the check when using an Istio proxy. This change resolves the issue. 
This came out of my investigation of [this issue](https://datadoghq.atlassian.net/browse/CONS-5326), and was previously noted in [this card](https://datadoghq.atlassian.net/browse/AGENT-8853) and [this Github issue](https://github.com/istio/istio/issues/11394). 
This bug can be reproduced with the following steps: 
1. Start up `minikube` or `kind cluster`
2. Install Istio on the cluster with the steps [here](https://istio.io/latest/docs/setup/install/helm/).
3. Tag the `default` namespace with `kubectl label namespace default …

Ensure Zookeeper command execution in proxy environments

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
snowflake/pyproject.toml

Updates `snowflake-connector-python` dependency to 3.0.0.
It's needed to make dependency constraints for a cryptography update work: https://github.com/DataDog/integrations-core/pull/13913
Should be merged at the same time as the matching update on omnibus: https://github.com/DataDog/datadog-agent/pull/15535

Update snowflake-connector-python to 3.0.0

---

ibm_ace/datadog_checks/ibm_ace/flows.py
ibm_ace/datadog_checks/ibm_ace/resources.py

It replaces all calls to `monotonic_count` with calls to `count`.
A support case reporting discrepancies between what the IBM ACE UI says and what Datadog reports.
The official docs are not explicit about what the reported counts are, but the fact that they come with interval timestamps seems to imply that they're counts applying only to specific intervals. I confirmed this for `ibm_ace.MessageFlow.TotalInputMessages`, which was the relevant metric on the support case.

Use `count` instead of `monotonic_count` for counters

---

kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
kafka_consumer/tests/test_kafka_consumer.py

This PR removes `KafkaClient` from being used in the check and also fixes the tests to use `KafkaAdminClient` instead.
Removing legacy code as part of refactor

Remove KafkaClient and refactor tests

---

postgres/datadog_checks/postgres/statement_samples.py

- Stop the postgres activity check from collecting a row matching the connection of the query collecting the samples.
All query executions:
Only query executions matching the word "pg_stat_activity":

Prevent postgres activity check from collecting samples of its own connection

---

kafka_consumer/datadog_checks/kafka_consumer/client/confluent_kafka_client.py
kafka_consumer/datadog_checks/kafka_consumer/client/kafka_client.py
kafka_consumer/datadog_checks/kafka_consumer/client/kafka_client_factory.py
kafka_consumer/datadog_checks/kafka_consumer/client/kafka_python_client.py
kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
kafka_consumer/tests/test_kafka_consumer.py

This PR refactors the Kafka Consumer check by doing a few things:
- Create new interface `KafkaClient` with children classes `ConfluentKafkaClient` and `KafkaPythonClient`
- Remove the sub check in `kafka_consumer.py`
- Move check logic into new `KafkaPythonClient` class
Initial refactor
Note that the client code still contains check logic. This will be removed in a [subsequent PR](https://github.com/DataDog/integrations-core/pull/13955) to reduce the content being changed.

Refactor Kafka Consumer

---

argocd/README.md

The Argo CD integration requires Agent version 7.42.0 and above in order to run. We could avoid support tickets created to troubleshoot this if it is made explicit in the docs.
Explicitly indicates the required Agent version for the Argo CD check.
Zendesk ticket [1098161](https://datadog.zendesk.com/agent/tickets/1098161).
Customer's Argo CD check was throwing an error and it was resolved by updating to 7.42.0. They suggested adding this to the doc to avoid the need to create a support ticket.
Here is the [integrations-core changelog](https://github.com/DataDog/integrations-core/blob/master/AGENT_CHANGELOG.md#datadog-agent-version-7420) showing that Argo CD was first introduced as an integration with version 7.42.0
Note that this is currently the only mention of Argo CD in all versions

Added required Agent version

---

amazon_msk/datadog_checks/amazon_msk/check.py

This is a fix for a [previous fix](https://github.com/DataDog/integrations-core/pull/13886) given that I learned the difference between `count` and `monotonic_count` methods 🙈

Switch count method to monotonic count, that's correct for OM counts

---

kafka_consumer/datadog_checks/kafka_consumer/client/confluent_kafka_client.py
kafka_consumer/datadog_checks/kafka_consumer/client/kafka_client.py
kafka_consumer/datadog_checks/kafka_consumer/client/kafka_python_client.py
kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py

Take metric and event reporting out of the kafka client file and put it back in the main check.

Move metric reporting back into main check

---

rabbitmq/hatch.toml
rabbitmq/tests/common.py
rabbitmq/tests/conftest.py
rabbitmq/tests/test_e2e.py
rabbitmq/tests/test_integration.py
rabbitmq/tests/test_unit.py

Management and prometheus (openmetrics) plugin tests are completely separate now.
Paying down tech debt :)

Finish splitting tests for different metrics sources

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
kafka_consumer/pyproject.toml

`ddev dep sync`
- Forgot to do it in https://github.com/DataDog/integrations-core/pull/13961 and the check did not run 😕 
- CI is failing in https://github.com/DataDog/integrations-core/pull/13918

Fix agent deps

---

pgbouncer/datadog_checks/pgbouncer/metrics.py

We are reverting this [PR](https://github.com/DataDog/integrations-core/pull/13952) because "name" tag is conflicting with name from kube_system. Instead of using "name", we will use postgres_db to represent the postgres database name (from `SHOW DATABASES` output).

Add pgbouncer_db tag into pgbouncer metrics

---

kafka_consumer/datadog_checks/kafka_consumer/client/kafka_client.py
kafka_consumer/datadog_checks/kafka_consumer/client/kafka_client_factory.py
kafka_consumer/datadog_checks/kafka_consumer/client/kafka_python_client.py
kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py

Move tls_context creation out of the client logic and back into the main check.

Move tls_context creation back into main check

---

ecs_fargate/README.md

Updates the "availability_zone" tag to "availability-zone" in the documentation for the ECS Fargate integration.
This change updates the documentation to reflect the change made to tagging for this integration. The former tag name has been deprecated in favor of the latter, with the intention being to make the tagging consistent between Fargate and other AWS infrastructure offerings, such as EC2 and ECS.
See corresponding agent code change here: https://github.com/DataDog/datadog-agent/pull/15629

Change "availability_zone" tag to "availability-zone" for ECS Fargate

---

snmp/tests/compose/data/args_list.txt
snmp/tests/conftest.py
snmp/tests/test_e2e_snmp_listener.py

Add test for SNMP Listener with auth proto SHA256
https://github.com/DataDog/datadog-agent/pull/15646

Add test for SNMP Listener with auth proto SHA256

---

kafka_consumer/tests/common.py
kafka_consumer/tests/conftest.py
kafka_consumer/tests/python_client/test_integration.py
kafka_consumer/tests/python_client/test_unit.py

- Refactor the tests
- Avoid some code duplication
- Add missing assert for the metadata
- Make some assert more strict

Refactor the tests

---

kafka_consumer/datadog_checks/kafka_consumer/client/kafka_client.py
kafka_consumer/datadog_checks/kafka_consumer/client/kafka_python_client.py
kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py

This PR formally removes `self.check` from the client code to fully separate the logic between check and Kafka client. This PR also does some other cleaning up.

Remove self.check and cleanup

---

elastic/metadata.csv

As mentioned here: 
https://github.com/DataDog/integrations-core/issues/13844
It does seem like we collect the percent memory used here and the value should be between 0 to 100
```
jvm.mem.heap_in_use                                                   gauge  1676561004  58            baz, cluster_name:test-cluster, elastic_cluster:test-cluster, foo:bar, node_name:test-node, url:http://localhost:9200  
```

fix metric description

---

envoy/datadog_checks/envoy/metrics.py
envoy/tests/fixtures/stat_prefix
envoy/tests/legacy/common.py
envoy/tests/legacy/test_envoy.py

This adds the logic that allows for ext_auth metrics to have the stat_prefix parsed out of the stats payload. To keep backwards compatibility, the original logic was preserved as well.
Albeit a bit hacky, given this is for the legacy implementation, I've tried to touch as a little of the legacy code as possible.

Parse and add the tag `stat_prefix` to `ext_authz` metrics if possible

---

postgres/metadata.csv

Fixes the missing metadata units for the `postgresql.seq_scans` which can lead to a confusing experience. Showing the gauge value in `scans/sec` will make it easier for users to understand this metric.

Update postgresql.seq_scans metadata to add missing units

---

kafka_consumer/datadog_checks/kafka_consumer/client/kafka_python_client.py
kafka_consumer/tests/python_client/test_unit.py

Disable a unit test that only validates some parameters which are tied to the client implementation
- We should not have a test that validates the parameters, but have one that really use oath (tbd in a follow-up PR)
- Will be needed for https://github.com/DataDog/integrations-core/pull/14022

Disable one unit test

---

process/assets/configuration/spec.yaml
process/datadog_checks/process/data/conf.yaml.example

Clarify `exact_match` setting.
The explanation of `exact_match` should be easier.
[proc.name()](https://github.com/DataDog/integrations-core/blob/58304dfcf51a7ba6b0680c2d3eafa395a0a976fd/process/datadog_checks/process/process.py#L164) is same as the result of `ps -e`.
```bash
$ sudo -u dd-agent /opt/datadog-agent/embedded/bin/python3 -c "import psutil; print([proc.name() for proc in psutil.process_iter(attrs=['name','pid'])])"
['systemd', 'kthreadd', 'rcu_gp', 'rcu_par_gp', 'slub_flushwq', 'netns', 'kworker/0:0H-events_highpri', 'mm_percpu_wq', 'rcu_tasks_rude_', 'rcu_tasks_trace', 'ksoftirqd/0', 'rcu_sched', 'migration/0', 'idle_inject/0', 'cpuhp/0', 'cpuhp/1', 'idle_inject/1', 'migration/1', 'ksoftirqd/1', 'kworker/1:0H-events_highpri', 'kdevtmpfs', 'inet_frag_wq', 'kauditd', …
```

Clarify `exact_match` setting document

---

openstack_controller/tests/test_e2e.py

Adds service check asserts to openstack_controller end to end test 
better coverage of the service checks

Add service check assertions to e2e test

---

postgres/datadog_checks/postgres/util.py

The `postgresql.replication_delay` metric sometimes spikes after a reload or restart to a large (sometimes multi-day) value and then immediately returns to zero.
`pg_last_xact_replay_timestamp()` doesn't update often on databases that don’t get many writes. Therefore, `now() -
pg_last_xact_replay_timestamp()` can get large on such databases.  This value is normally suppressed when `pg_last_wal_receive_lsn() = pg_last_wal_replay_lsn()`, but upon restart/reload one or both of those functions return `NULL` until replication has resumed. Per Postgres documentation:
> `pg_last_wal_receive_lsn() -> pg_lsn`: ... If streaming replication is disabled, or if it has not yet started, the function returns `NULL`.
>
> `pg_last_wal_replay_lsn() -> pg_lsn`: ... When the server has been started normally …

Avoid brief postgresql.replication_delay spikes after Postgres restart/reload

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/dep.py

Legacy parsing is no longer supported https://github.com/pypa/packaging/blob/5b34465682d40ddd42dd6cba88e158e1674de7b9/CHANGELOG.rst#220---2022-12-07 which then makes versions like https://pypi.org/project/boto/0.8d/ fail
Also accounts for https://github.com/pypa/packaging/issues/566

Fix dependency update logic for latest versions of `packaging`

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py

This PR adds `process` and `runtime` to `ALLOWED_PREFIXES`.
Fix validation for https://github.com/DataDog/integrations-core/pull/13933

Add process and runtime to allowed prefixes

---

envoy/datadog_checks/envoy/envoy.py
envoy/tests/legacy/common.py
envoy/tests/legacy/test_envoy.py

When using [stats_url](https://github.com/DataDog/integrations-core/blob/bb108d103e68db601665a61f5e558346f334186d/envoy/datadog_checks/envoy/data/conf.yaml.example#LL63C7-L63C16) instead of [openmetrics_endpoint](https://github.com/DataDog/integrations-core/blob/bb108d103e68db601665a61f5e558346f334186d/envoy/datadog_checks/envoy/data/conf.yaml.example#LL51C5-L51C25), Agent uses legacy [Envoy check](https://github.com/DataDog/integrations-core/blob/bb108d103e68db601665a61f5e558346f334186d/envoy/datadog_checks/envoy/envoy.py#L18). Now legacy Envoy check can take config values from `{include,exclude}_metrics`.
https://github.com/DataDog/integrations-core/blob/bb108d103e68db601665a61f5e558346f334186d/envoy/datadog_checks/envoy/envoy.py#L29-L41
Only …

Add `{include,exclude}_metrics` to legacy Envoy check

---

.azure-pipelines/templates/test-single-linux.yml

Increase linux test timeout from 90 -> 180 minutes. This now matches the windows timeout. 
Ideally, tests should be much faster than this. However we are seeing timeouts on a specific change we are trying to get into the agent before a freeze, so this is a temporary adjustment to get us past this hurdle. See discussion [here](https://dd.slack.com/archives/C9WBCH0AF/p1677626253008479).

increase linux pipeline test time limit to match windows

---

snmp/tests/metrics.py
snmp/tests/test_e2e_core.py
snmp/tests/test_e2e_core_vs_python.py
snmp/tests/test_e2e_snmp_listener.py

Update e2e to handle new interface speed metrics
https://github.com/DataDog/datadog-agent/pull/15721

Update e2e to handle new interface speed metrics

---

openstack_controller/tests/common.py
openstack_controller/tests/fixtures/openstack_bad_config.yaml
openstack_controller/tests/test_config.py

Adds unit tests for invalid configurations in the openstack_controller checks
We don't have any coverage for this and want to refactor the code, so we need to ensure we don't break behavior

Add tests for invalid configurations

---

sqlserver/assets/configuration/spec.yaml
sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
sqlserver/datadog_checks/sqlserver/statements.py
sqlserver/tests/test_high_cardinality.py

This lowers the frequency of query metrics collection to only run once every 60s by default. This proposal is being made to balance the staleness of data against having the lowest possible performance impact. We've found that customers generally do not need the high resolution of query metrics with the introduction of Activity events which are sampled at every 10s with much richer information. Query metrics are more often used for historical analysis.

Lower the frequency of query metrics collection

---

mysql/datadog_checks/mysql/mysql.py
mysql/tests/conftest.py
postgres/datadog_checks/postgres/postgres.py
postgres/tests/test_pg_integration.py

Add resolved_hostname to metadata for MySQL and Postgres.
More context here: [DBM-1862](https://datadoghq.atlassian.net/browse/DBM-1862)
[DBM-1862]: https://datadoghq.atlassian.net/browse/DBM-1862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DBM-1862] add resolved_hostname to metadata to mysql, postgres

---

snmp/tests/test_e2e_core.py
snmp/tests/test_e2e_snmp_listener.py

Rename speed_source tag value from `snmp` to `device`
https://github.com/DataDog/datadog-agent/pull/15920

Rename speed_source tag value from `snmp` to `device`

---

kafka_consumer/datadog_checks/kafka_consumer/client/generic_kafka_client.py
kafka_consumer/datadog_checks/kafka_consumer/client/kafka_python_client.py
kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py

This is required since the highwater offset metric depends on the consumer offset metrics. By doing this we can implement the highwater offsets separately to consumer offsets.

Pass consumer offsets into highwater offsets

---

kafka_consumer/datadog_checks/kafka_consumer/client/confluent_kafka_client.py
kafka_consumer/datadog_checks/kafka_consumer/client/generic_kafka_client.py
kafka_consumer/datadog_checks/kafka_consumer/client/kafka_client.py
kafka_consumer/datadog_checks/kafka_consumer/client/kafka_python_client.py
kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
kafka_consumer/tests/python_client/test_integration.py

This PR removes collect_broker_version from the kafka_consumer check since the Confluent library does not have the ability to query the broker version.

Remove collect_broker_version

---

kafka_consumer/datadog_checks/kafka_consumer/client/confluent_kafka_client.py
kafka_consumer/datadog_checks/kafka_consumer/client/generic_kafka_client.py

This PR implements `get_partitions_for_topic()`.

Implement get_partitions_for_topic

---

rabbitmq/assets/configuration/spec.yaml
rabbitmq/datadog_checks/rabbitmq/data/auto_conf.yaml

Turns the `instances` key into the expected array of objects instead of an object.

Fix autodiscovery config instances

---

sqlserver/datadog_checks/sqlserver/const.py
sqlserver/datadog_checks/sqlserver/sqlserver.py
sqlserver/tests/common.py
sqlserver/tests/test_integration.py
sqlserver/tests/test_unit.py

This PR is a follow on to https://github.com/DataDog/integrations-core/pull/13757 and addresses a bug, which has been brought to our attention as an urgent customer issue. Currently in the sqlserver default integration, instance metrics (os performance counter metrics) are collected in the following way:
1. The `include_instance_metrics` config is checked (defaults to True)
2. If `True` all of the metrics in the [INSTANCE_METRICS](https://github.com/DataDog/integrations-core/blob/master/sqlserver/datadog_checks/sqlserver/const.py#L60) AND the [INSTANCE_METRICS_TOTAL](https://github.com/DataDog/integrations-core/blob/master/sqlserver/datadog_checks/sqlserver/const.py#L86) lists are added to the dict of metrics to collect (this means they will be emitted by the integration). 
3. Both sets …

Do not double emit instance metrics when autodiscovery is enabled

---

kafka_consumer/tests/conftest.py
kafka_consumer/tests/runners.py

Replace the python kafka client in the test setup functions.
Will be needed to add new e2e envs with authentication

Use confluent-kafka during the test setup

---

kafka_consumer/hatch.toml
kafka_consumer/tests/common.py
kafka_consumer/tests/docker/noauth/docker-compose.yaml

Modify the hatch environment to support several authentication method
We have this in the kerberos and the ssl PRs so I'm moving it here se we can avoid code duplication in PRs

Modify the hatch environment to support several authentication method

---

databricks/README.md

Explicitly set the hostname on workers. Needed for agent 7.40+
- Support case
- This was added in [this PR](https://github.com/DataDog/integrations-core/pull/13628/files) but we forgot to do it for workers so the agent was not working properly.

Explicitly set the hostname on workers

---

zk/hatch.toml

Changes test env names of `zk` from:
```
py2.7-3.5.8-True
py2.7-3.5.8-False
py2.7-3.6.2-True
py2.7-3.6.2-False
py3.8-3.5.8-True
py3.8-3.5.8-False
py3.8-3.6.2-True
py3.8-3.6.2-False
```
to 
```
py2.7-3.5.8-ssl
py2.7-3.6.2-ssl
py3.8-3.5.8-ssl
py3.8-3.6.2-ssl
py2.7-3.5.8
py2.7-3.6.2
py3.8-3.5.8
py3.8-3.6.2
```
This makes it more clear that the `True`/`False` correlated to enabling-SSL

Change ddev test env names

---

mysql/datadog_checks/mysql/statement_samples.py
mysql/datadog_checks/mysql/statements.py

The tracked_method decorator is failing to track methods in two classes, MySQLStatementMetrics and MySQLStatementSamples, because the self._check variable is not available. This sets self._check on each
of those classes. 
[Jira bug report](https://datadoghq.atlassian.net/browse/DBM-2204)
[Related support ticket](https://datadoghq.atlassian.net/browse/SDBM-398)

[DBM-2204] mysql: set self._check instance variables to make tracking work

---

mcache/README.md

Added a line in the doc to use binary or auto as memcache binding protocol
Added a line in the mcacge doc to use binary or auto as memcache binding protocol instead of ascii
Internal support case

Update mcache doc

---

kafka_consumer/datadog_checks/kafka_consumer/client/confluent_kafka_client.py
kafka_consumer/datadog_checks/kafka_consumer/client/generic_kafka_client.py
kafka_consumer/datadog_checks/kafka_consumer/client/kafka_client.py

Remove some unused functions

---

kafka_consumer/tests/python_client/__init__.py
kafka_consumer/tests/python_client/test_integration.py
kafka_consumer/tests/python_client/test_unit.py
kafka_consumer/tests/test_e2e.py
kafka_consumer/tests/test_integration.py
kafka_consumer/tests/test_unit.py

Update all the tests to use the kafka_instance instead of a custom one. 
If we use a custom one, we do not provide all the necessary parameters such as: 
- Which client to use
- Authentication

Update all the tests to use the `kafka_instance` instead of a custom one

---

kafka_consumer/datadog_checks/kafka_consumer/client/confluent_kafka_client.py
kafka_consumer/datadog_checks/kafka_consumer/client/generic_kafka_client.py

Implement the `request_metadata_update` method

---

postgres/datadog_checks/postgres/relationsmanager.py

Add a deprecation notice to make clear to authors and contributors that our intention is to migrate query execution to a new API. These types of metrics that use per-DB views should be implemented using autodiscovery.

Add deprecation notice to relmetrics module

---

kafka_consumer/datadog_checks/kafka_consumer/client/confluent_kafka_client.py
kafka_consumer/datadog_checks/kafka_consumer/client/generic_kafka_client.py
kafka_consumer/datadog_checks/kafka_consumer/client/kafka_client.py
kafka_consumer/datadog_checks/kafka_consumer/client/kafka_python_client.py
kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
kafka_consumer/tests/test_unit.py

Remove the `get_dict` methods from the clients

---

iis/datadog_checks/iis/check.py

Prevents `iis.*_up` ServiceChecks with `site:`/`app_pool:` = `include`/`exclude` - when used in below example configuration.
```
-  sites:
include:
- Default Web Site
- foo
- bar
app_pools:
include_fast:
- baz
```
- AGENT-9272
This only addresses the `include`/`exclude` tags when a mapping is provided but does not take into consideration if regex patterns are provided.

fix `iis.*_up` service check when configured using a mapping

---

oracle/datadog_checks/oracle/queries.py
oracle/tests/test_unit.py

Update GV$PROCESS query to better handle multiple records with the same program value
This PR fixes the GV$PROCESS query so that the program value in each record returned is unique.
The current query returns multiple records with the same program value. And since program is the only tag, only one of the values is reported, and all the other values are omitted within DataDog. Based on my testing, only the values associated with the last record of a given program name is reported. This leads to incorrect calculations of PGA information in the database.
- [changelog/Fixed ] PR must have `changelog/` and `integration/` labels attached

Update GV$PROCESS query

---

sqlserver/assets/configuration/spec.yaml
sqlserver/datadog_checks/sqlserver/config_models/defaults.py
sqlserver/datadog_checks/sqlserver/connection.py
sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
sqlserver/datadog_checks/sqlserver/statements.py

Changes a default value for the `command_timeout` to prevent instances with large SQL caches from timing out. 10s should still provide reasonable protection from "runaway" SQL queries.
This change becomes more important in the context of https://github.com/DataDog/integrations-core/pull/14033, which results in a larger number of results scanned, which happens 6X less frequently.

Increase command_timeout default from 5s to 10s to prevent timeouts on instances with large SQL caches

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py

Conditional enablement with an environment variable is much easier for CI configuration than formatting a command with the flag

Allow enabling of tracing for tests with an environment variable

---

ecs_fargate/README.md

Remove the brief step to add a 8126 port mapping for the Agent container in ECS Fargate.
Setting this isn't actually necessary. When setting a container port in ECS Fargate, ECS will _actually_ create this as a `hostPort` like:
```json
"portMappings": [
{
"hostPort": 8126,
"protocol": "tcp",
"containerPort": 8126
},
```
It works in either case. But given the traces from the application container will hit the Agent container in the same task regardless - this isn't necessary and removing this step for simplicity.

Remove portMapping instructions for APM in Fargate

---

directory/datadog_checks/directory/directory.py
directory/tests/test_directory.py

Deduplicate symlink/target files that contribute to directory size
AGENT-8861 - bloated `system.disk.directory.bytes`

Deduplicate symlink/target files that contribute to directory size

---

.github/workflows/validations.yaml

We have close parity with validations in the `datadog-assets` github check that runs the manifest validations and reports errors back. Now we can stop double running validations and allow this type of error to only come back through the `datadog-assets` check.

Remove manifest validation from CI

---

.github/workflows/publish-test-results.yml

The workflow must be on master first in order to test:
- https://github.com/DataDog/integrations-core/pull/14187
- https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches

Add job to publish pull request test results

---

.github/workflows/pr-test.yml
.github/workflows/pr.yml

The trigger I'm testing requires that the called workflows are already on the default branch https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
> This event will only trigger a workflow run if the workflow file is on the default branch.

Add minimal workflows for CI testing

---

kubelet/datadog_checks/kubelet/summary.py
kubelet/metadata.csv
kubelet/tests/test_kubelet.py

* Retrieves memory usage from `/stats/summary` for containers, when `/metrics/cadvisor` content is not available (i.e. Rancher Kubernetes Engine 1.24.x)
* Adds `kubernetes.kubelet.memory.usage`, the memory usage of the `kubelet` when present in syscontainers
* Adds `kubernetes.runtime.memory.usage`, the memory usage of the `runtime` container (when present in syscontainers)
* https://datadoghq.atlassian.net/browse/CONT-3666 : in newer versions of RKE, the cAdvisor output is not full, and prevents the Agent from parsing it. A workaround is to use `/stats/summary` as the main source of data to retrieve some metrics, such as `kubernetes.cpu.usage.total`, but some metrics such as `kubernetes.memory.usage` would still not be collected, as the `kubelet` check does not collect …

Adds container memory usage metrics from /stats/summary and kubelet memory usage

---

mysql/datadog_checks/mysql/innodb_metrics.py
mysql/hatch.toml

This PR fixes the parsing of InnoDB pending flush metrics for modern MariaDB hosts (10.8+).
We have been observing the following error when metrics are collected from our MariaDB host:
```
2023-01-09 10:25:16 UTC | CORE | ERROR | (pkg/collector/worker/check_logger.go:69 in Error) | check:mysql | Error running check: [{"message": "list index out of range", "traceback": "Traceback (most recent call last):\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py\", line 1122, in run\n    self.check(instance)\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/mysql/mysql.py\", line 248, in check\n    raise e\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/mysql/mysql.py\", line 229, in …
```

Fix MariaDB InnoDB pending flush metric parsing

---

network/datadog_checks/network/network.py
network/tests/test_linux.py
network/tests/test_network.py

Uses `shutil.which` in place of `distutils.spawn.find_executable` for Python 3 to remove dependency on `distutils`
[AI-2974](https://datadoghq.atlassian.net/browse/AI-2974). We want to get rid of `distutils` because its version in the stdlib is essentially deprecated, and the replacement used by `setuptools` increases the agent's memory footprint. This is the only place in core integrations that uses `distutils` _directly_.
The reason that `distutils` is still used for Python 2 is that `shutil.which` was added on Python 3.3. There are less concerns about the use of `distutils` in Python 2, so missing a simple stand-in, it's fine to keep the statu quo there.
I haven't found a good way to add an integration test for this, so I've done a simple manual sanity check on the e2e environment to …

Remove `distutils` dependency from python 3 version of the check

---

apache/assets/configuration/spec.yaml
apache/datadog_checks/apache/data/conf.yaml.example
datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/default.yaml
nginx/datadog_checks/nginx/data/conf.yaml.example
snowflake/README.md
snowflake/datadog_checks/snowflake/data/conf.yaml.example
sqlserver/assets/configuration/spec.yaml
sqlserver/datadog_checks/sqlserver/data/conf.yaml.example

Fix a typo in the `disable_generic_tags` option description
Found this working on a support case

Fix a typo in the `disable_generic_tags` option description

---

docs/dev/check_references.md

Editorial review on the existing doc page + adds two shortcodes for cleaner table formatting: `integration-assets-reference.md` and `integration_categories.md`.
DOCS-4924
https://docs-staging.datadoghq.com/alai97/integrations-assets-reference-categories-update/developers/integrations/check_references/
To be reviewed with https://github.com/DataDog/documentation/pull/17294.

DOCS-4924 Integration Assets Reference Doc Updates + Adds Manifest File and Classifier Tag Shortcodes

---

gitlab/datadog_checks/gitlab/gitlab.py
gitlab/tests/test_integration.py

Add tags to the main service check even when its status is critical
Spotted working on the revamp.

Add missing tags when the service check is critical

---

gitlab/assets/configuration/spec.yaml
gitlab/datadog_checks/gitlab/config_models/defaults.py
gitlab/datadog_checks/gitlab/config_models/instance.py

Add the `prometheus_endpoint` option to the models but not to the config file. 
There's a super secret not documented alias for the `prometheus_url` option called `prometheus_endpoint` (see [this](https://github.com/DataDog/integrations-core/blob/26ad0e95a12582220390d04dd3faf9bb76687ee2/gitlab/datadog_checks/gitlab/gitlab.py#L82)). It's not a big deal but with the revamp we will validate the config with `pydantic` so I'll need to have this field in the models. We do not want to make it appear in the official config file though.

Add the `prometheus_endpoint` option to the models

---

gitlab/assets/configuration/spec.yaml
gitlab/datadog_checks/gitlab/config_models/defaults.py
gitlab/datadog_checks/gitlab/data/conf.yaml.example

Fix the `health_service_check` config option to `False` by default in the config file.
Because this is its default value in the code: https://github.com/DataDog/integrations-core/blob/d66a31a9a9fe2cd3d45e2a433f57b329747345ac/gitlab/datadog_checks/gitlab/gitlab.py#L94

Fix the `health_service_check` config option

---

.github/workflows/master.yml
.github/workflows/nightly-base-package.yml
.github/workflows/nightly-py2.yml
.github/workflows/validate.yml
.github/workflows/weekly-latest.yml

I noticed master kept getting canceled, this was unintentional

Only cancel concurrent workflows for pull requests

---

coredns/assets/configuration/spec.yaml
coredns/datadog_checks/coredns/data/auto_conf.yaml
coredns/datadog_checks/coredns/data/conf.yaml.example

Fix the `prometheus_url` and `openmetrics_endpoint` descriptions.
There's no `openmetrics_url` config option (not even as an alias), only `openmetrics_endpoint`.

Fix the url descriptions in the config file

---

.ddev/ci/scripts/singlestore/linux/55_set_license_secret.sh

We want both CI pipelines to run successfully in parallel for a day or two in order to accurately compare stats

Fix SingleStore CI script for Azure Pipelines

---

.github/workflows/test-target.yml

pipx somehow is not respecting the cache. removing it is fine since we already install ddev this way also

Fix caching of mitmproxy dependencies

---

cilium/manifest.json
istio/manifest.json

Add Process signatures for Cilium
https://datadoghq.atlassian.net/jira/software/c/projects/AI/boards/197?modal=detail&selectedIssue=AI-2891&assignee=61d602cda54af900697e79ba

add process signatures for cilium

---

postgres/datadog_checks/postgres/statement_samples.py

This PR adds cloud_metadata fields to all DBM event payloads, this adds necessary context in order link DBM event data with related cloud resource data in our backend.
The goal here is to allow customers to filter event data by a new universal tag database_instance, which will be applied across DBM and cloud telemetry.

[Unified Instance Tagging]: Add cloud_metadata to DBM event payloads

---

singlestore/README.md

Fixes a docs validation violation that all region shortcodes must be wrapped in HTML partial comments
As we start to allow more strict validations, docs has put in place this validation and this was the only integration in this repo that didn't comply. 
Here's an example of another integration that does have this - https://github.com/DataDog/integrations-core/blob/fca5670cf5d56df3f8ba197cb3aa4fa26a903e74/twistlock/README.md?plain=1#L72

Update singlestore to pass docs validation

---

.github/workflows/submit-traces.yml
ddev/src/ddev/utils/scripts/ci_matrix.py

https://docs.python.org/3/library/fnmatch.html
> Note that the filename separator ('/' on Unix) is not special to this module.

Fix edge case in CI matrix construction

---

snmp/assets/dashboards/interface_performance.json

Renaming some widget titles to use "Byte" instead of "Octet"

NDM: Rename octets to bytes

---

.github/workflows/release-hash-check.py

Fixes a check for an empty list in the `release-hash-check.py` script that runs on CI.
I've encountered this error on CI more than once:
```
File ".github/workflows/release-hash-check.py", line 27, in <module>
link_file = updated_link_files[0]
IndexError: list index out of range
```
Looking at the code I saw that the check that's supposed to check if the `updated_link_files` is empty was actually checking for negative length (!) so it wasn't really capturing this error condition. This way at least we'll get a more meaningful error message.

Fix length check in release-hash-check.py script

---

LICENSE-3rdparty.csv

This fix https://github.com/DataDog/integrations-core/pull/14358 was not available when this https://github.com/DataDog/integrations-core/pull/14354 was open and since the config validation happens first the license error was not seen

Sync third-party licenses metadata

---

tls/assets/configuration/spec.yaml
tls/datadog_checks/tls/config_models/instance.py
tls/datadog_checks/tls/data/conf.yaml.example
tls/datadog_checks/tls/tls_remote.py
tls/tests/compose/Dockerfile
tls/tests/compose/docker-compose.yml
tls/tests/conftest.py
tls/tests/test_remote.py

This PR adds support for StartTLS implementation of Mysql protocol
Similar to PR https://github.com/DataDog/integrations-core/pull/12596 we need to monitor SSL/TLS certificate expiration dates on remote Mysql servers
Had to increase sleep from 5 to 20 seconds in tls/tests/conftest.py to give Mysql docker container time to initialize default database. More details on https://hub.docker.com/_/mysql in section "No connections until MySQL init completes"

TLS check: implement StartTLS protocol for Mysql

---

ecs_fargate/README.md

Fixes ecs_fargate readme so that it shows up correctly in app as well as on docs site
DOCS-3931
In-app: https://app.datadoghq.com/integrations/aws-fargate
Docs: https://docs.datadoghq.com/integrations/ecs_fargate/

DOCS-3931 fix region-param tags showing on in-app docs

---

snmp/tests/test_e2e_core_metadata.py

Fix e2e test due to subnet being now optional
We added `omitempty` to subnet field here:
https://github.com/DataDog/datadog-agent/pull/16360/files#diff-e7320c03af9cecaf5519e47796b924d474112f6d1c07c4b457b042145f2371d5R35

Fix e2e test due to subnet being now optional

---

sqlserver/CHANGELOG.md

Remove duplicate changelog entry. These were both already released in 10.1.2 and 10.1.3:
https://github.com/DataDog/integrations-core/blob/master/sqlserver/CHANGELOG.md#1013--2023-02-01--agent-7430

remove duplicate changelog entry

---

postgres/datadog_checks/postgres/postgres.py
postgres/datadog_checks/postgres/statement_samples.py
postgres/datadog_checks/postgres/statements.py
postgres/datadog_checks/postgres/util.py
postgres/hatch.toml
postgres/tests/test_custom_metrics.py
postgres/tests/test_deadlock.py
postgres/tests/test_e2e.py
postgres/tests/test_pg_integration.py
postgres/tests/test_pg_replication.py
postgres/tests/test_relations.py
postgres/tests/test_replication_slot.py
postgres/tests/test_statements.py
postgres/tests/test_unit.py

This change builds off of the work that was done in https://github.com/DataDog/datadog-agent/pull/16102 to support the unified instance tagging effort. The change does the following:
1. Parses the `cloud_metadata` config, if set by users, and adds the related `dd.internal.resource:<resource_type>:<resource_name>` tag to all metrics emitted by the default integration.
2. Emits a `database_instance` resource tag (`dd.internal.resource:database_instance:<resolved_hostname>`) regardless, which allows us to relate all DBM, system, etc metrics to the default integration metrics emitted.
**Note:** these metrics are _internal_ to datadog && metrics-intake will use them to resolve resources as well as set the `database_instance` (and `<resource_type>`, if applicable) tag on all metrics ingested …

Send resource_type/name for postgres integration metrics

---

kafka_consumer/assets/configuration/spec.yaml
kafka_consumer/datadog_checks/kafka_consumer/client.py
kafka_consumer/datadog_checks/kafka_consumer/config.py
kafka_consumer/datadog_checks/kafka_consumer/config_models/defaults.py
kafka_consumer/datadog_checks/kafka_consumer/config_models/instance.py
kafka_consumer/datadog_checks/kafka_consumer/data/conf.yaml.example
kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
kafka_consumer/tests/test_integration.py

Remake of https://github.com/DataDog/integrations-core/pull/14193
This PR adds a new config option called `consumer_groups_regex`. This functions similarly to `consumer_groups` to allow configuration of consumer groups, topics, and partitions to monitor, however this allows regex strings to be used. 
This will be merged to `master` after https://github.com/DataDog/integrations-core/pull/13918 is merged.
Feature request
When `monitor_unlisted_consumer_groups` is set to `True`, then both `consumer_groups` and `consumer_groups_regex` will be ignored. 
When `consumer_groups` and `consumer_groups_regex` are both used, then consumer groups from both config options will be collected.

Implement regex for consumer_groups

---

mysql/datadog_checks/mysql/activity.py
mysql/datadog_checks/mysql/config.py
mysql/datadog_checks/mysql/const.py
mysql/datadog_checks/mysql/mysql.py
mysql/datadog_checks/mysql/statements.py
mysql/hatch.toml
mysql/tests/tags.py
mysql/tests/test_mysql.py
mysql/tests/test_query_activity.py
mysql/tests/test_statements.py
mysql/tests/test_unit.py

This change builds off of the work that was done in https://github.com/DataDog/datadog-agent/pull/16102 to support the unified instance tagging effort. The change does the following:
1. Parses the `cloud_metadata` config, if set by users, and adds the related `dd.internal.resource:<resource_type>:<resource_name>` tag to all metrics emitted by the default integration.
2. Emits a `database_instance` resource tag (`dd.internal.resource:database_instance:<resolved_hostname>`) regardless, which allows us to relate all DBM, system, etc metrics to the default integration metrics emitted.
**Note:** these metrics are _internal_ to datadog && metrics-intake will use them to resolve resources as well as set the `database_instance` (and `<resource_type>`, if applicable) tag on all metrics ingested …

Send resource_type/name for mysql integration metrics

---

mysql/README.md

Removing MariaDB as fully drop-in replacement for MySQL as newer versions seem to not be so and causing issues with the standard and DBM integration.
Increase number of support issues showing this.

Remove MariaDB compatibility in docs

---

gitlab/README.md
gitlab/assets/configuration/spec.yaml
gitlab/datadog_checks/gitlab/config_models/defaults.py
gitlab/datadog_checks/gitlab/data/conf.yaml.example

QA for https://github.com/DataDog/integrations-core/pull/14273
Reference to the legacy implementation should be just on the README.
Related fix on coredns where I believe the example was taken from https://github.com/DataDog/integrations-core/pull/14401

Fix gitlab documentation

---

kafka_consumer/datadog_checks/kafka_consumer/client.py
kafka_consumer/datadog_checks/kafka_consumer/config.py
kafka_consumer/tests/test_integration.py
kafka_consumer/tests/test_unit.py

It moves code that relates to config to the `KafkaConfig` class for better separation of concerns and more consistency.
QA plus preparation for follow-up changes involving the logic for consumer group filtering.

Move all configuration validation to config class

---

mysql/datadog_checks/mysql/mysql.py
mysql/tests/tags.py
mysql/tests/test_mysql.py
mysql/tests/test_unit.py

While taking over PR [14333](https://github.com/DataDog/integrations-core/pull/14333), I made the wrong call when addressing the end to end test failure related to the internal resource tags. Instead of removing the resources from service checks that we emit, we actually want to keep the resource tags so that the service check metrics like `check_run.postgres.can_connect.ok` have resources set on them.

Fix resources not sent on service check metrics

---

datadog_checks_dev/pyproject.toml

Python 2 is no longer supported and our tests are failing https://virtualenv.pypa.io/en/latest/changelog.html#v20-22-0-2023-04-19

Limit the version of `virtualenv` to continue testing Python 2

---

postgres/datadog_checks/postgres/statement_samples.py

Fixes DBM's query sampler which produces constant errors about undefined parameters.
e.g.
```
ERROR | (pkg/collector/python/datadog_agent.go:130 in LogMessage) | postgres:5579dc5d4143c336 | (tracking.py:84) | dd.trace_id=14998057449499886562 dd.span_id=15167319973303942127 | operation _run_explain error
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/utils/tracking.py", line 71, in wrapper
result = function(self, *args, **kwargs)
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/postgres/statement_samples.py", line 585, in _run_explain
cursor.execute(
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/ddtrace/contrib/dbapi/__init__.py", line 110, in execute
return …
```

Fix query sampler producing constant errors about undefined parameters

---

kubernetes_state/metadata.csv

This is a quick PR to change the name of the metric `kubernetes_state.persistentvolume.by_phase` to `kubernetes_state.persistentvolumes.by_phase` (added "s"). This is because the metric appears to have been added without an "s" when it was first noted in the docs in 2018 ([see here](https://github.com/DataDog/integrations-core/commit/e4b533a319e889ea3f34e610fb54845a2bb2d5b0#diff-46e3085ae5f9101b2cf8b9b89e73ea5e483c463bab0da11c55d9bce7229feb8f)) the metric had an "s" but the docs showed no "s."
This has gotten confusing because there _is_ a `kubernetes_state.persistentvolume.by_phase` in KSM core. Customer reached out asking about this seeming disrepency ([card here](https://datadoghq.atlassian.net/browse/CONS-5522)).

Fix metric name for persistentvolume.by_phase

---

rabbitmq/README.md

Add an example of how to scrap the /metrics/detailed endpoint of rabbitmq prometheus plugin in the documentation;
The documentation lacks this information; 
- [] Files changes must correspond to the primary purpose of the PR as described in the title (small unrelated changes should have their own PR)

add rabbitmq /metrics/detailed example

---

mysql/datadog_checks/mysql/statement_samples.py
mysql/datadog_checks/mysql/statements.py

Fix invalid references to `MySQLStatementMetrics.check` and `MySQLStatementSamples.check`
Also incorporating the suggestion from @iliakur in the original PR to use `operator.attrgetter` instead of a custom getter function duplicated in both files.
PR #14146 sets the `_check` attribute in the `MySQLStatementMetrics` and `MySQLStatementSamples` classes, but the original PR #13202 references the `check` attribute, causing the agent to flood the logs with errors:
```
Apr 19 20:12:35 replica1 agent: [collect_per_statement_metrics] invalid tracked_method. failed to get check reference.
Apr 19 20:12:35 replica1 agent: [_get_new_events_statements_current] invalid tracked_method. failed to get check reference.
Apr 19 20:12:35 replica1 agent: [_collect_plans_for_statements] invalid tracked_method. …
```

mysql: fix tracking references to self.check

---

gitlab/hatch.toml
gitlab/tests/compose/docker-compose.yml

Add the ability to use a different image to run the tests.
The official image takes forever to spin up on our M1s. Switching to a arm64 works fine, from ~10 minutes to ~2 minutes.
It's not yet possible to define an environment variable based on the architecture with hatch and I'd like to avoid having some if in the python code so I'm not adding anything to do it automatically

Add the ability to use a different image to run the tests

---

releasenotes/notes/remove-time-scope-dashboard-panels-17d19bddd5365517.yaml

Remove the reno releasenotes folder
We do not use reno in this repository. `ddev` generates the release notes for each integration based on the PRs and their labels.
This was added on [this PR](https://github.com/DataDog/integrations-core/pull/14091).

Remove the reno releasenotes folder

---

.ddev/ci/scripts/kafka_consumer/linux/32_install_kerberos.sh
kafka_consumer/hatch.toml
kafka_consumer/tests/README.md

Build librdkafka from source to run the tests in the CI. 
- It seems that we no longer have OOTB binaries for ubuntu 22.04 that we are using in the CI (GitHub actions). It was working well on azure but I think we were using a different version
- It's needed to be able to run the tests, especially the kerberos tests.
Also works on azure

Fix the `prepare script`

---

kube_apiserver_metrics/tests/test_kube_apiserver_metrics.py
kube_apiserver_metrics/tests/test_kube_apiserver_metrics_1_15.py
kube_apiserver_metrics/tests/test_kube_apiserver_metrics_1_19.py
kube_apiserver_metrics/tests/test_kube_apiserver_metrics_1_23.py
kube_apiserver_metrics/tests/test_kube_apiserver_metrics_1_24.py

* Changes the OpenMetrics test to use a pre-defined fixture
* Cleans the code to remove a lot of `NAMESPACE` entries by modifying the metric during the loop
* Review from @iliakur to clean tests in https://github.com/DataDog/integrations-core/pull/14147

Re-vamps kube_apiserver_metrics tests to match 14147

---

rabbitmq/README.md

The mapping from management cli to prometheus metrics led to a lot of confusion. Customers found the switch between raw prometheus metric names and datadog metric names for the legacy integration particularly confusing. 
At the end of the day customers just wanted to know if a particular metric from the legacy integration was also present in the new integration. This question can be answered just as well by consulting the metadata.csv-generated table with metric descriptions.
This PR removes the confusing table and points the customers to metadata.csv with clear instructions what to look for.

Clearer instructions for migrating to prometheus plugin

---

foundationdb/assets/dashboards/foundationdb_latency_probe.json
foundationdb/assets/dashboards/foundationdb_processes_and_utilization.json
foundationdb/assets/dashboards/foundationdb_transactions_and_queues.json
nginx/assets/dashboards/NGINX-Overview_dashboard.json
sqlserver/assets/dashboards/SQLServer-AlwaysOn_dashboard.json

This PR removes the `id` field from all our integration dashboards' JSON definitions so that they pass the dashboard validation that we are introducing in the Asset Publishing Workflow (see #apw-dashboard-reporting on Slack)
Note that we only accept string `id`s in our dashboard validators, but integration dashboards ids are integer and they are autogenerated on Postgres).
We want to add asset validation for the Asset Publishing Workflow.

[APW] Fix more integration dashboards' json definition

---

sqlserver/datadog_checks/sqlserver/activity.py
sqlserver/datadog_checks/sqlserver/statements.py
sqlserver/datadog_checks/sqlserver/utils.py
sqlserver/hatch.toml
sqlserver/tests/test_activity.py

This PR adds a new utility function `extract_sql_comments`, which parses sql comments from the full sql text & returns them as an array to be added to the activity payloads.
This fix is important for the DBM-APM linking feature because comments are added by tracers, when the feature is enabled, to propagate trace context information from the user's application to DB monitoring.
Due to way we query for the statement text in the [activity query currently](https://github.com/DataDog/integrations-core/blob/master/sqlserver/datadog_checks/sqlserver/activity.py#L55-L59), we are stripping the comments that are being pre-pended to the query by doing this:
```sql
SUBSTRING(qt.text, (req.statement_start_offset / 2) + 1,
((CASE req.statement_end_offset
WHEN -1 THEN DATALENGTH(qt.text)
ELSE …
```

Restore DBM-APM link functionality for SQL Server activity sessions

---

sqlserver/datadog_checks/sqlserver/activity.py
sqlserver/datadog_checks/sqlserver/const.py
sqlserver/datadog_checks/sqlserver/sqlserver.py
sqlserver/datadog_checks/sqlserver/statements.py
sqlserver/tests/test_activity.py
sqlserver/tests/test_integration.py
sqlserver/tests/test_statements.py

This change builds off of the work that was done in https://github.com/DataDog/datadog-agent/pull/16102 to support the unified instance tagging effort. The change does the following:
1. Parses the `cloud_metadata` config, if set by users, and adds the related `dd.internal.resource:<resource_type>:<resource_name>` tag to all metrics emitted by the default integration.
2. Emits a `database_instance` resource tag (`dd.internal.resource:database_instance:<resolved_hostname>`) regardless, which allows us to relate all DBM, system, etc metrics to the default integration metrics emitted.
**Note:** these metrics are _internal_ to datadog && metrics-intake will use them to resolve resources as well as set the `database_instance` (and `<resource_type>`, if applicable) tag on all metrics ingested …

Send resource_type/name for sqlserver integration metrics

---

openmetrics/README.md

Clarifies what formats are supported by the OpenMetrics check ~~and how to configure which format is used.~~
[AI-2416](https://datadoghq.atlassian.net/browse/AI-2416).
The docs don't provide any clarity as to what the actual format that we support by default in the OpenMetrics check is and  the name of the check (OpenMetrics, when we already have a check called Prometheus) doesn't help, considering we're actually assuming Prometheus format by default and not OpenMetrics. It's also not obvious how to enable OpenMetrics spec support (I'll be updating the config template to add some documentation in there as well).
[AI-2416]: https://datadoghq.atlassian.net/browse/AI-2416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Be specific about the exposition formats supported

---

rabbitmq/assets/configuration/spec.yaml
rabbitmq/datadog_checks/rabbitmq/data/conf.yaml.example
rabbitmq/tests/fixtures/mgmt/queues.json
rabbitmq/tests/test_unit.py

1. Docs for `*_regexes` config fields now 100% accurately reflect the implementation/behavior.
2. The unit test for `queues_regexes` reflects the customer's setup for more accurate regression testing.
We realized the documentation for the `*_regexes` fields still didn't quite reflect the behavior, so that's getting updated. The same customer who prompted us to review these fields also had a different setup than I originally captured in my unit test. I'm updating the test as well.

Adjust docs and tests based on customer feedback

---

aerospike/pyproject.toml
amazon_msk/pyproject.toml
arangodb/pyproject.toml
argocd/pyproject.toml
avi_vantage/pyproject.toml
boundary/pyproject.toml
calico/pyproject.toml
cert_manager/pyproject.toml
cilium/pyproject.toml
cockroachdb/pyproject.toml
coredns/pyproject.toml
envoy/pyproject.toml
gitlab/pyproject.toml
haproxy/pyproject.toml
impala/pyproject.toml
istio/pyproject.toml
kong/pyproject.toml
linkerd/pyproject.toml
openmetrics/pyproject.toml
pulsar/pyproject.toml
rabbitmq/pyproject.toml
teamcity/pyproject.toml
temporal/pyproject.toml
vault/pyproject.toml

#14445.
I'm unsure of what the changelog level should be here.

Update minimum datadog base package version

---

ecs_fargate/assets/configuration/spec.yaml

Small PR to change `min_collection_interval.enabled` to `true` instead of `20`.
This value should be `true` or `false`, not an int.

Change ecs_fargate min_collection_interval.enabled to boolean

---

postgres/datadog_checks/postgres/postgres.py
postgres/tests/test_statements.py

Improve Postgres test speed. 
Most of the time is spent sleeping as the job rate limiter will sleep until the next collection interval in test_statements.py tests. By reducing the collection interval, tests for a specific PG + python version goes from ~120s to ~20s.

Improve pg tests speed

---

postgres/datadog_checks/postgres/postgres.py
postgres/datadog_checks/postgres/util.py
postgres/metadata.csv
postgres/tests/common.py
postgres/tests/test_pg_integration.py
postgres/tests/test_pg_replication.py

Create a `postgresql.uptime` metric.
Managed cloud databases will restart servers during maintenance window for minor upgrades. Having the uptime can help to know if a specific server has already been restarted or not.

Create `postgresql.uptime` metric

---

eks_fargate/README.md

This is not a major issue as it will not stop the container or process.
When running Datadog Agent as a sidecar in EKS Fargate, the documented ClusterRole permissions are not enough for endpoints, resulting in an error.
From [Install the Datadog Agent on Kubernetes](https://docs.datadoghq.com/ja/containers/kubernetes/installation/?tab=daemonset), you can see the ClusterRole of the Agent installed on k8s. I believe this is necessary because the endpoints are defined in the ClusterRole of the Agent that will be installed on k8s from [Install the Datadog Agent on Kubernetes]().
There may be other permissions required in addition to this modification.
error log
```
2023-02-01 00:00:00 UTC | CORE | ERROR | (pkg/util/kubernetes/apiserver/apiserver_kubelet.go:28 in NodeMetadataMapping) | Could …
```

Add the necessary permissions to make the Agent work with EKS Fargate

---

kubelet/datadog_checks/kubelet/summary.py
kubelet/metadata.csv
kubelet/tests/test_kubelet.py

Add following metrics to Kubelet check:
```
kubernetes.node.filesystem.usage
kubernetes.node.filesystem.usage_pct
kubernetes.node.image.filesystem.usage
kubernetes.node.image.filesystem.usage_pct
```
Based on filesystem stats available in `/stats/summary`. Especially useful on Windows where access to host filesystem metrics is not possible.

[kubelet] Add node filesystem stat from stats/summary

---

sqlserver/hatch.toml

This PR removes SQL Server 2012 / odbc driver on Windows for our CI test matrix. We are doing this for the following reasons:
1. These tests were consistently causing our CI fail for `sqlserver.database.*` metrics -> user db tags (e.g. `datadog_test`) were not being properly added to these metrics. This means, this was failing for a small subset of metrics on a very old version of SQL Server, but it was blocking us from being able to **merge any PR** for the integration
2. SQL Server 2012 was officially EOL'd on [July 22, 2022](https://learn.microsoft.com/en-us/lifecycle/products/microsoft-sql-server-2012), and is no longer supported by AWS, Azure and other major cloud providers

Remove CI support for sqlserver 2012 & odbc on windows

---

sqlserver/datadog_checks/sqlserver/sqlserver.py
sqlserver/hatch.toml
sqlserver/tests/test_integration.py
sqlserver/tests/test_unit.py

This PR fixes a bug where the `resolved_hostname` was not properly set on default integration metrics for Azure SQL DB OR for users that relied on using the `reported_hostname` feature. This resulted in metrics emitted from the default integration to have an incorrect `hostname` tag. This was due to the order in which things were being initialized in the agent when the check was started.
For example, these metrics are coming from the same host but have different `host` tag values. The first is a metric from the default integration, which is using the value that was set as `host` in the instance config, while the other is a DBM metric using the host value we remapped during the initialization call in `resolved_hostname`:
Below, shows the tag being applied correctly on a default integration …

Properly initialize resolved_hostname so it is set consistently across dbm and default integration metrics

---

kafka_consumer/hatch.toml
kafka_consumer/tests/docker/noauth/docker-compose.yaml
kafka_consumer/tests/docker/ssl/docker-compose.yaml

- Disable Kraft by default in the e2e environment
- Reverts https://github.com/DataDog/integrations-core/pull/14481 so we are still getting the system updates
- Kraft is now enabled by default with the containers we are using.

Disable Kraft by default

---

datadog_checks_downloader/README.md
datadog_checks_downloader/datadog_checks/downloader/cli.py
datadog_checks_downloader/datadog_checks/downloader/download.py
datadog_checks_downloader/tests/conftest.py
datadog_checks_downloader/tests/test_downloader.py

Add an option in the checks downloader to disable TUF and in-toto verification
https://datadoghq.atlassian.net/browse/SINT-845
In case TUF or in-toto verification fails during the downloading of an integration and the user is sure that this is due to a bug and not to an attack, this option will make the user able to install the integration nonetheless.
An additional pull request may be necessary in the Agent repository for the user to able to use this option through the `datadog-agent integration install` command.

Add an option to bypass TUF and in-toto verification in the checks downloader

---

flink/README.md

Updates the Flink integration docs from 1.9 (no longer supported) to 1.16 (latest stable).
The docs are out-dated, and in fact do not work in 1.16.0.
The commit messages contain details for every change.

Update Flink integration docs to 1.16

---

sqlserver/datadog_checks/sqlserver/activity.py
sqlserver/datadog_checks/sqlserver/statements.py

These fields should be forwarded to the backend for all events so we can properly set internal resource tags on event payloads for Azure SQL DB
This is needed for unified instance tagging, which will allow customers to view all metrics/related metrics for their cloud dbs via a single tag, `database_instance`

Add sqlserver engine editition && version to DBM event payloads

---

elastic/datadog_checks/elastic/elastic.py

We use essentially the same logic to convert ES health statuses to DD statuses in two places. This PR unifies the two approaches.

Refactor: reduce duplication, condense method implementation

---

docs/developer/setup.md

This PR adds instructions about using unreleased `datadog_checks_dev` changes in `ddev`.
The formal process of applying `datadog_checks_dev` changes to `ddev` involves making a PR just for the `datadog_checks_dev` change, making another PR for the release, and then creating another PR to use the latest version of `datadog_checks_dev` in `ddev`. This is inconvenient, and also causes CI to fail in the meantime before the changes are applied.

Add note about development datadog_checks_dev for ddev

---

datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/scraper.py
openmetrics/tests/test_openmetrics.py

It looks like https://github.com/DataDog/integrations-core/pull/14445 introduced a bug that causes empty openmetrics scrapes to fail.
Without the fix, the added test fails as follows:
```
tests/test_openmetrics.py:110: in test_openmetrics_empty_response
dd_run_check(check)
../datadog_checks_dev/datadog_checks/dev/plugin/pytest.py:228: in run_check
raise Exception('\n'.join(exc_lines))
E   Exception:
E     File "/Users/ethan.lowman/go/src/github.com/DataDog/integrations-core/datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/scraper.py", line 289, in parse_metrics
E       line_streamer = chain([next(line_streamer)], line_streamer)
E   StopIteration
E
E   The above exception was the direct cause of the following exception:
E
E   Traceback …
```

Fix bug on empty openmetrics scrape response

---

datadog_checks_base/datadog_checks/base/utils/db/core.py
datadog_checks_base/datadog_checks/base/utils/db/query.py
datadog_checks_base/datadog_checks/base/utils/db/transform.py

Add a `tag_not_null` column type which doesn't report the tag if the value is none. 
This is needed for https://github.com/DataDog/integrations-core/pull/14500. This PR will add the `partition_of` tag to metrics but we only want to set this tag if the table is a partition.

Create `tag_not_null` type which doesn't set the tag when tag value is none

---

gitlab/tests/conftest.py

Use OMv2 by default in the e2e environment.
When spinning up the e2e environment, we were using an OMv1 instance. We now want to move to OMv2 by default.
It's still possible to edit the configuration once the environment is up and running with the `ddev env edit` and `ddev env reload` commands to switch back to OMv1 if needed

Use OMv2 by default in the e2e environment

---

ddev/hatch.toml

`vcrpy` currently cannot use the latest version of `urllib3` (v2.0.0 and up) due to the following error: 
```
AttributeError: module 'urllib3.connectionpool' has no attribute 'VerifiedHTTPSConnection'
```
This pin can be removed once `vcrpy` fixes this bug.
Failing CI: https://github.com/DataDog/integrations-core/actions/runs/4894505518/jobs/8738847769
`vcrpy` Github issue: https://github.com/kevin1024/vcrpy/issues/688
`urllib3` changelog: https://urllib3.readthedocs.io/en/stable/changelog.html

Pin urllib3

---

arangodb/datadog_checks/arangodb/check.py
azure_iot_edge/datadog_checks/azure_iot_edge/check.py
calico/datadog_checks/calico/check.py
cilium/datadog_checks/cilium/cilium.py
consul/datadog_checks/consul/consul.py
coredns/datadog_checks/coredns/coredns.py
datadog_cluster_agent/datadog_checks/datadog_cluster_agent/check.py
etcd/datadog_checks/etcd/etcd.py
external_dns/datadog_checks/external_dns/external_dns.py
impala/datadog_checks/impala/check.py

This PR adds missing `DEFAULT_METRIC_LIMIT = 0` for all OpenMetricsV1 and V2 checks.
There should be no metric limit for any non-custom OpenMetrics checks.
This is part 1 of adding validations for OpenMetrics metric limits. The actual validations are added in https://github.com/DataDog/integrations-core/pull/14528

Add DEFAULT_METRIC_LIMIT for OpenMetrics-based checks

---

postgres/assets/configuration/spec.yaml
postgres/datadog_checks/postgres/config.py
postgres/datadog_checks/postgres/config_models/instance.py
postgres/datadog_checks/postgres/data/conf.yaml.example
postgres/tests/test_statements.py

This updates the `azure`'s `name` configuration to `fully_qualified_domain_name` which is a more accurate name for the information that should be set in that field. This also updates the documentation for that field so that it's clear on the value that is expected. 
Note that this change is backward compatible but for the functionality to work on prior releases, the `azure.name` has the same requirements as with this change and needs to be the instance's fully qualified domain name. 
While doing work to integrate all the pieces for database unified instance tagging, we realized that the configuration wasn't accurately reflecting the input required for the linking to happen.

Rename azure.name configuration key to azure.fully_qualified_domain_name

---

postgres/datadog_checks/postgres/postgres.py
postgres/tests/common.py
postgres/tests/test_pg_integration.py

Don't use `pg_stat_get_wal_receiver` if an aurora instance is detected.
Calling `pg_stat_wal_receiver` on an aurora instance will return the following:
```
select * from pg_stat_wal_receiver;
ERROR:  Function pg_stat_get_wal_receiver() is currently not supported in Aurora
```
Which will be reported as an agent error
```
error: - | (core.py:80) | Error querying pg_stat_wal_receiver: Function pg_stat_get_wal_receiver() is currently not supported in Aurora
```
Fix https://github.com/DataDog/integrations-core/issues/14498

Don't try to collect wal receiver if aurora is detected

---

rabbitmq/datadog_checks/rabbitmq/openmetrics/check.py

Adds `DEFAULT_METRIC_LIMIT = 0` to rabbitmq's OpenMetrics check.
This was originally missed since the [openmetrics validation CLI command](https://github.com/DataDog/integrations-core/pull/14528) didn't account for check files in subdirectories of the package directory.

Add metric limit for rabbitmq

---

postgres/assets/configuration/spec.yaml
postgres/datadog_checks/postgres/data/conf.yaml.example
postgres/datadog_checks/postgres/statement_samples.py
postgres/tests/test_statements.py

Enables the explain parameterized query feature introduced in this [PR](https://github.com/DataDog/integrations-core/pull/13434) by default.

Enable explain parameterized query feature by default

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py

Alert was added previously to the [catalog.csv](https://github.com/DataDog/dogweb/blob/prod/integration/system/units_catalog.csv?plain=1#L162), token has also been added

Add `token` and `alert` as valid metric units

---

postgres/hatch.toml

Postgres 9.5 was EOL Feb 2021. This is cleanup.

No longer test postgres 9.5

---

rabbitmq/README.md
rabbitmq/assets/configuration/spec.yaml
rabbitmq/datadog_checks/rabbitmq/data/conf.yaml.example

Part of addressing https://datadoghq.atlassian.net/browse/AGENT-9611, where a customer had suggestions how to improve our documentation.

Expand migration docs

---

calico/README.md
datadog_checks_dev/datadog_checks/dev/tooling/create.py

Fixes some links to the developer tools documentation, which is now on a different page.

(DOCS-5505) Replace broken developer tool links in READMEs

---

mongo/assets/configuration/spec.yaml
mongo/datadog_checks/mongo/config.py
mongo/datadog_checks/mongo/data/conf.yaml.example
mongo/tests/test_config.py
mongo/tests/test_unit.py

Validates that the config doesn't include the `replicaSet` option as we already say that it is not supported. It also fixes the documentation itself where it was incorrectly named `replSet`.
At least one support case where something like this has come up. Also to keep documentation up to date and to enforce in code what's already documented.

Explicitly disallow setting `replicaSet` in the options

---

directory/datadog_checks/directory/directory.py
directory/datadog_checks/directory/traverse.py
directory/tests/test_directory.py

Changes our custom traversal implementation so that it can keep traversing even when there's an error during the traversal (such as not being able to list the contents of a directory due to lack of permissions). I implemented this roughly following [what the stdlib does](https://github.com/python/cpython/blob/79e63e528795c700a8bd198c15f3322ee25ea786/Lib/os.py#L280).
I also tried to clarify futher why we're using our custom `walk` as opposed of directly using `os.walk`, as it required some research to re-discover the reason behind it.
An issue that has come up a few times in support cases.

Continue directory traversal after errors

---

datadog_checks_base/datadog_checks/base/checks/base.py
postgres/assets/configuration/spec.yaml
postgres/datadog_checks/postgres/config.py
postgres/datadog_checks/postgres/config_models/defaults.py
postgres/datadog_checks/postgres/config_models/instance.py
postgres/datadog_checks/postgres/data/conf.yaml.example
postgres/datadog_checks/postgres/metadata.py
postgres/datadog_checks/postgres/postgres.py
postgres/tests/test_metadata.py

This feature adds a new job, `database-metadata`, which requires `dbm`. The job has two main features:
1. Sends cloud_metadata to the DBM backend for internal resource creation (important for unified host tagging)
2. Queries `pg_settings` && forwards this to the backend to be displayed in the DBM UI
An example of the settings in our UI is here:
There are a number of relevant use cases for this, for example:
1.  Engineer who is investigating a degraded database might want to check certain settings
2. Changes in certain settings could cause any number of issues for the database
3. Not all default settings are conducive to certain workloads, we can use this & other metrics to provide insights to users about how to tune/tweak them

Support ingesting pg_settings for `dbm` users

---

gitlab/tests/compose/docker-compose.yml
gitlab/tests/conftest.py

Mount and collect the gitlab logs
- The e2e env was not collecting the logs, so we could not easily test the dashboard with @anjaliDDog 
I could not use the `mount_logs` option from `docker_run` that does it automatically from the `spec.yaml` file because it first creates the files in a temp folder and then mount the files in both containers (here GitLab and the agent). However, GitLab drop the files we created and create other ones. So Here the idea is that I mount the whole temp folder and configure it manually so all files are available

Mount and collect the logs

---

temporal/README.md

Move logs configuration to the setup section so that it can be seen in the "Configure" tab on the integration tile.

Move logs configuration to Setup section so that it's shown in-app

---

vsphere/datadog_checks/vsphere/api_rest.py
vsphere/tests/test_api_rest.py

Adds a try/catch around getting tags from the vsphere API
We found a case where this call can error and we don't want this to fully break metric collection

Add error handling when getting tags from API

---

redisdb/datadog_checks/redisdb/redisdb.py
redisdb/metadata.csv
redisdb/tests/test_default.py
redisdb/tests/test_e2e.py

Adds timing for the ping redis command as a new metric, which can provide a more accurate measure of the actual latency with less extra overhead.
This also changes the timer for the info latency from `process_time` to a proper monotonic wall clock, because the time we want to measure is mainly I/O which is "sleep time" which wouldn't be reflected on `process_time`. It also didn't seem to fix the original problem it was introduced for, as agent load has still been seen to influence this metric.
Possible solution for [AGENT-9517](https://datadoghq.atlassian.net/browse/AGENT-9517).
~~Using `timeit` for the ping command to run it 10 times should be reasonable in most cases and might give us a more accurate value than just doing it once.~~ I discarded this because it's not supported in py2 and …

Add ping latency metric

---

kubernetes_state_core/metadata.csv

Adds description for the two new metrics introduced in [this PR](https://github.com/DataDog/datadog-agent/pull/16699) to the KSM Core Metadata. They are:
`kubernetes_state.secret.count`
`kubernetes_state.configmap.count`

Add new metrics to KSM Core metadata

---

mysql/datadog_checks/mysql/mysql.py
mysql/tests/test_query_activity.py

Currently, if a customer has enabled config options for both `table_size_metrics` and `system_table_size_metrics`, the system table size metrics will overwrite the table size metrics. This change prevents that.  
Customer bug report: table size metrics only showing up for system tables

mysql: don't overwrite table size metrics with sys table size metrics

---

gitlab_runner/assets/configuration/spec.yaml
gitlab_runner/datadog_checks/gitlab_runner/config_models/defaults.py
gitlab_runner/datadog_checks/gitlab_runner/data/conf.yaml.example

Fix some default values in the configuration file for the options: 
- health_service_check
- send_monotonic_counter
the default values are `False`: https://github.com/DataDog/integrations-core/blob/master/gitlab_runner/datadog_checks/gitlab_runner/gitlab_runner.py#L90-L91

Fix some default values in the configuration file

---

LICENSE-3rdparty.csv
datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/pyproject.toml
gitlab/pyproject.toml
gitlab_runner/pyproject.toml
kube_dns/pyproject.toml
kubernetes_state/pyproject.toml

Revert protobuf dep to version prior to #14594
[Failing tests](https://github.com/DataDog/integrations-core/actions/runs/5088179965/jobs/9144388611#step:12:381) after merging to master which somehow the branch's CI missed.

Revert protobuf dependency update

---

postgres/pyproject.toml

https://github.com/DataDog/integrations-core/pull/14581 introduced boto3 as a dep for postgres and wasn't matching the rest of the Agent environment (see https://github.com/DataDog/integrations-core/actions/runs/5092868979/jobs/9154780396)

Fix boto3 dep in postgres to match the Agent's

---

elastic/datadog_checks/elastic/elastic.py
elastic/tests/common.py
elastic/tests/fixtures/templates.json
elastic/tests/test_elastic.py

Correctly compute the templates.count metric
- QA for https://github.com/DataDog/integrations-core/pull/14569 which had no tests
- The previous implementation was dropping elements from the same list we were iterating on, so the index that were removed were not correct because the list was continuously updated. The previous implementation returned 12 instead of 6.

Correctly compute the `templates.count` metric

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/pyproject.toml
datadog_checks_dev/datadog_checks/dev/plugin/hatch/environment_collector.py
datadog_checks_dev/datadog_checks/dev/plugin/tox.py

Backport [pydantic upgrade](https://github.com/DataDog/integrations-core/pull/14594) from `1.10.4` to `1.10.8` to 7.45.x.
https://github.com/pydantic/pydantic/issues/5824

Backport pydantic 1.10.8 upgrade to 7.45

---

nginx/assets/dashboards/NGINX-Overview_dashboard.json

This PR updates the NGINX overview dashboard to remove `nginx_log_count_by_status`, since this is not a metric currently collected in the check.
Old:
New:

Fix NGINX overview dashboard

---

datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/base.py

Downgrade an info log to debug
We have this info log each time the check runs

Downgrade an info log to debug

---

.github/workflows/pr.yml

Run CI tests on PRs that do not target master
Tests were not running, spotted on this stack https://github.com/DataDog/integrations-core/pull/14627

Run CI tests on PRs that do not target master

---

datadog_checks_base/tests/base/checks/openmetrics/test_legacy/test_openmetrics.py
datadog_checks_base/tests/base/checks/prometheus/test_prometheus.py

Mock out http calls on flaky tests.
We have been getting pretty consistent timeouts on tests relying on hitting httpbin.org ([example](https://github.com/DataDog/integrations-core/actions/runs/5091948690/jobs/9152666896#step:12:1548)). As it turns out, after a bit of research on what these tests actually test, doing the actual http request is not really necessary and can be mocked away without any loss in terms of what gets tested.

Mock out httpbin.org responses to fix flaky tests

---

gitlab_runner/metadata.csv

Add the `jobs_total` metric in the metadata file
This metric is missing. It was added a long time ago ([here](https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/1018))

Add the `jobs_total` metric in the metadata file

---

docs/dev/log_integration.md

Adds a previous FAQ as a new doc page in the Integrations section of the Developers doc set.
DOCS-5515
https://docs-staging.datadoghq.com/alai97/log-integration-guide-to-page/developers/integrations/log_integration/

DOCS-5515 Adds Create a Log Integration Documentation

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/pyproject.toml
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/pyproject.toml
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/pyproject.toml

This PR updates the minimum datadog-checks-base version to 31.0.1 (same version in Agent 7.45) for new integrations after 7.45.0 is released.
Required after each release.

Update minimum base check version for templates

---

aerospike/hatch.toml
azure_iot_edge/hatch.toml
citrix_hypervisor/hatch.toml
cloud_foundry_api/hatch.toml
datadog_checks_base/hatch.toml
dns_check/hatch.toml
glusterfs/hatch.toml
ibm_mq/hatch.toml
marklogic/hatch.toml
mysql/hatch.toml
postgres/hatch.toml
rethinkdb/hatch.toml
singlestore/hatch.toml
snmp/hatch.toml
snowflake/hatch.toml
voltdb/hatch.toml
vsphere/hatch.toml
wmi_check/hatch.toml

https://github.com/DataDog/integrations-core/pull/14689 was a necessary fix but new versions of Mypy do not support Python 2
This will be required soon anyway as part of the process to only support Python 3 and use actual type annotations

Disable type checking for integrations that support Python 2

---

clickhouse/datadog_checks/clickhouse/data/conf.yaml.example
datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/db.yaml
mysql/datadog_checks/mysql/data/conf.yaml.example
oracle/datadog_checks/oracle/data/conf.yaml.example
sap_hana/datadog_checks/sap_hana/data/conf.yaml.example
singlestore/datadog_checks/singlestore/data/conf.yaml.example
snowflake/datadog_checks/snowflake/data/conf.yaml.example
sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
teradata/datadog_checks/teradata/data/conf.yaml.example
vertica/datadog_checks/vertica/data/conf.yaml.example
voltdb/datadog_checks/voltdb/data/conf.yaml.example

This PR updates the `custom_queries` option in `db.yaml` to include the multiple tag types available to configure. 
There are currently three possible tag types: `tag`, `tag_list`, and `tag_not_null`.
https://github.com/DataDog/integrations-core/pull/14503 added `tag_not_null`, although neither this nor `tag_list` are documented for contributors/custom query users.

Update custom_queries tag types wording

---

sqlserver/datadog_checks/sqlserver/queries.py
sqlserver/datadog_checks/sqlserver/sqlserver.py
sqlserver/datadog_checks/sqlserver/utils.py
sqlserver/hatch.toml
sqlserver/tests/common.py

This PR fixes [an issue](https://github.com/DataDog/integrations-core/issues/14565) we are seeing, where we were not able to properly get the SQL Server major version in some cases and so some metrics were not being collected. For example, if the major_version was not set [we would not collect any file stats queries](https://github.com/DataDog/integrations-core/blob/master/sqlserver/datadog_checks/sqlserver/sqlserver.py#L746-L751). 
In particular, this bug affected Azure SQL DB & Azure SQL MI because the query we use to set the major_version (`SELECT @@VERSION`) recently stopped returning results in [the expected format](https://github.com/DataDog/integrations-core/blob/master/sqlserver/datadog_checks/sqlserver/utils.py#L107-L116) & now returns this:
```
Microsoft SQL Azure (RTM) - …
```

Bug Fix: Support SQL Server file metrics for Azure SQL DB / MI

---

databricks/README.md

Use the `driver-env.sh` file instead of `master-params`
- The driver-only script was not using the correct file. The `all-node` and `job cluster` scripts are already correct. 
- https://docs.databricks.com/_extras/notebooks/source/datadog-init-script.html

Use the `driver-env.sh` file instead of `master-params`

---

postgres/datadog_checks/postgres/postgres.py

This PR fixes a bug, which is in 7.46 release of the agent. Without this commit, the check would not properly stop the  metadata job loop on cancel & therefore we would not properly shut down the db connection the job loops uses.

Properly close db connections for metadata check on cancel

---

ibm_was/tests/conftest.py

Tries to avoid the test failures we were seeing by monitoring for a line that comes later in IBM WAS' startup process.
Tests had been failing for a while for IBM WAS, and the culprit seemed to be that the docker image startup wasn't completing properly. I was able to reproduce locally. I don't know what changed to start seeing this failure, though.

Improve IBM WAS env startup detection to make tests more robust

---

.github/workflows/changelog-label-check.yml
.github/workflows/config/labeler.yml
ddev/hatch.toml

- Check job was not running on commits
- `changelog/no-changelog`
- ddev was always getting it
- it was generally not working as expected due to the use of pseudo-regex syntax

Fix labeler

---

etcd/assets/configuration/spec.yaml
etcd/datadog_checks/etcd/config_models/defaults.py
etcd/datadog_checks/etcd/config_models/instance.py
etcd/datadog_checks/etcd/data/auto_conf.yaml
etcd/datadog_checks/etcd/data/conf.yaml.example
etcd/datadog_checks/etcd/etcd.py
etcd/hatch.toml
etcd/tests/common.py
etcd/tests/conftest.py
etcd/tests/test_e2e.py
etcd/tests/test_integration.py
etcd/tests/utils.py

Drops support for etcd versions below v3.4. Technically the code changes might actually drop support for just etcd v2, but we're removing everything below 3.4 from the testing matrix.
#14458 brought to our attention that the [etcd project only supports the current and previous release](https://etcd.io/docs/v3.5/op-guide/versioning/), which currently means v3.5 and v3.4.

Drop support for etcd < v3.4

---

vsphere/datadog_checks/vsphere/api.py
vsphere/tests/test_check.py

Handle a None return value from RetrievePropertiesEx: https://vdc-download.vmware.com/vmwb-repository/dcr-public/fe08899f-1eec-4d8d-b3bc-a6664c168c2c/7fdf97a1-4c0d-4be0-9d43-2ceebbc174d9/doc/vmodl.query.PropertyCollector.html#retrievePropertiesEx'
We have received a few support cases where an exception is thrown when retrieving the infrastructure data.
From the [documentation](https://vdc-download.vmware.com/vmwb-repository/dcr-public/fe08899f-1eec-4d8d-b3bc-a6664c168c2c/7fdf97a1-4c0d-4be0-9d43-2ceebbc174d9/doc/vmodl.query.PropertyCollector.html#retrievePropertiesEx), this method can return None. In our case, this is usually is due to lack of permissions to view all objects.
```
File "DataDog/integrations-core/vsphere/datadog_checks/vsphere/api.py", line 224, in _get_raw_infrastructure
E …
```

Handle None return value from RetrievePropertiesEx

---

mapr/hatch.toml
mapr/tests/conftest.py

Updates confluent-kafka used in mapr tests to a version having binary wheels for both 2.7 and 3.9.
Tests were failing to run because it fails to install confluent-kafka during dependency installation (this dep is only used for tests).

Update confluent-kafka dependency used in mapr tests

---

mongo/README.md

Removes instructions for creating a user in Mongo v2.x.
Since we state in the README that the integration supports a minimum MongoDB version of v3.0+, having instructions for authenticating with v2.x are unnecessary and can be confusing.

Remove references to Mongo v2.x in instructions

---

kubernetes/assets/dashboards/kubernetes_clusters.json

Removes two links to a US1 specific dashboard that previously pointed to the Pods Overview dashboard. 
Two issues with these links. The first is that they do not link properly to any environment outside of US1, since the dashboard in question is specific to US1. The second is that they do not even work properly on US1 anymore, since they use the `/screen/` url instead of the modern `/dash/` url. So at the moment they are entirely broken.

Remove US1 link from Kubernetes Dashboard

---

ddev/pyproject.toml
ddev/src/ddev/cli/release/list_versions/__init__.py

Remove exclusions from the ddev specific pyproject. The ddev exclusion was ported over from the parent, but doesn't make sense to keep since the files shouldn't exist there.

remove exclusions

---

datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py

Update the expvar port and enable telemetry
- This [PR enables](https://github.com/DataDog/datadog-agent/pull/16900) a openmetrics new check by default
- We do not configure telemetry by default and the port used is `6062` (not random as mentioned in the comment), so the default integration can't access the endpoint and our logs are full of: 
```
2023-06-09 17:44:42 UTC | CORE | ERROR | (pkg/collector/worker/check_logger.go:69 in Error) | check:openmetrics | Error running check: [{"message": "There was an error scraping endpoint http://localhost:5000/telemetry: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /telemetry (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7419bbb0>: Failed to establish a new connection: [Errno …
```

Update the expvar port and enable telemetry

---

calico/tests/conftest.py

Add a condition to the e2e environment
Tests are flaky on master with this error: 
```
________________________________ test_check_ok _________________________________
tests/test_e2e.py:14: in test_check_ok
aggregator = dd_agent_check(rate=True)
../datadog_checks_dev/datadog_checks/dev/plugin/pytest.py:202: in run_check
replay_check_run(collector, aggregator, datadog_agent)
../datadog_checks_dev/datadog_checks/dev/_env.py:172: in replay_check_run
raise Exception("\n".join("Message: {}\n{}".format(err['message'], err['traceback']) for err in errors))
E   Exception: Message: There was an error scraping endpoint http://10.1.0.26:38205/metrics: HTTPConnectionPool(host='10.1.0.26', port=38205): Max retries exceeded with url: /metrics (Caused by …
```

Add a condition to the e2e environment

---

ibm_db2/README.md

This PR updates the `ibm_db2` integration docs to include directions for installing the external `ibm_db` client library on an offline device.
Provide greater support for the integration

Add offline client lib install directions

---

postgres/assets/configuration/spec.yaml
postgres/datadog_checks/postgres/data/conf.yaml.example
postgres/datadog_checks/postgres/postgres.py
postgres/datadog_checks/postgres/util.py
postgres/metadata.csv
postgres/tests/common.py
postgres/tests/test_pg_integration.py
postgres/tests/test_pg_replication.py
postgres/tests/test_unit.py

Add `postgres.wal_count`, `postgres.wal_size` and `postgres.wal_age` metrics
without the need to run locally. Only available starting PG10.
PG10 introduces the `pg_ls_waldir` function which allows us to inspect
the WAL dir content without the need to run the agent locally.
Use it to export the count, total size and age of the WAL files.
Since there's no constraint on running `pg_ls_waldir` except to have
`pg_monitor` access, it would make sense to make it available by default
instead of being opt-in as it was before.

PG: Add metrics for wal files: count, size and age

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/pyproject.toml

This PR updates the `requests-toolbelt` version.
The requests library was [updated](https://github.com/DataDog/integrations-core/pull/14670) a few hours but led to CI tests failing, because the `requests-toolbelt` version was out of date.

Update requests-toolbelt version

---

Dockerfile
kube_apiserver_metrics/assets/dashboards/overview.json
kube_apiserver_metrics/datadog_checks/kube_apiserver_metrics/kube_apiserver_metrics.py
kube_apiserver_metrics/tests/test_kube_apiserver_metrics_1_19.py
kube_apiserver_metrics/tests/test_kube_apiserver_metrics_1_23.py
kube_apiserver_metrics/tests/test_kube_apiserver_metrics_1_24.py
kube_apiserver_metrics/tests/test_kube_apiserver_metrics_1_25.py
kube_apiserver_metrics/tests/test_kube_apiserver_metrics_1_26.py

Backport for https://github.com/DataDog/integrations-core/pull/14738

[kube_apiserver_metrics] Rename aggregator_unavailable_apiservice `name` tag to `apiservice_name` (#14738)

---

sqlserver/tests/compose-ha/sql/aoag_primary.sql
sqlserver/tests/compose-ha/sql/aoag_secondary.sql
sqlserver/tests/compose-high-cardinality-windows/setup.sql
sqlserver/tests/compose-high-cardinality/setup.sql
sqlserver/tests/compose-windows/setup.sql
sqlserver/tests/compose/setup.sql
sqlserver/tests/test_statements.py

In the PR https://github.com/DataDog/integrations-core/pull/14495 we fixed the bug that prevented the correct functioning of statement metrics on the databases with Asian collations. 
In the course of fixing the bug, the customer removed an SQL comment from a test case, because this comment was causing the test case to fail on the first version of the bug fix. In the meantime, we arrived at a better solution. This PR restores the original test case with the aforementioned SQL comment.

Restore the test case with SQL comment

---

kube_apiserver_metrics/CHANGELOG.md
kube_apiserver_metrics/datadog_checks/kube_apiserver_metrics/__about__.py
requirements-agent-release.txt

Bumped kube_apiserver_metrics version to 3.6.1
Push https://github.com/DataDog/integrations-core/pull/14753 to master

[Release] Bumped kube_apiserver_metrics version to 3.6.1

---

postgres/datadog_checks/postgres/postgres.py
postgres/datadog_checks/postgres/util.py
postgres/metadata.csv
postgres/tests/common.py
postgres/tests/test_pg_integration.py
postgres/tests/test_pg_replication.py

[pg_control_checkpoint](https://pgpedia.info/p/pg_control_checkpoint.html) allows to get the current control state. Extract the timeline id and the checkpoint delay from this function.
This function is available since 9.6 and its content unchanged since this version.
Timeline id can give insight on when a failover happened and if there's a timeline mismatch between primary and replicas.

Add metrics for timeline id and checkpoint delay

---

snmp/assets/monitors/traps_linkDown.json
snmp/manifest.json

Add recommended monitor for setting up alerts on SNMP Traps linkDown.
Example Monitor: https://dd.datad0g.com/monitors/create/log?recommendedMonitorID=snmp_%5Bsnmp%5D_linkdown_trap_alert

[NDM] SNMP Trap recommended monitor

---

datadog_checks_base/datadog_checks/base/utils/db/utils.py
datadog_checks_base/tests/base/utils/db/test_util.py
mysql/tests/test_query_activity.py
mysql/tests/test_statements.py
postgres/tests/utils.py
sqlserver/tests/test_activity.py
sqlserver/tests/test_statements.py

This reverts some of the change to make [DBMAsyncJob cancellation synchronous](https://github.com/DataDog/integrations-core/pull/14717).
It still should ensure that the tests fixed by the synchronous cancellation change should pass, because now the waiting logic is in `run_one_check`, so threads from `postgres.py` will still be stopped before metrics are asserted.
The previous change sometimes caused a TimeoutError to happen if the check didn't finish running within 10 seconds after cancellation ([example](https://github.com/DataDog/integrations-core/actions/runs/5257094870/jobs/9499409345?pr=13768)).

Move cancel waiting logic to test functions for DBMAsyncJob 

---

gke/README.md

updates readme to link to general DD kubernetes install, rather than two separate links to helm and (legacy) daemonset
old link found by community

DOCS-5656 gke setup links to operator/helm

---

datadog_checks_base/datadog_checks/base/utils/discovery/filter.py
datadog_checks_base/tests/base/utils/discovery/test_discovery.py

The autodiscovery feature added in [this PR](https://github.com/DataDog/integrations-core/pull/13656) allows us to provide an `include` pattern as a string or directly as a regular expression. If the pattern is a string, we do not compile it and always forward the string to `re.search` which in turn will compile the string and use an internal cache. This PR pre-compiles the string in the discovery class to avoid multiple compilations of the same pattern.
I also added a test to ensure the filter is working as expected if we directly provide a compile regular expression.
Even if there's an [internal cache](https://docs.python.org/3.9/library/re.html#re.compile), I think we should compile them on our side to be completely sure they're not going to be recompiled each time the check runs
- I'm …

Internally compile the `include` patterns in the autodiscovery feature

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/prometheus.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/scripts/metrics2md.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/status.py
datadog_checks_dev/pyproject.toml
ddev/pyproject.toml
ddev/src/ddev/cli/config/__init__.py
ddev/tests/cli/config/test_find.py

In an effort to make installation faster, we should try to use versions of dependencies for which there are binary wheels. https://github.com/asweigart/pyperclip/issues/238
Largely, these features were not well received anyway

Remove `pyperclip` dependency and clipboard functionality

---

ddev/pyproject.toml
ddev/src/ddev/cli/clean/__init__.py

Also fixes https://github.com/DataDog/integrations-core/pull/14778, cleaning currently is breaking editable installations

Bump the minimum version of datadog-checks-dev

---

.github/workflows/build-ddev.yml
ddev/pyoxidizer.bzl

Fix LICENSE path for `build standalone binaries for ddev` workflow, which I missed in https://github.com/DataDog/integrations-core/pull/14774. Modified workflows so they only run when ddev files are modified, and windows and macos binaries run only when master is modified. 
`Build Windows installers` job was broken on the `build standalone binaries for ddev` workflow because the LICENSE path was incorrect.

Update license path for ddev binary builds

---

.github/workflows/pr-all.yml
.github/workflows/pr-test.yml

Temporarily disable py2 tests on PRs, we need to figure out how we are going to test our integrations with py2
- `setup-python` finally dropped support for py2.7, which we use
- We do not run any tests on PRs because of that, not even the py3 ones (example: https://github.com/DataDog/integrations-core/actions/runs/5310764140/jobs/9613140975)
The daily/weekly py2 pipeline on master will continue to fail.

Temporarily disable py2 tests on PRs

---

envoy/datadog_checks/envoy/check.py
envoy/datadog_checks/envoy/envoy.py
envoy/tests/test_unit.py

When the collect_server_info is set to false, we shouldn't try to collect the server metadata, including the server version.
A customer complained about errors when attempting to collect server info and version, despite them setting the collect_server_info to false.
The log they see:
`(pkg/collector/python/datadog_agent.go:134 in LogMessage) | envoy:9e356679f384318e | (utils.py:55) | Envoy endpoint <endpoint>/server_info responded with HTTP status code 404
` 
[Jira card](https://datadoghq.atlassian.net/browse/AGENT-9667)
This was originally done here in this [PR-9298](https://github.com/DataDog/integrations-core/pull/9298) but later the raw_version was updated as part of this [PR-10752](https://github.com/DataDog/integrations-core/pull/10752) to make calls to the function generating the …

Disable server info and version collection when collect_server_info is false

---

.github/workflows/build-ddev.yml

Fix flaky builds for windows/apple installation in `build-ddev.yml`, update `rcodesign` installation
https://github.com/pypa/hatch/pull/890

Fix build flake for ddev

---

postgres/pyproject.toml

This PR updates the dependencies for the Postgres agent check to require Python 3.8. 
I want to use some python 3 specific syntax in this PR: https://github.com/DataDog/integrations-core/pull/14786
and we are bumping the requirements in the next agent release anyway, so these dependencies should be updated.

Require Python 3 for Postgres integration

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/changelog.py

Modifies script to generate integration changelogs to its updated format
example: 
Current changelogs are not as intuitive to read

Update changelog generation to use a better formatting

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py

Set the `marker` option to `not e2e` by default in the `ddev test <INTEGRATION>` command.
We do not run the e2e tests when using this command by default. However, pytest does try to run them and we skip them at runtime in the `dd_agent_check` fixture [here](https://github.com/DataDog/integrations-core/blob/master/datadog_checks_dev/datadog_checks/dev/plugin/pytest.py#L141-L144). It means that the other fixtures can also run before we skip the test. In my case, the fixture `dd_environment` runs before we skip the test, leading us to spin up a whole environment that is not needed at all. This modification will speed up the tests for users and in the CI too.
Example with the DCGM integration: 
Before (but with the docker image already pulled): 
```
❯ ddev test dcgm
Running tests for `dcgm` …
```

Set the `marker` option to `not e2e` by default
