DataDog/integrations-core

- ibm_mq/tests/test_ibm_mq_int.py
Happens once a year 😅 https://github.com/DataDog/integrations-core/pull/9659
> Fix support for running E2E tests on Windows

- datadog_checks_base/tests/base/__init__.py
- datadog_checks_base/tests/base/utils/test_tracking.py
Necessary for https://github.com/DataDog/integrations-core/pull/12986
> Fix package structure of tests

- kafka_consumer/CHANGELOG.md
- rabbitmq/CHANGELOG.md
- sqlserver/CHANGELOG.md
Remove mention of integration name from changelog entries.
> Fix change log entries

- gitlab/tests/compose/docker-compose.yml
- gitlab/tests/conftest.py
- gitlab/tests/test_e2e.py
- gitlab/tox.ini
> Add Gitlab v15 to environments in gitlab integration

- mongo/CHANGELOG.md
Adds a missing changelog entry for mongo
A PR was marked as no/changelog when it modified code
> Add missing changelog entry

- spark/README.md
Adds a troubleshooting note in the readme about running apps
In the future, let's log a warning about this in the check.
> Add note about running apps

- ecs_fargate/README.md
Fixes some links in the readme
reported in Slack
> ECS Fargate links

- aerospike/datadog_checks/aerospike/data/conf.yaml.example
- amazon_msk/datadog_checks/amazon_msk/data/conf.yaml.example
- arangodb/datadog_checks/arangodb/data/conf.yaml.example
- avi_vantage/datadog_checks/avi_vantage/data/conf.yaml.example
- boundary/datadog_checks/boundary/data/conf.yaml.example
- calico/datadog_checks/calico/data/conf.yaml.example
- cert_manager/datadog_checks/cert_manager/data/conf.yaml.example
- cilium/datadog_checks/cilium/data/conf.yaml.example
- cockroachdb/datadog_checks/cockroachdb/data/conf.yaml.example
- coredns/datadog_checks/coredns/data/conf.yaml.example
- datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/openmetrics.yaml
- envoy/datadog_checks/envoy/data/conf.yaml.example
- haproxy/datadog_checks/haproxy/data/conf.yaml.example
- impala/datadog_checks/impala/data/conf.yaml.example
- istio/datadog_checks/istio/data/conf.yaml.example
- kong/datadog_checks/kong/data/conf.yaml.example
- linkerd/datadog_checks/linkerd/data/conf.yaml.example
- openmetrics/datadog_checks/openmetrics/data/conf.yaml.example
- pulsar/datadog_checks/pulsar/data/conf.yaml.example
- vault/datadog_checks/vault/data/conf.yaml.example
- Update the openmetrics template. Fix some errors and improve the doc. 
- Update the openmetrics integrations accordingly.
Those changes were requested by the doc team in [this PR](https://github.com/DataDog/integrations-core/pull/12548). 
Edit: [AI-2646](https://datadoghq.atlassian.net/browse/AI-2646)
> Update the openmetrics configuration template

- ddev/tests/conftest.py
- ddev/tests/test__utils.py
Need a way to make changes to a repo for individual tests
> Add test fixtures

- datadog_checks_dev/datadog_checks/dev/tooling/commands/create.py
- datadog_checks_dev/datadog_checks/dev/tooling/config.py
- datadog_checks_dev/datadog_checks/dev/tooling/constants.py
- datadog_checks_dev/datadog_checks/dev/tooling/create.py
> Add integrations repo to ddev.

- kafka_consumer/tests/test_kafka_consumer.py
Add a unit test to validate the oauth config is taken into account. 
QA for https://github.com/DataDog/integrations-core/pull/12891. It's not much but at least we check we read the config. Test about the authentication itself are in the base check along with the `AuthTokenOAuthReader` class
> Test the oauth config is properly read

- impala/hatch.toml
Remove the bench env from the hatch config.
No need to have it for this integration, it only slows down the CI.
> Remove the bench env from the hatch config

- datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py
Mention the `env reload` command to the `env start` output.
Forgot to reload it once and it's easier to copy/paste it
> Add the reload command to the `env start` output

- network/CHANGELOG.md
- network/datadog_checks/network/__about__.py
- requirements-agent-release.txt
Apply https://github.com/DataDog/integrations-core/pull/13044 to master branch.
Only merge this once network 2.9.1 finishes its release.
> Backport network to master

- datadog_checks_base/datadog_checks/base/utils/db/transform.py
https://datadoghq.dev/integrations-core/base/databases/#datadog_checks.base.utils.db.transform.ColumnTransformers.time_elapsed
> Fix code block in docstring

- teamcity/README.md
Updates the link for integration log pipelines
Noticed during a related update
> Fix integration pipelines link

- datadog_checks_dev/datadog_checks/dev/tooling/trello.py
Updates the agent QA Trello script with some new teams.
> Update agent QA trello script with new teams

- linkerd/README.md
Updating the Linkerd description and value add of the integration. 
There was very little information, and we wanted to provide Datadog users more context.
> Updating the Linkerd description

- datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/testable.py
Add new teams added [here](https://github.com/DataDog/integrations-core/pull/13030) to the `testable` script.
We forgot to add them.
> Add new teams to the trello `testable` script

- requirements-agent-release.txt
- sqlserver/CHANGELOG.md
- sqlserver/datadog_checks/sqlserver/__about__.py
Apply https://github.com/DataDog/integrations-core/pull/13064 on master
The integration is already released and the tag is ready
> [Release] Bumped sqlserver version to 9.0.1 (#13064)

- docs/developer/.scripts/33_render_status.py
Add the hatch migration status to the docs
We are migrating from tox to hatch.
> Add the hatch migration status to the docs

- datadog_checks_base/datadog_checks/base/utils/concurrency/__init__.py
- datadog_checks_base/datadog_checks/base/utils/concurrency/limiter.py
- datadog_checks_base/tests/base/utils/concurrency/__init__.py
- datadog_checks_base/tests/base/utils/concurrency/test_limiter.py
Need a way to gate the execution of checks
> Add utility to handle concurrent evaluation of conditions

- network/datadog_checks/network/network.py
- network/tests/conftest.py
- network/tests/test_ethtool.py
- network/tests/test_integration.py
- network/tests/test_network.py
Move check initialisation to init method
> Network check refactor: Create init method

- datadog_checks_base/CHANGELOG.md
Update the changelog of the datadog_checks_base.
We released the version 27.3.1 for the agent 7.40. https://github.com/DataDog/integrations-core/pull/13099
Since we already made a new release for the base check, I only updated the changelog file. We will need to re-release the 27.4 to include this fix @ofek
> Update the changelog of the datadog_checks_base

- cert_manager/manifest.json
Remove `Integration` from the tile title
We forgot to drop it when migrating from -extras
> Remove `Integration` from the title

- sqlserver/datadog_checks/sqlserver/statements.py
- sqlserver/tests/test_statements.py
Backport https://github.com/DataDog/integrations-core/pull/13089 to 7.40.x
We need it in the next release candidate.
> Fix Query Metrics query to correct for over-inflated / incorrect SQL Server metrics

- directory/datadog_checks/directory/directory.py
- directory/tests/test_directory.py
Cleans up the logic for iterating on the directory walker and catching and logging exceptions.
Follow up to https://github.com/DataDog/integrations-core/pull/13093, which introduced the error messages (in place of a cryptic `StopIteration` exception). Separating the details of iteration to a separate method reduces nesting and makes code easier to read.
The big chunk of diff in the middle of `_get_stats` is due to indentation change (due to removing a try-except nesting level), Github's diff isn't good at picking that up which makes it a bit harder to review.
> Refactor iterator and error logging in directory

- requirements-agent-release.txt
- sqlserver/CHANGELOG.md
- sqlserver/datadog_checks/sqlserver/__about__.py
Update the sqlserver version/changelog on master.
Follow up PR to https://github.com/DataDog/integrations-core/pull/13127
> [Release] Bumped sqlserver version to 9.0.2

- .ddev/config.toml
- ddev/src/ddev/config/file.py
- ddev/src/ddev/integration/__init__.py
- ddev/src/ddev/integration/core.py
- ddev/src/ddev/repo/config.py
- ddev/src/ddev/repo/constants.py
- ddev/src/ddev/repo/core.py
- ddev/src/ddev/utils/fs.py
- ddev/tests/conftest.py
- ddev/tests/helpers/api.py
- ddev/tests/integration/__init__.py
- ddev/tests/integration/test_core.py
- ddev/tests/repo/__init__.py
- ddev/tests/repo/test_config.py
- ddev/tests/repo/test_core.py
Prerequisite PR 1/3 to allow porting over commands
> Add more utilities

- ddev/src/ddev/integration/core.py
- ddev/src/ddev/repo/constants.py
- ddev/src/ddev/repo/core.py
- ddev/tests/conftest.py
- ddev/tests/integration/test_core.py
- ddev/tests/repo/test_core.py
Prerequisite PR 2/3 to allow porting over commands
> Add utilities for filtering integrations

- datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/testable.py
- datadog_checks_dev/datadog_checks/dev/tooling/trello.py
This PR updates the name of Infrastructure Integrations to Network Device Monitoring in datadog_checks_dev.
This was failing when generating new QA cards.
> Update NDM name

- docs/developer/ddev/about.md
> Add note in docs about ddev needing to support Python 2.7

- databricks/README.md
missing `DD_TAGS`
Fix a bug where `DD_TAG` are not being passed to `DD_HOST_TAGS` for the install script
- AGENT-8463
> fix init script bug

- ddev/src/ddev/cli/__init__.py
- ddev/src/ddev/cli/status/__init__.py
- ddev/src/ddev/repo/core.py
- ddev/src/ddev/utils/fs.py
- ddev/tests/cli/__init__.py
- ddev/tests/cli/status/__init__.py
- ddev/tests/cli/status/test_status.py
- ddev/tests/conftest.py
> Add `status` command

- .github/workflows/config/labeler.yml
> Exclude ddev from no-changelog PR label

- mysql/datadog_checks/mysql/statement_samples.py
- mysql/datadog_checks/mysql/statements.py
Add two Datadog metrics for our agent check for mysql query metrics collection.
> mysql: additional metrics for mysql metrics collection

- teamcity/assets/configuration/spec.yaml
- teamcity/datadog_checks/teamcity/data/conf.yaml.example
Separate openmetrics & rest configuration instances
> teamcity multi instance

- datadog_checks_dev/datadog_checks/dev/tooling/utils.py
- datadog_checks_dev/tests/tooling/test_utils.py
This report broke as part as the manifest v2 migration
> Fix process signature report

- postgres/datadog_checks/postgres/statement_samples.py
- postgres/tests/test_statements.py
Improves the detection of explain plan errors by capturing specific exceptions and mapping them to a more defined key.
Improve troubleshooting within the DBM app.
> Improve DBM explain plan error collection errors

- disk/datadog_checks/disk/disk.py
Refactor disk check to calculate tags on a separate method
> [disk] Extract tag calculation to a separate method

- docs/dev/oauth_for_data_integrations.md
Adds a blog post link to the OAuth for Data Integrations doc page. 
#writing Slack
> Adds Blog Post Link

- datadog_checks_base/datadog_checks/base/checks/base.py
Just a quick variable rename.
"result" was too generic a name and in some sense also wrong, because it didn't really capture all the result of the command.
> Rename variable to make its role clearer

- datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py
- datadog_checks_dev/datadog_checks/dev/tooling/commands/env/test.py
Improve some cli option help texts
I was confused by these help texts so I thought I'd clarify them a bit based on what I now know.
> [cli] expand help text for --dev and --base options

- datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/dep.py
> Improve message for dependency sync needed

- kubernetes/assets/dashboards/kubernetes_jobs.json
like for `job` success, failed job should be `avg` for the time aggregation.
Fix "failed job" counter on Kubernetes jobs dashboard.
> fix(kubernetes): fix failed job query

- ibm_mq/tests/test_config.py
Reduce some duplication with stacked pytest.parametrize, extend tests to cover more configuration constellations.
Part of QA week.
> DRY and extend tests for ssl options

- amazon_msk/README.md
Adds instructions to add custom tags and updates the Further Reading section.
DOCS-4234
> DOCS-4234 Amazon MSK (Agent) Edits

- kubelet/tests/fixtures/pod_list_probes.json
- kubelet/tests/fixtures/pods_windows.json
See https://github.com/kubernetes/kubernetes/issues/89477, https://github.com/kubernetes/kubernetes/issues/89477#issuecomment-603911496.
> stop using beta.kubernetes.io/os

- ibm_was/tox.ini
Updates a comment about why we don't have tests for v8 of IBM WAS
Was poking around for a ticket, saw an opportunity to clean up a bit.
> Update comment about lack of tests for version 8

- docs/dev/oauth_for_data_integrations.md
Updates the suggested uninstallation text for the OAuth docs
We've just made a change so that when a user clicks uninstall, any previous authorizations of an integration through OAuth will be revoked. Updating the suggest uninstallation instructions template in our docs to reflect that.
> Updating uninstallation suggestion

- boundary/assets/dashboards/boundary_overview.json
Add new logs widgets to dashboard
Screenshot: https://a.cl.ly/geuy5xpl
> Add new logs widgets to dashboard

- docs/developer/tutorials/snmp/profile-format.md
Document using extract_value to ignore surrounding non-printable chars
> Document using extract_value to ignore surrounding non-printable chars

- kafka/README.md
Tuesday tasks - adds a link to a related knowledge center article.
> Adding in a link to the new Kafka knowledge center article

- cockroachdb/hatch.toml
Pin cockroackdb test image versions
https://github.com/DataDog/integrations-core/pull/13317/files#r1022806623
> Pin test image versions

- docs/dev/new_check_howto.md
Streamlines the docs for creating an integration in integrations-extras.
DOCS OKR - [DOCS-4302](https://datadoghq.atlassian.net/browse/DOCS-4302)
[DOCS-4352](https://datadoghq.atlassian.net/browse/DOCS-4352)
> (DOCS-4352) Update documentation for creating an integration

- ibm_was/datadog_checks/ibm_was/metrics.py
I figured we point to the docs for the latest version that we support.
> IBM docs links point to v9 instead of obsolete v8.

- docs/developer/base/api.md
> Add newer AggregatorStub methods to api docs.

- sqlserver/assets/dashboards/SQLServer-Overview_dashboard.json
Updates the SQL Server Overview dashboard to a much richer and full-featured dashboard, also taking advantage of the new dashboard features since the original development.
> Update the SQL Server Overview dashboard

- ibm_db2/README.md
[AGENT-8989](https://datadoghq.atlassian.net/browse/AGENT-8989)
> Corrected readme for IBM Db2

- docs/dev/oauth_for_integrations.md
Renames a doc page and removes mention of a "data integration".
Slack with Ana
> Renames OAuth for Integrations Doc Page

- docs/dev/new_check_howto.md
Correct a minor inconsistency.
Noticed inconsistency.
> Correct minor punctuation inconsistency

- ibm_mq/datadog_checks/ibm_mq/collectors/channel_metric_collector.py
- ibm_mq/datadog_checks/ibm_mq/collectors/queue_metric_collector.py
- ibm_mq/datadog_checks/ibm_mq/ibm_mq.py
> Add messaging to service checks

- datadog_checks_dev/datadog_checks/dev/tooling/commands/docs/build.py
- datadog_checks_dev/datadog_checks/dev/tooling/commands/docs/serve.py
- datadog_checks_dev/datadog_checks/dev/tooling/commands/docs/utils.py
- datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py
- datadog_checks_dev/datadog_checks/dev/tooling/testing.py
https://github.com/DataDog/integrations-core/pull/13365
> Support isolated installation

- ddev/pyproject.toml
> Upgrade dependencies

- docs/developer/.snippets/links.txt
- docs/developer/setup.md
> Update ddev install docs

- snmp/datadog_checks/snmp/snmp.py
Rename check instance argument to _
> Rename check instance argument to _

- datadog_checks_base/datadog_checks/base/data/agent_requirements.in
- pgbouncer/pyproject.toml
- postgres/pyproject.toml
Split of https://github.com/DataDog/integrations-core/pull/13315
> Do not install psycopg2-binary on arm macs

- README.md
Remove the releasers list from the README.md
This section does not exist n our doc anymore. 
https://github.com/DataDog/integrations-core/pull/12089
> Remove the releasers list from the README.md

- ddev/pyproject.toml
- ddev/src/ddev/cli/__init__.py
- ddev/src/ddev/cli/config/__init__.py
- ddev/src/ddev/config/file.py
- ddev/src/ddev/config/utils.py
- ddev/tests/cli/config/__init__.py
- ddev/tests/cli/config/test_edit.py
- ddev/tests/cli/config/test_explore.py
- ddev/tests/cli/config/test_find.py
- ddev/tests/cli/config/test_restore.py
- ddev/tests/cli/config/test_set.py
- ddev/tests/cli/config/test_show.py
- ddev/tests/conftest.py
> Add `config` commands

- ddev/hatch.toml
- ddev/src/ddev/repo/core.py
- ddev/src/ddev/utils/fs.py
Enable mypy for ddev
We type everything but we do not validate it.
> Enable mypy

- impala/assets/dashboards/impala_overview.json
Update the global overview dashboard for Impala
- Add more notes
- Add links to the other Impala dashboards
> Update the global overview dashboard

- teamcity/assets/dashboards/overview.json
- teamcity/assets/recommended_monitors/build_status.json
- teamcity/manifest.json
> Add TeamCity dashboard and monitor

- .github/workflows/config/labeler.yml
> Fix ddev no-changelog glob pattern

- active_directory/pyproject.toml
- aspdotnet/pyproject.toml
- dotnetclr/pyproject.toml
- exchange_server/pyproject.toml
- hyperv/pyproject.toml
- iis/pyproject.toml
- windows_performance_counters/pyproject.toml
Bump dependencies for changes in the corresponding https://github.com/DataDog/integrations-core/pull/13243
> Bump minimum supported base package version for Windows performance counters-based checks

- calico/setup.py
Update the project URL
Calico used to be in extras and we forgot to update this.
> Fix the project URL

- process/tests/test_process.py
Update the tests of the process integration
nitpicking PR QAing https://github.com/DataDog/integrations-core/pull/13080
> Update tests to validate the logs

- oom_kill/README.md
Adding configuration with Docker
Adding required setting which was not documented.
> Adding configuration with Docker

- impala/manifest.json
Make the Impala integration public
Agent 7.40 is out.
> Display the Impala integration on the public website

- istio/assets/configuration/spec.yaml
- istio/datadog_checks/istio/data/auto_conf.yaml
- istio/datadog_checks/istio/data/conf.yaml.example
Clarify Istio Openmetrics v2 descriptions
Support question
> Update istio descriptions

- ddev/pyproject.toml
Bump datadog_checks_dev dependency to 17.5.0
Follow-up PR of https://github.com/DataDog/integrations-core/pull/13487
> Bump datadog_checks_dev dependency to 17.5.0

- sonarqube/assets/configuration/spec.yaml
- sonarqube/datadog_checks/sonarqube/config_models/instance.py
- sonarqube/datadog_checks/sonarqube/data/conf.yaml.example
Fixes configuration specification to properly generate all available configs in the example config file. 
QA
> Fix configuration spec

- sonarqube/datadog_checks/sonarqube/check.py
- sonarqube/tests/common.py
- sonarqube/tests/conftest.py
- sonarqube/tests/test_unit.py
> Projects processed in `components` excluded from `components_discovery`

- teamcity/datadog_checks/teamcity/common.py
- teamcity/datadog_checks/teamcity/teamcity_rest.py
Fix events so that the events are formatted and tagged correctly by build configuration "type".
QA
> Fix event tagging

- oracle/README.md
Fix indentation in the yaml config example
QA for https://github.com/DataDog/integrations-core/pull/13298
This is definitely a nit PR, sorry
> Update the readme

- datadog_checks_base/pyproject.toml
Remove the `Do Not Upload` classifier.
The base check needs to be uploaded to PyPi
> Remove the `Do Not Upload` classifier

- ibm_mq/tests/conftest.py
- ibm_mq/tests/test_ibm_mq_int.py
- ibm_mq/tests/test_ibm_mq_unit.py
- Fix the `test_check_cant_connect` because the assertions were never called
- Simplify the `instance` fixtures
- Add the messages in the `assert_service_check` (initial reason for this PR)
QA for https://github.com/DataDog/integrations-core/pull/13355
> Fix and refactor tests

- spark/tests/fixtures/metrics_json
- spark/tests/test_spark.py
QA for #13246. Added sample to the fixture and assertions for the punctuations in the query name.
> Add test samples to test punctuation in queryname

- zk/tests/common.py
- zk/tests/test_zk.py
Add test to PR that changed the regex matching for metadata. 
qa for #13171
> Add test for ZK metadata detection regex change

- win32_event_log/README.md
> Fix legacy mode configuration error in docs

- boundary/assets/dashboards/boundary_overview.json
Update boundary dashboard's logs widgets with new logs facets
> Update boundary dashboard logs facets

- hivemq/README.md
Adds a further reading section and blog link to the HiveMQ integration documentation.
Spread awareness of the ability to use HiveMQ and OpenTelemetry to monitor IoT applications in Datadog.
> Add further reading section and blog link

- datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/manifest.py
- datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/__init__.py
- datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/v2/validator.py
This is necessary for an upcoming pull request
> Add hidden option to ignore manifest schema validation

- postgres/assets/configuration/spec.yaml
- postgres/datadog_checks/postgres/config_models/instance.py
- postgres/datadog_checks/postgres/statements.py
Decided the potential integration performance degradation is not ideal to retrieve this information. We'll look into a better solution in the future.
> Remove query text length metric

- datadog_checks_dev/datadog_checks/dev/tooling/commands/config.py
- datadog_checks_dev/datadog_checks/dev/tooling/utils.py
```
Running tests for `...`
---------------------------------------
ERROR: tox config file (either pyproject.toml, tox.ini, setup.cfg) not found
```
> Properly account for other integration repos

- datadog_checks_base/datadog_checks/base/utils/tracing.py
Follow-up to https://github.com/DataDog/integrations-core/pull/13580, removing the now unused `@trace` decorator. I forgot to remove it in the original PR.
Cleanup of integration tracing code.
> remove unused tracing function

- datadog_checks_base/datadog_checks/base/utils/tracing.py
- datadog_checks_base/tests/base/utils/test_tracing.py
When `integration_tracing: true` we now trace all `AgentCheck.warning` calls, ensuring a detailed error span is collected for every warning emitted during the check run. The error span includes the warning message as well as the full stack trace at the point the warning was emitted.
We also now include `AgentCheck.check` in the set of methods that are traced when `integration_tracing: true`. If `AgentCheck.check` throws an exception then it is handled in `AgentCheck.run` where the tracing library doesn't know about it. By tracing `AgentCheck.check` we ensure any unhandled exceptions are captured in the trace by default.
Improve continuous integration tracing.
> Improve integration tracing of warnings & errors

- impala/README.md
Add more information on collecting logs, including that we need to enable it in the agent config itself and we have to update the impala.conf file.
- Improve the docs
- We have a validation failure in our weekly CI check that broke because of that
- [Rendered](https://github.com/DataDog/integrations-core/tree/florentclarret/impala/log-collection/impala#logs)
> Add more information on collecting logs

- datadog_checks_downloader/README.md
#13586 switched from tox to hatch, so instructions mentioning tox are no longer relevant.
> Update readme to remove references to tox

- ddev/tests/repo/test_core.py
https://github.com/DataDog/integrations-core/pull/13570#discussion_r1060067989
> parametrization suggestion

- .azure-pipelines/templates/test-single-linux.yml
- .azure-pipelines/templates/test-single-windows.yml
- datadog_checks_dev/datadog_checks/dev/tooling/testing.py
Rename TOX_SKIP_ENV to SKIP_ENV_NAME
https://github.com/DataDog/integrations-core/pull/13623#discussion_r1061613514
> Rename TOX_SKIP_ENV to SKIP_ENV_NAME

- mongo/README.md
- mongo/assets/configuration/spec.yaml
- mongo/datadog_checks/mongo/data/conf.yaml.example
Updates the instructions for configuring the Agent on a MongoDB replica set. 
See [DOCS-4591](https://datadoghq.atlassian.net/browse/DOCS-4591), [AGENT-9155](https://datadoghq.atlassian.net/browse/AGENT-9155).
[DOCS-4591]: https://datadoghq.atlassian.net/browse/DOCS-4591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-4591]: https://datadoghq.atlassian.net/browse/DOCS-4591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AGENT-9155]: https://datadoghq.atlassian.net/browse/AGENT-9155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AGENT-9155]: https://datadoghq.atlassian.net/browse/AGENT-9155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …
> (DOCS-4591) Update Replica Set config instructions

- datadog_checks_dev/datadog_checks/dev/docker.py
Remove the docker compatibility mode
https://datadoghq.atlassian.net/browse/AITOOLS-76
> Remove the docker compatibility mode

- oracle/tests/conftest.py
- oracle/tests/test_config.py
- oracle/tests/test_custom_queries.py
- oracle/tests/test_e2e.py
- oracle/tests/test_unit.py
- Remove some unused parameters
- Remove unnecessary `deepcopy` in some fixtures
- Add some assertions
QA https://github.com/DataDog/integrations-core/pull/13337
> Refactor the tests

- presto/hatch.toml
- presto/tests/common.py
- presto/tests/docker/docker-compose.yaml
- presto/tests/test_presto.py
Pin the presto version
https://datadoghq.atlassian.net/browse/AITOOLS-96
> Pin the presto version

- tls/tests/compose/Dockerfile
- tls/tests/compose/docker-compose.yml
Pin the docker versions
https://datadoghq.atlassian.net/browse/AITOOLS-96
> Pin the docker versions

- http_check/tests/compose/certs-builder/Dockerfile
Pin the alpine version
https://datadoghq.atlassian.net/browse/AITOOLS-96
> Pin the alpine version

- vault/tests/docker/docker-compose.yaml
Pin the consul version
https://datadoghq.atlassian.net/browse/AITOOLS-96
> Pin the consul version

- .azure-pipelines/all_pr.yml
- .azure-pipelines/changes.yml
Also run the tests on PRs that do not target the main branch
https://datadoghq.atlassian.net/browse/AITOOLS-99
> Run tests on PRs that do not target master

- rabbitmq/assets/configuration/spec.yaml
- rabbitmq/datadog_checks/rabbitmq/__init__.py
- rabbitmq/datadog_checks/rabbitmq/check.py
- rabbitmq/datadog_checks/rabbitmq/config_models/defaults.py
- rabbitmq/datadog_checks/rabbitmq/config_models/instance.py
- rabbitmq/datadog_checks/rabbitmq/data/conf.yaml.example
- rabbitmq/datadog_checks/rabbitmq/openmetrics/__init__.py
- rabbitmq/datadog_checks/rabbitmq/openmetrics/check.py
- rabbitmq/datadog_checks/rabbitmq/rabbitmq.py
- rabbitmq/hatch.toml
- rabbitmq/tests/compose/docker-compose.yaml
- rabbitmq/tests/conftest.py
- rabbitmq/tests/metrics.py
- rabbitmq/tests/test_openmetrics.py
- rabbitmq/tests/test_unit.py
The Openmetrics-related changes are minimal: just a basic class and a test that mostly makes sure that this class can be imported and run.
The rest is scaffolding: I needed new versions of rmq to test out my changes, the old tests needed adjusting to pass -> one config field had to be made optional to make sure my tests run -> etc...
> Setting the stage

- datadog_checks_base/datadog_checks/base/utils/discovery/__init__.py
- datadog_checks_base/datadog_checks/base/utils/discovery/cache.py
- datadog_checks_base/datadog_checks/base/utils/discovery/discovery.py
- datadog_checks_base/datadog_checks/base/utils/discovery/filter.py
- datadog_checks_base/tests/base/utils/discovery/test_discovery.py
Autodiscovery in Agent Integrations
[this](https://github.com/DataDog/architecture/blob/discovery/rfcs/discovery/rfc.md)
> Autodiscovery in Agent Integrations

- cloudera/datadog_checks/cloudera/api_client_v7.py
- cloudera/datadog_checks/cloudera/check.py
- cloudera/datadog_checks/cloudera/event.py
- cloudera/tests/conftest.py
- cloudera/tests/docker/etc/caddy/Caddyfile
- cloudera/tests/docker/fixtures/api/v48/events/get_events
- cloudera/tests/test_e2e.py
- cloudera/tests/test_integration.py
- cloudera/tests/test_unit.py
This PR adds event support to the Cloudera integration. 
Included in the initial release of the Cloudera check.
> Add events to Cloudera

- ddev/hatch.toml
- ddev/pyproject.toml
- ddev/src/ddev/cli/validate/__init__.py
- ddev/src/ddev/cli/validate/manifest.py
- ddev/tests/cli/validate/__init__.py
- ddev/tests/cli/validate/test_manifest.py
- ddev/tests/conftest.py
- fixtures/network/manifest/missing_app_uuid.yaml
- fixtures/network/manifest/success.yaml
Sometime in the next month the few legacy checks that the old validation performs will be moved to the backend, at which point we will solely rely on that
> Update manifest validation

- datadog_checks_base/datadog_checks/base/data/agent_requirements.in
Updates enum34 to match imposed constraints.
Working A5 build necessary.
> [base] updating enum34 deps

- docs/developer/setup.md
https://github.com/DataDog/integrations-core/pull/13562/commits/df1496e4639a5b461d4b4de4433e4523103c8d49
> Update developer installation docs

- cloudera/datadog_checks/cloudera/api_client.py
- cloudera/datadog_checks/cloudera/api_client_factory.py
- cloudera/datadog_checks/cloudera/api_client_v7.py
- cloudera/datadog_checks/cloudera/common.py
- cloudera/datadog_checks/cloudera/entity_status.py
- cloudera/datadog_checks/cloudera/event.py
- cloudera/datadog_checks/cloudera/metrics.py
- cloudera/tests/common.py
- cloudera/tests/test_e2e.py
- cloudera/tests/test_integration.py
- mysql/tests/generate_unique_query_signatures.py
- postgres/datadog_checks/postgres/explain_parameterized_queries.py
- postgres/tests/test_explain_parameterized_queries.py
- sqlserver/datadog_checks/sqlserver/connection_errors.py
Complete what started with #13511.
Some new files were created while #13511 was open which didn't add a license, so when adding the validation to the CI, it failed.
> Add license header files where missing

- datadog_checks_base/datadog_checks/base/checks/windows/perf_counters/counter.py
- datadog_checks_base/tests/base/checks/windows/perf_counters/test_integration.py
Previously, if one of the windows performance counters specified in the configuration file has a typo, integration code detected it as an error and prematurely exit processing next of the counters. In addition, subsequent errors in the log did not indicate premature loop exit and did not specify counter name which caused the problem which made it harder to troubleshoot. In a large configuration file it makes much harder to understand why some performance counters are reported but others are not. 
This PR fixed the problem by not immediately exiting a processing loop when "bad" counter is detected. Error will be reported and the following performance counters will be processed.
Customer reported problem
[WA-193](https://datadoghq.atlassian.net/browse/WA-193) Continue to process windows …
> Skip typo or not yet installed Windows performance counters to allow collection of subsequent counters

- docs/developer/.scripts/33_render_status.py
Remove the hatch migration status
- Migration is done
- Part of https://datadoghq.atlassian.net/browse/AITOOLS-21
> Remove the hatch migration status

- cloudera/assets/dashboards/cloudera_overview.json
- cloudera/manifest.json
Adds an overview dashboard for Cloudera
> Add Cloudera overview Dashboard

- sonarqube/datadog_checks/sonarqube/check.py
- sonarqube/tests/api_responses/components_search_with_tmp
- sonarqube/tests/api_responses/components_search_with_tmp_p1
- sonarqube/tests/api_responses/components_search_with_tmp_p2
- sonarqube/tests/test_unit.py
[this](https://datadoghq.atlassian.net/browse/AI-2872)
[this](https://datadoghq.atlassian.net/browse/AGENT-8996)
> Support components from paginated endpoint

- cloudera/datadog_checks/cloudera/check.py
- cloudera/tests/common.py
The `api_url` tag was improperly formatted. This PR fixes that.
> Fix api_url tag

- snmp/tests/test_e2e_core.py
To be merged later once a new agent is built
> [NDM] Remove ifalias tag from tests

- cloudera/README.md
- cloudera/assets/configuration/spec.yaml
- cloudera/datadog_checks/cloudera/api_client_v7.py
- cloudera/datadog_checks/cloudera/config_models/defaults.py
- cloudera/datadog_checks/cloudera/config_models/instance.py
- cloudera/datadog_checks/cloudera/data/conf.yaml.example
- cloudera/tests/conftest.py
- cloudera/tests/docker/etc/caddy/Caddyfile
- cloudera/tests/docker/fixtures/api/v48/timeseries/get_custom_metrics_alias
- cloudera/tests/docker/fixtures/api/v48/timeseries/get_custom_metrics_last_alias
- cloudera/tests/docker/fixtures/api/v48/timeseries/get_custom_metrics_no_alias
- cloudera/tests/test_integration.py
- cloudera/tests/test_unit.py
This PR adds custom query support for Cloudera.
> Add custom queries implementation

- rabbitmq/assets/configuration/spec.yaml
- rabbitmq/datadog_checks/rabbitmq/config_models/instance.py
- rabbitmq/datadog_checks/rabbitmq/data/conf.yaml.example
- rabbitmq/datadog_checks/rabbitmq/openmetrics/check.py
- rabbitmq/tests/fixtures/detailed-queue_coarse_metrics.txt
- rabbitmq/tests/fixtures/detailed.txt
- rabbitmq/tests/test_openmetrics.py
> support for specifying just detailed endpoint

- rabbitmq/datadog_checks/rabbitmq/openmetrics/check.py
- rabbitmq/tests/fixtures/per-object.txt
- rabbitmq/tests/test_openmetrics.py
> support for specifying just per-object endpoint

- rabbitmq/datadog_checks/rabbitmq/openmetrics/check.py
- rabbitmq/datadog_checks/rabbitmq/openmetrics/metrics.py
- rabbitmq/tests/fixtures/detailed-queue_coarse_metrics-queue_consumer_count.txt
- rabbitmq/tests/fixtures/detailed-queue_consumer_count.txt
- rabbitmq/tests/test_openmetrics.py
> specify both detailed and aggregated endpoints in one instance

- rabbitmq/datadog_checks/rabbitmq/config_models/validators.py
- rabbitmq/datadog_checks/rabbitmq/openmetrics/check.py
- rabbitmq/tests/common.py
- rabbitmq/tests/test_openmetrics.py
> validate check configuration values

- cloudera/datadog_checks/cloudera/api_client_v7.py
> Add futures result process to ThreadPoolExecutor

- rabbitmq/tests/test_integration_e2e.py
> Add openmetrics E2E test

- datadog_checks_dev/datadog_checks/dev/plugin/hatch/environment_collector.py
- datadog_checks_dev/datadog_checks/dev/plugin/tox.py
> Update style deps

- rabbitmq/datadog_checks/rabbitmq/check.py
- rabbitmq/datadog_checks/rabbitmq/config_models/validators.py
- rabbitmq/tests/test_openmetrics.py
Small punctuation fixes in the error messages
> Small punctuation fixes

- rabbitmq/assets/configuration/spec.yaml
- rabbitmq/datadog_checks/rabbitmq/data/conf.yaml.example
Separate the openmetrics and management plugin instance configs in the spec.yaml.
> Define multiple instances in config spec

- aerospike/datadog_checks/aerospike/data/conf.yaml.example
- amazon_msk/datadog_checks/amazon_msk/data/conf.yaml.example
- arangodb/datadog_checks/arangodb/data/conf.yaml.example
- argocd/datadog_checks/argocd/data/conf.yaml.example
- avi_vantage/datadog_checks/avi_vantage/data/conf.yaml.example
- boundary/datadog_checks/boundary/data/conf.yaml.example
- calico/datadog_checks/calico/data/conf.yaml.example
- cert_manager/datadog_checks/cert_manager/data/conf.yaml.example
- cilium/datadog_checks/cilium/data/conf.yaml.example
- cockroachdb/datadog_checks/cockroachdb/data/conf.yaml.example
- coredns/datadog_checks/coredns/data/conf.yaml.example
- datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/openmetrics.yaml
- envoy/datadog_checks/envoy/data/conf.yaml.example
- haproxy/datadog_checks/haproxy/data/conf.yaml.example
- impala/datadog_checks/impala/data/conf.yaml.example
- istio/datadog_checks/istio/data/conf.yaml.example
- kong/datadog_checks/kong/data/conf.yaml.example
- linkerd/datadog_checks/linkerd/data/conf.yaml.example
- openmetrics/datadog_checks/openmetrics/data/conf.yaml.example
- pulsar/datadog_checks/pulsar/data/conf.yaml.example
- teamcity/datadog_checks/teamcity/data/conf.yaml.example
- vault/datadog_checks/vault/data/conf.yaml.example
> Fix grammatical errors in OM instance template

- argocd/manifest.json
As part of the release process.
> Enable Argo CD for the public

- datadog_checks_dev/datadog_checks/dev/plugin/hatch/environment_collector.py
- datadog_checks_dev/datadog_checks/dev/plugin/tox.py
Bump pydantic version to 1.10.4
Forgotten in https://github.com/DataDog/integrations-core/pull/13726
> Bump pydantic version to 1.10.4

- datadog_checks_dev/datadog_checks/dev/tooling/e2e/run.py
Invoke hatch with `sys.exectable, '-m'` instead of directly.
This makes sure we use the `hatch` installed with `ddev`.
> Call hatch from `sys.executable`.

- .azure-pipelines/templates/test-all-checks.yml
- .codecov.yml
- go_expvar/assets/configuration/spec.yaml
- go_expvar/manifest.json
Updates the go_expvar source_type_name to match whats already defined and used in the backend
We're creating stronger validations to catch these types of inconsistencies going forward, but in order to enable them, we need to fix the breaking cases.
> Update go_expvar source_type_name to match backend

- argocd/manifest.json
- btrfs/manifest.json
- cloudera/manifest.json
- couch/manifest.json
- datadog_cluster_agent/manifest.json
- ssh_check/manifest.json
> Clean up manifests.

- datadog_checks_base/datadog_checks/base/data/agent_requirements.in
- snowflake/pyproject.toml
https://github.com/DataDog/integrations-core/pull/13756 but applied to `7.42.x`.
> Backport snowflake-connector-python bump 2.8.3 to 7.42.x

- cloudera/datadog_checks/cloudera/api_client_factory.py
- cloudera/datadog_checks/cloudera/api_client_v7.py
Make debug logging less verbose by changing logged raw responses to trace-level and supplementing them with less verbose debug logs.
> Make debug logging less verbose

- yarn/assets/service_checks.json
Update service check metadata with the `yarn.application.status` service check which wasn't documented previously.
> Update service checks metadata

- databricks/README.md
Removes a sentence directing readers to an outdated doc page with deprecated instructions for setting up Agent v7 and cleans up some links.
DOCS-4679
> DOCS-4679 Databricks Integration Edit

- cloudera/datadog_checks/cloudera/api_client_v7.py
- cloudera/tests/test_unit.py
Adds a test to ensure that at least on one scenario where an exception is raised on a sub-thread, that is captured by the main thread and reported as expected (as a critical service check).
It also factors out the common logic for making those exceptions raise on the parent thread, trying to make the purpose of #13739 more explicit and documented.
While doing QA for #13739, I couldn't tell right away what it was for.
> Add test and refactor for raising exceptions inside thread executor

- .github/workflows/slapr.yml
Add the tools squad slack channel to slapr
Automatically add emojis to our slack messages.
> Add the tools squad slack channel to slapr

- mysql/README.md
This documentation is not in line with our actual config file. Update to match.
> mysql/readme: correct param names in documentation

- airflow/manifest.json
Add process signatures.
https://datadoghq.atlassian.net/browse/AI-2893
> Add process signatures

- rabbitmq/tests/conftest.py
> Explain why we don't load openmetrics tests in certain contexts

- rabbitmq/tests/conftest.py
- rabbitmq/tests/metrics.py
- rabbitmq/tests/test_openmetrics.py
> Simplify tests and remove duplication

- rabbitmq/datadog_checks/rabbitmq/openmetrics/check.py
- rabbitmq/tests/fixtures/detailed-queue_coarse_metrics-queue_consumer_count.txt
- rabbitmq/tests/fixtures/detailed-queue_coarse_metrics.txt
- rabbitmq/tests/fixtures/detailed-queue_consumer_count.txt
- rabbitmq/tests/fixtures/detailed.txt
- rabbitmq/tests/fixtures/metrics.txt
- rabbitmq/tests/fixtures/per-object.txt
- rabbitmq/tests/test_openmetrics.py
Documents and tests that we share the node/cluster labels amongst all metrics.
This feature was originally merged untested due to time constraints. Now we have tests to confirm it works and we learned something about its limitations along the way!
> Test and document label sharing

- rabbitmq/tests/metrics.py
- rabbitmq/tests/test_openmetrics.py
> Fix and extend test for combination of endpoints

- argocd/README.md
* Corrects the annotations to include the protocol (`http://`) and removes the extra curly bracket in `init_config` : `{}}` -> `{}`
* Adds a blank line after the list of ArgoCD components so the `.md` is properly rendered.
* Adds a link to the sample conf yaml to easily find additional configuration options (mirroring our other integrations page)
* Troubleshooting an issue from a customer, I found that the doc needed some clearing. The first bullet point is the important one : without the `http://`, the integration would fail with a no protocol found error, and with the extra curly bracket, I would imagine the Agent also fails as the JSON is invalid and thus cannot be parsed into a YAML
> Fixes ArgoCD annotations + add sample conf + nits clearing

- .github/CODEOWNERS
Adds platform integrations as codeowners for cloud foundry api
> Add platform integrations as codeowners for cloud foundry api

- istio/tests/conftest.py
Use python to remove temporary files
`rm` is not working on Windows. Sorry about that.
> Use python to remove temporary files

- datadog_checks_base/datadog_checks/base/checks/base.py
- docs/developer/base/api.md
Document agent.warning shows messages in-app
https://datadoghq.atlassian.net/browse/AI-2430
> Document agent.warning shows messages in-app

- snowflake/CHANGELOG.md
To be merged after https://github.com/DataDog/integrations-core/pull/13829 and Agent 7.42.1 is released.
> Update CHANGELOG to include Snowflake 4.4.6 for Agent 7.42.1

- mongo/CHANGELOG.md
- mongo/datadog_checks/mongo/__about__.py
- requirements-agent-release.txt
Update the changelog and versions from a release from 7.43.x branch
> Changelog and version entry from release

- eks_fargate/README.md
Adds a section that briefly talks about cluster performance using the cluster checks runner
> DOCS-1862 eks fargate cluster performance

- ecs_fargate/README.md
Removes note about having to set `DD_DOGSTATSD_NON-LOCAL_TRAFFIC`.
> DOCS-4691 update dogstatsd note on fargate

- helm/README.md
previous language could be misinterpreted as saying that you need to make a cluster check. this language makes clear that all you need to do is add a helm check config, and that more information is available in the cluster checks docs
> DOCS-3987 clarify helm check config

- gke/manifest.json
adds to the integration title to make clear that this is the agent integration
> DOCS-4341 updating gke integration frontmatter

- kafka_consumer/assets/configuration/spec.yaml
- kafka_consumer/datadog_checks/kafka_consumer/config_models/defaults.py
- kafka_consumer/datadog_checks/kafka_consumer/config_models/instance.py
- kafka_consumer/datadog_checks/kafka_consumer/data/conf.yaml.example
- kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
- kafka_consumer/datadog_checks/kafka_consumer/new_kafka_consumer.py
- kafka_consumer/metadata.csv
- kafka_consumer/tests/test_kafka_consumer.py
Remove Data Streams Monitoring added in these PRs:
https://github.com/DataDog/integrations-core/pull/11861
https://github.com/DataDog/integrations-core/pull/12942
Kakfa Consumer check revamp
DSM product as a standalone product
> Remove DSM

- ibm_mq/README.md
Update the supported versions
- Support case
- 8.x and 9.0 EOLed on 2020-04-30 and 2021-09-30
- https://www.ibm.com/support/pages/lifecycle/search/?q=MQ
- I'll add test envs in a future PR for 9.2 and 9.3
> Update the supported versions

- datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/snmp_tile/snmp_{check_name}/manifest.json
See https://github.com/DataDog/integrations-core/pull/13919
> Remove autodiscovery category from the SNMP template

- activemq_xml/manifest.json
- hdfs_datanode/manifest.json
- hdfs_namenode/manifest.json
- kafka_consumer/manifest.json
See https://github.com/DataDog/integrations-core/pull/13919
> Remove autodiscovery category

- mysql/README.md
Removing `"init_config": {}` from the v2 annotations sample, as this is optional in v2.
> DOCS-4583 - MySQL annotations v2 clarification

- kafka_consumer/datadog_checks/kafka_consumer/client/confluent_kafka_client.py
- kafka_consumer/datadog_checks/kafka_consumer/client/kafka_client.py
- kafka_consumer/datadog_checks/kafka_consumer/client/kafka_python_client.py
Add consumer offset and lag collection to kafka consumer refactor
> Add consumer offset and lag collection

- kafka_consumer/datadog_checks/kafka_consumer/client/kafka_client.py
- kafka_consumer/datadog_checks/kafka_consumer/client/kafka_client_factory.py
- kafka_consumer/datadog_checks/kafka_consumer/client/kafka_python_client.py
- kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
- kafka_consumer/tests/test_kafka_consumer.py
This PR moves the implementations of `kafka-python` to its own class rather than directly implemented in the check itself. This step is necessary to make the transition to the new library easier.
> Refactor client creation

- sqlserver/assets/dashboards/SQLServer-Overview_dashboard.json
Updating the name of the SQL Server dashboard. ["SQLServer"](https://en.wikipedia.org/wiki/Microsoft_SQL_Server) is incorrect.
Erodes customer trust in our expertise and makes the dashboard unsearchable when they search for "SQL Server" as separate words.
> Update sql server dashboard name

- mysql/README.md
Updates the MySQL readme to clarify the different offerings Datadog provides for database monitoring as it is a common point of confusion.
> Disambiguate MySQL monitoring offerings

- postgres/README.md
Updates the Postgres readme to clarify the different offerings Datadog provides for database monitoring as it is a common point of confusion.
> Disambiguate Postgres monitoring offerings

- .gitignore
Ignore the config file for direnv, a tool I use locally to set some envvars automatically.
> Git ignores direnv file

- LICENSE-3rdparty.csv
- datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/licenses.py
Update the licenses to update the requests-ntlm name
> Change requests_nltm license entry to requests-nltm

- kafka_consumer/tests/common.py
- kafka_consumer/tests/python_client/__init__.py
- kafka_consumer/tests/python_client/test_e2e.py
- kafka_consumer/tests/python_client/test_integration.py
- kafka_consumer/tests/python_client/test_unit.py
Split the test file into several files depending on their type
- Will be useful to simplify the test suite and make sure we have enough coverage (feature wise)
I'm just moving code around, nothing else
> Split the tests

- kafka_consumer/datadog_checks/kafka_consumer/client/__init__.py
- kafka_consumer/datadog_checks/kafka_consumer/client/confluent_kafka_client.py
- kafka_consumer/datadog_checks/kafka_consumer/client/kafka_client_factory.py
Add missing license headers to some files
> Add missing license headers

- .github/workflows/validations.yaml
Run the `validations` job on each PR, even if they do not target the master branch.
Working on the kafak_consumer check, we open PRs against a main feature branch. We faced a lot of validations errors on the main feature because this job was not running in our other PRs.
> Run the `validations` job on each PR

- .github/workflows/validations.yaml
- kafka_consumer/datadog_checks/kafka_consumer/client/confluent_kafka_client.py
- kafka_consumer/datadog_checks/kafka_consumer/client/kafka_client.py
- kafka_consumer/datadog_checks/kafka_consumer/client/kafka_client_factory.py
- kafka_consumer/datadog_checks/kafka_consumer/client/kafka_python_client.py
- kafka_consumer/datadog_checks/kafka_consumer/config.py
- kafka_consumer/tests/python_client/__init__.py
- kafka_consumer/tests/python_client/test_e2e.py
- kafka_consumer/tests/python_client/test_integration.py
- kafka_consumer/tests/python_client/test_unit.py
> Fix license headers

- sqlserver/README.md
Updates the SQL Server readme to clarify the different offerings Datadog provides for database monitoring as it is a common point of confusion.
> Disambiguate SQL Server monitoring offerings

- kafka_consumer/tests/docker/docker-compose.yaml
Add healthchecks to zookeeper
The e2e is a bit flaky on my laptop. Seems like adding them solved the issue
> Add healthchecks to zookeeper

- requirements-agent-release.txt
- sqlserver/CHANGELOG.md
- sqlserver/datadog_checks/sqlserver/__about__.py
Port the changes from 7.43.x to master. The release was made off 7.43.x
> Update master with release from 7.43.x

- container/metadata.csv
Improve documentation of `container` check
> Add missing in generic container check

- docs/dev/api_integration.md
Updates installation/config docs for API integrations
> Update ddev instructions in api integrations doc

- clickhouse/tests/docker/docker-compose.yaml
> Add health check to zookeeper container, reduce duplication

- datadog_checks_dev/pyproject.toml
Pin the tox version we use to stay below version 4.
> Pin tox to below version 4

- calico/README.md
Update the link
The link was leading to a page not found by Translators.
- Please verify the new link is the correct reference
> Update link to Calico component metrics

- docs/dev/legacy.md
Update the casing of `agent`.
Noticed during unrelated update.
> Fix Agent casing

- ddev/pyproject.toml
> Bump datadog_checks_dev dependency version

- rabbitmq/tests/fixtures/mgmt/overview.json
- rabbitmq/tests/fixtures/mgmt/queues.json
- rabbitmq/tests/test_unit.py
> Add test for queues_regexes field

- datadog_checks_base/CHANGELOG.md
https://github.com/DataDog/integrations-core/commits/7.43.x
> Backport changelog from 7.43.x

- kafka/manifest.json
- kafka/metadata.csv
Users might configure the check to only collect one or the other
> Add another `metric_to_check`

- rabbitmq/datadog_checks/rabbitmq/data/conf.yaml.example
> Sync rabbitmq config example

- rabbitmq/assets/service_checks.json
- rabbitmq/tests/test_openmetrics.py
> Declare OpenMetrics service check in metadata

- couchbase/hatch.toml
Bump couchbase 6 docker image
Version 6.6.6 is available: https://docs.couchbase.com/server/6.6/release-notes/relnotes.html
> Bump couchbase 6 docker image

- datadog_checks_base/CHANGELOG.md
- datadog_checks_base/datadog_checks/base/__about__.py
- requirements-agent-release.txt
- snowflake/CHANGELOG.md
- snowflake/datadog_checks/snowflake/__about__.py
https://github.com/DataDog/integrations-core/commits/7.43.x
> Backport releases

- process/assets/configuration/spec.yaml
- process/datadog_checks/process/data/conf.yaml.example
This PR adds more detail to the `exact_match` config option modified in https://github.com/DataDog/integrations-core/pull/14035.
Clarify for Windows users and make the wording language-agnostic.
> Update wording of exact_match

- cloudera/README.md
This PR improves the wording of the Cloudera README
Cloudera request
> Clean up README

- LICENSE-3rdparty.csv
- datadog_checks_base/datadog_checks/base/data/agent_requirements.in
- kafka_consumer/pyproject.toml
> Add confluent_kafka dependency

- openstack_controller/datadog_checks/openstack_controller/api.py
- openstack_controller/datadog_checks/openstack_controller/openstack_controller.py
Standardizes log messages in the openstack controller check 
clean up
> Standardize log messages

- kafka_consumer/datadog_checks/kafka_consumer/client/confluent_kafka_client.py
- kafka_consumer/datadog_checks/kafka_consumer/config.py
> Create Kafka client for confluent lib

- cloudera/manifest.json
Enable Cloudera on public website.
Agent 7.43 is out
> Display Cloudera integration on public website

- directory/datadog_checks/directory/directory.py
Support case. We were spamming a customer's logs with warnings about not being able to stat files, but all their metrics were in order.
> Convert warning to debug log

- kafka_consumer/datadog_checks/kafka_consumer/client/confluent_kafka_client.py
- kafka_consumer/datadog_checks/kafka_consumer/client/generic_kafka_client.py
> Implement reset_offsets

- .ddqa/config.toml
https://github.com/DataDog/datadog-agent/pull/15675
> Create initial config for DDQA

- kafka_consumer/datadog_checks/kafka_consumer/client/confluent_kafka_client.py
- kafka_consumer/datadog_checks/kafka_consumer/client/generic_kafka_client.py
This PR implements `get_consumer_offsets()` and `get_consumer_offsets_dict()`
> Implement get_consumer_offsets and get_consumer_offsets_dict

- kafka_consumer/tests/python_client/test_unit.py
> Make the tests pass with the legacy implementation

- .ddqa/config.toml
https://github.com/DataDog/ddqa/pull/13
> Finalize the configuration for DDQA

- kafka_consumer/datadog_checks/kafka_consumer/client/confluent_kafka_client.py
- kafka_consumer/datadog_checks/kafka_consumer/client/generic_kafka_client.py
- kafka_consumer/datadog_checks/kafka_consumer/config.py
- kafka_consumer/tests/python_client/test_unit.py
This PR implements `get_highwater_offsets()` and `get_highwater_offsets_dict()`.
> Implement get_highwater_offsets and get_highwater_offsets_dict

- kafka_consumer/tests/common.py
- kafka_consumer/tests/conftest.py
- kafka_consumer/tests/docker/noauth/docker-compose.yaml
Create the topics from the python code instead of the docker image
Simplify the docker compose and make it easier to deal with future authentication methods.
> Create the topics from the python code instead of the docker image

- datadog_checks_dev/tests/tooling/manifest_validator/input_constants.py
Update the macOS classifier
See https://github.com/DataDog/integrations-core/pull/14074.
> Update the macOS classifier

- teamcity/assets/dashboards/overview.json
Update the dashboard. Credit to @anjaliDDog
> Update the dashboard

- databricks/README.md
Update the troubleshooting section to include a common error with Databricks Runtime 11 and above.
Some people faced this issue.
Related PRs and issues:
- https://github.com/DataDog/datadog-process-agent/issues/292
- https://github.com/DataDog/datadog-agent/issues/15191
- https://github.com/DataDog/datadog-agent/pull/10733
> Update the troubleshooting section

- .ddqa/config.toml
https://github.com/DataDog/ddqa/pull/17
> Update the configuration for DDQA

- datadog_checks_dev/tests/tooling/manifest_validator/input_constants.py
- docs/dev/new_check_howto.md
- kubernetes_state_core/manifest.json
Mac OS is deprecated, macOS is new.
DOCS-4971
> DOCS-4971 Batch Cleanup Deprecated Classifier Tag

- avi_vantage/README.md
- avi_vantage/datadog_checks/avi_vantage/check.py
> Remove metric limit for Avi Vantage

- snmp/assets/configuration/spec.yaml
- snmp/datadog_checks/snmp/data/conf.yaml.example
- snmp/metadata.csv
Add interface speed metrics to metadata.csv
> Add interface speed metrics to metadata.csv and config to example.conf.yaml

- cisco_aci/README.md
Add a note on long execution times coming from the check
Support cases
> add long execution description to cisco aci readme

- elastic/README.md
Updates documentation on elastic search privileges if using ElasticSearch security functions and want to get more info from indices.
Client specified discrepancy and misinformation in support ticket 
https://datadog.zendesk.com/agent/tickets/1109402
> Update Elastic Search Doc to reflect use of other privileges

- docs/developer/tutorials/snmp/profile-format.md
Add docs for `format: mac_address`
https://github.com/DataDog/datadog-agent/pull/11557
> Add docs for `format: mac_address`

- snmp/assets/monitors/device_unreachable.json
- snmp/manifest.json
Closes #14023
Add device unreachable recommended monitor
[NDM-1347]: https://datadoghq.atlassian.net/browse/NDM-1347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [snmp] Add device unreachable monitor

- LICENSE-3rdparty.csv
> Update snowflake license copyright years

- amazon_msk/datadog_checks/amazon_msk/amazon_msk.py
- amazon_msk/datadog_checks/amazon_msk/check.py
Make it easier to see openmetrics endpoints on amazon_msk.
Support
> Add debug lines for Openmetrics endpoint

- temporal/hatch.toml
- temporal/tests/README.md
- temporal/tests/compose/docker-compose.yaml
- temporal/tests/compose/worker/Dockerfile
- temporal/tests/compose/worker/run_worker.py
- temporal/tests/conftest.py
> Add the e2e environment

- requirements-agent-release.txt
- sqlserver/CHANGELOG.md
- sqlserver/datadog_checks/sqlserver/__about__.py
https://github.com/DataDog/integrations-core/commits/7.44.x
> [Release] Bumped sqlserver version to 11.0.2

- argocd/assets/dashboards/argo_cd_overview.json
One metric in the dashboard was incorrect. It should be the app_controller one instead of the api_server.
Issue:
https://github.com/DataDog/integrations-core/issues/14005
> fix wrong metric

- datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py
- datadog_checks_dev/datadog_checks/dev/tooling/testing.py
GitHub Actions does not allow for the conditional setting of environment variables
> Consider empty environment variables as unset

- datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py
- datadog_checks_dev/datadog_checks/dev/tooling/manifest_utils.py
Skips metrics metadata CSV validation if the integration isn't a metrics integration.
> Skip metadata validation for non-metrics integrations.

- calico/manifest.json
Process signature for calico
Examples:
```
calico-node -monitor-addresses
calico-node -monitor-token
calico-node -allocate-tunnel-addrs
calico-node -felix
calico-node -status-reporter
```
Linked PR:
https://github.com/DataDog/dd-go/pull/87109
> process signature calico

- docs/developer/tutorials/snmp/profile-format.md
Document support for formating bytes into ip_address
https://github.com/DataDog/datadog-agent/pull/16248
> Document support for formating bytes into ip_address

- sqlserver/README.md
Adds a new blog link to the SQL server page.
Tuesday Tasks.
> Add new blog link to SQL server

- datadog_checks_dev/datadog_checks/dev/ci.py
- datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py
https://github.com/DataDog/integrations-core/pull/14187
> Support GitHub Actions for testing

- LICENSE-3rdparty.csv
Fix the 3rdparty.csv file
Started to fail on my branch https://github.com/DataDog/integrations-core/actions/runs/4529484370/jobs/7977280540?pr=13918
> Fix the 3rdparty.csv file

- docs/developer/tutorials/snmp/profile-format.md
Add docs for SNMP profiles metric tags value mapping
DataDog/datadog-agent#16205
> Add docs for metric tags value mapping

- snowflake/README.md
- snowflake/assets/configuration/spec.yaml
- snowflake/datadog_checks/snowflake/data/conf.yaml.example
Updates the config example for Snowflake based on feedback from the Technical Solutions team.
DOCS-4925
> DOCS-4925: Update account name value

- gitlab/hatch.toml
- gitlab/tests/common.py
- gitlab/tests/conftest.py
- Bump from 13.0.6 to 13.13.15
- Add version 14.10.5
- Bump from 15.3.3 to 15.10.0
- Add a latest environment since GitLab is released quite often
- Update the GitLab password because they changed their password policy in the latest v15.
First step before the revamp
> Update the test environments

- mongo/metadata.csv
> Fix metric description based on customer feedback

- datadog_checks_dev/datadog_checks/dev/plugin/pytest.py
- datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py
```
cannot exec in a stopped state: unknown
```
I tried adding just the logging but the container is removed too soon as shown here https://github.com/DataDog/integrations-core/actions/runs/4547995222/jobs/8018595754
> Get more insight into Agent E2E communication errors

- rabbitmq/README.md
The Containerized section of how to configure this check was missing the `http://` in the `instance_config`  `url` section.
The check was failing without this.
> updating-containerized

- LICENSE-3rdparty.csv
Fix third party licenses
Started to fail on my PRs: 
- https://github.com/DataDog/integrations-core/actions/runs/4563407108/jobs/8051850559
> Fix third party licenses

- kafka_consumer/datadog_checks/kafka_consumer/client/confluent_kafka_client.py
- kafka_consumer/datadog_checks/kafka_consumer/config.py
- kafka_consumer/tests/test_integration.py
- kafka_consumer/tests/test_unit.py
> Implement OAuth config

- .github/workflows/test-results-pr.yml
- .github/workflows/test-target.yml
Condense into a single artifact
> Refactor the structure of the test results artifact

- calico/README.md
Add a further reading section and blog link to the new Calico blog post.
Spread awareness of Datadog's capabilities to monitor Calico.
> Add Further Reading section and link

- LICENSE-3rdparty.csv
- oom_kill/README.md
- tcp_queue_length/README.md
Adds configuration instructions for the operator
Operator pre-GA
> Add operator configuration instructions to oom_kill and tcp_queue_length checks

- datadog_operator/manifest.json
> Make Datadog Operator public

- LICENSE-3rdparty.csv
- druid/assets/configuration/spec.yaml
- druid/datadog_checks/druid/data/conf.yaml.example
After working on ticket https://datadog.zendesk.com/agent/tickets/1152524 , this customer informed me that druid uses multiple urls (druid coordinator / broker / router url) . For this integration to work, the druid coordinator url needs to be used. They requested our docs be more specific regarding which url is used.
Specify which druid url is used. 
https://datadog.zendesk.com/agent/tickets/1152524
> Update druid conf.yaml.example

- istio/manifest.json
Add process signature for Istio
https://datadoghq.atlassian.net/jira/software/c/projects/AI/boards/197?modal=detail&selectedIssue=AI-2889&assignee=61d602cda54af900697e79ba
> add process signature for istio

- .ddev/ci/scripts/traces.py
- .github/workflows/cache-shared-deps.yml
- .github/workflows/submit-traces.yml
- .github/workflows/test-target.yml
The current tool takes ~10 seconds to install on Linux and much more on Windows
> Capture traces without dependencies

- dotnetclr/hatch.toml
- dotnetclr/tests/conftest.py
- dotnetclr/tests/e2e_test.py
https://datadoghq.atlassian.net/browse/AI-2990
Add minimal end to end test for dotnetclr
https://datadoghq.atlassian.net/browse/AI-2990
> Create minimal e2e test for dotnetclr

- docs/dev/api_integration.md
Adding the integration asset table that is referenced in the Marketplace > Develop an Offering doc here as well.
Partner confusion on integration assets like codeowners file
> Update api_integration.md to include integration asset table

- temporal/assets/configuration/spec.yaml
- temporal/datadog_checks/temporal/data/conf.yaml.example
- temporal/manifest.json
- temporal/tests/compose/docker-compose.yaml
- temporal/tests/compose/template/config_template.yaml
- temporal/tests/conftest.py
> Collect the temporal logs

- temporal/assets/dashboards/server_overview.json
- temporal/assets/monitors/FrontendLatency.json
- temporal/assets/monitors/HistoryLatency.json
- temporal/assets/monitors/MatchingLatency.json
- temporal/assets/monitors/PersistenceLatency.json
- temporal/manifest.json
Adds a dashboard for the Temporal integration.
> Add Temporal assets

- ddev/pyproject.toml
Bump datadog_checks_dev version in ddev
> Bump datadog_checks_dev version in ddev

- pulsar/manifest.json
Add a process signature for pulsar for use with procmatch
Corresponding dd-go PR here: https://github.com/DataDog/dd-go/pull/89168 
https://datadoghq.atlassian.net/browse/AI-2987
> Add pulsar process signature

- istio/manifest.json
update procmatch signatures for istio
> update signatures for istio

- LICENSE-3rdparty.csv
- datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/licenses.py
Collect copyright information for the exact versions of the dependencies we need. Previously we got it from `main` branches of the source code repos.
This check was flaky to the point of disturbing and distracting us. I also think conceptually it makes more sense to care about copyright notices of the exact versions of dependencies that we currently use.
Should we also limit the CI job to only trigger on changes to the `agent-requirements.in` file?
> Make license validation deterministic wrt dependency specification

- process/datadog_checks/process/config_models/defaults.py
- process/datadog_checks/process/config_models/instance.py
- process/datadog_checks/process/data/conf.yaml.example
Finishes https://github.com/DataDog/integrations-core/pull/14337
CI failing
> Sync process config

- docs/developer/tutorials/snmp/introduction.md
Replace SNMP Labs MIB repository dead link
Dead link.
> Replace SNMP Labs MIB repository dead link

- LICENSE-3rdparty.csv
- datadog_checks_base/datadog_checks/base/data/agent_requirements.in
QA for https://github.com/DataDog/integrations-core/pull/14020
This dependency is used only for testing so it should not be added to the agent
> Do not add dependency to agent

- docs/developer/setup.md
Update the `ddev` install docs for ARM macs
Similar to https://datadoghq.dev/integrations-core/setup/#stable
> Update the `ddev` install docs for ARM macs

- temporal/assets/dashboards/server_overview.json
Collection of small nits to the temporal OOTB dashboard
> Temporal dashboard nits

- snmp/datadog_checks/snmp/data/profiles/_generic-bgp4.yaml
- snmp/datadog_checks/snmp/parsing/metrics.py
- snmp/tests/test_e2e_core.py
- snmp/tests/test_e2e_core_vs_python.py
- snmp/tests/test_profiles.py
Modify BGP SNMP profile to use constant metrics and tag value mapping.
The PR also modify the SNMP python check to avoid failing when using `constant_value_one` in profiles.
> [SNMP] Enriched BGP profile

- azure_iot_edge/README.md
Metrics have been enabled by default for years https://github.com/Azure/iotedge/commit/609a272716f7fbaae29a69854c1443e19b7df753
> Remove outdated instructions

- elastic/datadog_checks/elastic/metrics.py
The main goal is to make it easier in the future to add metrics that were introduced with a certain version of ES. It also reduces some duplication of information, since we don't need to have the ES version in the variable name and in the version spec used in the conditional.
> Generalize adding stats metrics

- gitlab/assets/service_checks.json
Update the agent version for the Gitaly service check.
Gitaly metrics and service check were added in [this PR](https://github.com/DataDog/integrations-core/pull/14316). In this PR the agent version was supposed to be 7.45, having 7.44 was a mistake. 
We did not manage to ship this feature with agent 7.45 so we need to bump it to 7.46
> Update the agent version for the Gitaly service check

- coredns/README.md
- coredns/assets/configuration/spec.yaml
- coredns/datadog_checks/coredns/config_models/defaults.py
- coredns/datadog_checks/coredns/data/conf.yaml.example
expose less of openmetricsv1 documentation
> Fix coredns documentation

- gitlab/assets/service_checks.json
- gitlab/tests/conftest.py
Small nit to update the version since these all came out in 7.45 instead of 7.44
QA:
https://datadoghq.atlassian.net/browse/AI-3019
> Change service check agent version

- datadog_checks_dev/datadog_checks/dev/docker.py
Without this I had to extract the docker compose command and run it in the terminal to debug why it failed.
If you know of tests I can add for this, please point me towards those 🙏
> Capture stderr from docker compose to improve debugging experience

- mongo/assets/logs/mongodb.yaml
- mongo/assets/logs/mongodb_tests.yaml
Align mongodb integrations with logs-backend
> Logs Assets - Align mongodb integrations with logs-backend

- kafka_consumer/hatch.toml
Pin the test image
We have this problem: https://github.com/bitnami/containers/issues/31789. They override the tags to keep the system up to date. So I pinned it to this particular build which worked. We will revert this once the problem will be fixed.
> Pin the test image

- snmp/assets/monitors/interface_down.json
- snmp/manifest.json
Add a SNMP recommended monitor on interface down
> [SNMP] Add interface down recommended monitor

- .github/workflows/pr-test.yml
https://github.com/re-actors/alls-green#why
> Add a single required check for PRs

- docs/developer/.snippets/links.txt
- docs/developer/testing.md
Kudos to @vivek-datadog for the find!
> Testing documentation references hatch instead of tox

- elastic/assets/configuration/spec.yaml
- elastic/datadog_checks/elastic/config.py
- elastic/datadog_checks/elastic/config_models/defaults.py
- elastic/datadog_checks/elastic/config_models/instance.py
- elastic/datadog_checks/elastic/data/conf.yaml.example
- elastic/datadog_checks/elastic/elastic.py
- elastic/tests/test_elastic.py
https://datadoghq.atlassian.net/browse/AI-2995
> Allow disabling event submission

- gitlab/assets/service_checks.json
Rename the readiness service checks to remove underscores.
This is what we display in the UI
> Rename the readiness service checks

- elastic/assets/configuration/spec.yaml
- elastic/datadog_checks/elastic/data/conf.yaml.example
Kudos to @FlorentClarret for coming up with better wording!
> Improve description of config field

- .github/workflows/run-validations.yml
- .github/workflows/validate.yml
> Apply openmetrics validation to CI

- openai/manifest.json
In preparation for the release
> Display OpenAI to public

- .ddev/config.toml
- .github/workflows/test-all.yml
I noticed while looking at a build
> Update display names

- openai/README.md
Remove unused links from the README file
They are not used
Noticed while I had a quick look at the consul PRs and the tile
> Remove unused links

- openai/README.md
Add blog link and fix links.
New blog
> Add blog link to OpenAI doc

- strimzi/README.md
Update the documentation
Mostly nit comments!
> Update the documentation

- postgres/tests/test_pg_replication.py
- postgres/tests/test_statements.py
- postgres/tests/utils.py
> fix replication tests

- docs/dev/agent_integration.md
> Small Link Fix in Further Reading Section

- etcd/datadog_checks/etcd/etcd.py
- etcd/tests/test_integration.py
> Update etcd leader check to use v3 endpoint instead of v3alpha

- postgres/assets/configuration/spec.yaml
- postgres/datadog_checks/postgres/aws.py
- postgres/datadog_checks/postgres/config_models/instance.py
- postgres/datadog_checks/postgres/data/conf.yaml.example
- postgres/datadog_checks/postgres/postgres.py
> Add region to the PG spec && don't use profile to connect

- gitlab/assets/dashboards/overview.json
This PR updates the dashboard of GitLab integration from:
to
> Update Gitlab dashboard

- gitlab/README.md
Update the metrics section to explain some metrics are specific to a given implementation
It was not clear enough
> Update the metrics section

- postgres/assets/configuration/spec.yaml
- postgres/datadog_checks/postgres/aws.py
- postgres/datadog_checks/postgres/config.py
- postgres/datadog_checks/postgres/config_models/instance.py
- postgres/datadog_checks/postgres/data/conf.yaml.example
- postgres/datadog_checks/postgres/metadata.py
- postgres/datadog_checks/postgres/postgres.py
- postgres/pyproject.toml
- postgres/tests/conftest.py
- postgres/tests/test_explain_parameterized_queries.py
- postgres/tests/test_metadata.py
- postgres/tests/test_metrics_cache.py
- postgres/tests/test_pg_integration.py
- postgres/tests/test_statements.py
This PR allows customers to configure IAM authentication via setting the `region` field in the `aws` block of the instance config. For example:
```yaml
instances:
- dbm: true
host: foo-endpoint.us-east-2.rds.amazonaws.com
port: 5432
ssl: "true"
username: datadog
aws:
region: us-east-2
instance_endpoint: foo-endpoint.us-east-2.rds.amazonaws.com
```
On the customer side of things, they only need to do the following:
1.  Configure an IAM role, which allows for IAM authentication on the database. E.g.:
```
{
"Version": "2012-10-17",
"Statement": [
{
"Sid": "VisualEditor0",
"Effect": "Allow",
"Action": "rds-db:connect",
"Resource": "arn:aws:rds-db:<region>:<account-id>:dbuser:<db-instance-id>/db-user"
}
]
}
```
2. Grant the role to the DD user on their RDS instance
```
GRANT rds_iam TO …
```
> Support IAM based RDS authentication

- openai/assets/dashboards/overview_dashboard.json
Fix a link in the dashboard
The link is missing
> Fix a link in the dashboard

- temporal/manifest.json
Make the Temporal integration public.
Agent 7.45.0 release.
> Display the Temporal integration on the public website

- disk/datadog_checks/disk/disk.py
Provide an argument's name in a function call.
Easier to understand what the argument means, boolean flags are notoriously opaque when passed as just positional arguments.
> Make argument explicit to improve clarity

- mongo/datadog_checks/mongo/mongo.py
> Remove service check that we don't submit from class docstring.

- cloudera/README.md
Adds blog post link to Cloudera docs.
Tuesday Tasks
> Add Cloudera blog post link

- docs/dev/oauth_for_integrations.md
Adds an alias to a previous URL of this doc page.
> Add Alias to OAuth for Integrations

- envoy/tests/test_e2e.py
- envoy/tests/test_integration.py
Add service checks validations
- QA for https://datadoghq.atlassian.net/browse/AI-3095
- They were missing
> Add service checks validations

- docs/developer/testing.md
Consistently use sentences in a bullet list. Add explanation for pytest's `-s` option that follows from our `--debug` flag.
Saw this while working on the team testing guidelines.
> Small wording improvements to pytest-equivalent options

- datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py
Rephrase the `--dev` description for the `start` command
I was a bit confused by the way we explained it.
> Rephrase the `--dev` description for the `start` command

- envoy/tests/common.py
- envoy/tests/conftest.py
- envoy/tests/test_unit.py
Test the metadata collection for OMv2 in a unit test
We were missing some tests https://app.codecov.io/gh/DataDog/integrations-core/blob/master/envoy/datadog_checks/envoy/check.py#L145
> Test the metadata collection for OMv2

- mongo/datadog_checks/mongo/collectors/custom_queries.py
- mongo/datadog_checks/mongo/collectors/db_stat.py
- mongo/datadog_checks/mongo/collectors/fsynclock.py
- mongo/datadog_checks/mongo/collectors/replica.py
- mongo/datadog_checks/mongo/collectors/replication_info.py
- mongo/datadog_checks/mongo/collectors/top.py
Adds some additional debug log entries
> Add debug logs

- mongo/README.md
See [DOCS-5575](https://datadoghq.atlassian.net/browse/DOCS-5575)
[DOCS-5575]: https://datadoghq.atlassian.net/browse/DOCS-5575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (DOCS-5575) Clarify MongoDB additional metrics

- datadog_checks_dev/datadog_checks/dev/docker.py
This reverts commit 8fe361407c3164bbcf75574a353bd6ebe7bec475.
This change broke our confluent_platform tests. We will try to find another approach to fix the original issue.
cc @iliakur as the original author and we discussed about that today
> Revert "Capture stderr from docker compose to improve debugging experience" (#13949)

- mongo/pyproject.toml
- oracle/pyproject.toml
Downgrade requirements to 3.8
I bumped it in [this PR](https://github.com/DataDog/integrations-core/pull/14701) by accident and the validation that is failing on master was green on the PR 🤔 https://github.com/DataDog/integrations-core/actions/runs/5213090364/jobs/9407589424
> Downgrade requirements to 3.8

- nfsstat/tests/compose/client/setup.sh
- nfsstat/tests/compose/compose.yaml
Fix the e2e tests and pin the versions
"Keep the bar green"
> Fix the e2e tests

- gitlab/tests/common.py
- gitlab/tests/test_e2e.py
Try to fix flaky tests.
The e2e tests are a bit flaky on master because the metrics are not always exposed.
> Try to fix flaky tests

- .ddqa/config.toml
> Update DDQA config

- ddev/tests/cli/meta/scripts/test_upgrade_python.py
https://github.com/DataDog/integrations-core/pull/14700#discussion_r1221919899
> Uncomment test assertions

- LICENSE-3rdparty.csv
- datadog_checks_base/datadog_checks/base/data/agent_requirements.in
- snowflake/pyproject.toml
Complement PR to https://github.com/DataDog/datadog-agent/pull/17445
https://github.com/DataDog/integrations-core/pull/14670#issuecomment-1574022248
> Bump snowflake connector python to 3.0.4

- Dockerfile
Drop an unused file
This file was added by accident in this PR: https://github.com/DataDog/integrations-core/pull/14738
> Drop an unused file

- docs/developer/tutorials/snmp/profile-format.md
- Add scale factor to doc
- Move all "symbol modifiers" to a separate section (symbol modifiers can be applied to symbols present in scalar metrics, table metrics, metadata, metric_tags, etc)
> Add scale factor to doc

- strimzi/pyproject.toml
Update the license field
https://github.com/DataDog/integrations-core/pull/14326 was merged right before https://github.com/DataDog/integrations-core/pull/14744
> Update the license field

- oracle/assets/dashboards/dbm_oracle_database_overview.json
- oracle/manifest.json
This PR adds a new Oracle DBM dashboard.
The dashboard displays new sysmetrics that were added with Oracle DBM monitoring.
[Slack discussion](https://dd.slack.com/archives/C9WBCH0AF/p1686299332021979)
> Add DBM Oracle dashboard

- snmp/assets/dashboards/netflow_monitoring.json
- snmp/manifest.json
Update Netflow dashboard
https://datadoghq.atlassian.net/browse/NDM-1585
> Update Netflow dashboard

- datadog_checks_dev/datadog_checks/dev/tooling/commands/release/changelog.py
- datadog_checks_dev/datadog_checks/dev/tooling/commands/release/make.py
- datadog_checks_dev/datadog_checks/dev/tooling/release.py
- datadog_checks_dev/datadog_checks/dev/tooling/utils.py
Releasing broke after https://github.com/DataDog/integrations-core/pull/14778
> Fix ability to release ddev

- snmp/tests/test_e2e_core_metadata.py
Sort assert_device_metadata tags
To make metadata assertions less fragile.
> Sort assert_device_metadata tags

- ddev/pyproject.toml
Add `pluggy` to ddev's `pyproject.toml`
> Add pluggy to ddev dependencies

- ddev/src/ddev/utils/git.py
- ddev/tests/conftest.py
- ddev/tests/utils/test_git.py
Upcoming commands will use these
> Add Git utilities

- .gitlab/tagger/Dockerfile
Our dev tool is being rewritten, and also the reminder job hasn't been used in a long time so I just removed it until/if we need it again
> Update Gitlab pipelines

- cassandra/README.md
Add Containerized Instructions (Kubernetes and Docker) to Cassandra Log Collection Section 
https://datadog.zendesk.com/agent/tickets/1235955
> Add Containerized Instructions to Cassandra Log Collection Section

- .gitlab/tagger/Dockerfile
> Remove [cli]

- .gitlab/tagger/Dockerfile
> Build ddev in separate image for tagger

- argocd/CHANGELOG.md
> Update formatting for changelogs

- ddev/pyproject.toml
Updates version of datadog-checks-dev in ddev's pyproject.toml
> Update version of datadog-checks-dev

- snowflake/README.md
Fixes the `yaml` file where we incorrectly defined `user` as the param, instead it should be `username`.
[DOCS-5721](https://datadoghq.atlassian.net/browse/DOCS-5721)
Per https://github.com/DataDog/integrations-core/blob/master/snowflake/datadog_checks/snowflake/data/conf.yaml.example#L60 
[DOCS-5721]: https://datadoghq.atlassian.net/browse/DOCS-5721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update README.md with username fixes

- datadog_checks_dev/datadog_checks/dev/tooling/commands/env/test.py
Update a log message to mention `hatch` instead of `tox`
We do not use tox anymore
> Update a log message to mention `hatch` instead of `tox`

- snmp/datadog_checks/snmp/data/default_profiles/3com-huawei.yaml
- snmp/metadata.csv
- snmp/tests/test_e2e_core_profiles/test_profile_3com_huawei.py
Update metadata.csv for 3com-huawei profile
> Update metadata.csv for 3com-huawei profile

- oracle/datadog_checks/oracle/oracle.py
> Add better logging in oracle

- .github/workflows/cache-shared-deps.yml
- .github/workflows/pr-all.yml
- .github/workflows/pr-test.yml
- .github/workflows/test-target.yml
Setup python2.7 using apt for linux and choco for windows.
Mitigation for https://github.com/actions/setup-python/issues/672
https://datadoghq.atlassian.net/wiki/spaces/AI/pages/3066003939/Python2+test+strategy+for+agent+releases
> [AITOOLS-194] Custom python2.7 setup for integrations-core pipeline

- elastic/CHANGELOG.md
- elastic/datadog_checks/elastic/__about__.py
- requirements-agent-release.txt
Cherry pick https://github.com/DataDog/integrations-core/pull/15055 on master
> Bumped elastic version to 5.4.2 (#15055)

- ibm_db2/README.md
The original instructions were for `ibm_db` v3.1.0 applicable for Ubuntu and could be copy-pasted. However, it is better to be OS-agnostic and not be specific to a version.
> Generalize instructions

- oracle/README.md
Remove `metric_prefix` from the Oracle README and update associated content
DOCS-5301
> (DOCS-5301) Remove metric_prefix

- datadog_checks_dev/tests/docker/test_default.yaml
Pin the vault version used in the tests
They no longer provide a `latest` image: https://hub.docker.com/_/vault/tags?page=1 and tests are failing
```
----------------------------- Captured stderr call -----------------------------
vault Pulling 
vault Error 
Error response from daemon: manifest for vault:latest not found: manifest unknown: manifest unknown
vault Pulling 
vault Error 
Error response from daemon: manifest for vault:latest not found: manifest unknown: manifest unknown
vault Pulling 
vault Error 
Error response from daemon: manifest for vault:latest not found: manifest unknown: manifest unknown
```
> Pin the vault version

- elastic/datadog_checks/elastic/elastic.py
Part of QA for 7.46, but we decided we don't need to backport this and keep just in master.
https://datadoghq.atlassian.net/browse/AI-3134
> Catch only requests-related exceptions

- ddev/hatch.toml
- ddev/pyproject.toml
- ddev/src/ddev/cli/__init__.py
- ddev/src/ddev/cli/application.py
- ddev/src/ddev/cli/clean/__init__.py
- ddev/src/ddev/cli/terminal.py
- ddev/src/ddev/config/model.py
- ddev/src/ddev/integration/core.py
- ddev/src/ddev/repo/constants.py
- ddev/src/ddev/repo/core.py
- ddev/src/ddev/utils/github.py
- ddev/tests/config/test_model.py
- ddev/tests/conftest.py
- ddev/tests/fixtures/network/github/get_pr_found.yaml
- ddev/tests/fixtures/network/github/get_pr_no_match.yaml
- ddev/tests/integration/test_core.py
- ddev/tests/utils/test_github.py
Necessary for upcoming commands
> Add utilities for GitHub

- win32_event_log/README.md
Small clarification from @iglendd on why we recommend using the `query` option.
Missed in #14765.
> Win32 Event Log Edit

- azure_active_directory/README.md
Update a link to point to the new Azure logs guide
DOCS-5393
> (DOCS-5393) Update link to Azure logs guide

- docs/dev/python.md
Bump python version in ddev installation instructions
ddev is now py3.9
> Bump python version in ddev installation instructions

- argocd/manifest.json
- calico/manifest.json
- foundationdb/manifest.json
- torchserve/manifest.json
Add missing log source names 
https://gitlab.ddbuild.io/DataDog/integrations-core/-/jobs/290304086 is failing because we forgot to declare the source name in the manifest
I will add a card to add this as part of our validations
> Add missing log source names

- ibm_ace/README.md
Update [IBM ACE ](https://docs.datadoghq.com/integrations/ibm_ace/) documentation to note the importance of correctly setting the environment variable for IBM MQ before setting up IBM ACE.
[DOCS-5778](https://datadoghq.atlassian.net/browse/DOCS-5778)
Preview:
[DOCS-5778]: https://datadoghq.atlassian.net/browse/DOCS-5778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update README.md with Env Variable Note

- docs/dev/legacy.md
- docs/dev/oauth_for_integrations.md
Small anchor link fixes in the Developers doc set.
Link checker output, ready to merge.
> Update Anchor Links in Developer Documentation

- kafka_consumer/datadog_checks/kafka_consumer/client.py
- kafka_consumer/datadog_checks/kafka_consumer/config.py
- kafka_consumer/tests/test_integration.py
> Update regex filtering to be more efficient

- gitlab/README.md
Add a section about CI Pipeline visibility
> Add a section about CI Pipeline visibility

- temporal/README.md
> Fix the numbered list

- torchserve/assets/logs/torchserve.yaml
- torchserve/assets/logs/torchserve_tests.yaml
Logs integrations synchronisation from logs-backend to integrations-core - TorchServe
> Logs integrations synchronisation from logs-backend to integrations-core - TorchServe

- ibm_ace/README.md
- ibm_ace/manifest.json
Document log collection
We have a log pipeline but we do not document it and the log source name is not declared
> Document log collection

- oom_kill/README.md
Updates the documentation on this page to reference the current source for the datadog helm charts, as the one linked has been archived.
Reading the docs and being pointed to outdated sources. 
N/A
> Link to current datadog helm chart repository

- directory/README.md
This is mapped to documentation and that is why I was tried to improve it. Added to the troubleshooting section but perhaps it should be added to config section. Not sure if needs to be translated to other languages. It is based on the real customer case.
> Added a warning about very large directory check

- tcp_queue_length/README.md
Update the helm charts link 
Same as https://github.com/DataDog/integrations-core/pull/14725
> Update the helm charts link

- kubelet/datadog_checks/kubelet/common.py
- kubelet/tests/fixtures/pods_images_sha.json
- kubelet/tests/test_common.py
Fix a bug that prevent some images to be included/excluded based on image path when an image you only referenced by `sha256`.
Bugfix.
> kubelet: fallback from image to imageID to align with Go counterpart

- cockroachdb/tests/README.md
- cockroachdb/tests/conftest.py
- cockroachdb/tests/docker/docker-compose.yaml
- cockroachdb/tests/docker/sql.sh
Adds a sql script and documents how to enable the E2E cockroachdb environment to run script and populate SQL metrics.
> Document how to populate sql metrics

- flink/manifest.json
Add process signature for flink integration
Include flink to [process discovery integration catalog](https://datadoghq.atlassian.net/wiki/spaces/PROC/pages/2196539020/Process+Discovery+integration+catalog)
[AI-2985 comment](https://datadoghq.atlassian.net/browse/AI-2985?focusedCommentId=1155220)
> [AI-2985] Add process signature for flink integration

- .github/workflows/build-ddev.yml
- ddev/hatch.toml
Account for https://github.com/DataDog/integrations-core/pull/15166
> Fix builds

- datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/pyproject.toml
- datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/pyproject.toml
- datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/pyproject.toml
Bump the minimal base check version in the integration templates
Part of the release process
> Bump the minimal base check version in the integration templates

- snmp_aruba/manifest.json
Update display_on_public_website to true
> Update display_on_public_website to true

- dcgm/README.md
Editorial reviews for the original PR: [https://github.com/DataDog/integrations-core/pull/14589](https://github.com/DataDog/integrations-core/pull/14589)
The PR had to be merged before I had a chance to review it.
> Editorial review of DCGM

- datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/dep.py
```
❯ ddev validate dep -h
Usage: ddev validate dep [OPTIONS] [CHECK]
This command will:
* Verify the uniqueness of dependency versions across all checks, or
optionally a single check * Verify all the dependencies are pinned. * Verify
the embedded Python environment defined in the base check and requirements
listed in every integration are compatible. * Verify each check specifies a
`CHECKS_BASE_REQ` variable for `datadog-checks-base` requirement *
Optionally verify that the `datadog-checks-base` requirement is lower-
bounded * Optionally verify that the `datadog-checks-base` requirement
satisfies specific version
```
```
❯ ddev validate dep -h
Usage: ddev validate dep [OPTIONS] [CHECK]
This command will:
* Verify the uniqueness of dependency versions across all checks, or optionally a …
```
> Fix formatting of list in click command help string

- datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/licenses.py
More convenient to copy/paste when fixing the licenses.
> Show full command to generate valid 3rdparty licenses

- postgres/pyproject.toml
Bump the minimum datadog-checks-base version
- https://github.com/DataDog/integrations-core/pull/14577 added stuff to the base check used in the postgres check and did not bump the min base check version.
- Nightly CI is broken https://github.com/DataDog/integrations-core/actions/runs/5516011250/jobs/10056955746
> Bump the minimum datadog-checks-base version

- .github/workflows/pr-test.yml
https://github.com/DataDog/integrations-core/pull/14718#issuecomment-1608053243
> Skip trace submission for contributors

- dcgm/README.md
> Implement product feedback to readme

- docs/dev/agent_integration.md
Bump python version to 3.9 in the "Create an Agent Integration" [page](https://docs.datadoghq.com/developers/integrations/agent_integration/?tab=buildanoutoftheboxintegration#prerequisites)
We now use py3.9
> Bump python version to 3.9 in the "Create an Agent Integration" page

- kafka_consumer/datadog_checks/kafka_consumer/constants.py
While QAing #15098 I thought I would do future us a favor by adding the explanation for the constant value.
> Add explanation for constant value.

- docs/developer/setup.md
- Update the python version in the ddev documentation.
- Also mention the GitHub releases
- We now use py3.9
- This page https://datadoghq.dev/integrations-core/setup/
> Update the python version in the ddev documentation

- terraform/manifest.json
Updates the title casing for the Terraform integration.
DOCS-5254
> (DOCS-5254) Fix title casing

- mysql/README.md
Remove two unused reference links.
DOCS-5287
> (DOCS-5287) Remove unused links

- cockroachdb/hatch.toml
Specify DDEV_SKIP_GENERIC_TAGS_CHECK in the latest env
We forgot to set it and the CI is failing https://github.com/DataDog/integrations-core/actions/runs/5504250352/jobs/10030330352
> Specify `DDEV_SKIP_GENERIC_TAGS_CHECK` in the latest env

- openai/README.md
> add node.js information to openai integration

- win32_event_log/README.md
Adds a blog post to the Further Reading section of the Win32 Event Log integration.
#writing on Slack
> Win32 Event Log Integration Further Reading Section Update

- docs/developer/tutorials/snmp/profile-format.md
Update profile-format.md for metric_type
> Update profile-format.md for metric_type

- iis/tests/test_iis.py
Run the legacy tests on py3
Same as https://github.com/DataDog/integrations-core/pull/15252
> Run the legacy tests on py3

- vsphere/tests/common.py
Add constants for test variables and remove option to set environment variables for them.
cleanup, and these instances aren't used in end to end tests so there should be no need for env variables to set them
> Add constants for test variables

- amazon_eks/manifest.json
Updates title ~and description~ for the Amazon EKS integration.
To match the product marketing name used by AWS
> Update title for Amazon EKS

- weaviate/assets/monitors/node_status.json
- weaviate/manifest.json
Adds a simple recommended monitor for Weaviate
> Add recommended monitor for Weaviate

- foundationdb/assets/monitors/service_check.json
- mysql/assets/monitors/replica_running.json
- postgres/assets/monitors/percent_usage_connections.json
- vertica/assets/monitors/vertica_replication_safety.json
Fix some broken monitor definition. These monitor definition are validated using `/api/v1/monitor/validate` API
> fix monitor definition

- torchserve/README.md
> Add the "coming soon" banner

- torchserve/assets/dashboards/overview.json
- torchserve/manifest.json
Add the dashboard, feat. @anjaliDDog
> Add the dashboard

- vsphere/metadata.csv
Add missing quote in `metadata.csv`
thanks @steveny91 for catching! https://github.com/DataDog/integrations-core/pull/15347#issuecomment-1650860457
> Add missing quote in `metadata.csv`

- .github/workflows/run-validations.yml
Other repositories sometimes wish to pin the version
> Add input to control the version of ddev

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/test-build-devcontainer.yml
- Dockerfile
Add VScode devcontainer configuration file (+ Dockerfile) to all the tooling ready to work on an integration.
Ease working on this repository. In our team we often struggle to configure our local environment to have all the proper tools (python, ddev, ruff....). By providing a Dockerfile with all the needed tools already configured, we want to speed up our local dev environment and be more efficient in our tasks.
It is a draft PR to open the discussion. we might me able to improve this PR thanks to your feedback.
> feat(tool): Add vscode devcontainer config

- weaviate/assets/dashboards/overview_dashboard.json
- weaviate/manifest.json
> Weaviate OOTB Dashboard

- dcgm/manifest.json
> Make dcgm docs public

- torchserve/README.md
> Add plain coming soon notice and remove un-rendered divs

- dcgm/README.md
- dcgm/manifest.json
> Add plain coming soon and remove un-rendered divs

- torchserve/manifest.json
Enable TorchServe docs for public
> Enable TorchServe docs for public

- torchserve/README.md
* Updates `README.md`
* Internal discussion with Ilia
> [Torchserve] Readme feedback

- airbyte/README.md
Slight rule changes. On staging it's mapping 79/79 when tested with the script.
Also change the white space. Reasoning:
So that it can be copied and pasted directly. Otherwise you would need to copy and paste and then remove the extra tabs.
> small nits to rules

- .devcontainer/devcontainer.json
Stop manually building pytest-memray i nthe dev container
[memray 1.9.0](https://github.com/bloomberg/memray/issues/426) got released with a fix
> Stop manually building pytest-memray

- marklogic/hatch.toml
- marklogic/tests/compose/cluster/docker-compose.yml
- marklogic/tests/compose/standalone/docker-compose.yml
- marklogic/tests/conftest.py
- marklogic/tests/test_marklogic.py
Update the docker image for marklogic 9 and 10. 
- The image for version 9 has been completely removed.
- Marklogic 9 is still supported https://help.marklogic.com/
- The image for marklogic 10 was changed
- Keep the bar green
- I pushed the image to our docker repository. Image can be built with https://github.com/marklogic/marklogic-docker
- They modified the logs so I also updated that
> Use other docker images to run the tests

- datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/CHANGELOG.md
- datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/CHANGELOG.md
- datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/CHANGELOG.md
- datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/metrics_pull/{check_name}/CHANGELOG.md
- datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/snmp_tile/snmp_{check_name}/CHANGELOG.md
- datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/tile/{check_name}/CHANGELOG.md
Update formatting of changelog templates to the new format
> Update formatting of changelog templates

- snmp/assets/configuration/spec.yaml
- snmp/datadog_checks/snmp/data/conf.yaml.example
Adds documentation for previously merged feature of interface tagging for the SNMP integration. See PR https://github.com/DataDog/datadog-agent/pull/17625 for implementation.
> [NDM] add interface tagging example

- calico/tests/common.py
- calico/tests/test_e2e.py
Consider flaky metrics in the e2e tests
- I tried to populate this metric in a couple of PRs and never managed to get it collected consistently. 
- Failing here https://github.com/DataDog/integrations-core/actions/runs/5720089482/job/15499398570
> Consider flaky metrics in the e2e tests

- active_directory/pyproject.toml
- iis/pyproject.toml
- rethinkdb/pyproject.toml
Bump the minimum base check version 
Missed them in https://github.com/DataDog/integrations-core/pull/15427
> Bump the minimum base check version

- snmp/datadog_checks/snmp/data/default_profiles/ubiquiti-unifi-security-gateway.yaml
- snmp/tests/compose/data/ubiquiti-unifi-security-gateway.snmprec
- snmp/tests/test_e2e_core_profiles/test_profile_ubiquiti_unifi_security_gateway.py
Add ubiquiti-unifi-security-gateway
> Add ubiquiti-unifi-security-gateway

- dcgm/README.md
- Add troubleshooting section for high resource usage. This involves adding some extra metrics until we support them fully.
- In the review process we also found problems with the "default" recommended metrics, this PR removes any that we do not support.
Feedback on integration dashboard.
> Rework metrics documentation

- network/datadog_checks/network/check_linux.py
Enhance debug logs for ena and ethtool network metric collection
[AGENT-9912](https://datadoghq.atlassian.net/browse/AGENT-9912)
Support [ticket](https://datadog.zendesk.com/agent/tickets/1274320)
[AGENT-9912]: https://datadoghq.atlassian.net/browse/AGENT-9912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AGENT-9912] Improve debug logs for ena and ethtool network metrics

- snmp/datadog_checks/snmp/data/default_profiles/omron-cj-ethernet-ip.yaml
- snmp/tests/compose/data/omron-cj-ethernet-ip.snmprec
- snmp/tests/test_e2e_core_profiles/test_profile_omron_cj_ethernet_ip.py
> Add profile omron-cj-ethernet-ip

- datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/dep.py
Fix for bug introduced in #15416.
> Change equality requirement to subset in dependency validation

- kafka_consumer/datadog_checks/kafka_consumer/client.py
- Reduce number of consumer creations for highwater offset collection
- Remove optimization based on consume group and cluster id
- Explicitly close consumer instance
Context: Optimization based on consumer group and cluster id helped to reduce the number of broker calls, but it still created multiple consumer instances
As the consumer groups are collected based on kafka_connect_str and the same is used for creating consumer at the time of highwater offset collection, they both are bound to be part of the same cluster. This means that highwater offset for (topic, partition) will be the same as the check runs in the context of a single cluster. Therefore it is beneficial to optimize based on (topic, partition) instead of consumer group or cluster id.
> [AGENT-9940] Reduce number of consumer creations

- ntp/README.md
- ntp/metadata.csv
Modifies the description of the ntp.offset metric + one small fix for grammar.
DOCS-5858
> Update ntp metrics description

- iam_access_analyzer/manifest.json
Remove the log collection classifier
- There's no pipeline for this one
- https://gitlab.ddbuild.io/DataDog/integrations-core/-/jobs/308059287#L43
> Remove the log collection classifier

- docs/dev/oauth_for_integrations.md
Restructures the doc and provides more information on testing based on recent partner feedback. Also provides an update on how partners should be adding an Uninstallation section to their README files
(formatting may be off, feel free to commit directly to fix 🙏 )
> Update OAuth docs

- calico/tests/common.py
Mark the `calico.felix.iptables.restore_errors.count` metric as optional
https://github.com/DataDog/integrations-core/actions/runs/5796655772/job/15710798696#step:14:88
> Mark the `calico.felix.iptables.restore_errors.count` metric as optional

- ddev/tests/conftest.py
> Exclude sensitive data from network test fixtures

- ddev/tests/conftest.py
> Filter more known sensitive data for network test fixtures

- .github/workflows/pr-check.yml
- .github/workflows/pr-quick-check.yml
- ddev/CHANGELOG.md
- ddev/src/ddev/cli/release/__init__.py
- ddev/src/ddev/cli/release/changelog.py
- ddev/src/ddev/cli/release/changelog/__init__.py
- ddev/src/ddev/cli/release/changelog/fix.py
- ddev/src/ddev/cli/release/changelog/new.py
- ddev/src/ddev/integration/core.py
- ddev/src/ddev/release/__init__.py
- ddev/src/ddev/release/constants.py
- ddev/src/ddev/repo/core.py
- ddev/src/ddev/utils/git.py
- ddev/src/ddev/utils/github.py
- ddev/src/ddev/utils/scripts/check_pr.py
- ddev/tests/cli/release/test_changelog.py
- ddev/tests/fixtures/network/release/changelog/fix_existing_pr.yaml
- ddev/tests/fixtures/network/release/changelog/fix_no_pr.yaml
- ddev/tests/utils/test_github.py
This will become our new process
> Add changelog enforcement

- openai/manifest.json
> add two new classifiers

- ddev/pyproject.toml
- ddev/src/ddev/cli/validate/licenses.py
This command is on the slower side, so I thought it would be nice to let the caller know what it's up to. From UX standpoint, progress bars do make it easier to tolerate slower-running commands.
> License validation more transparent about where it spends its time

- ddev/tests/cli/release/agent/test_changelog.py
Remove calls to `get_root()` and `set_root()`, and inline the config manipulation to an existing fixture.
Follow up to #15513, I forgot to drop the manipulation of the global root from `datadog_checks_dev` after refactoring.
> Remove global state manipulation from fixture

- datadog_checks_base/CHANGELOG.md
Move the Unreleased section to the top of the file
> Move the `Unreleased` section to the top of the file

- ddev/src/ddev/cli/release/agent/common.py
- ddev/tests/cli/release/agent/test_changelog.py
Simplify some code and add more testing cases for the refactored code.
Recent command migration #15513, I saw room for simplification while doing that.
- Context: The affected code handles some special cases where the agent requirements file had folder names (integration names) rather than python package names. These still need to be dealt with because we retrieve this file from our git history. My simplification revolves mainly around normalizing all names from the requirements file upfront.
- Apart from the added examples to the existing tests, I also ensured that the diff on our current repo state didn't change to double check.
- Having to add `datadog_checks_base` as an example in the tests regretfully led to some funkiness in how the expected output appears in the code because of …
> Refactor code handling normalization of integration names from requirements

- ddev/CHANGELOG.md
- ddev/src/ddev/cli/validate/ci.py
> Fix CI validation

- win32_event_log/README.md
Update links in the readme
https://github.com/DataDog/integrations-core/pull/15557
> Update links in the readme

- kafka_consumer/datadog_checks/kafka_consumer/client.py
- kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
Port [15285](https://github.com/DataDog/integrations-core/pull/15285) and [15476](https://github.com/DataDog/integrations-core/pull/15476) to 7.47
Refer respective pr description for details
> Port Kafka consumer improvements to 7.47.x

- elastic/CHANGELOG.md
- elastic/datadog_checks/elastic/elastic.py
- elastic/tests/test_unit.py
[AGENT-10055](https://datadoghq.atlassian.net/browse/AGENT-10055?focusedCommentId=1202223)
[AGENT-10055]: https://datadoghq.atlassian.net/browse/AGENT-10055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Avoid collecting template metrics on unsupported ES versions

- docs/dev/agent_integration.md
Updates two links to the correct pages
DOCS-6103
I'm new on the docs team, please let me know if I'm doing anything incorrectly.
> Update links to the correct pages

- mkdocs.yml
https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors
> Fix custom documentation color scheme

- datadog_checks_base/datadog_checks/base/data/agent_requirements.in
- postgres/datadog_checks/postgres/connections.py
- postgres/datadog_checks/postgres/explain_parameterized_queries.py
- postgres/datadog_checks/postgres/metadata.py
- postgres/datadog_checks/postgres/postgres.py
- postgres/datadog_checks/postgres/statement_samples.py
- postgres/datadog_checks/postgres/statements.py
- postgres/datadog_checks/postgres/version_utils.py
- postgres/pyproject.toml
- postgres/tests/common.py
- postgres/tests/conftest.py
- postgres/tests/test_connections.py
- postgres/tests/test_deadlock.py
- postgres/tests/test_explain_parameterized_queries.py
- postgres/tests/test_pg_integration.py
- postgres/tests/test_statements.py
- postgres/tests/test_unit.py
> Update pg integration to use pool of psycopg_pools

- postgres/tests/test_pg_integration.py
I accidentally merged a residual comment and I am removing it.
> Remove a commented out pytest.skip line

- mongo/CHANGELOG.md
- mongo/pyproject.toml
Bump base check version to 32.7.0
- https://github.com/DataDog/integrations-core/pull/15470
- https://github.com/DataDog/integrations-core/actions/runs/5863795549/job/15897917056
> Bump base check version to 32.7.0

- teamcity/tests/docker/teamcity_agent/agent.Dockerfile
Fix the tests manually adding a gpg key for perforce
- https://github.com/DataDog/integrations-core/actions/runs/5867534685/job/15908547803#step:14:539
- https://www.perforce.com/perforce-packages
> Fix the tests

- mesos_master/tests/compose/docker-compose.yml
Pin the zookeeper version
- https://github.com/DataDog/integrations-core/actions/runs/5891224129/job/15978034847
- the newest version broke something not related to our monitoring
> Pin the zookeeper version

- airbyte/manifest.json
- dcgm/manifest.json
See the title
These signatures were missing for the integrations.
> Add process signatures to airbyte and dcgm

- kafka_consumer/pyproject.toml
> Add comment for dependency

- .github/workflows/pr-check.yml
- .github/workflows/pr-quick-check.yml
Otherwise the access token doesn't work
> Update PR checker workflow to run on forks

- scylla/CHANGELOG.md
- scylla/assets/configuration/spec.yaml
- scylla/datadog_checks/scylla/data/conf.yaml.example
Add config the newly added metrics from: https://github.com/DataDog/integrations-core/pull/15592
> Add config for new metrics groups

- airbyte/manifest.json
Reworks the process signature for Airbyte
In the process of adding the signature to dd-go's tests I discovered that my first draft didn't work cuz I misunderstood the matching algorithm.
For reference, the relevant dd-go pr:
https://github.com/DataDog/dd-go/pull/100811
> Improve airbyte process signature based on testing with dd-go

- istio/CHANGELOG.md
Add missing unreleased changelog entry
> Add unreleased changelog entry

- gunicorn/tests/test_check.py
This test would fail sometimes when gunicorn didn't spin up all its workers in time.
> Remove test assertions for flaky metric values

- .github/workflows/pr-quick-check.yml
private repositories require the API
> Fix PR quick check job for other repositories

- .github/workflows/pr-quick-check.yml
- ddev/CHANGELOG.md
- ddev/src/ddev/utils/scripts/check_pr.py
A link to the change would not be accessible
> Support private repositories for changelog errors

- ddev/src/ddev/utils/scripts/check_pr.py
The push of the final commit of my previous PR failed and I did not notice...
> Final fix for changelog validation

- dcgm/tests/common.py
Better solution to achieve what we want.
> Enforce list sorting with assertion instead of comment.

- docs/developer/legacy/prometheus.md
reference the correct field name
docs are incorrect
> docs: prometheus.md change `send_histogram_buckets` to `send_histograms_buckets`

- calico/tests/common.py
Add more optional metrics
https://github.com/DataDog/integrations-core/actions/runs/5902270278/job/16010011525?pr=15619
> Add more optional metrics

- vertica/hatch.toml
Add the latest version to the test matrix
I wanted to do it after https://github.com/DataDog/integrations-core/pull/15413 but I forgot
They jumped from 12 to 23 (the year)
> Add the latest version to the test matrix

- langchain/CHANGELOG.md
Update changelog for langchain integration
> Changelog for langchain integration

- docs/developer/guidelines/pr.md
> Update docs about merges to reflect changelog generation changes.

- airbyte/manifest.json
- dcgm/manifest.json
- langchain/manifest.json
- openai/manifest.json
- torchserve/manifest.json
- weaviate/manifest.json
Add AI and LLM classifiers
AI-3439
> Add AI and LLM classifiers

- snmp/datadog_checks/snmp/data/default_profiles/nasuni-filer.yaml
- snmp/datadog_checks/snmp/data/default_profiles/synology-disk-station.yaml
- snmp/datadog_checks/snmp/data/default_profiles/vertiv-watchdog.yaml
- snmp/datadog_checks/snmp/data/default_profiles/western-digital-mycloud-ex2-ultra.yaml
> Add mappings source

- postgres/datadog_checks/postgres/connections.py
- postgres/datadog_checks/postgres/postgres.py
- postgres/tests/test_connections.py
> Set pool close timeouts to 0 in connections tests

- dcgm/manifest.json
> Add Nvidia to the tile

- snmp/tests/test_e2e_core_profiles/test_profile_netgear_readynas.py
Fix test_e2e_profile_netgear_readynas
> [SNMP] Fix test_e2e_profile_netgear_readynas

- datadog_checks_dev/CHANGELOG.md
- datadog_checks_dev/datadog_checks/dev/tooling/commands/dep.py
Allow bumping the version of lz4
https://github.com/DataDog/integrations-core/pull/15746
> Allow bumping the version of lz4

- .github/CODEOWNERS
Updates CODEOWNERS file for `datadog_operator` folder.
Direct PRs to right team.
> Update CODEOWNERS for Datadog Operator

- postgres/CHANGELOG.md
- postgres/datadog_checks/postgres/__about__.py
- requirements-agent-release.txt
Port release changes to master
> [Release] Bumped postgres version to 14.2.2

- .github/workflows/test-target.yml
- ddev/CHANGELOG.md
- ddev/src/ddev/cli/__init__.py
- ddev/src/ddev/cli/test/__init__.py
- ddev/src/ddev/config/constants.py
- ddev/tests/conftest.py
- ddev/tests/validation/test_tracker.py
I can't get Windows to work for now
> Add color output to tests in CI

- snmp/assets/dashboards/datadog_ndm_environment.json
> [NDM] Fix context links in environment dashboard

- .ddqa/config.toml
Update jira project ids to reflect company managed project conversion
Create jira tickets for 7.48.0-rc.4 QA
[Agent OKRs in jira tracking](https://docs.google.com/spreadsheets/d/1IMgAQvNe5A50idA5KkJNip-gnG3IfBTwMy3UcGTYc9w/edit#gid=1473884811)
**Status as of 2023-09-07:**
|Jira Project Name|Current PID|Newly Migrated C|Type|Status|Support Ticket|
|:----|:----|:----|:----|:----|:----|
|Agent Metrics Logs|AML|AMLII|Team-managed Project|In progress|SR-363141|
|Agent Shared Components|ASC|ASCII|Team-managed Project|Done|SR-360974|
|Agent Platform|AP|APL|Team-managed Project|In progress|SR-365451|
|Release Management|AGENTR|AGNTR|Team-managed Project|In progress|365419|
|Windows Agent|WA| |Team-managed Project|In progress| |
|Vector|VEC|VEK|Company-managed Project|In progress|NA|
|Container …
> Update jira project ids to reflect company managed project conversion

- kafka_consumer/CHANGELOG.md
This PR updates the 7.47.x changelog for kafka consumer
Make it better
> Fix 7.47.x kafka consumer changelog

- openstack/README.md
Removing containerized/non-containerized language from the documentation as it's not completely accurate.
This line in the documentation confuses a lot of people.
> removed containerized/non-containerized

- .github/workflows/test-target.yml
Fix the `Nightly minimum base package test` CI job
- https://github.com/DataDog/integrations-core/actions/runs/6142136985
- https://github.com/DataDog/integrations-core/pull/15762
> Fix the `Nightly minimum base package test` CI job

- strimzi/tests/common.py
- strimzi/tests/fixtures/0.34.0/user_operator_metrics.txt
Assert more metrics
- https://github.com/DataDog/integrations-core/actions/runs/6146591409/job/16676384397#step:15:411
```
Found metrics that are not asserted:
- strimzi.user_operator.reconciliations.locked.count
======================= 1 failed, 9 deselected in 7.91s ========================
```
> Assert more metrics

- snmp/CHANGELOG.md
Update PR #15643 changelog from Changed to Fixed
`Changed` will lead to major version update, but the PR is a fix.
> Update PR #15643 changelog from Changed to Fixed

- snmp/CHANGELOG.md
Fix snmp/CHANGELOG.md for 7.48.x
> Fix snmp/CHANGELOG.md for 7.48.x

- datadog_cluster_agent/assets/dashboards/datadog_cluster_agent_overview.json
- snmp/CHANGELOG.md
- snmp/datadog_checks/snmp/data/default_profiles/_dell-rac.yaml
- snmp/datadog_checks/snmp/data/default_profiles/avaya-cajun-switch.yaml
- snmp/datadog_checks/snmp/data/default_profiles/cisco-ucs.yaml
- snmp/tests/test_e2e_core_profiles/test_profile__dell_rac.py
- snmp/tests/test_e2e_core_profiles/test_profile_cisco_ucs.py
Update mappings in SNMP profiles
> Update mappings in SNMP profiles

- snmp/CHANGELOG.md
- snmp/datadog_checks/snmp/data/default_profiles/_dell-rac.yaml
- snmp/datadog_checks/snmp/data/default_profiles/dell-poweredge.yaml
- snmp/tests/test_e2e_core_profiles/test_profile__dell_rac.py
- snmp/tests/test_e2e_core_vs_python.py
> Fix mappings in _dell-rac & dell-poweredge

- docs/developer/base/databases.md
- docs/developer/ddev/cli.md
- hatch.toml
We forgot to remove ASCII art from the CLI rendering
Also upgraded dependencies and fixed an error I was getting locally by not referencing the full path to 2 API objects
> Fix docs build

- temporal/README.md
Links new blog post from the further reading section.
Tuesday tasks: https://www.datadoghq.com/blog/temporal-server-integration/
> Add blog post link to further reading

- kafka/assets/dashboards/kafka_dashboard.json
> Fix Kafka dashboard

- airflow/tests/compose/Dockerfile
Fix airflow test failure
https://github.com/DataDog/integrations-core/actions/runs/6254497264/job/16982190134#step:13:712
> Update Dockerfile for airflow test

- snmp/CHANGELOG.md
- snmp/datadog_checks/snmp/data/default_profiles/_cisco-metadata.yaml
- snmp/tests/test_e2e_core_metadata.py
Update Cisco model metadata regex to also match spaces
> Update Cisco model metadata regex

- strimzi/manifest.json
This PR adds log source name for `strimzi`.
Add official log support for Strimzi
> Add strimzi log support

- datadog_checks_dev/CHANGELOG.md
- datadog_checks_dev/datadog_checks/dev/plugin/pytest.py
Tests are running properly but the output always says `skipped`
> Fix test output rewrite conditional

- snmp/CHANGELOG.md
Fix snmp changelog
The missing `:` is causing issues with the release tooling
> Fix snmp changelog

- postgres/CHANGELOG.md
Moving changelog entry to proper location
> Move changelog to unreleased

- databricks/README.md
Adds options for troubleshooting to the doc.
> (DOCS-5920) Add Databricks troubleshooting steps

- kafka_consumer/CHANGELOG.md
This applies https://github.com/DataDog/integrations-core/pull/15793 to `master` branch.
Reduce confusion about what is included in Agent 7.47.
> Improve Kafka consumer changelog entry for 7.47

- ray/CHANGELOG.md
- ray/assets/configuration/spec.yaml
- ray/datadog_checks/ray/data/conf.yaml.example
Add the log section in the configuration file
- QA for https://github.com/DataDog/integrations-core/pull/15441
- https://datadoghq.atlassian.net/browse/AI-3588
- Spotted working on the README file (https://github.com/DataDog/integrations-core/pull/15976)
This will need to be backported
> Add the log section in the configuration file

- torchserve/README.md
> Fix typos in the readme file

- datadog_checks_dev/CHANGELOG.md
- datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/manifest.json
Fix the manifest template file
The default manifest generated using `ddev create` does not contain not a valid json
> Fix the manifest template file

- snmp/assets/dashboards/netflow_monitoring.json
> Fix NetFlow dashboard typo

- ddev/CHANGELOG.md
- ddev/src/ddev/cli/env/agent.py
- ddev/src/ddev/cli/env/reload.py
- ddev/src/ddev/cli/env/shell.py
- ddev/src/ddev/cli/env/show.py
- ddev/src/ddev/cli/env/start.py
- ddev/src/ddev/cli/env/stop.py
Find and replace overwrote a previous find and replace accidentally when responding to a review request https://github.com/DataDog/integrations-core/pull/15931/commits/c8f242821c3dafb46d202d6bfe0510849e399031
> Fix environment metadata accessor

- kubernetes/assets/dashboards/kubernetes_dashboard.json
Update the Kubernetes Overview dashboard to the new responsive-grid layout.
We want our dashboards to be up-to-date in term of dashboard capabilities.
Deployed to staging, check `Kubernetes - Overview` dashboard.
> [kubernetes] Update the Kubernetes Overview dashboard to the new responsive-grid layout

- strimzi/manifest.json
Enable Strimzi doc to the public
> Make strimzi docs public

- ray/README.md
Update the readme file
- This integration will be released with Agent 7.49
- https://datadoghq.atlassian.net/browse/AI-3253
> Update the readme file

- .gitlab-ci.yml
Add the job URL to the Slack message when the agent build is successful
I had several jobs and PRs and did not know which one succeeded
> Add the job URL to the Slack message when the agent build is successful

- cloudera/README.md
Adds a Requirements heading to the Cloudera documentation, [listing the version requirement](https://github.com/DataDog/integrations-core/blob/caf9bd6f3f00ed916f04fb621313245841785f4a/cloudera/datadog_checks/cloudera/api/factory.py#L36). 
A Zendesk ticket where this came up: https://datadog.zendesk.com/agent/tickets/1385377
Please merge once approved, I don't have permission to merge it myself.
> Cloudera: added requirements section to docs

- kafka_consumer/tests/README.md
Update the test README with the new option
We renamed this option `--recreate`
> Update the test README with the new option

- wmi_check/README.md
- wmi_check/manifest.json
This check is no longer supported or recommended for customers to use.
> Update WMI check to be officially legacy/unsupported

- sqlserver/README.md
This just updates our documentation to warn of a known issue that was discovered on agent 7.48.0 for the sqlserver check.
We want to make sure that we warn about this issue while we are providing a fix since 7.48.0 is available for public download.
> Warn of known agent 7.48.0 issue on ARM architecture.

- docs/developer/guidelines/pr.md
Still following in the steps of https://github.com/DataDog/integrations-core/pull/15983
> Update developer documentation to reflect new process for ints-core

- redisdb/assets/configuration/spec.yaml
Tag redis `password` config as a secret
> Tag redis password as secret

- kafka/assets/dashboards/kafka_dashboard.json
Add a note on Zookeeper widgets in the Kafka dashboard
Zookeeper is no longer required with kafka > 3.0
> Add a note on Zookeeper widgets in the Kafka dashboard

- elastic/assets/monitors/elastic_average_search_latency.json
- elastic/assets/monitors/elastic_indexing_load.json
- elastic/manifest.json
Add new OOTB monitor for elastic indexing metrics
> Add new OOTB monitor for elastic indexing metrics

- ibm_db2/README.md
> Fix broken link

- ray/manifest.json
Make the Ray documentation public
7.49.0 is out
> Make the Ray documentation public

- containerd/metadata.csv
Add `containerd.image.pull` metric to `metadata.csv` of `containerd` integration.
Updating the documentation.
> Add containerd.image.pull metric to metadata.csv in containerd check

- yarn/CHANGELOG.md
- yarn/changelog.d/15980.added
Converts unreleased changelog from #15980 to our new system.
I removed one of the entries because it was no longer relevant as part of some changes that occurred on that PR.
> Convert changelog to new system

- sqlserver/hatch.toml
This PR updates sqlserver 2022 image from preview to cumulative update images.
> update sqlserver 2022 image to cumulative update images

- kubernetes_state_core/README.md
Migrates README from docs repo
This file has been sourced from the documentation repo for a while. It's easier to maintain it here, where we can use the metadata for the metrics.
> (DOCS-6529) Migrate k8s state core doc

- nvidia_triton/CHANGELOG.md
- nvidia_triton/changelog.d/15918.added
- nvidia_triton/datadog_checks/nvidia_triton/__about__.py
Somehow these changes that I made in https://github.com/DataDog/integrations-core/pull/15991 got lost 😢 
We need them to be able to release the integration with the current changelog-generation process.
> Make it possible to release Nvidia Triton

- datadog_checks_dev/changelog.d/16166.fixed
- datadog_checks_dev/datadog_checks/dev/tooling/commands/dep.py
> Exclude orjson when checking for dependency updates

- vsphere/CHANGELOG.md
- vsphere/changelog.d/15992.added
> Add changelog entry in new format

- openstack_controller/assets/dashboards/openstack_controller_overview_[default_microversion].json
Makes a quick fix to the new openstack dashboard
> Add filters to hypervisor query in dashboard

- datadog_checks_base/CHANGELOG.md
- datadog_checks_base/changelog.d/16080.fixed
- ibm_was/CHANGELOG.md
- ibm_was/changelog.d/16080.fixed
- ibm_was/datadog_checks/ibm_was/__about__.py
- requirements-agent-release.txt
- sqlserver/CHANGELOG.md
Clean up changelogs and update with 7.49.1 releases
> Clean up change logs with 7.49.1 releases

- spark/README.md
Add a link to the Amazon EMR blog post 
Used in a support case
> Add a link to the Amazon EMR blog post

- kubelet/changelog.d/16187.fixed
- kubelet/datadog_checks/kubelet/common.py
Quick fix for https://github.com/DataDog/integrations-core/issues/16179
> Always define logger

- .github/workflows/config/labeler.yml
Add missing integrations to the labeler
We somehow forgot about them. I'll create a card to investigate and add that to our automations/validations
> Add missing integrations to the labeler

- couchbase/tests/common.py
Mark some metrics optional
https://github.com/DataDog/integrations-core/actions/runs/6891723951/job/18747491822
> Mark some metrics optional

- .ddev/config.toml
- LICENSE-3rdparty.csv
- datadog_checks_base/changelog.d/16269.removed
- datadog_checks_base/datadog_checks/base/data/agent_requirements.in
- datadog_checks_dev/changelog.d/16269.removed
- datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/licenses.py
- sqlserver/changelog.d/16269.removed
- sqlserver/pyproject.toml
This PR removes `pyro4` and `serpent` dependencies for `sqlserver` integration.
> remove pyro4 and serpent dependencies

- docs/developer/guidelines/pr.md
- mkdocs.yml
Feedback about changelog guidelines.
> Split changelog guidelines into separate tabs based on repo.

- openstack_controller/tests/test_e2e.py
assert glance service check in e2e tests
better e2e coverage
> Assert glance service check

- docs/developer/.scripts/33_render_status.py
Remove the config models and specs progress from [the status page](https://datadoghq.dev/integrations-core/meta/status/)
Migration is now complete 🎉
> Remove the config models and specs progress from the status page

- .ddqa/config.toml
Exclude Shanel in the ddqa config
She's in the GitHub team but I don't think we should assign her QA cards.
> Exclude Shanel in the ddqa config

- .coveragerc
https://app.codecov.io/github/DataDog/integrations-core/tree/master/snmp/tests
> Fix SNMP code coverage

- calico/tests/conftest.py
Add more attempts to the conditions
Sometimes the env is [not ready yet](https://github.com/DataDog/integrations-core/actions/runs/7094147369/job/19308962656). Bumping the attempts from 60 to 100
> Add more attempts to the conditions

- sap_hana/hatch.toml
Update the docker image used in tests
The CI is broken on master because they dropped the image from dockerhub and added another one https://hub.docker.com/r/saplabs/hanaexpress/tags
> Update the docker image used in tests

- coredns/manifest.json
Adds process signature for the CoreDNS integration
For reference, the relevant dd-go PR: https://github.com/DataDog/dd-go/pull/112976
> Adds process signature for the CoreDNS integration

- sonarqube/manifest.json
Adds process signature for the SonarQube integration
For reference, the relevant dd-go PR: https://github.com/DataDog/dd-go/pull/113633
> Adds process signature for the Sonarqube integration

- spark/manifest.json
Adds process signature for the Spark integration
For reference, the relevant dd-go PR: https://github.com/DataDog/dd-go/pull/114099
> Adds process signature for the Spark integration

- strimzi/assets/dashboards/overview.json
- strimzi/manifest.json
Updates our Strimzi OOTB dashboard
> Update Strimzi dashboard

- strimzi/assets/dashboards/overview.json
> Small dashboard naming change

- ray/assets/dashboards/overview_dashboard.json
- ray/manifest.json
Adds dashboard to our Ray integration
> Adds dashboard to Ray integration

- .github/codeql_config.yml
Add back the `codeql_config.yml` file
it worked well without on my PR [here](https://github.com/DataDog/integrations-core/pull/16430) but it now fails [on master](https://github.com/DataDog/integrations-core/actions/runs/7219340347/job/19670179070)
> Add back the `codeql_config.yml` file

- nvidia_triton/README.md
- nvidia_triton/assets/configuration/spec.yaml
- nvidia_triton/changelog.d/16438.added
- nvidia_triton/datadog_checks/nvidia_triton/data/conf.yaml.example
- nvidia_triton/manifest.json
- Add configuration section for logs.
- Add documentation section about logs.
- Add classifier for log collection.
> Nvidia Triton supports log collection

- postgres/tests/common.py
- postgres/tests/test_logical_replication.py
Fix a flaky test
https://github.com/DataDog/integrations-core/actions/runs/7265983705/job/19796910311
> Fix a flaky test

- ray/assets/logs/ray.yaml
- ray/assets/logs/ray_tests.yaml
> Sync logs assets from logs-backend 2023-11-20

- openstack_controller/tests/fixtures/GET/baremetal/v1/nodes/detail/limit=1000/response-1.80.json
- openstack_controller/tests/fixtures/GET/baremetal/v1/nodes/detail/limit=1000/response.json
- openstack_controller/tests/fixtures/GET/baremetal/v1/nodes/detail=True/limit=1000/response-1.80.json
- openstack_controller/tests/fixtures/GET/baremetal/v1/nodes/detail=True/limit=1000/response.json
- openstack_controller/tests/test_unit_ironic.py
Adds a test for when the paginated_limit exceeds the number of ironic nodes
> [PLINT-246] Add a test for a high paginated_limit

- process/README.md
Include the process integration limitation on Windows in the process integration documentation
https://datadoghq.atlassian.net/browse/AI-3125
> Update Process documentation

- .builders/images/linux-x64_86/Dockerfile
> Patches for dependency building

- sqlserver/changelog.d/16461.fixed
- sqlserver/datadog_checks/sqlserver/statements.py
> fix unexpected exception when reporting sqlserver statements obfuscate xml plan error

- karpenter/README.md
Add documentation for Karpenter log collection
> Add documentation for Karpenter log collection

- postgres/CHANGELOG.md
- postgres/changelog.d/16439.fixed
- postgres/datadog_checks/postgres/__about__.py
- requirements-agent-release.txt
- sqlserver/CHANGELOG.md
- sqlserver/changelog.d/16439.fixed
- sqlserver/changelog.d/16461.fixed
- sqlserver/datadog_checks/sqlserver/__about__.py
> port 7.50.2 releases to master

- nvidia_triton/assets/logs/nvidia_triton.yaml
- nvidia_triton/assets/logs/nvidia_triton_tests.yaml
- ray/assets/logs/ray.yaml
- ray/assets/logs/ray_tests.yaml
> Sync logs assets from logs-backend 2023_12_18

- ecs_fargate/README.md
Added details to configure process collection in ECS Fargate.
Added a section to the ECS Fargate Integration page to help customers configure process collection in ECS Fargate, and monitor their processes using the Live Processes product.
The Live Processes team recently launched process monitoring for ECS Fargate. We want to make sure customers setting up the ECS Integration know they can monitor their Fargate processes.
> Configuring process collection in ECS Fargate

- argocd/assets/monitors/application_sync_status.json
- avi_vantage/assets/monitors/error_rate_monitor.json
- boundary/assets/monitors/active_connections.json
- cloudera/assets/monitors/cloudera_high_cpu.json
- glusterfs/assets/monitors/brick_status.json
- helm/assets/monitors/monitor_failed_releases.json
- hudi/assets/monitors/commit_duration.json
- istio/assets/monitors/failed_sidecar_injection.json
- langchain/assets/monitors/error_rate.json
- langchain/assets/monitors/request_duration.json
- rabbitmq/assets/monitors/disk_usage_prometheus.json
- rabbitmq/assets/monitors/message_unack_prometheus.json
- redisdb/assets/monitors/high_mem.json
- scylla/assets/monitors/instance_down.json
- silk/assets/monitors/latency_high.json
- sonarqube/assets/monitors/vulnerabilities.json
- teamcity/assets/monitors/build_status.json
- torchserve/assets/monitors/error_ratio.json
- vault/assets/monitors/vault_S3_time_high.json
- vertica/assets/monitors/vertica_replication_safety.json
- voltdb/assets/monitors/cpu_load.json
- weaviate/assets/monitors/node_status.json
The title and the description of recommended monitors of the following integrations have been updated following the new guidelines:
- argocd
- avi_vantage
- boundary
- cloudera
- glusterfs
- helm
- hudi
- istio
- redisdb
- scylla
- silk
- sonarqube
- teamcity
- torchserve
- vault
- vertica
- voltdb
- weaviate 
- langchain
- rabbitmq
> Recommended Monitor Revamp - Update title and description of multiple integrations' monitors

- azure_iot_edge/assets/monitors/disk_usage.json
- azure_iot_edge/assets/monitors/edgehub_retries.json
- azure_iot_edge/assets/monitors/iothub_syncs.json
- azure_iot_edge/assets/monitors/memory_usage.json
The title and the description of the azure_iot_edge recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of azure_iot_edge monitors

- snowflake/assets/monitors/snowflake_failed_logins.json
The title and the description of the snowflake recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of snowflake monitors

- marklogic/assets/monitors/marklogic_high_load.json
- marklogic/assets/monitors/marklogic_long_requests.json
- marklogic/assets/monitors/marklogic_low_cache.json
The title and the description of the marklogic recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of marklogic monitors

- sqlserver/assets/monitors/sqlserver_ao_not_healthy.json
- sqlserver/assets/monitors/sqlserver_db_not_online.json
- sqlserver/assets/monitors/sqlserver_db_not_sync.json
- sqlserver/assets/monitors/sqlserver_high_number_failed_auto_param.json
- sqlserver/assets/monitors/sqlserver_high_processes_blocked.json
The title and the description of the sqlserver recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of sqlserver monitors

- mongo/assets/monitors/high_connections.json
The title and the description of the mongo recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of mongo monitors

- teradata/assets/monitors/high_disk_space.json
- teradata/assets/monitors/low_ready_threads.json
The title and the description of the Teradata recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of Teradata monitors

- mysql/assets/monitors/replica_running.json
- mysql/assets/monitors/select_query_rate.json
The title and the description of the Kubernetes recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of mysql monitors

- weblogic/assets/monitors/active_threads.json
- weblogic/assets/monitors/stuck_threads.json
The title and the description of the Weblogic recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of Weblogic monitors

- foundationdb/assets/monitors/conflicts.json
- foundationdb/assets/monitors/errors_logged.json
- foundationdb/assets/monitors/high_durability_lag.json
- foundationdb/assets/monitors/log_queue_spill.json
- foundationdb/assets/monitors/low_disk_space.json
- foundationdb/assets/monitors/read_latency_probe.json
- foundationdb/assets/monitors/rejections.json
- foundationdb/assets/monitors/transaction_commit_latency.json
- foundationdb/assets/monitors/transaction_start_latency.json
The title and the description of the Foundationdb recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of Foundationdb monitors

- arangodb/assets/monitors/high_server_kernel_mode.json
- arangodb/assets/monitors/high_server_user_mode.json
The title and the description of the Arangodb recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of Arangodb monitors

- temporal/assets/monitors/FrontendLatency.json
- temporal/assets/monitors/HistoryLatency.json
- temporal/assets/monitors/MatchingLatency.json
- temporal/assets/monitors/PersistenceLatency.json
The title and the description of the Temporal recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of Temporal monitors 

- calico/assets/monitors/dataplane_failures.json
- calico/assets/monitors/ipset_error.json
- calico/assets/monitors/iptables_restore_errors.json
- calico/assets/monitors/iptables_save_errors.json
The title and the description of the Calico recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of Calico monitors

- openai/assets/monitors/api_token_usage.json
- openai/assets/monitors/request_limits.json
- openai/assets/monitors/tokens_limits.json
The title and the description of the Openai recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of Openai monitors

- airbyte/assets/monitors/long_running_jobs.json
The title and the description of the Airbyte recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of Airbyte monitors

- kubernetes/assets/monitors/monitor_deployments_replicas.json
- kubernetes/assets/monitors/monitor_node_unavailable.json
- kubernetes/assets/monitors/monitor_pod_crashloopbackoff.json
- kubernetes/assets/monitors/monitor_pod_imagepullbackoff.json
- kubernetes/assets/monitors/monitor_pods_failed_state.json
- kubernetes/assets/monitors/monitor_pods_restarting.json
- kubernetes/assets/monitors/monitor_statefulset_replicas.json
The title and the description of the Kubernetes recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of Kubernets monitors

- nginx/assets/monitors/4xx.json
- nginx/assets/monitors/5xx.json
- nginx/assets/monitors/upstream_peer_fails.json
The title and the description of the nginx recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of nginx monitors

- tomcat/assets/monitors/error_count.json
- tomcat/assets/monitors/max_proc_time.json
- tomcat/assets/monitors/processing_time.json
- tomcat/assets/monitors/req_count.json
- tomcat/assets/monitors/thread_busy.json
- tomcat/assets/monitors/thread_count_max.json
The title and the description of the Tomcat recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of Tomcat monitors

- postgres/assets/monitors/percent_usage_connections.json
- postgres/assets/monitors/replication_delay.json
The title and the description of the Postgres recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of Postgres monitors

- elastic/assets/monitors/elastic_pending_tasks_high.json
- elastic/assets/monitors/elastic_query_latency_high.json
- elastic/assets/monitors/elastic_query_load_high.json
- elastic/assets/monitors/elastic_requests.json
The title and the description of the Elastic recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of Elastic monitors

- apache/assets/monitors/apache_low_idle_workers.json
- apache/assets/monitors/high_keep_alive_and_cpu.json
The title and the description of the apache recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of apache monitors

- dcgm/assets/monitors/gpu_temperature.json
- dcgm/assets/monitors/memory_usage.json
- dcgm/assets/monitors/xid_errors.json
The title and the description of the dcgm recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of dcgm monitors

- iis/assets/monitors/err.json
- iis/assets/monitors/lock.json
- iis/assets/monitors/req.json
The title and the description of the iis recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of iis monitors

- coredns/assets/monitors/coredns_cache_hits_low.json
- coredns/assets/monitors/coredns_request_duration_high.json
The title and the description of the coredns recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of coredns monitors

- activemq/assets/monitors/activemq_artemis_high_disk_store.json
- activemq/assets/monitors/activemq_artemis_unrouted_messages.json
The title and the description of the activemq recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of activemq monitors

- active_directory/assets/monitors/ldap_binding.json
- active_directory/assets/monitors/ldap_binding_successful.json
- active_directory/assets/monitors/ldap_client_sessions.json
The title and the description of the active_directory recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of active_directory monitors

- citrix_hypervisor/assets/monitors/host_cpu_high.json
- citrix_hypervisor/assets/monitors/vm_cpu_high.json
The title and the description of the citrix_hypervisor recommended monitors that are currently present in the Recommended Monitor library have been updated following the new guidelines.
> Recommended Monitor Revamp - Update title and description of citrix_hypervisor monitors

- snmp/assets/monitors/device_down.json
- snmp/assets/monitors/device_unreachable.json
- snmp/assets/monitors/interface_down.json
- snmp/assets/monitors/traps_linkDown.json
This reverts commit b76dfc5e622bf43cd3af7a648f0f728af296810c.
> Revert "Recommended Monitor Revamp - Update title and description of snmp monitors (#16258)"

- fluxcd/assets/configuration/spec.yaml
- fluxcd/datadog_checks/fluxcd/config_models/defaults.py
- fluxcd/datadog_checks/fluxcd/config_models/instance.py
- fluxcd/datadog_checks/fluxcd/config_models/shared.py
- fluxcd/datadog_checks/fluxcd/data/conf.yaml.example
- fluxcd/tests/test_unit.py
switch config from minimal template to OM template.
This is a standard OM integration, we might as well have the right config for it.
This builds on top of #16476, wait till that's merged to merge this.
> Correct config for OM integration

- mysql/README.md
Adds an extra note linking to the config file.
DOCS-6887
> (DOCS-6887) Add extra note to MySQL doc

- ddev/changelog.d/16555.fixed
- ddev/src/ddev/cli/dep.py
Allow bumping the version of `pymongo`
https://github.com/DataDog/integrations-core/pull/16554
> Allow bumping the version of `pymongo`

- ddev/changelog.d/16550.fixed
- ddev/src/ddev/cli/dep.py
Allow bumping the version `openstacksdk`
https://github.com/DataDog/integrations-core/pull/16549
> Allow bumping the version `openstacksdk`

- foundationdb/hatch.toml
- foundationdb/tests/common.py
- foundationdb/tests/conftest.py
- foundationdb/tests/test_foundationdb.py
Run the TLS tests
The env name was hardcoded, which contains the Python version. switching to a specific env variable instead.
> Run the TLS tests

- teradata/tests/common.py
- teradata/tests/test_e2e.py
Run the sandbox tests
The env name was hardcoded, which contains the Python version. switching to a specific env variable instead.
> Run the sandbox tests

- postgres/changelog.d/16608.fixed
- postgres/datadog_checks/postgres/metrics_cache.py
- postgres/datadog_checks/postgres/postgres.py
- teradata/changelog.d/16608.fixed
- teradata/datadog_checks/teradata/utils.py
Fix incompatibility issues with Python 3.9 and lower
https://github.com/DataDog/integrations-core/pull/16608
> [7.51.x] Fix incompatibility issues with Python 3.9 and lower

- postgres/CHANGELOG.md
- postgres/changelog.d/16608.fixed
- postgres/changelog.d/16612.fixed
- postgres/datadog_checks/postgres/__about__.py
- requirements-agent-release.txt
- teradata/CHANGELOG.md
- teradata/changelog.d/16608.fixed
- teradata/datadog_checks/teradata/__about__.py
master counterpart of https://github.com/DataDog/integrations-core/pull/16617
> [Release] Port postgres and teradata releases to master

- .gitlab-ci.yml
- .gitlab/validate-agent-build/trigger_agent_build.py
Fix the trigger-agent build script
https://github.com/DataDog/integrations-core/pull/16621
> Fix the trigger-agent build script

- tomcat/tests/common.py
- tomcat/tests/compose/docker-compose.yml
- tomcat/tests/conftest.py
Collect logs in the e2e environment
Improve the e2e env, we're refreshing the integration.
[datadoghq.atlassian.net/browse/AI-3731](https://datadoghq.atlassian.net/browse/AI-3731)
> Collect logs in the e2e environment

- harbor/tests/compose/harbor-1.10.0/docker-compose.yml
- harbor/tests/compose/harbor-2.0.5/docker-compose.yml
- harbor/tests/compose/harbor-2.3.2/docker-compose.yml
Remove unused volumes in the compose file
This folder is not in the repo, we do not populate it and is not shared with other containers. 
[It also sometimes fails on master](https://github.com/DataDog/integrations-core/actions/runs/7541219368/job/20527728720#step:13:1101)
> Remove unused volumes in the compose file

- karpenter/manifest.json
Add the `Log Collection` category to the manifest
- It's missing and we do collect logs 
- https://gitlab.ddbuild.io/DataDog/integrations-core/-/jobs/408145998
> Add the `Log Collection` category to the manifest

- openstack_controller/README.md
small change to remove the words "containerized" and "non-containerized", which confuses some people
> remove containerized vs non-containerized language

- fluxcd/tests/test_e2e.py
> Clarify that we only test v2 of flux and why.

- karpenter/assets/dashboards/karpenter_overview.json
Update dashboard for Karpenter
Staging:
https://dd.datad0g.com/dashboard/ewb-ypx-eb6/karpenter-overview?refresh_mode=sliding&view=spans&from_ts=1704824390444&to_ts=1705429190444&live=true
> updated dashboard

- docs/developer/guidelines/dashboards.md
> Dashboards Guidelines Edit

- snmp/assets/dashboards/bgp_ospf_overview.json
- snmp/manifest.json
https://datadoghq.atlassian.net/browse/NDMII-2440
Dashboard: https://dd.datad0g.com/dash/integration/32235/ndm-bgpospf-overview
> Add BGP/OSPF OOTB dashboard

- tomcat/assets/monitors/error_count.json
- tomcat/assets/monitors/max_proc_time.json
- tomcat/assets/monitors/req_count.json
Update some descriptions in monitors
https://datadoghq.atlassian.net/browse/AI-3734
> Update some descriptions in monitors

- .github/workflows/slapr.yml
- Tools squad is no more @alopezz 😢 
- Adding the review slack channel
> Update the slapr config

- tomcat/README.md
Remove the section about Agent 5
Agent 5.3.0 came out in 2015. Time to say goodbye.
> Remove the section about Agent 5

- tomcat/README.md
Add a blog post to the README file
This blog post is mentioned in the dashboard but not in the docs
https://datadoghq.atlassian.net/browse/AI-3739
> Add a blog post to the README file

- datadog_checks_dev/changelog.d/16676.added
- datadog_checks_dev/pyproject.toml
Beta releases/wheels might have no changes, but we still want to publish them.
> Bump towncrier version to support releasing with empty changelogs

- kafka_consumer/changelog.d/16677.fixed
- kafka_consumer/datadog_checks/kafka_consumer/client.py
- kafka_consumer/datadog_checks/kafka_consumer/config.py
Update the `log_level` in librkafka and redirect the logs. Make it configurable, but do not document it as I don't expect customers to tweak it.
Support case
> Update the `log_level` in librkafka and redirect the logs

- ddev/changelog.d/16686.fixed
- ddev/src/ddev/cli/dep.py
> Prevent `ddev dep` to bump `cryptography`

- ecs_fargate/README.md
> correct typo in ECS Fargate docs

- datadog_checks_dev/changelog.d/16693.added
- datadog_checks_dev/datadog_checks/dev/tooling/commands/create.py
- datadog_checks_dev/datadog_checks/dev/tooling/create.py
- datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/CHANGELOG.md
- datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/changelog.d/1.added
- datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/CHANGELOG.md
- datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/changelog.d/1.added
- datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/CHANGELOG.md
- datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/changelog.d/1.added
> Different changelog template depending on release process.

- openai/assets/dashboards/usage_overview_dashboard.json
- openai/manifest.json
- openai/metadata.csv
> Chris.laverdiere/openai remove deprecated metrics

- .github/workflows/build-deps.yml
https://github.com/DataDog/integrations-core/actions/runs/7670838326/job/20907878150
> Fix dependency builds on pushes

- .github/CODEOWNERS
> Fix CODEOWNERS for cisco umbrella DNS

- datadog_checks_dev/changelog.d/16726.fixed
- datadog_checks_dev/pyproject.toml
> Bump pytest-asyncio to be compatible with pytest 8

- fluxcd/tests/conftest.py
> Collect metrics from more controllers

- openai/README.md
Noticed some broken links on the node tab
> (DOCS) Fix broken links

- kafka_consumer/tests/python_client/script.py
Print the config options in the utility script that mimics what the integration does
We mostly use this script for support cases. It would be nice to print the config options that were used to execute the script to avoid asking the customer to double check the values.
> Print the config options in the utility script that mimics what the integration does

- nvidia_triton/assets/dashboards/nvidia_triton_overview.json
Update 3 queries in the dashboard to point to metrics that we emit.
The existing names must have come from an unreleased/sandbox version of the integration. They even have a different prefix.
> Update queries to reflect names of metrics we emit

- .gitlab-ci.yml
Migrate our runners to Kubernetes
Requested by Dom. 
Green job [here](https://gitlab.ddbuild.io/DataDog/integrations-core/-/pipelines/27539689)
> Migrate the GitLab jobs to Kubernetes

- README.md
> [INTPLAT-13] Generalize README.md file

- calico/README.md
> Update mistypo in calico doc

- .github/workflows/config/labeler.yml
> Add the `zeek` integration the labeler config

- cisco_umbrella_dns/manifest.json
> [INTPLAT-12] Update manifest.json

- fluxcd/README.md
- fluxcd/assets/monitors/error_count.json
Fix small trivial issues in FluxCD integration
> [QA] Fixes trivial issues in FluxCD integrations

- airflow/README.md
Removes a sentence in the Airflow Integration with an example for Kubernetes that was already removed.
Cleaner and updated documentation.
> Update Airflow README.md ; Remove sentence with the link to an integration that no longer exits

- .github/workflows/config/labeler.yml
> Add the `cisco_umbrella_dns` integration the labeler config

- .github/workflows/update-agent-changelog.yml
Update the tag pattern when updating the changelog
This is a glob, not a regex
> Update the tag pattern when updating the changelog

- ddev/changelog.d/16806.changed
- ddev/pyproject.toml
> Bump datadog_checks_dev dependency requirement

- ddev/CHANGELOG.md
- ddev/changelog.d/16774.added
- ddev/changelog.d/16806.changed
> [Release] Bumped ddev version to 8.0.0

- datadog_checks_base/changelog.d/16742.fixed
- datadog_checks_base/datadog_checks/base/utils/db/utils.py
- datadog_checks_base/tests/base/utils/db/test_util.py
- sqlserver/changelog.d/16742.fixed
- sqlserver/datadog_checks/sqlserver/activity.py
- sqlserver/datadog_checks/sqlserver/statements.py
- sqlserver/tests/compose-ha/sql/aoag_primary.sql
- sqlserver/tests/compose-high-cardinality-windows/setup.sql
- sqlserver/tests/compose-high-cardinality/setup.sql
- sqlserver/tests/compose-windows/setup.sql
- sqlserver/tests/compose/setup.sql
- sqlserver/tests/test_statements.py
> [DBMON-3495] Backport #16742

- ecs_fargate/README.md
> (Docs) Add blog post link to Fargate doc

- requirements-agent-release.txt
- sqlserver/CHANGELOG.md
- sqlserver/changelog.d/16742.fixed
- sqlserver/datadog_checks/sqlserver/__about__.py
The release already happened off the agent release branch, now we just need to sync master state.
> Apply changelog and version bump after releasing for agent v7.51.0

- openstack/README.md
- openstack_controller/README.md
> Add blog link to OpenStack doc

- fluxcd/assets/logs/fluxcd.yaml
- fluxcd/assets/logs/fluxcd_tests.yaml
- zeek/assets/logs/zeek.yaml
- zeek/assets/logs/zeek_tests.yaml
Syncing integrations with logs-backend (this is a no-op change for now as we're not reading these integrations from APW in prod)
> Sync integrations with logs-backend

- ibm_mq/README.md
- Fix a broken link
- Give an example for clarity.
> fix broken link and further details
