DataDog/integrations-core

datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py
This reverts commit https://github.com/DataDog/integrations-core/pull/14804.
Some integrations only have e2e tests 😢 which makes the CI fail because there's no tests to run. We missed that in the original PR because not all the integration tests ran. Example: https://github.com/DataDog/integrations-core/actions/runs/5330550724/jobs/9657370490
For ActiveMQ: 
```
============================= test session starts ==============================
platform linux -- Python 3.9.17, pytest-7.3.2, pluggy-1.0.0 -- /home/runner/.local/share/hatch/env/virtual/datadog-activemq/C9F59Roh/py3.9-2.15.0-artemis.yaml/bin/python
cachedir: .pytest_cache
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False …
```
=> Revert "Set the `marker` option to `not e2e` by default (#14804)"

snmp/datadog_checks/snmp/data/default_profiles/hp-ilo.yaml, snmp/tests/test_e2e_core_profiles/test_profile_hp_ilo.py
Refactor hp-ilo profile vendor to use `metadata` section instead of older `device.vendor`.
It's safe to remove `device.vendor` (that also removes `snmp_vendor` tag) since the profile is new and not released in a new agent version yet: https://github.com/DataDog/integrations-core/pull/14771
=> Refactor hp-ilo profile vendor

snmp/tests/fixtures/user_profiles/apc_ups_user.yaml, snmp/tests/test_e2e_core.py, snmp/tests/test_e2e_core_vs_python.py
Add test_e2e_profile_apc_ups_user
Make sure that python integration also partially support user profiles.
Python user profiles support is implemented here: https://github.com/DataDog/integrations-core/pull/14752
=> Add python vs core test for user profiles feature

datadog_operator/assets/dashboards/operator_overview.json, kubernetes/assets/dashboards/kubernetes_clusters.json, kubernetes/assets/dashboards/kubernetes_dashboard.json
Updates remaining references to the Kubernetes Pods dashboard to use generic link
A follow-up to https://github.com/DataDog/integrations-core/pull/14822, there were a couple of other references to the old, us1 specific dashboard.
=> Update remaining links to pods dashboard from kubernetes dashboards

datadog_checks_dev/datadog_checks/dev/tooling/constants.py
Modified order of changelogs so that in future releases, when `CHANGELOG.md` is updated the changelog types will be categorized by their importance
=> Reorder changelogs by priority

datadog_checks_dev/pyproject.toml
Remove ddev script from `datadog_checks_dev`. The new CLI package provides that and therefore this is a duplicate that can potentially cause conflicts
=> Remove ddev script from datadog_checks_dev

datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py
Switch from a python boolean to a string integer to enable DD_TELEMETRY_ENABLED
Python `True` is not always well handled in env variables
=> Switch from a python boolean to a string integer to enable DD_TELEMETRY_ENABLED

.gitlab-ci.yml
We need to update the `tagger-image-builder` script to swap out `datadog-checks-dev` with `ddev`.
https://github.com/DataDog/integrations-core/pull/14844
=> Replace datadog-checks-dev with ddev in tagger-image-builder

elastic/README.md, elastic/assets/configuration/spec.yaml, elastic/datadog_checks/elastic/data/conf.yaml.example, elastic/datadog_checks/elastic/elastic.py, elastic/tests/test_integration.py, elastic/tests/test_unit.py
Elastic custom metric integration allows specifying a value path traversing a nested dictionary. Allow specifying a path that can also include list indices to traverse a path of nested dictionaries and lists.
Ex. value_path -> `a.0.b` of dictionary `{"a": [{"b": "c"}]}` should return `"c"`.
Desire for multiple tags pulled per aggregation bucket. This is able to be achieved with [Elasticsearch Multi Term Aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-multi-terms-aggregation.html) but the original implementation did not allow for specifying the key path as a list index.
=> Add support for list value paths in Elastic custom metrics.

kubelet/metadata.csv
Updates the description for a metric `kubernetes.kubelet.runtime.errors` to specify that it is cumulative
Found by @marielle-spiteri
=> DOCS-4656 - Update kubelet metric to note it is cumulative

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py
Add Synthetics test run step unit to metadata check
Synthetics now emits some metrics that are related to the number of steps executed during a Synthetics test.
=> Add step unit to metadata check

elastic/datadog_checks/elastic/elastic.py, elastic/tests/test_unit.py
Do not stop collecting metrics if the templates endpoint is not reachable. This was introduced in https://github.com/DataDog/integrations-core/pull/14569
In some cases we can get a 403 on this endpoint. The check should continue collecting the other metrics.
This will be backported to 7.46
=> Do not stop collecting metrics if the templates endpoint is not reachable

datadog_checks_base/datadog_checks/base/utils/http.py, datadog_checks_base/tests/base/utils/http/test_tls_and_certs.py
This PR adds the feature for non-443 ports to be used when getting intermediate certs.
https://github.com/DataDog/integrations-core/issues/14734
Currently [looking into setting up E2E testing](https://github.com/chromium/badssl.com/commit/3fdc123eccaeaf0a5e30827bdd5d7804a3f11408) for this and other intermediate cert features, since badssl.com no longer has valid certs, so [we are skipping some tests](https://github.com/DataDog/integrations-core/blob/2546231d9b6c4367745ed8adbd9012137469a6c9/datadog_checks_base/tests/base/utils/http/test_tls_and_certs.py#L188).
=> Allow non-443 port to be used in intermediate certs

sqlserver/datadog_checks/sqlserver/statements.py
Currently, because of `select *` procedure text gets sent twice for each row in query metrics. We are removing this redundancy.
Some customer have been experiencing timeouts when collecting query metrics. The query was waiting on "Network":
The biggest contributor to the network traffic is the procedure text. It's worth noting that not only do we send the query text, but we also send the complete source code of the procedure which is executing the query. If we have a large procedure executing many queries, we will select the procedure source code many times. This PR halves the network traffic.
https://datadoghq.atlassian.net/browse/DBM-2535
=> SQL Server query metrics: avoid sending procedure text twice

sqlserver/tests/test_statements.py
Always look back 60s further than the parameter had intended to ensure we account for test pauses which may cause this interval to not be wide enough.
=> fix sqlserver test_statement_basic_metrics_query test

sqlserver/datadog_checks/sqlserver/statements.py
We're already able to link to the procedure via procedure_name and procedure_signature so we don't need the text in metrics payloads.
Reduce the size of metrics payloads.
=> sqlserver: remove unused `procedure_text` from metrics payloads

sqlserver/hatch.toml
Only skip E2E tests on windows when running in CI. This enables us to continue to run sqlserver environments manually on a windows dev host.
=> sqlserver enable running on windows

datadog_checks_base/tests/base/utils/http/test_tls_and_certs.py
Python 2 tests were disabled temporarily when this was merged https://github.com/DataDog/integrations-core/pull/14817
=> Fix tests on Python 2

.codecov.yml
Lower snmp coverage to 50
Codecov doesn't take into account tests run via ddev env test and snmp integration have a lot of them.
[this codecov report for snmp integration](https://app.codecov.io/gh/DataDog/integrations-core/pull/15102/blob/snmp/tests/test_e2e_core_profiles/test_profile_brother_net_printer.py) e2e test file, and it says the file is mostly not reached.
Hence we are seeing codecov check fail due to coverage (without e2e tests) below 75.
=> Lower snmp coverage to 50

.ddev/ci/scripts/kafka_consumer/linux/32_install_kerberos.sh, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, kafka_consumer/hatch.toml, kafka_consumer/pyproject.toml, kafka_consumer/tests/README.md
Bump the confluent-kafka version. Also update the CI to be able to run the tests using this version.
We wanted to bump it in [this PR](https://github.com/DataDog/integrations-core/pull/14594) be we ran into some issues so we decided to leave this for later. 
Tested with the agent image generated by omnibus:
```
❯ ddev env start -a 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent/agent:v16364585-4a91d5b1-7-arm64 kafka_consumer py3.8-3.3-kerberos
Setting up environment `py3.8-3.3-kerberos`... success!
Updating `486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent/agent:v16364585-4a91d5b1-7-arm64`... success!
Detecting the major version... Agent 7 detected
Writing configuration for `py3.8-3.3-kerberos`... success!
Starting the Agent... success!
To edit config file, do: …
```
=> Bump the confluent-kafka version

helm/README.md
* Adds a tab with instructions to enable the Helm check using the Datadog Operator
* Support request on how to use the Helm check with the Operator
* ~~Currently, this requires a "lengthy" setup, it might be appropriate to add it in `features` of the Operator, e.g. `features.helmCheck.enabled` to mimic the Helm ease of installation and add the RBAC automatically. Checking with #container-ecosystems. Will remove `do-not-merge`~~
* For now, this is a FR tracked in https://datadoghq.atlassian.net/browse/CONTECO-489, so moving forward with the doc PR
=> [Helm check] Operator instructions

torchserve/hatch.toml
Bump torchserve version in tests
[A new version is out](https://github.com/pytorch/serve/releases/tag/v0.8.1) that improves some tests and significantly reduces the docker image size: 
```
pytorch/torchserve   0.8.1-cpu   68a3fcae81af   4 hours ago     662MB
pytorch/torchserve   0.8.0-cpu   958ef6dacea2   4 weeks ago     2.37GB
```
This will speed up the tests a bit:
- Master: unit/integration-> 2m 3s, e2e -> 1m 21s
- This branch: unit/integration-> 1m 24s, e2e -> 1m 22s (the image was already downloaded during unit/integration tests so no change)
=> Bump torchserve version in tests

kubernetes/assets/monitors/monitor_pod_crashloopbackoff.json
Updates the CrashloopBackOff recommended monitor by adding the default_zero() function
A change that has been recommended by the Monitors team, see more information in this escalation: https://datadoghq.atlassian.net/browse/CONS-5639?focusedCommentId=1129240
=> Updating query for the CrashloopBackOff recommended monitor

kubernetes/assets/dashboards/kubernetes_clusters.json, kubernetes_state_core/metadata.csv
kubernetes_state.crd.count has been supported recently. See: https://github.com/DataDog/datadog-agent/pull/16141
and https://github.com/DataDog/helm-charts/pull/1040
This pr will update the document for this metric and update OOTB dashboard
Update OOTB dashboard and document to expose this metric to clients
=> Add crd.count to kubernetes_state core metrics

ddev/src/ddev/cli/application.py, ddev/src/ddev/cli/terminal.py, ddev/src/ddev/config/constants.py
- Adds VerbosityLevels class for ddev/terminal use
Verbosity levels were checked as numeric values in cli/terminal setup, converting this to an enum with meaningful name will help future developers on the intent behind the relevant initialization and comparisons
=> Add VerbosityLevels class for ddev cli/terminal use

ddev/pyproject.toml
A release will happen after this since there will be a very short period where no package provides our Hatch plugin
=> Bump the minimum supported version of datadog-checks-dev

kafka_consumer/hatch.toml
We are currently running test environments for Kafka 1.1 (released March 28, 2018) and 2.3 (released Jun 25, 2019). The `kafka_consumer` check uses the `confluent-kafka-python` library call `list_consumer_group_offsets` which [doesn't work as expected for Kafka 2.3 and below](https://github.com/confluentinc/confluent-kafka-python/issues/1600). Since Confluent itself [no longer supports Kafka versions older than 2.5](https://docs.confluent.io/platform/current/installation/versions-interoperability.html), I think it makes sense to drop them in our test environment.
This PR also cleans up a few additional things that were unnecessary in the `hatch.toml` file and re-enables e2e tests for non-v3.3 environment. They were [originally disabled since e2e tests were timing …
=> Drop testing for kafka 2.5 and below

sqlserver/assets/configuration/spec.yaml, sqlserver/datadog_checks/sqlserver/config_models/instance.py, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example, sqlserver/datadog_checks/sqlserver/statements.py, sqlserver/tests/test_statements.py
This PR adds a config option for query-metrics that allows the user to specify an amount of `max-queries` to send to the backend. 
https://datadoghq.atlassian.net/browse/DBM-2563
=> Add a limit on the number of queries in the query metrics payload at the Agent

datadog_checks_dev/hatch.toml, datadog_checks_dev/pyproject.toml, ddev/hatch.toml
Exclude click 8.1.4 to solve mypy issues
https://github.com/pallets/click/issues/2558
=> Exclude click 8.1.4 to solve mypy issues

kafka_consumer/datadog_checks/kafka_consumer/client.py
Do not check consumer_groups if the offset is invalid
- QA for https://github.com/DataDog/integrations-core/pull/15106
- We don't need to test the regex if the offset is not valid
- This will improve performance for this check in some cases with a very large regex and a high number of groups
- This is a refactor, existing tests are enough to validate everything is still working
=> Do not check consumer_groups if the offset is invalid

active_directory/pyproject.toml, aspdotnet/pyproject.toml, avi_vantage/pyproject.toml, dotnetclr/pyproject.toml, exchange_server/pyproject.toml, ibm_ace/pyproject.toml, iis/pyproject.toml, impala/pyproject.toml, teradata/pyproject.toml, win32_event_log/pyproject.toml, windows_performance_counters/pyproject.toml, yarn/pyproject.toml
Bump the minimum datadog-checks-base version
- [Bumping pydantic](https://github.com/DataDog/integrations-core/pull/14594) broke our minimum version CI check for these integrations https://github.com/DataDog/integrations-core/actions/runs/5504262506/jobs/10030322834
=> Bump the minimum datadog-checks-base version

ddev/src/ddev/utils/scripts/ci_matrix.py
Add `snmp/data/default_profiles` to matrix TESTABLE_FILE_PATTERN
SNMP tests need be run on CI again when files in `snmp/data/default_profiles` changes.
=> Add `snmp/data/default_profiles` to matrix TESTABLE_FILE_PATTERN

aspdotnet/tests/test_aspdotnet.py
Run the legacy tests on py3 too
- These tests are not running on py3, which is too bad because they are literally there and working. 
- Improve test coverage on master too because we do not run py2 tests on master, only on the nightly build
- We don't remember why this was not enabled on py3
- Adding the option is needed because we automatically switch to the new implementation when running on py3, unless this option is provided
=> Run the legacy tests on py3 too

snmp/datadog_checks/snmp/data/default_profiles/_generic-host-resources-base.yaml, snmp/tests/test_e2e_core_profiles/utils.py, snmp/tests/test_profiles.py
Add `hr_device_index` tag to `snmp.hrProcessorLoad` metric
`snmp.hrProcessorLoad` is currently only tagged with `processorid`:
```
- tag: processorid
column:
OID: 1.3.6.1.2.1.25.3.3.1.1
name: hrProcessorFrwID
```
But based on real device `snmpwalk`(s), the value of  1.3.6.1.2.1.25.3.3.1.1/hrProcessorFrwID is often `0.0` for all rows, which make it unsuitable as unique tag for this table.
```
1.3.6.1.2.1.25.3.3.1.1.768|6|0.0
1.3.6.1.2.1.25.3.3.1.1.769|6|0.0
1.3.6.1.2.1.25.3.3.1.1.770|6|0.0
1.3.6.1.2.1.25.3.3.1.1.771|6|0.0
```
```
1.3.6.1.2.1.25.3.3.1.1.196608|6|0.0
1.3.6.1.2.1.25.3.3.1.1.196609|6|0.0
1.3.6.1.2.1.25.3.3.1.1.196610|6|0.0
1.3.6.1.2.1.25.3.3.1.1.196611|6|0.0
1.3.6.1.2.1.25.3.3.1.1.196612|6|0.0
1.3.6.1.2.1.25.3.3.1.1.196613|6|0.0
```
=> Add `hr_device_index` tag to `snmp.hrProcessorLoad` metric

kafka_consumer/datadog_checks/kafka_consumer/config.py
Simplify regex compilation to avoid using `rstrip`
- The regex is continuously build and the extra `|` get stripped at the very end in another function.  This pr uses `"|".join` instead to avoid that 
- QA for https://github.com/DataDog/integrations-core/pull/15106
- This is a refactor, existing tests are enough to validate everything is still working
=> Simplify regex compilation

datadog_checks_dev/tests/test_docker.py, datadog_checks_dev/tests/test_kind.py
Speed up the kind and docker tests mocking the KindRun/KindDown classes and up/down functions because we do not need to spin up a real environment, we just want to make sure our retry mechanism on conditions work. 
Also lowers the `attempts_wait` parameter.
Working on a unrelated issue I noticed the tests were taking forever on that part.
Running the command `ddev test datadog_checks_dev -k test_retry_` locally:
| Before | After |
|--------|--------|
| `10 passed, 414 deselected in 163.05s (0:02:43)` | `10 passed, 414 deselected in 0.83s` |
For only one environment.
CI is failing because of an unrelated issue I was trying to fix on master
=> Speed up the kind and docker tests

strimzi/tests/test_e2e.py, strimzi/tests/test_unit.py
- Assert service check count in e2e test
- Add unit test for parse config
Equivalent assertions done in unit and integration tests. Observed during QA week
None
=> [AI-3144] Enhance unit and e2e test

snowflake/datadog_checks/snowflake/check.py, snowflake/tests/snowflake_connector_patch/_snowflake_connector_patch/connector.py, snowflake/tests/test_snowflake.py
Changes `fetchall()` with iterating on the cursor, which is equivalent to fetching the results one by one.
A support case reported running into increased memory usages when the queries return a large number of row. The snowflake [docs](https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-example#using-cursor-to-fetch-values) indicate that this is the way to go when `fetchall()` results in memory usage issues.
- As far as I know, this should not result in any performance regression, as under the hood `fetchall()` [is using `fetchone()` in a loop](https://github.com/snowflakedb/snowflake-connector-python/blob/7ac23578fa906cf9e969a6fff2ed4a202a7b69b0/src/snowflake/connector/cursor.py#L1296-L1304).
- [Reference](https://github.com/snowflakedb/snowflake-connector-pyth …
=> Process query rows one at a time to reduce memory footprint

openai/assets/dashboards/overview_dashboard.json
Modifies the OpenAI Overview dashboard to include prompt completion logging for the extra endpoints supported by the OpenAI V2 integration ([ref](https://github.com/DataDog/dd-trace-py/pull/5857)).
Also modifies the template variable `$model` to use the tag name `openai.request.model` instead of `openai.model` as per the V2 integration's tag name change.
The OpenAI V2 integration added tracing support for additional OpenAI endpoints, which means we should add prompt-completion log sampling for the audio/images/edits endpoints. Additionally, the V2 integration changed the tag name for the OpenAI model from `openai.model` to `openai.request.model`, which means the template variables, graphs, and metrics querying for model names should change correspondingly.
=> Modify OpenAI Dashboard to display new endpoints

kubernetes/CHANGELOG.md
While validating the formatting of changelogs I realized that I missed one spacing case, where I didn't check if there was an empty line between the version/date header and bullet points. This PR fixes the case that I missed
=> Changelog spacing fix

datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/scraper.py, datadog_checks_base/tests/base/checks/openmetrics/test_v2/test_config.py, openmetrics/tests/test_openmetrics.py
It reverts the default accept header to request `text/plain` (i.e. prometheus format) that was introduced by #14445.
It looks like the library support for OpenMetrics format generation and parsing is somewhat immature (e.g. https://github.com/prometheus/client_golang/issues/829) which made setting the accept header to request the OpenMetrics format if available more disturbing than we anticipated.
=> Revert to requesting Prometheus format by default

gitlab/metadata.csv
Removes a metric that is no longer collected by any officially documented method from the metadata.csv.
Partly due to #15085, which intends to use the term "legacy" for referring to OMv1, resulting in an overload for the term, and generally being impossible to tell from a user's perspective what `[Legacy]` indicates here. Since new users are not going to encounter this metric, it looks safe to delete it and removes noise.
=> Remove legacy metric from metadata.csv

weaviate/README.md
Weaviate Docs that didn't make it into the integration release.
For the docs team, can you review the metadata.csv for the metric description and the conf.yaml.example as well? It's mostly from templates the only unique parameter would be the `weaviate_api_endpoint` parameter that is new.
=> Weaviate Docs

.gitlab/tagger/Dockerfile
Bump awscli in the tagger image
See https://github.com/DataDog/datadog-agent/pull/18216 for full background. 
awscli already has a new version so we just bump it. Error in our CI: 
```
Collecting PyYAML<5.5,>=3.10 (from awscli==1.27.159)
Downloading PyYAML-5.4.1.tar.gz (175 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 341.9 MB/s eta 0:00:00
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [62 lines of output]
/tmp/pip-build-env-e5y3oqf4/overlay/local/lib/python3.10/dist-packages/setuptools/config/setupcf …
```
=> Bump awscli in the tagger image

LICENSE-3rdparty.csv, datadog_checks_base/datadog_checks/base/data/agent_requirements.in
Bump pydantic version in the agent_requirements.in file
- We forgot to add it here https://github.com/DataDog/integrations-core/pull/15212, CI is failing on main: 
```
Run ddev validate dep $TARGET
ddev validate dep $TARGET
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
PYTHON_VERSION: 3.9
TARGET: 
pythonLocation: /opt/hostedtoolcache/Python/3.9.17/x64
PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.17/x64/lib/pkgconfig
Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.17/x64
Python[2](https://github.com/DataDog/integrations-core/actions/runs/5604095001/jobs/10251613574#step:12:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/DataDog/integrations-core/actions/runs/5604095001/jobs/10251613574#step:12:3).9.17/x6[4](https://github.com/DataDog/integrations-core/ …
```
=> Bump pydantic version in the agent_requirements.in file

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/changelog.py
Changed changelog generation so that the new version and changelog entries are added below the 'Unreleased' section of the changelog
In preparation for enforcing manual changelog entries in integrations, the 'Unreleased' section of the changelog should always stay at the top of the file. 
example (with blank Unreleased section): 
example (with content in Unreleased section):
=> Add new release notes below the Unreleased section of changelogs

confluent_platform/assets/service_checks.json
Document the `WARNING` status for `confluent.can_connect`
Support case [AGENT-9930](https://datadoghq.atlassian.net/browse/AGENT-9930)
Next steps:
- Update the generic JMX docs to include this.
- Review all the other integrations to add this status as well
[AGENT-9930]: https://datadoghq.atlassian.net/browse/AGENT-9930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Document the `WARNING` status for `confluent.can_connect`

datadog_checks_dev/datadog_checks/dev/tooling/commands/create.py
An unsupported field was added with the create scaffolding. This PR is to remove that field because it causes validations to fail.
=> Remove `legal_email` field from Ecosystem template

LICENSE-3rdparty.csv, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/pyproject.toml, ddev/src/ddev/plugin/external/hatch/environment_collector.py
Pydantic now builds successfully
=> Upgrade pydantic

activemq/assets/service_checks.json, cassandra/assets/service_checks.json, hazelcast/assets/service_checks.json, hive/assets/service_checks.json, hivemq/assets/service_checks.json, hudi/assets/service_checks.json, ignite/assets/service_checks.json, jboss_wildfly/assets/service_checks.json, kafka/assets/service_checks.json, presto/assets/service_checks.json, solr/assets/service_checks.json, sonarqube/assets/service_checks.json, tomcat/assets/service_checks.json, weblogic/assets/service_checks.json
Document the WARNING status for the *.can_connect service checks in JMX integrations
See https://github.com/DataDog/integrations-core/pull/15351
=> Document the `WARNING` status for the `*.can_connect` service checks in JMX integrations

mysql/README.md, oracle/README.md, supervisord/README.md
Updates the README with `username`/`password` instead of the deprecated `user`/`pass`
https://github.com/DataDog/integrations-core/pull/9340
=> Doc update based on #9340

kafka_consumer/datadog_checks/kafka_consumer/client.py, kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
- Highwater offsets were collected in a loop with one call made to the broker for every topic partition. This was causing a large number of calls (tens of thousands as per the debug flare from AGENT-9940) to the broker and the highwater offset collection was taking more than 2min
- This change introduces the ability to query the highwater offsets of all topic partitions within a kafka cluster in a single call
- Also multiple early exits have been configured while fetching highwater offsets as performance optimization
- Improved debug logs
[AGENT-9940](https://datadoghq.atlassian.net/browse/AGENT-9940)
[AGENT-9940]: https://datadoghq.atlassian.net/browse/AGENT-9940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [AGENT-9940] Optimize highwater offset collection

torchserve/assets/dashboards/overview.json
Small nit as requested from PMs
Updates to order of widget groups. The dashboard is identical to the old one, but has widget groups rearranged to fit the desired order for better visibility when viewing in laptop mode
=> Small edits for torchserve dashboard

elastic/datadog_checks/elastic/elastic.py
Lower logging level if there's an error scraping the template endpoint to DEBUG
- Support case
- This endpoint does not exist in older versions of elastic search that are still supported. In that case we just spams the log file with this error
=> Lower logging level if there's an error scraping the template endpoint to DEBUG

argocd/assets/service_checks.json
Changes the service check to the generic openmetrics health check and also set it to the correct agent version.
=> Fix service check with correct name and version

vertica/datadog_checks/vertica/vertica.py, vertica/tests/conftest.py, vertica/tests/test_vertica.py
Close and recreate a connection instead of using the `reset_connection` method
Support case
- When the check runs for the first time, we initiate a new connection using `vertica.connect` which works fine for the current check run.
- If the connection is closed or the `connection_load_balance` option is used (which was the case in our support case), we reset the connection using the `reset_connection` method (code [here](https://github.com/vertica/vertica-python/blob/master/vertica_python/vertica/connection.py#L636-L638)).
- This method does not work as expected because the next check runs are all failing with the following timeout error: 
```
E   Exception: Message: timed out
E     File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/vertica_ …
```
=> Close and recreate a connection instead of using the `reset_connection` method

kubernetes/assets/monitors/monitor_node_unavailable.json, kubernetes/assets/monitors/monitor_pod_imagepullbackoff.json, kubernetes/assets/monitors/monitor_pods_failed_state.json
This PR updates the following Kubernetes recommended monitors to add the default_zero() function:
[kubernetes] Monitor Kubernetes Failed Pods in Namespaces (monitor_pods_failed_state.json)
[kubernetes] Pod {{pod_name.name}} is ImagePullBackOff on namespace {{kube_namespace.name}} (monitor_pod_imagepullbackoff.json)
[kubernetes] Monitor Unschedulable Kubernetes Nodes (monitor_node_unavailable.json)
This has been asked by the Monitors team, you can find more details in this escalation card: https://datadoghq.atlassian.net/browse/CONS-5669
=> Updating Kubernetes recommended monitors to add default_zero() function

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/pyproject.toml, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/pyproject.toml, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/pyproject.toml
Bump the min base check version in the templates to 32.6.0
Follow-up PR https://github.com/DataDog/integrations-core/pull/15427
=> Bump the min base check version in the templates to 32.6.0

calico/tests/common.py
Mark the calico.felix.ipset.errors.count as optional in the e2e tests
- Follow-up PR: https://github.com/DataDog/integrations-core/pull/15440
- https://github.com/DataDog/integrations-core/actions/runs/5728498990/job/15523284954
=> Mark  the `calico.felix.ipset.errors.count` as optional in the e2e tests

kafka_consumer/hatch.toml
"Pin" the 3.3.2 docker image
Even if our version is pinned already, Bitnami overrides the tag to push security/os fixes to their image. They also provide a tag that they do not override. Two days ago they pushed something that makes our ssl tests fail (see [this example](https://github.com/DataDog/integrations-core/actions/runs/5736291708/job/15545679445)). I pinned the docker image to the previous one.
We already had this kind of issues with the kafka images that are overriden: https://github.com/DataDog/integrations-core/pull/14481, not sure I'll "unpin" it this time
=> Pin the 3.3.2 docker image

snmp/tests/test_e2e_core_profiles/test_profile__generic_entity_sensor.py, snmp/tests/test_e2e_core_profiles/test_profile_extreme_switching.py, snmp/tests/test_e2e_core_profiles/test_profile_nvidia_cumulus_linux_switch.py, snmp/tests/test_e2e_core_profiles/test_profile_nvidia_mellanox_switchx.py, snmp/tests/test_e2e_core_profiles/utils.py
Rename to assert_extend_generic_entity_sensor to match profile name
`assert_extend_*` should match the profile name `_generic-entity-sensor.yaml`
=> Rename to assert_extend_generic_entity_sensor to match profile name

airbyte/manifest.json
Add 2 more metrics to check for when deciding to autoenable the integration tile.
Airbyte may not submit the metric we initially added, but it will definitely submit at least one of the 3 metrics we will have after this PR is merged.
=> Add more metrics that we check to autoenable integration tile.

snmp/datadog_checks/snmp/data/default_profiles/_generic-bgp4.yaml, snmp/tests/test_e2e_core.py, snmp/tests/test_profiles.py
The remote AS identifier is a number but that is not expected to change for a given device and bgp peer. Submitting this only as a gauge makes it complicated to use it in queries so let's add it as a tag as well.
=> [NDM] Add bgpPeerRemoteAs as tag

network/README.md
Update documentation of Network integration for Kubernetes and AWS ENA metrics collection.
I had to configure AWS ENA metrics collection with Datadog agent installed on Kubernetes via Helm charts and found the doc hard to follow:
- Some important step was missing: it requires `collect_aws_ena_metrics: true` in network check config but it is not mentionned
- Current doc recommends to use a Patch because Helm charts does not support update of securityContext, but it does with `agent.containers.agent.securityContext` (maybe it's a recent change). I found this config after quite a lot of trial and error, at first I also thought it wasn't possible, so the previous MR updating this doc is not really to blame. 
- Even if used, the documented patch is not sufficient. It will just add `NET_ADMIN` …
=> doc: improve network integration AWS ENA metrics instructions

calico/tests/common.py
Mark the `calico.felix.iptables.restore_calls.count` metric optional in the e2e tests
https://github.com/DataDog/integrations-core/actions/runs/5758934015/job/15612228195
=> Mark the `calico.felix.iptables.restore_calls.count` metric optional in the e2e tests

postgres/datadog_checks/postgres/statements.py, postgres/tests/test_statements.py
This fixes a bug introduced in https://github.com/DataDog/integrations-core/pull/15411 where we were erroneously checking the `sqlstate` field in order to properly format our error messages, when the `Diagnostic` [object](https://www.psycopg.org/psycopg3/docs/api/errors.html#db-api-exceptions) contains the message that was relevant.  
To test, just run a simple script 
```python
import psycopg
try:
conn = psycopg.connect(host="localhost", dbname="datadog_test", user="bob", password="bob")
cursor = conn.cursor()
cursor.execute("SELECT * FROM fake")
except psycopg.Error as e:
print(e.diag.message_primary)
```
-> which produces `relation "fake" does not exist`, which would then be caught [here](https://github.com/DataDog/integrations-core/blob/master/postgres/datadog_checks/postgres/statement …
=> Fix error handling for psycopg3 err messages

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, postgres/datadog_checks/postgres/connections.py, postgres/datadog_checks/postgres/postgres.py, postgres/pyproject.toml, postgres/tests/test_connections.py, postgres/tests/test_statements.py, postgres/tests/utils.py
Updates `psycopg3` to the [latest released version](https://www.psycopg.org/psycopg3/docs/news.html#psycopg-3-1-10), which contains nice fixes like this one:
> Fix [connect()](https://www.psycopg.org/psycopg3/docs/api/module.html#psycopg.connect) to avoid “leaking” an open [PGconn](https://www.psycopg.org/psycopg3/docs/api/pq.html#psycopg.pq.PGconn) attached to the [OperationalError](https://www.psycopg.org/psycopg3/docs/api/errors.html#psycopg.OperationalError) in case of connection failure. [Error.pgconn](https://www.psycopg.org/psycopg3/docs/api/errors.html#psycopg.Error.pgconn) is now a shallow copy of the real libpq connection, and the latter is closed before the exception propagates (ticket [#565](https://github.com/psycopg/psycopg/issues/565)).
Also, adds a `timeout` parameter on …
=> Bump psycopg3 version && add timeouts on blocking functions

ddev/src/ddev/cli/validate/licenses.py, ddev/src/ddev/cli/validate/licenses_utils.py, ddev/tests/cli/validate/test_licenses.py
Migrates `ddev validate licenses` command from datadog_checks_dev to ddev.
I did not test parts of the code (ex: checking for the correct format of the 3rd party extra license csv files) because of an issue (https://github.com/kevin1024/vcrpy/issues/716) with multithreading HTTPX requests.
=> Migrate `ddev validate licenses` command to ddev

.codecov.yml, ddev/hatch.toml, ddev/src/ddev/cli/validate/ci.py, ddev/tests/cli/validate/test_ci.py, ddev/tests/cli/validate/test_metrics.py
=> Migrate `validate ci` to ddev

postgres/datadog_checks/postgres/metadata.py, sqlserver/assets/configuration/spec.yaml, sqlserver/datadog_checks/sqlserver/config_models/instance.py, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example, sqlserver/datadog_checks/sqlserver/metadata.py, sqlserver/datadog_checks/sqlserver/sqlserver.py, sqlserver/tests/test_high_cardinality.py, sqlserver/tests/test_metadata.py
This PR follows on https://github.com/DataDog/integrations-core/pull/14577, and allows us to ingest sqlserver instance configuration from the [configurations](https://learn.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-configurations-transact-sql?view=sql-server-ver16) view.
A good write up of what these configurations are can be [found here](https://www.red-gate.com/simple-talk/databases/sql-server/database-administration-sql-server/how-to-document-and-configure-sql-server-instance-settings/)
=> Add support to ingest sys.configurations for SQL Server instances

.codecov.yml, ddev/src/ddev/cli/validate/ci.py, ddev/tests/cli/validate/test_ci.py
Uncommented a test case from migration of `ddev validate ci` from `datadog_checks_dev` to `ddev`. It was previously failing because I changed some project names in `.codecov.yml`
=> Update `ddev validate ci` testing

mysql/assets/configuration/spec.yaml, mysql/datadog_checks/mysql/config.py, mysql/datadog_checks/mysql/config_models/instance.py, mysql/datadog_checks/mysql/data/conf.yaml.example, mysql/datadog_checks/mysql/metadata.py, mysql/datadog_checks/mysql/mysql.py, mysql/tests/test_metadata.py
Follow on PR to https://github.com/DataDog/integrations-core/pull/15496
Adds support to ingest mysql [global settings](https://dev.mysql.com/doc/refman/8.0/en/performance-schema-system-variable-tables.html), and forward them to the DBM backend
=> Add support for ingesting mysql config settings

mongo/datadog_checks/mongo/mongo.py, mongo/tests/test_diagnose.py
Implements a diagnostic to help users detect if the certificates they specify in their config exist and are readable.
Proof of concept for the use of diagnostics as introduced by https://github.com/DataDog/integrations-core/pull/14394.
[ASUP-14](https://datadoghq.atlassian.net/browse/ASUP-14)
This still needs a new release of the base check to include #14394 and a bump to the minimum base version before actually getting merged.
I struggled to come up with good pragmatic ideas for diagnostics for this integration. Other than the one I actually implemented, I considered trying to check that the configured users had the necessary permissions on the Mongo database as required by our integration, but that proved difficult to do (partly because it's not even clear to me what permissions our …
=> Add a diagnostic for TLS certificate files

ddev/src/ddev/cli/release/agent/__init__.py, ddev/src/ddev/cli/release/agent/changelog.py, ddev/src/ddev/cli/release/agent/common.py, ddev/src/ddev/repo/core.py, ddev/src/ddev/utils/git.py, ddev/tests/cli/release/agent/test_changelog.py
Migrates `release agent changelog` from `datadog_checks_dev`.
[AITOOLS-161](https://datadoghq.atlassian.net/browse/AITOOLS-161)
For reviewers: I tried to organize commits into meaningful units for ease of review.
[AITOOLS-161]: https://datadoghq.atlassian.net/browse/AITOOLS-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Migrate `release agent changelog` to ddev

ddev/tests/conftest.py
This was causing one test to fail for me because I have that envvar set.
=> Ignore ddev repo envvar when testing

datadog_checks_dependency_provider/MANIFEST.in, datadog_checks_dependency_provider/pyproject.toml, datadog_checks_dependency_provider/setup.py
The `ddev release agent changelog` command started to fail after #15513 because it expects all projects to have a pyproject.toml file.
=> Convert `datadog_checks_dependency_provider` to hatch

datadog_checks_dev/CHANGELOG.md, datadog_checks_dev/datadog_checks/dev/plugin/pytest.py, datadog_checks_dev/datadog_checks/dev/tooling/testing.py, datadog_checks_dev/datadog_checks/dev/utils.py
Stop using the TOX_ENV_NAME variable from ddev
We do not use tox anymore, we only use hatch now
=> Stop using the TOX_ENV_NAME variable

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, snowflake/pyproject.toml
Bump snowflake connector to 3.1.0
- We need to bump snowflake to bump cryptography to fix https://github.com/DataDog/image-vuln-scans/issues/1077
Should be merged at the same time as https://github.com/DataDog/datadog-agent/pull/18679
=> Bump snowflake connector to 3.1.0

ddev/CHANGELOG.md, ddev/src/ddev/cli/release/agent/changelog.py
More manual testing after the migration, I was trying to redirect the output to a file and found that it didn't, and it was because I wasn't aware of the distinction between the different new output functions.
=> Output changelog to stdout instead of stderr on `ddev release agent changelog`

.github/workflows/run-validations.yml
Remove the recommended_monitors option from the GH Action Templates
All other integrations repos no longer set this option (and the underlying command is removed on the main branch of ddev)
=> Remove recommended monitors from GH templates

teamcity/README.md
Update teamcity setup config docs to reflect basic auth provision in addition to metric collection via guest login
Request from Clay Richard (sales engineer).
I am working with the [Joby Aviation](https://datadog.lightning.force.com/lightning/r/Opportunity/0068Y00001Qsd8aQAB/view) team and we are working to get the TeamCity integration setup. We have hit a few roadblocks and if you can provide any support, it would greatly assist in this deal. 
When going through the setup docs, they noticed that we need to [Enable Guest Login](https://docs.datadoghq.com/integrations/teamcity/?tab=host#:~:text=see%20Enabling%20Guest%20Login.). They then mentioned that their company has a security policy against allowing this, so they cannot move forward if this is the only option. The TeamCity Data brings …
=> Update teamcity setup config docs to reflect basic auth provision

postgres/CHANGELOG.md, postgres/assets/configuration/spec.yaml, postgres/datadog_checks/postgres/config.py, postgres/datadog_checks/postgres/config_models/defaults.py, postgres/datadog_checks/postgres/config_models/instance.py, postgres/datadog_checks/postgres/metadata.py, postgres/datadog_checks/postgres/postgres.py, postgres/datadog_checks/postgres/statements.py, postgres/datadog_checks/postgres/util.py, postgres/tests/test_metadata.py, postgres/tests/test_pg_integration.py, postgres/tests/test_statements.py
This adds sending of a new metadata kind: `database_instance`. This doesn't require any new queries to collect the data as it's inferred from configuration and things collected during initialization (like version). 
We'd like to keep a better inventory of database instances regardless of whether dbm is enabled or not. We already have a concept of `database_instance` but this makes it a more direct element of collected information rather than something that is inferred / implicit from other data we collect.
=> Add support for sending database_instance metadata

coredns/README.md
Updates the CoreDNS readme with a Further Reading section linking to the recent series of blog posts
The Docs team does this as a courtesy to drive traffic to the Datadog blog
=> CoreDNS: Add a further reading section and link to blog posts

vsphere/assets/service_checks.json
Removes `vcenter_host` group from the service checks definition
This tag is only sent on service checks from the legacy implementation of the check
=> Remove deprecated service check group

airflow/README.md
An Airflow user might choose to use dots in their DAG name. The Pattern will then not match and produce very expensive custom metrics in datadog.
With this change, all DAG names are accepted
Update Airflow Statsd integration documentation
The original mapping rules cost us a lot of money
-
=> Provide exhaustive mapping rules for Airflow StatsD Integration

kubernetes/assets/dashboards/kubernetes_nodes.json
Use `last` instead of `avg` as an aggregator so it's immediately known how many nodes aren't ready in `Nodes not ready`'s `Query Value` widget.
This is because the number of nodes in not ready are always averaged which is not the current value. If we use `last`, it will always reflect the most current and actionable value.
=> fix(kubernetes-node): "Nodes not ready": use last

system_core/datadog_checks/system_core/system_core.py, system_core/tests/test_system_core.py
- remove unnecessary conversion to dict
- make sure variable with tags for cpu frequency is always defined.
[qa card](https://trello.com/c/YfJQEvXv/12526-adds-systemcorefrequency-metric)
=> Clean up system core cpu freq logic a little

otel/metadata.csv
We're adding support for OTel Python runtime metrics so this PR adds metadata entries for all of the new OTel runtime metrics from the [OTel Python SDK](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-system-metrics/src/opentelemetry/instrumentation/system_metrics/__init__.py).
=> Add metadata for OTel Python runtime metrics

otel/assets/recommended_monitors/otel_refused_spans.json, otel/manifest.json
This monitor alerts the user when there has been on average > 100 spans refused per second by a receiver in the past hour. The avg is used instead of sum in order to prevent alerting on "one-off" data losses, as this monitor should be used to scale the system after sustained data loss. The Defaults of 1 hour timeframe and 100 spans per second are high, but the user has the ability to change the value when they create the recommended monitor.
Several metrics were considered for this monitor, please see: https://docs.google.com/document/d/1P5gBaHacgc_UBrDIgNRlW2mF7BAX_ni6hfZK3j3GA4g/edit#.
R&D week project.
=> Add recommended monitor for OTel metrics

oracle/datadog_checks/oracle/oracle.py
The oracle check may have a memory leak when it cannot connect to the Oracle DB via JDBC, since the thread is never detached from the JVM.
=> Detach thread from JVM after connection

hatch.toml
A transitive dependency is now bounded to prevent a breaking change https://mkdocstrings.github.io/python/changelog/#130-2023-08-06
=> Fix documentation

datadog_checks_dev/CHANGELOG.md, datadog_checks_dev/datadog_checks/dev/tooling/commands/dep.py
Ignore `pydantic` when bumping the dependencies
https://github.com/DataDog/integrations-core/pull/15596
=> Ignore `pydantic` when bumping the dependencies

datadog_checks_dev/CHANGELOG.md, datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/prometheus.py
Print the metric list when parsing a prometheus endpoint
We use this list in the tests
Before:
```
╰─❯ ddev meta prom parse -f ray_head.txt ray                                                                                                                                                                                                                                                                                                                         ─╯
Globally available options:
t - Append .total to the available options
s - Skip
q - Quit
(1 of 1) python_gc_objects_collected_total
Type: counter
Info: Objects collected during gc
1 - python.gc.objects.collected.total
2 - python.gc.objects.collected_total
3 - python.gc.objects_collected.total
4 - python.gc.objects_collected_total
5 - …
```
=> Print the metric list when parsing a prometheus endpoint

datadog_checks_base/CHANGELOG.md, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/pyproject.toml
Downgrade pydantic to 2.0.2
- We can't use pydantic 2.1.1 because it needs pydantic-core 2.4.0 that we can't build on centos 6 (see https://github.com/DataDog/datadog-agent/pull/18303)
- The CI was already failing on the bump PR https://github.com/DataDog/integrations-core/pull/15585
I'll open another PR to exclude this dependency from the ddev command until we stop supporting centos 6
=> Downgrade pydantic to 2.0.2

postgres/assets/configuration/spec.yaml, sqlserver/assets/configuration/spec.yaml, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
The `disable_generic_tags` option namespaces tags like `host` to instead use `sqlserver_host` as the tag key. The original intention for this was described [here](https://datadoghq.atlassian.net/wiki/spaces/AI/pages/2205975610/RFC+-+Generic+tags) (for Datadog employees).
The config is used in the Service Check tags here: https://github.com/DataDog/integrations-core/blob/53daf26263a660685e4fefe8821d8d1fd61e4ee7/sqlserver/datadog_checks/sqlserver/sqlserver.py#L377-L383
However, this namespacing interferes with the Recommended Monitor feature, DBM, and Unified host linking features which rely on the `host` tag being set. It also makes it hard to document expected behaviors and train solutions engineers to assist customers because this option forks the expected behavior of the output tag …
=> Remove disable_generic_tags from the example yaml

eks_fargate/README.md
The PR updates the helm values supplied in the `Running the Cluster Agent or the Cluster Checks Runner` section of the EKS Fargate documentation with a necessary environment variable.
This environment variable is how we determine whether we are running on EKS Fargate or not. Without it, any logic we have in place which depends on running in Fargate is not used. This could have unintended consequences, such as the cluster name not being populated properly (as was detailed [here](https://github.com/DataDog/datadog-agent/pull/18859))
[Ticket](https://datadoghq.atlassian.net/browse/CONT-3975)
=> Update EKS Fargate docs to include DCA env var

docs/developer/meta/config-models.md
https://github.com/DataDog/integrations-core/pull/15212
=> Update config model docs

LICENSE-3rdparty.csv, datadog_checks_base/CHANGELOG.md, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, sqlserver/CHANGELOG.md, sqlserver/assets/configuration/spec.yaml, sqlserver/datadog_checks/sqlserver/azure.py, sqlserver/datadog_checks/sqlserver/config_models/instance.py, sqlserver/datadog_checks/sqlserver/connection.py, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example, sqlserver/pyproject.toml, sqlserver/tests/odbc/odbcinst.ini, sqlserver/tests/test_connection.py
Adds support for Azure AD managed authentication in the SQL Server integration. Specifically, this implementation works with **[Azure Managed Identity](https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview-for-developers?tabs=portal%2Cdotnet)** (both `system` and `user`).
Note: this feature requires using the [ODBC driver (version 18 or above)](https://learn.microsoft.com/en-us/sql/connect/odbc/using-azure-active-directory?view=sql-server-ver16#new-andor-modified-dsn-and-connection-string-keywords) in order to connect.
Azure Managed Identity works very similar to AWS's IAM, in that it allows the customer to avoid managing credentials. There are two main types of managed identities:
1. System-assigned. Some Azure resources, such as virtual …
=> Support Auth through Azure AD MI / Service Principal

LICENSE-3rdparty.csv, datadog_checks_base/CHANGELOG.md, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, sqlserver/CHANGELOG.md, sqlserver/pyproject.toml
Removes support for python versions older than 3.9 for the sqlserver integration
=> Remove python 2 references from SQL Server integration

ddev/CHANGELOG.md, ddev/src/ddev/cli/release/agent/__init__.py, ddev/src/ddev/cli/release/agent/integrations_changelog.py, ddev/src/ddev/cli/terminal.py, ddev/tests/cli/release/agent/test_integrations_changelog.py
[AITOOLS-186](https://datadoghq.atlassian.net/browse/AITOOLS-186)
I've left the completion command to still depend on `datadog_checks_dev` because since it's something that will be used from different places and it feels like a separate concern it should probably be dealt with in a separate PR.
[AITOOLS-186]: https://datadoghq.atlassian.net/browse/AITOOLS-186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Migrate `ddev release agent integrations` to `ddev`

cacti/tests/common.py
Do not install `libpython2-dev` in the agent container
- https://github.com/DataDog/integrations-core/actions/runs/5900811282/job/16005852279#step:14:36
- Seems like it's not needed anyway
=> Do not install libpython2-dev in the agent container

.ddev/config.toml, LICENSE-3rdparty.csv, datadog_checks_base/CHANGELOG.md, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_dev/CHANGELOG.md, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/licenses.py, postgres/CHANGELOG.md, postgres/datadog_checks/postgres/connections.py, postgres/datadog_checks/postgres/explain_parameterized_queries.py, postgres/datadog_checks/postgres/metadata.py, postgres/datadog_checks/postgres/postgres.py, postgres/datadog_checks/postgres/statement_samples.py, postgres/datadog_checks/postgres/statements.py, postgres/datadog_checks/postgres/version_utils.py, postgres/pyproject.toml, postgres/tests/common.py, postgres/tests/conftest.py, postgres/tests/test_connections.py, postgres/tests/test_deadlock.py, postgres/tests/test_explain_parameterized_queries.py, postgres/tests/test_pg_integration.py, postgres/tests/test_pg_replication.py, postgres/tests/test_statements.py, postgres/tests/test_unit.py
We are intermittently seeing the following error, when running the integration on our internal clusters via the cluster check runner:
```
psycopg.OperationalError: sending query failed: another command is already in progress
```
While the `pyscopg3` Connection object is thread safe, we cannot execute a command on that connection when another is in the process of executing. This makes sharing the connection between multiple threads a bit dangerous, since `psycopg` doesn't do a good job of handling that situation under the hood. After this happens, the connection is basically unusable to the client, which breaks the check. 
This leaves us with the following options:
1. Create a connection per thread
2. Make all queries on the same connection object synchronized
3. Catch this exception & …
=> Prevent `command already in progress` errors in the Postgres integration

postgres/CHANGELOG.md, postgres/assets/configuration/spec.yaml, postgres/datadog_checks/postgres/config.py, postgres/datadog_checks/postgres/config_models/defaults.py, postgres/datadog_checks/postgres/config_models/validators.py, postgres/datadog_checks/postgres/data/conf.yaml.example
Since updating our config validation code, we started seeing issues with setting the default value for `ssl` mode as it was being interpretted as a `boolean` instead of a `str` during the validation process. This would lead to errors like this:
```
2023-08-17 20:16:45 UTC | CORE | ERROR | (pkg/collector/worker/check_logger.go:70 in Error) | check:postgres | Error running check: [{"message": "Detected 1 error while loading configuration model `InstanceConfig`:\nssl\n  Input should be a valid string", "traceback": "Traceback (most recent call last):\n  File \"/usr/src/dbm-integrations-core/datadog_checks_base/datadog_checks/base/checks/base.py\", line 1126, in run\n    initialization()\n  File \"/usr/src/dbm-integrations-core/datadog_checks_base/datadog_checks/base/checks/base.py\", line …
```
=> Fix InstanceConfig loading error for `ssl` config

.ddqa/config.toml
ddqa reporting an error from Jira: `The value 'PINT' does not exist for the field 'project'.`. Apparently the Jira project for Platform Integrations has been renamed from PINT to PLINT.
=> Rename Jira project PINT -> PLINT in ddqa config

supervisord/CHANGELOG.md, supervisord/assets/configuration/spec.yaml, supervisord/datadog_checks/supervisord/data/conf.yaml.example
Update the description of the `status_mapping_override` option
- This is probably nitpicking, but `Supervisor` is the product, `supervisord` is the process and this is what we use everywhere else in the config file, so switching for consistency.
- This was requested by the docs team: https://github.com/DataDog/integrations-core/pull/14190#discussion_r1142131918 
- It was applied here: https://github.com/DataDog/integrations-core/pull/14190/commits/1975802b245c374e850971e46a9e7891e941b751
- And dropped there: https://github.com/DataDog/integrations-core/pull/14190/commits/4774a316ad8180ccd09523ed444b5d64f913f7d3
=> Update the description of the `status_mapping_override` option

kafka_consumer/CHANGELOG.md, kafka_consumer/datadog_checks/kafka_consumer/client.py
Add missing timeout when looking up offsets
- QA for https://github.com/DataDog/integrations-core/pull/15285
- https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#id14
=> Add missing timeout when looking up offsets

supervisord/CHANGELOG.md, supervisord/datadog_checks/supervisord/supervisord.py, supervisord/tests/common.py
Stop raising `TypeError`s when `status_mapping_override` contains unknown Datadog statuses
QA for https://github.com/DataDog/integrations-core/pull/14190
```
>>> print("%s - %s" % [1, 2])
File "<stdin>", line 1, in <module>
TypeError: not enough arguments for format string
>>> print("%s - %s" % (1, 2))
1 - 2
```
`[...]` is used in the other exceptions because we need a list there, here we want to print both parameters
I'll probably refactor this giant test in the future to use `parametrize`
=> Stop raising `TypeError`s when `status_mapping_override` contains unknown Datadog statuses

airbyte/assets/dashboards/airbyte_overview.json
- Correct metric names.
- Remove widgets that reference deprecated metrics.
Addressing https://github.com/DataDog/integrations-core/pull/15376#discussion_r1295997700
=> Fix airbyte dashboard based on customer feedback

postgres/tests/test_statements.py
`test_statement_samples_main_collection_rate_limit` relies on sleep time and the sleep needs to be low in order to make test run time reasonable. But given this and the time-driven nature of this test, the collection rate value ends up often being off by one (3 instead of 2). We could help with this by increasing the test duration but then we pay the penalty every time we run tests. Instead, this relaxes the tolerance for the collection rate. Now the test would pass if the value is 3.
=> Reduce postgres test_statement_samples_main_collection_rate_limit test flakyness

ecs_fargate/CHANGELOG.md, ecs_fargate/datadog_checks/ecs_fargate/ecs_fargate.py
Multiplies the value of memory by 1024*1024 to ensure that the `ecs.fargate.mem.task.limit` metric is reported correctly.
When testing that the ECS Fargate integration now has a new task memory limit metric (`ecs.fargate.mem.task.limit`), it was noticed that though the metric shows up, the units are in the wrong order of magnitude. This change updates the value so it matches the actual value being sent through. 
Original PR adding this feature: https://github.com/DataDog/integrations-core/pull/15401
=> Fix ECS Fargate memory task limit units

sqlserver/CHANGELOG.md, sqlserver/datadog_checks/sqlserver/queries.py
This change fixes an issue we are seeing where file stats metrics for Azure SQL DB were incorrect. You can see in the screenshot below that the sizes tagged by `logical_name` look wrong since one is tagged as `none`
... this is because, our query calls the `sys.dm_io_virtual_file_stats` function with the `database_id` parameter set to `NULL`, which will show data for all databases on the Azure SQL DB, **despite the fact that the user does not have access to these other databases, and therefore doesn't need this information**.  This returns a strange result that looks like this:
... what we should do is use the `database_id` parameter to filter to the database we are connected to (and the only one the customer cares about). This returns correct results:
=> Fix sqlserver file stats metrics for Azure SQL DB

openmetrics/README.md
Adds an explanation for the default behavior around untyped metrics and how to collect such metrics.
#15431 rightly pointed out that the default behavior around untyped metrics seems to be undocumented.
Documentation about our Openmetrics integration is somewhat spread around guides beyond the integration's documentation which I'm updating here. #15431 pointed at https://docs.datadoghq.com/containers/kubernetes/prometheus/, but I feel that this README should be the ultimate and common source of truth when it comes to this integration, hence why I'm putting it there.
=> Add a section to Openmetrics README on how untyped metrics are handled

harbor/hatch.toml
Revive the 2.3.2 test env
In https://github.com/DataDog/integrations-core/pull/13079, I copied the test matrix which did not include `2.3.2`, but the environment was declared, it was just not used
=> Revive the 2.3.2 test env

confluent_platform/tests/metrics.py
Mark a broker metric as optional
This metric is a bit flaky: https://github.com/DataDog/integrations-core/actions/runs/5940406795/job/16109082882
```
___________________________________ test_e2e ___________________________________
tests/test_e2e.py:35: in test_e2e
aggregator.assert_metric(metric)
../datadog_checks_base/datadog_checks/base/stubs/aggregator.py:368: in assert_metric
self._assert(condition, msg=msg, expected_stub=expected_metric, submitted_elements=self._metrics)
../datadog_checks_base/datadog_checks/base/stubs/aggregator.py:410: in _assert
assert condition, new_msg
E   AssertionError: Needed at least 1 candidates for 'confluent.kafka.controller.unclean_leader_elections_per_sec.rate', got 0
E …
```
=> Mark a broker metric as optional

openldap/assets/dashboards/openldap_overview.json
Adjustments to OpenLDAP dashboards in the Threads section.
- Change formula in "Remaining Available Threads" graph to use `openldap.threads.max - openldap.threads:active` (only subtracting `active` threads instead of the sum of all threads).
- Change "Threads by Status" graph to use lines instead of areas, to account for the fact that the values are not really additive in general.
#15255. There's a mistake in how available threads are calculated in the "Remaining Available Threads" graph. Not all values for the `openldap.threads` metric represent threads in use, and in fact there's even some overlap between the values for the different statuses. The calculation that makes the most sense here is to subtract just the `active` threads.
That same overlap means that "Threads by Status" is …
=> Fixes to OpenLDAP dashboard regarding Thread metrics

marklogic/tests/README.md
This PR adds instructions for testing MarkLogic 11 on ARM Macs.
Docker Desktop 4.16+ supports running amd64 containers on ARM using Virtualization.
This could likely also work for other integrations with intel-based containers.
=> Add E2E testing instructions for marklogic on ARM

datadog_checks_downloader/tests/test_downloader.py
This PR removes `datadog-go-metro` from being tested in the datadog-checks-downloader E2E tests.
[`go-metro`](https://github.com/DataDog/integrations-core/tree/master/go-metro) is an Agent v5-only integration that was [last signed by a revoked dev](https://github.com/DataDog/integrations-core/pull/8782), so it occasionally [fails CI](https://github.com/DataDog/integrations-core/actions/runs/5937862379/job/16101230312#step:12:638).
[AI-3435](https://datadoghq.atlassian.net/browse/AI-3435)
[AI-3435]: https://datadoghq.atlassian.net/browse/AI-3435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Exclude go-metro from downloader testing

ddev/CHANGELOG.md
This PR adds a missing changelog entry for https://github.com/DataDog/integrations-core/pull/15475. 
The feature is [included in ddev 3.5.0](https://github.com/DataDog/integrations-core/commits/ddev-v3.5.0/ddev).
=> Add missing changelog for ddev

kafka_consumer/tests/README.md, kafka_consumer/tests/python_client/script.py
This PR adds a test script `script.py` that attempts a connection to Kafka for debugging. The script will connect to the Kafka cluster and output all consumer groups.
This is helpful for support cases where connection issues are difficult to determine.
=> Add test script for debugging

ddev/CHANGELOG.md, ddev/pyproject.toml
Bump datadog-checks-dev version to ~=24.0
I needed https://github.com/DataDog/integrations-core/pull/15586 that is shipped in 24.*
=> Bump datadog-checks-dev version to ~=24.0

confluent_platform/tests/conftest.py
Add more attempts to the conditions in the e2e environment 
- https://datadoghq.atlassian.net/browse/AI-3436
- The e2e is a bit flaky, let's give it a bit more time to spin up
```
2023-08-28T15:59:11.5859720Z E           datadog_checks.dev.errors.RetryError: Command: ['docker', 'logs', 'connect']
2023-08-28T15:59:11.5878665Z E           Failed to match `3` of the patterns.
2023-08-28T15:59:11.5899736Z E           Provided patterns: 	- re.compile(' Started KafkaBasedLog', re.MULTILINE)	- re.compile('INFO REST resources initialized', re.MULTILINE)	- re.compile('Kafka Connect started', re.MULTILINE)
2023-08-28T15:59:11.5920885Z E           Missing patterns: 	- re.compile(' Started KafkaBasedLog', re.MULTILINE)	- re.compile('INFO REST resources initialized', re.MULTILINE)	- re.compile('Kafka …
```
=> Add more attempts to the conditions in the e2e environment

wincrashdetect/manifest.json
Disable the showing of these docs on the documentation site. 
There is no associated logo (which we're actively adding a validation for, and this is failing)
So the tile and docs page show an empty logo until thats resolved.
=> Disable docs appearing + validation for wincrashdetect

snmp/CHANGELOG.md, snmp/datadog_checks/snmp/data/default_profiles/ubiquiti-unifi-security-gateway.yaml, snmp/datadog_checks/snmp/data/default_profiles/ubiquiti-unifi.yaml
See title. `_base.yaml` exists in `_ubiquiti.yaml`
Relates to https://github.com/DataDog/integrations-core/pull/15399
=> Delete unnecessary extend for ubiquiti profiles

datadog_checks_dev/CHANGELOG.md, datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py
Add short hand for `--force-env-rebuild`
=> Add short hand for force env rebuild in test

calico/tests/common.py
Mark one metric as optional
https://github.com/DataDog/integrations-core/actions/runs/6015629865/job/16317946139:
```
E   AssertionError: Needed at least 1 candidates for 'calico.felix.int_dataplane_failures.count', got 0
E   Expected:
E           MetricStub(name='calico.felix.int_dataplane_failures.count', type=None, value=None, tags=None, hostname=None, device=None, flush_first_value=None)
E   Similar submitted:
E   Score   Most similar
E   0.[64](https://github.com/DataDog/integrations-core/actions/runs/6015629865/job/16317946139#step:14:65)    MetricStub(name='calico.felix.iptables.chains', type=0, value=32, tags=['endpoint:http://10.1.0.230:34737/metrics', 'ip_version:4', 'table:filter'], hostname='fv-az448-717', device=None, flush_first_value=False)
E   0.64 …
```
=> Mark one metric as optional

mysql/tests/test_query_activity.py
This PR fixes the flakey test `test_activity_collection_rate_limit`. 
The test relies on `time.sleep(sleep_time)` to run the activity collection for certain period of time and then uses the `sleep_time` to calculate the maximum possible metrics to be collected during this time period.
The reason why the test sometimes fails is because `check.cancel()` cancels a list of checks one by one. By the time it successfully cancels `_query_activity`, the collection of the metrics might run slightly over the `sleep_time`, causing the number of metrics collected exceed the maximum number we are expecting. 
The change is to calculate the expected `max_collections` based on `time_elapsed`. This way it provides a more accurate view of how much time the check has been running. 
More robust logic in …
=> [DBM-2797] fix rate limited activity collection test case

postgres/tests/test_pg_integration.py
This PR checks PG version in `test_snapshot_xmin`. `txid_current_snapshot` and `txid_current` is deprecated starting PG 13. For PG > 13, use `pg_current_snapshot` and `txid_current`. 
In addition to the PG version check, also reordered the steps in the test to ensure we correctly collect the metrics and compare to the right value.
=> [DBM-2734] fix test_snapshot_xmin for pg > 13

postgres/tests/test_statements.py
We are seeing this test fail the night jobs periodically, so this should help make the test less flakey. The failure is caused by a db connection not being closed completely on a call to `cancel` before we assert that all connections are closed. This commit changes the following:
1. Updates the `min_collection_interval` for the test to be 1 second, which is also the [timeout we set on the blocking call to close connections at shutdown](https://github.com/DataDog/integrations-core/blob/master/postgres/datadog_checks/postgres/postgres.py#L737). For the regular check, this number is typically much higher, but we set it to `.2` for the tests.
2. Assert that the job loops are no longer running, which could be holding the open connection in the connection pooling logic
3. Move the db connection …
=> Make test_async_job_enabled less flakey

openmetrics/README.md
* Changes the headers code snippet to be a dictionary instead of a list as expected by the config : https://github.com/DataDog/integrations-core/blob/master/openmetrics/datadog_checks/openmetrics/data/conf.yaml.example#L537
* Aligns the `...` to emphase it is meant to represent the other options **inside** the instance
* Customer case, using the example, we get an error while the check tries to parse through the configuration :
=> [Openmetrics] Remove dash to use proper headers mapping -> dic, not list

clickhouse/CHANGELOG.md, clickhouse/pyproject.toml, datadog_checks_base/CHANGELOG.md, datadog_checks_base/datadog_checks/base/data/agent_requirements.in
Newer versions of pip cannot understand ranges that erroneously include wildcards:
- https://github.com/mymarilyn/clickhouse-driver/pull/291
- https://github.com/pypa/packaging/issues/673
```
Collecting clickhouse-driver==0.2.3 (from datadog-clickhouse==3.0.0)
Downloading clickhouse-driver-0.2.3.tar.gz (213 kB)
-------------------------------------- 213.3/213.3 kB 4.3 MB/s eta 0:00:00
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'error'
error: subprocess-exited-with-error
python setup.py egg_info did not run successfully.
exit code: 1
[15 lines of output]
C:\Users\ofek\AppData\Local\hatch\env\virtual\datadog-clickhouse\BSWKISFA\latest\Lib\site-packages\setuptools\config\setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
!! …
```
=> Upgrade clickhouse-driver to 0.2.6 on Python 3

dcgm/README.md, torchserve/README.md, weaviate/README.md
This PR removes the `coming soon` banners for Weaviate, Torchserve, and DCGM once 7.47 is available.
Once 7.47 is available the banners are no longer necessary.
=> Remove coming soon banner

sqlserver/CHANGELOG.md, sqlserver/datadog_checks/sqlserver/const.py, sqlserver/datadog_checks/sqlserver/metrics.py, sqlserver/metadata.csv, sqlserver/tests/compose/setup.sql
- Add `index_name` tag to `.database.avg_fragmentation_in_percent`, `.database.fragment_count`, `.database.avg_fragment_size_in_pages` metrics. 
- Also add a new metric `sqlserver.database.index_page_count`, tagged by `database_name`, `object_name`, `index_id` and `index_name`.
Wanted better and cleaner coverage of SQLServer index fragmentation data from sys.dm_db_index_physical_stats.
=> [SQLServer] - Add index page count metric, and index name to fragmentation metrics

ddev/src/ddev/config/file.py, ddev/tests/cli/config/test_show.py, ddev/tests/cli/release/test_list_versions.py, ddev/tests/cli/validate/test_ci.py, ddev/tests/cli/validate/test_http.py, ddev/tests/cli/validate/test_licenses.py, ddev/tests/cli/validate/test_manifest.py, ddev/tests/cli/validate/test_metrics.py, ddev/tests/cli/validate/test_openmetrics.py, ddev/tests/conftest.py, ddev/tests/utils/test_github.py
- Often the tests need a real repository but do not need to make modifications necessitating a cleanup Git reset step
- An upcoming PR requires this to prevent a significant increase in CI time
- Linux about the same [2:12](https://github.com/DataDog/integrations-core/actions/runs/6052110731/job/16425053267) to [2:08](https://github.com/DataDog/integrations-core/actions/runs/6065951218/job/16456407905)
- Windows [4:08](https://github.com/DataDog/integrations-core/actions/runs/6052110731/job/16425026443) to [3:06](https://github.com/DataDog/integrations-core/actions/runs/6065951218/job/16456407845)
=> Speed up test suite

.gitlab/validate-logs-intgs/validate_log_intgs.py
We have a script to validate integrations that have a log pipeline are correctly documented. This PR allows aws-fargate to raise the ERR_UNEXPECTED_LOG_DOC error.
There's no pipeline for this integration but we have a ton of examples that match the patterns caught by the validation. It's fine for this integration to define these examples and should not raise an error.
=> Allow aws-fargate to have a source name without log pipeline in its README

datadog_checks_dev/CHANGELOG.md, datadog_checks_dev/datadog_checks/dev/tooling/commands/dep.py
Allow bumping the version of clickhouse-driver
We can now bump it again https://github.com/DataDog/integrations-core/pull/15726 and we use the [latest version](https://pypi.org/project/clickhouse-driver/)
=> Allow bumping the version of clickhouse-driver

.gitlab/tagger/build-packages.sh
ci_build env variables are being removed for ci_job equivalents
We are upgrading gitlab to gitlab 16
=> update removed gitlab env variables

kube_controller_manager/CHANGELOG.md, kube_controller_manager/datadog_checks/kube_controller_manager/kube_controller_manager.py, kube_controller_manager/tests/fixtures/metrics.txt, kube_controller_manager/tests/test_kube_controller_manager.py
Capture the `node_collector_evictions_total` metric emitted by the kube controller manager, and map it to `kube_controller_manager.nodes.evictions` in Datadog.
In Kubernetes v1.24, the `node_collector_evictions_number` metric, which we currently map to `kube_controller_manager.nodes.evictions`, was deprecated and replaced with the `node_collector_evictions_total` metric. This change updates the check logic so we can continue to capture this data for users using Kubernetes v1.24+.
* Does this PR fall under `Changed` or `Added` ?
* Would separating out the test into a new file make more sense?
=> Capture `node_collector_evictions_total` metric in kube controller manager

requirements-agent-release.txt, snmp/CHANGELOG.md, snmp/datadog_checks/snmp/__about__.py
Update changelog for backported 6.2.1 release for 7.48: https://github.com/DataDog/integrations-core/pull/15753
=> [Release] Bumped snmp version to 6.2.1

.coveragerc, .github/workflows/test-target.yml, ddev/CHANGELOG.md, ddev/pyproject.toml, ddev/src/ddev/cli/__init__.py, ddev/src/ddev/cli/test/__init__.py, ddev/src/ddev/integration/core.py, ddev/src/ddev/plugin/external/hatch/environment_collector.py, ddev/src/ddev/testing/__init__.py, ddev/src/ddev/testing/constants.py, ddev/src/ddev/utils/fs.py, ddev/tests/cli/test/__init__.py, ddev/tests/cli/test/test_test.py, ddev/tests/conftest.py, ddev/tests/helpers/api.py, docs/developer/testing.md
This moves the test command to ddev
- The command now accepts the name of a single target to test rather than an arbitrary number (not providing this will still test everything that has changed). All arguments after this are passed to the underlying command(s) which is usually just `pytest`, thus removing the need for the `--pytest-args`, `--marker`, `--filter`, `--pdb` and `--debug` options. You may now pass arguments like this:
```
ddev test [TARGET] -- -m unit
```
A benefit of this is that we no longer pass arguments using environment variables and so the full command will be displayed which will ease debugging:
```
cmd [1] | pytest -vv --benchmark-skip --tb short -m unit
```
Since the first argument is the optional name of a target, passing arguments to the underlying commands for …
=> Migrate test command

postgres/CHANGELOG.md, postgres/assets/configuration/spec.yaml, postgres/datadog_checks/postgres/config.py, postgres/datadog_checks/postgres/config_models/defaults.py, postgres/datadog_checks/postgres/config_models/instance.py, postgres/datadog_checks/postgres/connections.py, postgres/datadog_checks/postgres/postgres.py, postgres/tests/test_connections.py
This updates the default `timeout` parameter used when grabbing a connection from the [psycopg_pool](https://www.psycopg.org/psycopg3/docs/api/pool.html), which was previously 30 seconds. When databases are misconfigured, this timeout will be hit & can cause issues for the CLC, which is running more checks than just postgres. 
For example, a `PoolTimeout` exception was hit on initialization for this misconfigured databas:
```
Error running check: [{"message": "couldn't get a connection after 30.0 sec", "traceback": "Traceback (most recent call last):
File \"/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/base/checks/base.py\", line 1210, in run
initialization()
File \"/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/postgres/postgres.py\", line …
```
=> Set lower connection timeout on connection pool, to avoid long running checks

postgres/CHANGELOG.md, postgres/datadog_checks/postgres/__about__.py, requirements-agent-release.txt
Port postgres 14.2.3 [release](https://github.com/DataDog/integrations-core/pull/15771) changes from 7.48 to master
https://github.com/DataDog/integrations-core/pull/15768
=> [Release] Bumped postgres version to 14.2.3 (#15771)

postgres/CHANGELOG.md, postgres/datadog_checks/postgres/connections.py, postgres/datadog_checks/postgres/postgres.py, postgres/datadog_checks/postgres/statement_samples.py, postgres/datadog_checks/postgres/statements.py, postgres/tests/test_statements.py
This PR initialize `pg_settings` on Postgres check starts. When retrieving `pg_settings`, it will lazy load from database if it's not set. As part of the PR, we also default `pg_stat_statements.max` to `5000` if it's not been explicitly set. `5000` is the [default](https://www.postgresql.org/docs/current/pgstatstatements.html)) `pg_stat_statements.max` from Postgres.
Fixes uncaught exception
```
Unable to collect statement metrics due to an error
File "/usr/src/dbm-integrations-core/postgres/datadog_checks/postgres/statements.py", line 193, in collect_per_statement_metrics
rows = self._collect_metrics_rows()
File "/usr/src/dbm-integrations-core/datadog_checks_base/datadog_checks/base/utils/tracking.py", line 71, in wrapper
result = function(self, *args, …
```
=> Initialize pg_settings on postgres check start and lazy load pg_settings if not set

datadog_checks_dev/CHANGELOG.md, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/pyproject.toml
Remove setuptools from the build-system for new integrations
https://github.com/DataDog/integrations-core/pull/15441#discussion_r1317175844
=> Remove setuptools from the build-system for new integrations

datadog_checks_dev/CHANGELOG.md, datadog_checks_dev/datadog_checks/dev/tooling/signing.py
Stop using the old GPG_COMMAND constant from securesystemslib
They created a new `gpg_command` function instead [here](https://github.com/secure-systems-lab/securesystemslib/commit/56697adf9803a7bcecadc737d8b160a9ab22392e) and dropped the constant after.
We should have caught that with the tests. We will add more when moving this command to ddev
=> Stop using the old GPG_COMMAND constant from securesystemslib

ddev/CHANGELOG.md, ddev/src/ddev/cli/application.py
setting `DDEV_REPO`  environment would not change which tests `ddev test` ran, it would always run the tests for the `core` repo.
`ddev test` respects fully `DDEV_REPO` envvar.
I work with [git worktrees](https://git-scm.com/docs/git-worktree), this helps me maintain multiple unfinished contexts in parallel. I don't want to run ddev tests with the `-x` flag all the time so I set the envvar for REPO to the worktree directory. Unfortunately `ddev test` would ignore this setting.
Any suggestions for **how exactly** to test this would be welcome.
=> Make sure repo override in envvar makes it into config

http_check/CHANGELOG.md, http_check/assets/configuration/spec.yaml, http_check/datadog_checks/http_check/config.py, http_check/datadog_checks/http_check/config_models/defaults.py, http_check/datadog_checks/http_check/config_models/instance.py, http_check/datadog_checks/http_check/data/conf.yaml.example, http_check/datadog_checks/http_check/http_check.py, http_check/tests/test_http_integration.py, http_check/tests/test_unit_config.py
Inconsistencies between the original HTTP request and the second socket based poll such as proxying
=> Add `use_cert_from_response` option

.github/workflows/pr-all.yml, datadog_checks_dev/CHANGELOG.md, datadog_checks_dev/hatch.toml, datadog_checks_dev/pyproject.toml, datadog_checks_dev/setup.cfg, datadog_checks_downloader/CHANGELOG.md, datadog_checks_downloader/hatch.toml, datadog_checks_downloader/pyproject.toml, teamcity/CHANGELOG.md, teamcity/hatch.toml, teamcity/pyproject.toml, teamcity/setup.cfg, win32_event_log/hatch.toml, win32_event_log/setup.cfg
Fix stuff coming from https://github.com/DataDog/integrations-core/pull/15762
- Add more pytest options to some integrations that require it
- Run all tests when ddev is modified
- Move most of the command overrides to either `pyproject.toml` (for python3) or `setup.cfg` (for py2)
https://github.com/DataDog/integrations-core/actions/runs/6105895055/job/16570096990
When we add parameters after 
https://github.com/DataDog/integrations-core/blob/c758504930a54f90c4d35d2d4b5e6868415b6106/ddev/src/ddev/cli/test/__init__.py#L154
, they will be forward to 
https://github.com/DataDog/integrations-core/blob/master/ddev/src/ddev/plugin/external/hatch/environment_collector.py#L114-L119 as `args` and we loose the `tests` part of the command, which make us load everything. 
Trigger all the tests when …
=> Override the default test options for some integrations

sqlserver/CHANGELOG.md, sqlserver/datadog_checks/sqlserver/metrics.py, sqlserver/tests/test_integration.py, sqlserver/tests/test_unit.py
- Adds the `db:` tag to every metric that bears another key for database name. i.e. `database_name` or `database` for consistency.
We would like to standardize on the `db` tag for logical database name.
=> [SQLServer] - Standardize on db tag for database name

win32_event_log/CHANGELOG.md, win32_event_log/pyproject.toml
I forgot to override the testspath [here](https://github.com/DataDog/integrations-core/pull/15779/files#diff-a6a32ae655e670b8ba693c0ffabd276ea6cba6b469b40b57155b7d4a418aba01) for py3 tests so only tests/legacy were running (you can see that [here](https://app.codecov.io/gh/DataDog/integrations-core/tree/master/win32_event_log%2Ftests))
=> Run all the tests on py3

snowflake/README.md
Add instructions to grant usage to your default warehouse to the role DATADOG
[DOCS-6150](https://datadoghq.atlassian.net/browse/DOCS-6150)
- https://datadog.zendesk.com/agent/tickets/1326287
- https://datadog.zendesk.com/agent/tickets/548919
- https://datadog.zendesk.com/agent/tickets/477220
[DOCS-6150]: https://datadoghq.atlassian.net/browse/DOCS-6150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Grant usage to default warehouse to the role DATADOG

.github/CODEOWNERS, openai/assets/dashboards/overview_dashboard.json
This PR updates the estimated cost calculation query in the OpenAI integration dashboard to use the OpenAI V2 integration's `openai.request.model` instead of `openai.model`. This was missed in the V2 integration PR.
This PR also updates the pricing doc the dashboard provides to reflect correct model prices as of September 1, 2023.
This PR also removes the apm-python-core team as a codeowner for the integrations, as this will be owned by the llm-observability team moving forward.
=> OpenAI update correct model tag name in cost calculation, update pricing doc

requirements-agent-release.txt, snmp/CHANGELOG.md, snmp/datadog_checks/snmp/__about__.py
Port snmp v6.2.2 release from 7.48.x to master
https://github.com/DataDog/integrations-core/pull/15765 and https://github.com/DataDog/integrations-core/pull/15800
=> [Release] Bumped snmp version to 6.2.2 (#15812)

ddev/CHANGELOG.md, ddev/pyproject.toml
Bump the `target-version` to python 3.9 for ruff and black
We now use py3.9
=> Bump the `target-version` to python 3.9 for ruff and black

ddev/CHANGELOG.md, ddev/pyproject.toml
Bump the `datadog-checks-dev` version to ~=25
https://github.com/DataDog/integrations-core/pull/15822
=> Bump the `datadog-checks-dev` version to ~=25

datadog_cluster_agent/assets/dashboards/datadog_cluster_agent_overview.json
Two new widgets are added to the cluster agent dashboard for the `datadog.cluster_agent.admission_webhooks.library_injection_attempts` and `datadog.cluster_agent.admission_webhooks.library_injection_errors` metrics.
These metrics are currently used to track library injection events in the agent. These events are not currently tracked by the `datadog.cluster_agent.admission_webhooks.mutation_attempts`/`datadog.cluster_agent.admission_webhooks.mutation_errors` metrics, which already have widgets in the dashboard.
=> Add admission controller library injection widgets to OOTB cluster agent dashboard

requirements-agent-release.txt, snmp/CHANGELOG.md, snmp/datadog_checks/snmp/__about__.py
Port snmp v6.2.3 release from 7.48 to master
https://github.com/DataDog/integrations-core/pull/15826
=> [Release] Bumped snmp version to 6.2.3 (#15829)

ddev/CHANGELOG.md, ddev/src/ddev/cli/test/__init__.py, ddev/src/ddev/plugin/external/hatch/environment_collector.py, ddev/tests/cli/test/test_test.py
Fix the `--compat` option of the `test` command.
Also allow you to run `ddev test http_check && ddev test --compat http_check && ddev test http_check` since now the `--compat` option will recreate the environment and remove it after running the tests, which was not possible without this fix.
It is failing here in some cases: https://github.com/DataDog/integrations-core/actions/runs/6155117614/job/16701562039#step:14:185 
Run `ddev test --compat http_check` if you want to double check the fix is working. 
The bug is coming from [here](https://github.com/DataDog/integrations-core/commit/8ca9fa2242010365f562c23ce9b8c4b4753454cb?diff=split#diff-ecde22fd90da0cd98a6fda7df0f5499102ca47c3724706d612b0cd1c2964513b)
=> Fix the `--compat` option of the `test` command

ddev/CHANGELOG.md, ddev/src/ddev/cli/__init__.py, ddev/src/ddev/cli/dep.py, ddev/src/ddev/integration/core.py, ddev/src/ddev/utils/fs.py, ddev/tests/cli/test_dep.py
[AITS-228](https://datadoghq.atlassian.net/browse/AITS-228).
As part of the migration I've also ported the code from `aiohttp` to `httpx` and removed the use of `aiomultiprocessing`, without any performance loss as far as I could tell (I think it was even faster after some code reshuffling).
[AITS-228]: https://datadoghq.atlassian.net/browse/AITS-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Migrate `ddev dep` to `ddev`

.github/workflows/build-ddev.yml
Installers like an MSI should be the only way to upgrade/downgrade/remove installations that have already been installed that way
=> Only enable ddev management commands for standalone binaries

postgres/CHANGELOG.md, postgres/datadog_checks/postgres/connections.py, postgres/datadog_checks/postgres/postgres.py, postgres/tests/test_connections.py
This PR 
- adds a safeguard to test postgres connection before trying to establish a connection pool. The check `_attempt_to_connect` will make a connection (not a connection pool) to postgres when postgres check is initialized. If the connection is failed to establish, it will immediately fail the check.
- Set the reconnect timeout to 0 (fail fast)
Previously, connection error will only be observed when the first query is executed. The default psycopg connection pool has default 30s reconnect timeout, which will block for 30s while retry is happening.
=> test postgres connection before initializing connection pool

datadog_checks_dev/CHANGELOG.md, datadog_checks_dev/datadog_checks/dev/tooling/commands/dep.py
Prevent us from upgrading psycopg with all other dependencies.
https://github.com/DataDog/integrations-core/pull/15859
=> Exclude psycopg2 from automatic upgrades

postgres/CHANGELOG.md, postgres/datadog_checks/postgres/__about__.py, requirements-agent-release.txt
Port postgres v14.3.0 release to master
https://github.com/DataDog/integrations-core/pull/15839 and https://github.com/DataDog/integrations-core/pull/15859
=> [Release] Bumped postgres version to 14.3.0 (#15863)

postgres/CHANGELOG.md, postgres/datadog_checks/postgres/__about__.py, requirements-agent-release.txt
Port postgres v14.4.0 release to master
https://github.com/DataDog/integrations-core/pull/15866
Correct the changelog between 14.3.0 and 14.4.0
=> Port postgres v14.4.0 release to master

sqlserver/CHANGELOG.md, sqlserver/datadog_checks/sqlserver/statements.py, sqlserver/tests/test_statements.py
We recently heard from a customer that certain long-running queries of theirs were missing corresponding metrics. Looking into it, this is due to the query duration exceeding the check's collection interval because we use the collection interval to calculate a lookback time window to control which statements we emit metrics for. 
In [this PR](https://github.com/DataDog/integrations-core/commit/5bc51aee49a5dd134dbc5093c7f03e89e2339b28#diff-8e277bbbdb25fa9b90a692e922e3f7e352ffa0d8ab4114441766e811b768f3bfL51-R51), we changed how we bound this lookback time into the actual query text, and we didn't bring along a corresponding multiplier which scaled the connection interval by 2 to increase the lookback window. This restores that logic in the new parameter binding.
A [customer reported query …
=> Multiply the lookback interval time by 2.

datadog_checks_dev/CHANGELOG.md, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/jmx_metrics.py, tomcat/CHANGELOG.md, tomcat/README.md, tomcat/datadog_checks/tomcat/data/metrics.yaml
This is a follow up to issue https://github.com/DataDog/integrations-core/issues/10233.
It has been suggested we support both `Catalina` and `Tomcat` bean names for JMX. 
This would cover both cases of standalone and embedded Tomcat versions (Spring Boot).
It seems the JMX fetch project supports `domain` and also `domain_regex`.
I am using `domain_regex` here to support both cases.
Regex seems to be supported since 2015: https://github.com/DataDog/jmxfetch/pull/57.
Spring Boot is widely popular and supporting these useful Tomcat metrics out of the box is a great advantage.
It is not as simple to rename the metric if people are using the agent with Kubernetes, as it requires mounting a file and adding a JVM argument to each pod where this is required.
The PR build is failing as it seems …
=> Tomcat: Make JMX metrics available on both standalone and embedded Tomcat versions

gitlab/README.md
When syncing tiles, the fact that the reference [30] is not present got flagged. It got in as part of #15085. Turns out the whole paragraph seems inapplicable to this integration (no `use_prometheus` here), so it probably ended up there as contamination with the rest of related PR's that we were working on simultaneously.
=> Drop erroneous readme paragraph

.gitlab-ci.yml
This PR updates the Slack message on integrations-core CI failure.
The Slack notification for failing CI is not very descriptive nor does it help fix CI issues.
=> Improve CI failure message

sqlserver/assets/configuration/spec.yaml, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example, sqlserver/datadog_checks/sqlserver/queries.py, sqlserver/hatch.toml
Now that we officially support SQL Server 2022, this adds the new linux image & 2022 to our test matrix
=> Add SQL Server 2022 to test matrix

.github/CODEOWNERS
This PR corrects the codeowner name for the openai and langchain integrations from `llm-obs` to `ml-observability`, as the Github team name was changed recently.
=> Correct codeowner name for openai/langchain integrations

strimzi/README.md
* References the container name in the cluster operator annotation, which is the relevant container identifier (`ad.datadoghq.com/<CONTAINER_IDENTIFIER>.checks`) to ensure the check is scheduled while the service account is not relevant
* Adds reference to the Kafka Consumer integration for a full "end-to-end" Kafka/ZK monitoring with relevant annotations
* Tabs the `user_operator` annotations so the `.yaml` is correct
* Removes the TLS listener on 9093 that adds un-necessary clutter in the example (we keep 9092 that is not tls-secured for the Kafka consumer check)
* Removes un-necessary Zookeeper annotations `key1` and `key2`
* Correction and completeness
=> [Strimzi doc] Kafka consumer + nits

ddev/CHANGELOG.md, ddev/src/ddev/utils/scripts/ci_matrix.py, tomcat/datadog_checks/tomcat/data/metrics.yaml
Triggers tests for integrations on PRs when `data/metrics.yaml` is modified.
Noticed tests were not being triggered on https://github.com/DataDog/integrations-core/pull/15761.
Manual testing shows that the tests get triggered. See https://github.com/DataDog/integrations-core/actions/runs/6260431555/job/16998471283?pr=15877 on https://github.com/DataDog/integrations-core/pull/15877/commits/7a91244cbf82194a8e9d6ba74fe13dfe88874be6.
=> Trigger tests on PRs for JMX metrics.yaml changes

datadog_checks_dev/CHANGELOG.md, datadog_checks_dev/pyproject.toml
Set upper-bound for pydantic version we support.
The latest release of pydantic (2.4) doesn't jive well with datamodel_code_generator, it seems. While we investigate further, we can unblock the CI with this.
=> Quick fix to unblock CI

postgres/CHANGELOG.md, postgres/datadog_checks/postgres/postgres.py
Customers will see this error frequently if they have a lot of tables in their db and because it is a `warning` level log, it will pollute agent logs even if log_level is set to `info`
Since there is nothing customers can really do about this, it makes more sense to set it as `debug` level log
Customer support tickets have reported the following:
> TLDR: A customer set up relation metrics and due to the 300 relation limit the agent spammed the agent log with error messages per relation it tried to collect above this limit. The customer was ingesting logs so they were alerted to this error only because of the $$ increase it cost them to ingest the agent log.
Since it makes no sense to log this outside of the `DEBUG` context, I think it makes sense to lower the log level from `warning` to …
=> Set lower log level for relations metrics truncated

container/metadata.csv
Document the new `container.memory.{page_faults,major_page_faults}` metrics implemented by DataDog/datadog-agent#19457.
=> Add page faults metrics in the generic container check doc

win32_event_log/CHANGELOG.md, win32_event_log/README.md, win32_event_log/assets/configuration/spec.yaml, win32_event_log/datadog_checks/win32_event_log/check.py, win32_event_log/datadog_checks/win32_event_log/config_models/defaults.py, win32_event_log/datadog_checks/win32_event_log/config_models/shared.py, win32_event_log/datadog_checks/win32_event_log/data/conf.yaml.example, win32_event_log/tests/legacy/test_win32_integration.py, win32_event_log/tests/test_config.py
Add the `legacy_mode` option to the shared `init_config` configuration section.
Enable `legacy_mode: false` in `init_config` in the config example by default.
Set the option once in `init_config` rather than setting the option in every single instance.
https://datadoghq.atlassian.net/browse/WINA-265
=> Add `legacy_mode` option to init_config

postgres/CHANGELOG.md, postgres/datadog_checks/postgres/postgres.py, postgres/tests/test_pg_integration.py
Creates a condition to check whether the instance is a Postgres Aurora instance and prevents collection of metrics from `pg_stat_wal` and `pg_ls_waldir()` 
For PostgreSQL Aurora, our current code produces the following errors and is flooding the agent logs:
```
Error querying stat_wal_metrics: Function pg_stat_get_wal() is currently not supported for Aurora
Error querying wal_metrics: permission denied for function pg_ls_waldir
```
We're getting this error because for example, `pg_ls_waldir` is a filesystem function that is not supported by Postgres Aurora because of it being a managed service. The function is typically used to list the files in the WAL (write-ahead log) directory which is a part of Postgres’ replication and transaction log system. Since Aurora is a managed service, users …
=> Adding check for Postgres Aurora to not collect STAT_WAL_METRICS & WAL_FILE_METRICS

postgres/CHANGELOG.md, postgres/assets/configuration/spec.yaml, postgres/datadog_checks/postgres/config.py, postgres/datadog_checks/postgres/config_models/defaults.py, postgres/datadog_checks/postgres/data/conf.yaml.example
This updates the default config for `ssl` from `disable` to `allow`. The reason is that postgres 15 on RDS is [switching the default for `force_ssl` to `true`](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL.Concepts.General.SSL.html#PostgreSQL.Concepts.General.SSL.Requiring). Setting the default to `allow` means that a failure to connect without ssl will trigger an attempt to connect using ssl. 
We could also consider going a bit further and setting the default to `prefer` which means ssl would be used first but I went with a more conservative approach that's closer to our current value (prefer non-ssl and switch to ssl on failure). 
Help make for a smoother transition for RDS Postgres users when they upgrade to postgres 15.
=> Update default configuration for ssl to 'allow'

argocd/README.md
The ArgoCD example for clashing tag names was missing a comma - this PR adds it.
The example annotation does not work without the comma.
=> Documentation - Fix ArgoCD clashing tag names example

sqlserver/hatch.toml, sqlserver/tests/test_activity.py, sqlserver/tests/test_connection.py, sqlserver/tests/test_e2e.py, sqlserver/tests/test_integration.py, sqlserver/tests/test_metadata.py, sqlserver/tests/test_statements.py, sqlserver/tests/test_stored_procedures.py
Some tests were taking 10s to complete, which _could_ be due to us not setting low collection intervals everywhere. For example,  `test_get_available_query_metrics_columns` was taking 10+ seconds but it simply runs a query to check that columns are populated in a cache:
```
Time Delta: 10.044208 seconds - 2023-09-28T19:21:00.3845525Z tests/test_statements.py::test_get_available_query_metrics_columns[expected_columns0-available_columns0] PASSED [ 68%]
Time Delta: 10.030386 seconds - 2023-09-28T19:08:10.5933882Z tests/test_statements.py::test_get_available_query_metrics_columns[expected_columns0-available_columns0] PASSED [ 68%]
```
I've seen this before in our postgres tests when we add new jobs & its possible that is what is happening here. Currently sql server CI take 2+ hours to run, …
=> Try to make sqlserver tests run faster by setting low coll intervals for DBM jobs

datadog_checks_dev/CHANGELOG.md, datadog_checks_dev/datadog_checks/dev/tooling/commands/release/show/changes.py
Stops `ddev release show changes` from aborting when no changes have been found, so that it retains behavior that other commands rely upon.
[AITS-247](https://datadoghq.atlassian.net/browse/AITS-247)
Aborting causes the application to exit regardless of context, which is a problem when that breaks expectations of other commands that rely on invoking this command directly.
This was causing `release make all` to abort early as soon as an integration didn't have a change. This regression was introduced in #15378; we weren't aborting under that scenario before.
Longer term, I think we should try to avoid invoking commands from within any sort of minimally complex logic, and be careful with where we call functions that can exit the interpreter completely. We can leave this as it is for now …
=> Don't abort on `ddev release show changes` when no changes are found

sqlserver/metadata.csv
"Lookups" is not a valid metric metadata unit, and this is whats causing the production metrics issues. I switched this to be a valid unit.
=> Update "Lookups" unit to instead use "occurrence"

.ddqa/config.toml
The team key seems to be WINA:
https://a.cl.ly/rRumlPd7
Was getting a 403 trying to create qa cards for the windows agent team.
=> Fix windows agent team key

ddev/pyproject.toml
Excludes the autogenerated `_version.py` from being linted by `black`.
[Linting failures](https://github.com/DataDog/integrations-core/actions/runs/6396904435/job/17363734743) for ddev on CI.
This file is already in our repo-wide .gitignore; black is therefore [supposed to ignore it anyway](https://black.readthedocs.io/en/stable/usage_and_configuration/file_collection_and_discovery.html#gitignore) (possibly because the way hatch runs things?). It looks reasonable to exclude it explicitly.
=> Don't run `black` on autogenerated `_version.py` file

postgres/CHANGELOG.md, postgres/datadog_checks/postgres/connections.py, postgres/datadog_checks/postgres/metadata.py, postgres/datadog_checks/postgres/postgres.py, postgres/datadog_checks/postgres/statement_samples.py, postgres/datadog_checks/postgres/statements.py, postgres/datadog_checks/postgres/version_utils.py, postgres/tests/test_connections.py, postgres/tests/test_pg_integration.py, postgres/tests/test_statements.py, postgres/tests/test_unit.py
We are seeing main thread db being closed prematurely, causing check to error out. This PR gets rid of the persistent main thread db property and use `db` context manager to ensure a dedicated healthy main db connection is returned.
=> Establish a dedicated main db connection with heath check

mysql/tests/test_mysql.py, mysql/tests/test_query_activity.py, mysql/tests/test_statements.py
Some of these tests are hanging for long periods of time, due to the fact that we are enabling DBM jobs but not setting a low collection interval. This is a similar fix to the implementation we did in https://github.com/DataDog/integrations-core/pull/15928 for SQL Server CI, which improved the test time from 2 hours -> 30 min
=> Improve speed of mysql CI by setting lower coll intervals for DBM jobs

network/tests/test_integration.py
Remove system.net.conntrack.helper from linux test as it is removed since kernel 6.0-rc4
More details at https://www.spinics.net/lists/netfilter/msg60942.html. Introducing an optional metric based on kernel version is an overhead. Marking this as an optional metric will always make the test pass even if this metric is missing. The logic to check for conntrack metric is similar for rest of them as well, so the core conntrack metric collection logic is not compromised by removing one metric
=> Exclude system.net.conntrack.helper from linux test

sqlserver/CHANGELOG.md, sqlserver/datadog_checks/sqlserver/stored_procedures.py
Changes the stored procedure collection check to `run_sync=False` which was mistakenly set to True and merged as-is. This is blocking the rest of the SQLServer checks and causing intermittent telemetry collection. 
This:
Should actually be like this:
=> [SQLServer] - set run_sync to False

container/metadata.csv
Documents the new `container.memory.usage.peak` metric.
It was introduced here: https://github.com/DataDog/datadog-agent/pull/18716
https://github.com/DataDog/datadog-agent/pull/19615
=> Add "container.memory.usage.peak" metric

kafka_consumer/CHANGELOG.md, kafka_consumer/assets/configuration/spec.yaml, kafka_consumer/datadog_checks/kafka_consumer/__about__.py, kafka_consumer/datadog_checks/kafka_consumer/client.py, kafka_consumer/datadog_checks/kafka_consumer/config.py, kafka_consumer/datadog_checks/kafka_consumer/config_models/defaults.py, kafka_consumer/datadog_checks/kafka_consumer/config_models/instance.py, kafka_consumer/datadog_checks/kafka_consumer/data/conf.yaml.example, kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py, requirements-agent-release.txt
Port agent OOM kill fix to 7.48
https://github.com/DataDog/integrations-core/pull/15960
=> Port agent OOM kill fix to 7.48

kube_scheduler/CHANGELOG.md, kube_scheduler/datadog_checks/kube_scheduler/kube_scheduler.py, kube_scheduler/datadog_checks/kube_scheduler/sli_metrics.py, kube_scheduler/tests/fixtures/metrics_slis_1.27.3.txt, kube_scheduler/tests/test_sli_metrics.py
The kube scheduler SLI metrics are updated such that:
* The tag `name` is renamed to `sli_name` to avoid confusion with other tags
* Only metrics with type `healthz` are parsed with this metric
* Uses a `GET` request to probe for the `/metrics/slis` endpoint; initial `HEAD` request introduced in #15731 seems to be throwing a `403` preventing metrics from being collected
For consistency with other SLI metrics, the kube scheduler SLI metrics logic is updated to match the kube controller manager: #15914  
Would it make more sense to pull all the SLI metrics logic into a common file to avoid duplication across all kubernetes components?
=> Update tags and filter by type for kube scheduler SLI metrics

kube_apiserver_metrics/CHANGELOG.md, kube_apiserver_metrics/datadog_checks/kube_apiserver_metrics/kube_apiserver_metrics.py, kube_apiserver_metrics/metadata.csv, kube_apiserver_metrics/tests/fixtures/metrics_1.28.0.txt, kube_apiserver_metrics/tests/test_kube_apiserver_metrics_1_28.py
Add `etcd_requests_total` and `etcd_request_errors_total` new metrics for Kubernetes 1.28.
The unit tests for `etcd_request_errors_total` where manually implemented since it was not easy to trigger this metric.
We need to support new Kubernetes versions.
=> [kube_apiserver_metrics] Add `etcd_requests_total` and `etcd_request_errors_total` new metrics

mysql/CHANGELOG.md, mysql/datadog_checks/mysql/activity.py, mysql/datadog_checks/mysql/statements.py, postgres/CHANGELOG.md, postgres/datadog_checks/postgres/statement_samples.py, postgres/datadog_checks/postgres/statements.py, sqlserver/CHANGELOG.md, sqlserver/datadog_checks/sqlserver/activity.py, sqlserver/datadog_checks/sqlserver/statements.py
This PR reports sql obfuscation error when obfuscator fails to obfuscate input queries. This will help us understand the number of obfuscation errors happen right now prior to the obfuscator upgrade.
=> [DBMON-2989] report sql obfuscation error count

ddev/tests/cli/meta/scripts/conftest.py, ddev/tests/cli/meta/scripts/test_upgrade_python.py
Use a dummy repository to run the `upgrade_python` tests
- Stop relying on the current repo to make tests easier to write/maintain
- Needed for https://github.com/DataDog/integrations-core/pull/16000 and https://github.com/DataDog/integrations-core/pull/15997
=> Use a dummy repository to run the `upgrade_python` tests

rabbitmq/hatch.toml
Bump the `pika` version to 1.3.2
- Current version is 4 years old: https://pypi.org/project/pika/0.13.0/
- This version does not work well with python 3.11 in this PR: https://github.com/DataDog/integrations-core/pull/15997
Relates to https://datadoghq.atlassian.net/browse/AITS-277
=> Bump the `pika` version to 1.3.2 on py3

win32_event_log/CHANGELOG.md, win32_event_log/assets/configuration/spec.yaml, win32_event_log/datadog_checks/win32_event_log/config_models/defaults.py, win32_event_log/datadog_checks/win32_event_log/config_models/instance.py, win32_event_log/datadog_checks/win32_event_log/data/conf.yaml.example
Fix the `timeout` config option definition
- According to the doc mentioned in the code [here](https://github.com/DataDog/integrations-core/blob/9ad0a36fe91cc3728f8e2ce4d08a5f73a505e6ab/win32_event_log/datadog_checks/win32_event_log/check.py#L316-L318), this option is supposed to be a integer and in millisonds
- Spotted working on [this PR](https://github.com/DataDog/integrations-core/pull/15997) where I got this error: 
```
FAILED tests/test_check.py::test_sid - Exception: 
File "D:\a\integrations-core\integrations-core\datadog_checks_base\datadog_checks\base\checks\base.py", line 1235, in run
File "D:\a\integrations-core\integrations-core\win32_event_log\datadog_checks\win32_event_log\check.py", line 135, in check
for event in …
```
=> Fix the `timeout` config option definition

mapr/hatch.toml
Bump the `confluent_kafka` version to 2.2.0 on py3
- There's no wheel for the 1.7.0 version on py3.11, see [this job](https://github.com/DataDog/integrations-core/actions/runs/6534891548/job/17743392376?pr=15997)
- Needed for https://github.com/DataDog/integrations-core/pull/15997
Relaytes to https://datadoghq.atlassian.net/browse/AITS-277
=> Bump the `confluent_kafka` version to 2.2.0 on py3

win32_event_log/CHANGELOG.md, win32_event_log/assets/configuration/spec.yaml, win32_event_log/datadog_checks/win32_event_log/config_models/defaults.py, win32_event_log/datadog_checks/win32_event_log/data/conf.yaml.example
Set back the `timeout` option to seconds
- I updated this in my other PR: https://github.com/DataDog/integrations-core/pull/16017
- But I was wrong as this is converted [here](https://github.com/DataDog/integrations-core/blob/master/win32_event_log/datadog_checks/win32_event_log/config_models/validators.py#L24-L25)
Relates to https://datadoghq.atlassian.net/browse/AITS-277
=> Set back the `timeout` option to seconds

php_fpm/CHANGELOG.md, php_fpm/datadog_checks/php_fpm/php_fpm.py, php_fpm/tests/test_e2e.py, php_fpm/tests/test_php_fpm.py
Add a metric for how long it takes to load the FPM status page.
The status page requires a free FPM worker to load, so if the listen queue is backed up it can take a long time for the health check to work its way through the queue. It can be helpful to know about how long it takes to get from the end of the queue to the front.
=> Add metric for status page load duration

datadog_checks_dev/CHANGELOG.md, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/datadog_checks/{check_name}/__about__.py, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/datadog_checks/{check_name}/__about__.py, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/datadog_checks/{check_name}/__about__.py
Initial version in `__about__.py` is the same as the initial version in the `CHANGELOG.md`.
Found this while reviewing the nvidia triton PR
=> Align package version in integration template with changelog

hatch.toml, mkdocs.yml
Use `material.extensions.emoji.twemoji` instead of `materialx.emoji.twemoji`
- https://github.com/DataDog/integrations-core/actions/runs/6546603485/job/17777385830?pr=16030
```
Material emoji logic has been officially moved into mkdocs-material
version 9.4. Please use Material's 'material.extensions.emoji.twemoji'
as mkdocs_material_extensions is deprecated and will no longer be
supported moving forward. This is the last release.
File "/home/runner/.local/share/hatch/env/virtual/integrations-core/9U2N5cW6/docs/lib/python3.9/site-packages/materialx/emoji.py", line 106, in twemoji
return _patch_index(options)
File "/home/runner/.local/share/hatch/env/virtual/integrations-core/9U2N5cW6/docs/lib/python3.9/site-packages/materialx/emoji.py", line 59, in _deprecated_func
warnings.warn(
WARNING - …
```
=> Use `material.extensions.emoji.twemoji` instead of `materialx.emoji.twemoji`

datadog_checks_dev/CHANGELOG.md, datadog_checks_dev/datadog_checks/dev/tooling/commands/dep.py
Allow bumping the version of `pyodbc`
It's now safe to update it https://github.com/DataDog/integrations-core/pull/16021
Relates to https://datadoghq.atlassian.net/browse/AITS-277
=> Allow bumping the version of `pyodbc`

strimzi/assets/logs/strimzi.yaml, strimzi/assets/logs/strimzi_tests.yaml, tenable/assets/logs/tenable.yaml
Syncing integrations with logs-backend
Logs integrations in this repo are out of date with logs-backend. We also need to sync this as part of [LOGSC-509](https://datadoghq.atlassian.net/browse/LOGSC-509)
[LOGSC-509]: https://datadoghq.atlassian.net/browse/LOGSC-509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Sync integrations-core with logs-backend

datadog_checks_base/CHANGELOG.md, datadog_checks_base/datadog_checks/base/utils/db/utils.py, postgres/CHANGELOG.md, postgres/datadog_checks/postgres/postgres.py, postgres/datadog_checks/postgres/version_utils.py, postgres/tests/test_pg_integration.py, postgres/tests/test_pg_replication.py, postgres/tests/test_statements.py, postgres/tests/utils.py
This PR makes dbm async job cancel non-blocking to resolve error
```
an error occurred while calling check.Cancel(): timeout while calling check.Cancel()
```
=> Make dbm async job cancel non-blocking

elastic/hatch.toml
This PR adds support for Elasticsearch `8.8.2`. It also removes version `8.6.2`, since having one Elasticsearch 8 version is enough.
Use a newer Elasticsearch version that fixes some bugs found in previous ES8 version. This is one the main ones https://github.com/apache/lucene/pull/12072.
=> Add support for Elasticsearch 8.8.2

snowflake/CHANGELOG.md, snowflake/datadog_checks/snowflake/check.py, snowflake/tests/common.py, snowflake/tests/test_unit.py
It fixes a bug causing instance-specific configuration affecting all instances by avoiding modification of global variables.
A bug was found where instances with `aggregate_last_24_hours` set to `true` would still be seen to be using the `date_trunc` function in the query, which turned out to be because of other instances on the same Agent, with that setting set to `false`, were influencing global behavior.
[AGENT-10283](https://datadoghq.atlassian.net/browse/AGENT-10283)
[AGENT-10283]: https://datadoghq.atlassian.net/browse/AGENT-10283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Prevent `aggregate_last_24_hours` option from affecting global state

ddev/CHANGELOG.md, ddev/src/ddev/cli/meta/scripts/upgrade_python.py, ddev/tests/cli/meta/scripts/conftest.py, ddev/tests/cli/meta/scripts/test_upgrade_python.py
Improve the upgrade-python script to:
- Update the classifiers in the `pyproject.toml` files
- Update the classifiers in the `setup.py` files (if any)
- Update the CI files
- Update the ddev `pyproject.toml` file to bump the versions for ruff and black
- Update the template files for new integrations
- Warn the user if there's an override that the script can't handle automatically (I tried, I don't manage to have the right format for the output file, I don't know why. Feel free to let me know if you know why, but I did not want to waste too much time on this)
- Remind the user to update the documentation. I did not want to update it with the script as our documentation can be modified pretty often and this would make the script not working as expected. I prefer having a script warning …
=> Improve the upgrade-python script

datadog_checks_dev/CHANGELOG.md, datadog_checks_dev/datadog_checks/dev/tooling/commands/release/show/changes.py
Restores displaying pending changes for a release.
This got lost when switching to using the changelog as the source for changes (#15378). Just realized it while preparing a release for an integration.
=> Display changes on `ddev show changes` when found

ddev/tests/cli/meta/scripts/conftest.py, ddev/tests/cli/meta/scripts/test_upgrade_python.py
Remove hardcoded Python versions in the `test_upgrade_python` test file
- Remove code duplication and hardcoded values
- Make it easier to bump the versions if needed in the future
Relates to https://datadoghq.atlassian.net/browse/AITS-283
=> Remove hardcoded Python versions in the `test_upgrade_python` test file

.gitlab-ci.yml, .gitlab/validate-agent-build/validate_agent_build.py
Increase the timeout for the validate-agent-build job to 3 hours
I'm sorry, I do not have a better short-term solution. If you have one, please let me know.
The job timed out a couple of times: 
- https://gitlab.ddbuild.io/DataDog/integrations-core/-/jobs/351999212
- https://gitlab.ddbuild.io/DataDog/integrations-core/-/jobs/352000584
There was only one job left (a windows one)
=> Increase the timeout for the validate-agent-build job to 3 hours

ray/tests/common.py
Mark some `object_store` metrics optional
None of these metrics are exposed in this job: https://github.com/DataDog/integrations-core/actions/runs/6571259966/job/17850155794
```
FAILED tests/test_integration.py::test_check[worker] - AssertionError: Needed at least 1 candidates for 'ray.object_store.size.sum', got 0
Expected:
MetricStub(name='ray.object_store.size.sum', type=None, value=None, tags=None, hostname=None, device=None, flush_first_value=None)
Similar submitted:
Score   Most similar
0.79    MetricStub(name='ray.object_store.memory', type=0, value=0.0, tags=['Component:raylet', 'Location:SPILLED', 'NodeAddress:172.18.0.3', 'ObjectState:', 'SessionName:session_2023-10-19_00-32-47_834579_7', 'Version:2.6.1', 'WorkerId:', 'endpoint:http://localhost:8081'], hostname='', device=None, …
```
=> Mark some `object_store` metrics optional

ddev/CHANGELOG.md, ddev/src/ddev/cli/env/test.py
Fixes the field where platforms are obtained from environment data so that `ddev env test <check>` works as before when an environment is not specified.
Realized that E2E tests were not actually running on CI.
I chose to remove the walrus thingy from the conditional because I found it obfuscated a little bit the conditional on an already somewhat complex conditional.
Also, I haven't looked into whether any tests are covering this (I think that restoring E2E tests on CI is urgent enough to leave that for later).
=> Fix `ddev env test` so that tests run for all environments properly

datadog_checks_downloader/CHANGELOG.md
Our tooling should have done it, but it didn't.
Our release pipeline failed recently. While investigating it we noticed that the changelog for the downloader package hasn't been updated with the last  2 releases of the Agent. I'm fixing this manually here, there's a jira ticket to track the bug.
=> Manually add agent versions to releases.

cacti/CHANGELOG.md, cacti/pyproject.toml, datadog_checks_base/CHANGELOG.md, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, mysql/CHANGELOG.md, mysql/hatch.toml, mysql/pyproject.toml, proxysql/CHANGELOG.md, proxysql/pyproject.toml, singlestore/CHANGELOG.md, singlestore/hatch.toml, singlestore/pyproject.toml
Bump the `pymysql` version to 1.1.0 on Python 3
- This version was pinned in [this PR](https://github.com/DataDog/integrations-core/pull/12612) because of a bug in the version 1.0.2
- The bug got fixed in 1.0.3
- The version we use does not officially support Python 3.11, so I'd like to bump it to 1.1.0 which does
Relates to https://datadoghq.atlassian.net/browse/AITS-277
=> Bump the `pymysql` version to 1.1.0 on Python 3

ddev/CHANGELOG.md, ddev/src/ddev/plugin/external/hatch/environment_collector.py
Fixes the way we include the `src` folder for `ddev`.
I realized we were only measuring coverage under `tests` for ddev, meaning we lost visibility onto our test coverage for the actual code.
=> Fix coverage for ddev's src

ray/tests/common.py
Mark some worker metrics optional
None of these metrics are exposed in this job: https://github.com/DataDog/integrations-core/actions/runs/6580779512/job/17879563864
```
FAILED tests/test_integration.py::test_check[worker] - AssertionError: Needed at least 1 candidates for 'ray.worker.register_time.sum', got 0
Expected:
MetricStub(name='ray.worker.register_time.sum', type=None, value=None, tags=None, hostname=None, device=None, flush_first_value=None)
Similar submitted:
Score   Most similar
0.60    MetricStub(name='ray.process.start_time', type=0, value=1697753917.95, tags=['endpoint:http://localhost:8081'], hostname='', device=None, flush_first_value=False)
0.55    MetricStub(name='ray.process.resident_memory', type=0, value=111812608.0, tags=['endpoint:http://localhost:8081'], …
```
=> Mark some `worker` metrics optional

datadog_checks_base/CHANGELOG.md, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, ibm_i/CHANGELOG.md, ibm_i/pyproject.toml, sqlserver/CHANGELOG.md, sqlserver/pyproject.toml
Bump the `pyodbc` version to 5.0.1
- I bumped the version for both py2 and py3 [here](https://github.com/DataDog/integrations-core/pull/16021), but turns out we could directly bump it to 5.0.1. They dropped py2 support with version 5
- Also I missed that these two integrations do not support py2 anymore 🙈 
- We need to keep the `python_version > '3.0'` specifier because otherwise this library is installed with Python 2 on Agent 6 and we don't need it there (and can't in fact)
- Relates to https://datadoghq.atlassian.net/browse/AITS-277
=> Bump the `pyodbc` version to 5.0.1

ecs_fargate/CHANGELOG.md, ecs_fargate/datadog_checks/ecs_fargate/ecs_fargate.py, ecs_fargate/metadata.csv, ecs_fargate/tests/conftest.py
We want to provide I/O metrics to Windows ECS users by using `Task metadata`.
The call to the `/stats` endpoint will return two I/O related sections:
* `blkio_stats` for Linux.
* `storage_stats` for Windows.
When one is set, the other one is not.
On a Windows task:
```
"blkio_stats": {
"io_service_bytes_recursive": null,
"io_serviced_recursive": null,
"io_queue_recursive": null,
"io_service_time_recursive": null,
"io_wait_time_recursive": null,
"io_merged_recursive": null,
"io_time_recursive": null,
"sectors_recursive": null
},
"num_procs": 2,
"storage_stats": {
"read_count_normalized": 95145,
"read_size_bytes": 709917184,
"write_count_normalized": 217642,
"write_size_bytes": 1126764544
},
```
On a Linux task:
```
"blkio_stats": {
"io_service_bytes_recursive": [
{
"major": 202,
"minor": …
```
=> [ecs_fargate] Add storage_stats support for Windows ECS Fargate

postgres/CHANGELOG.md
Changes in the config validation made `true` an invalid value for `ssl` in the postgres integration. In order to surface this change a little better, this updates the CHANGELOG for 7.48.0 to describe the change and advise users to replace `ssl: true` with `ssl: require`.
=> Clarify deprecation of ssl: true in CHANGELOG

clickhouse/tests/conftest.py
Add a ping to clickhouse in the e2e tests setup
The env is a bit flaky: https://github.com/DataDog/integrations-core/actions/runs/6608937843/job/17948410687
```
__________________________________ test_check __________________________________
tests/test_clickhouse.py:17: in test_check
dd_run_check(check)
../datadog_checks_dev/datadog_checks/dev/plugin/pytest.py:259: in run_check
raise Exception('\n'.join(exc_lines))
E   Exception: 
E     File "/home/runner/.local/share/hatch/env/virtual/datadog-clickhouse/KY25C-l6/py3.9-18/lib/python3.9/site-packages/datadog_checks/base/checks/base.py", line 1129, in run
E       self.check(instance)
E     File "/home/runner/work/integrations-core/integrations-core/clickhouse/datadog_checks/clickhouse/clickhouse.py", …
```
=> Add a ping to clickhouse in the e2e tests setup

snmp/CHANGELOG.md, snmp/assets/configuration/spec.yaml, snmp/datadog_checks/snmp/data/conf.yaml.example
Deprecate init_config.profiles
Deprecate init_config.profiles in favour of other profiles sources (RC, downloaded, yaml profiles folder)
=> Deprecate init_config.profiles

postgres/CHANGELOG.md, postgres/datadog_checks/postgres/config.py
Add `obfuscation_mode` config option to allow enabling obfuscation with `go-sqllexer`. This config option is hidden to end user on purpose as we are testing and finalizing the new obfuscation implementation witg `go-sqllexer` pkg.
=> [DBMON-2461] Add obfuscation_mode config option to allow enabling obfuscation with go-sqllexer

ddev/CHANGELOG.md, ddev/src/ddev/cli/meta/scripts/upgrade_python.py, ddev/tests/cli/meta/scripts/conftest.py, ddev/tests/cli/meta/scripts/test_upgrade_python.py
Bump the Python version in the dependency provider when bumping the Python version
We missed it because it has no `hatch` file
=> Bump the Python version in the dependency provider when bumping the Python version

mysql/CHANGELOG.md, mysql/datadog_checks/mysql/mysql.py, mysql/pyproject.toml, mysql/tests/test_mysql.py, mysql/tests/variables.py
This PR starts emitting mysql metrics queries operation time.
Emitting the metrics queries operation time will help us understand how long each metrics query take. When troubleshooting long running integration checks, query level operation time will provide more insights into delays caused by particular metric queries.
=> [DBMON-3030] Report metrics query operation time

activemq/manifest.json, activemq_xml/manifest.json, hivemq/manifest.json, ibm_mq/manifest.json, kafka/manifest.json, kafka_consumer/manifest.json, pulsar/manifest.json, rabbitmq/manifest.json
Renaming messaging category to message queues based on feedback
=>  Renaming integration category: messaging -> message queues

kubernetes/assets/dashboards/kubernetes_nodes.json
Update the Kubernetes Node Overview dashboard to the new responsive-grid layout.
We want our dashboards to be up-to-date in term of dashboard capabilities.
Deployed to `production`, check `Kubernetes Nodes Overview (Edwin MSL conversion)` dashboard.
=> [kubernetes] Update the Kubernetes Node Overview dashboard to the new responsive-grid layout

sqlserver/CHANGELOG.md, sqlserver/datadog_checks/sqlserver/sqlserver.py, sqlserver/tests/test_integration.py
Add type cast to ensure `dbm_enabled` is a boolean. This was to fix issue when customer put `dbm: "true"|"false"` in yml config.
=> safeguard to ensure dbm_enabled is a boolean

postgres/CHANGELOG.md, postgres/datadog_checks/postgres/postgres.py, postgres/tests/test_discovery.py, postgres/tests/test_statements.py
This PR fixes issue relates to not collecting dynamic relation metrics for auto-discovered databases. One side effect of this issue is that the `table_size` of auto-discovered tables are not populated in DBM Schema tab. 
After fix:
=> [DBMON-3050] Collect dynamic relation metrics for autodiscovered databases

cisco_aci/CHANGELOG.md, cisco_aci/pyproject.toml, datadog_checks_base/CHANGELOG.md, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/pyproject.toml, http_check/CHANGELOG.md, http_check/pyproject.toml, mysql/CHANGELOG.md, mysql/pyproject.toml, tls/CHANGELOG.md, tls/pyproject.toml
Bump the `cryptography` version to 41.0.5
- [pyopenssl](https://pypi.org/project/pyOpenSSL/23.3.0/) was released earlier today
- This version requires `cryptography>=41.0.5` : `pyopenssl 23.3.0 has requirement cryptography<42,>=41.0.5, but you have cryptography 41.0.4.`
- The agent is broken on master and on the release branch 
I'll backport this patch to the release branch
=> Bump the `cryptography` version to 41.0.5

cisco_aci/CHANGELOG.md, cisco_aci/pyproject.toml, datadog_checks_base/CHANGELOG.md, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/pyproject.toml, http_check/CHANGELOG.md, http_check/pyproject.toml, mysql/CHANGELOG.md, mysql/pyproject.toml, tls/CHANGELOG.md, tls/pyproject.toml
Bump the cryptography version to 41.0.5
Backport of https://github.com/DataDog/integrations-core/pull/16083
[DBMON-2915]: https://datadoghq.atlassian.net/browse/DBMON-2915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bump the cryptography version to 41.0.5

ddev/tests/cli/release/test_changelog.py
We need to ignore any actual contents of a specific folder in the repo
This is a follow-on of https://github.com/DataDog/integrations-core/pull/15983, an unreleased feature. So no separate changelog needed for this.
=> Fix bug in test fixture

kafka/assets/dashboards/kafka_dashboard.json
Fix some metric names in the dashboard
`kafka.consumer.lag` and `kafka.consumer.offset` are from a custom integration. The OOTB one has `kafka.consumer_lag` and `kafka.consumer_offset`
=> Fix some metric names in the dashboard

kafka_consumer/CHANGELOG.md, kafka_consumer/changelog.d/15951.fixed
https://github.com/DataDog/integrations-core/pull/15951 was opened before the changelog migration and kept the old format.
=> Fix the changelog

datadog_checks_base/changelog.d/16089.fixed, datadog_checks_base/datadog_checks/base/stubs/datadog_agent.py, datadog_checks_base/tests/base/checks/test_agent_check.py, datadog_checks_base/tests/stubs/test_datadog_agent.py
Add the ability to assert the `external_tags` when running tests
The Platform integrations team uses them and would like to have a way to assert them without mocking the function.
- I'll update the ambari tests to use this to avoid issues with the changelog [in another PR](https://github.com/DataDog/integrations-core/pull/16091)
- Relates to https://datadoghq.atlassian.net/browse/AITS-287
=> Add the ability to assert the `external_tags` when running tests

ambari/tests/test_ambari.py
Update the test that assert external tags
Use https://github.com/DataDog/integrations-core/pull/16089
Relates to https://datadoghq.atlassian.net/browse/AITS-287
=> Update the test that assert external tags

datadog_checks_base/changelog.d/16105.fixed, datadog_checks_base/datadog_checks/base/stubs/datadog_agent.py, datadog_checks_base/tests/stubs/test_datadog_agent.py
Do not verify the tags order by default when testing the external tags
Tags order does not matter in general.
Relates to https://datadoghq.atlassian.net/browse/AITS-287
=> Do not verify the tags order by default when testing the external tags

linkerd/manifest.json, linkerd/metadata.csv
With this change, either linkerd.openmetrics.health or linkerd.prometheus.health should cause the integration tile to show as healthy.
https://datadog.zendesk.com/agent/tickets/1388328
https://dd.slack.com/archives/CB9QX75H6/p1697841212331629
=> Update manifest.json to include openmetrics version of health check

kafka_consumer/hatch.toml, kafka_consumer/tests/common.py, kafka_consumer/tests/docker/scripts/install_librdkafka.bash
Manually install the right version of librdkafka if needed
Context: 
- The kafka_consumer integration uses confluent-kafka which in turns relies on librdkafka
- We use a manually built version of librdkafka to support kerberos authentication on linux
- librdkafka is built directly on the agent with a patch in omnibus: https://github.com/DataDog/datadog-agent/blob/bf082c7f571b5e7770be5257cbc362377d8c3973/omnibus/config/software/librdkafka.rb#L4
Problem:
- In our case you can not have confluent-kafka 2.3.0 with librdkafka 2.2.0 for instance
- When we bump the version of confluent-kafka, we need to bump the librdkafka version too on the agent
- At the moment when you bump this version the kerberos e2e tests fail because the agent that is used still does not have the right librdkafka version …
=> Manually install the right version of librdkafka if needed

ddev/changelog.d/16112.fixed, ddev/src/ddev/cli/dep.py
Stop automatically upgrading `lxml` when bumping the dependencies
https://github.com/DataDog/integrations-core/pull/16080
=> Stop automatically upgrading `lxml` when bumping the dependencies

kubernetes/assets/dashboards/kubernetes_deployments.json
Update the Kubernetes Deployments Overview dashboard to the new responsive-grid layout.
We want our dashboards to be up-to-date in term of dashboard capabilities.
Deployed to `production`, check `Kubernetes Deployments Overview (cloned) (cloned)` dashboard.
=> [kubernetes] Update the Kubernetes Deployments Overview dashboard to the new responsive-grid layout

ddev/changelog.d/16123.fixed, ddev/src/ddev/e2e/agent/docker.py
The `_run_command` method does not capture output and therefore it was decoding a None value, now we have even more output
=> Properly show extra output for failed Docker Agent E2E

sqlserver/CHANGELOG.md, sqlserver/changelog.d/16114.fixed, sqlserver/datadog_checks/sqlserver/connection.py, sqlserver/datadog_checks/sqlserver/sqlserver.py, sqlserver/tests/test_integration.py, sqlserver/tests/test_unit.py
The SQLServer integration was tagging the `sqlserver.can_connect` metric with different `host` tags when it was emitting `OK` vs `CRITICAL`. This fixes the issue by always using the same `host` tag and adding the connection string host via the `connection_host` tag. 
The overall result is:
- `host` will be tagged with the agent host
- `sqlserver_host` will be tagged with the resolved hostname (i.e. reported_hostname or connection host without the port)
- `connection_host` will always be exactly what the user put in the `host` value in their integration config.
=> [SQLServer] - Ensure we have the same host tag for can_connect metric

sqlserver/changelog.d/16125.added, sqlserver/datadog_checks/sqlserver/sqlserver.py
Add `obfuscation_mode` config option to allow enabling obfuscation with go-sqllexer. This config option is hidden to end user on purpose as we are testing and finalizing the new obfuscation implementation witg go-sqllexer pkg.
Add this "hidden" config option gives us a way to work with customer to enable the new obfuscation behavior if needed.
=> [DBMON-3053] Add obfuscation_mode config option to allow enabling obfuscation with go-sqllexer

win32_event_log/README.md
Switch the order of the Events and Logs tabs on the Event Log integration page. Even though customers can send data both as event and logs, we want to show Logs first.
https://datadoghq.atlassian.net/browse/WINA-34
=> switch logs and events tabs

databricks/README.md
DD_LOGS_ENABLED is not supported with the install script. This does enables the log agent by editing the datadog.yaml directly.
=> Update docs for logs in databricks

kafka/assets/dashboards/kafka_dashboard.json
Update the kafka dashboard:
- Use `kafka.replication.under_replicated_partitions` instead of `dd.kafka.replication.under_replicated_partitions`
- Drop the `kafka_node` template variable.
- `dd.kafka.replication.under_replicated_partitions` is an intenral metric
- `kafka_node` has always been in the dashboard/screenboard. I don't know where it came exactly from but we do not have it by default anymore so it's safe to drop it I think
=> Update the kafka dashboard

ambari/changelog.d/16139.changed, ambari/pyproject.toml
Bump the minimum base check version to 34.1.2
Following https://github.com/DataDog/integrations-core/pull/16091, we now use https://github.com/DataDog/integrations-core/pull/16089 that's released with https://github.com/DataDog/integrations-core/pull/16137
=> Bump the minimum base check version to 34.1.2

clickhouse/tests/conftest.py
Add more attempts to the ping clickhouse condition when setting up the e2e environment
In https://github.com/DataDog/integrations-core/pull/16067 I added a condition to ping clickhouse. However there was no retries to this particular condition and the e2e env was shutdown as a whole if clickhouse is not reachable. `WaitFor` allows us to retry several times this specific condition.
Example on master: https://github.com/DataDog/integrations-core/actions/runs/6732626133/job/18299747619
https://datadoghq.atlassian.net/browse/AI-3623
=> Add more attempts to the ping clickhouse condition when setting up the e2e environment

datadog_cluster_agent/assets/dashboards/datadog_cluster_agent_overview.json
Adds the widgets from #15796 back to the Datadog Cluster Agent dashboard.
These changes were removed from the main branch by accident when new widgets were added to the dashboard.
=> Add admission controller lib injection widgets back to cluster agent dashboard

ddev/changelog.d/16144.fixed, ddev/src/ddev/cli/validate/ci.py, ddev/tests/cli/validate/test_ci.py
Do not validate the codecov file in marketplace when running the `validate ci` command
They do not have this file, but we should still validate the matrix.
=> Do not validate the codecov file in marketplace when running the `validate ci` command

datadog_checks_base/changelog.d/16012.added, datadog_checks_base/datadog_checks/base/errors.py
Add new `SkipInstanceError` exception to be raised by a check to indicate it wants to skip the provided configuration. Used in the win32_event_log check https://github.com/DataDog/integrations-core/pull/16108 to switch between the Python and Go versions of the check based on the check configuration version.
See related agent PR https://github.com/DataDog/datadog-agent/pull/20114
To enable using the Go check as the new default implementation, and require setting a configuration option to use the previous version.
https://datadoghq.atlassian.net/browse/WINA-475
=> Add exception to skip instance configurations

ddev/changelog.d/16155.fixed, ddev/src/ddev/cli/dep.py
Add `oracledb` to the ignored dependencies when we bump them before a release
We are facing issues with the verison of odpi that is loaded. 
[This card](https://datadoghq.atlassian.net/browse/AI-3442) tracks the issue
=> Add `oracledb` to the ignored dependencies when we bump them before a release

postgres/CHANGELOG.md, postgres/changelog.d/16146.fixed, postgres/datadog_checks/postgres/postgres.py
Note: **this is something we are going to fix in our backend first, to prevent customers from being affected by this issue on 7.48**. 
This PR fixes a bug, which was introduced in the 7.48 version of the postgres agent that resulted in multiple `db` tags being applied to all metrics generated by the integration. For example, see `postgresql.queries.count` after upgrading to 7.48:
... downgrading by to 7.47 fixes the issue 
&& finally, this fix resolves the issue:
=> Database instance metadata payloads should not contain duplicate `db` tags

http_check/assets/configuration/spec.yaml, http_check/changelog.d/16163.fixed, http_check/datadog_checks/http_check/config_models/defaults.py, http_check/datadog_checks/http_check/config_models/instance.py, http_check/datadog_checks/http_check/data/conf.yaml.example, http_check/tests/test_http_integration.py
It makes `http_check` accept `integer` as a valid type for the `http_response_status_code` option.
#16008.
The Pydantic update made types stricter, which is affecting users of the `http_check` who might have been setting `http_response_status_code` to a single code. Since YAML has implicit typing, it's not necessarily obvious for everyone that quotes might be necessary for something to be interpreted as a string.
=> Allow to use an integer for the expected status code in the config

datadog_checks_base/changelog.d/16080.fixed, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, ibm_was/changelog.d/16080.fixed, ibm_was/pyproject.toml, sqlserver/changelog.d/16080.fixed, sqlserver/pyproject.toml
This downgrades the `lxml` dependency to v4.9.2.
We are seeing the Agent fail to load the `sqlserver` check in v7.48, only on arm64 architectures. We tracked this down to a failure to load the `lxml` Python library. Looking at the `lxml` release history, [they made some changes to the Cython version used](https://pypi.org/project/lxml/4.9.3/), which sounds like a likely cause of architecture incompatibilities.
I successfully built and tested an agent with the `lxml` dependency downgraded to 4.9.2 on arm64, so this will allow the check to properly load for customers.
We will look into fixing the root issue as a followup so that we can get back to the latest released version of `lxml` (4.93). I'll also open an issue on their repo to see if this is a known issue. In the meantime, I think we …
=> Downgrade lxml version to fix DBMON-3047

ddev/changelog.d/16157.fixed, ddev/pyproject.toml, ddev/src/ddev/e2e/agent/docker.py, ddev/tests/e2e/agent/test_docker.py
Add a retry mechanism when pulling the agent docker image
Sometimes we do not manage to get the image and we fail the tests: https://github.com/DataDog/integrations-core/actions/runs/6772328879/job/18404845840#step:15:645
https://datadoghq.atlassian.net/browse/AI-3635
=> Add a retry mechanism when pulling the agent docker image

containerd/metadata.csv
PR [#16659](https://github.com/DataDog/datadog-agent/pull/16659) renamed `containerd.mem.private_working_set` to `containerd.mem.working_set`. It is now available for both Linux and windows. 
This PR updates the metadata.csv so the documentation can be up to date.
=> Update containerd working_set metric

sqlserver/README.md
Update adoprovider parameter to use MSOLEDBSQL19 instead of MSOLEDBSQL.
Microsoft OLE DB Driver for SQL Server 19 is now the default download on Microsoft's [Microsoft ODBC Driver](https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server) page, meaning that without this change Datadog's SQL Server integration will always fail with an error "Provider cannot be found. It may not be properly installed". This follows the same changes made to spec.yaml and conf.yaml.example in https://github.com/DataDog/integrations-core/pull/12916
=> [SQL Server] Update MSOLEDBSQL provider details

openstack_controller/manifest.json
Reverts dashboard ID change (from https://github.com/DataDog/integrations-core/pull/15918) to ensure a smooth transition for those using the current dashboard. This has no effects on the UI
=> Revert dashboard ID change

langchain/assets/monitors/request_duration.json
This PR fixes the langchain integration's recommended monitor for request latency. Previously it was querying `system.load` which was incorrect, this was fixed by querying the correct `langchain.request.duration` metric.
=> Use correct query for langchain request latency monitor

sqlserver/changelog.d/16136.added, sqlserver/datadog_checks/sqlserver/const.py, sqlserver/tests/common.py, sqlserver/tests/conftest.py, sqlserver/tests/test_metrics.py
This PR adds dedicated unit test `test_metrics` to independently assert (almost) every configurable SQLServer metrics with expected tags. 
We will NOT remove existing unit tests for now until we are comfortable that the new tests can fully replacing what we had in `test_e2e` and `test_integration`.
Previously, we rely on (sort of) e2e tests to assert SQLServer metrics, and often without asserting expected tags. This is not only leaving gaps in test coverage, but also makes adding/removing metrics hard without proper unit tests to specifically assert the changes. This PR is to create dedicated tests for each and every metrics that we collect.
=> [DBMON-3054] Add unit tests to assert every configurable metrics collection

windows_service/changelog.d/16120.fixed, windows_service/datadog_checks/windows_service/windows_service.py, windows_service/tests/common.py, windows_service/tests/conftest.py, windows_service/tests/test_windows_service.py
Restores functionality provided by https://github.com/DataDog/integrations-core/pull/4503
Adds a comment and a test so we don't unintentionally remove it again.
Unintentionally removed this in https://github.com/DataDog/integrations-core/pull/12940
https://datadoghq.atlassian.net/browse/AGENT-10543
The original PR reverse sorted the names, but did so case sensitively so it would fix the issue for configs like
```
services:
- dfs
- dfsr
```
but not for configs like
```
services:
- Dfs
- DFSR
```
This PR sorts on the length instead, so longer/more specific names are checked first, regardless of letter case.
=> Handle prefix patterns by sorting

openstack_controller/assets/configuration/spec.yaml, openstack_controller/assets/service_checks.json, openstack_controller/changelog.d/16186.added, openstack_controller/datadog_checks/openstack_controller/api/api_rest.py, openstack_controller/datadog_checks/openstack_controller/api/api_sdk.py, openstack_controller/datadog_checks/openstack_controller/components/component.py, openstack_controller/datadog_checks/openstack_controller/components/image.py, openstack_controller/datadog_checks/openstack_controller/config_models/instance.py, openstack_controller/datadog_checks/openstack_controller/metrics.py, openstack_controller/datadog_checks/openstack_controller/openstack_controller.py, openstack_controller/metadata.csv, openstack_controller/tests/conftest.py, openstack_controller/tests/docker/docker-compose.yaml, openstack_controller/tests/docker/etc/caddy/glance/Caddyfile, openstack_controller/tests/docker/fixtures/image/v2/images/get.json, openstack_controller/tests/fixtures/GET/image/response.json, openstack_controller/tests/fixtures/GET/image/v2/images/response.json, openstack_controller/tests/fixtures/POST/identity/v3/auth/tokens/1e6e233e637d4d55a50a62b63398ad15.json, openstack_controller/tests/fixtures/POST/identity/v3/auth/tokens/6e39099cccde4f809b003d9e0dd09304.json, openstack_controller/tests/metrics.py, openstack_controller/tests/test_unit_glance.py
Adds support for the glance component in openstack, adding a service check, response time metric, and image count metric.
=> [PLINT-245] Add support for glance component 

openai/manifest.json
Fixes no-data issue for openai web usage metrics (shared tile with openai apm).
=> Update metric to check for openai web usage

jmeter/README.md
Brings JMeter's Readme up to date. The new content is copied over from https://github.com/DataDog/jmeter-datadog-backend-listener/blob/e17d84e708c23969115eef2f52a0e10a6aa272ef/README.md
This is what actually gets displayed in [our docs](https://docs.datadoghq.com/integrations/jmeter/), but it is not completely up to date and doesn't include proper installation and configuration instructions. This is intended to remediate that.
=> Update JMeter readme

kubelet/changelog.d/16192.fixed, kubelet/datadog_checks/kubelet/common.py, kubelet/datadog_checks/kubelet/kubelet.py, kubelet/datadog_checks/kubelet/probes.py, kubelet/datadog_checks/kubelet/prometheus.py
centralize the `get_prometheus_url()` function call in the kubelet check.
Wait the `super()` function are call before trying to log a warning with `self.log`
Fixes: CONTINT-3443
* Send the warning to the correct logger.
* Simplify code
This PR is a follow up of https://github.com/DataDog/integrations-core/pull/16187
=> [CONTINT-3443] fix(kubelet): centralize `get_prometheus_url` call

nvidia_triton/manifest.json
Adds the source_type_id of this integration to the manifest (note it matches the one that was autogenerated for it during its staging sync). 
This should be a no-op, but its in the perfect case for me to test out some new functionality we're introducing to APW.
=> Add source_type_id to nvidia_triton

.ddqa/config.toml
- Remove Julia from our exclusion because she's not in our GitHub team anymore
- Add `team/<TEAM_NAME>` as a `github_labels` to all the teams
This will allow us to automatically assign QA cards to the right teams. This label is not yet used in this repository, I'll work on that during the hackathon.
=> Add team labels to the DDQA config

sqlserver/changelog.d/16207.changed, sqlserver/datadog_checks/sqlserver/sqlserver.py, sqlserver/tests/test_integration.py
This change makes sure that the check's `resolved_hostname` always represents the database instance. The previous behavior of the `resolved_hostname` property was to use the agent hostname as the `host` when dbm was disabled. This caused issues when, with agent 7.48.0, we started sending `database_instance` metadata. With the `agent_hostname` being used instance of each instance's host value, agents with multiple databases being monitored would end up creating and clobbering the same `database_instance` which, in turn, caused tag interference between database instances monitored by the same agent. 
Very importantly, that problem surfaced the broken experience when dbm is disabled in regards to the host used on integration metrics: instead of having the sqlserver metrics tagged by the …
=> INCIDENT-23437 Always resolve hostname regardless of whether is dbm enabled or not

postgres/changelog.d/16199.changed, postgres/datadog_checks/postgres/postgres.py, postgres/tests/test_pg_integration.py, postgres/tests/test_unit.py
This change makes sure that the check's `resolved_hostname` always represents the database instance. The previous behavior of the `resolved_hostname` property was to use the agent hostname as the `host` when dbm was disabled or `disable_generic_tags` was enabled. This caused issues when, with agent 7.48.0, we started sending `database_instance` metadata. With the `agent_hostname` being used instance of each instance's host value, agents with multiple databases being monitored would end up creating and clobbering the same `database_instance` which, in turn, caused tag interference between database instances monitored by the same agent. 
Very importantly, that problem surfaced the broken experience when dbm is disabled in regards to the host used on integration metrics: instead of having …
=> INCIDENT-23437 Always resolve hostname regardless or dbm or generic tags enabled or not

postgres/tests/test_pg_integration.py
This PR makes `test_snapshot_xmin` less flaky by
- skip asserting the `snapshot_xmin/xmax` exact value
- assert `snapshot_xmin_xmin/xmax` value is larger than baseline value
=> make test_snapshot_xmin less flaky

openai/README.md
This PR adds a note to the openai integration README, clarifying which metrics will be collected based on the setup method (APM vs Web API key).
The OpenAI integration involves two separate components, which provide two different sets of metrics:
1. APM: all `openai.request*`, `openai.tokens.*`, `openai.organization.*`, `openai.ratelimit*` metrics
2. Web API key: `openai.api.usage.*` metrics
A support issue was found where a customer wasn't sure about this differentiation between metrics collected, so this PR serves to clarify which metrics will be collected, based on the setup method.
=> Update openai readme, clarify which metrics are available based on setup method

iam_access_analyzer/README.md
The docs were unclear/misleading for how to set up the EventBridge trigger to send AWS IAM Access Analyzer findings via the Lambda Forwarder. This updates the docs to more closely follow the steps in AWS.
=> Update AWS IAM Access Analyzer docs for clarity

postgres/changelog.d/16206.changed, postgres/datadog_checks/postgres/metrics_cache.py, postgres/datadog_checks/postgres/util.py, postgres/tests/test_pg_integration.py
Exclude manual vacuum from `pg_stat_activity` results.
Manually launched vacuum behaves the more or less the same way as autovacuum and won't keep the transaction and MVCC snapshot opened during the vacuum. We want to be able to monitor xact age and xmin without vacuums.
=> PostgreSQL: Exclude manually launched vacuum from pg_stat_activity

openstack_controller/changelog.d/16200.fixed, openstack_controller/datadog_checks/openstack_controller/api/api_rest.py, openstack_controller/tests/conftest.py, openstack_controller/tests/test_unit_neutron.py, openstack_controller/tests/test_unit_nova.py, openstack_controller/tests/test_unit_octavia.py
Use params arg over manual url encoding for requests with query params 
- will make paginated endpoint support simpler and cleaner
- It's recommended to allow the requests lib to encode the URL rather than manually doing so
=> Use params argument over manual url encoding for requests with query params

.github/workflows/pr-test.yml
Add the `python-version` param to the `pr-test` workflow.
If we bump the Python version from let's say 3.9 to 3.11 in integrations-core, there's currently no way for other repositories that use the `pr-test` workflow to specify their version. So their CI starts to use Python 3.11 on PRs, while their repos is not ready yet. 
Note that this feature is already implemented for [`test-all`](https://github.com/DataDog/integrations-core/blob/395d163218893afb221d99fdab899a737b32c75c/.github/workflows/test-all.yml#L10-L13) workflow which is used on master branches
For reference, this will be used [here](https://github.com/DataDog/integrations-extras/blob/master/.github/workflows/pr.yml#L12-L17) and [there](https://github.com/DataDog/marketplace/blob/master/.github/workflows/pr.yml#L12-L17), same …
=> Add the `python-version` param to the `pr-test` workflow

snmp/tests/common.py, snmp/tests/test_check.py
Fix the tests, adding back the `strict` option to the `ip_network` calls.
I messed up with the tests in [this PR](https://github.com/DataDog/integrations-core/pull/15997) where I also modified some `zip` calls that uses a `strict` parameter too since Python 3.11.
I'm sorry, I'll be extra careful next time.
=> Fix the tests

openstack_controller/tests/test_unit_nova.py
- Skip the tests that make use of `assert_external_tags` if the version of the base check is too old and does not provide this method.
I don't manage to find a better approach for now, especially because I can't do anything on older release version of the base check. I think this mock should live somewhere else (probably in `datadog_checks_dev`) and injected at runtime when running the tests instead of being imported [that way](https://github.com/DataDog/integrations-core/blob/fc38712fc34d2f027d9801b753fa6f2c52fc49bc/datadog_checks_base/datadog_checks/base/checks/base.py#L62-L66). I'll work on that later.
You can test this running: 
```
❯ ddev test --compat openstack_controller:py3.11-gcp -- -k test_external_tags
───────────────────────────────────────────────────────────────────────────── …
```
=> Skip tests that assert external tags if the base check version is too old

php_fpm/changelog.d/16193.added, php_fpm/datadog_checks/php_fpm/php_fpm.py, php_fpm/tests/test_e2e.py
The PHP-FPM status page also provides the "max active processes" statistic, which translates to the maximum number of processes that can be executed at once. This is particularly useful in understanding saturation within the PHP-FPM container, in a manner that allows horizontal scaling in a more intelligent way than the built-in CPU and memory metrics in Kubernetes. This pairs well with the Datadog External Metrics functionality as well
We turned on the External Metrics functionality with Datadog. I wanted to implement saturation-based scaling signals that the Datadog Agent provides through the various `php_fpm.*` metrics, but unfortunately there isn't a metric yet for detecting the maximum number of workers yet. So, here it is! 
I've been going off of the status pages for our internal …
=> feat(php_fpm): track maximum active processes

.github/workflows/do-not-merge-label.yml
Add a CI job to check `do-not-merge` labels. If one of this label is found, fail the CI.
We use this PR to notify reviewers that the PR is not ready to be merged. We do not always use the Draft PR because when we undraft PRs we need to seek for reviewers once again as team approval are not applied on draft PRs.
- Feel free to play with this PR to test the workflow (and to spam me)
- https://datadoghq.atlassian.net/browse/AITS-318
=> Add a CI job to check `do-not-merge` labels

gitlab_runner/tests/conftest.py
Try to make the GitLab runner e2e less flaky running the same conditions that check the endpoints twice
From master: 
```
___________________________________ test_e2e ___________________________________
tests/test_e2e.py:12: in test_e2e
aggregator = dd_agent_check(CONFIG, rate=True)
../datadog_checks_dev/datadog_checks/dev/plugin/pytest.py:233: in run_check
replay_check_run(collector, aggregator, datadog_agent)
../datadog_checks_dev/datadog_checks/dev/_env.py:173: in replay_check_run
raise Exception("\n".join("Message: {}\n{}".format(err['message'], err['traceback']) for err in errors))
E   Exception: Message: Http status code 502 on url http://localhost:8085/ci
E     File "/home/datadog_checks_base/datadog_checks/base/checks/base.py", line 1235, in …
```
=> Try to make the GitLab runner e2e less flaky

cert_manager/README.md
* Adds a troubleshooting section on the "common" issues with multiple values for the `name` tag due to this tag also being collected by the AWS integration for each host
* Multiple customer tickets trying to understand the origin of these duplicate values
=> [cert-manager][doc] Multiple values for `name` tag troubleshooting note

postgres/changelog.d/16290.fixed, postgres/datadog_checks/postgres/metrics_cache.py, postgres/datadog_checks/postgres/util.py, postgres/tests/test_pg_integration.py
Exclude manual vacuum from pg_stat_activity metric.
Manual vacuum behaves similarly to autovacuum and process' xmin age won't be used as the oldest xmin despite being reported by pg_stat_activity.
A first attempt was made in https://github.com/DataDog/integrations-core/pull/16206 but this change only impacted waiting queries/active queries count.
This change will impact all statistics reported by activity metrics while also simplifying the query: there's no need to filter autovacuum since we're already filtering on client backend.
=> Exclude manual vacuum from reported xid and xmin age

.github/workflows/test-target.yml
Use the provided python version (if any) to set the PYTHON_FILTER env variable 
The nightly job in marketplace fails because the PYTHON_FILTER is set to 3.11: https://github.com/DataDog/marketplace/actions/runs/7000845616/job/19042112520#step:13:7 They are still using Python 3.9 on master.
=> Use the provided python version (if any) to set the PYTHON_FILTER env variable

postgres/tests/test_pg_integration.py
- Add missing assert statements added in https://github.com/DataDog/integrations-core/pull/16263/files
- Apply the same logic to the previous assertion in the tests
- We're not asserting anything right now
- The CI is still flaky https://github.com/DataDog/integrations-core/actions/runs/7015727525/job/19085619262#step:13:1771
=> Add missings asserts and make the tests less flaky

flink/changelog.d/16302.added, flink/pyproject.toml, flink/setup.py, journald/changelog.d/16302.added, journald/pyproject.toml, journald/setup.py, pan_firewall/changelog.d/16302.added, pan_firewall/pyproject.toml, pan_firewall/setup.py, sidekiq/changelog.d/16302.added, sidekiq/pyproject.toml, sidekiq/setup.py, tenable/changelog.d/16302.added, tenable/pyproject.toml, tenable/setup.py
Bump Python version from py3.9 to py3.11 in log integrations.
This has almost no effect since they are not Python integrations. We only have a config file to configure the log collection
Missed in https://github.com/DataDog/integrations-core/pull/15997, I'll fix the script
https://datadoghq.atlassian.net/browse/AITS-277
=> Bump Python version from py3.9 to py3.11

ddev/changelog.d/16303.fixed, ddev/src/ddev/cli/meta/scripts/upgrade_python.py, ddev/tests/cli/meta/scripts/conftest.py, ddev/tests/cli/meta/scripts/test_upgrade_python.py
- Take into account logs only integrations when bumping the Python version
Currently we iterate only over testable integrations, the ones which have a `hatch.toml` file. That's not right because some integrations do not have one, such as logs only integration.
https://datadoghq.atlassian.net/browse/AITS-283
=> Take into account logs only integrations when bumping the Python version

flink/requirements-dev.txt, journald/requirements-dev.txt, pan_firewall/requirements-dev.txt, sidekiq/requirements-dev.txt, tenable/requirements-dev.txt
Remove the `requirements-dev.txt` files
We do not use them anymore because we no longer use tox and this is include in our hatch setup. They are not used in logs integrations anyway
=> Remove the `requirements-dev.txt` files

vsphere/changelog.d/16314.fixed, vsphere/datadog_checks/vsphere/vsphere.py, vsphere/tests/test_unit.py
Fixes a typo in log line when collecting property metrics
https://github.com/DataDog/integrations-core/pull/16296#discussion_r1408998421
=> Fix typo in log line

sqlserver/tests/compose/docker-compose.yaml
Reverts DataDog/integrations-core#16307
We do use them when we want to test the logs product, see:
- https://datadoghq.dev/integrations-core/ddev/test/#logs
- https://github.com/DataDog/integrations-core/blob/d4233a46329b8c446c06d363b2ce4f3721a81f9b/sqlserver/tests/conftest.py#L329
=> Revert "Remove SQL Server logs from tests"

postgres/tests/test_pg_integration.py
Try to make one test less flaky
This test is flaky https://github.com/DataDog/integrations-core/actions/runs/7087443444/job/19287825626#step:13:2932
I try the same approach applied in https://github.com/DataDog/integrations-core/pull/16292 and https://github.com/DataDog/integrations-core/pull/16263
=> Attempt to fix some flaky tests

.github/CODEOWNERS
This is a policy change to require the @DataDog/database-monitoring-agent team to approve all PRs on functional changes (code changes) for the database integrations.
The objective is to consolidate reviewers to increase context and standardization of design choices until standards can be enforced with automation.
=> Codeowners: Require Agent team PRs for functional code changes in the database integrations

openai/assets/dashboards/overview_dashboard.json
This PR updates the estimated cost calculation query in the openAI overview dashboard to use the correct formula that reflects the correct OpenAI model prices as of November 6, 2023 (includes new gpt-4-preview models). Additionally, this PR applies the same changes to the second `estimated cost` widget that was missed in the previous PR (#15738). This PR also updates the pricing text block the dashboard provides to reflect correct model prices as of November 6, 2023.
=> Update openai dashboard model pricing to latest

karpenter/README.md, karpenter/datadog_checks/karpenter/data/conf.yaml.example
The Karpenter [PR](https://github.com/DataDog/integrations-core/pull/16082) was merged before docs could do an editorial review so I'm opening a PR with a couple editorial edits.
I also updated a couple of links in the doc because the links used were aliases.
[DOCS-6660](https://datadoghq.atlassian.net/browse/DOCS-6660)
[DOCS-6660]: https://datadoghq.atlassian.net/browse/DOCS-6660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-6660] Editorial review of Karpenter integration doc

.github/workflows/pr-add-team-labels.yml
Automatically add a team labels to the PRs
Our QA tool can use labels to automatically pre-assign the cards to the right teams. In order to do that, the agent repo is using `team/<team-name>` labels to do so. However their process is manual, the author of a PR has to do it manually. I do not want to do this manually in this repo since we can use the codeowners file (through the reviewers) to do so.
It will also be easier to filter PRs on the right team if needed
This job will not enforce a label to be present, if the author decides to remove a label (or add an extra team) for whatever good reason, it's ok. This job is a convenient way to add labels automatically, not a way to enforce something. 
Relates to https://datadoghq.atlassian.net/browse/AITS-313 but also related to a hackathon …
=> Automatically add a team labels to the PRs

datadog_checks_dev/changelog.d/16345.added, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/config.py, datadog_checks_dev/tests/tooling/commands/validate/data/my_check/datadog_checks/my_check/data/conf.example.yaml, datadog_checks_dev/tests/tooling/commands/validate/test_config.py
Make the `spec.yaml` mandatory in integrations-core if there are configuration files
We want to enforce using the spec file to generate the examples in integrations-core. 
- https://datadoghq.atlassian.net/browse/AITS-145
=> Make the `spec.yaml` mandatory in integrations-core if there are configuration files

kafka/assets/dashboards/kafka_dashboard.json
This PR removes metrics `kafka.replication.leader_elections` from the kafka OOTB Dashboard. This metric is not collected by the kafka check: https://github.com/DataDog/integrations-core/blob/master/kafka/datadog_checks/kafka/data/metrics.yaml.
This PR also removes `.weighted()` from `kafka.replication.leader_elections.rate` query, as this is not supported.
=> Remove kafka.replication.leader_elections from OOTB Dashboard

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
* Updates the devcontainer to install `datadog_checks_dev[cli]`
* Adds `docker` packages to be able to use `ddev env start` commands
* Self-testing, current devcontainer has limited usefulness
* We cannot share the docker socket from the host as ddev tests are meant to be run from a host (targetting localhost from the forwarded test containers ports), so we use docker-in-docker instead
=> [Tooling] Update devcontainer to use pip for ddev installation & docker-in-docker for `ddev env start` commands

ddev/changelog.d/16365.fixed, ddev/src/ddev/cli/dep.py, ddev/tests/cli/test_dep.py
Take into account the base check when bumping the dependencies. Right now only agent checks are take into account, not the base check which is not directly an agent check.
On https://github.com/DataDog/integrations-core/pull/16358 which was created with https://github.com/DataDog/integrations-core/pull/16348 I got a validation error. Turns out it's because the base check is not updated by the new `ddev dep updates --sync` command. The base check is not considered an agent_check because it's not really a check. I don't think it's worth it to add a new method to the Integration class because it seems to be an edge case here so it should be fine to manually add it here.
=> Take into account the base check when bumping the dependencies

.github/workflows/labeler-reusable.yml
Platform Integrations team name has a space inside of it. This causes the labeler to break. The label they have is `team/platform-integration`. 
I checked all other teams that have a label currently and I don't see any negative side affects from adding this label. The teams that this will affect are:
Platform Integration : team/platform-integration
Network Device Monitoring: team/network-device-monitoring
Labels are case insensitive. https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/using-labels-with-self-hosted-runners#creating-a-custom-label
=> add simple replacement logic to replace ` ` with `-` in team labels

kafka/assets/dashboards/kafka_dashboard.json
This PR switches from using these [GC metrics](https://github.com/DataDog/jmxfetch/blob/master/src/main/resources/org/datadog/jmxfetch/old-gc-default-jmx-metrics.yaml) to the [following GC metrics](https://github.com/DataDog/jmxfetch/blob/master/src/main/resources/org/datadog/jmxfetch/new-gc-default-jmx-metrics.yaml).
It also adds a comment saying that `new_gc_metrics` needs to be enabled for this section to populate.
`jvm.gc.cms.count` is replaced by `jvm.gc.minor_collection_count` and `jvm.gc.major_collection_count` by type. `jvm.gc.parnew.time` is replaced by `jvm.gc.minor_collection_time` and `jvm.gc.major_collection_time` by type.
`jvm.gc.collectors.old.collection_time` is removed without replacement.
Here is the new look of the section:
This PR also fixes an issue with the …
=> Update legacy JVM Metrics

openstack_controller/assets/dashboards/openstack_controller_overview_[default_microversion].json
Removes unused template variables in openstack dashboard
when filtering by a template variable of a tag that doesn't exist on a metric, that metric graph is broken
=> Remove unused template variables in dashboard

.github/workflows/update-dependencies.yml
- Generate the changelogs only if a PR was created
- Trigger the pipeline earlier when we have less traffic on GitLab
- No need to run this command if nothing changed
- Running it before the PR is created is not always reliable. The command will try to guess the PR number, which in some cases do not pick the right number. If we open the PR first the command will use the PR number from GitHub
=> Generate the changelogs only if a PR was created

ddev/changelog.d/16405.fixed, ddev/pyproject.toml
Pin the hatch version to 1.7.0
Hatch 1.8.0 broke [some of our tests](https://github.com/DataDog/integrations-core/actions/runs/7179040309/job/19548524127). Ofek is on it but I pin it to unblock the CI
=> Pin the `hatch` version to 1.7.0

ddev/changelog.d/16411.fixed, ddev/src/ddev/cli/env/start.py, ddev/src/ddev/e2e/constants.py, ddev/tests/cli/env/test_start.py
Mount the logs volumes inside the agent with the `env start` command
- When we use [`mount_logs=True`](https://github.com/DataDog/integrations-core/blob/fc38712fc34d2f027d9801b753fa6f2c52fc49bc/datadog_checks_dev/datadog_checks/dev/docker.py#L120), `datadog_checks_dev` adds the automatically generated volume's paths to the env variables using [`save_state`](https://github.com/DataDog/integrations-core/blob/fc38712fc34d2f027d9801b753fa6f2c52fc49bc/datadog_checks_dev/datadog_checks/dev/docker.py#L103)
- When we switched the `env start` (and `env test` etc...) commands to `ddev`, we started [to only use the `docker_volumes`](https://github.com/DataDog/integrations-core/blob/f824c47f1e9e37ba5ca557af9577ce7d8dd71870/ddev/src/ddev/e2e/agent/docker.py#L140) declared in the metadata by the tests. …
=> Mount the logs volumes inside the agent with the `env start` command

ddev/changelog.d/16427.fixed, ddev/pyproject.toml
Revert "Pin the hatch version to 1.7.0 (#16405)"
Will fix the docs job
=> Revert "Pin the hatch version to 1.7.0 (#16405)"

envoy/changelog.d/16432.added, envoy/datadog_checks/envoy/metrics.py, envoy/metadata.csv, envoy/tests/fixtures/legacy/local_rate_limit.txt, envoy/tests/fixtures/legacy/rbac_metric.txt, envoy/tests/legacy/common.py, envoy/tests/legacy/test_unit.py
Add new RBAC metrics in the legacy version of the check.
=> Add new RBAC metrics in Legacy check

airflow/tests/compose/Dockerfile
Remove the mysql certificates
- Their certificates expired yesterday night and we don't really need them in our test suite. 
- https://github.com/apache/airflow/issues/36231
=> Remove the mysql certificates

airflow/README.md
The update adds an warning to set the variable **statsd_datadog_enabled** to false.
We've a few customers with the same issue when they follow the Airflow integration, adding this will help reduce the number of tickets.
**Reason**: 
- When "statsd_datadog_enabled" is set to true, the connection between airflow and dogstatsd doesn't seem to function properly.
**Context**: 
Airflow has in his configuration documentation page the variable **statsd_datadog_enabled**. However in our integration we don't recommend use it. When customers use it, it seems to create a conflict with dogstatsd.
=> Update Airflow README.md to warn users relative to the use of statsd_datadog_enabled

iis/README.md
The Datadog agent user needs read and execute permissions to be able to tail logs files.
Correct the needed permissions for the Datadog agent user to tail logs files
This was brought up in a slack conversation https://dd.slack.com/archives/C046YU1V0SK/p1702457801831989
Which lead to creating this Jira escalation: https://datadoghq.atlassian.net/browse/AGENT-10762
=> adding execute to the needed permissions to tail the logs files

mysql/changelog.d/16439.fixed, mysql/datadog_checks/mysql/activity.py, mysql/datadog_checks/mysql/statements.py, postgres/changelog.d/16439.fixed, postgres/datadog_checks/postgres/statement_samples.py, postgres/datadog_checks/postgres/statements.py, sqlserver/changelog.d/16439.fixed, sqlserver/datadog_checks/sqlserver/activity.py, sqlserver/datadog_checks/sqlserver/statements.py
[INCIDENT-24014] This reverts commit 5ba30fc8c999591b53f924ac5a4832fb6ab2959d.
We've noticed increased memory usage with databases with high cardinality, for example, Postgres with exploded pg_stat_statements, due to this change.
=> Revert "[DBMON-2989] report sql obfuscation error count (#15990)"

openai/README.md
This PR adds a brief note to the OpenAI readme doc specifying that `DD_SITE` needs to be specified for non-us1 customers.
=> Add openai readme note about DD_SITE

ddev/changelog.d/16449.fixed, ddev/src/ddev/cli/dep.py
Ignore rethinkdb when bumping the deps
They forgot to add some deps on version `2.4.10` and created a `2.4.10.post1` version which breaks the py2 env. Waiting for a proper `2.4.11`
=> Ignore `rethinkdb` when bumping the deps

nginx_ingress_controller/manifest.json
Switch the logs source name to `nginx-ingress-controller`, the README already has it
https://github.com/DataDog/security-monitoring/pull/3874
=> Fix the logs source name in the manifest

mysql/changelog.d/16454.fixed, mysql/datadog_checks/mysql/activity.py
In Aurora MySQL with some character sets, these double quotes in our activity query cause an error which blocks activity collection. Swap to single quotes.
=> [DBMON-3207] use single quotes in activity query to fix char set issue

sqlserver/changelog.d/16455.fixed, sqlserver/datadog_checks/sqlserver/activity.py, sqlserver/tests/compose-ha/sql/aoag_primary.sql, sqlserver/tests/compose-high-cardinality-windows/setup.sql, sqlserver/tests/compose-high-cardinality/setup.sql, sqlserver/tests/compose-windows/setup.sql, sqlserver/tests/compose/setup.sql, sqlserver/tests/test_activity.py
In sqlserver query activity collection, query statement is wrongly marked as `ERROR: failed to obfuscate` when the query is part of a truncated stored procedure. 
The stored procedure is truncated when it exceeds the `PROC_CHAR_LIMIT`, which is `500` characters. Although the stored procedure is truncated and fails obfuscation due to statement ends at an incomplete position, the actual executed statement from the procedure is often collected and obfuscated without issue. 
The integration did not distinguish the difference between SQL statement obfuscation error and stored procedure obfuscation error, result in SQL statement always be marked as `ERROR: failed to obfuscate` when either one fails to obfuscate.
For example, a stored procedure starts with large comment block like below is …
=> [DBMON-3197] ensure accurate collection of query activity with statement when stored procedure is failed to obfuscate

ddev/changelog.d/16460.added, ddev/src/ddev/cli/release/agent/changelog.py, ddev/src/ddev/utils/git.py, ddev/tests/cli/release/agent/test_changelog.py, ddev/tests/utils/test_git.py
Fetch all the tags before generating the Agent changelog
On https://github.com/DataDog/integrations-core/pull/16458, @iliakur faced some issues which were due to the fact that he was missing some tags locally. The fact he also updated some old versions also shows this problem (previous RMs probably did not have some tags locally when they ran the command).
=> Fetch all the tags before generating the Agent changelog

envoy/changelog.d/16453.added, envoy/datadog_checks/envoy/metrics.py, envoy/tests/common.py, envoy/tests/fixtures/legacy/rbac_metric.txt, envoy/tests/fixtures/openmetrics/openmetrics.txt, envoy/tests/fixtures/openmetrics/openmetrics_1_28.txt, envoy/tests/legacy/test_integration.py, envoy/tests/legacy/test_unit.py, envoy/tests/test_unit.py
Add a metric that was collected in Legacy that wasn't ported over to OMv2. Also add the ability for rbac metric to have a optional tag for shadow_rule_prefix
=> Add connect state to OMv2 and shadow prefix tag to legacy

sqlserver/changelog.d/16461.fixed, sqlserver/datadog_checks/sqlserver/statements.py
This PR fixes an unexpected exception when reporting `obfuscate-xml-plan` error metric.
=> fix unexpected exception when reporting sqlserver statements obfuscate xml plan error

disk/changelog.d/16452.fixed, disk/datadog_checks/disk/disk.py
=> Moves noisy warn logs to debug level

mysql/assets/configuration/spec.yaml, mysql/changelog.d/16429.added, mysql/datadog_checks/mysql/config.py, mysql/datadog_checks/mysql/config_models/instance.py, mysql/datadog_checks/mysql/data/conf.yaml.example, postgres/assets/configuration/spec.yaml, postgres/changelog.d/16429.added, postgres/datadog_checks/postgres/config.py, postgres/datadog_checks/postgres/config_models/instance.py, postgres/datadog_checks/postgres/data/conf.yaml.example, sqlserver/assets/configuration/spec.yaml, sqlserver/changelog.d/16429.added, sqlserver/datadog_checks/sqlserver/config.py, sqlserver/datadog_checks/sqlserver/config_models/instance.py, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
This PR adds new SQL obfuscation options to `postgres`, `mysql` and `sqlserver` integration. The new options includes
- `obfuscation_mode`: enables/disables SQL obfuscation with new obfuscator from `go-sqllexer`
- `remove_space_between_parentheses`: remove spaces between parentheses in your normalized SQL statements.
- `keep_null`: keep the keyword `NULL` in your obfuscated SQL statements.
- `keep_boolean`: keep the keywords `TRUE` and `FALSE` in your obfuscated SQL statements.
- `keep_positional_parameter`: keep positional parameters (e.g. `$1`) in your obfuscated SQL statements.
- `keep_trailing_semicolon`: keep trailing semicolons in your normalized SQL statements.
- `keep_identifier_quotation`: keep identifier quotations (e.g. `"my_table"`) in your normalized SQL statements.
The new …
=> [DBMON-3271] add new obfuscator options to customize SQL obfuscation and normalization

sqlserver/assets/configuration/spec.yaml, sqlserver/changelog.d/16462.added, sqlserver/datadog_checks/sqlserver/activity.py, sqlserver/datadog_checks/sqlserver/config.py, sqlserver/datadog_checks/sqlserver/config_models/defaults.py, sqlserver/datadog_checks/sqlserver/config_models/instance.py, sqlserver/datadog_checks/sqlserver/const.py, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example, sqlserver/datadog_checks/sqlserver/statements.py, sqlserver/datadog_checks/sqlserver/utils.py, sqlserver/tests/test_activity.py, sqlserver/tests/test_statements.py
This PR adds config option `stored_procedure_characters_limit` (defaults to 500) to set upper limit of stored procedure text collected in query metrics and query activity. 
It replaces the hard coded 500 characters `PROC_CHAR_LIMIT`. 
Stored procedure characters limit was added in #15105. Making the upper configurable provides value to users with large stored procedure, often starts with a block of comments that describes what the procedure does (for example see #16455).
Increase the characters limit will have direct impact on the amount of data being transferred between the monitored database to the agent and to Datadog.
=> [DBMON-3197] add config option to set character limit of stored procedure text

sqlserver/changelog.d/16469.fixed, sqlserver/datadog_checks/sqlserver/metrics.py, sqlserver/datadog_checks/sqlserver/sqlserver.py, sqlserver/tests/test_unit.py
This PR fixes a bug that caused SQLServer SqlFractionMetric failed to report due to base_name equals to None. 
Fix reported error
```
metadata:
resolved_hostname: D-DEV-DB-L
Error: 'NoneType' object has no attribute 'strip'
File "C:\\Program Files\\Datadog\\Datadog Agent\\embedded3\\lib\\site-packages\\datadog_checks\\base\\checks\\base.py", line 1235, in run
File "C:\\Program Files\\Datadog\\Datadog Agent\\embedded3\\lib\\site-packages\\datadog_checks\\sqlserver\\sqlserver.py", line 779, in check
self.collect_metrics()
File "C:\\Program Files\\Datadog\\Datadog Agent\\embedded3\\lib\\site-packages\\datadog_checks\\sqlserver\\sqlserver.py", line 877, in collect_metrics
metric.fetch_metric(rows, cols, …
```
=> [DBMON-3220] skip reporting SqlFractionMetric when base_name is None

.github/workflows/update-agent-changelog.yml
Add an action to automatically update the agent changelog after a release. This job is triggered when the agent tag is pushed by the RM
When the Agent gets released, we create a new tag in integrations-core and then update the changelog. Having a job that does it automatically will save us a bit of time and will be less error prone. 
I created https://github.com/DataDog/integrations-core/pull/16491 from this PR (and edited the tag name because this PR is not merged yet)
=> Add an action to automatically update the agent changelog after a release

ddev/changelog.d/16474.fixed, ddev/src/ddev/cli/env/start.py, ddev/tests/cli/env/test_start.py
Override the default configuration when environment vars are provided in the `env start` command
CLI params should take precedence
https://datadoghq.atlassian.net/browse/AITS-323
=> Override the default configuration when environment vars are provided in the `env start` command

ddev/changelog.d/16472.added, ddev/pyproject.toml, ddev/src/ddev/cli/meta/scripts/__init__.py, ddev/src/ddev/cli/meta/scripts/generate_metrics.py, ddev/src/ddev/integration/core.py, ddev/src/ddev/integration/metrics.py, ddev/tests/cli/meta/scripts/conftest.py, ddev/tests/cli/meta/scripts/test_generate_metrics.py, ddev/tests/integration/conftest.py, ddev/tests/integration/test_core.py
Add a script to generate all the metrics for a given integration
I wrote a tiny script to do that for an integration to populate some metrics that are sometimes hard to get, so I thought it would be a good idea to add it to ddev.
The values are randomly generated, but we could do something smarter in the future I think (hackathon?).
For Ray I get this output: 
```
Metric ray.process.cpu_seconds.count with value 73 and type 0
Metric ray.process.max_fds with value 2 and type 3
Metric ray.process.open_fds with value 12 and type 3
Metric ray.process.resident_memory with value 4 and type 3
Metric ray.process.start_time with value 23 and type 3
Metric ray.process.virtual_memory with value 53 and type 3
Metric ray.python.gc.collections.count with value 88 and type 0
Metric …
```
=> Add a script to generate all the metrics for a given integration

ddev/changelog.d/16492.fixed, ddev/src/ddev/cli/release/agent/integrations_changelog.py, ddev/tests/cli/release/agent/conftest.py, ddev/tests/cli/release/agent/test_changelog.py, ddev/tests/cli/release/agent/test_integrations.py, ddev/tests/cli/release/agent/test_integrations_changelog.py
Update the CHANGELOG file for packages in the `integrations-changelog` command
`iter('all')` returns [`integrations`](https://github.com/DataDog/integrations-core/blob/b10e1e0bd7b41cc54f2074cd82851843e881685a/ddev/src/ddev/repo/core.py#L93-L99), which should [contain a manifest](https://github.com/DataDog/integrations-core/blob/master/ddev/src/ddev/integration/core.py#L154). The base check and the downloader don't have any but they should be updated as well since they have a README. We must use `iter_all` instead since they are [`valid`](https://github.com/DataDog/integrations-core/blob/b10e1e0bd7b41cc54f2074cd82851843e881685a/ddev/src/ddev/repo/core.py#L101-L107) (in the `ddev` sense because [they are packaged or have a manifest](https://github.com/DataDog/integrations-core/blob/master/dd …
=> Update the CHANGELOG file for packages in the `integrations-changelog` command

envoy/changelog.d/16478.added, envoy/datadog_checks/envoy/envoy.py, envoy/tests/legacy/test_integration.py, envoy/tests/legacy/test_unit.py
Add the a endpoint tag to the legacy version of the envoy check. 
While going over the check, I notice that the OpenMetricsV2 implementation has a useful endpoint check. The legacy version however lacks this check. This can cause problems if a single agent were to monitor different stats_url endpoints. There might be no way to distinguish them from one another. 
```
envoy.server.state                                         gauge  1703021786  0                                                                  
envoy.server.total_connections                             gauge  1703021786  0                                                                  
envoy.server.uptime                                        gauge  1703021786  160 …
```
=> Add endpoint tag to legacy

amazon_msk/changelog.d/16496.fixed, amazon_msk/datadog_checks/amazon_msk/check.py
Avoid `TypeError`.
To Fix this error when `tags` are not defined in `/etc/datadog-agent/conf.d/amazon_msk.d/conf.yaml`.
```
amazon_msk (4.3.0)
------------------
Instance ID: amazon_msk:3ae8d89697858242 [ERROR]
Configuration Source: file:/etc/datadog-agent/conf.d/amazon_msk.d/conf.yaml
Total Runs: 2
Service Checks: Last Run: 0, Total: 0
Average Execution Time : 1ms
Last Execution Date : 2023-12-26 11:16:40 UTC (1703589400000)
Last Successful Execution Date : Never
Error: can only concatenate tuple (not "NoneType") to tuple
File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/base/checks/base.py", line 1210, in run
initialization()
File …
```
=> Fix TypeError when tags are undefined

datadog_checks_dev/changelog.d/16504.fixed, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/pyproject.toml, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/pyproject.toml, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/pyproject.toml
Set the Python version back to 3.9 in the templates 
Agent 7.51 that is shipped with Python 3.11 is not out yet so the integrations that are created right now can't be installed on the current Agent.
=> Set the Python version back to 3.9 in the templates

ddev/changelog.d/16506.fixed, ddev/pyproject.toml
Bump the datadog-checks-dev minimum version to 29.0.1
https://github.com/DataDog/integrations-core/pull/16505
=> Bump the `datadog-checks-dev` minimum version to 29.0.1

datadog_checks_base/datadog_checks/__init__.py, datadog_checks_dev/changelog.d/16507.fixed, datadog_checks_dev/pyproject.toml
Pin the pytest-asyncio version to 0.23.2
Something [broke the base check's tests](https://github.com/DataDog/integrations-core/actions/runs/7384236138/job/20086796772) with the latest version related to https://github.com/pytest-dev/pytest-asyncio/issues/729, pinning it for now until it's resolved
Green job [here](https://github.com/DataDog/integrations-core/actions/runs/7384477100/job/20087538171?pr=16507)
=> Pin the `pytest-asyncio` version

tls/tests/conftest.py
Update the cloudflare instances to fail only if the certificates are going to expire the next day
Their certificates are going to expire in 9 days so our check emits a warning (set to 14 days by default). 
I know it's not perfect, we're highly dependant on an external resources we do not control
=> Update the cloudflare instances to fail only if the certificates are going to expire the next day

datadog_checks_base/changelog.d/16479.added, datadog_checks_base/datadog_checks/base/checks/base.py, datadog_checks_base/datadog_checks/base/utils/db/utils.py, datadog_checks_base/tests/base/utils/db/test_util.py
This PR adds memory profiling to DBMAsyncJob when `profile_memory` is set in check `init_config`. 
The implementation follows the same memory profile [implementation](https://github.com/DataDog/integrations-core/blob/ae4f42ae63a774b7c8c1ea9407d9f5b9a69d1143/datadog_checks_base/datadog_checks/base/checks/base.py#L1221) in check run. 
When memory profiling is enabled, `datadog.agent.profile.memory.check_run_alloc` will be available for DBM async jobs. 
Memory snapshots & diffs will also be produced per async job on the agent host.
The `memory_profile` debug feature is enabled only for check main thread that executes `run` function. During #incident-24014, we manually added [tracemalloc](https://github.com/DataDog/integrations-core/compare/7.49.x...justindd/postgres-tracemalloc-749) to the …
=> conditionally enable memory profile for DBMAsyncJob

sqlserver/changelog.d/16431.added, sqlserver/datadog_checks/sqlserver/data/driver_config/odbcinst.ini
Adds support for using the Microsoft ODBC driver in the SQL Server agent for dockerized builds. This relies on this [change in the datadog-agent](https://github.com/DataDog/datadog-agent/pull/20825). I tested this on a sandbox instance using the following docker command (with a test internal docker image)
```
docker run -d \
-e "DD_API_KEY=${DD_API_KEY}" \
-v /var/run/docker.sock:/var/run/docker.sock:ro \
-l com.datadoghq.ad.check_names='["sqlserver"]' \
-l com.datadoghq.ad.init_configs='[{}]' \
-l com.datadoghq.ad.instances='[{
"dbm": true,
"host": "dbm-agent-integration-managed-instance-ao.cfcc2366ab90.database.windows.net,1433",
"connector": "odbc",
"ssl": "require",
"driver": "{ODBC Driver 18 for SQL Server}",
"tags": [
"service:jm-test-odbc-mi",
"env:dev"
],
"managed_identity": { …
```
=> Add ODBC driver support for the SQL Server agent

envoy/assets/monitors/connected_state.json, envoy/manifest.json
Recommended monitor for envoy.
Alerting criteria (tl;dr):
Alert if the connected_state is down (0) at all time for longer than 10 minutes.
Longer:
The metric that is being monitored will either report a 1 for being connected or a 0 when it's disconnected. The criteria for alerting will be if the metric has been reporting 0(or less) for 10 minutes straight. This is broken up by endpoint so that we can alert on each individual endpoint. This feature is available in Openmetrics, but I'll create another pr to add the endpoint tag to the legacy check.
=> Add recommended monitor for Envoy

datadog_checks_downloader/tests/test_downloader.py
Mark one of the test flaky and re-run it up to 3 times if it fails with a 10 second delay
- When we run this test in the middle of a release it can fail because we are replacing the metadata file
- We will rework the release process in Q1/Q2 so I think it's reasonable to simply re-run this test if it fails until then
- https://datadoghq.atlassian.net/browse/AI-3438
=> Mark one of the tests flaky

sqlserver/README.md
Currently the DBM docs imply that ports must be static. However, per the sample config files DBM can support dynamic ports, so the docs should reflect that. 
Removes the line in `prereqs` saying a static port is required. Per this [PR](https://github.com/DataDog/integrations-core/pull/13135) DBM can support dynamic port discovery and the docs should reflect that. 
Implementing DBM and discovered this is possible but not documented anywhere except the sample config file. While that is useful, it contradicts the docs.
=> Add dynamic port settings to sqlserver docs

.github/workflows/pr-check.yml
Do not run the pr-check workflow on PRs that do not target master
It failed [here](https://github.com/DataDog/integrations-core/pull/16519) but it's ok, intermediate PRs do not need this
=> Do not run the `pr-check` workflow on PRs that do not target master

kube_proxy/metadata.csv
This PR removes the metric `kubeproxy.network_programming.duration` from the CSV document that list available metrics as confirmed in this [PR](https://github.com/DataDog/integrations-core/pull/11182).
Question raised by customer about why this metric still appear in the list of captured metric while we do not capture it.
=> kubeproxy.network_programming.duration - Documentation update

rabbitmq/tests/conftest.py, rabbitmq/tests/metrics.py
Fix a flaky test
We sometimes get a connection in the e2e env and we do not really care about the value in the e2e tests, only in the unit tests: 
```
_________________________ test_rabbitmq_e2e_management _________________________
tests/test_e2e.py:22: in test_rabbitmq_e2e_management
assert_metric_covered(aggregator)
tests/metrics.py:389: in assert_metric_covered
aggregator.assert_metric('rabbitmq.connections', tags=['rabbitmq_vhost:/', "tag1:1", "tag2"], value=0, count=1)
../datadog_checks_base/datadog_checks/base/stubs/aggregator.py:368: in assert_metric
self._assert(condition, msg=msg, expected_stub=expected_metric, submitted_elements=self._metrics) …
```
=> Fix a flaky test

postgres/README.md
Adds a doc page link to the Docs Site on the Postgres integration tile, which is currently redirecting users back to the in-app tile.
Makes the user journey not so confusing.
=> Postgres Integration Edit

postgres/changelog.d/16517.fixed, postgres/datadog_checks/postgres/metadata.py, postgres/tests/common.py, postgres/tests/compose/resources/03_load_data.sh, postgres/tests/test_metadata.py
This PR handles an edge case on Postgres schema collection for partitioned table. The integration relies on table activity (sequence scan & index scan) as the sort key of collected table, that way we can prioritize collecting schemas for tables with high activity. 
The current implementation fails for an edge case when a partitioned table has no children (partitioned sub-tables). This edge case will result in no returned rows for the `PARTITION_ACTIVITY_QUERY`, due to the join with `pg_inherits`. 
Customer reported issues on collecting schema https://datadoghq.atlassian.net/browse/SDBM-776
=> [DBMON-3299] edge case handling when partitioned table has no activity

airflow/README.md
This is updating the airflow integration doc to fix the tasks logs path.
The airflow tasks logs path in the doc has two issues
- the logs are 1 folder deeper, the structure is `{{ ti.dag_id }}/{{ ti.task_id }}/{{ ts }}/{{ try_number }}.log` documented just below in the same doc
- the `!(scheduler)` pattern is not regonized by the datadog agent
Datadog agent status before addressing 2nd bullet point:
```
- Type: file
Path: /opt/airflow/logs/!(scheduler)/*/*/*.log
Source: airflow
Status: Error: could not find any file matching pattern /opt/airflow/logs/!(scheduler)/*/*/*.log, check thatall its subdirectories are executable
```
Datadog agent status after:
```
- Type: file
Path: /opt/airflow/logs/*/*/*/*.log
Source: airflow
Status: OK
```
=> Fix airflow taks logs path in readme

datadog_checks_dev/changelog.d/16527.fixed, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/pyproject.toml, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/pyproject.toml
Make those consistent with the `check` template. We don't need `setuptools` anymore.
Detected while reviewing https://github.com/DataDog/integrations-core/pull/16499
=> Remove setuptools depedency for jmx and logs integration templates

sqlserver/changelog.d/16465.added, sqlserver/datadog_checks/sqlserver/activity.py, sqlserver/tests/test_activity.py
- Adds the `is_user_process` field to our activity events to filter out background processes in the UI
- Customers are seeing background processes in some places in the UI, and these have a disproportionally high duration compared to other samples.
=> [DBM] - Add whether a SPID is a user or bg process

datadog_checks_dev/changelog.d/16528.fixed, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/pyproject.toml
Update the template for logs integrations to not require a specific Python and base check version
- https://github.com/DataDog/integrations-core/pull/16499#discussion_r1441653005
- We don't really need to ensure this for logs integrations since they are not checks
=> Update the template for logs integrations to not require a specific Python and base check version

postgres/changelog.d/16516.fixed, postgres/datadog_checks/postgres/explain_parameterized_queries.py, postgres/datadog_checks/postgres/statement_samples.py, postgres/datadog_checks/postgres/util.py, postgres/tests/test_explain_parameterized_queries.py
This PR adds proper error handling and emit correct error message when explain parameterized query fails. 
Prior to the fix, when `explain_parameterized_queries` is enabled but the integration fails to explain the parameterized query, an incorrect error `DBExplainError.parameterized_query` will be set by the agent. 
This is often very confusing to the user as DBM will display below error message on the UI. User might wonder whether `explain_parameterized_queries` is actually enabled or not. But in reality, `explain_parameterized_queries` is often properly set in the config but other exceptions are raised when explain parameterized query.
=> [DBMON-3302] emit correct error message when explain parameterized query fails

.builders/build.py, .builders/images/linux-x86_64/Dockerfile, .builders/images/runner_dependencies.txt, .builders/images/windows-x86_64/Dockerfile, .builders/scripts/build_wheels.py, .deps/build_dependencies.txt
- Made the Python version argument required for the inner build script.
- Changed the logic for the runner component: the runner now must be the Python 3 executable that is outside/parent of the virtual environment. As such, this Python is only one that should ever be on PATH.
- Python 2 on Windows does not yet work for IBM MQ but we should get this merged to unblock the Linux side
=> Add Python 2 to Windows

postgres/assets/configuration/spec.yaml, postgres/changelog.d/16540.added, postgres/datadog_checks/postgres/config.py, postgres/datadog_checks/postgres/config_models/defaults.py, postgres/datadog_checks/postgres/config_models/instance.py, postgres/datadog_checks/postgres/data/conf.yaml.example, postgres/datadog_checks/postgres/postgres.py, postgres/tests/test_pg_integration.py
This fixes an issue where we do not allow people to not set `host` and `username` fields in the config, which breaks the host auto discovery feature for postgres users. This results in the following error in the status output
```
Loading Errors
==============
postgres
--------
Core Check Loader:
Check postgres not found in Catalog
JMX Check Loader:
check is not a jmx check, or unable to determine if it's so
Python Check Loader:
could not configure check instance for python check postgres: could not invoke 'postgres' python check constructor. New constructor API returned:
File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/postgres/postgres.py", line 95, in __init__
self._config = PostgresConfig(self.instance)
File …
```
=> When host auto discovery is enabled, do nothing and emit OK for check status

postgres/changelog.d/16581.fixed, postgres/datadog_checks/postgres/relationsmanager.py, postgres/tests/test_relations.py
Fix age of vacuum events
`age(t1)` will yield `t1 - current_date at midgnight` which is incorrect for our usage.
We want the number of seconds since the last vacuum event. We will use age(t1, t2) which yield `t1 - t2` using the start of the statement time as t1 and the vacuum event as t2.
=> Fix vacuum age computation

openstack_controller/changelog.d/16566.fixed, openstack_controller/datadog_checks/openstack_controller/api/api_rest.py, openstack_controller/tests/fixtures/GET/baremetal/v1/nodes/detail/limit=1/marker=9d72cf53-19c8-4942-9314-005fa5d2a6a0/response-1.80.json, openstack_controller/tests/fixtures/GET/baremetal/v1/nodes/detail/limit=1/marker=9d72cf53-19c8-4942-9314-005fa5d2a6a0/response.json, openstack_controller/tests/fixtures/GET/baremetal/v1/nodes/detail/limit=1/marker=bd7a61bb-5fe0-4c93-9628-55e312f9ef0e/response-1.80.json, openstack_controller/tests/fixtures/GET/baremetal/v1/nodes/detail/limit=1/marker=bd7a61bb-5fe0-4c93-9628-55e312f9ef0e/response.json, openstack_controller/tests/fixtures/GET/baremetal/v1/nodes/detail/limit=1/response-1.80.json, openstack_controller/tests/fixtures/GET/baremetal/v1/nodes/detail/limit=1/response.json, openstack_controller/tests/fixtures/GET/baremetal/v1/nodes/detail=True/limit=1/marker=9d72cf53-19c8-4942-9314-005fa5d2a6a0/response-1.80.json, openstack_controller/tests/fixtures/GET/baremetal/v1/nodes/detail=True/limit=1/marker=9d72cf53-19c8-4942-9314-005fa5d2a6a0/response.json, openstack_controller/tests/fixtures/GET/baremetal/v1/nodes/detail=True/limit=1/marker=bd7a61bb-5fe0-4c93-9628-55e312f9ef0e/response-1.80.json, openstack_controller/tests/fixtures/GET/baremetal/v1/nodes/detail=True/limit=1/marker=bd7a61bb-5fe0-4c93-9628-55e312f9ef0e/response.json, openstack_controller/tests/fixtures/GET/baremetal/v1/nodes/detail=True/limit=1/response-1.80.json, openstack_controller/tests/fixtures/GET/baremetal/v1/nodes/detail=True/limit=1/response.json
Fixes pagination logic for ironic nodes endpoint- 'next' signifier is not in the `nodes` list, it is a top-level attribute
QA for https://github.com/DataDog/integrations-core/pull/16400
ironic nodes API documentation: https://docs.openstack.org/api-ref/baremetal/#list-nodes-detailed
overall pagination docs https://docs.openstack.org/api-guide/compute/paginated_collections.html
=> Fix ironic nodes pagination logic

.builders/images/linux-x86_64/Dockerfile, .builders/images/linux-x86_64/build_script.sh, .builders/images/linux-x86_64/install-from-source.sh, .builders/scripts/build_wheels.py, .builders/scripts/repair_wheels.py
Creating a wheel for confluent-kafka such that it's actually self contained is way too hard to be worth it, due to how `cyrus-sasl` works. Instead, we're linking dynamically against `cyrus-sasl` but not including it in the wheel, such that the resulting wheel will rely on the Agent having that library properly installed and convigured.
=> Add kerberos support to confluent-kafka

.github/workflows/run-validations.yml, datadog_checks_dev/changelog.d/16541.fixed, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/dep.py
- Fix a bug that prevents the validate dep command to fail if extra deps are found in the Agent file
- Also run the full validation on PRs to spot this kind of issues
- Comes from this [refacto](https://github.com/DataDog/integrations-core/pull/15416) where we lost the `s`
- Spotted thanks to this https://github.com/DataDog/integrations-core/pull/15859
- It should have failed
- I know, there's no tests. I'll add them when we'll move this to the new `ddev`
- To be merged after https://github.com/DataDog/integrations-core/pull/16538, that's why the CI is red
=> Fix a bug that prevents the `validate dep` command to fail if extra deps are found in the Agent file

ddev/changelog.d/16537.fixed, ddev/src/ddev/cli/dep.py, ddev/tests/cli/test_dep.py
Take into account all the checks when bumping or freezing the dependencies (reminder: checks = integrations that are shipped with the agent)
The `dep` commands do not take into account all the checks that are shipped, namely the downloader in my case. [This PR](https://github.com/DataDog/integrations-core/pull/16365) was not enough
=> Take into account all the checks when bumping or freezing the dependencies

gitlab/changelog.d/16572.fixed, gitlab/pyproject.toml, gitlab_runner/changelog.d/16572.fixed, gitlab_runner/pyproject.toml, kube_dns/changelog.d/16572.fixed, kube_dns/pyproject.toml, kubernetes_state/changelog.d/16572.fixed, kubernetes_state/pyproject.toml
Remove the direct dependency to `protobuf`
`protobuf` is used for the [prometheus check](https://github.com/DataDog/integrations-core/blob/b7c15a6882af399c6f477b7c751c7b0dac23a0ce/datadog_checks_base/datadog_checks/base/checks/prometheus/mixins.py#L25-L31) and thus should be declared [in the base check only](https://github.com/DataDog/integrations-core/blob/645175ff5709e5295367489b7a3c3d2b073cda78/datadog_checks_base/pyproject.toml#L56-L57). There's no need to duplicate the  dependency in other integrations since they depend on the base check.
I found this trying to bump `protobuf`, I'll do that in a follow-up PR.
=> Remove the direct dependency to `protobuf`

LICENSE-3rdparty.csv, btrfs/changelog.d/16547.added, btrfs/pyproject.toml, datadog_checks_base/changelog.d/16547.added, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, disk/changelog.d/16547.added, disk/pyproject.toml, gunicorn/changelog.d/16547.added, gunicorn/pyproject.toml, ibm_mq/changelog.d/16547.added, ibm_mq/pyproject.toml, network/changelog.d/16547.added, network/pyproject.toml, process/changelog.d/16547.added, process/pyproject.toml, system_core/changelog.d/16547.added, system_core/pyproject.toml, system_swap/changelog.d/16547.added, system_swap/pyproject.toml
Bump `psutil` version to 5.9.7
[One version broke our tests](https://github.com/DataDog/integrations-core/blame/master/ddev/src/ddev/cli/dep.py#L27) but it's not the case anymore. I'll drop it from the `dep` command in a follow-up PR
=> Bump `psutil` version to 5.9.7

datadog_checks_base/changelog.d/16560.added, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, snmp/changelog.d/16560.added, snmp/pyproject.toml
Bump `pycryptodomex` version to 3.19.1
We [do not bump pycryptodomex with ddev](https://github.com/DataDog/integrations-core/blob/4df0799a10ce2ce651675d44f6af8f99cd5a0c66/ddev/src/ddev/cli/dep.py#L24), but seems like it is now working. I'll drop it from ddev in a follow-up PR
=> Bump `pycryptodomex` version to 3.19.1

postgres/changelog.d/16612.fixed, postgres/datadog_checks/postgres/metrics_cache.py
Fix autovacuum metrics for postgres >= 10
Missed in https://github.com/DataDog/integrations-core/pull/16290
=> Fix autovacuum metrics for postgres >= 10

postgres/changelog.d/16608.fixed, postgres/datadog_checks/postgres/metrics_cache.py, postgres/datadog_checks/postgres/postgres.py, teradata/changelog.d/16608.fixed, teradata/datadog_checks/teradata/utils.py
Fix incompatibility issues with Python 3.9 and lower
The `strict` param was added in Python 3.10. The default value is `false`. A customer is trying to install the 16.0.0 wjheel on 7.50.2 and it's not working because of this
=> Fix incompatibility issues with Python 3.9 and lower

.gitlab-ci.yml, .gitlab/validate-agent-build/trigger_agent_build.py
Fix the trigger-agent build script
There's a bug in the Agent CI, the quick fix is to set the `RUN_E2E_TESTS` variable to true. We will drop it as soon as they fix the pipeline on their side
I pushed a new version of the docker image using this branch, see the commit history if needed
=> [7.51.x] Fix the trigger-agent build script

.devcontainer/devcontainer.json
* Changes the dev container Python version from system-provided to 3.11, current target version the repo
* Some ddev features require 3.10+ and Python version from the container should simply be aligned with the target, itself aligned with the Agent
=> [Tooling] Pin dev container python to 3.11

.github/CODEOWNERS
* Adds container integrations team as codeowner of the integrations-core dev container
=> [Tooling] Add container integrations team as devcontainer codeowner

datadog_checks_dev/changelog.d/16544.added, datadog_checks_dev/datadog_checks/dev/tooling/create.py, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/manifest.json, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/manifest.json, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/manifest.json, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/metrics_pull/{check_name}/manifest.json, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/snmp_tile/snmp_{check_name}/manifest.json
Adds an auto-generation of "source_type_id" and put it in the `manifest.json` file during `ddev create`.
This is a field that already exists for all current integrations and followup work will backport the current IDs into the existing manifests. 
Otherwise, the rationale can be found here - https://datadoghq.atlassian.net/wiki/spaces/MKT/pages/3306327909/2023-11-27+APW+Integration+Source+Type+ID+Generation
I was able to test this by running `ddev -x create test_integration`. Then the resulting `test_integration/manifest.json` contained the following:
```
...
"assets": {
"integration": {
"source_type_id": 4526851,
"source_type_name": "test_integration",
"configuration": {
"spec": "assets/configuration/spec.yaml"
},
...
```
=> Autogenerate source_type_id when running ddev create

tomcat/tests/test_e2e.py
Test the metadata for counter metrics again
This TODO is almost 4 years old and it is now fixed
[datadoghq.atlassian.net/browse/AI-3731](https://datadoghq.atlassian.net/browse/AI-3731)
=> Test the metadata for counter metrics again

tomcat/changelog.d/16650.removed, tomcat/datadog_checks/tomcat/data/metrics.yaml, tomcat/metadata.csv
Remove deprecated `tomcat.cache` metrics
Tomcat 7 EOLed 3 years ago and we do not have these metrics anymore.
They are not tested anymore
[datadoghq.atlassian.net/browse/AI-3731](https://datadoghq.atlassian.net/browse/AI-3731)
=> Remove deprecated `tomcat.cache` metrics

vsphere/assets/dashboards/vsphere_overview.json
Fixes the disk usage color formula in the OOTB dashboard; currently, it only ever colors the bars green
support case
=> Fix disk usage widget color formula in dashboard

openstack/tests/test_openstack.py
Adds tests for config validation 
QA for https://github.com/DataDog/integrations-core/pull/16299; we did not have any tests for openstack that ran check initializations using `dd_run_check`
=> Add openstack config tests

datadog_checks_base/changelog.d/16542.added, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, vsphere/changelog.d/16542.added, vsphere/datadog_checks/vsphere/api.py, vsphere/pyproject.toml, vsphere/tests/test_api.py
Updates pyvmomi to the next major version and newest release
Support for new API parameters added in recent releases and eventual support for vSphere 8
the major upgrade to 8.x (https://github.com/vmware/pyvmomi/commit/a90023fedfeda48cb1824200dc4530084215f99e#diff-5a4a25310fcd77c939492db13158e8639be94c33532b071817930805a7be554b) includes removal of the `ParserError` class. Handling this error was added in https://github.com/DataDog/integrations-core/pull/6658 to account for this [issue](https://github.com/vmware/pyvmomi/issues/190). 
`ParserError` was used as a catch-all parsing excepting in `ParseData`, which was removed from `Deserialize` in the new version of the library
```
def Deserialize(data, resultType=object, stub=None):
parser = ParserCreate(namespace_separator=NS_SEP)
ds = …
```
=> [PLINT-265] Update pyvmomi to 8.0.2.0.1

postgres/tests/test_pg_integration.py
Mark the `test_wal_stats` as flaky.
This PR is a suggestion more than anything else. I'm trying to get our CI. I noticed this test seems to be flaky (failure on master [here](https://github.com/DataDog/integrations-core/actions/runs/7572167556/job/20621539708)). My idea is to mark these tests as flaky and re-run them when they fail, hoping they will eventually be green. 
I know this is not ideal and it's a short-term solution. When we merge this kind of PR, we should open a card in our respective backlog to eventually fix this test and get rid of the `@flaky`.
=> Mark the `test_wal_stats` as flaky

kubernetes/assets/dashboards/kubernetes_cpu_memory.json, kubernetes/manifest.json
Add a new ootb dashboard for the Kubernetes integration
The dashboard provide K8s Memory/CPU utilization insights that are complementary to the Kubernetes resource utilization product
Based on the work of @nxnarbais
=> Add Kubernetes resource dahsboard

postgres/tests/test_deadlock.py
Mark the `test_deadlock` test as flaky
This test is flaky: https://github.com/DataDog/integrations-core/actions/runs/7584228469/job/20657565448
Created https://datadoghq.atlassian.net/browse/DBMON-3437
=> Mark the `test_deadlock` test as flaky

terraform/README.md
Add information about setting the `api_url` parameter for users not using the Datadog US1 site
DOCS-7017
=> (DOCS-7017) Add site information

postgres/tests/test_logical_replication.py
Mark the `test_common_logical_replica_metrics` test as flaky
https://github.com/DataDog/integrations-core/actions/runs/7607378517/job/20714699481?pr=16672#step:13:4129
https://datadoghq.atlassian.net/browse/DBMON-3441
=> Mark the `test_common_logical_replica_metrics` test as flaky

ddev/changelog.d/16671.fixed, ddev/src/ddev/cli/env/test.py, ddev/tests/cli/env/test_test.py
Fix a bug that prevents to run e2e tests in a non-default repository (for instance if you run `ddev -e env test <something>` when you are using `core` by default in your config)
- In the plugin we call the agent with [this](https://github.com/DataDog/integrations-core/blob/ae3fdeef335839272136b75aa7b2dd5fd327d88c/datadog_checks_dev/datadog_checks/dev/plugin/pytest.py#L190)
- As you can see, it does not forward the `-e`, because it does not really know about it.
- The idea is to leverage [this](https://github.com/DataDog/integrations-core/blob/ae3fdeef335839272136b75aa7b2dd5fd327d88c/ddev/src/ddev/cli/application.py#L73-L74) and set the env variable before we run the tests
=> Fix a bug that prevents to run e2e tests in a non-default repository

ddev/changelog.d/16672.added, ddev/src/ddev/cli/meta/scripts/generate_metrics.py
Add the possibility to send specific values in the `generate_metrics` script
Right now the values are all random. We sometimes need to provide the value ourselves.
=> Add the possibility to send specific values in the `generate_metrics` script

datadog_checks_dev/changelog.d/16647.added, datadog_checks_dev/datadog_checks/dev/tooling/create.py, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/manifest.json, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/manifest.json, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/manifest.json, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/metrics_pull/{check_name}/manifest.json, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/snmp_tile/snmp_{check_name}/manifest.json
This will make `ddev create` always include an explicit `auto_install` flag so we can get rid of the `integration sync` logic that tries to infer it from the repo.
=> [ECOS-1127] Set explicit auto_install value based on the integration type.

ecs_fargate/README.md, eks_fargate/README.md
Adds notes on the ECS Fargate and EKS Fargate readmes that NPM is not supported.
DOCS-7069
=> DOCS-7069 - state that fargate doesn't support npm

mysql/changelog.d/16681.added, mysql/datadog_checks/mysql/config.py, postgres/changelog.d/16681.added, postgres/datadog_checks/postgres/config.py, sqlserver/changelog.d/16681.added, sqlserver/datadog_checks/sqlserver/config.py
This PR defaults postgres, mysql and sqlserver integrations' `obfuscation_mode` to `obfuscate_and_normalize`. With this change, the integration will use `go-sqllexer` as the default sql statements obfuscator.
Default to `go-sqllexer` as the default sql statements obfuscator to better obfuscation on edge cases and error handling.
=> [DBMON-3271] DBM integrations now defaulted to use new go-sqllexer pkg to obfuscate sql statements

ddev/changelog.d/16682.fixed, ddev/src/ddev/utils/scripts/ci_matrix.py
Prevents CI failures like this one: https://github.com/DataDog/integrations-extras/actions/runs/7617723824/job/20747356953?pr=2265
=> [ECOS-1128] Allow script to run on apps that lack integration assets.

ddev/changelog.d/16691.fixed, ddev/src/ddev/cli/env/test.py, ddev/src/ddev/cli/test/__init__.py
- Remove unnecessary `short_help` option.
- Clearer name for pytest args
- Add link to official docs that explain how to pass environments and pytest args
- Add examples for unit/integration test command
Someone reached out on slack, their team-internal docs were out of date and they couldn't get the information they needed to get started from our docs.
=> Documentation improvements for testing commands:

twistlock/changelog.d/16680.fixed, twistlock/datadog_checks/twistlock/twistlock.py, twistlock/tests/fixtures/empty_images.json, twistlock/tests/fixtures/prisma_cloud/images.json, twistlock/tests/test_twistlock.py
This issue came up in a support case where the customer is getting an IndexError since their `/images` endpoint for Primsa Cloud returns an empty images array. We call the first Index directly with `instance = instances[0]` so this PR helps alleviate the `IndexError` issue from happening, allowing the rest of the check to go to completion.
=> Fix for empty "/image" instances for Twistlock

postgres/changelog.d/16530.added, postgres/datadog_checks/postgres/postgres.py, postgres/datadog_checks/postgres/util.py, postgres/tests/compose/etc/postgresql/postgresql.conf, postgres/tests/compose/etc/postgresql_logical_replica/postgresql.conf, postgres/tests/compose/etc/postgresql_replica/postgresql.conf, postgres/tests/compose/etc/postgresql_replica2/postgresql.conf, postgres/tests/compose/resources/02_setup.sh, postgres/tests/test_discovery.py
Postgres integration will start collecting function & count metrics for auto discovered databases.
Function & count metrics are database specific, but they were not being properly collected for auto discovered databases.
=> [DBMON-3300] collect function & count metrics for auto discovered databases

postgres/assets/configuration/spec.yaml, postgres/changelog.d/16634.added, postgres/datadog_checks/postgres/config_models/instance.py, postgres/datadog_checks/postgres/data/conf.yaml.example, postgres/datadog_checks/postgres/metadata.py, postgres/tests/test_metadata.py
- Adds the `ignored_settings_patterns` configuration under `collect_settings`. This allows users to define a list of setting patterns that the agent should NOT collect.
- Some settings are set on a per-connection level, and with connection reuse, our agent sometimes picks up on these per-connection settings as changes. With the addition of change tracking, this creates unnecessary noise. We set the default to be `['plpgsql%']`.
=> [Postgres] - Allow configuration of ignored patterns for settings

postgres/tests/test_relations.py
Mark the `test_vacuum_age` test as flaky
https://github.com/DataDog/integrations-core/actions/runs/7621280878/job/20757461388
I created https://datadoghq.atlassian.net/browse/DBMON-3472
=> Mark the `test_vacuum_age` test as flaky

harbor/tests/common.py, harbor/tests/conftest.py
Add more conditions to the e2e env
- We currently do not retry the check on this URL, if it fails the first time we try to call it, we fail the try and retry completely
- https://github.com/DataDog/integrations-core/actions/runs/7648392751/job/20841166307
=> Add more conditions to the e2e env

sqlserver/datadog_checks/sqlserver/metadata.py
Fix metadata debug logging error due to mismatched arguments
=> Fix metadata debug logging error due to mismatched arguments

datadog_checks_base/changelog.d/16702.removed, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, directory/changelog.d/16702.fixed, directory/datadog_checks/directory/traverse.py, directory/pyproject.toml
1. This function was added to standard lib in python 3.5, scandir itself claims [support until 3.7](https://github.com/benhoyt/scandir/blob/e33140fe0dfe5b967e9eb2595b6e6e8eb3c91a64/setup.py#L82)
2. fix tests on at least macos m1
=> Switch to os.scandir for Python >= 3.5

.ddqa/config.toml
This past release showed that we still have **some QA cards to assign** to the `agent-integrations` team:
1. New/migrated integrations.
2. Changes to datadog-agent repo.
We have some folks who are part of the github team who we would like to exclude from getting QA cards.
=> Exclude former teammates from QA card assignment

airflow/changelog.d/16646.added, airflow/datadog_checks/airflow/airflow.py, airflow/tests/test_unit.py
Uses Airflow's stable API to get version and determines which health endpoint needs to be hit for our service check.
https://datadoghq.atlassian.net/browse/FRAGENT-2003
=> Use Airflow version to determine health endpoint

.github/workflows/config/labeler.yml
Update the labeler config for releases 
Checks that are not included in the agent (namely checks_dev, ddev) don't get the release label
=> Update the labeler config for releases

datadog_checks_dev/changelog.d/16737.fixed, datadog_checks_dev/datadog_checks/dev/tooling/commands/release/make.py
Do not sign `ddev` after the release
- When we release ddev, we end up with an empty signature file: https://github.com/DataDog/integrations-core/pull/16732
- Then the release pipeline fails because of that
- So we have to manually update the signatures: https://github.com/DataDog/integrations-core/pull/16735
If we stop signing it, no need to update the signatures again
kinda related to https://datadoghq.atlassian.net/browse/AITS-188
=> Do not sign `ddev` after the release

docker_daemon/manifest.json
The docker integration definition and assets appear to exist both in dogweb code here: https://github.com/DataDog/dogweb/tree/prod/integration/docker and in the integrations-core repo here: https://github.com/DataDog/integrations-core/tree/master/docker_daemon .
We'd like to consolidate these assets in one place as part of cleaning up hacks in the integration publishing code like this one: https://github.com/DataDog/declarative-integration-pipeline/blob/2043224e62d52c6c410c15ee0af582f478989c4c/declarative_integrations/create_agent_integration/constants.py#L163
This PR ensures that the source_type_id and auto_install flag match between the 2 repos.
This is a no-op for customers because the integration loader for dogweb services will ignore this manifest.
=> [ECOS-1179] Sync the auto_install flag and source type id for the docker integration

harbor/tests/conftest.py
Attempt to make the e2e env less flaky
- The env is a bit flaky, this attempt is not great but I don't see any other solutions right now
- https://github.com/DataDog/integrations-core/actions/runs/7707856696/job/21005858677#step:13:1842
=> Attempt to make the e2e env less flaky

datadog_checks_base/changelog.d/16742.fixed, datadog_checks_base/datadog_checks/base/utils/db/utils.py, datadog_checks_base/tests/base/utils/db/test_util.py, sqlserver/changelog.d/16742.fixed, sqlserver/datadog_checks/sqlserver/activity.py, sqlserver/datadog_checks/sqlserver/statements.py, sqlserver/tests/compose-ha/sql/aoag_primary.sql, sqlserver/tests/compose-high-cardinality-windows/setup.sql, sqlserver/tests/compose-high-cardinality/setup.sql, sqlserver/tests/compose-windows/setup.sql, sqlserver/tests/compose/setup.sql, sqlserver/tests/test_statements.py
This PR
- [datadog_checks_base] Add `replace_null_character` option in `obfuscate_sql_with_metadata` to replace embedded nulls with empty string
- [sqlserver] Replaces all embedded nulls in sql statement text 
Fix error `ValueError: embedded null character` in obfuscation and logging. 
```
2024-01-26 18:18:57 EST | CORE | ERROR | (pkg/collector/python/datadog_agent.go:129 in LogMessage) | sqlserver:5632e6fae0b72e41 | (tracking.py:84) | operation collect_statement_metrics_and_plans error
File "C:\Program Files\Datadog\Datadog Agent\embedded3\Lib\site-packages\datadog_checks\sqlserver\statements.py", line 314, in _normalize_queries
statement = obfuscate_sql_with_metadata(row['statement_text'], self._config.obfuscator_options) …
```
=> [DBMON-3495] Replace embedded null characters in query text

sqlserver/changelog.d/16750.fixed, sqlserver/pyproject.toml
Another follow-up to https://github.com/DataDog/integrations-core/pull/16742. sqlserver check needs the latest base check version to work.
=> Require base check that has fix for null characters in query strings

.github/workflows/build-deps.yml
PRs should be the only time where it's okay for in progress jobs to get canceled since no publishing would occur
=> Ensure that builds run to completion on merges

.builders/images/linux-x86_64/Dockerfile, .builders/images/linux-x86_64/build_script.sh
Adds optimization flag to all compilations and compiles librdkakfa with curl support.
Equivalents found in Omnibus:
- https://github.com/DataDog/omnibus-ruby/blob/f3cbfdcf00a208cc165a30da80a95c456b5fa25a/lib/omnibus/software.rb#L788C25-L788C64
- https://github.com/DataDog/datadog-agent/pull/22040/files
I found out about this while working on the MacOS build and made a note to add them to the Linux build.
=> Tweaks to Linux dependency build

.builders/images/runner_dependencies.txt, .builders/scripts/repair_wheels.py
Changes version of auditwheel to use a patched fork that sets the RPATH the way we want.
https://github.com/pypa/auditwheel/compare/main...DataDog:auditwheel:alopez/set-correct-rpath-on-copied-libs
When trying to integrate our repaired wheels into the Agent build, Omnibus' health check failed. The reason is related to what is reported in https://github.com/pypa/auditwheel/issues/451. The summary of the issue is that `ldd` can't find the libraries linked from libraries that are copied into the wheel because the `RPATH` of the copied libraries does not point to the right location.
This required some changes to the repair script that calls functions within auditwheel because apparently that API is not really stable.
=> Use forked version of auditwheel with correct rpath patching

datadog_checks_dev/changelog.d/16759.fixed, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/README.md, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/metrics_pull/{check_name}/README.md, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/tile/{check_name}/README.md
Removes the angle brackets from these templates because they cause `integration sync` to fail in a confusing way.
=> Remove unsupported characters from README templates.

.github/workflows/backport-pr.yml
Add a GitHub action to backport PRs.
- Once the PR is merged, if it has a `backport/<branch-name>` label, the pipeline will run and open a backport PR to the `branch-name` branch if there's no conflicts
- This `backport/<branch-name>` label can be applied after the PR is merged, it does not need to be there when the PR is merged, it can be added afterward.
- Several `backport/` labels can be applied to the same PRs 
- The backport PR will have the `backport` and `bot` labels by default and other labels will be applied automatically (team, changelogs, etc)
Suggested by @clamoriniere 
I'm going to request IT to rename the bot we are using for this since we now use it not just for the labeler
=> Add a GitHub action to backport PRs

.builders/images/linux-x86_64/Dockerfile
Sets the `rpath` to `$ORIGIN` on the `LDFLAGS` so that all the libraries we ship have that set from the start.
Auditwheel only patches the `RPATH` if it's already set (or if `RUNPATH` is set). See [here](https://github.com/pypa/auditwheel/blob/db7962149a3e971eba3974a58edcb2226c787f8d/src/auditwheel/repair.py#L166-L167). That means that currently we can't rely on it to set the `RPATH` as needed by the health check.
=> Set rpath to $ORIGIN

.builders/scripts/repair_wheels.py
It removes zlib from the whitelist in the policies included with auditwheel, so that it gets included.
The Omnibus health check flags this library.
auditwheel whitelisted zlib in https://github.com/pypa/auditwheel/pull/334. The rationale is that this would be acceptable according to [PEP-600](https://peps.python.org/pep-0600/) due to zlib being shipped with all major distros supporting the base minimum glibc version.
=> Include zlib in wheels that need it

.builders/images/linux-x86_64/Dockerfile, .builders/images/linux-x86_64/build_script.sh, .builders/scripts/repair_wheels.py
Compiles `cyrus-sasl` statically.
Being able to create a self-contained wheel for the confluent-kafka-python package.
- [Topic in official docs](https://www.cyrusimap.org/sasl/sasl/advanced.html#using-cyrus-sasl-as-a-static-library). The caveats don't apply for our case, as we don't expect to add mechanisms to an existing Agent installation without upgrading the whole agent (for which case a recompiled version of the library could be shipped).
- I tested this by running e2e tests using an ad-hoc datadog-agent docker image based on the official one with these two changes:
- Deleting all library files associated to sasl2, libgssapi, and librdkafka from the Agent's embedded environment.
- Forcing installation of the separately built wheels onto the Agent's Python environment.
- I hope to …
=> Build cyrus-sasl statically into librdkafka for inclusion in wheel (Linux)

.gitlab-ci.yml
Run the `release-auto` GitLab job on release branches
- Currently we only run this job on the master branch
- When we need to release something off another branch, we need to rely on the [manual job](https://github.com/DataDog/integrations-core/blob/florentclarret/release_branch/.gitlab-ci.yml#L192-L212) that is triggered once we pushed the release tag with `ddev release tag`
- We often release integrations from the release branch, and we will do that more and more often in the future, to the point where releasing the integrations off the release branch will be the norm, and no longer the exception
- Running this job on release branches will allow us to avoid forgetting about pushing the tags
Note that for beta releases we can still manually push the tag to another branch to trigger the …
=> Run the `release-auto` GitLab job on release branches

postgres/assets/dashboards/postgresql_screenboard_dashboard.json
- Removes literal `scope` tag prefix.
- Apply template variable `$scope` to missed widgets.
- Rename duplicated "Top function calls" widget.
SDBM-815
=> [Postgres] fix OOB screeboard

postgres/assets/configuration/spec.yaml, postgres/changelog.d/16834.changed, postgres/datadog_checks/postgres/data/conf.yaml.example, postgres/datadog_checks/postgres/metadata.py
[DBMON-3579]
We are currently excluding tables from schema collection if we don't have metrics data for them. This is unexpected behavior: we would expect collected schemas to be complete, even if we are collecting table metrics from a subset of tables. 
[DBMON-3579]: https://datadoghq.atlassian.net/browse/DBMON-3579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> postgres schemas: don't exclude tables without metrics from schema collection

.github/workflows/labeler-reusable.yml
The former token no longer has SSO. We need SSO to create the token if it does not exist, not to apply labels.
I'm creating a GH app right now to replace the old bot
=> Update the labeler token

.ddev/config.toml, ddev/changelog.d/16845.fixed, ddev/src/ddev/cli/validate/labeler.py, ddev/tests/cli/validate/conftest.py
Extract hardcoded additional integrations from the `validate labeler` command to the config file
This config file is there to avoid hardcoded values in ddev
=> Extract hardcoded additional integrations from the `validate labeler` command to the config file

.ddev/config.toml, ddev/changelog.d/16846.fixed, ddev/src/ddev/cli/dep.py, ddev/tests/cli/test_dep.py
Extract hardcoded dependencies from the `dep updates` command to the config file
- This will avoid us to clutter the changelog with "allow ddev to bump XYZ dependencies".
- This config file is there to avoid hardcoded values in ddev
=> Extract hardcoded dependencies from the `dep updates` command to the config file

.builders/lock.py, .builders/scripts/build_wheels.py, .builders/upload.py
- Makes all built wheels use a build number
- Generate the full lock file as a final step
- Use direct references
- Using a build number allows us to make changes in our build system without overwriting filenames which would break expected hashes during Agent builds
- Also some built packages on Linux don't actually produce unique filenames because they are actually pure Python and therefore the hash becomes tied to whatever happens to be uploaded last
=> Lock dependencies with direct references

directory/tests/test_directory.py
Not whether a private method was invoked.
Make test less coupled to check implementation.
=> Make assertions only about behavior in test

ddev/changelog.d/16859.added, ddev/src/ddev/cli/test/__init__.py, ddev/tests/cli/test/test_test.py
Add the `all` argument to `ddev test`
I wanted to run black on every single integration but could not with `ddev test all -fs`
=> Add the `all` argument to `ddev test`

postgres/tests/test_pg_integration.py
Mark the `test_backend_transaction_age` as flaky
https://github.com/DataDog/integrations-core/actions/runs/7883762572/job/21511447542?pr=16857
https://datadoghq.atlassian.net/browse/DBMON-3591
=> Mark the `test_backend_transaction_age` as flaky

amazon_msk/changelog.d/16858.added, amazon_msk/pyproject.toml, datadog_checks_base/changelog.d/16858.added, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/pyproject.toml, ibm_i/changelog.d/16858.added, ibm_i/pyproject.toml, postgres/changelog.d/16858.added, postgres/pyproject.toml, sqlserver/changelog.d/16858.added, sqlserver/pyproject.toml
Bump dependencies
Part of the release process
=> Bump dependencies

nginx/changelog.d/16797.fixed, nginx/datadog_checks/nginx/nginx.py, nginx/tests/test_e2e.py, nginx/tests/test_nginx.py, nginx/tests/test_plus_api.py, nginx/tests/test_vts.py
Modify the tags for metrics to behave the same as service checks.
Only Service Checks are tagged with `nginx_host`, while metrics do not have the `nginx_host` tag.
Why don't we add normalized generic tags to metrics as service check?
```
$ sudo -u dd-agent datadog-agent check nginx
...
=== Series ===
....
{
"metric": "nginx.net.connections",
"points": [
[
1707205887,
1
]
],
"tags": [],  <<--- WATCH
"host": "i-09df1e4674d40f561",
"type": "gauge",
"interval": 0,
"source_type_name": "System"
}
]
=== Service Checks ===
[
{
"check": "nginx.can_connect",
"host_name": "i-09df1e4674d40f561",
"timestamp": 1707205887,
"status": 0,
"message": "",
"tags": [
"nginx_host:localhost", <<--- WATCH
"port:80"
]
}
]
```
AFTER THIS PR
```
{
"metric": "nginx.net.waiting",
"points": [
[
1707206029,
0
]
], …
```
=> nginx: metrics should have same tags as service checks

.builders/images/install-from-source.sh, .builders/images/macos/builder_setup.sh, .builders/images/macos/extra_build.sh
Compile `cyrus-sasl` statically for macOS.
Follow-up to #16827.
=> Build cyrus-sasl statically into librdkafka for inclusion in wheel (macOS)

postgres/changelog.d/16870.changed, postgres/datadog_checks/postgres/config.py
We want to decouple schema collection from relations metrics, so remove this configuration enforcement.
=> [DBMON-3579] don't require relation metrics to be enabled to collect schemas

ddev/changelog.d/16836.added, ddev/src/ddev/cli/meta/scripts/serve_openmetrics_payload.py
Add a `config` option to the `serve-openmetrics-payload` script.
- By default we only set the `openmetrics_endpoint`
- The endpoint will be overriden no matter what to use the right URL to collect the metrics
Example:
```
❯ cat config.yaml
instances:                                                                                                                                                                                                                                                                                                                                                
- openmetrics_endpoint: test
min_collection_interval: 10
❯ ddev meta scripts serve-openmetrics-payload -c config.yaml ray ray_worker.txt
Digest: sha256:3c1672ec3ce46edea83bac19ec5d1347793218f23a60565f5b00430ecebf2 …
```
=> Add a `config` option to the `serve-openmetrics-payload` script.

postgres/assets/configuration/spec.yaml, postgres/changelog.d/16880.fixed, postgres/datadog_checks/postgres/data/conf.yaml.example, postgres/datadog_checks/postgres/metadata.py
[DBMON-3483] 
Until recently we required table metrics to be enabled to collect table information via schemas collection. Relation metrics have a default limit of 300 relations, this provided a hidden default of 300 relations we would collect via schema collection.
Since we no longer require relation metrics for schema collection, we are lowering the default relations collection limit for schemas to match the previous hidden default. 
[DBMON-3483]: https://datadoghq.atlassian.net/browse/DBMON-3483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> update default table schema collection limit to 300

mysql/hatch.toml
This PR updates test env mariadb 10.10 to 10.11. mariadb 10.10 is deprecated in https://github.com/bitnami/containers/pull/56652
=> [DBMON-3435] Update mariadb 10.10 to 10.11

nginx/changelog.d/16797.fixed, nginx/changelog.d/16872.fixed, nginx/datadog_checks/nginx/nginx.py, nginx/tests/test_e2e.py, nginx/tests/test_nginx.py, nginx/tests/test_plus_api.py, nginx/tests/test_vts.py
This reverts commit a0d9e91.### What does this PR do?
There are problems in the webapp with us submitting metrics tagged as `host`. It's too close to a release for us to investigate this properly, so we're reverting all changes for now.
fyi @keisku we'll have to tackle this again in the next release, I'm afraid.
=> Revert nginx tag changes (#16872 and #16797)

postgres/changelog.d/16895.changed, postgres/datadog_checks/postgres/config.py, postgres/datadog_checks/postgres/postgres.py, postgres/tests/common.py, postgres/tests/conftest.py, postgres/tests/test_custom_metrics.py, postgres/tests/test_deadlock.py, postgres/tests/test_e2e.py, postgres/tests/test_logical_replication.py, postgres/tests/test_pg_integration.py, postgres/tests/test_pg_replication.py, postgres/tests/test_relations.py, postgres/tests/test_replication_slot.py, postgres/tests/test_statements.py, postgres/tests/test_unit.py
Enable tag replication role by default.
The tag information (`master` or `standby`) is extremely useful to have to identify who is the primary in a cluster. It is also cheap to get (only a call to `pg_is_in_recovery`) and a db host will mostly be tagged with a single value except when a promotion happens. By enabling it by default, we can rely on its presence for other part of the product like watchdog alerts. 
The unit test `test_replication_stats` was removed as it was redundant with integration test done on a replica. 
`test_replication_tag` was moved from test_unit since it relies on an existing pg_instance.
=> PG: Collection replication role tag by default

postgres/changelog.d/16900.added, postgres/datadog_checks/postgres/postgres.py, postgres/tests/common.py, postgres/tests/test_e2e.py, postgres/tests/test_logical_replication.py, postgres/tests/test_pg_integration.py, postgres/tests/test_pg_replication.py, postgres/tests/test_statements.py
Add a new `postgresql_version` tag to all metrics.
Making version available as a metric tag provides multiple benefits:
- We can observe the change of version from minor or major upgrades that could explain instance restarts during a maintenance windows.
- We can list the number of instances per version and track outdated clusters
`copy.tag` was removed as `self.gauge` is already creating a copy of normalised tags so there's no need for this additional copy.
=> Add PG server version as tag

.gitlab/validate-agent-build/trigger_agent_build.py
Add `RUN_E2E_TESTS=off` environment variable to child `datadog-agent` child pipeline, according to https://github.com/DataDog/datadog-agent/blob/main/.gitlab-ci.yml#L214
Disable e2e tests when running datadog-agent children pipelines. The goal of those pipelines is to ensure the build and packaging steps still work when we update dependencies on integrations-core side.
=> [gitlab] disable e2e tests in child agent pipeline

.gitlab/validate-agent-build/trigger_agent_build.py
Use `BUCKET_BRANCH: "dev"` and `DEPLOY_AGENT: "false"` instead of `BUCKET_BRANCH: "none"`
`BUCKET_BRANCH: "none"` is a legacy value, moving to defaults values, but using explicit here for readability. `BUCKET_BRANCH: "dev"` allows to avoid issues such as this [datadog-agent child pipeline](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/28491285) that was running some post build jobs like kitchen deploy ones, that deploy for tests, and failing as deployment jobs were uploading packaging missing the pipeline id. 
Test deployments should always include the pipeline_id. We'll come back to merge the `"RUN_KITCHEN_TESTS": "false", "RUN_E2E_TESTS": "off"` options when working on  https://datadoghq.atlassian.net/browse/APL-2844
=> [gitlab] improve datadog-agent pipeline variables

argocd/README.md, argocd/changelog.d/16897.added, argocd/datadog_checks/argocd/metrics.py, argocd/metadata.csv
PR adds the `argocd_app_labels` argocd metric for collection
Having app labels available in a metric will be useful for routing alerts using ArgoCD metrics based on application labels
- [Exposing Application Labels as Prometheus Metrics](https://argo-cd.readthedocs.io/en/stable/operator-manual/metrics/#exposing-application-labels-as-prometheus-metrics)
=> feat: Collect 'argocd_app_labels' argocd metric

sqlserver/tests/common.py, sqlserver/tests/test_activity.py
Skip `test_activity_nested_blocking_transactions` on windows sqlserver 2019 as it's flaky
=> test_activity_nested_blocking_transactions is flaky

postgres/changelog.d/16911.added, postgres/datadog_checks/postgres/postgres.py, postgres/tests/common.py, postgres/tests/test_e2e.py, postgres/tests/test_pg_integration.py
Add `system_identifier` tag to all PostgreSQL metrics.
[pg_control_system](https://pgpedia.info/p/pg_control_system.html) was introduced in PG 9.6 and expose the `system_identifier` from the control file. 
This `system_identifier` is initialised during initdb to identify an installation in an unique way. An interesting property of this system identifier is that it is shared between the primary and its replicas. This means we can use it as a way to identify clusters and aggregate/filter metrics per cluster.
=> PostgreSQL: Add system_identifier as a metric tag

datadog_checks_dev/changelog.d/16917.fixed, datadog_checks_dev/datadog_checks/dev/tooling/commands/create.py, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/datadog_checks/{check_name}/__about__.py, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/datadog_checks/{check_name}/__about__.py, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/datadog_checks/{check_name}/__about__.py
Follow-up to [Different changelog template depending on release process.](https://github.com/DataDog/integrations-core/pull/16693), we just forgot to change the `__about__.py` version too. Noticed this when fixing manually some of the new integrations.
=> starting version in templates aligns with changelog type

otel/assets/dashboards/otel_collector_metrics_dashboard.json
Adds two new groups to the OOTB OTel Collector metrics dashboard:
Datadog Exporter: Traffic Sent
Datadog Connector: Stats Sent
These two groups offer more observability into our collector components and the metrics are generated by the trace agent.
=> Edit OTel Collector dashboard to include Datadog Exporter and Datadog Connector metrics

otel/assets/dashboards/otel_collector_metrics_dashboard.json
Updates OOTB OTel Collector dashboard to change column break group.
Before:
After:
=> Update OTel Collector dashboard column break group

active_directory/README.md, active_directory/assets/configuration/spec.yaml, active_directory/datadog_checks/active_directory/data/conf.yaml.example, active_directory/manifest.json
removing references to Logs feature that doesn't exist, undoing this PR: https://github.com/DataDog/integrations-core/pull/1813/files
https://datadoghq.atlassian.net/browse/WINA-649
=> remove Logs from Active Directory docs

mysql/changelog.d/16936.fixed, mysql/datadog_checks/mysql/statement_samples.py, mysql/tests/test_statements.py
This PR handles the case when events_statements_* `timer_end` overflows. `timer_end` is in picosecond has column type `BIGINT`, when it overflows and wrapped around, the calculated of statement timestamp based on server `UPTIME` could become stale. 
This PR handles this case by calculate "how many time timer_end overflowed" and makes up the difference. 
MySQL explain plan events are dropped when timestamp is stale. This change ensures we don't get a stake timestamp.
=> [DBMON-3642] Proper handle events_statements_* timer_end overflow

aerospike/manifest.json
Metric to check is using a legacy one. This PR adds a new metric from the OMv2 implementation.
=> Fix metric to check aerospike

fluxcd/README.md
Update the documentation for FluxCD integration to point the openmetrics endpoint towards the [default location](https://fluxcd.io/flux/monitoring/metrics/#controller-metrics). 
The configuration did not work when copy pasting.
=> Fix fluxcd default address documentation

datadog_cluster_agent/CHANGELOG.md, datadog_cluster_agent/changelog.d/16928.added, datadog_cluster_agent/datadog_checks/datadog_cluster_agent/__about__.py, requirements-agent-release.txt
Port https://github.com/DataDog/integrations-core/pull/16967 to master
=> [Release] Bumped datadog_cluster_agent version to 2.11.0 (#16967)

.builders/images/linux-x86_64/Dockerfile
It changes how Python is compiled in builders so that no shared library is created.
This causes some extensions to link against libpython which then causes problems with the omnibus healthcheck. This is also a simpler and less fragile setup w.r.t. how python finds libpython; the `--enable-shared` was carried over from copying what we do in Omnibus.
=> Don't build shared libraries when compiling python on builders

.builders/images/macos/builder_setup.sh, .builders/scripts/repair_wheels.py
Compiles zlib for macOS so that it can be included in wheels.
Omnibus health check complains about it; for consistency with other OSes and with what we've been doing, I think it's best to just include it in wheels as needed.
=> Add zlib to macOS builder

.github/CODEOWNERS, .gitlab-ci.yml, .gitlab/software_composition_analysis.yaml
Add a new Gitlab CI job listing this repository dependencies with trivy and uploading them to Datadog. This will make it possible to use the SCA product for this repository (see https://app.datadoghq.com/ci/code-analysis?limit=100&offset=0).
@DataDog/software-integrity-and-trust partners with @DataDog/static-analysis to dogfood their SCA product and secure Datadog's supply chain.
[Successful CI run](https://gitlab.ddbuild.io/DataDog/integrations-core/-/jobs/440579100)
=> [SINT-1841] Run Datadog SCA in the CI

mysql/datadog_checks/mysql/statement_samples.py
This PR fixes the max value for `timer_end` because the column type is `bigint unsigned`. 
Skipping changelog as this PR is just a fix of #16936
=> timer_end is bigint unsigned

.builders/images/macos/builder_setup.sh, .builders/images/macos/extra_build.sh, .github/workflows/build-deps.yml
Cache whatever the builder setup stores inside the "builder root". This is an attempt at mimicking the caching that we get with Docker for all the other platforms.
Most of the necessary machinery was already in place the implementation of the builder setup was done with this in mind. This just adds the necessary code to the CI workflow.
=> Implement builder caching for macOS build

.github/workflows/update-dependencies.yml
Add the `qa/skip-qa` label to PRs that bump dependencies
- We used to not QA these kind of PRs and I forgot to add the label when I added the bot
- We do not really need to check anything if the tests are all green in the CI
=> Add the `qa/skip-qa` label to PRs that bump dependencies

mysql/assets/configuration/spec.yaml, mysql/changelog.d/16988.added, mysql/datadog_checks/mysql/config.py, mysql/datadog_checks/mysql/config_models/defaults.py, mysql/datadog_checks/mysql/config_models/instance.py, mysql/datadog_checks/mysql/data/conf.yaml.example, mysql/datadog_checks/mysql/mysql.py, mysql/tests/test_connection.py
This PR adds a new config option `read_timeout` to specify the timeout for reading from the connection in seconds. The default `read_timeout` is 10s.
=> [DBMON-3557] add read_timeout for reading from the connection in seconds

postgres/assets/configuration/spec.yaml, postgres/changelog.d/16990.added, postgres/datadog_checks/postgres/config.py, postgres/datadog_checks/postgres/data/conf.yaml.example, postgres/datadog_checks/postgres/postgres.py, postgres/tests/test_pg_integration.py
This PR makes existing config `collect_wal_metrics` applicable for all postgres versions. 
Prior to this PR, WAL file metrics are collected by default on PG version 10 using function `pg_ls_waldir`. However executing `pg_ls_waldir` function requires `cloudsqlsuperuser` role on GCP Cloud SQL for Postgres. Granting superuser role to datadog monitoring user is often not recommended. As a workaround, we suggest user to create a stored procedure with superuser access and grant the execution privilege to datadog user.  The workaround resolves the issue of collecting WAL file metrics, but it does not stop error messages flood in agent log.
This PR let user set `collect_wal_metrics` to false to disable collecting WAL file metics from function `pg_ls_waldir`.
=> [DBMON-3691] set collect_wal_metrics to false will disable wal file metrics collection for all pg versions

datadog_checks_base/changelog.d/16958.added, datadog_checks_base/datadog_checks/base/utils/db/core.py, datadog_checks_base/datadog_checks/base/utils/db/query.py, datadog_checks_base/tests/base/utils/db/test_custom_queries.py, datadog_checks_base/tests/base/utils/db/test_query_executor.py, oracle/changelog.d/16958.fixed, oracle/datadog_checks/oracle/oracle.py
This PR adds an optional `metric_prefix` to QueryExecutor to support override the default metric prefix `<INTEGRATION>` namespace. When `metric_prefix` is set to none empty string, the custom query metrics will use the provided metric_prefix instead of the integration namespace. 
TODO: custom_queries configuration template change will be updated in follow up PR.
This is the first step to migrate Postgres custom_queries to `QueryManager`. Postgres integration custom_queries currently support customizable `metric_prefix` as documented [here](https://docs.datadoghq.com/integrations/faq/postgres-custom-metric-collection-explained/#configuration). Customer has found this `metric_prefix` useful as it overrides the default `postgresql` metric prefix. For example, customer can have a simple query …
=> support custom metric_prefix in QueryExecutor

nfsstat/manifest.json
Add source_type_id and auto_install to the nfsstat integration manifest
Because this integration has logs assets defined, I need to allow it to go through APW. In order to remove this integration from the blacklist, it needs to have all the expected manifest fields
Note: I generated this source_type_id by running `ddev create` and took the generated value.
=> Add source_type_id and auto_install to nfsstat integration folder

postgres/assets/configuration/spec.yaml, postgres/changelog.d/17005.removed, postgres/datadog_checks/postgres/config.py, postgres/datadog_checks/postgres/config_models/instance.py, postgres/datadog_checks/postgres/data/conf.yaml.example, postgres/datadog_checks/postgres/postgres.py, postgres/tests/conftest.py, postgres/tests/test_metrics_cache.py, postgres/tests/test_pg_integration.py
Effectively reverts https://github.com/DataDog/integrations-core/pull/16540, since we have since changed how we pass auto discovery configuration to the agent
=> Remove unnecessary logic around init config auto discovery configuration

kafka_consumer/tests/common.py, kafka_consumer/tests/conftest.py, kafka_consumer/tests/test_integration.py
Add a condition to the e2e env to make sure we can get the cluster id
Sometimes this info is not yet available and the broker does not respond https://github.com/DataDog/integrations-core/actions/runs/8093321612/job/22115795857#step:15:779
=> Make the e2e environment less flaky

gitlab/tests/test_e2e.py
Mark the `test_e2e` test flaky and retry it if needed
GitLab can start returning 502s even after all the conditions in the e2e env were met: https://github.com/DataDog/integrations-core/actions/runs/8092578398/job/22113596713#step:15:497
The previous test ran successfully so GitLab returned a 200, I'm not sure we can do anything about it, besides retrying 🙁 We have unit tests to cover this error
=> Mark the `test_e2e` test flaky and retry it if needed

mysql/changelog.d/17002.fixed, mysql/datadog_checks/mysql/activity.py, mysql/datadog_checks/mysql/metadata.py, mysql/datadog_checks/mysql/mysql.py, mysql/datadog_checks/mysql/statement_samples.py, mysql/datadog_checks/mysql/statements.py, mysql/datadog_checks/mysql/util.py
- Sets the autocommit explicitly when opening a new connection.
PyMYSQL will only set autocommit as true when it detects from the server status that it's disabled. We suspect that there are some situations such as [this](https://repost.aws/questions/QUSRDBZhpGQjibIl0xUQTe5w/mysql-aurora-8-0-and-pymysql-issue-with-autocommit), [this](https://github.com/dolthub/dolt/issues/1712) or [this](https://bugs.mysql.com/bug.php?id=66884) where MySQL is misreporting the autocommit status.
=> [MySQL] - SDBM-830 - Make the autocommit explicit

postgres/changelog.d/17007.added, postgres/datadog_checks/postgres/postgres.py, postgres/datadog_checks/postgres/util.py, postgres/tests/test_connections.py, postgres/tests/test_pg_integration.py, postgres/tests/test_statements.py
This PR adds an explicit postgres database connection health check at the start of every check run. 
Postgres integration establish the database connection on first check run and maintains the open connection until the check is canceled or closed by server. Prior to the PR, the integration implicitly relies on query operations performed on the open connection to update the Service Check status `postgres.can_connect`. When an uncaught exception is raised, the service check will be updated to `CRITICAL`. 
This PR performs explicit health check by executing a simple `SELECT 1` to ensure the connection is healthy.
=> [DBMON-3288] Perform database connection health check at the start of check run

ddev/changelog.d/17019.fixed, ddev/src/ddev/cli/validate/manifest.py, ddev/tests/cli/validate/test_manifest.py, ddev/tests/conftest.py
Remove references to the old validate manifest command
Missed in https://github.com/DataDog/integrations-core/pull/17008, we now use the endpoint and the `validate-manifest` job to validate it
=> Remove references to the old validate manifest command

datadog_cluster_agent/CHANGELOG.md, datadog_cluster_agent/changelog.d/17001.fixed, datadog_cluster_agent/datadog_checks/datadog_cluster_agent/__about__.py, requirements-agent-release.txt
Port https://github.com/DataDog/integrations-core/pull/17013 to master
=> [Release] Bumped datadog_cluster_agent version to 2.11.1 (#17013)

ddev/changelog.d/17021.fixed, ddev/src/ddev/utils/github.py
Fix a deprecation warning 
```tests/utils/test_github.py::TestCreateLabel::test_create_label
/Users/florent.clarret/Library/Application Support/hatch/env/virtual/ddev/U6fecnxT/ddev/lib/python3.11/site-packages/httpx/_content.py:204: DeprecationWarning: Use 'content=<...>' to upload raw bytes/text content.
warnings.warn(message, DeprecationWarning)
```
=> Fix a deprecation warning

sqlserver/assets/configuration/spec.yaml, sqlserver/changelog.d/16977.fixed, sqlserver/datadog_checks/sqlserver/config.py, sqlserver/datadog_checks/sqlserver/config_models/defaults.py, sqlserver/datadog_checks/sqlserver/config_models/instance.py, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example, sqlserver/datadog_checks/sqlserver/sqlserver.py
This PR filters out tempdb from the index usage query.
In the sqlserver integration a query collects statistics on the index usage. This query was flagged as blocking - https://datadoghq.atlassian.net/browse/DBMON-3582. As tempdb is an internal DB used to store temporary data it was decided to not query it's index usage.
=> [DBMON-3582] Skip index usage collection for tempdb

sqlserver/changelog.d/17020.fixed, sqlserver/datadog_checks/sqlserver/activity.py, sqlserver/datadog_checks/sqlserver/statements.py, sqlserver/tests/test_activity.py
Fixes an issue where enabling obfuscation error logging would still hide the statement text if the statement is part of a stored procedure. 
Customers enabling the logging of obfuscation errors can't debug which statement is causing the issue.
=> [SQLServer] - Improve the logging around query obfuscation errors

ddev/tests/cli/meta/scripts/conftest.py, ddev/tests/cli/meta/scripts/test_upgrade_python.py, ddev/tests/conftest.py
We're not sure why this breaks tests on master and not on PRs. Conceptually it's a problem because our github checkout actions only grab 1 commit, so we shouldn't have access to the full git history.
=> Revert ddev fixture pin

.github/CODEOWNERS
Similar to https://github.com/DataDog/marketplace/pull/1025
The goal is to make @DataDog/logs-backend be CODEOWNERS of any integration's logs pipeline. 
I updated all integration codeowners to reflect this while still leaving their current owners in place.
=> [ECOS-1235] Add logs-backend to CODEOWNERS of assets/logs files

datadog_checks_dev/changelog.d/17042.fixed, datadog_checks_dev/pyproject.toml
Pin pytest to fix `flaky` issues
https://github.com/box/flaky/issues/198
https://github.com/iiasa/ixmp/pull/519
=> Pin pytest to fix `flaky` issues

.github/workflows/docs.yml
Only run the `docs` job when needed on PRs
This job takes ~8 minutes, let's not run it if not strictly needed
=> Only run the `docs` job when needed on PRs

.builders/lock.py
Adds a missing pattern to the patterns we use to match platforms when resolving the final lock file.
PyYAML was failing to resolve: https://github.com/DataDog/integrations-core/actions/runs/8114079173/job/22188895871#step:8:31
The reason being that the file we're uploading in that case is named `PyYAML-5.4.1-1-cp27-cp27mu-linux_aarch64.whl` which wasn't matched by our logic, causing this specific dependency (pyyaml 5.4.1 for py2 for aarch64) to not be found.
=> Add `linux_aarch64` as pattern for arm64 linux lockfile resolution

.builders/scripts/repair_wheels.py
Adds a step on wheel repair to handle platform-independent wheels such that wheels we build ourselves will always have a platform tag.
Since we build wheels unconditionally for all platforms (regardless of whether we've already built a compatible wheel while building for a different platform), we get different versions of the same wheel with slight differences in how the metadata is formatted (resulting in different hashes). This is a simple workaround to make it easier to upload wheels when we really need to.
For Linux, I'm relying on the `NonPlatformWheel` exception raised by `auditwheel` (which is raised when no platform-dependent files are found within the wheel); since I couldn't find anything similar for `delvewheel` and `delocate`, I simply based the logic on the presence of the …
=> Ensure all wheels that we build have a platform tag

.github/workflows/config/labeler.yml, airflow/datadog_checks/airflow/__about__.py
Fix the labeler config for releases 
In https://github.com/DataDog/integrations-core/pull/16729 we drop the requirement file because it is not needed. However `*/__about__.py` is wrong because this file is in a sub-directory. So this pattern basically never worked 😅 
Spotted on https://github.com/DataDog/integrations-core/pull/17053
=> Fix the labeler config for releases

.builders/tests/test_upload.py, .builders/upload.py
- Take compatibility tags (python, abi, platform) into account when comparing an upload candidate to existing packages in the repository.
- Use only the build number when deciding which is the most recent package to upload against.
Follow up to #16993. I realized that we were still re-uploading many more packages than expected and this was the most obvious reason.
=> Take compatibility tags into account when comparing packages to upload

clickhouse/assets/configuration/spec.yaml, clickhouse/changelog.d/17061.fixed, clickhouse/datadog_checks/clickhouse/data/conf.yaml.example, snowflake/assets/configuration/spec.yaml, snowflake/changelog.d/17061.fixed, snowflake/datadog_checks/snowflake/data/conf.yaml.example, vertica/assets/configuration/spec.yaml, vertica/changelog.d/17061.fixed, vertica/datadog_checks/vertica/data/conf.yaml.example
Document the `metric_prefix` option for custom queries
Added in https://github.com/DataDog/integrations-core/pull/16958
=> Document the `metric_prefix` option for custom queries

datadog_checks_dev/changelog.d/17066.fixed, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/models.py
Print the info logs in the correct order in the `validate models -s` command
Before:
```
❯ ddev validate models disk -s
Validating data models for 1 checks ...                                                                                                                                                                                                                                                                                                                           ─╯
Writing data model file to `/Users/florent.clarret/go/src/github.com/DataDog/integrations-core/disk/datadog_checks/disk/config_models/defaults.py`
Writing data model file to `/Users/florent.clarret/go/src/github.com/DataDog/integrations-core/disk/datadog_checks/disk/config_models/instance.py`
disk:
All 5 data model files …
```
=> Print the info logs in the correct order in the `validate models -s` command

teleport/datadog_checks/teleport/check.py, teleport/datadog_checks/teleport/metrics.py, teleport/tests/fixtures/metrics.txt, teleport/tests/test_auth.py, teleport/tests/test_common.py, teleport/tests/test_integration.py, teleport/tests/test_proxy.py
Reports metrics for the Auth Service and Backends as documented [here](https://goteleport.com/docs/reference/metrics/#auth-service-and-backends).
Fixes some auth metrics that were reported as proxy metrics `grpc_server*`.
https://datadoghq.atlassian.net/browse/PLINT-303
=> [PLINT-303] Report Teleport Auth Service and Backends metrics

.builders/images/linux-aarch64/Dockerfile, .builders/images/linux-aarch64/build_script.sh
- Move platform-based requirements logic to environment markers.
- Remove patching and rust installation inherited from the equivalent x64 images.
I was looking into some other aarch64 related failure when I realized that I had missed these possible improvements when we originally introduced this builder. Considering how long aarch64 builds currently take, the pydantic-core and rust related removals should at least help a little.
=> Streamline aarch64 dependency build.

.pre-commit-config.yaml
Add a pre-commit hook to validate service checks
Got an error in https://github.com/DataDog/integrations-core/pull/17070/files that could be easily validated before
The validate is blazing fast so it should not be a problem.
Example:
```
❯ pre-commit
Run linters..........................................(no files to check)Skipped                                                                                                                                                                                                                                                                                   
Validate service checks..................................................Failed
- hook id: service_checks
- exit code: 1
Validating service_checks.json files for 227 checks ... …
```
=> Add a pre-commit hook to validate service checks

sqlserver/changelog.d/17063.fixed, sqlserver/datadog_checks/sqlserver/const.py, sqlserver/datadog_checks/sqlserver/sqlserver.py, sqlserver/tests/test_metrics.py
This PR skips `sqlserver.latches.latch_wait_time` metric on sqlserver versionn 2014 and lower.
The base counter `Average Latch Wait Time Base` is available starting with SQL Server 2016. Without the base counter, the integration is not able to compute the `sqlserver.latches.latch_wait_time` metric.
Below docs show no `Average Latch Wait Time Base` counter in SQL Server 2012 and 2014. 
- [SQL Server 2012](https://learn.microsoft.com/en-us/previous-versions/sql/sql-server-2012/ms177421(v=sql.110))
- [SQL Server 2014](https://learn.microsoft.com/en-us/previous-versions/sql/2014/relational-databases/performance-monitor/sql-server-latches-object?view=sql-server-2014)
=> [SDBM-857] skip sqlserver.latches.latch_wait_time metric on sqlserver version 2014 and lower

journald/README.md
This PR adds the fact that to collect all logs, we do not need to add a wildcard to the `include_units` section.
- Working on a customer case [AGENT-11124], we discovered that the following prevented log collection:
```
include_units: 
- *
```
- https://github.com/DataDog/datadog-agent/blob/7.50.x/pkg/logs/tailers/journald/tailer.go#L116-L126
[AGENT-11124]: https://datadoghq.atlassian.net/browse/AGENT-11124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adding further information regarding `include_units`

.builders/tests/test_upload.py, .builders/upload.py
- Fixes the timestamp format used in uploaded build numbers.
- Fixes how candidates to matched are obtained. I misunderstood how `match_glob` works in my initial implementation and it wasn't really matching anything.
- Adds an additional log file for more visibility.
Found that new builds were being uploaded even when it wasn't necessary.
=> Fix matching built wheels in uploading logic

confluent_platform/changelog.d/17107.fixed, confluent_platform/datadog_checks/confluent_platform/data/metrics.yaml
Changed 'falied' to 'failed' in the status attribute values of Kafka Connect Metrics. This correction ensures accurate status tracking for connectors.
This pull request corrects a spelling error in the Kafka Connect Metrics. Specifically, it changes 'falied' to 'failed' in the status attribute values.
The motivation for this change was to ensure accurate status tracking of Kafka connectors. The incorrect spelling could potentially lead to misinterpretation of the connector status, affecting monitoring and debugging processes.
=> fix: Corrected spelling error in Kafka Connect Metrics

.ddev/config.toml
Allow ddev to bump cryptography, orjson and pydantic
https://github.com/DataDog/integrations-core/pull/17054
=> Allow ddev to bump cryptography, orjson and pydantic

LICENSE-3rdparty.csv, btrfs/changelog.d/17112.added, btrfs/pyproject.toml, datadog_checks_base/changelog.d/17112.added, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, disk/changelog.d/17112.added, disk/pyproject.toml, gunicorn/changelog.d/17112.added, gunicorn/pyproject.toml, ibm_mq/changelog.d/17112.added, ibm_mq/pyproject.toml, network/changelog.d/17112.added, network/pyproject.toml, process/changelog.d/17112.added, process/pyproject.toml, system_core/changelog.d/17112.added, system_core/pyproject.toml, system_swap/changelog.d/17112.added, system_swap/pyproject.toml
Revert https://github.com/DataDog/integrations-core/pull/16547
We have a performance regression issue, see #incident-25881
=> Revert "Bump psutil version to 5.9.7 (#16547)" 

mysql/changelog.d/17029.fixed, mysql/datadog_checks/mysql/activity.py, mysql/tests/compose/mysql.conf, mysql/tests/test_query_activity.py
This PR add `digest_text` to MySQL activity query and use `digest_text` (post obfuscation) to computed query signature whenever `digest_text` is not NULL. 
Prior to the change, `query_signature` differs in Query Samples & Explain Plans
With this fix, `query_signature` is the same now  in Query Samples & Explain Plans
The PR fixes an annoying mismatch in query_signature between MySQL query activity and explain plan
`digest_text` can be NULL in MySQL version < 8.0 even when `statements_digest` consumer is enabled.
=> [DBMON-2609] use digest_text to compute query signature for collected activities

otel/assets/dashboards/otel_collector_metrics_dashboard.json
Updates the following sections in the default OTel Collector dashboard:
=> Update default OTel Collector dashboard with telemetry source tag

.pre-commit-config.yaml
Add a pre-commit hook to validate the labeler config
I left one error when I modified it in https://github.com/DataDog/integrations-core/pull/17132 that would have been caught by the validation command
=> Add a pre-commit hook to validate the labeler config

.github/workflows/config/labeler.yml
Automatically apply the `qa/skip-qa` to some PRs
So release PRs are skipped automatically by ddqa
=> Automatically apply the `qa/skip-qa` to some PRs

ddev/changelog.d/17136.fixed, ddev/src/ddev/cli/validate/metadata.py, ddev/src/ddev/repo/core.py, ddev/tests/repo/test_core.py
Fix the validation of metadata files 
The validation in the CI does not work anymore because `changed` is not recognized anymore and an empty list is now considered as `changed` in ddev while it used to be considered `all` in dcd 
I'll improve the testing part of the command in a follow-up PR. I want to bring the validation back ASAP
=> Fix the validation of metadata files

datadog_checks_base/changelog.d/17134.added, datadog_checks_base/datadog_checks/base/stubs/aggregator.py, datadog_checks_base/tests/stubs/test_aggregator_metric_has_tag.py
Add a method to assert several metric tags at once
I always end up in my tests with something like this
```python
for tag in tags:
self.assert_metric_has_tag(metric_name, tag)
```
Having it (and tested) in the aggregator will allow me to avoid copy/paste stuff around
=> Add a method to assert several metric tags at once

.github/workflows/build-deps.yml
Run aarch64 build natively instead of through QEMU.
Native arm64 runners being made available.
=> Use arm64 runners to run arm64 build

kube_scheduler/changelog.d/17110.added, kube_scheduler/datadog_checks/kube_scheduler/kube_scheduler.py, kube_scheduler/tests/fixtures/metrics_1.29.0.txt, kube_scheduler/tests/test_kube_scheduler_1_29.py
Adds support for the new `scheduler_pod_scheduling_sli_duration_seconds` metric. It was introduced in Kubernetes 1.29 and replaces the now deprecated `scheduler_pod_scheduling_duration_seconds`.
The tests added follow the same structure as the existing ones but use an input based on Kubernetes 1.29.
=> Support new `scheduler_pod_scheduling_sli_duration_seconds` metric

.builders/build.py, .builders/images/linux-aarch64/Dockerfile, .builders/images/linux-x86_64/Dockerfile
Adds `--strip-debug` linker flag so that all binaries get stripped of debug symbols, reducing package size and improving reproducibility.
Looking for ways to improve build reproducibility and avoiding unnecessarily uploading equivalent packages.
=> Strip debug symbols in compiled dependencies

postgres/assets/configuration/spec.yaml, postgres/changelog.d/17109.changed, postgres/datadog_checks/postgres/data/conf.yaml.example, postgres/datadog_checks/postgres/metrics_cache.py, postgres/datadog_checks/postgres/postgres.py, postgres/datadog_checks/postgres/util.py, postgres/tests/common.py, postgres/tests/test_pg_integration.py
Replace table count query from using `pg_stat_user_tables` view to directly calling `pg_class`. 
max_relation limit was also removed from the query.
We currently rely on `pg_stat_user_tables` to count the number of tables per schema. With a high number of tables, this view is expensive to query due to the order by and a lot of work is wasted as we ignore all toast tables and system schema like `pg_catalog` and `information_schema`.
We can replace this by a direct call to `pg_class`, filtering as much as possible early and keeping the price of `pg_namespace` join low by pushing the join to the end.
The `max_relation` limit was removed as keeping the results stable requires a sort on relation name and schema. That sort made the query more expensive than getting all results by far (see plans …
=> PostgreSQL: Optimise table count metrics

postgres/changelog.d/17144.added, postgres/datadog_checks/postgres/statements.py, postgres/tests/test_statements.py
Adds support for collecting wall metrics from postgres which become available after PG13.
The exact metrics are
- wal_bytes
- wal_fpi
- wal_records
These metrics are useful when tuning INSERT/DELETE/UPDATE operations
https://datadoghq.atlassian.net/browse/DBMON-3619
Backend Change Pr:https://github.com/DataDog/dd-go/pull/126362
=> [DBMON-3619] Add support for Postgres Wal metric

weblogic/assets/saved_views/weblogic_overview.json, weblogic/manifest.json
The WebLogic integration has an assets/saved_views folder but they weren't registered in the manifest. This PR adds them there. 
I'm looking to integration saved_views into APW and noticed this was missing during my testing.
=> Add the saved views to the weblogic manifest

docs/developer/guidelines/pr.md
- Changelog entries header is shared between different tabs.
- Shorter sections above changelog, less likely to be missed.
- Expand instructions for integrations-core.
Noticed when tried to link an external contributor to the docs.
=> More improvements to PR guidelines

cilium/assets/dashboards/overview_v2.json, cilium/manifest.json
Creates a new OOTB dashboard using OMv2 metrics for Cilium
https://datadoghq.atlassian.net/browse/AI-3780
=> add new OMv2 dashboard for cilium

sqlserver/changelog.d/17162.added, sqlserver/datadog_checks/sqlserver/connection.py, sqlserver/datadog_checks/sqlserver/cursor.py, sqlserver/datadog_checks/sqlserver/statements.py, sqlserver/pyproject.toml, sqlserver/tests/test_connection.py, sqlserver/tests/test_cursor.py, sqlserver/tests/test_statements.py, sqlserver/tests/test_unit.py
This PR uses `add_sql_comment` to tag all sqlserver integration queries with `service:datadog-agent`. This allows user to filter agent integration queries in query samples and explain plans.
=> tag sqlserver agent queries

openstack_controller/tests/conftest.py
Uses rest config as the default in the lab instance, while leaving the options for the SDK version in the config but commented out. 
the REST configuration of the openstack controller check is more common than the SDK config. So when testing it is usually more beneficial to test the REST method. The rest method also performs more custom logic so we often want to test it more thoroughly.
=> Use rest config by default in lab instance

argocd/README.md
[DOCS-7419](https://datadoghq.atlassian.net/browse/DOCS-7419)
This PR provides a link to the section of the `conf.yaml` example file so users can more easily see the list of additional supported endpoints to configure.
[DOCS-7419]: https://datadoghq.atlassian.net/browse/DOCS-7419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-7419] adding conf.yaml link to additional supported endpoints

.builders/images/linux-aarch64/Dockerfile, .builders/images/linux-aarch64/build_script.sh
- Install openssl in the default prefix and keep old openssl devel package uninstalled for the build. This makes it easy to find for programs looking for it in standard location.
- Always build pyodbc. Building pyodbc ourselves lets us include the odbc library in the wheel, which is the simplest way of preventing the omnibus healthcheck from flagging it.
Omnibus healthcheck reported failures ([example](https://gitlab.ddbuild.io/datadog/datadog-agent/builds/454874659)).
- Related to the openssl included in confluent-kafka
- Related to the odbc linked to by pyodbc.
In the case of openssl, this also brought to our attention that an old version of openssl was being included (the one installed via yum).
=> Builders: Install openssl in default prefix and always build pyodbc

datadog_checks_dev/datadog_checks/dev/_env.py, mapreduce/pyproject.toml
Print raw output of the agent if the metric name is empty. This won't be released
We try to debug [this](https://github.com/DataDog/integrations-core/actions/runs/8276747701/job/22645912805) in the CI which we can't reproduce locally. We think there's a bug in the aggregator, having the output will allow us to debug it
=> Print raw output of the agent if the metric name is empty

datadog_checks_base/changelog.d/17181.fixed, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/pyproject.toml
requests-oauthlib v1.4.0 drops python support without updating the wheel metadata. That's why we have to explicitly pin to a version that still works with python 2.
=> Pin requests-oauthlib for Py2

harbor/changelog.d/17194.fixed, harbor/datadog_checks/harbor/harbor.py, harbor/tests/common.py, harbor/tests/test_harbor.py
Add missing custom tags to the `can_connect` service check
https://github.com/DataDog/integrations-core/issues/17188
=> Add missing custom tags to the `can_connect` service check

sqlserver/datadog_checks/sqlserver/connection.py, sqlserver/datadog_checks/sqlserver/const.py, sqlserver/datadog_checks/sqlserver/sqlserver.py, sqlserver/tests/test_integration.py
This PR changes the way we perform service check for auto discovered databases on non Azure SQL dabases.
Creating a connection to each DB is costly and doesn't yield additional value when we can use 'use db_name'.
test is in tests/test_integration.py - test_autodiscovery_db_service_checks
We don't have an Azure test env, so only the newly added cost path will be tested.
We might wont to use an extra configuration parameter for testing or let be with the idea that we will get Azure test env eventually.
=> improve sqlserver db check

.builders/images/linux-aarch64/build_script.sh, .builders/images/linux-x86_64/build_script.sh
Fixes `PIP_NO_BINARY` syntax and ensures pyobdc is always built in linux
#17142 tried to force the installation of pyodbc for linux-aarch64 to avoid an omnibus health-check issue. However, we were passing package names separated by spaces to `PIP_NO_BINARY` when it actually expects commas, so it turns out we were still using the pyodbc from PyPI.
In addition, with the update of the linux-x86 image to manylinux2014, we now also need to do the same thing in that platform.
Proof it builds it now:
- https://github.com/DataDog/integrations-core/actions/runs/8294569329/job/22699839228?pr=17186#step:10:37891
- https://github.com/DataDog/integrations-core/actions/runs/8294569329/job/22699839525?pr=17186#step:12:36956
=> Fix `PIP_NO_BINARY` syntax and ensure pyobdc is always built in linux

kubelet/changelog.d/17196.added, kubelet/pyproject.toml
Bump the min base check version to 34.2.0
[This](https://github.com/DataDog/integrations-core/pull/16856/files#diff-5667d0679f771917c408c64bc4f6fe3e07a79d03e663038809fe82804f636cd3R19) was [introduced](https://github.com/DataDog/integrations-core/pull/16012) in the base check 34.2.0 so it now [fails](https://github.com/DataDog/integrations-core/actions/runs/8291565112/job/22691510705#step:14:328) with older base checks
=> Bump the min base check version to 34.2.0

oracle/changelog.d/17197.added, oracle/pyproject.toml
With [this](https://github.com/DataDog/integrations-core/pull/16958) we now need a more recent version of the base check to support this feature.
It failed [here](https://github.com/DataDog/integrations-core/actions/runs/8291565112/job/22691522884#step:14:377)
=> Bump the min base check version to 36.5.0

postgres/changelog.d/17148.added, postgres/datadog_checks/postgres/statements.py, postgres/tests/test_statements.py
Adds support for collection plan time metrics from PG_STAT_STATEMENTS for PG 13 and up. This will help users verify any optimizations they are making to their queries to reduce the amount of time the PG database takes to plan the query.
The following are the newly added metrics
- total_plan_time
- min_plan_time
- max_plan_time
- mean_plan_time
- stddev_plan_time
https://datadoghq.atlassian.net/browse/DBMON-3618
=> [DBMON-3618] Add support for collecting plan time metrics from PG_STAT_STATEMENTS 

.github/workflows/run-validations.yml, .github/workflows/validate.yml, datadog_checks_dev/changelog.d/17199.added, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/codeowners.py, ddev/tests/cli/validate/conftest.py, ddev/tests/cli/validate/test_codeowners.py
Allow the codeowners validation in integrations-core
We will very soon extend this validation to also validate stuff in integrations-core
We do not have any tests for this yet, I'll add them when I'll move them to ddev
=> Allow the codeowners validation in integrations-core

datadog_cluster_agent/assets/dashboards/datadog_cluster_agent_overview.json, datadog_cluster_agent/changelog.d/17195.removed, datadog_cluster_agent/datadog_checks/datadog_cluster_agent/check.py, datadog_cluster_agent/tests/fixtures/metrics.txt, datadog_cluster_agent/tests/test_datadog_cluster_agent.py
This PR removes the `admission_webhooks_mutation_errors` metric and updates the DCA OOTB dashboard/
- `admission_webhooks_mutation_errors` is removed from the cluster agent telemetry in [this](https://github.com/DataDog/datadog-agent/pull/23770) PR
- Depends on:
-  [PR](https://github.com/DataDog/datadog-agent/pull/23770)
=> [CONTINT-3892] remove mutation_errors and update dashboard

.gitlab/software_composition_analysis.yaml
- use a more recent version of the Datadog SCA product
- use osv-scanner to produce SBOMs instead of trivy
Requested by @juli1
[Successful job execution](https://gitlab.ddbuild.io/DataDog/integrations-core/-/jobs/463266986)
=> [SINT-INTERRUPT] Update SCA CI image

http_check/tests/compose/certs-builder/Dockerfile, tls/tests/compose/Dockerfile
Pin libfaketime in our docker images
https://github.com/wolfcw/libfaketime/issues/467 broke us https://github.com/DataDog/integrations-core/actions/runs/8355648482/job/22871222835
=> Pin libfaketime

.github/workflows/build-ddev.yml
Fixes the builds by:
- upgrading pyapp
- removing the 32-bit linux build, as recommended by @ofek
=> Fix ddev builds

postgres/changelog.d/17234.fixed, postgres/datadog_checks/postgres/relationsmanager.py, postgres/tests/test_relations.py, postgres/tests/test_replication_slot.py
This PR skips relations with granted `AccessExclusiveLock` in relations metrics query to avoid query timeout. 
https://datadoghq.atlassian.net/browse/DBMON-3424
`QUERY_PG_CLASS` acquires `AccessSharelock` in function `pg_relation_size`. The query could timeout is other running queries acquires `AccessExclusiveLock` in relations.
=> skip locked relations to avoid relations metrics query timeout

postgres/changelog.d/17235.fixed, postgres/datadog_checks/postgres/metadata.py, postgres/tests/common.py, postgres/tests/compose/resources/03_load_data.sh, postgres/tests/test_metadata.py
This PR fixes `NoneType` error in schema collection when partition tables have no activities.
=> Fix NoneType error in schema collection when partition tables have no activities

nginx/changelog.d/17233.added, nginx/datadog_checks/nginx/nginx.py, nginx/tests/common.py, nginx/tests/conftest.py, nginx/tests/test_e2e.py, nginx/tests/test_nginx.py, nginx/tests/test_plus_api.py, nginx/tests/test_vts.py
Second take on [nginx: metrics should have same tags as service checks](https://github.com/DataDog/integrations-core/pull/16797), but this time we don't submit `host` tag with metrics ever.
=> Tag metrics with nginx host and port.

sqlserver/changelog.d/17245.fixed, sqlserver/datadog_checks/sqlserver/connection.py, sqlserver/datadog_checks/sqlserver/sqlserver.py, sqlserver/tests/test_connection.py
This PR refactors the  SQLServer connector and adoprovider initialization from configuration to follow the order of:
- instance config
- init config
- the default connection/adoprovider
https://datadoghq.atlassian.net/browse/DBMON-3722
Properly log debugging message of the defaulted connector, adoprovider and odbc driver.
=> Refactor SQLServer connector and adoprovider initialization from configuration

teleport/assets/configuration/spec.yaml, teleport/datadog_checks/teleport/config_models/defaults.py, teleport/datadog_checks/teleport/config_models/instance.py, teleport/datadog_checks/teleport/data/conf.yaml.example
Adds `teleport_url` and `diag_port` properties to the spec.
=> [PLINT-325] Update Teleport Configuration spec

ddev/changelog.d/17257.fixed, ddev/src/ddev/plugin/external/hatch/environment_collector.py
Update the ruff command for ruff 0.3.3
- https://github.com/DataDog/integrations-core/pull/17244
```
cmd [2] | ruff --config ./pyproject.toml --fix .
warning: `ruff <path>` is deprecated. Use `ruff check <path>` instead.
```
=> Update the ruff command for ruff 0.3.3

datadog_checks_dev/changelog.d/17269.fixed, datadog_checks_dev/pyproject.toml, ddev/changelog.d/17269.fixed
That version of flaky fixes a problem with 8.1.1 of pytest
=> Bump pytest and require flaky minimum version

kubelet/changelog.d/17280.fixed, kubelet/datadog_checks/kubelet/kubelet.py, kubelet/tests/test_kubelet.py
* Changes the `parse_quantity` function to cover resources from pods set with exponent notation https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory : 
> Limits and requests for memory are measured in bytes. You can express memory as a plain integer or as a fixed-point number using one of these [quantity](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/) suffixes: E, P, T, G, M, k. You can also use the power-of-two equivalents: Ei, Pi, Ti, Gi, Mi, Ki. For example, the following represent roughly the same value:
`128974848, 129e6, 129M,  128974848000m, 123Mi`
* Customer case where the current parsing provides exabytes value for `kubernetes.memory.requests` due to the current parsing function : …
=> [Python-based kubelet] Parse resources with exponent notation

sqlserver/changelog.d/17275.fixed, sqlserver/datadog_checks/sqlserver/connection.py, sqlserver/datadog_checks/sqlserver/sqlserver.py, sqlserver/tests/test_connection.py
This PR breaks circular dependencies between `SQLServer` check class and `Connection` class.
=> Break circular dependency between sqlserver check and connection

.builders/build.py, .builders/scripts/build_wheels.py, .builders/scripts/repair_wheels.py, .builders/upload.py
Incorporates our custom indices to the sources for used in resolution+retrieval+build process (through `pip wheel`), by adding them with `--extra-index-url`.
- Adds our custom "external" index always.
- Adds our custom "built" index when the build images haven't changed.
A few other changes were required to account for the introduction of build tags through our own index in parts of the process where we didn't have any.
- Protection from 3rd parties through PyPI.
- Optimization by avoiding rebuilds that may be unnecessary.
- I think adding the "external" index via `--extra-index-url` is always safe, regardless of the lack of priority guarantees between PyPI and the additional index. `pip` will consider artifacts from both indices and choose the "best" fit (highest compatible version, …
=> Reuse our own package indices when retrieving wheels for resolution

openstack_controller/metadata.csv
openstack.ironic.node.up doesn't measure how many ironic nodes are up; it measures if a given node is up. The description in the metadata.csv file is updated to clarify this.
=> Changed the description of the openstack.ironic.node.up metric

.github/workflows/pr-quick-check.yml
Bring back the comment when contributors use the changed changelog fragment. 
Example [here](https://github.com/DataDog/integrations-core/pull/17289#issuecomment-2022317426) triggered on this PR changing something in `ddev` with a `changed` fragment. (I reverted the modification)
- It got dropped when we changed the way to manage changelogs and I think it was useful and saves us some friction on a lot of PRs.
https://github.com/DataDog/integrations-core/blob/7.45.x/.github/workflows/changelog-label-check.yml#L22-L29
- I reviewed a couple of PRs where people used `changed` without knowing what it would do.
- We have to use an action to filter jobs on path that were modified, the built-it path option only works for workflows
=> Bring back the comment when contributors use the `changed` changelog fragment

sqlserver/changelog.d/17299.fixed, sqlserver/datadog_checks/sqlserver/queries.py
This PR fixes 2 missing metrics `sqlserver.files.write_io_stall_queued` and `sqlserver.files.read_io_stall_queued` for sqlserver major version > 2012 and not Azure SQL Database/Azure SQL Managed Instance.
=> fix missing file stats metrics for sqlserver newer than 2012 and not Azure SQL Database/Azure SQL Managed Instance

eks_fargate/README.md
The token requires a 32 char min.  If not an error will show up in the container sidecar as such... "Could not detect the Datadog Cluster Agent's endpoint: temporary failure in clusterAgentClient, will retry later: cluster agent authentication token length must be greater than 32, currently: 7"
Documentation change on the EKS Fargate configuration setup.  The token between the DCA and agent sidecar requires a 32 char min.
Not list in the doc which is a important requirement.
If an example block of the Datadog Helm chart where we specify the `token` that would be even more helpful.
> datadog:
>   clusterName: <their-cluster-name>
> agents:
>   enabled: false # No DaemonSet generated
> clusterAgent:
>   enabled: true
>   replicas: 1
>   token: "<some 32 chars random-token>" # Some token, …
=> Update EKS Fargate token setup

postgres/changelog.d/17314.added, postgres/datadog_checks/postgres/metadata.py, postgres/tests/test_metadata.py
Adds the postgres table `owner`, which we already have support for in our backend. We were [always collecting this](https://github.com/DataDog/integrations-core/blob/master/postgres/datadog_checks/postgres/metadata.py#L62) in our queries, but never sending it to the backend to be used in our schemas UI.
=> Collect postgres table owner in database-monitoring schema payloads

argo_rollouts/assets/monitors/rollout_phase.json, argo_rollouts/manifest.json
Argo Rollout recommended monitor. Looks at a metric that reports the phase of the rollout. It alerts if a rollout is ever in the InvalidSpec, Aborted, Error or TimeOut phase for 10 minutes. 
staging link:
https://dd.datad0g.com/monitors/recommended?q=argo_rollouts&only_installed=true&p=1
=> Argo Rollout Recommended Monitor

kafka_consumer/README.md
Updates the `kafka_consumer` readme to use non-JMX containerized instructions.
Flagged by support, kafka_consumer is not a JMX check.
=> DOCS-7515: update kafka_consumer readme

pan_firewall/manifest.json, tokumx/manifest.json
Updates 2 manifest to remove their empty "process signatures" field. These are the only two integrations that list the field with an empty list. 
Cleans up two unused fields while we work on finalizing a migration of certain fields over to APW!
=> Remove empty process_signatures field

ddev/changelog.d/17316.added, ddev/src/ddev/cli/meta/scripts/serve_openmetrics_payload.py
Collect all metrics by default for the OpenMetrics integration in the serve payload script
This is not needed for OM-based integrations because we override the `metrics` option for them, but not for the default OM integration. That way we can collect everything by default
=> Collect all metrics by default for the OpenMetrics integration in the serve payload script

oracle/README.md
Replacing documentation for the legacy Oracle check with the Oracle core setup.
In the Agent `7.53.0` we are deprecating the Oracle Python integration.
=> Replacing documentation for the legacy Oracle check (DBMON-3848)

mongo/hatch.toml, mongo/tests/conftest.py, mongo/tests/test_e2e.py
Add mongo 6 and 7 to the test environments
We do not test with the latest versions
The `mongo` command got dropped https://www.mongodb.com/docs/manual/release-notes/6.0-compatibility/#legacy-mongo-shell-removed
=> Add mongo 6 and 7 to the test environments

oracle/README.md
This PR looks to have accidentally removed the `## Troubleshooting` header - https://github.com/DataDog/integrations-core/commit/6bb58bb3bd4aa410f86682eb814d0ff3f2428624
This is a required header. We plan on adding stronger validations around these kinda of things in the future.
=> Add back troubleshooting header

amazon_msk/changelog.d/17332.added, amazon_msk/pyproject.toml, datadog_checks_base/changelog.d/17332.added, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/pyproject.toml, postgres/changelog.d/17332.added, postgres/pyproject.toml
I need to trigger a build of dependencies so I'm just bumping a patch release
=> Upgrade boto dependencies

openai/README.md
Fix command
Fix OpenAI docs' command.
1. At current command, user face below error.
```
$ pip install ddtrace>=1.13
-bash: =1.13: Permission denied
$ sudo pip install ddtrace>=1.13
-bash: =1.13: Permission denied
```
2. Also, DD_API_KEY is not necessary at ddtrace-run just for APM. 
3. As for DD_OPENAI_LOGS_ENABLED, default value is "false". So this should be better to change "true".
https://ddtrace.readthedocs.io/en/stable/integrations.html#openai
=> Update OpenAI README.md

ibm_ace/changelog.d/17336.fixed, ibm_ace/datadog_checks/ibm_ace/check.py, ibm_ace/tests/test_integration.py
Do not fail if no tags are provided in the config
This field is optional and defaults to `None`. The problem is if we run the check without specifying any tags in the instance config, we end up failing here: https://github.com/DataDog/integrations-core/blob/master/ibm_ace/datadog_checks/ibm_ace/check.py#L35
With this kind of error: 
```
Error: Value after * must be an iterable, not NoneType
File "/opt/datadog-agent/embedded/lib/python3.11/site-packages/datadog_checks/base/checks/base.py", line 1210, in run
initialization()
File "/opt/datadog-agent/embedded/lib/python3.11/site-packages/datadog_checks/ibm_ace/check.py", line 35, in initialize_config
tags = [f'mq_server:{self.config.mq_server}', f'mq_port:{self.config.mq_port}', *self.config.tags]
```
=> Do not fail if no tags are provided in the config

.github/workflows/pr-quick-check.yml
Add a comment to the PR when the `removed` fragment is used
This is also a major bump https://github.com/DataDog/integrations-core/blob/6194881ba79a1646a93a012a7501e7e2e490b2d5/datadog_checks_dev/datadog_checks/dev/tooling/constants.py#L39-L53
=> Add a comment to the PR when the `removed` fragment is used

.github/workflows/build-deps.yml
The fix yesterday https://github.com/DataDog/integrations-core/pull/17331 also introduced another issue [`34105da` (#17333)](https://github.com/DataDog/integrations-core/pull/17333/commits/34105da07d6f36f79d9457e97d84f35bd4ddc681) which is why the conditional was set up like that originally.
Now both cases are handled; we either get the new digest from registry or we copy the existing one.
=> Persist the target image digest

sqlserver/assets/configuration/spec.yaml, sqlserver/changelog.d/17300.fixed, sqlserver/datadog_checks/sqlserver/config.py, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example, sqlserver/datadog_checks/sqlserver/sqlserver.py, sqlserver/tests/test_metrics.py, sqlserver/tests/test_unit.py
Removes the database exist check in sql_integration if ignore_missing_database is set to false
The database exist check got introduced in https://github.com/DataDog/integrations-core/pull/357 for the reason that we don't see as valid anymore. The check is error prone and causes false positive. Nevertheless in order to avoid a breaking change we dont modify the behaviour for users that set ignore_missing_database to true. For user who set it to False we remove the check as anyway the exception when connecting to database will be thrown.
=> Partially remove db exist check if ignore db is false

ddev/src/ddev/cli/config/__init__.py, ddev/src/ddev/cli/config/edit.py, ddev/src/ddev/cli/config/explore.py, ddev/src/ddev/cli/config/find.py, ddev/src/ddev/cli/config/restore.py, ddev/src/ddev/cli/config/set.py, ddev/src/ddev/cli/config/show.py, ddev/src/ddev/cli/config/update.py
Split the `config`  command into several files
I struggled a bit to find the implementations, other commands have their own file. It should be easier to navigate them that way.
They are already unit tested in separate files https://github.com/DataDog/integrations-core/tree/2d97c5a8bdd3d6985aa60f92695ecf250c03844a/ddev/tests/cli/config
=> Split the `config`  command into several files

ddev/tests/conftest.py
Fix the message when tests are skipped because of the platform 
On my mac I got: 
```
tests/utils/test_json.py::test_save PASSED                               [ 94%]
tests/utils/test_platform.py::TestWindows::test_tag SKIPPED (Only running on Windows) [ 94%]
tests/utils/test_platform.py::TestWindows::test_format_for_subprocess_list SKIPPED (Not running on Windows) [ 94%]
tests/utils/test_platform.py::TestWindows::test_format_for_subprocess_list_shell SKIPPED (Not running on Windows) [ 95%]
tests/utils/test_platform.py::TestWindows::test_format_for_subprocess_string SKIPPED (Not running on Windows) [ 95%]
tests/utils/test_platform.py::TestWindows::test_format_for_subprocess_string_shell SKIPPED (Not running on Windows) [ 95%]
tests/utils/test_platform.py::TestMacOS::test_tag PASSED …
```
=> Fix the message when tests are skipped because of the platform

ddev/changelog.d/17348.fixed, ddev/src/ddev/cli/release/changelog/new.py, ddev/tests/cli/release/test_changelog.py
Do not open the editor if no changelog should be generated in the changelog new command
I ran the `changelog new` command for a PR that only changed a `conftest.py` file. No changelog files were generated (which is expected) but I got confused because ddev opened the editor and the success message was misleading. I thought there was a bug in the command before figuring out it's actually the expected behaviour.
=> Do not open the editor if no changelog should be generated in the changelog new command

sqlserver/assets/configuration/spec.yaml, sqlserver/changelog.d/17361.added, sqlserver/datadog_checks/sqlserver/config.py, sqlserver/datadog_checks/sqlserver/config_models/defaults.py, sqlserver/datadog_checks/sqlserver/config_models/instance.py, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example, sqlserver/datadog_checks/sqlserver/metrics.py, sqlserver/datadog_checks/sqlserver/sqlserver.py
This PR adds a new config option `include_db_fragmentation_metrics_tempdb` (default to false) to skip index fragmentation metrics for `tempdb`.
By default, index fragmentation will NOT be collected for `tempdb`.
https://datadoghq.atlassian.net/browse/DBMON-3530
We have observed situations where the `sys.dm_db_index_physical_stats` DMF was blocked by `LCK_M_S` locks in `tempdb`. Additionally, there have been instances of deadlocks, with errors like `Transaction was deadlocked on lock resources with another process and has been chosen as the deadlock victim` indicating potential significant contention in `tempdb`.
=> Skip index fragmentation metrics for tempdb

esxi/datadog_checks/esxi/check.py, esxi/datadog_checks/esxi/constants.py, esxi/datadog_checks/esxi/metrics.py, esxi/metadata.csv, esxi/tests/test_integration.py, esxi/tests/test_unit.py
- Adds `esxi.host.count` and `esxi.vm.count` metrics to the esxi integration
- also make the VM resource type name lowercase to match the other resource type names
Is `esxi.host.count` needed if it will always be 1?
=> [PLINT-317] Add support for infrastructure metrics

gke/README.md
Replace [deprecated parameter `datadog.apm.enabled`](https://github.com/DataDog/helm-charts/tree/main/charts/datadog#values:~:text=datadog.apm.enabled,apm.portEnabled%20instead) with replacement parameter `datadog.apm.portEnabled`. 
Also updates some broken links in the Autopilot tab + adds more Monitor blog posts.
[Hotjar user feedback](https://datadoghq.atlassian.net/browse/DOCS-7626).
=> DOCS-7626 Google Kubernetes Engine Doc Update

.deps/resolved/macos_py3.txt, .gitlab-ci.yml
Changes triggering of agent builds to when the lockfiles are changed, since that will become the source of truth for installing dependencies from the Agent build once https://github.com/DataDog/datadog-agent/pull/23094 is in place.
[BARX-288](https://datadoghq.atlassian.net/browse/BARX-288)
The goal is to catch possible issues with PR's that modify the dependency lockfiles that will be used by the Agent.
Tested a successful trigger in [e366bf7](https://github.com/DataDog/integrations-core/pull/17232/commits/e366bf7e5c452b8dd901bb9370b37adac192c3d8).
[BARX-288]: https://datadoghq.atlassian.net/browse/BARX-288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Trigger the agent build when anything changes under .deps

mapr/README.md, mapr/tests/conftest.py
- Fixes e2e test setup that was failing.
- Adds docs with extra step needed to be able to make the integration work.
Fix failing tests ([example](https://github.com/DataDog/integrations-core/actions/runs/8627672648/job/23648162655)) because of https://github.com/DataDog/datadog-agent/pull/23094. `librdkakfa` headers are no longer available in the Agent which causes the installation of mapr-streams-python to fail, as it tries to install confluent-kafka.
=> Updates to mapr e2e test setup and instructions to add librdkafka headers

mysql/metadata.csv
Adds a definition for how MySQL defines a "slow query".
Flagged by a user in Hotjar: ["What do you consider "slow"?"](https://insights.hotjar.com/sites/1021060/surveys/responses/950698?prid=736807086)
=> MySQL Metric Description Update

.github/CODEOWNERS
[BARX-307](https://datadoghq.atlassian.net/browse/BARX-307)
The rationale for the ownership assignment is:
- agent-integrations is responsible for dependency updates and as such need to own or co-own all the files that might be involved (any patching or additional non-Python dependency that might be required at some point).
- agent-build-and-releases is responsible for the build and upload machinery itself, and should be giving a hand whenever dependencies require changes in the build images, etc.
[BARX-307]: https://datadoghq.atlassian.net/browse/BARX-307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Assign ownership to BARX for relevant parts of new deps building system

mongo/tests/test_integration_standalone.py
We've been seeing this test fail *sometimes* where the number of samples for one of the metrics was greater than 1.
Using the default `at_least=1` seems appropriate here from the point of view of behavior.
=> Relax assertion about metric count to make test less flaky

esxi/assets/configuration/spec.yaml, esxi/datadog_checks/esxi/check.py, esxi/datadog_checks/esxi/config_models/instance.py, esxi/datadog_checks/esxi/constants.py, esxi/datadog_checks/esxi/data/conf.yaml.example, esxi/datadog_checks/esxi/utils.py, esxi/tests/conftest.py, esxi/tests/test_unit.py
Adds support for per instance filters in the ESXi integration. per-instance metrics are more granular, non-aggregated metrics that have additional tags and tag values that we collect and send
vSphere has this option, much of this logic is copied from the vSphere integration
=> [PLINT-314] Add support for per instance filters

postgres/assets/configuration/spec.yaml, postgres/changelog.d/17400.fixed, postgres/datadog_checks/postgres/config_models/defaults.py, postgres/datadog_checks/postgres/data/conf.yaml.example
Fixes the default value for pg_stat_statements_view in the example config
Some customers are confused by the current default, which is not the correct default.
=> Fix default value for pg_stat_statements_view

.builders/images/linux-aarch64/Dockerfile, .builders/images/linux-x86_64/Dockerfile, .builders/images/macos-x86_64/builder_setup.sh
Bumps openssl from 3.0.12 to 3.0.13 on dependency builders.
Make sure we ship a recent enough version of OpenSSL with our python dependencies.
For reference, this is the same version now shipped with the Agent (https://github.com/DataDog/omnibus-software/blob/6707f681c44a2f0664f2b9c4c726b94ad6f49cb9/config/software/openssl3.rb#L27)
=> Bump openssl on dependency builders

esxi/datadog_checks/esxi/check.py, esxi/tests/test_integration.py, esxi/tests/test_unit.py
Adds an `esxi_host` tag to as a VM host tag, signifying what esxi host the VM is running on 
While we are already submitting the `esxi_url` tag, this is most likely different than the host's name. 
This will be the same for all VMs
=> [PLINT-361] Add esxi_host tag 

.devcontainer/Dockerfile
In `.devcontainer/dockerfile`, patch `/etc/init.d/docker` to change the `ulimit` command arguments and allows to run docker-in-docker commands.
I followed the workaround instruction defined [here](https://forums.docker.com/t/etc-init-d-docker-62-ulimit-error-setting-limit-invalid-argument-problem/139424). The issue seems to be linked to an change in the base image used by the upstream python devcontainer container image.
```
Container where the error was received: Debian GNU/Linux 11 (bullseye)
This error started to be received approximately as of Friday, January 19, 21:00:00UTC 2024.
```
Be able to use .devcontainer with this repository.
=> fix(devcontainer): patch /etc/init.d/docker to support DiD

sqlserver/changelog.d/17430.fixed, sqlserver/datadog_checks/sqlserver/config.py, sqlserver/datadog_checks/sqlserver/database_metrics/db_fragmentation_metrics.py, sqlserver/datadog_checks/sqlserver/metrics.py
Fixes a bad assumption about YAML/Python nulls to provide default values.
If the config explicitly specifies `null` for a list or dict value, the `get` won't return the default value and iteration will crash.
=> Fix null checks

.builders/images/linux-aarch64/Dockerfile, .builders/images/macos-x86_64/builder_setup.sh
I chose the versions to match what lxml, the python package requiring these dependencies, includes (see [here](https://github.com/lxml/lxml/blob/a22e83caf637c8c68030da0278591df60c994126/.github/workflows/wheels.yml#L113-L114)). That's relevant because those are the versions that we use whenever we actually use upstream wheels (like for linux x64 at the moment, and probably what we'll do for all platforms whenever we manage to update lxml to a version that has wheels for more platforms).
=> Update libxml2 and libxslt for building dependencies

esxi/assets/configuration/spec.yaml, esxi/datadog_checks/esxi/check.py, esxi/datadog_checks/esxi/config_models/defaults.py, esxi/datadog_checks/esxi/config_models/instance.py, esxi/datadog_checks/esxi/data/conf.yaml.example, esxi/tests/common.py, esxi/tests/test_integration.py, esxi/tests/test_unit.py
add support for SSL verification when connecting to ESXi host
Implementation differs from vSphere as we now use `PROTOCOL_TLS_CLIENT` since `PROTOCOL_TLS` is deprecated. we favor matching the implementation in the base check over vSphere, but use the same option names as the vSphere check
=> [PLINT-316] Add support for SSL verification

.github/workflows/build-ddev.yml, .github/workflows/cache-shared-deps.yml, .github/workflows/compute-matrix.yml, .github/workflows/docs.yml, .github/workflows/pr-quick-check.yml, .github/workflows/release-base.yml, .github/workflows/release-dev.yml, .github/workflows/release-hash-check.yml, .github/workflows/run-validations.yml, .github/workflows/test-target.yml, .github/workflows/update-agent-changelog.yml, .github/workflows/update-dependencies.yml
=> Update setup-python github action to use Node 20

esxi/assets/configuration/spec.yaml, esxi/datadog_checks/esxi/check.py, esxi/datadog_checks/esxi/config_models/instance.py, esxi/datadog_checks/esxi/data/conf.yaml.example, esxi/datadog_checks/esxi/metrics.py, esxi/datadog_checks/esxi/utils.py, esxi/tests/test_unit.py
Add the ability to filter metrics, mirroring the behavior of the vSphere check
=> [PLINT-313] Add support for metric filters

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/marketplace/IMAGES_README.md
Update the `IMAGES_README` file that `ddev create` adds to the scaffolding for new integrations.
The image must be exactly 16:9 (as enforced by the datadog-assets tile validation, not linked here because it's not open source).
=> ddev: Update IMAGES_README template

vsphere/changelog.d/17446.fixed, vsphere/datadog_checks/vsphere/vsphere.py, vsphere/tests/common.py, vsphere/tests/test_unit.py
Only collect property metrics for resources that support it and lower log line _level
The `Could not retrieve properties for resource` message was appearing often in logs. It is not a critical failure (worthy of a warning log) and often avoidable. The most common reason this happens is when attempting to collect property metrics for datacenters, which don't support property metrics. After this change, we don't try to collect property metrics for datacenters. 
The PR also lowers the log level so if the issue does happen again, it does not spam the agent logs anymore
=> Only collect property metrics for resources that support it and lower log line level

esxi/changelog.d/17459.fixed, esxi/datadog_checks/esxi/check.py
Lower log level for missing metric
a missing metric value should not be a warning
=> Lower log level for missing metric

postgres/changelog.d/17418.added, postgres/datadog_checks/postgres/postgres.py, postgres/metadata.csv, postgres/tests/common.py
Add a `postgresql.running` metric.
We want to be able to aggregate the number of database instances per version, system_identifier or any other arbitrary tags. The metrics currently available don't allow this.
=> Add postgresql.running metric

.github/CODEOWNERS
Moves ownership for build-deps.yml to a place on the CODEOWNERS file that ensures it is honored.
Automatically asked reviewers for #17449 didn't match what I expected (as intended with the change #17387).
Codeowners precedence is actually order based, not specificity based (my initial assumption).
=> Tweak codeowners to properly set build-deps.yml's owner

teleport/tests/test_common.py
Update the match field in the exception we receive to support different exceptions messages raised by different `requests` versions.
=> Fix exception handling in Teleport tests

postgres/changelog.d/17451.added, postgres/datadog_checks/postgres/relationsmanager.py, postgres/tests/test_relations.py
Add `fastpath` as a tag to pg_locks metrics.
We want to be able to see unexpected increase in locks that were not granted with fastpath and if there's any correlation with an increase in Lock wait event.
=> Add fastpath tag to lock metrics

openstack_controller/assets/dashboards/openstack_controller_overview_[default_microversion].json
New cinder metrics have been added in the latest agent release, so the dashboard needed to be updated to display these metrics.
=> Updating openstack controller [default microversion] dashboard to include new cinder metrics

argo_rollouts/changelog.d/17476.fixed, argo_rollouts/datadog_checks/argo_rollouts/data/conf.yaml.example, argo_workflows/changelog.d/17476.fixed, argo_workflows/datadog_checks/argo_workflows/data/conf.yaml.example, tekton/changelog.d/17476.fixed, tekton/datadog_checks/tekton/data/conf.yaml.example
https://github.com/DataDog/integrations-core/pull/16981 but for the latest integrations
My PR was a bit behind and these integrations were not merged yet
=> Update the description for the tls_ca_cert config option to use openssl rehash instead of c_rehash

.github/workflows/build-deps.yml
It does the equivalent to what is currently already done in master w.r.t. dependency builds, uploads and lockfile updates to release branches.
With the new dependency build process, there's no good way to cherry pick individual dependency changes to release branches (or to update individual dependencies within a release branch, for that matter). This is because lockfiles are resolved for a predefined set of direct dependencies (as defined in agent_requirements.in); cherry picking a dependency update out of many updates would result in a new set of direct dependencies that would need separate resolution.
The auto-PR should, according to the [documentation](https://github.com/peter-evans/create-pull-request#action-inputs) for the Action that we use to generate it, inherit the base branch …
=> Trigger dependency build-related jobs on release branches too

mysql/hatch.toml
Inspired by https://github.com/DataDog/integrations-core/pull/16886, I'm adding the 10.6 version of MariaDB into the tests.
10.6 is one of the LTS versions, so it should be much more used than other versions, and thus should be tested.
I've also added details on the existing versions.
Depending on the cost to maintain them, you might want to drop the 10.8 & 10.9 versions: they are not LTS, and there is the 10.11 afterwards already included.
=> Add mariadb 10.6

openstack_controller/assets/configuration/spec.yaml, openstack_controller/datadog_checks/openstack_controller/api/api_rest.py, openstack_controller/datadog_checks/openstack_controller/api/api_sdk.py, openstack_controller/datadog_checks/openstack_controller/components/image.py, openstack_controller/datadog_checks/openstack_controller/config_models/instance.py, openstack_controller/datadog_checks/openstack_controller/metrics.py, openstack_controller/metadata.csv, openstack_controller/tests/conftest.py, openstack_controller/tests/fixtures/GET/image/v2/images/28c293db-48c5-4c8b-a711-09b2c11fa8e5/members/response.json, openstack_controller/tests/metrics.py, openstack_controller/tests/test_unit_glance.py
Adding metric openstack.glance.image.member.count
=> [PLINT-376] Adding glance image member metrics

postgres/assets/dashboards/postgresql_screenboard_dashboard.json
- Updates the Postgres screenboard to have widgets rely on the $host template variable where applicable.
=> Update postgres screenboard to scope things to the host variable.

.builders/images/linux-aarch64/Dockerfile
Apply various small changes that were made to the linux x64 build image but for some reason never made it to the aarch64 one.
=> Change aarch64 build image to follow the x64 more closely

sqlserver/changelog.d/17503.fixed, sqlserver/datadog_checks/sqlserver/metrics.py
User contribution from https://github.com/DataDog/integrations-core/pull/17439. Created on repo to add a changelog. Original contribution from @omarmxdbe 
- Fixes the always-on query in SQLServer to prevent duplicate rows. This affects the following 2 metrics `sqlserver.ao.replica_failover_mode` and `sqlserver.ao.replica_failover_readiness`.
=> SQLServer - Fix Always-On metrics query for replica_failover_mode and replica_failover_readiness

postgres/assets/dashboards/postgresql_screenboard_dashboard.json
This PR will allow the List Widget for the Logs were not using the host template variable to scope the results.
Customer feedback.
=> Minor update to Postgres - Overview dashboard

datadog_cluster_agent/changelog.d/17530.added, datadog_cluster_agent/datadog_checks/datadog_cluster_agent/check.py, datadog_cluster_agent/metadata.csv, datadog_cluster_agent/tests/fixtures/metrics.txt, datadog_cluster_agent/tests/test_datadog_cluster_agent.py
Add CWS Instrumentation histogram metric in the datadog_cluster_agent check.
Keep the integration up-to-date and collect new metrics introduced in this [PR](https://github.com/DataDog/datadog-agent/pull/25433).
=> [datadog-cluster-agent] Add CWS Instrumentation metrics

jboss_wildfly/README.md
https://datadoghq.atlassian.net/browse/DOCS-6911
Added instructions for enabling default JBoss/Wildly-DD integration metrics via JMXFetch. 
JIRA ticket, request from Fred Shad, which I believe was inspired by customer feedback/support requests.
=> Added section to enable default metrics through jmxfetch

postgres/assets/configuration/spec.yaml, postgres/datadog_checks/postgres/config.py, postgres/tests/test_pg_integration.py
Reduces collection interval from 30 minutes to 5 minutes for database instances.
This change makes it less likely that a database instance will be incorrectly deleted from our stores, and improves the responsiveness of updates to database instances. This is intended to counteract bugs where databases are disappearing and causing tag flapping, as well as improving user experience with seeing the database instances they expect.
Database instance events are fairly lightweight so no noticeable performance impact is expected.
=> Decrease database instance collection interval

agent_metrics/manifest.json, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/snmp_tile/snmp_{check_name}/manifest.json, dns_check/manifest.json, external_dns/manifest.json, http_check/manifest.json, network/manifest.json, ntp/manifest.json, snmp_aruba/manifest.json, tcp_check/manifest.json
Remove deprecated `Monitoring` and `Web` categories from integration manifests so we can complete the deprecation process
=> [ECOS-141] Removed deprecated Monitoring and Web categories #678 

mongo/assets/configuration/spec.yaml, mongo/changelog.d/17518.added, mongo/datadog_checks/mongo/api.py, mongo/datadog_checks/mongo/common.py, mongo/datadog_checks/mongo/config.py, mongo/datadog_checks/mongo/config_models/defaults.py, mongo/datadog_checks/mongo/config_models/instance.py, mongo/datadog_checks/mongo/data/conf.yaml.example, mongo/datadog_checks/mongo/mongo.py, mongo/tests/conftest.py, mongo/tests/fixtures/getShardMap, mongo/tests/test_integration.py, mongo/tests/test_integration_shard.py, mongo/tests/test_integration_standalone.py, mongo/tests/test_unit.py, mongo/tests/test_unit_config.py
In this PR, the mongo integration will emit `mongodb_instance` metadata event which contains instance level metadata including
- hostname
- version
- replica set name
- replica set state
- sharding cluster role
- cluster type
- hosts (list of mongodb instances this mongodb connects to)
- shards (list of shards this mongos instance connects to)
- cluster name
[DBMON-4003](https://datadoghq.atlassian.net/browse/DBMON-4003)
`mongodb_instance` ingested in staging
[DBMON-4003]: https://datadoghq.atlassian.net/browse/DBMON-4003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [mongo] Emit mongodb_instance metadata event

datadog_checks_dev/changelog.d/17538.fixed, datadog_checks_dev/datadog_checks/dev/tooling/commands/create.py
Fix trailing comma in the manifest
=> Fix trailing `,` in manifest generation

esxi/assets/configuration/spec.yaml, esxi/changelog.d/17544.added, esxi/datadog_checks/esxi/check.py, esxi/datadog_checks/esxi/config_models/defaults.py, esxi/datadog_checks/esxi/config_models/instance.py, esxi/datadog_checks/esxi/data/conf.yaml.example, esxi/tests/test_unit.py
Add an option `use_configured_hostname` to allow users to set the hostname of ESXi hosts to be the configured `host` instead of the name found from pyvmomi
If a customer enables both the ESXi and vSphere integration, they could have duplicated hosts without this option
=> Add option to use configured host as hostname for esxi hosts

mysql/changelog.d/17555.fixed, mysql/datadog_checks/mysql/mysql.py
This PR fixes a bug in the `database_instance` tag propagation where aurora tags like `replication_role` were not being added to the metadata payload. This results in users losing host tags that previously existed when `database_instance` creation happened from the metrics-processor
You can see the tag now appears here after the fix:
=> Fix tag propagation of aurora `replication_role` tag

teleport/assets/dashboards/teleport_overview.json, teleport/manifest.json
Adds the Overview dashboard for the Teleport Integration
=> Add Teleport Overview Dashboard

.github/workflows/test-target.yml
Follow-up to https://github.com/DataDog/integrations-core/pull/17470, where we didn't have unique artifact names for different test targets.
Unfortunately we can only trigger this workflow once we merge to master.
=> Unique test result name for each target

.github/CODEOWNERS
This PR reorders the code owner of mongo integration as `agent-integrations` remains the primary codeowner of mongo integration. 
The ensures the correct primary code owner of mongo integration until DBM for MongoDB is GA.
=> Reorder code owner for mongo

.github/workflows/test-target.yml, ddev/src/ddev/__init__.py
#17470 missed some changes required to make our pipelines work with the new version of the action. I should have done the same trick in that PR as I used here to trigger all the jobs.
You can see the successful jobs in the CI for commit [`65c7f33` (#17566)](https://github.com/DataDog/integrations-core/pull/17566/commits/65c7f333472f50ad418996b831571eaedf8593bc)
=> More unique artifacts

datadog_checks_base/changelog.d/17557.added, datadog_checks_base/datadog_checks/base/utils/db/timed_cache.py, datadog_checks_base/tests/base/utils/db/test_timed_cache.py
This PR introduces the `TimedCache` class, which adds functionality for managing a cache where the entire cache expires after a set interval, and to be manually cleared. 
This `TimedCache` is intended to be used in scenario where the check caches data for multiple check runs but wants to periodically clear the cache and re-build after sometime. It's mainly to avoid a cache to grow indefinitely. 
The `TimedCache` will be first used by postgres query metrics where we need to cache the `pg_stat_statements` as baseline and keep adding new queryid to the cache as new normalized queries appear. However, to avoid the baseline cache grow overtime, we will check if the cache is expired and rebuild the baseline periodically. 
The `TimedCache` is different from cachetools `TTLCache`. In `TTLCache`, …
=> Add TimedCache for controlled cache expiration

teamcity/changelog.d/17478.fixed, teamcity/datadog_checks/teamcity/teamcity_openmetrics.py, teamcity/datadog_checks/teamcity/teamcity_rest.py
Skip adding auth type to URL if using token auth.
As currently implemented, the teamcity integration automatically adds either 'guestAuth' or 'httpAuth' to the URL, and doesn't offer any mechanism to skip adding them. However, these paths don't work when using token auth, making it impossible to use this integration with a TeamCity server that doesn't allow either anonymous access or basic auth.
=> Fix token auth for teamcity integration

requirements-agent-release.txt
This part 1 of the fix to address the misunderstanding that some users may have about the `requirements-agent-release.txt`'s purpose.
It focuses on making the file unusable with `pip` directly. We also add a note to the file warning users against modifying the file or passing it to pip.
=> Quick fix for dependency confusion

mongo/changelog.d/17576.added, mongo/datadog_checks/mongo/config.py, mongo/tests/test_integration.py
This PR adds tag `cluster_name` to mongo metrics when `cluster_name` is configured in conf.yaml. 
https://datadoghq.atlassian.net/browse/DBMON-4005
=> [mongo] Add cluster_name to metrics tags

.github/workflows/test-results-master.yml, .github/workflows/test-results-pr.yml
When we collect test results for publishing we should account for the fact that our test result artifacts now have names that include more than just "test-result"
=> Fix how we collect test results to publish them

mongo/changelog.d/17576.added, mongo/datadog_checks/mongo/config.py, mongo/tests/test_integration.py
This reverts commit 58abe3d64d6672c4f8f4c778d6ec5f4d3fb05b71. The `cluster_name` tag conflicts with k8s cluster_name.
=> Revert "[mongo] Add cluster_name to metrics tags (#17576)"

.github/workflows/submit-traces.yml
1. Adjusts submit-traces action to the new artifact naming convention
2. Simplifies the action by dropping an unused input
=> Simplify submit-trace action and adjust it to new artifact upload

.github/workflows/test-target.yml
Leaving breadcrumbs so that next time others (or I myself) have a look at CI config, we can get up to speed easier.
=> Give some context to the test-target action

teleport/README.md, teleport/manifest.json
Makes the Teleport integration documentation to be publically available on the documentation website.
=> Make Teleport Documentation Public

datadog_checks_base/changelog.d/17597.added, datadog_checks_base/datadog_checks/base/stubs/datadog_agent.py
This PR adds `obfuscate_mongodb_string` to `datadog_agent` stub. The `obfuscate_mongodb_string` function is implemented in https://github.com/DataDog/datadog-agent/pull/25569
=> [base] add obfuscate_mongodb_string to datadog_agent stub

.github/workflows/update-dependencies.yml
When the bot updates the dependencies, it makes 2 commits: one to bump the deps, separate one to update changelogs.
Github PR UI only shows checks for the second commit, which don't include tests (changelogs don't trigger tests). So it's harder to see at a glance if the dependency update bump was fine.
This way GitHub PR UI shows tests for affected integrations as well.
=> Dependency and changelog update in one commit

kafka/changelog.d/17612.added, kafka/datadog_checks/kafka/data/metrics.yaml, kafka/metadata.csv
Updates the metrics.yaml for the kafka integration to collect the bufferpool-wait-time-ns-total and bufferpool-wait-ratio attributes from the kafka producer
https://datadoghq.atlassian.net/browse/AI-3858
=> Add bufferpool-wait-time-ns-total and bufferpool-wait-ratio for kafka producer

mysql/metadata.csv
If more than one underscore (`_`) exists in a string, then this breaks our docs UI, e.g.:
This PR adds backticks (``) to the remaining areas in the MySQL Integration docs where this issue occurs.
See above.
N/A
=> Fix other formatting issues in MySQL Integration docs

openstack_controller/changelog.d/17643.added, openstack_controller/datadog_checks/openstack_controller/metrics.py, openstack_controller/tests/test_unit_cinder.py
To monitor Openstack resources using Ceph, we are allowing for filtering of cinder volumes by adding a volume_type tag. Customers can simply set the volume_type of a Ceph volume to 'ceph', and filter the volumes with ‘volume_type=ceph’.
=> [PLINT-347] Add volume_type tag to cinder volumes for ceph monitoring

mongo/assets/configuration/spec.yaml, mongo/datadog_checks/mongo/data/conf.yaml.example
This PR hides `dbm` config option in `conf.yaml.example` for mongo.
https://datadoghq.atlassian.net/browse/DBMON-4088
=> Hide dbm config option for mongo

datadog_checks_base/changelog.d/17667.added, datadog_checks_base/datadog_checks/base/agent.py, datadog_checks_base/datadog_checks/base/checks/base.py, datadog_checks_base/datadog_checks/base/checks/kube_leader/mixins.py, datadog_checks_base/datadog_checks/base/checks/openmetrics/mixins.py, datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/scraper.py, datadog_checks_base/datadog_checks/base/log.py, datadog_checks_base/datadog_checks/base/utils/__init__.py, datadog_checks_base/datadog_checks/base/utils/db/utils.py, datadog_checks_base/datadog_checks/base/utils/headers.py, datadog_checks_base/datadog_checks/base/utils/http.py, datadog_checks_base/datadog_checks/base/utils/metadata/core.py, datadog_checks_base/datadog_checks/base/utils/replay/redirect.py, datadog_checks_base/datadog_checks/base/utils/tracing.py, datadog_checks_base/tests/test_metadata.py
Reduce clutter; I'm about to add another spot where we use the `datadog_agent` object
Individual integrations can be modified in a separate PR after this is released and they bump the minimum supported version of the base package
=> Add dedicated module for the Agent interface

.github/workflows/pr.yml
Reverts DataDog/integrations-core#17652
Discussed offline, we must revert temporarily
=> Revert "Run PR test with access to tokens"
