DataDog/integrations-core

windows_performance_counters/README.md
Adds a blog link to the Windows Performance Counters doc.
=> Add blog link to Windows Performance Counters doc

http_check/tests/conftest.py
Add more conditions to the e2e environment
The env is flaky https://github.com/DataDog/integrations-core/actions/runs/7846711536/job/21414130651
=> Add more conditions to the e2e environment

.github/workflows/backport-pr.yml, .github/workflows/labeler-community.yml, .github/workflows/labeler-reusable.yml, .github/workflows/labeler.yml, .github/workflows/update-agent-changelog.yml, .github/workflows/update-dependencies.yml
Use the token from the `datadog-agent-integrations-bot` GH app
The old bot no longer exists
=> Use the token from the `datadog-agent-integrations-bot` GH app

fluxcd/README.md
It's unclear how to install the integration on agent <= 7.51.0.
=> Describe how to install community version of integration.

ibm_i/README.md
Describes why there is no support for IBM i currently
=> [Update] Describe support for Windows

fluxcd/README.md
=> Consistent naming of Flux system

snmp/assets/configuration/spec.yaml, snmp/changelog.d/16881.added, snmp/datadog_checks/snmp/data/conf.yaml.example
Adds documentation to the SNMP integration for ping.
Documenting changes brought to the agent with this PR: https://github.com/DataDog/datadog-agent/pull/21939
=> [NDMII-2518] Add ping documentation

fluxcd/assets/dashboards/fluxcd.json
While migrating the integration to the agent we touched up the dashboard.
=> Update fluxcd dashboard

datadog_checks_base/CHANGELOG.md
Our automation missed this because the integration's release tag was not on `master` branch.
=> Add entry for 7.51.0 bugfix release

nginx/assets/saved_views/5xx_errors.json, tomcat/assets/saved_views/tomcat_4xx.json, tomcat/assets/saved_views/tomcat_5xx.json, tomcat/assets/saved_views/tomcat_status_code_overview.json, tomcat/manifest.json
Add logs saved views to the Tomcat integration.
- Quickly get the errors from your Tomcat servers
=> Add some log saved views

.github/workflows/build-deps.yml
[`19c3628` (#16798)](https://github.com/DataDog/integrations-core/pull/16798/commits/19c3628e1316cea8eb676f81c71b96cd1ffaafec)
=> Always save image digests

tomcat/assets/saved_views/tomcat_overview.json, tomcat/manifest.json
Add an overview saved_view
Part of the refresh 
https://datadoghq.atlassian.net/browse/AI-3754
=> Add an overview saved_view

nginx/hatch.toml, nginx/tests/test_nginx.py, nginx/tests/test_unit.py
Part of https://datadoghq.atlassian.net/browse/AI-3774
- Decouple it from the implementation.
- Make sure we test both values of the config setting.
Follow-up to https://github.com/DataDog/integrations-core/pull/16797.
Want to make it explicit that
=> Improve tests for generic tag removal

ddev/changelog.d/16905.added, ddev/src/ddev/cli/release/__init__.py, ddev/src/ddev/cli/release/branch/__init__.py, ddev/src/ddev/cli/release/branch/create.py, ddev/src/ddev/utils/github.py, ddev/tests/cli/release/branch/__init__.py, ddev/tests/cli/release/branch/test_create.py, ddev/tests/conftest.py, ddev/tests/fixtures/network/github/create_label.yaml, ddev/tests/utils/test_github.py
Add a command to create the release branch. This command will also create the `backport/` label for this branch which can be used to backport PR.
Example: 
```
❯ ddev release branch create 4.4.x
Checking out the master branch....                                                                                                                                                                                                                                                                                                                      
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
Done.
Updating the master branch...
From github.com:DataDog/integrations-core
* branch                  master     -> FETCH_HEAD
Already up to date.
Done.
Creating the release branch …
```
=> Add a command to create the release branch

snowflake/tests/keys/README
Explain how to generate the keys
In our tests we use keys but we don't explain how to get them.
=> Explain how to generate the keys

sqlserver/README.md
Adds a blog link to the SQL Server integration doc.
Tuesday Tasks on Docs Team
=> Add blog link to SQL Server integration docs

datadog_checks_dev/tests/tooling/manifest_validator/test_v2_validator.py
Fix a manifest test
https://github.com/DataDog/integrations-core/pull/16865 broke these tests because they rely on the current repo and not on a fake version
=> Fix manifest tests

sqlserver/changelog.d/16910.fixed, sqlserver/datadog_checks/sqlserver/metrics.py
=> [DBM] - Backport Fix space-used returning as None on azure sql servers (#16910)

sqlserver/CHANGELOG.md, sqlserver/changelog.d/16910.fixed
=> Port #16941 to 7.52.x

requirements-agent-release.txt, sqlserver/CHANGELOG.md, sqlserver/changelog.d/16910.fixed, sqlserver/datadog_checks/sqlserver/__about__.py
Port https://github.com/DataDog/integrations-core/pull/16943 to master
=> [Release] Bumped sqlserver version to 17.0.1 (#16943)

etcd/README.md
Adds blog links for etcd integration. Part of Tuesday Tasks on the Docs Team.
=> Add blog links for etcd integration

datadog_checks_dev/changelog.d/16972.fixed, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/pyproject.toml, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/pyproject.toml
Bump the required python version in the integration templates
7.51.0 is out with py3.11
=> Bump the required python version in the integration templates

envoy/assets/dashboards/openmetrics_overview.json
Log setion group name was missing
=> log group rename

airflow/assets/dashboards/overview.json
Adds some features/descriptions missed in the first iteration of Airflow dashboard revamp.
=> Airflow touch up

nvidia_triton/assets/dashboards/nvidia_triton_overview.json, nvidia_triton/manifest.json
=> dashboard touchup

fluxcd/README.md
Removes an extraneous comma from the JSON.
=> DOCS-7311 - remove comma from json

CONTRIBUTING.md, docs/developer/guidelines/pr.md
=> Improve PR guidelines and make them easier to discover

nvidia_triton/manifest.json
Add the AI/ML category 
We forgot to add it when we created the integration
=> Add the AI/ML category

fluxcd/manifest.json
=> Add CI/CD label to Flux

.github/workflows/docs.yml
=> Cache python depedencies to speed up docs job

ddev/changelog.d/17068.fixed, ddev/src/ddev/integration/core.py, ddev/tests/repo/test_core.py
Remove tox references
We don't use it anymore
=> Remove tox references

datadog_checks_dev/changelog.d/17071.fixed, datadog_checks_dev/datadog_checks/dev/utils.py
Add utility function to assert service checks
- https://github.com/DataDog/integrations-core/pull/17070#discussion_r1514257054
- Avoid copy/pasting this everywhere
=> Add utility function to assert service checks

sqlserver/README.md
=> [DBMON-3742] Update docs to include fixed versions for issue.

cockroachdb/hatch.toml, cockroachdb/tests/docker/docker-compose.yaml
Add a test environment with the latest version
Update the test envs
=> Add a test environment with the latest version

datadog_checks_downloader/tests/test_downloader.py
Fix an import
- [Silly me](https://github.com/DataDog/integrations-core/pull/16514/files)
- https://github.com/DataDog/integrations-core/actions/runs/8189951738/job/22396086212#step:13:477
=> Fix an import

cisco_aci/CHANGELOG.md, cisco_aci/changelog.d/17054.security, cisco_aci/datadog_checks/cisco_aci/__about__.py, datadog_checks_base/CHANGELOG.md, datadog_checks_base/changelog.d/17054.security, datadog_checks_base/datadog_checks/base/__about__.py, http_check/CHANGELOG.md, http_check/changelog.d/17054.security, http_check/datadog_checks/http_check/__about__.py, mysql/CHANGELOG.md, mysql/changelog.d/17054.security, mysql/datadog_checks/mysql/__about__.py, requirements-agent-release.txt, tls/CHANGELOG.md, tls/changelog.d/17054.security, tls/datadog_checks/tls/__about__.py
Port https://github.com/DataDog/integrations-core/pull/17093 to master
=> Port #17093 to master

datadog_checks_base/changelog.d/17099.added, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, snowflake/changelog.d/17099.added, snowflake/pyproject.toml
bump snowflake
We need it to have cryptography 42+
=> bump snowflake

datadog_checks_base/CHANGELOG.md, datadog_checks_base/datadog_checks/base/__about__.py, requirements-agent-release.txt, snowflake/CHANGELOG.md, snowflake/datadog_checks/snowflake/__about__.py
Port https://github.com/DataDog/integrations-core/pull/17106 to master
=> Release snowflake and the base check (#17106)

openstack_controller/changelog.d/16930.added, openstack_controller/changelog.d/17026.added, openstack_controller/changelog.d/17100.added, openstack_controller/datadog_checks/openstack_controller/api/api_rest.py, openstack_controller/datadog_checks/openstack_controller/api/api_sdk.py, openstack_controller/tests/config/openstack_config_updated.yaml, openstack_controller/tests/conftest.py, openstack_controller/tests/fixtures/GET/load-balancer/v2/lbaas/loadbalancers/project_id=1e6e233e637d4d55a50a62b63398ad15/limit=1/marker=4bb7bfb1-83c2-45e8-b0e1-ed3022329115/response.json, openstack_controller/tests/fixtures/GET/load-balancer/v2/lbaas/loadbalancers/project_id=1e6e233e637d4d55a50a62b63398ad15/limit=1/response.json, openstack_controller/tests/fixtures/GET/load-balancer/v2/lbaas/loadbalancers/project_id=1e6e233e637d4d55a50a62b63398ad15/limit=1000/response.json, openstack_controller/tests/fixtures/GET/load-balancer/v2/lbaas/loadbalancers/project_id=6e39099cccde4f809b003d9e0dd09304/limit=1/response.json, openstack_controller/tests/fixtures/GET/load-balancer/v2/lbaas/loadbalancers/project_id=6e39099cccde4f809b003d9e0dd09304/limit=1000/response.json, openstack_controller/tests/test_unit_octavia.py
Adding pagination support for loadbalancers.
=> [PLINT-246] Add pagination support for loadbalancers

btrfs/CHANGELOG.md, btrfs/changelog.d/17112.added, btrfs/datadog_checks/btrfs/__about__.py, datadog_checks_base/CHANGELOG.md, datadog_checks_base/changelog.d/17112.added, datadog_checks_base/datadog_checks/base/__about__.py, disk/CHANGELOG.md, disk/changelog.d/17112.added, disk/datadog_checks/disk/__about__.py, gunicorn/CHANGELOG.md, gunicorn/changelog.d/17112.added, gunicorn/datadog_checks/gunicorn/__about__.py, ibm_mq/CHANGELOG.md, ibm_mq/changelog.d/17112.added, ibm_mq/datadog_checks/ibm_mq/__about__.py, network/CHANGELOG.md, network/changelog.d/17112.added, network/datadog_checks/network/__about__.py, process/CHANGELOG.md, process/changelog.d/17112.added, process/datadog_checks/process/__about__.py, requirements-agent-release.txt, system_core/CHANGELOG.md, system_core/changelog.d/17112.added, system_core/datadog_checks/system_core/__about__.py, system_swap/CHANGELOG.md, system_swap/changelog.d/17112.added, system_swap/datadog_checks/system_swap/__about__.py
Port https://github.com/DataDog/integrations-core/pull/17115 to master
#incident-25881
=> Release integrations with psutil

gitlab_runner/tests/test_e2e.py
Make e2e test less likely to flake
=> e2e test focuses on whether we can connect to gitlab instance

.pre-commit-config.yaml
Add a hook to validate metadata files
Got burnt in another PR
=> Add a hook to validate metadata files

openstack_controller/changelog.d/17120.added, openstack_controller/datadog_checks/openstack_controller/api/api_rest.py, openstack_controller/datadog_checks/openstack_controller/api/api_sdk.py, openstack_controller/tests/conftest.py, openstack_controller/tests/fixtures/GET/load-balancer/v2/lbaas/listeners/project_id=1e6e233e637d4d55a50a62b63398ad15/limit=1/marker=9da03992-77a4-4b65-b39a-0e106961f577/response.json, openstack_controller/tests/fixtures/GET/load-balancer/v2/lbaas/listeners/project_id=1e6e233e637d4d55a50a62b63398ad15/limit=1/marker=de81cbdc-8207-4253-8f21-3eea9870e7a9/response.json, openstack_controller/tests/fixtures/GET/load-balancer/v2/lbaas/listeners/project_id=1e6e233e637d4d55a50a62b63398ad15/limit=1/response.json, openstack_controller/tests/fixtures/GET/load-balancer/v2/lbaas/listeners/project_id=1e6e233e637d4d55a50a62b63398ad15/limit=1000/response.json, openstack_controller/tests/fixtures/GET/load-balancer/v2/lbaas/listeners/project_id=6e39099cccde4f809b003d9e0dd09304/limit=1/response.json, openstack_controller/tests/fixtures/GET/load-balancer/v2/lbaas/listeners/project_id=6e39099cccde4f809b003d9e0dd09304/limit=1000/response.json, openstack_controller/tests/test_unit_octavia.py
Adding pagination support for listeners
=> [PLINT-246] Add pagination support for listeners

spark/assets/dashboards/databricks_overview.json
This PR revamps OOTB dashboard for Databricks
https://datadoghq.atlassian.net/browse/AI-3788
=> [Databricks] Dashboard revamp

openstack_controller/changelog.d/17140.added, openstack_controller/datadog_checks/openstack_controller/api/api_rest.py, openstack_controller/datadog_checks/openstack_controller/api/api_sdk.py, openstack_controller/tests/conftest.py, openstack_controller/tests/fixtures/GET/load-balancer/v2/lbaas/pools/project_id=1e6e233e637d4d55a50a62b63398ad15/limit=1/marker=d0335b34-3115-4b3b-9a1a-7e2363ebfee3/response.json, openstack_controller/tests/fixtures/GET/load-balancer/v2/lbaas/pools/project_id=1e6e233e637d4d55a50a62b63398ad15/limit=1/response.json, openstack_controller/tests/fixtures/GET/load-balancer/v2/lbaas/pools/project_id=1e6e233e637d4d55a50a62b63398ad15/limit=1000/response.json, openstack_controller/tests/fixtures/GET/load-balancer/v2/lbaas/pools/project_id=6e39099cccde4f809b003d9e0dd09304/limit=1/response.json, openstack_controller/tests/fixtures/GET/load-balancer/v2/lbaas/pools/project_id=6e39099cccde4f809b003d9e0dd09304/limit=1000/response.json, openstack_controller/tests/test_unit_octavia.py
Adding pagination support for pools.
=> [PLINT-246] Add pagination support for pools

nvidia_triton/assets/dashboards/nvidia_triton_overview.json
=> Remove reference to rabbitmq from nvidia triton dashboard

teleport/datadog_checks/teleport/metrics.py, teleport/tests/common.py, teleport/tests/fixtures/metrics.txt, teleport/tests/test_database.py
=> [PLINT-305] Report metrics for the Teleport Database Service

teleport/datadog_checks/teleport/metrics.py, teleport/tests/common.py, teleport/tests/fixtures/metrics.txt, teleport/tests/test_bpf.py
=> [PLINT-308] Report metrics for the Teleport Enhanced Session Recording / BPF

teleport/datadog_checks/teleport/metrics.py, teleport/tests/common.py, teleport/tests/test_prometheus.py
=> [PLINT-307] Report metrics for the Teleport internal Prometheus

kube_controller_manager/hatch.toml, kube_scheduler/hatch.toml
This pin applies https://github.com/DataDog/integrations-core/pull/17181 to the nightly job that checks compatibility with the base check.
=> Pin requests-oauthlib for py2 in kube scheduler and controller tests

nginx/assets/configuration/spec.yaml, nginx/changelog.d/17173.fixed, nginx/datadog_checks/nginx/data/conf.yaml.example
=> Document that disabling generic tags only matters for service checks

strimzi/README.md
Add Further Reading with Blog Link for Strimzi
https://www.datadoghq.com/blog/container-native-integrations/#messaging-and-streaming-with-strimzi
=> Add Further Reading with Blog Link for Strimzi

fluxcd/README.md
Add Further Reading with Blog Link for Flux
https://www.datadoghq.com/blog/container-native-integrations/#cicd-with-flux
=> Add Further Reading with Blog Link for Flux

mysql/CHANGELOG.md, mysql/changelog.d/16924.fixed, mysql/changelog.d/16936.fixed, postgres/CHANGELOG.md, sqlserver/CHANGELOG.md, sqlserver/changelog.d/16977.fixed
This PR removes ticket id from postgres, mysql and sqlserver changelog entries.
=> Remove ticket id from changelog entries

ddev/tests/cli/validate/test_metrics.py
Fix metadata tests
- https://github.com/DataDog/integrations-core/actions/runs/8325943970/job/22780815224
- Broken they depends on the file in the repo and I modified them: https://github.com/DataDog/integrations-core/pull/17177
=> Fix metadata tests

fluxcd/manifest.json
=> Process signature for fluxcd

cisco_secure_firewall/CHANGELOG.md, cisco_secure_firewall/datadog_checks/cisco_secure_firewall/__about__.py
Fix the version
- Missed it in https://github.com/DataDog/integrations-core/pull/16747
- It will be bumped during the realease
=> Fix the version

sqlserver/datadog_checks/sqlserver/sqlserver.py
Fixes typo in a service function call check
=> fix typo in function name

ddev/changelog.d/17222.fixed, ddev/src/ddev/cli/release/changelog/new.py
Also make entry type arg clearer in docs
=> Say changelog entries are in Markdown format.

cassandra/README.md, hazelcast/README.md, hive/README.md, hivemq/README.md, ignite/README.md, jboss_wildfly/README.md, presto/README.md, sonarqube/README.md
Update the readme file for JMX integrations
`info` is the Agent v5 command, which was renamed to `status` with Agent 6+ so that can be confusing.
=> Update the readme file for JMX integrations

cisco_duo/assets/logs/cisco-duo_tests.yaml, cisco_secure_firewall/assets/logs/cisco-secure-firewall_tests.yaml, tekton/assets/logs/tekton_tests.yaml
Fixes the integration samples that are already committed and thus failing the `LIVE` deployments of APW assets
=> Fix logs integrations test samples

ddev/changelog.d/17255.fixed, ddev/pyproject.toml
We in fact need this for codeowner validations to work.
=> Bump datadog_checks_dev required version

.pre-commit-config.yaml
Add a note to install hooks internally
This is the approved way to do it
=> Add a note to install hooks internally

karpenter/assets/saved_views/karpenter_error_logs.json, karpenter/assets/saved_views/karpenter_overview.json, karpenter/manifest.json
Simple saved view for karpenter logs
=> Add simple saved views for Karpenter

cockroachdb/CHANGELOG.md
Credit @sudomateo for their contributions to the release. 
https://github.com/DataDog/integrations-core/pull/16697#issuecomment-2011779768
=> Mention contributors in the changelog

istio/tests/test_e2e.py, istio/tests/test_unit_istio_v1.py, istio/tests/test_unit_istio_v2.py
Rename test files and remove unneeded markers
Same as https://github.com/DataDog/integrations-core/pull/17278
=> Rename test files

tekton/tests/common.py, tekton/tests/test_e2e.py
Add optional metrics
- Sometimes, they are there https://github.com/DataDog/integrations-core/actions/runs/8438855923/job/23112206872#step:15:364
=> Add optional metrics

eks_fargate/README.md
This fixes the product name to make Network Performance Monitoring support (or lack thereof) more clear for our customers.
=> Fix NPM product name

argo_workflows/assets/dashboards/argo_workflows.json, argo_workflows/manifest.json
=> Add dashboard for argo workflows

docs/developer/meta/cd.md, docs/developer/meta/ci/labels.md, docs/developer/process/integration-release.md, mkdocs.yml
We don't do continuous delivery (yet) so even if we were to find bandwidth to fill it out we couldn't :joy:
=> Remove empty docs page about Continuous Delivery.

checkpoint_quantum_firewall/CHANGELOG.md, checkpoint_quantum_firewall/changelog.d/16522.changed, checkpoint_quantum_firewall/datadog_checks/checkpoint_quantum_firewall/__about__.py, palo_alto_panorama/CHANGELOG.md, palo_alto_panorama/changelog.d/16748.added, palo_alto_panorama/datadog_checks/palo_alto_panorama/__about__.py, requirements-agent-release.txt
=> Backport Palo Alto Panorama and Checkpoint Quantum Firewall into master

argo_workflows/README.md
=> Readme for Argo Workflows

argo_workflows/assets/dashboards/argo_workflows.json, argo_workflows/assets/monitors/errors.json, argo_workflows/manifest.json
=> Add monitor to Argo Workflows

.builders/lock.py, .builders/scripts/build_wheels.py, .builders/upload.py
The domain name and certificate has been finalized along with a fresh bucket for use.
=> Finalize dependency storage location

oracle/tests/docker/Dockerfile
Use a custom image to run the tests
The current image is gone
=> Use a custom image to run the tests

istio/assets/saved_views/istio_error_overview.json, istio/assets/saved_views/istio_overview.json, istio/assets/saved_views/istio_pilot_errors.json, istio/assets/saved_views/istio_pilot_logs.json, istio/assets/saved_views/istio_proxyv2_errors.json, istio/assets/saved_views/istio_proxyv2_logs.json, istio/manifest.json
Simple Saved Views for istio logs
=> istio saved views

.github/workflows/build-deps.yml
There is no image to inspect for the save step https://github.com/DataDog/integrations-core/actions/runs/8527249884/job/23360726169#step:15:19
=> Fix dependency builds

boundary/changelog.d/17337.fixed, boundary/datadog_checks/boundary/check.py, boundary/tests/test_unit.py
Do not fail if no tags are provided in the config
Same as https://github.com/DataDog/integrations-core/pull/17336 but for boundary
=> Do not fail if no tags are provided in the config

.github/workflows/docs.yml
=> Trigger docs build and validation for base check dependency bumps

.github/workflows/docs.yml
Run the docs job on PR that modifies it
So we can catch issues 🙂
=> Run the docs job on PR that modifies it

argo_workflows/assets/saved_views/errors.json, argo_workflows/assets/saved_views/overview.json, argo_workflows/manifest.json
=> Add Saved Views for Argo Workflows

fluxcd/assets/saved_views/errors.json, fluxcd/assets/saved_views/overview.json, fluxcd/manifest.json
=> Add saved views for Flux

esxi/tests/test_unit.py
We currently only have an integration test for this and nothing asserting the log line
better unit test coverage
=> Add unit test for ESXI up

pan_firewall/README.md
[DOCS-7553](https://datadoghq.atlassian.net/browse/DOCS-7553)
Adding information on how metrics are pulled in for this integration.
[DOCS-7553]: https://datadoghq.atlassian.net/browse/DOCS-7553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> adding information on metrics for PANOS integration

ray/README.md
Remove trailing comma in config example
Trailing comma is incorrect JSON syntax, and customers who copy paste this example will not see data come through to Datadog.
[[slack discussion](https://dd.slack.com/archives/C0DESMBQU/p1713187226290539)]
Please merge after review
=> Remove trailing comma

tomcat/README.md
Corrects the example commands.
DOCS-7509
=> Update example commands

snowflake/README.md
Removes an outdated warning banner.
Outdated docs
=> Removes outdated warning banner

snmp/tests/conftest.py
Following [this PR](https://github.com/DataDog/datadog-agent/pull/24724), change tests e2e
=> [NDM][NDMII-2635]test the automatic activation of autodiscovery

.github/workflows/build-ddev.yml, .github/workflows/cache-shared-deps.yml, .github/workflows/compute-matrix.yml, .github/workflows/docs.yml, .github/workflows/pr-quick-check.yml, .github/workflows/release-base.yml, .github/workflows/release-dev.yml, .github/workflows/release-hash-check.yml, .github/workflows/run-validations.yml, .github/workflows/submit-traces.yml, .github/workflows/test-results-master.yml, .github/workflows/test-target.yml
=> Upgrade checkout action to use Node 20

fluxcd/README.md
- Flux is only deployed on kubernetes, host and docker configurations.
- Add section for collecting logs.
- Mention which services/pods from flux we monitor.
=> Fluxcd Readme Improvements

esxi/assets/configuration/spec.yaml, esxi/datadog_checks/esxi/check.py, esxi/datadog_checks/esxi/config_models/instance.py, esxi/datadog_checks/esxi/constants.py, esxi/datadog_checks/esxi/data/conf.yaml.example, esxi/datadog_checks/esxi/resource_filters.py, esxi/datadog_checks/esxi/utils.py, esxi/tests/test_unit.py
Adds support for resource filters
=> [PLINT-313] Add support for resource filters 

esxi/datadog_checks/esxi/__about__.py
We will release this properly as part of preparing for the agent release.
=> fix esxi initial version number

esxi/pyproject.toml
We're using assert methods that only become available in a later version of the base package.
=> Fix minimum required base package version

.github/CODEOWNERS
=> Add Teleport folder to CODEOWNERS

esxi/CHANGELOG.md, esxi/changelog.d/17027.added, esxi/changelog.d/17459.fixed, esxi/datadog_checks/esxi/__about__.py, requirements-agent-release.txt, teleport/CHANGELOG.md, teleport/changelog.d/16877.added, teleport/datadog_checks/teleport/__about__.py
=> Release new integrations for 7.54 Agent

fluxcd/assets/dashboards/fluxcd.json
=> Implement feedback for fluxcd dashboard

.github/workflows/build-deps.yml, .github/workflows/cache-shared-deps.yml, .github/workflows/test-target.yml
=> Update cache github action to use Node 20

openmetrics/README.md
Changes the language referring to the configuration directory to be clearer
[Docs ticket](https://datadoghq.atlassian.net/browse/DOCS-7759)
=> (DOCS-7759) Change language regarding directory

weaviate/manifest.json
=> Fix description

postgres/CHANGELOG.md, postgres/changelog.d/17480.fixed, postgres/datadog_checks/postgres/__about__.py, requirements-agent-release.txt
=> [Release] [Backport 7.54.x] Include schema in filter for indexes

datadog_checks_dev/changelog.d/17491.added, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/metadata.csv, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/metadata.csv, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/metadata.csv, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/metrics_crawler/{check_name}/metadata.csv, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/tile/{check_name}/metadata.csv
Add new column to metadata.csv for integrations created with ddev.
=> add new column

postgres/assets/dashboards/postgresql_screenboard_dashboard.json
=> Missing  variable in other postgres screenboard widgets

airflow/assets/monitors/heartbeat_failures.json, airflow/assets/monitors/ongoing_duration.json
Writing recommended monitor guidelines
=> Monitor Title Fixes

cisco_duo/README.md
Fixes the instructions for configuring the integration.
=> Corrections to Cisco Duo configuration instructions

oracle/README.md
Adding a note for Oracle RAC customers that the agent must connect to each node separately
Removing ambiguity.
=> Add note for Oracle RAC customers

openstack_controller/assets/dashboards/openstack_controller_overview_[default_microversion].json
Updating openstack controller [default microversion] dashboard to include new glance metrics
=> Updating openstack controller [default microversion] dashboard to include new glance metrics

.devcontainer/dbm/Dockerfile
This PR installs `mongosh` on dbm dev containers.
=> install mongosh on dbm devcontainer

datadog_cluster_agent/CHANGELOG.md, datadog_cluster_agent/changelog.d/17530.added, datadog_cluster_agent/datadog_checks/datadog_cluster_agent/__about__.py, requirements-agent-release.txt
=> [Port to master] [Backport 7.54.x] [datadog-cluster-agent] Add CWS Instrumentation

changelog.d/17535.fixed
Adds a changelog that was missed for the internal change in https://github.com/DataDog/integrations-core/pull/17535
=> Add Changelog

tls/tests/compose/docker-compose.yml
Fix Flaky TLS Mysql test by pinning mysql image.
=> fix tls test

changelog.d/17535.fixed, postgres/assets/configuration/spec.yaml, postgres/datadog_checks/postgres/config.py, postgres/tests/test_pg_integration.py
Reverts DataDog/integrations-core#17537
=> Revert "[Backport 7.54.x] Decrease database instance collection interval"

.github/CODEOWNERS
This PR adds database-monitoring team as mongo code owner.
=> add database-monitoring team as mongo code owner

openstack_controller/assets/configuration/spec.yaml, openstack_controller/datadog_checks/openstack_controller/data/conf.yaml.example
Refer to https://dd.slack.com/archives/C051PFJ8CUB/p1715558314982139?thread_ts=1715221801.165929&cid=C051PFJ8CUB
=> Changing the conf.yaml.example file by enabling the default of use_legacy_check_version

openstack_controller/assets/dashboards/openstack_controller_overview_[default_microversion].json
Signed-off-by: rahulkaukuntla <rahul.kaukuntla@datadoghq.com>
Updating openstack controller [default microversion] dashboard to include new ironic metrics
=> Updating openstack controller [default microversion] dashboard to include new ironic metrics

airbyte/manifest.json, argocd/manifest.json, calico/manifest.json, cloudera/manifest.json, cockroachdb/manifest.json, elastic/manifest.json, envoy/manifest.json, fluxcd/manifest.json, gitlab/manifest.json, istio/manifest.json, kafka/manifest.json, langchain/manifest.json, nvidia_triton/manifest.json, openstack/manifest.json, openstack_controller/manifest.json, ray/manifest.json, strimzi/manifest.json, temporal/manifest.json, torchserve/manifest.json, weaviate/manifest.json
Product did an analysis of recently created or updated integrations to audit their "category" tags. This PR updates all integrations that were part of that effort. Full sheet here - https://docs.google.com/spreadsheets/d/1-Q6-cvO0DlYMahYT_DeqY-WHiHDWrX76Cg04X5tsit4/edit#gid=0&fvid=524701216
=> [ECOS-1439] Update categories for newer/updated integrations

.github/workflows/build-ddev.yml
Bump pypa/gh-action-pypi-publish
- https://github.com/pypi/warehouse/issues/15611#issuecomment-2003569493
- https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.8.13
=> Bump pypa/gh-action-pypi-publish

win32_event_log/README.md, win32_event_log/assets/configuration/spec.yaml, win32_event_log/manifest.json
Add `source_type` info to windows event log integration
https://datadoghq.atlassian.net/browse/WINA-798
=> add source type info

argo_rollouts/manifest.json
=> public docs for argo rollouts

win32_event_log/manifest.json
https://datadoghq.atlassian.net/browse/WINA-768
=> match app id to dogweb id for APW

cisco_sdwan/manifest.json
Display cisco sd-wan in public docs
=> [Cisco SD-WAN] Display docs

.github/workflows/build-ddev.yml
=> Upgrade action that adds assets to github release

cisco_sdwan/README.md
Adds private beta callout to Cisco SD-WAN integration
=> [DOCS-7854] updating private beta for Cisco SD-WAN

cisco_sdwan/README.md
This fixes a broken link  to the metadata.csv file
=> Fix broken link in Cisco SD WAN integration

cisco_aci/README.md, snmp_arista/README.md, snmp_aruba/README.md, snmp_chatsworth_products/README.md, snmp_cisco/README.md, snmp_dell/README.md, snmp_f5/README.md, snmp_fortinet/README.md, snmp_hewlett_packard_enterprise/README.md, snmp_juniper/README.md
Updating existing Network Vendors integrations pages to link back to the NDM Vendor profiles table.
=> [DOCS-7957] updating Network vendors

LICENSE-3rdparty.csv
=> Sync LICENSE-3rdparty.csv

snmp/assets/dashboards/ndm_troubleshooting.json, snmp/manifest.json
Following [this PR](https://github.com/DataDog/web-ui/pull/135404) we change the the name and so the link of the Datadog NDM Environment
=> [NDM][NDMII-2722]change ndm environment dashboard name

mongo/assets/configuration/spec.yaml, mongo/datadog_checks/mongo/data/conf.yaml.example
This PR adds a private beta note for MongoDB database monitoring (dbm).
=> [mongo] update mongo dbm config note

.github/workflows/update-dependencies.yml
tested with [this job](https://github.com/DataDog/integrations-core/actions/runs/9227264006/job/25388822117?pr=17626)
=> Don't edit commit message when amending dep update commit

mysql/metadata.csv
Fixes formatting issues identified in the following areas:
https://datadoghq.atlassian.net/browse/DOCS-7983
N/A
=> Fix param formatting issue in MySQL Integration docs

.github/workflows/pr.yml
We take advantage
We think this will solve a problem with our dependency update PRs.
The problem is that for all commits other than the very first one, the tests don't run.
=> Run PR test with access to tokens

gke/README.md
Deletes worse method of setting up GKE Autopilot in favor of a link to the better method, which is already documented elsewhere in the docs.
Ticket filed by TSE
=> (DOCS-8053) Points GKE Autopilot setup instructions to existing doc

mongo/datadog_checks/mongo/mongo.py, openstack_controller/tests/test_unit_swift.py
=> Fix lint issue

teleport/README.md
Remove integration install command, as the check is included in recent versions of the Agent.
No longer needed to manually install.
=> update Teleport install instructions

win32_event_log/README.md
Adding a link to out of the box dashboard.
https://datadoghq.atlassian.net/browse/WINA-769
=> add link to Windows Event Log OOTB dashboard

mongo/datadog_checks/mongo/api.py
This is a behavior-preserving refactor, just moving some code around.
The new structure should make it easy to add another check for DocumentDB
=> Clearly separate different ways to determine deployment type

changelog.d/17535.fixed
Removes change log from integration-core root directory.
=> remove changelog entry from integration-core root

openstack_controller/assets/dashboards/openstack_controller_overview_[default_microversion].json
Signed-off-by: rahulkaukuntla <rahul.kaukuntla@datadoghq.com>
=> Updating openstack controller [default microversion] dashboard to include new heat and swift metrics

tekton/README.md, tekton/assets/service_checks.json
Small editorial review through the Tekton integration docs before it goes live.
DOCS-8126
=> DOCS-8126 Tekton Integration Doc Edits

tekton/manifest.json
=> Publish tekton documentation

.github/workflows/build-deps.yml
=> Add push action to dep build workflow

win32_event_log/README.md
Add config example for dd_security_events option
=> Add dd_security_events config example

snowflake/manifest.json
Hide the Snowflake agent integration doc
DOCS-8102
=> (DOCS-8102) Hide Snowflake agent integration doc

snowflake/manifest.json
Reverts DataDog/integrations-core#17739
=> Revert "Revert "(DOCS-8102) Hide Snowflake agent integration doc""

traefik_mesh/README.md
This PR adds annotations and logs sections to our public facing documentation.
=> Add annotations and logs sections to Readme

requirements-agent-release.txt, snmp/CHANGELOG.md, snmp/changelog.d/17722.fixed, snmp/datadog_checks/snmp/__about__.py
Porting this forward from the 7.55.x release
=> port forward

kubernetes_cluster_autoscaler/README.md
Add the annotation section to the integration docs
=> Update kubernetes cluster autoscaler docs to add annotations

cisco_sdwan/README.md
Add events and service checks to Data Collected
Metrics table is not populating under the Data Collected
=> Add events and service checks to Data Collected

openstack_controller/assets/dashboards/openstack_controller_overview_[default_microversion].json
=> Separating Heat and Swift widgets

.github/workflows/test-target.yml, rabbitmq/datadog_checks/__init__.py
=> Fix CodeCov upload job

oracle/tests/test_e2e.py
Should be enabled after test failure is fixed
=> Disable E2E test impacting master pipelines.

openstack_controller/changelog.d/17771.fixed, openstack_controller/datadog_checks/openstack_controller/components/bare_metal.py
Fix uninitialized variables
Some variables were only initialized in some branches of the code. It caused failures when the executed branch was different.
=> Fix uninitialized variables

ecs_fargate/README.md
=> Add Blog Post Link to ECS Fargate Integration

mongo/changelog.d/17798.added, mongo/changelog.d/17798.changed, mongo/datadog_checks/mongo/collectors/db_stat.py, mongo/tests/test_integration.py
=> Always collect db stats from replicaset primaries

datadog_checks_base/datadog_checks/base/utils/db/utils.py, datadog_checks_base/tests/base/utils/db/test_util.py
A follow up to https://github.com/DataDog/integrations-core/pull/17716
Applies linter.
=> Apply linter to datadog_checks_base

ddev/changelog.d/17810.fixed, ddev/src/ddev/cli/test/__init__.py
=> Help docs for --compat flag mention it implies --recreate

.codecov.yml
This simply place the Teleport entry in it's right order.
=> Fix Teleport entry in codecov.yml

.github/workflows/nightly-base-package.yml
=> Allow triggering minimum base package check manually.

fluentd/hatch.toml, fluentd/tests/compose/docker-compose.yaml
Docker image bump to fix some fluentd tests.
=> Fix Fluentd tests

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/models.py
=> variables clearly differentiate between collections and counts

marathon/tests/compose/docker-compose.yml
=> Update mesos-master and mesos-slave versions for tests

mesos_master/hatch.toml, mesos_master/tests/common.py, mesos_master/tests/fixtures/state.json, mesos_master/tests/test_integration_e2e.py
Before: 1.0.1-2.0.93.ubuntu1404, 1.1.0-2.0.107.ubuntu1404
After: 1.7.1
=> Update test docker images of mesos-master

agent_requirements.in, datadog_checks_downloader/pyproject.toml
Also tested by downloading the current repository state (with `hatch run test-data:create
`) and running the tests with that.
=> Bump TUF to address security vulnerability

snowflake/manifest.json
=> [AI-3972] rename snowflake tile

teleport/README.md
removed beta banner from this integration
this integration is no longer in beta and is in the most recent production version of the agent
=> remove Teleport beta banner

databricks/manifest.json, openai/README.md
Update openai and databricks docs to include CCM
=> [SAASINT-2441] update CCM docs

otel/README.md
- Adds Important note that already exists on OTel landing page to OTel integration page.
- Covering our bases for customers missing this important upgrade detail.
=> [DOCS-8202] Add Upgrade Guide Warning to OTel Integration Page

kubernetes_cluster_autoscaler/datadog_checks/kubernetes_cluster_autoscaler/config_models/instance.py, kubernetes_cluster_autoscaler/manifest.json
Adds the process signature for the kubernetes cluster autoscaler integration.
https://datadoghq.atlassian.net/browse/AI-3822
=> Add process signature for kubernetes cluster autoscaler

windows_service/README.md
Updating Docs for https://github.com/DataDog/integrations-core/pull/17657
https://datadoghq.atlassian.net/browse/WINA-795
=> Update README.md for Windows Service for #17657

kafka_consumer/metadata.csv
Update kafka estimated lag metrics description
[docs](https://docs.google.com/document/d/1fynnAu_xmZpelLLgNCaJgLYulW8qx5i7ULMl4Ip22us/edit?pli=1
)
=> Update kafka estimated lag metrics description

kafka_consumer/tests/common.py
Fix the unit test to be compatible with the base package.
This was fixed but reverted accidently with another change.
=> Fix unit test failing the base package

esxi/README.md
Updates esxi readme to mention per_instance_filters and link to vSphere documentation
=> Update ESXi readme

snmp_cisco/README.md
This PR adds a few links to the Cisco integration to allow other Cisco integrations to be found easier (Cisco SD-WAN/ Meraki, etc),
=> [DOCS-8304] updates to Cisco integration

.github/workflows/update-dependencies.yml
This lets us test removing items from the "exclude" list without merging to master.
For example https://github.com/DataDog/integrations-core/pull/17951 could be tested before we merge it to master.
=> Allow triggering update dependencies workflow manually

teleport/README.md
Add related link to Teleport blog post.
=> Add related link to Teleport blog post

datadog_checks_base/tests/base/utils/http/test_kerberos_int.py
=> Mark base check kerberos tests as flaky

.ddev/config.toml
It's blocking other dependency updates.
Tested by [this](https://github.com/DataDog/integrations-core/pull/17953)
=> Allow updates to kubernetes

docs/developer/guidelines/dashboards.md
=> Clarify how to pass flag for extras repo and trim whitespace

vllm/assets/monitors/latency.json, vllm/assets/monitors/token_throughput.json, vllm/manifest.json
=> Add vLLM recommended monitors

.github/workflows/flaky-tests.yml, .github/workflows/pr-test.yml, .github/workflows/test-all.yml, .github/workflows/test-target.yml, ddev/src/ddev/cli/validate/ci.py
=> Fix format issue with master pipeline flaky test management pr17910

envoy/tests/legacy/test_integration.py, envoy/tests/test_integration.py
=> Mark envoy tests as flaky

requirements-agent-release.txt, vllm/CHANGELOG.md, vllm/changelog.d/17756.added, vllm/datadog_checks/vllm/__about__.py
port https://github.com/DataDog/integrations-core/pull/17987 to master
=> [Release] Bumped vllm version to 1.0.0

cisco_sdwan/README.md
Bold Cisco sdwan beta banner
[preview](https://dd.datad0g.com/integrations/cisco-sdwan?search=cisco)
=> [NDM][Cisco SD-WAN] Bold Cisco sdwan beta banner

.github/workflows/build-deps.yml
Fix https://github.com/DataDog/integrations-core/actions/runs/9854184766, caused by https://github.com/DataDog/integrations-core/pull/17995 (Thanks GH for skipping the check instead of marking it as a failure).
=> Fix build-deps workflow yaml

kyverno/datadog_checks/kyverno/__about__.py
=> Kyverno starting version should be 0.0.1

kyverno/CHANGELOG.md, kyverno/changelog.d/17757.added, kyverno/datadog_checks/kyverno/__about__.py, requirements-agent-release.txt
=> Port kyverno release to 7.56

snmp/assets/dashboards/ndm_troubleshooting.json
Remove invalid filters from NDM environment dashboard
=> [SNMP] Remove invalid filters from dashboard

argo_rollouts/README.md
Small update on the code snippet which is causing the integration to fail.
DOCS-8383
=> DOCS-8383 Argo Rollouts Edit

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/README.md
We recently had doubts about the structure of this template. When I started digging it turned out that lots of people didn't really know how this was used and why.
Including people (ahem, me) who had definitely heard this before.
Since I can't trust our collective memory on this, I'm adding a note as close to the source as I can.
=> Add explanation to logs-only template

traefik_mesh/manifest.json
Enables public display for Traefik Mesh
=> Enable public display for Traefik Mesh

process/README.md
modifies the indents of example yaml in process/README.md
```yaml
init_config:
instances:
- name: ssh
search_string:
- ssh
- sshd
```
↓
```yaml
init_config:
instances:
- name: ssh
search_string:
- ssh
- sshd
```
To prevent setup issues regarding indents
=> Modify the indents of yaml in process / README.md

datadog_checks_dev/changelog.d/18039.added, datadog_checks_dev/datadog_checks/dev/tooling/commands/create.py, datadog_checks_dev/datadog_checks/dev/tooling/create.py, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/README.md, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/README.md, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/metrics_crawler/README.md, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/tile/README.md
=> Show descriptions of templates in ddev create help

.github/CODEOWNERS, fly_io/assets/logs/fly.io_test.yaml, fly_io/assets/logs/fly_io.yaml
=> Add logs pipeline for Fly.io

.builders/images/linux-aarch64/Dockerfile, .builders/images/linux-x86_64/Dockerfile, .builders/images/macos-x86_64/builder_setup.sh
https://datadoghq.atlassian.net/browse/VULN-7643
=> update cURL from 8.4.0 to 8.7.1

mongo/README.md
=> Fix misspelled database name

mongo/CHANGELOG.md, mongo/changelog.d/18067.fixed, mongo/datadog_checks/mongo/__about__.py, requirements-agent-release.txt
port https://github.com/DataDog/integrations-core/pull/18075 to master
=> [Release] Bumped mongo version to 6.7.2

wincrashdetect/manifest.json
make the crash detection integration documentation public
it's ready for release
=> make windows crash detection docs public

kyverno/CHANGELOG.md, kyverno/changelog.d/18088.fixed, kyverno/datadog_checks/kyverno/__about__.py, requirements-agent-release.txt
Port https://github.com/DataDog/integrations-core/pull/18094 to master
=> [Release] Bumped kyverno version to 1.0.1

kyverno/manifest.json
=> process signature

cisco_sdwan/assets/monitors/device_reboot.json, cisco_sdwan/assets/monitors/device_unreachable.json, cisco_sdwan/assets/monitors/tunnel_down.json
Update Cisco SD-WAN monitor tags
=> [NDM] Update Cisco SD-WAN monitor tags

aerospike/README.md, istio/README.md
Enhances instructions for integration configuration in containerized environments for the following integrations:
- Istio
- Aerospike
=> [DOCS-7701] readme improvements for Istio and Aerospike

vllm/assets/dashboards/overview.json, vllm/manifest.json
=> Initial feedback for vLLM dashboard

mysql/CHANGELOG.md, mysql/changelog.d/18097.fixed, mysql/datadog_checks/mysql/__about__.py, openstack_controller/CHANGELOG.md, openstack_controller/changelog.d/17996.fixed, openstack_controller/datadog_checks/openstack_controller/__about__.py, requirements-agent-release.txt
Port https://github.com/DataDog/integrations-core/pull/18113 to master
=> Port releases for rc7 of 7.56 to master

mimecast/README.md
=> remove angle braces to fix integration sync issues

teleport/README.md, teleport/manifest.json
updates Teleport tile to include resource links (blog and documentation)
=> update Teleport overview and tile

databricks/README.md
=> Fix formatting of the DJM callout

kyverno/assets/dashboards/overview.json, kyverno/manifest.json
=> kyverno ootb dashboard

ddev/changelog.d/18147.added, ddev/src/ddev/cli/validate/metadata_utils.py
Add new metric unit_names:
https://github.com/DataDog/dogweb/pull/98741
=> add joule metric units

cisco_secure_endpoint/manifest.json, mimecast/manifest.json, network_path/manifest.json, palo_alto_cortex_xdr/manifest.json, sophos_central_cloud/manifest.json
=> add missing offering tags

kyverno/CHANGELOG.md, kyverno/changelog.d/18149.fixed, kyverno/datadog_checks/kyverno/__about__.py, postgres/CHANGELOG.md, postgres/changelog.d/18009.fixed, postgres/datadog_checks/postgres/__about__.py, requirements-agent-release.txt
Port https://github.com/DataDog/integrations-core/pull/18162 to master
=> Port releases to master

ddev/src/ddev/cli/release/changelog/fix.py, ddev/src/ddev/cli/release/changelog/new.py, ddev/src/ddev/cli/status/__init__.py, ddev/src/ddev/repo/core.py, ddev/src/ddev/utils/git.py, ddev/tests/cli/release/agent/test_changelog.py, ddev/tests/cli/release/branch/test_create.py, ddev/tests/cli/release/test_changelog.py, ddev/tests/helpers/api.py, ddev/tests/utils/test_git.py
- Improve name for class.
- Drop premature optimizations to simplify code and tests.
- When getting tags we can now use git's built-in filtering mechanism
I want to use this abstraction for a command I'm adding. I noticed some small stuff can be tweaked along the way, so I went for it.
=> Refactor git repository abstraction

datadog_operator/manifest.json
=> Add missing category tag

spark/README.md
Link to DJM from Spark docs
Spark users would want to get DJM but end up in Spark docs
=> Add DJM callout to Spark documentation

oom_kill/manifest.json, prometheus/manifest.json
[ECT-1772](https://datadoghq.atlassian.net/browse/ECT-1772)
Tag following integrations with `event management`:
oom_kill
prometheus
When searching integrations with event management, these integrations will show in the searching result.
[ECT-1772]: https://datadoghq.atlassian.net/browse/ECT-1772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Tag integrations with event management

datadog_checks_dev/changelog.d/18168.fixed, datadog_checks_dev/pyproject.toml
=> Pin towncrier to 23.11, subsequent release broke us

.ddev/ci/scripts/sqlserver/linux/55_install_odbc.sh, .devcontainer/dbm/Dockerfile
This PR fixes msodbcsql18 version in ci
=> fix msodbcsql18 version in ci

.github/workflows/pr-quick-check.yml, .github/workflows/run-validations.yml
Keeping CI tooling up to date and staying on GH's good side :joy:
=> Upgrade github-script action to use newer Node version

mapreduce/tests/test_e2e.py, marklogic/tests/test_marklogic.py, sqlserver/tests/test_agent_jobs.py
=> Mark some known flaky tests

postgres/tests/test_cursor.py
=> Mark flaky postgres test

sap_hana/hatch.toml
They dropped the tag we were using from docker hub, that broke our e2e environment.
=> Fix SAP Hana docker image tag

sqlserver/tests/test_metadata.py, sqlserver/tests/test_statements.py, sqlserver/tests/test_stored_procedures.py
=> Mark some sqlserver flaky tests

teamcity/changelog.d/18122.fixed, teamcity/datadog_checks/teamcity/teamcity_rest.py
=> [AGENT-11701] Fix handling of deleted build config

ibm_mq/tests/test_utils.py
=> Mark ibm MQ test as flaky

istio/README.md
Clarifies and adds more detail for getting logs from Istio.
=> improving Istio logging docs

.github/workflows/pr-quick-check.yml, .github/workflows/run-validations.yml
Fix gh action after it was updated:
https://github.com/actions/github-script#:~:text=For%20example%2C%20github.issues.createComment%20in%20V4%20becomes%20github.rest.issues.createComment%20in%20V5
=> fix gh action

ddev/changelog.d/18206.added, ddev/pyproject.toml
=> Bump datadog_checks_dev dependency to 33.0+.

ddev/CHANGELOG.md, ddev/changelog.d/17615.removed, ddev/changelog.d/17932.added, ddev/changelog.d/17934.added, ddev/changelog.d/17969.fixed, ddev/changelog.d/18063.added, ddev/changelog.d/18147.added, ddev/changelog.d/18206.added
=> [Release] Bumped ddev version to 10.0.0

vllm/README.md, vllm/assets/logs/vllm.yaml, vllm/assets/logs/vllm_tests.yaml, vllm/assets/saved_views/errors.json, vllm/manifest.json
Here's the logs-backend ticket https://datadoghq.atlassian.net/browse/LOI-243
=> Add logs pipeline to vllm

sqlserver/tests/test_activity.py
=> Mark sqlserver test as flaky

mongo/README.md
=> [mongo] fix doc for metrics prefix for additional_metrics

datadog_checks_dev/changelog.d/18217.added, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/licenses.py
Reverts DataDog/integrations-core#18217
=> Revert "Add new `ddtrace` license to known licenses"

strimzi/tests/test_e2e.py
=> Mark strimzi e2e test as flaky

docs/developer/base/api.md
=> Expose methods related to submitting logs in developer docs

ibm_ace/tests/test_e2e.py
=> Mark IBM Ace test as flaky

docs/developer/tutorials/memory-profiling.md, mkdocs.yml
=> Remove empty docs page

dcgm/README.md
=> Remove `provides` from DCGM

sap_hana/README.md, sap_hana/assets/configuration/spec.yaml, sap_hana/changelog.d/18193.added, sap_hana/datadog_checks/sap_hana/data/conf.yaml.example, sap_hana/datadog_checks/sap_hana/queries.py, sap_hana/datadog_checks/sap_hana/sap_hana.py, sap_hana/pyproject.toml, sap_hana/tests/conftest.py, sap_hana/tests/test_integration.py
=> Collect audit logs

zeek/manifest.json
=> Make Zeek docs page public

sqlserver/changelog.d/18249.fixed
=> Add missing changelog entry for #18249

requirements-agent-release.txt, sqlserver/CHANGELOG.md, sqlserver/changelog.d/18249.fixed, sqlserver/datadog_checks/sqlserver/__about__.py
Port https://github.com/DataDog/integrations-core/pull/18260 to master
=> Port sqlserver release to master

ping_federate/README.md
- Fenced code blocks on separate lines
- Add Support header since it's listed on the manifest file.
- Documentation build
=> Break out fenced code blocks

calico/tests/test_e2e.py
=> Mark calico e2e as flaky

.github/workflows/labeler-reusable.yml
=> Document the labeler cannot create new labels

dotnetclr/tests/e2e_test.py, kafka_consumer/tests/test_integration.py, vault/tests/test_integration.py
=> More flaky test markers

suricata/README.md
- Update agent-version to 7.57.0 in README
=> DDS: Update Agent Version in Readme

fly_io/assets/dashboards/overview.json, fly_io/manifest.json
Adds a default dashboard for fly
=> Add default dashboard

requirements-agent-release.txt, sqlserver/CHANGELOG.md, sqlserver/changelog.d/18292.fixed, sqlserver/datadog_checks/sqlserver/__about__.py
=> [Port to master][sqlserver] Timing for sqlserver agent job completions

cisco_sdwan/metadata.csv
Add metadata for BGP and cloud application metrics
NDMII-3013
=> [Cisco SD-WAN] Add metadata for BGP and cloud application metrics

ddev/changelog.d/18346.added, ddev/pyproject.toml
=> Bump dcd in ddev

ddev/CHANGELOG.md, ddev/changelog.d/18213.added, ddev/changelog.d/18221.added, ddev/changelog.d/18271.fixed, ddev/changelog.d/18346.added
=> [Release] Bumped ddev version to 10.1.0

.github/workflows/build-ddev.yml
=> remove broken step

mongo/CHANGELOG.md, mongo/changelog.d/18342.fixed, mongo/datadog_checks/mongo/__about__.py, requirements-agent-release.txt
=> [Port to master][mongo] collection stats metrics should be optional

aws_neuron/assets/monitors/execution_errors.json, aws_neuron/assets/monitors/execution_latency.json, aws_neuron/assets/monitors/neuron_runtime_vcpu.json, aws_neuron/manifest.json
=> AWS Neuron - Monitors

fluentd/hatch.toml
=> Pin fluentd image version

hatch.toml
=> Bump mkdocstrings-python to fix documentation build

openai/README.md
This updates the public doc for the OpenAI PHP integration.
The implementation of the OpenAI Integration was just merged in the PHP Tracing Library: https://github.com/DataDog/dd-trace-php/pull/2685
Preview docs: https://docs-staging.datadoghq.com/esther/preview-openai-php/integrations/openai/?tab=php
=> docs(openai): PHP OpenAI Integration

vllm/manifest.json
=> make vLLM docs public

kyverno/README.md, kyverno/manifest.json
Display docs on public website
=> display docs

ibm_db2/README.md, ibm_db2/hatch.toml, ibm_db2/tests/docker/requirements.txt
=> Bump the `ibm_db` version for py3.12

network_path/assets/dashboards/network_path_agents.json, network_path/manifest.json
Add Network Path Agents dashboard
Network Path Agents dashboard helps customer/us have visibility on how agents are running for Network Path.
=> Add Network Path Agents OOTB dashboard

teleport/manifest.json
Adds a process signature for the teleport integration.
https://datadoghq.atlassian.net/browse/PLINT-475
=> Add process signature for teleport

.builders/images/linux-aarch64/Dockerfile, .builders/images/linux-x86_64/Dockerfile, .builders/images/macos-x86_64/builder_setup.sh
Match https://github.com/DataDog/omnibus-software/pull/540.
=> Update curl to 8.9.1

istio/README.md
Updates the code snippets for the OpenMetrics latest and legacy mode configuration sections in the Istio integration doc page.
User feedback from Hotjar
=> DOCS-8740 Istio Integration Edits

aws_neuron/assets/monitors/execution_errors.json, aws_neuron/assets/monitors/execution_latency.json, aws_neuron/assets/monitors/neuron_runtime_vcpu.json
Add messages to the Neuron monitors.
=> [AWS Neuron]Add monitor messages

network_path/assets/dashboards/network_path_agents.json
Add origin tag to Network Path Agents OOTB
=> Add origin tag to Network Path Agents OOTB

mongo/CHANGELOG.md, mongo/changelog.d/18408.fixed, mongo/changelog.d/18416.added, mongo/datadog_checks/mongo/__about__.py, requirements-agent-release.txt
=> [Port to master][mongo] Mongo additions

aerospike/hatch.toml, azure_iot_edge/hatch.toml, citrix_hypervisor/hatch.toml, cloud_foundry_api/hatch.toml, datadog_checks_base/hatch.toml, dns_check/hatch.toml, glusterfs/hatch.toml, ibm_mq/hatch.toml, marklogic/hatch.toml, postgres/hatch.toml, rethinkdb/hatch.toml, singlestore/hatch.toml, snowflake/hatch.toml, voltdb/hatch.toml, vsphere/hatch.toml, wmi_check/hatch.toml
We are no longer testing or supporting Python 2
=> Remove mypy arguments for Python 2

oracle/README.md
This PR adds deprecation notice to the oracle integration.
=> [oracle] add oracle integration deprecation notice to readme

ibm_was/CHANGELOG.md, ibm_was/changelog.d/18244.fixed, ibm_was/datadog_checks/ibm_was/__about__.py, requirements-agent-release.txt, sqlserver/CHANGELOG.md, sqlserver/changelog.d/18244.fixed, sqlserver/datadog_checks/sqlserver/__about__.py
=> [Port to master] Bumps to `sqlserver` and `ibm_was`

mysql/hatch.toml, mysql/tests/test_metadata.py, mysql/tests/test_unit.py, mysql/tests/utils.py, sqlserver/hatch.toml, sqlserver/tests/test_metadata.py, sqlserver/tests/test_unit.py, sqlserver/tests/utils.py
Remove test dependency `deepdiff`
=> remove test dep deepdiff

cisco_aci/README.md, pan_firewall/README.md, snmp_arista/README.md, snmp_aruba/README.md, snmp_chatsworth_products/README.md, snmp_cisco/README.md, snmp_dell/README.md, snmp_f5/README.md, snmp_fortinet/README.md, snmp_hewlett_packard_enterprise/README.md, snmp_juniper/README.md
As part of overhauling the [NDM page](https://github.com/DataDog/documentation/pull/24770), we have moved the Supported Devices to it's own page, so updating the links on the Integrations
=> [DOCS-8686] updating links to vendor profiles

mysql/assets/configuration/spec.yaml, mysql/datadog_checks/mysql/data/conf.yaml.example
Documents conditional default values for `options.replication` and `options.extra_status_metrics`
- https://github.com/DataDog/integrations-core/pull/10541
- ZD 1753288
=> [mysql] Update documented defaults

glusterfs/tests/conftest.py
Add an inline comment explaining a minor detail.
=> Add inline comment

.ddev/config.toml
=> Fix `pysmi` pin comment

cisco_aci/CHANGELOG.md, cisco_aci/changelog.d/18414.fixed, cisco_aci/datadog_checks/cisco_aci/__about__.py, requirements-agent-release.txt
port https://github.com/DataDog/integrations-core/pull/18480 to master
=> Port cisco_aci release to master

mapr/hatch.toml
=> Update `confluent-kafka` dependency in MapR

LICENSE-3rdparty.csv, agent_requirements.in, riakcs/changelog.d/18495.added, riakcs/datadog_checks/riakcs/riakcs.py, riakcs/pyproject.toml, riakcs/tests/conftest.py, riakcs/tests/test_unit.py
Boto3 supports Python 3.12 which we need to upgrade to.
This is technically a no-changelog change because we don't change any user-visible behavior.
=> Switch to boto3

ddev/CHANGELOG.md, ddev/changelog.d/18413.added
=> [Release] Bumped ddev version to 10.2.0

mimecast/manifest.json
=> [INTPLAT-109] Mimecast - enable public docs

hazelcast/changelog.d/18520.added
=> Fix hazelcast dep name in changelog entry

envoy/hatch.toml, envoy/tests/docker/api_v3/Dockerfile-service, envoy/tests/fixtures/legacy/server_info_api_v3, envoy/tests/test_unit.py
bump test to v1.31.0
this will help cover more newly added metrics
=> envoy: bump test to v1.31.0

kubernetes/assets/dashboards/kubernetes_clusters.json
Fix a couple of broken links in the OOTB "Kubernetes Cluster Overview Dashboard"
=> Fix broken links in kubernetes cluster overview dashboard

tibco_ems/README.md
This PR adds the readme for Tibco EMS
=> Add Tibco EMS readme

tibco_ems/manifest.json
=> Make Tibco EMS tile public for release

tibco_ems/manifest.json
=> Remove windows classifier tag from Tibco

.ddev/config.toml, .github/workflows/test-all.yml, tokumx/README.md
Stop testing the integration in CI, add a note in the README that it's not actively developed.
We are dropping Python 2 from our CI, so we must stop testing this integration. While we're at it we may as well be explicit in the README.
=> Officially sunset tokumx integration.

contentful/README.md
=> Add Contentful copy updates

checkpoint_quantum_firewall/manifest.json, cisco_secure_firewall/manifest.json, palo_alto_panorama/manifest.json
=> Make docs available to public

.github/workflows/build-deps.yml
=> Stop resolving and building external dependencies for Python 2

network_path/assets/dashboards/network_path_agents.json
Update Network Path Agents OOTB with more agent level metrics
=> Update Network Path Agents OOTB with more agent level metrics

postgres/tests/test_logical_replication.py
=> Mark postgres test as flake

eks_fargate/README.md
Add instruction to set service account when using Sidecar Injection by Admission Controller
=> Add service account instruction

kubeflow/manifest.json
Add Kubeflow process signature
=> Add Kubeflow process signature

kubeflow/hatch.toml
=> Update Kubeflow python environment to 3.12.6

apache/datadog_checks/apache/apache.py, gitlab/datadog_checks/gitlab/common.py, scylla/datadog_checks/scylla/scylla.py, spark/datadog_checks/spark/spark.py, spark/tests/test_spark.py, supervisord/datadog_checks/supervisord/supervisord.py, supervisord/tests/conftest.py, supervisord/tests/test_supervisord_unit.py, teamcity/datadog_checks/teamcity/common.py, tls/datadog_checks/tls/tls_remote.py, tls/datadog_checks/tls/utils.py, tls/tests/utils.py, varnish/datadog_checks/varnish/varnish.py
=> Remove some more basic Python 2 compatibility code

oracle/changelog.d/18207.added
=> Remove py3.12 bump from Oracle changelog

aws_neuron/assets/dashboards/aws_neuron_overview.json, aws_neuron/manifest.json
Adds [this dashboard](https://dd.datad0g.com/dashboard/mpp-yps-ggq/aws-neuron-dashboard?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1724753410519&to_ts=1724757010519&live=true) to the AWS Neuron integration
=> [AWS Neuron] Add dashboard

kubeflow/README.md
=> Kubeflow fix readme link

karpenter/changelog.d/18448.added
=> add forgotten changelog

fly_io/README.md, fly_io/manifest.json
=> Make fly.io public 

sqlserver/hatch.toml, sqlserver/tests/compose-ha/sql/db-init.sh, sqlserver/tests/compose-high-cardinality/setup.sh, sqlserver/tests/compose/setup.sh
This PR updates sqlserver integration test images. mssql-2019 & mssql-2022 now uses msodbcsql18 by default.
=> [sqlserver] update sqlserver test images

istio/README.md
Istio docs needed some touch up
=> istio docs

kubevirt_handler/hatch.toml
=> Fix KubeVirt E2E environment

palo_alto_cortex_xdr/manifest.json
=> [INTPLAT-158] Display Palo Alto Cortex XDR docs

vsphere/CHANGELOG.md
=> Port vSphere release to `master`

requirements-agent-release.txt
=> Fix requirements-agent-release.txt

cisco_aci/changelog.d/18748.added, cisco_aci/datadog_checks/cisco_aci/cisco.py, cisco_aci/hatch.toml, cisco_aci/tests/test_cisco.py, cisco_aci/tests/test_fabric.py, cisco_aci/tests/test_tenant.py
https://datadoghq.atlassian.net/browse/NDMII-2903
Part of above ticket to be able clearly understand integration performance and improve on it
Additional metrics may be useful to add, this is a first pass to quickly start iterating on without deeper refactoring effort given capacity in Q4
=> [NDM] [Cisco ACI] Add check metrics

terraform/README.md
Add a partial around a `region-param` shortcode to allow it to render properly in-app
DOCS-9122
=> (DOCS-9122) Add partial

mongo/assets/configuration/spec.yaml, mongo/datadog_checks/mongo/data/conf.yaml.example
=> [mongo] unhide slow_operations config

kubeflow/manifest.json
=> Make Kubeflow public

appgate_sdp/CHANGELOG.md, appgate_sdp/changelog.d/18465.added, appgate_sdp/datadog_checks/appgate_sdp/__about__.py, kubeflow/CHANGELOG.md, kubeflow/changelog.d/18617.fixed, kubeflow/datadog_checks/kubeflow/__about__.py, kubevirt_api/CHANGELOG.md, kubevirt_api/changelog.d/18179.added, kubevirt_api/changelog.d/18617.fixed, kubevirt_api/datadog_checks/kubevirt_api/__about__.py, kubevirt_controller/CHANGELOG.md, kubevirt_controller/changelog.d/18186.added, kubevirt_controller/changelog.d/18617.fixed, kubevirt_controller/datadog_checks/kubevirt_controller/__about__.py, kubevirt_handler/CHANGELOG.md, kubevirt_handler/changelog.d/18283.added, kubevirt_handler/datadog_checks/kubevirt_handler/__about__.py, requirements-agent-release.txt
port https://github.com/DataDog/integrations-core/pull/18767 to master
=> Release new integrations for agent 7.59

cisco_secure_endpoint/README.md
PR for changes in readme file
- Updated API Domain Name and Get Endpoint Details parameter description in readme file.
=> DDS: Cisco Secure Endpoint - V1.0.0 - Updated Readme file.

network/CHANGELOG.md, network/datadog_checks/network/__about__.py, requirements-agent-release.txt
=> Port network release to master

vsphere/changelog.d/18774.fixed, vsphere/datadog_checks/vsphere/vsphere.py
Adds a debug line for external tags
currently we don't have visibility into these and if/when they are sent
=> Add debug log line for external tags

godaddy/assets/dashboards/godaddy_overview.json, godaddy/assets/monitors/godaddy_certificate_denied.json, godaddy/assets/monitors/godaddy_certificate_expired.json, godaddy/assets/monitors/godaddy_certificate_in_an_error_state.json, godaddy/assets/monitors/godaddy_certificate_revoked.json, godaddy/assets/monitors/godaddy_days_remaining_for_expiration_of_certificate.json, godaddy/assets/monitors/godaddy_domain_fraud_detected.json, godaddy/assets/monitors/godaddy_domain_verification_failed.json
This PR makes a minor change to the GoDaddy monitors and updates the alias name in the dashboard
=> DDSaaS: GoDaddy: Monitor changes

requirements-agent-release.txt, sqlserver/CHANGELOG.md, sqlserver/changelog.d/18781.changed, sqlserver/datadog_checks/sqlserver/__about__.py
=> [Release] Bumped sqlserver version to 20.0.0

glusterfs/CHANGELOG.md, glusterfs/changelog.d/18808.fixed, glusterfs/datadog_checks/glusterfs/__about__.py, requirements-agent-release.txt
=> [Release] Bumped glusterfs version to 3.0.1

postgres/CHANGELOG.md, postgres/changelog.d/18788.fixed, postgres/datadog_checks/postgres/__about__.py, requirements-agent-release.txt
=> [Release] Bumped postgres version to 22.0.1

.github/workflows/pr.yml
=> Fix workflow condition syntax

oracle/README.md
=> [oracle] update oracle config example

mongo/CHANGELOG.md, mongo/changelog.d/18843.added, mongo/datadog_checks/mongo/__about__.py, requirements-agent-release.txt
=> [Release] Bumped mongo version to 8.1.0

vsphere/README.md, vsphere/assets/configuration/spec.yaml, vsphere/datadog_checks/vsphere/data/conf.yaml.example
=> update docs for include_events option

.github/PULL_REQUEST_TEMPLATE.md
Remove unused parts of the PR template.
- Additonal Notes is almost never used.
- We have a validation that makes sure we add changelog entries.
Should help make previews of PRs in slack easier to skim.
In general, we should strive for minimal boilerplate.
=> Slim down PR template

lastpass/manifest.json
=> [lastpass] Flip display on public website to true

postgres/CHANGELOG.md, postgres/changelog.d/18866.fixed, postgres/datadog_checks/postgres/__about__.py, requirements-agent-release.txt, tibco_ems/CHANGELOG.md, tibco_ems/changelog.d/18840.added, tibco_ems/datadog_checks/tibco_ems/__about__.py
=> [Release] Bumped postgres version to 22.0.2 and tibco_ems version to 2.1.0

ibm_db2/README.md
Updates the dependencies section for Windows to account for users using older versions of the Datadog Agent
https://dd.enterprise.slack.com/archives/CB9QX75H6/p1729276751907259
=> Update README.md for ibm_db2

cisco_aci/README.md
https://docs.datadoghq.com/integrations/cisco_aci/?tab=host
Assuming this is synced with this page ^^
With the addition of NDM device and interface metadata being supported, updating the documentation a bit to make this clearer to customers
=> [NDM] [Cisco ACI] Update documentation

postgres/CHANGELOG.md, postgres/changelog.d/18870.fixed, postgres/datadog_checks/postgres/__about__.py, requirements-agent-release.txt
=> [Release] Bumped postgres version to 22.0.3

vsphere/assets/configuration/spec.yaml, vsphere/datadog_checks/vsphere/data/conf.yaml.example
=> Fixing vstorage typo

ddev/CHANGELOG.md, ddev/changelog.d/18918.added, ddev/pyproject.toml
=> Release ddev

win32_event_log/README.md, win32_event_log/manifest.json
Adds a link to the new blog post "Monitor your Windows event logs with Datadog Cloud SIEM" to the Windows Event Logs documentation.
The documentation team adds these links to drive traffic to the blog.
=> Add blog link

.github/CODEOWNERS
Change codeowner order for mongo integration.
=> [mongo] dbm now onws mongo integration

databricks/assets/dashboards/databricks_cost_overview.json, databricks/manifest.json
=> [databricks] Add cost dashboard

aerospike/README.md, eks_fargate/README.md, istio/README.md
Replaces <CONTAINER_IDENTIFIER> with <CONTAINER_NAME> in docs for greater clarity
Request from support
=> DOCS-9358 - update <CONTAINER_IDENTIFIER> placeholder in readmes

trend_micro_email_security/README.md
This PR makes a minor change to the Trend Micro Email Security README file
=> DDS: Trend Micro Email Security - README changes

.github/workflows/test-target.yml
=> Document why we keep Python 2 options in CI.

vllm/assets/service_checks.json, vllm/tests/common.py
=> Remove unused configuration option in mocked instance

argocd/assets/dashboards/argo_cd_overview.json
=> fix metric name

fluxcd/assets/dashboards/fluxcd.json
Add template variable for kube_cluster_name
=> add kube_cluster_name template variable

trend_micro_email_security/manifest.json
=> [INTPLAT-137] Make Trendmicro email security Docs Public

jboss_wildfly/manifest.json
=> Add jboss wildfly process signature

requirements-agent-release.txt, slurm/CHANGELOG.md, slurm/changelog.d/18893.added, slurm/datadog_checks/slurm/__about__.py
=> [Release] Bumped slurm version to 1.0.0

sophos_central_cloud/manifest.json
=> Update title for sophos central cloud

aws_neuron/README.md, aws_neuron/manifest.json
=> Update Neuron docs

airflow/README.md
=> Add mappings for 3 new airflow metrics

.github/workflows/test-target.yml
=> Use descriptive flag in CI

eks_fargate/README.md
Updates Helm install instructions to not use `helm --set` but create a values.yaml instead 
Request from Daan Coenen
=> DOCS-9130 - updating helm snippet for EKS Fargate readme

cisco_secure_email_threat_defense/manifest.json
=> INTPLAT-216 - Display Cisco Secure Email Threat Defense Docs Publically

ibm_db2/README.md, ibm_db2/tests/common.py, ibm_db2/tests/docker/requirements.txt
- Install instructions for unix should mention the latest version that we support
- We can simplify the test setup now that we no longer test python 2
=> Update docs and tests for ibm DB2

helm/README.md
Changes a tab name so that the tab actually works
Reported by Daan Coenen
=> DOCS-8894 - fix tabs in helm integration readme

ibm_db2/README.md, ibm_db2/changelog.d/18908.fixed, ibm_db2/datadog_checks/ibm_db2/ibm_db2.py
fix `unable to import module` on Windows
- AGENT-12576
=> Fixes 'unable to import module' on Windows

aws_neuron/assets/dashboards/aws_neuron_overview.json
=> Fix Neuron logs widget

sqlserver/tests/test_connection.py
=> mark test flaky

.ddev/config.toml
=> Override confluent-kafka license

.ddev/config.toml
=> Add reminder to `confluent-kafka` license override

kafka_consumer/CHANGELOG.md, kafka_consumer/changelog.d/19099.security, kafka_consumer/datadog_checks/kafka_consumer/__about__.py, requirements-agent-release.txt, slurm/CHANGELOG.md, slurm/changelog.d/19117.fixed, slurm/datadog_checks/slurm/__about__.py, sqlserver/CHANGELOG.md, sqlserver/changelog.d/19110.fixed, sqlserver/datadog_checks/sqlserver/__about__.py
=> Port changes from 7.60 RC6 to master

trend_micro_vision_one_endpoint_security/README.md
This PR makes a minor change to the Trend Micro Vision One Endpoint Security README file
=> DDS: Trend Micro Vision One Endpoint Security - README changes

windows_service/README.md
Add a step to install the Windows Service integration.
DOCS-9347
=> Include integration installation step

envoy/tests/conftest.py, sap_hana/tests/conftest.py
=> Retry Docker setup more times and wait longer

vsphere/assets/dashboards/vsphere_overview.json
Updating the vSphere dashboard with vSAN.
=> [PLINT-468] Updating the vSphere dashboard with vSAN

nvidia_nim/assets/dashboards/nvidia_nim_overview.json
=> NIM Dashboard additions

nvidia_nim/CHANGELOG.md, nvidia_nim/changelog.d/18964.added, nvidia_nim/changelog.d/19156.fixed, nvidia_nim/datadog_checks/nvidia_nim/__about__.py, requirements-agent-release.txt, sonicwall_firewall/CHANGELOG.md, sonicwall_firewall/changelog.d/18667.added, sonicwall_firewall/datadog_checks/sonicwall_firewall/__about__.py, symantec_endpoint_protection/CHANGELOG.md, symantec_endpoint_protection/changelog.d/18714.added, symantec_endpoint_protection/datadog_checks/symantec_endpoint_protection/__about__.py, wazuh/CHANGELOG.md, wazuh/changelog.d/18646.added, wazuh/datadog_checks/wazuh/__about__.py
Port https://github.com/DataDog/integrations-core/pull/19157 to master
=> Port 7.61 new integrations to master

kubeflow/README.md, kubeflow/assets/dashboards/overview.json
=> Kubeflow : add preview message to Dashboard and public docs

sqlserver/tests/test_activity.py
=> Mark test as flaky

mongo/tests/test_integration.py
Explain what the parameters mean.
Found this while cleaning up stuff. Small and easy enough change to just submit it.
=> Clearer test parameters

cisco_sdwan/README.md
=> [DOCS-9488] SD WAN GA updates

vllm/README.md, vllm/manifest.json
Add blog link for vLLM integration
=> Add blog link for VLLM integration

datadog_checks_base/CHANGELOG.md, datadog_checks_base/changelog.d/19190.added, datadog_checks_base/datadog_checks/base/__about__.py, requirements-agent-release.txt
=> [Release] Bumped datadog_checks_base version to 37.2.0

.github/workflows/build-ddev.yml, .github/workflows/build-deps.yml, ddev/changelog.d/19163.changed, ddev/src/ddev/utils/scripts/ci_matrix.py, docs/developer/meta/ci/testing.md
=> Upgrade GitHub Actions mac runner. (#19163)

requirements-agent-release.txt, slurm/CHANGELOG.md, slurm/changelog.d/19182.fixed, slurm/datadog_checks/slurm/__about__.py
=> Port release Slurm 1.0.3 (#19213) to master

ddev/CHANGELOG.md, ddev/changelog.d/19051.added, ddev/changelog.d/19126.added, ddev/changelog.d/19163.changed, ddev/changelog.d/19208.removed
=> [Release] Bumped ddev version to 11.0.0

docs/developer/guidelines/dashboards.md
Read the docs for dashboards, noticed this.
=> Fix indentation in tip block: contents should be text, not listing

snmp/assets/service_checks.json
Clarify that metrics are pulled from the SNMP Agent
=> [DOCS-9636] adding clarification

ibm_mq/README.md
Adds a few example lines for granting the correct permissions to the Datadog user, requested by a customer.
DOCS-9561
=> Add permissions setup example

kubevirt_api/README.md, kubevirt_api/manifest.json, kubevirt_controller/README.md, kubevirt_controller/manifest.json, kubevirt_handler/README.md, kubevirt_handler/manifest.json
Makes the kubevirt integrations documentation public, and adds a banner to mention that they are in beta.
=> Make kubevirt integrations public

octopus_deploy/assets/configuration/spec.yaml, octopus_deploy/datadog_checks/octopus_deploy/data/conf.yaml.example
Updates the docs for autodiscovery components in the octopus integration
Give users examples and better instructions on how to use these options
=> [PLINT-595] Update autodiscovery config docs

airflow/README.md, iam_access_analyzer/README.md, kubernetes_state_core/README.md
=> fix relative docs links

elastic/changelog.d/19249.fixed, elastic/datadog_checks/elastic/elastic.py, elastic/tests/test_unit.py
Fix regression that I introduced [while removing the `six` dependency](https://github.com/DataDog/integrations-core/pull/18616/files#diff-c6a16fd0b579ee0555b3cf608278193ad35ebad8c6200757b1077e04ca95ab54L265-R264).
=> Regression: handle missing index fields in payload

elastic/CHANGELOG.md, elastic/changelog.d/19249.fixed, elastic/datadog_checks/elastic/__about__.py, requirements-agent-release.txt
Port  https://github.com/DataDog/integrations-core/pull/19255 to master.
=> Port release elastic 8.0.1 to master

wincrashdetect/manifest.json
Update manifest to include links to resources and Windows category tag.
=> Update manifest.json for crash detection integration

teamcity/README.md
update openmetrics example 
https://datadoghq.atlassian.net/browse/AGENT-12910
=> update teamcity docs for openmetrics

nvidia_nim/assets/configuration/spec.yaml, nvidia_nim/datadog_checks/nvidia_nim/data/conf.yaml.example
=> Add logs section to configuration spec

godaddy/README.md
This PR makes a minor change to the GoDaddy README file.
=> [SAASINT-3465] DDSaaS: GoDaddy: README changes

container/metadata.csv
Add `container.restarts` to the documentation.
https://github.com/DataDog/datadog-agent/pull/30173#pullrequestreview-2439317222
=> Add `container.restarts` to doc

nvidia_nim/manifest.json
=> Fix Nvidia NIM tile

cisco_sdwan/README.md
Changing from Beta to Preview, this was previously missed.
=> Update Cisco SD-WAN

aws_neuron/assets/logs/aws_neuron.yaml, aws_neuron/assets/logs/aws_neuron_tests.yaml
=> [LOI-341] Add Neuron error logs parser

datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/metrics.py
=> Make `go_memstats_alloc_bytes` type `native_dynamic`

snmp/README.md, snmp_american_power_conversion/README.md, snmp_arista/README.md, snmp_aruba/README.md, snmp_chatsworth_products/README.md, snmp_check_point/README.md, snmp_cisco/README.md, snmp_dell/README.md, snmp_fortinet/README.md, snmp_hewlett_packard_enterprise/README.md, snmp_netapp/README.md
Fixing some broken links caused by restructuring the NDM setup pages
=> fixing broken links

milvus/manifest.json
=> [AI-4449] Add Milvus process signature

nvidia_nim/README.md, nvidia_nim/assets/dashboards/nvidia_nim_overview.json
This PR adds in the preview notifications in the tile and public facing documentation as well
=> Add NIM dashboard and docs preview message

mysql/README.md
Tiny readme fix, that I made in https://github.com/DataDog/integrations-core/pull/19383
Remove quotes to avoid confusing customers.
=> remove quotes from sql query in readme

databricks/assets/dashboards/databricks_cost_overview.json
=> [databricks] Update cost dashboard to use daily rollups

openai/assets/dashboards/cost_overview_dashboard.json
Widgets use the daily rollup instead of 1D rollup
=> [openai] Update dashboard to use daily rollups

datadog_checks_base/CHANGELOG.md, datadog_checks_base/changelog.d/19312.added, datadog_checks_base/datadog_checks/base/__about__.py, requirements-agent-release.txt
Port a release that was done in 7.62.x
=> port dcb rel to master

octopus_deploy/changelog.d/19432.fixed, octopus_deploy/datadog_checks/octopus_deploy/config_models/instance.py, octopus_deploy/datadog_checks/octopus_deploy/data/conf.yaml.example, octopus_deploy/pyproject.toml
incorporates changes from https://github.com/DataDog/integrations-core/pull/19334/s to octopus
octopus was merged right after this PR
=> Sync octopus models and config

ddev/CHANGELOG.md, ddev/changelog.d/17353.added, ddev/changelog.d/17936.added, ddev/changelog.d/19179.security, ddev/changelog.d/19252.added, ddev/changelog.d/19386.fixed
=> [Release] Bumped ddev version to 11.1.0

argo_workflows/tests/test_unit.py
=> Use pytest IDs for clearer test logs

milvus/assets/dashboards/milvus_overview.json, milvus/manifest.json
Adds an overview dashboard for Milvus.
See [here](https://dd.datad0g.com/dashboard/v45-tdz-sud/milvus-overview?fromUser=true&refresh_mode=paused&from_ts=1736858361490&to_ts=1736859523626&live=false)
=> Add Milvus overview dashboard

.github/workflows/test-fips.yml
- correct syntax to trigger for changes to files
- load the base check into the e2e agent
=> Fix workflow to trigger FIPS e2e tests.

quarkus/README.md, quarkus/assets/service_checks.json
- Readme for quarkus is ready.
- Mention quarkus is available with agent 7.63 in the readme and in the service check metadata.
=> Finalize readme for quarkus.

mongo/README.md
This PR adds DBM for MongoDB to readme.
=> [mongo] add DBM for MongoDB to readme

duckdb/CHANGELOG.md, duckdb/changelog.d/1.added, duckdb/datadog_checks/duckdb/__about__.py, octopus_deploy/CHANGELOG.md, octopus_deploy/changelog.d/18488.added, octopus_deploy/changelog.d/19432.fixed, octopus_deploy/datadog_checks/octopus_deploy/__about__.py, requirements-agent-release.txt
=> Port new integration changelogs to master

quarkus/assets/dashboards/overview.json
=> Add Quarkus dashboard

quarkus/README.md
=> Add steps to configure Quarkus

sap_hana/README.md
=> Add docs to configure SAP HANA for us to read logs from it.

supabase/assets/configuration/spec.yaml, supabase/changelog.d/19502.fixed, supabase/datadog_checks/supabase/config_models/instance.py, supabase/datadog_checks/supabase/data/conf.yaml.example
=> Fix configuration parameter name

contentful/manifest.json
=> GA docs Contentful

ecs_fargate/manifest.json
=> Fix further reading link

keda/assets/monitors/scaler_errors.json, keda/manifest.json
=> rec monitor

quarkus/manifest.json
=> Publish Quarkus docs

sap_hana/README.md
=> Document one more permission needed to collect logs

supabase/assets/monitors/ram_usage.json, supabase/manifest.json
=> Supabase recommended monitor

supabase/assets/dashboards/supabase_overview.json, supabase/manifest.json
=> Supabase dashboard

keda/manifest.json
=> public docs

agent_requirements.in, snowflake/changelog.d/19545.added, snowflake/pyproject.toml
This PR bumps version if `snowflake-connector-python`
https://datadoghq.atlassian.net/browse/VULN-9810
=> Bump Snowflake dependency

keda/manifest.json
=> process signatures

supabase/manifest.json
=> Make Supabase docs public

trend_micro_vision_one_xdr/manifest.json
- Update the manifest to reflect the change in product title case
=> DDS: Trend Micro Vision One XDR: Manifest Update

oke/manifest.json, oke/metadata.csv
Adds OKE metric metadata and metrics check in manifest
We want the OKE integration tile to show the data collected
https://datadoghq.atlassian.net/browse/ECI-444
=> ECI-444 [OCI]update manifest and metadata for OKE integration

intercom/manifest.json
=> Turn on intercom docs

ddev/changelog.d/19566.fixed, ddev/src/ddev/cli/validate/licenses.py
We spent some cycles figuring out what to do so I figured I put this into the error message as breadcrumbs for next time.
=> Validation error for unknown licenses says how to fix the validation

intercom/README.md
Remove unused code block in Intercom docs. (This is causing the docs build to break.)
=> Remove unused code block in Intercom docs

streamnative/manifest.json
Turn on public docs for Crest Streamnative Integration
=> Streamnatvie: Turn on public docs

.builders/images/linux-aarch64/Dockerfile, .builders/images/linux-x86_64/Dockerfile, .builders/images/macos-x86_64/builder_setup.sh
=> [Linux] Bump OpenSSL 3.3.3

kafka_consumer/changelog.d/19591.added
Add a changelog entry for the OpenSSL upgrade in kafka_consumer.
=> Add kafka_consumer changelog entry

incident_io/manifest.json
Going GA with incident.io integration
=> SAASINT-3742 Turn on public docs for incident.io

adyen/manifest.json
Going GA with Adyen integration!
=> SAASINT-3698 Turn on Adyen public docs

.github/workflows/test-fips-e2e.yml
Cherry-pick FIPS test fixes from master. Fixes [DataDog/integrations-core/actions/runs/13303680072/job/37149778322?pr=19603](https://github.com/DataDog/integrations-core/actions/runs/13303680072/job/37149778322?pr=19603).
=> Cherry-pick Fix FIPS E2E workflow (#19487) from master.

.builders/images/linux-aarch64/Dockerfile, .builders/images/linux-x86_64/Dockerfile, .builders/images/macos-x86_64/builder_setup.sh, .builders/images/windows-x86_64/Dockerfile, .builders/images/windows-x86_64/build_script.ps1
=> Update confluent-kafka OpenSSL to 3.4.1

sqlserver/changelog.d/19600.added, sqlserver/datadog_checks/sqlserver/const.py, sqlserver/datadog_checks/sqlserver/sqlserver.py, sqlserver/tests/test_integration.py
=> Get SQL Server ServerName

adyen/README.md
Fixes the tables in the Adyen public docs to look like tables
=> Fix tables in Adyen public docs

.ddev/ci/scripts/foundationdb/linux/55_install_client.sh
This reverts commit 5e31e04c77230d2af641854cf526c5fca953f894.
=> Revert "Remove unused CI script for foundationdb (#19636)"

ecs_fargate/README.md
Adds a row to the environment variables table for `DD_TAGS`
Request from @ConorByrneDataDog
=> DOCS-9992: Default tags for Fargate

datadog_checks_base/changelog.d/19671.fixed, datadog_checks_base/datadog_checks/base/checks/base.py, datadog_checks_base/tests/base/checks/test_agent_check.py
We decided to remove the logic implemented in this PR
=> Revert "[NDMII-3310] add support for HA for integrations"

delinea_privilege_manager/CHANGELOG.md, delinea_privilege_manager/changelog.d/19223.added, delinea_privilege_manager/datadog_checks/delinea_privilege_manager/__about__.py, ivanti_connect_secure/CHANGELOG.md, ivanti_connect_secure/changelog.d/19237.added, ivanti_connect_secure/datadog_checks/ivanti_connect_secure/__about__.py, keycloak/CHANGELOG.md, keycloak/changelog.d/19019.added, keycloak/datadog_checks/keycloak/__about__.py, requirements-agent-release.txt
Port c85353cd74d89f4ea477f8f31e69d28c46db47be to master
=> Port new releases to master (original commit: c85353cd74d89f4ea477f8f31e69d28c46db47be)

datadog_checks_base/CHANGELOG.md, datadog_checks_base/changelog.d/19671.fixed, datadog_checks_base/datadog_checks/base/__about__.py, requirements-agent-release.txt
=> Port to master: bump datadog_checks_base to 37.6.1 (#19676)

.builders/images/linux-aarch64/Dockerfile, .builders/images/linux-x86_64/Dockerfile, .builders/images/macos-x86_64/builder_setup.sh, .builders/images/windows-x86_64/Dockerfile, .builders/images/windows-x86_64/build_script.ps1
=> Update `curl` version to 8.12.1

ddev/pyproject.toml, ddev/src/ddev/plugin/external/hatch/environment_collector.py, pyproject.toml
=> Update `pydantic` version used in CI

ddev/CHANGELOG.md, ddev/changelog.d/19566.fixed, ddev/changelog.d/19670.fixed, ddev/changelog.d/19720.added
=> [Release] Bumped ddev version to 11.2.0

ivanti_nzta/assets/dashboards/ivanti_nzta_analytics_logs.json, ivanti_nzta/manifest.json
- This PR contains minor change in manifest title and query for `Created User Details` panel in Analytics Logs.
=> DDS: Ivanti nZTA Minor Update

kong/manifest.json
Add another metrics to check in manifest for kong.
Requested internally.
=> Add another metrics as the metric to check for the Kong tile

datadog_checks_base/changelog.d/19626.security, datadog_checks_base/changelog.d/19735.added, datadog_checks_base/datadog_checks/base/utils/fips.py, datadog_checks_base/tests/base/utils/test_fips.py
- **Add is_enabled() to fips utils**
- **Add link to Agent implementation**
=> Add is_enabled() to FIPS utils

elastic/README.md
Customer asked for more information about writing custom queries. As this information was hidden in the assets/configuration/spec.yaml, I'm surfacing it to the readme/docs.
=> DOCS-9949 - Elasticsearch custom queries

datadog_checks_base/tests/base/checks/test_agent_check.py, marklogic/tests/test_marklogic.py, tls/tests/test_remote.py
=> Escape regex special characters in service check message assertions

temporal_cloud/manifest.json
=> launch public docs for temporal cloud

sqlserver/tests/test_integration.py
=> Update service check assertion

temporal/README.md
links to the new Temporal Cloud docs.
=> Update Temporal docs with Temporal Cloud link

spark/changelog.d/19750.fixed, spark/datadog_checks/spark/spark.py, spark/tests/test_spark.py
Second attempt at https://github.com/DataDog/integrations-core/pull/19561
=> Gracefully handle missing app properties

.github/CODEOWNERS
This PR updates the codeowners for the GPU integration to the ebpf-platform team.
=> Update gpu integration codeowners

ping_one/README.md
Updating the README steps as per the Slack discussion.
Slack discussion Link: https://crestdatasystems.slack.com/archives/C067GU53VEW/p1741314383844379?thread_ts=1741099747.627729&cid=C067GU53VEW
=> DDS: PingOne README Update

trellix_endpoint_security/README.md
As per the updates made by Trellix for Client Credentials generation steps, raised this PR to align with their changes.
=> DDS: Update README Trellix Endpoint Security

metabase/manifest.json
=> [metabase] Frontend docs turn on

.github/workflows/test-fips-e2e.yml
We want to detect if dependency changes in the base package will cause FIPS to break
=> Run fips tests if base pkg deps change

datadog_checks_base/datadog_checks/base/checks/base.py
Without this note new and external folks will write integrations that submit service checks.
=> Add note about soft deprecation for service checks

mailchimp/manifest.json
=> [mailchimp] Switch on public docs

anthropic/manifest.json
Update Anthropic Desc to include LLM Obs
=> Update Anthropic Desc

vsphere/assets/configuration/spec.yaml, vsphere/datadog_checks/vsphere/data/conf.yaml.example
Add note about resource filters
support case
=> Add note about resource filters

.cursor/rules/edit-changelog.mdc, .cursor/rules/format-code.mdc, .cursor/rules/general.mdc, .cursor/rules/testing.mdc
Getting started with cursor rules.
SaaS Integration's [big success with Cursor rules ](https://github.com/DataDog/crawler-sdk/pull/346/files#diff-b0c2d8bc57965c43044923574dbc2f851e7c3b744ad3bf498bbd82f211aaca47) during Innovation Week!
=> Add basic Cursor rules

datadog_checks_base/README.md, datadog_checks_base/changelog.d/19838.added, datadog_checks_base/changelog.d/19842.fixed, datadog_checks_base/changelog.d/19845.added, datadog_checks_base/datadog_checks/base/checks/base.py, datadog_checks_base/datadog_checks/base/utils/http.py
Follow up to various performance-improving PRs:
- https://github.com/DataDog/integrations-core/pull/19845
- https://github.com/DataDog/integrations-core/pull/19781
- https://github.com/DataDog/integrations-core/pull/19842
Only tweaks comments, README and changelog fragments.
I just felt like this upcoming release will contain such extensive changes that we need some more polishing for the docs and justification.
=> Touch up performance docs and changelog entries

bitdefender/README.md
This PR makes a minor change to the Bitdefender README file.
=> DDS: Bitdefender Integration: Readme changes

cilium/README.md
Typo in the reference link leads to a 404.
Broken link
=> Fix typo in reference link

snmp/tests/test_e2e_core_metadata.py
Fix e2e test following the merge of DataDog/datadog-agent#34477
=> [SNMP] Fix e2e test

.deps/resolved/windows-x86_64_3.12.txt
This change builds the Agent with cryptography from external resolved dependency.
=> Use external cryptography when building on Windows

cisco_secure_web_appliance/CHANGELOG.md, cisco_secure_web_appliance/changelog.d/18717.added, cisco_secure_web_appliance/datadog_checks/cisco_secure_web_appliance/__about__.py, infiniband/CHANGELOG.md, infiniband/changelog.d/19748.added, infiniband/datadog_checks/infiniband/__about__.py, requirements-agent-release.txt, silverstripe_cms/CHANGELOG.md, silverstripe_cms/changelog.d/19364.added, silverstripe_cms/datadog_checks/silverstripe_cms/__about__.py, sonatype_nexus/CHANGELOG.md, sonatype_nexus/changelog.d/19365.added, sonatype_nexus/datadog_checks/sonatype_nexus/__about__.py, velero/CHANGELOG.md, velero/changelog.d/19539.added, velero/datadog_checks/velero/__about__.py
=> [Port to master] New integrations changelog

mesos_slave/hatch.toml, mesos_slave/tests/compose/docker-compose.yml
This reverts commit 39f653821c0a01b2cd574ffc0408ad21a646dc7f.
=> Revert "[AI-5059] Handle Mesos Slave for Ubuntu-22.04 (#19878)"

keycloak/manifest.json
=> Publish keycloack

ivanti_connect_secure/manifest.json
=> Publish Ivanti Connect Secure

amazon_msk/README.md, confluent_platform/README.md, kafka/README.md, rabbitmq/README.md
=> [DSM] Add link text to DSM to each core DSM integration so that DSM shows up on the website

velero/assets/monitors/backup_failures.json, velero/assets/monitors/backup_staleness.json, velero/assets/monitors/restore_failures.json, velero/manifest.json
- **Add monitor files**
- **Format monitors**
- **Update manifest.json**
=> [AI-4902] Add Velero recommended monitors

keycloak/manifest.json
=> Publish Delinea Priviledge Manager

mysql/changelog.d/19910.added
After consulting with DBM, adding a changelog for #19910.
=> Add changelog entry for MySQL configuration change from #19910

anthropic/README.md, openai/README.md
=> Add LLM Eval Instructions

openai/README.md
Corrects a link formatting issue that seems to be causing problems with the documentation build process
Broken build
=> Update link format

octopus_deploy/assets/configuration/spec.yaml, octopus_deploy/datadog_checks/octopus_deploy/data/conf.yaml.example
Add example for both server and deploy logs in conf.yaml
Before, we only had an example for deploy logs
=> Add example for server logs in conf.yaml

amazon_eks/README.md, amazon_eks_blueprints/README.md, docker_daemon/README.md, ecs_fargate/README.md, eks_fargate/README.md, iam_access_analyzer/README.md, mongo/README.md, spark/README.md
Update AWS service names. Reference:
https://aws.amazon.com/products/
=> [DOCS-10533] Update AWS service names

celery/assets/service_checks.json
=> Small Celery fix

forcepoint_secure_web_gateway/README.md
This PR makes a minor change to the Forcepoint Secure Web Gateway README file.
=> DDS: Forcepoint Secure Web Gateway Integration: Readme changes

appgate_sdp/assets/dashboards/overview.json, appgate_sdp/assets/monitors/monitor_Active_connection_exceeds_limit.json, appgate_sdp/assets/monitors/monitor_Appliance_Function_Suspension_state.json, appgate_sdp/assets/monitors/monitor_Appliance_Function_Unhealthy.json, appgate_sdp/assets/monitors/monitor_Appliance_status_warning_for_appliance.json, appgate_sdp/assets/monitors/monitor_Certificate_expiration_soon.json, appgate_sdp/assets/monitors/monitor_Controller_Database_Replication.json, appgate_sdp/assets/monitors/monitor_Database_replication_replay_lag_on_controller.json, appgate_sdp/assets/monitors/monitor_Excessive_database_size_on_controller.json, appgate_sdp/assets/monitors/monitor_High_CPU_on_appliance.json, appgate_sdp/assets/monitors/monitor_High_Disk_Utilization_on_appliance.json, appgate_sdp/assets/monitors/monitor_High_IP_pool_utilization_on_appliance.json, appgate_sdp/assets/monitors/monitor_High_disk_utilization_for_controller_database_partition.json, appgate_sdp/assets/monitors/monitor_High_event_queue_on_gateway.json, appgate_sdp/assets/monitors/monitor_High_memory_on_appliance.json, appgate_sdp/assets/monitors/monitor_High_sessiond_heap_utilization_on_appliance.json, appgate_sdp/assets/monitors/monitor_High_token_size_utilization_on_gateway.json, appgate_sdp/assets/monitors/monitor_High_user_license_utilization_on_controller.json, appgate_sdp/assets/monitors/monitor_Hight_Gateway_session_count.json, appgate_sdp/assets/monitors/monitor_SSH_Access_attempted.json, appgate_sdp/manifest.json
=> Appgate SDP integration assets

okta_workflows/manifest.json
=> Turn on public docs for Okta Workflows GA

octopus_deploy/manifest.json
Adds process signature for octopus deploy
=> Add octopus process signature

bitdefender/README.md, snmp_f5/README.md, tibco_ems/README.md, trend_micro_vision_one_endpoint_security/README.md, vsphere/README.md
Apply minor documentation changes flagged by the Vale linter
DOCS-10533
=> [DOCS-10533] Apply Vale updates

esxi/manifest.json
Display ESXi on public website
=> Make esxi integration public

bitdefender/manifest.json
=> [IDP-54] bitdefender public docs

tenable_io/manifest.json
=> SAASINT-3499 Turn on Tenable IO public docs

orca_security/manifest.json
=> [IDP-52] GA Orca Security Public Docs

celery/assets/monitors/celery_exection_idle.json, celery/assets/monitors/celery_workers_down.json, celery/manifest.json
=> Add Celery monitors

.github/CODEOWNERS
Update CODEOWNERS to remove agent-platform
We no longer own this check
=> Update CODEOWNERS to remove agent-platform

orca_security/README.md
Fix a code block that was breaking the build.
=> Fix broken code block

temporal/README.md
Adds a section for containerized setup to Temporal readme.md
=> DOCS-10432: add autodiscovery to temporal doc

ecs_fargate/README.md
Add a note with information and a link to set the `env` and `service` tags for ECS Fargate metrics
DOCS-10341
=> [DOCS-10341] Add unified service tagging note

postgres/CHANGELOG.md, postgres/datadog_checks/postgres/__about__.py, requirements-agent-release.txt
Applying #20055 to master.
Consistent changelog and version
=> Fix postgres changelog and version

.github/CODEOWNERS, .github/workflows/resolve-build-deps.yaml
=> Fix trigger paths in dependency resolution workflow

docusign/README.md
This PR makes a minor change to the Docusign README file.
=> DDSaaS: Docusign: README changes

coredns/manifest.json
Add another metric for the tile to check in order to detect CoreDNS incoming data.
=> Fix CoreDNS Tile No data status

docs/developer/tutorials/snmp/profile-format.md
This tweaks the language in our documentation slightly to make it clearer how tables work.
This was motivated by several support tickets stemming from tabular misconfigurations, such as users putting an OID *with an index* in their table, or users not putting any tags in a table. Example tickets:
* https://datadoghq.atlassian.net/browse/AGENT-13566
* https://datadoghq.atlassian.net/browse/AGENT-13621
=> Tweak language around tables.

celery/CHANGELOG.md, celery/changelog.d/1.added, celery/datadog_checks/celery/__about__.py, requirements-agent-release.txt
Release the Celery integration 1.0.0
=> Release Celery 1.0.0 (#20084)

gpu/README.md
Updates the README for the GPU monitoring integration with instructions for the 7.65 agent version.
Keep instructions up to date.
=> gpu: Update installation instructions

mysql/CHANGELOG.md, mysql/changelog.d/20089.fixed, mysql/changelog.d/20090.added, mysql/datadog_checks/mysql/__about__.py, requirements-agent-release.txt
=> [mysql] Port changes to master

elastic/CHANGELOG.md, elastic/changelog.d/20121.added, elastic/datadog_checks/elastic/__about__.py, requirements-agent-release.txt
=> [elastic] Release (#20125)

mongo/changelog.d/20124.added, mongo/datadog_checks/mongo/mongo.py, mysql/changelog.d/20124.added, mysql/datadog_checks/mysql/mysql.py, postgres/changelog.d/20124.added, postgres/datadog_checks/postgres/postgres.py, sqlserver/changelog.d/20124.added, sqlserver/datadog_checks/sqlserver/sqlserver.py
Support HA agent support for DBM integrations. 
https://datadoghq.atlassian.net/browse/DBMON-5221
=> Enable HA agent support for DBM integrations

shopify/README.md, shopify/manifest.json
=> Update shopify readme footer + flip public docs flag

mongo/CHANGELOG.md, mongo/changelog.d/20135.added, mongo/datadog_checks/mongo/__about__.py, requirements-agent-release.txt, sqlserver/CHANGELOG.md, sqlserver/changelog.d/20097.fixed, sqlserver/datadog_checks/sqlserver/__about__.py
=> Port changelogs master

vsphere/README.md
Add notes to vSphere readme to make it clear you only need to configure the integration once per vCenter
support case
=> Add note to vSphere readme

.github/workflows/submit-traces.yml, .github/workflows/test-fips-e2e.yml, .github/workflows/test-target.yml, arangodb/datadog_checks/arangodb/metrics.py
After validating this works, we can rename the key back to DD_API_KEY
=> Update actions to use new DD API key

.github/workflows/datadog-static-analysis.yml, arangodb/datadog_checks/arangodb/metrics.py
Update actions to use new DD API key for static analysis
=> Update actions to use new DD API key for static analysis 

.github/workflows/backport-pr.yml, .github/workflows/labeler-community.yml, .github/workflows/labeler.yml, .github/workflows/update-agent-changelog.yml, .github/workflows/update-dependencies.yml
=> Update workflows to use new secret for the integrations-bot

.github/workflows/pr.yml, .github/workflows/test-fips-e2e.yml, .github/workflows/test-target.yml, arangodb/datadog_checks/arangodb/metrics.py
Updates and pin codecov version used in actions
=> Update and pin codecov version used in actions

.github/workflows/master.yml, .github/workflows/nightly-base-package.yml, .github/workflows/pr-all.yml, .github/workflows/pr.yml, .github/workflows/test-fips-e2e.yml, .github/workflows/test-target.yml
backports codecov update to release branch
fix CI
=> [Backport] Update and pin codecov version used in actions (#20191)

mapr/hatch.toml, mapr/tests/conftest.py
=> Fix MapR E2E

.github/workflows/datadog-static-analysis.yml, .github/workflows/submit-traces.yml, .github/workflows/test-fips-e2e.yml, .github/workflows/test-target.yml
Revert api keys to original names
=> Revert api keys to original names

mysql/CHANGELOG.md, mysql/changelog.d/20222.fixed, mysql/datadog_checks/mysql/__about__.py, requirements-agent-release.txt
=> Port MySQL changes to master

mapr/hatch.toml, mapr/tests/conftest.py
=> Unpin MapR

mysql/changelog.d/20259.added, postgres/changelog.d/20259.added
=> Add missing changelogs

kafka_consumer/hatch.toml
There's no such envvar in that file anymore
=> Remove inaccurate comment

sqlserver/CHANGELOG.md
=> Fix SQLServer changelog and add Agent version

.github/workflows/flaky-tests.yml, .github/workflows/master.yml, .github/workflows/nightly-base-package.yml, .github/workflows/pr-all.yml, .github/workflows/pr.yml, .github/workflows/test-agent.yml, .github/workflows/test-fips-e2e.yml, .github/workflows/test-target.yml, .github/workflows/weekly-latest.yml
backports https://github.com/DataDog/integrations-core/pull/20239 so we can run github actions on the release branch
=> Backport codecov gh actions fix

delinea_secret_server/CHANGELOG.md, delinea_secret_server/changelog.d/19857.added, delinea_secret_server/datadog_checks/delinea_secret_server/__about__.py, juniper_srx_firewall/CHANGELOG.md, juniper_srx_firewall/changelog.d/19749.added, juniper_srx_firewall/datadog_checks/juniper_srx_firewall/__about__.py, kaspersky/CHANGELOG.md, kaspersky/changelog.d/19926.added, kaspersky/datadog_checks/kaspersky/__about__.py, linux_audit_logs/CHANGELOG.md, linux_audit_logs/changelog.d/19907.added, linux_audit_logs/datadog_checks/linux_audit_logs/__about__.py, microsoft_sysmon/CHANGELOG.md, microsoft_sysmon/changelog.d/19874.added, microsoft_sysmon/datadog_checks/microsoft_sysmon/__about__.py, openvpn/CHANGELOG.md, openvpn/changelog.d/19811.added, openvpn/datadog_checks/openvpn/__about__.py, requirements-agent-release.txt
Port new ints releases for 7.67.x to master: https://github.com/DataDog/integrations-core/pull/20299
=> Port new ints releases for 7.67.x

postgres/CHANGELOG.md, postgres/changelog.d/20316.fixed, postgres/datadog_checks/postgres/__about__.py, requirements-agent-release.txt, sqlserver/CHANGELOG.md, sqlserver/changelog.d/20293.added, sqlserver/changelog.d/20302.fixed, sqlserver/datadog_checks/sqlserver/__about__.py
Port 7.67.0-rc.2 releases to master
=> Port 7.67.0-rc.2 releases

celery/manifest.json
=> Make Celery documentation publicly available

.github/CODEOWNERS, .github/workflows/config/labeler.yml, box/CHANGELOG.md, box/README.md, box/manifest.json
PR includes skeleton of Box integration without any assets like dashboards, image, README content, etc.
This is beta release of crawler integration and is intended for internal testing before going live. As per @nathanmadams's suggestion, we will raise separate PR with assets and all necessary information later.
=> [SAASINT-4022] DDS: Box: Crawler Integration Without Assets

celery/assets/dashboards/celery_overview.json
=> Update Celery logo

.ddev/config.toml
=> Pin FoundationDB

genesys/README.md
Added the changes in the README file as per the configurable Region field.
=> DDSaaS: Genesys: Updated Readme as per the configurable Region field

.github/CODEOWNERS
The agent-delivery team was split, and the relevant pieces in this repo belong to build-related concerns.
=> Change ownerships from agent-delivery to agent-build

sqlserver/assets/configuration/spec.yaml, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
Updated the description for collect_raw_query_statement
Prevent customer confusion
=> updated description for collect_raw_query_statement

falco/manifest.json
=> GA Falco public docs

airflow/README.md
DOCS-10338, clarification requested by a customer.
=> Clarify value of CONTAINER_IDENTIFIER

falco/manifest.json
This adds process signature for the Falco integration
https://github.com/DataDog/dd-go/pull/188477
=> Add Falco process signature

windows_certificate/README.md
Updating Readme for Windows Certificate Store integration to include the minimum agent version required to run it.
=> Update README for Windows Certificate Store integration

.ddev/config.toml
=> Pin vSphere

pyproject.toml
This is a test PR to validate that mergegate now works on the merge queue.
=> Test commit for mergegate validation

ddev/CHANGELOG.md, ddev/changelog.d/20312.added, ddev/changelog.d/20330.added, ddev/changelog.d/20330.changed, ddev/changelog.d/20341.added, ddev/changelog.d/20419.fixed, ddev/changelog.d/20431.added, ddev/changelog.d/20435.fixed, ddev/changelog.d/20451.added, ddev/changelog.d/20451.changed
Release latest changes in `ddev`
Need to release to ensure that everyone has access to the latest version with the new format and linting commands
=> [Release] Bumped ddev version to 12.0.0

postgres/CHANGELOG.md, postgres/changelog.d/20605.fixed, postgres/datadog_checks/postgres/__about__.py, requirements-agent-release.txt
=> Port to master: Bumped postgres version to 22.14.2 (#20635)

kubeflow/CHANGELOG.md, kubeflow/datadog_checks/changelog.d/18391.added
Changelog contains reference to PR where we added integration.
Fewer surprises when skimming repo.
=> Move changelog fragment from incorrect folder to CHANGELOG.md

falco/README.md
=> Remove Metrics section from Falco readme

hubspot_content_hub/README.md, hubspot_content_hub/manifest.json
Making HubSpot integration docs public to be published on our website
Jira ticket: [SAASINT-4296](https://datadoghq.atlassian.net/browse/SAASINT-4296)
[SAASINT-4296]: https://datadoghq.atlassian.net/browse/SAASINT-4296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(SAASINT-4296): Making hubspot docs public

.ddev/config.toml, .github/workflows/test-all.yml, docs/developer/meta/ci/testing.md
Update runners:
https://github.com/actions/runner-images/issues/12045
=> Update Windows action runners

.ddqa/config.toml
Add the Agent Build config for ddqa
They own some stuff in this repo
=> Add the Agent Build config for ddqa

postgres/changelog.d/20676.fixed, postgres/datadog_checks/postgres/statement_samples.py, postgres/datadog_checks/postgres/statements.py
=> Fix log lines

gitlab/assets/app-builder-blueprints/scaffold-new-project-in-gitlab.json
correct the fqn for the blueprint asset
=> Update FQN for gitlab blueprint asset

databricks/README.md
=> Fix databricks tab shortcodes

argocd/assets/service_checks.json
Update a service check's description
DOCS-11395
=> [DOCS-11395] Update service check description

falco/README.md, proxmox/README.md
=> Fix readme validation

datadog_checks_dev/changelog.d/20749.fixed, datadog_checks_dev/datadog_checks/dev/tooling/constants.py
Updates new integration readme template
the links have moved (however the old links still redirect)
=> Update new integration readme template

airflow/hatch.toml
Stop testing unsupported versions of airflow: https://airflow.apache.org/docs/apache-airflow/stable/installation/supported-versions.html
airflow test environments are failing to build due to buster [eol](https://www.debian.org/News/2024/20240615):
```
#8 [server 3/6] RUN apt-get update
#8 0.187 Ign:1 http://deb.debian.org/debian buster InRelease
#8 0.193 Ign:2 http://security.debian.org/debian-security buster/updates InRelease
#8 0.197 Ign:3 http://deb.debian.org/debian buster-updates InRelease
#8 0.199 Err:4 http://security.debian.org/debian-security buster/updates Release
#8 0.199   404  Not Found [IP: 146.75.30.132 80]
#8 0.207 Get:5 https://packages.microsoft.com/debian/10/prod buster InRelease [6538 B]
#8 0.215 Err:6 http://deb.debian.org/debian buster Release
#8 0.215   404  Not …
```
=> Only test supported versions of airflow

proxmox/README.md
Add installation information in proxmox readme
=> [AI-5350] Update proxmox readme

falco/manifest.json
=> Update Falco manifest description

mongo/changelog.d/20783.fixed, mysql/changelog.d/20783.fixed, sqlserver/changelog.d/20781.fixed
This PR fixes missing changelogs for https://github.com/DataDog/integrations-core/pull/20781 and https://github.com/DataDog/integrations-core/pull/20783
=> [DBM] Fix missing changelogs

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/config.py
We always end up with `echo_failure`, so no need for the conditional
=> Remove unnecessary conditional

mongo/README.md
Clarifies use of "mongod" (vs. MongoDB) by putting it into code formatting. I also took the opportunity to capitalize the product name in a couple places and add some missing punctuation.
Reported typo in slack by @lukas-wenzel-hh
=> Fix styling and capitalization in MongoDB integration doc

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/config.py
Improve readability by reordering statements into coherent blocks
=> Small refactoring of config validation

mongo/CHANGELOG.md, mongo/changelog.d/20783.fixed, mongo/datadog_checks/mongo/__about__.py, mysql/CHANGELOG.md, mysql/changelog.d/20783.fixed, mysql/datadog_checks/mysql/__about__.py, requirements-agent-release.txt
=> Port DBM changes to master

bitwarden/assets/dashboards/bitwarden_user_and_organization_insights.json
- Minor update to the Overview panel for User and Organization Insights dashboard.
=> DDS: Bitwarden: Minor fix in integration link in dashboard overview

kafka_consumer/CHANGELOG.md, kafka_consumer/changelog.d/20842.fixed, kafka_consumer/datadog_checks/kafka_consumer/__about__.py, requirements-agent-release.txt
=> Port to master "Bump kafka_consumer to 6.6.1 (#20854)"

lustre/changelog.d/20857.fixed, lustre/datadog_checks/lustre/constants.py
=> [Lustre] Fix OSS param typo

proxmox/manifest.json
Add another metric to check. This is emitted for VM and Node hosts
=> Add another metric to check

lustre/README.md
=> Fix Lustre commands in README.md

falco/README.md
=> Update Falco log collection documentation

.ddev/config.toml, LICENSE-3rdparty.csv, agent_requirements.in, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/licenses.py, silverstripe_cms/datadog_checks/silverstripe_cms/database_client.py, silverstripe_cms/pyproject.toml
Reverts DataDog/integrations-core#20601
=> Revert "Upgrade Silverstripe CMS to `psycopg3` and stop shipping `psycopg2-binary`"

postgres/datadog_checks/postgres/statements.py, postgres/tests/test_statements.py
Reverts DataDog/integrations-core#20850
=> Revert "[Backport 7.69.x] Fix pgerror reference"

.ddev/config.toml, LICENSE-3rdparty.csv, agent_requirements.in, pgbouncer/datadog_checks/pgbouncer/pgbouncer.py, pgbouncer/pyproject.toml, pgbouncer/tests/conftest.py, pgbouncer/tests/test_pgbouncer_integration_e2e.py, pgbouncer/tests/test_pgbouncer_unit.py
Reverts DataDog/integrations-core#20550
=> Revert "Upgrade PGBouncer to psycopg3"

pgbouncer/CHANGELOG.md, pgbouncer/changelog.d/20884.added, pgbouncer/datadog_checks/pgbouncer/__about__.py, postgres/CHANGELOG.md, postgres/datadog_checks/postgres/__about__.py, requirements-agent-release.txt, silverstripe_cms/CHANGELOG.md, silverstripe_cms/datadog_checks/silverstripe_cms/__about__.py
=> Port changelogs to master

eks_fargate/README.md
Describes how to enable Agent kubelet logging for EKS workloads.
Documenting a new feature.
=> Add new EKS Logging documentation

lustre/changelog.d/20727.fixed, lustre/datadog_checks/lustre/check.py, lustre/datadog_checks/lustre/constants.py, lustre/tests/test_unit.py
Improves robustness and error handling through changes in `dict` access, checks for malformed input and extra logging.
=> Lustre implementation follow-up

postgres/datadog_checks/postgres/discovery.py, postgres/datadog_checks/postgres/explain_parameterized_queries.py, postgres/datadog_checks/postgres/metadata.py, postgres/datadog_checks/postgres/postgres.py, postgres/datadog_checks/postgres/statement_samples.py, postgres/datadog_checks/postgres/statements.py, postgres/datadog_checks/postgres/util.py, postgres/datadog_checks/postgres/version_utils.py
* Expands use of try/except
* Stops passing around long-lived cursors
=> Wrap postgres cursor usage in try/except

.builders/images/linux-aarch64/Dockerfile, .builders/images/linux-x86_64/Dockerfile, .builders/images/macos/builder_setup.sh, .builders/images/windows-x86_64/Dockerfile
Update libcurl used to build dependencies to 8.15.0
Match https://github.com/DataDog/datadog-agent/pull/38821
=> Update libcurl used to build dependencies to 8.15.0

proxmox/assets/saved_views/proxmox_api_logs.json, proxmox/manifest.json
Add saved view for proxmox API logs
=> [AI-5347] Add proxmox saved view

falco/assets/dashboards/falco_metrics.json
=> Small Falco Dashboard fix

datadog_checks_dev/changelog.d/20974.fixed, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/codeowners.py
Fix validation for code owners for lint for correct team.
=> fix validation for proper team

iboss/manifest.json
iboss GA
tile FF to be enabled https://sdp.ddbuild.io/#/feature-flags/display-tile-iboss?targeting-rule=v5
=> [SAASINT-4018] iboss GA

watchguard_firebox/README.md
Fixes a broken link in the docs.
=> [Docs only] Correct WatchGuard Firebox conf example link

beyondtrust_password_safe/CHANGELOG.md, beyondtrust_password_safe/changelog.d/20630.added, beyondtrust_password_safe/datadog_checks/beyondtrust_password_safe/__about__.py, requirements-agent-release.txt
[Release][port] Bumped beyondtrust_password_safe version to 1.0.0
=> [Release][port] Bumped beyondtrust_password_safe version to 1.0.0

.github/workflows/test-target.yml
I misunderstood how the script handles variables.
=> Fix Workflow by removing variable

greenhouse/manifest.json
=> Enable greenhouse public docs

requirements-agent-release.txt
=> [Backport 7.69.x] Remove Kaspersky from requirements-agent-release.txt

mac_audit_logs/manifest.json, proxmox/manifest.json
=> Make public display tiles for Mac Audit Logs and Proxmox

ddev/changelog.d/21124.added, ddev/pyproject.toml
=> Bump Datadog Checks Dev requirement in DDEV

active_directory/README.md
=> Test release commit

.gitlab/build_agent.yaml
Run the Agent E2E tests on "Update dependency resolution" PRs in `integrations-core`.
https://datadoghq.atlassian.net/browse/AI-5685
=> Run Agent E2E tests on triggered Agent builds

infiniband/assets/dashboards/infiniband_overview.json
Capitalization fix in the logo link
=> Capitalization fix in the logo link

.github/workflows/backport-pr.yml, .github/workflows/labeler-community.yml, .github/workflows/labeler.yml, .github/workflows/update-agent-changelog.yml, .github/workflows/update-dependencies.yml
=> Fix secret references in workflow files

ibm_db2/README.md, ibm_db2/hatch.toml, ibm_db2/tests/common.py, ibm_was/pyproject.toml
Update deps in preparation for py3.13
=> Update deps in preparation for py3.13

klaviyo/manifest.json
=> Enable Public Docs for Klaviyo GA

cisco_duo/assets/logs/cisco-duo.yaml, cisco_duo/assets/logs/cisco-duo_tests.yaml
Preserve source in 2 fields OCSF piepline
=> Oren.margalit/loi 571 cisco duo preserve source ocsf

sqlserver/assets/configuration/spec.yaml, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
This will just remove the reference to explain plans for the `collect_raw_query_statement` option to avoid setting the wrong expectations for customers.
A support question on Slack [link](https://dd.slack.com/archives/C027TGQFUMR/p1756252659233489).
=> Updating description for collect_raw_query_statement

datadog_checks_base/CHANGELOG.md, datadog_checks_base/datadog_checks/base/__about__.py, requirements-agent-release.txt
Port this release to master https://github.com/DataDog/integrations-core/pull/21247/commits/315e7b8b5ede7ef8e7edd3ccf93b08b6549b867a
=> Port datadog-checks-base `37.18.1` release to master

hugging_face_tgi/manifest.json
=> [Hugging Face TGI] Add process signature

snowflake/manifest.json, squid/manifest.json
Set the `owner` for snowflake and squid to saas-integrations. This is consistent with CODEOWNERS.
=> IDP-592 - set saas-int as the owner of snowflake

databricks/README.md
Updates Databricks integration docs to better reflect the current state of the integration. Includes more information on configuring DJM and CCM (in addition to Model Serving). Removes outdated Spark configuration instructions.
=> Modernize Databricks integration docs

mac_audit_logs/README.md
Update setup instructions for mac_audit_logs to include permissions needed to be given to the agent user
=> Update setup instructions for mac_audit_logs to include necessary permissions

slurm/assets/dashboards/hpc_overview_dashboard.json, slurm/manifest.json
=> Add HPC Overview Dashboard to Slurm integration

.github/CODEOWNERS, .github/workflows/config/labeler.yml, cofense_triage/CHANGELOG.md, cofense_triage/README.md, cofense_triage/manifest.json
PR includes skeleton of Cofense Triage integration without any assets like dashboards, image, README content, etc.
This is beta release of crawler integration and is intended for internal testing before going live. As per @nathanmadams's suggestion, we will raise separate PR with assets and all necessary information later.
=> DDS: Cofense Triage: Crawler Integration Without Assets

.gitlab/build_agent.yaml
=> Target 7.72.x for Agent build pipeline

supply_chain_firewall/manifest.json
Turns on public documentation for the Supply Chain Firewall integration to go GA
=> SAASINT-4513 Turn on public docs for Supply Chain Firewall

versa/manifest.json
=> Make Versa public

mysql/CHANGELOG.md, mysql/changelog.d/21523.fixed, mysql/changelog.d/21532.fixed, mysql/datadog_checks/mysql/__about__.py, postgres/CHANGELOG.md, postgres/changelog.d/21523.fixed, postgres/datadog_checks/postgres/__about__.py, requirements-agent-release.txt, sqlserver/CHANGELOG.md, sqlserver/changelog.d/21523.fixed, sqlserver/datadog_checks/sqlserver/__about__.py
=> Port changelog to master

trend_micro_cloud_one/README.md
- Minor update to the cURL command in the Network Security section of the README.
=> DDS: Trend Micro Cloud One: Minor update in README

anthropic/assets/dataflows.yaml
Adds dataflow definitions for the `anthropic` integration.
=> [IXP-656] Define dataflow for Anthropic

postgres/CHANGELOG.md, postgres/changelog.d/21557.fixed, postgres/changelog.d/21560.fixed, postgres/datadog_checks/postgres/__about__.py, requirements-agent-release.txt
=> Postgres fixes master port

prometheus/assets/configuration/spec.yaml, prometheus/changelog.d/21584.fixed, prometheus/datadog_checks/prometheus/config_models/defaults.py, prometheus/datadog_checks/prometheus/config_models/instance.py, prometheus/datadog_checks/prometheus/data/conf.yaml.example
Fix minor issues in Prometheus spec files:
- 8196492920 Fix indentation issue in prometheus spec file
- 6749fb4e2c regenerate instances
- 11ae8ed23f add changelogs
https://datadoghq.atlassian.net/browse/FA-1028
=> fix(yaml-specs): fix bad indent in prometheus spec
