DataDog/integrations-core

- mongo/changelog.d/17665.fixed
- mongo/datadog_checks/mongo/mongo.py
This PR swaps the order of `_send_database_instance_metadata` and `_collect_metrics` to make sure the database_instance metadata is always sent before metrics are collected. This is to ensure the integration always emit the `database_instance` in case `_collect_metrics` fails with uncaught exceptions.
> [mongo] send database_instance metadata before collecting metrics

- sqlserver/changelog.d/17648.added
- sqlserver/datadog_checks/sqlserver/activity.py
- sqlserver/tests/test_activity.py
Adding the `context_info` field to SQL Server activity samples.
APM tracers will populate this field needed for the full mode APM/DBM link. The details are [here](https://docs.google.com/document/d/1AAo50nJNcb5r7BU9Hqc0i_V-KsmnLw8lgpwV--qamto/edit?usp=sharing).
> Add context_info to SQL Server activity samples (DBMON-4106)

- win32_event_log/README.md
Documentation for new feature to send default Security Events to Datadog as Logs.
New feature to send default Security Events to Datadog as Logs.
> add dd_security_events to docs

- windows_service/assets/configuration/spec.yaml
- windows_service/changelog.d/17657.added
- windows_service/datadog_checks/windows_service/config_models/defaults.py
- windows_service/datadog_checks/windows_service/config_models/instance.py
- windows_service/datadog_checks/windows_service/data/conf.yaml.example
- windows_service/datadog_checks/windows_service/windows_service.py
- windows_service/tests/test_windows_service.py
Add a new tag to each windows_service service check that includes the Windows Service Display Name as the tag `display_name`.
Add a `collect_display_name_as_tag` option to control presence/absence of the tag.
Customer Requests: https://datadoghq.atlassian.net/browse/WINA-795
> Add optional display_name tag

- sqlserver/changelog.d/17675.fixed
- sqlserver/datadog_checks/sqlserver/config.py
- sqlserver/datadog_checks/sqlserver/sqlserver.py
- sqlserver/tests/test_integration.py
This PR swaps the order of _send_database_instance_metadata and _collect_metrics to make sure the database_instance metadata is always sent before metrics are collected. This is to ensure the integration always emit the database_instance in case _collect_metrics fails with uncaught exceptions.
Keep consistency with the rest of the dbms integrations. As fixed recently in #17590 and #17665
> [sqlserver] send database_instance metadata before collecting metrics

- postgres/changelog.d/17679.fixed
- postgres/datadog_checks/postgres/postgres.py
Currently any exception we get while trying to run custom checks on postgres integration will cause all subsequent checks that run to fail unless they are ProgammingError or QueryCancelled. We also lose any debugging information about the failure. We should loosen up this [exception](https://github.com/DataDog/integrations-core/blob/45d17147c1befd4127b5c34d5aaf24d1792e03bf/postgres/datadog_checks/postgres/postgres.py#L901) so that we don’t skip the rest of the checks and we have useful debugging info to help ourselves and customers debug issues
> [DBMON-4112] postgres - loosen up custom query exception handling

- .github/workflows/build-deps.yml
In the Aarch runner the directories were all listed under root. Because of this, the runner user that the runner run as doesn't have the correct permissions to create the file and thus the job always fails with a permission denied error:
```
/home/runner/work/_temp/6822cb3e-4435-4ce9-8eb5-3746fd134886.sh: line 1: output/linux-aarch64/image_digest: Permission denied
```
https://github.com/DataDog/integrations-core/actions/runs/9291550932/job/25620772401
Inspecting the permissions in the runner:
```
Run ls -la output/linux-aarch64/
total 16
drwxr-xr-x 4 root root 4096 May 30 20:23 .
drwxr-xr-x 3 root root 4096 May 30 20:22 ..
drwxr-xr-x 3 root root 4096 May 30 20:23 py2
drwxr-xr-x 3 root root 4096 May 30 20:22 py3
```
It's different when compared to the linux-x86_64 runner:
```
Run ls -la …
```
> Manually change the permissions to allow for the runner to create file

- oom_kill/README.md
Update the `oom_kill` check kernel version requirement to make it match what we really test.
The code of the check test for kernel `4.9`: https://github.com/DataDog/datadog-agent/blob/f181fade8a1342b39062b4876ed0a4806b4dbdf0/pkg/collector/corechecks/ebpf/probe/oomkill/oom_kill.go#L70
And the test is also validating that `oom_kill` works on this kernel: https://github.com/DataDog/datadog-agent/blob/71b3fd461d6e6ed09558621a92ed4ad8c7e5903e/pkg/collector/corechecks/ebpf/probe/oomkill/oom_kill_test.go#L48
> Update the `oom_kill` check kernel version requirement to make it match what we test

- mongo/changelog.d/17697.fixed
- mongo/datadog_checks/mongo/mongo.py
- mongo/tests/test_integration.py
This PR changed emitting `database_instance` metadata for mongo only when `dbm` is enabled.
We've observed conflict mongo database_instance collected from `serverStatus.host` for mongo on k8s. The database_instance conflict causes tag flip when 2 mongodb instances emit the same database_instance.
> [mongo] Only emit database_instance when dbm is enabled

- .builders/images/linux-aarch64/Dockerfile
- .builders/images/linux-x86_64/Dockerfile
Sets `sysconfdir` when building unixODBC to maintain the behavior previous to the split of the dependencies build.
When starting to build the dependencies separately, we missed that for the SQLServer integrations, customers are [instructed](https://github.com/DataDog/integrations-core/blob/658cf3c51081f3a769640a279f93aa6f4b3cf55c/sqlserver/README.md#linux) to copy their driver configuration to `/opt/datadog-agent/embedded/etc`. Therefore, the way the library is currently built, it will break customers that rely on this.
> Set confdir for unixODBC to the expected location inside the Agent installation

- agent_requirements.in
- cacti/changelog.d/17696.fixed
- cacti/pyproject.toml
- mysql/changelog.d/17696.fixed
- mysql/pyproject.toml
- proxysql/changelog.d/17696.fixed
- proxysql/pyproject.toml
- singlestore/changelog.d/17696.fixed
- singlestore/pyproject.toml
This PR upgrades PyMySQL to the newest version to fix a bug in the library
This [changelog](https://github.com/PyMySQL/PyMySQL/blob/main/CHANGELOG.md#v111)
* Fixes DataDog/image-vuln-scans#1489
> Upgrade PyMySQL

- .github/workflows/build-deps.yml
Required to trigger dependency resolutions that target this release branch.
> [Backport 7.54.x] Trigger dependency build-related jobs on release branches too

- teleport/assets/dashboards/teleport_overview.json
Fixes some widget's metric names e.g. `user.login.count` -> `user_login.count`, that was the case for around 5-7 metrics.
> Fix Teleport Dashboard metric names

- sqlserver/changelog.d/17717.fixed
- sqlserver/datadog_checks/sqlserver/statements.py
- sqlserver/tests/test_statements.py
This PR adds filters to sqlserver query metrics to exclude metrics from databases that are not configured to be monitored. When the check is configured to only monitor a single non-master database (with database_autodiscovery disabled), query metrics from unmonitored databases are filtered out. 
Prior to the fix, query metrics from multiple databases are collected on Azure SQL Database, which is supposed to have access contained to a single database.
With the fix, query metrics from unmonitored databases are not included, even when using admin user to monitor (although highly not recommended).
https://datadoghq.atlassian.net/browse/DBMON-4135
This change is to ensure not including query metrics from unmonitored databases. On Azure SQL Database, if the check is configured to use an admin …
> [SQLServer] Filter query metrics by database_name if check is configured to a single non-master db

- .github/workflows/build-deps.yml
This PR adds permissions already available to our `build-deps.yaml`. This had to be added manually as our token used to backport doesn't have permissions to be able to edit/change workflows.
https://github.com/DataDog/integrations-core/pull/17680
> Manually change the permissions to allow for the runner to create file 

- snowflake/manifest.json
Reverts DataDog/integrations-core#17731 -- doc-merging logic not yet implemented
> Revert "(DOCS-8102) Hide Snowflake agent integration doc"

- win32_event_log/assets/configuration/spec.yaml
- win32_event_log/datadog_checks/win32_event_log/check.py
- win32_event_log/datadog_checks/win32_event_log/config_models/defaults.py
- win32_event_log/datadog_checks/win32_event_log/config_models/instance.py
- win32_event_log/datadog_checks/win32_event_log/data/conf.yaml.example
- win32_event_log/datadog_checks/win32_event_log/legacy/win32_event_log.py
- win32_event_log/tests/test_config.py
Add `dd_security_events` to config spec and config example
Add a warning if the option is used in legacy_v2 mode
https://datadoghq.atlassian.net/browse/WINA-840
forgot to add in 7.54 when the feature was added, so this is mostly just a docs change
> Add dd_security_events option to spec

- snmp/changelog.d/17722.fixed
- snmp/datadog_checks/snmp/data/default_profiles/_cisco-voice.yaml
- snmp/tests/test_profiles.py
Use a forced metric type of gauge for ccmRejectedPhones and ccmUnregisteredPhones in the _cisco-voice.yaml default profile.  Without this those two metrics are incorrectly inferred to be rates. 
A customer reported the issue.
To test:
1) ddev env start snmp py3.11-false -e DD_TAGS="ndm_qa:test-17722" -e DD_SITE=datad0g.com -e DD_DD_URL=https://app.datad0g.com -e DD_API_KEY=$DATADOG_STAGING_ORG2_API_KEY
2) ddev env config edit snmp py3.11-false
Change community_string from public to cisco_icm
3) ddev env reload snmp py3.11-false
4) Go to https://dd.datad0g.com/metric/explorer and confirm that ccmRejectedPhones and ccmUnregisteredPhones metrics show up as non-zero.
> Use a forced metric type of gauge for ccmRejectedPhones and ccmUnregisteredPhones.

- sqlserver/changelog.d/17750.fixed
- sqlserver/datadog_checks/sqlserver/sqlserver.py
We received customer reports about missing `sqlserver_version`. The problem is that we store the version in a cache that has a 1 day TTL, and we never refresh the cache. The fix is to refresh the cache during each check run.
You can see the problem here where I changed the TTL to 5 minutes:
> [dbm] fix flapping sqlserver_version

- windows_service/changelog.d/17749.fixed
- windows_service/datadog_checks/windows_service/windows_service.py
Moving some variables to be constants in the `ServiceView` class rather than being reassigned in each check loop.
https://github.com/DataDog/integrations-core/pull/17657#discussion_r1622862493
https://datadoghq.atlassian.net/browse/WINA-795
> Using constant values instead of reassigning variables in each check run

- sqlserver/tests/test_activity.py
To be enabled once test failure is fixed
> Disable SQLServer on Windows test failure impacting master pipeline

- kafka_consumer/changelog.d/17686.added
- kafka_consumer/datadog_checks/kafka_consumer/client.py
- kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
- kafka_consumer/tests/common.py
- kafka_consumer/tests/test_unit.py
Add the consumer group state as tag
https://datadoghq.atlassian.net/browse/AI-3859
> Kafka consumer : add consumer group state as tag 

- sqlserver/changelog.d/17765.added
- sqlserver/datadog_checks/sqlserver/data/driver_config/odbcinst.ini
This PR updates the embedded odbc driver config to use msodbcsql 18.3.3.1.
Tested with new driver
https://datadoghq.atlassian.net/browse/DBMON-4155
depends on https://github.com/DataDog/datadog-agent/pull/26195
> [sqlserver] Bump embedded odbc driver to 18.3.3.1

- mysql/hatch.toml
- mysql/tests/conftest.py
This PR pings mysql version `8.0.36` in the test to fix nightly test failure due to container fail to start.
> ping 8.0.36 version for mysql

- openstack_controller/changelog.d/17791.fixed
- openstack_controller/changelog.d/17791.removed
- openstack_controller/datadog_checks/openstack_controller/api/api_rest.py
- openstack_controller/datadog_checks/openstack_controller/api/api_sdk.py
- openstack_controller/tests/configs.py
- openstack_controller/tests/test_unit_ironic.py
Remove baremetal allocations microversion check
We no longer need microversion checking of baremetal allocations as we handle it the common way like a 400/500 error if it fails.
> Remove baremetal allocations microversion check

- mongo/changelog.d/17785.fixed
- mongo/datadog_checks/mongo/dbm/operation_samples.py
This PR skips emitting mongodb operation samples (DBM only) on unexplainable operations such as getmore.
> [mongo] skip emit samples on unexplainable operations

- datadog_checks_base/changelog.d/17716.added
- datadog_checks_base/datadog_checks/base/utils/db/utils.py
- datadog_checks_base/tests/base/utils/db/test_util.py
- sqlserver/tests/odbc/odbcinst.ini
The DBMAsyncJob class allows synchronous and asynchronous jobs to run at fixed intervals.
This PR updates the approach to throttling in the sync jobs of the DBMAsyncJob class. Rather than pausing a thread after executing the job, we now evaluate whether the job should proceed. For example, if a job is scheduled to run every 10 seconds and only 1 second has passed since its last execution, the run_job_loop call will not trigger the job.
This change enables running synchronous jobs on the main thread without putting the main thread to sleep after each job execution.
> Improve throttling in sync jobs

- .builders/.force-rebuild
Due to some lack of prevision, https://github.com/DataDog/integrations-core/pull/17709 failed to trigger the dependency resolution that would've made the changes to the Dockerfiles (that affect the buiild) go into effect.
When we managed to trigger the resolution afterwards, the previously defined Docker image continued to be pulled because we rely on changes to the builders file to decide whether to rebuild or not: https://github.com/DataDog/integrations-core/blob/ac4c0569e5b6104b3807b2d921130aa00739be5d/.github/workflows/build-deps.yml#L92-L93
This edge case triggered the actual fix to not be built and uploaded, and thus not propagated to the Agent.
This PR forces a rebuild from scratch to make sure we're using the latest for everything.
> Force rebuild of dependencies from scratch 7.54.x

- .builders/.force-rebuild
Due to some lack of prevision, https://github.com/DataDog/integrations-core/pull/17709 failed to trigger the dependency resolution that would've made the changes to the Dockerfiles (that affect the buiild) go into effect.
When we managed to trigger the resolution afterwards, the previously defined Docker image continued to be pulled because we rely on changes to the builders file to decide whether to rebuild or not: https://github.com/DataDog/integrations-core/blob/ac4c0569e5b6104b3807b2d921130aa00739be5d/.github/workflows/build-deps.yml#L92-L93
This edge case triggered the actual fix to not be built and uploaded, and thus not propagated to the Agent.
This PR forces a rebuild from scratch to make sure we're using the latest for everything. …
> Force rebuild of dependencies from scratch 7.55.x

- mesos_slave/hatch.toml
- mesos_slave/tests/common.py
- mesos_slave/tests/fixtures/state.json
Before: 1.0, 1.1, 1.7
After: 1.7
https://datadoghq.atlassian.net/browse/AI-3951
> Drop testing on mesos-slave versions incompatible with gh runner docker v26

- rabbitmq/hatch.toml
py2: remove 3.5, 3.6
py3: rmeove 3.8, 3.9, 3.10
> Drop testing on rabbitmq versions incompatible with gh runner docker v26

- twemproxy/tests/compose/docker-compose.yaml
> Update etcd0 to latest to be compatible with gh runner docker v26

- kubernetes_cluster_autoscaler/assets/dashboards/kubernetes_cluster_autoscaler_overview.json
Fix typos in metrics names in the dashboard.
> Fix metrics names in kubernetes cluster autoscaler dashboard

- .github/workflows/submit-traces.yml
- .github/workflows/test-results-master.yml
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20
- emibcn/badge-action@v2.0.2
- geekyeggo/delete-artifact@v2
> Update Publish and Submit traces github actions

- mongo/changelog.d/17876.added
- mongo/datadog_checks/mongo/config.py
- mongo/tests/results/opeartion-activities-mongos.json
- mongo/tests/results/opeartion-activities-standalone.json
- mongo/tests/results/operation-samples-mongos.json
- mongo/tests/results/operation-samples-standalone.json
- mongo/tests/test_dbm_operation_samples.py
- mongo/tests/test_integration.py
This PR adds tag `clustername` to mongo metrics when `cluster_name` is provided in the configuration. Tag name `clustername` also matches the default tag for metrics pushed by MongoDB Atlas.
> [mongo] Add tag clustername to mongo metrics

- openstack_controller/tests/conftest.py
- openstack_controller/tests/test_unit_glance.py
- openstack_controller/tests/test_unit_heat.py
- openstack_controller/tests/test_unit_ironic.py
- openstack_controller/tests/test_unit_keystone.py
- openstack_controller/tests/test_unit_neutron.py
- openstack_controller/tests/test_unit_nova.py
- openstack_controller/tests/test_unit_octavia.py
- openstack_controller/tests/test_unit_swift.py
Add the possibility of checking the value reported by the `response_time` metrics of each of the components in our unit tests
Until now, only the existence of the metric was checked, and its value could be incorrect and not detected by our unit tests.
> Mock response_time expected value with elapsed_total_seconds argument in mock_http_get

- .gitlab-ci.yml
Avoid triggering Agent build pipelines on:
- tag pipelines
- release branches (this should no longer be needed at this point)
The current logic has flaws that causes unnecessary triggers on release branches; in the case of tags, a massive number of references might be created which spawns the same number of pipelines (#incident-28175).
> Limit the cases in which an agent build pipeline is triggered

- mysql/tests/test_statements.py
- postgres/tests/test_statements.py
- sqlserver/tests/test_statements.py
- sqlserver/tests/test_stored_procedures.py
- sqlserver/tests/utils.py
Fixes tests that relied on main thread being put to sleep by DBMAsync.
Tests started to fail after this PR - https://github.com/DataDog/integrations-core/pull/17716 got submitted.
> Fix tests that expect DBMAsync to put thread to sleep in sync mode

- postgres/tests/test_replication_slot.py
Adds a sleep to make sure the `pg_replication_slots` table is saturated. Not an ideal solution but it will un-flake this test until we can implement better polling across our tests.
There appears to be a small delay before this table is ready.
> None check

- datadog_checks_base/changelog.d/17893.fixed
- datadog_checks_base/datadog_checks/base/utils/db/utils.py
- datadog_checks_base/tests/base/utils/db/test_util.py
This PR fixes a bug in DBMAsync job that is ran in sync mode.
Prior to this change, the DBMAsync job would not take into account the time of the job execution when throttling by the collection interval.
Before:
<--job runs--><--collection interval--><--job runs-->
After
<--collection interval--> <--collection interval-->
<--job runs--> ..............                <--job runs-->
> Fix rate limiter in sync mode of DBMAsync job.

- .github/workflows/permissions-advisor.yml
Adds a workflow that helps to understand the permissions required for a given workflow
https://datadoghq.atlassian.net/browse/SINT-2063
https://github.blog/2023-06-26-new-tool-to-secure-your-github-actions/
> Add github actions workflow permissions advisor

- postgres/changelog.d/17903.fixed
- postgres/datadog_checks/postgres/cursor.py
- postgres/datadog_checks/postgres/explain_parameterized_queries.py
- postgres/datadog_checks/postgres/statement_samples.py
- postgres/datadog_checks/postgres/statements.py
- postgres/tests/test_cursor.py
- postgres/tests/test_statements.py
This PR prepends a new comment `/* DDIGNORE */` to the DBM explain plan collection queries. The comment `/* DDIGNORE */` is used to ignore these queries in query metrics.
With this change, below agent queries are ignored in query metrics
- `SELECT datadog.explain_statement ( ? )` - pre-configured function to explain non-parametrized queries
- `PREPARE dd_{query_signature} AS {statement}` - creates prepared statement to explain queries with extended protocol
- `DEALLOCATE PREPARE dd_{query_signature}` - deallocate the prepared statement used for explain
> [Postgres] Ignore explain plan collection queries in query metrics

- vsphere/assets/service_checks.json
* Updates the service check asset : 
* Use the current namespace `vsphere` instead of the legacy `vcenter` https://github.com/DataDog/integrations-core/blob/b8c883091cbdf86546470f238be58efe2b3ca205/vsphere/datadog_checks/vsphere/vsphere.py#L64-L68
* Clarifies the description on the API usage, not simply a "ping"
* Customer is confused about having no data for `vcenter.can_connect` which is expected as they are using the non-legacy implementation. Our [documentation](https://docs.datadoghq.com/integrations/vsphere/#service-checks) relies on this asset which is currently the legacy one
> update service check to use current implementation instead of legacy

- vsphere/README.md
- vsphere/assets/configuration/spec.yaml
- vsphere/changelog.d/17855.added
- vsphere/datadog_checks/vsphere/api.py
- vsphere/datadog_checks/vsphere/config.py
- vsphere/datadog_checks/vsphere/config_models/instance.py
- vsphere/datadog_checks/vsphere/constants.py
- vsphere/datadog_checks/vsphere/data/conf.yaml.example
- vsphere/datadog_checks/vsphere/event.py
- vsphere/datadog_checks/vsphere/vsphere.py
- vsphere/tests/test_event.py
The vSphere integration currently only reports events from a hardcoded list. We want to allow customers to determine which events they want to receive, as well as which messages from said events they don't want to receive.
> [FRAGENT-807] Adding an include_events config option to vSphere

- process/assets/configuration/spec.yaml
- process/changelog.d/17817.added
- process/datadog_checks/process/config_models/defaults.py
- process/datadog_checks/process/config_models/instance.py
- process/datadog_checks/process/data/conf.yaml.example
- process/datadog_checks/process/process.py
- process/hatch.toml
- process/tests/test_bench.py
- process/tests/test_process.py
This check adds a bool parameter `use_oneshot` that can be set to true so that the check uses `psutil.Process().oneshot()` (https://psutil.readthedocs.io/en/latest/#psutil.Process.oneshot) to cache metrics and have a ~2x speed up of the check run.
This defaults to `true` so that users are using the quicker/more efficient version of the check.
https://datadoghq.atlassian.net/browse/WINA-805
From psutil docs: https://psutil.readthedocs.io/en/latest/#psutil.Process.oneshot
> The advice is to use this every time you retrieve more than one information about the process.
With this in mind we have set `use_oneshot` to be true by default since the check runs the `psutil.Process` methods often. So far this was tested through ddev on a Windows Laptop and a Linux container.
Benchmark results:
> adding `use_oneshot` parameter to speed up check runs with `psutil.Process().oneshot()`

- docs/developer/setup.md
Add the `-L` flag to `curl` in the developper docs to install `ddev`.
Without it `curl` won't follow redirects and so won't be able to download the file.
> Fix developper docs to install ddev

- kubernetes_cluster_autoscaler/manifest.json
Display public docs for the integration and enables the tile
> Kubernetes cluster autoscaler enable public display

- esxi/changelog.d/17919.fixed
- esxi/datadog_checks/esxi/check.py
- esxi/metadata.csv
- esxi/tests/test_integration.py
- esxi/tests/test_unit.py
Maintains a long lived connection to ESXi host rather than reconnecting every check run. If can't connect when gathering version info, attempt to reconnect then raise exception. Also changes `esxi.can_connect` to a gauge 
perform connection once rather than every check run; the agent's connection to the ESXi host is expected to be stable
> [PLINT-356] Maintain a long lived connection

- ddev/changelog.d/17932.added
- ddev/src/ddev/cli/__init__.py
Useful to quickly switch between configurations of matching DD_SITE and credentials.
> Add cli option to override org config value at runtime

- sqlserver/changelog.d/17933.fixed
- sqlserver/datadog_checks/sqlserver/queries.py
- sqlserver/tests/test_metadata.py
Moving sqlserver foreign key information to the dependant table
It is better to represent foreign keys like this.
> Move foreign key information to the dependent table

- vsphere/assets/configuration/spec.yaml
- vsphere/changelog.d/17917.added
- vsphere/datadog_checks/vsphere/constants.py
- vsphere/datadog_checks/vsphere/data/conf.yaml.example
- vsphere/datadog_checks/vsphere/event.py
- vsphere/tests/conftest.py
- vsphere/tests/test_event.py
> [FRAGENT-807] Adding more events/resource to be filtered in vSphere with event_resource_filters

- mongo/assets/configuration/spec.yaml
- mongo/changelog.d/17940.added
- mongo/datadog_checks/mongo/config_models/instance.py
- mongo/datadog_checks/mongo/data/conf.yaml.example
This PR unhides the DBM config options in mongo configuration spec since DBM for MongoDB is now in private beta.
Get Mongo integration config ready for DBM for MongoDB [private beta](https://docs.datadoghq.com/database_monitoring/setup_mongodb/)
> [mongo] Update mongo config yaml to unhide DBM config options

- tcp_check/changelog.d/17912.added
- tcp_check/datadog_checks/tcp_check/tcp_check.py
TCP CHECKS data is reported even when `DNS RESOLVE fails`, causing confusion in monitoring.
If `DNS RESOLVE` failed don't report metrics.
> [tcp_checks] If dns-resolve failed don't report metrics.

- datadog_checks_base/tests/compose/kerberos/kerberos-kdc/Dockerfile
Adds a step updating all `.repo` files in the setup of Kerberos tests in order to fix the unresolved CentOS mirror url.
[This](https://serverfault.com/questions/1161816/mirrorlist-centos-org-no-longer-resolve) stack exchange post explains that since the mirror url "mirrorlist.centos.org" no longer exists, some changes need to be made if we want to keep supporting CentOS 7.
> update mirror endpoint for kerberos tests

- mysql/assets/configuration/spec.yaml
- mysql/datadog_checks/mysql/data/conf.yaml.example
- postgres/assets/configuration/spec.yaml
- postgres/datadog_checks/postgres/data/conf.yaml.example
- sqlserver/assets/configuration/spec.yaml
- sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
The collection of settings is generally available, so we can remove the alpha label.
> [dbm] remove alpha label for settings collection

- kafka_consumer/tests/docker/kerberos/kdc/Dockerfile
Same as https://github.com/DataDog/integrations-core/pull/17964 but for kafka consumer integration.
> Fix centos mirrorlist for kafka consumer tests

- postgres/changelog.d/17974.changed
- postgres/datadog_checks/postgres/explain_parameterized_queries.py
Explain plan collection can fail for any number of legitimate reasons, so avoid polluting the logs by logging them at the debug level.
We heard feedback that these logs were noisy in the cases where explain plan collection was expected to fail.
> Drop explain plan failures to debug level

- sqlserver/datadog_checks/sqlserver/schemas.py
Fixes the early return that wouldve prevented switching back to the original DB during the schema collection
we need to switch back to the original DB when the collection of schemas is stoped on one of them
fix for unreleased feature, hence no changelog
> Switch back to the intial database while collecting schemas

- teleport/assets/logs/teleport.yaml
- teleport/assets/logs/teleport_tests.yaml
Make component name optional in the log prefix helper rule.
Parsing `log.level` fails in some rare cases where the component name is missing.
https://datadoghq.atlassian.net/browse/LOI-241
> Update Logs Parsing rules for the Teleport Pipeline

- openstack_controller/changelog.d/17996.fixed
- openstack_controller/datadog_checks/openstack_controller/api/api_rest.py
- openstack_controller/datadog_checks/openstack_controller/api/api_sdk.py
- openstack_controller/datadog_checks/openstack_controller/components/heat.py
- openstack_controller/tests/fixtures/POST/identity/v3/auth/tokens/1e6e233e637d4d55a50a62b63398ad15.json
- openstack_controller/tests/fixtures/POST/identity/v3/auth/tokens/6e39099cccde4f809b003d9e0dd09304.json
- openstack_controller/tests/fixtures/POST/identity/v3/auth/tokens/system.json
- openstack_controller/tests/test_unit_heat.py
We noticed that the heat stacks weren't being discovered in the Openstack Controller integration:
`2024-07-03 15:55:34 UTC | CORE | DEBUG | (pkg/collector/python/datadog_agent.go:133 in LogMessage) | - | (connectionpool.py:474) | [http://10.164.0.33:80](http://10.164.0.33/) "GET /heat-api/v1/***************************87d1e/v1/***************************87d1e/stacks HTTP/1.1" 404 154
2024-07-03 15:55:34 UTC | CORE | ERROR | (pkg/collector/python/datadog_agent.go:127 in LogMessage) | openstack_controller:92e51db26f99a1e5 | (component.py:79) | HTTPError: <Response [404]>`
When reading the API documentation for heat (https://docs.openstack.org/api-ref/orchestration/v1/), there is no endpoint for /v1 or /v1/{tenant_id}. 
So looking at how we get the endpoint in …
> Fixed the heat endpoint for the Openstack Controller

- .github/workflows/build-deps.yml
Makes it possible to manually trigger a dependency resolution (via the GitHub Actions UI). The result of that workflow is getting up to date dependencies uploaded to our index, and triggering an automated PR to update the lockfile.
Being able to get updated versions of transitive dependencies without having to update any direct dependency; also enabling a escape hatch to trigger the workflow for situations where some part of the process may fail unexpectedly.
- It's not clear from the documentation, but only members with write access should be able to trigger this manually (i.e. the same people that can already merge PR's).
> Enable manual triggering of dependency build & resolution

- mongo/changelog.d/17997.fixed
- mongo/datadog_checks/mongo/dbm/operation_samples.py
- mongo/datadog_checks/mongo/dbm/types.py
- mongo/tests/fixtures/$currentOp-standalone
- mongo/tests/results/opeartion-activities-mongos.json
- mongo/tests/results/opeartion-activities-standalone.json
- mongo/tests/results/operation-samples-mongos.json
- mongo/tests/results/operation-samples-standalone.json
This PR fixes a bug where the null value of `waiting_for_latch` in operation sampling is wrongly set to bool `False`. The correct waiting_for_latch null value should be an empty dict when an operation is not waiting for latch.
> [mongo] Properly handle the null value of waiting_for_latch in operation sampling

- wincrashdetect/assets/monitors/windows_crash.json
- wincrashdetect/manifest.json
adds a default monitor to the existing wincrashdetect check
feature request
> add default monitor for wincrashdetect

- datadog_checks_base/tests/base/checks/openmetrics/test_v2/test_transformers/test_counter.py
Add some more tests for openmetrics counters
The point about `_total` suffixes comes up from time to time, it would be good to formalize it with a test.
Also I could not find where we test the logic to force untyped metrics to be counters.
> Add tests for openmetrics counters

- .github/CODEOWNERS
Remove SIT as code owners of checks downloader
The SIT team is not a core contributor to this software anymore
> Remove SIT as code owners of checks downloader

- datadog_checks_base/tests/base/utils/db/test_util.py
- datadog_checks_base/tests/base/utils/test_tracking.py
Pytest tries to treat classes that start with 'Test' as tests. Helper class
names shouldn't start with 'Test' to avoid pytest complaining about them.
> Rename classes to avoid pytest warnings

- ray/manifest.json
- supervisord/manifest.json
Remove the use of `python` as part of any process signatures used for auto detection.
`python` itself is not necessary to detect any integration and conflicts with other ways to launch python integrations such as `python3`. This results in missed matches. Removing it will remove the ambiguity and allow proper matching. This was verified by regenerating the catalog in dd-go and verifying existing tests pass.
> Remove use of python from integration process signatures

- datadog_cluster_agent/changelog.d/18030.added
- datadog_cluster_agent/datadog_checks/datadog_cluster_agent/check.py
- datadog_cluster_agent/metadata.csv
- datadog_cluster_agent/tests/fixtures/metrics.txt
- datadog_cluster_agent/tests/test_datadog_cluster_agent.py
Adds some tagger and workloadmeta metrics to the `datadog_cluster_agent` integration:
- tagger.stored_entities
- tagger.updated_entities
- workloadmeta.events_received
- workloadmeta.notifications_sent
- workloadmeta.stored_entities
- workloadmeta.subscribers
The tagger and workloadmeta are used in some features offered by the Datadog Cluster Agent and these metrics are useful to debug potential issues.
> [datadog_cluster_agent] Add tagger and workloadmeta metrics

- .github/CODEOWNERS
Add network_path to codeowners
> Add network_path to codeowners

- network_path/manifest.json
Remove macOS support
Network Path is not supported yet on macOS due to permissions issues.
> Remove macOS support

- mysql/changelog.d/18024.fixed
- mysql/datadog_checks/mysql/const.py
- mysql/datadog_checks/mysql/mysql.py
- mysql/datadog_checks/mysql/queries.py
- mysql/tests/test_mysql.py
- mysql/tests/variables.py
Previously, we where assuming the following columns existed in every MySQL version:
- `COUNT_TRANSACTIONS_REMOTE_IN_APPLIER_QUEUE`
- `COUNT_TRANSACTIONS_REMOTE_APPLIED`
- `COUNT_TRANSACTION_LOCAL_PROPOSED`
- `COUNT_TRANSACTION_LOCAL_ROLLEDBACK`
- `member_role`
This only exist in version [8.0.2+](https://dev.mysql.com/blog-archive/group-replication-extending-group-replication-performance_schema-tables/), so we need to handle this case for lower versions. 
https://datadoghq.atlassian.net/browse/DBMON-2842
> [dbm] Handles group replication metrics for MySQL version < 8.0.2

- .github/CODEOWNERS
Add NDM as codeowners now that the team will be developing the Cisco ACI integration
> [NDM] [Cisco ACI] Add NDM as codeowners for Cisco ACI integration

- mongo/changelog.d/18044.fixed
- mongo/datadog_checks/mongo/collectors/coll_stats.py
- mongo/datadog_checks/mongo/collectors/index_stats.py
This PR fixes `OperationFailure` error on collection stats metrics when the datadog user is not authorized to run `$collStats` or `$indexStats` aggregation on system collections (e.g. system.replset on local database) on MongoDB Atlas. 
When `OperationFailure` happens in collection stats metrics, we will continue with the remain collections and log a warning message. 
`read` permission on `local` database grants access to datadog user to run `$collStats` or `$indexStats` aggregation for self-hosted mongodb. However `$collStats` or `$indexStats` fails for system collections on local database for MongoDB Atlas with error `not authorized on local to execute command`. 
The fix prevents the check to fail when `$collStats` or `$indexStats` fails for one collection.
> [mongo] Continue coll/index stats collection if user is not authorized to perform aggregation

- postgres/changelog.d/18047.added
- postgres/datadog_checks/postgres/config.py
- postgres/datadog_checks/postgres/postgres.py
- postgres/tests/conftest.py
- postgres/tests/test_metrics_cache.py
Adds a warning when `ssl` is set to an invalid value, and defaults to `allow` in those cases
Resolves #16764
> Improve log error for invalid ssl option in postgres config

- mongo/CHANGELOG.md
- mongo/changelog.d/18044.fixed
- mongo/datadog_checks/mongo/__about__.py
- requirements-agent-release.txt
Port release of mongodb integration to master branch.
> [Release] Bumped mongo version to 6.7.1

- datadog_checks_dev/changelog.d/18066.fixed
- datadog_checks_dev/pyproject.toml
Slack thread for context:
https://dd.slack.com/archives/C01C4E552HJ/p1721246310606769
Breaking tests in `datadog_checks_dev` due to pysmi update from July 16, 2024 ([version 1.4.4](https://pypi.org/project/pysmi/) was being picked up)
Pinning the version that was being utilized before for now
> [NDM] Pin pysmi version for breaking generate traps DB tests

- mongo/changelog.d/18067.fixed
- mongo/datadog_checks/mongo/dbm/operation_samples.py
- mongo/datadog_checks/mongo/mongo.py
- mongo/tests/results/opeartion-activities-mongos.json
- mongo/tests/results/opeartion-activities-standalone.json
- mongo/tests/results/operation-samples-mongos.json
- mongo/tests/results/operation-samples-standalone.json
- mongo/tests/test_integration.py
Rename dbms from mongodb to mongo so that dbms is consistent with integration name. This is to prevent double tagging on dbms with two different values `mongo` and `mongodb`. 
Prevent tag `dbms` double tagging with two different values `mongo` and `mongodb`.
> [mongo] rename dbms from mongodb to mongo

- .builders/images/linux-aarch64/Dockerfile
- .builders/images/linux-x86_64/Dockerfile
- .builders/images/macos-x86_64/builder_setup.sh
(cherry picked from commit 698f112f3a03191de7b7da1dcfb61bc306578fc7)
Backport of https://github.com/DataDog/integrations-core/pull/18064 to 7.56
https://datadoghq.atlassian.net/browse/VULN-7643
> update cURL from 8.4.0 to 8.7.1 (#18064)

- teamcity/changelog.d/18041.fixed
- teamcity/datadog_checks/teamcity/teamcity_rest.py
Handles TeamCity projects that have yet to be built.
The logic before this PR was such that if a `build config` had no builds, a re-initialization of all projects and `build configs` would be triggered. 
This is not what we want.
Now we only trigger a request to check if said `build config` has had its first build(s).
> [AGENT-11701] Fix TeamCity Integration

- mysql/assets/configuration/spec.yaml
- mysql/changelog.d/18097.fixed
- mysql/datadog_checks/mysql/config.py
- mysql/datadog_checks/mysql/config_models/defaults.py
- mysql/datadog_checks/mysql/data/conf.yaml.example
- mysql/tests/test_connection.py
This PR reverts the default 10s read_timeout for MySQL integration as we see connection leaks in rare cases.
Due to the default 10s read_timeout, mysql queries can sometimes timeout and result in uncaught exception. The uncaught exceptions that happen in DBM async threads will cause those threads to shutdown. A new thread will be started with a new database connection. In rare cases, the database connection from prior thread is closed on the client side but remains open on the database server side. This has resulted in more new connections being opened with datadog user and caused connection surge on the database.
> [mysql] revert default read_timeout

- postgres/assets/configuration/spec.yaml
- postgres/changelog.d/17993.added
- postgres/datadog_checks/postgres/config.py
- postgres/datadog_checks/postgres/config_models/defaults.py
- postgres/datadog_checks/postgres/config_models/instance.py
- postgres/datadog_checks/postgres/config_models/shared.py
- postgres/datadog_checks/postgres/data/conf.yaml.example
- postgres/tests/test_custom_metrics.py
Adds support for global custom queries for the postgres integration.
We run the same set of custom queries against multiple postgres databases. This feature will help to reduce the number of duplicate lines in the config file.
All tests have passed locally.
> Add global custom queries feature for postgres

- sqlserver/assets/monitors/sqlserver_db_not_sync.json
Adjusting the description based on customer feedback
This PR adjusts the description of the monitor definition for sqlserver backups
SDBM-1074 :  Customer feedback that the description was misleading
> SDBM-1074: Update sqlserver_db_not_sync.json

- argo_rollouts/README.md
- argo_workflows/README.md
- argocd/README.md
- fluxcd/README.md
- tekton/README.md
Add a link to a relevant blog post.
Tuesday Tasks
> Add Further Reading links

- kyverno/assets/monitors/controller_drops.json
- kyverno/manifest.json
> recommended monitor

- openai/README.md
- Re-add the API Key setup instructions under the API key tab
- Noticed that this tab information was empty even though it did previously have information
- Couldn't tell if is was intentionally removed, but other tab sections reference the "API Key setup" with no additional reference, so I added it back to the docs.
> Readd the API Key installation instructions

- cisco_aci/assets/configuration/spec.yaml
- cisco_aci/changelog.d/18099.added
- cisco_aci/datadog_checks/cisco_aci/config_models/defaults.py
- cisco_aci/datadog_checks/cisco_aci/config_models/instance.py
- cisco_aci/datadog_checks/cisco_aci/data/conf.yaml.example
- cisco_aci/datadog_checks/cisco_aci/fabric.py
- cisco_aci/tests/common.py
Part of the proposal to deal with new and existing customers that will be using Cisco ACI integration to explicitly enable sending metadata to NDM.
**Changes**
* Add config flag `enable_ndm` that defaults to False
* Send device/interface metadata if this flag is enabled
> [NDM] [Cisco ACI] Add config flag for enabling sending metadata to NDM

- datadog_checks_base/datadog_checks/base/checks/libs/prometheus.py
Tweak to a recently merged (and not released yet) [PR](https://github.com/DataDog/integrations-core/pull/17514). It started out as a way to satisfy the linter, but then became a logic change.
cc @Nevon
> Separate parsing crashes before and while we loop over metric items

- mysql/README.md
A user reported that this command is missing a semicolon and causes the prompt to hang.
> Add missing semicolon to Mysql command

- datadog_checks_base/tests/base/utils/http/test_http.py
- datadog_checks_downloader/tests/test_downloader.py
- gitlab/tests/test_e2e.py
- postgres/tests/test_deadlock.py
- postgres/tests/test_logical_replication.py
- postgres/tests/test_pg_integration.py
- postgres/tests/test_pg_replication.py
- postgres/tests/test_relations.py
Replaces `@flaky` with `@pytest.mark.flaky`
`@pytest.mark.flaky` has the same features **plus it lets you (de)select tests using pytest**.
> Change flaky test marker to work with pytest marker selection

- postgres/assets/configuration/spec.yaml
- postgres/changelog.d/18144.fixed
- postgres/datadog_checks/postgres/data/conf.yaml.example
- postgres/datadog_checks/postgres/metadata.py
- postgres/datadog_checks/postgres/postgres.py
- postgres/tests/test_discovery.py
- postgres/tests/test_metadata.py
Removes the restriction on postgres schema collection that relation metrics must be enabled. Replaces it with a warning if there are too many tables to return all of them and relation metrics are disabled.
This requirement is confusing to users and usually unnecessary. In the cases where the warning triggers, a sampling of tables will be returned and users can troubleshoot one of the two solutions for the missing tables.
> Remove schema collection dependency on relations configuration

- .ddev/ci/scripts/sqlserver/linux/55_install_odbc.sh
This PR installs msodbcsql18 version `18.3.3.1` in ci. `18.3.3.1` is the embedded msodbcsql18 version in datadog-agent. Forcing ci to install the exact version avoids test fail when a new msodbcsql18 is released. It also makes sure the test uses the same msodbcsql18 version as datadog-agent.
> pin msodbcsql18 to 18.3.3.1 in ci

- postgres/changelog.d/18169.added
- postgres/datadog_checks/postgres/util.py
- postgres/metadata.csv
- postgres/tests/common.py
Collect blk time metrics from `pg_stat_database` to create the following metrics:
- `postgresql.blk_read_time`: Time spent reading blocks in ms
- `postgresql.blk_write_time`: Time spent writing blocks in ms
pg_stat_database provides blk_read_time and blk_write_time since PG 9.2. We do have an existing `postgresql.queries.blk_x_time` metric but it is by query and relies on pg_stat_statements. Having the metric on a db level is more reliable and cheaper as it won't be impacted by possible gc of tracked queries in pg_stat_statements.
> Collect blk read/write time from pg_stat_database

- datadog_checks_base/changelog.d/18019.added
- datadog_checks_base/datadog_checks/base/checks/base.py
- datadog_checks_base/datadog_checks/base/checks/logs/__init__.py
- datadog_checks_base/datadog_checks/base/checks/logs/crawler/__init__.py
- datadog_checks_base/datadog_checks/base/checks/logs/crawler/base.py
- datadog_checks_base/datadog_checks/base/checks/logs/crawler/stream.py
- datadog_checks_base/datadog_checks/base/stubs/datadog_agent.py
- datadog_checks_base/datadog_checks/base/utils/serialization.py
- datadog_checks_base/tests/base/checks/logs/__init__.py
- datadog_checks_base/tests/base/checks/logs/crawler/__init__.py
- datadog_checks_base/tests/base/checks/logs/crawler/test_base.py
- datadog_checks_base/tests/base/checks/test_agent_check.py
This adds a `send_log` method to the base class which sends a log to the Agent for eventual submission. There is also a `cursor` keyword argument which may be used to persist metadata across Agent restarts in order to resume from the point of shutdown.
Blocked on https://github.com/DataDog/datadog-agent/pull/26978
> Support log submission from checks

- sap_hana/README.md
- sap_hana/hatch.toml
- sap_hana/tests/common.py
> Update `hdbcli` dependency

- datadog_checks_base/datadog_checks/base/checks/base.py
Minor fixes to the docstring of the unreleased `send_log` method.
Since it hasn't been released yet, there's no need for a changelog
> Brush up docs for send_log method

- datadog_operator/assets/dashboards/operator_overview.json
- kubernetes/assets/dashboards/kubernetes_clusters.json
- kubernetes/assets/dashboards/kubernetes_dashboard.json
- kubernetes/assets/dashboards/kubernetes_pods.json
- vsphere/assets/dashboards/vmware_vsphere_tkg_-_overview.json
https://datadoghq.atlassian.net/browse/CONTINT-4331
Updated Kubernetes OOTB Dashboards to use the most recent container status waiting metric from `kube-state-metrics`. Allows users to use the `reason` tag. Also synchronizes the data between the `Container States` widget and `Containers in CrashloopBackOff (by Pod)` widget. 
Previously a mix of `kubernetes_state.container.waiting` and `kubernetes.containers.state.waiting` were used. Now all cases use `kubernetes_state.container.status_report.count.waiting`.
Users could not access a `reason` tag for some `container.status.waiting` metrics on the Dashboards. Different metrics were being used in different places on the dashboards as well. Updated all instances to the most recent metric from `kube-state-metrics` to synchronize them and ensure …
> [CONTINT-4331] Update Container Waiting Graphs in Kubernetes OOTB Dashboards

- kubernetes/assets/dashboards/kubernetes_pods.json
Adds a new widget to show `Pods Running by Runtime Class` on the Kubernetes Pods Overview dashboard. 
Recently added `kube_runtime_class` tag to kubernetes pods that will be released with agent v7.57.
See: https://github.com/DataDog/datadog-agent/pull/28076
Widget allows users to see pods sorted by `runtime_class`.
> Added Pods Running by Runtime Class Widget to Kubernetes Pods Overview

- sqlserver/changelog.d/18203.fixed
- sqlserver/datadog_checks/sqlserver/connection.py
- sqlserver/datadog_checks/sqlserver/connection_errors.py
- sqlserver/tests/test_connection.py
This PR fixes connection string password obfuscation in OLE DB driver error message when one or more backslash exist in the password. 
https://datadoghq.atlassian.net/browse/DBMON-4349
> [sqlserver] fix connection string password obfuscation in OLE DB driver error message

- datadog_checks_base/changelog.d/18119.fixed
- datadog_checks_base/datadog_checks/base/utils/http.py
Fixes a bug when making HTTP requests to Unix sockets
I encountered the following bug in production when trying to specify a unix socket path for an openmetrics endpoint.
```
File "/opt/datadog-agent/embedded/lib/python3.11/site-packages/datadog_checks/base/utils/http.py", line 609, in should_bypass_proxy
ipaddress = ip_address(ensure_unicode(parsed_uri))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/datadog-agent/embedded/lib/python3.11/ipaddress.py", line 54, in ip_address
raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: None does not appear to be an IPv4 or IPv6 address
During handling of the above exception, another exception occurred:
File …
```
> Ensures that 'should_bypass_proxy' correctly considers unix:/// URLs

- datadog_checks_dev/changelog.d/18217.added
- datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/licenses.py
Add new `ddtrace` license to known licenses
https://github.com/DataDog/integrations-core/pull/18215
> Add new `ddtrace` license to known licenses

- datadog_checks_base/changelog.d/18218.added
- datadog_checks_base/datadog_checks/base/checks/base.py
- datadog_checks_base/tests/base/checks/test_agent_check.py
Backend expects milliseconds but Python's timestamps are usually seconds
> Enforce format of timestamp logs attribute

- .github/workflows/test-target.yml
Adds a pip cache to our CI test jobs.
We install quite a few dependencies for in order to execute our tests in CI.
We've already introduced the pip cache to the job that builds our docs, it shaved 2 minutes off the job's runtime.
There have been no issues with it in several months, so it's time we try it for the test jobs too.
> Add pip cache to CI test jobs

- postgres/assets/configuration/spec.yaml
- postgres/changelog.d/18228.added
- postgres/datadog_checks/postgres/aws.py
- postgres/datadog_checks/postgres/config_models/instance.py
- postgres/datadog_checks/postgres/data/conf.yaml.example
- postgres/datadog_checks/postgres/postgres.py
This PR adds new optional config option `role_arn` to postgres aws managed authentication.
For example:
```
aws:
instance_endpoint: xxxxxxxx.us-east-1.rds.amazonaws.com
region: us-east-1
managed_authentication:
enabled: true
role_arn: arn:aws:iam::xxxxxxxx:role/rds-iam-role
```
The new `role_arn` option can be used to support cross aws account iam authentication. 
TODO: once the change is released, update public doc to include examples for cross account iam authentication.
https://datadoghq.atlassian.net/browse/DBMON-3445
> [postgres] add role_arn to support cross account iam auth

- sqlserver/datadog_checks/sqlserver/sqlserver.py
Reverts DataDog/integrations-core#17750
Reverting this PR as it contains a *very* bad bug where the host field on metrics and events will fall back to `None` when the static information cache reaches its TTL of 1 day. When this happens, we see gaps in data for sqlserver instances because our backend drops these as bad payloads. We can see an example of this happening in our integration environment:
... meanwhile, if we log the payloads we see the `host` value is set to `null`:
```
{"host":null,"ddagentversion":"7.56.0","ddsource":"sqlserver",...
```
A follow up PR will be merged to fix the version tag issue in a subsequent release https://github.com/DataDog/integrations-core/pull/18237
> Revert "[dbm] fix flapping sqlserver_version"

- mongo/assets/configuration/spec.yaml
Update the `database_instance_collection_interval` example value to 300 seconds to be inline with the default collection interval. `database_instance_collection_interval` is a hidden config option so no public config example updates.
> [mongo] fix the database_instance_collection_interval example in config

- gitlab_runner/tests/test_e2e.py
> Retry gitlab runner test if we get transient 502 response

- datadog_checks_base/changelog.d/18273.added
- datadog_checks_base/datadog_checks/base/utils/replay/execute.py
Combines `stderr` with `stdout` (using `stderr=subprocess.STDOUT`) so only one pipe carries both regular messages and error messages. 
`master` pipeline hangs when running `test_replay_all` in `datadog_checks_base`
> Combine streams to single pipe

- ddev/changelog.d/18271.fixed
- ddev/src/ddev/e2e/agent/docker.py
If the combo of agent and integration found in the pre-built agent image crashes the agent, we can't test a fix with `ddev env test` because we crash before we get to load the local package
We disable the integration until we've installed the local package.
Easier tests, clearer mental model for users.
> Enable local check only after installing it in agent container.

- datadog_cluster_agent/changelog.d/18265.added
- datadog_cluster_agent/datadog_checks/datadog_cluster_agent/check.py
Add scraping of Autoscaling metrics in DCA check
Autoscaling Private Beta
Currently not documented and no payloads added on purpose. Things are likely to change and will really be available when we hit public beta, for which we will come back and add documentation and test paylods.
> Add telemetry scraping for Autoscaling

- datadog_checks_base/changelog.d/18278.added
- datadog_checks_base/datadog_checks/base/utils/db/query.py
- datadog_checks_base/datadog_checks/base/utils/db/transform.py
- datadog_checks_base/datadog_checks/base/utils/db/utils.py
- datadog_checks_base/tests/base/utils/db/common.py
- datadog_checks_base/tests/base/utils/db/test_query_manager.py
- datadog_checks_base/tests/base/utils/db/test_transformers.py
Follow-up to https://github.com/DataDog/integrations-core/pull/18019, allow customers to submit logs from databases
I haven't yet thought of a way for configuring the cursor plus modifying the query based on the cursor, that will come in another PR
> Add `log` transformer to the QueryManager

- postgres/assets/configuration/spec.yaml
- postgres/changelog.d/18287.fixed
- postgres/datadog_checks/postgres/data/conf.yaml.example
- postgres/datadog_checks/postgres/metrics_cache.py
- postgres/datadog_checks/postgres/statement_samples.py
- postgres/datadog_checks/postgres/util.py
- postgres/tests/test_connections.py
- postgres/tests/test_statements.py
* Fixes various edge case errors that could result from `ignore_databases` being set in combination with other options
* Clarifies the documentation on how `ignore_databases` interacts with `collect_default_database`
> Fix errors resulting from ignore_databases

- envoy/tests/conftest.py
CI occasionally fails with retry errors when we fail to set up the docker containers for envoy.
This adds some more retries to get us to pass more often.
> Retry envoy docker setup more times

- kafka_consumer/changelog.d/18307.fixed
- kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
Make the write and the read from persistent cache use the same key (fix typo).
https://datadoghq.atlassian.net/browse/AGENT-11612
> Fix typo when saving broker timestamp

- mongo/changelog.d/18334.added
- mongo/datadog_checks/mongo/metrics.py
- mongo/metadata.csv
- mongo/tests/fixtures/dbstats-local
- mongo/tests/results/metrics-dbstats-local.json
This PR adds a new metric `mongodb.stats.views` for number of views in the database.
> [mongo] collect metric number of views in the database

- sqlserver/assets/configuration/spec.yaml
- sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
Updated the description for the availability_group option in SQL Server to make the expected value more clear.
The description for `availability_group` was misleading users to put the availability group name instead of the resource group id which is what we actually check against.
> Updated description for the availability_group option

- datadog_checks_base/datadog_checks/base/checks/base.py
- mkdocs.yml
We also explicitly state in the docs config that we are using this format.
Rendering of parameters is broken without this change.
> Base package docstrings follow google format

- .github/workflows/build-ddev.yml
[Relevant Doc](https://github.com/actions/download-artifact/tree/main?tab=readme-ov-file#v4---whats-new:~:text=%23%20A%20glob%20pattern%20to%20the%20artifacts%20that%20should%20be%20downloaded.%0A%20%20%20%20%23%20Ignored%20if%20name%20is%20specified.%0A%20%20%20%20%23%20Optional.%0A%20%20%20%20pattern%3A)
Paper trail:
I was comparing logs of the installers (which were getting uploaded) and binaries which weren't. 
Binaries:
```
Run actions/download-artifact@v4
Downloading single artifact
Preparing to download the following artifacts:
- standalone (ID: 1780011911, Size: 3369639)
```
Installers:
```
Run actions/download-artifact@v4
Found 17 artifact(s)
Filtering artifacts by pattern 'installers-*'
Preparing to download the following artifacts:
- installers-Windows (ID: 1780014765, Size: …
```
> fix gh action that uploads standalone binaries

- mongo/changelog.d/18342.fixed
- mongo/datadog_checks/mongo/mongo.py
This PR fixes a bug where the optional collections stats metrics are always collected regardless it's enabled or not.
MongoDB collection stats metrics are optional and can be enabled by adding `collection` to `additional_metrics` config. Running `$collStats` on every collection (especially when database autodiscovery is enabled) can be a costly operation when a database has large number of collections. As per our document, collection stats metrics is opted in. 
However the integration always collects collection stats metrics but only skips submitting the collection stats metrics. This behavior is undesired and put unwanted load on the monitored database.
> [mongo] collection stats metrics should be optional

- redisdb/README.md
Puts a table of AD parameters in the Redis integration readme. Follows pattern in other integrations.
Request from Technical Solutions.
> DOCS-8541 - Put AD table in Redis integration readme

- nginx/README.md
Puts a table of AD parameters in the NGINX integration readme. Follows pattern in other integrations.
Request from Technical Solutions.
> DOCS-8540 - Put AD table in NGINX readme

- postgres/datadog_checks/postgres/postgres.py
Add log to report Agent uses password or token for connection.
- For easy troubleshooting.
- Agent replaces a given password with token implicitly when `aws` / `azure` section is configured.
```
2024-08-13 05:14:17 UTC | CORE | DEBUG | (pkg/collector/python/datadog_agent.go:131 in LogMessage) | postgres:8343993ddd1c5f02 | (postgres.py:796) | Try to connect to 172.25.0.3 with password
```
> postgres: add log to specify Agent uses password or token to connect to db

- .builders/images/macos-x86_64/extra_build.sh
- .builders/scripts/build_wheels.py
Passes additional environment variables to ensure we use the correct libxml2 and lxslt versions.
A build flaked (https://github.com/DataDog/integrations-core/actions/runs/10380933633/job/28741538776#step:7:1069) and it included this message:
```
Building against libxml2 2.9.4 and libxslt 1.1.29
```
That means the dependencies we built explicitly for this python package are not being picked up given that the versions don't match:
https://github.com/DataDog/integrations-core/blob/138b5e104dc6be1f2103713391e82cfc43c0120f/.builders/images/macos-x86_64/builder_setup.sh#L47-L49
- This is not too well documented in lxml's building docs, and the setup script has quite a bit of complex logic. The piece of code that led me to find these env variables is: …
> Pass explicit paths for dependencies for building lxml

- otel/assets/dashboards/otel_collector_metrics_dashboard.json
Service can be used to differentiate metrics between OSS collector (service:otelcol) and Converged Agent Collector (service:datadog-agent). This is a follow up to: https://github.com/DataDog/datadog-agent/pull/28064.
https://datadoghq.atlassian.net/browse/OTEL-2015
> Add service template variable to OTel Collector Metrics Dashboard

- fly_io/changelog.d/18337.fixed
- fly_io/datadog_checks/fly_io/check.py
- fly_io/datadog_checks/fly_io/errors.py
- fly_io/tests/test_unit.py
Adds error handle decorator to catch http and misc errors to preserve metric collection
catch errors for all api methods while not repeating code
inspired by [openstack_controller](https://github.com/DataDog/integrations-core/blob/master/openstack_controller/datadog_checks/openstack_controller/components/component.py#L67) and [vsphere](https://github.com/DataDog/integrations-core/blob/master/vsphere/datadog_checks/vsphere/api.py#L28)
> [PLINT-449] Add more robust error handling

- fly_io/manifest.json
Adds a metric to check for fly from the rest API
still register integration if openmetrics endpoint is down
> Add another metric to check

- openai/assets/dashboards/overview_dashboard.json
This PR allows for the Log Widgets of the OpenAI OOTB dashboard to query logs using `@`.
The implementation of the OpenAI Integration was just merged in the PHP Tracing Library: https://github.com/DataDog/dd-trace-php/pull/2685
OOTB, logs generated from the PHP Integration, despite having the `openai.request.endpoint` tag, weren't picked up by the logs widget as shown in the screenshot below
However, when using `@`, they were:
> feat(openai): Query logs by log tag

- flink/README.md
- Remove dynamic parameter, Flink uses different datacenter parameters than Datadog.
- There are only two datacenters (EU/US) that are supported. [[source](https://nightlies.apache.org/flink/flink-docs-release-1.20/docs/deployment/metric_reporters/#datadog:~:text=(optional)%20The%20data%20center%20(EU/US)%20to%20connect%20to%2C%20defaults%20to%20US.)]
- [DOCS-8618](https://datadoghq.atlassian.net/browse/DOCS-8618)
[DOCS-8618]: https://datadoghq.atlassian.net/browse/DOCS-8618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove dynamic parameter

- postgres/changelog.d/18386.fixed
- postgres/datadog_checks/postgres/config.py
Added the expected default port to the PostgresConfig
This PR will actually set the default port to 5432 when user don't provide a port in the conf.yaml.
When the `port` is empty in the `postgres.d/conf.yaml`, we currently would leave the `port` as an empty string and then if the user was trying to use IAM Authentication, the generate token would be invalid for authenticating because no port is provided.
When using standard authentication this isn't an issue because `psycopg2` will use `5432` as the port if none if provided to it.
> Added default port

- postgres/assets/configuration/spec.yaml
- postgres/changelog.d/18358.added
- postgres/datadog_checks/postgres/config.py
- postgres/datadog_checks/postgres/data/conf.yaml.example
- postgres/pyproject.toml
- postgres/tests/test_pg_integration.py
In https://github.com/DataDog/integrations-core/pull/18269 and https://github.com/DataDog/datadog-agent/pull/28027, I added functions to get the host tags of the agent host. This PR updates the agent host tags that we use in the postgres integration. This change only affects customers with the `propagate_agent_tags` flag set to true. By calling `get_agent_host_tags`, we not only use the tags in the conf.yaml file but also other tags on the agent host. 
Metrics emitted by DBM integrations (postgres, sql server, and mysql) are tagged with the tags from the database instance host. We would like to update the `propagate_agent_tags` option (default false) that allows us to also consider the tags of the agent host. If this setting is enabled, we will propagate all agent host tags. This allows …
> Propagate agent host tags for postgres

- agent_requirements.in
- snmp/changelog.d/18245.changed
- snmp/changelog.d/18245.fixed
- snmp/datadog_checks/snmp/commands.py
- snmp/pyproject.toml
This PR bumps `pysnmp` to fix integration tests for py3.12
[4.4.10](https://github.com/pysnmp/pysnmp/blob/main/CHANGES.txt) rebased MIB importing code onto `importlib` because `imp` is long deprecated. Python 3.12 removes `imp`.
> Bump the `pysnmp` version for py3.12

- mongo/changelog.d/18405.added
- mongo/datadog_checks/mongo/collectors/base.py
- mongo/datadog_checks/mongo/collectors/index_stats.py
- mongo/datadog_checks/mongo/metrics.py
- mongo/metadata.csv
- mongo/tests/results/metrics-indexes-stats-autodiscover.json
- mongo/tests/results/metrics-indexes-stats.json
This PR adds new metric `mongodb.collection.indexes.accesses.opsps` to measure number of times the index was used per second. The existing `mongodb.collection.indexes.accesses.ops` metric is an ever increasing value. The new metric provides better insights into index usage changes.
> [mongo] add index usage per second metric

- postgres/changelog.d/18402.added
- postgres/datadog_checks/postgres/postgres.py
- postgres/tests/common.py
- postgres/tests/compose/etc/postgresql/postgresql.conf
- postgres/tests/compose/etc/postgresql_replica2/postgresql.conf
- postgres/tests/test_discovery.py
- postgres/tests/test_e2e.py
- postgres/tests/test_pg_integration.py
- postgres/tests/test_pg_replication.py
- postgres/tests/test_statements.py
- postgres/tests/utils.py
Set `cluster_name` as a `postgresql_cluster_name` metric tag if it's configured in postgresql.conf. 
PostgreSQL instances can set a cluster_name parameter that will be used in the process' title. There's currently no standard way to name a cluster so custom_tags are used as a replacement but this usually leads to having different tag names. Relying on the defined cluster_name from postgresql.conf allows to have a standard tag.
The fetch of the system identifier was moved from being executed at every check to the initialiser's checks. This required some changes in the test to use `check.run()` instead of `check.check(...)` in order to go through the initialisation queries to correctly set the expected tags.
> Add cluster_name as tag to PG metrics

- mongo/changelog.d/18408.fixed
- mongo/datadog_checks/mongo/dbm/utils.py
This PR fixes a bug to skip explain get profile level & listCollections command.
> [mongo] skip explain get profile level & listCollections command

- mongo/assets/configuration/spec.yaml
- mongo/changelog.d/18416.added
- mongo/datadog_checks/mongo/api.py
- mongo/datadog_checks/mongo/collectors/coll_stats.py
- mongo/datadog_checks/mongo/collectors/index_stats.py
- mongo/datadog_checks/mongo/config.py
- mongo/datadog_checks/mongo/config_models/instance.py
- mongo/datadog_checks/mongo/data/conf.yaml.example
- mongo/datadog_checks/mongo/dbm/operation_samples.py
- mongo/datadog_checks/mongo/dbm/slow_operations.py
- mongo/datadog_checks/mongo/mongo.py
- mongo/tests/conftest.py
- mongo/tests/fixtures/profile-admin
- mongo/tests/test_dbm_operation_samples.py
- mongo/tests/test_dbm_slow_operations.py
This PR adds a config option `database_autodiscovery.max_collections_per_database` (default to 100) to `database_autodiscovery` configuration block. This option is applied to limit the maximum number of collections per database to collect collection stats and indexes stats. 
`$collStats` and `$indexStats` aggregation can have negative performance impact on the monitored database when number of collections is high.
https://datadoghq.atlassian.net/browse/DBMON-4461
> [mongo] limit max number of collections to be monitored per database

- network_path/manifest.json
Network Path integration is currently not supported on windows
Network Path integration is currently not supported on windows
> Network Path integration is currently not supported on windows

- oracle/README.md
- oracle/manifest.json
- Updates the oracle tile name to `Oracle Database`
- An `Oracle Cloud Infrastructure` integration is being built. Since the existing `Oracle` integration is for Oracle Databases, it will be nice to make this more specific to not cause confusion with the OCI integration 
- @romandatadog discussed and got approval from `Jonathan Morin`, `Casey Culligan`, and `Justin Iso`
> [eci][oci] update Oracle tile name to Oracle Database

- datadog_checks_base/changelog.d/18438.added
- datadog_checks_base/datadog_checks/base/utils/http.py
- datadog_checks_base/tests/base/utils/http/test_http.py
Along the way also add optional kwarg to override the `session` attribute of `RequestsWrapper`.
This test's flakiness wasn't worth the value it was delivering, i.e. testing
that the requests lib respects the timeout.
We've refocused the test on checking that we provide the timeout correctly to
requests and that we let the timeout error bubble up.
> Convert an integration test to unit test.

- mysql/changelog.d/18450.fixed
- mysql/datadog_checks/mysql/activity.py
- mysql/tests/test_query_activity.py
A customer was seeing a wrong agent message in DBM UI while using Azure Flexible Server. Query Activity and Wait Event collection [is not supported](https://docs.datadoghq.com/database_monitoring/setup_mysql/troubleshooting/#query-activity-is-missing) for MySQL Azure Flexible Server deployment type, so we should not emit the warning when this is the case. 
Customer support escalation.
> [dbm] Handles mysql flexible server warning bug

- mongo/changelog.d/18461.fixed
- mongo/datadog_checks/mongo/dbm/slow_operations.py
- mongo/datadog_checks/mongo/mongo.py
- mongo/pyproject.toml
This PR adds a TTL cache (ttl 60 mins) to avoid repeated query for database profiling level in slow operations collections.
https://datadoghq.atlassian.net/browse/DBMON-4484
> [mongo] cache database profiling level to avoid repeated queries

- mongo/changelog.d/18463.added
- mongo/datadog_checks/mongo/common.py
- mongo/datadog_checks/mongo/dbm/operation_samples.py
- mongo/datadog_checks/mongo/dbm/schemas.py
- mongo/datadog_checks/mongo/dbm/slow_operations.py
- mongo/datadog_checks/mongo/mongo.py
- mongo/tests/fixtures/isMaster-replica-primary
- mongo/tests/results/metrics-replset-lag-from-primary.json
- mongo/tests/test_integration.py
This PR includes replica set tags in metrics. Replica set tags are optional tags set in replica set configuration. 
NOTE: The replica set tags are different from MongoDB Atlas cluster tags. MongoDB Atlas cluster tags cannot be retrieved with mongodb driver api at the moment. 
https://datadoghq.atlassian.net/browse/DBMON-4485
> [mongo] include replica set tags in metrics

- .builders/images/linux-x86_64/Dockerfile
Needed for the py3.12 update.
We probably dropped this because we were using prebuilt wheels for py3.11 on that architecture, that won't be the case for the combination of lxml and python versions we are targeting.
> Build lxml dependencies for linux x64

- databricks/README.md
Adding note from databricks documentation regarding global init scripts
Customer reached about some confusion in our databricks documentation, where global init scripts only run on clusters configured with single user or legacy no-isolation shared access mode. There is a link to the databricks documentation, but worth noting in our documents.
https://datadog.zendesk.com/agent/tickets/1808056
> Update Databricks integration

- spark/tests/test_spark.py
Preparation for https://github.com/DataDog/integrations-core/pull/18212
> Switch away from deprecated ssl API

- ntp/README.md
one line addition to docs to mention networking requirements
to avoid misconfiguration of the NTP check
> edit NTP check docs to mention networking requirements

- mongo/metadata.csv
`mongodb.collection.indexes.accesses.opsps` should be events/second.
> [mongo] fix mongodb.collection.indexes.accesses.opsps metric unit

- teleport/assets/configuration/spec.yaml
- teleport/changelog.d/18466.added
- teleport/datadog_checks/teleport/config_models/defaults.py
- teleport/datadog_checks/teleport/config_models/instance.py
- teleport/datadog_checks/teleport/config_models/shared.py
- teleport/datadog_checks/teleport/data/conf.yaml.example
Adds the openmetrics properties to the Teleport configuration spec
Allow more control of the check behavior using the builtin openmetrics properties.
> Add openmetrics properties to Teleport configuration spec

- ibm_db2/hatch.toml
- ibm_db2/tests/docker/requirements.txt
Bumped version of IBM DB due to failing CI in python 3.12 bump
https://github.com/ibmdb/python-ibmdb/pull/920
> Bump `ibm_db` version

- fly_io/README.md
Remove min collection interval from recommended config 
we should use the default collection interval for now
> Remove min collection interval from recommended config 

- mongo/changelog.d/18476.added
- mongo/datadog_checks/mongo/api.py
- mongo/datadog_checks/mongo/common.py
- mongo/datadog_checks/mongo/dbm/schemas.py
- mongo/datadog_checks/mongo/mongo.py
- mongo/tests/fixtures/list_search_indexes
- mongo/tests/mocked_api.py
- mongo/tests/results/schemas-standalone-atlas.json
- mongo/tests/results/schemas-standalone.json
- mongo/tests/test_dbm_schemas.py
This PR adds search indexes to mongo schema collection for mongodb atlas instance.
https://datadoghq.atlassian.net/browse/DBMON-4488
> [mongo] collect search indexes for mongodb atlas instance

- mongo/changelog.d/18473.added
- mongo/datadog_checks/mongo/mongo.py
- mongo/tests/fixtures/server_info
- mongo/tests/test_integration.py
- mongo/tests/test_integration_standalone.py
This PR adds `modules` to mongodb instance metadata. `modules` are a list of add-on modules that [mongod](https://www.mongodb.com/docs/manual/reference/program/mongod/#mongodb-binary-bin.mongod) was built with. Possible values currently include "enterprise" and "rocksdb". This can be used to determine if the mongodb instance is built with community or enterprise edition.
https://datadoghq.atlassian.net/browse/DBMON-4487
> [mongo] add modules to mongodb instance metadata

- ddev/changelog.d/18413.added
- ddev/src/ddev/cli/release/branch/__init__.py
- ddev/src/ddev/cli/release/branch/tag.py
- ddev/src/ddev/utils/git.py
- ddev/tests/cli/release/branch/test_tag.py
By automating this task we reduce cognitive load on release managers and reduce the probability of pushing an incorrect tag.
> Tag release branch

- mongo/assets/configuration/spec.yaml
- mongo/changelog.d/18502.added
- mongo/datadog_checks/mongo/config.py
- mongo/datadog_checks/mongo/data/conf.yaml.example
This PR enables MongoDB inferred schema collection by default (DBM only).
> [mongo] enable inferred schema collection by default

- snmp/assets/configuration/spec.yaml
- snmp/datadog_checks/snmp/data/conf.yaml.example
Clarified that the `match_value` for `interface_configs` is case sensitive in `conf.yaml.example`
[A customer support ticket](https://datadog.zendesk.com/agent/tickets/1826540)
Please merge when approved
> Added 'case sensitive' to interface_configs in SNMP

- mongo/changelog.d/18506.added
- mongo/datadog_checks/mongo/collectors/coll_stats.py
- mongo/datadog_checks/mongo/collectors/index_stats.py
This PR adds warnings when agent user is not authorized to run collStats and indexStats on collections.
https://datadoghq.atlassian.net/browse/DBMON-4500
> [mongo] Add warnings when agent user is not authorized to run collStats and indexStats on collections

- datadog_cluster_agent/README.md
This PR adds some details about how the Datadog Cluster Agent check runs - namely in a node Agent, not in the Cluster Agent.
The motivation started with a [customer Zendesk ticket](https://datadog.zendesk.com/agent/tickets/1795585). The feedback there was there was confusion about getting the status of the Cluster Agent. The user expected to see the Datadog Cluster Agent integration there.
Please merge when ready
> clarified cluster agent check docs

- process/README.md
The [Processes integration doc](https://docs.datadoghq.com/integrations/process/?site=us) lists some specific metrics which are not available on Windows. `system.processes.mem.real` is not listed here, but we can see from the 'Data collected' (metadata.csv) that this metric is also not available on Windows.
This PR updates the note to include this metric
https://datadog.zendesk.com/agent/tickets/1832589
> update processes integration doc 'Metrics notes'

- .github/workflows/config/labeler.yml
- ddev/tests/cli/validate/test_labeler.py
- We update the labeler config to satisfy the validation.
- We change our tests so that they catch this next time it changes from under us.
Prevent folks who are submitting new integrations from having to deal with indentation in their PRs.
> Adjust labeler config and ddev tests to how pyyaml indents lists

- .builders/images/macos-x86_64/builder_setup.sh
- .github/workflows/build-deps.yml
- Removes references to DD_PYTHON_2 which is no longer defined at the job.
- Adds workflow file to cache key to prevent this kind of error from not being caught on the PR.
- Adds workflow files to triggers for pushes to master.
https://github.com/DataDog/integrations-core/pull/18577 breaks macOS builds as soon as there's a cache miss during builder setup: https://github.com/DataDog/integrations-core/actions/runs/10836797983/job/30071333931?pr=18212.
We missed this on #18577 because the cache key doesn't include the workflow key despite it potentially affecting the setup.
> Fix dependency build for macOS

- ddev/tests/cli/validate/test_licenses.py
Fixes the mock fixture data for a ddev test.
The test is relying on real data **in the master branch**. So it passed when for the [PR that changed this data](https://github.com/DataDog/integrations-core/pull/18417) but as soon as we merged to master it started failing.
I have it on my radar to fix this testing setup, it's a drag.
> Fix test for license validation

- sqlserver/changelog.d/18586.fixed
- sqlserver/datadog_checks/sqlserver/utils.py
- sqlserver/tests/test_connection.py
- sqlserver/tests/test_unit.py
Fix `odbc.ini` config handling for Linux.
With some recent changes, `/opt/datadog-agent/embedded/etc` wasn't in the ODBC config search path anymore. For example, in [this escalation](https://datadoghq.atlassian.net/browse/), the customer upgraded from `7.53` to `7.56.2` and `odbc.ini` stored in `/opt/datadog-agent/embedded/etc` was ignored.
`odbc.ini` is looked for in the directory configured in the `ODBCSYSINI` environment variable. `odbcinst.ini` have to be in the same directory.
The algorithm:
1. If the environment variable `ODBCSYSINI` is set externally, we don't do anything - that step remained unchanged.
2. Change: if `ODBCSYSINI` isn't set  and there's a non-empty `odbc.ini` in `/opt/datadog-agent/embedded/etc`, the Agent sets `ODBCSYSINI` to `/opt/datadog-agent/embedded/etc`. If …
> [sqlserver] Fix odbc.ini config handling for Linux (SDBM-1171)

- requirements-agent-release.txt
- sqlserver/CHANGELOG.md
- sqlserver/changelog.d/18586.fixed
- sqlserver/datadog_checks/sqlserver/__about__.py
Porting changelog and versions from 7.58.x release
> [Release] Bumped sqlserver version to 17.5.3

- ddev/tests/cli/meta/scripts/conftest.py
- ddev/tests/cli/meta/scripts/test_upgrade_python.py
> Improve assertions in test for python upgrade script

- mongo/datadog_checks/mongo/metrics.py
This PR adds comments to metrics to indicate which collector it comes from
> [mongo] add comments to metrics to indicate which collector it comes from

- vsphere/changelog.d/18601.fixed
- vsphere/datadog_checks/vsphere/vsphere.py
- vsphere/tests/test_unit.py
This PR just takes the logic for excluded host tags [already being used](https://github.com/DataDog/integrations-core/blob/master/vsphere/datadog_checks/vsphere/vsphere.py#L442) for non-property metrics, and applies it to property metrics.
> [PLINT-508] Fixed excluded host tags for property metrics in vSphere

- active_directory/datadog_checks/active_directory/active_directory.py
- aerospike/datadog_checks/aerospike/aerospike.py
- amazon_msk/datadog_checks/amazon_msk/amazon_msk.py
- argocd/datadog_checks/argocd/check.py
- argocd/tests/test_argocd.py
- aspdotnet/datadog_checks/aspdotnet/aspdotnet.py
- cilium/datadog_checks/cilium/cilium.py
- cockroachdb/datadog_checks/cockroachdb/cockroachdb.py
- coredns/datadog_checks/coredns/coredns.py
- dotnetclr/datadog_checks/dotnetclr/dotnetclr.py
- envoy/datadog_checks/envoy/envoy.py
- exchange_server/datadog_checks/exchange_server/exchange_server.py
- gitlab/datadog_checks/gitlab/gitlab.py
- haproxy/datadog_checks/haproxy/check.py
- hyperv/datadog_checks/hyperv/hyperv.py
- kong/datadog_checks/kong/kong.py
- linkerd/datadog_checks/linkerd/linkerd.py
- openmetrics/datadog_checks/openmetrics/config_models/validators.py
- openmetrics/datadog_checks/openmetrics/openmetrics.py
- rabbitmq/datadog_checks/rabbitmq/check.py
- scylla/datadog_checks/scylla/scylla.py
- teamcity/datadog_checks/teamcity/check.py
- teamcity/datadog_checks/teamcity/teamcity_rest.py
- vault/datadog_checks/vault/vault.py
- win32_event_log/datadog_checks/win32_event_log/check.py
This PR focuses on simplifying logic that loads integration classes. We no longer need anything related to Python 2, so we're dropping it. No changelog since we officially dropped Python 2 support already, so this isn't worth a separate changelog entry.
> Remove Python2 logic when loading checks

- kafka/README.md
- kafka_consumer/README.md
Remove the note about DSM now that we display the product connection as a UI component in app so there isn't redundant info. See the example: https://app.datadoghq.com/marketplace/integration/kafka
See https://datadoghq.atlassian.net/browse/ECOS-1687
> update kafka readme

- citrix_hypervisor/datadog_checks/citrix_hypervisor/check.py
- citrix_hypervisor/tests/test_citrix_hypervisor.py
- citrix_hypervisor/tests/test_metadata.py
- datadog_checks_tests_helper/datadog_test_libs/win/pdh_mocks.py
- gearmand/datadog_checks/gearmand/gearmand.py
- network/datadog_checks/network/ethtool.py
- postgres/datadog_checks/postgres/statement_samples.py
After this all we have left is a more complicated `spark` case, then the base check and tooling (datadog_checks_dev).
> Remove last batch of easy 'six' dependencies

- kubernetes_cluster_autoscaler/README.md
The first link in readme was not changed.
> Fix link in readme for kubernetes cluster autscaler

- spark/tests/test_spark.py
This involves a small refactor of the assertion setup. Was easier to do it this way than search/replace.
Keeping this separate because it's not like the other changes related to six.
> Remove 'six' usage from spark test

- karpenter/CHANGELOG.md
- karpenter/changelog.d/18448.added
- karpenter/datadog_checks/karpenter/__about__.py
- requirements-agent-release.txt
Changelog ports from 7.58 karpenter releases
> [Release] Bumped karpenter version to 1.6.0

- .builders/images/linux-aarch64/Dockerfile
- .builders/images/linux-x86_64/Dockerfile
- .builders/images/macos-x86_64/builder_setup.sh
Bump OpenSSL version to 3.3.2
BARX-558
> Bump OpenSSL in dependency builders

- clickhouse/assets/configuration/spec.yaml
- clickhouse/changelog.d/18677.added
- clickhouse/datadog_checks/clickhouse/clickhouse.py
- clickhouse/datadog_checks/clickhouse/config_models/instance.py
- clickhouse/datadog_checks/clickhouse/data/conf.yaml.example
- clickhouse/tests/test_unit.py
This PR adds ability to pass a CA cert to Clickhouse 
> Add ability to pass a CA cert to Clickhouse

- vsphere/README.md
Adds note about property metrics to instruct users on how to collect these
> Add note about property metrics

- .ddev/config.toml
- .github/workflows/test-all.yml
- sqlserver/tests/compose/Dockerfile
- sqlserver/tests/compose/docker-compose.yaml
`mssql` container seeing fatal error on starting with ubuntu 22.04 runner follow kernel [update](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240915.1) on 9/15. This has caused sqlserver integration tests fail to connect to the test database. Change the test runner to ubuntu 20.04.
(i've tried updating mssql to 2017-latest, 2019-latest & 2022-latest but that doesn't work. i kept the image tag as it is for now even thought these image tags are old and we should probably update them)
Fix mssql container fatal error
```
E   Captured Output: sqlserver-1  | This program has encountered a fatal error and cannot continue running at Thu Sep 26 20:58:40 2024
E   sqlserver-1  | The following diagnostic information is available:
E   sqlserver-1  | 
E   sqlserver-1  | …
```
> run sqlserver tests on ubuntu 20.04

- datadog_checks_base/tests/base/utils/discovery/test_discovery.py
Add more unit tests for empty include lists in the Discovery class, while also increasing the specificity of the existing unit tests.
more documentation/test coverage to indicate that we expect an include list when using Discovery
maybe we can throw a configuration exception if this is the case?
> Add more unit tests for empty include lists in Discovery

- mongo/changelog.d/18750.added
- mongo/datadog_checks/mongo/mongo.py
- mongo/tests/test_integration.py
- mongo/tests/test_unit.py
Always emit `database_instance` metadata regardless of dbm status.
> [mongo] always emit database_instance

- postgres/assets/configuration/spec.yaml
- postgres/changelog.d/18726.added
- postgres/datadog_checks/postgres/config.py
- postgres/datadog_checks/postgres/config_models/instance.py
- postgres/datadog_checks/postgres/data/conf.yaml.example
This PR adds `keep_json_path` to obfuscator_options to allow users to control whether JSON paths following JSON operators in SQL statements should be obfuscated. By default, these paths are treated as literals and are obfuscated to ?.
For example, in the SQL statements
```SQL
-- Extracts JSON object field with the given key
SELECT data::jsonb -> 'name'
```
The JSON path `name` following the JSON operator -> would normally be obfuscated to `?`, resulting in:
```SQL
SELECT data::jsonb -> ?
```
With the `keep_json_path` option enabled, users can skip this obfuscation, preserving the original JSON path `name` in the query.
Related change: https://github.com/DataDog/datadog-agent/pull/29655
> [dbm] add keep_json_path to obfuscator_options

- mongo/changelog.d/18751.added
- mongo/datadog_checks/mongo/config.py
- mongo/datadog_checks/mongo/mongo.py
This PR adds tag `clustername` & `database_instance` to mongo service check tags.
> [mongo] include clustername & database_instance in service check tags

- sqlserver/assets/configuration/spec.yaml
- sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
Unhide SQL Server deadlocks collection config.
The agent and backend are ready. Frontend will be ready by the time the next agent version  is released.
The deadlocks collection remains disabled by default for now.
> Unhide SQL Server deadlocks collection config

- postgres/changelog.d/18762.fixed
- postgres/datadog_checks/postgres/statement_samples.py
Parses each row in `pg_stat_activity` individually.
Azure databases are inserting invalid UTF8 into the `pg_stat_activity` table. To avoid crashing we need to parse each row individually and skip rows with invalid UTF8.
> Parse each row of pg_stat_activity separately inside a try/catch

- datadog_checks_base/changelog.d/18758.added
- datadog_checks_base/datadog_checks/base/stubs/datadog_agent.py
- postgres/changelog.d/18758.added
- postgres/datadog_checks/postgres/metadata.py
- postgres/datadog_checks/postgres/postgres.py
- postgres/datadog_checks/postgres/statement_samples.py
* Adds cross-org telemetry metrics for Postgres integration.
* Adds stubs for the new `emit_agent_telemetry` method on `datadog_agent`.
We want to use the new cross-org telemetry system to gather data on overall performance of the Postgres integration. 
See [this PR](https://github.com/DataDog/datadog-agent/pull/29776) for adding the metrics to the whitelist for collection.
> Postgres cross-org telemetry

- sqlserver/changelog.d/18760.fixed
- sqlserver/datadog_checks/sqlserver/agent_history.py
- sqlserver/tests/test_agent_jobs.py
This PR adds an optimization to the sqlserver agent job query, which queries `msdb.dbo.sysjobhistory` for a list of completed jobs + job steps since the last collection time. 
We were seeing customer issues like [SDBM-1193](https://datadoghq.atlassian.net/browse/SDBM-1193) with query times getting up to 7-8 minutes on job history logs of lengths 40k or 50k rows. 
This is because the original query included a n^2 subquery to calculate the `completion_instance_id` of the job associated with each job step:
```
SELECT 
job_id,
.....
(
SELECT MIN(sjh2.instance_id)
FROM msdb.dbo.sysjobhistory AS sjh2
WHERE sjh2.job_id = sjh1.job_id
AND sjh2.step_id = 0
AND sjh2.instance_id >= sjh1.instance_id
) AS completion_instance_id,
....
```
i.e. for each row, we re-run this subquery to scan ahead for the …
> SDBM-1193 Sqlserver agent jobs: reduce querying time for large histories

- cisco_sdwan/README.md
Remove beta label from Cisco SD-WAN and changing to "in Preview" - not quite ready for GA
> Remove beta label from Cisco SD-WAN

- mysql/changelog.d/18785.fixed
- mysql/datadog_checks/mysql/mysql.py
Checks if binary logs are enabled before logging a warning about permissions.
If binlogs are disabled the `SHOW` will fail but it's not a permissions error, binlogs are just disabled.
> Fix incorrect binlog permissions errors

- postgres/changelog.d/18788.fixed
- postgres/datadog_checks/postgres/metadata.py
Wraps the attempt at schema collection in a try block.
If schema collection throws for any reason we want to still mark collection as complete so the next run will execute.
> Wrap schema collection attempt in try

- sqlserver/changelog.d/18760.fixed
- sqlserver/datadog_checks/sqlserver/agent_history.py
- sqlserver/tests/test_agent_jobs.py
* Update job history query
Backport #18760 to 7.58.x. 
This backported PR resolves a customer facing query efficiency issue and significantly reduced the SQLServer agent job history query efficiency (7 min execution time -> 1s). 
[SDBM-1193](https://datadoghq.atlassian.net/browse/SDBM-1193)
[SDBM-1193]: https://datadoghq.atlassian.net/browse/SDBM-1193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Backport 7.58.x] Sqlserver agent jobs: reduce querying time for large histories (#18760)

- .github/workflows/pr.yml
Adds "merge_group" as a trigger type for the "pr" workflow. 
The `PR test / check` status check is required for the `master` branch of this repo. In order to support Merge Queues, this check needs to support being triggered from the `merge_group` event. See GH docs:
* https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue?tool=webui
* https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
If Merge Queues are enabled and this required check isn't configured to be triggered, it'll time out, and the queued PR will be "dropped" off the queue. 
Since …
> [INTPLAT-182] Support merge group events in Workflow "Test"

- .github/workflows/pr.yml
Removes a comment that I've since realized isn't true. While the templates ARE all shared between integration repos, each repo has its own `on` clause. For example, here is a PR that enables the merge events in extras - https://github.com/DataDog/integrations-extras/pull/2503
The comment isn't actually valid, so I don't want to leave it around.
> Remove comment about merge events being for marketplace

- mongo/assets/configuration/spec.yaml
- mongo/datadog_checks/mongo/config_models/instance.py
- mongo/datadog_checks/mongo/data/conf.yaml.example
Fix typo
The proper spelling is `max_collections_per_database`, but some documentation (and implementation) used `max_collection_per_database`.
https://github.com/DataDog/integrations-core/blob/fcbaaa1cefe2363b2ac22f10a7ebe22cd2107ad3/mongo/CHANGELOG.md?plain=1#L61
I first found the configuration example and followed that but won't worked...
> fix(mongo) fix typo in configuration example and schema (`max_collection"s"_per_database`)

- spark/assets/configuration/spec.yaml
- spark/changelog.d/18791.added
- spark/datadog_checks/spark/config_models/defaults.py
- spark/datadog_checks/spark/config_models/instance.py
- spark/datadog_checks/spark/data/conf.yaml.example
- spark/datadog_checks/spark/spark.py
- spark/tests/test_spark.py
This adds an option to disable `stage_id` from being attached to `spark.job` metrics and adds an option to disable the collection of stage metrics as a whole.
> Add option to disable stage metrics and `stage_id` tags

- sqlserver/assets/configuration/spec.yaml
- sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
Remove the commend that deadlocks collection is supported only with ODBC driver from the config.
In the meantime, we support MSOLEDB, but I forgot to update the config file to reflect this.
> Remove the comment that deadlock is supported only with ODBC

- cilium/metadata.csv
Tiny formatting fix for the Cilium metric table in the documentation. Right now it is not rendered properly because of the corrupted first row (probably due to a bad copy-paste):
https://docs.datadoghq.com/integrations/cilium/?tab=host#data-collected
> Cilium: fix metric table

- .github/workflows/pr.yml
Skip the `test` job of the `pr.yml` github action workflow for `integrations-core` repo and Merge Queue trigger.
Lets us enable Github's Merge Queue for this repo without making developer experience worse.
> Skip test job for pull requests in merge queue if it's flaky

- postgres/assets/configuration/spec.yaml
- postgres/changelog.d/18807.fixed
- postgres/datadog_checks/postgres/config.py
- postgres/datadog_checks/postgres/config_models/defaults.py
- postgres/datadog_checks/postgres/data/conf.yaml.example
Changes the default postgres `ignore_databases` from `template%` to specific databases (`template0` and `template1`)
In some scenarios we can have databases that start with template that should not be ignored, this default tries to target `template0` and `template1` which should be ignored but it can also target databases that should not be ignored.
> Use specific databases for template on postgres ignore

- ddev/changelog.d/18845.added
- ddev/src/ddev/cli/validate/metadata_utils.py
add the bit family as valid units 
https://datadoghq.atlassian.net/wiki/spaces/GE/pages/2671673472/Splitting+bytes+families+disambiguation
already added to dogweb
> add bit family as valid units

- mongo/assets/configuration/spec.yaml
- mongo/changelog.d/18843.added
- mongo/datadog_checks/mongo/api.py
- mongo/datadog_checks/mongo/data/conf.yaml.example
This PR applies the `timeout` config option (defaults to 30s) to `timeoutMS` connection option. With `timeoutMS`, a client-side operation timeout is properly specified. Prior to the change, long running integration command will get a network timeout due to `socketTimeoutMS`, however the operation will still be running on the server side. By setting `timeoutMS`, it ensures the operation is properly ended when exceeds defined timeout.
> [mongo] Apply configured timeout to timeoutMS connection option

- .builders/images/linux-aarch64/Dockerfile
- .builders/images/linux-x86_64/Dockerfile
- .builders/images/windows-x86_64/Dockerfile
Removes Python 2 installation from all builders, as we're no longer building dependencies for Python 2.
> Remove Python 2 from builders

- tibco_ems/changelog.d/18840.added
- tibco_ems/datadog_checks/tibco_ems/constants.py
- tibco_ems/datadog_checks/tibco_ems/tibco_ems.py
- tibco_ems/tests/fixtures/show_all
- tibco_ems/tests/fixtures/show_server
This generalizes the unit format for Tibco size metrics.
> Fix unit parsing issue

- .github/workflows/pr-test.yml
- .github/workflows/pr.yml
This PR moves the "check if merge group event is the trigger" check to be a step below where it is now. GitHub docs state that they treat "skipped" checks as "success". I believe the reason this didn't work before was that the skip was happening at the top level and not at the specific `test / check` status check. The `test / check` is what the branch protection has set to be a "required check". 
Continue iterating so that we can enable Merge Queues in this repository. 
Github docs on "skipped == success" - https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/using-conditions-to-control-job-execution#overview
> [INTPLAT-356] Specifically avoid running 'test / check' on merge group events, which is the required status check

- network/changelog.d/18819.added
- network/datadog_checks/network/check_linux.py
This PR will add two new tags (mtu and speed) to any network device that supports that information out of /sys/class/net/<device>
If the data cannot be determined it is skipped (for example, the `lo` interface has no speed).
The following `system.net` metrics will receive the new tags:
```
bytes_rcvd
bytes_sent
packets_in.count
packets_in.drop
packets_in.error
packets_out.count
packets_out.drop
packets_out.error
```
It's currently not possible to build host network device dashboards grouped by speed, unless you manually define which interfaces are which speed (this can be different between OS flavors, or just different server configurations).
There is an existing metric named `system.net.iface.mtu` which is tagged by `iface`, but in my opinion `mtu` makes more sense to be in a tag, MTU …
> adding mtu and speed tags to interfaces that support it

- postgres/changelog.d/18866.fixed
- postgres/datadog_checks/postgres/statement_samples.py
Revert "Parse each row of pg_stat_activity separately inside a try/catch (#18762)"
#incident-31599
We see unexpected high warnings during fetchone (not unicode decode error). Reverting the change for now and investigate the cause.
> Revert "Parse each row of pg_stat_activity separately inside a try/catch (#18762)"

- cisco_aci/changelog.d/18842.added
- cisco_aci/datadog_checks/cisco_aci/models.py
- cisco_aci/datadog_checks/cisco_aci/ndm.py
- cisco_aci/tests/fixtures/metadata.py
Interfaces in Cisco ACI are uniquely identified by their `id` - for example: `eth1/1` for a leaf switch and `eth5/1` for a spine node. This does not correspond to the required `int` type that interface index is typed as. 
Previously, the denominator for the number (i.e. 1 from `5/1` or 25 from `1/25`) but this doesn't work for spine nodes which can have different numerators which would have overlap (`5/1` and `7/1` interface IDs would end up both being index 1 for the device, which would overwrite one another). 
We are now utilizing the `raw_id` and `raw_id_type` fields that were introduced with the Cisco Meraki integration. Tests to reference expectations can be seen [here](https://github.com/DataDog/dd-go/blob/6646f200ed4166e41cf83837d0930d098ba1418a/apps/network-devices-writer/payload/p …
> [NDM] [Cisco ACI] Utilize raw ID for interface metadata

- postgres/changelog.d/18870.fixed
- postgres/datadog_checks/postgres/metadata.py
- postgres/tests/test_metadata.py
This PR fixes `UnboundLocalError` caused by referencing local variable start_time before assigned. The error will fail the postgres schema collection but failed to reset `_is_schemas_collection_in_progress`. Consecutive schema collection will not run due to incorrect `_is_schemas_collection_in_progress` remains true. 
Fixing unexpected postgres schema collection interruption. https://datadoghq.atlassian.net/browse/SDBM-1258
> [postgres] Fix UnboundLocalError caused by referencing local variable start_time before assigned

- datadog_cluster_agent/changelog.d/18867.added
- datadog_cluster_agent/datadog_checks/datadog_cluster_agent/check.py
- datadog_cluster_agent/metadata.csv
- datadog_cluster_agent/tests/fixtures/metrics.txt
- datadog_cluster_agent/tests/test_datadog_cluster_agent.py
Adds telemetry for new Validating Admission Controller.
Maintain visibility of new feature status.
> [CONTP-382] Add Validation Webhook telemetry metrics

- mysql/changelog.d/18885.fixed
- mysql/datadog_checks/mysql/innodb_metrics.py
This PR fixes `mysql.innodb.mem_total` metric for MySQL version 5.7 and above. 
https://datadoghq.atlassian.net/browse/DBMON-4283
> [mysql] fix innodb mem total parsing for newer mysql versions

- sqlserver/assets/configuration/spec.yaml
- sqlserver/changelog.d/18875.added
- sqlserver/datadog_checks/sqlserver/config_models/defaults.py
- sqlserver/datadog_checks/sqlserver/config_models/instance.py
- sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
- sqlserver/datadog_checks/sqlserver/database_metrics/__init__.py
- sqlserver/datadog_checks/sqlserver/database_metrics/xe_session_metrics.py
- sqlserver/datadog_checks/sqlserver/sqlserver.py
- sqlserver/metadata.csv
- sqlserver/tests/test_database_metrics.py
Add SQL Server XE session monitoring.
Since XE powers deadlock monitoring, it's important to monitor the service.
We are monitoring:
- Whether the XE session is running.
- The number of missing events in the ring buffer’s XML representation, due to a known [SQL Server issue](https://techcommunity.microsoft.com/t5/sql-server-support-blog/you-may-not-see-the-data-you-expect-in-extended-event-ring/ba-p/315838).
> Extended events (XE) session monitoring

- cloudera/assets/configuration/spec.yaml
- cloudera/changelog.d/18886.added
- cloudera/datadog_checks/cloudera/api/factory.py
- cloudera/datadog_checks/cloudera/client/cm_client.py
- cloudera/datadog_checks/cloudera/config_models/defaults.py
- cloudera/datadog_checks/cloudera/config_models/instance.py
- cloudera/tests/test_unit_client.py
Add a config key option `pools_size` for the number of connection pools to cache before discarding the least recently used pool. Default value: 4
https://datadoghq.atlassian.net/browse/AGENT-12498
> [cloudera] Configure the number of connection pools to cache

- kube_apiserver_metrics/README.md
Support request:
[DOCS-9152](https://datadoghq.atlassian.net/browse/DOCS-9152)
[DOCS-9152]: https://datadoghq.atlassian.net/browse/DOCS-9152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-9152] adding more information to kube_api_server check

- datadog_checks_base/tests/base/utils/db/test_db_statements.py
Relax `MEMORY_USAGE_THRESHOLD` in test to account for slightly increased mem from tracing.
> relax MEMORY_USAGE_THRESHOLD in test to account for slightly increased mem from tracing

- sqlserver/changelog.d/18882.fixed
- sqlserver/datadog_checks/sqlserver/statements.py
Update sqlserver metric collection `row_key` to prevent overwriting metric information for two queries with the same query_plan_hash but part of two different stored procedures.
We noticed that while we separate queries by stored procedure names, the row_key used to aggregate metrics is using `query_plan_hash`. This value can be identical since it's a hash of the plan nodes specific to this query, which can be shared in two different stored procedures. Changing the row_key to use the procedure name should fix this edge case.
> Fix sqlserver metric collection row_key

- datadog_checks_dev/changelog.d/18914.fixed
- datadog_checks_dev/datadog_checks/dev/jmx.py
Add this metric (jvm.unloaded_classes) to the JVM_E2E_METRICS list we test against the jmx based metrics.
The metric was added [here](https://github.com/DataDog/jmxfetch/pull/540).
> Fix jmx based integrations test

- mongo/changelog.d/18844.fixed
- mongo/datadog_checks/mongo/dbm/utils.py
- mongo/tests/test_unit.py
This PR skips explain plan collection for mongo administrative aggregation pipeline, including `$collStats`, `$currentOp`, `$indexStats` and `$sample`.
> [mongo] skip explain administrative aggregation pipeline

- docusign/manifest.json
- mailchimp/manifest.json
Monitor name is manifest should not have app name again according to guideline https://docs.google.com/document/d/1q0ChqrEDNUVA3zA3ZP5p8MKCTWWAw9A-Gq_tnbsfaJQ/edit?pli=1&tab=t.0#heading=h.s0c5ovxeyzto
> Remove asset name in manifest monitor name

- ibm_db2/README.md
Fixes the issue where pip installation will fail stating that it would require "Microsoft C++ Build Tools". 
As per testing, on DD Agent 7.58.x / Python 3.12 / Windows 2016, I get the following results:
- pip install of  ibm_db == 3.1.4 / 3.2.0 / 3.2.1 / 3.2.2
```
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for ibm_db
Failed to build ibm_db
ERROR: Could not build wheels for ibm_db, which is required to install pyproject.toml-based projects
```
Note that I did get it installed after installing "Microsoft C++ Build Tools" but it was a bit of a hassle …
> Update dependency for Agent versions >= 7.58

- postgres/changelog.d/18938.fixed
- postgres/datadog_checks/postgres/statement_samples.py
This PR fixes the bug encountered in Azure PostgreSQL Flexible Server in the `backend_type` column of `pg_stat_activity`.
There is a bug on Microsoft's side where they send a non valid utf-8 string in that column, leading to decoding errors when trying to fetch this column. 
The workaround is to query that same column with `::bytea `suffix to convert the field into bytes then parsing `backend_type` manually. The bug still exists but now we just handle those error cases instead of failing on the whole query. 
https://datadoghq.atlassian.net/browse/SDBM-1169
https://datadoghq.atlassian.net/browse/SDBM-1197
#incident-31599
A couple of customers where seeing errors utilizing DBM with Azure PG Flexible Server when agent tries to query `backend_type` from `pg_stat_activity`. We previously …
> [postgres]  Fix unicode decode error from Azure PostgreSQL Flexible Server

- mongo/changelog.d/18953.fixed
- mongo/datadog_checks/mongo/dbm/operation_samples.py
- mongo/datadog_checks/mongo/dbm/slow_operations.py
- mongo/datadog_checks/mongo/dbm/utils.py
- mongo/tests/test_unit.py
This PR fixes a bug in parsing db name from namespace when namespace has no collection name, e.g. `admin.$cmd` vs. `admin`. This usually happens with database level administration command on earlier MongoDB version (version 5 or earlier). 
https://datadoghq.atlassian.net/browse/DBMON-4723
> [mongo] fix db name parsing when namespace has no collection

- mysql/changelog.d/18966.added
- mysql/datadog_checks/mysql/mysql.py
- postgres/changelog.d/18966.added
- postgres/datadog_checks/postgres/postgres.py
Adds `port` to database instance metadata for MySQL and Postgres.
For hosts with multiple instances port can be used to distinguish between them.
> Send port as part of database instance for MySQL and Postgres

- sqlserver/changelog.d/18940.fixed
- sqlserver/changelog.d/18958.fixed
- sqlserver/datadog_checks/sqlserver/activity.py
Fix missing appended SQL comments.
As an optimization, the agent selects only the first 500 characters of a query text. Consequently, the appended SQL comments are lost for longer queries. Now, we select the last 200 characters of longer queries to parse appended comments.
> Fix missing appended SQL comments

- .github/workflows/dismiss-stale-reviews.yaml
This yaml file defines a workflow that uses balvajs/dismiss-stale-reviews@v3 GitHub action to dismiss stale reviews based on file ownerships (smarter compared to default GitHub behavior). For example:
1. User1 makes a PR that changes file-a, owned by group-a, and file-b, owned by group-b.
2. The PR was approved by both group-a and group-b.
3. User1 updated file-b.
4a. (GitHub default behavior) Approvals from both group-a and group-b are dismissed.
4b. (New behavior) Group-b's approval is dismissed. Group-a's approval is still valid.
See [here](https://github.com/DataDog/crawler-sdk/pull/205) for a real example.
This is already added to [integrations-internal-core](https://github.com/DataDog/integrations-internal-core/blob/main/.github/workflows/dismiss-stale-reviews.yaml) for a week and …
> INTPLAT-231: add yaml for dismiss-stale-reviews

- datadog_cluster_agent/assets/dashboards/datadog_cluster_agent_overview.json
Updates the Datadog Cluster Agent - Overview dashboard. 
* Adds grouping to widgets on related widgets [CONTP-429]
* Adds new validation_attempts metric widget [CONTP-382]
1. Make easier for user to view the DCA Dashboard in different screen sizes by using groups to maintain the display/order of widgets together.
2. Include newly added telemetry into the dashboard to make it easier to users to debug validation webhook
Note: the two added widgets were at the bottom called Successful validation_attempts and Failed validation_attempts
[CONTP-429]: https://datadoghq.atlassian.net/browse/CONTP-429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CONTP-382]: https://datadoghq.atlassian.net/browse/CONTP-382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
> [CONTP-382] Updating dashboards to use grouping and validation widget

- mongo/changelog.d/18953.fixed
- mongo/datadog_checks/mongo/dbm/operation_samples.py
- mongo/datadog_checks/mongo/dbm/slow_operations.py
- mongo/datadog_checks/mongo/dbm/utils.py
- mongo/tests/test_unit.py
> [Backport/7.60.x] [mongo] fix db name parsing when namespace has no collection

- ddev/changelog.d/18993.fixed
- ddev/src/ddev/cli/meta/scripts/scripts/serve.py
`serve.py` can only work as part of the `ddev meta scripts serve-openmetrics-payload` command.
You can call `serve.py` directly to serve openmetrics payloads.
Some integrations, for instance `vllm` don't work with the `serve-openmetrics-payload` command. They require more than just the OM HTTP endpoint, they scrape some endpoints for metadata.
I found that I needed to hack something together for that case:
1. invoke `serve.py` directly to serve the OM payloads
2. modify the `vllm` source to skip crawling the metadata endpoint
3. run `ddev env start vllm...` and point the agent to the server exposed by `serve.py`
> Don't hardcode location of payload file in serving script.

- openai/manifest.json
We're remove the now-unused Product::LLM Observability classifier tag from the OpenAI integration since it is no longer used. 
Avoid confusion and potential side effects by removing unused classifier tag.
> [ECOS] Remove Product classifier tag from OpenAI

- sqlserver/changelog.d/19014.fixed
- sqlserver/datadog_checks/sqlserver/sqlserver.py
- sqlserver/tests/test_integration.py
This PR fixes the `azure_sql_server_database` internal resource aliasing. Previously the `azure_sql_server_database` resource is set to the resolved hostname, which can be overwritten to any user preferred hostname. The `azure_sql_server_database` resource should be independent from the resolved database hostname, and always follow the format of `{fully_qualified_doman_name}/{database}`. This ensures the correct resource aliasing in unified instance tagging. 
https://datadoghq.atlassian.net/browse/DBMON-4756
> [sqlserver] fix azure_sql_server_database resource

- sqlserver/assets/configuration/spec.yaml
- sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
Unhide the `schemas_collection` parameter as it's now available in the frontend.
[Link to feature release](https://datadoghq.atlassian.net/wiki/spaces/DM/pages/4368302348/2024-11-11+-+SQLServer+Host+Detail+Schema+Tab)
We want this option exposed to customers now that there's a frontend for it.
> Unhide schemas_collection and write agent version

- sqlserver/assets/configuration/spec.yaml
- sqlserver/changelog.d/19032.added
- sqlserver/datadog_checks/sqlserver/config.py
- sqlserver/datadog_checks/sqlserver/config_models/defaults.py
- sqlserver/datadog_checks/sqlserver/config_models/instance.py
- sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
- sqlserver/datadog_checks/sqlserver/sqlserver.py
- sqlserver/tests/test_integration.py
- sqlserver/tests/test_statements.py
This PR adds a new config option `azure.aggregate_sql_databases` to group multiple azure sql databases into one logical SQL Server database host. 
Prior to this change, Azure SQL databases are monitored and reported as independent database instances due to the it's network isolation between databases. With the new config, user has the option to continue monitor Azure SQL databases independently but have them aggregated into one single database host in DBM. 
This is an opted in option and not enabled by default. 
https://datadoghq.atlassian.net/browse/DBMON-4762
> [sqlserver] Add option to aggregate azure sql database into one db host

- .github/workflows/pr-test.yml
- rabbitmq/datadog_checks/rabbitmq/openmetrics/check.py
All in the title.
validated with this run: https://github.com/DataDog/integrations-core/actions/runs/11854331621/job/33036295900?pr=19066
Simplest way to stop setting up Python 2 in integrations core.
I suspect the `compute_matrix.py` script may need a facelift, but I'll deal with that separately.
> Stop setting up Python2 for PRs in ints-core repo

- postgres/assets/configuration/spec.yaml
- postgres/changelog.d/19061.fixed
- postgres/datadog_checks/postgres/config.py
- postgres/datadog_checks/postgres/config_models/defaults.py
- postgres/datadog_checks/postgres/data/conf.yaml.example
- postgres/datadog_checks/postgres/discovery.py
Similar to `cloudsqladmin`, this PR adds `alloydbadmin` & `alloydbmetadata` to default list of databases to exclude from autodiscovery and databases to ignore to prevent failures on Postgres on GCP AlloyDB.
https://datadoghq.atlassian.net/browse/DBMON-4770
https://github.com/DataDog/integrations-core/issues/18783
> [postgres] add alloydbadmin & alloydbmetadata to default exclusion list

- ntp/README.md
Adding a tab for containerized config: https://datadoghq.atlassian.net/browse/DOCS-9517
> Add tab for NTP containerized config

- .ddev/ci/scripts/traces.py
- .github/workflows/master.yml
- .github/workflows/submit-traces.yml
@vivek-datadog noticed that the "Upload Traces" workflow in CI was taking half to two-thirds of the total test time, on master test runs. Optimizing that part is definitely a low-hanging fruit!
This PR speeds up the "trace upload" workflow so that it runs in 2 minutes instead of 50 minutes, for the master test runs. The total test time was 1.5 - 2 hours before this change.
A large amount of logging was slowing down the GitHub actions job. 
The agent log level is now set to "warn" instead of "trace". Also, only the test name and the HTTP status code are now printed, instead of the full response from the Agent:
```
/// Replaying: Appgate SDP
200 OK
200 OK
/// Replaying: ArangoDB
200 OK
/// Replaying: Argo Rollouts
200 OK
/// Replaying: Argo Workflows
200 OK
/// Replaying: ArgoCD
200 OK
/// …
```
> Speed Up Trace Uploads in GHA

- mongo/changelog.d/19080.fixed
- mongo/datadog_checks/mongo/dbm/operation_samples.py
- mongo/tests/test_dbm_operation_samples.py
Fixes a bug that caused the MongoDB DBM operation samples collection to crash when a node is in recovering mode.
Previously, the DBM operation samples collection could crash with a `NotPrimaryError` if a node entered recovering mode. This situation often occurs when a MongoDB node is disconnected from the replica set for an extended period and is catching up on replication after rejoining the set. This PR ensures the integration can gracefully handle nodes in recovery, preventing unexpected crashes.
> [mongo] gracefully fail on operation samples colleciton when node is in recovering mode

- nvidia_nim/README.md
- nvidia_nim/assets/configuration/spec.yaml
- nvidia_nim/assets/dashboards/nvidia_nim_overview.json
- nvidia_nim/assets/monitors/latency.json
- nvidia_nim/assets/service_checks.json
- nvidia_nim/datadog_checks/nvidia_nim/check.py
- nvidia_nim/datadog_checks/nvidia_nim/data/conf.yaml.example
- nvidia_nim/datadog_checks/nvidia_nim/metrics.py
- nvidia_nim/manifest.json
> nvidia dash

- vsphere/assets/configuration/spec.yaml
- vsphere/datadog_checks/vsphere/data/conf.yaml.example
The vSAN Performance Service needs to be enabled to collect vSAN Performance metrics.
> Updating vSAN documentation

- .github/workflows/test-results-master.yml
- .github/workflows/test-results-pr.yml
Add permissions for the [EnricoMi/publish-unit-test-result-action@v2](https://github.com/EnricoMi/publish-unit-test-result-action) and the [emibcn/badge-action@v2.0.3 actions](https://github.com/emibcn/badge-action). They will be needed when we set default workflow permissions to *read-only* for the repo.
For the GitHub Action to Publish Test Results, the required permissions are documented.
For for Badge action, I ran an [experiment](https://github.com/nubtron/badge-action-experiment/actions/runs/11931462935/job/33254376136) to see which permissions are needed.
> Add permissions to the test-results-master and test-results-pr workflows in GitHub Actions

- .builders/images/linux-aarch64/build_script.sh
- .builders/images/linux-x86_64/build_script.sh
- .builders/images/macos-x86_64/extra_build.sh
- .ddev/ci/scripts/kafka_consumer/linux/32_install_kerberos.sh
- .ddev/config.toml
- agent_requirements.in
- kafka_consumer/changelog.d/19099.security
- kafka_consumer/hatch.toml
- kafka_consumer/pyproject.toml
This updates `confluent-kafka` builders and dependency to address this [CVE ](https://nvd.nist.gov/vuln/detail/CVE-2024-7264)
https://github.com/confluentinc/librdkafka/releases/tag/v2.6.1
> -  Upgrade Linux dependencies: OpenSSL 3.0.15, CURL 8.10.1 (https://github.com/confluentinc/librdkafka/pull/4875).
> - Upgrade Windows dependencies: MSVC runtime to 14.40.338160.0,
zstd 1.5.6, zlib 1.3.1, OpenSSL 3.3.2, CURL 8.10.1 (https://github.com/confluentinc/librdkafka/pull/4872).
> Bump confluent-kafka to 2.6.1 to address CVE

- mongo/assets/configuration/spec.yaml
- mongo/changelog.d/19098.added
- mongo/datadog_checks/mongo/collectors/base.py
- mongo/datadog_checks/mongo/collectors/coll_stats.py
- mongo/datadog_checks/mongo/collectors/index_stats.py
- mongo/datadog_checks/mongo/collectors/sharded_data_distribution_stats.py
- mongo/datadog_checks/mongo/config.py
- mongo/datadog_checks/mongo/config_models/instance.py
- mongo/datadog_checks/mongo/data/conf.yaml.example
- mongo/datadog_checks/mongo/mongo.py
- mongo/tests/test_integration.py
- mongo/tests/test_unit_config.py
- mongo/tests/utils.py
This PR introduces a new configuration option, `metrics_collection_interval`, which allows users to customize the collection interval for collection statistics, index statistics, and sharded data distribution metrics.
The `$collStats`, `$indexStats`, and `$shardedDataDistribution` aggregation pipelines can be resource-intensive for large databases. Allowing users to adjust the collection frequency provides flexibility to minimize the integration's performance impact while still gathering important metrics.
> [mongo] allow customizable collection interval for collection and sharded data distribution metrics

- sqlserver/changelog.d/19110.fixed
- sqlserver/datadog_checks/sqlserver/queries.py
- sqlserver/datadog_checks/sqlserver/schemas.py
Fixes the query for sqlserver versions <= 2016
Changes:
> [DBM] - Use alternative query for sqlserver 2016 and older

- .github/workflows/master.yml
- .github/workflows/pr-quick-check.yml
This PR adds a couple of missing permissions:
* Permissions from ./.github/workflows/test-results-master.yml in master.yml, because parent job needs to specify the permissions of a child job. This fixes `The workflow is not valid. .github/workflows/master.yml` in the master CI check.
* Read permissions in pr-quick-check, because manually specifying a permission sets all others to 'none', including read ones.
> Fix missing permissions in GitHub Actions

- .gitignore
Git no longer ignores `.zip` files.
We have some test data committed that's in zipfiles. For instance, `datadog_checks_downloader/tests/data`. I have no idea how it made it past the ignore file [when it got added at first](https://github.com/DataDog/integrations-core/pull/12584). Now I need to add another zip file to that folder and I'm blocked by `.gitignore`.
I can't find why zipfiles are being ignored. The PR that introduces this together with an integration gives no explanation.
Just to be sure I ran some `redisdb` tests and those didn't add any stray zipfiles.
> Stop git from ignoring zip files

- .github/workflows/pr-check.yml
- .github/workflows/pr-quick-check.yml
This PR sets permissions explicitly for pr-check.yml so that they match the ones for pr-quick-check.yml. It fixes the "The workflow is not valid. .github/workflows/pr-check.yml " error in the "Check PR" action.
> Fix permissions in the "Check PR" action.

- mongo/assets/configuration/spec.yaml
- mongo/datadog_checks/mongo/data/conf.yaml.example
Removes "Private Beta" label from DBM Mongo conf setting since Mongo is GA since October 2024
Customer question
> Remove Private Beta label from Mongo conf

- snmp/datadog_checks/snmp/data/default_profiles/citrix-netscaler-sdx.yaml
Fix a typo in one of our out-of-the-box SNMP profiles.
Metric tags using the old syntax (where OID and name are top-level instead part of Symbol) don't support the `format` specifier, and it gets silently ignored by the YAML loader.
From a user perspective, the only thing that will change is that anyone using citrix netscaler SDX devices will suddenly see a few tags that are IP addresses be formatted as such instead of as raw bytes.
https://github.com/DataDog/datadog-agent/pull/31054 revealed this issue.
> [NDMII-3168] Fix Citrix Profile

- sqlserver/changelog.d/19139.fixed
- sqlserver/datadog_checks/sqlserver/deadlocks.py
- sqlserver/datadog_checks/sqlserver/queries.py
Fix duplicate deadlock events.
The deadlock query compares the UTC deadlock timestamp with the local time, which can cause duplicate events in non-UTC databases
> Fix duplicate deadlock events

- sonarqube/changelog.d/19145.added
- sonarqube/changelog.d/19149.added
- sonarqube/datadog_checks/sonarqube/check.py
- sonarqube/datadog_checks/sonarqube/constants.py
This PR sets the max number of pages our Sonarqube integration can query through
It's not possible to browse more than 10,000 results. This limitation to 10000 results applies to web services that are backed by ElasticSearch index. Searching more than this results in the below error:
```
"message": "400 Client Error:  for url: http://[2600:1f18:1bbd:6503:f9cf::3]:9000/api/components/search?qualifiers=TRK\u0026p=101",
```
> Add `MAX_PAGES` to Sonarqube API request

- network_path/manifest.json
Adds the Windows support tag to go out with agent 7.61.
Windows support begins in agent 7.61
> [Network Path] Add Windows support tag for 7.61

- kubevirt_handler/changelog.d/19156.fixed
- kubevirt_handler/pyproject.toml
- nvidia_nim/changelog.d/19156.fixed
- nvidia_nim/pyproject.toml
- slurm/changelog.d/19156.fixed
- slurm/pyproject.toml
We also bump the base package in `kubevirt_handler` to use a test function.
Tested with [this pipeline](https://github.com/DataDog/integrations-core/actions/runs/12065933428).
> Bump base package dependency to get fixed pyyaml

- octopus_deploy/datadog_checks/octopus_deploy/check.py
- octopus_deploy/tests/constants.py
- octopus_deploy/tests/fixtures/GET/api/Spaces-1/events/from=2024-09-23 14:45:00.123000+00:00/to=2024-09-23 14:45:00.123000+00:00/eventCategories=MachineHealthy,MachineUnhealthy,MachineUnavailable,CertificateExpired,DeploymentFailed,DeploymentSucceeded,LoginFailed,MachineAdded,MachineDeleted/response.json
- octopus_deploy/tests/fixtures/GET/api/Spaces-1/events/from=2024-09-23 14:45:00.123000+00:00/to=2024-09-23 14:45:15.123000+00:00/eventCategories=MachineHealthy,MachineUnhealthy,MachineUnavailable,CertificateExpired,DeploymentFailed,DeploymentSucceeded,LoginFailed,MachineAdded,MachineDeleted/response.json
- octopus_deploy/tests/test_unit.py
Adds support for audit events in octopus integration.
currently, we only support a few event categories. Later we may add support for customizing what event categories to emit and add more tags to the events.
> [PLINT-485] Add support for events 

- octopus_deploy/assets/configuration/spec.yaml
- octopus_deploy/datadog_checks/octopus_deploy/check.py
- octopus_deploy/datadog_checks/octopus_deploy/data/conf.yaml.example
- octopus_deploy/tests/constants.py
- octopus_deploy/tests/docker/Caddyfile
- octopus_deploy/tests/fixtures/GET/api/Spaces-1/tasks/ServerTasks-1844/details/response.json
- octopus_deploy/tests/fixtures/GET/api/Spaces-1/tasks/ServerTasks-1845/details/response.json
- octopus_deploy/tests/fixtures/GET/api/Spaces-1/tasks/ServerTasks-1846/details/response.json
- octopus_deploy/tests/fixtures/GET/api/Spaces-1/tasks/ServerTasks-1847/details/response.json
- octopus_deploy/tests/test_e2e.py
- octopus_deploy/tests/test_unit.py
Uses the new logs in integrations feature to support deployment logs in the octopus integration. Additionally adds the server_node tag to deployment metrics and logs.
Users may want a way to pull in logs from their deployments for debugging and to correlate with metrics about each deployment.
Open questions:
Should we attempt to handle multi-line logs now?
> [PLINT-484]  Add support for deployment logs

- sqlserver/changelog.d/19189.changed
- sqlserver/datadog_checks/sqlserver/database_metrics/xe_session_metrics.py
- sqlserver/datadog_checks/sqlserver/deadlocks.py
- sqlserver/datadog_checks/sqlserver/queries.py
- sqlserver/tests/test_deadlocks.py
If the `datadog` XE session isn't created, the agent will retrieve deadlocks from `system_health/event_file`.
Some customers can't or prefer not to create dedicated XE sessions. We use event_file over ring_buffer to avoid truncating recent events, but `datadog` XE session remains the preferred option for better performance.
> Fall back to system_health/event_file when querying deadlocks

- kafka_consumer/datadog_checks/kafka_consumer/client.py
- kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
- kafka_consumer/tests/test_unit.py
**This is a big PR, so I split it into meaningful commits!**
At the same time, the commits are incremental steps to the final result. So it makes sense to review them all in sequence as a *story* in a way.
We need to expand the test coverage for this integration in response to support cases (and to prevent new ones).
Unit tests are better suited for this, but they work best with as little as possible mocking.
The existing code structure encouraged more extensive mocking thus reducing coverage that we could achieve with unit tests.
**FUN FACT: our branch coverage by unit tests went from 66% to 92%. Without adding any new unit tests!**
> Refactor: move logic out of client for easier unit testing

- amazon_msk/CHANGELOG.md
- cisco_aci/CHANGELOG.md
- datadog_checks_base/CHANGELOG.md
- http_check/CHANGELOG.md
- kafka_consumer/CHANGELOG.md
- mysql/CHANGELOG.md
- openstack_controller/CHANGELOG.md
- postgres/CHANGELOG.md
- redisdb/CHANGELOG.md
- snmp/CHANGELOG.md
- snowflake/CHANGELOG.md
- tls/CHANGELOG.md
- vertica/CHANGELOG.md
When merging https://github.com/DataDog/integrations-core/pull/18187 we forgot to check that the changelog files were valid.
The bot had pointed them to the wrong PR.
I was looking at an affected changelog for a support case and got very confused when I clicked on the link that's in the Changelog.
> Fix PR number in changelog entries

- mysql/assets/configuration/spec.yaml
- mysql/datadog_checks/mysql/data/conf.yaml.example
- postgres/assets/configuration/spec.yaml
- postgres/datadog_checks/postgres/data/conf.yaml.example
- sqlserver/assets/configuration/spec.yaml
- sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
Adds a note to the `collect_commands` query obfuscator options stating that this option must remain `true` in order for proper propagation of APM traces into DBM query sample collection. If this option is false then we won't extract and submit comments to be processed on the backend leading to incomplete APM <> DBM linking
The default option is already to have this enabled. We want to documentation to be clear that disabling this will affect APM linking
> Add note about required obfuscator option for APM linking in DBM integrations

- envoy/tests/docker/api_v3/go.mod
Attempt to fix envoy flakiness by bumping the required Go version modules
> Envoy flaky CI fix attempt

- mysql/changelog.d/19121.added
- mysql/datadog_checks/mysql/const.py
- mysql/metadata.csv
- mysql/tests/variables.py
Add new metrics.
> The number of digest instances that could not be instrumented in the [events_statements_summary_by_digest](https://dev.mysql.com/doc/refman/8.4/en/performance-schema-statement-summary-tables.html) table. This can be nonzero if the value of [performance_schema_digests_size](https://dev.mysql.com/doc/refman/8.4/en/performance-schema-system-variables.html#sysvar_performance_schema_digests_size) is too small.
https://dev.mysql.com/doc/refman/8.4/en/performance-schema-status-variables.html#statvar_Performance_schema_digest_lost
[Advanced Configuration for MySQL Database Monitoring](https://github.com/DataDog/documentation/blob/a8d2b8b22c173059c018e09076e8ff1326277f02/content/en/database_monitoring/setup_mysql/advanced_configuration.md?plain=1#L17-L21) in our doc says ...
> …
> Add `mysql.performance.performance_schema_digest_lost`

- datadog_checks_downloader/tests/test_downloader.py
One more to be excluded
Should be the last one that needs to be excluded. The one remaining integration that is causing issue is zeek since that a log only integration released by a revoked key. I think we have to re-release zeek or also add that to an exlude list for another reason.
> Agent 5 only datadog-ntp needs to be excluded

- cisco_aci/assets/dashboards/cisco_aci_dashboard.json
https://datadoghq.atlassian.net/browse/NDINT-255
`integration sync staging --branch zoe/aci-dashboard cisco-aci`
^ i guess this is deprecated and actually it's part of C/I now?
https://datadoghq.atlassian.net/wiki/spaces/DB/pages/3458924568/Synchronize+an+out-of-the-box+Dashboard+with+APW
> [NDM] [Cisco ACI] Update OOTB dashboard

- datadog_cluster_agent/changelog.d/19229.added
- datadog_cluster_agent/datadog_checks/datadog_cluster_agent/check.py
Two metrics are added
'datadog.cluster_agent.autoscaling_workload_store_load_entities' for tracking the total number of entities in autoscaling workload store
'datadog.cluster_agent.autoscaling_workload_store_job_queue_length' for tracking the pending job queue len
> [datadog_cluster_agent] Add local failover workload store metric

- vsphere/README.md
- Links vSphere billing docs to integration docs
- additionally makes the TKG section a heading since it doesn't belong under "Troubleshooting" or "Billing"
Make it easier to find this information
> Link vSphere billing docs to integration docs

- snmp/assets/dashboards/interface_performance.json
Before 
Rules are treated in order, because 1 <= 2 then it shows as yellow
> Fix interface perf dashboard colors

- avi_vantage/tests/test_avi_vantage.py
Explicitly mark unit and integration tests for the avi vantage integration.
There's only one of each test, it would be overkill to create 2 separate files to take advantage of our implicit marking mechanism.
Drive-by. Was looking at the integration and noticed this.
> Mark unit and integration tests for avi vantage integration

- mongo/changelog.d/19244.fixed
- mongo/datadog_checks/mongo/collectors/base.py
- mongo/datadog_checks/mongo/collectors/coll_stats.py
- mongo/datadog_checks/mongo/collectors/index_stats.py
- mongo/tests/conftest.py
- mongo/tests/fixtures/$collStats-oplog.rs
- mongo/tests/fixtures/list_collection_names-local
- mongo/tests/mocked_api.py
- mongo/tests/results/metrics-collection-autodiscover.json
This PR updates the behavior of our collection and index stats gathering to skip unauthorized local database collections, specifically `system.replset`, `replset.election`, and `replset.minvalid`. These collections are excluded because the `$collStats` and `$indexStats` commands are not authorized for users with the `clusterMonitor `or `read` roles unless explicitly granted admin-level permissions.
https://datadoghq.atlassian.net/browse/DBMON-4827
The `$collStats` and `$indexStats` commands fail on certain local database collections (`system.replset, replset.election, and replset.minvalid`) when executed by users with the clusterMonitor or read roles. By skipping these collections, we avoid unnecessary errors and improve compatibility without requiring additional admin-level permissions …
> [mongo] skip collStats and indexStats on unauthorized local db collections

- vsphere/assets/configuration/spec.yaml
- vsphere/datadog_checks/vsphere/config.py
- vsphere/datadog_checks/vsphere/data/conf.yaml.example
- vsphere/tests/test_event.py
The include_events config option requires specifying "excluded messages" (i.e. not pulling events with the specified messages). We want to allow customers to not have to specify the excluded message, and just pull in all events of that event type.
> Making the excluded_messages field optional

- ddev/changelog.d/19252.added
- ddev/src/ddev/cli/validate/metadata_utils.py
[GXP-2329 
](https://datadoghq.atlassian.net/browse/GXP-2329)
add units for bytes and bit which funnel into separate bytes families 
https://datadoghq.atlassian.net/wiki/spaces/GE/pages/2671673472/Splitting+bytes+families+disambiguation
> add family specific byte units

- sqlserver/hatch.toml
We removed equivalent envvar setting in the agent. While investigating I saw this and thought we can remove it too.
> Remove unused distutils-related envvar

- slurm/manifest.json
Agent 7.60 came out. So we can make these docs available.
> mark slurm docs as available

- .builders/deps/build_dependencies.txt
- .builders/images/windows-x86_64/Dockerfile
- .builders/images/windows-x86_64/build_script.ps1
- .builders/images/windows-x86_64/update_librdkafka_manifest.py
- .builders/scripts/repair_wheels.py
- It adds a check during the repair step to find copies of dynamically linked versions of OpenSSL 3, for Windows and Linux.
- To make that check pass on Windows, this also implements the build of confluent-kafka-python and all its dependency chain, allowing us to choose the OpenSSL version (retrieved and built via vcpkg).
macOS is currently left out because that rises questions about psycopg2-binary, which would need to be addressed. Since this is already useful without that, that is left for future work (that may require discussion among a few teams to fully resolve).
[BARX-669](https://datadoghq.atlassian.net/browse/BARX-669)
[BARX-669]: https://datadoghq.atlassian.net/browse/BARX-669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Implement logic to catch externally built OpenSSL copies

- .builders/deps/build_dependencies.txt
Removes build dependencies for Python 2, as they are not needed.
Cleanup.
> Drop python2 requirements for deps builders

- postgres/datadog_checks/postgres/statement_samples.py
This PR adds a debug log when a query from activity sampling is truncated due to exceeding `track_activity_query_size`.
> [postgres] debug log when query is truncated

- airflow/assets/configuration/spec.yaml
- airflow/changelog.d/19278.added
- airflow/datadog_checks/airflow/airflow.py
- airflow/datadog_checks/airflow/config_models/defaults.py
- airflow/datadog_checks/airflow/config_models/instance.py
- airflow/datadog_checks/airflow/data/conf.yaml.example
- airflow/tests/test_unit.py
This PR uses the `start_date` instead of `execution_date` for ongoing duration metrics
> Use `start_date` instead of `execution_date` for ongoing duration metrics

- airflow/README.md
Fix typo of duplicate metric
I updated my mapping by copying from the airflow integration page, and noticed this metric disappeared
> Fix typo in airflow dogstatsd mapping

- postgres/changelog.d/19271.fixed
- postgres/datadog_checks/postgres/statement_samples.py
Fixes the logic for collecting query activity by:
1. Always collecting the `now` timestamp.
2. Checking for collection once, rather than in two places.
We should always collect `now` since it's used for checking the in-flight duration of requests. Missing this field was exacerbated by testing for if this collection cycle should submit activity events in two places. If the first test failed, fields would be missing from the query, but in the time between that execution and the next one the elapsed time could change and incomplete data would be submitted.
> Fix check for Postgres collect query activity

- kubeflow/README.md
- nvidia_nim/README.md
- tibco_ems/README.md
It's confusing to say we don't submit service checks when we clearly do.
It's also confusing to point to the service checks JSON when we don't submit any service checks.
> Clarify about service checks

- snmp/tests/test_e2e_core_metadata.py
We now pass the `integration` field in topology links, this PR updates the tests to reflect this.
> [SNMP] Update topology link metadata tests

- datadog_checks_base/changelog.d/19309.added
- datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/metrics.py
> Use `time_elapsed` metric type for process start time and last GC time metrics

- tomcat/manifest.json
This PR adds an additional tomcat process signature that can be used for integration auto-detection.
The current signature was not exhaustive enough as some customers were not seeing their Tomcat processes properly be detected.
> Add additional tomcat process signature

- postgres/changelog.d/19351.fixed
- postgres/datadog_checks/postgres/relationsmanager.py
- postgres/tests/test_relations.py
This PR resolves an issue where duplicate rows were returned for a single table in `QUERY_PG_CLASS`. The duplication occurred due to multiple locks (e.g., `AccessShareLock`, `RowShareLock`) being present for the same table in the `pg_locks` table during a LEFT JOIN operation. As a result, metrics like `postgresql.rows_inserted` (rate type) were submitted multiple times with identical values, causing rate calculations to incorrectly drop to zero. The fix ensures that each table is represented only once by deduplicating locks in the query, preventing incorrect metric submission.
https://datadoghq.atlassian.net/browse/SDBM-1298
> [postgres] Fix duplicated rows returned from QUERY_PG_CLASS 

- istio/README.md
Adds annotations v2 code sample for Istio integration. 
This was a request that came in on the Docs Team board.
> Add Annotations v2 for control plane configuration

- .builders/images/windows-x86_64/Dockerfile
- .builders/images/windows-x86_64/build_script.ps1
This PR adds the ability to specify the version of CURL used when building `librdkafka`/`confluent-kafka` on Windows
It makes sense to also build CURL since there are CVE's that come up related it and waiting on a vendor fix is just as tedious as waiting for a vendor fix for OpenSSL.
> Specify curl version when building confluent-kafka-python on Windows

- datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/base.py
- datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/scraper.py
- datadog_checks_base/tests/base/checks/logs/crawler/test_base.py
- datadog_checks_base/tests/base/checks/openmetrics/test_v2/test_info.py
* Adds support for `target_info` metric type
* Adds tests to ensure tags are added to metrics
> Utx only/openmetric target info 2

- hudi/tests/conftest.py
Hudi occasionally fails in master because the connection to apache archive times out. Some examples:
- https://github.com/DataDog/integrations-core/actions/runs/12712182319/job/35437303130#step:16:187
- https://github.com/DataDog/integrations-core/actions/runs/12712182319/job/35437303130#step:16:187
We hope that by waiting longer and retrying more we can make the test more robust.
> More attempts and wait to set up docker-compose

- datadog_checks_base/CHANGELOG.md
1. We didn't release a new version of the base check in Agent 7.61.0.
2. We had the 7.58.0 annotation on the wrong release.
Correct changelog doesn't confuse our automation.
> Fix agent release annotations in changelog

- .gitlab/build_agent.yaml
Save some $$ for the agent build folks :)
> Don't trigger agent build for GitHub MergeQueue branches

- .builders/images/linux-aarch64/build_script.sh
- .builders/images/linux-x86_64/build_script.sh
- .builders/images/macos-x86_64/extra_build.sh
- .builders/images/windows-x86_64/build_script.ps1
- .ddev/ci/scripts/kafka_consumer/linux/32_install_kerberos.sh
- .ddev/config.toml
- agent_requirements.in
- kafka_consumer/changelog.d/19370.added
- kafka_consumer/hatch.toml
- kafka_consumer/pyproject.toml
The license metadata was fixed in version 2.8.0 of `confluent-kafka-python`. This PR removes the override so we validate from PyPI.
https://github.com/confluentinc/confluent-kafka-python/issues/1857
> Update confluent-kafka-python to fix license metadata

- .builders/images/linux-aarch64/Dockerfile
- .builders/images/linux-x86_64/Dockerfile
This PR fixes `integrations-core` builder PYTHON_VERSION warnings
```
1 warning found (use docker --debug to expand):
- UndefinedVar: Usage of undefined variable '$PYTHON_VERSION' (did you mean $PYTHON3_VERSION?) (line 50)
```
https://github.com/DataDog/integrations-core/actions/runs/12716427655/job/35450751933?pr=19372#step:10:26669
> Fix `integrations-core` builder `$PYTHON_VERSION` warnings

- amazon_msk/changelog.d/19376.added
- amazon_msk/datadog_checks/amazon_msk/check.py
This prevents propagation of `botocore` logs into the Agent.
```
yyyy-MM-dd HH:mm:ss UTC | CORE | INFO | (pkg/collector/python/* in LogMessage) | - | (credentials.py:1075) | Found credentials from IAM Role: *
```
This log pattern spams the Agent every time the check is run so we prevent this from happening by setting the `botocore`
log level to `CRITICAL`
> Reduced the volume of logging from the `botocore` library

- sqlserver/changelog.d/19384.fixed
- sqlserver/datadog_checks/sqlserver/connection.py
- sqlserver/datadog_checks/sqlserver/schemas.py
- sqlserver/datadog_checks/sqlserver/utils.py
- sqlserver/tests/test_unit.py
This PR fixes a `KeyError` bug in the SQL Server schema collection process. The issue occurred when the database name in `sys.databases` was uppercase in a case-insensitive collation, such as `SQL_Latin1_General_CP1_CI_AS`. 
https://datadoghq.atlassian.net/browse/DBMON-4901
> handle case insensitive db name in schema collection

- mongo/tests/test_integration_shard.py
This PR marks a MongoDB integration test as flaky.
A [job](https://github.com/DataDog/integrations-core/actions/runs/12751733681/job/35539667470) MongoDB failed in our master pipeline. This failure happened once in the past month so marking the integration test as potentially flaky.
> Mark MongoDB integration test as flaky

- milvus/manifest.json
Previously, the process signature was `milvus run standalone` which is just an example of a possible cmdline entry for Milvus.
> Fix Milvus process signature

- docs/developer/setup.md
I noticed that a couple of lines in the docs still reference Python 3.11. We're now using Python 3.12.
> Update Python version in ddev setup docs

- rabbitmq/hatch.toml
We don't need the python2 spec anymore
> Remove python2-only spec for pika client

- mongo/changelog.d/19395.added
- mongo/datadog_checks/mongo/api.py
This PR introduces support for `zlib` network compression in the MongoDB integration client. Starting from MongoDB v3.6, `zlib` compression is natively supported, and it is available in PyMongo without requiring additional dependencies.
- If network compression is disabled or `zlib` is unavailable on the server side, the integration connection gracefully falls back to connecting without compression.
- Users can customize the agent mongo client compressor settings by using the `options.compressors` configuration to override the default `zlib` compressor if needed.
This change enhances performance by reducing network overhead between agent and monitored mongodb database when `zlib` compression is supported by the server.
https://datadoghq.atlassian.net/browse/DBMON-4909
> [mongo] add zlib compression to agent client

- mongo/assets/configuration/spec.yaml
- mongo/changelog.d/19396.added
- mongo/datadog_checks/mongo/config.py
- mongo/datadog_checks/mongo/config_models/instance.py
- mongo/datadog_checks/mongo/data/conf.yaml.example
- mongo/datadog_checks/mongo/dbm/schemas.py
- mongo/tests/results/schemas-standalone-atlas-search-indexes.json
- mongo/tests/test_dbm_schemas.py
This PR introduces a configuration option to control the collection of MongoDB Atlas search indexes via the `$listSearchIndexes` aggregation pipeline. By default, this feature is now disabled.
The change is motivated by performance considerations, as the `$listSearchIndexes` aggregation can run slowly and impact database performance. 
https://datadoghq.atlassian.net/browse/DBMON-4910
> [mongo] add config option to enable search indexes collection

- LICENSE-3rdparty.csv
- agent_requirements.in
- datadog_checks_base/CHANGELOG.md
- duckdb/README.md
- duckdb/datadog_checks/duckdb/check.py
- duckdb/hatch.toml
- duckdb/pyproject.toml
- duckdb/tests/conftest.py
- duckdb/tests/test_e2e.py
The duckdb python library seems to increase the agent package tremendously (around 50MB), so removing it from the agent dependencies to avoid impacting users who do not use the duckdb integration and making it a part of the installation steps.
> Remove Duckdb dependency 

- kube_apiserver_metrics/changelog.d/19415.added
- kube_apiserver_metrics/datadog_checks/kube_apiserver_metrics/kube_apiserver_metrics.py
- kube_apiserver_metrics/metadata.csv
- kube_apiserver_metrics/tests/test_kube_apiserver_metrics.py
- kube_apiserver_metrics/tests/test_kube_apiserver_metrics_1_15.py
- kube_apiserver_metrics/tests/test_kube_apiserver_metrics_1_19.py
- kube_apiserver_metrics/tests/test_kube_apiserver_metrics_1_23.py
- kube_apiserver_metrics/tests/test_kube_apiserver_metrics_1_24.py
- kube_apiserver_metrics/tests/test_kube_apiserver_metrics_1_25.py
- kube_apiserver_metrics/tests/test_kube_apiserver_metrics_1_26.py
- kube_apiserver_metrics/tests/test_kube_apiserver_metrics_1_27.py
- kube_apiserver_metrics/tests/test_kube_apiserver_metrics_1_28.py
This PR adds `process_cpu_seconds_total` to the list of metrics collected by the kube_apiserver_metrics check and remaps it to `process_cpu_total`
GitHub issue: https://github.com/DataDog/integrations-core/issues/18219
Tested with a custom built datadog-agent container that includes this change.
> Add process_cpu_seconds_total to kube_apiserver_metrics check

- .ddqa/config.toml
Exclude Cédric and Haïssam from container-integrations QA
Cédric recently got auto-assigned one of the QA cards from this repo meant for our team and we didn't notice until quite late into the release cycle.
I have never actually seen Haïssam be assigned one of the cards but he is a part of the @DataDog/container-integrations team on GitHub; if this isn't used and there's another place that should be updated please let me know!
> [ddqa/config] Exclude Cédric and Haïssam from container-integrations QA

- datadog_checks_base/changelog.d/19312.added
- datadog_checks_base/datadog_checks/base/utils/tls.py
- datadog_checks_base/tests/base/utils/test_tls.py
Reverts DataDog/integrations-core#19336
> Revert "[Backport 7.62.x] Allow SSLContext ciphers to be customized"

- datadog_checks_base/CHANGELOG.md
- kafka_consumer/assets/configuration/spec.yaml
- kafka_consumer/datadog_checks/kafka_consumer/config.py
- kafka_consumer/datadog_checks/kafka_consumer/config_models/defaults.py
- kafka_consumer/datadog_checks/kafka_consumer/config_models/instance.py
- kafka_consumer/datadog_checks/kafka_consumer/data/conf.yaml.example
- kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
- kafka_consumer/tests/common.py
- kafka_consumer/tests/test_integration.py
- kafka_consumer/tests/test_unit.py
Collect group state tag (introduced in https://github.com/DataDog/integrations-core/pull/17686) only when a configuration variable is set.
Collecting the consumer group state seems to increase the agent resources usage.
Some support cases:
- https://datadoghq.atlassian.net/browse/AGENT-13057
- https://datadoghq.atlassian.net/browse/AGENT-12832
> Disable collecting consumer group state behind a feature flag

- postgres/changelog.d/19406.added
- postgres/datadog_checks/postgres/metadata.py
- postgres/tests/test_metadata.py
This PR enhances PostgreSQL schema collection by adding index state attributes from the pg_index system catalog. The newly collected attributes provide detailed insights into index properties and include:
- is_unique: Indicates if the index enforces uniqueness.
- is_exclusion: Specifies if the index is an exclusion constraint.
- is_immediate: States if the constraint enforcement is immediate.
- is_clustered: Indicates if the index is clustered.
- is_valid: Specifies if the index is valid for use.
- is_checkxmin: Indicates if the index must enforce a transaction’s visibility snapshot.
- is_ready: Shows if the index is ready for use.
- is_live: States if the index is live.
- is_replident: Indicates if the index is used as a replica identity.
- is_partial: Specifies if the index is a partial …
> [postgres] collect index state attributes

- ibm_mq/datadog_checks/ibm_mq/collectors/queue_metric_collector.py
```
2025-01-08 10:01:56 EST | CORE | DEBUG | (pkg/collector/python/datadog_agent.go:149 in LogMessage) | ibm_mq:e2ffdbf676c471d7 | (queue_metric_collector.py:248) |
Unable to get ibm_mq.queue.last_get_time. Turn on queue level monitoring to access these metrics for ICE.MINITMC.REPLYDISPATCHER.IN.
```
```
2025-01-08 10:01:56 EST | CORE | DEBUG | (pkg/collector/python/datadog_agent.go:149 in LogMessage) | ibm_mq:e2ffdbf676c471d7 | (queue_metric_collector.py:248) | Unable to get ibm_mq.queue.last_get_time. Turn on queue level monitoring to access these metrics for ICE.MINITMC.REPLYDISPATCHER.IN.
```
> Debug log on the same line as the timestamp.

- .ddev/config.toml
The broken rethinkdb version was only relevant for Python 2, which we don't support anymore.
> Allow upgrading rethinkdb

- mongo/assets/configuration/spec.yaml
- mongo/changelog.d/19445.added
- mongo/datadog_checks/mongo/config.py
- mongo/datadog_checks/mongo/data/conf.yaml.example
- mongo/tests/results/schemas-mongos.json
- mongo/tests/results/schemas-standalone-atlas-search-indexes.json
- mongo/tests/results/schemas-standalone-atlas.json
- mongo/tests/results/schemas-standalone.json
This PR increases the default collection interval for MongoDB inferred schema and index definitions to 1 hour.
The inferred schema for MongoDB collections is gathered using the `$sample` aggregation pipeline, which can be resource-intensive for large collections, even with the default sampling size of 10 documents. This operation often exceeds 100ms and is categorized as a slow query by MongoDB. By extending the default collection interval, this change reduces the monitoring overhead on the database while maintaining a balance between data freshness and resource consumption.
https://datadoghq.atlassian.net/browse/DBMON-4928
> [mongo] increase mongo schema and index definition default collection interval to 1 hour

- datadog_checks_base/changelog.d/19371.fixed
- datadog_checks_base/datadog_checks/base/utils/http.py
- datadog_checks_base/tests/base/utils/http/test_authtoken.py
Allow for an empty `expires_in` field in OAuth Access Token response as detailed by [RFC 6749](https://www.rfc-editor.org/rfc/rfc6749#section-5.1).
Handle unexpected type in `expires_in` field, e.g. string.
> [AGENT-12890] Handle unexpected values for `expires_in` in OAuth Access response

- mongo/changelog.d/19450.added
- mongo/datadog_checks/mongo/dbm/operation_samples.py
This PR adds support for capturing explain operations in MongoDB activity samples.
Previously, explain operations were excluded from activity samples, which could result in an incomplete count of active database operations. Including them ensures more accurate tracking and representation of database activity.
> [mongo] include explain operations in samples

- mysql/changelog.d/19478.fixed
- mysql/pyproject.toml
- postgres/changelog.d/19478.fixed
- postgres/pyproject.toml
- sqlserver/changelog.d/19478.fixed
- sqlserver/pyproject.toml
Bumps the dependency for DBM checks to properly include stub for emit_agent_telemetry.
> Bump datadog-checks-base version

- milvus/assets/monitors/dml_channel_lag.json
- milvus/assets/monitors/index_build_latency.json
- milvus/assets/monitors/request_latency.json
- milvus/manifest.json
> [AI-4453] Add Milvus recommended monitors

- datadog_checks_base/changelog.d/19469.added
- datadog_checks_base/datadog_checks/base/utils/http.py
- datadog_checks_base/tests/base/utils/http/test_http.py
> [AGENT-12451] Add ciphers option for fetch_intermediate_certs

- sqlserver/assets/configuration/spec.yaml
- sqlserver/changelog.d/19479.added
- sqlserver/datadog_checks/sqlserver/activity.py
- sqlserver/datadog_checks/sqlserver/config_models/instance.py
- sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
- sqlserver/tests/test_activity.py
Adds an option to sample recently active idle sessions.
Improve APM/DBM correlation by ~3x.
For example, the execution plan for the query below, which ran in 2ms, was captured only after several executions:
Capturing queries is essential for APM/DBM correlation. Currently, only active sessions are sampled, missing many fast queries. By sampling idle sessions that were recently active, we can significantly increase the number of captured queries.
The option is disabled by default because, in SQL Server, identifying queries from idle sessions requires a second scan, doubling activity collection time.
Sampled idle sessions are excluded from the active sessions graph but appear in the samples with the `Wait Event` set to `Other`. If we don't filter them, they should be marked as `Idle`.
> Add option for sampling idle recently active sessions

- .github/workflows/test-fips-e2e.yml
This PR modifies the FIPS E2E test to use the standard Agent for the tests where FIPS is disabled.
Starting the FIPS Agent with `GOFIPS=0` does not impact the config loaded by the Agent's OpenSSL, which means it still operates in FIPS mode.
> Fix FIPS E2E workflow

- .github/workflows/build-ddev.yml
Status quo: hatch is not pinned, but the tooling to publish to PYPI is hard pinned.
They can become out of sync, which is what caused one release of ddev not to be uploaded:
https://github.com/DataDog/integrations-core/actions/runs/12890858404
To be exact, `hatch` [produced metadata v2.4](https://github.com/pypa/hatch/releases/tag/hatchling-v1.27.0), but twine from the github action was too old to support that (that support added [in 1.12.3](https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.12.3)). So the upload failed.
We have 2 options: either pin both or relax the pin for PYPI upload tooling.
Pinning hatch sounds like more maintenance.
Having `v1` will be enough to make sure we don't get breaking changes for this action while getting the latest stuff that's compatible with …
> Loosen pin for github action that uploads ddev to PYPI

- sqlserver/assets/configuration/spec.yaml
- sqlserver/changelog.d/19421.added
- sqlserver/datadog_checks/sqlserver/activity.py
- sqlserver/datadog_checks/sqlserver/config.py
- sqlserver/datadog_checks/sqlserver/config_models/instance.py
- sqlserver/datadog_checks/sqlserver/statements.py
- sqlserver/tests/compose-ha/sql/aoag_primary.sql
- sqlserver/tests/compose-high-cardinality-windows/setup.sql
- sqlserver/tests/compose-high-cardinality/setup.sql
- sqlserver/tests/compose-windows/setup.sql
- sqlserver/tests/compose/setup.sql
- sqlserver/tests/test_activity.py
- sqlserver/tests/test_statements.py
This PR introduces a feature to ingest raw query statements and explain plans when the `collect_raw_query_statement.enabled` option is set to true. The raw query statement is collected alongside activity samples from `sys.dm_exec_input_buffer` using session_id and request_id, which provides the input text that triggers query execution.
https://datadoghq.atlassian.net/browse/DBMON-4952
This enhancement supplements obfuscated and normalized query statements with de-obfuscated query statements and execution plans, provides insights into query parameter values. 
Note that raw query statements include parameter values only for non-prepared statements.
> [sqlserver] Emit raw query statements and plans for non prepared statements

- sqlserver/assets/configuration/spec.yaml
- sqlserver/changelog.d/19479.added
- sqlserver/datadog_checks/sqlserver/activity.py
- sqlserver/datadog_checks/sqlserver/config_models/instance.py
- sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
- sqlserver/tests/test_activity.py
Reverts DataDog/integrations-core#19479
Motivation: exploring an alternative approach with a new `dbm_type`
> Revert "Add option for sampling idle recently active sessions"

- sqlserver/changelog.d/19495.added
- sqlserver/datadog_checks/sqlserver/statements.py
- sqlserver/tests/test_statements.py
This PR adds `raw_signature` to `rqp` (raw query plan) event. `raw_signature` can be used to lookup de-obfuscated explain plan. 
https://datadoghq.atlassian.net/browse/DBMON-4952
> [sqlserver] add raw_signature to plan event

- karpenter/README.md
Update the default Karpenter metrics port to `8080`
*Note*: Feel free to give feedback on whether or not we would like to keep documentation around for any <1.0.0 release. Could not find any similar changes here. 
The documentation does not reflect this change in [Karpenter v1.0.0](https://github.com/aws/karpenter-provider-aws/pull/6578)
> Update Karpenter documentation, update default metrics port

- octopus_deploy/assets/dashboards/overview.json
- octopus_deploy/manifest.json
Adds a dashboard for octopus deploy
> [PLINT-539] Add octopus dashboard

- pgbouncer/CHANGELOG.md
- pgbouncer/changelog.d/19497.fixed
- pgbouncer/datadog_checks/pgbouncer/__about__.py
- postgres/CHANGELOG.md
- postgres/changelog.d/19499.fixed
- postgres/datadog_checks/postgres/__about__.py
- requirements-agent-release.txt
Port changelogs and version bumps from [7.63.0-rc.3](https://github.com/DataDog/integrations-core/releases/tag/7.63.0-rc.3) to master.
> Port changelogs and version bumps from 7.63 RC3 to master.

- ecs_fargate/README.md
Adds a JSON example in the docs for the AP1 region site in "Fluent Bit and FireLens" procedure, step 2. This appears to have been accidentally omitted, as there isn't any other content conditionalized out for AP1 on the page.
> [DOCS-9811] Add missing JSON example in docs for AP1 region

- datadog_checks_dev/changelog.d/19538.fixed
- datadog_checks_dev/pyproject.toml
- fly_io/README.md
Pins beautifulsoup 
CI validation for readmes started failing on the new release this AM 
https://groups.google.com/g/beautifulsoup/c/GHpJYIlF6AA
https://groups.google.com/g/beautifulsoup/c/M_vgwfO0RLA
> Pin beautifulsoup

- .builders/images/linux-aarch64/Dockerfile
- .builders/images/linux-x86_64/Dockerfile
- .builders/images/macos-x86_64/builder_setup.sh
- .builders/images/windows-x86_64/Dockerfile
This PR bumps the version of OpenSSL we ship with `confluent-kafka-python`.
https://datadoghq.atlassian.net/browse/VULN-9651
> Bump confluent-kafka OpenSSL version to 3.4.0

- mysql/datadog_checks/mysql/databases_data.py
- mysql/tests/test_metadata.py
Adjusting the mySQL schema definition outputted by the agent. We should not emit null values to avoid needing to make these adjustments further in the pipeline. 
Working with these null fields gone from the agent rather than null values greatly simplifies changes I'm making in dd-go to process these schemas.
> Omit null and empty values in mysql schema definition

- mongo/changelog.d/19571.fixed
- mongo/datadog_checks/mongo/collectors/host_info.py
- mongo/tests/test_integration.py
This PR skips host info system metrics collection on arbiter. `hostInfo` command cannot be ran on arbiter node even logged in with authentication. 
https://datadoghq.atlassian.net/browse/SDBM-1491
> [mongo] skip host info system metrics collection on arbiter

- .github/workflows/flaky-tests.yml
Fixes permissions for the daily flaky tests GitHub Actions workflow.
The workflow was failing with this error: 
```
The workflow is not valid. .github/workflows/flaky-tests.yml (Line: 32, Col: 3): Error calling workflow 'DataDog/integrations-core/.github/workflows/test-results-master.yml@cdcf656538ec4f2b9d7c6cfc3552fdaf966592c4'. The nested job 'test-results' is requesting 'checks: write, contents: write, pull-requests: write', but is only allowed 'checks: none, contents: read, pull-requests: none'.
```
Example: https://github.com/DataDog/integrations-core/actions/runs/13233335605/workflow
> Fix permissions for the flaky tests workflow

- sqlserver/changelog.d/19577.added
- sqlserver/datadog_checks/sqlserver/database_metrics/xe_session_metrics.py
- sqlserver/datadog_checks/sqlserver/deadlocks.py
- sqlserver/datadog_checks/sqlserver/queries.py
Add deadlocks monitoring for Azure database.
Azure DB can't access the instance views, so I modified the query to get deadlocks from the local views.
```
CREATE EVENT SESSION datadog
ON database
ADD EVENT sqlserver.database_xml_deadlock_report
ADD TARGET package0.ring_buffer
WITH (
MAX_MEMORY = 1024 KB,
EVENT_RETENTION_MODE = ALLOW_SINGLE_EVENT_LOSS,
MAX_DISPATCH_LATENCY = 30 SECONDS,
STARTUP_STATE = ON
);
GO
ALTER EVENT SESSION datadog ON DATABASE STATE = START;
GO
```
Requested by customers, e.g. by Thomson Reuters.
> Add deadlock support for Azure DB

- sonarqube/tests/test_e2e.py
- sonarqube/tests/test_integration.py
- sonarqube/tests/test_unit.py
> Remove explicit pytest labels

- postgres/assets/configuration/spec.yaml
- postgres/changelog.d/19582.fixed
- postgres/datadog_checks/postgres/config.py
- postgres/datadog_checks/postgres/statements.py
- postgres/tests/test_statements.py
This PR splits query metrics payload into separate submissions to keep each below the max content size limit for the `dbm-metrics` pipeline.
This change will allow customers with unusually large query metrics payloads to still submit metrics.
> Split Postgres query metrics payload to conform to max payload size

- postgres/changelog.d/19586.fixed
- postgres/datadog_checks/postgres/postgres.py
- postgres/tests/test_discovery.py
Previously, if the agent failed to connect to one database, it stopped collecting metrics for all. Now, an exception logs the error but allows processing to continue.
> Fix exception handling for auto discovered databases

- mysql/changelog.d/19598.fixed
- mysql/datadog_checks/mysql/mysql.py
- mysql/tests/test_mysql.py
This PR fixes a bug where the `dbms_flavor` tag was incorrectly appended to the tags list on every integration check run.
https://datadoghq.atlassian.net/browse/DBMON-5003
> [mysql] fix bug where dbms_flavor is appended to tags on every check run

- .github/workflows/labeler-community.yml
- .github/workflows/labeler.yml
Adds `pull-requests: write` permissions to labeler-community.yml and labeler.yml.
We're the [only ones using labeler-reusable.yml](https://github.com/search?q=org%3ADataDog+labeler-reusable.yml&type=code)  so no fixes needed in other repos.
Fixes this error in the `Community PR Labels` workflow in CI:
```
Invalid workflow file
The workflow is not valid. .github/workflows/labeler-community.yml (Line: 15, Col: 3): Error calling workflow 'DataDog/integrations-core/.github/workflows/labeler-reusable.yml@b33cd00ba0f9619b587a209b628df1ce2e55a814'. The nested job 'apply' is requesting 'pull-requests: write', but is only allowed 'pull-requests: none'.
```
> Fix GitHub Actions permissions for Labeler

- cisco_aci/datadog_checks/cisco_aci/cisco.py
- datadog_checks_base/changelog.d/19580.added
- datadog_checks_base/datadog_checks/base/checks/base.py
- datadog_checks_base/tests/base/checks/test_agent_check.py
This PR adds a class attribute `HA_SUPPORTED` to the `Check` class which is false by default.
Overriding it to true means that the integration does support HA.
If a user configures an integration with `ha_enabled:` true on a non supported integration the`__init__` will fail and the check not schedule
> [NDMII-3310] add support for HA for integrations

- agent_requirements.in
- mongo/changelog.d/19610.added
- mongo/datadog_checks/mongo/collectors/custom_queries.py
- mongo/pyproject.toml
- mongo/tests/conftest.py
- mongo/tests/test_unit.py
This PR manually bumps `pymongo` to 4.11 and fixes tests. 
Automated dependencies update failed due to pymongo `MongoClient` and `command_cursor` import errors.
> bump pymongo to 4.11

- .builders/images/windows-x86_64/Dockerfile
- .builders/images/windows-x86_64/build_script.ps1
- kafka_consumer/changelog.d/19608.added
Fixes [CVE-2024-12797.](https://nvd.nist.gov/vuln/detail/CVE-2024-12797)
3.4.1 is not on [vcpkg.io](https://vcpkg.io/en/package/openssl) yet but it's accessible in the CLI.
```
PS C:\Users\Administrator\Downloads\vcpkg> .\vcpkg.exe search openssl
...
openssl                  3.4.1            OpenSSL is an open source project that provides a robust, commercial-grade...
```
Upgrading to from 3.3.2 directly to 3.4.1 because it seems like [the vcpkg project is skipping 3.3.3 and upgrading the 3.4.X branch instead](https://github.com/microsoft/vcpkg/issues/43779). 
The CVE was already fixed on Linux and MacOS in [a previous commit](https://github.com/DataDog/integrations-core/commit/18deb23bf132f2f50afd11ca56ddec12f9926a5c).
> Bump OpenSSL in confluent-kafka to 3.4.1 on Windows

- dcgm/README.md
Update docs. The important update this references in the readme change is a change that got shipped with agent 7.59, which remapped some metric labels to standard kubernetes tags such as pod_name and kube_namespace.
> readme update

- mysql/CHANGELOG.md
This PR ports the changelog for the dmb_flavor fix from 7.62.3 rc1. I added notes to clarify that 14.5.0 doesn't have the fix.
> Port changelog from 7.62.3 rc1

- .github/CODEOWNERS
We don't want to bother SAAS ints to approve PRs like this one to update dependencies:
https://github.com/DataDog/integrations-core/pull/19576
Without co-ownership though, we're blocked on that.
> Add Agent Ints as co-owners of pyproject.toml and changelog snippets

- octopus_deploy/changelog.d/19613.fixed
- octopus_deploy/datadog_checks/octopus_deploy/check.py
- octopus_deploy/tests/test_unit.py
Adds a role_name tag key to octopus machine metrics
Make the metrics easier to filter by in dashboard queries
> Add role_name tag key to machine metrics

- airflow/README.md
[Jira](https://datadoghq.atlassian.net/browse/DJM-634) 
Add a call out to DJM in the airflow integration documentation
In the same fashion as we did for Databricks and Spark, we want to have a call out to the Data Jobs Monitoring product in the Airflow integration documentation, as it is the first result on search results pages when searching for "Datadog Airflow" or "Airflow Datadog".
> [DJM] Add callout to DJM in airflow docs

- duckdb/manifest.json
Change DuckDB `display_on_public_website` in the `manifest.json` to `true`. It's a step in the Release for [Everyone checklist](https://datadoghq.atlassian.net/browse/AI-4471).
> DubckDB: Set "display_on_public_website" to true

- spark/changelog.d/19561.fixed
- spark/datadog_checks/spark/spark.py
- spark/tests/common.py
- spark/tests/test_spark.py
Quick note on terms: "aspects" here refers to properties of an app like `jobs` or `stages`. I'm open to use the word "properties" instead.
We would throw an exception if we couldn't parse the json for some aspect/property of an app. This meant that any available apps after an unavailable one would not get collected.
We gracefully skip the unavailable apps, keep collecting the available ones.
> Gracefully handle unavailable apps and their aspects

- spark/changelog.d/19561.fixed
- spark/datadog_checks/spark/spark.py
- spark/tests/common.py
- spark/tests/test_spark.py
This reverts commit 7c6d13f0d22062f1e05b38a913a4e244c88a18ac.
The e2e tests started failing more often. There's no pressure to ship this, so we'll revert and investigate.
> Revert "Gracefully handle unavailable apps and their aspects (#19561)"

- postgres/changelog.d/19470.fixed
- postgres/datadog_checks/postgres/relationsmanager.py
Omits the relation name filter when the regex is equal to `.*`.
This filter will match all but force the query to evaluate all rows for the match. Omitting it should improve performance.
> Omit .* regex filter

- streamnative/README.md
This PR updated the description about the authorization for the StreamNative Metrics API since users can also use a a normal service account with `metrics-viewer` role. 
Super Admin service account works for StreamNative Metrics API authorization but it may caue the abuse of privileges since super admin can do almost everything on StreamNative Cloud. So, a normal service account with `metrics-viewer` role to limit the permission is a more acceptabled solution for users.
> streamnative: update the metrics api permission documentation

- kubevirt_api/changelog.d/19655.fixed
- kubevirt_api/pyproject.toml
Makes kubernetes an official dependency of kubevirt_api and updates version
> Update kubernetes dependency and move to correct place

- milvus/manifest.json
> enable docs for public

- .builders/images/linux-aarch64/Dockerfile
- .builders/images/linux-x86_64/Dockerfile
- .builders/images/windows-x86_64/Dockerfile
- .github/workflows/build-deps.yml
- .github/workflows/master.yml
Bump the Python version from 3.12.8 to 3.12.9 to address CVEs.
> Bump Python from 3.12.8 to 3.12.9

- postgres/changelog.d/19694.fixed
- postgres/datadog_checks/postgres/metadata.py
- postgres/tests/compose/resources/03_load_data.sh
Adds a check to only trigger the activation of extensions that are installed in `public` or `pg_catalog`.
If an extension is installed into a schema that the agent does not have access to, it causes the settings collection to fail.
> Only trigger extensions in default namespaces

- openstack_controller/changelog.d/19701.fixed
- openstack_controller/datadog_checks/openstack_controller/api/api.py
- openstack_controller/datadog_checks/openstack_controller/api/api_rest.py
Removes unused code
I found this while reviewing the permissions flow
> remove unused code

- .github/CODEOWNERS
PRs with new releases of the snowflake integration **require** approval from SAAS ints.
PRs with new releases of the snowflake integration can be merged after Agent Ints team approves them. No need to ping SAAS ints or admin-merge.
No need to bother SAAS ints if we're releasing a new snowflake integration version due to dependency or Python version updates.
> Agent integrations team can approve snowflake version bumps.

- postgres/changelog.d/19625.added
- postgres/datadog_checks/postgres/metrics_cache.py
- postgres/datadog_checks/postgres/postgres.py
- postgres/datadog_checks/postgres/statements.py
- postgres/datadog_checks/postgres/util.py
- postgres/datadog_checks/postgres/version_utils.py
- postgres/hatch.toml
- postgres/tests/common.py
- postgres/tests/test_pg_integration.py
- postgres/tests/test_progress_stats.py
- postgres/tests/test_statements.py
- postgres/tests/utils.py
Copying the changes from https://github.com/DataDog/integrations-core/pull/19568 by @vcabbage:
Postgres changes are noted in the [release notes](https://www.postgresql.org/docs/current/release-17.html#RELEASE-17-MIGRATION). I've included links to the commits as they provide more detail.
Fixes for the following Postgres changes:
* Columns moved and renamed from `pg_stat_bgwriter` to new `pg_stat_checkpointer`. ([96f052613](https://postgr.es/c/96f052613))
* `buffers_backend` and `buffers_backend_fsync` columns removed from `pg_stat_checkpointer`. The PG commit explains that they're not actually checkpointer properties and `pg_stat_io` provides the equivalent and more accurate information. ([74604a37f](https://postgr.es/c/74604a37f))
* `max_dead_tuples` renamed to `max_dead_tuple_bytes` and …
> PG17 support

- .gitignore
- ddev/.gitignore
- ddev/pyproject.toml
ruff will automatically ignore linting for files in the .gitignore. This might be better since we don't want to really lint for files that are automatically generated and we have little control over.
> Use`.gitignore` to allow ruff to skip over linting autogenerated file

- mailchimp/README.md
- mux/README.md
> [SAASINT-3785][mux][mailchimp] Copy updates

- teleport/assets/logs/teleport.yaml
This PR fixes two rules of the `Grok Parser` of the `Teleport` integration log pipeline, which contains `\n` (newline) characters in the middle of some regex.
Even if they are (apparently) valid and parsed correctly, this breaks the usual convention of having a rule defined on a single line. This also make future edit potentially tricky as it's unclear how the spaces in between are handled (trimmed? not trimmed?).
> Fix Teleport log pipeline Grok parser rules containing newlines

- vsphere/changelog.d/19393.fixed
- vsphere/datadog_checks/vsphere/config.py
- vsphere/datadog_checks/vsphere/event.py
- vsphere/datadog_checks/vsphere/legacy/vsphere_legacy.py
- vsphere/datadog_checks/vsphere/vsphere.py
- vsphere/tests/test_event.py
Submits placeholder value for empty hostnames in the vSphere check, where these hosts will be removed later on.
> Add empty hostname workaround

- .gitlab/build_agent.yaml
Small update on the agent build CI config file to define separate jobs and understand if the corresponding one is the one being run.
- Update the regex to ensure we are using a dot (`.`) instead of any character.
- Define 2 downstream trigger jobs to understand if the proper one is triggered form a release branch
Already validated that the override is working properly. This change is meant to be tested on a release branch.
> Update agent build in GitLab CI to point to the proper branch

- ecs_fargate/README.md
This PR adds an example of securely passing an API key as opposed to adding the API key in plain text
Hotjar request from https://datadoghq.atlassian.net/browse/DOCS-10224
> DOCS-10224 added an example to securely pass API key

- otel/assets/dashboards/otel_collector_metrics_dashboard.json
Fix DD exporter and connector APM related metrics on OTel collector dashboard
- https://datadoghq.atlassian.net/browse/SEMCON-748 Filter internal APM health metrics (`otelcol_datadog_trace_agent_*` metrics) by `source:datadogexporter`, only metrics with this tag are indeed from DD exporter or connector. 
- **Note** most metrics from DD connector also have `source:datadogexporter` rather than `source:datadogconnector` because metrics are sent with DD exporter.
- https://datadoghq.atlassian.net/browse/OTAGENT-44 Add deprecation notice to traces/s and spans/s metrics on the DD connector section. Those 2 metrics no longer apply when native ingest in DD connector is enabled, in that case traces go through the new OTel stats API rather than the OTLP receiver in trace agent.
> [SEMCON-748] fix DD exporter and connector metrics on OTel collector dashboard

- mongo/assets/configuration/spec.yaml
- mongo/changelog.d/19756.added
- mongo/datadog_checks/mongo/collectors/coll_stats.py
- mongo/datadog_checks/mongo/collectors/db_stat.py
- mongo/datadog_checks/mongo/collectors/session_stats.py
- mongo/datadog_checks/mongo/common.py
- mongo/datadog_checks/mongo/config.py
- mongo/datadog_checks/mongo/config_models/defaults.py
- mongo/datadog_checks/mongo/config_models/instance.py
- mongo/datadog_checks/mongo/data/conf.yaml.example
- mongo/datadog_checks/mongo/dbm/utils.py
- mongo/datadog_checks/mongo/mongo.py
- mongo/tests/results/metrics-collection-non-system.json
- mongo/tests/results/metrics-dbstats-non-system.json
- mongo/tests/results/metrics-indexes-stats-non-system.json
- mongo/tests/test_integration.py
- mongo/tests/test_unit_config.py
This PR introduces new configuration options to improve control over MongoDB system database statistics collection and metric collection intervals:
- system_database_stats (default: true) – Allows users to optionally skip collecting database stats, collection stats, and index stats for system databases (admin, local, and config). By default, stats metrics are still collected from system databases.
- metrics_collection_interval.db_stats and metrics_collection_interval.session_stats – Enable customizable collection intervals for database stats and session stats (applicable to mongos instances only).
These changes provide greater flexibility in monitoring configurations, reducing mongo integration overhead where needed.
https://datadoghq.atlassian.net/browse/DBMON-5056
> Add config option to skip db, collection and index stats for system databases

- mongo/changelog.d/19768.fixed
- mongo/datadog_checks/mongo/api.py
- mongo/tests/mocked_api.py
- mongo/tests/test_unit.py
This reverts commit 6c5362ed47c57f1fb1119b8015c5ab59c9e1d01a.
`comment` breaks mongodb prior to v4.4 and documentdb v4 and v5. we can rely on `application_name:datadog-agent` to identify queries from the agent
> Revert "[mongo] add service tag to agent operations (#19456)"

- postgres/changelog.d/19773.added
- postgres/datadog_checks/postgres/version_utils.py
- postgres/tests/test_version_utils.py
When Amazon adds Extended Support to older Postgres versions, they update the version string to a format we are currently unable to parse. This adds the ability to parse those versions. Here is an example announcement where they communicate such a version string: https://aws.amazon.com/about-aws/whats-new/2024/12/amazon-rds-postgresql-minor-11-22-rds-20241121/
> Parse RDS end-of-life versions.

- nginx/hatch.toml
Adds the 1.27 version to nginx test.
Cover newer versions of nginx by test.
> Add nginx version 1.27

- .gitlab/build_agent.yaml
We noticed that the pipeline kicks in on any branch after being merged. Ideally we want the agent build to happen whenever a relevant file is changed before merging it. The change on `build-agent-auto` modifies its behavior so it only triggers on Github PRs that modify those files.
EDIT: after the PR was created we noticed that the [external pull requests](https://docs.gitlab.com/ci/ci_cd_for_external_repos/#pipelines-for-external-pull-requests) does not work with our sync to GitLab. The latest commit removes the use of external pull requests and instead avoid running it after having merged it to a release branch.
Once the PR is merged we should have the option to trigger a manual build either on the corresponding agent  branch:
- If we merged the PR to a release branch, the manual build …
> Modify auto agent build behavior and manual build agent branch

- ceph/changelog.d/19284.added
- ceph/datadog_checks/ceph/ceph.py
- ceph/metadata.csv
- ceph/tests/fixtures/ceph_stats_by_class.json
- ceph/tests/test_unit.py
Adds a metric for the percentage of storage used in Ceph, broken down by device class.
The Ceph integration does not currently report the amount of space utilized by device class, leading to a lack of visibility over potential issues with a specific device class becoming full. According to [the documentation](https://docs.ceph.com/en/nautilus/rados/operations/monitoring/#checking-a-cluster-s-usage-stats) the `ceph df` command has provided a RAW STORAGE section (called `stats_by_class` in the JSON output) since Nautilus, enabling this reporting across the six newest versions of Ceph.
I have not updated the unit test for the new metric, as I am unsure if there are any special requirements related to generating/updating the `raw.json`/`raw2.json` fixtures required. I apologize if I have …
> Add Ceph usage by device class metric

- sqlserver/hatch.toml
This PR removes MSSQL 2017 on Linux from the SQLServer integration test suite. The MSSQL 2017 container fails to start or crashes intermittently on Linux kernel 6.7 and 6.8.
On February 26, GitHub updated the ubuntu-22.04 runner kernel from 6.5.0 to 6.8.0, which caused SQL Server tests to start failing on MSSQL 2017. Currently, neither the MSSQL 2017 container nor the non-containerized version of MSSQL 2017 on Linux works with kernel 6.8.0.
To unblock the pipeline, this PR removes MSSQL 2017 from the test suite (for now, hopefully temporarily).
Related issue: https://github.com/microsoft/mssql-docker/issues/868
> [sqlserver] Remove mssql 2017 on linux from test suite

- mongo/changelog.d/19798.added
- mongo/datadog_checks/mongo/dbm/utils.py
This PR updates the mongo integration to skip running explain on aggregation pipelines that include the `$mergeCursors` stage.
- The $mergeCursors stage is used internally in sharded cluster aggregations to merge cursor results across shards.
- Running explain on a query that includes $mergeCursors can cause MongoDB to execute the stage in an unintended context, potentially leading to a server crash.
- Additionally, explaining this stage does not provide useful query execution insights since it references cursor IDs from a previous step that no longer exist.
> [mongo] skip explain aggregation pipeline with mergeCursors stage

- mysql/hatch.toml
Add MariaDB 11.4 LTS to test suite. Removed 10.2, 10.8 and 10.9 from the test suite.
> update mariadb test suite to include 11.4 LTS and remove eol versions

- sqlserver/changelog.d/19807.changed
- sqlserver/datadog_checks/sqlserver/database_metrics/index_usage_metrics.py
- sqlserver/datadog_checks/sqlserver/sqlserver.py
Optimize the index usage stats query for sqlserver
- Remove function in filter (OBJECTPROPERTY), replace with a join on sys.objects
- Remove function in filter (DB_NAME), replace with database_id comparison
- Remove group by, not needed
- Replace CASE with COALESCE
This query can take ~minutes, for example https://datadoghq.atlassian.net/browse/SDBM-1534
> [SDBM-1534] Modify sqlserver index usage stats query

- sqlserver/changelog.d/19803.fixed
- sqlserver/datadog_checks/sqlserver/database_metrics/base.py
- sqlserver/tests/test_database_metrics.py
This PR fixes a bug where `tempdb` is wrongly excluded in database files metrics due to all instances inherited from `SqlserverDatabaseMetricsBase` share the same reference of auto-discovered databases.
> [sqlserver] fix bug where tempdb is wrongly excluded in database files metrics

- datadog_checks_base/changelog.d/19791.fixed
- datadog_checks_base/datadog_checks/base/checks/prometheus/mixins.py
- datadog_checks_base/datadog_checks/base/utils/http.py
- datadog_checks_base/tests/base/utils/http/test_tls_and_certs.py
We log if we make an unverified HTTP request. This PR changes the level from WARNING to DEBUG.
WARNING level is spamming our internal logs and users aren't responding to it.
> Reduce log verbosity level for unverified HTTP requests.

- agent_requirements.in
- mongo/changelog.d/19814.fixed
- mongo/datadog_checks/mongo/collectors/custom_queries.py
- mongo/pyproject.toml
- mongo/tests/conftest.py
- mongo/tests/test_unit.py
This reverts commit 772ccc5ada1e5c431802a85666d66ffe5cb75f1c.
Custom queries crash with the following error:
```
2025-03-12 10:57:06 UTC | CORE | INFO | (pkg/collector/python/datadog_agent.go:147 in LogMessage) | mongo:7e361d43268980ce | (mongo.py:328) | Unable to collect logs from collector <datadog_checks.mongo.collectors.custom_queries.CustomQueriesCollector object at 0x785e08260140>. Some metrics will be missing.
File "/usr/src/dbm-integrations-core/mongo/datadog_checks/mongo/mongo.py", line 326, in _collect_metrics
collector.collect(self.api_client)
File "/usr/src/dbm-integrations-core/mongo/datadog_checks/mongo/collectors/custom_queries.py", line 207, in collect
raise e  # Critical failures must bubble up to trigger a CRITICAL service check. …
```
> Revert "bump pymongo to 4.11 (#19610)"

- .github/workflows/test-target.yml
Looking at CI health I noticed that there were failures related with a typo on the tests we are running in which `--` were passed twice and `-k "no fips"` was understood to be a folder to discovery tests. The error showed the folder does not exist.
- [Example error](https://github.com/DataDog/integrations-core/actions/runs/13756610984/job/38465071863#step:14:289)
- [Example wrong command](https://github.com/DataDog/integrations-core/actions/runs/13756610984/job/38465071863#step:14:270)
Run tests:
```
ddev test azure_iot_edge -- -m unit -k "not fips"
```
Output:
```
────────────────────────────────────────────────────────────────────────────────────────────────────── Azure IoT Edge ────────────────────────────────────────────────────────────────────────────────────────────────────── …
```
> Fix not fips keyword on target tests

- ceph/tests/test_integration.py
- ceph/tests/test_unit.py
Updates ceph tests to use `dd_run_check` 
We want to test configuration loading for ceph, and `dd_run_check` executes configuration loading as well as the `check.check` method. Follow up to comment here https://github.com/DataDog/integrations-core/pull/19284/s
> Use `dd_run_check` in ceph tests

- agent_requirements.in
- mongo/changelog.d/19814.fixed
- mongo/datadog_checks/mongo/collectors/custom_queries.py
- mongo/pyproject.toml
- mongo/tests/conftest.py
- mongo/tests/test_unit.py
* Revert "bump pymongo to 4.11 (#19610)"
This reverts commit 772ccc5ada1e5c431802a85666d66ffe5cb75f1c.
* add changelog
(cherry picked from commit b0a752ba98de68757b415e0dc5d0d75371ed74b1)
> Port "Revert "bump pymongo to 4.11 (#19610)" (#19814)" to 7.64

- datadog_cluster_agent/assets/dashboards/datadog_cluster_agent_overview.json
Updates the Datadog Cluster Agent - Overview dashboard.
[CONTP-672]Add widget for local failover metric store in cluster-agent
The widget will provide entities number in dca's local failover metric store. These entities and metric values will be used for local autoscaling recommendation. 
The data is selected by cluster->namespace. The columns of the table include deployment name, workload metrics name, and number of entities stored in dca (for example, it could populated from number of container if metric is container metric, or number of pods if the metric is pod metric )
**Query**
[CONTP-672]: https://datadoghq.atlassian.net/browse/CONTP-672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CONTP-672]Add widget for local failover metric store in cluster-agent

- .github/workflows/validate.yml
All in the title. We now have a more up-to-date validation coming from the Asset Publishing Workflow.
I've even seen our validations diverge with it already.
> Stop validating assets since APW now handles that

- zero_networks/README.md
- zero_networks/assets/dashboards/zero_networks_network_activities.json
This pull request includes minor changes to a parameter name in the README, a query modification for one of the panels, and a filter-related update for the Zero Networks - Network Activities dashboard.
> Zero Networks: Minor changes

- .ddev/config.toml
- LICENSE-3rdparty.csv
- agent_requirements.in
- datadog_checks_base/pyproject.toml
Extracted from https://github.com/DataDog/integrations-core/pull/19838, we want the dependencies built already in order to test on a live Agent
> Add `lazy-loader` dependency

- datadog_checks_base/README.md
- datadog_checks_base/changelog.d/19845.added
- datadog_checks_base/changelog.d/19845.added.1
- datadog_checks_base/datadog_checks/base/checks/base.py
- datadog_checks_base/datadog_checks/base/checks/libs/prometheus.py
- datadog_checks_base/datadog_checks/base/checks/openmetrics/base_check.py
- datadog_checks_base/datadog_checks/base/checks/openmetrics/mixins.py
- datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/base.py
- datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/scraper.py
- datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/utils.py
- datadog_checks_base/datadog_checks/base/log.py
- datadog_checks_base/datadog_checks/base/stubs/datadog_agent.py
- datadog_checks_base/datadog_checks/base/utils/_http_utils.py
- datadog_checks_base/datadog_checks/base/utils/db/sql.py
- datadog_checks_base/datadog_checks/base/utils/db/utils.py
- datadog_checks_base/datadog_checks/base/utils/format/__init__.py
- datadog_checks_base/datadog_checks/base/utils/format/_json.py
- datadog_checks_base/datadog_checks/base/utils/format/json.py
- datadog_checks_base/datadog_checks/base/utils/http.py
- datadog_checks_base/datadog_checks/base/utils/replay/execute.py
- datadog_checks_base/datadog_checks/base/utils/replay/redirect.py
- datadog_checks_base/datadog_checks/base/utils/serialization.py
- datadog_checks_base/datadog_checks/base/utils/tracing.py
- datadog_checks_base/tests/base/utils/db/test_util.py
- datadog_checks_base/tests/base/utils/format/__init__.py
- datadog_checks_base/tests/base/utils/format/test_json.py
- datadog_checks_base/tests/base/utils/http/test_auth.py
- Reverts this PR minus the changelog entry: https://github.com/DataDog/integrations-core/pull/19781
- Makes a new `datadog_checks.base.utils.format.json` module that everything should switch to instead of `datadog_checks.base.utils.serialization` to avoid always importing `orjson` (and for a nicer API)
- Adds lazy loading to other parts of the base package, especially the HTTP utilities. Checks that use them will now have a much lower memory overhead most of the time (depending on the configuration)
This PR provides a long-term lazy import solution: https://github.com/DataDog/integrations-core/pull/19838
- We should switch to using absolute imports everywhere for better readability and the possibility of compiling with Mypyc
- We should also switch all comment-based type hints to …
> Refactor imports

- mongo/assets/configuration/spec.yaml
- mongo/changelog.d/19856.added
- mongo/datadog_checks/mongo/config.py
- mongo/tests/test_unit_config.py
This PR increased MongoDB the default collection stats and collection index stats to 5 mins.
Reduce the performance overhead from frequent `$collStats` and `$indexStats` operations on all collections.
> [mongo] increase collection stats and collection index stats collect interval to 5 mins

- .ddev/config.toml
- LICENSE-3rdparty.csv
- agent_requirements.in
- datadog_checks_base/changelog.d/19842.fixed
- datadog_checks_base/pyproject.toml
- datadog_checks_dev/changelog.d/19842.fixed
- datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/licenses.py
- win32_event_log/changelog.d/19842.fixed
- win32_event_log/datadog_checks/win32_event_log/legacy/win32_event_log.py
- win32_event_log/pyproject.toml
Stop using the uptime library. 
- `uptime` is no longer maintained (last release: 2013)
- We already have psutil, which is maintained, and can be used to achieve the same thing
- We use it in only one check and for its legacy version it seems
- It's not used in extras, marketplace nor internal
- Even if `uptime` is lightweight, that's still one less deps to ship with the agent
> Stop using the uptime library

- kafka_consumer/changelog.d/19819.fixed
- kafka_consumer/datadog_checks/kafka_consumer/client.py
- kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
- kafka_consumer/tests/test_client.py
- kafka_consumer/tests/test_unit.py
Renames `describe_consumer_groups` to `describe_consumer_group` and stops returning `group_id`. 
This function only describes one consumer group at a time, the `consumer_group` argument. Furthermore, since it's passed in as an argument, there's no need to return the `group_id`. 
follow-up to https://github.com/DataDog/integrations-core/pull/19744
> Rename `describe_consumer_groups` and don't return `group_id`

- .github/workflows/pr-test.yml
Stop running compute_matrix on merge_group
it always fails due to lack of `github.event.pull_request.head.sha` and `github.event.pull_request.base.sha`, and we don't run tests in merge_group so it's not needed
> dont run compute_matrix on merge_group

- mesos_slave/hatch.toml
- mesos_slave/tests/common.py
- mesos_slave/tests/compose/docker-compose.yml
Adds `privileged: true` to the mesos slave service. 
Pins the zookeeper version.
> [!WARNING]
> We don't know why adding `privileged: true` solves the issue but it does. 🤷  
Tests on Ubuntu 22.04 were failing with:
```
E           mesos-slave-1  | E0319 12:51:34.982699 209223 main.cpp:483] EXIT with status 1: Failed to create a containerizer: Could not create DockerContainerizer: Failed to create docker: Failed to find a mounted cgroups hierarchy for the 'cpu' subsystem; you probably need to mount cgroups manually
```
> [AI-5059] Handle Mesos Slave for Ubuntu-22.04

- .github/workflows/build-deps.yml
It fixes the manual trigger for deps resolution.
It does so by replacing `github.ref` by `github.ref_name`, based on [this debug job](https://github.com/DataDog/integrations-core/actions/runs/13970294300/job/39110129009#step:2:16) that I created ad-hoc:
```
github.event_name = workflow_dispatch
github.ref = refs/heads/alopez/fix-build-deps-workflow-dispatch
github.ref_name = alopez/fix-build-deps-workflow-dispatch
github.event.repository.default_branch = master
github.event.ref = refs/heads/alopez/fix-build-deps-workflow-dispatch
```
That is, the `ref` includes the `refs/heads` suffix which makes it not match the name of the default branch, whereas `ref_name` does include just the name of the branch. This should work with main, too.
I discovered that it wasn't running the `publish` job …
> Fix Workflow Dispatch for build deps workflow

- tekton/tests/common.py
- tekton/tests/test_e2e.py
Adds more optional metrics in tests 
tekton integration e2e tests started flaking https://github.com/DataDog/integrations-core/actions/runs/13951715127/job/39053051152
> Add more optional metrics in tests

- gke/README.md
A bit of cleanup on the GKE install page:
- Cleans up description for what GKE is and what Datadog does. Don't really need to compare it to AWS.
- Gets rid of section for creating a new `doglib` cluster. This is not necessary and was a point of confusion for a few users.
- Modified to "Kubernetes integration" instead of "GKE integration" and provided a bit more context towards the K8s setup in general and Autopilot.
Internally tracking: [TEEP-384](https://datadoghq.atlassian.net/browse/TEEP-384)
Started with removing the `doglib` cluster instructions but became just a general touch up for this doc.
[TEEP-384]: https://datadoghq.atlassian.net/browse/TEEP-384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cleanup for GKE recommendations

- mysql/changelog.d/19908.changed
- mysql/datadog_checks/mysql/statement_samples.py
Show a warning if the `explain_plan` statement is missing in the schema.
Alert customers about a problem in the execution plan collection. For example, Believe (1000143129), a heavy APM/DBM user, never gets execution plan in APM traces due to the missing function.
> Warning for missing explain_plan function

- cisco_aci/assets/logs/cisco-aci.yaml
- cisco_aci/assets/logs/cisco-aci_tests.yaml
Add assets for new logs being sent by Cisco ACI integration in https://github.com/DataDog/integrations-core/pull/19836.
> Logs integrations assets for Cisco ACI integration faults sent as logs.

- mongo/changelog.d/19798.added
- mongo/datadog_checks/mongo/dbm/utils.py
Backport https://github.com/DataDog/integrations-core/commit/0c8fdf35338c1ae20789e90a513e1f500c699c4e to fix a high severity issue that causes MongoDB to crash due to explaining queries with `$mergeCursors` stage
* skip explain aggregation pipeline with  stage
* add changelog
Backport to `7.64.x` to fix a high severity issue reported by customer. The mongo integration samples running operations and explains the operation to gather execution plan. When it tries to explain an aggregation pipeline with `$mergeCursors` stage, it potentially caused MongoDB database engine to crash. The issue is escalated from the customer to MongoDB support with below explanation
```
For aggregations which target at least two shards for a sharded collection, the original aggregation is run in the following …
```
> Backport: [mongo] skip explain aggregation pipeline with mergeCursors stage (#19798)

- sqlserver/changelog.d/19921.fixed
- sqlserver/datadog_checks/sqlserver/queries.py
Replaces a `like` in the SQL Server deadlock query with an `=` since there is no wildcard in the target string.
This will improve performance on the query.
> Remove unnecessary 'like'

- .github/workflows/resolve-build-deps.yaml
I strongly associate this workflow with the word "resolve", so it's hard for me to find it without that anchor.
There are also places where this is referred to as "dependency resolution", so I'm not a unicorn.
As for the "Publish artifacts" job, I forgot that it also opened a PR until I re-read it. Adding that to the job title as a breadcrumb for later.
> Make dependency resolution workflow names more explicit

- vsphere/changelog.d/19944.fixed
- vsphere/datadog_checks/vsphere/vsphere.py
- vsphere/tests/test_unit.py
Stops submitting property metrics with 'unknown' hostname, now sends with None so it is either empty or the agent default hostname.
support case
> Don't submit property metrics with unknown hostname

- datadog_checks_base/datadog_checks/base/stubs/aggregator.py
- datadog_checks_base/tests/stubs/test_assert_metric.py
Add comment describing how to assert a metric was submitted with an empty hostname in `assert_metric`. The base check's `_submit_metric` method converts a hostname submitted with None to "": https://github.com/DataDog/integrations-core/blob/7.65.x/datadog_checks_base/datadog_checks/base/checks/base.py#L760, so to assert that a metric has an empty hostname, you must assert `hostname=""`
> Add comment and test about how to assert empty hostname in `assert_metric`

- ibm_mq/assets/configuration/spec.yaml
- ibm_mq/changelog.d/19912.added
- ibm_mq/datadog_checks/ibm_mq/collectors/stats_collector.py
- ibm_mq/datadog_checks/ibm_mq/config.py
- ibm_mq/datadog_checks/ibm_mq/config_models/defaults.py
- ibm_mq/datadog_checks/ibm_mq/config_models/instance.py
- ibm_mq/datadog_checks/ibm_mq/data/conf.yaml.example
- ibm_mq/datadog_checks/ibm_mq/stats/base_stats.py
- ibm_mq/datadog_checks/ibm_mq/stats/channel_stats.py
- ibm_mq/datadog_checks/ibm_mq/stats/queue_stats.py
- ibm_mq/tests/test_ibm_mq_unit.py
Old change that I had laying around that solved an escalation. https://datadoghq.atlassian.net/browse/AGENT-12517
The customer had a timezone set in their ibm mq instance that wasn't UTC, as a result a lot of their metrics were not getting collected as the check would think they were too old.
Not sure how to test it, but it was confirmed working here:
https://datadoghq.atlassian.net/browse/AGENT-12794
> Allow timezone config option to be used in metric collection

- sqlserver/changelog.d/19930.fixed
- sqlserver/datadog_checks/sqlserver/queries.py
- sqlserver/tests/compose-ha/sql/aoag_primary.sql
- sqlserver/tests/compose-high-cardinality-windows/setup.sql
- sqlserver/tests/compose-high-cardinality/setup.sql
- sqlserver/tests/compose-windows/setup.sql
- sqlserver/tests/compose/setup.sql
- sqlserver/tests/test_metadata.py
Add testing and support for case-sensitive collations in SQL Server.
Currently if users choose a case-sensitive collation one of our schema queries fails with the wrong case.
> Add support for case sensitive collations in SQL Server

- .github/workflows/config/labeler.yml
We'd apply the `changelog/no-changelog` label for any PRs that don't modify specific paths.
Only apply `changelog/no-changelog` label for release PRs.
Firstly, the labeler config's logic is a subset of the changelog check github action. No point having this in 2 places, the changelog check has proven to be reliable.
Secondly, [PRs like this](https://github.com/DataDog/integrations-core/pull/19931) trick the labeler into applying the label and thus stopping the changelog check.
> Weaken conditions for applying the no-changelog label

- mongo/datadog_checks/mongo/dbm/utils.py
This PR excludes `createIndexes` operation in explain collection. 
`createIndexes` is not explanable.
```json
[{"code":"OperationFailure","message":"Cannot explain cmd: createIndexes, full error: {'ok': 0.0, 'errmsg': 'Cannot explain cmd: createIndexes', 'code': 20, 'codeName': 'IllegalOperation', '$clusterTime': {'clusterTime': Timestamp(1743171592, 5), 'signature': {'hash': b'\\x19\\x12[\\xea\\xc5\\xb0a6T.\\xd5\\xbeq\\xd6O\\x9a\\x88\\x02J\\xaf', 'keyId': 7486515201114636293}}, 'operationTime': Timestamp(1743171592, 5)}"}]
```
> Exclude createIndexes operation in explain collection

- postgres/changelog.d/19969.fixed
- postgres/datadog_checks/postgres/explain_parameterized_queries.py
- postgres/datadog_checks/postgres/statement_samples.py
- postgres/datadog_checks/postgres/util.py
- postgres/tests/test_statements.py
This PR adds error handling for the `IndeterminateDatatype` error in the Postgres statement samples collection. This error occurs when PostgreSQL cannot determine the data type of a parameter in a query and explicitly handling this case  will allow us to surface a clearer error message in the agent logs and in the UI.
Jira tickets:
- https://datadoghq.atlassian.net/browse/DBMON-5129
- https://datadoghq.atlassian.net/browse/SDBM-1618
- https://datadoghq.atlassian.net/browse/SDBM-1494
> [PostgreSQL] Add handling for IndeterminateDatatype error

- mongo/changelog.d/19990.fixed
- mongo/datadog_checks/mongo/dbm/utils.py
This PR skips explain `shardCollection` operation because it is not explainable. 
Fix error `not authorized on admin to execute command { explain: { shardCollection: "collection", key: { _id: "hashed" }`
> [mongo] shardCollection operation is not explainable

- vsphere/changelog.d/19987.added
- vsphere/datadog_checks/vsphere/vsphere.py
Add failover support with Agent High Availability feature
HA Working as expected for vSphere:
^ as we can see, the `vsphere.cluster.count` metric is first reporting by the agent1 and then agent2 when the active agent switched.
> Add failover support with Agent High Availability feature

- foundationdb/changelog.d/19771.fixed
- foundationdb/datadog_checks/foundationdb/check.py
- foundationdb/tests/test_foundationdb.py
This change fixes an issue where the FoundationDB integration appears to accept user-provided tags, but then does not actually apply them to metrics/service checks/events. This fixes #19769.
In a use case where an operator has several FoundationDB clusters, it can be helpful to apply different sets of tags to different clusters.
> Honor `tags` instance configuration in FoundationDB integration

- postgres/changelog.d/19998.fixed
- postgres/datadog_checks/postgres/explain_parameterized_queries.py
- postgres/datadog_checks/postgres/statement_samples.py
- postgres/datadog_checks/postgres/util.py
This PR adds error handling for the `UndefinedFunction` error in the Postgres statement samples collection. This error can occur when a function is not given the right parameters in a statement. In our case, this is likely because of obfuscation (ex. original query `'hi' + myString`, new query `'hi' + $1` and `$1` is not a string). Explicitly handling this case  will allow us to surface a clearer error message in the agent logs and in the UI.
Jira ticket: https://datadoghq.atlassian.net/browse/SDBM-1611
> [PostgreSQL] Add handling for UndefinedFunction error

- LICENSE-3rdparty.csv
- agent_requirements.in
- datadog_checks_base/pyproject.toml
pins `urllib3`, a transitive dep of requests that we sometimes use
we use it here:
https://github.com/DataDog/integrations-core/blob/d44b9cb4cc9ff8db559a067e8c3e5bc926653f6a/datadog_checks_base/datadog_checks/base/__init__.py#L8 
and here https://github.com/DataDog/integrations-core/blob/master/datadog_checks_base/datadog_checks/base/log.py#L166-L170
and https://github.com/DataDog/integrations-core/blob/master/datadog_checks_base/datadog_checks/base/utils/http.py#L20
if they reorganize their imports/package structure that could potentially break things for us
> [AI-5184] pin urllib3

- otel/assets/dashboards/otel_collector_metrics_dashboard.json
Reverts DataDog/integrations-core#19980
leads to dashboard breakage
> Revert "[OTAGENT-359] use equiv_otel in DD exporter and connector metrics"

- postgres/README.md
This PR includes Autodiscovery v2 Annotations for collecting metrics from a postgres database.
Documentation should always support the latest versions of software. Future configurations would, hopefully use the Autodiscovery Annotations v2 configuration instead which would make deprecating Autodiscovery Annotations v1 easier in the future.
> update postgres ECS docs to include Autodiscovery v2 Annotations

- snmp/changelog.d/20021.changed
- snmp/pyproject.toml
Bumps the minimum datadog-base-check dependency version to >= 37.9.0.
Fix the Nightly minimum base check CI test because of a recent change in our pyyaml usage.
> Bump minimum base check version for SNMP to 37.9.0

- gpu/assets/dashboards/network_metrics.json
- gpu/manifest.json
Sets up a skeleton for an empty dashboard for networking metrics
> [NWL-807] Add empty dashboard + set up dashboard in manifest

- .ddev/config.toml
We pinned pymongo[srv] previously, but this didn't work. This fixes the pin as the dependency is pymongo and not pymongo[srv]
This was bumped once:
https://github.com/DataDog/integrations-core/pull/19610
Reverted here:
https://github.com/DataDog/integrations-core/pull/19814
> Pin pymongo dependency correctly

- esxi/changelog.d/20022.fixed
- esxi/datadog_checks/esxi/check.py
- esxi/tests/test_unit.py
Add support for custom tags in esxi integration
customer request and we should have supported this before
> [AGENT-13541] Properly support for custom tags in esxi

- cisco_aci/assets/dashboards/cisco_aci_dashboard.json
- cisco_aci/assets/monitors/critical_fault.json
- cisco_aci/manifest.json
Add Cisco ACI critical fault sample monitor.  Add Faults to Cisco ACI dashboard.
> Add Cisco ACI critical fault sample monitor.  Add Faults to Cisco ACI dashboard.

- postgres/changelog.d/20035.added
- postgres/datadog_checks/postgres/discovery.py
- postgres/datadog_checks/postgres/metrics_cache.py
- postgres/datadog_checks/postgres/postgres.py
- postgres/datadog_checks/postgres/util.py
- postgres/tests/common.py
- postgres/tests/test_pg_integration.py
- postgres/tests/test_replication_slot.py
(This is a draft PR)
JIRA - https://datadoghq.atlassian.net/browse/ADPPOS-2295 
This PR adds replication slot name and replication slot type to Postgres replication stat metrics.
Testing -
Getting Postgres replication slot information is helpful to know what type of replication (physical or logical) is lagging behind the primary instance and set up monitoring and alerting accordingly.
> add replication slot information and replication slot type to postgres replication stat metric

- istio/README.md
There was a previous change (https://github.com/DataDog/integrations-core/pull/19344) which altered the Autodiscovery Annotations for the Control Plane (`istiod`) portion of the monitoring. This effectively reverts that change. 
The annotations provided were already the Autodiscovery V2 syntax, so it wasn't necessary to add these in. This placed the valid V2 annotations in the V1 tab. The V2 annotations added in are invalid.
> Fix Autodiscovery Annotations for Istio Control Plane

- .cursor/rules/testing.mdc
Fixes a small typo in the cursor rules: `pbouncer` -> `pgbouncer`
> Fix small typo in cursor rules

- gunicorn/changelog.d/20059.added
- gunicorn/datadog_checks/gunicorn/gunicorn.py
- gunicorn/tests/test_unit.py
Adds NoSuchProcess during search for master process.
While we have NoSuchProcess exception handling while scraping GUnicorn workers, we don't have that functionality when looking at master procs during the first scan. This has caused issues like: https://github.com/DataDog/integrations-core/issues/19637.
> Add `NoSuchProcess` exception handling

- http_check/assets/configuration/spec.yaml
- http_check/changelog.d/20062.added
- http_check/datadog_checks/http_check/config_models/defaults.py
- http_check/datadog_checks/http_check/data/conf.yaml.example
Add defaults for `days_critical` and `days_warning` config options
https://github.com/DataDog/integrations-core/issues/19416
> Add defaults for `days_critical` and `days_warning` config options

- mysql/assets/configuration/spec.yaml
- mysql/changelog.d/20008.added
- mysql/datadog_checks/mysql/activity.py
- mysql/datadog_checks/mysql/config.py
- mysql/datadog_checks/mysql/config_models/defaults.py
- mysql/datadog_checks/mysql/config_models/instance.py
- mysql/datadog_checks/mysql/data/conf.yaml.example
- mysql/tests/test_query_activity.py
Implements MySQL blocking queries for MySQL 8.
High demand.
A slight decrease in performance when grabbing active sessions:
28.8% might look severe, but the response times are still under 10ms.
> MySQL blocking queries

- mysql/assets/configuration/spec.yaml
- mysql/changelog.d/20068.added
- mysql/datadog_checks/mysql/activity.py
- mysql/datadog_checks/mysql/data/conf.yaml.example
Adds blocking queries support for MySQL versions lower than 8.
High demand
> Blocking queries for older MySQL releases

- mysql/assets/configuration/spec.yaml
- mysql/changelog.d/20074.added
- mysql/datadog_checks/mysql/activity.py
- mysql/datadog_checks/mysql/data/conf.yaml.example
Add blocking queries support for MariaDB.
High demand
> Add blocking queries support for MariaDB

- mysql/changelog.d/20090.added
- mysql/datadog_checks/mysql/databases_data.py
When collecting mySQL schemas, if we lack proper permissions but the config is enabled, we will silently fail to pull table data. MySQL will not error. This PR adds a warning to indicate this case. Also small improvement to string concatenation logic and a missing return value. 
Experienced lack of visibility first hand.
> Print permission mySQL warning

- mysql/changelog.d/20089.fixed
- mysql/datadog_checks/mysql/databases_data.py
Adds `database_instance` to the MySQL schema data.
This fixes a problem where MySQL schema data isn't associated correctly in REDAPL.
> Pass database instance for MySQL schema data

- mysql/changelog.d/20095.fixed
- mysql/datadog_checks/mysql/statement_samples.py
- mysql/tests/test_statements.py
This fixes two issues observed with collection of mysql explain plan samples
1. Explain plan samples were incorrectly using the query end time as the event timestamp. This can lead to events populating in the past and if too far back will get rejected. We're now using collection time as the event timestamp. This brings us in line with how we generate events elsewhere in mysql and our other DBM supported dbms types.
2. Upon fixing this timestamp issue it became prevalent that some explain plans seem to be emitted every 4 minutes indefinitely. This was tracked down to opening a connection session, issuing a query and sitting idle on the connection. Queries will remain in `performance_schema.events_statements_current` until the connection is closed or the next query is issued. The …
> [DBMON-5158] Fix duplicate mysql explain plan samples submitting in the past

- mysql/CHANGELOG.md
- mysql/changelog.d/19341.added
- mysql/datadog_checks/mysql/__about__.py
- postgres/CHANGELOG.md
- postgres/changelog.d/19341.added
- postgres/datadog_checks/postgres/__about__.py
- requirements-agent-release.txt
- sqlserver/CHANGELOG.md
- sqlserver/changelog.d/19341.added
- sqlserver/datadog_checks/sqlserver/__about__.py
* [Release] Bumped mysql version to 15.1.0
* [Release] Bumped postgres version to 22.10.0
* [Release] Bumped sqlserver version to 22.2.0
* [Release] Update metadata
> Release `postgres`, `mysql`, and `sqlserver` (#20102)

- sqlserver/changelog.d/20097.fixed
- sqlserver/datadog_checks/sqlserver/statements.py
Updates the query metrics collection query for azure sql databases, for which sometimes a left join on sys.databases won't work, per the following [remarks](https://learn.microsoft.com/en-us/sql/t-sql/functions/db-id-transact-sql?view=sql-server-ver16#remarks)
> Use DB_NAME for query metrics in an azure sql database

- postgres/changelog.d/20096.added
- postgres/datadog_checks/postgres/statements.py
- postgres/pyproject.toml
- postgres/tests/test_statements.py
This is a follow up PR to https://github.com/DataDog/integrations-core/pull/20037. Adding `calls` to statement metrics `execution_indicators` to ensure the integration does not emit query metrics with `count=0`. 
https://datadoghq.atlassian.net/browse/DBMON-4170
> [postgres] Add calls to query metrics derivative compute execution_indicators

- foundationdb/changelog.d/19682.added
- foundationdb/datadog_checks/foundationdb/check.py
- foundationdb/tests/test_foundationdb.py
This pull request adds additional tags to existing FoundationDB process metrics to help operators identify which roles the associated processes are performing.
FoundationDB processes can take on one or more roles within a cluster. When scaling a cluster, operators generally add new processes for overloaded roles. The heuristics for "overloaded" vary by process, but basic indicators like CPU utilization often give helpful first-order clues for where to begin.
Before this change, each process would report metrics (like CPU utilization) such that each metric was tagged with the process ID. We _can_ use the process ID in conjunction with additional external tools to identify the roles a process is performing, but it would be much more convenient if the process metrics were already tagged by …
> Tag FoundationDB process metrics with process class, assigned roles

- ddev/changelog.d/20117.added
- ddev/src/ddev/cli/validate/licenses.py
In a recent run of the [Update Dependencies workflow](https://github.com/DataDog/integrations-core/actions/runs/14566016802/job/40855350575), the job failed because license could not be found for the `urlib3` package.
This PR updates the `ddev validate licenses` command to ensure that we evaluate the newer `license-expression` that caused this to fail.
Update all dependencies
```
hatch run ddev dep updates --sync
Files updated: 11
Updated 13 dependencies
```
Validate them before adding `license-expression` to ensure the display error was fixed
```
hatch run ddev validate licenses --sync
Validating main licenses.
Generating CSV lines.: 100%|██████████| 72/72 [00:19<00:00,  3.74pkgs/s]
Licenses
└── urllib3
no license information
Errors: 1
```
Validate them after the full fix to ensure we …
> Update ddev validate licenses command to support license expression

- otel/assets/dashboards/otel_collector_metrics_dashboard.json
2nd attempt to roll forward https://github.com/DataDog/integrations-core/pull/19980
- Add equiv_otel to DD exporter and connector internal metrics on OOTB OTel collector health dashboard
- Remove group-by-host from these graphs. It is a bad practice and leads to pressure to queries
- Change as_rate to per_second in these graphs since as_rate does not work with equiv_otel. as_rate and per_second are semantically equivalent
- Add a note to the top that customers need to opt in to equiv_otel preview if they want to use it elsewhere
This is tested in [a cloned dashboard in org 2](http://app.datadoghq.com/dashboard/7k9-478-p8r/opentelemetry-collector-metrics-dashboard-with-equivotel?fromUser=false&refresh_mode=sliding&from_ts=1744919883623&to_ts=1744923483623&live=true). …
> [OTAGENT-359] use equiv_otel in DD exporter and connector graphs

- elastic/README.md
- elastic/changelog.d/20121.added
- elastic/datadog_checks/elastic/config.py
- elastic/tests/test_config.py
This PR sanitizes the user and password from our `url` tag when the `url` configuration option is supplied with them.
When setting up an instance of Elasticsearch, it can be set-up with a YAML file containing the url in the format `http://<USER>:<PASSWORD>@<ENDPOINT>`
ex: 
```
init_config: {}
instances:
- url: http://user:hunter2@127.0.0.1:9200/
cluster_stats: false
index_stats: false
pending_task_stats: false
```
In this case the full URL, including the `user:password` show up in the `url` tag  in the Web UI.
> [elastic] Sanitize user and password from url tag

- mysql/changelog.d/20092.fixed
- mysql/datadog_checks/mysql/metadata.py
During metadata collection for MySQL, we sometimes lose the connection on some databases due to it not being used for a while. This will call the pymysql ping() method which will trigger a check and reconnect if the connection was lost. 
A customer noticed that settings collection worked on the first fetch but then failed on the underlying connection being lost. Reducing the interval to 60s instead of 600s fixed it for them, which adds confidence that a check for the connection still being established (and potential reconnect) would be necessary.
> Make the pymysql connection ping() to reconnect for metadata collection

- postgres/assets/configuration/spec.yaml
- postgres/datadog_checks/postgres/data/conf.yaml.example
This PR will just hid the query_activity.collection_interval option in the `conf.yaml` to prevent misuse.
[DBMON-5020](https://datadoghq.atlassian.net/browse/DBMON-5020)
[DBMON-5020]: https://datadoghq.atlassian.net/browse/DBMON-5020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DBM] [Postgres] Hides the query_activity.collection_interval option to prevent misuse

- postgres/changelog.d/20137.added
- postgres/datadog_checks/postgres/metadata.py
- postgres/tests/compose/resources/03_load_data.sh
- postgres/tests/test_metadata.py
Include foreign tables in dbm agent schema collection for postgres https://datadoghq.atlassian.net/browse/DBMON-4167
https://datadoghq.atlassian.net/browse/DBMON-4167
Manual Test:
> Include foreign tables in DBM agent schema collection

- .pre-commit-config.yaml
- datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/service_checks.py
- datadog_checks_dev/datadog_checks/dev/tooling/manifest_utils.py
Recently we have removed service checks validations from our CI since APW is doing this validation now (see #19835). Since CI is doing a more official validation of assets for us now, this PR removes the service checks validation from `pre-commit`.
It also fixes the validation, in case we want to run it, to ensure it does not break if no `service_checks` path is defined in the manifest of the integration. This is the case for more recent integrations like [infiniband](https://github.com/DataDog/integrations-core/blob/master/infiniband/manifest.json#L23-L38) and [check_point_harmony_email](https://github.com/DataDog/integrations-core/blob/master/checkpoint_harmony_email_and_collaboration/manifest.json#L39-L46). These do not have service checks and, therefore, there is no path for them in …
> Fix service-checks validation and remove them from pre-commit

- sqlserver/assets/configuration/spec.yaml
- sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
This PR will just hid the query_activity.collection_interval option in the conf.yaml to prevent misuse.
[DBMON-5019](https://datadoghq.atlassian.net/browse/DBMON-5019)
[DBMON-5019]: https://datadoghq.atlassian.net/browse/DBMON-5019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DBM] [SQL Server] Hides the query_activity.collection_interval option to prevent misuse

- mysql/assets/configuration/spec.yaml
- mysql/datadog_checks/mysql/data/conf.yaml.example
This PR will just hid the query_activity.collection_interval option in the conf.yaml to prevent misuse.
[DBMON-5021](https://datadoghq.atlassian.net/browse/DBMON-5021)
[DBMON-5021]: https://datadoghq.atlassian.net/browse/DBMON-5021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DBM] [MySQL] Hides the query_activity.collection_interval option to prevent misuse

- mongo/assets/configuration/spec.yaml
- mongo/changelog.d/20135.added
- mongo/datadog_checks/mongo/collectors/db_stat.py
- mongo/datadog_checks/mongo/config.py
- mongo/datadog_checks/mongo/config_models/defaults.py
- mongo/datadog_checks/mongo/config_models/instance.py
- mongo/datadog_checks/mongo/data/conf.yaml.example
- mongo/tests/fixtures/dbstats-non-free-storage-admin
- mongo/tests/fixtures/dbstats-non-free-storage-config
- mongo/tests/fixtures/dbstats-non-free-storage-local
- mongo/tests/fixtures/dbstats-non-free-storage-test
- mongo/tests/mocked_api.py
- mongo/tests/results/metrics-dbstats-non-free-storage.json
- mongo/tests/test_integration.py
This PR will add a new configuration called `free_storage_metrics` to the mongo integration that would allow customers to disable collecting free storage metrics.
[DBMON-5228](https://datadoghq.atlassian.net/browse/DBMON-5228)
[DBMON-5228]: https://datadoghq.atlassian.net/browse/DBMON-5228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [mongo] Provide a way to optionally disable collecting free storage metrics

- strimzi/tests/common.py
This metric been flaky here and there.
> Add `strimzi.cluster_operator.reconciliations.locked.count` metric as flaky

- mongo/changelog.d/20149.fixed
- mongo/datadog_checks/mongo/dbm/utils.py
This PR skips explaining `serverStatus` command. 
https://datadoghq.atlassian.net/browse/DBMON-5242
> [mongo] serverStatus cannot be explained

- foundationdb/changelog.d/19706.added
- foundationdb/datadog_checks/foundationdb/check.py
- foundationdb/metadata.csv
- foundationdb/tests/common.py
- foundationdb/tests/test_foundationdb.py
This introduces a new, single `foundationdb.processes_per_role` gauge that is tagged by `fdb_role` and `fdb_process_class`. It makes no changes to existing metrics.
There are two main motivations for this new gauge:
1. The set of role types in a FoundationDB cluster can change from version to version. For example, FoundationDB 6.x had a notion of a `proxy` role, but in FoundationDB 7.x, that role is gone and has been replaced by `grv_proxy` and `commit_proxy`. Using tags (instead of individual gauges) to count processes by role gives this integration more flexibility to work with different versions of FoundationDB.
2. Having processes tagged by role gives operators a mechanism by which they can detect if a single process is performing multiple roles. For example, in a heavily-loaded …
> Consolidate process count metrics

- slurm/changelog.d/20170.added
- slurm/datadog_checks/slurm/check.py
- slurm/datadog_checks/slurm/constants.py
- slurm/tests/common.py
- slurm/tests/fixtures/squeue.txt
Adding slurm_partition_name to job metrics. The tag is added in squeue metrics and duplicated in sacct metrics. This is to easier correlate them if they have a single unified tag.
> Add slurm_partition_name to job metrics

- .github/workflows/build-ddev.yml
- .github/workflows/claim-pypi-name.yaml
- .github/workflows/release-base.yml
- .github/workflows/release-dev.yml
This PR updates the PyPi tokens used to publish images using the new created ones. After validating that workflows work we will replace them back with the proper naming.
Scheduled secrets rotation
> Update GH workflows to use new PiPy keys

- .github/workflows/claim-pypi-name.yaml
After merging #20178 we have validated that the new key works. Successful run [here](https://github.com/DataDog/integrations-core/actions/runs/14755277804) that was run with the commit after merging the PR [234e046](https://github.com/DataDog/integrations-core/commit/234e04695bbad447a8d44c2eb031d976d7a6150e).
Finalize rotation of this PyPi secret
> Rename the name squatting PyPi key after rotation

- teleport/README.md
Fix broken link to external Teleport documentation
Customer noted broken link in the ticket: https://datadog.zendesk.com/agent/tickets/2119183
> Fix broken link in Teleport documentation

- ddev/CHANGELOG.md
- ddev/changelog.d/19971.fixed
- ddev/changelog.d/20117.added
[Bumped ddev version to 11.3.0](https://github.com/DataDog/integrations-core/commit/7f7f198958c3ded8a1265bf3703685e95edaeb05)
> [Release] Bumped ddev version to 11.3.0

- .github/workflows/resolve-build-deps.yaml
We use the "Agent Platform" bot to open the PR after resolving and building dependencies.
We use the "Agent Integrations" bot to open the PR after resolving and building dependencies.
Easier maintenance: no need to coordinate between teams when rotating the token.
> Use Agent Integrations bot to open PR when resolving dependencies

- .ddev/ci/scripts/singlestore/linux/55_set_license_secret.sh
- .github/workflows/test-fips-e2e.yml
- .github/workflows/test-target.yml
- singlestore/tests/compose/docker-compose.yaml
- singlestore/tests/conftest.py
- singlestore/tests/test_integration.py
backports "update singlestore image and version used in CI (#20207)" to fix ci
> [Backport 7.66.x] Update singlestore image and version used in CI (#20207)

- mysql/assets/configuration/spec.yaml
- mysql/changelog.d/20176.added
- mysql/datadog_checks/mysql/aws.py
- mysql/datadog_checks/mysql/config_models/instance.py
- mysql/datadog_checks/mysql/data/conf.yaml.example
- mysql/datadog_checks/mysql/mysql.py
- mysql/pyproject.toml
Adds IAM authentication support to MySQL
Validated this in `dbm-sandbox`:
```
instances:
- host: mysql-iam-auth-2-rdsinstance-g1qvdicrqyhg.cn6qqa2qkfmv.us-east-2.rds.amazonaws.com
port: 3306
dbm: true
username: datadog
ssl:
ca: /usr/src/global-bundle.pem
check_hostname: false
aws:
region: us-east-2
instance_endpoint: mysql-iam-auth-2-rdsinstance-g1qvdicrqyhg.cn6qqa2qkfmv.us-east-2.rds.amazonaws.com
managed_authentication:
enabled: true
role_arn: arn:aws:iam::074787506366:role/iam-ec2
```
> MySQL IAM Auth

- mysql/changelog.d/20226.fixed
- mysql/datadog_checks/mysql/mysql.py
Restores `HA_SUPPORTED = True`, which was inadvertently removed in a previous PR.
> Reenable HA

- redisdb/changelog.d/20227.added
- redisdb/datadog_checks/redisdb/redisdb.py
- redisdb/hatch.toml
Fix the following error of the `redisdb` check when executed against a Redis 8+ server:
```
redisdb (7.1.0)
---------------
Instance ID: redisdb:83469dfb5c3328af [ERROR]
Configuration Source: file:/etc/datadog-agent/conf.d/redisdb.d/auto_conf.yaml
Total Runs: 1
Metric Samples: Last Run: 7, Total: 7
Service Checks: Last Run: 1, Total: 1
Average Execution Time : 275ms
Last Execution Date : 2025-05-06 13:21:00 UTC (1746537660000)
Last Successful Execution Date : Never
Error: 'expires'
File "/opt/datadog-agent/embedded/lib/python3.12/site-packages/datadog_checks/base/checks/base.py", line 1301, in run
File "/opt/datadog-agent/embedded/lib/python3.12/site-packages/datadog_checks/redisdb/redisdb.py", line 554, …
```
> Fix `redisdb` check on Redis 8

- mysql/changelog.d/20222.fixed
- mysql/datadog_checks/mysql/activity.py
- mysql/tests/test_unit.py
Remove duplicate idle MySQL activity rows
Sampling idle blockers can produce rows for the statements that were already completed, because sometimes it can take longer to purge old statements from `performance_schema.events_statements_current`.
> Remove duplicate idle MySQL activity rows

- .github/workflows/validate-pinned-actions.yml
This is a safe guard to ensure that master always run this in case someone merged skipping validations. This is also needed so the status check is visible in GitHub repo settings for some reason.
Allow the status check to be configured as a requried status check on PRs.
> Ensure Validate Pinned Actions run on master

- mysql/assets/configuration/spec.yaml
- mysql/datadog_checks/mysql/config_models/defaults.py
- mysql/datadog_checks/mysql/config_models/instance.py
- mysql/datadog_checks/mysql/data/conf.yaml.example
- postgres/assets/configuration/spec.yaml
- postgres/datadog_checks/postgres/config_models/defaults.py
- postgres/datadog_checks/postgres/config_models/instance.py
- postgres/datadog_checks/postgres/data/conf.yaml.example
Adds `exclude_hostname` to Postgres and MySQL specs.
> Add exclude_hostname to Postgres and MySQL specs

- kubernetes_cluster_autoscaler/README.md
The Kubernetes Cluster Autoscaler does not work out of the box with the configuration listed in the README.md file.
The default container name changes depending on where it is deployed, and `controller` is not a valid container name for all deployments.
Abstracted the readme to highlight the fact that you need to specify the container name as part of the annotation instead of using `controller` for the container name.
In an AWS EKS deployment, the container name is `aws-cluster-autoscaler` and the integration didn't work out of the box with the instructions from the readme.
> Update README.md for kubernetes_cluster_autoscaler

- esxi/changelog.d/20271.changed
- esxi/pyproject.toml
- mongo/changelog.d/20271.changed
- mongo/pyproject.toml
- slurm/changelog.d/20271.changed
- slurm/pyproject.toml
Bump the minimum base check dependency in `slurm`, `esxi` and `mongo` extensions to the latest one. These were the only integrations that still had a base checks version with support for python 2. 
For `mongo` and `esxi` the python version has also been bumped to 3.12 to be coherent with the latest requirement in the base package.
Get out of python 2 support and [fix our CI](https://github.com/DataDog/integrations-core/actions/runs/14988644575) where python 2 construct are not available anymore.
> Bump minimum base version and python to 3.12 for slurm, esxi and mongo

- snmp/tests/test_e2e_python.py
Since PR https://github.com/DataDog/datadog-agent/pull/36207, the loader by default for SNMP is the Core one. This PR fix the failing `test_e2e_python` test which assumed that the loader by default is Python.
Tested with `ddev`, the `test_e2e_python` test was failing before the change, and it succeeds with the change.
> Fix test_e2e_python by specifying Python loader in config

- redisdb/changelog.d/20261.fixed
- redisdb/datadog_checks/redisdb/redisdb.py
- redisdb/tests/test_unit.py
Allow the slowlog collection to fail during the API call.
Some managed Redis do not allow the SLOWLOG GET command. 
This results in repeated error messages from the Redis CLI as there is no option to disable the slowlog collection.
>[!NOTE]
> Another solution would be to add a config parameter that allows to disable the slowlog collection.
> Allow slowlog collection to fail

- otel/assets/dashboards/otel_collector_metrics_dashboard.json
Fix DD connector & exporter graphs on OTel dashboard
Those graphs used to have as_rate() but  as_rate()  doesn't work with equiv_otel so we replaced  as_rate()  with per_second. It looks like for per_second  to work properly, the graphs need as_count() too
Tested in org [Datadog OpenTelemetry](http://app.datadoghq.com/dashboard/miv-gng-wvk/opentelemetry-collector-metrics-dashboard-with-equivotel?fromUser=false&refresh_mode=sliding&from_ts=1747152563648&to_ts=1747156163648&live=true). Graphs do show a difference in values before and after adding as_count()
[#incident-38288](https://dd.slack.com/archives/C08RQ56NV39/p1747148094858549)
> [OTELS-583] Fix DD connector & exporter graphs on OTel dashboard

- sqlserver/changelog.d/20293.added
- sqlserver/datadog_checks/sqlserver/xe_collection/base.py
- sqlserver/tests/test_integration.py
- sqlserver/tests/test_xe_collection.py
Add two missing pieces of info in the XE query_completion and query_error events:
1. Metadata: Added metadata section to all events with tables, commands, and comments
2. primary_sql_field: denote which field should be considered the primary sql field, and was used to generate the query signature. 
Building backend portion, need these fields.
> SQLServer XE add missing event fields

- sqlserver/assets/configuration/spec.yaml
- sqlserver/changelog.d/20301.added
- sqlserver/datadog_checks/sqlserver/const.py
- sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
- sqlserver/datadog_checks/sqlserver/sqlserver.py
* Adds the connection database to SQL Server database identifier
* Adds the Azure hostname minus the windows suffix to the identifier variables
Azure SQL Server pool users often use the database to distinguish between multiple DBM instances and may want to refer to the hostname without the suffix due to previous DBM behavior
> Add database to database identifier template variables

- requirements-agent-release.txt
- sqlserver/CHANGELOG.md
- sqlserver/changelog.d/20301.added
- sqlserver/datadog_checks/sqlserver/__about__.py
Backport sqlserver version 22.5.0 release
> [Backport] [Release] Bumped sqlserver version to 22.5.0

- postgres/changelog.d/20310.fixed
- postgres/datadog_checks/postgres/version_utils.py
Currently the Postgres integration always calls `aurora_version()` to check if the database is running on AWS Aurora. If it's not, the query fails with a function not found error. This leads to query errors in database logs. To avoid calling a function that won't exist outside of AWS Aurora environment, we will now lookup available postgres extensions. If aurora related extensions are available, we can assume we're running in AWS and will verify by querying the `aurora_version()`. Changes were made to the `VersionUtils.is_aurora()` to cache the results of the first execution as this shouldn't change over the lifetime of the connection.
Running this query on Aurora Postgres will return the following extensions
```sql
SELECT * FROM pg_available_extension_versions WHERE name ILIKE '%aurora%' …
```
> Only query aurora_version() if aurora postgres extensions are available 

- postgres/changelog.d/20316.fixed
- postgres/changelog.d/20316.fixed.1
- postgres/datadog_checks/postgres/util.py
This PR fixes a bug to add the `replication` prefix to our lag metrics - `postgresql.replication.wal_write_lag`, `postgresql.replication.wal_flush_lag`, `postgresql.replication.wal_replay._lag`. 
Earlier, this PR https://github.com/DataDog/integrations-core/pull/20035/files was created to add replication slot information to our existing lag metrics but in this change the lag metrics were not prefixed with `replication` . These metrics name got updated from `postgresql.replication.wal_write_lag`, `postgresql.replication.wal_flush_lag`, `postgresql.replication.wal_replay._lag` to postgresql.wal_write_lag`, `postgresql.wal_flush_lag`, `postgresql.wal_replay._lag` respectively in the latest agent release.
Test results
> fix Postgresql replication stat metrics to include replication prefix

- kube_scheduler/assets/dashboards/overview.json
This PR fixes a typo in the Kube Scheduler dashboard
Typo was found during a dash workshop dry run
> Fix `scheduling-attemps` typo

- .github/workflows/test-fips-e2e.yml
- .github/workflows/test-target.yml
- arangodb/tests/conftest.py
bumps codecov pin to > `4.2.0` to fix codecov uploads on forks
we're running into this issue: https://github.com/codecov/codecov-action/issues/1821
> Bump codecov action hash

- kafka/assets/dashboards/kafka_dashboard.json
https://datadoghq.atlassian.net/browse/DSMON-748
Update the kafka dashboard to include DSM metrics, with a callout to instrument with DSM
Current OOT Dashboard: https://app.datadoghq.com/dash/integration/50/kafka-zookeeper-and-kafka-consumer-overview
New version (feel free to copy + past json from diff if you'd like): https://app.datadoghq.com/dashboard/pqw-u3q-5tj/kafka-zookeeper-and-kafka-consumer-overview?fromUser=false&refresh_mode=sliding&from_ts=1747853399177&to_ts=1747856999177&live=true
> [Kafka][DSM] Update kafka ootb dashboard with dsm metrics

- wlan/manifest.json
makes the wlan integration public on the docs page
The agent release is live, and this integration is ready to be public.
> display wlan integration on docs

- mongo/tests/test_integration.py
- mysql/tests/conftest.py
- mysql/tests/test_mysql.py
- postgres/tests/test_pg_integration.py
- sqlserver/tests/test_integration.py
We had a couple of tests across the DBM integrations that were incorrectly doing assertion comparisons on `.sort()` which is an in place sort function that returns `None`. These changes fix the sorting to sort into a new list and actually compare the sorted results. It fixes expected tags where the tests were incorrect previously.
> [DBMON-5380] Fix incorrect tag assertion in tests

- sqlserver/assets/configuration/spec.yaml
- sqlserver/changelog.d/20342.added
- sqlserver/datadog_checks/sqlserver/const.py
- sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
- sqlserver/datadog_checks/sqlserver/sqlserver.py
- sqlserver/tests/test_integration.py
- sqlserver/tests/test_unit.py
This pull request introduces support for a new `$full_server_name` variable in the SQL Server integration for the `template` config key, which represents the full server name as returned by `@@SERVERNAME`. The changes include updates to constants, configuration templates, caching mechanisms, and tests to incorporate this new field.
* Added `STATIC_INFO_FULL_SERVERNAME` as a new constant in `sqlserver/datadog_checks/sqlserver/const.py` to represent the full server name.
* Updated the example configuration file (`sqlserver/datadog_checks/sqlserver/data/conf.yaml.example`) to include `full_server_name` as a new template option for identifying SQL Server instances.
* Modified `load_static_information` in `sqlserver/datadog_checks/sqlserver/sqlserver.py` to cache the `full_server_name` value. …
> Add  full_server_name support as template variable to sqlserver template config key

- ddev/tests/conftest.py
This is a small PR to ensure that the `local_clone` fixture does what we expect it to do. This fixture relies on the current state of the developer local repo which can cause tests to not have the lates version of origin. The test `test__utils.py` validates we are not too far behind with the number of integrations in our local repo but since we create `ddev-testing` by running
`git checkout -fB ddev-testing origin/master`
but after we have cloned the repo to a temporary directory, here, `origin` refers to our local repo not to the `origin` set in our local repo.
This causes that if the developr rarely uses their local `master` branch (work mostly with fetch rebase, for example), the expected fixture state is not ensured.
Ensure tests behave as expected independently of the current local …
> Modify local_clone fixture logic to ensure we use proper origin

- gpu/README.md
Improved instructions to deploy GPU Monitoring on mixed cluster (with gpu and non-gpu nodes) using helm chart
Customers struggled to fulfill the instructions based on the current version
> GPU: improve GPU mixed environment setup instructions

- ddev/tests/cli/config/test_override.py
Fixes a test that could fail when run in a specific order for the new override ddev command. We do this by ensuring the local override file is removed after each test (since tests run sequentially that should be enough) and also improve it by avoiding deleting the pyproject.toml of the local clone.
Ensure tests are stable.
> Fix flaky ddev override test

- agent_requirements.in
- datadog_checks_base/changelog.d/20358.added
- datadog_checks_base/pyproject.toml
Bumps `ddtrace` to v3 for performance improvements and general enhancements
> Bump ddtrace to 3.7.2

- .github/workflows/build-ddev.yml
- .github/workflows/claim-pypi-name.yaml
- .github/workflows/release-base.yml
- .github/workflows/release-dev.yml
This PR updates the actions that publish new packages to PyPi to use trusted publishers and run behind a given environment. Any run outside the appropriate environment won't be able to retrieve the short-lived JWT token.
For the typo squatting an environment has been defined to run only in `master` and the secret has been moved to the environment secrets. This will allow to remove repository secrets.
Improved security and reduce token rotation requirements.
> Migrate PyPi publishing to Trusted Publishers and environments

- .gitlab-ci.yml
This PR fixes the builder jobs in GitLab pipeline to only run when in master and there are changes on the specified paths. The current behavior builds it whenever it is in master OR there are changes in the files. This triggers builds from PR which is undesirable.
Fix when the builders should run.
> Fix builder jobs in gitlab pipeline

- .ddev/config.toml
Allow our weekly dependency update bot to bump `ddtrace`.
After https://github.com/DataDog/integrations-core/pull/20358 we don't have any reason not to update the library.
> Unpin ddtrace dependency

- docs/developer/ddev/multirepo.md
This PR fixes the valid repo names for the `ddev config override`. Before releasing the final version of the command we decided to simplify these names but forgot to update the documentation.
Proper docs.
> Fix the valid repos in the documentation page for the override command

- .cursor/rules/testing.mdc
Fixes the ddev word appearing twice in the cursor instructions.
> Fix duplicate ddev command in cursor instructions

- .github/workflows/validate-pinned-actions.yml
Adds a message to clarify why pinact failed to help the user troubleshooting it.
Make sure that when we want to update a pinned action we do not need to care about any pending PR using an older version as this message should help the user know they need to rebase their branch
> Add a step to guide users in case the pinact workflow is failing

- ecs_fargate/README.md
Removing callout: CNM now supports ECS Fargate
> Update ECS Fargate

- datadog_checks_base/changelog.d/20397.added
- datadog_checks_base/datadog_checks/base/utils/db/utils.py
- datadog_checks_base/tests/base/utils/db/test_util.py
Adds a new class TagManager to dbm's base utils module. This will be used to replace our current naive tag lists we maintain in the various dbms integrations. The goal of this class is to have an easy an efficient wrapper around tags that can allow us to efficiently perform CRUD type of operations on our list of tags in order to ensure that we can accurately modify tags over the life of the integration check as the source database values change and avoid emitting stale or inaccurate values.
This is being added in order to fix an issue that affects all of our python dbms integrations. Having shared logic will allow us to ensure tagging logic is implemented the same across integrations
> [DBMON-5404] Add TagManager class to dbm base utils

- appgate_sdp/manifest.json
This makes Appgate SDP integration documentation publicly available.
> Make Appgate docs public

- appgate_sdp/README.md
> Update Appgate SDP README

- gpu/README.md
- adds a minimal supported version requirement for the dd-operator
- adds additional config flags to override when using older versions of dd-operator for k8s deployment 
Better documentation for the customers that don't use the latest dd-operator version
> [GPUM:] updated onboarding documentation for deployment with dd-operator

- postgres/changelog.d/20266.added
- postgres/datadog_checks/postgres/metadata.py
- postgres/tests/test_metadata.py
Causes the agent to emit events with data about installed PostgreSQL extensions (i.e. sourced from `pg_extension`.
Scheduled feature development (see ticket)
> Dbmon 5125 collect postgres extensions in agent

- sqlserver/changelog.d/20424.fixed
- sqlserver/datadog_checks/sqlserver/activity.py
- sqlserver/datadog_checks/sqlserver/agent_history.py
- sqlserver/datadog_checks/sqlserver/deadlocks.py
- sqlserver/datadog_checks/sqlserver/metadata.py
- sqlserver/datadog_checks/sqlserver/metrics.py
- sqlserver/datadog_checks/sqlserver/schemas.py
- sqlserver/datadog_checks/sqlserver/sqlserver.py
- sqlserver/datadog_checks/sqlserver/statements.py
- sqlserver/datadog_checks/sqlserver/stored_procedures.py
- sqlserver/datadog_checks/sqlserver/xe_collection/base.py
- sqlserver/pyproject.toml
- sqlserver/tests/test_activity.py
- sqlserver/tests/test_database_metrics.py
- sqlserver/tests/test_integration.py
- sqlserver/tests/test_metrics.py
- sqlserver/tests/test_statements.py
- sqlserver/tests/test_stored_procedures.py
- sqlserver/tests/test_unit.py
- sqlserver/tests/test_xe_collection.py
* Migrates the SQLServer integration to use the new TagManager
* Fixes a race condition with certain database identifier template variables
Previously certain tags were set before the static info cache had been populated. This led to placeholders appearing in database instance identifiers.
> Update SQL server to TagManager

- mysql/tests/tags.py
- mysql/tests/test_mysql.py
- mysql/tests/test_query_activity.py
- mysql/tests/test_statements.py
This changes our expected tag constants to tuples instead of lists. This helps us guard against any accidental mutation of these tags which lead to leakage to our other tests and can cause difficult to debug unrelated to failures or incorrect test functionality.
Added skip-qa and no-changelog tags as these changes are only in our tests
While working on plumbing some new dynamic derived base tags this issue was a painful footgun to run into. Fixing this up to help avoid future toil and splitting it into its own PR for simple isolated review
> [DBMON-5429] Switch expected tags to tuples to avoid mutation leakage in tests

- repository.datadog.yaml
This patch enables warning messages sent over Slack to PR authors when the PR has an unsigned commit.
The warning is non-blocking to allow folks time to get their commits signed before enforcement goes into effect.
> chore: warn on unsigned commits

- mysql/changelog.d/20446.added
- mysql/datadog_checks/mysql/mysql.py
- mysql/datadog_checks/mysql/queries.py
- mysql/tests/tags.py
- mysql/tests/test_metadata.py
- mysql/tests/test_mysql.py
- mysql/tests/test_query_activity.py
- mysql/tests/test_statements.py
Adds `server_uuid` tag to mysql metrics and events. This is a unique uuid generated when the database is first created. We want to start adding this in preparation for identifying and building out a topology graph of replicated databases.
Note that server_uuid doesn't exist in MariaDB.
> [DBMON-5356] Add server_uuid tag to mysql metrics and events

- postgres/assets/configuration/spec.yaml
- postgres/datadog_checks/postgres/config_models/defaults.py
- postgres/datadog_checks/postgres/data/conf.yaml.example
This config option has been enabled by default in code since https://github.com/DataDog/integrations-core/pull/16895 but the example config still shows it disabled by default. Updating the example config to reflect reality also sets the `tag_replication_role` to hidden as we want this enabled by default and will be relied on for cluster support
> [DBMON-5438] Update out of date postgres tag_replication_role config example

- .github/workflows/pr-quick-check.yml
Updates the GHA that creates a comment when a major version fragment is found to avoid commenting multiple times in the same issue. 
In PRs where a major bump will be issued any revision triggers the same comment which makes the PR hard to navigate full of duplicates.
For example: #20451
> Modify GitHub action that comments on major bump warning to multiple comments

- nginx_ingress_controller/README.md
Add a mention in the documentation for the `collect_nginx_histograms` boolean that is required to have the histogram metrics collected by the agent.
The integration documentation lists metrics that will not be visible in datadog unless one provides the parameter in the instances configuration. This can easily lead to believing there is an issue with metrics collection since the additional (required) parameter to have all listed metrics is not mentioned in the page.
> doc(nginx-ingress-controller): mention the additional parameter required for histogram metrics

- ddev/changelog.d/20341.added
- ddev/src/ddev/cli/validate/metadata_utils.py
Adds nanodollar unit to the list of valid units. See https://github.com/DataDog/dd-source/pull/220160 and https://github.com/DataDog/dogweb/pull/142407 for corresponding PRs to add the nanodollar unit.
> [MLOB-2838] add nanodollar unit to list of valid metric units

- mongo/changelog.d/20515.fixed
- mongo/datadog_checks/mongo/api.py
- mongo/datadog_checks/mongo/collectors/conn_pool_stats.py
- mongo/datadog_checks/mongo/collectors/fsynclock.py
- mongo/datadog_checks/mongo/collectors/host_info.py
- mongo/datadog_checks/mongo/collectors/replica.py
- mongo/datadog_checks/mongo/collectors/replication_info.py
- mongo/datadog_checks/mongo/collectors/server_status.py
- mongo/datadog_checks/mongo/collectors/top.py
This PR adds `maxTimeMS` to limit agent resource consumption and prevent operations from running indefinitely on the server side. 
[maxTimeMS](https://www.mongodb.com/docs/manual/tutorial/terminate-running-operations/#maxtimems) ensures queries are properly terminated in addition to the client side operation timeout set by `timeoutMS`. 
https://datadoghq.atlassian.net/browse/SDBM-1738
> force maxTimeMS for mongo integration queries

- mysql/changelog.d/20514.fixed
- mysql/datadog_checks/mysql/databases_data.py
- mysql/datadog_checks/mysql/queries.py
Avoids a query to `INFORMATION_SCEMA.COLUMNS` that's currently made when schema collection is enabled. This query currently gets executed one time per 500 tables in a schema per check run to determine if a column exists for a subsequent query for index usage information. The `EXPRESSION` column was added in mysql 8.0.13 as noted in information_schema.columns [docs](https://dev.mysql.com/doc/refman/8.0/en/information-schema-statistics-table.html) and MariaDB does not support this so we can statically check the version and flavor to determine which query we should run
> [DBMON-5463] Switch sql index query resolution over to a static version check

- .builders/scripts/repair_wheels.py
Use JSON-based PyPI API instead of html-based one to determine whether a build was built.
I was seeing [this sort](https://github.com/DataDog/integrations-core/actions/runs/15675912436/job/44156055521?pr=20513) of failures while working on a PR. Digging a bit I realized that the logic that we use to determine whether a wheel was built by us or not, used to determine whether it needs to go through the repairing or not, wasn't properly filtering out wheels that shouldn't be repaired (ddtrace was the one with which it was failing).
What I found was that the page we were parsing ([ddtrace example](https://pypi.org/simple/ddtrace/)) has some extra newlines that split the link in two lines in the html source, breaking the regex-based parsing.
I found out that there's now a [JSON-based …
> Use json-based PyPI API instead of html-based one to determine whether a build was built

- foundationdb/changelog.d/19865.fixed
- foundationdb/datadog_checks/foundationdb/check.py
[Fix the FoundationDB check so that the 'tls_ca_file' and 'tls_password' options are respected.](https://github.com/DataDog/integrations-core/blob/master/foundationdb/datadog_checks/foundationdb/data/conf.yaml.example#L48)
They weren't being respected.
> FoundationDB: Respect 'tls_ca_file' and 'tls_password' config options

- datadog_checks_base/changelog.d/20528.added
- datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/scraper/__init__.py
- datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/scraper/base_scraper.py
- datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/scraper/decorators.py
- datadog_checks_base/tests/base/checks/openmetrics/test_v2/scraper/test_first_scrape_handler.py
- datadog_checks_base/tests/base/checks/openmetrics/test_v2/scraper/test_http_status_class_scraper.py
This PR adds a OpenMetricsScraper decorator that automatically adds `code_class` to the loaded OpenMetrics if an http code tag is configured.
It also moves the scraper module to a package preserving the existing import mechanism while allowing it to grow without making the scraper module too big.
When dealing with metrics that track HTTP requests it is common to include the response code in the tags. These tags are useful but can contribute to busy dashboards and a common approach is to group them by 2xx, 4xx etc.
The Kuma integration already does this and likely the KrakenD integration will as well. This centralizes the logic of such approach to easily load this in the future.
I thought that we might want to do these kind of things often for common practices and having it as a decorator …
> Add new scraper decorator that adds http code class to OpenMetrics

- windows_certificate/manifest.json
This makes the Windows Certificate Integration documentation public for the release of Agent v7.67
Agent 7.67 is set to be released on June 18th, 2024 and this integration is ready to be public.
> Display Windows Certificate integration docs

- marklogic/tests/metrics.py
- marklogic/tests/test_marklogic.py
Fixes flakey test to assert optional metrics and remove flakey label
We should aim to mark less tests as flaky because these are still run in the Test Agent Release workflow
> Unmark integration test as flaky

- datadog_checks_base/changelog.d/20555.fixed
- datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/scraper/base_scraper.py
- datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/scraper/decorators.py
- datadog_checks_base/tests/base/checks/openmetrics/test_v2/scraper/test_http_status_class_scraper.py
This PR updates the new decorator that adds `code_class` as tag whenever an http code tag is present to also support running with target_info enabled.
The recently introduced version only covers the `consume_metrics` but if target info is requested the method that gets executed is `consume_metrics_w_target_info`. This ensures that whatever way we are running it we get the code class tag added.
> Fix WithHttpCodeClass decorator to also add code class when running with target_info enabled

- spark/README.md
Adding [Docker and Integrations](https://docs.datadoghq.com/containers/docker/integrations/) to the Containerized Configuration section.
Right now, the documentation only links to the Kubernetes case, so it is confusing for customers that want to implement this integration in a containerized way with Docker.
> Add link to Docker and Integrations

- gunicorn/metadata.csv
DOCS-10879, a customer requested more clarity around the gunicorn.workers definition.
Local preview:
> Add clarity around the gunicorn.workers definitions

- .builders/images/runner_dependencies.txt
Bump `delocate` to a version that better supports Python wheels embedding multiple macOS architectures.
Working on adding support for macOS AArch64/ARM64 "native" build, I faced that:
```py
Using existing wheel
--> cm_client-45.0.4-py3-none-any.whl
--> confluent_kafka-2.8.0-cp312-cp312-macosx_11_0_universal2.whl
[...]
NotImplementedError: This function does not support separate values per-architecture: {'x86_64': [('/usr/lib/libSystem.B.dylib', '1.0.0', '1336.61.1')], 'arm64': [('/Users/runner/builder_root/prefix/lib/librdkafka.1.dylib', '0.0.0', '0.0.0'), ('/usr/lib/libSystem.B.dylib', '1.0.0', '1336.61.1')]}
```
See https://github.com/DataDog/integrations-core/actions/runs/15850271495/job/44681764771?pr=20455#step:7:17535
It turns out this issue got …
> [ABLD-28] Bump `delocate` for better macOS multiarch support

- .github/workflows/pr-all.yml
Removes condition for pr all
Currently, when making stacked PRs that target `ddev` or `datadog_checks_base`, no tests are run since PR All isn't triggered and compute-matrix returns empty
Additionally, the PR workflow is not restricted in this way: https://github.com/DataDog/integrations-core/blob/master/.github/workflows/pr.yml#L4-L13
> Run `PR All` on stacked PRs

- sqlserver/changelog.d/20584.fixed
- sqlserver/datadog_checks/sqlserver/statements.py
- sqlserver/tests/test_statements.py
There are cases where we are not able get a plan from the cache (ex. sqlserver evicted the relevant plan to free up memory). When this happens, we still submit a plan event with a plan signature but no plan definition. When querying for plans this is a bit weird since we say we've collected a plan because we see a plan event with a plan signature but we don't have the actual plan to show the user.
I see a few options here:
1. We can not submit plan events if we don't have the plan definition. This makes the most sense to me right now but would appreciate other perspectives/things I may be missing
2. We could submit the plan with a collection_error that says the plan is null because it was not found
3. We could leave plan collection as is and change the way we query for plans on the front …
> [SDBM-1807] Do not submit plan events when plan definition has been evicted from cache

- mongo/assets/configuration/spec.yaml
- mongo/changelog.d/20603.added
- mongo/datadog_checks/mongo/config.py
- mongo/datadog_checks/mongo/config_models/deprecations.py
- mongo/datadog_checks/mongo/config_models/instance.py
- mongo/datadog_checks/mongo/data/conf.yaml.example
- mongo/tests/test_dbm_schemas.py
Add new `collect_schemas` configuration to replace deprecated `schemas` while maintaining backward compatibility.
> add collect_schemas config option and deprecate schemas option

- mysql/assets/configuration/spec.yaml
- mysql/changelog.d/20602.added
- mysql/datadog_checks/mysql/config.py
- mysql/datadog_checks/mysql/config_models/deprecations.py
- mysql/datadog_checks/mysql/config_models/instance.py
- mysql/datadog_checks/mysql/data/conf.yaml.example
- mysql/tests/test_metadata.py
Add new `collect_schemas` configuration options to replace deprecated `schemas_collection` options while maintaining backward compatibility.
> deprecate schemas_collection config option

- postgres/changelog.d/20605.fixed
- postgres/datadog_checks/postgres/metadata.py
- postgres/tests/test_metadata.py
Metadata processor expects it this way.
Changes the type used by the agent to submit extension ids.
Logs such as [these](https://ddstaging.datadoghq.com/logs?query=service%3Adbm-metadata-redapl-writer%20pg_extension&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1750965568564&to_ts=1751051968564&live=true) showed that the metadata processor was failing to deserialize this field.
> Cast pg_extension id to text

- kafka/assets/dashboards/kafka_dashboard.json
- rabbitmq/assets/dashboards/rabbitmq_dashboard.json
- rabbitmq/assets/dashboards/rabbitmq_screenboard_dashboard.json
Adds the DSM map to the kafka and rabbitmq ootb dashboards
Example dashboards of the changes made
- [Rabbitmq management](https://app.datadoghq.com/dashboard/de4-5kb-m62?fromUser=false&refresh_mode=sliding&from_ts=1751299225819&to_ts=1751302825819&live=true)
- [Rabbitmq open metrics](https://app.datadoghq.com/dashboard/c86-zwv-fxt?fromUser=false&refresh_mode=sliding&from_ts=1751299236023&to_ts=1751302836023&live=true)
- [Kafka](https://app.datadoghq.com/dashboard/7wg-48i-ir7?fromUser=false&refresh_mode=sliding&from_ts=1751298414774&to_ts=1751302014774&live=true)
Example change (they all add the map next to the lag/time in queue graph)
Improved display of topology for customers that have DSM, adding visibility for DSM on ootb dashboards
> [DSM][Kafka][RabbitMQ] - Add the dsm map to OOTB dashboards

- .github/workflows/test-target.yml
Update the lint workflow step to show instructions including the update to `ddev-12.0.0`.
**Note**: I am not updating anything in velero, just used that integration as a test :)
Some partners might see CI failing  in linting and if they do not upgrade to the latest version of `ddev` they won't be able to fix it. This will give them the tools to handle the update on their own.
Eventually we should be able to remove the message.
> Add ddev udpate notice for lint failures

- nginx/metadata.csv
Added identifier (Included with open source NGINX) to the only metrics you would get when using open source NGINX vs NGINX plus. A majority are for NGINX plus only, so opted to annotated the 7 you get with open source NGINX
A customer ticket, where they were not sure which metrics to expect when using open source NGINX. While there is a description at the top of the integration page, there were metrics with similar descriptions shared with no way to identify which to expect.
> Update metadata.csv to identify open source NGINX metrics

- datadog_checks_base/changelog.d/20651.fixed
- datadog_checks_base/datadog_checks/base/utils/tracing.py
- datadog_checks_base/tests/base/utils/db/test_db_statements.py
Getting the following warning:
```
/home/runner/.local/share/hatch/env/virtual/datadog-ibm-mq/4jzrwvHc/py3.12-9/lib/python3.12/site-packages/ddtrace/_monkey.py:325: DDTraceDeprecationWarning: patch_all is deprecated and will be removed in a future version of the tracer.: patch_all is deprecated in favor of ``import ddtrace.auto`` and ``DD_PATCH_MODULES``
environment variable if needed.
deprecate(
```
https://ddtrace.readthedocs.io/en/stable/basic_usage.html#ddtrace-auto
> Replace `patch_all` with modern config option `ddtrace.auto`

- external_dns/changelog.d/20682.fixed
- external_dns/datadog_checks/external_dns/metrics.py
Fixes the collection of the `external_dns.registry.errors.total` and `external_dns.source.errors.total` metrics as the payload changed after External DNS v0.14.x
https://datadoghq.atlassian.net/browse/AGENT-14107
> Fix collection of source and registry error metrics

- .gitignore
- kafka_consumer/changelog.d/20512.added
- kafka_consumer/datadog_checks/kafka_consumer/client.py
- kafka_consumer/datadog_checks/kafka_consumer/config.py
- kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
- kafka_consumer/tests/runners.py
- kafka_consumer/tests/test_integration.py
- kafka_consumer/tests/test_unit.py
The integration reads from a config modified by the agent [in this PR](https://github.com/DataDog/datadog-agent/pull/37884) and retrieves messages from Kafka. It then logs the messages, for the Datadog UI to pick them up.
We are working on a new feature called "Live Messages" for Data Streams, for Kafka.
The feature will enable users to retrieve messages from Kafka on-demand, and send them as logs to Datadog.
> Data Streams live messages

- .github/workflows/test-agent.yml
- .github/workflows/test-all.yml
We currently run test all with the agent release pipeline. The tests keep failing for ddev. This change aims to remove ddev from being tested in that pipeline. 
- The test fails because it tries to compare repo that is tagged with master so if there's any new changes added to master, it will find differences and cause the test to fail
- The agent isn't shipped with ddev. So testing for ddev with the agent doesn't quite make sense (to me atleast)
> Remove ddev tests from the test agent release workflow

- ddev/changelog.d/20705.added
- ddev/src/ddev/cli/validate/ci.py
CI validation is failing for the below:
https://github.com/DataDog/integrations-core/pull/20704/s
This PR addresses the PR validation for the above.
> Update ci validation to include the new flag to skip ddev tests

- ddev/changelog.d/20708.added
- ddev/src/ddev/cli/validate/ci.py
Add the new option added in #20704 to the ci validation job
CI is failing after the merge to master yesterday if we don't
> Add the skip-ddev option to ci validation script

- mysql/changelog.d/20702.fixed
- mysql/datadog_checks/mysql/mysql.py
- mysql/datadog_checks/mysql/queries.py
Switches the query used to collect table row stats on Percona Mysql and MariaDB flavors over to performance_schema as opposed to the heavier information_schema source.
information_schema is a heavier table to access. The old query can also be susceptible to triggering Percona Server bug [PS-8975](https://perconadev.atlassian.net/browse/PS-8975) on v8.0.34 on busy databases that have concurrent user privilege changes occurring alongside the agent check query.
> Switch table rows stats query over to performance_schema

- kaspersky/manifest.json
Remove public facing docs for Kaspersky from being displayed
> Remove public facing docs for Kaspersky from being displayed

- tekton/changelog.d/20721.fixed
- tekton/pyproject.toml
- tekton/tests/conftest.py
- tekton/tests/kind/tekton-operator.yaml
fixes tekton e2e tests 
Tekton E2e end tests are failing to start up due to their migration from gcr.io to ghcr.io: https://tekton.dev/blog/2025/04/03/migration-to-github-container-registry/
we're seeing errors such as:
```
timed out waiting for the condition on pods/tekton-operator-76dc68cf47-pk95w
timed out waiting for the condition on pods/tekton-operator-webhook-76bd499ff7-6w5cg
error: no matching resources found
error: no matching resources found
error: resource mapping not found for name: "hello-pipeline" namespace: "" from "/home/runner/work/integrations-core/integrations-core/tekton/tests/kind/tekton-pipeline-hello.yaml": no matches for kind "Pipeline" in version "tekton.dev/v1beta1"
```
> Fix tekton E2E tests

- postgres/changelog.d/20731.added
- postgres/datadog_checks/postgres/relationsmanager.py
- postgres/tests/test_relations.py
- postgres/tests/test_relationsmanager.py
Add a valid tag to index metrics. 
Indexes creating with `CREATE INDEX CONCURRENTLY` can fail and leave indexes in an invalid state. The valid tag will allow to track those invalid indexes.
The call to pg_stat_user_indexes was replaced by direct calls to `pg_stat_get*` functions in order to avoid unnecessary join to pg_index.
> PG: Add valid tag to index metrics

- .builders/lock.py
We are currently modifying the dependency resolution process to create wheels with a new build number format which includes the workflow ID and the string 'WID' to distinguish this new format from the old one (timestamp): https://datadoghq.atlassian.net/browse/AI-5425
However, when we push the branch to make this update, the pipeline will start uploading wheels with this new format, which the current pipeline can't handle (we cast the build number to int). This PR is a temporary fix to make the pipeline pass in the time between us pushing the branch for the refactor, and merging that branch.
> Temporarily handle new wheel build number format

- sqlserver/assets/configuration/spec.yaml
- sqlserver/changelog.d/20599.added
- sqlserver/datadog_checks/sqlserver/config.py
- sqlserver/datadog_checks/sqlserver/config_models/deprecations.py
- sqlserver/datadog_checks/sqlserver/config_models/instance.py
- sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
- sqlserver/tests/test_deadlocks.py
- sqlserver/tests/test_metadata.py
- sqlserver/tests/test_xe_collection.py
Add new collect_* configuration options (collect_schemas, collect_deadlocks, collect_xe) to replace deprecated *_collection options while maintaining backward compatibility.
> deprecate schemas_collection, deadlock_collection and xe_collection config option

- postgres/changelog.d/20774.fixed
- postgres/datadog_checks/postgres/postgres.py
- postgres/tests/test_pg_integration.py
Fixes a condition where the Postgres integration would inadvertantly overwrite the configured cloud metadata used for connecting to AWS.
> Avoid overwriting AWS cloud_metadata

- gpu/README.md
Adds a missing volume mount that is required for operator versions < 1.18. Note that this is only necessary if there are no other system-probe features enabled, so the mount is not required for mixed-node deployments.
Correct deployment instructions.
Related ticket: https://datadoghq.atlassian.net/browse/EBPF-768
> gpu: add missing volume mount to the operator

- ecs_fargate/README.md
Adds an additional reason behind recommending AWS FireLens for ECS fargate log collection.
The ECS explorer relies on tags like `service_name`, `cluster_name`, `task_arn` which are added with FireLens+Fluentbit, but not with the Lamdbda forwarder.
> Indicate recommended log collection method for ECS explorer correlation

- agent_requirements.in
- ibm_ace/changelog.d/20815.fixed
- ibm_ace/pyproject.toml
- ibm_mq/changelog.d/20815.fixed
- ibm_mq/pyproject.toml
This removes a special case where `pymqi` was depended on by all target platforms (including macOS on x86_64/AMD64) **except macOS on AArch64/ARM64**.
There doesn't seem to be a compelling reason for keeping such an ad hoc exclusion since `pymqi` 1.12.11 basically consists in an installer that extracts a source tarball (https://pypi.org/project/pymqi/#files) and compiles it for the _effective_ platform, in place.
In other words, what works for `macosx_10_12_x86_64` should also work for `macosx_11_0_arm64`.
Moreover, `pymqi` is declared as an **optional** project dependency for both "IBM ACE" and "IBM MQ", which already offers some leverage since the dependency is _not installed unless explicitly qualified_:
- https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optiona …
> Lift `pymqi` dependency exclusion for macOS on AArch64/ARM64 (ABLD-28 follow-up)

- mysql/changelog.d/20833.fixed
- mysql/datadog_checks/mysql/version_utils.py
- mysql/tests/test_unit.py
- Moved logger instantiation in MySQL version compatibility check to the except block to avoid costly call to `get_check_logger()` when there are no warning logs to output.
- Added test coverage for `MySQLVersion.version_compatible`
> [DBMON-5538] MySQL version compatibility check: move get_check_logger() to except block

- datadog_checks_dev/changelog.d/20832.fixed
- datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/config.py
The whole validation would pass, but we would annotate on `spec.yaml` that we are missing the default templates.
The whole validation now fails if `spec.yaml` is missing the default templates.
Along the way refactor how we search for the templates.
Follow-up to https://github.com/DataDog/integrations-core/pull/20801. I noticed that I did break the logic a bit and we're getting annotations about failed files, but the validation passes.
> Fail config validation if templates are missing.

- mongo/changelog.d/20834.fixed
- mongo/datadog_checks/mongo/dbm/slow_operations.py
- mongo/hatch.toml
- mongo/tests/compose/mongo-standalone.yaml
This PR fixes incorrect timestamp parsing for slow queries collected from the `system.profile` collection when database profiling is enabled.
The `ts` field in `system.profile` is a naive datetime object in UTC. It contains no timezone offset information. Previously, when parsing this field without explicitly specifying a timezone, it is defaulted to the agent's local system timezone. This led to timestamp mismatches when the agent was running in a non-UTC environment.
With this fix, we explicitly interpret the `ts` field as UTC, ensuring accurate and consistent timestamp parsing across all timezones.
This issue only affects slow queries collected from database profiling. Slow queries from logs is not affected because the `ts` field from logs include the timezone.
Correctly parse …
> [mongo] Fix system.profile naive timestamp parsing

- ecs_fargate/README.md
Update public docs for the Datadog ECS Fargate Terraform module to properly reference the registry source as expected in the in the [module](https://registry.terraform.io/modules/DataDog/ecs-datadog/aws/latest/submodules/ecs_fargate?tab=dependencies)
> ECS Fargate Terraform Source Docs Update

- postgres/changelog.d/20846.fixed
- postgres/datadog_checks/postgres/statements.py
- postgres/tests/test_statements.py
* Fixes the reference to the now non-existent `e.pgerror`
* Updates tests to create an actual database error rather than use mocks
> Fix pgerror reference

- proxmox/assets/monitors/node_cpu_usage.json
- proxmox/assets/monitors/node_memory_usage.json
- proxmox/assets/monitors/vm_cpu_usage.json
- proxmox/assets/monitors/vm_memory_usage.json
- proxmox/manifest.json
Add Proxmox recommended monitors
> [AI-5348] Add Proxmox recommended monitors 

- mysql/assets/dashboards/overview-screenboard.json
- mysql/assets/dashboards/overview.json
Reverts DataDog/integrations-core#20460
mysql aren't working properly with semantic_mode, [traces](https://app.datadoghq.com/apm/traces?agg_m_a=count&agg_m_b=count&agg_m_source_a=base&agg_m_source_b=base&agg_q_a=%40view.url_path_group&agg_q_source_a=base&agg_t_a=count&agg_t_b=count&analyticsOptions=%5B%22bars%22%2C%22dog_classic%22%2Cnull%2Cnull%2C%22value%22%5D&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&colsTraces=service%2Cresource_name%2C%40duration%2C%40_span.count%2C%40_duration.by_service&fromUser=false&graphType=waterfall&historicalData=true&messageDisplay=inline&panel=%7B%22queryString%22%3A%22%40http.path_group%3A%2Fapi%2Fui%2Fquery%2Ftimeseries%20%40view.url_path_group%3A%5C%22%2Fdash%2Fintegration%2F%3F%2Fmysql%5C%22%22%2C%22fi …
> Revert "Adapt MySQL integration dashboards for OTel"

- ddev/CHANGELOG.md
- ddev/changelog.d/20816.added
Release ddev. The changes to CI is causing ci validation to now fail for extras and marketplace
> [Release] Bumped ddev version to 12.2.0

- ibm_i/assets/configuration/spec.yaml
Fix invalid value of `exclusiveMinimum` in the spec file of `ibm_i` integration.
`exclusiveMinimum` is a number, not a boolean:
- https://spec.openapis.org/oas/v3.0.3#properties
- https://json-schema.org/understanding-json-schema/reference/numeric#range
https://datadoghq.atlassian.net/browse/FA-1028
> fix(json-specs): ibm_i - fix invalid type on exclusiveMinimum prop

- .ddqa/config.toml
- .github/CODEOWNERS
This PR renames the windows-agent team to windows-products across the repository.
Team renamed from Windows Agent to Windows Products
> Update windows-agent team name to windows-products

- kubernetes/assets/dashboards/kubernetes_clusters.json
- kubernetes/assets/dashboards/kubernetes_cpu_memory.json
- kubernetes/assets/dashboards/kubernetes_daemonsets.json
- kubernetes/assets/dashboards/kubernetes_dashboard.json
- kubernetes/assets/dashboards/kubernetes_deployments.json
- kubernetes/assets/dashboards/kubernetes_jobs.json
- kubernetes/assets/dashboards/kubernetes_nodes.json
- kubernetes/assets/dashboards/kubernetes_pods.json
- kubernetes/assets/dashboards/kubernetes_replicasets.json
- kubernetes/assets/dashboards/kubernetes_services.json
- kubernetes/assets/dashboards/kubernetes_statefulsets.json
This PR should be a no-op - this is the result of copying the dashboard JSON. The expected changes are that older syntax `q:` style queries are updated to be distinct `queries` and `formulas`.
The motivation is to reduce the changeset introduced by https://github.com/DataDog/integrations-core/pull/20805.
> No op new baseline

- .github/workflows/flaky-tests.yml
- .github/workflows/master.yml
- .github/workflows/nightly-base-package.yml
- .github/workflows/pr-all.yml
- .github/workflows/pr-test.yml
- .github/workflows/pr.yml
- .github/workflows/test-agent.yml
- .github/workflows/test-fips-e2e.yml
- .github/workflows/test-target.yml
- .github/workflows/weekly-latest.yml
This reverts commit a43fc0f8a890c395dccca676d96f1221fbc98be8.
We are bringing back Codecov having a single job that uploads coverage results from artifacts stored in each job run.
I created this PR on top of this branch to validate the execution: [Dummy commit](https://github.com/DataDog/integrations-core/pull/20941/checks)
Bring coverage report back.
> Fix Codecov by having a single job uploading results

- kubernetes/assets/dashboards/kubernetes_dashboard.json
All widgets on the dashboard use the $cluster variable to filter events by cluster when the user inputs a cluster name.
Add that filter for the event list widget.
make the widget user friendly by displaying only the data filtered by the user
> kubernetes dashboard - add cluster dashboard for event widget

- datadog_checks_base/changelog.d/20947.fixed
- datadog_checks_base/datadog_checks/base/utils/db/utils.py
Fixes deprecation warnings on DBMAsyncJob class
Cleans up these warnings all over DBM related tests
```
=============================== warnings summary ===============================
tests/test_statements.py::test_async_job_cancel_cancel
integrations-core/datadog_checks_base/datadog_checks/base/utils/db/utils.py:337: DeprecationWarning: isSet() is deprecated, use is_set() instead
if self._cancel_event.isSet():
```
> [DBMON-5558] Fix deprecation warnings on isSet()

- .github/workflows/test-target.yml
This PR modifies the job name for each test-target run to include the environment selected, if any.
There are 2 issues with the current approach:
- After parallelizing the tests with different environments, the name for all jobs of the same integration are the same which makes it hard to track which job is which.
- More importantly, the job name is used for the artifact names for traces and test results. When replying traces this can cause files to be corrupted of they are being overwritten in parallel. See [these failures](https://github.com/DataDog/integrations-core/actions/runs/16607430143/job/46985434754). By using a proper job name we should fix this issue and make the job name clear on the interface.
> Modify the job name for test target to fix the artifact overriding

- ddev/changelog.d/20967.fixed
- ddev/src/ddev/cli/env/test.py
- ddev/src/ddev/repo/constants.py
- ddev/tests/cli/env/test_test.py
Makes sure that the and `ddev test` command does not run for packages in the repo that do not have any E2E environment to test.
Since we move to run tests parallelized, we are seeing issues when running tests in packages without E2E tests because the environment is provided.
This makes the E2E tests to actually trigger and a requriement to start the environment is to load the `dd_environmet` fixture. For packages without E2E tests this fixture does not exist and the command fails even before filtering `e2e` tests.
This update makes it explicit that some packages do not run E2E tests and skips them. I have followed the same approach that we have now in which we keep a list of packages that are not shippable but defined a new one which keeps track of packages that do not have E2E tests.
> Ensure that E2E tests do not run for packages that won't contain any E2E

- confluent_platform/hatch.toml
Removes test environment for `confluent_platform` for version 5.4.
This version reached the end-of-life in 2023 and the docker image [is not available anymore](https://hub.docker.com/layers/confluentinc/ksql-examples).
We have started failing tests because the image could not be pulled. See [here](https://github.com/DataDog/integrations-core/actions/runs/16800733542/job/47581348673?pr=20967)
> Drop test environment for confluent 5.4 since the docker image has been removed

- postgres/datadog_checks/postgres/connection_pool.py
- postgres/tests/test_connection_pool.py
Fixes a race condition that exists when calling `get_connection()`. Currently we have locks around access to our multi-pool dict and closing our pool safe from concurrent access. When calling `get_connection()` it was previously calling `get_pool` and then within ConnectionProxy we'd call `pool.get_connection()`. There existed a case where between getting a psycopg ConnectionPool, and grabbing a connection from it, the main thread could call `close_all_pools()` which would then lead to our thread calling `pool.get_connection()` to throw a psycopg pool closed exception. 
The changes here are aimed to fix this race condition and simplify our overall interface. We're only ever making use of individual connections and want the concept of multiple ConnectionPools to be hidden away anyway, so …
> Fixes a race condition during pool close

- .github/CODEOWNERS
The codeowners was incorrectly assigned to @DataDog/logs-integrations-reviews instead of @DataDog/logs-integrations-reviewers
> Fix the code owners for logs assets

- .github/workflows/validate-skip-qa.yml
- argocd/pyproject.toml
Avoid running the action when the PRs are labeled. Since the labeler adds a bunch of labels, each time it does a new message is posted.
Also post the message only if it has not yet been posted.
See #21015 as an example.
There is no need to bomb ard the PR author once the message has been posted once.
> Reduce verbosity of validate skip qa label action

- .ddev/ci/scripts/sqlserver/linux/55_install_odbc.sh
SqlServer CI tests began failing on Linux CI. We run these on Azure linux. It looks like Azure has added these microsoft repos by default now so we're currently adding duplicates which is leading to apt errors.
Previously failing [CI link](https://github.com/DataDog/integrations-core/actions/runs/16905142568/job/47893103962#step:21:27)
The output of our first `apt-get update` shows we have `https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64` already in our source list
```
sudo apt-get update
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [144 B]
Get:6 https://packages.microsoft.com/repos/azure-cli jammy InRelease [3596 B]
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Get:7 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [3632 B]
Get:3 …
```
> [DBMON-5566] Sqlserver remove duplicate microsoft apt index / keys

- .github/workflows/test-target.yml
Since the parallelization testing functionality was introduced, this test has been failing for marketplace. The reason is that some of the environment does not contain any e2e environment and exits with code 5 which in one scenario we don't catch. This PR aims to always catch this error code 5. 
example:
https://github.com/DataDog/marketplace/actions/runs/16916367530/job/47931201446
> Refactor and enhance the test-target e2e test step

- .builders/images/linux-aarch64/Dockerfile
- .builders/images/linux-x86_64/Dockerfile
- .builders/images/macos/builder_setup.sh
- .builders/images/windows-x86_64/Dockerfile
Updates curl in for integrations dependencies to 8.14.1.
> Update curl to 8.14.1

- tibco_ems/changelog.d/21039.fixed
- tibco_ems/datadog_checks/tibco_ems/constants.py
- tibco_ems/tests/common.py
- tibco_ems/tests/fixtures/show_queues
Collects information about queues with a `none` prefetch value.
The previous regex matching the prefetch field did not catch all cases.
Namely, it did not include a case for a `none` value, which is documented [here](https://docs.tibco.com/pub/ems/8.6.0/doc/html/GUID-7687D8CC-02F9-4896-A0DC-80B1DFCA35B0.html).
> [Tibco EMS] Fix collection of queues with a `none` prefetch value

- kafka/README.md
Updates the configuration section of the kafka broker integration too highlight DSM earlier
From feedback in slack:
> [DSM] Move the DSM callout above the JMX notice in Kafka Broker configuration

- .github/workflows/test-agent-target.yml
This PR ads a workflow to be able to run tests for a given integration and environment with a version of the agent of our choice.
The Test agent workflow runs all integrations and environments. This means that if we want to retry a failed job to validate flakes during the release process we need to wait for all jobs to finish.
Some integrations tests run in windows which is not easy to test while developing. We can leverage this workflow to test different versions of the agent as well.
> Add workflow to run a test of a given integration and environment with a version of the agent

- .github/workflows/test-agent-target.yml
Remove the windows image selection from the workflow.
Since we are selecting which platform to run the tests for in the workflow there is no point on having an image for windows and another for linux.
> Leave single image to select in test agent target

- .gitlab/build_agent.yaml
Reverts DataDog/integrations-core#21046
> Revert "Run the Agent build on release branches instead of main from release …"

- sqlserver/tests/test_e2e.py
Disables the E2E test on Windows for SQL Server.
This test is currently broken for unknown reasons an provides minimal value.
> Disable E2E on SQL Sever Windows

- datadog_checks_dev/changelog.d/21104.added
- datadog_checks_dev/datadog_checks/dev/conditions.py
- datadog_checks_dev/datadog_checks/dev/docker.py
- datadog_checks_dev/tests/docker/test_default.yaml
- datadog_checks_dev/tests/test_conditions.py
Adds two options to improve docker compose reliability:
- Option to provice the service we want to check the logs from when running docker compose.
- Option to make the `docker compose up` command to wait for health before finishing.
When running docker compose we can define health checks to ensure that service that depend on each other only start once the dependency is healthy. Passing `--wait` to `docker compose up` ensures the command does not finish until the healthy state has been achieved.
The improvement on logs check is specially important when running multi service setups. `docker compose logs` can take some time to include logs from service that took longer to start. This can cause timeouts that are not real. By being able to provide the service we want to check the logs from we …
> Add option to specify container to check logs from and to wait for health when running docker compose up

- ddev/src/ddev/cli/release/agent/changelog.py
> Remove `DELETED_INTEGRATION` workaround from `ddev`

- .github/workflows/validate-skip-qa.yml
Modifies the `validate-skip-qa` action to run on `pull_request_target` to allow comments to be added from forked repos.
Since we have partners opening PRs from forked repos, `pull_request` gives read-only permissions which forbid the action from adding comments to the PRs. An example is #20344 where a Sacumen PR would have the action failing.
Moving it to `pull_request_target` allows permissions to add comments using the base branch as context of the action.
> Make the validate-skip-qa action trigger on pull_request_target

- workato/assets/dashboards/workato_overview.json
- workato/assets/monitors/high_percentage_of_recipe_job_failures.json
- workato/manifest.json
- Add new monitor for notifying on recent high recipe job failure
- Update dashboard svg image reference for better display in dark mode
> Workato: Add new monitor; update svg for better dark mode support

- rabbitmq/assets/configuration/spec.yaml
- rabbitmq/changelog.d/21120.added
- rabbitmq/datadog_checks/rabbitmq/config_models/defaults.py
- rabbitmq/datadog_checks/rabbitmq/config_models/instance.py
- rabbitmq/datadog_checks/rabbitmq/data/conf.yaml.example
Adds `rabbitmq_user` and `rabbitmq_pass` to RabbitMQ example conf. These params are used for the management plugin. Reference: https://www.datadoghq.com/blog/openstack-monitoring-datadog/#integrating-rabbitmq-with-datadog
reported by Kelly Wiese
> DOCS-11532: add rabbitmq_user and rabbitmq_pass to rabbitmq conf.yaml.example

- jamf_pro/manifest.json
Making Jamf Pro documentation public on website
Jira ticket: [SAASINT-4380](https://datadoghq.atlassian.net/browse/SAASINT-4380)
[SAASINT-4380]: https://datadoghq.atlassian.net/browse/SAASINT-4380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(SAASINT-4380): Making Jamf Pro docs public

- ddev/changelog.d/21136.added
- ddev/src/ddev/cli/release/branch/create.py
- ddev/src/ddev/cli/release/branch/tag.py
- ddev/tests/cli/release/branch/test_create.py
This allows us to target the right Agent branch as part of our release process workflow.
https://datadoghq.atlassian.net/browse/AI-5682
> Use `ddev` to target Agent branch in `build_agent.yaml`

- kafka_consumer/changelog.d/20716.fixed
- kafka_consumer/datadog_checks/kafka_consumer/client.py
- kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
- kafka_consumer/tests/test_unit.py
This PR makes improvements in kafka consumer check to reduce the time it takes to fetch highwater offset for cluster with large number of consumer groups. More details are outlined in #20715.
cc @iliakur as they worked on a related issue https://github.com/DataDog/integrations-core/issues/19564
> Improve kafka consumer highwater offset collection time

- cisco_aci/hatch.toml
- datadog_checks_downloader/hatch.toml
This PR bumps the version of freezegun use for python 3.13 support
> Bump `freezegun` to 1.5.5 for Python 3.13

- sqlserver/tests/test_stored_procedures.py
We're regularly seeing SqlServer test failures from `test_procedure_metrics` due to this assertion line. We should remove this as it's not a stable assertion or necessary in this case. We already ensure all of our expected procedures are captured properly and asserted on in a loop before this line. When we see query counts higher than our expected manually called procedures they are due to procedures ran internally by the SQL Server Agent. Since we don't control when these occur, that is why this passes sometimes, but other times it fails with additional procedure queries.
Attached is an example of a previous flaky failure. We can see that the procedure names are from SqlServer internal operations and can safely be ignored
```
E       AssertionError: should have as many emitted rows as …
```
> [DBMON-5583] SqlServer remove unnecessary flaky assertion

- ecs_fargate/assets/monitors/ecs_fargate_cpu_usage.json
- ecs_fargate/assets/monitors/ecs_fargate_ephemeral_storage.json
- ecs_fargate/assets/monitors/ecs_fargate_mem_usage.json
- ecs_fargate/assets/monitors/ecs_fargate_net_rcvd.json
- ecs_fargate/assets/monitors/ecs_fargate_net_sent.json
- ecs_fargate/manifest.json
Add recommended ECS Fargate monitors
CAP-2761 - part of OKR to improve the overall ECS alerting and troubleshooting experience in Datadog.
> CAP-2761 Add recommended ecs_fargate monitors

- mac_audit_logs/README.md
Updates installation instructions for the Mac Audit Logs integration to clarify that it is included with the Datadog Agent.
> Fix Mac Audit Logs installation instructions

- docs/developer/tutorials/snmp/profiles.md
This PR adds a warning in the ddev SNMP profiles docs to redirect users to the new SNMP Profile Manager docs.
> [NDMII-3524] Direct users to profile onboarding docs from ddev SNMP profiles docs

- kafka_consumer/changelog.d/21221.fixed
- kafka_consumer/changelog.d/9999.fixed
- kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
- kafka_consumer/tests/test_unit.py
Improve check efficiency with many topics or partitions per consumer group when `collect_consumer_group_state` is enabled. This is done by only getting the consumer group state once per consumer group.
Make the kafka_consumer check faster.
> [kafka_consumer] Improve efficiency of collecting consumer group state.

- postgres/tests/test_pg_integration.py
- postgres/tests/test_progress_stats.py
To avoid flakiness, we skip the vacuum phase and directly run an analyze.
Tests are currently using `vacuum analyze` to check metrics reporting analyze progress. If the vacuum phase takes more than 1s, the test will fail as the wait_for_value will exit and only a running vacuum will be present when metrics are collected.
> PG: Directly run ANALYZE for the test_analyze_progress

- cisco_aci/datadog_checks/cisco_aci/fabric.py
- cisco_aci/tests/test_fabric.py
This PR udpates cisco aci integration to tag metrics by `ndm_interface` and `ndm_device`
> [NDMII-3565]enrich ndm interface metrics with redapl tags

- mysql/changelog.d/21198.fixed
- mysql/datadog_checks/mysql/databases_data.py
- mysql/datadog_checks/mysql/metadata.py
Fixes a memory leak where errors during schema collection could lead to table metadata being held onto between check runs. Previously `db_to_tables` metadata dict was only cleared on successful submission. Now we're also cleaning it up when we reset.
We're now more aggressively clearing schema collection state before and after check runs to ensure we're not holding references in memory between the long collection intervals as well. This should decrease overall memory consumption from schema collection
> [DBMON-5587] Always clear out state between schema collections

- .github/workflows/test-target.yml
Updates the `test-target` job when running outside the `core` repo to pass the `--dev` option.
It seems we were relying on the `new-env` flag to ensure the integrations get installed but this option is a noop in `ddev`. Integrations outside core are not built within the agent and unless we build them manually before launching the agent, e2e tests won't run.
> Update test-target job to install the integration in the agent when running e2e tests

- docker_daemon/assets/service_checks.json
Adds Agent support info for the docker.container_health service check. This check is not supported in Agent v7 and above.
A request from Support captured in https://datadoghq.atlassian.net/browse/DOCS-11888?atlOrigin=eyJpIjoiMjcxY2Y4MGY2ZjQyNDNlODgwZWY0OTcxODY1MjUyYTgiLCJwIjoiaiJ9
> (DOCS-11888) Added Agent support info for container health service check

- sqlserver/tests/test_unit.py
Remove broken `test_submit_is_called_if_too_many_columns` test
This test has multiple issues:
1. Mocks `_query_schema_information` to return wrong data structure
2. Uses non-existent `called_once()` method instead of `assert_called_once()`
3. Expects `StopIteration` but tests "too many columns" logic which doesn't raise it
4. Doesn't actually test the timeout condition that would raise `StopIteration`
The test is fundamentally broken and doesn't test what it claims to test.
> Remove broken `test_submit_is_called_if_too_many_columns` test

- ddev/changelog.d/21234.fixed
- ddev/src/ddev/cli/size/utils/common_funcs.py
Removes duplicated `os.path.join` when defining the path for the resolved folder.
`os.path.join` was duplicated.
> Fix path in ddev size command

- LICENSE-3rdparty.csv
- agent_requirements.in
- ssh_check/changelog.d/21266.fixed
- ssh_check/pyproject.toml
Paramiko upgrade came with Invoke that breaks the dependency resolution pipeline.
> Downgrade paramiko back to 3.5.1

- .github/CODEOWNERS
Updates the CODEOWNERS file so the Docs Team is only listed for the files we typically review.
The Docs Team was being requested for reviews on `.py` files we don’t usually review because of how CODEOWNERS was scoped.
> DOCS-11957: Update codeowners for Cisco ACI

- ddev/changelog.d/21340.added
- ddev/src/ddev/utils/git.py
- ddev/tests/utils/test_git.py
Adds a new helper method `get_merge_base` in the `GitRepository` class in `ddev`. It returns the commit hash of the common ancestor between HEAD and the given reference. 
The quality gates need to get the merge base in order to compare sizes in PRs.
> Add get_merge_base to ddev git 

- .github/workflows/testing-run-on-wf-run.yml
This PR creates a dummy GitHub Actions workflow that runs once the Resolve Build Deps has finished and prints the workflow run ID.
The `on: workflow_run` trigger cannot be tested within a branch, it only works once the workflow exists in the master branch. This dummy workflow provides a way to validate and test the trigger behavior.
> Add dummy workflow to test workflow_run trigger

- lustre/changelog.d/21270.added
- lustre/datadog_checks/lustre/check.py
- lustre/datadog_checks/lustre/constants.py
- lustre/tests/conftest.py
- lustre/tests/test_unit.py
Add `filesystem`, `jobid_var` and `jobid_name` tags to metrics that support them.
This will allow more granular analysis for HPC.
> [Lustre] Add additional tags

- agent_requirements.in
- datadog_checks_base/changelog.d/21360.added
- datadog_checks_base/pyproject.toml
Upgrade ddtrace to 3.12.5. 3.12.3 had an issue that cause increase CPU usage.
https://github.com/DataDog/dd-trace-py/releases#:~:text=profiling%3A%20This%20fixes%20a%20performance%20regression%20where%20the%20memory%20profiler%27s%20collector%20thread%20would%20spin%20in%20a%20tight%20loop%2C%20consuming%20nearly%20a%20full%20CPU%20core.
> Upgrade ddtrace to 3.12.5

- .builders/images/linux-aarch64/Dockerfile
- .builders/images/linux-x86_64/Dockerfile
- .builders/images/macos/builder_setup.sh
- .builders/images/windows-x86_64/Dockerfile
- .builders/images/windows-x86_64/build_script.ps1
Bump version of cURL to 8.16.0 to address CVEs
> Bump cURL to 8.16.0

- kubernetes/assets/monitors/monitor_pod_oomkilled.json
- kubernetes/manifest.json
This pull request extends the integration between Kubernetes Remediation and Datadog monitors by adding support for OOMKilled workloads. Specifically:
- Introduces a new JSON definition file for OOMKilled pods with the reason:oomkilled tag enabled.
- Updates the manifest.json file to include a new path for handling OOMKilled monitors.
- Ensures that users can now view Remediation Affected Workloads when a pod enters an OOMKilled state.
- Provides a new monitor template in staging for Pods in the OOMKilled state, allowing configuration and creation of corresponding monitors.
The motivation for this change is to expand existing remediation functionality to include Out-Of-Memory (OOM) killed scenarios. Previously, remediation only covered certain workload failure reasons; with this …
> [REMED-230] Adding template for OOMKilled monitors

- pgbouncer/tests/compose/docker-compose-v3.yml
Use `bitnamilegacy` image for pgbouncer E2E env
bitnami images are being removed and there is a brownout now: https://github.com/bitnami/charts/issues/35164
the images are available from bitnamilegacy but they won't be updated, so we will need to migrate to a different source soon/
> [AI-6103] Use bitnamilegacy for pgbouncer E2E

- docs/developer/base/logs-crawlers.md
We have recently updated our docs to include information about persistent cache in the `AgentCheck` base class. This PR adds information about how the LogCrawlerCheck uses persistent cache to store the log cursor for each stream.
Keep the documentation complete after the recent updates.
> Add persistent cache information to the LogCrawlerCheck documentation

- mysql/changelog.d/21421.fixed
- mysql/datadog_checks/mysql/config.py
- mysql/datadog_checks/mysql/mysql.py
Originally we checked for `disable_innodb_metrics` before our innodb query to `SHOW INNODB STATUS` but we've since extended support for querying for deadlocks from `information_schema.INNODB_METRICS`. This second query isn't currently excluded when disabling innodb metrics which leads to a consistent query exception when using a different mysql engine or very old Mysql versions that don't have `information_schema.INNODB_METRICS` table. 
We already check if InnoDB engine is in use before issuing these queries, but if `INNODB_METRICS` table doesn't exist it will crash. This change moves evaluation of the `disable_innodb_metrics` config value into our `_check_innodb_engine_enabled` function so that it's respected everywhere we query innodb allowing customers to disable them if desired.
This …
> [DBMON-5685] Ensure innodb lock queries respect disable_innodb_metrics config option

- ddev/changelog.d/20444.added
- ddev/src/ddev/repo/core.py
- ddev/src/ddev/utils/git.py
- ddev/tests/cli/env/conftest.py
- ddev/tests/cli/meta/scripts/conftest.py
- ddev/tests/cli/release/test_changelog.py
- ddev/tests/cli/test/test_test.py
- ddev/tests/cli/test_dep.py
- ddev/tests/cli/validate/conftest.py
- ddev/tests/cli/validate/test_codeowners.py
- ddev/tests/cli/validate/test_metrics.py
- ddev/tests/cli/validate/test_version.py
- ddev/tests/conftest.py
- ddev/tests/helpers/api.py
- ddev/tests/integration/test_core.py
- ddev/tests/repo/test_core.py
- ddev/tests/utils/test_git.py
Updates ddev to ensure that when scaning packages in the repo, any git worktree found is not treated as a possible integration.
When working with worktrees it is common to define the worktree as a folder within your repository directory. When ddev scans pacakges within the repo it checks all directory as possible integrations/packages, this includes worktrees folders. This triggers undesired side effect like slow linting and format checks. This is because `ddev test -s` also runs on untracked items and worktrees will likely be untracked.
> Ensure that ddev does not treat worktrees as extra packages

- .github/workflows/test-agent-target.yml
This fixes the title of the jobs launched on test during the `test-agent-target` workflow.
The other job name, while useful, is not valid to upload artifacts because the agent image has a colon which is a forbidden character. See [this job](https://github.com/DataDog/integrations-core/actions/runs/16967475658/job/48095163004#step:24:34)
> Fix title and inputs for test-agent-target

- .builders/scripts/repair_wheels.py
Removes the bypassing mechanism introduced in https://github.com/DataDog/integrations-core/pull/20513.
This is no longer necessary after https://github.com/DataDog/integrations-core/pull/21074 implemented the build of psycopg, for which this bypassing mechanism had initially been introduced. This addresses [this comment](https://github.com/DataDog/integrations-core/pull/21074#issuecomment-3324121147).
> Remove openssl-3 check bypassing mechanism

- pgbouncer/CHANGELOG.md
- pgbouncer/changelog.d/21074.fixed
- pgbouncer/datadog_checks/pgbouncer/__about__.py
- postgres/CHANGELOG.md
- postgres/changelog.d/21074.fixed
- postgres/datadog_checks/postgres/__about__.py
- requirements-agent-release.txt
- silverstripe_cms/CHANGELOG.md
- silverstripe_cms/changelog.d/21074.fixed
- silverstripe_cms/datadog_checks/silverstripe_cms/__about__.py
Port the release and changelogs from 7.71.0 after release of patches.
> Port changelog changes from 7.71.0

- kubernetes/assets/monitors/monitor_pod_oomkilled.json
This PR updates the monitor template for Pods in an OOMKilled state.
Previously, the template incorrectly relied on the metric kubernetes_state.container.status_report.count.waiting. While this metric is valid for other failure cases such as ImagePullBackOff and CrashLoopBackOff, it does not correctly represent Pods terminated due to OOMKilled events.
The template has been updated to use kubernetes.containers.state.terminated, which accurately reflects Pods that have been terminated because of OOMKilled.
- This change was driven by [REMED-248](https://datadoghq.atlassian.net/browse/REMED-248), which identified the incorrect metric usage for OOMKilled Pods. This mismatch in metric alignment caused no evaluation data to show up in the out of the box templates provided for OOMKilled Pods.
- …
> [REMED-248] Updating the OOMKilled monitor template to measure a different metric

- sqlserver/changelog.d/21319.fixed
- sqlserver/datadog_checks/sqlserver/connection_errors.py
This PR compiles and reuses regex patterns in the SqlServer integration to avoid rebuilding the pattern frequently
For each connection error we currently loop through a static list of connection error regex patterns that we're dynamically searching for each time. We can pre compile all these regex patterns to avoid recomputing
> [DBMON-5640] SqlServer - compile and reuse connection error regex

- sqlserver/assets/configuration/spec.yaml
- sqlserver/changelog.d/21481.added
- sqlserver/datadog_checks/sqlserver/config.py
- sqlserver/datadog_checks/sqlserver/config_models/instance.py
- sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
This PR adds `replace_bind_parameter` config option to sqlserver obfuscator options. 
Depends on https://github.com/DataDog/datadog-agent/pull/41408
https://datadoghq.atlassian.net/browse/SDBM-2069
> add replace_bind_parameter to sqlserver obfuscator option

- postgres/tests/conftest.py
Automatically cancels Postgres checks created during tests.
This is necessary to clean up threads used by the connection pool.
> Auto cancel Postgres checks after tests

- postgres/changelog.d/21503.fixed
- postgres/datadog_checks/postgres/azure.py
- postgres/datadog_checks/postgres/connection_pool.py
- postgres/datadog_checks/postgres/postgres.py
- postgres/tests/test_token_provider.py
Adds support for refreshing AWS IAM tokens and Azure Managed Identity tokens. The connection pool refactor for psycopg3 upgrade fixed issues we previously had with churning through connections, but accidentally only generated cloud provider credentials once on startup. This updates the connections from the connection pool to be able to handle refreshing their tokens when needed
> [DBMON-5707] Add support for refreshing cloud provider tokens in Postgres integration

- nfsstat/assets/configuration/spec.yaml
- nfsstat/datadog_checks/nfsstat/data/conf.yaml.example
Correct description of disable_missing_mountpoints_warning, if the value is _true_ then the warning is suppressed.
Customer reported incorrect description.
> Correct description of disable_missing_mountpoints_warning

- ddev/changelog.d/21536.fixed
- ddev/src/ddev/cli/size/utils/common_funcs.py
Adds logic in `get_last_dependency_sizes_artifact` to retrieve the previous commit when the `merge base` with master equals the current commit (the commit is already on master).
In the `measure disk usage` workflow, when it runs on a `push` to master, the current commit is on master, so the `merge base` is the commit itself. In this case we couldn’t determine the previous sizes.
> Get previous commit when push on master

- .github/workflows/test-agent.yml
Unchecks the "Run Python 2 Tests" checkbox when displaying a "Test Agent release" dialog. This only changes the default, the checkbox can still be checked.
Saves a click.
> Skip Python 2 tests by default in Test Agent release

- postgres/changelog.d/21557.fixed
- postgres/datadog_checks/postgres/config.py
- postgres/datadog_checks/postgres/statement_samples.py
- postgres/datadog_checks/postgres/statements.py
Backfills keys for obfuscator settings passed from Postgres to the agent SQL obfuscator.
The obfuscator expects certain legacy keys for its configuration that no longer match the options documented in the Postgres integration.
> Backfill old keys used in SQL obfuscator

- linux_audit_logs/README.md
We received customer feedback that the command in the instructions for configuring the audit daemon on this page was incorrect: this PR adds the correct spacing for the line added to the conf file (`log_group = dd-agent` instead of `log_group=dd-agent`).
> [DOCS-12068] Correct command for giving dd-agent permissions

- .ddev/config.toml
Update the dependencies GH Action is failing due to missing license for `azure-identity`. We override the license since it's missing in PYPI project metadata: https://pypi.org/project/azure-identity/
> Override `azure-identify` license

- proxmox/changelog.d/21581.added
- proxmox/datadog_checks/proxmox/check.py
- proxmox/tests/test_unit.py
Add additional proxmox_type tag to nodes
Standardize with other hypervisor integrations
> Add additional proxmox_type tag to nodes
