DataDog/integrations-core

istio/README.md

- Add link to new blog post
- Email about new blog post
N/A

[Istio] add blog link

---

directory/tests/common.py
directory/tests/compose/docker-compose.yml
directory/tests/conftest.py
directory/tests/test_directory.py
directory/tests/test_integration.py

Add E2E directory

---

haproxy/tox.ini

Upgrade haproxy to python 3.7

---

ecs_fargate/README.md

- Add link to Docker Agent environment variables on ECS Fargate readme
N/A

[ECS Fargate] update readme

---

nginx_ingress_controller/README.md

Remove unnecessary line

---

ibm_mq/README.md

- Add IBM MQ blog post link
- New blog post
N/A

[IBM MQ] add blog post link

---

process/tests/common.py
process/tests/conftest.py
process/tests/test_integration.py

Adding the E2E testing for process.
More testing.

Add process e2e

---

system_core/tests/common.py
system_core/tests/conftest.py
system_core/tests/test_integration.py
system_core/tests/test_system_core.py

Add e2e for system_core.
More testing.

Add e2e system_core

---

active_directory/datadog_checks/active_directory/data/conf.yaml.example
activemq_xml/datadog_checks/activemq_xml/data/conf.yaml.example
apache/datadog_checks/apache/data/conf.yaml.example
aspdotnet/datadog_checks/aspdotnet/data/conf.yaml.example
btrfs/datadog_checks/btrfs/data/conf.yaml.example
cacti/datadog_checks/cacti/data/conf.yaml.example
ceph/datadog_checks/ceph/data/conf.yaml.example
cockroachdb/datadog_checks/cockroachdb/data/conf.yaml.example
couch/datadog_checks/couch/data/conf.yaml.example
directory/datadog_checks/directory/data/conf.yaml.example
dns_check/datadog_checks/dns_check/data/conf.yaml.example
dotnetclr/datadog_checks/dotnetclr/data/conf.yaml.example
elastic/datadog_checks/elastic/data/conf.yaml.example
envoy/datadog_checks/envoy/data/conf.yaml.example
exchange_server/datadog_checks/exchange_server/data/conf.yaml.example
fluentd/datadog_checks/fluentd/data/conf.yaml.example
gearmand/datadog_checks/gearmand/data/conf.yaml.example
gitlab/datadog_checks/gitlab/data/conf.yaml.example
gitlab_runner/datadog_checks/gitlab_runner/data/conf.yaml.example
go-metro/datadog_checks/go-metro/data/conf.yaml.example
go_expvar/datadog_checks/go_expvar/data/conf.yaml.example
gunicorn/datadog_checks/gunicorn/data/conf.yaml.example
haproxy/datadog_checks/haproxy/data/conf.yaml.example
http_check/datadog_checks/http_check/data/conf.yaml.example
iis/datadog_checks/iis/data/conf.yaml.example

Removes trailing whitespaces left over in some configuration files.

Removing trailing whitespace

---

marathon/datadog_checks/marathon/data/conf.yaml.example

Migrates Marathon configuration file to the new norm.

[Marathon] migrating configuration file to new norm

---

mongo/datadog_checks/mongo/data/conf.yaml.example
nagios/README.md
nagios/datadog_checks/nagios/data/conf.yaml.example

* Migrates Nagios configuration file to the new norm.
* Removes a trailing whitespace from mongo configuration file

[Nagios] New configuration file.

---

docker_daemon/metadata.csv

Add metadata for the two new gauges added by https://github.com/DataDog/datadog-agent/pull/3171

Add docker.thread.* metadata

---

datadog_checks_base/datadog_checks/base/utils/agent/debug.py

Blank lines, comments, docstrings, etc.
No changelog b/c not yet released

Handle edge cases for finding the first and last lines

---

network/datadog_checks/network/data/conf.yaml.default

Migrates network configuration file to the new norm.

[Network] Migrating configuration file to the new norm

---

openldap/datadog_checks/openldap/data/conf.yaml.example

Migrates Openldap configuration file to the new norm.

[Openldap] migrating configuration file to new norm

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/check.py
datadog_checks_dev/datadog_checks/dev/tooling/e2e/config.py
datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py
datadog_checks_dev/datadog_checks/dev/tooling/e2e/local.py

Feature parity with https://github.com/DataDog/datadog-agent/blob/master/cmd/agent/app/check.go

Support all options for the Agent check command

---

ssh_check/tests/common.py
ssh_check/tests/compose/docker-compose.yml
ssh_check/tests/conftest.py
ssh_check/tests/test_integration.py
ssh_check/tests/test_ssh.py

Add e2e testing to ssh_check.
Test test test.

Add e2e ssh check

---

vault/README.md

- Add blog post link
- Update wording / formatting / links
- New blog post
N/A

[Vault] update readme

---

pdh_check/datadog_checks/pdh_check/data/conf.yaml.example

Migrates pdh check configuration file to the new norm.

[PDH check] Migrating configuration file to new norm

---

php_fpm/datadog_checks/php_fpm/data/conf.yaml.example

Migrating PHP FPM configuration file to the new norm.

[PHP FPM] migrating configuration file to the new norm

---

pgbouncer/README.md
pgbouncer/datadog_checks/pgbouncer/data/conf.yaml.example

Migrates the configuration file to the new norm.
There is the definition for `use_cached` parameter that is missing. ping @zippolyte any insights?

[PGbouncner] Migrating configuration file to new norm

---

envoy/datadog_checks/envoy/__init__.py
envoy/datadog_checks/envoy/envoy.py
envoy/datadog_checks/envoy/metrics.py
envoy/datadog_checks/envoy/parser.py
envoy/datadog_checks/envoy/utils.py
envoy/setup.py
envoy/tests/common.py
envoy/tests/conftest.py
envoy/tests/docker/default/service.py
envoy/tests/test_bench.py
envoy/tests/test_envoy.py
envoy/tests/test_parser.py
envoy/tests/test_utils.py
envoy/tox.ini

Adhere to style

---

redisdb/CHANGELOG.md
redisdb/metadata.csv

Specifies that we're talking about the main db in `redis.stats.keyspace_hits` and `redis.stats.keyspace_misses`
Customer feedback.

updating description`redis.stats.keyspace_hits` and `redis.stats.keyspace_misses`

---

postfix/datadog_checks/postfix/data/conf.yaml.example

Migrates Postfix configuration file to the new format.

[Postfix] Migrating configuration file

---

linux_proc_extras/tests/common.py
linux_proc_extras/tests/conftest.py
linux_proc_extras/tests/test_integration.py
linux_proc_extras/tests/test_linux_proc_extras.py
linux_proc_extras/tox.ini

Add e2e testing to linux proc extras
More testing

Add e2e linux proc extras

---

squid/datadog_checks/squid/data/conf.yaml.example

Migrates Squid Configuration file to the new norm.

[Squid] Migrating configuration file to new norm

---

sqlserver/datadog_checks/sqlserver/data/conf.yaml.example

Removes trailing whitespace in the configuration file.

[SQL server] Removing trailing whitespace

---

supervisord/datadog_checks/supervisord/data/conf.yaml.example

Migrating SupervisorD configuration file to the new norm.

[SupervisorD] Migrating configuration file to the new norm

---

presto/datadog_checks/presto/data/conf.yaml.example

Configuration file was already migrated, but this PR fixes some minor nits

[Presto] migrating configuration file to new norm

---

process/datadog_checks/process/data/conf.yaml.example

Migrating the configuration file for the process integration.

[Process] Migrating the configuration file

---

riakcs/datadog_checks/riakcs/data/conf.yaml.example

Migrates RiakCS configuration file to the new norm.

[RiakCS] migrating to new configuration file norm

---

statsd/datadog_checks/statsd/data/conf.yaml.example

Migrating StatsD configuration file to the new norm.

[StatsD] Migrating configuration file to the new norm

---

spark/datadog_checks/spark/data/conf.yaml.example

Migrates Spark configuration file to the new norm.
Some paramters don't have a description yet.

[Spark] Migrating configuration file to the norm

---

system_core/datadog_checks/system_core/data/conf.yaml.example
system_swap/datadog_checks/system_swap/data/conf.yaml.example

Migrates Sywtem swap and system core configuration file to the new norm.

[System] Migrating configuration file to the new norm

---

tcp_check/datadog_checks/tcp_check/data/conf.yaml.example

Migrates TCP check configuration file to the new norm.

[TCP check] Migrating configuration file to the new norm

---

teamcity/datadog_checks/teamcity/data/conf.yaml.example

Migrates configuration file from teamcity to the new file norm.

[Teamcity] Migrating configuration file to the new norm

---

marathon/datadog_checks/marathon/data/conf.yaml.example

Fixes a typo issue in the configuration file.

[Marathon] Wording update

---

tokumx/datadog_checks/tokumx/data/conf.yaml.example

Migrates TokuMX configuration file to the new norm.

[TokuMX] Migrating configuration file to the new norm

---

tomcat/datadog_checks/tomcat/data/conf.yaml.example

Migrates Tomcat configuration file to the new norm.

[Tomcat] Migrating configuration file to the new norm

---

twistlock/datadog_checks/twistlock/data/conf.yaml.example

Enhance the Twistlock configuration file.

[Twistlock] Wording enhancement

---

varnish/datadog_checks/varnish/data/conf.yaml.example

Migrates Varnish configuration file to the new norm.

[Varnish] Migrating configuration file to the new norm

---

mysql/README.md
mysql/datadog_checks/mysql/data/conf.yaml.example

Refactors MySQL configuration file for the new norm.

[MySQL] refactoring configuration file

---

ssh_check/datadog_checks/ssh_check/data/conf.yaml.example

Migrates ssh check configuration files to new norm.

[SSH Check] Migrating configuration file to the new norm

---

solr/datadog_checks/solr/data/conf.yaml.example

Migrates Solr configuration file to the new norm.

[Solr] migrating to new configuration file norm

---

rabbitmq/datadog_checks/rabbitmq/data/conf.yaml.example

Migrates RabbitMQ configuration file.

[RabbitMQ] migrating configuration file

---

zk/datadog_checks/zk/data/conf.yaml.example

Migrates Zookeeper configuration file to the new norm.

[ZK] Migrating configuration file to the new norm

---

yarn/datadog_checks/yarn/data/conf.yaml.example

Migrates Yarn configuration file to the new norm.

[Yarn] Migrating configuration file to the new norm

---

windows_service/datadog_checks/windows_service/data/conf.yaml.example
wmi_check/README.md
wmi_check/datadog_checks/wmi_check/data/conf.yaml.example

Refactors heavily the configuration file and Readme.md file from the WMI check.

[WMI] New configuration file + Readme

---

vault/datadog_checks/vault/data/conf.yaml.example

Migrates vault configuration file to the new norm.

[Vault] Migrating configuration file to the new norm

---

win32_event_log/datadog_checks/win32_event_log/data/conf.yaml.example

Migrates Win32 Event Log integration configuration file to the new norm.

[Win32 event Log] Migrating configuration file to the new norm

---

snmp/datadog_checks/snmp/data/conf.yaml.example

Enhance SNMP configuration file.

[SNMP] enhancing configuration file

---

couch/datadog_checks/couch/data/conf.yaml.example

Migrates Couch configuration file to the new format.

[Couch] Migrating couch to the new configuration format

---

ibm_was/manifest.json

fixing a typo that is making this categorize incorrectly in the docs
It's broken!

fixing a typo that is making this categorize incorrectly in the docs

---

marathon/tests/common.py
marathon/tests/compose/docker-compose.yml
marathon/tests/conftest.py
marathon/tests/test_integration.py

Add E2E testing for marathon
More testing

Add marathon e2e

---

activemq/datadog_checks/activemq/data/conf.yaml.example
kafka/datadog_checks/kafka/data/conf.yaml.example

Migrates Kafka configuration file to the new norm.

[Kafka] Migrating configuration file to the new norm

---

hdfs_datanode/datadog_checks/hdfs_datanode/data/conf.yaml.example
hdfs_namenode/datadog_checks/hdfs_namenode/data/conf.yaml.example

Migrates both HDFS integration configuration files to the new norm.

[HDFS] Migrating configuration files to the new norm

---

cisco_aci/datadog_checks/cisco_aci/data/conf.yaml.example

Migrates Cisco ACI configuration file to the new norm.

[Cisco_ACI] Migrating configuration file to the norm

---

consul/datadog_checks/consul/data/conf.yaml.example

Migrates consul configuration file to the new norm.

[Consul] Migrating configuration file to the new norm

---

kube_scheduler/datadog_checks/kube_scheduler/kube_scheduler.py

fix ddev validate py3 kube_scheduler
fix introduced py3 validation issue on master branch

Fix ddev validate py3 kube_scheduler

---

docs/dev/new_check_howto.md

Up-to-date best practices and examples

Update the tutorial for creating a new check

---

datadog_checks_dev/datadog_checks/dev/tooling/create.py

Make sure caches aren't preventing the use of new features

Update version of datadog-checks-base for extras

---

containerd/manifest.json

Remove windows and macOS compat

---

ibm_db2/README.md
jboss_wildfly/README.md

- Update agent guide links
- Link changes
N/A

[Documentation] fix agent guide links

---

datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py

Fix breakpoint agent check flag

---

ibm_mq/manifest.json
kong/manifest.json
solr/manifest.json

Updates catagories to be constant with similar integrations like kafka.

Update categories for consistency

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/check/{check_name}/setup.py
datadog_checks_dev/datadog_checks/dev/tooling/templates/check/{check_name}/tox.ini

`ddev test datadog_checks_base:py27 -pa "test_agent_check.py test_ddyaml.py::test_unsafe"`

Add posargs in tox.ini

---

.travis.yml

Add python3 linkerd to travis

---

docs/dev/new_check_howto.md

Some wording and formatting fixes in the final few sections of the Create a New Integration documentation.
Just doing my job. 😄

[skip ci] small documentation wording and formatting fixes

---

ceph/tests/common.py
ceph/tests/compose/docker-compose.yaml
ceph/tests/conftest.py
ceph/tests/fixtures/ceph_bin.sh
ceph/tests/test_integration.py
ceph/tests/test_unit.py
ceph/tox.ini

^
I only added the latest version of ceph (`mimic`) for now. The `luminous` container is broken for some reason, and I haven't tried earlier versions yet (checks and metrics are a bit different for earlier versions).

Add ceph e2e

---

ambari/datadog_checks/ambari/ambari.py
ambari/tests/test_ambari.py

Created some constants for API URL

Create constants for API URLS

---

fluentd/tests/compose/docker-compose.yaml
fluentd/tox.ini

Add v1.4 to tests

---

kube_scheduler/manifest.json

use dashes instead of underscores in kube_scheduler manifest.json

FIX update manifest.json in kube_scheduler

---

fluentd/datadog_checks/fluentd/data/conf.yaml.example
fluentd/datadog_checks/fluentd/fluentd.py

This reverts commit bd6937960c2af662fb1d0198e118626cced16caa. Accidentally pushed on master 
:<

Revert "Add support for proxy settings"

---

datadog_checks_dev/datadog_checks/dev/plugin/tox.py

Some checks narrow the supported platforms in the global section

Ensure style envs support every platform

---

dns_check/README.md

Fixes a minor error in documentation for `dns_check`.
I noticed it in the docs.
N/A

Fix error in dns_check README

---

process/README.md
process/datadog_checks/process/data/conf.yaml.example

Add notes about options that can cause problems in the process check for agent 6.11.x on windows
New version 6.11 of the agent on windows runs as an unprivileged user

Add notes about unprivileged user on windows

---

postgres/datadog_checks/postgres/data/conf.yaml.example

Migrates PostgresSQL configuration file to the new norm.

[PostgresSQL] Migrating configuration file to new norm

---

ibm_was/datadog_checks/ibm_was/__init__.py
ibm_was/datadog_checks/ibm_was/ibm_was.py
ibm_was/datadog_checks/ibm_was/metrics.py
ibm_was/datadog_checks/ibm_was/validation.py
ibm_was/setup.py
ibm_was/tests/common.py
ibm_was/tests/conftest.py
ibm_was/tests/docker/docker-compose.yaml
ibm_was/tests/docker/init.jython
ibm_was/tests/docker/scripts/8.5.5.14-profile/init.jython
ibm_was/tests/docker/scripts/9.0.0.11/init.jython
ibm_was/tests/test_unit.py
ibm_was/tox.ini

Standardize code formatting across all integrations
Also fixes CI

Adhere to code style

---

cassandra_nodetool/datadog_checks/cassandra_nodetool/data/conf.yaml.example

Add a note on actions to be taken when using check on windows with the new unprivileged user

add note on windows unpriviledged user

---

docs/dev/README.md
docs/dev/new_check_howto.md

Doc updates for clarity, consistency, and accuracy.
Integration workshop at Datadog Summit Seattle 2019.
All of the code and config examples here are valid as of the time of this PR. We'll need to ensure that they _stay_ valid over time. 🙂

[skip ci] doc updates for clarity, consistency, and accuracy

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py
datadog_checks_dev/datadog_checks/dev/tooling/e2e/local.py

Install deps not shipped with the Agent (like ibm_db), etc.

Add ability to specify extra start-up commands for e2e

---

datadog_checks_dev/datadog_checks/dev/tooling/create.py

Tiny wording chance in a ddev template.
https://github.com/DataDog/integrations-extras/pull/340#discussion_r255637938

Fixed language in template for integration extras readme

---

ecs_fargate/README.md

Fixing code blocks to fix the prod tile display

[Fargate] Fixing code blocks for tile display

---

docs/dev/new_check_howto.md

Further refinements to the new integration documentation, based on feedback gathered primarily from @bkabrda (thanks 😄).
Integration Workshop at Datadog Summit Seattle 2019

[skip ci] Additional refinements to the new integration doc

---

docs/dev/python.md

Fixes bullet point + minor typo

Fixing bullet point list

---

amazon_eks/README.md

- A new blog post link
- New blog post
N/A

[Amazon EKS] add blog link

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/check/{check_name}/README.md

@phrawzty Told me to send him a pull request to send in a PR to fix this template.
Spelling duty.

Spelling fix!

---

rabbitmq/tests/conftest.py
rabbitmq/tests/test_rabbitmq.py
rabbitmq/tox.ini

This makes integration tests pass when docker is not running on localhost.

Fix tests not running on localhost

---

ecs_fargate/README.md

Fixing anchor

---

twistlock/README.md

Changes the Twistlock readme so that metrics will display consistently with other integrations.
support request

twistlock metrics - consistent display

---

aerospike/manifest.json
ibm_db2/manifest.json
jboss_wildfly/manifest.json
kube_scheduler/manifest.json
openstack_controller/manifest.json
presto/manifest.json

change is_public to true for new integrations

---

ibm_mq/service_checks.json

Adds a service_checks.json file for this check. 
It was missing

Add service_checks.json file

---

.travis.yml

Update the integrations that actually support PY3 in Travis.yml
Travis was out of sync

Update Travis with integrations that support PY3

---

datadog_checks_base/datadog_checks/base/checks/base.py

https://github.com/DataDog/integrations-core/pull/3249
https://github.com/DataDog/integrations-core/pull/3665

Handle more tag decoding errors

---

jboss_wildfly/service_checks.json

This fixes the "integration" field in the service check file.

Fix integration name in service check

---

ecs_fargate/README.md

- Update Fargate doc to include Trace Collection information
- PM request @andrewsouthard1 
Tested and working in AWS demo account.

[ECS Fargate] Trace Collection

---

presto/README.md
presto/datadog_checks/presto/data/conf.yaml.example
presto/manifest.json

Update presto log path
The log path was too generic and not focused on presto logs.

Update the log path for the presto integration

---

win32_event_log/datadog_checks/win32_event_log/data/conf.yaml.example
win32_event_log/datadog_checks/win32_event_log/win32_event_log.py
win32_event_log/tests/test_check.py

Require the use of filters for new installations

---

jboss_wildfly/README.md
presto/README.md

This fixes links in jboss and presto READMEs.

Fix agent links in presto and jboss README

---

riakcs/README.md
riakcs/datadog_checks/riakcs/data/conf.yaml.example

* Adds info about metrics collection for RiackCS v2.1+ in the main README.md
* Adds missing parameter in the RiackCS configuration file.
Customer feedback.

[RiackCS] Adding metrics info for RiackCS v2.1+

---

apache/datadog_checks/apache/data/conf.yaml.example

Fixes indent in a configuration file
It didn't follow the norm

Fixing indent

---

envoy/README.md

Fixing Placeholder format in order to match doc guidelines
Translation issue

[Envoy] Fixing placeholder form

---

datadog_checks_dev/datadog_checks/dev/tooling/create.py
datadog_checks_dev/datadog_checks/dev/tooling/templates/jmx/{check_name}/manifest.json
datadog_checks_dev/datadog_checks/dev/tooling/templates/tile/{check_name}/manifest.json

Regression in https://github.com/DataDog/integrations-core/pull/3264

Fix creation of jmx & tile integrations

---

hyperv/README.md

- Add link to new blog post for HyperV
- New blog post
N/A

[HyperV] add blog post link

---

exchange_server/README.md

Fix code block formatting

---

.github/ISSUE_TEMPLATE.md
CONTRIBUTING.md

Add note about feature requests

[skip ci] Add note about feature requests

---

.github/actions/trello_release/Dockerfile
.github/actions/trello_release/entrypoint.sh

From the original PR the file name of the action python file changed from create_card.py to action.py. Forgot to change the entrypoint and Dockerfile to reflect that change. This fixes that.

[Action] Fix file names in Dockerfile and Entrypoint

---

.github/actions/trello_release/action.py
.github/actions/trello_release/entrypoint.sh
.github/main.workflow

Create the workflow that uses the new Trello Github action created in - https://github.com/DataDog/integrations-core/pull/3727
Also fixes up minor issue in the action code.
All future pull request events will trigger this action. 
Start using this action!

Create the Workflow to use new Trello Action

---

docs/dev/new_check_howto.md

Improve (?) the documentation for the `new check howto`.
I attended today's DataDog Seattle Summit, and enjoyed Daniel's Maher's workshop.  I noticed a few very small discrepancies between the docs and what the tools produces, so... here we are.
No additional notes.

[skip ci] metadata and service check config documentation corrections

---

ibm_was/datadog_checks/ibm_was/data/conf.yaml.example
ibm_was/datadog_checks/ibm_was/ibm_was.py
ibm_was/setup.py

Use the request wrapper for IBM WAS. 
This grants us the ability to get a bunch of request parameters for "free". Things like authentication/ssl/proxies/etc Customer requested support for basic auth 
Requires the latest and greatest in checks_base technology - https://github.com/DataDog/integrations-core/blob/master/datadog_checks_base/CHANGELOG.md#640--2019-03-22

Use request wrapper

---

.github/main.workflow

Move back to pull request style in the workflow.
After some testing, it looks like the issue actually is exhibited when the branch is deleted before the workflow actually begins. 

Move back to Pull Request Event

---

.github/actions/trello_release/action.py

Fix environment variable in github action code

---

.github/actions/trello_release/README.md

Cleanup the github trello action readme formatting
General cleanliness

Action readme formatting cleanups

---

kafka_consumer/datadog_checks/kafka_consumer/data/conf.yaml.example

Removes an hyphen.
Better docs for a better world.
Regression introduced with https://github.com/DataDog/integrations-core/pull/3153

Fix kafka_consumer conf file

---

kafka_consumer/datadog_checks/kafka_consumer/data/conf.yaml.example

Adds an alias for the SNMP FAQ and consolidates information from that FAQ into the integration page.
Consolidation of information inspired by the FAQ audit.
This should be merged before https://github.com/DataDog/documentation/pull/4603

Merging FAQ doc into SNMP integration doc

---

openshift/README.md

- Update Openshift doc to include information and links to Docker documentation
PR for [in-app instructions](https://app.datadoghq.com/account/settings#agent/openshift) - https://github.com/DataDog/dogweb/pull/37024

[Openshit] doc update

---

mesos_slave/tests/common.py
mesos_slave/tests/conftest.py
mesos_slave/tests/test_check.py
mesos_slave/tox.ini

The docker set up doesn't work with tests, only e2e. We'll fix in future

Refactor tests

---

.travis.yml

[tls] adds `tls` to .travis.yml

---

fluentd/tests/conftest.py

https://travis-ci.com/DataDog/integrations-core/jobs/200765520

Fix wait condition

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/requirements.in
datadog_checks_dev/setup.py

requests now allows urllib3 v1.25.x https://github.com/urllib3/urllib3/issues/1553

Upgrade requests to 2.22.0

---

sqlserver/datadog_checks/sqlserver/data/conf.yaml.example

[sqlserver] fix typo

---

oracle/README.md
oracle/datadog_checks/oracle/data/conf.yaml.example
oracle/datadog_checks/oracle/oracle.py
oracle/tests/test_config.py
oracle/tests/test_metrics.py
oracle/tests/test_oracle.py
oracle/tox.ini

This adds multiple results supports to custom queries. This allows having
several tags for a single metric.

Support multiple results in custom queries

---

.travis.yml

Add twistlock to travis config

---

coredns/README.md

fixing wording

---

snmp/README.md

removing stale FAQ entry

---

sqlserver/README.md
sqlserver/datadog_checks/sqlserver/data/conf.yaml.example

Update the documentation to specify how to use the Windows Authentication for the SQL Server Integration.
Customer request.
Maybe it should be a separate argument instead of using `connection_string`.

Update doc on Windows Auth

---

datadog_checks_dev/datadog_checks/dev/plugin/tox.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/manifest.py
datadog_checks_dev/setup.py

Behavior change introduced in https://github.com/tox-dev/tox/pull/1284

Fix tox plugin

---

README.md

Rotate developer GPG public keys.
To inform interested end-users about developer keys.
N/A

Rotate developer GPG public keys

---

iis/README.md

Removing confusing example

---

iis/datadog_checks/iis/iis.py

I'm trying to understand IIS code. Refactored it a bit to have less nesting

Refactor IIS check and add new log line

---

datadog_checks_downloader/datadog_checks/downloader/download.py

Remove dead code.
Noticed that this dead code somehow slipped through.
N/A.

Remove dead code

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release.py

Better error message

---

mesos_master/README.md

Adds a link to mesos slave.
Makes the combined integration page more clear.

[docs update] adding a link to mesos slave content

---

vsphere/datadog_checks/vsphere/event.py
vsphere/datadog_checks/vsphere/vsphere.py
vsphere/tests/test_vsphere.py
vsphere/tox.ini

There were a few issues with publishing event from alarms, some with tags, the others with encoding that was reproduced on our environment. This should fix them.

Fix event alarms publishing

---

iis/datadog_checks/iis/iis.py

PDHBaseCheck uses this flag to refresh counters. It performs a bit
worse, but fixes cache issues. Let's duplicate this in the check, which
overrides the check method.

Handle the refresh_counters flag

---

kube_scheduler/README.md
kube_scheduler/manifest.json

Add log instructions for the kube_scheduler integration
New integration with metrics and logs

Update Kube_scheduler with log instructions

---

openshift/README.md

Fixing text link for consistency.
A better doc for a better world.

Fixing link text

---

.github/CODEOWNERS

Was overidden by the other line
Be notified on prometheus/openmetrics/kube_leader changes

Add container integrations back to checks_base

---

ceph/datadog_checks/ceph/__init__.py
presto/datadog_checks/presto/__init__.py

Fix version discovery

---

datadog_checks_dev/datadog_checks/dev/tooling/trello.py

Update APM team label

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/jmx/{check_name}/datadog_checks/{check_name}/__init__.py

https://github.com/DataDog/integrations-core/pull/3874

Fix JMX template

---

mongo/datadog_checks/mongo/data/conf.yaml.example
mongo/datadog_checks/mongo/mongo.py
mongo/tests/conftest.py
mongo/tests/test_mongo.py

1) Add more examples to `mongo/datadog_checks/mongo/data/conf.yaml.example`
2) Fix logging issues
1) It's quite tricky to get the queries right, so providing few more examples will probably help the user.

[mongo] custom queries: add examples and fix logging

---

gunicorn/datadog_checks/gunicorn/gunicorn.py
gunicorn/tox.ini

On mac some processes are protected and exception are being raised. This PR catches those errors and ignores them.

Fix mac compatibility

---

apache/README.md
apache/manifest.json

- Consolidate information from Apache FAQ into main readme
- Forward FAQ url to Apache main readme
Docs FAQ auidt
N/A

Apache doc update

---

cassandra/README.md
datadog_checks_dev/datadog_checks/dev/tooling/templates/jmx/{check_name}/README.md
squid/README.md

- Replace support email address with links to `/help`
- Minor wording / formatting updates
Trello request
N/A

Support email address

---

activemq_xml/README.md
agent_metrics/README.md
directory/README.md
go_expvar/README.md
linux_proc_extras/README.md
nagios/README.md
prometheus/README.md
snmp/README.md
windows_service/README.md
wmi_check/README.md

- Add information to READMEs on integrations that can emit custom metrics
- Wording / formatting
Docs FAQ audit
N/A

Add notes to integrations with custom metrics

---

yarn/datadog_checks/yarn/data/conf.yaml.example

Better docs for a better world

Fix `application_tags` in conf file

---

kubelet/datadog_checks/kubelet/prometheus.py
kubelet/tests/test_kubelet.py

Reverts DataDog/integrations-core#3740

Revert "Collect network usage metrics"

---

lighttpd/tests/test_check.py
lighttpd/tox.ini

This adds a simple rate test using the new e2e automated infrastructure.

Add e2e testing

---

pdh_check/datadog_checks/pdh_check/data/conf.yaml.example

Updates pdh example file with parameters from base class

Add base class config options to pdh check

---

hive/README.md
hive/datadog_checks/hive/data/conf.yaml.example
hive/manifest.json

Add log section and documentation for Hive.

Add log section

---

iis/datadog_checks/iis/data/conf.yaml.example

[skip ci]
The article referenced by: 
https://support.microsoft.com/en-us/help/922775/how-to-troubleshoot-monitoring-and-logging-issues-for-performance-coun.
Has been removed by Microsoft. 
This PR removes a dead link.
I have looked for a replacing article, but haven't been able to find one.

Removed Dead link

---

kafka_consumer/datadog_checks/kafka_consumer/data/conf.yaml.example

Fix typo: WARING --> WARNING

---

win32_event_log/README.md

Adds a note in order to notify user to check DD agent user perm if one wants to collect the Security logs.
Customer feedback.

Adding note about security logs

---

ambari/assets/dashboards/base_dashboard.json

Fix ambari dashboard logo url

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/datadog_checks/base/utils/http.py
datadog_checks_base/requirements.in
datadog_checks_base/setup.py
datadog_checks_base/tests/test_http.py

Make everything use the wrapper
https://github.com/DataDog/integrations-core/pull/1812
https://github.com/DataDog/integrations-core/pull/2516
https://github.com/DataDog/integrations-core/pull/2591

Add others forms of auth to RequestsWrapper

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/datadog_checks/base/utils/http.py
datadog_checks_base/requirements.in
datadog_checks_base/setup.py
datadog_checks_base/tests/test_http.py

Reverts DataDog/integrations-core#3956

Revert "Add others forms of auth to RequestsWrapper"

---

tls/datadog_checks/tls/data/conf.yaml.example
tls/datadog_checks/tls/tls.py
tls/tests/conftest.py
tls/tests/test_remote.py

Allow certificate validation to be completely disabled

---

powerdns_recursor/README.md

Removes a wrong section definition in the integrations Readme.md file

Removing wrong section

---

nginx/README.md
nginx/datadog_checks/nginx/data/conf.yaml.example

Documents configuration for use with the new NGINX Plus API, http_api_module. 
Support case
Resources:
https://nginx.org/en/docs/http/ngx_http_api_module.html
http://nginx.org/en/docs/http/ngx_http_status_module.html

documents http_api_module configuration

---

prometheus/README.md

Addresses https://github.com/DataDog/integrations-core/issues/3907

update spacing in readme

---

twistlock/README.md

Correcting sample annotation from check_name to **check_names**.
Reference: https://docs.datadoghq.com/agent/autodiscovery/integrations/?tab=kubernetespodannotations#configuration

Update Twistlock README.md

---

rabbitmq/README.md

- Minor update to make it clearer configuration option examples are available in the example `conf.yaml`
N/A

RabbitMQ doc update

---

.github/CODEOWNERS

Remove intg-tools-libs from the markdown and requirements files
Adds us to the assets folder
Properly get notifications

Update intg-tools-libs codeowners

---

ssh_check/manifest.json

Add the `metric_to_check` to `ssh_check` to have this integration shown as `installed` when it is.

Add metric_to_check

---

ecs_fargate/README.md

- Adds clarification information to the docs for global tagging with Fargate.
Multiple support requests
N/A

Fargate doc

---

ambari/README.md
ambari/datadog_checks/ambari/data/conf.yaml.example
ambari/manifest.json

Adds multi line managing for ambari logs

Add logs multiline managing

---

kube_apiserver_metrics/README.md
kube_apiserver_metrics/manifest.json

Makes integration titles more explicit in order to boost search in dd doc.

Making title more explicit

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/datadog_checks/base/utils/http.py
datadog_checks_base/requirements.in
datadog_checks_base/setup.py
datadog_checks_base/tests/test_http.py

Blocked on https://github.com/DataDog/datadog-agent/pull/3741

Revert "Revert "Add others forms of auth to RequestsWrapper""

---

.github/CODEOWNERS

Update CODEOWNERS so Baklava is notified about docs changes for container integrations
Baklava was not auto-added when I did a PR for ECS Fargate
N/A

Docs codeowners

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/datadog_checks/base/utils/http.py
datadog_checks_base/requirements.in
datadog_checks_base/setup.py
datadog_checks_base/tests/test_http.py

Reverts DataDog/integrations-core#3998 to temporarily fix the Agent build pipeline

Revert "Revert "Revert "Add others forms of auth to RequestsWrapper"""

---

cisco_aci/requirements.in
datadog_checks_base/datadog_checks/base/data/agent_requirements.in
http_check/requirements.in
mysql/requirements.in
ssh_check/requirements.in
tls/requirements.in

We're using a 2 years old version, let's try to upgrade.

Update cryptography version

---

pgbouncer/README.md
pgbouncer/datadog_checks/pgbouncer/data/conf.yaml.example
pgbouncer/manifest.json

Add logs to `pgbouncer`
More logs

Add logs section

---

consul/datadog_checks/consul/data/conf.yaml.example

Fix documentation typo

---

presto/assets/dashboards/overview.json
presto/manifest.json

A step toward adding a default dashboard to presto. 
I wrote a blog post announcing the presto integration and was asked to help get the dashboard out along with it. 
Yes, as outlined here in the wiki the `integration` command needs to be run before the dashboard can be added. I need someone who does to do this.

Adding Presto Default Dashboard

---

couch/tests/test_couchv2.py

Fix couch flaky test.
The `_compact` instructions sometimes finish before the check call, so some metric are not generated.

Fix flaky test

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/requirements.in
datadog_checks_base/setup.py

Customer requests
See https://github.com/Anorov/PySocks/blob/91dcdf0fec424b6afe9ceef88de63b72d2f8fcfe/setup.py#L11-L12
Also changed `auth` extra to `http`

Support SOCKS proxies

---

datadog_checks_base/datadog_checks/base/checks/win/wmi/sampler.py
wmi_check/datadog_checks/wmi_check/wmi_check.py

Make WMISampler hashable (fix)
Appveyor builds are failling https://ci.appveyor.com/project/Datadog/integrations-core/builds/25744348

Make WMISampler hashable (fix)

---

ambari/manifest.json
hive/manifest.json
kube_apiserver_metrics/manifest.json
kube_metrics_server/manifest.json
tls/manifest.json

Make docs public

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
oracle/requirements.in
snmp/requirements.in
sqlserver/requirements.in

Upgrade dependencies for Python 3.7 binary wheels

---

ambari/README.md

Apply readme suggestions

---

docs/dev/new_check_howto.md

Updates the heading again to a more precise title.
More precise docs for a more successful world

[docs] updating the heading to a more precise title

---

openldap/tests/conftest.py

Fix tests on Azure

---

appveyor.yml

Download and install the agent binary in the appveyor CI.

Install windows agent in Appveyor

---

network/README.md

- Add note concerning `system.net.conntrack` metrics
N/A

Network docs

---

mesos_master/tests/common.py
mesos_master/tests/conftest.py
mesos_master/tests/test_integration.py
mesos_master/tox.ini

Fix/Add integration test for `mesos_master`

Fix integration tests

---

hdfs_datanode/datadog_checks/hdfs_datanode/data/conf.yaml.example
hdfs_datanode/datadog_checks/hdfs_datanode/hdfs_datanode.py
hdfs_datanode/requirements.in
hdfs_datanode/tests/conftest.py
hdfs_datanode/tests/test_hdfs_datanode.py
hdfs_datanode/tests/test_integration.py

Standardize configuration, esp. for proxy behavior

Use the new RequestsWrapper for connecting to services

---

ambari/datadog_checks/ambari/data/conf.yaml.example
harbor/datadog_checks/harbor/data/conf.yaml.example

Fix typo TSL => TLS

---

nginx/assets/dashboards/plus_overview.json
nginx/manifest.json

Add NGINX Plus dashboard.
The classic NGINX logo is used, maybe we should have a NGINX Plus logo to put in there.

Add nginx plus dashboard

---

istio/README.md

Add citadel endpoint to readme

---

datadog_checks_base/datadog_checks/base/checks/openmetrics/mixins.py
datadog_checks_base/tests/test_openmetrics.py

Fix https://github.com/DataDog/integrations-core/issues/2054

Fix label encoding

---

hive/README.md
hive/manifest.json

Set to public

---

agent_metrics/README.md
agent_metrics/manifest.json
agent_metrics/metadata.csv

Add metrics to metadata for `agent_metrics` for #3251 
No description yet
Not checked yet
Since it's A5 only, should we do it?

Add metrics to metadata

---

mesos_slave/README.md

Fixes links for mesos slave readme in order to not conflict with mesos master in the doc.

Fixing links for mesos slave

---

docs/dev/new_check_howto.md

Updates the filesystem path of `service_checks.json` to reflect the "new" location.
Accuracy is important.

[skip ci] fix the filesystem location of service_checks.json

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py

No changelog since not released yet

Fix item access

---

disk/datadog_checks/disk/disk.py
disk/tests/test_unit.py

Reverts https://github.com/DataDog/integrations-core/pull/2848
Agent 5 is in its own branch

Remove legacy code

---

elastic/datadog_checks/elastic/config.py
elastic/datadog_checks/elastic/data/conf.yaml.example
elastic/datadog_checks/elastic/elastic.py
elastic/tests/conftest.py
elastic/tests/test_config.py

[elastic] Use requests wrapper

---

datadog_checks_base/datadog_checks/base/checks/prometheus/base_check.py
datadog_checks_base/datadog_checks/base/checks/prometheus/prometheus_base.py
datadog_checks_base/tests/test_prometheus.py

Reverts DataDog/integrations-core#4089

Revert "Fix prometheus label encoding"

---

datadog_checks_base/datadog_checks/base/checks/openmetrics/mixins.py
datadog_checks_base/tests/test_openmetrics.py

Reverts DataDog/integrations-core#4073

Revert "Fix label encoding"

---

ecs_fargate/README.md

- Update Fargate note
- Customer feedback
N/A

Update Fargate note

---

ibm_db2/README.md

Fix typo in logs section

---

spark/datadog_checks/spark/spark.py

Remove unused configs and code for spark check

Remove unused configs and code for spark check

---

oracle/assets/dashboards/oracle_overview.json
oracle/manifest.json

Adds the Oracle Dashboard to this repo.
Open Source :allthethings:
This Integration Dashboard already exists, it's just getting a new home 💜

Add Oracle Dashboard Here

---

http_check/datadog_checks/http_check/utils.py
http_check/tests/conftest.py
http_check/tests/test_utils.py

https://github.com/DataDog/datadog-agent/commit/74d2ba08b3eb36ae2da6e27f74aba0fd1ce2014c

Fix detection of the embedded Agent directory

---

docs/dev/new_check_howto.md
ibm_db2/README.md
snmp/README.md

Fix \embedded references. There is another one in https://github.com/DataDog/integrations-core/blob/master/snmp/README.md but is an example output so I don't think it should be fixed

Fix \embedded directory references

---

win32_event_log/README.md

Removes the code snippet that was outdated since 6.12. [this PR](https://github.com/DataDog/integrations-core/pull/3652) was merged, requiring filters in the configuration.
The new documentation follows the general design and will avoid further confusions

[Win32] Documentation Update

---

hive/tox.ini

Add py2 environment to hive

---

ibm_mq/tests/common.py
ibm_mq/tests/test_ibm_mq.py
ibm_mq/tests/test_ibm_mq_e2e.py
ibm_mq/tox.ini

Add e2e test for ibm_mq

---

.codecov.yml

Remove diff from codecov report, as it's meaningless for us.

Modify codecov report

---

apache/tests/test_apache.py
apache/tox.ini

This adds a simple e2e test for apache check.

Add e2e test

---

couch/datadog_checks/couch/couch.py
couch/datadog_checks/couch/data/conf.yaml.example
couch/tests/conftest.py
couch/tests/test_couchv2.py

Add RequestsWrapper to couch

---

rabbitmq/datadog_checks/rabbitmq/rabbitmq.py
rabbitmq/tests/test_unit.py

Fix queue, node and echange limit. #1140

Fix queue, node and echange limit

---

cassandra/datadog_checks/cassandra/data/conf.yaml.example
hive/datadog_checks/hive/data/conf.yaml.example
presto/datadog_checks/presto/data/conf.yaml.example

Fixes placeholders + description for some configuration file.

Fixing configuration file

---

consul/datadog_checks/consul/consul.py

Resolves https://github.com/DataDog/integrations-core/issues/2695

Fix Consul event timestamp

---

kube_metrics_server/assets/dashboards/overview.json
kube_metrics_server/manifest.json

Adds the dashboard for the Kubenretes Metrics Server
Users need dashboards!

Add kubernetes metrics server default dashboard

---

activemq_xml/datadog_checks/activemq_xml/activemq_xml.py
activemq_xml/datadog_checks/activemq_xml/data/conf.yaml.example
activemq_xml/tests/test_activemq_xml.py

Update the `conf.yaml` file with proxy settings. Replace the requests with our HTTP wrapper.

Update with proxy settings 

---

ecs_fargate/datadog_checks/ecs_fargate/data/conf.yaml.example
ecs_fargate/datadog_checks/ecs_fargate/ecs_fargate.py

Updates the check with proxy config options and wrapper

Update with proxy settings and request wrapper

---

squid/README.md

- Fix metrics wording so metrics table displays on the docs page
- Standardize wording / formatting based on the current template
- Came across this in the docs
N/A

Squid docs

---

kyototycoon/datadog_checks/kyototycoon/data/conf.yaml.example
kyototycoon/datadog_checks/kyototycoon/kyototycoon.py

Add requests wrapper to kyototycoon

Add Requests Wrapper to Kyototycoon

---

datadog_checks_base/datadog_checks/base/checks/base.py
datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/datadog_checks/base/utils/agent/memory.py
datadog_checks_base/requirements.in

See the docstring & comments
Also, https://github.com/DataDog/datadog-agent/pull/3902

Add the ability to debug memory usage

---

go_expvar/datadog_checks/go_expvar/data/conf.yaml.example
go_expvar/datadog_checks/go_expvar/go_expvar.py

Add config standardization remapper and requests wrapper.

Add proxy settings support

---

datadog_checks_base/datadog_checks/base/stubs/datadog_agent.py
datadog_checks_base/datadog_checks/base/utils/headers.py
datadog_checks_base/datadog_checks/base/utils/http.py
datadog_checks_base/tests/test_http.py

Also added the `User-Agent` as a default header

Add option for specifying extra headers in RequestsWrapper

---

squid/datadog_checks/squid/data/conf.yaml.example
squid/datadog_checks/squid/squid.py
squid/tests/test_unit.py

Add requests wrapper to squid

---

teamcity/datadog_checks/teamcity/data/conf.yaml.example
teamcity/datadog_checks/teamcity/teamcity.py

Add requests wrapper to teamcity

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
oracle/requirements.in

Upgrade JPype1 to 0.7.0

---

datadog_checks_dev/datadog_checks/dev/docker.py

New integration needs a clean volume every run

Make `docker_run` clean up volumes and orphaned containers

---

teamcity/datadog_checks/teamcity/data/conf.yaml.example

Fix wording for config option description

---

systemd/assets/dashboards/overview.json
systemd/manifest.json

Add Systemd Overview Dashboard

Add Systemd Overview Dashboard

---

nagios/datadog_checks/nagios/data/conf.yaml.example

- Add Icinga version supported to Nagios conf example
Icinga v1 and Icinga v2 have different code-bases

Nagios conf example update

---

lighttpd/datadog_checks/lighttpd/data/conf.yaml.example
lighttpd/datadog_checks/lighttpd/lighttpd.py
lighttpd/tests/conftest.py

Add requests wrapper to lighttpd

---

gitlab_runner/datadog_checks/gitlab_runner/data/conf.yaml.example
gitlab_runner/datadog_checks/gitlab_runner/gitlab_runner.py

Add requests wrapper to gitlab_runner

---

datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py
datadog_checks_dev/datadog_checks/dev/tooling/e2e/local.py

Fix pip location replacement for E2E start up commands

---

datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py
datadog_checks_dev/datadog_checks/dev/tooling/e2e/local.py

It doesn't work when calling putenv later on.

Don't put integer in environment

---

twistlock/datadog_checks/twistlock/config.py
twistlock/datadog_checks/twistlock/data/conf.yaml.example
twistlock/datadog_checks/twistlock/twistlock.py

Refactor twistlock to use RequestsWrapper 
DRY

Add RequestsWrapper to twistlock

---

gitlab_runner/datadog_checks/gitlab_runner/gitlab_runner.py

Update RequestsWrapper with read/connect timeout

---

istio/README.md

adds "disable sidecar injection" section
user on twitter reached out

add note about disabling sidecar injection to istio readme

---

datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py

Let's use the new split images for now.

Use the new split images

---

marathon/tests/test_e2e.py
marathon/tests/test_integration.py
marathon/tests/test_unit.py
marathon/tox.ini

Adding simple tests to marathon

Add e2e tests

---

gunicorn/tests/common.py
gunicorn/tests/compose/Dockerfile
gunicorn/tests/conftest.py
gunicorn/tests/test_gunicorn.py
gunicorn/tox.ini

Adding simple e2e tests to gunicorn

Adding e2e tests

---

gitlab/datadog_checks/gitlab/data/conf.yaml.example
gitlab/datadog_checks/gitlab/gitlab.py

Add requests wrapper to gitlab

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
kafka_consumer/requirements.in

Changelog: https://github.com/python-zk/kazoo/releases/tag/2.6.1

Bump Kazoo to 2.6.1 to pull in some minor bugfixes

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/requirements.in

A new version happened that broke agent builds.

Pin pyasn1-modules

---

activemq_xml/tox.ini
apache/tox.ini
btrfs/tox.ini
envoy/tox.ini

Remove leftover flake8 configs.

Remove remaining flake8 configs from tox

---

vault/tests/conftest.py
vault/tests/test_integration.py
vault/tox.ini

Add integration and e2e tests to vault

---

php_fpm/datadog_checks/php_fpm/data/conf.yaml.example
php_fpm/datadog_checks/php_fpm/php_fpm.py
php_fpm/tests/conftest.py
php_fpm/tests/test_unit.py

Add request wrappers to php_fpm

---

powerdns_recursor/datadog_checks/powerdns_recursor/data/conf.yaml.example
powerdns_recursor/datadog_checks/powerdns_recursor/powerdns_recursor.py
powerdns_recursor/tests/conftest.py

Add requests wrapper to powerdns_recursor

---

apache/datadog_checks/apache/apache.py
apache/datadog_checks/apache/data/conf.yaml.example

Update requests with HTTP wrapper. Add proxy options to `conf.yaml`.

Add support for proxy options

---

rabbitmq/datadog_checks/rabbitmq/data/conf.yaml.example
rabbitmq/datadog_checks/rabbitmq/rabbitmq.py
rabbitmq/tests/conftest.py
rabbitmq/tests/test_unit.py
rabbitmq/tox.ini

Add requests wrapper to RabbitMQ

---

oracle/assets/dashboards/oracle_overview.json

Update the Oracle Dashboard Title to match what it currently is in Datadog
The value of the title field should match whats its already defined as in the Datadog platform.

Change the Oracle Dashboard Title

---

pgbouncer/README.md
prometheus/README.md

- Fix links
- Spotted while syncing tiles
N/A

Fix broken links

---

twemproxy/tests/conftest.py
twemproxy/tests/metrics.py
twemproxy/tests/test_twemproxy.py
twemproxy/tox.ini

Add e2e test to twemproxy

---

datadog_checks_dev/datadog_checks/dev/ssh_tunnel.py
oracle/tests/conftest.py
oracle/tests/terraform/cfgrsp.properties
oracle/tests/terraform/db.rsp
oracle/tests/terraform/grant.sql
oracle/tests/terraform/main.tf
oracle/tests/terraform/script.sh
oracle/tests/test_e2e.py
oracle/tox.ini

This adds a terraform environment to run end to end testing, creating a
SSH tunnel for the database connection.

Add terraform environment

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/requirements.in
snmp/requirements.in
ssh_check/requirements.in

Also unpinned `pyasn1-modules` (https://github.com/DataDog/integrations-core/pull/4275) since `pyasn1` itself now allows what we need

Upgrade pyasn1

---

systemd/manifest.json

Make systemd public

---

kafka_consumer/datadog_checks/kafka_consumer/data/conf.yaml.example

While the functionality likely won't be removed for years, best to
document it now.

Document that fetching consumer offsets from Zookeeper is deprecated

---

systemd/manifest.json

Reverts DataDog/integrations-core#4297

Revert "Make systemd public"

---

tls/assets/dashboards/overview.json
tls/manifest.json

Adds a defaults dashboard for the TLS integration

Add TLS default dashboard

---

kafka_consumer/datadog_checks/kafka_consumer/legacy_0_10_2.py

Previously, it was confusing why there were two similarly named methods
for fetching consumer offsets from Kafka.
This clarifies the difference between them using a combination of better
docstrings, better naming, and better code flow/organization.

Doc and code flow cleanups

---

tls/tests/test_e2e.py
tls/tox.ini

Add tls e2e

---

nginx/datadog_checks/nginx/data/conf.yaml.example
nginx/datadog_checks/nginx/nginx.py
nginx/tests/conftest.py
nginx/tests/test_nginx.py
nginx/tests/test_unit.py
nginx/tests/test_vts.py
nginx/tests/utils.py

Add requests wrapper to Nginx

---

haproxy/datadog_checks/haproxy/data/conf.yaml.example
haproxy/datadog_checks/haproxy/haproxy.py
haproxy/tests/conftest.py
haproxy/tests/test_haproxy.py
haproxy/tests/test_unit.py

Add requests wrapper to haproxy

---

system_swap/tests/common.py
system_swap/tests/conftest.py
system_swap/tests/test_e2e.py
system_swap/tests/test_integration.py
system_swap/tox.ini

Add system_swap e2e

---

tcp_check/tests/common.py
tcp_check/tests/conftest.py
tcp_check/tests/test_e2e.py
tcp_check/tests/test_integration.py
tcp_check/tox.ini

Add tcp e2e

---

system_core/tests/common.py
system_core/tests/conftest.py
system_core/tests/test_e2e.py
system_core/tests/test_integration.py
system_core/tox.ini

Add e2e test to system_core

---

nginx/metadata.csv

Fix metric types for metrics submitted as `rate`:
https://github.com/DataDog/integrations-core/blob/master/nginx/datadog_checks/nginx/nginx.py#L119-L125
Trello request
N/A

NGINX metric types

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/requirements.in

Pin pyasn1-modules for branch 6.12.x

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/requirements.in

Pin pyasn1-modules for branch 6.11.x

Pin pyasn1-modules for branch 6.11.x

---

mysql/README.md

Update Readme to highlight support for MariaDB
To make Datadog support for MariaDB clearer for customers

Update MySQL Readme

---

cockroachdb/tests/conftest.py
cockroachdb/tests/test_cockroachdb.py
cockroachdb/tox.ini

[cockroachdb] Add e2e tests

---

aerospike/tests/test_aerospike.py
aerospike/tox.ini

Add aerospike e2e test

---

activemq_xml/tests/conftest.py
activemq_xml/tests/test_activemq_xml.py
activemq_xml/tox.ini

Add activemq_xml e2e

---

ssh_check/tests/common.py
ssh_check/tests/conftest.py
ssh_check/tests/test_e2e.py
ssh_check/tests/test_integration.py
ssh_check/tox.ini

Add ssh_check e2e test

---

ambari/datadog_checks/ambari/ambari.py
ambari/tests/test_ambari.py

Add custom tags to service checks

Add custom tags to service checks

---

cacti/tests/conftest.py
cacti/tox.ini

Reverts DataDog/integrations-core#4313
Reverting as per https://github.com/DataDog/integrations-core/pull/4325

Revert "[cacti] Use docker lib"

---

cassandra_nodetool/tests/conftest.py
ceph/tests/conftest.py
couchbase/tests/conftest.py
datadog_checks_dev/datadog_checks/dev/docker.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/env/check.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py
datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py
datadog_checks_dev/setup.py
riakcs/tests/common.py

Reverts DataDog/integrations-core#4214 as is breaking debug

Revert "Julia/docker lib"

---

elastic/tests/test_elastic.py
elastic/tox.ini

Add elastic e2e

---

directory/tests/test_e2e.py
directory/tox.ini

Add directory e2e tests

---

openstack_controller/metadata.csv

- Fix [flavor metric](https://github.com/DataDog/integrations-core/blob/master/openstack_controller/datadog_checks/openstack_controller/openstack_controller.py#L534) names
N/A

Openstack controller metric names

---

harbor/manifest.json

Blog post has just been posted

Make harbor public

---

tls/README.md

Reorders the TLS Data Collected section in the docs so that the docs site picks it up correctly.
https://github.com/DataDog/integrations-core/issues/4341

[Docs] TLS order update to fix formatting

---

gearmand/datadog_checks/gearmand/gearmand.py
gearmand/tests/test_integration.py
gearmand/tests/test_integration_e2e.py
gearmand/tox.ini

Add gearmand e2e

---

gitlab_runner/tests/conftest.py
gitlab_runner/tests/test_integration.py
gitlab_runner/tests/test_integration_e2e.py
gitlab_runner/tox.ini

Add gitlab_runner e2e

---

harbor/tests/test_harbor.py
harbor/tox.ini

Add harbor e2e test

---

kafka_consumer/datadog_checks/kafka_consumer/legacy_0_10_2.py

Use tags more cleanly within the code flow, no interface changes

Use tags more cleanly and consistently

---

openstack_controller/datadog_checks/openstack_controller/api.py
openstack_controller/datadog_checks/openstack_controller/data/conf.yaml.example
openstack_controller/datadog_checks/openstack_controller/openstack_controller.py
openstack_controller/tests/common.py
openstack_controller/tests/conftest.py
openstack_controller/tests/test_metrics.py
openstack_controller/tests/test_openstack.py
openstack_controller/tests/test_simple_api.py

Add requests wrapper to openstack_controller

---

kafka_consumer/datadog_checks/kafka_consumer/legacy_0_10_2.py

Now that each instance gets its own object, we can store the
`KazooClient` instance as a long-lived client... this improves both
code quality and should be significantly more performant.
Additionally, this handles the prefix properly as a `chroot` which is
what they're called in the zookeeper world.
Note: This PR has multiple commits which I've pulled off into other PR's... please merge those before merging this as that will make the diff much smaller... Alternatively you can do a merge commit, but please do **NOT** merge by squashing all of these into a single commit.

Kazoo client should be long lived

---

kafka_consumer/datadog_checks/kafka_consumer/legacy_0_10_2.py

Drop iteritems & text_type
With the impending move to python 3, drop `iteritems` in favor of just
using `items`. The perf hit is minimal given the size of the data, and
just makes the code cleaner now that my eyes are used to python 3 code.
Additionally, `text_type` doesn't really make sense here... it's already
a string, no need to recast to a string.

Drop iteritems

---

kafka_consumer/datadog_checks/kafka_consumer/data/conf.yaml.example
kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
kafka_consumer/datadog_checks/kafka_consumer/legacy_0_10_2.py

This previously existed but wasn't documented. Additionally, this
respaces some of the other comments to the new line length.

Document kafka_client_api_version

---

kafka_consumer/datadog_checks/kafka_consumer/legacy_0_10_2.py

No need to explicitly pass this around because we can just check against
the list maintained in `ClusterMetadata`. Also force metadata update (in
the background) if we hit situations where metadata is possibly out of
date.

Better manage partitions that are in the middle of failover

---

ntp/README.md

Document `use_local_defined_servers`

Add use_local_defined_servers documentation.

---

datadog_checks_dev/datadog_checks/dev/_env.py
http_check/tests/common.py
http_check/tests/conftest.py
http_check/tests/test_integration.py
http_check/tests/test_integration_e2e.py
http_check/tests/test_unit.py
http_check/tests/test_unit_config.py
http_check/tests/test_unit_utils.py
http_check/tox.ini

1) Add http_check e2e
2) Update `replay_check_run` to handle multiple instandces

Add http_check e2e

---

kafka_consumer/datadog_checks/kafka_consumer/legacy_0_10_2.py

In `kafka-python` >= 1.4.5, `partitions_for_topic()` becomes a
non-blocking call, which can cause problems if the local metadata cache
is accessed before its populated:
https://github.com/dpkp/kafka-python/issues/1774
So we proactively make sure the metadata request/response cycles has
finished and the cluster metadata cache is populated as part of the
kafka client creation process.
Also includes a few other minor fixups.

Force initial population of the cluster cache

---

http_check/datadog_checks/http_check/config.py
http_check/datadog_checks/http_check/data/conf.yaml.example
http_check/datadog_checks/http_check/http_check.py
http_check/tests/conftest.py
http_check/tests/test_integration.py
http_check/tests/test_unit.py
http_check/tests/test_unit_config.py

Add request wrapper to http_check

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py

Don't fail e2e on unsupported platforms

---

redisdb/datadog_checks/redisdb/redisdb.py

If warn_on_missing_keys is True, we should always publish a value
associated with the configured keys.

Always publish a value for missing keys

---

ibm_mq/datadog_checks/ibm_mq/config.py
ibm_mq/datadog_checks/ibm_mq/data/conf.yaml.example
ibm_mq/datadog_checks/ibm_mq/ibm_mq.py
ibm_mq/tests/test_ibm_mq.py

Add channel_status_mapping config
User request

Add channel_status_mapping config

---

etcd/datadog_checks/etcd/data/conf.yaml.example
etcd/datadog_checks/etcd/etcd.py
etcd/tests/test_etcd.py

Add requests wrapper to etcd

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
ssh_check/requirements.in

Since we only directly use `paramiko`

Remove unused dependencies

---

coredns/tests/common.py
coredns/tests/test_check.py
coredns/tests/test_e2e.py
coredns/tox.ini

Add e2e to coredns

---

process/tests/test_integration.py
process/tox.ini

Add e2e to process check

---

redisdb/README.md

- Add container configuration section
- Re-arrange content for the new section
- Remove additional configuration options in favor of pointing to the `conf.yaml`
- Small wording updates
N/A

Redis container configuration

---

ibm_db2/tests/test_integration.py
ibm_db2/tests/test_integration_e2e.py
ibm_db2/tox.ini

Add ibm_db2 e2e test

---

systemd/README.md
systemd/assets/dashboards/overview.json
systemd/manifest.json
systemd/metadata.csv

Related/Motivation PR https://github.com/DataDog/datadog-agent/pull/3974

Improve systemd configuration and metric names (docs)

---

network/tests/test_e2e.py
network/tox.ini

Add e2e to network

---

datadog_checks_base/tests/test_similar.py

Fix assertions on bucket similarity

Fix bucket similarity tests

---

datadog_checks_base/datadog_checks/base/checks/base.py
datadog_checks_base/datadog_checks/base/stubs/datadog_agent.py
datadog_checks_base/datadog_checks/base/utils/agent/memory.py

https://github.com/DataDog/datadog-agent/pull/4043

Support continuous memory profiling metric submission

---

sqlserver/tests/common.py
sqlserver/tests/conftest.py
sqlserver/tests/test_sqlserver.py
sqlserver/tests/utils.py
sqlserver/tox.ini

Also made test setup work on Windows & macOS

Add SQL Server e2e tests

---

mesos_slave/tests/test_check.py

Add mesos_slave disable_ssl_validation config tests

Add mesos_slave disable_ssl_validation config tests

---

cassandra/datadog_checks/cassandra/data/conf.yaml.example

Removes the default since it's not true.

Removing defaults that doesn't exist

---

kafka_consumer/tests/conftest.py
kafka_consumer/tests/test_kafka_consumer.py
kafka_consumer/tests/test_kafka_consumer_zk.py

https://github.com/DataDog/integrations-core/pull/4464

Fix e2e support

---

consul/datadog_checks/consul/consul.py
consul/tests/test_unit.py

Add tests and fixes for changes introduced in https://github.com/DataDog/integrations-core/pull/3363/files

Fix RequestsWrapper options

---

postgres/datadog_checks/postgres/postgres.py

Co-Authored-By: dpierce-aledade <dpierce-aledade@users.noreply.github.com>
See https://github.com/DataDog/integrations-core/issues/4471

Fix query condition

---

teamcity/datadog_checks/teamcity/teamcity.py
teamcity/tests/common.py
teamcity/tests/test_teamcity.py
teamcity/tests/test_unit.py

Fix request wrapper bug, adds config test. 

Fix teamcity request wrapper bug and refactor/add test

---

ntp/README.md

- Update link in NTP doc
- Request from support
N/A

[Docs] NTP link

---

postgres/datadog_checks/postgres/data/conf.yaml.example

Config introduced in https://github.com/DataDog/integrations-core/pull/3729/

Document new config option

---

couch/tests/test_unit.py

Add couch config test
Related to https://github.com/DataDog/integrations-core/pull/4118

Add couch config test

---

kube_metrics_server/assets/dashboards/overview.json

Turns on legend for KSM File Descriptors widget
Improve UX

change legend to true for ksm file descriptors dashboard

---

gitlab_runner/tests/test_unit.py

Add gitlab_runner test for timeout

Add gitlab_runner test for timeout

---

nginx/tests/test_unit.py

Add nginx config tests

---

postgres/datadog_checks/postgres/data/conf.yaml.example

Adds default value to the configuration file after this change: 
https://github.com/DataDog/integrations-core/pull/4480/

Adding default value

---

nginx/README.md

Adds link to a common FAQ for nginx logs

Adding link to faq for nginx log.

---

datadog_checks_dev/datadog_checks/dev/plugin/pytest.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py
openmetrics/tests/common.py
openmetrics/tests/conftest.py
openmetrics/tests/test_integration.py
openmetrics/tox.ini

Add e2e to openmetrics

---

rabbitmq/tests/test_unit.py

Add rabbitmq config test

---

postgres/datadog_checks/postgres/postgres.py

By default postgres does not have a timeout on statements but most production environment have one. When such a timeout happens, the `QueryCanceled` exception is raised + the whole transaction block is in an unhealthy state. That means that any following query will fail until we "rollback" the current failing transactions.
This PR does two things:
- It catches the QueryCanceled error and rollback the failing transaction to continue execution (this is fine because each query is independent, the result of one is not used for another one)
- The `get_connection` method also checks for the "status" of the connection, if it's not in a "READY" state, it'll rollback the current transaction.

Catch statement timeouts correctly

---

mapreduce/tests/common.py
mapreduce/tests/test_integration.py
mapreduce/tests/test_integration_e2e.py
mapreduce/tox.ini

Adds end to end tests to mapreduce

Add e2e to mapreduce

---

statsd/tests/test_statsd.py
statsd/tox.ini

Add e2e test to statsd

---

powerdns_recursor/tests/test_e2e.py
powerdns_recursor/tox.ini

Add e2e test to powerdns_recursor

---

kafka_consumer/tests/test_kafka_consumer.py
kafka_consumer/tests/test_kafka_consumer_zk.py
kafka_consumer/tox.ini

Add kafka_consumer e2e tests

---

squid/tests/test_unit.py

Add legacy username pass test to Squid

Add legacy username pass test to Squid

---

couchbase/tests/test_unit.py
datadog_checks_dev/datadog_checks/dev/env.py

Add RequestWrapper tests

---

pgbouncer/tests/conftest.py
pgbouncer/tests/test_pgbouncer.py
pgbouncer/tox.ini

Add e2e test to pgbouncer

---

kyototycoon/tests/test_kyototycoon.py
kyototycoon/tox.ini

Add kyototycoon e2e

---

couch/tests/common.py
couch/tests/conftest.py
couch/tests/test_couchv1.py
couch/tests/test_couchv2.py
couch/tests/test_unit.py
couch/tox.ini

Add couch e2e test

---

pdh_check/README.md
pdh_check/manifest.json

- Add note about custom metrics
- Update wording / formatting
- Trello request
N/A

PDH check docs

---

snmp/datadog_checks/snmp/config.py
snmp/datadog_checks/snmp/data/conf.yaml.example
snmp/datadog_checks/snmp/snmp.py
snmp/requirements.in
snmp/tests/test_check.py
snmp/tests/test_unit.py

This adds support for scanning a network range and find hosts in it that
responds to SNMP discovery.

Basic discovery mechanism and test

---

ibm_mq/datadog_checks/ibm_mq/ibm_mq.py
ibm_mq/tests/test_ibm_mq.py

Fix duplicate service checks

---

cockroachdb/datadog_checks/cockroachdb/cockroachdb.py
cockroachdb/tests/test_bench.py
cockroachdb/tests/test_cockroachdb.py
envoy/tests/conftest.py
envoy/tests/test_bench.py
envoy/tests/test_envoy.py
vault/tests/test_bench.py

benchmarks have been failing
https://github.com/DataDog/integrations-core/blob/2c498e7d52243c03f65ddbea3f8010f343ac170f/.travis.yml#L36

Fix benchmarks

---

.azure-pipelines/templates/install-deps.yml
.azure-pipelines/templates/test-single-linux.yml
.azure-pipelines/templates/test-single-windows.yml
datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py
datadog_checks_dev/datadog_checks/dev/tooling/e2e/run.py
datadog_checks_dev/datadog_checks/dev/utils.py
datadog_checks_dev/tests/test_utils.py
datadog_checks_dev/tests/tooling/commands/test_create.py
datadog_checks_dev/tox.ini

Update tooling for Azure Pipelines

---

ibm_db2/README.md
snmp/README.md

Update embedded docs
Docs of the Windows Agent: Basically, as soon as 6.14.0 is out, what was changed in https://github.com/DataDog/integrations-core/pull/4159 and https://github.com/DataDog/documentation/pull/5020 will have to be updated again

Update embedded docs

---

couchbase/README.md
couchbase/datadog_checks/couchbase/data/conf.yaml.example
couchbase/manifest.json

Add documentation for the couchdb log integration
It was supported but not documented

Add log documentation for the couchdb integration

---

druid/manifest.json

Update Druid display name

---

snmp/assets/service_checks.json
snmp/datadog_checks/snmp/config.py
snmp/datadog_checks/snmp/data/conf.yaml.example
snmp/datadog_checks/snmp/snmp.py
snmp/tests/common.py
snmp/tests/test_bench.py
snmp/tests/test_check.py
snmp/tests/test_unit.py

This should make things a bit faster on large tables.

Use bulk call when possible

---

envoy/manifest.json

The previous `metric_to_check` is not available in Envoy 1.11.1. Updating to another metric.

Update metric_to_check for envoy

---

envoy/requirements-dev.txt

Fix envoy requirements-dev.txt

Fix envoy requirements-dev.txt

---

mysql/manifest.json

Fixing typo in integration desc

---

.azure-pipelines/templates/test-single-linux.yml
.azure-pipelines/templates/test-single-windows.yml

This will display a nice test list in the build.

Publish test results in AZP

---

datadog_checks_dev/datadog_checks/dev/conditions.py

Improve RetryError message

---

cacti/tests/common.py
cacti/tests/conftest.py
datadog_checks_dev/datadog_checks/dev/conditions.py

Fix flaky Cacti e2e

---

mongo/README.md
mongo/manifest.json

- Add container configuration section
- Re-arrange content for the new section
- Remove additional configuration options in favor of pointing to the `conf.yaml`
- Small wording updates

MongoDB container instructions

---

mcache/README.md
mcache/manifest.json

- Add container configuration section
- Re-arrange content for the new section
- Remove additional configuration options in favor of pointing to the `conf.yaml`
- Small wording updates

Memcached container instructions

---

marathon/README.md
marathon/manifest.json

- Add container configuration section
- Re-arrange content for the new section
- Remove additional configuration options in favor of pointing to the `conf.yaml`
- Small wording updates

Marathon container instructions

---

druid/tests/compose/docker-compose.yaml

Update druid version
Wait for https://github.com/DataDog/docker-library/pull/53 to be merged and image to be pushed to docker registry.

Update druid version

---

ambari/README.md

Fixes Ambari doc by fixing a link + removing outdated info

[Ambari] Fixing doc

---

druid/README.md

Fix druid image link

---

.azure-pipelines/templates/run-tests.yml
.azure-pipelines/templates/test-single-linux.yml
.azure-pipelines/templates/test-single-windows.yml

Factor CI templates
Reduce duplication.

Factor CI templates

---

.azure-pipelines/all.yml

With 35 runners, we can enable all builds on master.

Enable all builds on master

---

couchbase/README.md

Fixes the code in the bullet list for the doc.

[Couchbase] Fixing code block design

---

vertica/README.md

Adds Vertica code samples to the Vertica integration readme
trello

[Vertica] adds code samples for vertica

---

mesos_slave/README.md

Fixes the JSON to define the Datadog Agent application with marathon.
https://github.com/DataDog/datadog-agent/issues/4020

Fixing docker image conf

---

mongo/README.md
mysql/README.md

- Remove Non-ASCII characters from README files
- Staging tiles broke
N/A

Non-ASCII characters

---

process/metadata.csv

Add "(Linux only)" note for `system.processes.mem.real`
Trello request from support

system.processes.mem.real

---

ecs_fargate/README.md

Fix the documentation at https://docs.datadoghq.com/integrations/ecs_fargate/ for accounts using `datadog.eu`.
I was not able to use ECS Fargate integration without this.

Update ECS Fargate Integration documentation

---

kafka_consumer/datadog_checks/kafka_consumer/data/conf.yaml.example

We upgraded to v1.4.7 of `kafka-python` which includes extended support for `sasl_mechanism` and `security_protocol`.
Customer case

Update config to match kafka-python 1.4.7

---

openstack/datadog_checks/openstack/data/conf.yaml.example

Fix documented default for `use_agent_proxy`

---

mysql/tests/conftest.py

Add comment about Mysql 5.5 image.

Add comment about Mysql 5.5 image

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/py3.py
datadog_checks_dev/setup.py

Call directly pylint instead of a7

Don't use a7

---

datadog_checks_base/tests/conftest.py

Another attempt for https://github.com/DataDog/integrations-core/pull/4677/files

Fix socks5 test

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release.py
datadog_checks_dev/datadog_checks/dev/tooling/trello.py

Added Platform team with its trello list, renamed Core team in mapping
New Platform team.
Does this change require anything from checklist?

Update teams in ddev trello tool

---

redisdb/datadog_checks/redisdb/redisdb.py
redisdb/tests/common.py
redisdb/tests/conftest.py
redisdb/tests/test_default.py
redisdb/tests/utils.py

Depends on https://github.com/DataDog/integrations-core/pull/4704

Submit version metadata

---

.github/CODEOWNERS

Updates CODEOWNERS with new Platform team
The new Agent Platform team owns the "system" checks
(i.e. checks enabled by default on a host install of the Agent),
and the process check

Update CODEOWNERS with new Platform team

---

ibm_was/datadog_checks/ibm_was/data/conf.yaml.example
ibm_was/datadog_checks/ibm_was/ibm_was.py
ibm_was/tests/fixtures/server.xml
ibm_was/tests/test_unit.py

This will allow submitting CountStatistic with a unit as a gauge instead
of count.

Add an option for custom count with units

---

mysql/datadog_checks/mysql/mysql.py

Fix typo in a log message.
Words should be properly spelled :-)
None.

Fix typo in logs (Instace -> Instance)

---

openmetrics/datadog_checks/openmetrics/data/conf.yaml.example

Document distribution bucket option

---

openmetrics/datadog_checks/openmetrics/data/conf.yaml.example

Fix copypasta

---

lighttpd/datadog_checks/lighttpd/lighttpd.py

Fix log format for lighttpd
Merge after https://github.com/DataDog/integrations-core/pull/4711

Fix lighttpd logging format

---

druid/datadog_checks/druid/druid.py

Fix druid logging format
Merge after https://github.com/DataDog/integrations-core/pull/4731

Adhere to logging call convention

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/check/{check_name}/datadog_checks/{check_name}/data/conf.yaml.example
datadog_checks_dev/datadog_checks/dev/tooling/templates/jmx/{check_name}/datadog_checks/{check_name}/data/conf.yaml.example

Reverts DataDog/integrations-core#4752
cc @AlexandreYang

Revert "Better default conf.yaml.example"

---

snmp/datadog_checks/snmp/snmp.py
snmp/tests/test_unit.py

This stores discovered hosts, so that restarting the agent bootstraps
quickly.
Depends on https://github.com/DataDog/datadog-agent/pull/4267

Store discovered hosts

---

vault/tests/conftest.py
vault/tests/docker/consul_config.json
vault/tests/docker/docker-compose.yaml
vault/tests/docker/vault_config.json
vault/tests/test_integration.py
vault/tests/test_vault.py

Basically, replace the dev environment we have with a more production-like use setup.

Vault environment with consul and replication in tests

---

nagios/README.md

Adds AD instructions for the Datadog-Nagios integration.

Nagios Autodiscovery

---

druid/README.md
druid/datadog_checks/druid/data/conf.yaml.example

Add druid logs

---

ecs_fargate/README.md

update firelense docs urls

---

rabbitmq/tests/conftest.py
rabbitmq/tox.ini

Fix rabbitmq test envs
We were only testing 3.6.

Fix rabbitmq test envs

---

istio/README.md
istio/manifest.json

Add instruction to collect istio logs
A new integration was added for Istio

Add instruction to collect istio logs

---

snmp/README.md

Changes the language in the SNMP docs to be explicit that the integration SNMP metrics collected will be billed as custom.  
Docs are not super explicit -- want to be clear for customers  

update snmp billing language in docs

---

snmp/README.md

Small clarification and fixes some grammar issues.
Translator feedback.

[documentation] small clarifications to SNMP profiling

---

druid/tests/README.md

Add Druid dev doc

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
druid/requirements.in
pgbouncer/requirements.in
postgres/requirements.in

https://github.com/psycopg/psycopg2/issues/957
Also removed it from `druid`, must have been a copy/paste error

Upgrade psycopg2-binary to 2.8.4

---

nginx/README.md

Adds autodiscovery instructions for nginx
Better AD documentation.

Adding autodiscovery instructions

---

squid/README.md
squid/manifest.json

Adds log collection instructions for Squid
PM request.

Squid: Adding log collection instructions

---

mapr/manifest.json

Tag the mapr integration as log collection
Integration was added as well as documentation but it seems that the tag is missing

Tag mapr as log collection integration

---

.azure-pipelines/templates/test-all-checks.yml

Need fix after this merge https://github.com/DataDog/integrations-core/pull/4748

Fix test-all-checks.yml

---

mesos_slave/tests/common.py
mesos_slave/tests/test_integration.py
mesos_slave/tests/test_integration_e2e.py

Tests works on windows, just not on CI due to docker windows mode.

Use not_windows_ci

---

cacti/tests/common.py
cacti/tests/compose/docker-compose.yaml
cacti/tests/conftest.py

Use specific port to add coverage for mysql_port config
Better coverage

Use specific mysql_port to add coverage for mysql_port config

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/check/{check_name}/README.md

Add link to the `metadata.csv` file in the `Metrics` section of the README template.

Update metadata link in template

---

win32_event_log/README.md

Update Win 32 event log note
N/A

[Docs] Win 32 event log note

---

docs/dev/new_check_howto.md

Fix broken links in docs
The links were broken!

Fix links to metrics information

---

mapr/assets/dashboards/mapr_overview.json
mapr/manifest.json

See https://dddev.datadoghq.com/dashboard/2db-kqp-3h5/kai-mapr---fs?from_ts=1571920629901&live=true&to_ts=1571924229901&tv_mode=true

Add dashboard

---

squid/README.md
squid/manifest.json

- Instructions for using Squid with the Agent container
N/A

[Docs] Squid container instructions

---

spark/README.md
spark/manifest.json

- Add containerized instructions for Spark integration
N/A

[Docs] Spark containerized

---

openmetrics/README.md
prometheus/README.md

- Wording, formatting, and link updates for OpenMetrics / Prometheus docs
Trello request from PM
N/A

[Docs] OpenMetrics

---

mapr/README.md

Fixes wording.
Translator feedback.

Wording fix

---

ssh_check/README.md
ssh_check/manifest.json

Add container instructions for SSH check
Someone from the containers team should review before merge

[Docs] SSH container instructions

---

disk/datadog_checks/disk/disk.py
disk/tests/test_check.py
disk/tests/test_filter.py
disk/tests/test_unit.py

We don't nee agentConfig anymore.

Use Agent 6 signature

---

datadog_checks_base/datadog_checks/base/utils/common.py
datadog_checks_base/datadog_checks/base/utils/constants.py

Needed for SAP HANA, and now ClickHouse

Add total_time_to_temporal_percent utility

---

rabbitmq/datadog_checks/rabbitmq/rabbitmq.py
rabbitmq/tests/conftest.py
rabbitmq/tests/test_rabbitmq.py

Add method to version metadata from RabbitMQ.
Add tests

Add version metadata to RabbitMQ check

---

datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py

Fixes https://github.com/DataDog/integrations-core/pull/4895

Fix e2e on Windows

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release.py

Simple sanity check to prevent pipeline from trying to build nothing

Never sign an empty release

---

redisdb/datadog_checks/redisdb/data/conf.yaml.example

Current example shows `KEY_REGEX` while the comment says its a pattern.
This change KEY_REGEX in KEY_PATTERN to avoid confusion
Avoid documentation confusion

Fix example keys config

---

druid/manifest.json

[HOLD, merge when 6.15 is out] Make Druid public

---

statsd/README.md
statsd/manifest.json

- Add StatsD container instructions
This PR should be reviewed by a member of the containers team before merge.

Docs StatsD container instructions

---

datadog_checks_base/datadog_checks/base/stubs/datadog_agent.py

Better metadata assertion output by leveraging pytest dictionary assertion.
Before:
```
def assert_metadata(self, check_id, data):
for name, value in data.items():
>           assert self._metadata[(check_id, name)] == value
E           AssertionError: assert '1' == '9'
E             - 1
E             + 9
```
After
```
def assert_metadata(self, check_id, data):
actual = {k: v for k, v in self._metadata[check_id].items() if k in data}
>       assert data == actual, 'Metadata provided does not match for check_id `{}`, all metadata: {}'.format(
check_id, self._metadata[check_id]
)
E       AssertionError: Metadata provided does not match for check_id `test:123`, all metadata: {'version.raw': '1.4.26', 'version.patch': '26', 'version.minor': '4', 'version.scheme': 'semver', 'version.major': …
```

Better metadata assertion output

---

postfix/tests/common.py
postfix/tests/test_e2e.py

Add test for postqueue mode
- Better coverage
- Used as regression test for this PR https://github.com/DataDog/integrations-core/pull/4949

Add test for postqueue mode

---

couch/datadog_checks/couch/couch.py
couch/tests/conftest.py

This adds an additional condition on v2 to remove sleep call, and adds a
log message for an intermittent error appearing in CI.

Try to improve test reliability

---

spark/README.md

Clean-up Spark doc
Noticed wording did match the current template
N/A

Spark doc clean-up

---

supervisord/README.md
supervisord/manifest.json

- Add container instructions for Supervisord
A member of the containers team should review before merge

Supervisord Container instructions

---

mapr/datadog_checks/mapr/mapr.py
nagios/datadog_checks/nagios/nagios.py

Found 2 instances of wrong logging format

Fix use of format in logging

---

squid/README.md
squid/datadog_checks/squid/data/conf.yaml.example

Adds new Squid log integration
Publish new Squid log integration

Adding log section

---

systemd/README.md

- Remove Autodiscovery sentence
- Small wording / formatting updates
N/A

Systemd doc update

---

kafka_consumer/README.md

Add note about implementation choice

---

vertica/datadog_checks/vertica/data/conf.yaml.example
vertica/datadog_checks/vertica/vertica.py
vertica/tests/common.py
vertica/tests/conftest.py
vertica/tests/test_vertica.py

Create a new connection at every check run when necessary

---

couchbase/datadog_checks/couchbase/couchbase.py
couchbase/tests/test_couchbase.py
datadog_checks_base/datadog_checks/base/stubs/datadog_agent.py

Adds version metadata and tests

add version metadata

---

snmp/datadog_checks/snmp/snmp.py
snmp/metadata.csv
snmp/tests/test_check.py

This adds a new gauge counting the number of discovered devices for one
network.

Count the number of discovered devices

---

external_dns/README.md

Removes duplicated sentence
Translators feedback

Removing duplicated sentence

---

mongo/README.md

Fixes a broken link in the mongo integration.

[Mongo] Fixing broken link

---

snmp/datadog_checks/snmp/data/profiles/f5-big-ip.yaml
snmp/datadog_checks/snmp/data/profiles/generic-router.yaml
snmp/datadog_checks/snmp/snmp.py
snmp/tests/test_check.py

This collects ifAdminStatus and ifOperStatus in the profiles

Add interface statuses to profiles

---

vsphere/datadog_checks/vsphere/vsphere.py

When requesting metrics from the vCenter API, the integration uses `maxSample` to request only a single datapoint (the latest one).
This parameter is ignored when requesting historical metrics. vCenter then decides how best to serve that query, potentially with hundreds of datapoints per request.
This PR addresses this issue by specifying a startTime to all the requests, all answers will have only a few datapoints. Unfortunately for some reason, that makes historical query slightly slower 🤷‍♂ 
Even though it's slower we still need to do it otherwise we may receive data which is aggregated over a week which wouldn't be very valuable.
Also because the integration was expecting a single datapoint it was using something like `result.value[0]` to get the datapoint it expects. In the case of …

Collect the latest non-negative value for historical metrics

---

mapr/manifest.json

MapR fix category name `data-store` --> `data store`
Fix docs integration category
N/A

[Docs] MapR fix category

---

kafka/manifest.json

Does not match https://github.com/DataDog/integrations-core/blob/6d0c1986c04e7d5b3a3ee4e9ad1c50623de65ad2/kafka/datadog_checks/kafka/data/metrics.yaml#L327

Fix metric_to_check

---

kafka/metadata.csv

Fix metrics names to match https://github.com/DataDog/integrations-core/blob/master/kafka/datadog_checks/kafka/data/metrics.yaml

Fix metrics names

---

.azure-pipelines/templates/run-tests.yml

This is segfaulting enough that it's annoying.

Disable profiling in CI

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/config.py

Add command to navigate to config directory

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/create.py

Fix typo in name warning in `ddev create`

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/prometheus.py

https://github.com/DataDog/integrations-core/blob/df470635b3f56fb686aaf0f70b4145bd417f0486/datadog_checks_base/datadog_checks/base/checks/openmetrics/mixins.py#L621-L642

Support more metric types for `ddev meta prom`

---

.azure-pipelines/changes.yml
varnish/datadog_checks/varnish/varnish.py

Remove shlex
shlex not supported on windows

Remove shlex

---

process/README.md

Removes duplicated info + make the doc more streamlined

[Process] Refactoring doc

---

hive/setup.py
hive/tests/conftest.py
hive/tests/test_check.py
hive/tox.ini

Add hive e2e test

---

system_core/README.md
system_swap/README.md

- Remove Autodiscovery sentence
- Small wording / formatting updates
Correct information
Haissam confirmed these integrations cannot be autodiscovered.

[Docs] System Core and System Swap

---

mysql/README.md

Changes boolean for replication from 0 to false.
Trello card request for continuity in documentation as all other examples are true or false.

Changed replication boolean from 0 to false

---

tls/README.md
tls/manifest.json

- Add Autodiscovery instructions for TLS integration
Do not merge until a member of the containers team reviews.

[Docs] TLS containerized

---

tokumx/README.md
tokumx/manifest.json

- Add Tokumx container Autodiscovery instructions
- Update host parameter to match container parameter

[Docs] Tokumx container instructions

---

oracle/README.md
oracle/manifest.json

* Adds AD instructions for the oracle integration.
* Adds configuration snippet for the host configuration.
Better AD support.

[Oracle] Adding AD instructions

---

pgbouncer/README.md
pgbouncer/manifest.json

* Adds AD instructions for metrics + log collection
* Factorise the user creation in the installation section

[PgBouncer] Adding AD instructions

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in

Needed in the Agent for a new integration

Require boto3

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release.py

Dry mode displays cards that will be created.
It is nice to see what will be really created.
Replace https://github.com/DataDog/integrations-core/pull/4783

Improve dry mode

---

datadog_checks_base/tests/test_openmetrics.py

This migrates the mocking testing to the datadog_agent fixture.

Use new metadata testing method

---

jboss_wildfly/datadog_checks/jboss_wildfly/data/conf.yaml.example

Updates jboss_wildfly example yaml file to require username and password. 
Support case

Update example config to require `username` and `password`

---

datadog_checks_dev/CHANGELOG.md

I didn't fix the version properly, so let's fix the changelog.

Fix dev changelog

---

twemproxy/README.md
twemproxy/manifest.json

Add Autodiscovery instructions for Twemproxy integration

[Docs] Twemproxy with Autodiscovery

---

varnish/README.md

- Update Varnish for AD structure
N/A

[Docs] Varnish AD updates

---

tcp_check/README.md

- Add Autodiscovery instructions for the TCP check
A member of the containers team should review before this PR is merged

[Docs] TCP containerized

---

teamcity/README.md
teamcity/manifest.json

- Add container template for Teamcity
Do not merge until a member of the containers team reviews.

[Docs] Teamcity container template

---

datadog_checks_base/datadog_checks/base/checks/base.py
http_check/tests/test_integration.py

We changed the normalize behavior a bit too much in normalize_tag, let's
revert back.

Revert normalize behavior

---

external_dns/README.md
external_dns/datadog_checks/external_dns/data/auto_conf.yaml
external_dns/datadog_checks/external_dns/data/conf.yaml.example
external_dns/datadog_checks/external_dns/external_dns.py
external_dns/metadata.csv

- FIxes autoconf file
- Fixes documentation
- Fixes metric names
- Fixes default config

Fix docs and AD config

---

cilium/datadog_checks/cilium/cilium.py
cilium/datadog_checks/cilium/data/conf.yaml.example

The errors were intantiated but not raised. This also fixes a small doc
mismatch.

Raise configuration errors

---

riakcs/README.md

Removing ad instructions since this doesn't run usually in a docker container.

Removing ad instructions

---

tomcat/README.md
tomcat/manifest.json

* Cleanup Tomcat integration docs
* Add link to Autodiscovery with JMX guide
N/A

[Docs] Tomcat Autodiscovery

---

solr/README.md
solr/manifest.json

- Cleanup Solr integration docs
- Add link to Autodiscovery with JMX guide
N/A

[Docs] Solr integration

---

jboss_wildfly/tests/conftest.py

Update jboss client url
Using Azure storage is probably faster for CI.

Update jboss client url

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/config.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py
datadog_checks_dev/datadog_checks/dev/tooling/config.py

Add support for switching between multiple orgs' API/APP keys

---

istio/tests/README.md
istio/tests/terraform/main.tf

Brief walkthrough of steps to get terraform env up and running.  Also removed the `min_master_version` reference since that was causing issues and doesn't seem necessary to spin up resources successfully.
README specific to Istio for now, if approved, can create a new PR for Cilium.

Add README for terraform environment

---

snmp/datadog_checks/snmp/snmp.py

Trying to use a single next command to fetch all table oids can lead to
misleading results. We ignore the additional values for now, but newer
versions of pysnmp changed the behavior and it breaks us.

Fetch table oids per table

---

coredns/README.md
coredns/manifest.json

autodisco instructions for coredns

[docs] coredns autodisco

---

zk/README.md
zk/manifest.json

- Add Autodiscovery instructions for Zookeeper
- Remove unneeded section
- Update wording

[Docs] Zookeeper Autodiscovery

---

yarn/README.md
yarn/manifest.json

- Add Autodiscovery instructions for Yarn

[Docs] Yarn Autodiscovery

---

aerospike/README.md
aerospike/manifest.json

adds autodisco instructions for the aerospike integration

[docs] aerospike autodisco

---

cisco_aci/README.md
cisco_aci/manifest.json

adds autodisco instructions for cisco_aci integration

[docs] cisco_aci autodisco

---

cockroachdb/README.md
cockroachdb/manifest.json

adds autodisco instructions for cockroachdb

[docs] cockroachdb autodisco

---

gearmand/README.md
gearmand/manifest.json

adds autodisco intstructions for gearmand

[docs] gearmand autodisco

---

activemq/README.md
activemq/manifest.json

instructions for using activemq with the Agent container

[docs] activemq autodiscovery

---

twistlock/README.md
twistlock/manifest.json

- Add Autodiscovery instructions for Twistlock integration
- Re-arrange some content
- Small fixes

[Docs] Twistlock Autodiscovery

---

apache/datadog_checks/apache/data/auto_conf.yaml
apache/datadog_checks/apache/data/conf.yaml.example
apache/datadog_checks/apache/data/conf_spec.yaml

https://github.com/DataDog/integrations-core/pull/5072

Add configuration specification

---

datadog_checks_base/datadog_checks/base/utils/http.py

Fix default

---

datadog_checks_dev/datadog_checks/dev/kube_port_forward.py
datadog_checks_dev/datadog_checks/dev/ssh_tunnel.py
datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py
datadog_checks_dev/datadog_checks/dev/utils.py

It is annoying not to be able to run the `agent status` command for troubleshooting issues.

Fix agent status with ddev

---

.github/CODEOWNERS

Update the codeowners file to reflect the files the integrations-tools-and-libraries should be watching.

Update the codeowners file

---

twistlock/README.md

This reverts commit 66fd046f498f77b2c8a9c98864368ae4a6fdeea3.

Revert "indent config"

---

elastic/datadog_checks/elastic/elastic.py

Part 2 of https://github.com/DataDog/integrations-core/pull/5249
Less config to set up

Add OOTB support for AWS Signature Version 4 Signing

---

vault/README.md
vault/manifest.json

- Add Autodiscovery instructions for the Vault integration

[Docs] Vault Autodiscovery

---

go_expvar/README.md
go_expvar/manifest.json

Adds AD instructions for Go Expvar

[Go Expvar] Adding AD instructions

---

haproxy/README.md
haproxy/manifest.json

[HAproxy] Adding ad instructions

---

etcd/README.md
etcd/manifest.json

[Etcd] Adding AD instructions

---

exchange_server/README.md

Removes useless code block + format all links as reference.

[Exchange server] Removing useless codeblock

---

kafka_consumer/README.md
kafka_consumer/manifest.json

* Adds AD instructions.
* Format all links

[Kafka consumer] Adding AD instructions

---

gitlab/README.md
gitlab/manifest.json

Adds AD instructions for Gitlab integration.
Better AD support.

[Gitlab] Adding ad instructions

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/__init__.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/dashboard.py
datadog_checks_dev/datadog_checks/dev/tooling/config.py
datadog_checks_dev/datadog_checks/dev/tooling/utils.py

Add meta command to export dashboards

---

activemq_xml/README.md
activemq_xml/manifest.json

[ActiveMQ XML] Adding ad instructions

---

ecs_fargate/README.md

Fixes a small typo that slipped through in the README
Update to the correct code sample from the AWS page.

Fix typo in Firelens README

---

lighttpd/README.md
lighttpd/manifest.json

[Lighttpd] Adding AD instructions

---

linkerd/README.md
linkerd/manifest.json

[Linkerd] Adding AD instructions

---

mapreduce/README.md
mapreduce/manifest.json

[Mapreduce] Adding AD instructions

---

harbor/README.md
harbor/manifest.json

[Harbor] Adding AD instructions

---

fluentd/README.md
fluentd/manifest.json

[Fluentd] Adding AD instructions

---

envoy/README.md
envoy/manifest.json

[Envoy] Adding AD instructions

---

elastic/README.md
elastic/manifest.json

[Elastic] Adding AD instructions

---

couchbase/README.md
couchbase/manifest.json

[Couchbase] Adding AD instructions

---

couch/README.md
couch/manifest.json

[CouchDB] Adding AD instructions

---

apache/README.md
apache/manifest.json

[Apache] Adding AD instructions

---

jboss_wildfly/README.md
jboss_wildfly/manifest.json

* Adds AD instructions
* Format links

[Jboss Wildfly] Adding AD instructions

---

ibm_mq/README.md
ibm_mq/manifest.json

* Adds AD instructions
* Reformat links as reference

[IBM MQ] Adding AD instructions

---

ibm_db2/README.md
ibm_db2/manifest.json

* Adds AD instructions
* Format all links

[IBM DB2] Adding AD instructions

---

iis/README.md
iis/manifest.json

* Adds AD instructions.
* Removes documentation for optional param since those information are now in the configuration file.

[IIS] Adding AD instructions

---

hdfs_datanode/README.md
hdfs_datanode/manifest.json

[HDFS Datanode] Adding ad instructions

---

ibm_was/README.md
ibm_was/manifest.json

* Adds AD instructions
* Format all links

[IBM Was] Adding AD instructions

---

.azure-pipelines/scripts/sap_hana/linux/50_increase_docker_memory.sh
sap_hana/tox.ini

Increase Docker memory for SAP HANA

---

apache/tests/compose/apache.yaml
apache/tests/compose/httpd.conf
apache/tests/conftest.py

https://github.com/DataDog/integrations-core/pull/5346
Will require rebasing after ^ is merged

Add logs setup to test environment

---

.azure-pipelines/all_pr.yml

Exclude agent_requirements.in from AZP
Integrations tests are not impacted by change of `agent_requirements.in`, hence no need to trigger all integrations tests.
`ddev validate dep` is already checking `agent_requirements.in` on every `PR Changes` pipeline build.

Exclude agent_requirements.in for PR All Pipeline

---

cassandra/README.md

Fixes a broken link for logs multi-line aggregation.
Fix

Fix broken link to logs multi-line aggregation docs

---

gitlab/README.md

Remove random `gs` from README
Saw this while syncing tiles
N/A

[Docs] Gitlab small fix

---

crio/README.md
crio/manifest.json

* Remove AD sentence on the cri-o integration
* Wording / formatting updates
N/A

[docs] crio autodisco

---

hive/README.md
hive/manifest.json

[Hive] Adding ad instructions

---

ambari/README.md
ambari/manifest.json

[Ambari] adding ad instructions

---

elastic/README.md
elastic/datadog_checks/elastic/data/conf.yaml.example

Adds elasticsearch configuration instructions to README.

Add documentation for slow logs

---

ecs_fargate/README.md

Update documentation links to graphing section
Graphing section reorg
N/A

[Docs] Update links to graphing docs

---

druid/README.md

1. Fixes list layout in the public doc.
2. Update all links as reference

[Druid] Fixing layout

---

hdfs_namenode/README.md
hdfs_namenode/manifest.json

[HDFS Namenode] Adding ad instructions

---

cassandra_nodetool/README.md
cassandra_nodetool/manifest.json

Refactors instructions to be consistent with other integrations

[Cassandra Nodetool] Refactoring instructions.

---

kafka/README.md
kafka/manifest.json

[Kafka] Adding AD instructions

---

cacti/README.md
cacti/manifest.json

Format instructions to make it more streamlined

[Cacti] Formating instructions

---

airflow/assets/dashboards/overview.json
airflow/manifest.json

Add Airflow Dashboard

---

vault/README.md
vault/assets/configuration/spec.yaml
vault/datadog_checks/vault/data/conf.yaml.example
vault/manifest.json
vault/tests/conftest.py
vault/tests/docker/docker-compose.yaml

Enable logs in dev env and add instructions on logs configuration.
To enable the logs testing:
1. Add `spec.yaml` to `<INTEGRATION>/assets/configurations/` path.
2. Validate config `ddev validate config <INTEGRATION>`
3. Add spec path to `manifest.json`.
4. Enable `mount_logs=True` in `dd_environment`.
5. Include the log file paths in `docker-compose.yaml` volumes.
```
volumes:
- ${DD_LOG_1}:/vault/vault-audit.log
- ${DD_LOG_2}:/var/log/vault.log 
```

Add vault logs documentation and test env

---

dotnetclr/README.md
dotnetclr/metadata.csv

- Docs update for .NET CLR integration
Feedback from support
N/A

DOCS-402 .NET CLR update

---

snmp/datadog_checks/snmp/compat.py
snmp/datadog_checks/snmp/snmp.py
snmp/datadog_checks/snmp/utils.py

* Split profile loading logic into smaller functions.
* Move agent-compatibility code to a dedicated `compat.py` module.
Code in the SNMP check is somewhat cluttered and hard to read. I'd like to split more things into named functions, and add a bunch of white space here and there. This PR is a first step!
/

Refactor loading of SNMP profiles

---

vault/assets/dashboards/vault_overview.json
vault/manifest.json

Add vault dashboard

---

snmp/datadog_checks/snmp/config.py

Refactor `snmp/config.py`:
- Group related lines visually by separating them by blank lines.
- Explicitly define `.resolve_oid()` (used by `SNMPCheck`)  as a method.
Make the SNMP code easier on the eyes. :-)
Other possible refactoring on `Config`:
- Move auth building to util functions.
- Refactor `.parse_metrics()` to allow at most 2-3 levels of indentation, and minimize mutable state.
- ...

Give some air to SNMP config

---

vault/assets/configuration/spec.yaml
vault/datadog_checks/vault/data/conf.yaml.example
vault/datadog_checks/vault/vault.py
vault/tests/test_vault.py

Add support for metric collection without a token

---

cassandra/README.md
cassandra/datadog_checks/cassandra/data/conf.yaml.example

Needed to handle:
```
DEBUG [ScheduledTasks:1] 2018-11-22 12:50:31,441  MonitoringTask.java:173 - 3 operations were slow in the last 5000 msecs:
<SELECT * FROM offernet.work_e WHERE community_id = 1496222336 AND member_id = 49 AND ~~edge_label_id = 65550 LIMIT 50000>, time 505 msec - slow timeout 500 msec
<SELECT * FROM offernet.item_e WHERE community_id = 2052914560 AND member_id = 189 AND ~~edge_label_id = 65553 LIMIT 50000>, time 505 msec - slow timeout 500 msec
<SELECT * FROM offernet.item_e WHERE community_id = 2140990336 AND member_id = 212 AND ~~edge_label_id = 65553 LIMIT 50000>, time 504 msec - slow timeout 500 msec
```

Add multi_line log_processing_rules

---

istio/README.md

Adds new Istio blog post to the Istio readme further reading section. 
Making sure blog posts are circulated through docs

[docs] Istio further reading link

---

linkerd/assets/dashboards/overview.json

Remove dashboard icon reference

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_downloader/requirements.in

Update dependency for `datadog-checks-downloader`
Fix a bug
Should have no functional difference for customers

Update TUF dependency

---

spark/datadog_checks/spark/spark.py

Make sure version collection does not bring down the whole check run if the `http.get` fail.

Make sure version collection fail gracefully

---

datadog_checks_base/datadog_checks/base/checks/openmetrics/mixins.py

https://github.com/DataDog/integrations-core/blob/1bf1bcf5f4af4a54f16bf45ad76d55c4f364ce05/datadog_checks_base/datadog_checks/base/checks/openmetrics/mixins.py#L581-L583

Re-introduce legacy cert option handling

---

snmp/datadog_checks/snmp/snmp.py

This fixes 2 potential issues with discovery:
* Save the cache more often, to get a more accurate picture
* Filter out end of mib values, instead of logging the values as
warning

Tweak behavior related to discovery

---

kube_metrics_server/README.md

adds instructions to configure kube metrics server if your endpoint is secured
h/t @Marcquero

[docs] SSL config for kube metrics server

---

datadog_checks_base/datadog_checks/base/checks/openmetrics/mixins.py
kubelet/datadog_checks/kubelet/kubelet.py
kubelet/tests/test_kubelet.py

Defaults are overwritten dynamically during every check run

Fix Kubelet credentials handling

---

openshift/README.md

Explicitly calls out support for Openshift 4

[DOCS-524] Support for Openshift 4

---

ecs_fargate/README.md

Removes the duplicated Host Param.

Removing duplicated param

---

.github/stale.yml

I noticed comments had improper new line spacing

Fix comment formatting

---

eks_fargate/manifest.json

Fixes the EKS fargate manifest to display it in the public documentation + fixes some other parameter value
Making this documentation public.

Fixing manifest

---

datadog_checks_base/tests/test_http.py

Add aws empty config tests.
Test for https://github.com/DataDog/integrations-core/pull/5290
Better coverage.

Add aws empty config tests

---

vault/tests/conftest.py

Use sudo in test only if needed
That will avoid asking for password when not needed (at least on MacOS).

Use sudo in test only if needed

---

amazon_eks/README.md

EKS Managed Node Groups is supported by this integration, this PR displays the info :)

[DOCS-523] Adding info about EKS Managed Node Groups

---

process/datadog_checks/process/process.py
process/tests/test_process.py

This fixes a typo in a debug message, and rearrange formatting a bit.

Fix small typo

---

datadog_checks_base/datadog_checks/base/checks/base.py

Add new deprecation

---

sqlserver/datadog_checks/sqlserver/sqlserver.py

Fixes a small capitalization error in a log found while QAing #5377

Fix small capitalization error in log

---

datadog_checks_base/datadog_checks/base/checks/base.py
datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/requirements.in

Add type comment to AgentCheck
Added `typing` dep, it will also be used later for additional typing annotation for base package.
Help IDE to infer that `AgentCheck` is a `__AgentCheck`.
Before:
After:

Add type comment to AgentCheck

---

datadog_checks_base/setup.py
elastic/tests/test_elastic.py
elastic/tox.ini

Related PR: https://github.com/DataDog/integrations-core/pull/5289

Add aws auth test

---

.azure-pipelines/templates/run-validations.yml
.azure-pipelines/templates/test-all-checks.yml
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/__init__.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/ci.py

I noticed a few jobs that should be running on master were missing

Add validation for CI infrastructure configuration

---

.flake8
datadog_checks_base/datadog_checks/base/checks/base.py
datadog_checks_dev/datadog_checks/dev/plugin/tox.py

Enforce lazy logging

---

datadog_checks_base/tests/test_pdhbasecheck.py

Assert default dwType and lpLocalName

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/config.py

Add instructions about org config options in `-h`.

Document setting org config

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/requirements.in

Upgrade ddtrace to 0.32.2

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/ls.py

Avoid blank output when nothing gets found.

Add some helpful output to ddev env ls command

---

kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
kafka_consumer/datadog_checks/kafka_consumer/legacy_0_10_2.py

https://github.com/dpkp/kafka-python/pull/1196

Update imports for newer versions of kafka-python

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/assets/configuration/spec.yaml
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/datadog_checks/{check_name}/data/conf.yaml.example
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/manifest.json
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/assets/configuration/spec.yaml
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/datadog_checks/{check_name}/data/conf.yaml.example
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/datadog_checks/{check_name}/data/metrics.yaml
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/manifest.json

https://github.com/DataDog/integrations-core/pull/5072

Make new integrations use config specs

---

containerd/README.md
cri/README.md

Updated containerd and cri readme to reflect this: https://github.com/DataDog/datadog-agent/issues/3701#issuecomment-510115593
Also, added a kubernetes example for CRI and reworked the wording.
https://github.com/DataDog/datadog-agent/issues/3701#issuecomment-510115593
and also customers using CRI should have an example as well

Updated the containerd and cri doc

---

kong/assets/dashboards/kong_overview.json
kong/manifest.json

Adds a kong screenboard for OOTB dashboards.

Add kong dashboard

---

mcache/README.md

Fix indentation to properly display the code block

Fix indent

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_dev/datadog_checks/dev/tooling/signing.py
datadog_checks_dev/setup.py
datadog_checks_downloader/requirements.in

Update in-toto and its deps.
Handle breaking changes while using latest deps.
Should not merge until tox passes.

Update in-toto and its deps

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/run.py

Small update to handle help switches.

Allow help options to ddev run command

---

kubelet/datadog_checks/kubelet/kubelet.py
kubelet/tests/test_kubelet.py

We make a manual call in kubelet, which generates a lot of insecure
warniings that we used to ignore. Let's silent them.

Ignore insecure warnings for kubelet requests

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/agent_reqs.py

Update agent_reqs to list unreleased checks.
More helpful output.

Update `validate agent-reqs` cmd to list unreleased checks

---

linux_proc_extras/README.md

There are metrics collected by linux_proc_extras, updating the section with link to metadata.csv

Update metadata.csv link

---

openshift/README.md

Clarify OpenShift documentation

Clarify OpenShift pseudo-check documentation

---

couch/datadog_checks/couch/couch.py
couch/tests/conftest.py
couch/tests/test_couchv2.py

Fixes the replication test. Adds `WaitFor` to try sending replication tasks and tracking active_tasks.

Fix replication task test

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/scripts/__init__.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/scripts/upgrade_python.py
datadog_checks_dev/datadog_checks/dev/utils.py

We'll upgrade next week https://github.com/DataDog/datadog-agent/pull/4464

Add meta command to upgrade the Python version of all test environments

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
supervisord/requirements.in

Python 3.8 compatibility fix https://github.com/Supervisor/supervisor/pull/1258

Upgrade supervisor dependency

---

jboss_wildfly/README.md

Various links were missing or pointing to the wrong location.

Fix links in README

---

vsphere/tests/.gitignore
vsphere/tests/test_lab.py
vsphere/tox.ini

Add vSphere lab test and debug helper
More info in docstring.

Add vSphere lab test and debug helper

---

eks_fargate/README.md

Adds precision around the minimum Agent version required to run the master Agent version.
Reduce confusion.

[DOCS-528] Adding agent 7.17 precision

---

airflow/manifest.json

Merge when Agent 6/7.17 is released.

Make airflow public

---

cilium/README.md

Adds log instructions, removes note about cluster agent (not needed, we can just annotate to collect metrics)

Add cilium logs instruction

---

datadog_checks_dev/datadog_checks/dev/tooling/config.py

Add jira to ddev config (needed for #5457 )

Add jira to ddev config

---

apache/README.md
cassandra/README.md

Fixes indentation on some integrations
It seems that indentation was not correctly picked up when linting those file, this PR corrects it.

Indent fix

---

haproxy/metadata.csv

All the rate metrics were listed as gauge, this fixes it.
Closes #5604

Fix type of rate metrics

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
kafka_consumer/requirements.in

Upgrade kafka-python to 2.0.0

---

vsphere/metadata.csv

Fixes https://github.com/DataDog/integrations-core/blob/master/vsphere/metadata.csv to have a proper csv format
it's broken

Adding missing value

---

envoy/metadata.csv
systemd/metadata.csv

Fixing the errors that validate metadata hasn't caught

Fix invalid metadata rows

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py

Validate metadata uses all f strings

---

postgres/README.md
postgres/datadog_checks/postgres/data/conf.yaml.example

Update description of the `dbname` configuration setting.
Support case

Update dbname description in conf.yaml.example

---

haproxy/metadata.csv

Reverts DataDog/integrations-core#5691
Rates are really gauges.

Revert "Fix type of rate metrics"

---

mongo/metadata.csv

The metadata csv contains the in-app type, not the submission type.
There shouldn't any rates in there.

Really fix metadata

---

.github/workflows/slapr.yml

There are some issues using aliased emojis: https://github.com/DataDog/integrations-core/runs/445690237?check_suite_focus=true

Avoid aliased emoji

---

scylla/manifest.json

Better describe the features of the Scylla integration
@FlorianVeaux 😄

Update scylla tagline

---

php_fpm/README.md

Correct integration name
Came up on a ticket

Correct integration name

---

snmp/datadog_checks/snmp/config.py
snmp/datadog_checks/snmp/snmp.py
snmp/tests/test_check.py
snmp/tests/test_e2e.py

This adds a new uptime metric for all SNMP devices.

Fetch sysUpTimeInstance automatically

---

ceph/metadata.csv

Rates have a gauge in-app type.

Fix metadata rate

---

vsphere/datadog_checks/vsphere/api_rest.py
vsphere/datadog_checks/vsphere/config.py
vsphere/datadog_checks/vsphere/data/conf.yaml.example
vsphere/tests/test_check.py

Renaming vsphere_tags_prefix config to tags_prefix

---

pdh_check/README.md

Reformatted metrics section to highlight custom metrics only
[JIRA](https://datadoghq.atlassian.net/browse/DOCS-616) request

PDH Metrics edits

---

couchbase/README.md

Updates a couchbase service check name.
There is a mistake in the check name. Correct check name from the code: https://github.com/DataDog/integrations-core/blob/master/couchbase/datadog_checks/couchbase/couchbase_consts.py#L12

Update couchbase service check name

---

postgres/tests/compose/docker-compose.yaml
postgres/tests/test_integration.py

The newest docker images now require to have a password.

Pass password to docker image

---

flink/manifest.json

Make flink private

---

flink/README.md
flink/datadog_checks/flink/data/conf.yaml.example

Adds documentation on how to enable flink logs.

Add flink logs

---

oracle/README.md

Changes the config file path typo from int to etc
JIRA request

[Docs] Oracle docs typo

---

datadog_checks_dev/datadog_checks/dev/tooling/configuration/spec.py
datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/default.yaml
datadog_checks_dev/tests/tooling/configuration/consumers/test_example.py

Easier to broadly alter default options

Add ability for config templates to reference other templates

---

openshift/README.md

adds a note about log collection
pm request

[DOCS-406] refer users to k8s log file collection method

---

snmp/datadog_checks/snmp/data/conf.yaml.example
snmp/datadog_checks/snmp/data/profiles/hpe-proliant.yaml
snmp/tests/conftest.py
snmp/tests/test_check.py

Adding SNMP profile for HPE Proliant

Add hpe proliant profile

---

openshift/README.md

Run Agent with elevated privileges to collect metrics from Docker in Openshift

[Docs] Openshift note about running Agent with elevated privileges 

---

kong/assets/configuration/spec.yaml
kong/datadog_checks/kong/data/conf.yaml.example
kong/datadog_checks/kong/kong.py
kong/manifest.json

Adds RequestsWrapper to Kong
kong-need-additional-headers-for-authentication

Adds RequestsWrapper to Kong

---

flink/metadata.csv

Provide more units for flink metrics
