DataDog/integrations-core

flink/CHANGELOG.md, flink/MANIFEST.in, flink/datadog_checks/__init__.py, flink/datadog_checks/flink/__about__.py, flink/datadog_checks/flink/__init__.py, flink/datadog_checks/flink/data/__about__.py, flink/datadog_checks/flink/data/__init__.py, flink/datadog_checks/flink/data/conf.yaml.example, flink/requirements-dev.txt, flink/setup.py
=> Add flink required files

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/requirements.in
They don't understand how wheels work https://bitbucket.org/stoneleaf/enum34/issues/27/enum34-118-broken
=> Pin enum34 to 1.1.6

harbor/setup.py
Update base dependency to latest version that had changes to requests or requests wrapper.
See original PR #5468
=> Update base dependency for harbor

vsphere/setup.py
We need it for the extra_headers feature
=> Bump base version

consul/setup.py, windows_service/setup.py
Reason: https://github.com/DataDog/integrations-core/pull/5539/files
=> Bump minimun agent version

apache/setup.py, kong/setup.py, vault/setup.py
Update dependencies for datadog_checks_base due to changes from this PR: #5805 
Affects:
- apache
- kong
- vault
=> Update datadog_checks_base dependencies

openstack_controller/setup.py
Update the base dependency.
See #5586
=> Bump datadog_checks_base dependency to 11.0.0

win32_event_log/setup.py, wmi_check/setup.py
Reason: https://github.com/DataDog/integrations-core/pull/5510
=> Bump minimum base check on wmi checks

datadog_checks_dev/setup.py
Pin virtualenv due to https://github.com/pypa/virtualenv/issues/1669
Demo: https://github.com/DataDog/integrations-core/pull/5892
=> Pin virtualenv due to https://github.com/pypa/virtualenv/issues/1669

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_downloader/requirements.in
https://github.com/secure-systems-lab/securesystemslib/releases/tag/v0.14.2
=> Bump securesystemslib to 0.14.2

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/config.py
Handle logs only integrations for config validator
Needed for https://github.com/DataDog/integrations-core/pull/5898
=> Handle logs only integrations for config validator

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/config.py
=> Include flink in logs only integrations for validation

vsphere/datadog_checks/vsphere/data/conf.yaml.example
Adds default tags section in vsphere conf.yaml
=> Add tags section in conf.yaml

redisdb/metadata.csv
Update the description to match metrics type
RATE_KEYS [here](https://github.com/DataDog/integrations-core/blob/master/redisdb/datadog_checks/redisdb/redisdb.py#L93-L102) are submitted as rate: https://github.com/DataDog/integrations-core/blob/master/redisdb/datadog_checks/redisdb/redisdb.py#L241
https://trello.com/c/Uh1tszN8/1960-sometimes-redisstatskeyspacehits-reports-0
=> [doc]update description for redis metrics

http_check/datadog_checks/http_check/data/conf.yaml.example
Cleanup for #5775 (itself a cleanup for #5770).
A customer was confused to see it in the example config although we are now encouraging the use of `tls_verify`.
=> Update reference to `disable_ssl_validation`

spark/tests/test_spark.py
Adding small test for https://github.com/DataDog/integrations-core/pull/5465
=> Add test for spark version collection

postgres/datadog_checks/postgres/postgres.py, postgres/tests/common.py, postgres/tests/test_unit.py
Testing addition from https://github.com/DataDog/integrations-core/pull/5710
=> Add unit tests for build relations filter and remove unneeded code

datadog_checks_base/tests/test_wmisampler.py
Reason: No tests included in https://github.com/DataDog/integrations-core/pull/5510
=> Add wmi sampler tests

cisco_aci/tests/test_cisco.py
Add config test for requests wrapper https://github.com/DataDog/integrations-core/pull/5684
=> Add test for config options

datadog_checks_base/tests/test_agent_check.py
=> Cover setting 0 limit on an unlimited check

jboss_wildfly/README.md, jboss_wildfly/datadog_checks/jboss_wildfly/data/conf.yaml.example
This includes a few doc fixes:
* Mention the jmx service check
* Mention the need of a custom jar
* Fill missing doc in the sample file
=> Various doc fixes

snmp/datadog_checks/snmp/data/profiles/hp-ilo4.yaml
=> Remove unnecessary forced_type

tenable/README.md
Fix link and formatting
Observation of [docs page](https://docs.datadoghq.com/integrations/tenable/#configuration)
N/A
=> [Docs] Tenable

tenable/README.md, tenable/manifest.json
=> Updated display name and 

windows_service/tests/test_windows_service.py
Add minor extra test for better coverage.
=> Add warning test

dns_check/assets/service_checks.json
Tags were wrong, see https://github.com/DataDog/integrations-core/blob/1bf1bcf5f4af4a54f16bf45ad76d55c4f364ce05/dns_check/datadog_checks/dns_check/dns_check.py#L140-L145
=> Fix "dns_check" service check metadata

oracle/tests/test_e2e.py
=> [test] Add more metrics to e2e tests

docker_daemon/datadog_checks/docker_daemon/docker_daemon.py
=> Old style exceptions are syntax errors in Python

couchbase/README.md, couchbase/datadog_checks/couchbase/data/conf.yaml.example
Changes the couchbase path and source for log collection to be specific to couchbase, not couchdb.
This PR changes the README and the example yaml.
Internal review
=> Update `conf.yaml.example` log collection section

datadog_checks_base/datadog_checks/base/__about__.py, datadog_checks_dev/setup.py
https://github.com/pypa/virtualenv/issues/1669#issuecomment-595087025
=> Upgrade virtualenv to 20.0.8

etcd/README.md
Fixing AD param to match configuration: https://github.com/DataDog/integrations-core/blob/master/etcd/datadog_checks/etcd/data/conf.yaml.example#L34
https://github.com/DataDog/documentation/issues/6765
=> Fixing AD param

docker_daemon/CHANGELOG.md, docker_daemon/README.md, docker_daemon/assets/service_checks.json, docker_daemon/datadog_checks/__init__.py, docker_daemon/datadog_checks/docker_daemon/__about__.py, docker_daemon/datadog_checks/docker_daemon/__init__.py, docker_daemon/datadog_checks/docker_daemon/data/conf.yaml.example, docker_daemon/datadog_checks/docker_daemon/docker_daemon.py, docker_daemon/manifest.json, docker_daemon/metadata.csv, docker_daemon/setup.py, docker_daemon/test/test_docker_daemon.py
Backport docker daemon changes from master to agent-v5 before removal (https://github.com/DataDog/integrations-core/pull/5988)
=> Backport docker-daemon changes

datadog_checks_base/datadog_checks/base/utils/__init__.py, datadog_checks_base/datadog_checks/base/utils/tracing.py, datadog_checks_base/tests/test_tracing.py, snmp/datadog_checks/snmp/snmp.py
Add better support for thread tracing and profiling.
=> Expand tracing options and support threads

datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/jmx.yaml, hive/datadog_checks/hive/data/conf.yaml.example
Remove examples from jmx template
We expect those values to be changed.
=> Remove examples from jmx template

snmp/README.md
=> Link SNMP Profiles to README

snmp/datadog_checks/snmp/config.py, snmp/datadog_checks/snmp/resolver.py, snmp/datadog_checks/snmp/snmp.py
- Add types to `OIDResolver`, and broken associated type hints in `InstanceConfig`.
- Refactor/split methods and add docstrings.
- Help readers understand what `OIDResolver` class does and what its purpose is.
- Improve readability in general.
=> Refactor and add types to `OIDResolver`

.github/CODEOWNERS
DataDog/baklava is no more, long live DataDog/documentation !
=> Using DataDog/documentation as new team

scylla/README.md, scylla/datadog_checks/scylla/data/conf.yaml.example
Updates the README and the conf.yaml.example file.
=> Add documentation for scylla logs integration

process/datadog_checks/process/cache.py, process/datadog_checks/process/data/conf.yaml.example, process/datadog_checks/process/lock.py, process/datadog_checks/process/process.py, process/tests/test_lock.py, process/tests/test_process.py
Uses a single process list for all check runners, protected by a ReadWriteLock.
Only gets useful attributes from `psutil.process_iter`.
Try to improve process check performance, it's responsible for high CPU spikes on Windows environments.
=> Improve check performance

envoy/tests/docker/default/Dockerfile-xds
Docker image was not being build correctly anymore
=> Fix e2e tests

fluentd/datadog_checks/fluentd/fluentd.py
Reason: https://github.com/DataDog/integrations-core/pull/5057#issuecomment-597429953
=> Allow disabling metadata collection in fluentd

gitlab/README.md
Add note about gitlab version.
=> Add note to readme

eks_fargate/README.md
Adds disclaimer about container metrics in Fargate.
=> [DOCS-690] Adding disclaimer for container metrics

agent_metrics/manifest.json, amazon_msk/manifest.json, external_dns/manifest.json, flink/manifest.json, scylla/manifest.json
Enable bots to index `README.md` content for the Datadog public documentation.
=> Mark integrations public for 7.18 release

flink/README.md
=> Update flink readme to not be version specific

datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/init_config/jmx.yaml, datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/jmx.yaml, hive/datadog_checks/hive/data/conf.yaml.example
Moved to a separate PR from https://github.com/DataDog/integrations-core/pull/5733#issuecomment-599957710
=> Fix JMX spec doc

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/setup.py, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/setup.py, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/setup.py
We're testing on 3.8 now, let's change the default setup.py.
=> Bump classifiers

datadog_checks_dev/datadog_checks/dev/tooling/commands/clean.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/config.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/prometheus.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/scripts/remove_labels.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/scripts/upgrade_python.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/release/make.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/release/tag.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/release/testable.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py
=> Update docs to be markdown compatible

supervisord/README.md, supervisord/datadog_checks/supervisord/data/conf.yaml.example
=> Update Supervisord doc

.azure-pipelines/scripts/sqlserver/windows/32_install_odbc.bat
The previous download link was reporting 404 in CI runs, this PR updates it to the latest version.
=> Update ODBC download URL

cassandra/README.md
Fix an error in the documentation
The docs are incorrect
=> Pattern needs to be quoted

kafka/README.md
related https://github.com/DataDog/logs-backend/pull/8331
document a new kafka log format integration (cf: https://github.com/apache/kafka/blob/trunk/config/log4j.properties#L22-L23 )
=> document a new kafka log format integration

confluent_platform/metadata.csv
Fix metadata.csv to match metrics in https://github.com/DataDog/integrations-core/blob/master/confluent_platform/datadog_checks/confluent_platform/data/metrics.yaml
=> Fix metadata.csv

mongo/datadog_checks/mongo/metrics.py, mongo/datadog_checks/mongo/mongo.py, mongo/tests/test_unit.py
Extract all metric constants from `mongo.py` to `metrics.py`
=> Extract metrics constants to a separate file

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/imports.py, datadog_checks_dev/datadog_checks/dev/tooling/utils.py, datadog_checks_dev/tests/tooling/test_utils.py
Adds a `get_check_files` function to dev utils to aid in accessing various files per check.
In the PR for #6081 a suggestion was made to move the logic to a utility function.
=> Add get_check_files utility function

envoy/tests/docker/default/Dockerfile-xds, envoy/tests/docker/default/controlplane.go
Fix envoy integration test
```
---------------------------- Captured stdout setup -----------------------------
Step 1/6 : FROM gcr.io/istio-testing/go-control-plane-ci:08-20-2019
---> b0050d42e594
Step 2/6 : RUN go get github.com/envoyproxy/go-control-plane/envoy/api/v2
---> Using cache
---> 6c6fc37b5ca4
Step 3/6 : RUN go get github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1
---> Using cache
---> 26e1b204e232
Step 4/6 : COPY controlplane.go /go-control-plane/controlplane.go
---> Using cache
---> b79bc0919a9c
Step 5/6 : RUN go build
---> Running in ac1f6ebb2f4e
./controlplane.go:55:23: undefined: cache.Resource
```
https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=11240&view=logs&j=5e7fd8a3-b132-5246-3e9c-553f252343b6&t=d902c9d7-22a7-5fac-5c7d-d0e58f …
=> Fix envoy integration test

oracle/README.md
=> Add notice to install microsoft visual c++ runtime 2015

haproxy/datadog_checks/haproxy/haproxy.py
=> Fix event submission on Python 3

ceph/datadog_checks/ceph/ceph.py
https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=11368&view=logs&jobId=155efd4a-3db6-57a2-0ce3-7e8c157a4e0a&j=155efd4a-3db6-57a2-0ce3-7e8c157a4e0a&t=14ad84b1-deaa-56ae-fa3a-8c65976e41fb
=> Fix response handling

datadog_checks_base/datadog_checks/base/utils/serialization.py, datadog_checks_base/setup.py, datadog_checks_base/tests/test_serialization.py
Make it easier for our ARM builders to run tests
Also added a log line and a test
=> Exclude optional JSON lib from required `deps`

twistlock/setup.py
Follow-up to https://github.com/DataDog/integrations-core/pull/6143, see https://github.com/DataDog/integrations-core/pull/6155
=> Update base pin

flink/assets/dashboards/overview.json
Update flink dashboard based on revisions from writing team.
=> Update flink dashboard

airflow/metadata.csv, airflow/tests/test_integration_e2e.py
=> Fix metrics types

external_dns/manifest.json
Sync `metric_to_check` with the one that's actually submitted (and listed in `metadata.csv`).
It's wrong right now :-)
Also pre-requisite to making #6170 pass
=> Fix `metric_to_check`

datadog_checks_dev/datadog_checks/dev/tooling/configuration/consumers/example.py, datadog_checks_dev/tests/tooling/configuration/consumers/test_example.py
https://github.com/DataDog/integrations-core/pull/6142/files#r399296131
=> Add `default` value field for config specs

istio/datadog_checks/istio/istio.py, istio/metadata.csv, istio/tests/common.py
**Motivation**
High cardinality
Following same pattern as https://github.com/DataDog/integrations-core/pull/4433
=> Blacklist mcp_source.request_acks_total

confluent_platform/datadog_checks/confluent_platform/data/metrics.yaml, confluent_platform/tests/metrics.py
=> Fix metrics rule

redisdb/README.md
=> Added Tracing setup instructions to Redis

mongo/README.md
=> Add Tracing instructions to Mongo integration

elastic/README.md
=> Add Tracing instructions for ElasticSearch integration

postgres/README.md
=> Add instructions to Postgres integration

mcache/README.md
=> Add tracing instructions to Memcache integration

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/catalog.py, datadog_checks_dev/datadog_checks/dev/tooling/utils.py
=> Consider log collection from the readme

gitlab/manifest.json
Updates metric to check in gitlab
https://github.com/DataDog/integrations-core/pull/6201 used a distribution metric
=> Update metric to check

hive/tests/compose/docker-compose.yaml
We need additional options to make it work through docker.
=> Expose JMX on localhost

snmp/datadog_checks/snmp/data/conf.yaml.example
The sample given isn't correct, it doesn't match properly the regular
expression.
=> Fix tag matching documentation

confluent_platform/assets/configuration/spec.yaml, confluent_platform/assets/service_checks.json, confluent_platform/datadog_checks/confluent_platform/data/conf.yaml.example, confluent_platform/tests/test_e2e.py
Depend on https://github.com/DataDog/integrations-core/pull/6163
=> Fix service check name

snmp/datadog_checks/snmp/data/profiles/dell-poweredge.yaml, snmp/datadog_checks/snmp/data/profiles/generic-router.yaml, snmp/datadog_checks/snmp/data/profiles/hp-ilo4.yaml, snmp/datadog_checks/snmp/data/profiles/hpe-proliant.yaml, snmp/datadog_checks/snmp/data/profiles/idrac.yaml, snmp/datadog_checks/snmp/data/profiles/meraki-cloud-controller.yaml, snmp/tests/test_profiles.py
This mostly adds _base.yaml to the profiles missing it.
=> Small profiles cleanups

jboss_wildfly/assets/configuration/spec.yaml, jboss_wildfly/assets/service_checks.json, jboss_wildfly/datadog_checks/jboss_wildfly/data/conf.yaml.example, jboss_wildfly/manifest.json, jboss_wildfly/tests/test_check.py
Depend on:
- https://github.com/DataDog/integrations-core/pull/6230
- https://github.com/DataDog/integrations-core/pull/6229
=> Fix service check name and add config spec

datadog_checks_base/datadog_checks/base/utils/common.py, datadog_checks_base/tests/test_utils.py, elastic/datadog_checks/elastic/elastic.py, haproxy/datadog_checks/haproxy/haproxy.py, kubernetes_state/datadog_checks/kubernetes_state/kubernetes_state.py, linkerd/tests/conftest.py, vsphere/datadog_checks/vsphere/legacy/vsphere_legacy.py, vsphere/datadog_checks/vsphere/utils.py, vsphere/datadog_checks/vsphere/vsphere.py, vsphere/tests/test_check.py
Revert https://github.com/DataDog/integrations-core/pull/5996 for integrations (not base).
=> Revert `to_native_string` to `to_string` for integrations

openmetrics/datadog_checks/openmetrics/data/conf.yaml.example
Run `ddev validate config --sync`
`master` is broken:
```
$ ddev validate config       
Validating default configuration files...
openmetrics:
File `conf.yaml.example` needs to be synced
Files with errors: 1
Files valid: 174
```
It's a race condition: #5833 was merged w/o changes from #6142, then #6247 was merged w/o changes from #5833.
=> Sync OpenMetrics config

sidekiq/README.md, sidekiq/metadata.csv
- Simplifies metric remapping needed for Sidekiq
- Makes description of perform metrics more descriptive
Review and testing with writing team.
=> Update sidekiq perform remapping and description

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py, directory/setup.py
Addresses minor bug in PR #6254 for checking config in e2e tests.
=> Fix e2e config

aerospike/README.md
Add comments and arrange content to support tabs on the public docs site
Page readability
- Changes only affect the public docs site
- Related PR: https://github.com/DataDog/documentation/pull/6954
=> DOCS-721 Aerospike tabs

ibm_mq/datadog_checks/ibm_mq/connection.py
This breaks some local testing setup.
=> Don't import pymqi unconditionally

zk/datadog_checks/zk/zk.py
Resolves https://github.com/DataDog/integrations-core/issues/6321
=> Handle non-integers when parsing latency values

vsphere/datadog_checks/vsphere/data/conf.yaml.example
QA for #6215 - fixes small capitalization error in vSphere config
=> Fix vsphere capitalization

gitlab/metadata.csv
Updates gitlab `metadata.csv` to remove unicode quotes.
=> Don't use unicode string in gitlab metadata

oracle/README.md
Removed 3rd step from Oracle Instant Client docs per request
Jira request for the docs team
=> Removed step from Oracle docs

.azure-pipelines/templates/run-validations.yml, aerospike/tests/test_unit.py, proxysql/tests/test_proxysql.py
=> Fix deprecated imports

openstack/README.md, openstack_controller/README.md
Links OpenStack and openstack_controller docs so they can be more easily referenced  by customers.
=> Morgan.lupton/link openstack and controller docs

openstack/README.md, openstack_controller/README.md
Replacing markdown bold w/ HTML bold because it doesn't work in this div
=> [PROD] fix bolding in note in openstack docs

rethinkdb/manifest.json, varnish/manifest.json
Updates the `varnish` integration signature and adds a signature to `rethinkdb`
We want to update these integrations signature so we'd be able to autodetected them by matching a process command line.
@DataDog/processes
=> [proc] Update integrations signature

couch/tests/conftest.py
https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=12831&view=logs&j=c73aedc7-d1f1-5bee-93b6-629007590bd5&t=cf069ff2-7a0e-5fd9-5497-1142afc72d27&l=445
=> Fix flakes

istio/assets/configuration/spec.yaml, istio/datadog_checks/istio/data/conf.yaml.example, istio/manifest.json
Add config spec with openmetrics config template to istio
=> Add config spec

win32_event_log/datadog_checks/win32_event_log/win32_event_log.py, win32_event_log/tests/test_check.py
This change normalizes integers event values.
In some circumstances, some integer values might be returned as float.
Before this change the message contain `EventCode: 1000.0`, now it's `EventCode: 1000`.
User request. Make sense to normalize since those are integers, not a floats.
=> Normalize integers

haproxy/tests/conftest.py, haproxy/tests/test_haproxy.py
Add tcp instance to e2e
Easier QA.
=> Add tcp instance to e2e

tomcat/assets/configuration/spec.yaml, tomcat/datadog_checks/tomcat/data/conf.yaml.example, tomcat/manifest.json
=> Use config spec

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/config.py
Add verbose mode to validate config
Useful for displaying checks without specs.
=> Add verbose mode to validate config

tomcat/assets/configuration/spec.yaml
Spec need to be updated due to https://github.com/DataDog/integrations-core/pull/6328
=> Fix config spec

aerospike/tests/test_unit.py
=> Properly name test method.

http_check/metadata.csv, http_check/tests/test_integration_e2e.py
Assert metrics in metadata.csv
=> Assert metrics in metadata.csv

.stubs/pyVmomi/__init__.pyi, .stubs/pyVmomi/vim/__init__.pyi, .stubs/pyVmomi/vim/event.pyi, .stubs/pyVmomi/vim/view.pyi, .stubs/pyVmomi/vmodl/__init__.pyi
- Add stubs removal todo for pyVmomi
- Backport changes from https://github.com/python/typeshed/pull/3921
Reminder to remove the stubs when upstream PR is merged.
=> Update pyVmomi stubs

snmp/datadog_checks/snmp/commands.py, snmp/datadog_checks/snmp/snmp.py, snmp/tox.ini
- Fix remaining type checking issues in `snmp.py` and `commands.py`.
- Activate `dd_check_types` on all modules.
Most modules were type checked already, but notably `snmp.py` was not type checked yet, which could cause types to drift there.
=> Check types on all modules

nginx_ingress_controller/README.md
Update installation instructions to better emphase AD instructions as this integration is primarily for the Agent running in a Container.
Just a better doc for a better world.
=> [DOCS-435] Using new AD template format

vsphere/README.md
Adds a disclaimer above the metrics table to warn about the collection level parameter behaviour.
=> [DOCS-385] Adding disclaimer for collection level

kafka_consumer/tests/conftest.py, kafka_consumer/tests/docker/docker-compose.yaml
=> Increase timeouts & pin zookeeper image

.azure-pipelines/scripts/ibm_mq/linux/55_install_client.sh
Retry curl on CI
Make CI less flaky.
=> Retry curl on CI

snmp/datadog_checks/snmp/snmp.py, snmp/datadog_checks/snmp/types.py
We don't have repr on the debug printer.
=> Fix debug output

couch/tests/conftest.py
Split conditions with longer waits and add a bit more to the last one
=> Add more wait time for last condition

.azure-pipelines/scripts/sqlserver/windows/40_install_sqlserver.py, .azure-pipelines/scripts/sqlserver/windows/55_setup_sqlserver.bat, datadog_checks_dev/datadog_checks/dev/tooling/commands/ci/setup.py, datadog_checks_dev/setup.py
Sandbox PR https://github.com/DataDog/integrations-core/pull/6420
Fix flaky CI by retrying sql-server install
Example of retry build:
https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=13438&view=logs&jobId=2064ccbf-f126-5e0d-1852-308004bf09c4&j=2064ccbf-f126-5e0d-1852-308004bf09c4&t=ae56cbae-b97f-5880-ee8c-b02fcb57b4a6
```
D:\a\1\s>sqlcmd -Q "ALTER LOGIN sa with PASSWORD = 'Password12!';ALTER LOGIN sa ENABLE;" 
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Named Pipes Provider: Could not open a connection to SQL Server [2]. .
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL …
```
=> Fix flaky CI by retrying sql-server install

proxysql/assets/dashboards/-_overview.json, proxysql/assets/dashboards/overview.json, proxysql/manifest.json
Internal link: https://dddev.datadoghq.com/dashboard/258-j85-hpt/proxysql-overview
=> Add ProxySQL dashboard

ecs_fargate/assets/dashboards/amazon_fargate_overview.json
Moved commits from https://github.com/DataDog/integrations-core/pull/6284 in order to sync dashboard on staging. Added integration logo back
=> Update OOTB dashboard for ECS Fargate with new network metrics 

snmp/datadog_checks/snmp/metrics.py, snmp/datadog_checks/snmp/models.py, snmp/datadog_checks/snmp/pysnmp_inspect.py
We have a few necessary `HACK` to introspect PySNMP values, so this PR centralizes them in a dedicated module.
More easily keep track track of our hacks, and keep the main logic clean.
Extracted from https://github.com/DataDog/integrations-core/pull/6411
=> Isolate PySNMP inspection hacks

vault/manifest.json
=> removes docs categories

istio/README.md
Add instructions to istio readme about new endpoint config.
=> Update readme with 1.5 instructions

clickhouse/tests/test_unit.py
https://github.com/ClickHouse/ClickHouse/pull/10042
=> Update location of metrics tests

active_directory/tests/test_active_directory.py
=> Assert metrics using metadata

istio/README.md, istio/assets/service_checks.json
The `service_checks.json` was previously never updated.
=> Document new and legacy service checks

istio/assets/dashboards/istio_1_5_overview, istio/manifest.json
=> Add istio 1.5 dashboard

snmp/datadog_checks/snmp/config.py, snmp/tests/test_unit.py
This will help supporting autodiscovery.
=> Remove empty values in config

iis/assets/saved_views/4xx_errors.json, iis/assets/saved_views/5xx_errors.json, iis/assets/saved_views/bot_errors.json, iis/assets/saved_views/response_time.json, iis/assets/saved_views/status_code_overview.json, iis/manifest.json
Add saved views for the IIS integration
Saved views are now included in integrations
- https://github.com/DataDog/integrations-core/pull/5866
- https://github.com/DataDog/integrations-core/pull/5865
- https://github.com/DataDog/integrations-core/pull/5713
=> Add IIS integration saved views

mongo/assets/saved_views/operations.json, mongo/assets/saved_views/operations_by_type_overview.json, mongo/assets/saved_views/queries.json, mongo/assets/saved_views/queries_by_type_overview.json, mongo/assets/saved_views/slow_queries.json, mongo/manifest.json
Add saved views for the Mongo integration
Saved views are now included in integrations
- https://github.com/DataDog/integrations-core/pull/5713
- https://github.com/DataDog/integrations-core/pull/5865
- https://github.com/DataDog/integrations-core/pull/5866
- https://github.com/DataDog/integrations-core/pull/5870
- https://github.com/DataDog/integrations-core/pull/5871
- https://github.com/DataDog/integrations-core/pull/5872
- https://github.com/DataDog/integrations-core/pull/5873
- https://github.com/DataDog/integrations-core/pull/6386
- https://github.com/DataDog/integrations-core/pull/6393
- https://github.com/DataDog/integrations-core/pull/6401
- https://github.com/DataDog/integrations-core/pull/6402
=> Add Mongo integration saved views

varnish/assets/saved_views/4xx_errors.json, varnish/assets/saved_views/5xx_errors.json, varnish/assets/saved_views/bot_errors.json, varnish/assets/saved_views/status_code_overview.json, varnish/manifest.json
Add saved views for the Varnish integration
Saved views are now included in integrations
- https://github.com/DataDog/integrations-core/pull/5713
- https://github.com/DataDog/integrations-core/pull/5865
- https://github.com/DataDog/integrations-core/pull/5866
- https://github.com/DataDog/integrations-core/pull/5870
- https://github.com/DataDog/integrations-core/pull/5871
- https://github.com/DataDog/integrations-core/pull/5872
- https://github.com/DataDog/integrations-core/pull/5873
- https://github.com/DataDog/integrations-core/pull/6386
- https://github.com/DataDog/integrations-core/pull/6393
- https://github.com/DataDog/integrations-core/pull/6401
- https://github.com/DataDog/integrations-core/pull/6402
- https://github.com/DataDog/integrations-core/pull/6403
- …
=> Add Varnish integration saved views

vault/assets/saved_views/error_warning_status.json, vault/assets/saved_views/service_name_overview.json, vault/assets/saved_views/vault_patern.json, vault/manifest.json
Add saved views for the Vault integration
Saved views are now included in integrations
- https://github.com/DataDog/integrations-core/pull/5713
- https://github.com/DataDog/integrations-core/pull/5865
- https://github.com/DataDog/integrations-core/pull/5866
- https://github.com/DataDog/integrations-core/pull/5870
- https://github.com/DataDog/integrations-core/pull/5871
- https://github.com/DataDog/integrations-core/pull/5872
- https://github.com/DataDog/integrations-core/pull/5873
- https://github.com/DataDog/integrations-core/pull/6386
- https://github.com/DataDog/integrations-core/pull/6393
- https://github.com/DataDog/integrations-core/pull/6401
- https://github.com/DataDog/integrations-core/pull/6402
- https://github.com/DataDog/integrations-core/pull/6403
- …
=> Add Vault integration saved views

flink/metadata.csv
=> Remove duplicate metric descriptions

iis/datadog_checks/iis/iis.py
Needed for adding new metrics in the next PR
=> Refactor check to allow collection of counters not of class `Web Service`

confluent_platform/manifest.json, hazelcast/manifest.json, ignite/manifest.json, proxysql/manifest.json, rethinkdb/manifest.json, sidekiq/manifest.json
Make integrations public, documentation will be made public.
=> Make all new integrations public

hazelcast/manifest.json, ignite/manifest.json
Those two integrations are not yet released
=> Fix is_public

gitlab_runner/metadata.csv, gitlab_runner/tests/common.py, gitlab_runner/tests/test_integration_e2e.py
- removes duplicate descriptions and short names in metadata.csv
- apply some grammar fixes to metadata
- assert metadata in e2e tests
=> Remove duplicates in metadata and asset metadata metrics

vault/README.md, vault/tests/common.py, vault/tests/conftest.py, vault/tests/docker/docker-compose.yaml, vault/tests/docker/metrics_policy.hcl, vault/tests/docker/vault_server_config_noauth.json, vault/tests/test_integration.py, vault/tests/test_vault.py, vault/tox.ini
- Better docs
- Better test coverage
- `/sys/leader` and `/sys/health` are accessible without token
- token is required by default to access `/sys/metrics`
```
root@docker-desktop:/# curl http://localhost:8200/v1/sys/leader
{"ha_enabled":true,"is_self":true,"leader_address":"http://172.23.0.3:8200","leader_cluster_address":"https://172.23.0.3:8201","performance_standby":false,"performance_standby_last_remote_wal":0}
root@docker-desktop:/# curl http://localhost:8200/v1/sys/health
{"initialized":true,"sealed":false,"standby":false,"performance_standby":false,"replication_performance_mode":"disabled","replication_dr_mode":"disabled","server_time_utc":1588065887,"version":"1.4.0","cluster_name":"vault-cluster-3bdb9d48","cluster_id":"3ea9b1c4-9881-6a37-bc3a-602d39208e82"} …
```
=> Add authentication doc and tests

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/env/test.py, datadog_checks_dev/datadog_checks/dev/tooling/config.py
Consistency,
- https://github.com/DataDog/integrations-core/pull/5197
- https://github.com/DataDog/integrations-core/pull/6254
=> Add dedicated config section for E2E agent selection

snmp/datadog_checks/snmp/config.py, snmp/datadog_checks/snmp/data/conf.yaml.example, snmp/tests/test_unit.py
Change default timeout form 1 to 5
=> Change default timeout to 5

mongo/assets/configuration/spec.yaml, mongo/datadog_checks/mongo/data/conf.yaml.example, mongo/datadog_checks/mongo/mongo.py, mongo/tests/common.py, mongo/tests/conftest.py, mongo/tests/test_mongo.py, mongo/tests/test_unit.py
Support for using secrets for password. Also, easier to configure and debug
=> Refactor connection configuration

rabbitmq/metadata.csv, rabbitmq/tests/test_integration_e2e.py
Asserts metadata and removes duplicate descriptions in rabbitmq
=> Remove duplicate metric descriptions in metadata

snmp/datadog_checks/snmp/config.py, snmp/datadog_checks/snmp/data/conf.yaml.example, snmp/tests/test_check.py
Add a auto_conf file, and allow specifying protocols with shorter names.
=> Improve autodiscovery support

eks_fargate/README.md
makes note that process collection is not currently available for eks fargate
pm request
=> [DOCS-690] document eks fargate limitations

datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py, datadog_checks_dev/datadog_checks/dev/tooling/e2e/local.py
https://github.com/DataDog/integrations-core/pull/6589
=> Install checks' dependencies for E2E using `deps` extra feature

disk/README.md
Fix broken conf link
Fix broken link
correctness, caffeine 
none
=> Fix broken conf.yaml.example link for Disk check

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/assets/configuration/spec.yaml
=> Update JMX template to use JMX config spec

sqlserver/assets/configuration/spec.yaml, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example, sqlserver/manifest.json
Add the `spec.yaml` file to generate de `conf.yaml.example`
This file need to be there to start an environment that sends logs (https://github.com/DataDog/integrations-core/pull/6625)
=> Add spec.yaml

vsphere/datadog_checks/vsphere/config.py, vsphere/tests/test_filters.py
Customer encountered this confusing case
=> Properly error when filtering resources by the `tag` property but `collect_tags` is disabled

vsphere/tests/common.py, vsphere/tests/conftest.py
Useful for testing `ddev env start vsphere py38`
=> Add `dd_environment`

snmp/datadog_checks/snmp/data/auto_conf.yaml
Was supposed to be added in a previous PR.
=> Add missing auto_conf

aerospike/metadata.csv
Illegal quoting error on github
=> Fix illegal quoting in metadata description

sidekiq/README.md
=> Update quotes for regex mapping

.flake8
Fix flake8 exclude paths (`flake8 3.8.2`)
Breaking 2 exclude rules
https://gitlab.com/pycqa/flake8/-/merge_requests/431
=> Fix flake8 exclude paths

docs/developer/tutorials/snmp/profiles.md
`ddev -k test_stuff ...` -> `ddev test -k test_stuff ..`
=> Fix example

mapr/requirements-dev.txt
Pin test dep confluent_kafka to 1.4.1
https://github.com/confluentinc/confluent-kafka-python/issues/882
=> Pin test dep confluent_kafka to 1.4.1

snmp/metadata.csv, snmp/tests/test_profiles.py
=> Add `bgpPeerFsmEstablishedTime` to metadata.csv

sqlserver/README.md, sqlserver/assets/configuration/spec.yaml, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example, sqlserver/manifest.json, sqlserver/requirements.in, sqlserver/tests/compose/docker-compose.yaml, sqlserver/tests/conftest.py
Add SQL Server log documentation
Allow the test environment to be used for logs
=> Add sqlserver log support

.stubs/pyVmomi/vim/event.pyi, vsphere/README.md, vsphere/datadog_checks/vsphere/api.py, vsphere/datadog_checks/vsphere/legacy/event.py, vsphere/tests/test_event.py
Add ALLOWED_EVENTS
Avoid retrieving non used events.
=> Filter by allowed events

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/testable.py
Add author and labels to Trello card
It's convenient to have labels and author directly in Trello card.
=> Add author and labels to Trello release cards

mongo/README.md
Update the MongoDB README to show usage with the new connection configuration options.
Prompted by https://github.com/DataDog/integrations-core/pull/6688#discussion_r427536233
https://github.com/DataDog/integrations-core/pull/6574 added a new connection configuration interface but the README was not updated.
=> Update configuration instructions in README

rethinkdb/metadata.csv
Update `metadata.csv` to more clearly differentiate between what `client_connections` and `clients_active` mean.
The question came up while editing the GA announcement blog post.
=> Clarify difference between `client_connections` vs `clients_active`

envoy/tests/test_envoy.py
- QA for https://github.com/DataDog/integrations-core/pull/6685
=> Add additional exception test 

.github/workflows/docs.yml, README.md, docs/developer/index.md
We'll do https://github.com/DataDog/integrations-core/pull/6719 in a separate PR
=> Build and deploy new docs site with GitHub Actions

.azure-pipelines/templates/install-deps.yml, disk/datadog_checks/disk/__about__.py
I rebased on their master branch
https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=16612&view=logs&j=762a2123-1c7c-5bf0-0e62-04885c3ecd74&t=7c2e5104-22a0-57d1-ea6f-4dd05c8354a8&l=1707
=> Fix Codecov uploads

docs/developer/.snippets/links.txt, docs/developer/ddev/configuration.md, docs/developer/process/agent-release.md
- Included `trello_users_$team` as part of set up.
- Add note on Pypi
- Update communication to reflect new process
=> Update agent release page

docs/developer/.snippets/links.txt, docs/developer/guidelines/style.md
Add `mypy` section for the type checking.
=> Add mypy section

.codecov.yml, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/ci.py, datadog_checks_dev/datadog_checks/dev/tooling/utils.py
Ensures a flag is configured for every check for a better pull request experience, see https://docs.codecov.io/docs/carryforward-flags
https://blog.codecov.io/2020/04/21/new-test-only-what-you-change-with-carryforward-flags/
I think this has to be merged for comments to change, nothing happening yet
=> Add Codecov config validation

.codecov.yml
Finish https://github.com/DataDog/integrations-core/pull/6749
=> Update Codecov comments

mkdocs.yml, tox.ini
Eventually there will be a toggle:
- https://github.com/squidfunk/mkdocs-material/pull/1639#issuecomment-629761383
- https://github.com/squidfunk/mkdocs-material/issues/1716#issuecomment-634578496
=> Use dark mode for docs site

docs/developer/.snippets/uml.txt, docs/developer/assets/css/custom.css
Shout-out to @facelessuser for the help
Before:
After:
Before:
After:
=> Improve styling for dark mode

datadog_checks_dev/datadog_checks/dev/tooling/release.py
Resolves https://github.com/DataDog/integrations-core/pull/5512
=> Build packages with the current Python

mysql/README.md
fixes a link to the mysql documentation
=> [DOCS-905] - link update

istio/README.md
Remove note about 7.20.0
Make note for mesh metrics and `auto_conf.yaml`
=> Update README.md for 7.20.0

datadog_checks_base/datadog_checks/base/__about__.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py, datadog_checks_dev/datadog_checks/dev/tooling/config.py, datadog_checks_dev/datadog_checks/dev/tooling/e2e/agent.py, datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py, datadog_checks_dev/datadog_checks/dev/tooling/utils.py
Fixes https://github.com/DataDog/integrations-core/pull/6731
=> Update default E2E Agent configuration

datadog_checks_dev/setup.py
=> Update CLI dependencies

.azure-pipelines/templates/run-validations.yml, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/__init__.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/saved_views.py, datadog_checks_dev/datadog_checks/dev/tooling/utils.py
Adds validation for saved views
=> Add validation for saved views

.azure-pipelines/templates/test-all.yml, datadog_checks_base/datadog_checks/base/__about__.py
```
__built-in-schema.yml: Maximum events exceeded while evaluating the template. This may indicate an infinite loop or too many nested loops.
```
=> Avoid hitting Azure Pipelines max event/step limit

mysql/datadog_checks/mysql/data/conf.yaml.example, mysql/datadog_checks/mysql/mysql.py, mysql/tests/conftest.py, mysql/tests/test_mysql.py
=> Add custom queries

docs/developer/base/prometheus.md
=> Fix typo in prometheus.md

twistlock/metadata.csv, twistlock/tests/test_twistlock.py
- Remove duplicate short names and descriptions in metadata
- Assert metadata in tests
=> Remove duplicate short names and descriptions and assert metadata in tests

process/README.md, process/assets/configuration/spec.yaml, process/datadog_checks/process/data/conf.yaml.example, process/datadog_checks/process/process.py, process/manifest.json, process/setup.py, process/tests/test_process.py
Note to reviewers: It's best to review hiding whitespace changes
=> Config specs and new agent signature

mysql/README.md
updated link that was redirecting to the wrong place
=> [DOCS-918] link fix

ecs_fargate/README.md
removes section about live process monitoring because it isn't supported
yair request
=> [DOCS-860] remove live process monitoring section

docs/developer/tutorials/snmp/profiles.md
Add the `sysobjectid` line to the `.snmprec` example.
=> Add sysobjectid to snmprec

rethinkdb/manifest.json
Cleanup for https://github.com/DataDog/integrations-core/pull/6837
Forgot to update the dashboard title in `manifest.json` while updating it elsewhere… Realized this when looking at the `integration sync` PR content.
=> Fix dashboard title in manifest.json

win32_event_log/README.md
The filters in this page only apply to events, and not to logs, this should be reflected in the docs
It's confusing for our customers as they can think that they are able to filter logs.
=> Changed the filters title

hivemq/assets/configuration/spec.yaml, hivemq/datadog_checks/hivemq/data/conf.yaml.example
https://www.hivemq.com/docs/hivemq/4.2/user-guide/logging.html#event
=> Add event log file to example config

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/dashboards.py
- validate that dashboards have required fields
- remove unneeded `REQUIRED_ATTRIBUTES`
- update format string for python3
https://github.com/DataDog/integrations-core/pull/6787/
=> Validate that dashboards have required fields

exchange_server/assets/dashboards/overview.json, exchange_server/manifest.json
Add Exchange Server dashboard.
Hard time having nice metrics. Best screenshot I have for now
=> Exchange Server dashboard

tls/README.md
=> Add note only leaf certificates are verified

airflow/assets/dashboards/overview.json
Fix dashboard Can Connect
It was a typo.
=> Fix dashboard Can Connect

airflow/assets/dashboards/overview.json
Add scope and host
Consistent with the rest of the OOTB dashboard widgets.
=> Add scope and host

nginx_ingress_controller/assets/configuration/spec.yaml, nginx_ingress_controller/datadog_checks/nginx_ingress_controller/data/conf.yaml.example, nginx_ingress_controller/manifest.json
Adds openmetrics config spec to nginx ingress controller
Include additional openmetrics base check config options
=> Add configuration spec

sqlserver/manifest.json
**MERGE when 6/7.20 is officially released.**
Add MacOS support to `manifest.json`.
We added MacOS support here:
- https://github.com/DataDog/datadog-agent/pull/5555
- https://github.com/DataDog/integrations-core/pull/6633
=> Add MacOS support to `manifest.json`

network/assets/configuration/spec.yaml, network/datadog_checks/network/data/conf.yaml.default, network/manifest.json
Add spec for the network integration
=> Add network spec

elastic/README.md
- Add note concerning ES API requests
- Wording updates
N/A
=> DOCS-951 ES API requests

airflow/README.md
Fixes README to fix broken formatting in the main doc:
https://docs.datadoghq.com/integrations/airflow/#log-collection
Doc kapuut
=> [Airflow] Formatting fixes

twemproxy/datadog_checks/twemproxy/twemproxy.py, twemproxy/tests/common.py, twemproxy/tests/compose/docker-compose.yaml, twemproxy/tests/test_twemproxy.py, twemproxy/tox.ini
Collect version metadata for `twemproxy`
=> Collect version metadata

supervisord/README.md
Adds name parameter to instance config parameter in documentation
[DOCS-998](https://datadoghq.atlassian.net/browse/DOCS-998)
n/a
=> Add name value to supervisord instance config table

kube_apiserver_metrics/datadog_checks/kube_apiserver_metrics/data/conf.yaml.example
=> Sync example configs

hdfs_datanode/assets/configuration/spec.yaml, hdfs_datanode/datadog_checks/hdfs_datanode/data/conf.yaml.example, hdfs_datanode/manifest.json
=> Add config specs

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, ibm_mq/README.md, ibm_mq/manifest.json, ibm_mq/requirements.in, ibm_mq/tests/README.md, ibm_mq/tox.ini
Add MacOS Support
No code change. Only documentation update.
=> Add MacOS Support

ssh_check/datadog_checks/ssh_check/ssh_check.py, ssh_check/tests/conftest.py, ssh_check/tests/test_integration.py, ssh_check/tests/test_ssh.py
=> Agent6 style init

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, ibm_mq/README.md, ibm_mq/manifest.json, ibm_mq/requirements.in, ibm_mq/tests/README.md, ibm_mq/tox.ini
Reverts DataDog/integrations-core#6927
=> Revert "Add MacOS Support"

ibm_mq/datadog_checks/ibm_mq/collectors/__init__.py, ibm_mq/datadog_checks/ibm_mq/collectors/channel_metric_collector.py, ibm_mq/datadog_checks/ibm_mq/collectors/queue_metric_collector.py, ibm_mq/datadog_checks/ibm_mq/ibm_mq.py
=> Refactor by grouping collectors

zk/datadog_checks/zk/zk.py, zk/tests/conftest.py, zk/tests/test_zk.py
=> Use Agent6 style init

aerospike/metadata.csv
Fix typo in aerospike's metadata.csv
=> [aerospike] Fix latency description

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/README.md, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/README.md
https://github.com/DataDog/integrations-extras/pull/625
=> Fix README link for templates

eks_fargate/README.md
adds note on how to view eks fargate containers
support request
=> [DOCS-1006] eks fargate container view

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, ibm_mq/README.md, ibm_mq/manifest.json, ibm_mq/requirements.in, ibm_mq/tests/README.md, ibm_mq/tox.ini
Reverts DataDog/integrations-core#6931
Merge after these PRs:
• https://github.com/DataDog/datadog-agent/pull/5770
• https://github.com/DataDog/datadog-agent-buildimages/pull/50
=> Revert "Revert "Add MacOS Support""

vsphere/README.md
See https://github.com/DataDog/integrations-core/blob/master/vsphere/datadog_checks/vsphere/event.py
=> [docs] Clarify what events are emitted by the integration

snmp/datadog_checks/snmp/snmp.py, snmp/datadog_checks/snmp/types.py, snmp/datadog_checks/snmp/utils.py, snmp/tests/test_unit.py
Quick PR to clean up the implementation of OID batching with a dedicated `batches()` helper.
Cleaner code, reduce logic duplication, increase unit testing coverage
=> [Refactor] Clean up batching implementation

directory/datadog_checks/directory/config.py, directory/datadog_checks/directory/directory.py, directory/tests/conftest.py, directory/tests/test_directory.py, directory/tests/test_e2e.py, directory/tests/test_integration.py
=> Refactor config

directory/datadog_checks/directory/directory.py
Simplify walker recursive condition
=> Simplify walker recursive condition

ignite/assets/dashboards/ignite_overview.json, ignite/manifest.json
=> Add ignite dashboard

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/testable.py, datadog_checks_dev/datadog_checks/dev/tooling/trello.py
=> Add tools and libraries team to trello

.github/CODEOWNERS
Update CODEOWNERS for Security
Deprecation of ProdSec team
N/A
=> Update CODEOWNERS for Security

active_directory/requirements.in, aspdotnet/requirements.in, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/requirements.in, dotnetclr/requirements.in, exchange_server/requirements.in, iis/requirements.in, pdh_check/requirements.in, sqlserver/requirements.in, win32_event_log/requirements.in, windows_service/requirements.in, wmi_check/requirements.in
Need https://github.com/mhammond/pywin32/pull/1524 for `win32_event_log` rewrite
=> Upgrade pywin32 to 228

flink/manifest.json
- removes unnecessary categories from flink
=> Remove unneeded categories 

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, ssh_check/requirements.in
Bumps Paramiko to `2.1.6`.
Housekeeping.
=> [ssh_check] paramiko: bump to health 2.1.6

sidekiq/manifest.json
- remove unneeded category from sidekiq
=> Remove unneeded category

squid/datadog_checks/squid/squid.py
See https://github.com/DataDog/integrations-core/issues/6778
=> Fix formatting of a log line

oom_kill/manifest.json
Fix issue that validator did not catch due to bug (original PR https://github.com/DataDog/integrations-core/pull/6984)
=> Fix invalid integration_id

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/manifest.py
Refs #6848, see [comment](https://github.com/DataDog/integrations-core/pull/6848/files#r447506282)
Looks like due to these 2 leftover debug lines (most likely added because manifest validation with `-i` is now very slow, see [comment](https://github.com/DataDog/integrations-core/pull/6848/files#r447509426)), no manifest validation has run at all in the past 3 weeks.
As a result, there are 2 errors in master:
```console
$ ddev validate manifest   
Validating all manifest.json files...
cloud_foundry_api/manifest.json... FAILED
required non-null string: short_description
oom_kill/manifest.json... FAILED
integration_id contains invalid characters
147 valid files
2 invalid files
```
So, expecting the CI build on this PR to fail…
=> Run manifest validations again

docs/dev/check_references.md
=> remove note about spaces cos they dont exist

hazelcast/assets/dashboards/overview.json, hazelcast/manifest.json
=> Add Hazelcast dashboard

twemproxy/datadog_checks/twemproxy/twemproxy.py
- QA for https://github.com/DataDog/integrations-core/pull/6899
- if users have metadata disabled they should not receive warnings about unknown version
=> Don't collect version if metadata is not enabled

airflow/README.md, airflow/assets/configuration/spec.yaml, airflow/datadog_checks/airflow/data/conf.yaml.example
- Add clarifications to the Airflow integration docs
- Formatting
N/A
=> DOCS-983 Airflow integration

ignite/assets/dashboards/ignite_overview.json
Update ignite dashboard with new format.
=> Update with new dashboard format

http_check/datadog_checks/http_check/http_check.py, http_check/tests/test_unit.py
Increases the message size of the http_check
=> Raise http service check message limit

oom_kill/README.md
Fixes indents observed here https://docs.datadoghq.com/integrations/oom_kill/#configuration
=> [oom kill] add spaces to fix indentation

twemproxy/metadata.csv, twemproxy/tests/test_twemproxy.py
Remove duplicate descriptions and assert metadata in tests
=> Fix metric descriptions and assert metadata in tests

mysql/assets/recommended_monitors/mysql_replication_seconds_behind_master.json, mysql/assets/recommended_monitors/mysql_replication_slave.json, mysql/manifest.json
testing recommended monitors flow.
testing testing.
everything might break. I joke. everything is behind a feature flag.
=> Mysql recommended monitors

postgres/datadog_checks/postgres/config.py, postgres/datadog_checks/postgres/statements.py
=> add optional functions for pg_stat_* tables

redisdb/datadog_checks/redisdb/redisdb.py
- Remove the need for `if instance is None` conditionnal
- Rename `instance` to `instance_config` to mitigate risk of issues like: https://github.com/DataDog/integrations-core/pull/6680
=> Refactor instance argument

kafka_consumer/tox.ini
Kafka consumer tests were timing out.
=> Less e2e tests

flink/README.md
Update flink docs to clarify that flink doesn't send metrics to the agent.
=> Clarify flink instructions

kubernetes_state/metadata.csv
=> Renaming kubernetes state metrics job metrics in metadata.csv

mysql/datadog_checks/mysql/const.py, mysql/datadog_checks/mysql/mysql.py
Split off https://github.com/DataDog/integrations-core/pull/7169
The check has 200+ lines of constants, it's better to move them out to a separate file
=> Move constants to a separate file

mysql/datadog_checks/mysql/collection_utils.py, mysql/datadog_checks/mysql/mysql.py
Split of https://github.com/DataDog/integrations-core/pull/7169
Moves some collection utility method to a separate file so later they can be shared between the main `mysql.py` and the innodb split
=> Split collection utils

mysql/datadog_checks/mysql/mysql.py, mysql/datadog_checks/mysql/queries.py
Split of https://github.com/DataDog/integrations-core/pull/7169
=> Move query definitions to a separate file

aerospike/datadog_checks/aerospike/aerospike.py
Add debug log for get info calls
Helps investigation/support.
=> Add debug log for get info calls

aerospike/tox.ini
Use specific versions in integration/e2e tests
More predictable tests
=> Use specific versions in integration/e2e tests

spark/README.md, spark/assets/configuration/spec.yaml, spark/datadog_checks/spark/data/conf.yaml.example, spark/manifest.json
Updates `conf.yaml.example` and `README.md`
=> Add documentation for spark logs

hazelcast/tox.ini
Test specific versions
- ~~Fix CI. CI was failing with latest 4.0.2.~~ Fixed in https://github.com/hazelcast/management-center-docker/issues/36
- More stable CI
Created AI-993 for investing testing 3.X and 4.0.2.
=> Test specific versions for integration/e2e

mysql/tox.ini
Current tested MariaDB version EOLs in three months
=> Update tested mariadb version

kubernetes_state/datadog_checks/kubernetes_state/kubernetes_state.py
Use `allow` instead of `whitelist` to name variables
Inclusive terminology
=> Use inclusive terminology

harbor/tests/test_unit.py
=> Fix semantics of test assertion

linux_proc_extras/README.md
Add `Restart Agent` step to Linux Proc Extras
Jira request
N/A
=> DOCS-1107 Linux Proc Extras

datadog_checks_base/datadog_checks/base/utils/tailfile.py
Add open file debug log for tailer
Helps investigation/support.
=> Add open file debug log for tailer

mysql/datadog_checks/mysql/mysql.py, mysql/datadog_checks/mysql/statements.py
* some minor cleanup/simplification.
* protect from obfuscate sql exception crash
=> mysql switch to statsd counts

datadog_checks_base/datadog_checks/base/utils/db/statement_metrics.py, mysql/datadog_checks/mysql/statements.py, postgres/datadog_checks/postgres/config.py, postgres/datadog_checks/postgres/statements.py
* switch from `self.count` to `statsd.increment` to fix metrics
=> postgres check use shared StatementMetrics

ecs_fargate/datadog_checks/ecs_fargate/ecs_fargate.py, ecs_fargate/tests/test_unit.py
Support include/exclude logic based on container name and image in ECS Fargate
Feature was incomplete before
=> Support include/exclude containers in ECS Fargate

yarn/assets/configuration/spec.yaml, yarn/datadog_checks/yarn/data/conf.yaml.example, yarn/manifest.json, yarn/tests/compose/docker-compose.yaml, yarn/tests/conftest.py
Note the spec includes reference to logs integration, but the README update is covered in #7168 .
=> Add config specs for YARN integration

datadog_checks_dev/datadog_checks/dev/tooling/commands/config.py
Directly edit the config file instead of just exploring in File Manager.
Monday morning laziness 😄
=> Add "ddev config edit" subcommand

mysql/assets/configuration/spec.yaml, mysql/datadog_checks/mysql/config.py, mysql/datadog_checks/mysql/data/conf.yaml.example, mysql/datadog_checks/mysql/mysql.py, mysql/tests/test_connection.py
Refactor connection method, add tests. Improve configuration documentation and add more warnings.
Step prior to https://github.com/DataDog/integrations-core/pull/7216
=> Refactor connection, improve documentation

docs/developer/meta/ci.md
- adds developer docs for readme and codeowner validation
=> Add developer docs for readme and codeowner validation

snmp/datadog_checks/snmp/config.py, snmp/datadog_checks/snmp/discovery.py, snmp/datadog_checks/snmp/snmp.py
Extracted from https://github.com/DataDog/integrations-core/pull/7110
Refactor how OIDs are managed
Preparation for adding OID caching.
=> Refactor how OIDs are managed

oracle/README.md
Change prerequisite option order in the README.
We had some support cases where it was easier to use the Oracle Instant Client method than the JDBC one.
=> Change prerequisite option order

http_check/assets/configuration/spec.yaml, http_check/datadog_checks/http_check/data/conf.yaml.example, http_check/manifest.json
Extension of https://github.com/DataDog/integrations-core/pull/7213
=> Add config specs to http check

.gitlab/validate-logs-intgs/validate_log_intgs.py, azure_active_directory/manifest.json
=> Use log source attribute in validation

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/dashboards.py
Adding more validation steps to prevent users from "faking" that the dash is using the screen format.
Before that PR users were able to simple add a few fields manually to pass the tests.
```
ddev -e validate dashboards
Validating all Dashboard definition files...
k6...  FAILED
/Users/florian.veaux/dd/integrations-extras/k6/assets/dashboards/overview.json is using the new /dash payload format which isn't currently supported. Please use the format from the /screen or /time API endpoints instead.
3 valid files
1 invalid files
```
=> Validate dashboards are using the screen API

zk/assets/configuration/spec.yaml, zk/datadog_checks/zk/data/conf.yaml.example, zk/manifest.json, zk/setup.py
Adding config specs to the zookeeper integration
=> Use config specs

.gitignore
Tells git to ignore intellij project files.
=> git ignore intellij project files

datadog_checks_dev/datadog_checks/dev/tooling/testing.py
PR: https://github.com/DataDog/integrations-core/pull/7269
Broke the CI on master
=> Fix TOX_SKIP_ENV filtering

.azure-pipelines/nightly_py2.yml
https://github.com/DataDog/integrations-core/pull/7257 needs to be merged first: ✅
=> [CI] Add nightly run with py2 tests

mysql/assets/monitors/mysql_replication_seconds_behind_master.json, mysql/assets/monitors/mysql_replication_slave.json
Update monitor with integration tag
CI for validation PR https://github.com/DataDog/integrations-core/pull/7280 fails without these fixes
=> Update monitor tag with integration

mongo/assets/monitors/high_connections.json, mongo/manifest.json
Adds a default monitor for MongoDB integration
=> Add monitor for MongoDB integration

kafka/metadata.csv, kafka/tests/common.py, kafka/tests/test_check.py
Adds missing metrics to metadata csv
Corrects submission type gauge -> rate of some that were incorrectly set
=> Add missing metrics to metadata.csv

cloud_foundry_api/datadog_checks/cloud_foundry_api/cloud_foundry_api.py, cloud_foundry_api/tests/conftest.py, cloud_foundry_api/tests/fixtures/events_v3_p0.json, cloud_foundry_api/tests/test_cloud_foundry_api.py
Stop sending events multiple times to Datadog.
=> Stop sending events multiple times

sqlserver/README.md
Add containerized docs
https://github.com/DataDog/integrations-core/issues/6591#issuecomment-666948000
=> Add containerized docs

scylla/assets/monitors/instance_down.json
=> Add integration tag to scylla monitor

activemq_xml/datadog_checks/activemq_xml/data/conf.yaml.example, airflow/datadog_checks/airflow/data/conf.yaml.example, ambari/datadog_checks/ambari/data/conf.yaml.example, apache/datadog_checks/apache/data/conf.yaml.example, consul/datadog_checks/consul/data/conf.yaml.example, couch/datadog_checks/couch/data/conf.yaml.example, datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/http.yaml, datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/openmetrics.yaml, druid/datadog_checks/druid/data/conf.yaml.example, elastic/datadog_checks/elastic/data/conf.yaml.example, envoy/datadog_checks/envoy/data/conf.yaml.example, fluentd/datadog_checks/fluentd/data/conf.yaml.example, gitlab/datadog_checks/gitlab/data/conf.yaml.example, hdfs_datanode/datadog_checks/hdfs_datanode/data/conf.yaml.example, hdfs_namenode/datadog_checks/hdfs_namenode/data/conf.yaml.example, http_check/datadog_checks/http_check/data/conf.yaml.example, istio/datadog_checks/istio/data/conf.yaml.example, kong/datadog_checks/kong/data/conf.yaml.example, kube_apiserver_metrics/datadog_checks/kube_apiserver_metrics/data/conf.yaml.example, lighttpd/datadog_checks/lighttpd/data/conf.yaml.example, marathon/datadog_checks/marathon/data/conf.yaml.example, mesos_slave/datadog_checks/mesos_slave/data/conf.yaml.example, nginx/datadog_checks/nginx/data/conf.yaml.example, nginx_ingress_controller/datadog_checks/nginx_ingress_controller/data/conf.yaml.example, openmetrics/datadog_checks/openmetrics/data/conf.yaml.example, riak/datadog_checks/riak/data/conf.yaml.example, spark/datadog_checks/spark/data/conf.yaml.example, twistlock/datadog_checks/twistlock/data/conf.yaml.example, vault/datadog_checks/vault/data/conf.yaml.example, yarn/datadog_checks/yarn/data/conf.yaml.example
Addresses feedback from https://github.com/DataDog/integrations-core/pull/7291
=> Apply config feedback

datadog_checks_base/datadog_checks/base/checks/base.py, disk/datadog_checks/disk/disk.py, mongo/datadog_checks/mongo/mongo.py, rabbitmq/datadog_checks/rabbitmq/rabbitmq.py
Update target version for too optimistic FIXMEs.
Previous target versions have already happened.
=> Update target version for too optimistic FIXMEs

.azure-pipelines/templates/run-validations.yml, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py
Add hide warnings option to validate metadata
=> Add show warnings option to validate metadata

mysql/datadog_checks/mysql/execution_plans.py
=> [Dev] Use MySQL `explain_statement` function when available to collect execution plans

amazon_eks/README.md
Updating our documentation for the AWS Outposts Service Ready Program
=> Adding support for Amazon EKS on AWS Outposts

yarn/README.md
Fix the markdown rendering in yarn's readme
=> Fix markdown in readme

datadog_checks_dev/datadog_checks/dev/tooling/trello.py
Fix labels for `Tools and Libraries` team
=> Fix intg-tools-libs entry in trello.py

snmp/datadog_checks/snmp/data/profiles/apc_ups.yaml, snmp/tests/test_e2e.py, snmp/tests/test_profiles.py
Fix `apc_ups` snmp profile
QA #7072
=> Fix apc ups profile

tox.ini
- https://pip.pypa.io/en/stable/user_guide/#resolver-changes-2020
- https://github.com/DataDog/integrations-core/runs/977044150?check_suite_focus=true
- https://github.com/pawamoy/mkdocstrings/blob/d1b9401afecb20d3123eec7334605cb15bf9d877/pyproject.toml#L25
=> Fix dependency resolution for docs

network/README.md
adds a note to the network integration about adding the conntrack binary in the Agent image
=> add line about conntrack binary

docs/developer/tutorials/snmp/how-to.md
Add docs about:
- Making walk queries (included the `-ObentU` options)
- Using walks as simulation data for local debugging of live devices.
Rendering preview:
=> Add docs on working with walks

snmp/README.md
=> correct typo

coredns/metadata.csv
Some metrics were not in the `metadata.csv` file.
QA: #6973
=> Update coredns metadata.csv

.github/workflows/changelog-label-check.yml, .github/workflows/labeler.yml
Trigger check label action after the labeler.
=> Trigger action after labeler

istio/manifest.json
=> Fix short name

envoy/README.md
Fix an invalid syntax in envoy/README.md.
Cause I found an invalid configuration syntax :)
None
=> Fix an invalid syntax in envoy/README.md

docs/developer/architecture/win32_event_log.md, mkdocs.yml, win32_event_log/datadog_checks/win32_event_log/check.py, win32_event_log/datadog_checks/win32_event_log/constants.py, win32_event_log/datadog_checks/win32_event_log/data/conf.yaml.example, win32_event_log/datadog_checks/win32_event_log/filters.py, win32_event_log/datadog_checks/win32_event_log/legacy/win32_event_log.py, win32_event_log/datadog_checks/win32_event_log/utils.py, win32_event_log/tests/common.py, win32_event_log/tests/conftest.py, win32_event_log/tests/legacy/test_win32_integration.py, win32_event_log/tests/test_check.py, win32_event_log/tests/test_config.py, win32_event_log/tests/test_filters.py, win32_event_log/tox.ini
https://github.com/DataDog/integrations-core/blob/ofek/event/docs/developer/architecture/win32_event_log.md
1. Customer requests regarding performance
2. Remove all uses of WMI
Since this is the final check using WMI, once the legacy implementation is removed we'll move all WMI code out of the base package and directly into `wmi_check` 😄
=> Introduce new, more performant implementation

scylla/assets/dashboards/overview.json
=> Fix dashboard logo

docs/developer/tutorials/jmx/tools.md
List jmx beans using jmxterm with extra jars.
Useful command for debugging some integrations like jboss
=> List jmx beans using jmxterm with extra jars

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/status.py, datadog_checks_dev/datadog_checks/dev/tooling/trello.py
=> Add security team

datadog_checks_tests_helper/datadog_test_libs/__init__.py, datadog_checks_tests_helper/datadog_test_libs/mock_dns.py, datadog_checks_tests_helper/datadog_test_libs/utils/mock_dns.py, http_check/tests/conftest.py, http_check/tests/test_http_integration.py, http_check/tests/test_integration_e2e.py, http_check/tox.ini, kafka_consumer/tests/conftest.py, kafka_consumer/tests/test_kafka_consumer.py, kafka_consumer/tox.ini, mapreduce/tests/conftest.py, mapreduce/tox.ini, tls/tests/conftest.py, tls/tests/test_remote.py, tls/tox.ini
=> Add a test helper to mock dns on local and e2e

mysql/datadog_checks/mysql/version_utils.py, mysql/tests/test_mysql.py
Parse version even if the returned string is a bytes string.
Support case
=> Parse byte string versions

vsphere/assets/dashboards/vsphere_overview.json
=> Update vsphere dashboard

gunicorn/README.md
h/t @DanyNarcisse the note about not using both methods is no longer true, removing
=> remove innacurate note

linkerd/tests/terraform/main.tf
- https://github.com/DataDog/integrations-core/pull/5167
- https://github.com/DataDog/integrations-core/pull/5176
=> Remove GKE cluster version limitation

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/dashboards.py
Change the warning we emit when we detect a dashboard is using the old /screen or /time payload to an error and fail the validation
All integration dashboards should now be migrated to the new payload, so this should only impact any future dashboards that are being added.
=> Change old_payload warning to failure

spark/assets/configuration/spec.yaml, spark/datadog_checks/spark/data/conf.yaml.example, spark/tests/test_spark.py
=> Fix order of options in default config

docs/developer/architecture/vsphere.md
=> Add vSphere architecture documentation

vsphere/README.md
=> Update vsphere docs

sidekiq/README.md
Fix missing space in yaml example
Hotjar feedback
Docs only change
=> Fix yaml space

sqlserver/README.md, sqlserver/tests/README.md
- Clean-up wording / formatting
- Move testing info out of main README
- Add note about dynamic ports
- Jira request
N/A
=> DOCS-1177 SQL Server docs

rabbitmq/datadog_checks/rabbitmq/rabbitmq.py, rabbitmq/tests/test_unit.py
=> Ensure basic auth encoding defaults to UTF-8

elastic/README.md
Adds more information about validating with AWS
=> [docs update] adding a point about aws credentials

datadog_checks_base/datadog_checks/base/utils/tailfile.py
Requirement for https://github.com/DataDog/integrations-core/pull/7447/
=> Add close method to tailer

spark/datadog_checks/spark/spark.py, spark/tests/test_spark.py
=> Add Stage and Job ID tags

apache/README.md
Updating this to link to the the docs page
More clarity on how to get started with the Agent.
=> [documentation] link update

gitlab_runner/README.md, gitlab_runner/assets/configuration/spec.yaml, gitlab_runner/datadog_checks/gitlab_runner/data/conf.yaml.example, gitlab_runner/manifest.json, gitlab_runner/tests/common.py, gitlab_runner/tests/compose/support/custom_config.toml, gitlab_runner/tests/compose/support/wait_for_master.sh, gitlab_runner/tests/conftest.py, gitlab_runner/tox.ini
Add `gitlab_runner` log support
=> Add log support

mapreduce/README.md
Includes standard logs section in `mapreduce` README file.
=> Update mapreduce README with logs section

docs/developer/process/agent-release/pre-release.md
Add before freeze update style deps
Related PR: https://github.com/DataDog/integrations-core/pull/7485
Since we now pin style deps, we need a process to update them.
=> Add before freeze update style deps

datadog_checks_dev/datadog_checks/dev/plugin/tox.py
Pin style deps to latest versions if not pinned yet.
Make builds more reliable/predictable.
Sandbox PR to trigger all builds: https://github.com/DataDog/integrations-core/pull/7486
=> Pin style deps

sqlserver/assets/configuration/spec.yaml, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example, sqlserver/datadog_checks/sqlserver/sqlserver.py, sqlserver/tests/test_sqlserver.py, sqlserver/tests/test_unit.py
Removes legacy code that supported multiple simultaneous instances in a single check.  This streamlines some of the logic and makes the code a bit easier to read.
Also addresses an E2E issue that appeared during local testing.
Preparation for adding additional metrics.
=> Update sqlserver to Agent 6 single instance logic

cisco_aci/assets/configuration/spec.yaml
Are there any other integrations that need this?
=> Simplify config spec

docs/developer/tutorials/snmp/introduction.md
Add link to https://www.youtube.com/playlist?list=PL4j_fCKQ7Bso1wGplcaF2pcDGeLVCuKHU
Great series of videos found by @AlexandreYang, could be useful to anyone working with our SNMP integration.
=> Add link to SNMP tutorial videos

.azure-pipelines/templates/run-validations.yml
Adds EULA validation to marketplace repo choice CI
Also adds the ddev validate package to validate the setup.py package name. 
The latest release of ddev includes these new validations, so run them in CI
=> Add eula validation to azp

etcd/manifest.json, gitlab_runner/manifest.json, mapreduce/manifest.json
Add missing log sources
https://github.com/DataDog/logs-backend/tree/prod/service/src/main/resources/integrations-tests
=> Add log sources for etcd, gitlab-runner and mapreduce

.gitlab/validate-logs-intgs/validate_log_intgs.py
And also sort existing exclusions
=> Exclude linkerd from log pipeline validation

haproxy/datadog_checks/haproxy/haproxy.py, haproxy/tests/test_haproxy.py, haproxy/tests/test_unit.py, haproxy/tox.ini
Solves https://github.com/DataDog/integrations-core/issues/7492
Alternative to https://github.com/DataDog/integrations-core/pull/7521
=> Add regex tags in status metrics

sqlserver/datadog_checks/sqlserver/connection.py, sqlserver/datadog_checks/sqlserver/sqlserver.py, sqlserver/tests/common.py, sqlserver/tests/conftest.py, sqlserver/tests/test_sqlserver.py, sqlserver/tests/test_unit.py
Refactors out the connection logic to a separate module and class to better separate concerns.  Also adds some additional tests for custom metrics and stored procedure guards.
Code cleanup to make the check more maintainable and easier to expand for new metric types.
Refactoring of the Metric classes will be covered in a separate PR.
=> Refactor sqlserver connection class and expand test coverage

nginx/metadata.csv
=> Remove illegal quoting in nginx metadata

datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/init_config/db.yaml, datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/db.yaml
Integrations that use the database utilities share common custom query configuration options. This PR adds a template for them.
As more database integrations are being converted or implemented with the database utility class, the options are being repeated.
=> Add custom query database template

datadog_checks_base/datadog_checks/base/log.py
Add doc for get_check_logger
Better doc.
=> Add doc for get_check_logger

vsphere/assets/configuration/spec.yaml, vsphere/datadog_checks/vsphere/data/conf.yaml.example, vsphere/manifest.json
Write a config spec for vsphere
Updating to use spec.yaml template instead of manual entry.
=> Add config spec for vsphere

varnish/assets/configuration/spec.yaml, varnish/datadog_checks/varnish/data/conf.yaml.example, varnish/manifest.json, varnish/setup.py
Adding config spec for varnish
Updating to use `spec.yaml` template instead of manual entry.
=> Add config spec for varnish

datadog_checks_dev/datadog_checks/dev/tooling/configuration/template.py, datadog_checks_dev/tests/tooling/configuration/test_template.py
https://github.com/DataDog/integrations-core/pull/7444#discussion_r480999851
=> [config specs] Support overrides for mappings when references start with a name

sqlserver/datadog_checks/sqlserver/metrics.py, sqlserver/datadog_checks/sqlserver/sqlserver.py
Extracts the metrics classes into a separate module and cleans up the interface for creating and extracting metrics.
Make it easier to expand support for new metrics types and tables.
=> SQL Server metrics refactor

vertica/assets/configuration/spec.yaml, vertica/datadog_checks/vertica/data/conf.yaml.example, vertica/manifest.json, vertica/setup.py
Adding spec.yaml for vertica.
Updating to use spec.yaml template instead of manual entry.
n/a
=> Add config spec for Vertica

haproxy/datadog_checks/haproxy/haproxy.py, haproxy/datadog_checks/haproxy/version_utils.py
Extract version related code to another file, also do not collect metadata if disabled
=> Extract version utils

README.md
=> Add isort badge

nginx/assets/dashboards/plus_overview.json
Updating NGINX Plus' dashboard to be more blog-like.
Link to this UI can be found here: https://dd.datad0g.com/screen/integration/30235/nginx-plus---overview?from_ts=1599671461966&live=true&to_ts=1599675061966
To keep formatting up-to-date with current standards.
_(Added by @florimondmanca) Previous dashboard, for comparison_:
=> Update NGINX Plus' dashboard into blog

.gitlab/validate-logs-intgs/validate_log_intgs.py
=> Fixing log validation

openshift/README.md
Quick update to the anchor to actually match the title on the page
=> Update anchor to match title

lighttpd/tests/docker/noauth/docker-compose.yaml
Pin lighttpd version 1.4.54 for noauth test
=> Fix lighttpd noauth image

vsphere/datadog_checks/vsphere/api.py, vsphere/datadog_checks/vsphere/vsphere.py
=> Add debug logs to help support

etcd/assets/dashboards/etcd_overview.json
=> Update dashboard title and description

kubernetes/assets/monitors/monitor_pods_restarting.json
Address error when parsing the monitor.
=> Fix kubernetes recommended monitor

mongo/datadog_checks/mongo/mongo.py
Preliminary work for better tests: https://github.com/DataDog/integrations-core/pull/7604/
=> Submit collection metrics even if value is zero

ecs_fargate/README.md
Adds a CloudFormation template example to the existing AWS Fargate docs
Jira request
=> CloudFormation example for AWS Fargate

oom_kill/metadata.csv
=> Fix typo in OOM_kill check metadata.csv

sidekiq/assets/dashboards/overview.json
Update Sidekiq dashboard formatting and logs widget.
Screenshot:
Staging link: 
https://dd.datad0g.com/screen/integration/30273/sidekiq-overview?from_ts=1600457360766&live=true&to_ts=1600460960766
=> Update Sidekiq dashboard

redisdb/assets/dashboards/overview.json, redisdb/manifest.json
Add redis Dashboard
Since integrations-core supports dashboard, we are adding all dashboards here
=> Add redis dashboard

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py
Check that the provided `integration` name in metadata.csv files match the normalized version of the display name, including that its lowercase. 
The system that reads these expects the name to be lowercased. 
I ran this against the integrations in this repo + extras, the only integration impacted is Pihole - https://github.com/DataDog/integrations-extras/blob/master/pihole/metadata.csv
=> Check case of integration header in metadata.csv files for metadata validation

marklogic/README.md
=> Fix marklogic readme

mongo/tests/test_unit.py
Adds test for https://github.com/DataDog/integrations-core/pull/7393
=> Add unit test for collection metric names depletion

sqlserver/metadata.csv
Adds missing metrics in metadata.csv introduced in https://github.com/DataDog/integrations-core/pull/5840/s
=> Add metric metadata for scheduler and task metrics

oom_kill/README.md
Update doc for OOM Kill check to include a link to an example configuration file
Clarity/better user experience
=> oom kill docs: add link to example conf

nginx/manifest.json
=> Add metric to check for nginx plus

amazon_eks/manifest.json
Adds windows.
We've really expanded our windows support! Adding this with several other places in the docs.
=> [documentation] adding windows since it is now supported

mkdocs.yml
https://squidfunk.github.io/mkdocs-material/upgrading/#upgrading-from-5x-to-6x
=> Fix docs config to handle theme update

marklogic/manifest.json
Add marklogic process signature
=> Add process signature

tls/datadog_checks/tls/tls.py
Adding debug logging to TLS check to assist with troubleshooting.
See this [T2 triage support ticket](https://datadoghq.atlassian.net/browse/AGENT-5032?focusedCommentId=275762)
=> Adding debug logging to tls check

gunicorn/README.md
This update reflects what our current GUnicorn yaml file shows: https://github.com/DataDog/integrations-core/blob/master/gunicorn/datadog_checks/gunicorn/data/conf.yaml.example
=> Update Gunicorn yaml example based on current one

oracle/README.md
- adds tabs for user creation to differentiate single / multitenant setup
- adds a custom query example based on customer feedback
Jira requests
=> Oracle tabbing and examples

fluentd/datadog_checks/fluentd/fluentd.py, fluentd/metadata.csv, fluentd/tests/common.py, fluentd/tests/test_integration.py, fluentd/tests/test_integration_and_e2e.py, fluentd/tests/util.py
This PR introduces more metrics.
Since 1.6, there were more metrics added. https://www.fluentd.org/blog/fluentd-v1.6.0-has-been-released
=> Add support for additional metrics

spark/README.md
Removed the logs section from the containerized tab
Jira request
=> Spark Check tabbing fix

cri/assets/dashboards/overview.json, cri/manifest.json, crio/assets/dashboards/overview.json, crio/manifest.json, hyperv/assets/dashboards/overview.json, hyperv/manifest.json, ibm_mq/assets/dashboards/overview.json, ibm_mq/manifest.json, ibm_was/assets/dashboards/overview.json, ibm_was/manifest.json, kube_controller_manager/assets/dashboards/overview.json, kube_controller_manager/manifest.json, kube_scheduler/assets/dashboards/overview.json, kube_scheduler/manifest.json, nginx_ingress_controller/assets/dashboards/overview.json, nginx_ingress_controller/manifest.json, twistlock/assets/dashboards/overview.json, twistlock/manifest.json
Migrate dashboards to the new payload format and migrate here
=> Migrate dashboards to new payload format

mongo/README.md
Small typo in the containerized configuration for mongo. `%%hosts%%` is not a valid template variable.
=> Fix mongo readme typo

docs/developer/ddev/test.md, supervisord/README.md, supervisord/assets/configuration/spec.yaml, supervisord/datadog_checks/supervisord/data/conf.yaml.example, supervisord/manifest.json, supervisord/setup.py, supervisord/tests/compose/supervisord.yaml, supervisord/tests/conftest.py
Add supervisord logs
- [web-ui#20394](https://github.com/DataDog/web-ui/pull/20394)
- [logs-backend#12606](https://github.com/DataDog/logs-backend/pull/12606)
- [JIRA#AI-738](https://datadoghq.atlassian.net/browse/AI-738)
Add support for supervisord logs
=> Add supervisord logs

mysql/assets/configuration/spec.yaml, mysql/datadog_checks/mysql/data/conf.yaml.example
=> Fix config spec default values

active_directory/assets/dashboards/active_directory.json, active_directory/manifest.json
=> Add active directory dashboard

.azure-pipelines/templates/run-validations.yml
Adding http validator to CI.
Refer to https://github.com/DataDog/integrations-core/pull/7676.
=> Add http validator to CI

docs/developer/.scripts/33_render_status.py
Exclude integrations where we cannot build logs integration
=> exclude when not possible

docs/developer/faq/faq.md
Adding an example of bug in test code fixed thanks to test coverage.
Practical example of why it is a good practice to include test code in test coverage
=> Add example of why we test cover test code

coredns/assets/dashboards/coredns.json, coredns/manifest.json
=> Add coredns dashboard

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, kafka_consumer/requirements.in
https://github.com/dpkp/kafka-python/blob/master/CHANGES.md#202-sep-29-2020
=> Update kafka-python to 2.0.2

openshift/manifest.json, openshift/metadata.csv
Metric listed has changed for newer version
=> Update metric_to_check for newer Openshift version

datadog_checks_dev/datadog_checks/dev/tooling/github.py
Check the git token scope has `org` when getting team members.
Previous error message was not helpful
```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/orgs/DataDog/teams/agent-apm/members
```
=> Check the git token scope when calling `get_team_members`

marklogic/manifest.json, snowflake/manifest.json
Make `snowflake` and `marklogic` integrations public when 7.23.0 is released
=> Make 7.23 integrations public

gitlab_runner/README.md
Noticed some typos for logs collection section in gitlab runner
=> Fix typos in readme

redisdb/assets/dashboards/overview.json
Redis blog-like dashboard
[JIRA#AI-193](https://datadoghq.atlassian.net/browse/AI-193)
=> Update redis dashboard to be blog-like

datadog_checks_dev/datadog_checks/dev/_env.py, datadog_checks_dev/datadog_checks/dev/plugin/pytest.py, proxysql/tests/test_proxysql.py
=> Make inventories metadata testable in e2e

elastic/README.md
Lets customers know that if they are using a cluster is not running the agent, they should set integration-level tags for tagging consistency.
Jira request
=> Elasticsearch host setup note

statsd/README.md, statsd/assets/configuration/spec.yaml, statsd/datadog_checks/statsd/data/conf.yaml.example, statsd/tests/compose/Dockerfile, statsd/tests/compose/statsd.yaml, statsd/tests/test_statsd.py
=> Add statsd logs

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, kafka_consumer/manifest.json, kafka_consumer/requirements.in
=> Support Windows

airflow/README.md
Add note for metrics not reported when using Airflow  KubernetesExecutor
https://github.com/apache/airflow/issues/11514
=> Add note for metrics not reported when using Airflow  KubernetesExecutor

snowflake/datadog_checks/snowflake/queries.py, snowflake/metadata.csv, snowflake/tests/test_snowflake.py
=> Add bytes_spilled metrics

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/fixed_cards_mover.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/testable.py, datadog_checks_dev/datadog_checks/dev/tooling/trello.py
For each new PR, this code tries to move a card from the column `HAVE BUGS - FIXME` or `FIXED - Ready to Rebuild` instead of creating a new Trello card. This PR looks for a Github Pull request in the Trello card either as a widget or inside the comments
Avoid card duplications.
=> Add fixed_cards_mover.py

snowflake/CHANGELOG.md
Update changelog with manual releases
=> Update Snowflake Changelog

snowflake/setup.py
Bump Snowflake base requirement
=> Properly pin base package version for new QueryManager feature

openshift/README.md
Updates an outdated link in the openshift docs
=> [documentation] updating broken link in openshift

istio/README.md
Istio 1.6+ may require additional steps to enable prometheus mesh metrics
=> Add note about v1 telemetry

datadog_checks_dev/datadog_checks/dev/tooling/cli.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py, datadog_checks_dev/datadog_checks/dev/tooling/testing.py
Add more debug lines to ddev.
Abort if there are tox errors
=> Detect and abort if there are tox errors

datadog_checks_base/datadog_checks/base/utils/agent/utils.py, datadog_checks_base/tests/test_utils_agent_utils.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py
Rename, keeping compatibility with the old names.
Needs corresponding changes in datadog-agent: https://github.com/DataDog/datadog-agent/pull/6413
Changelog will be in the agent side.
=> Tracemalloc: Rename white/blacklist to include/exclude

datadog_checks_base/datadog_checks/base/utils/db/sql.py, datadog_checks_base/tests/test_db_sql.py
**NOTE:** This PR is not to master, it is to merge into https://github.com/DataDog/integrations-core/pull/7837, which has grown quite large with comments. This PR is to centralize discussion.
Addresses PR feedback in https://github.com/DataDog/integrations-core/pull/7851 and https://github.com/DataDog/integrations-core/pull/7852 to centralize the commas "hack."
=> Break out the normalize query function into datadog_checks_base

.azure-pipelines/templates/install-deps.yml, .azure-pipelines/templates/test-all-checks.yml, .azure-pipelines/templates/test-all.yml, .azure-pipelines/templates/test-single-windows.yml
Installs Visual C++ on windows so we can compile Python2 dependencies.
=> Install vcpython27 for ddbase on windows

ecs_fargate/README.md
=> add note to reference AWS secrets for apikey

.github/CODEOWNERS
Add infrastructure integration as owner of snmp, vsphere and openstack integrations.
=> Update CODEWONERS file

azure_iot_edge/README.md, azure_iot_edge/manifest.json
Add documentation on log collection for `azure_iot_edge`.
Let users know how to configure log collection for this integration.
- Tests were already setup to allow collecting logs during development.
- Log parser is WIP (doesn't block this PR): https://github.com/DataDog/logs-backend/pull/13498
=> Add logs support

.azure-pipelines/scripts/datadog_checks_base/windows/55_vcpython27.bat, .azure-pipelines/templates/install-deps.yml, .azure-pipelines/templates/test-all-checks.yml, .azure-pipelines/templates/test-all.yml, .azure-pipelines/templates/test-single-windows.yml, datadog_checks_base/tox.ini
doesn't work on PRs atm
doc: https://datadoghq.dev/integrations-core/meta/ci/#scripts
=> Fix conditional installation of vcpython27

cisco_aci/requirements.in, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/requirements.in, http_check/requirements.in, mysql/requirements.in, tls/requirements.in
=> Upgrade `cryptography` dependency

docs/developer/base/basics.md
Adding content for the Basics page on Agent Integrations docs:
https://datadoghq.dev/integrations-core/base/basics/
The current Basics page is empty.
=> Add Basics page for Agent Integrations docs

datadog_checks_dev/datadog_checks/dev/tooling/utils.py, docs/developer/.scripts/33_render_status.py
=> Add progress for agent 8 check signature

docs/developer/meta/ci.md
To match https://github.com/DataDog/integrations-core/commit/982cf3bf27a97b7d009311b527b4406cd6c79287
=> Update recommended dashboard endpoint

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/http.py
Adds the requests options method for validation.
Support case
=> add options method for validation

snowflake/README.md
=> Fix link in div

datadog_checks_base/datadog_checks/base/checks/openmetrics/mixins.py
https://github.com/DataDog/datadog-agent/pull/6663
There are common scenarios when the first value is important:
1. Agent restart scenario - when Datadog Agent container restarts, the next value of metric+tags seen by the Agent will be considered as the first one.
2. “Cold phases” - where the combination of metric value + tags is only reported once after many days
3. Application restarts - after an application container restarts, any counters will be restarted to 0 and will not be reported by the Datadog Agent.
Will be tested during QA next week
=> Sample the first value of monotonic counts for Open Metrics checks

snowflake/README.md, snowflake/assets/configuration/spec.yaml, snowflake/datadog_checks/snowflake/data/conf.yaml.example
Markdown doesn't work in html `<div>` tags. 
Updating code tick format and adding note about latency.
Feedback
=> Make improvements to documentation

http_check/datadog_checks/http_check/http_check.py, http_check/setup.py
Adds support for the OPTIONS method to the http_check
Support case
=> Add support for OPTIONS method

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/testable.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/tester_selector/tester_selector.py
The Agent repo was hard coded recently
=> Fix Trello release script

couch/datadog_checks/couch/couch.py
Fix message duplication when the version is unsupported
Ex `Unknown version: Unknown version: 0.2.1`
QA #7570
=> Fix exception message

snowflake/assets/dashboards/snowflake.json, snowflake/manifest.json
OOTB dashboard for integration
=> Add Snowflake dashboard

snowflake/assets/dashboards/snowflake.json
Remove blue conditional graph background colors
=> Remove conditional formatting for query graphs

mysql/assets/configuration/spec.yaml, mysql/datadog_checks/mysql/data/conf.yaml.example
=> Fix configuration typo

azure_iot_edge/README.md
=> Fix log section in readme

snowflake/manifest.json
=> Make new integration public

marklogic/assets/configuration/spec.yaml, marklogic/datadog_checks/marklogic/api.py, marklogic/datadog_checks/marklogic/data/conf.yaml.example
Remove the trailing `/` in the configuration example, and change the code logic to only have one `/` in the base url
=> Fix url configuration example

vault/README.md
Adds a note to the Vault docs to let customers know v 1.1.0 is required to collect metrics with the `sys/metrics` endpoint.
Jira request
=> Version requirements for Vault docs

snowflake/assets/configuration/spec.yaml, snowflake/datadog_checks/snowflake/data/conf.yaml.example
Enable so that default 1 hour min collection interval is collected as documented
=> Enable min collection interval

mongo/metadata.csv
Fixing units in the metadata.csv
=> Update metadata.csv for mongo

azure_iot_edge/tests/test_e2e.py
QA
The test will break when the issue will be resolve in Edge Hub
E2E tests for `azure_iot_edge` do not run on CI yet
=> Add bad_url e2e test

datadog_checks_dev/datadog_checks/dev/tooling/configuration/spec.py, datadog_checks_dev/tests/tooling/configuration/test_load.py
https://github.com/DataDog/integrations-core/pull/7938
=> Allow mechanism for handling duplicate option names for config specs

azure_iot_edge/README.md
Fix formatting issues in the Azure IoT Edge README
See current state on https://docs.datadoghq.com/integrations/azure_iot_edge/
=> Fix README formatting

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/http.py
Adding fix for `ddev validate http` logic from https://github.com/DataDog/integrations-core/pull/7676
Will need to merge https://github.com/DataDog/integrations-core/pull/7938 first for CI to pass.
=> Fix http validator

postgres/assets/configuration/spec.yaml, postgres/datadog_checks/postgres/data/conf.yaml.example
**Low-priority:** this was a small product request to update the language on docs for deep_database_monitoring features.
Postgres equivalent here: https://github.com/DataDog/integrations-core/pull/7948
=> Change deep_database_monitoring Postgres language from BETA to ALPHA

mysql/assets/configuration/spec.yaml, mysql/datadog_checks/mysql/data/conf.yaml.example
**Low-priority:** this was a small product request to update the language on docs for deep_database_monitoring features.
Postgres equivalent here: https://github.com/DataDog/integrations-core/pull/7947
=> Change deep_database_monitoring MySQL language from BETA to ALPHA

aerospike/manifest.json, requirements-agent-release.txt
Address issues in https://github.com/DataDog/integrations-core/pull/7957
=> Fix release platforms

azure_iot_edge/assets/configuration/spec.yaml, azure_iot_edge/datadog_checks/azure_iot_edge/data/conf.yaml.example, cilium/assets/configuration/spec.yaml, cilium/datadog_checks/cilium/data/conf.yaml.example
imports openmetrics template to Prometheus integrations
Address errors caught in validation: https://github.com/DataDog/integrations-core/pull/7999/s
=> Fix openmetrics integrations config specs

exchange_server/datadog_checks/exchange_server/data/conf.yaml.example
Blocked on https://github.com/DataDog/integrations-core/pull/8015/s
=> Fix line wrap in conf.yaml

datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/tls.yaml
See: https://github.com/DataDog/integrations-core/pull/7812 and https://github.com/DataDog/integrations-core/pull/8013
=> Add config template for TLS helper

docs/developer/tutorials/snmp/tools.md, mkdocs.yml
Add snmp tcpdump doc
Can help troubleshooting
=> Add snmp tcpdump doc

marklogic/assets/dashboards/overview.json, marklogic/manifest.json
=> Add MarkLogic dashboard

ibm_mq/metadata.csv
Per customer request, updating the old IBM MQ descriptions to be more descriptive and include the parameters that the metric references.
Used this document to get most of the information: http://ftpmirror.your.org/pub/misc/ftp.software.ibm.com/software/mqseries/pdf/csqzai02.pdf.
=> Update IBM MQ descriptions

mysql/datadog_checks/mysql/mysql.py
=> Add debug log line for replication status

vertica/assets/configuration/spec.yaml, vertica/datadog_checks/vertica/data/conf.yaml.example, vertica/datadog_checks/vertica/vertica.py, vertica/tests/test_vertica.py
Adds option to limit metric collection for predefined tables.
https://datadoghq.atlassian.net/browse/AI-1189
N/A
=> Add option to limit metric collection

varnish/datadog_checks/varnish/varnish.py
There is a customer case where this code is throwing a Key exception, this change makes it skip the metric and log it so we can get more information about what's going on.
=> Skip metrics instead of throwing exceptions

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/readmes.py
Adds a section to the `ddev validate readmes` that checks if "partner" integrations contain the required "support" h2 header
This is required in the backend so, adding validations here to fail closer to the source of truth.
This will be skipped for any non partner integrations
=> Validate partner integration readmes contain an h2 support section

spark/assets/configuration/spec.yaml, spark/datadog_checks/spark/data/conf.yaml.example, spark/datadog_checks/spark/spark.py, spark/metadata.csv, spark/tests/test_spark.py
=> Add more granular metrics

aerospike/README.md, aerospike/assets/configuration/spec.yaml, aerospike/datadog_checks/aerospike/data/conf.yaml.example, aerospike/manifest.json
=> Add log pipeline

varnish/metadata.csv
=> Fix metadata

airflow/tests/compose/docker-compose.yaml
CI is failing `docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings`
=> Fix test environment

active_directory/datadog_checks/active_directory/data/conf.yaml.example, datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/pdh.yaml, hyperv/datadog_checks/hyperv/data/conf.yaml.example, pdh_check/datadog_checks/pdh_check/data/conf.yaml.example
=> Fix pdh configuration spec

docs/developer/.scripts/33_render_status.py
Updating the list of log integrations we are not building
=> Update the not possible list for log integrations

tomcat/assets/dashboards/metrics.json, tomcat/assets/dashboards/overview.json, tomcat/manifest.json
Add blog-like Tomcat dashboard.
https://datadoghq.atlassian.net/browse/AI-1213
=> Add Tomcat blog dashboard

azure_iot_edge/manifest.json
Mark `azure_iot_edge` integration as public
Agent 7.24.0 is out, so the docs for this integration can be indexed and published
=> Mark azure_iot_edge as public

zk/README.md
Adding a snippet about requirements for SSL support.
=> Update ZooKeeper README about SSL support version requirement.

iis/assets/dashboards/iis_dashboard.json, iis/assets/dashboards/iis_overview.json, iis/manifest.json
Migrate both preset IIS dashboards to integrations-core
Easier to update dashboards in the future: e.g https://github.com/DataDog/integrations-core/pull/8066
=> Migrate dashboard

elastic/assets/configuration/spec.yaml, elastic/datadog_checks/elastic/data/conf.yaml.example, elastic/datadog_checks/elastic/elastic.py, elastic/datadog_checks/elastic/metrics.py, elastic/tests/common.py, elastic/tests/test_elastic.py, elastic/tests/test_metrics.py
jvm.gc.collectors.young/old metrics are total, constantly increasing values. 
This PR also refactors the unit tests
Request
=> Submit jvm.gc.collectors metrics as rate

snmp/tests/test_check.py
`test_timeout` in `test_check` was randomly failing for `Python 2.7`. After investigation, we found it was due to the use of `dict` to store oids from tables: until `Python 3.6` `dict` doesn't preserve elements insertion order. Because of this, when converting the `dict` into a list of oids, the order of the oids was random on `Python 2.7`. This list is eventually sliced in batches, and each batch is used to get values using snmp get functions. When a single element within a batch has a timeout, the entire batch times out. Consequently we were receiving metrics randomly, depending on whether or not they were collected in the same batch as the single metric expected to timeout.
To stabilise this test we opted to reduce the batch size to `1`, so that every metric is collected singularly. …
=> [SNMP] stabilise test timeout

snmp/assets/dashboards/device_dashboard.json, snmp/manifest.json
Part 1 of 2: adding device dashboard
Add out of the box dashboard to monitor snmp devices
=> Add snmp device dashboard

haproxy/README.md, haproxy/assets/configuration/spec.yaml, haproxy/datadog_checks/haproxy/data/conf.yaml.example
Update the integration documentation according to this HAProxy blogpost https://www.haproxy.com/blog/haproxy-exposes-a-prometheus-metrics-endpoint/
=> Update haproxy doc for prometheus endpoint

mongo/README.md
Documentation updates for datadog-mongo v2.0.0 that will be released with agent 7.24
=> Update mongo docs for new release

haproxy/assets/dashboards/overview.json, haproxy/manifest.json
=> Migrate haproxy dashboard

snmp/assets/dashboards/datacenter_overview.json, snmp/manifest.json
Add a SNMP datacenter dashboard
Add an out of the box view for snmp datacenters
=> Add snmp datacenter dashboard

aerospike/datadog_checks/aerospike/aerospike.py, aerospike/tests/test_aerospike.py, aerospike/tests/test_unit.py
Update the check signature to only use `self.instance`
=> Update check signature

powerdns_recursor/README.md, powerdns_recursor/assets/configuration/spec.yaml, powerdns_recursor/datadog_checks/powerdns_recursor/data/conf.yaml.example, powerdns_recursor/manifest.json
Add logs support documentation.
Blocked on: https://github.com/DataDog/logs-backend/pull/13115
=> Add log collection docs

snowflake/README.md
move note higher
fix formatting
=> Fix formatting

datadog_checks_dev/datadog_checks/dev/tooling/utils.py, docs/developer/.scripts/33_render_status.py
Adding `saved_views` progress
Excluding the same integrations for logs progression
=> Add saved_views progress

snowflake/assets/recommended_monitors/snowflake_failed_logins.json
Increases the alert threshold and fixes the type to pass backend validation
=> Update recommended monitor

mongo/tests/common.py, mongo/tests/conftest.py, mongo/tests/test_mongo.py
Add an integration test for replset metrics
QA
=> Add replset metrics test

sap_hana/README.md, sap_hana/datadog_checks/sap_hana/data/conf.yaml.example
- Changes default port as it's incorrect, should be 39015
- Updates commands to add `;` as they won't work in HANA studio without them
- Adds note to see SAP setup docs for information on setting up ports
Jira request
=> SAP HANA docs and conf.yaml.example

istio/README.md
Fixes broken link in Istio integration readme
Report by @DanyNarcisse in #documentation channel
Docs-only update.
=> Fix Telemetry link to Istio docs

kubernetes/assets/dashboards/kubernetes_deployments.json, kubernetes/assets/dashboards/kubernetes_pods.json
Some minor adjustments to K8s Dashboards
https://datadoghq.atlassian.net/browse/CAP-380
=> [CAP-380] P.z/pods deployments dashboard fixes

mongo/README.md
Fixes broken MongoDB docs by adding the missing closing tab line
Docs request
=> MongoDB docs fix

etcd/assets/dashboards/etcd_2_overview.json, etcd/manifest.json
Migrate screenboard from dogweb
=> Migrate etcd dashboard

pgbouncer/datadog_checks/pgbouncer/pgbouncer.py, pgbouncer/tests/test_pgbouncer_unit.py
This PR adds to https://github.com/DataDog/integrations-core/pull/8124 by adding the exception message to the log exception message.
=> Add exception message to the logger to help with debugging

aerospike/assets/dashboards/overview.json
=> Update dashboard to blog like

gearmand/manifest.json
All the metrics sent are in `gearman.`
=> Fix gearman metric prefix

marklogic/assets/recommended_monitors/marklogic_high_load.json, marklogic/assets/recommended_monitors/marklogic_long_requests.json, marklogic/assets/recommended_monitors/marklogic_low_cache.json, marklogic/manifest.json
This PR adds new recommended monitors for MarkLogic:
1. `[MarkLogic] {{host.name}} cache is not large enough to handle new requests`
2. `[MarkLogic] Forest Processing Load is High on {{host.name}}`
3. `[MarkLogic] Active requests are taking too long on average`
=> Add recommended monitors for MarkLogic

docs/developer/process/agent-release/pre-release.md
=> Update release docs communication 

datadog_checks_dev/datadog_checks/dev/tooling/utils.py, docs/developer/.scripts/33_render_status.py
* Add numbers no the completed section
* Reorder elements (moving config specs lower now that we're almost done)
* Adding recommended monitors
=> more status tracking

oracle/tests/test_oracle.py
Makes tests for https://github.com/DataDog/integrations-core/pull/8083 more accurate
=> Make tests more accurate

marklogic/tests/test_api.py
Test for https://github.com/DataDog/integrations-core/pull/7941
=> Add test for url formatting

pgbouncer/README.md
Adds a note to modify the SSL configuration for the PGBouncer integration if required.
Jira/Zendesk request
=> PGBouncer SSL note

snmp/datadog_checks/snmp/snmp.py, snmp/tests/test_unit.py
Add bandwidth unit tests
Better coverage
=> Add bandwidth error message and unit tests

teamcity/README.md, teamcity/assets/configuration/spec.yaml, teamcity/datadog_checks/teamcity/data/conf.yaml.example, teamcity/manifest.json, teamcity/tests/common.py, teamcity/tests/conftest.py, teamcity/tests/docker/docker-compose.yaml
Also added a minimal E2E environment
=> Document logs support

sqlserver/datadog_checks/sqlserver/metrics.py, sqlserver/datadog_checks/sqlserver/sqlserver.py
Add small debug messages to help with debugging.
Customer support issue.
=> Add debug messages to SQLServer

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/snmp_tile/snmp_{check_name}/README.md
Small changes in `README.md` template, after Natalie's review:
* Remove word "SNMP" 
* Replace link to SNMP tile by link to online documentation
=> Small changes in template for "SNMP tiles"

spark/README.md
Fixing Formatting
Fixes Formatting on `/etc/datadog-agent/conf.d/spark.d/conf.yaml` for Agent 6/7
Reviewed documentation with TL
=> Fixing Formatting

disk/README.md
- Add info on enabling service check
- General wording cleanup
Jira request
N/A
=> DOCS-1528 Disk service check

apache/assets/dashboards/apache_dashboard.json
=> Add log stream widget to preset dashboard

sqlserver/README.md
AlwaysOn metrics for SQL Server require additional monitoring permissions.
=> Update README for AlwaysOn permissions

istio/assets/monitors/failed_sidecar_injection.json, istio/manifest.json
Monitor Istio failed sidecar injections
=> Add recommended monitor

gunicorn/datadog_checks/gunicorn/gunicorn.py, gunicorn/tests/test_check.py
Prevents raising an error if the master process no longer exists; raise a warning instead similar to the Process check.
current:
```
gunicorn (1.14.0)
-----------------
Instance ID: gunicorn:d5d42f235d8e8cb5 [ERROR]
Configuration Source: file:/etc/datadog-agent/conf.d/gunicorn.d/conf.yaml
Total Runs: 1
Service Checks: Last Run: 1, Total: 1
Average Execution Time : 15ms
Last Execution Date : 2021-01-11 00:18:40.000000 UTC
Last Successful Execution Date : Never
Error: Found no master process with name: gunicorn: master [<PROC_NAME>]
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 863, in run
File …
```
=> Prevent raising an error if the master process no longer exists

mongo/assets/monitors/high_connections.json
=> Fix mongo rec monitor

ecs_fargate/datadog_checks/ecs_fargate/data/conf.yaml.default, eks_fargate/datadog_checks/eks_fargate/data/conf.yaml.default, kubelet/datadog_checks/kubelet/data/conf.yaml.default
Add default config files with AD identifier to go with: https://github.com/DataDog/datadog-agent/pull/6798
=> Add new default for newly autodiscovered checks

oom_kill/README.md
This flag is no longer required.
=> [skip ci] Remove reference to system_probe_config.enabled

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py
Sync `units_catalog.csv` with metadata validation
Keep list of valid unit names in sync
=> Add span unit to metadata valid unit names

win32_event_log/datadog_checks/win32_event_log/check.py
Questions about this have come up a couple of times so adding a clarifying comment
=> Clarifiying comment in code

openshift/README.md
Removes extra spaces in tab markdown.
=> fix tab syntax in openshift docs

mongo/assets/monitors/high_connections.json, sqlserver/assets/recommended_monitors/sqlserver_db_not_sync.json, voltdb/assets/monitors/cpu_load.json
This PR fixes a few recommended monitors:
- VoltDB - add parenthesis
- SQLServer - change `metric alert` to `query alert`.
=> Fix rec monitor syntax

openshift/README.md
Prior PR used incorrect format for tabs, so the content didn't render, things should be correct now.
=> use github friendly tab format for openshift docs

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/datadog_checks/base/utils/db/transform.py, datadog_checks_base/datadog_checks/base/utils/db/utils.py, datadog_checks_base/requirements.in, datadog_checks_base/tests/test_db.py, rethinkdb/datadog_checks/rethinkdb/utils.py, rethinkdb/tests/unit/test_utils.py
Complete TODO from https://github.com/DataDog/integrations-core/pull/6692
=> Remove unneccessary `pytz` dependency

flink/README.md
Add dataCenter param
Jira request
Related docs PR: https://github.com/DataDog/documentation/pull/9449
=> DOCS-1507 Flink dataCenter

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/stats/stats.py
Add option to exclude release PRs from the list of merged PRs between 2 RC
Having them in the list can be a bit noisy.
=> Add option to exclude release prs

datadog_checks_base/datadog_checks/base/__about__.py, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/requirements.in, datadog_checks_base/tests/test_openmetrics.py
=> Upgrade dependency `prometheus-client` to 0.9.0

datadog_checks_dev/datadog_checks/dev/tooling/utils.py, docs/developer/.scripts/33_render_status.py
Add a new running status for docs spec completions to the status lists here: https://datadoghq.dev/integrations-core/meta/status/
=> Add docs spec progress to docs status board

.gitlab/tagger/Dockerfile
Gitlab job failing on CI because it's using python 3.6
`TypeError: namedtuple() got an unexpected keyword argument 'defaults'`
=> Update tagger Dockerfile image

.gitlab/tagger/Dockerfile
=> Use ubuntu tagger image

elastic/datadog_checks/elastic/elastic.py, elastic/datadog_checks/elastic/metrics.py, elastic/metadata.csv, elastic/tests/compose/docker-compose.yaml, elastic/tests/conftest.py, elastic/tests/test_elastic.py
Add metrics about snapshot lifecycle management, available since 7.4.0
Resolve #8178 
```
elasticsearch.slm.snapshot_deletion_failures
elasticsearch.slm.snapshots_deleted
elasticsearch.slm.snapshots_failed
elasticsearch.slm.snapshots_taken
```
=> Add SLM metrics

network/tests/test_network.py
CI fails because coverage is under 75%
=> Add submit_ena test

btrfs/tests/test_btrfs.py
=> Add get_usage test

mysql/datadog_checks/mysql/mysql.py
A customer has reported having the situation where the service check reports ok but Slave_SQL_Running is reporting No. Although according to MySQL documentation, this cannot happen we can still check for it.
=> Tighten condition for mysql.replication.slave_running

clickhouse/requirements.in, datadog_checks_base/datadog_checks/base/data/agent_requirements.in
Bump the version of `clickhouse-driver`.
=> Bump version of clickhouse-driver

cassandra_nodetool/README.md
Adds a section for log collection that redirects to Cassandra's logging instructions. 
The numbering of the markdown reference links did not start from 1, so I made this change as well.
=> Added documentation for cassandra-nodetool logging

mysql/metadata.csv
Clarifies the language of the DBM metrics so it is clear they are only part of the ALPHA.
=> Update MySQL metadata to clarify DBM ALPHA

postgres/metadata.csv
Clarifies the language of the DBM metrics so it is clear they are part of the ALPHA.
=> Update postgres metadata to clarify DBM ALPHA

azure_iot_edge/assets/dashboards/overview.json, azure_iot_edge/manifest.json
Add an OOTB dashboard for Azure IoT Edge.
Link to staging: https://dd.datad0g.com/screen/integration/30572/azure-iot-edge-overview
* Work begun by @jonepstein105 
* Prerequisite to blog post announcement
Staging preview:
=> Add OOTB dashboard for Azure IoT Edge

vault/README.md
Updates Readme to add prereq: configuring Prometheus metrics in Vault config
DOCS-1517
=> DOCS-1517 document prometheus prereq

sqlserver/assets/configuration/spec.yaml, sqlserver/datadog_checks/sqlserver/connection.py, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
We've seen a couple of support cases with confusion around this
=> Clarify authentication in SQL Server

tcp_queue_length/README.md
Updating README.md to reflect the recent changes in this integration
=> Update tcp_queue_length README.md

datadog_checks_dev/datadog_checks/dev/tooling/templates/docs/default.yaml, datadog_checks_dev/datadog_checks/dev/tooling/templates/docs/setup/configuration/log_collection.yaml, rethinkdb/README.md
Some fields like `service` are no longer required in logs configuration. Also removes note about Agent 6.0
=> Update logs readme template

oracle/README.md
Make instructions easier to follow
=> Move JDBC requirements to its own section

oracle/datadog_checks/oracle/oracle.py
Small improvement of debug lines
=> Make more explicit which connection was established

voltdb/manifest.json
Cleanup for #8385 
Prompted by https://github.com/DataDog/integrations-core/pull/8411#discussion_r562740051
Interestingly this didn't prevent me from seeing logs by `service:voltdb` or `source:voltdb` when validating the parser: https://github.com/DataDog/logs-backend/pull/16218
I'll check in how this attribute is used by our pipeline or by the app…
=> Add missing voltdb logs source

glusterfs/README.md, glusterfs/assets/configuration/spec.yaml, glusterfs/datadog_checks/glusterfs/data/conf.yaml.example, glusterfs/manifest.json
document logs support: https://github.com/DataDog/logs-backend/pull/15814
=> Document glusterfs logs support

haproxy/setup.py, istio/setup.py
https://github.com/DataDog/integrations-core/pull/8300
=> Update base package pin

haproxy/setup.py, istio/setup.py
This reverts commit 5dcd7a36f5e8f8d6e2e1a4fde73aaddaa1bb144e.
=> Revert "Update base package pin (#8426)"

linkerd/datadog_checks/linkerd/check.py, linkerd/datadog_checks/linkerd/linkerd.py, linkerd/datadog_checks/linkerd/metrics.py, linkerd/setup.py, linkerd/tests/common.py, linkerd/tests/test_linkerd.py
Beta test a fix for https://github.com/DataDog/integrations-core/issues/8076
=> Allow the use of the new OpenMetrics implementation

glusterfs/manifest.json, voltdb/manifest.json
=> Make new integration docs public for 7.26

nginx/datadog_checks/nginx/nginx.py
Resolves https://github.com/DataDog/integrations-core/issues/8439 and sets the metadata entrypoint decorator, so only when the option is enabled do we collect/submit version data.
=> Lower log level for version metadata submission

datadog_checks_dev/datadog_checks/dev/tooling/templates/docs/setup/configuration/log_collection.yaml, rethinkdb/README.md
Fix log collection template for better rendering.
Before
=> Fix log collection template

docs/developer/process/agent-release/pre-release.md
Update Agent "pre-release" docs with clearer review expectations for the initial "release all" review.
Mainly so we avoid issues like inappropriate semver bumps:
> During QA, just saw that https://github.com/DataDog/integrations-core/pull/8220 was labeled `changelog/Changed` , and it triggered a major version bump.
But also just as a general guideline to have good copywriting in our changelogs.
=> Update Agent release docs

istio/README.md
Adds more context to the istio docs
We now support a lot more cross-platform functionality
=> [documentation] adding cross-platform Istio information

cisco_aci/requirements.in, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/requirements.in, http_check/requirements.in, mysql/requirements.in, tls/requirements.in
Upgrade `cryptography` python package
=> Upgrade cryptography python package

azure_iot_edge/README.md
Adds a link to a new blog post
docs on-call tasks
docs only
=> Add link to related blog post to Azure IoT Edge integration readme

gunicorn/datadog_checks/gunicorn/gunicorn.py
While reviewing https://github.com/DataDog/integrations-core/pull/8314 I found it confusing that the service check is reported at different levels (`check` vs `_get_master_proc_by_name`) depending on the circumstances. This way also serves better the single responsability principle of `_get_master_proc_by_name`
=> Improve readability a bit

datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/labels.py, datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/transformers/histogram.py, datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/utils.py, datadog_checks_base/tests/openmetrics/test_transformers/test_histogram.py
https://github.com/DataDog/integrations-core/blob/60015f3da3fb0c514d4d83be531825884bc6c398/datadog_checks_base/datadog_checks/base/checks/openmetrics/mixins.py#L245-L246
=> Fix histogram upper bound label name for new OpenMetrics implementation

elastic/CHANGELOG.md, elastic/datadog_checks/elastic/__about__.py, requirements-agent-release.txt
Release changes in `elastic` integration for 7.26.0-rc.4.
Avoid included unrelated changes already in `master` such as  #8443 (see #8513).
* Similar to #6610
* PR #8511 was cherry-picked directly into `7.26.x` before opening this release PR.
* No `in-toto` metadata since it is not used on release branch, and we won't be tagging this release anyway (Agent builds from git tag directly).
=> Manually release `elastic` to 1.23.1

datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py
Only directories work directly
Encountered while running E2E for `tls`
=> Support bind mounting single files for Docker E2E on Windows

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, oracle/requirements.in
bug fixes, in particular https://github.com/jpype-project/jpype/pull/852
=> Upgrade JPype1 to 1.2.1

datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/init_config/openmetrics.yaml, datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/openmetrics.yaml
See:
- https://github.com/DataDog/integrations-core/blob/ae06f305290a211ab6f0dcfc697fad07045e8f0a/datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/scraper.py#L25
- https://github.com/DataDog/integrations-core/blob/ae06f305290a211ab6f0dcfc697fad07045e8f0a/datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/transform.py#L16
- https://github.com/DataDog/integrations-core/blob/ae06f305290a211ab6f0dcfc697fad07045e8f0a/datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/labels.py#L8
=> Add config spec for the new OpenMetrics implementation

datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py
Datadog_checks_downloader should also not be checked against base package
=> Do not run base_check for any base package

datadog_checks_dev/datadog_checks/dev/tooling/templates/docs/data_collected/metrics.yaml, datadog_checks_dev/datadog_checks/dev/tooling/templates/docs/default.yaml
Add `integration_id` as a parameter in the URL.
=> Update metrics template

eks_fargate/README.md
Fix a small grammar issue in the docs
mentioned in #documentation channel in slack
=> Fix grammar issue

haproxy/datadog_checks/haproxy/metrics.py, haproxy/tox.ini
this metric contains a tag with the version label which is super helpful during upgrades
also bump tests to haproxy 2.2.8 and 2.3.4
=> Add build_info metric

redisdb/assets/monitors/high_mem.json, redisdb/manifest.json
This PR is the first of many, i'm starting a new crusade to add as many OOTB monitors as possible over Agent integration.
This one is just a new conflict free version of: https://github.com/DataDog/integrations-core/pull/7313
Actually leveraging features and processes that have been developed.
=> [RedisDB] Adds default high mem usage monitor for Redis integration

airflow/README.md, airflow/metadata.csv, airflow/tests/test_check_metrics_up_to_date.py
=> Add missing metrics

.github/CODEOWNERS
- Update code owners of Nvidia Jetson and OpenTelemetry integrations
- Notify Agent Platform team on changes on these integrations
=> Update Agent Platform CODEOWNERS

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/testable.py, datadog_checks_dev/datadog_checks/dev/tooling/trello.py
- Fix the ids for `DONE` and `IN PROGRESS` columns
- Add a more explicit message when the milestone does not match.
- Check each card not in `RC builds` column has a label associated with the team.
- Fix `Infra-Integrations` label
=> Fix the ids `done` in `progress` columns

.azure-pipelines/templates/run-validations.yml
Print validation commands so it's easier for contributors to run locally in case they need to fix something.
=> Print validation commands

linkerd/setup.py
=> Bump base package requirement

openshift/README.md
Our translators pointed out that it is called a Pod Network - https://docs.openshift.com/enterprise/3.1/admin_guide/pod_network.html
=> [documentation] fixing typo

.github/CODEOWNERS
Update CODEOWNERS for openstack_controller.
=> Ownership for openstack_controller

snmp_juniper/README.md
Updated Juniper integration readme with latest NDM docs pages links
question from a docs translator
The link URLs work as is, but this makes them more resilient, less reliant on redirects.
=> Update Juniper readme with recent link changes

datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/labels.py, datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/scraper.py, datadog_checks_base/datadog_checks/base/utils/common.py, datadog_checks_base/datadog_checks/base/utils/functions.py
I need these for an upcoming PR, + these represent common patterns
=> Add logical utility functions

cassandra_nodetool/tox.ini
=> Add HOME to tox passenv

scylla/assets/configuration/spec.yaml, scylla/datadog_checks/scylla/data/conf.yaml.example
Encountered while working on the upcoming data model consumer
=> Fix logs section placement in example config

vsphere/assets/configuration/spec.yaml, vsphere/datadog_checks/vsphere/data/conf.yaml.example, vsphere/datadog_checks/vsphere/vsphere.py, vsphere/tests/test_check.py
Support filtering by tags set by integration
User request
=> Support filtering by tags set by integration

cisco_aci/requirements.in, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/requirements.in, http_check/requirements.in, mysql/requirements.in, tls/requirements.in
Upgrade cryptography python package
Refs #8611
=> Backport #8611 to 7.26.x: Upgrade cryptography python package

postgres/assets/configuration/spec.yaml
Encountered error while working on the upcoming data model consumer
=> Remove erroneous fields in config spec

kafka/assets/recommended_monitors/kafka_high_producer_request_rate.json, kafka/assets/recommended_monitors/kafka_offline_partition.json, kafka/manifest.json
Add recommended monitors for kafka integration
=> Add kafka recommended monitors

datadog_checks_base/datadog_checks/base/checks/base.py
Follow-up on https://github.com/DataDog/integrations-core/pull/5965/files#r389048486
=> Remove unused attribute

.azure-pipelines/templates/test-all-checks.yml, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/ci.py, tokumx/README.md
=> Do not run tokumx in py3 master build

voltdb/assets/dashboards/voltdb_overview.json, voltdb/manifest.json
Add an OOTB dashboard for VoltDB
[Staging link](https://dd.datad0g.com/screen/integration/30577/voltdb---overview)
* OOTB dashboard coverage
* Prepare announcement blog post
Any ideas for "blog-like sticky note hints" much welcome. :)
=> Add VoltDB out-of-the-box dashboard

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/readmes.py
The display queue doesn't work with tuples
=> Fix validate readme command

snmp/datadog_checks/snmp/data/conf.yaml.example
Fix oids not increasing link
Old link not working anymore
=> Fix oids not increasing link

docs/developer/ddev/cli.md
Follow-up to #8659
I had this change locally (as shown in the screenshot in #8659), but forgot to commit before merging. 🤦
=> Enable CLI options tables

activemq/assets/dashboards/activemq_dashboard.json
=> 💄 Use SVG logo for ActiveMQ dashboard

mapreduce/assets/dashboards/mapreduce_dashboard.json, mapreduce/manifest.json, marathon/assets/dashboards/marathon-overview_dashboard.json, marathon/manifest.json, openstack/assets/dashboards/openstack_dashboard.json, openstack/manifest.json, powerdns_recursor/assets/dashboards/powerdns_dashboard.json, powerdns_recursor/manifest.json, rabbitmq/assets/dashboards/rabbitmq_dashboard.json, rabbitmq/assets/dashboards/rabbitmq_screenboard_dashboard.json, rabbitmq/manifest.json
- mapreduce [Staging Link](https://dd.datad0g.com/screen/integration/89/mapreduce---overview?from_ts=1613748526194&to_ts=1613752126194&live=true)
- marathon [Staging Link](https://dd.datad0g.com/screen/integration/132/marathon---overview?from_ts=1613751543027&live=true&to_ts=1613755143027)
- openstack [Staging Link](https://dd.datad0g.com/screen/integration/85/openstack---overview?from_ts=1613748542371&to_ts=1613752142371&live=true) 
- powerdns_recursor [Staging Link](https://dd.datad0g.com/screen/integration/98/powerdns-recursor---overview?from_ts=1613748550468&to_ts=1613752150468&live=true)
- rabbitmq  
- [Staging Link -- Overview](https://dd.datad0g.com/screen/integration/124/rabbitmq---overview?from_ts=1613754122616&to_ts=1613757722616&liv …
=> Migrate mapreduce, marathon, openstack, powerdns_recursor, rabbitmq dashboards

docs/developer/guidelines/conventions.md
Noticed a few cases while working on a new feature
=> Document our attribute naming convention

cacti/datadog_checks/cacti/cacti.py, datadog_checks_base/datadog_checks/base/__about__.py, datadog_checks_base/datadog_checks/base/utils/tls.py, directory/datadog_checks/directory/directory.py, docs/developer/guidelines/style.md, elastic/datadog_checks/elastic/elastic.py, ibm_mq/datadog_checks/ibm_mq/ibm_mq.py, ibm_mq/tests/test_ibm_mq_int.py, marklogic/datadog_checks/marklogic/check.py, marklogic/tests/test_resource_filters.py, mongo/datadog_checks/mongo/collectors/replica.py, mongo/datadog_checks/mongo/mongo.py, mongo/tests/test_unit.py, mysql/datadog_checks/mysql/mysql.py, postgres/datadog_checks/postgres/postgres.py, postgres/tests/test_pg_integration.py, postgres/tests/test_unit.py, rethinkdb/datadog_checks/rethinkdb/check.py, snowflake/datadog_checks/snowflake/check.py, snowflake/tests/test_unit.py, twistlock/datadog_checks/twistlock/twistlock.py, vsphere/datadog_checks/vsphere/vsphere.py, vsphere/tests/test_check.py, vsphere/tests/test_filters.py
Adhere to https://datadoghq.dev/integrations-core/guidelines/conventions/#attribute-naming for an incoming new feature
=> Rename config attribute to not shadow the one provided by the base class

mysql/README.md
Documents `mysql.replication.replica_running` service check.
Related to https://github.com/DataDog/integrations-core/pull/8402
=> Update Service Checks section

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/datadog_checks/{check_name}/check.py
Adds snippets of code in the `check` method. Examples for http requests, performing DB queries, and submitting metrics. 
New contributors can draw inspiration from the snippets provided and explore the documentation referred in the samples.
Potentially the snippets could be more complex to showcase more practical functionality that would happen when writing an actual check (error checking, overriding `__init__` method), but I am not sure how in depth we would want these snippets to be. 
Code was initially uncommented, but it was failing CI. In order to pass CI, the snippets would need to be more involved.
=> Add code snippets to check template

riak/assets/dashboards/riak_dashboard.json, riak/manifest.json, spark/assets/dashboards/spark_dashboard.json, spark/manifest.json, vsphere/assets/dashboards/vsphere_dashboard.json, vsphere/manifest.json, wmi_check/assets/dashboards/windows_server_dashboard.json, wmi_check/manifest.json
- riak [Staging Link](https://dd.datad0g.com/dash/integration/36/riak---metrics?from_ts=1614013712877&live=true&to_ts=1614017312877)
- spark [Staging Link](https://dd.datad0g.com/screen/integration/96/spark---overview?from_ts=1613773917753&to_ts=1613777517753&live=true)
- vsphere [Staging Link](https://dd.datad0g.com/screen/integration/133/vmware-vsphere---overview?from_ts=1614013707218&live=true&to_ts=1614017307218) 
- wmi_check [Staging Link](https://dd.datad0g.com/screen/integration/77/windows-server---overview?from_ts=1613774871994&to_ts=1613778471994&live=true)
[Dogweb PR](https://github.com/DataDog/dogweb/pull/56766)
Compatibility
=> Migrate riak, spark, vsphere, wmi_check dashboards

airflow/README.md
https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/metrics.html#counters
=> Fix heartbeat failure metric name

openshift/README.md
- Fix link so it works on the docs site
- Format table
Jira request
N/A
=> DOCS-1551 Openshift link fix

wmi_check/README.md
Update docs
[staging](https://dd.datad0g.com/account/settings#integrations/wmi)
=> Fix header level for configuration section in wmi docs

snmp/datadog_checks/snmp/snmp.py
Add extract_value_pattern to log on failure to submit metric
Help support
=> Add extract_value_pattern  to log on failure to submit metric

databricks/manifest.json
=> Enable docs for databricks

coredns/assets/monitors/coredns_cache_hits_low.json, coredns/assets/monitors/coredns_request_duration_high.json, coredns/manifest.json
=> Add recommended monitors

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/fixed_cards_mover.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/testable.py
Create missing cards when using `--move-cards`
Make sure all PRs are QAed.
=> Create missing cards when using `--move-cards`

couchbase/datadog_checks/couchbase/couchbase.py, couchbase/tests/test_couchbase.py, couchbase/tests/test_unit.py
Responding to feedback for Sync Gateway metrics and decided to open a separate PR to introduce complete refactor
=> Refactor and use new Agent signature

btrfs/assets/dashboards/btrfs_dashboard.json, btrfs/manifest.json, couchbase/assets/dashboards/couchbase_dashboard.json, couchbase/manifest.json, fluentd/assets/dashboards/fluentd_dashboard.json, fluentd/manifest.json, gearmand/assets/dashboards/gearman_dashboard.json, gearmand/manifest.json
- btrfs [Staging Link](https://dd.datad0g.com/dash/integration/61/system---btrfs?from_ts=1614096983823&live=true&to_ts=1614100583823)
- couchbase [Staging Link](https://dd.datad0g.com/dash/integration/45/couchbase---metrics?from_ts=1614096991433&live=true&to_ts=1614100591433) 
- fluentd [Staging Link](https://dd.datad0g.com/dash/integration/72/fluentd---metrics?from_ts=1614096997878&live=true&to_ts=1614100597878)
- gearman [Staging Link](https://dd.datad0g.com/dash/integration/38/gearman---metrics?from_ts=1614097007351&live=true&to_ts=1614100607351) 
[Dogweb PR](https://github.com/DataDog/dogweb/pull/56811)
=>  Migrate btrfs, couchbase, fluentd, gearman dashboards to integrations core 

kafka/assets/dashboards/kafka_dashboard.json, kafka/manifest.json, kong/assets/dashboards/kong_dashboard.json, kong/manifest.json, kyototycoon/assets/dashboards/kyototycoon_dashboard.json, kyototycoon/manifest.json, lighttpd/assets/dashboards/lighttpd_dashboard.json, lighttpd/manifest.json
- kafka [Staging Link](https://dd.datad0g.com/screen/integration/50/kafka---overview?from_ts=1614100395310&to_ts=1614103995310&live=true)
- kong
- kong [Staging Link](https://dd.datad0g.com/dash/integration/95/kong---metrics?from_ts=1614106703631&live=true&to_ts=1614110303631) 
- kong Overview [Staging Link](https://dd.datad0g.com/screen/integration/30262/kong-overview?from_ts=1614106500442&live=true&to_ts=1614110100442) 
- kyoto_tycoon [Staging Link](https://dd.datad0g.com/dash/integration/49/kyoto-tycoon---metrics?from_ts=1614109732848&live=true&to_ts=1614110032848)
- lighttpd [Staging Link -- Overview](https://dd.datad0g.com/screen/integration/44/lighttpd---overview?from_ts=1614100408940&to_ts=1614104008940&live=true) 
[Dogweb …
=> Migrate kafka, kong, kyototycoon, lighttpd dash from dogweb

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/requirements.in, datadog_checks_base/tests/test_ddyaml.py, datadog_checks_dev/setup.py
Upgrade `pyyaml` python package.
=> Upgrade pyyaml python package

datadog_checks_dev/datadog_checks/dev/tooling/utils.py, datadog_checks_dev/tests/tooling/test_utils.py, docs/developer/.scripts/33_render_status.py
Do not report e2e or metadata for logs only integrations
=> Check if integrations are logs only

zk/tests/conftest.py
ZK SSL tests are flaking. This is an attempt to get a more stable build
=> Check for more logs in ZK SSL startup

.azure-pipelines/templates/test-all.yml
`eq(parameters.os, 'linux')` should be `eq(check.os, 'linux')`
=> Fix e2e on master

ecs_fargate/README.md, eks_fargate/README.md
=> adding blog links to fargate docs

docs/developer/ddev/test.md, docs/developer/guidelines/dashboards.md, docs/developer/guidelines/pr.md, docs/developer/meta/ci.md, docs/developer/meta/config-specs.md, docs/developer/meta/docs-specs.md, docs/developer/process/agent-release/post-release.md, docs/developer/process/agent-release/pre-release.md, docs/developer/process/integration-release.md
https://github.com/DataDog/integrations-core/pull/8659
=> Fix links to CLI commands

snmp_juniper/README.md
Adds a link to a relevant blog post
=> Add blog link to Juniper readme

.azure-pipelines/templates/test-all-checks.yml, .codecov.yml, nginx/assets/dashboards/NGINX-Metrics_dashboard.json, nginx/assets/dashboards/NGINX-Overview_dashboard.json, nginx/manifest.json, pgbouncer/assets/dashboards/pgbouncer_dashboard.json, pgbouncer/manifest.json, postfix/assets/dashboards/postfix_dashboard.json, postfix/manifest.json, riakcs/assets/configuration/spec.yaml, riakcs/assets/dashboards/riakcs_dashboard.json, riakcs/manifest.json
- nginx
- overview [Staging Link](https://dd.datad0g.com/screen/integration/21/nginx---overview?from_ts=1614109300901&to_ts=1614112900901&live=true) 
- metrics [Staging Link](https://dd.datad0g.com/dash/integration/20/nginx---metrics?from_ts=1614109302336&live=true&to_ts=1614112902336) 
- pgbouncer [Staging Link](https://dd.datad0g.com/dash/integration/79/pgbouncer---metrics?from_ts=1614109373770&live=true&to_ts=1614112973770)
- postfix [Staging Link](https://dd.datad0g.com/dash/integration/51/postfix---metrics?from_ts=1614109388838&live=true&to_ts=1614112988838)
- riakcs [Staging Link](https://dd.datad0g.com/dash/integration/73/riakcs---metrics?from_ts=1614109395306&live=true&to_ts=1614112995306)
[Dogweb …
=> Migrate nginx, pgbouncer, postfix, riakcs dash from dogweb

gunicorn/assets/dashboards/gunicorn_dashboard.json, gunicorn/manifest.json, tokumx/assets/dashboards/tokumx_dashboard.json, tokumx/manifest.json
- gunicorn [Staging Link](https://dd.datad0g.com/screen/integration/46/gunicorn---overview?from_ts=1614354831198&to_ts=1614358431198&live=true)
- tokumx [Staging Link](https://dd.datad0g.com/dash/integration/53/tokumx---metrics?from_ts=1614357755430&live=true&to_ts=1614361355430)
[Dogweb PR](https://github.com/DataDog/dogweb/pull/56977)
=> Migrate gunicorn, TokuMX from dogweb

solr/assets/dashboards/solr_dashboard.json, solr/manifest.json, sqlserver/assets/dashboards/SQLServer-Overview_dashboard.json, sqlserver/assets/dashboards/sqlserver_dashboard.json, sqlserver/manifest.json, varnish/assets/dashboards/varnish_dashboard.json, varnish/manifest.json, zk/assets/dashboards/zookeeper_dashboard.json, zk/manifest.json
- solr [Staging Link](https://dd.datad0g.com/dash/integration/31/solr---metrics?from_ts=1614113012311&live=true&to_ts=1614116612311)
- sqlserver
- overview [Staging Link](https://dd.datad0g.com/screen/integration/123/sqlserver---overview?from_ts=1614113018094&to_ts=1614116618094&live=true) 
- metrics [Staging Link](https://dd.datad0g.com/dash/integration/33/sqlserver---metrics?from_ts=1614113017088&live=true&to_ts=1614116617088) 
- varnish [Staging Link](https://dd.datad0g.com/dash/integration/18/varnish---metrics?from_ts=1614113023055&live=true&to_ts=1614116623055)
- zookeeper [Staging Link](https://dd.datad0g.com/screen/integration/35/zookeeper---overview?from_ts=1614113027368&to_ts=1614116627368&live=true)
[Dogweb …
=> Migrate solr, sqlserver, varnish, zookeeper dashes from dogweb

oracle/assets/dashboards/oracle_overview.json
Update Default Oracle Dashboard to use Global timeframe in all widgets
https://datadog.zendesk.com/agent/tickets/453615
=> Update Default Oracle Dashboard

datadog_checks_base/datadog_checks/base/__about__.py, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/requirements.in
Generally to stay current, + many fixes https://github.com/jpadilla/pyjwt/blob/master/CHANGELOG.rst#v200
=> Upgrade PyJWT to 2.0.1 on Python 3

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/requirements.in
Perf https://github.com/ijl/orjson/blob/master/CHANGELOG.md
=> Upgrade orjson to 3.5.0

elastic/assets/monitors/elastic_pending_tasks_high.json, elastic/assets/monitors/elastic_query_latency_high.json, elastic/assets/monitors/elastic_query_load_high.json, elastic/assets/monitors/elastic_requests.json, elastic/manifest.json
Add recommended monitors to elasticsearch
=> Add elastic monitors

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/requirements.in
Reverts DataDog/integrations-core#8765
=> Revert "Upgrade orjson to 3.5.0"

postgres/setup.py
Bump to new version containing this fix: https://github.com/DataDog/integrations-core/pull/8767
=> postgres: bump datadog_checks_base min version

eks_fargate/assets/configuration/spec.yaml, eks_fargate/conftest.py, eks_fargate/datadog_checks/eks_fargate/common.py, eks_fargate/datadog_checks/eks_fargate/data/conf.yaml.example, eks_fargate/datadog_checks/eks_fargate/eks_fargate.py, eks_fargate/metadata.csv, eks_fargate/tests/fixtures/pods.json, eks_fargate/tests/test_eks_fargate.py
Update EKS Fargate check to also report capacity metrics, available via [pod annotation
](https://docs.aws.amazon.com/eks/latest/userguide/fargate-pod-configuration.html)
Better experience for EKS Fargate users in tracking pod capacities
=> [eks_fargate] Add pod capacity metrics

vault/assets/monitors/vault_S3_time_high.json, vault/manifest.json
=> Add recommended Vault monitor

ecs_fargate/README.md
=> [DOCS 1417] Update Fargate readme with env vars

mkdocs.yml
https://github.com/squidfunk/mkdocs-material/issues/2342
=> Fix table of contents

docs/developer/meta/docs.md
https://datadoghq.dev/integrations-core/meta/docs/
=> Fix svg icons

datadog_checks_base/datadog_checks/base/checks/kube_leader/record.py
Import kubernetes lazily to reduce memory footprint
RSS increase
=> Import kube client lazily

sqlserver/datadog_checks/sqlserver/metrics.py
Add code comment for https://github.com/DataDog/integrations-core/pull/8481
=> Add code comment

kafka_consumer/datadog_checks/kafka_consumer/legacy_0_10_2.py
Adds more logging to the kafka consumer legacy check
=> Add more logging

hazelcast/README.md
Our Docs doesn't mention about the Hazelcast version supported.
Ticket: https://datadog.zendesk.com/agent/tickets/441115
This is described in Jira card: https://datadoghq.atlassian.net/browse/AGENT-5545?focusedCommentId=325289
=> Update Hazelcast supported Versions.

couchbase/datadog_checks/couchbase/couchbase.py
https://github.com/DataDog/integrations-core/pull/8712
=> Finish refactor

couchbase/tests/test_couchbase.py
=> Remove check instance argument from tests

docs/developer/process/agent-release/pre-release.md
=> Specify testable origin master in docs

consul/assets/configuration/spec.yaml, consul/datadog_checks/consul/consul.py, consul/datadog_checks/consul/data/auto_conf.yaml, consul/datadog_checks/consul/data/conf.yaml.example, consul/tests/consul_mocks.py, consul/tests/test_unit.py
Followup of https://github.com/DataDog/integrations-core/pull/8377 for more consistent and inclusive naming
=> Rename service_whitelist to services_include

voltdb/README.md, voltdb/manifest.json
Adds a link to a new blog post 
Docs on-call tasks
=> VoltDB Readme: Add link to blog post

datadog_checks_base/datadog_checks/base/utils/time.py, datadog_checks_base/tests/test_time.py
With the merge of #8837 there were now three different checks using the same code block to get precision time measurements.  This PR factors them out into the base check.
This PR covers datadog_checks_base, changes to the other checks will be covered separately.
=> Add new precision time function

dns_check/datadog_checks/dns_check/dns_check.py, dns_check/setup.py, dns_check/tests/test_dns_check.py, sqlserver/datadog_checks/sqlserver/metrics.py, sqlserver/datadog_checks/sqlserver/utils.py, sqlserver/setup.py, tcp_check/datadog_checks/tcp_check/tcp_check.py, tcp_check/setup.py
Building on top of #8838 this PR migrates the related time code to utilize the new base check functionality.
=> Utilize time precision function from datadog_checks_base

active_directory/README.md
=> Update Active Directory docs

active_directory/requirements.in, aspdotnet/requirements.in, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/requirements.in, dotnetclr/requirements.in, exchange_server/requirements.in, iis/requirements.in, pdh_check/requirements.in, sqlserver/requirements.in, win32_event_log/requirements.in, windows_service/requirements.in, wmi_check/requirements.in
https://github.com/mhammond/pywin32/commit/907c97ed0cd426539f765a809a94466249e2b202
=> Upgrade pywin32 on Python 3

oracle/README.md
Clarify docs with commonly encountered issues.
=> Add troubleshooting instructions

kafka/assets/dashboards/kafka_dashboard.json
New changes are in bottom right corner
[Staging Link](https://dd.datad0g.com/screen/integration/50/kafka---overview?from_ts=1615997648417&live=true&to_ts=1616001248417)
=> Add kafka consumer metrics to kafka dashboard

activemq/assets/recommended_monitors/activemq_artemis_high_disk_store.json, activemq/assets/recommended_monitors/activemq_artemis_unrouted_messages.json, activemq/manifest.json
Add recommended monitors for ActiveMQ Artemis integration.
=> Add ActiveMQ Artemis recommended monitors

datadog_checks_base/datadog_checks/base/checks/win/winpdh_base.py
Followup of https://github.com/DataDog/integrations-core/pull/8821
=> Make counter refresh-related code more reusable

vertica/assets/configuration/spec.yaml, vertica/datadog_checks/vertica/data/conf.yaml.example
=> Fix logs section in example config file

activemq/README.md
Fix rendering of Overview tab for ActiveMQ tile.
=> Update metrics link

cassandra/tests/compose/docker-compose.yml, cassandra/tests/conftest.py
=> Add logs for cassandra e2e environment
