datadog_checks_dev/datadog_checks/dev/tooling/signing.py

Prevents in-toto from normalizing line endings when hashing files.
That works for developers on Windows (where they must hash files that end up being normalized in git), but not for extras on Linux.
N/A

ddev for extras must not rewrite line endings

---

snmp/datadog_checks/snmp/parsing/metrics.py

Revert Fix wrong indentation of `table` key in column metric tags #7024
We keep the profiles indent fixes made in #7024
Need more investigation about the consequence of raising an ConfigurationError at this location.
Currently, the check will fail on startup with `Warning: found unexpected "table" key in column`.

Revert Fix wrong indentation of `table` key in column metric tags #7024

---

.azure-pipelines/templates/test-all.yml

This PR adds the `coverage` parameter to the test-all.yml template to get passed down to the test-single job. 
The parameter seemed to be propagating down for the test changes pipeline in external repos, but not for the test all pipeline. This should resolve that.

Add coverage param to test-all

---

mysql/assets/configuration/spec.yaml
mysql/datadog_checks/mysql/data/conf.yaml.example

- QA for https://github.com/DataDog/integrations-core/pull/7204
- make default values more accurate

Update config spec default values

---

docs/dev/new_check_howto.md

updates `pip` to `pip3` in new check doc. confirmed ddev needs to be installed with pip3

DOCS 1160 - ddev needs pip3

---

datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py

Adds E2E support for adding custom hosts to the Agent `/etc/hosts` file.
This could be used in place of the functionality provided by `mock_e2e_agent` in #7106.
Example usage:
```python
MOCKED_E2E_HOSTS = ('namenode', 'datanode', 'resourcemanager', 'nodemanager', 'historyserver')
def get_custom_hosts():
custom_hosts = [(host, '127.0.0.1') for host in MOCKED_E2E_HOSTS]
return custom_hosts
@pytest.fixture(scope="session")
def dd_environment():
env = {'HOSTNAME': HOST}
with docker_run(
compose_file=os.path.join(HERE, "compose", "docker-compose.yaml"),
conditions=[
WaitFor(setup_mapreduce, attempts=240, wait=5)
],
mount_logs=True,
env_vars=env,
):
yield INSTANCE_INTEGRATION, {'custom_hosts': get_custom_hosts()}
```
This ends up appending the following options to the `docker run` command: …

Support updating Agent /etc/hosts in E2E envs

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/recommended_monitors.py

Recommended monitors currently allow `metric alert`, `query alert` and `event alert` types, so this PR adds a validation for that. 
I also modified the error messaging a bit to try and make the recommended solution a bit more clear. 
I also only print the filename instead of the file path at the beginning of the error. Since the errors are nested under the integration name anyway, it makes the error line shorter.

Add monitor validation on allowed types and more friendly error messages

---

mapreduce/assets/configuration/spec.yaml
mapreduce/datadog_checks/mapreduce/data/conf.yaml.example
mapreduce/manifest.json

Add config spec for `mapreduce` check.
`conf.yaml.example` synced with #7177 in place.

Add mapreduce config specs

---

istio/assets/dashboards/istio_1_5_overview.json
istio/manifest.json

Update the Istio 1.5+ OOB dashboard
- Make capitalization consistent
- Change "Mesh throughput" to the more accurate "Mesh metrics"
- Aggregate by host in the "Hosts with the highest GC time toplist"
- Remove names of deprecated Istio microservices
- Aggregate the xDS pushes widget by push type
- Rename "LDS/EDS/RDS/CDS Build,Send Errors" since the metric
no longer includes build errors in recent versions of Istio.
See:
https://github.com/istio/istio/commit/e97b19756df06bf04784e2cf1cd6f1176c9ef64d
- Remove the istio.pilot.xds.eds_all_locality_endpoints widget
since the metric has been removed from recent versions of
Istio. See:
https://github.com/istio/istio/commit/eb4178a79ad31dd63e901c2902af65354afc2e26
- Replace the all locality endpoints widget with one for …

Update the Istio 1.5+ dashboard.

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/dashboard.py

This PR updates the `ddev meta dash export` command to support the newer `dashboard` api instead of the older apis.
I also updated the regex to allow you to paste in a URL that just ends with the dash id
I added a success message at the end if the CLI completed properly. 
I also made the integration argument required, it looks like with the way the board_id regex was, this was being required anyway. 
An effort to start using the newer dashboard payloads and migrate existing dashboards away from the old format.

Update dash export command to use newer api

---

pdh_check/datadog_checks/pdh_check/pdh_check.py
pdh_check/tests/test_pdh_check.py

Raises ConfigurationError if required config option is missing

add counterset validation in pdh check

---

mongo/datadog_checks/mongo/mongo.py

Solves bug introduced in https://github.com/DataDog/integrations-core/pull/6085/files#diff-0efa0f9b704463fe48690c966595316cR90 that made collection metrics be collected only once.

Avoid depleting collection_metric_names

---

linkerd/assets/dashboards/overview.json
mapr/assets/dashboards/mapr_overview.json
nginx/assets/dashboards/plus_overview.json
openstack/assets/dashboards/openstack-controller.json
oracle/assets/dashboards/oracle_overview.json
presto/assets/dashboards/overview.json
proxysql/assets/dashboards/overview.json
rethinkdb/assets/dashboards/overview.json
sap_hana/assets/dashboards/overview.json
scylla/assets/dashboards/overview.json
sidekiq/assets/dashboards/overview.json
systemd/assets/dashboards/overview.json
tls/assets/dashboards/overview.json
vault/assets/dashboards/vault_overview.json
vertica/assets/dashboards/overview.json
vsphere/assets/dashboards/vsphere_overview.json

Migrates a handful of integration dashboards to use the new `dashboard` payload structure
Trying to migrate away from the older screenboard/timeboard payload usage
Can be confirmed by checking each dashboard loads properly on staging.

Migrate Integration Dashboards to new payload structure

---

.gitlab/tagger/build-packages.sh

Remove unused ORIG_CI_BUILD_REF_NAME param in release

---

cloud_foundry_api/datadog_checks/cloud_foundry_api/cloud_foundry_api.py
cloud_foundry_api/tests/test_cloud_foundry_api.py

Adds `space_id` and `org_id` tags in addition to `space_guid` and `org_guid` to make sure users can use the same set of tags as they use for the datadog-firehose-nozzle.
We should provide usage consistency with https://github.com/DataDog/datadog-firehose-nozzle which submits `org_id` and `space_id` tags.

Add space_id and org_id tags in addition to space_guid and org_guid

---

cloud_foundry_api/datadog_checks/cloud_foundry_api/cloud_foundry_api.py
cloud_foundry_api/tests/fixtures/event_v2.json
cloud_foundry_api/tests/fixtures/event_v3.json
cloud_foundry_api/tests/test_cloud_foundry_api.py

Adds the CF API event metadata to DataDog events as serialized JSON (also makes the event text markdown in order to be able to use preformatted text).

Add Cloud Foundry event metadata to DataDog event text as serialized JSON

---

activemq/datadog_checks/activemq/data/conf.yaml.example
cassandra/datadog_checks/cassandra/data/conf.yaml.example
confluent_platform/datadog_checks/confluent_platform/data/conf.yaml.example
consul/datadog_checks/consul/data/conf.yaml.example
datadog_checks_dev/datadog_checks/dev/tooling/configuration/consumers/example.py
hazelcast/datadog_checks/hazelcast/data/conf.yaml.example
hive/datadog_checks/hive/data/conf.yaml.example
hivemq/datadog_checks/hivemq/data/conf.yaml.example
ignite/datadog_checks/ignite/data/conf.yaml.example
jboss_wildfly/datadog_checks/jboss_wildfly/data/conf.yaml.example
kafka/datadog_checks/kafka/data/conf.yaml.example
kube_apiserver_metrics/datadog_checks/kube_apiserver_metrics/data/auto_conf.yaml
kube_apiserver_metrics/datadog_checks/kube_apiserver_metrics/data/conf.yaml.example
postgres/datadog_checks/postgres/data/conf.yaml.example
solr/datadog_checks/solr/data/conf.yaml.example
tokumx/datadog_checks/tokumx/data/conf.yaml.example
tomcat/datadog_checks/tomcat/data/conf.yaml.example

- Have a consistent format on rendered `default` values.
- If setting `default: true` on the configuration specification of a check, it will be rendered as `default: True`, instead of `default: true`, which is what happens when setting `example: true`.

[datadog_checks_dev] Use consistent formatting for boolean values

---

airflow/assets/dashboards/overview.json
amazon_msk/assets/dashboards/overview.json
ambari/assets/dashboards/base_dashboard.json
cilium/assets/dashboards/overview.json
clickhouse/assets/dashboards/overview.json
cockroachdb/assets/dashboards/overview.json
confluent_platform/assets/dashboards/overview.json
druid/assets/dashboards/overview.json
ecs_fargate/assets/dashboards/amazon_fargate_overview.json
envoy/assets/dashboards/envoy_overview.json
etcd/assets/dashboards/etcd_overview.json
exchange_server/assets/dashboards/overview.json
flink/assets/dashboards/overview.json
gitlab/assets/dashboards/overview.json
harbor/assets/dashboards/overview.json
hazelcast/assets/dashboards/overview.json
hive/assets/dashboards/overview.json
hivemq/assets/dashboards/hivemq.json
ibm_db2/assets/dashboards/overview.json
ignite/assets/dashboards/ignite_overview.json
istio/assets/dashboards/istio_1_5_overview.json
istio/assets/dashboards/istio_overview.json
kong/assets/dashboards/kong_overview.json
kube_metrics_server/assets/dashboards/overview.json
kubernetes/assets/dashboards/kubernetes_deployments.json
kubernetes/assets/dashboards/kubernetes_nodes.json
kubernetes/assets/dashboards/kubernetes_pods.json

This pull request converts the rest of the dashboard payloads in `integrations-core`.
@DataDog/dashboards is seeking to deprecate all legacy payloads as they are cumbersome and difficult to get. We use the new format payloads everywhere now.
Ensure that these boards still work on staging:
* https://dd.datad0g.com/screen/integration/30253/airflow-overview?from_ts=1597861698253&live=true&to_ts=1597865298253
* https://dd.datad0g.com/screen/integration/30260/amazon-msk-overview
* https://dd.datad0g.com/screen/integration/30198/ambari-base-dashboard
* https://dd.datad0g.com/screen/integration/30247/cilium-overview?from_ts=1597861751948&to_ts=1597865351948&live=true
* https://dd.datad0g.com/screen/integration/30256/clickhouse-overview?from_ts=1597861767907&to_ts=1597865367907&live=true
* …

[dashboards] Convert rest of integrations-core dashboard payloads

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/rc_build_cards_updater.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/testable.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/tester_selector/cache.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/tester_selector/github_trello_user_matcher.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/tester_selector/github_users.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/tester_selector/tester_selector.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/tester_selector/tester_selector_team.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/tester_selector/trello_users.py
datadog_checks_dev/datadog_checks/dev/tooling/github.py
datadog_checks_dev/datadog_checks/dev/tooling/trello.py

This PR assign a tester to the Trello cards created by `ddev release trello testable` 
The algorithm is the following:
1. Consider teammates who are neither the author of the PR nor a reviewer.
2. Select the teammate with the least number of assigned cards. If several teammates meet these criterion, select one randomly.
If a tester cannot be find, use 2. but consider teammates that reviewed the PR.
A user is not considered if she did not open a pull request on DataDog/datadog-agent during the last 6 weeks.
Note: If someone review all the PRs of her team, the algorithm never select her.
Algorithm is implemented in `tester_selector_team.py`
Assigning a tester that is neither the author nor a review is time consuming
To match Trello users and Github users, the code uses heuristics as I was …

Auto assign card

---

win32_event_log/datadog_checks/win32_event_log/check.py
win32_event_log/datadog_checks/win32_event_log/data/conf.yaml.example
win32_event_log/datadog_checks/win32_event_log/legacy/win32_event_log.py

Background: new implementation for win32_event_log has been introduced in https://github.com/DataDog/integrations-core/pull/7005
* Add notes on legacy config options
* Remove redundant username, while keeping compatibility
* Add warnings if using the wrong config options

Make it easier to configure legacy vs new options

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/recommended_monitors.py

Adds service checks to `ALLOWED_MONITOR_TYPES` for recommended monitors.  Support added https://github.com/DataDog/web-ui/pull/18806 and https://github.com/DataDog/k8s-resources/pull/9827
Recommended monitors work

Support service checks in recommended monitors

---

ssh_check/assets/configuration/spec.yaml
ssh_check/datadog_checks/ssh_check/data/conf.yaml.example
ssh_check/datadog_checks/ssh_check/ssh_check.py

###What does this PR do?
If `private_key_file` exists, `password` is used for decryption instead of plain username/password auth
AI-909
- I used the existing `password` parameter since it will not be used in plain authentication if a `private_key_file` was set; it will instead be used for decrypting the private key file. If this is not fine, we could possibly add `private_key_file_password`

pass the password to be used for pkey decryption

---

datadog_checks_base/datadog_checks/base/utils/aws.py
datadog_checks_base/tests/test_aws.py

Exposes a utility function for parsing AWS RDS metadata to tag database integrations with when they are connecting to an RDS / Aurora instance.
This improves the experience for customers because it will provide a common tag set they can use to link Cloudwatch integration metrics with database integration metrics. This common tagging will be used in database monitoring dashboards so customers need only toggle a single tag instead of multiple tags on dashboards.

Add function to parse RDS tags from the endpoint

---

redisdb/datadog_checks/redisdb/redisdb.py
redisdb/tests/test_slowlog.py

Check the `redis_role` exist before adding it as a tag.
Gracefully handle cases where the role is not here.
It seems the role is not in Alibaba ApsaraDB for example https://github.com/DataDog/integrations-core/issues/5915.
Note that it may not be enough to support ApsaraDB and other Redis-like.

Handle redis role missing

---

etcd/README.md
etcd/datadog_checks/etcd/data/conf.yaml.example
etcd/manifest.json
etcd/tests/conftest.py

updates readme and conf.yaml to let users know how to set up logs. Updates testing env to forward logs.
https://datadoghq.atlassian.net/browse/AI-739
https://github.com/DataDog/web-ui/pull/19132
https://github.com/DataDog/logs-backend/pull/11873

Add support for etcd logs

---

mapreduce/manifest.json
mapreduce/tests/README.md

Updates `manifest.json` to indicate logs support, and adds a README for how to get logs extracted in an E2E test environment.

Document logs support in e2e

---

.github/CODEOWNERS

Removes intg-tools-libs from the codeowners file for this repo
We'll get notified when an integration gets synced after this point, so this removes getting notified on all manifest/asset changes.

Remove intg-tools-libs from codeowners

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/__init__.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/eula.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/recommended_monitors.py
datadog_checks_dev/datadog_checks/dev/tooling/utils.py

Add a new ddev validate subcommand for `eula`. This will quickly validate that EULA files attached to an integration:
* exist
* contain the .pdf extension
* Are of the type "pdf" when opened (detected by the file's magic number)
More validations cross all pieces of an integration. 
While EULAs aren't attached to integrations in this repo, they are used in marketplace integrations. I'd like to add this to the CI in the Azure Pipeline templates if the repo choice is set to marketplace in a followup PR, if/when this is merged and released.

Add initial validations for EULA files

---

couch/manifest.json

`couchdb.couchdb.request_time` is not available for V2.
Adds `couchdb.couchdb.request_time.n` for tile installation for couchdb v2 users.

Use more specific metric_to_check

---

postgres/datadog_checks/postgres/postgres.py
postgres/tests/test_pg_integration.py

Caches version and is_aurora independently.
Alternative to https://github.com/DataDog/integrations-core/pull/7471
We should address https://github.com/DataDog/integrations-core/pull/7471#issuecomment-685357152 on a separate PR

Cache version and is_aurora independently

---

ecs_fargate/README.md

Remove mention of `.json` from `datadog-agent-ecs-fargate.json` as a customer mentioned using IE will download this as a gzip file, which contains the json. Removing to avoid future confusion.
Jira request

Remove .json from ecs fargate docs

---

solr/README.md

Addition of all required param to the example host `solr.d/conf.yaml` given within the documentation.
The current example is deceptive. If it is directly copied and used for`solr.d/conf.yaml,` the integration will not work.
Lines added to the documentation are directly taken from:
https://github.com/DataDog/integrations-core/blob/bb5d227c5e32ce489c501b81b27615783a03892c/solr/datadog_checks/solr/data/conf.yaml.example#L3-L13

[doc] addition to host conf.yaml example

---

datadog_checks_dev/datadog_checks/dev/tooling/configuration/spec.py
datadog_checks_dev/datadog_checks/dev/tooling/configuration/template.py
datadog_checks_dev/tests/tooling/configuration/test_template.py

This 
```yaml
- template: instances/tags
- template: instances/service
- template: instances/global
overrides:
min_collection_interval.value.default: 15
min_collection_interval.value.example: 180
```
Should be
```yaml
- template: instances/default
overrides:
min_collection_interval.value.default: 15
min_collection_interval.value.example: 180
```

Apply overrides recursively to config specs

---

sqlserver/assets/configuration/spec.yaml
sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
sqlserver/datadog_checks/sqlserver/sqlserver.py
sqlserver/tests/common.py
sqlserver/tests/test_sqlserver.py

Added collecting metrics from two additional tables: 
- sys.dm_os_schedulers
- sys.dm_os_tasks
Their class names are SqlOsSchedulers & SqlOsTasks respectively. 
**SqlOsSchedulers** 
- Tagged with session_id
- Metrics: [Link](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-schedulers-transact-sql?view=sql-server-2016)
**SqlOsTasks**
- Tagged with session_id & scheduler_id
- Metrics: [Link](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-tasks-transact-sql?view=sql-server-ver15)
Requested by customer
Issue [AI-559](https://datadoghq.atlassian.net/browse/AI-559)
- These additional metrics are added by default and are **not** via custom metrics. 
- This PR does not fully address the …

Add Scheduler and Task Metrics for SQL Server

---

datadog_checks_base/datadog_checks/base/stubs/_util.py
datadog_checks_base/datadog_checks/base/utils/subprocess_output.py

Add a new `env` parameter to `get_subprocess_output` to be able to specify custom environment variables when spawning subprocesses.
Thanks to DataDog/datadog-agent#5987, it is now possible to use the `env` parameter of `get_subprocess_output` to explicitly set custom environment variables when spawning subprocesses.
This change needs to be reflected in the python code.
This will be used by #7095.

Add the new env parameter to get_subprocess_output

---

nagios/datadog_checks/nagios/nagios.py
nagios/tests/test_nagios.py
nagios/tests/test_unit.py

If a nagios log file suddenly end up missing the check enters an unhealthy state where even if the file re-appears in the future, the agent will not be able to recover from the error.
The PR allows the check to recover.

Fix tailer on missing file

---

snmp/datadog_checks/snmp/data/profiles/chatsworth_pdu.yaml
snmp/datadog_checks/snmp/parsing/metrics.py
snmp/datadog_checks/snmp/parsing/metrics_types.py
snmp/datadog_checks/snmp/snmp.py
snmp/datadog_checks/snmp/utils.py
snmp/tests/test_parsing.py
snmp/tests/test_profiles.py
snmp/tests/test_utils.py

TL;DR: Currently we can’t tag with an external table that have different indexes. There is a possible solution, but we need to provide more info to tell how to match the indexes.
Note: feel free to comment if you think of another way to handle this feature or another syntax/way for indicating `index_transform: "1:8"`
TODO:
The current table have multiple indexes and we want to tag metrics using another table which has a subset of the current table.
> im looking to add the pdu_name tag to metrics from the cpiPduBranchTable — pdu_name comes from cpiPduTable  and both tables contain an index from MAC address. branchtable is indexed by both branch id and PDU MAC
Currently, when fetching metrics from Table1, we don’t handle tagging by an external Table2 with different indexes.
OK cases:
- …

Add `index_transform` to support tagging using another table with different indexes

---

datadog_checks_dev/datadog_checks/dev/tooling/cli.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/config.py
datadog_checks_dev/datadog_checks/dev/tooling/config.py
datadog_checks_dev/datadog_checks/dev/tooling/constants.py
datadog_checks_dev/datadog_checks/dev/tooling/utils.py

This PR adds marketplace to the allowed set of repo choices in ddev
This also fully ties the `-x/here` global ddev option to repo choice, so using `-x` will now make `repo_choice` use whatever the directory name you're in is. 
Eases working on marketplace integrations
Makes `-x` tied to repo_choice. There are a few places in ddev where logic is different depending on the repo choice, like which validations to perform for example. This ensures that no matter what the repo choice is, `-x` will use the logic designated for whichever repo directory you're in. 
This may cause issues if you're using -x in a repo you cloned under a different name than the original

Add marketplace to repo choices and make -x set repo_choice

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/manifest.py

An empty pricing object in the manifest should result in an error, but was passing. This adds a min items count of 1 for this field
I also updated the error message when jsonschema validation fails. Currently the `messages` don't include the actual part of the schema thats failing. 
The output of `ddev validate manifest` now looks like this:
```
test_int/manifest.json... FAILED
pricing:[] is too short
short_description:'' is too short
```
where its currently this:
```
test_int/manifest.json... FAILED
'' is too short
```

Add minItems to pricing and better validation error message

---

oom_kill/README.md

- Correct name of system-probe.yaml
- Fix indentation issue in the system-probe.yaml code snippet, which
resulted from the snippet being embedded in a Markdown list.
Following the documentation as it was led to errors when loading the check config.
I used the docs for the TCP queue length check (https://docs.datadoghq.com/integrations/tcp_queue_length/) as a reference for formatting the code snippet. Though a numbered list would be a bit clearer, I thought it would look awkward to include a list for only two of the three steps in the instructions.

[documentation] Add minor fixes to the OOM kill check documentation.

---

gunicorn/README.md

Edits the Gunicorn README metrics section to inform users that they will need to use DogStatsD in order to collect all integration metrics.
Jira request

Gunicorn README metrics

---

datadog_checks_dev/datadog_checks/dev/tooling/utils.py

Strip the `integrations-` prefix from the repo_choice we autodetect when using the -x/here global ddev option.
The autodetected repo_choice winds up being the dirname, which would be integrations-core/integrations-extras. However the repo_choice throughout the codebase expects these to just be `core` or `extras`
Adding no-changelog since this hasn't been released yet.

Strip integrations- prefix when detecting 'here'

---

kubelet/datadog_checks/kubelet/kubelet.py

In combination with DataDog/datadog-agent#6315 , this change improves the `kubelet` check error reported in the output of `agent status` when the agent cannot properly connect to the kubelet.
In case the agent cannot properly connect to the kubelet, the useful details were in the logs but the output of the `agent status` command gave no clue about the reasons.
Here is an example of the `agent status` output in such a case:
```
$ agent status
[…]
=========
Collector
=========
Running Checks
==============
kubelet (4.1.1)
---------------
Instance ID: kubelet:d884b5186b651429 [ERROR]
Configuration Source: file:/etc/datadog-agent/conf.d/kubelet.d/conf.yaml.default
Total Runs: 1
Service Checks: Last Run: 0, Total: 0
Average …
```

Improve the kubelet check error reporting in the output of `agent status`

---

datadog_checks_dev/setup.py

Add flag to pip install to resolve dependencies
https://github.com/tobgu/pyrsistent/blob/97190f8ad43553603a95a83361d4c0fe02e86970/CHANGES.txt#L4-L5
Dropped py2 support resulting in CI failing https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=23293&view=logs&j=910f82a4-622d-5ace-f877-8b75c045486c&t=b8a76c45-01d6-50b1-e11b-d9fedb0dbe38&l=230
Use https://github.com/DataDog/integrations-core/pull/7545 when issue is resolved via https://github.com/tobgu/pyrsistent/pull/206

Pin transient dependency pyrsistent to < 0.17.0

---

process/datadog_checks/process/process.py

This PR prevents uncaught psutil exceptions from changing unfound processes from creating an Error state in the check as opposed to the warning state.
This is blocking upgrade to the newer version of the agent rpm and utilizing some universal tagging functionality, since some of our existing process checks will now generate Error states instead of Warning states.
Live usage example from our agent
With the fix above:
```
Instance ID: process:dummy-target-process:d33e96bb37c78a9d [WARNING]
Configuration Source: file:/etc/datadog-agent/conf.d/process.yaml
Total Runs: 8
Metric Samples: Last Run: 1, Total: 8
Service Checks: Last Run: 1, Total: 8
Average Execution Time : 13ms
Last Execution Date : 2020-09-01 14:20:06.000000 EDT
Last Successful Execution Date : …
```

Handle unfound processes in no matching PIDs logs

---

docs/developer/tutorials/snmp/profile-format.md

Add doc for `index_transform`
Add `index_transform` to support tagging using another table with different indexes #7489
https://github.com/DataDog/integrations-core/pull/7489

Add doc for `index_transform`

---

postgres/datadog_checks/postgres/postgres.py

Remove extra comma in PostgreSQL connection string when using ident authentication.
I was getting the following error:
```
Jul 27 22:56:29 HOST agent[13961]: 2020-07-27 22:56:29 CEST | CORE | ERROR | (pkg/collector/runner/runner.go:292 in work) |
Error running check postgres: [
{
"message": "FATAL:  database \"mydb,\" does not exist\n",
"traceback": "Traceback (most recent call last):\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py\", line 841, in run\n    self.check(instance)\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/postgres/postgres.py\", line 431, in check\n    )\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/postgres/postgres.py\", line 415, in check\n    # …
```

Fix PostgreSQL connection string when using ident authentication

---

active_directory/CHANGELOG.md
datadog_checks_dev/datadog_checks/dev/tooling/commands/agent/__init__.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/agent/changelog.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/agent/common.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/agent/integrations_changelog.py
datadog_checks_dev/datadog_checks/dev/tooling/constants.py
datadog_checks_dev/datadog_checks/dev/tooling/git.py

Add command to update integration changelog with Agent version
Related PRs:
- Add agent versions to integrations changelog https://github.com/DataDog/integrations-core/pull/7519
- Add `ddev agent integrations-changelog` to post release actions #7520
Sometimes we know that a feature has been release with integration version X and we want to know (easily) what was the first version of the agent containing that feature.
Does not interfere with existing `ddev release make`

Add command to add Agent version to integrations CHANGELOG.md

---

docs/developer/process/agent-release/post-release.md

Add `ddev agent integrations-changelog` to post release actions
Merge after https://github.com/DataDog/integrations-core/pull/7518
https://github.com/DataDog/integrations-core/pull/7518

Add `ddev agent integrations-changelog` to post release actions

---

linux_proc_extras/datadog_checks/linux_proc_extras/data/conf.yaml.example
linux_proc_extras/datadog_checks/linux_proc_extras/linux_proc_extras.py
linux_proc_extras/tests/common.py
linux_proc_extras/tests/test_integration.py

Puts #7166 metrics behind config option that is disabled by default.

Put interrupt metrics behind a config option

---

ibm_mq/datadog_checks/ibm_mq/connection.py
ibm_mq/tests/conftest.py
ibm_mq/tests/test_ibm_mq_unit.py

Try normal connection before SSL connection
```
```
Details: https://github.com/dsuch/pymqi/issues/208

Try normal connection before SSL connection

---

pyproject.toml

Ignore . prefixed folders for isort
Needed for https://github.com/PyCQA/isort/pull/1473

Ignore . prefixed folders for isort

---

ibm_mq/datadog_checks/ibm_mq/ibm_mq.py
ibm_mq/tests/test_ibm_mq_unit.py

Raise exception on connection error
By raising an exception, the issue will be visible when using `agent status` command.
Currently, user only see warning logs.

Raise exception on connection error

---

datadog_checks_base/datadog_checks/base/stubs/aggregator.py

Metrics name are also normalized here https://github.com/DataDog/integrations-core/blob/a3de7a27db9e29e138ba3ab9e27f3d0b0f45afc8/datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py#L201-L211
So we need to normalize them when asserting with metadata
Needed to `assert_metrics_using_metadata` for MarkLogic https://github.com/DataDog/integrations-core/pull/6524

Normalize metric when asserting with metadata

---

clickhouse/assets/configuration/spec.yaml
clickhouse/datadog_checks/clickhouse/data/conf.yaml.example
datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/db.yaml
mysql/assets/configuration/spec.yaml
mysql/datadog_checks/mysql/data/conf.yaml.example
vertica/datadog_checks/vertica/data/conf.yaml.example

Apply db template to integrations with the spec.yaml using the custom query options

Use database config template in existing specs

---

datadog_checks_base/datadog_checks/base/checks/openmetrics/mixins.py
datadog_checks_base/tests/test_openmetrics.py

- Remove the leading dot in metric names when the namespace is empty (e.g `.process.vm.bytes` -> `process.vm.bytes`)
- Users might want to pass an empty namespace to the `openmetrics` check to ease the migration from Prometheus (by having the same metric names in DD)

Better metric names handling when the namespace is empty

---

vsphere/assets/dashboards/vsphere_overview.json

The `vsphere.*.count` metrics are count type metrics which defaults to time aggregation. That means that when zooming out, the value of the graph will increase as a summation rollup will be performed.
Such a metric has to be a count because of how it's incremented on the agent, but the query value widgets used in the dash should make the correct query. Otherwise, we see the value bumping every now and then and the wrong value being displayed when looking at a more than 4hours timewindow.

Fix vsphere dash query value widgets

---

docs/developer/ddev/configuration.md

Update github to trello mapping link

Update github to trello mapping link

---

vsphere/datadog_checks/vsphere/vsphere.py

Adding hostname to vsphere debug metrics
From @FlorianVeaux 
```
Some vSphere debug metrics do not explicitly define an hostname. For regular check this is not an issue as an unset hostname means "use the local agent hostname".
But for vsphere we explicitly set "empty_default_hostname: true" in the config. 
```

Add hostname to vsphere debug metrics

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/init_config/db.yaml

There is no standard `metric_prefix` option, only in older custom query logic (deprecated)

Fix init_config/db config spec template

---

vsphere/datadog_checks/vsphere/api.py
vsphere/datadog_checks/vsphere/vsphere.py
vsphere/tests/mocked_api.py
vsphere/tests/test_check.py

Use server time
Local time might differ from server time.
> PerfQuerySpec.startTime* | xsd:dateTime | The server time from which to obtain counters. If not specified, defaults to the first available counter. When a startTime is specified, the returned samples do not include the sample at startTime.
https://www.vmware.com/support/developer/vc-sdk/visdk41pubs/ApiReference/vim.PerformanceManager.QuerySpec.html
With this PR:
```
vsphere (5.4.0)
---------------
Instance ID: vsphere:9ee463a9fc5cb748 [OK]
Configuration Source: file:/etc/datadog-agent/conf.d/vsphere.d/vsphere.yaml
Total Runs: 1
Metric Samples: Last Run: 1,649, Total: 1,649
Service Checks: Last Run: 1, Total: 1
Average Execution Time : 15.126s
Last Execution Date : 2020-09-16 10:59:06.000000 UTC
Last …
```

Use server time to compute startTime

---

ntp/README.md

Updates the docs to reflect that the default cloud provider is now based on the one that is detected. Related change in agent-core: https://github.com/DataDog/datadog-agent/pull/6279

Updated docs to reflect cloud provider detection for NTP check

---

.azure-pipelines/templates/run-validations.yml
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/manifest.py
datadog_checks_dev/datadog_checks/dev/tooling/git.py
docs/developer/meta/ci.md

Updates the `ddev validate manifest` command to:
* remove the `-i` option
* remove the `repo_url` option
and switch the method used to detect if a manifest file changed to use a local git diff instead of the github api.
Using local git is much faster (and less error prone) than reaching out to the github API for each integration's manifest content. Locally the runtime of the command went from ~45 seconds down to ~3 seconds. 
Additionally this lets us work with private integration repos since the detection is all done locally. 
This comes with the drawback of no longer supporting the `fix` flag for this specific part of the validation.

Use `git diff` instead of GitHub's API to detect if manifest fields changed during validation

---

cacti/tests/common.py

Fix cacti test
Failing due to:
```
2020-09-16T22:10:44.7465383Z Package libpython-dev is not available, but is referred to by another package.
2020-09-16T22:10:44.7466054Z This may mean that the package is missing, has been obsoleted, or
2020-09-16T22:10:44.7466542Z is only available from another source
2020-09-16T22:10:44.7466973Z However the following packages replace it:
2020-09-16T22:10:44.7467604Z   libpython2-dev
2020-09-16T22:10:44.7467971Z 
2020-09-16T22:10:44.7468608Z E: Package 'libpython-dev' has no installation candidate
```
https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=24299&view=logs&jobId=9f1de384-230b-528c-4a39-e126e25236ca&j=9f1de384-230b-528c-4a39-e126e25236ca&t=715013fb-940a-5df6-f53e-cd98dc790235

Fix tests by installing libpython2-dev instead of libpython-dev

---

vsphere/datadog_checks/vsphere/api.py

Better trace log
It's a very long multiline log, it will make it easier to know where the query and response start/end.

Better trace log

---

snowflake/requirements.in

Add note about snowflake-connector-python version cap
For future reference.

Add note for snowflake-connector-python version cap

---

kube_scheduler/assets/configuration/spec.yaml
kube_scheduler/datadog_checks/kube_scheduler/data/auto_conf.yaml
kube_scheduler/datadog_checks/kube_scheduler/data/conf.yaml.example
kube_scheduler/manifest.json
kube_scheduler/setup.py

Updates config spec for kube_scheduler
See https://github.com/DataDog/integrations-core/issues/7605

Add kube_scheduler config spec

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/manifest.py

This recent PR - https://github.com/DataDog/integrations-core/pull/7599/files changed the way the detection of manifest changes occur, from using the github api to using a git diff local command. 
This change didn't take into account new integrations, as once they're `git add`-ed, they'll have a changed manifest against master that include the fields we're checking for, which causes the manifest validation to fail.
This PR takes into account new integrations by checking for the `new file` string in the git diff output and skips the change validation if present. It logs an info level log stating that we have detected a new integration and are skipping this piece of validation.

Fix changed manifest validation for new integrations

---

snowflake/README.md

Add note check not available for MacOS in Agent 6 using Python 2
Motivation and details: https://github.com/DataDog/datadog-agent/pull/6391

Add note that check is not available for MacOS in Agent 6 using Python 2

---

datadog_checks_dev/datadog_checks/dev/tooling/utils.py

Cleanup for https://github.com/DataDog/integrations-core/pull/7473
When the `terms.eula` key is missing, `<None>.split()` was called resulting in an `AttributeError`:
```console
$ ddev -m validate eula
Validating all EULA files...
File "/Users/florimond.manca/go/src/github.com/DataDog/marketplace/venv/bin/ddev", line 11, in <module>
load_entry_point('datadog-checks-dev', 'console_scripts', 'ddev')()
File "/Users/florimond.manca/go/src/github.com/DataDog/marketplace/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/Users/florimond.manca/go/src/github.com/DataDog/marketplace/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File …
```

Handle missing "eula" key in EULA validation

---

datadog_checks_base/tests/conftest.py
datadog_checks_base/tests/test_http.py
docs/developer/.snippets/links.txt
docs/developer/base/http.md

Cleanup for #7585 
A few changes to mark Unix Socket support in `RequestsWrapper` as Unix-only (or rather, not supported on Windows).
- Explicitly skip integration test for this reason.
- Update docs.
Also fixed the missing link to `requests-unixsocket`.
Note that we don't need to change anything to our usage of `requests-unixsocket`, since importing that library and mounting the adapter works on Windows (a user would only see a syscall failure when effectively trying to make a `unix://` request). This means when Python adds support we should automatically support UDS on Windows.
Even though Windows added `AF_UNIX` support in Windows 10, Python doesn't have support yet, and this won't be in 3.9 either, see https://bugs.python.org/issue33408
Will log a ticket to track adding support on …

Mark Unix Socket support as Unix-only

---

disk/assets/configuration/spec.yaml
disk/datadog_checks/disk/data/conf.yaml.default
disk/datadog_checks/disk/disk.py

Refactor for an upcoming PR that will introduce a new default

Add options for global exclusion patterns

---

disk/assets/configuration/spec.yaml
disk/datadog_checks/disk/data/conf.yaml.default
disk/datadog_checks/disk/disk.py
disk/tests/test_filter.py
disk/tests/test_unit.py

- https://github.com/DataDog/datadog-agent/issues/1961
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-1049
- https://github.com/DataDog/integrations-core/issues/2492

Ignore `/proc/sys/fs/binfmt_misc` by default

---

datadog_checks_base/datadog_checks/base/checks/prometheus/mixins.py
datadog_checks_base/datadog_checks/base/utils/http.py
datadog_checks_base/tests/test_http.py

Cleanup #7512
Inspect URL schemes so we don't emit a warning if using `verify: false` but an `http://` request is being made.
When requesting an `http://` (plaintext) endpoint, whether TLS verification is disabled is irrelevant. Besides the warning we're logging is explicitly for "an HTTPS request", so I assume this was an oversight.

Do not emit insecure warning log for HTTP requests

---

network/datadog_checks/network/network.py

Running the network check in a container (https://github.com/DataDog/integrations-core/pull/7095) does not work as the `procfs_path` value is not retrieved correctly, always defaulting to `/proc`.

Fix procfs_path retrieval in network check

---

datadog_checks_base/datadog_checks/base/stubs/aggregator.py

Allow `monotonic_count` metrics to match expected type of `count` when comparing collected metrics with `metadata.csv`.
`metadata.csv` cannot contain `monotonic_count` (only `count` is allowed AFAIK), so when a `monotonic_count` metric is submitted and is defined in `metadata.csv`, `assert_metrics_using_metadata()` fails.
Example for Azure IoT Edge (currently making #7465 fail):
```console
tests/test_check.py:58: in test_check
aggregator.assert_metrics_using_metadata(get_metadata_metrics())
../datadog_checks_base/datadog_checks/base/stubs/aggregator.py:358: in assert_metrics_using_metadata
assert not errors, "Metadata assertion errors using metadata.csv:" + "\n\t- ".join([''] + sorted(errors))
E   AssertionError: Metadata assertion errors using metadata.csv:
E       - Expect …
```

Normalize count metric type in `assert_metrics_using_metadata()`

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/config.py

Add an actionable hint to the 'needs to be synced' error message.
I did't know what to do when I got this error.

Better error message when config example not in sync

---

ibm_db2/datadog_checks/ibm_db2/ibm_db2.py

Updates the default port in the integration to 50000, to match the default port in the [conf.yaml](https://github.com/DataDog/integrations-core/blob/3ebbde03483312601db9395f8044bd02fc3a8344/ibm_db2/datadog_checks/ibm_db2/data/conf.yaml.example#L38) and in the [db2 docs](https://www.ibm.com/support/pages/db2-db2-server-tcpip-port-numbers) 

Fix default port value

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/__init__.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/rc_build_cards_updater.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/update_rc_links.py

- Adds the MacOS card to the list of cards to update when there's a new RC.
- Adds a separate command to call `update_cards` directly.
- New MacOS card.

[ddev] Trello update RC link in MacOS card as well

---

elastic/datadog_checks/elastic/elastic.py

In cases of missing data for elastic checks, this adds more context to which index it applies to.

Extra debug for missing metrics

---

postgres/datadog_checks/postgres/version_utils.py

On postgres servers that are not aurora it is giving the following error in the log: "ERROR: function aurora_version () does not exist at character 8". From now on it will only be checked if there is a function, if there is, it is understood that it is an aurora.
Because my Postgres servers (which are not aurora) in production have this error in the log very often
No aurora_version function value was used, so I think that just seeing if it exists in pg_proc is enough

When postgres is not an aurora it is giving error in the execution of agent

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/__init__.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/http.py
datadog_checks_dev/datadog_checks/dev/tooling/utils.py

Adding a validator that checks the following:
- if using the requests library instead of HTTP wrapper library. 
- if using HTTP wrapper library for the integration, then the config spec uses the `instances/http` template. 
The validator outputs a warning if any of the two cases above fail.
Can be executed using `ddev validate http`
Example output: 
The team has updated to use http wrapper instead of requests library, and future integrations should adhere to the standard.
In the original ticket, the second case should be "if using http wrapper, http specs are included in the config spec", however I felt that it would be more efficient to just check for the http template in the `spec.yaml` file. 
Also, I added an optional parameter to `get_check_files()` in `util.py` to skip test files from …

Adding HTTP wrapper class validator

---

disk/datadog_checks/disk/disk.py

- Fix deprecation warnings being utterly broken.
- Fix passing empty lists which were evaluated falsey in the `or` chain.

Fix config option rename refactor

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/http.py

Including instances/openmetrics and init_config/openmetrics to check for when checking for http template in spec.yaml files.
Not sure if I should try for a more optimized way of checking for the http template if new templates with http are added?

adding instances/openmetrics and init_config/openmetrics for http template check

---

.azure-pipelines/scripts/mapreduce/linux/50_increase_docker_memory.sh
datadog_checks_tests_helper/datadog_test_libs/utils/mock_dns.py
mapreduce/tests/common.py
mapreduce/tests/conftest.py
mapreduce/tests/test_mapreduce_integration_e2e.py

Two previous PRs added functionality to mock hostname references for E2E testing: #7106 and #7343 .
The latter PR was merged first and included code borrowed from #7106.  When #7106 was merged it also made some changes to #7343 functionality which duplicated code.
This PR cleans up the duplicate code, references the library function from #7106, and removes a now unused function call `mock_e2e_agent` to avoid future confusion.

Cleanup mock_dns library calls

---

docs/developer/.scripts/33_render_status.py

There are integrations like cilium that even though are not tile only do not have a log section on the config file.
This PR fixes logs integration status report to account for that

Fix log reporting

---

haproxy/datadog_checks/haproxy/legacy/const.py
haproxy/datadog_checks/haproxy/legacy/haproxy.py
haproxy/tests/legacy/common.py

Submit `bin` and `bout` information as gauge in addition to submitting those as rate for the legacy haproxy check.
https://github.com/DataDog/integrations-core/issues/7691
These metrics are already sent by the prometheus version of the haproxy check

Send bytes.in/out.total metrics with legacy check

---

network/datadog_checks/network/network.py

Collect cx state metrics on BSD platform (OSX)
AGENT-4978

Collect connection state metrics on BSD/OSX

---

wmi_check/datadog_checks/wmi_check/wmi_check.py
wmi_check/tests/test_wmi_check.py

Fix missing tags from `tag_by`
Used to be passed to `self._get_running_wmi_sampler` but has changed in 
https://github.com/DataDog/integrations-core/pull/6325/files#diff-5616a77c5830301f9247aa423b0158edL59
AGENT-5007

Fix missing tags from tag_by

---

envoy/datadog_checks/envoy/parser.py
envoy/tests/fixtures/multiple_services

Resolves #7686 
A subsequent PR will add the new metrics

Properly handle a parsing edge case

---

varnish/datadog_checks/varnish/varnish.py
varnish/tests/fixtures/stats_output_json_6.5
varnish/tests/test_unit.py

Fixes parsing of the varnishstat 6.5 JSON output.
The JSON structure returned by `varnishstat -j` changed in version 6.5.
Notably, all counters have been moved under the "counters" key.
https://github.com/varnishcache/varnish-cache/blob/6.5/doc/changes.rst#varnish-cache-650-2020-09-15

varnish: fix parsing of varnishstat 6.5 JSON output

---

vsphere/assets/configuration/spec.yaml
vsphere/datadog_checks/vsphere/data/conf.yaml.example

The `empty_default_hostname` default config was removed in https://github.com/DataDog/integrations-core/pull/7537
This PR re-adds it at the top of the config file.

Re-add empty_default_hostname to configuration by default

---

pgbouncer/assets/configuration/spec.yaml
pgbouncer/datadog_checks/pgbouncer/data/conf.yaml.example

In reaction to a support case.
Will log a ticket in our backlog to review and add support for automatically quoting passwords in `password` option, and possibly `database_url` too.
Goal of this PR is solely to clarify _current_ expectations and abilities of the check.

Clarify password percent-encoding expectations

---

lighttpd/README.md
lighttpd/assets/configuration/spec.yaml
lighttpd/datadog_checks/lighttpd/data/conf.yaml.example
lighttpd/manifest.json
lighttpd/setup.py
lighttpd/tests/conftest.py
lighttpd/tests/docker/noauth/docker-compose.yaml
lighttpd/tests/docker/noauth/lighttpd.conf

Add support for lighttpd log integration
- [JIRA](https://datadoghq.atlassian.net/browse/AI-743?atlOrigin=eyJpIjoiOTcwNTRlMGZiMjE4NGY3NWI5YTk0Njk4OTViZDI2NzQiLCJwIjoiaiJ9)
- [logs-backend PR](https://github.com/DataDog/logs-backend/pull/12575)
- [web-ui](https://github.com/DataDog/web-ui/pull/21116)

Add lighttpd logs

---

snowflake/assets/configuration/spec.yaml
snowflake/datadog_checks/snowflake/check.py
snowflake/datadog_checks/snowflake/config.py
snowflake/datadog_checks/snowflake/data/conf.yaml.example
snowflake/tests/test_unit.py

This PR adds OAuth as per beta user feedback.
This PR also fixes connection issue because the snowflake python connector's connection must be explicitly closed. see `snowflakedb/snowflake-connector-python/issues/42`

Add OAuth authentication option and use new connection on check run

---

sqlserver/assets/configuration/spec.yaml
sqlserver/datadog_checks/sqlserver/connection.py
sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
sqlserver/datadog_checks/sqlserver/metrics.py
sqlserver/datadog_checks/sqlserver/sqlserver.py
sqlserver/metadata.csv
sqlserver/tests/common.py
sqlserver/tests/compose/Dockerfile
sqlserver/tests/compose/docker-compose.yaml
sqlserver/tests/compose/entrypoint.sh
sqlserver/tests/compose/setup.sh
sqlserver/tests/compose/setup.sql
sqlserver/tests/test_sqlserver.py

Expand support of SQL Server check to additional metrics.
- Expanded metrics from the `sys.dm_os_performance_counters` table, and clarify these are *instance* level metrics, vs *database* specific ones
- New database-specific metrics from the `sys.database_files` and `sys.databases` tables
Additionally enhances the test config to add an example database for better metrics collection.

Support additional performance metrics 

---

docs/developer/ddev/configuration.md

`ddev release trello testable` also needs `read:org` permission to get the team composition

Fix token permissions documentation

---

mongo/datadog_checks/mongo/mongo.py
mongo/datadog_checks/mongo/utils.py
mongo/tests/test_unit.py

Port 27017 is already the default no matter what in mongo so there's no harm in removing it in any use case.
This extra logic was creating an issue with the `mongo+srv://` connection scheme. This scheme takes a hostname that resolves DNS information. The port should never be included in the URI, otherwise we see
```
pymongo.errors.InvalidURI: mongodb+srv:// URIs must not include a port number
Deprecated constructor API
```
Also, a legacy (and rare) use case is reintroduced. When using x509 authentication, it is possible to login to mongo simply using certificate files. These certificate files contain a username in them.
Priori to v3.4 of MongoDB, the URI needed to contain the username in the URI like so `mongodb://username@host/db` but this is not required anymore.
Currently the building …

Fix building of the connection string

---

fluentd/README.md

Changes the plugin link from rubydoc to a datadog github repo, so customers aren't mislead into thinking we don't own it

DOCS-1268 fluentd link update

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/manifest.py
datadog_checks_dev/datadog_checks/dev/tooling/utils.py

Adds validation for the `assets/metrics_metadata` field in the manifest.json.
This field is still **optional** to allow integration without a metadata.csv file. 
The new validation checks two things:
- If a metadata file is specified, it needs to exist on the filesystem.
- If a metadata file is found at the root called "metadata.csv", it needs to be defined in the manifest.json file
Note: No test as we don't have any testing setup for validation. This is a task on its own.

Validate metrics_metadata in manifest.json

---

clickhouse/datadog_checks/clickhouse/queries.py
clickhouse/tests/test_unit.py
datadog_checks_base/datadog_checks/base/utils/db/core.py
datadog_checks_base/tests/test_db.py
oracle/datadog_checks/oracle/queries.py
oracle/tests/test_metrics.py
proxysql/datadog_checks/proxysql/queries.py
snowflake/datadog_checks/snowflake/queries.py
snowflake/tests/test_snowflake.py

Database checks pass instances of 'Query' directly to the QueryManager for them to be 'compiled' and used.
The QueryManager modifies those 'Query' instances in-place which means that multiple instances of a same check will share the same references to those 'Query' objects.
It wouldn't be a problem if those Query did not contain references to bounded methods of the check.
Impact:
Any check currently using the QueryManager with multiple configuration instances will see metrics that should be submitted with one instance being submitted with another one. This is transparent to users, metrics will be sent to Datadog app anyway.
If the check is using autodiscovery, configuration instances are generated dynamically. Instances can be unscheduled and that leads to integrations trying to report …

QueryManager - Prevent queries leaking between check instances

---

datadog_checks_base/datadog_checks/base/utils/containers.py
datadog_checks_base/tests/test_utils.py

* Update `hash_mutable` to allow `hash_mutable(['test', None])` to succeed, whereas right now it fails with a `TypeError` on Python 3:
```console
>>> from datadog_checks.base.utils.containers import hash_mutable
>>> hash_mutable(['test', None])
File "<stdin>", line 1, in <module>
File "/Users/florimond.manca/go/src/github.com/DataDog/integrations-core/datadog_checks_base/datadog_checks/base/utils/containers.py", line 25, in hash_mutable
return hash(freeze(m))
File "/Users/florimond.manca/go/src/github.com/DataDog/integrations-core/datadog_checks_base/datadog_checks/base/utils/containers.py", line 13, in freeze
return tuple(sorted(freeze(e) for e in o))
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```
* Add unit tests for this …

Add support for hashing sequences that contain None in `hash_mutable` on Python 3

---

datadog_checks_base/datadog_checks/base/utils/containers.py
datadog_checks_base/tests/test_utils.py

Reverts DataDog/integrations-core#7763
**Motivation**
`hash` can't be trusted, need a different approach:
```python
>>> hash(-1)
-2
>>> hash(-2)
-2
```

Revert "Add support for hashing sequences that contain None in `hash_mutable` on Python 3"

---

kubernetes_state/datadog_checks/kubernetes_state/kubernetes_state.py
kubernetes_state/tests/test_kubernetes_state.py

This change respects the pod_labels from label_joins when emitting the container status metrics.
This is similar to how `SAMPLE_LABELS` are processes for other resources in the check.
Users rely on label_join to associate labels from the `kube_pod_labels` with other `kube_pod_*` metrics. For example, we rely on various labels to help us route alerts to the correct team for metrics within monitors.
Nope.

add labels from `self.SAMPLE_LABELS` to container status metrics

---

clickhouse/datadog_checks/clickhouse/data/conf.yaml.example
datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/db.yaml
mysql/datadog_checks/mysql/data/conf.yaml.example
snowflake/datadog_checks/snowflake/data/conf.yaml.example
vertica/datadog_checks/vertica/data/conf.yaml.example

Fix `custom_queries` description for database instances. It removes `clickhouse` reference.

Fix custom_queries description

---

http_check/assets/configuration/spec.yaml
http_check/datadog_checks/http_check/data/conf.yaml.example

In https://github.com/DataDog/integrations-core/pull/7008/files#diff-d1d3b592cf2ef4b7512bec5a80f322f0ce4391a524574c9e67693d840adc26bdR31 we updated the limit on the check side. Since, the backend has updated the intake limit to 500 so let's update the documentation to reflect that https://docs.datadoghq.com/api/v1/service-checks/

Update documentation about service check message limit

---

datadog_checks_base/datadog_checks/base/utils/containers.py
datadog_checks_base/tests/test_utils.py

Alternative to #7763, refs https://github.com/DataDog/integrations-core/pull/7752#issuecomment-706207004
Update `hash_mutable` to allow `hash_mutable(['test', None])`, whereas right now it fails with a `TypeError` on Python 3:
```console
>>> from datadog_checks.base.utils.containers import hash_mutable
>>> hash_mutable(['test', None])
File "<stdin>", line 1, in <module>
File "/Users/florimond.manca/go/src/github.com/DataDog/integrations-core/datadog_checks_base/datadog_checks/base/utils/containers.py", line 25, in hash_mutable
return hash(freeze(m))
File "/Users/florimond.manca/go/src/github.com/DataDog/integrations-core/datadog_checks_base/datadog_checks/base/utils/containers.py", line 13, in freeze
return tuple(sorted(freeze(e) for e in o))
TypeError: …
```

Add support for hashing sequences containing None on Python 3

---

snmp/datadog_checks/snmp/data/profiles/_cisco-generic.yaml
snmp/tests/test_profiles.py

Adding a tag to avoid ambiguity in metrics concerning power supply state of stacked switches.

Adding tag ciscoEnvMonSupplyStatusDescr to disambiguate metric

---

statsd/manifest.json

I forgot to add the logs source in https://github.com/DataDog/integrations-core/pull/7773, this PR integrates the missing change.
Add log support for statsd

Add source logs in statsd manifest

---

nginx_ingress_controller/datadog_checks/nginx_ingress_controller/nginx_ingress_controller.py
nginx_ingress_controller/metadata.csv
nginx_ingress_controller/tests/test_nginx_ingress_controller.py

Currently the metric being collected `nginx_ingress_controller_success` is described as `Cumulative number of Ingress controller reload operations`
https://github.com/kubernetes/ingress-nginx/blob/master/internal/ingress/metric/collectors/controller.go#L98
Changing the metric to use `nginx_ingress_controller_config_last_reload_successful` is described as `Whether the last configuration reload attempt was successful`
https://github.com/kubernetes/ingress-nginx/blob/master/internal/ingress/metric/collectors/controller.go#L84
The reason for this is because measuring and alerting on `Cumulative number of Ingress controller reload operations` is useless and not helpful to the end user monitoring ingress controller.  What is helpful is the gauge metric …

fix which prometheus metric is used for reload.success to properly monitor nginx config reload errors

---

mongo/tests/compose/scripts/init-shard01.js
mongo/tests/conftest.py
mongo/tox.ini

Make sure that the container `shard01a` will be the pirmary node. It seems like priori to v4.1 of mongo, the node on which the replica set is initialized is always the primary.
Since v4.1 (or before), the primary seems to be picked on another criteria. This PR sets a higher priority to `shard01a` so that we're sure that this one will become the primary eventually.
The `create_shard_user` method is also moved in a `WaitFor` so that it is retried until `shard01a` gets elected as primary.

Fix test environment setup with mongo 4.1

---

mongo/assets/configuration/spec.yaml
mongo/datadog_checks/mongo/common.py
mongo/datadog_checks/mongo/data/conf.yaml.example
mongo/datadog_checks/mongo/mongo.py
mongo/tests/test_integration.py

Prevents custom queries from being run on secondaries by default. To enable them, users now have to set `run_on_secondary: true` in each query.
1. In most cases it doesn't make sense to run queries on something else than a `mongos` if using shards or the `primary` if using a single replica set (or on a standalone). But there are rare cases where it make senses (like collecting stats from the 'local' database, different on each node) so the user is responsible for configuring the check correctly. For example, when using shards, check instances connected to the primary of a shard will still execute the queries as instructed by the configuration.
2. In replica set, custom queries should only be run once and preferably on the primary. But because a mongod node can change state, the user …

Stop collecting custom queries from secondaries by default

---

kyototycoon/README.md
kyototycoon/assets/configuration/spec.yaml
kyototycoon/datadog_checks/kyototycoon/data/conf.yaml.example
kyototycoon/manifest.json
kyototycoon/tests/compose/compose_kyototycoon.yaml
kyototycoon/tests/conftest.py

Add logs support for the `kyototycoon` integration.
1. Let users know how to configure the integration to collect logs.
2. Allow sending logs from a `ddev` env, eg for testing.
Follow-ups (that this PR doesn't require nor block, but just for reference):
- Add log parser in `logs-backend`.
- Link metrics and logs `web-ui` (similar to https://github.com/DataDog/web-ui/pull/20394).

Add logs support

---

datadog_checks_base/datadog_checks/base/utils/http.py
datadog_checks_base/tests/test_http.py

After refactoring I missed the fact that the type for the exp timestamp is no longer int.

[dcos-auth] Fix bug with exp timestamp being non-int

---

jboss_wildfly/assets/configuration/spec.yaml
jboss_wildfly/datadog_checks/jboss_wildfly/data/conf.yaml.example

During addition of config specs in this PR https://github.com/DataDog/integrations-core/pull/6225 the `custom_jar_paths` option was omitted by accident

Add missing custom_jar_paths option

---

postgres/datadog_checks/postgres/config.py
postgres/datadog_checks/postgres/statements.py

Change default behavior to include only obfuscated plans & statements:
* put the obfuscated plan in `db.plan` 
* new config `collect_exec_plan_debug` to enable `db.debug` fields, which will contain the raw original statement

dbm do optional debug for postgres

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py

```
$ ddev -e  env start zabbix py38
`integrations-extras` directory `/workspace/integrations-extras` does not exist, defaulting to the current location.
Be sure to run environment with --dev for extras or custom integrations.
Setting up environment `py38`...
```
Since extras and custom integrations are not bundled within the agent image we use, running the check will throw an error due to integration module not found.

Add warning when running environment without dev flag for non-core integrations

---

.github/workflows/release-hash-check.yml

The release-hash-check job stopped working to detect hash mismatch. The PR reference may not be up to date.
Previous job was working here: https://github.com/FlorianVeaux/integrations-core/pull/6/checks?check_run_id=919053005 so I'm not so sure what's the reason.
Now the job explicitly merges master into the current branch so that files are guaranteed to be updated.
Re-running the job in this PR did not catch the signature error: https://github.com/DataDog/integrations-core/pull/7799

Fix release-hash-check

---

datadog_checks_base/datadog_checks/base/checks/win/winpdh_base.py
datadog_checks_base/tox.ini

Follow-up to #7752 
Add and enforce type checking on `winpdh_base.py`, so that bugs that can be caught by mypy like the one fixed by #7752 don't creep up again in the future.
Type safety

Enforce type checking on winpdh_base.py

---

nginx/assets/monitors/4xx.json
nginx/assets/monitors/5xx.json
nginx/assets/monitors/upstream_peer_fails.json
scylla/assets/monitors/instance_down.json

`renotify_interval` should be int and not a string. This is causing ES 7 migration to fail on staging
ES 7 migration for gov cloud for recommended monitors 
https://datadoghq.atlassian.net/browse/MA-1641

[Recommended Monitors] Fix renotify_interval 

---

datadog_checks_base/datadog_checks/base/checks/base.py
datadog_checks_base/datadog_checks/base/utils/tls.py
datadog_checks_base/tests/test_tls.py

Adds a new method to the base class `AgentCheck.get_tls_context(self, refresh=False)`
This helper method can be used by checks to create an `SSLContext` instance in a reliable way using generic configuration.
The default fields in the configuration are the following ones:
configuration | defaults | description
------------ | ------------- | -----
tls_verify | True | Whether or not the SSLContext instance will verify the validity of the certificates. If false, the context will still be used to establish a SSL/TLS connection but in an insecure way.
tls_ca_cert | None | Path to a file or a directory of certificate files in PEM format
tls_cert | None | Path to a certificate file
tls_private_key | None | Optional key for the certificate file. If missing, the key is expected to be in the same …

Add a TLSContextWrapper to the base class

---

mongo/datadog_checks/mongo/common.py
mongo/datadog_checks/mongo/mongo.py
mongo/tests/fixtures/getCmdLineOpts-configsvr-primary
mongo/tests/fixtures/getCmdLineOpts-configsvr-secondary
mongo/tests/fixtures/replSetGetStatus-configsvr-primary
mongo/tests/fixtures/replSetGetStatus-configsvr-secondary
mongo/tests/test_integration.py

Useful to differentiate a `shardSvr` (ie a member of a shard containing data), from a `configSvr` (i.e storing the cluster configuration) from a `mongos`

Add the shard cluster role as a tag

---

mongo/datadog_checks/mongo/metrics.py

A warning was raised as `jumbo_chunks` was not a recognized option

Fix warning when adding 'jumbo_chunks' metrics

---

mongo/datadog_checks/mongo/collectors/replica.py
mongo/metadata.csv
mongo/tests/fixtures/replSetGetStatus-replica-primary
mongo/tests/fixtures/replSetGetStatus-replica-primary-in-shard
mongo/tests/results/metrics-replset-lag-from-primary-in-shard.json
mongo/tests/results/metrics-replset-lag-from-primary.json
mongo/tests/test_integration.py

Adds a new metric called `mongodb.replset.optime_lag` (open to better naming suggestions).
This metric is a replacement for `mongodb.replset.replicationlag` currently submitted by the mongo integration but both continue to be collected.
In mongo, all writes go to the primary. The operations are stored in an "oplog" and each secondary reads from this oplog and applies the same operations. Each member also stores where it's at in the oplog and stores the timestamp of the latest operation applied. This timestamp is the 'optime'
When fetching the optime from the secondaries, it is possible to find the secondary optime ahead of the primary optime. This does not mean that the secondary is ahead of the primary, rather than the secondary hasn't recently received an update from the primary with …

New replication lag metric collected from the primary

---

docs/developer/.snippets/links.txt
docs/developer/guidelines/style.md

Add some more hints on configuring `mypy` for partial type checking, in this case configuring `mypy` so that it only type checks a few select files instead of the entire `datadog_checks/` directory.
More helpful developer docs

Add note on configuring mypy `files`

---

sap_hana/assets/configuration/spec.yaml
sap_hana/datadog_checks/sap_hana/data/conf.yaml.example
sap_hana/manifest.json
sap_hana/setup.py

Add config spec for `sap_hana`

Add sap hana config spec

---

azure_iot_edge/manifest.json

Cleanup for #7465, pre-requisite to #7841
Add `mac_os` to `supported_os` in `manifest.json`.
Although Azure IoT Edge as a technology isn't intended to run on macOS systems (it only supports Linux and Windows), there's no reason to not ship the integration on macOS. Indeed, there's nothing in the integration code that's incompatible with macOS. And we could imagine a weird (but valid) scenario where a macOS native Agent would be used to monitor a distant device — no need to artificially disallow it.
So let's just ship the integration everywhere.

Mark Azure IoT Edge integration as macOS-compatible

---

sidekiq/README.md

It removes the sidekiq validation section since sidekiq integration doesn't show up on agent status page because it is not the sort of integration where the Agent runs a Python check every <n> seconds. It is merely Dogstatsd waiting for metrics to be sent to it.
[Motivation](https://datadoghq.atlassian.net/browse/AGENT-5012?focusedCommentId=290152&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-290152)

[DOC] Remove sidekiq integration under agent status validation section

---

snmp/datadog_checks/snmp/config.py
snmp/datadog_checks/snmp/data/conf.yaml.example
snmp/datadog_checks/snmp/snmp.py
snmp/tests/test_check.py

Make `refresh_oids_cache_interval` available as init_config
User request.

Make refresh_oids_cache_interval available as init_config

---

harbor/assets/configuration/spec.yaml
harbor/datadog_checks/harbor/data/auto_conf.yaml
harbor/datadog_checks/harbor/data/conf.yaml.example
harbor/manifest.json
harbor/setup.py

Add config spec for `harbor` integration
This adds the other http configuration available

Add config spec

---

network/datadog_checks/network/network.py
network/metadata.csv
network/tests/test_network.py

Collect the send and receive queues metrics in the output of `ss` or `netstat`.
The TCP queues length metrics are already gathered by the [eBPF-based `tcp-queue-length` core check](https://github.com/DataDog/integrations-core/tree/master/tcp_queue_length), but being able to collect those data from the `network` python check has the advantage of simplicity. There’s no need for running `system-probe`, installing the kernel headers, etc.

[network] Collect receive and send queue metrics

---

mysql/assets/configuration/spec.yaml
mysql/datadog_checks/mysql/config.py
mysql/datadog_checks/mysql/data/conf.yaml.example
mysql/datadog_checks/mysql/mysql.py
mysql/datadog_checks/mysql/statements.py
mysql/metadata.csv
mysql/setup.py
mysql/tests/compose/mariadb.conf
mysql/tests/conftest.py
mysql/tests/test_mysql.py
mysql/tox.ini

This PR adds MySQL statement-level metrics from performance_schema. 
Please also refer to the code in the datadog_checks_base PR which is used here: https://github.com/DataDog/integrations-core/pull/7837
* MySQL Integration PR: https://github.com/DataDog/integrations-core/pull/7851
* Postgres Integration PR: https://github.com/DataDog/integrations-core/pull/7852
Query-level metrics is one of the features of Deep Database Monitoring. This change will give customers metrics like `mysql.queries.time` tagged by `query` and `query_signature` to report the time spent executing a particular normalized statement.

Support MySQL statement-level metrics for deep database monitoring

---

datadog_checks_base/datadog_checks/base/checks/openmetrics/mixins.py
datadog_checks_base/tests/fixtures/prometheus/ksm.txt
datadog_checks_base/tests/test_openmetrics.py

Add support for `'*'` syntax in `labels_to_match` field. It allows to gather labels from some time series and apply them to all others.
It's useful in some scenarios, for instance in leader/follower scenarios, to easily tag metrics coming with proper `leader: true/false` label.

Support '*' (match all) in OpenMetrics labels_to_match - allows to apply labels to all timeseries

---

datadog_checks_base/datadog_checks/base/utils/http.py
datadog_checks_base/tests/test_http.py

- Support wildcard subdomain. e.g. `*.example.com`
- Support single wildcard effectively disabling proxy.
- wildcard subdomain widely used in Windows environment and some linux systems
- Only subdomain can be used with wildcard. e.g. `*.example.com` OK, `*example.com` NOT supported
- Wildcards in middle or at the end are not supported. e.g. `foo.*.bar` or `127.*.*.*`
- Public doc update to follow after

[http] Support wildcard subdomain and single wildcard in proxies

---

datadog_checks_base/datadog_checks/base/checks/win/winpdh.py

First step to address: https://github.com/DataDog/integrations-core/pull/7853
IIS checks relies on the counter "class name" which can be localized and has different logic based on it. Currently the check compares the class name to the english class names of the counters ("Web Service" and "APP_POOL_WAS") which can be localized.
Currently the IIS check has no other option as the english class name is discarded once the localized name is found.
This PRs adds two new public properties to WinPDHCounter `localized_class_name` and `english_class_name` which, as they name suggest, return the name of the counter class either in english or localized.

Store english and localized counter classes for reusability

---

azure_iot_edge/tox.ini
datadog_checks_base/tox.ini
docs/developer/guidelines/style.md
mypy.ini

* Drop [`--disable-untyped-defs`](https://mypy.readthedocs.io/en/stable/config_file.html#confval-disallow_untyped_defs) and add [`--check-untyped-defs`](https://mypy.readthedocs.io/en/stable/config_file.html#confval-check_untyped_defs) in our default `mypy.ini`.
* Drop `--check-untyped-defs` from `tox.ini` files that were using it, since it's now enabled by default.
* Update [docs](https://datadoghq.dev/integrations-core/guidelines/style/#mypy).
Consider a check with the following `tox.ini`:
```ini
; ...
[testenv]
dd_check_types = true
dd_mypy_args = --py2 datadog_checks/ tests/
```
And the following `check.py` snippet:
```python
from typing import Iterator
from datadog_checks.base import AgentCheck
from .config import Config
from .types import Metric
class ExampleCheck(AgentCheck):
def …
```

Check types inside untyped functions by default

---

azure_iot_edge/tox.ini
datadog_checks_base/tox.ini
docs/developer/guidelines/style.md
mypy.ini

This reverts commit 2aba166904fdea971c2438bc7a51a749c612aaa0.
CI is breaking because enabling this flag creates mypy error in some checks, like `cloud_foundry_api`, `datadog_checks_dev`, and some others. After revert is merged, we can create a sandbox PR to see all issues, and secure them separately.

Revert "Check types inside untyped functions by default (#7839)"

---

iis/datadog_checks/iis/iis.py

Collection of IIS metrics was failing on non-english system as the counter class names are localized. In this PR we replace the check on the counter class name by a check on the english version of the class name.

Fix iis metrics collection on non-english systems

---

datadog_checks_base/datadog_checks/base/checks/openmetrics/mixins.py
datadog_checks_base/tests/test_openmetrics.py

This PR introduces a config option that allows users to ignore metrics with certain labels or label values.
in conf.yaml
```
init_config: {}
instances:
prometheus_endpoint: http://localhost:8086/-/metrics
ignore_metrics_by_labels:
pid:
- puma_master
worker: *
```
The above will ignore metrics with labels `pid:puma_master` or any metric with label `worker:<ANY>`
FR

Filter metrics by label keys and values

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/tester_selector/github_users.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/tester_selector/tester_selector.py

This PR uses creation, update and closed date to detect user inactivity.
If a user open a pull request and merge it several weeks later, the last activity date must be the close date of the PR.

Use creation, update and closed date to detect user inactivity.

---

datadog_checks_base/datadog_checks/base/utils/subprocess_output.py
network/datadog_checks/network/network.py
network/tests/test_network.py

Set PATH env to ensure "sh" command receive the same PATH as the caller process.
Customers find network metric collection failure in CentOS, it's a regression from 7.22.1.
None

Fix network metric collection failure on CentOS

---

sqlserver/assets/configuration/spec.yaml
sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
sqlserver/datadog_checks/sqlserver/metrics.py
sqlserver/datadog_checks/sqlserver/sqlserver.py

Adding the ability to only emit AlwaysOn metrics for a specific database `ao_database`. 
Customer may want to specify a database rather than get metrics for all AlwaysOn databases. 
This is a continuation of https://github.com/DataDog/integrations-core/pull/7824.
Instead of using the existing `database` option, I created a new `ao_database` option to keep backwards compatibility with the existing code and to make it more clear.

Add new option to filter AlwaysOn metrics by database

---

tcp_queue_length/manifest.json
tcp_queue_length/metadata.csv

Update the `tcp_queue_length` check documentation following DataDog/datadog-agent#6625.

Update the metrics exposed by the tcp_queue_length check

---

rabbitmq/assets/configuration/spec.yaml
rabbitmq/datadog_checks/rabbitmq/data/conf.yaml.example
rabbitmq/datadog_checks/rabbitmq/rabbitmq.py
rabbitmq/tests/common.py
rabbitmq/tests/test_integration_e2e.py

- I refactored one duplicate code that append_lines to a data structure in the _filter_list. The new method is rabbitmq._append_match_lines 
- In _append_match_lines is where is the logic to get the regex and associate to the tags values, this is where I added the support to get the regexes names and transform to TAGS. 
- The old use of tag_families was maintained and it's happens when there are no named groups specifieds in the regex, so it's the default choice.
When I tried to use the integration of RabbitMQ, I had the need to specify more than one "tag" in my regex group, to create
better monitors/dashboards.
So I was asking myself, why I cant use the named groups from regexes to match the tags I want to upload to DD? 
I don't know if there are some limitations for tags that should had …

Add support for named groups in regular expressions

---

ignite/tests/common.py
ignite/tests/compose/docker-compose.yml
ignite/tests/conftest.py
ignite/tox.ini

Update E2E tests for `ignite` to add support for Ignite 2.9 and above.
These E2E failures on Ignite have been preventing the CI pipeline from succeeding for a few days.
The Ignite 2.9 Docker image changed: instead of calling into `ignite.sh` (the ignite setup script), it calls the JVM directly, so JMX must be configured through standard JVM options (rather than the custom `functions.sh` script we have, which is run by `ignite.sh` on < 2.9).
2.9 Docker docs: https://ignite.apache.org/docs/latest/installation/installing-using-docker
2.9 release notes: https://github.com/apache/ignite/blob/master/RELEASE_NOTES.txt
> * Replaced ignite.sh invocation with the direct JVM call for Docker deployment

Fix E2E tests for Ignite 2.9

---

squid/datadog_checks/squid/squid.py
squid/tests/test_squid.py

Squid versions scheme has changed from `major.minor.patch` to simply `major.minor`

Fix squid version collection

---

datadog_checks_base/datadog_checks/base/utils/metadata/core.py
datadog_checks_base/tests/test_metadata.py

Open to thoughts and comments.
Metadata collection is often problematic and we often see the `Unable to transform version metadata` because the version string doesn't exactly match the expected format.
Most integrations are logging version metadata errors at the debug log level at the moment, this PR pushes the same id to the base class

Change metadata errors log level

---

datadog_checks_base/datadog_checks/base/checks/base.py
datadog_checks_base/datadog_checks/base/stubs/aggregator.py

https://github.com/DataDog/datadog-agent/pull/6663
The next PR will apply it to the Open Metrics base class

Support `flush_first_value` flag for monotonic counts

---

lighttpd/README.md
lighttpd/assets/configuration/spec.yaml
lighttpd/datadog_checks/lighttpd/data/conf.yaml.example

Drop `encoding: utf-16-le` option from logs config for lighttpd.
Cleanup for #7719 
Found during QA
With the current setup, where `mount_logs=True` injects the `encoding: utf-16-le` option defined in `spec.yaml`, I am not able to have the Agent collect logs.
```
==========
Logs Agent
==========
Sending uncompressed logs in SSL encrypted TCP to agent-intake.logs.datad0g.com on port 10516
You are currently sending Logs to Datadog through TCP (either because logs_config.use_tcp or logs_config.socks5_proxy_address is set or the HTTP connectivity test has failed). To benefit from increased reliability and better network performances, we strongly encourage switching over to compressed HTTPS which is now the default protocol.
BytesSent: 0
EncodedBytesSent: 28
LogsProcessed: 0
LogsSent: 0 …
```

Remove default `encoding` example in logs config

---

lighttpd/tests/docker/auth/docker-compose.yaml
lighttpd/tests/docker/auth/lighttpd.conf

Enable log collection in `-auth` test envs.
Cleanup for https://github.com/DataDog/integrations-core/pull/7719
#7719 only updated `docker-compose.yaml` and `lighttpd.conf` for the `-noauth` variant of the test env, which starting an env like `lighttpd py38-auth` would not collect logs.

Enable logs support in -auth test environments

---

lighttpd/setup.py

Remove duplicate copyright line in `lighttpd/setup.py`.
Discovered during QA of: https://github.com/DataDog/integrations-core/pull/7719

Remove duplicate copyright line in setup.py

---

directory/assets/service_checks.json
directory/datadog_checks/directory/directory.py
directory/tests/test_directory.py

The service check needs tags:
1. custom tags in the config should be reflected
2. The service check needs to be tagged by the dir name, otherwise there's no way to differentiate them if mulitple directory checks are running on the same agent.

Add tags to the new `system.disk.directory.exists` service check

---

vault/datadog_checks/vault/vault.py
vault/tests/test_vault.py

If a vault node starts as a secondary but changes to a primary at a later point in time, the integration is not able to pick up that change and start collecting metrics again.
This PRs makes sure that the status of the node is updated on every check run.

Fix secondary mode detection logic

---

snowflake/tests/conftest.py

Fix scope of `instance` fixture in Snowflake tests.
We can't `ddev env start` without this change because `dd_environment(instance)` is session-scoped but `instance` is function-scoped (and pytest disallows this).
I checked and `instance` isn't modified by tests, so we don't need to `deepcopy`.

Fix instance fixture scope

---

snowflake/README.md

Looks like the release for 7.24.0. resulted in 2.1.0 being incompatible with 7.23.0

Use 2.0.1 with 7.23.0

---

snowflake/datadog_checks/snowflake/__init__.py

Fix #7931
I implemented a workaround to run snowflake integration properly.
#7931

Add workaround for issue in platform.platform() on python 3.8 or later

---

sqlserver/tests/compose-ha/docker-compose.yaml

Minor compatibility change so the HA environment can be brought up with earlier versions of macOS Docker.

Update e2e config for more compatibility

---

mongo/datadog_checks/mongo/collectors/replica.py
mongo/tests/results/metrics-replset-lag-from-primary-configsvr.json
mongo/tests/results/metrics-replset-lag-from-primary-in-shard.json

The `mongo.replication.optime_lag` metric is computed from the primary for all secondaries. Thus the `repl_set_state` tags need to be removed and overriden with the state of the other nodes, not the current node.

Add sharding_cluster_role tag to optime_lag metric

---

mongo/datadog_checks/mongo/mongo.py
mongo/tests/fixtures/getCmdLineOpts-replica-secondary

There are two ways to configure a mongo replicaset, either by setting `replication->replSetName` in a yaml file (the documented way as mentioned here https://docs.mongodb.com/v4.4/reference/configuration-options/#replication.replSetName
or by using the old (pre v2.4) flat configuration file and setting `replSet` directly https://docs.mongodb.com/v2.4/reference/configuration-options/#replSet
Those two options are slightly different so even when parsed and exposed by mongo through `getCmdLineOpts`, they end up in different fields of the payload. In the first case, the replSetName value ends up in `replication->replSetName`, in the latter case it ends up in `replication->replSet`
This PR adds support for this.
For reviewers:
We could also assume that the node is a replica set, run the …

Fix replicaset identification with old configuration

---

envoy/tests/test_envoy.py

Test for #7740 since there is no test checking tags for envoy.
I don't know if the test is correct.
Metrics are defined as:
```
'cluster.grpc.success': {
'tags': (
('cluster_name', ),
('grpc_service', 'grpc_method', ),
(),
),
'method': 'monotonic_count',
},
```
I dont' understand very well this formatting. What does it mean each tuple, what's an empty tuple in the middle of non empty tuples, etc.
On this test I'm considering all tags should be there or no tags at all, but not all tags metrics are emmited.

Add test for tags

---

.azure-pipelines/templates/checkout-code.yml

Azure updated how they checkout code from
```
git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=10 origin
```
to 
```
git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=10 origin +cf2cf619b65b333822e900d36a76a21393cceb4e:refs/remotes/origin/cf2cf619b65b333822e900d36a76a21393cceb4e
```
But we need the master ref in our CI

[ci] Fix checking out master

---

harbor/assets/configuration/spec.yaml
harbor/datadog_checks/harbor/data/conf.yaml.example
hazelcast/assets/configuration/spec.yaml
hazelcast/datadog_checks/hazelcast/data/conf.yaml.example

`hazelcast` and `harbor` are currently failing `ddev validate http` due to not using `http` template while using http wrapper: https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=30327&view=logs&j=910f82a4-622d-5ace-f877-8b75c045486c&t=12901f7b-620f-5414-43d1-3ae27e5163d7&l=19. 
This PR adds the templates to pass CI.

Add http templates for integrations using http wrapper

---

mongo/datadog_checks/mongo/mongo.py

Minor typo in the debug message output for when `mongo` doesn't run custom queries on secondaries.

Fix debug typo for custom queries

---

network/README.md
network/assets/configuration/spec.yaml
network/datadog_checks/network/data/conf.yaml.default
network/datadog_checks/network/network.py

Add a parameter to disable receive and send queues collection implemented in #7861.
Receive and send queues collection generate two data points per `ss` (or `netstat`) line.
The data are then aggregated on agent side in an histogram.
If this aggregation process consumes too much CPU, a new `network` check parameter `collect_connection_queues` can be used to disable this feature.

[network] Add a parameter to disable receive and send queues collection

---

cockroachdb/tests/conftest.py
cockroachdb/tests/docker/docker-compose.yaml

Fix `cockroachdb` test setup to support 20.2+.
Latest version 20.2 made it required for [`start`](https://www.cockroachlabs.com/docs/stable/start-a-local-cluster.html) to include a `--join` flag, making CI fail:
```console
cockroachdb    | * ERROR: ERROR: no --join flags provided to 'cockroach start'
cockroachdb    | * HINT: Consider using 'cockroach init' or 'cockroach start-single-node' instead
```
This PR applies the hint above: on 20.2, use [`start-single-node`](https://www.cockroachlabs.com/docs/v20.2/cockroach-start-single-node) (we have a single-node test setup).
Note: Cockroach switched to [a form of Calver](https://www.cockroachlabs.com/docs/releases/release-support-policy.html#current-supported-releases) end of 2019, so version history is like this: 2.0.5, 2.11.1, (switch) …

Fix CockroachDB test setup for 20.2+ compatibility

---

datadog_checks_base/datadog_checks/base/utils/db/statement_metrics.py
datadog_checks_base/tests/test_db_statements.py

For database stats tables, this changes the behavior when a truncated row is found. Because this function computes the difference in monotonic counters between check runs, a value lower than the previous check run is assumed to be invalid. Currently, all rows are dropped when a single row is negative. This can result in states where all rows are dropped every check run due to bad state on a single row. 
This was an edge case we caught early on, but forgot about when I opened the PR. I added a comment to avoid making the same mistake again.

Change DB utils behavior when a truncated row is found to only drop the row

---

postgres/datadog_checks/postgres/statements.py

This causes a bug in display of the `query` tag that includes comments. Unfortunately, I can't add proper tests because it calls the datadog_agent API and the stub doesn't provide actual obfuscation.

Fix query tag for postgres to use the normalized query

---

marklogic/datadog_checks/marklogic/check.py
marklogic/tests/fixtures/bad_resource_storage.yaml
marklogic/tests/test_resource_filters.py

Handle exceptions when information about a filtered resource is not available.
This can happen when we try to get a forest information, but its database is disabled.

Handle unavailable specific resource information

---

mongo/datadog_checks/mongo/collectors/replica.py
mongo/tests/fixtures/replSetGetStatus-replica-primary-in-shard

For nodes that are neither a primary nor a secondary (they are starting up for example), mongo exposes an optimeData with a value of `ISODate("1970-01-01")`.
This PR ignores those nodes from the `mongodb.replication.optime_lag` metric, otherwise graphs get a huge spike when a new node is restarting.
This will help to make this metric more useful and to reliably trust monitors alerting on the value of the lag.

Ignore startup nodes for lagtime

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/http.py

This PR makes sure that integrations that are not directly using the http wrapper but inherit the OpenMetricsBaseCheck are also validated. Also makes the validation a little bit faster by only checking python files and fixes message warning to incorporate openmetrics errors.
I noticed that some openmetrics integrations that were missing the openmetrics template did not fail validation because it was only looking for explicit `self.http` calls.

Include openmetrics integrations in http validation

---

mysql/README.md
mysql/assets/configuration/spec.yaml
mysql/datadog_checks/mysql/data/conf.yaml.example

- The currently suggested multi-line aggregation rule for the MySQL general log file is appropriate for some, but not all customers.  A different format exists, and it is helpful to add the regular expression that will result in this different format being aggregated properly.  
- This rule was added to help users with the MySQL general log format wherein each new log does not start with a timestamp.  Instead, the timestamp is only logged once every second, and the logs in between those with a timestamp start with at least two tab characters (potentially followed by additional whitespace), followed by an integer, the thread ID, instead.
Support cases with improperly aggregated MySQL logs from the general log file where a different multi-line aggregation rule was needed to get each log to …

Adds helpful multi-line rule suggestion for MySQL general log file

---

.azure-pipelines/templates/checkout-code.yml

Enable `persistCredentials` when checking out the repo in CI.
Follow-up to #7975 
After #7975, we're still seeing issues with `git fetch origin master` on our private repos (eg `marketplace`).
```console
git fetch origin master && git checkout master
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/5f115d19-c0d2-4256-a31a-3a9a0e99a2c1.sh
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```
I don't know if something changed (seems so), but it looks like `script` tasks aren't allowed to interact with the remote by default.
Azure docs indicate turning on this flag to allow this: https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=ya …

CI: persist credentials when checking out code

---

datadog_checks_dev/datadog_checks/dev/tooling/configuration/consumers/example.py
datadog_checks_dev/tests/tooling/configuration/consumers/test_example.py

Fixes: https://github.com/DataDog/integrations-core/pull/7600/files#r506236986

[Config specs] Allow longer line in compact_example lists

---

datadog_checks_base/datadog_checks/base/utils/tls.py
datadog_checks_base/tests/test_tls.py

This option isn't used yet and doesn't provide any value, there's no point in verifying the TLS connection if no CA is provided

Remove unused 'tls_load_default_certs' option 

---

istio/tests/terraform/1.2.3/main.tf
istio/tests/terraform/1.5.1/main.tf

This PR truncates the user name to workaround GCP size limit of cluster names.
As a matter of fact, GCP limits cluster names to 40 characters (https://cloud.google.com/sdk/gcloud/reference/container/clusters/create#:~:text=The%20name%20of%20the%20cluster,no%20longer%20than%2040%20characters.&text=Attaches%20accelerators%20(e.g.%20GPUs)%20to%20all%20nodes.).

Overcome GCP limit for cluster names (40 chars).

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/http.py

Some integrations (snowflake) use the http wrapper but not necessarily utilizing the request function should skip validation.
This PR allows an inline comment `SKIP_HTTP_VALIDATION` which avoids failing for other use cases.
Use case:
- Snowflake uses `self.http.options` to use formatted proxies from config.
Snippet:
```
try:
proxies = self.http.options['proxies']  # SKIP_HTTP_VALIDATION
with self.MONKEY_PATCH_LOCK:
```

Support inline comment to skip http validation

---

snmp/datadog_checks/snmp/data/profiles/_dell-rac.yaml
snmp/datadog_checks/snmp/data/profiles/dell-poweredge.yaml
snmp/tests/test_profiles.py

Add device_index to idrac
To discriminate each row of the table, we need to tag by device_index too.

Add device_index to idrac (AI-938)

---

nginx/datadog_checks/nginx/nginx.py
nginx/tests/test_nginx.py

Fix how we submit the nginx version metadata.
~Send it only when the configuration enables it~
Send the correct nginx version:
* From the header response in the classic API
* `version` from the `/nginx` endpoint  of the PLUS API https://docs.nginx.com/nginx/admin-guide/monitoring/live-activity-monitoring/#getting-statistics-with-the-api, that it different from the API version, also named `version` in a different endpoint.
We explicitly get the version from the correct endpoint, so it's not override in the metric loop.

Fix version metadata collection

---

snowflake/assets/configuration/spec.yaml
snowflake/datadog_checks/snowflake/check.py
snowflake/datadog_checks/snowflake/config.py
snowflake/datadog_checks/snowflake/data/conf.yaml.example
snowflake/tests/test_unit.py

This PR introduces a workaround to add proxy support to Snowflake.
Currently, Snowflake python connector supports proxy by setting environment variables `HTTP_PROXY`/`HTTPS_PROXY`/`NO_PROXY`. We want to avoid using this as these configuration settings will affect other services and the integration will not be using proxy settings specified in the Agent.
https://docs.snowflake.com/en/user-guide/python-connector-example.html#using-a-proxy-server
This PR also removes the min_collection config in the code since we don't use this at the check level.
There is an upstream PR for this fix `https://github.com/snowflakedb/snowflake-connector-python/pull/352`.
We can remove the workaround once the fix is available.
Manually tested with squid proxy

Support proxy settings

---

tcp_queue_length/manifest.json
tcp_queue_length/metadata.csv

This renames the following metrics reported by the `tcp_queue_length` check:
- `tcp_queue.read_buffer_max_fill_rate` => `tcp_queue.read_buffer_max_usage_pct`
- `tcp_queue.write_buffer_max_fill_rate` => `tcp_queue.write_buffer_max_usage_pct`
Better readability and clarity about what these metrics represent

[tcp_queue_length] Rename tcp_queue_length metrics

---

kubernetes/assets/dashboards/kubernetes_replicasets.json
kubernetes/assets/dashboards/kubernetes_services.json
kubernetes/manifest.json

Add ReplicaSets and Services dashboards for the kubernetes integration.
Check them out on staging :)

[kubernetes] add replicasets and services dashboards

---

oracle/metadata.csv

This changes the description of the units for the metrics oracle.database_wait_time_ratio. The units for this metric is currently "fraction" but this metric represents a percentage.
Customer question and ticket: https://datadog.zendesk.com/agent/tickets/417961

Update oracle.database_wait_time_ratio unit to percent

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py

This PR adds sub-watt units to the validate command.
Validation works on manifests that contain sub-watt units, such as the Nvidia Jetson integration.

Add sub-watt metric metadata units

---

rabbitmq/README.md

log_processing_rules is supposed to be an array.

Fixed documentation for RabbitMQ logs

---

haproxy/manifest.json

The prometheus version of the check does not send `haproxy.frontend.bytes.in_rate` anymore, and it sends `haproxy.frontend.bytes.in.total`
Support case

Add metric to check for prometheus

---

mysql/assets/dashboards/overview-screenboard.json
mysql/assets/dashboards/overview.json
mysql/manifest.json

This PR does two things:
1. Migrates the original timeboard from `dogweb` to `integrations-core` for compatibility.
2. Adds a new screenboard dashboard for MySQL that is more blog-like.
*Current:*
*New:*
Staging link: https://dd.datad0g.com/screen/integration/30536/mysql?from_ts=1605626831278&live=true&to_ts=1605630431278
TODO: Migrate the existing dashboard from dogweb to integrations-core. This PR is more just to get eyes on the new dashboard for edits. PR for migration: https://github.com/DataDog/dogweb/pull/52934

Update MySQL dashboard to be blog-like and migrate old dashboard

---

airflow/tests/k8s_sample/README.md

Updates the helm stable url within the in-app docs as it has changed (see [docs here](https://charts.helm.sh/stable/#usage) for more info)
Jira request for docs

Helm chart url in Airflow docs

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/show/changes.py

Adds a new "since" flag to `ddev release show changes`
Adds help text to all `ddev release show changes` options to be viewable via `ddev release show changes --help`
When working with repositores that don't strictly adhere to semver (for example those that adhere to PEP440), the command can't autodetect the latest tag because it can't sort PEP440 tags. While it may be possible to have this command support arbitrary versioning schemas, instead this approach lets a user manually enter the tag that they want to query. This allows:
* bypassing the auto retrieval and work of sorting tags, and thus allowing arbitrary versioning schemas
* Seeing what changed since an arbitrary point in time, not strictly the last release.

Add 'since' flag to manually specify tag to look from

---

tomcat/README.md

Adds information and links for configuring log4j, since it's no longer configured as default for Tomcat
DOCS-1432

Add information for configuring log4j

---

sqlserver/assets/configuration/spec.yaml
sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
sqlserver/datadog_checks/sqlserver/metrics.py
sqlserver/datadog_checks/sqlserver/sqlserver.py
sqlserver/tests/common.py
sqlserver/tests/test_integration.py
sqlserver/tests/test_unit.py

Adds the ability to configure custom SQL queries for metric extraction from SQL Server.
The approach was heavily influenced by the `postgres` [implementation](https://github.com/DataDog/integrations-core/blob/91203785970f30e95a11f63e73471e267aa330c8/postgres/datadog_checks/postgres/postgres.py#L321) and [associated tests](https://github.com/DataDog/integrations-core/blob/91203785970f30e95a11f63e73471e267aa330c8/postgres/tests/test_custom_metrics.py).  As a result, the queries can be largely open ended as long as they provide extractable data.
Limitations:
- Limited to tables other than performance counters and the `sys.dm_os_performance_counters` table, since those data points require the special handling as done with the myriad of sqlserver metrics classes.  But, if a user chooses to …

Add support for custom SQL queries

---

zk/README.md

This PR does two things:
- Add new documentation to the README to help users understand how to map ZooKeeper's JKS file format to PEM file format. 
- Change `Zookeeper` to `ZooKeeper` to be more aligned with Apache's standards.
In https://github.com/DataDog/integrations-core/pull/7884, SSL support was added for the ZooKeeper check. Customers that are used to ZooKeeper's JKS file format may not be familiar with PEM file format, hence this documentation update to help map JKS to PEM.

Add new documentation to explain how to map JKS to PEM files for ZooKeeper SSL

---

network/README.md
network/assets/configuration/spec.yaml
network/datadog_checks/network/data/conf.yaml.default
network/datadog_checks/network/network.py
network/tests/test_network.py

Set the `collect_connection_queues` parameter default value to `false`.
On hosts which have a huge number of connection, the extra CPU and memory consumed

[network] Set the collect_connection_queues parameter default value to false

---

network/README.md
network/assets/configuration/spec.yaml
network/datadog_checks/network/data/conf.yaml.default
network/datadog_checks/network/network.py
network/tests/test_network.py

Add a parameter to explicitly enable receive and send queues collection implemented in #7861.
Receive and send queues collection generate two data points per `ss` (or `netstat`) line.
The data are then aggregated on agent side in an histogram.
As this aggregation process can consume a lot of CPU, this feature now requires a new `network` check parameter `collect_connection_queues` to be explicitly set to `true` to enable this feature.

Backport #7985 and #8059 to 7.24.x: [network] Set the collect_connection_queues parameter default value to false

---

varnish/metadata.csv

Most metrics have second as per_unit_name, which does not make sense. Then `uptime` was missing the units so I've removed second from everywhere and added it to uptime.
Splitting https://github.com/DataDog/integrations-core/pull/8049/ for easier review

Remove second as per_unit_name from metadata.csv

---

docs/developer/tutorials/snmp/profile-format.md

Add Mapping index to tag string value
The doc was missing, example:
https://github.com/DataDog/integrations-core/blob/ccd8854297c40c6df8b6b5543445a349c4c3193a/snmp/datadog_checks/snmp/data/profiles/_generic-ip.yaml#L68-L77

Add Mapping index to tag string value documentation

---

snmp/datadog_checks/snmp/parsing/metrics.py

Add deprecation notice for metric[].name syntax

Add deprecation notice for metric[].name syntax

---

haproxy/datadog_checks/haproxy/legacy/haproxy.py
haproxy/tests/legacy/test_unit.py

Update the logic for parsing the Unix socket response so it's more robust to newlines.
Support case — the customer is seeing the `CheckException` trigger on an output which seems to be missing the final newline.
Refs #6158 — this PR added this logic originally, but it breaks if there's an extra or missing newline character.

Increase robustness of parsing of Unix socket responses in legacy implementation

---

disk/assets/configuration/spec.yaml
disk/datadog_checks/disk/data/conf.yaml.default

Update description of `use_mount` option of `disk` check.
The current description is confusing because it seems to indicate that `use_mount` may affect collection, i.e. metric values and cardinality. In reality it is only a presentational knob that only affects the `device` tag:
https://github.com/DataDog/integrations-core/blob/a9caf4b06a4063e27376d45b4110f4c3cbc997b9/disk%2Fdatadog_checks%2Fdisk%2Fdisk.py#L144
https://github.com/DataDog/integrations-core/blob/a9caf4b06a4063e27376d45b4110f4c3cbc997b9/disk%2Fdatadog_checks%2Fdisk%2Fdisk.py#L161

Clarify effect of enabling `use_mount`

---

sqlserver/datadog_checks/sqlserver/sqlserver.py
sqlserver/tests/common.py
sqlserver/tests/test_integration.py
sqlserver/tests/test_unit.py

This minor change works around a possible bug with service check handling during initialization.
It was observed that running `ddev env check sqlserver py38-default` with multiple check instances configured would result in service checks showing up under the first check config.  By moving the connection checks outside of `__init__`, the resulting service checks appear in the correct place.
The underlying cause is still TBD, but it's deemed to be relatively minor in any case - the service checks only get conflated on check startup, but subsequent checks are associated correctly.
A separate PR to update best practices in the docs will follow.

Move connection initialization outside init function

---

oracle/datadog_checks/oracle/oracle.py
oracle/tests/test_config.py
oracle/tests/test_metrics.py
oracle/tests/test_oracle.py

Establishing a connection can be flaky, which over time may result in many unsuccessful check runs and therefore noisy logs.

Cache the client connection when there are no errors

---

ceph/datadog_checks/ceph/ceph.py
ceph/tests/common.py
ceph/tests/test_integration.py
ceph/tox.ini

Resolves https://github.com/DataDog/integrations-core/issues/8067
- detects octopus version
- updates logic to ensure metrics are compatible (`mon_status` is deprecated )
- updates fsid tag detection
- adds octopus e2e test environment

Support octopus version

---

datadog_checks_base/datadog_checks/base/stubs/aggregator.py
directory/tests/test_integration.py
mapreduce/tests/test_mapreduce_integration_e2e.py
mongo/tests/test_integration.py

Add `check_submission_type` argument to check submission type instead in-app type.
The goal would be to update integration tests using `check_metric_type=False` along with their `metadata.csv` to get rid of this argument.
Updated mapreduce and mongo tests to use `check_submission_type=True`
Used information from https://github.com/DataDog/datadog-agent/tree/master/pkg/metrics to create the type mapping

Allow asserting metrics types with metadata in integration tests

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/translate_profile.py

mibs.snmplabs.com has been down since late August, as reported in https://github.com/etingof/pysnmp/issues/376. In the meantime a copy has been provided at https://github.com/projx/snmp-mibs. This PR changes the target mibs source url 
We might also create our copy and point to our mibs - not sure there could be security concerns 
Fix ddev mibs resolution

Use snmp mibs copy while mibs.snmplabs.com is down

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/__init__.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/generate_profile.py
docs/developer/tutorials/snmp/profiles.md

This PR adds a ddev command to generate a profile given:
- a directory containing 
- (optional) a filter file to include only subgroups of a given MIB
And generates a profile with default metric_tags, more readable than MIB files. It uses `pysmi` to translate MIBs to json.
Generating profiles have some mechanical steps that can be automated by a script. This tooling is meant to improve the dev experience when creating or updating new profiles.

[SNMP] Generate profiles from MIBs

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/test.py

Add test filter to env test
Example:
```
$ ddev env test check snmp:py38-python_ad -k test_e2e_metric_types
```
Useful to filter tests.

Add test filter to env test

---

sqlserver/datadog_checks/sqlserver/connection.py
sqlserver/tests/test_unit.py

We are now raising a ConfigurationError if database names don't match exactly, but that is too restrictive.  This PR handles the process more gracefully, allowing mixed case database names where it doesn't matter, but enforcing it when a database is explicitly case sensitive.
Support ticket.

Handle case sensitivity on database names

---

active_directory/assets/configuration/spec.yaml
active_directory/datadog_checks/active_directory/data/conf.yaml.example
datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/pdh.yaml
hyperv/datadog_checks/hyperv/data/conf.yaml.example
pdh_check/datadog_checks/pdh_check/data/conf.yaml.example

Removes active directory references from the base template and fix counter_data_types which had been incorrectly formatted when adding the config specs.

Remove active_directory references from config

---

docs/developer/tutorials/snmp/profile-format.md
snmp/datadog_checks/snmp/data/conf.yaml.example

1. Use suggest MIB-less syntax, since it's the preferred way.
2. The profile format in `conf.yaml.example` is out of date. It's better to link to the complete doc located at https://datadoghq.dev/integrations-core/tutorials/snmp/profile-format/#metrics

Use MIB less syntax in example and link to profile format doc

---

datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py

Skip adding the `-py2` or `-py3` suffix if we're using an RC Agent build, such as `datadog/agent:7.23.0-rc.2`.
RC builds aren't published with a `-py2` or `-py3` suffix, and I got tired of commenting out this auto-set code when doing QA. :-)
Might need an additional tweak and thinking, because even public tags don't have `-py2` or `-py3` suffixes either, but only internal dev versions such as `datadog/agent-dev:master-py3`. But for now I'm just scratching my own itch!

Skip auto-setting Python version suffix if using an RC build

---

activemq/README.md

Update the ActiveMQ `README.md`:
- Remove `init_config.conf` field.
- Add missing `init_config.is_jmx` and `init_config.collect_default_metrics` fields.
- Add link to `metrics.yaml`.
The current example config in the ActiveMQ README is wrong. Configuring an integration with it will result in the Agent ignoring the filters and collecting all metrics emitted by JMX, soon exceeding the 350 metrics limit. This causes confusion for customers, and unnecessary support tickets. Also, I think `is_jmx: true` and `collect_default_metrics: true` were missing.
AFAIK the Agent should collect what's in `metrics.yaml` by default, so we don't actually need to have users specify the list of metrics if they're fine with the default ones.

Drop metrics listing from README example config

---

amazon_msk/assets/configuration/spec.yaml
amazon_msk/datadog_checks/amazon_msk/amazon_msk.py
amazon_msk/datadog_checks/amazon_msk/data/conf.yaml.example

This allows the user to specify a role to assume when retrieving MSK metadata.
We are monitoring multiple MSK clusters across our company from centralized k8s clusters. The MSK clusters are in separate accounts from the k8s clusters which causes issues when trying to retrieve the MSK metadata during `list_nodes` call in the Amazon MSK check. This allows the user to set up a role that has MSK read only access in the account containing the target MSK cluster and allows the boto3 client to assume that role during runtime.
Couldn't really provide a great unit test for this as it requires access to the AWS STS API.

Add support for AssumeRole in Amazon MSK check

---

pgbouncer/datadog_checks/pgbouncer/pgbouncer.py

An error collecting one scope of metrics should not prevent the rest from being collected

Make pgbouncer more reslient

---

sqlserver/assets/configuration/spec.yaml
sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
sqlserver/datadog_checks/sqlserver/sqlserver.py
sqlserver/tests/common.py
sqlserver/tests/conftest.py
sqlserver/tests/test_unit.py

Add support for database autodiscovery via additional configuration options:
- `database_autodiscovery` - toggles the feature on or off
- `autodiscovery_include` - list of patterns to always include, defaults to `.*`
- `autodiscovery_exclude` - list of patterns to exclude, overridden by the include option if there are conflicts
- `database_autodiscovery_interval` - how often to recheck, defaults to an hour
When enabled and databases have been found, metrics which have the ability to report at the database level will be created.  This largely affects the performance counter metrics, but also other database-level metrics.
Feature enhancement.
The pattern matching and options selection were largely borrowed from the `disk` check to make things more uniform across checks, though there are …

Add support for database autodiscovery

---

mysql/README.md

Adds a multi-line aggregation rule suggestion to the README for the mysql slowlog for versions < 5.7.
The currently suggested rule can cause improper line aggregation for versions < 5.7.  
This comment added to the README should help guide any customers using these versions.
note: Version 5.6 is due to reach end of support in Febuary 2021.

Add mysql slowlog multi-line rule suggestion for versions < 5.7 (README only)

---

kubernetes/assets/monitors/monitor_pod_crashloopbackoff.json
kubernetes/assets/monitors/monitor_pod_imagepullbackoff.json

Changes the Kubernetes recommended monitor metric to use a KSM metric that reports a `reason` tag
Customer report. `kubernetes_state.container.waiting` does not report a `reason` tag that the monitor is trying to scope over so the monitor won't be scoped over any timeseries. `kubernetes_state.container.status_report.count.waiting` does report a `reason` tag: https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md
N/A

Use a KSM metric that reports a reason tag in recommended monitors

---

oom_kill/README.md
tcp_queue_length/README.md

Adds a note about not supporting CentOS/RHEL versions < 8 and instructions on installing `kernel-devel` on those distributions to the `oom_kill` and `tcp_queue_length` checks
Customer report of the `oom_kill` check failing to compile on CentOS 7
N/A

Add CentOS/RHEL version support note and instructions to install kernel-devel

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/check.py
datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py
datadog_checks_dev/datadog_checks/dev/tooling/e2e/local.py

Add `--table` option to `ddev env check`.
Takes advantage of new feature added to agent from this PR: https://github.com/DataDog/datadog-agent/pull/6836
Note: this option will only be available on dev versions of the Agent or once it gets compiled into the next version release (`7.25.0`).
It can be tested with the following dev image: `datadog/agent-dev:mg-table-writer-py3`.
For example:
> ddev env start -a datadog/agent-dev:mg-table-writer-py3 --dev sqlserver py38-default

Add support for tabular check output

---

snowflake/README.md
snowflake/assets/configuration/spec.yaml
snowflake/datadog_checks/snowflake/check.py
snowflake/datadog_checks/snowflake/config.py
snowflake/datadog_checks/snowflake/data/conf.yaml.example

This PR emphasizes the creation of custom role to monitor Snowflake with sql example.
- make `role` config option required because default `ACCOUNTADMIN` is removed. 
- encourages users to use better security practices according to Snowflake
- Add example script for creating new user/role or just assigning permissions to sysadmin role
- clarify debug log for proxy 
Make note more obvious in configuration step.

Make role configuration step more explicit

---

nagios/README.md
nagios/assets/configuration/spec.yaml
nagios/datadog_checks/nagios/data/conf.yaml.example
nagios/manifest.json
nagios/tests/compose/docker-compose.yaml
nagios/tests/conftest.py

Add log support for nagios integration.
Note that the current integration already creates event from this log file, and creates metrics from other files.
I only added a parser for `nagios.log`.

Add log support

---

postgres/datadog_checks/postgres/util.py
postgres/metadata.csv

Two metrics are submitted twice:
- `postgresql.index_scans` is submitted from the `idx_scan` column in the `pg_stat_user_tables` table tagged by table and schema. This metric is also submitted from the `idx_scan` column in the `pg_stat_user_indexes` tagged this time by table, schema and index.
- `postgresql. index_rows_fetched` is submitted from the `idx_tup_fetched` column in the `pg_stat_user_tables` table tagged by table and schema. This metric is also submitted from the `idx_scan` column in the `pg_stat_user_indexes` tagged this time by table, schema and index. Also another metric called `postgresql.index_rel_rows_fetched` is submitted from the `idx_typ_fetched` column in the `pg_stat_user_tables` table tagged by table and schema.
For the second metric, this PR simply removes the …

Removed duplicated metrics

---

docs/developer/architecture/snmp.md

Fix some links in the SNMP architecture dev docs.
```
$ ddev docs serve
INFO    -  Building documentation... 
INFO    -  Cleaning site directory 
WARNING -  Documentation file 'architecture/snmp.md' contains a link to '../assets/images/snmp-architecture.png' which is not found in the documentation files. 
WARNING -  Documentation file 'architecture/snmp.md' contains a link to '../assets/images/snmp-architecture-cluster-agent.png' which is not found in the documentation files. 
INFO    -  Documentation built in 14.08 seconds 
```
I'm not getting the WARNINGs anymore when serving from this branch. :-) And images still show up just fine.
The images show up fine in the built website, but that may be "by accident" (eg maybe MkDocs has some mechanism to auto-fix links, or ignore those that go …

Fix links to SNMP architecture images

---

datadog_checks_base/datadog_checks/base/utils/db/core.py
datadog_checks_base/datadog_checks/base/utils/db/query.py
datadog_checks_base/datadog_checks/base/utils/db/transform.py
datadog_checks_base/tests/test_db.py

Prompted by https://github.com/DataDog/integrations-core/pull/8143#discussion_r537394319
Add a new `tag_list` column type to `QueryManager`.
Example usage:
Database tuples:
```console
["us,primary,default", 42]
["eu", 12]
["eu,primary", 21]
```
Query definition:
```python
query = {
"name": "example",
"query": "...",
"columns": [
{"name": "server_tag", "type": "tag_list"},
{"name": "foo", "type": "gauge"},
]
}
```
Resulting submissions:
```python
gauge("foo", tags=["server_tag:us", "server_tag:primary", "server_tag:default"])
gauge("foo", tags=["server_tag:eu"])
gauge("foo", tags=["server_tag:eu", "server_tag:primary"])
```
After analyzing the situation, I need this to migrate RethinkDB to `QueryManager` (see #8143). RethinkDB allows users to define "server tags" at startup. The …

Add `tag_list` column type, allowing to ingest variable-size database-provided tags

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/docs/build.py

Enable `--strict` mode when building docs.
In this mode, `mkdocs build` errors out if any warnings were discovered while building:
> Determines how warnings are handled. Set to true to halt processing when a warning is raised. Set to false to print a warning and continue processing.
https://www.mkdocs.org/user-guide/configuration/#strict
Prevents issues like #8150 from happening again. (We don't typically watch build logs to see if there are warnings, so they could sneak in unknowingly.)

Build developer docs in strict mode

---

snmp/assets/dashboards/datacenter_overview.json

Fixing custom links in datacenter overview dashboard to target device dashboard using only `short_name` (`Device%20Dashboard`) 
Fix custom links in datacenter dashboard

SNMP Use device dashboard short_name in datacenter dashboard

---

zk/setup.py

Zookeeper makes use of get_tls_context that was introduced in 15.2.0

Bump base check package

---

tox.ini

Upgrade `mkdocs-click` dependency to `0.2.*` for building the docs site.
Released 0.2.0: https://pypi.org/project/mkdocs-click/0.2.0
See: https://github.com/DataDog/mkdocs-click/pull/23
Ran the docs site locally using `ddev docs serve`, all look good. (Which is expected: version 0.2.0 doesn't contain breaking changes.)

Upgrade mkdocs-click dep to 0.2.*

---

tox.ini

Drop `--use-feature=2020-resolver` in our `tox.ini` configuration.
As noted by @mgarabed, pip 20.3 is out, which enables the resolver automatically. We are effectively already using it in CI.
Locally I had set `--use-feature=2020-resolver` in my `.zshrc`, so `pip` started warning about it:
```
WARNING: --use-feature=2020-resolver no longer has any effect, since it is now the default dependency resolver in pip. This will become an error in pip 21.0.
```
For some reason, we don't see these warnings in CI. My best bet is that they may be swallowed by tox, somehow, since we _are_ using pip 20.3.* in CI already: https://github.com/DataDog/integrations-core/runs/1524211865?check_suite_focus=true#step:4:31

Drop --use-feature=2020-resolver

---

cassandra/assets/dashboards/cassandra_overview.json
cassandra/assets/dashboards/cassandra_read.json
cassandra/assets/dashboards/cassandra_sstable.json
cassandra/assets/dashboards/cassandra_write.json
cassandra/manifest.json

Moves preset dashboard payloads into integrations-core
Easier for future updates

Migrate cassandra preset dashboards

---

kafka_consumer/assets/configuration/spec.yaml
kafka_consumer/datadog_checks/kafka_consumer/data/conf.yaml.example
kafka_consumer/manifest.json
kafka_consumer/setup.py

Adds spec.yaml for the configuration.
https://datadoghq.dev/integrations-core/meta/status/#config-specs

Add Kafka Consumer spec

---

kafka_consumer/assets/configuration/spec.yaml
kafka_consumer/datadog_checks/kafka_consumer/data/conf.yaml.example
kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py

Some consumers (like `HighLevelConsumer`) used to store and fetch offset from Zookeeper. This is deprecated and the supported way is to fetch offset from kafka brokers.
https://www.confluent.io/blog/tutorial-getting-started-with-the-new-apache-kafka-0-9-consumer-client/
A customer asked for clarification about this deprecation note.
Config specs added https://github.com/DataDog/integrations-core/pull/8108, let's be careful not to override the note update

Update deprecation notice

---

docs/dev/new_check_howto.md

Encourages the reader to try out `template: instances/http` when generating the config in the tutorial.
This was the original motivation; `instances/default` was a mistake. :P 
- ~[ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)~

make the "uncomment this" more interesting in the tutorial

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/catalog.py
datadog_checks_dev/datadog_checks/dev/tooling/utils.py
docs/developer/.scripts/33_render_status.py

Flink was not correctly identified as having logs

Refactor has logs

---

activemq/datadog_checks/activemq/data/conf.yaml.example
cassandra/datadog_checks/cassandra/data/conf.yaml.example
confluent_platform/datadog_checks/confluent_platform/data/conf.yaml.example
datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/jmx.yaml
hazelcast/datadog_checks/hazelcast/data/conf.yaml.example
hive/datadog_checks/hive/data/conf.yaml.example
hivemq/datadog_checks/hivemq/data/conf.yaml.example
ignite/datadog_checks/ignite/data/conf.yaml.example
jboss_wildfly/datadog_checks/jboss_wildfly/data/conf.yaml.example
kafka/datadog_checks/kafka/data/conf.yaml.example
presto/datadog_checks/presto/data/conf.yaml.example
solr/datadog_checks/solr/data/conf.yaml.example
sonarqube/datadog_checks/sonarqube/data/conf.yaml.example
tomcat/datadog_checks/tomcat/data/conf.yaml.example

Added docs for `collect_default_jvm_metrics`. This flag allows users to disable default jvm metrics in JMXFetch
Related PRs:
https://github.com/DataDog/datadog-agent/pull/6923
https://github.com/DataDog/jmxfetch/pull/345

Document new collect_default_jvm_metrics flag for JMXFetch integrations

---

mcache/assets/dashboards/memcached_dashboard.json
mcache/manifest.json

Migrate memcache dashboard from dogweb to integrations-core.
Corresponding `dogweb` PR: https://github.com/DataDog/dogweb/pull/54131
Will add new screenboard for memcache.

Migrate Memcache dashboard to integrations-core

---

kubernetes/README.md

Removes the sample kubernetes yaml file from the Kubernetes docs as it no longer exists
Jira request

Remove sample kubernetes yaml file

---

zk/datadog_checks/zk/zk.py

Bundle the socket error `exc` message with connection failure exceptions.
Found while QAing #7884 — this is a small UX improvement for Py2 users.
When an SSL error occurs (eg because the cert is invalid), we raise a `ZkConnectionFailure()`. On Python 3.8, there's exception chaining so the traceback of the original `socket.error` is shown as well. However on Python 2.7 there's no exception chaining, so only the last exception is shown. As a result we get this blank traceback in the Agent status:
```console
Error: 
File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/base.py", line 876, in run
File "/home/zk/datadog_checks/zk/zk.py", line 131, in check
ruok_out = self._send_command('ruok')
File …
```

Ensure connection failure message is shown on Python 2

---

process/README.md

Updates the metrics section to remove the notes and restore the magic phrase. The notes are keeping the metrics from rendering on the tile and on the documentation.
Broken things should be fixed.

[documentation] moving info out of the metrics section

---

datadog_checks_base/datadog_checks/base/checks/openmetrics/mixins.py
datadog_checks_base/tests/test_openmetrics.py

Avoid KeyError reported by customer when metrics disappear from KSM output.
Customer report

openmetrics: fix error in label_joins when metrics in label_mapping are not present anymore in active_label_mapping

---

varnish/tests/test_varnish.py

This PR removes `GAUGE_IN_5_RATE_IN_6` in the varnish check, since it is no longer being used.
`GAUGE_IN_5_RATE_IN_6` was only used for `test_check` and was removed in https://github.com/DataDog/integrations-core/pull/8075.

Remove unused value in Varnish

---

mongo/metadata.csv
mongo/tests/fixtures/serverStatus
mongo/tests/results/metrics-default.json
mongo/tests/test_mongo.py

Update the `metadata.csv` adding a missing metric 
CI of #8204 failing

Add missing mongodb.extra_info.heap_usage_bytesps in metadata.csv

---

kubernetes_state/datadog_checks/kubernetes_state/kubernetes_state.py
kubernetes_state/tests/fixtures/prometheus.txt
kubernetes_state/tests/test_kubernetes_state.py

changes the cardinality count of previous added deployment.count.
Now running `deployment.count` should return the expected number of deployments without the need to filter_by
Before one had to filter_by `condition:available, status:true` to get the correct count. But users would not expect this when calling `deployment.count`
Check looks like this
```
{
"metric": "kubernetes_state.deployment.count",
"points": [
[
1608292794,
1
]
],
"tags": [
"namespace:default"
],
"host": "agent-dev-nam",
"type": "gauge",
"interval": 0,
"source_type_name": "System"
},
```

[orchestrator] change cardinality of deployment count

---

windows_service/assets/service_checks.json

Change the default tag for windows_service monitor scope from service to windows_service.
The service_check doesn't always come with a service tag, but does with a windows_service tag
https://dd.datad0g.com/monitors#create/integration
https://a.cl.ly/5zudn5NP

change default monitor tag group from service to windows_service

---

docs/developer/tutorials/snmp/how-to.md

Adding an example to show how to use `mib2dev.py` to generate multiple rows for a table with the `--table-size`. Also replacing the `snmp` doc link with the github repo's, as `snmp` website is down 😞
We recently stumbled upon data generation and found this command very useful.

[SNMP] add table recording example to docs

---

haproxy/tox.ini

haproxy: bump all minors version we test against
this will make sure we rely on the latest minors versions available
haproxy: adding test support for v2.2.x
for now avoid legacy tests, as prometheus metrics are now the advised
ones
v2.3.x has some incompatibilities I'm working on

haproxy: minor versions update and adding v2.2 tests

---

kubernetes_state/datadog_checks/kubernetes_state/kubernetes_state.py
kubernetes_state/tests/fixtures/prometheus.txt
kubernetes_state/tests/test_kubernetes_state.py

* Revert #8222 
* ignore `kube_deployment_status_condition` which is too high cardinality for our use
* use `kube_deployment_status_observed_generation` to count deployments instead

Fix deployment count metric

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/shell.py

Adds a new option `--exec-command` to `ddev env shell` to execute a command directly.  
For example: `ddev env shell snowflake -c "apt update && apt install -y libssl-dev"`
In most cases the better approach is to edit the underlying Docker file, but when experimenting this can be a nice approach.  A side benefit: the commands will be stored in command history for easy repeatability.
Testing required manual tweaks.

Add exec command option to ddev env shell

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/manifest.py

Validate `snmp_<vendor>` integrations `metric_to_check` using metrics defined in `snmp`
While working on snmp we decided to add one tile per vendor supported by this integration. Each tile will define `metric_to_check` specific to the vendor metrics. As metrics and snmp vendor have an N:M relation, we decided to keep all metrics in snmp root folder. This change makes it possible to use `snmp` metrics as `metric_to_check` values in a `snmp_<vendor>` integration.
Required by https://github.com/DataDog/integrations-core/pull/8156/commits/33cd21e2ff39e723a4c57cd470f67ed1a7244047

Add metric_to_check validation redirection for snmp_<vendor> integrations

---

vertica/assets/configuration/spec.yaml
vertica/datadog_checks/vertica/data/conf.yaml.example
vertica/datadog_checks/vertica/vertica.py
vertica/setup.py
vertica/tests/common.py
vertica/tests/conftest.py
vertica/tests/test_unit.py
vertica/tests/test_vertica.py

This PR updates Vertica's TLS verify implementation to use updated in-house TLS library.
Note: Vertica's SSL/TLS implementation is only used for `tls_verify`. There is no official support to connect to Vertica via SSL/TLS yet. Another PR will add this feature.
Reduce Tech debt

Replace old tls_verify implementation with in-house TLS library.

---

datadog_checks_dev/datadog_checks/dev/tooling/signing.py

Since `in-toto` v1.0.0 update, importing `util` from `in-toto` is not possible anymore.

Fix release

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/config.py

Some config specs are missing default template. These templates are used by the agent/global and should be present in all integrations.
CI failing because of pending fixes: https://github.com/DataDog/integrations-core/pull/8233/files
caught this in some contributor PRs and will make our own code reviews easier.

Ensure default templates are included in config spec

---

mcache/assets/dashboards/memcached_screenboard.json
mcache/manifest.json

Adds a Memcache screenboard that is blog-like. Currently there is only a timeboard for Memcache.

Add new Memcache Screenboard

---

zk/README.md

The ZooKeeper SSL information was accidentally placed under the Hosts tab, which could unintentionally convey that SSL is not supported for Containerized:
This PR moves the SSL information to under the ZooKeeper Whitelist tab.

Move ZooKeeper SSL info out of Hosts tab in README

---

marklogic/metadata.csv

Fix `marklogic.forests.total_load` unit
According to the [doc](https://docs.marklogic.com/REST/GET/manage/v2/forests@view=status): `The sum of the processing load factors in seconds per second.`
Noticed it in #8226

Fix marklogic.forests.total_load unit

---

cacti/assets/configuration/spec.yaml
cacti/datadog_checks/cacti/data/conf.yaml.example

This PR fixes Cacti's `spec.yaml` to add in the `default` template. 
This is blocking https://github.com/DataDog/integrations-core/pull/8230 because the CI keeps failing.

Fix cacti config

---

amazon_msk/datadog_checks/amazon_msk/data/conf.yaml.example
azure_iot_edge/datadog_checks/azure_iot_edge/data/conf.yaml.example
cilium/datadog_checks/cilium/data/conf.yaml.example
cockroachdb/datadog_checks/cockroachdb/data/conf.yaml.example
coredns/datadog_checks/coredns/data/conf.yaml.example
crio/datadog_checks/crio/data/conf.yaml.example
datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/openmetrics.yaml
etcd/datadog_checks/etcd/data/conf.yaml.example
external_dns/datadog_checks/external_dns/data/conf.yaml.example
gitlab/datadog_checks/gitlab/data/conf.yaml.example
gitlab_runner/datadog_checks/gitlab_runner/data/conf.yaml.example
haproxy/datadog_checks/haproxy/data/conf.yaml.example
istio/datadog_checks/istio/data/conf.yaml.example
kube_apiserver_metrics/datadog_checks/kube_apiserver_metrics/data/conf.yaml.example
kube_scheduler/datadog_checks/kube_scheduler/data/conf.yaml.example
linkerd/datadog_checks/linkerd/data/conf.yaml.example
nginx_ingress_controller/datadog_checks/nginx_ingress_controller/data/conf.yaml.example
openmetrics/datadog_checks/openmetrics/data/conf.yaml.example
scylla/datadog_checks/scylla/data/conf.yaml.example

`prometheus_metrics_prefix` is used when the prometheus all have the same prefix and removes that prefix before submitting the metrics. See https://github.com/DataDog/integrations-core/blob/master/datadog_checks_base/datadog_checks/base/checks/openmetrics/mixins.py#L122
This PR makes this behavior a bit more clear.

Update prometheus_metrics_prefix documentation

---

sap_hana/assets/configuration/spec.yaml
sap_hana/datadog_checks/sap_hana/connection.py
sap_hana/datadog_checks/sap_hana/data/conf.yaml.example
sap_hana/datadog_checks/sap_hana/sap_hana.py
sap_hana/setup.py
sap_hana/tests/test_unit.py

The library we use (PyHDB) does not support SSL options when creating the connection to the database.  See https://github.com/SAP/PyHDB/issues/107
This PR updates the Connection class to add SSL support when opening the socket to the db.
The official SAP HANA python driver has all the necessary configuration to connect with SSL), but unfortunately it's using a license that doesn't permit redistribution so we aren't using it.

Add SSL support for connection

---

kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
kafka_consumer/datadog_checks/kafka_consumer/legacy_0_10_2.py

Update the debug message to a real warning. Helpful to understand why the kafka_consumer check doesn't emit metrics anymore.

Make 'Context limit reached' message a warning

---

process/datadog_checks/process/process.py

* After a lengthy discussion with Datadog support, they suggested changing the cache values
to avoid false negatives
* After restarting a process, the pids will obviously change, but the process can/usually is still live
* This small patch should clear the cache when the cached pids cannot be found
which will update the cache
* similar to https://github.com/DataDog/integrations-core/blob/26ad0e95a12582220390d04dd3faf9bb76687ee2/process/datadog_checks/process/process.py#L282-L283
* This way there's no need to reduce the cache size or hurt performance
and still more accurately deal with process restarts
see above
See above

Clear stale PIDs from cache

---

envoy/datadog_checks/envoy/envoy.py
envoy/tests/test_envoy.py

Update check signature from `check(self, instance)` to `check(self, _)`
Now throw a `ConfigurationError` in the constructor if the required `stats_url` option is not in the configuration file, instead of a KeyError in the check method

Update check signature

---

datadog_checks_dev/datadog_checks/dev/http.py
datadog_checks_dev/datadog_checks/dev/plugin/pytest.py

This adds a new global fixture that returns a function used to mock HTTP requests for the lifetime of a test
I am using this in a feature branch and realized we often need this

Add new global fixture to mock HTTP requests

---

datadog_checks_dev/datadog_checks/dev/_env.py

Fix ddev env test last error
Last error might not be a json object: https://github.com/DataDog/integrations-core/blob/12f3147323b6012845141b08ade3cb1c8f6bd5c6/datadog_checks_base/datadog_checks/base/checks/base.py#L882
Corecheck integration errors are not json object with message and traceback.
This doesn't change current behaviour.
We test python snmp impl against corecheck snmp impl, when there is an error, it will throw a json decoding error, this PR should fix that.

Fix ddev env test last error

---

sqlserver/metadata.csv

There were some small typos in the description of metric `sqlserver.ao.replica_sync_state`with incorrect state names and FCI metrics that had `bytes` as a unit of measurement.

Fix small typos in metadata.csv

---

datadog_checks_base/datadog_checks/base/stubs/aggregator.py

Fix aggregator stub's `assert_histogram_bucket` method

---

.azure-pipelines/all_master.yml
.azure-pipelines/all_pr.yml
.azure-pipelines/nightly_latest_base.yml
.azure-pipelines/templates/run-tests.yml
.azure-pipelines/templates/run-validations.yml
.azure-pipelines/templates/test-all-checks.yml
.azure-pipelines/templates/test-all.yml
.azure-pipelines/templates/test-single-linux.yml
.azure-pipelines/templates/test-single-windows.yml
datadog_checks_dev/datadog_checks/dev/plugin/tox.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py

Adds support to test against the latest released version of `datadog_checks_base` as part of `ddev test` command.
Includes a few related features:
- New `ddev test` options: `--force-base-package` and `--force-env-rebuild`
- Nightly CI tests with those options enabled
- Add `ispr` parameter to CI to limit certain tests/validations to PRs-only
- Add PR validation for `ddev validate dep --require-base-check-version`
Avoid surprises when a check depends on unreleased `datadog_checks_base` functionality.
While not needed for CI, the `--force-env-rebuild` is helpful for local testing since `tox` will just reuse an existing env.

Support nightly datadog_checks_base package checks

---

activemq/setup.py
cassandra/setup.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/dep.py
datadog_checks_dev/datadog_checks/dev/tooling/dependencies.py
kafka/setup.py
proxysql/setup.py
solr/setup.py
tomcat/setup.py

Expands the `ddev validate dep` command to also examine check `setup.py` files ensuring they specify a dependency on `datadog-checks-base`.  
Also normalizes a few older check files to use the same format of `CHECKS_BASE_REQ = 'datadog-checks-base'`, so that the validation will pass.
By default, the validation only checks if the dependency exists, optionally it can ensure that it's pinned to a minimum version.  This extra option could be added to CI for PR's only, so that we don't force changes on checks all at once.  Output with this option enabled:
```
❯ ddev validate dep --require-base-check-version
Unspecified version found for dependency `datadog-checks-base`: activemq, btrfs, and 26 others
```
UPDATED:
Added option `--min-base-check-version` which allows for a version specifier to …

Add version verification for datadog-checks-base

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/snmp_tile/snmp_{check_name}/README.md
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/snmp_tile/snmp_{check_name}/manifest.json

Minor fixes in snmp_tile template files:
* cleanup link list in `readme`
* add `snmp` prefix to `integration-id` and `name` in `manifest.json`
* add `Datadog-` prefix to `public-title` field in `manifest.json`
Changes required to be consistent with other integration tiles

Add prefix to manifest fields and update link list in readme in snmp_tile template

---

.azure-pipelines/templates/run-validations.yml
.azure-pipelines/templates/test-single-linux.yml
.azure-pipelines/templates/test-single-windows.yml
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/dep.py
datadog_checks_dev/datadog_checks/dev/tooling/dependencies.py

PR https://github.com/DataDog/integrations-core/pull/8293 added support to perform stricter dependency validation on PRs to gradually force updates to checks, but this validation runs across the whole repo.
This fixes it so the validation can run against a single check which should limit the scope in PR CI runs.

Fix dep validation to work on single checks for PRs

---

postfix/datadog_checks/postfix/postfix.py
postfix/tests/fixtures/postqueue_p.txt
postfix/tests/test_unit.py

Fix how we count defer messages using `postqueue -p`
The queue id can start with any alphanumerical char
Support case
http://www.postfix.org/postqueue.1.html

Fix postqueue defer counting

---

datadog_checks_base/datadog_checks/base/utils/metadata/version.py

Allow semver version metadata to start with an optional `v`

---

http_check/assets/service_checks.json
http_check/datadog_checks/http_check/http_check.py
http_check/tests/test_http_integration.py

Only send ssl metrics if a connection succeeded
- AGENT-5349

Only send ssl metrics if a connection succeeded

---

disk/datadog_checks/disk/disk.py
disk/tests/test_unit.py

This makes labels a bit more consistent with agent's builtin `io` check, which uses [device_label](https://github.com/DataDog/datadog-agent/blob/99507c6d14ee154eb2079254d7e9624b23e9c62b/pkg/collector/corechecks/system/iostats_nix.go#L98). When this is merged, users will be able to consistently use `device_label` tag for metrics from both of these checks.

Add device_label tag in addition to label tag.

---

datadog_checks_base/datadog_checks/base/checks/base.py
datadog_checks_base/datadog_checks/base/utils/tls.py
datadog_checks_base/tests/test_tls.py
tls/datadog_checks/tls/tls.py

This PR adds the option for `get_tls_context()` to add an `overrides` argument to set config values.
This is intended to be compatible with integrations that hardcode the values of SSL context config values in their checks. 
Note that the `overrides` argument takes precedent over reading the values for the respective config value. 
This change can affect 
- `http_check`: https://github.com/DataDog/integrations-core/blob/master/http_check/datadog_checks/http_check/http_check.py#L309-L311 
- `proxysql`: https://github.com/DataDog/integrations-core/blob/master/proxysql/datadog_checks/proxysql/ssl_utils.py#L17.
This can also be applied to recently updated SSL context checks, such as 
- `tls`: https://github.com/DataDog/integrations-core/pull/8230/files#r550231989
- `vertica`: …

Add optional argument for overriding get_tls_context() parameters

---

mongo/assets/configuration/spec.yaml
mongo/datadog_checks/mongo/collectors/replica.py
mongo/datadog_checks/mongo/data/conf.yaml.example
mongo/datadog_checks/mongo/mongo.py
mongo/tests/common.py
mongo/tests/compose/docker-compose.yml
mongo/tests/compose/scripts/init-router.js
mongo/tests/compose/scripts/init-shard01.js
mongo/tests/conftest.py
mongo/tests/fixtures/getCmdLineOpts-replica-arbiter
mongo/tests/fixtures/getCmdLineOpts-replica-arbiter-in-shard
mongo/tests/fixtures/replSetGetStatus-replica-arbiter
mongo/tests/fixtures/replSetGetStatus-replica-arbiter-in-shard
mongo/tests/results/metrics-replset-arbiter.json
mongo/tests/test_integration.py
mongo/tests/test_mongo.py
mongo/tox.ini

Better support for arbiter nodes:
- For collecting replica metrics, an additional connection is made to the primary in order to run the replSetGetConfig command
- Running `list_databases` on arbiters is forbidden, so skip it.
- Adds extensive fixture-based tests.

Better arbiter support

---

sqlserver/assets/recommended_monitors/sqlserver_ao_not_healthy.json
sqlserver/assets/recommended_monitors/sqlserver_db_not_online.json
sqlserver/assets/recommended_monitors/sqlserver_db_not_sync.json
sqlserver/assets/recommended_monitors/sqlserver_high_number_failed_auto_param.json
sqlserver/assets/recommended_monitors/sqlserver_high_processes_blocked.json
sqlserver/manifest.json

This PR adds 5 new recommended monitors for SQLServer.
1. `[SQLServer] Availability Group is not healthy`.
2. `[SQLServer] High number of processes blocked`.
3. `[SQLServer] High number of failed auto-parameterization attempts`.
4. `[SQLServer] Database is not marked for replication sync`.
5. `[SQLServer] Database is not online`

Add recommended monitors for SQLServer

---

haproxy/datadog_checks/haproxy/metrics.py
haproxy/metadata.csv
haproxy/tox.ini

typo in s/frontent/frontend/
this typo has been fixed upstream by commit:
http://git.haproxy.org/?p=haproxy.git;a=commit;h=1e3697635292b0f194171958a26766ae3e8d8453
and backported in all minor versions

Fix typo for ssl reuse metric

---

datadog_checks_base/datadog_checks/base/checks/prometheus/base_check.py
datadog_checks_base/datadog_checks/base/checks/prometheus/mixins.py
datadog_checks_base/datadog_checks/base/checks/prometheus/prometheus_base.py
datadog_checks_base/tests/test_prometheus.py

Update `PrometheusScraperMixin` to use `RequestWrapper` instead of directly using the `requests` python package

Update prometheus mixin to use the request wrapper

---

datadog_checks_base/datadog_checks/base/utils/aws.py
datadog_checks_base/tests/test_aws.py

This is a follow-up to: https://github.com/DataDog/integrations-core/pull/7353. A previous conversation on that PR (now removed due to a force push) suggested there may be a billing impact to adding the `host` tag to metrics. At the time, it was removed for investigation. I confirmed that host tags on metrics are not used for metering and will not impact host counts, so it is safe to add this tag back.
This tag will allow customers monitoring RDS instances to filter by `host:{rds_instance}` and group by `host`. Currently the tag set sent with metrics are:
```
["host:agent_hostname", ...other tags]
```
With this change, the tag set will be:
```
["host:agent_hostname", "host:rds_hostname", ...other tags]
```
If approved/merged, I will need help to cut a new release so postgres/mysql …

Add the `host` tag to RDS instances' parsed tags

---

datadog_checks_base/datadog_checks/base/utils/db/core.py
datadog_checks_base/tests/test_db.py

This PR adds the functionality to pass additional tags to the QueryManager after initialization.
In https://github.com/DataDog/integrations-core/pull/8282, I want to set the `replication_role` tag based on whether the instance is a reader or a writer. This has to be queried after a connection is made to the database.
It seems like the database integration classes are growing quite large and there is mixed access to instance-level state and function-level locals. Since my change requires tags to be mutable, I want to keep tags a function local variable and I don't see any cases where tags need to be stateful. I thought that this PR was the best way to go about making that change, but let me know if I'm heading in the wrong direction.
If we agree on this approach, I will update the …

Support tags set at runtime on the DB QueryManager

---

http_check/datadog_checks/http_check/http_check.py
http_check/tests/test_http_integration.py

This PR updates the http_check integration to use the TLS context wrapper rather than a custom wrapper.
Not too much needed to be changed, as the integration already used updated config parameters found in `instances/http`.

Update http_check to use TLS context wrapper

---

haproxy/datadog_checks/haproxy/metrics.py
haproxy/tests/common.py
haproxy/tests/conftest.py
haproxy/tests/legacy/common.py
haproxy/tests/legacy/test_haproxy.py
haproxy/tox.ini

haproxy: adding support for 2.3.x
in v2.3 two metrics are being renamed, so imply add them to the list,
but update tests to exclude them depending on versions
haproxy: sanitize the way we handle version
- use packaging.version
- move from table to string in metrics to check
- remove redundancy of legacy vs common

Adding support for v2.3

---

amazon_msk/assets/configuration/spec.yaml
amazon_msk/datadog_checks/amazon_msk/data/conf.yaml.example

Hide the `prometheus_url` option from Amazon MSK example config.
Customer and SE were confused about this option being present and marked as "required", but they didn't know what to put there.
Turns out the option is irrelevant to the MSK check:
https://github.com/DataDog/integrations-core/blob/2fdc311b8bfae5a4bc0a12e03b45934764dbff31/amazon_msk/datadog_checks/amazon_msk/amazon_msk.py#L33-L34
The check iterates through MSK nodes returned by the AWS API, and auto-fills the `prometheus_url` for each:
https://github.com/DataDog/integrations-core/blob/2fdc311b8bfae5a4bc0a12e03b45934764dbff31/amazon_msk/datadog_checks/amazon_msk/amazon_msk.py#L78-L82
As our test setup confirms, only `cluster_arn` is really required:
https://github.com/DataDog/integrations-core/blob/1bf1bcf5f4af4a54f16bf45ad76d5 …

Hide auto-populated prometheus_url from config spec

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/docs/default.yaml
datadog_checks_dev/datadog_checks/dev/tooling/templates/docs/example_nagios.yaml
datadog_checks_dev/datadog_checks/dev/tooling/templates/docs/example_rethinkdb.yaml
docs/developer/meta/docs-specs.md

Includes a draft of the specification for a new documentation spec format.  
Spec [rendered view](https://github.com/DataDog/integrations-core/blob/0abca820b02d6104cdc8cbf99eda47097bae06c4/docs/developer/meta/docs-specs.md).
Also includes notional templates consolidated into a single file for easier viewing, and two notional spec files for Nagios and RethinkDB.
Inspiration: Config specs - https://github.com/DataDog/integrations-core/pull/5072
- Link handling needs some more thought, but could be addressed incrementally.  Initially, the spec defines all links to be described within either the template or the spec file, but for often used links we should be able to abstract these to common patterns, like we use for our [docs pages](https://github.com/DataDog/integrations-core/blob/master/doc …

Initial draft of doc spec with examples

---

docs/developer/meta/docs-specs.md
mkdocs.yml

Cleanup for #7792
* Fix undefined links
* Add docs specs to nav, with a clear "warning: this is WIP" admonition.
This is making the `docs/build` job on master and PRs fail currently:
```
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
- meta/docs-specs.md 
WARNING -  mkdocstrings.plugin: meta/docs-specs.md: Could not find cross-reference target '[doc-spec-producer]' 
WARNING -  mkdocstrings.plugin: meta/docs-specs.md: Could not find cross-reference target '[doc-spec-templates]' 
```
#7792 was opened in October 2020, and `master` has not been merged into it since then before merging. But meanwhile we merged #8152 which enabled `--strict` build mode that would surface the issues seen on `master` now that #7792 has been merged.

Fix inclusion of docs spec draft in docs build

---

sqlserver/datadog_checks/sqlserver/metrics.py
sqlserver/tests/test_integration.py

With autodiscovery option enabled for `sqlserver`, certain tables will only provide data relative to the current database context.  [`sys.database_files`](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-database-files-transact-sql?view=sql-server-ver15) is one of those tables and we query it to extract two metrics: `sqlserver.database.files.size` and `sqlserver.database.files.state`.
Without this change we will report incorrect database statistics, all relative to the initial database.

Handle database specific queries for autodiscovery

---

openshift/README.md

Added additional instructions for applying the SCC using helm.  
Removed old "starting with version 6.1" message (don't believe this is necessary at this point). 
Customers aren't aware that the Helm chart can deploy the SCC automatically, so most folks are deploying the SCC directly. The SCC separate from the helm chart can occassionally be out of sync.

add SCC instructions for Helm for OpenShift

---

datadog_checks_base/tests/compose/kerberos-agent.yaml
datadog_checks_base/tests/compose/kerberos-agent/Dockerfile
datadog_checks_base/tests/compose/kerberos-agent/configurekerberos.sh
datadog_checks_base/tests/compose/kerberos-agent/configurenginx.sh
datadog_checks_base/tests/compose/kerberos-agent/entrypoint.sh
datadog_checks_base/tests/compose/kerberos-agent/nginx.yaml
datadog_checks_base/tests/compose/kerberos-kdc/init.sh
datadog_checks_base/tests/compose/kerberos-nginx/configurenginx.sh
datadog_checks_base/tests/compose/kerberos-nginx/setupkeytab.sh
datadog_checks_base/tests/compose/kerberos.yaml
datadog_checks_base/tests/conftest.py
datadog_checks_base/tests/test_http.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py

For Agent QA, it can be helpful to test our Kerberos authentication using the actual Agent container, rather than just a stub.
This adds an additional docker-compose setup for testing.
This currently relies on a manual inspection of the Agent check, but it could also be improved to be fully automated if that need arises.
Steps to utilize the test fixture:
1. Change test decorator from `True` to `False` to enable test
2. Edit compose/kerberos-agent/Dockerfile to appropriate Agent release
3. Run test via `ddev test -k test_kerberos_auth_with_agent datadog_checks_base:py38`
4. After compose builds, exec into Agent container via `docker exec -it compose_agent_1 /bin/bash`
5. Execute check via `agent check nginx` and verify successful result.
6. Exit test via Ctrl-C (test will show as failed, …

Add scaffolding for testing Agent with Kerberos

---

datadog_checks_dev/datadog_checks/dev/http.py

https://requests.readthedocs.io/en/master/api/#requests.Response.iter_lines
Allows for multiple streaming requests in a single test

Allow MockResponse method `iter_lines` to be called multiple times

---

datadog_checks_base/datadog_checks/base/utils/common.py

Often you'll want to cache a unit of work like a function based on conditions. However, if nothing needs to be done you must either check if the reference is `None` or create an anonymous function which can be costly.

Add `no_op` utility

---

.azure-pipelines/templates/run-tests.yml
.azure-pipelines/templates/test-single-linux.yml
datadog_checks_dev/datadog_checks/dev/plugin/tox.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py
datadog_checks_dev/datadog_checks/dev/tooling/dependencies.py

Updates `ddev test` command with two options:
- `--force-base-min` (renamed from `--force-base-package`) to detect the minimum specified version of `datadog-checks-base` that a check specifies, then attempt to install that version and run tests with it.  
- `--force-base-unpinned` which handles the use case of installing an unpinned version of `datadog-checks-base`. This has the effect of ensuring the latest released version of the package is tested, versus the editable development version.
The `force-base-min` option will have quite a few failures which may not be material, but would highlight opportunities to bump the requirement spec.  For example, when the exact minimum version doesn't exist:
```
❯ ddev test --force-base-min --force-env-rebuild redisdb:py38-latest
Running tests for …
```

Support installing minimum and unpinned datadog_checks_base dependencies for tests

---

datadog_checks_dev/datadog_checks/dev/tooling/specs/docs/spec.py
datadog_checks_dev/datadog_checks/dev/tooling/templates/docs/default.yaml
datadog_checks_dev/datadog_checks/dev/tooling/templates/docs/setup/configuration/log_collection.yaml
rethinkdb/README.md

Fix indentation of YAML snippets in `log_configuration.yaml`.
Prompted by https://github.com/DataDog/integrations-core/pull/7891/files#r557275622
Goal is to have these snippets align with the `1.` and `2.` items, instead of being at the regular left-hand side of the content area.
Take a look at the RethinkDB readme in prod: https://docs.datadoghq.com/integrations/rethinkdb
The logs snippets were dedented when adding docs specs: https://github.com/DataDog/integrations-core/pull/8355/files#diff-cc5366001ead2c6612aa8bc99ee3be2594b38d422259ae6e434a245788508c17L52-R63

Increase indentation of log snippets

---

snowflake/datadog_checks/snowflake/config.py
snowflake/tests/conftest.py
snowflake/tests/test_unit.py

The config validation would throw a configuration error if password is not configured. This PR ensures that password is only checked when using `snowflake` authenticator.

Do not throw configuration error for missing password when using OAuth

---

elastic/datadog_checks/elastic/elastic.py
elastic/datadog_checks/elastic/metrics.py
elastic/metadata.csv

Add a new `elasticsearch.index.health.reverse` that gives the same information as `elasticsearch.index.health` but with values aligned with `elasticsearch.cluster_status`
Resolve #8310 
Open to naming suggestions

Add index.health.reverse metric

---

docs/developer/base/tls.md
mkdocs.yml

This PR adds a new page for the TLS context wrapper on the Agent Integration docs.
This page includes one section:
- Using TlsContextWrapper from dev side

Add TLS docs page

---

sqlserver/datadog_checks/sqlserver/metrics.py
sqlserver/datadog_checks/sqlserver/sqlserver.py

In `sqlserver` check we have one query that aggregates data via `SUM` operation for the [`sys.dm_os_tasks`](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-tasks-transact-sql?view=sql-server-ver15) table.  The columns are defined as `int`s, but we have reports of this overflowing when the sum gets applied.  This fix casts the results into a `bigint` data type instead.
It also adds a try/except block around the sql query operations to guard against errors of this type in the future while still allowing the rest of the check to continue.  
Bug fix.

Handle overflow error for certain sql queries

---

sqlserver/datadog_checks/sqlserver/connection.py
sqlserver/tests/test_unit.py

According to the [`sys.databases`](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-databases-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15) documentation, if a database is offline then the value of `collation_name` will be NULL.  This PR guards against that condition and just assumes the database is case-insensitive (which is the default).

Handle offline databases for existence check

---

.codecov.yml

Openstack integration is currently at 50%, with a 75% target making the master CI fail.
Since this integration is kind of deprecated and not updated, I don't think it's worth adding new tests to fix the codecov check.

Decrease openstack codecov target

---

http_check/datadog_checks/http_check/http_check.py

This error is misleading and is causing some confusion. We don't know if the site is down, just that we cannot connect

Fix misleading debug message

---

datadog_checks_dev/datadog_checks/dev/tooling/specs/configuration/consumers/example.py
datadog_checks_dev/datadog_checks/dev/tooling/specs/configuration/spec.py
datadog_checks_dev/tests/tooling/configuration/consumers/test_example.py
datadog_checks_dev/tests/tooling/configuration/test_load.py
docs/developer/meta/config-specs.md

https://swagger.io/docs/specification/data-models/data-types/#mixed-type
Many integrations need this

Add config spec support for options with multiple types

---

clickhouse/datadog_checks/clickhouse/clickhouse.py
clickhouse/tests/test_unit.py

Clickhouse integration - in the connection to database, passes a setting that according to CH docs is only needed if a huge amount of incorrect syntax queries are passed.  The queries that this integration sends are all valid syntax.  With this setting being passed, the user account on the CH side must have permissions to modify its own settings, and therefore cannot just be a read-only account.
Removes the clickhouse_driver setting `calculate_text_stack_trace` to False.
With Clickhouse, if you pass any settings as part of the connection, the user account you're connecting with must not be read-only (as modifying a setting is a "write").
The only setting that is being passed is `calculate_text_stack_trace`.  According to [Clickhouse Docs this …

Remove `calculate_text_stack_trace` setting from Clickhouse Integration

---

datadog_checks_base/datadog_checks/base/checks/base.py

Correct the behavior to match the other submission methods
Noticed bug while working on the OpenMetrics rewrite
Integrations using `submit_histogram_bucket`:
- `mapr` - will not be affected b/c no `__NAMESPACE__`
- `azure_iot_edge` - defines a `__NAMESPACE__`, but was only just made public in 7.25.x and if any users have happened to enable `send_distribution_buckets` they likely are struggling to find the metrics in the UI

Properly support check namespacing for the `submit_histogram_bucket` method

---

mysql/datadog_checks/mysql/config.py
mysql/datadog_checks/mysql/mysql.py

Factor replica metrics and service check into its own methods and added more debug lines. Also stopped passing down params that are accessible through self. And put whole tag calculation on the config object creation

Refactor replica metrics and add some debug lines

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/stats/stats.py

Add option to export the list of merged PRs between 2 references as a CSV.
Command example:
```
ddev release stats merged-prs --from-ref 7.23.0-rc.1 --to-ref 7.23.0 --release-milestone 7.23.0 --export-csv ./changes_7_23.csv
```
Export all the changes (`datadog-agent` and `integrations-core`) made for 7.23.0 after the first rc in `changes_7_23.csv`.
Help release manager to keep track of all the changes.
Related PR to remove the release PRs from this list (#8351)

Add --export-csv option

---

datadog_checks_dev/setup.py
tox.ini

Docs CI builds are currently broken due to https://github.com/yaml/pyyaml/issues/478
I proposed to help there, but let's pin here until the issue gets fixed so contributors aren't confused.
Note that's we're already properly pinned in the `base` package, so not a problem for the upcoming Agent release.
https://github.com/DataDog/integrations-core/blob/8c8c8a6f342c8fd87034bedc07b5457c407996d7/datadog_checks_base/requirements.in#L18

Pin pyyaml in datadog_checks_dev

---

sidekiq/README.md

Updates code snippet of configuration step 2 (https://docs.datadoghq.com/integrations/sidekiq/#configuration) to include localhost instead of metrics.example.com and a note to add agent container address for containerized deployments
Customer Ticket: https://datadog.zendesk.com/agent/tickets/391292

Update step 2 of configuration to include localhost/agent container address for containerized deployment

---

ecs_fargate/README.md

At some point, this link got mixed up with another in the document and is now wrongly linking out to a blog post. This commit restores it to the correct example that's being referenced.

Fix link from fargate README.

---

mysql/assets/SERVICE_CHECK_CLARIFICATION.md
mysql/assets/service_checks.json
mysql/datadog_checks/mysql/mysql.py

`Slave_running` was not present in 5.7, is removed in 8.0 and it is redundant in any case so lets get rid of it
https://dev.mysql.com/doc/refman/5.7/en/server-status-variables.html#statvar_Slave_running

Simplify replication status check

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/tile/{check_name}/README.md

Fix conflicting links in template
First link should be a placeholder for integration site.

Fix conflicting link references in tile readme template

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/docs/setup/configuration/log_collection.yaml
rethinkdb/README.md

I based the logs docs off of rethinkdb for another integration(which uses the readme specs). this PR updates the wording/links to conf.yaml.example
Before, the following line contained long link:
```
Change the `path` parameter value based on your environment. See the https://github.com/DataDog/integrations-core/blob/master/rethinkdb/datadog_checks/rethinkdb/data/conf.yaml.example for all available configuration options.
```
Now, it is appropriately linked with text `sample conf.yaml`:
```
Change the `path` parameter value based on your environment. See the [sample conf.yaml][7] for all available configuration options.
```

Update logs template with docs feedback

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/manifest.json
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/manifest.json
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/manifest.json
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/tile/{check_name}/manifest.json

metrics_metadata is a field required if the integration contains a `metadata.csv`. This PR ensures that templates contain so they don't fail CI

Add metrics_metadata to templates

---

datadog_checks_dev/datadog_checks/dev/tooling/specs/docs/spec.py

The second part of the string didn't pass through the `f` processor leaving the double-`{` still in the resulting `MISSING` template string.

Minor error message fix

---

process/datadog_checks/process/cache.py
process/datadog_checks/process/process.py
process/tests/test_process.py

* follow-up from #8263
* adding a `reset` method to ProcessListCache
* also resetting this cache when pids cannot be found
see above and #8057
is caching even needed in Linux?
perhaps it will be better to skip it completely and only use it in Windows?

Clear process cache if cached PIDs not found

---

datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/scraper.py
datadog_checks_base/tests/openmetrics/test_options.py

So that all other configuration may reference the trimmed metric name, thus eliminating much confusion for users
I made this `Added` rather than `Fixed` since the legacy version did not do this:
https://github.com/DataDog/integrations-core/blob/45274b9e3657ed66a570f927393d925df3c2c353/datadog_checks_base/datadog_checks/base/checks/openmetrics/mixins.py#L422-L432

Remove any OpenMetrics metric prefixes immediately during parsing

---

datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/transform.py
datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/transformers/__init__.py
datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/transformers/rate.py
datadog_checks_base/tests/openmetrics/test_transformers/test_rate.py

Uncommon, but some integrations use it:
https://github.com/DataDog/integrations-core/blob/afa78a2b91fe1f904c2025e298ec25b2e22c3cfd/linkerd/datadog_checks/linkerd/metrics.py#L102-L108

Add `rate` OpenMetrics transformer

---

datadog_checks_base/datadog_checks/base/__init__.py
datadog_checks_base/datadog_checks/base/checks/openmetrics/base_check.py
datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/base.py
datadog_checks_base/tests/openmetrics/test_bench.py
datadog_checks_base/tests/openmetrics/test_interface.py
datadog_checks_base/tests/openmetrics/utils.py
haproxy/datadog_checks/haproxy/check.py
istio/datadog_checks/istio/istio.py

This makes it so that checks must explicitly opt-in to the conditional use of the latest implementation with their own `__new__` method like so:
```python
class Check(OpenMetricsBaseCheck):
def __new__(cls, name, init_config, instances):
instance = instances[0]
if not PY2 and 'openmetrics_endpoint' in instance:
return NewCheck(name, init_config, instances)
else:
return super(Check, cls).__new__(cls)
```
As shown when running tests on the first commit of this PR, checks that enable the new functionality did not have their class data available to `OpenMetricsBaseCheckV2`. This makes sense of course since there is no intrinsic relationship, but was an oversight in the test cases.
As a workaround, I tried:
```python
def __new__(cls, *args, **kwargs):
if kwargs or len(args) != 3 or not …
```

Remove class substitution logic for new OpenMetrics base class

---

sqlserver/datadog_checks/sqlserver/metrics.py

Observed via log files that the fix from #8329 would add the same database for each metric in the table, resulting in duplicate queries.  Changing class collection to a set will avoid duplicates.

Avoid redundant queries

---

.azure-pipelines/changes.yml
.azure-pipelines/templates/test-all-checks.yml
network/datadog_checks/network/network.py
network/tests/test_network.py

`fcntl` is not importable on Windows, so we have to create a try/except clause for its import so that the check itself is importable on Windows.

Ensure network check doesn't fail on importing fcntl on Windows

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/dep.py

Fix behavior of `ddev validate dep <check>`
Found during QA for #8297 
Currently `$ ddev validate dep nginx` fails with a large list of errors:
```console
$ ddev validate dep nginx
Stale dependency needs to be removed by syncing: adodbapi
Stale dependency needs to be removed by syncing: aerospike
Stale dependency needs to be removed by syncing: aws-requests-auth
[...]
Stale dependency needs to be removed by syncing: uptime
Stale dependency needs to be removed by syncing: vertica-python
Stale dependency needs to be removed by syncing: win-inet-pton
```
This is because when passing a `<check>`, we currently still validate `check_dependencies` (which only contains the deps for `<check>`, rather than the set of all deps for all checks) against `agent_dependencies` (which contains all …

Fix validation of Agent deps when using single check

---

datadog_checks_dev/datadog_checks/dev/tooling/specs/configuration/consumers/example.py
datadog_checks_dev/tests/tooling/configuration/consumers/test_example.py

```
File "C:\Users\ofek\AppData\Local\Programs\Python\Python38\Scripts\ddev-script.py", line 30, in <module>
sys.exit(load_entry_point('datadog-checks-dev', 'console_scripts', 'ddev')())
File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 782, in main
rv = self.invoke(ctx)
File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1259, in invoke
return …
```

Fix handling of multiple nested types for the example config spec consumer

---

redisdb/metadata.csv

Fix `redis.cpu.*` metrics unit.
The raw values are in seconds https://redis.io/commands/info https://stackoverflow.com/questions/20680032/what-unit-is-used-to-display-redis-cpu-usage
But we submit it as a rate https://github.com/DataDog/integrations-core/blob/43ab9f9ae5ca7436eeff6a0cc7219b65b45b510d/redisdb/datadog_checks/redisdb/redisdb.py#L251
So the metrics have no unit
Also fixing `redis.stats.keyspace_*` metric unit

Fix redis metadata units

---

containerd/README.md

The default conf file is called https://github.com/DataDog/datadog-agent/blob/master/cmd/agent/dist/conf.d/containerd.d/conf.yaml.default not https://github.com/DataDog/datadog-agent/blob/master/cmd/agent/dist/conf.d/containerd.d/conf.yaml.example
Page not found: https://a.cl.ly/Jru1AvWN

sample config file page not found

---

datadog_checks_base/tests/test_http.py

Cleanup for #8234 
Add note that in case of errors while using the Kerberos setup, developer might have to rebuild fresh images.
Found while testing #8234 
Spent a fair amount of time figuring out why the Kerberos wouldn't work on my machine. @mgarabed and I eventually figured out I had older versions of the custom-built images, and `ddev test` doesn't rebuild those automatically.

Add note hinting to rebuild Kerberos images

---

glusterfs/datadog_checks/glusterfs/check.py

Properly handle sudo access error.
Found while testing #8159 during QA
To test for sudo access we run:
```console
$ sudo -ln <cmd>
```
This should output the command path on stdout if sudo access is available, eg:
```console
$ sudo -s
(root) $ sudo -ln test
/usr/local/opt/coreutils/libexec/gnubin/test
```
If sudo access is not available, we either get a non-0 error code and/or empty output. Eg on macOS we get both:
```console
$ sudo -ln test
sudo: a password is required
```
So right now we get an unhelpful "output empty" error:
```console
Error: get_subprocess_output expected output but had none.
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 901, in run
File …
```

Fix error handling when Agent has no sudo access

---

glusterfs/assets/dashboards/red_hat_gluster_storage.json

Fix path to logo image in GlusterFS dashboard
Current path does not exist and results in a "blank" image widget (error in browser console):
```console
GET https://static.datadoghq.com/static/images/saas_logos/bot/red_hat_gluster_storage@2x.png 403
```
Fixed path to point to correct path in `web-ui`: https://github.com/DataDog/web-ui/blob/prod/public/static/images/saas_logos/bot/glusterfs@2x.png

Fix GlusterFS dashboard logo path

---

sqlserver/datadog_checks/sqlserver/metrics.py

In some implementations, the `cursor.execute()` call will return None, and cannot be chained with a `fetchall()` method.
This breaks it into the more common approach of separate method calls.
Noted specifically on Windows using the default connection library.

Fix cursor execution returning None

---

datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/transformers/summary.py
datadog_checks_base/tests/openmetrics/test_transformers/test_summary.py

Found bug during QA. Remapped summary metrics are not submitting quantile metrics.
In V2, the following config only yields 15 metrics because `openmetrics.target_interval_seconds.quantile` were not being submitted.
```
init_config: {}
instances:
- metrics:
- prometheus_target_interval_length_seconds: target_interval_seconds
- prometheus_http_request_duration_seconds: http_req_duration_seconds
- go_memstats_mallocs_total
- go_memstats_alloc_bytes
namespace: openmetrics
openmetrics_endpoint: http://localhost:9090/metrics
```

Fix Prometheus summary quantile metrics

---

mysql/datadog_checks/mysql/mysql.py
mysql/tests/test_mysql.py

Having `slave_io_running=False` and `slave_sql_running=False` set the service check as WARNING, but it should be CRITICAL.
QA

Fix condition for replication status

---

elastic/tox.ini

Elastic 7.0 ended life in October 2020 https://www.elastic.co/support/eol

Remove EOLed elastic version

---

postgres/datadog_checks/postgres/metrics_cache.py
postgres/datadog_checks/postgres/postgres.py
postgres/tests/test_metrics_cache.py

Previously we were only skipping replication metrics in Aurora < 10, they should be skipped in all versions

Do not run replication metrics on newer aurora versions either

---

ceph/datadog_checks/ceph/ceph.py

Ceph is flaking on CI with following errors:
```
__________________________________ test_check __________________________________
tests/test_integration.py:18: in test_check
ceph_check.check(copy.deepcopy(BASIC_CONFIG))
datadog_checks/ceph/ceph.py:319: in check
raw = self._collect_raw(ceph_cmd, ceph_cluster, instance)
datadog_checks/ceph/ceph.py:73: in _collect_raw
mon_map = raw['status']['monmap']
E   KeyError: 'status'
---------------------------- Captured stderr setup -----------------------------
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Creating network "compose_default" with the default driver
Creating dd-test-ceph ... …
```

Fail more gracefully

---

datadog_checks_base/datadog_checks/base/stubs/_util.py

Provide error message, if any, when there is no subprocess output to better diagnose the issue

Provide error message on subprocess output

---

postgres/datadog_checks/postgres/statements.py

Removes a query to `information_schema` which requires different permissions from what our documentation grants. This change gets the required columns for querying pg_stat_statements directly from the view/function used.
We ran into an issue with later versions of postgres on aurora where the `pg_stat_statements` view is owned by user `rdsadmin` and therefore the column names of the view are not exposed in information_schema.

Fix Postgres statements to remove information_schema query

---

tcp_queue_length/README.md

Setting system_probe_config.enabled=true can cause network performance monitoring to get inadvertently enabled.  Our docs should not require this!

Update agent version and config requirements for tcp_queue_length

---

elastic/assets/configuration/spec.yaml
elastic/datadog_checks/elastic/config.py
elastic/datadog_checks/elastic/data/conf.yaml.example
elastic/datadog_checks/elastic/elastic.py
elastic/tests/test_elastic.py

Fix #8335 and disable SLM metrics by default.
`manage_slm` seems not to be part of the `manage` permission, which causes 403 error when trying to get slm metrics.

Disable SLM metrics by default

---

cacti/README.md
cacti/tests/compose/Dockerfile
cacti/tests/compose/restore.sh

Cacti tests are failing
```
---------------------------- Captured stderr setup -----------------------------
Creating network "compose_default" with the default driver
Building cacti
Service 'cacti' failed to build : manifest for quantumobject/docker-cacti:1.2.8 not found: manifest unknown: manifest unknown
=========================== 1 error in 7.59 seconds ============================
```
It seems that since 2 days ago the only tag for that docker image is `latest` https://hub.docker.com/r/quantumobject/docker-cacti/tags
The restore script has been deleted https://github.com/QuantumObject/docker-cacti/commit/5ab073d64e1a6d5626ddc6a8d767e1bb189d66f2

Fix cacti e2e

---

tls/tests/conftest.py

```
docker: Error response from daemon: invalid mode: \Users\ofek\Desktop\code\integrations-core\tls\tests\compose\ca.crt.
```

Fix tests on Windows

---

datadog_checks_dev/datadog_checks/dev/tooling/specs/docs/spec.py
datadog_checks_dev/tests/tooling/docs/test_load.py

Add more tests for docs validator. New tests check for functionality of nested sections. There was a fix provided for the name of nested sections not being included in the error messages.

fix nested sections in docs validator

---

datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/scraper.py
datadog_checks_base/tests/openmetrics/test_compat_scraper.py
datadog_checks_base/tests/openmetrics/test_interface.py
datadog_checks_base/tests/openmetrics/utils.py
linkerd/tests/common.py
linkerd/tests/test_linkerd.py

This makes it so that users of existing OpenMetrics checks can enable the new implementation (when supported) by only setting `openmetrics_endpoint`
Avoid displaying both configs; only `openmetrics_endpoint` will be documented until full deprecation

Add support for legacy config to OpenMetricsCompatibilityScraper

---

scylla/assets/monitors/instance_down.json
sonarqube/assets/recommended_monitors/vulnerabilities.json

Monitor teams are working on making `metric alert` and `query alert` be the same, they advise us to only keep `query alert`.

Convert monitor to query alert

---

aerospike/datadog_checks/aerospike/aerospike.py

fixes
```
During handling of the above exception, another exception occurred:
tests/test_aerospike.py:22: in test_check
check.check(None)
datadog_checks/aerospike/aerospike.py:116: in check
self.collect_info('statistics', CLUSTER_METRIC_TYPE, required_keys=self._metrics, tags=self._tags)
datadog_checks/aerospike/aerospike.py:189: in collect_info
entries = self.get_info(command, separator=separator)
datadog_checks/aerospike/aerospike.py:256: in get_info
self.log.warning("Command `%s` was unsuccessful: %s"(command, str(e)))
E   TypeError: 'str' object is not callable
```

Fix logging

---

tls/assets/configuration/spec.yaml
tls/datadog_checks/tls/data/conf.yaml.example

https://github.com/DataDog/integrations-core/pull/5694

Remove outdated description of `local_cert_path` option

---

tls/assets/configuration/spec.yaml
tls/datadog_checks/tls/data/conf.yaml.example
tls/datadog_checks/tls/tls.py
tls/tests/conftest.py
tls/tests/test_remote.py

A great deal of support cases are due to incomplete cert chains; this should solve the majority of them
- See https://bugs.python.org/issue18617
- The test utilizes https://badssl.com rather than a locally generated cert. In future we should make that

Implement AIA chasing

---

mysql/assets/configuration/spec.yaml
mysql/datadog_checks/mysql/data/conf.yaml.example
postgres/assets/configuration/spec.yaml
postgres/datadog_checks/postgres/data/conf.yaml.example

Changes the example config for integrations to default to `false`. This is to avoid customers copying the default config and accidentally opting into beta features. While the "default" value was false, the "example" value was true.
Since this is only a documentation change, I grouped both mysql and postgres integrations together.

Change example configs for databases to default to deep_database_monitoring: false

---

nginx/tests/fixtures/plus_api_stream_zone_sync.json
nginx/tests/test_unit.py

Since there isn't a direct way to test against the Plus API, added a small enhancement to ensure that we are extracting tags from the new endpoint, using the [example](https://nginx.org/en/docs/http/ngx_http_api_module.html?_ga=2.265971592.646968122.1610742992-1877968259.1610742992#def_nginx_stream_zone_sync) from the docs.

Enhance test for API v3

---

datadog_checks_dev/datadog_checks/dev/tooling/specs/configuration/spec.py
datadog_checks_dev/tests/tooling/configuration/test_load.py

See https://swagger.io/docs/specification/data-models/dictionaries/
https://github.com/DataDog/integrations-core/pull/8452/files

Support `additionalProperties` object field for config specs

---

datadog_checks_dev/datadog_checks/dev/tooling/specs/docs/consumers/readme.py

Handles the case where a section contains subsections in the readme rendering. 
READMEs were not rendering properly. 
Example of fix:
Say we have:
`section = [s1, s2, s3]` and `s2` has subsections `s2.1, s2.2`
we would want to process the list as follows: 
`section = [s1, s2, s2.1, s2.2, s3]`

fix nested sections for readme rendering

---

airflow/README.md

Update broken hyperlink in our Airflow Integration public document: https://docs.datadoghq.com/integrations/airflow/?tab=host#airflow-datadoghook 
Broken hyperlink was reported via Zendesk ticket: https://datadog.zendesk.com/agent/tickets/442208
I want to ensure other customers don't come across this problem so that's why I want this fixed.
None.

Update broken link to Airflow Apache Page - 442208

---

aerospike/datadog_checks/aerospike/aerospike.py
aerospike/tox.ini

Fixes:
```
tests/test_aerospike.py:35: in test_version_metadata
check.check(None)
datadog_checks/aerospike/aerospike.py:116: in check
self.collect_info('statistics', CLUSTER_METRIC_TYPE, required_keys=self._metrics, tags=self._tags)
datadog_checks/aerospike/aerospike.py:193: in collect_info
for entry in entries:
E   TypeError: 'NoneType' object is not iterable
```
And
```
tests/test_aerospike.py:35: in test_version_metadata
check.check(None)
datadog_checks/aerospike/aerospike.py:148: in check
version = self.collect_version()
datadog_checks/aerospike/aerospike.py:172: in collect_version
raw_version = self.get_info("build")[0]
E   IndexError: list index out of range
```
Raised an internal issue to fix the underlying flakeyness

Return empty array instead of None

---

datadog_checks_dev/datadog_checks/dev/tooling/specs/configuration/spec.py

Properly require `example` only at the top level

Fix `oneOf` in config specs

---

datadog_checks_dev/datadog_checks/dev/tooling/specs/docs/core.py
datadog_checks_dev/tests/tooling/docs/test_load.py

Handles the case when there are nested sections with links in the `description` tab.

Normalize links in docs validator for nested sections

---

tls/datadog_checks/tls/tls.py
tls/tests/test_config.py

The `validate_cert` option is not backwards compatible with the tls context remapper.
https://github.com/DataDog/integrations-core/blob/7.23.x/tls/datadog_checks/tls/data/conf.yaml.example#L62-L71

Include validate_cert in backwards compatibility remapper

---

requirements-agent-release.txt
tls/CHANGELOG.md
tls/datadog_checks/tls/__about__.py

Manually release TLS check.
* Prepare 7.26.0-rc.4
* Manual release bc other unrelated `Added` changes were added in `master` since last 7.26.0 bug fix.

Manually release tls to 2.1.1

---

datadog_checks_dev/datadog_checks/dev/tooling/specs/docs/consumers/readme.py
datadog_checks_dev/datadog_checks/dev/tooling/specs/docs/core.py
datadog_checks_dev/tests/tooling/docs/test_load.py

Implements the functionality for the `prepend_section` and `append_section` options in docs validator. Validates these sections as well as adds them to the output document. 
These two options are useful for overrides in templates. It allows you to use a commonly used template for different sections of our integrations docs but allows you to add specific remarks before and after the template without having to override the description. Additionally, if we modify the way we do something (eg. installation) the template for installation can be modified and would be reflected on all integrations that use the template, making it more scalable.
`spec.yaml`
```
name: Nginx
files:
- name: README.md
sections:
- template: overview
overrides:
prepend_text: This is prepended text.
append_text: This is …
```

Implement append and prepend options for docs validator

---

istio/README.md

Clarify disabling sidecar injection is for Datadog agent pods only

Clarify set up instructions

---

datadog_checks_dev/datadog_checks/dev/tooling/specs/docs/consumers/readme.py

Fixed an issue where links in `prepend_text` and `append_text` were not being converted into references. This meant that something like this:
```
name: integration_id
files:
- name: README.md
sections:
- name: cool section
header_level: 1
prepend_text: |
[cool link][1]
[1]: link.com
description: |
[another cool link][1]
[1]: foo.com
```
would generate a `README.md` as such
```
...
[cool link][link.com]
[another cool link][1]
[1]: foo.com
```
The fix will process links in `prepend_text` and `append_text` and generate a `README.md` as such.
```
...
[cool link][1]
[another cool link][2]
[1]: link.com
[2]: foo.com
```

Fix link referencing for append and prepend

---

mongo/README.md

The 2.6+ version requirement in the ReadMe comes from a limitation of the pymongo library.
Besides pymongo, we also rely on specific commands including `replSetGetConfig` that requries v3.0+ of mongo.
Mongo 2.6 is EOL since October 2016, the next version is 3.0 which is EOL since Feb 2018: https://www.mongodb.com/support-policy

Update minimum mongo version requirement

---

datadog_checks_dev/datadog_checks/dev/tooling/specs/docs/consumers/readme.py
datadog_checks_dev/tests/tooling/docs/consumers/__init__.py
datadog_checks_dev/tests/tooling/docs/consumers/test_readme.py
datadog_checks_dev/tests/tooling/docs/test_load.py
datadog_checks_dev/tests/tooling/docs/utils.py

Fixes an issue where the readme consumer was not parsing sections with `tab` attributes correctly. It would assume each section was its own `tab` rather than grouping multiple tabs together, as we would want to display in our [docs](https://docs.datadoghq.com/integrations/nginx/?tab=host#configuration)
For better understanding of this issue, check out this PR for nginx docs spec using the current readme consumer (https://github.com/DataDog/integrations-core/pull/8549). This [comment](https://github.com/DataDog/integrations-core/pull/8549#discussion_r571228833) plus the diff might be useful to understand the issue.  
This solution was developed with two assumptions:
- All `tab` attributes exist as top level sections. 
- Adjacent sections with a `tab` attribute are to be grouped together. …

Fix tabs in readme consumer

---

amazon_msk/README.md

PR added a line in Installation -> Set up to include, enabling prometheus monitoring on the MSK side for the integration to work.
Ticket #443176
Please review the steps, and the ticket #443176 has more details

Added enabling Prometheus monitoring

---

sonarqube/assets/configuration/spec.yaml
sonarqube/datadog_checks/sonarqube/check.py
sonarqube/datadog_checks/sonarqube/data/conf.yaml.example
sonarqube/datadog_checks/sonarqube/data/metrics.yaml

Signed-off-by: Daniel Bright <daniel.bright@datadoghq.com>
This PR updates the SonarQube check to exclude specific, problematic metrics that are identified by the `key` of `new_.*`, these metrics are used in the SonarQube dashboard to indicate "new" items between the most current scan and the last scan, they also break metric collection due to their format, example `new_blocker_violations`:
```json
{
"metric": "new_blocker_violations",
"periods": [
{
"index": 1,
"value": "0",
"bestValue": true
}
],
"period": {
"index": 1,
"value": "0",
"bestValue": true
}
},
```
Versus a valid metric, `blocker_violations`: 
```json
{
"metric": "blocker_violations",
"value": "0",
"bestValue": true
},
```
Zendesk request
I cannot see why these metrics would be valid other than use on the SonarQube …

Fix automatic discovery of metrics from web API and improve example config documentation

---

kubelet/datadog_checks/kubelet/kubelet.py
kubelet/tests/test_kubelet.py

Fix issue where retrieved pod_list is occasionally `None`, leading to a `TypeError` when attempting to loop through the variable.
Prevent an ERROR log

[kubelet] Fix TypeError when retrieved pod_list is occasionally None

---

cassandra_nodetool/tox.ini

Image tag `3.0` recently changed to `3.0.23` and it broke integration tests, because the nodes in the cluster test didn't have the same version. Pinning the image patch version solves this.
Error: `There are nodes in the cluster with a different schema version than us we did not merged schemas from, our version`

Pin cassandra test version

---

yarn/datadog_checks/yarn/yarn.py

This PR ensures that the check will not fail on KeyError when there is an empty list for app/node/queue.
Resolves https://github.com/DataDog/integrations-core/issues/8553

Avoid failing on KeyError

---

hdfs_namenode/datadog_checks/hdfs_namenode/hdfs_namenode.py

Do not submit `hdfs.namenode.capacity_in_use` if CapacityTotal is 0.
Resolves https://github.com/DataDog/integrations-core/issues/8564

Avoid ZeroDivisionError for hdfs.namenode.capacity_in_use 

---

elastic/assets/configuration/spec.yaml
elastic/assets/dashboards/overview.json
elastic/datadog_checks/elastic/data/conf.yaml.example
elastic/datadog_checks/elastic/elastic.py
elastic/tests/common.py
elastic/tests/conftest.py
elastic/tests/test_elastic.py

The `cluster_name` tag is submitted for container environments. This PR introduces an option to disable the commonly used tag and renames the cluster tag to `elastic_cluster`.
This PR also updates the template var used in the OOTB dashboard to use new tag.
Customer support

Rename cluster_name tag to elastic_cluster

---

vault/assets/configuration/spec.yaml
vault/datadog_checks/vault/data/conf.yaml.example
vault/datadog_checks/vault/vault.py
vault/tests/test_integration.py
vault/tests/test_vault.py

This PR introduces a backwards compatible config option `disable_legacy_cluster_tag` which will stop sending `cluster_name` tag.
`cluster_name` tag is also emitted at the hostlevel. Using a service specific tag key will prevent conflicts/confusion.

Rename cluster_name tag to vault_cluster

---

openstack/metadata.csv
openstack_controller/metadata.csv

Fix unit from gibibyte to mebibyte
The ram units are in MB, not GB:
https://github.com/gophercloud/gophercloud/blob/v0.15.0/openstack/compute/v2/extensions/limits/results.go#L54-L56
https://github.com/gophercloud/gophercloud/blob/v0.15.0/openstack/compute/v2/extensions/limits/results.go#L67-L68
https://docs.openstack.org/api-guide/compute/limits.html

Fix unit from gibibyte to mebibyte

---

activemq/assets/dashboards/activemq_dashboard.json
activemq/manifest.json
datadog_checks_dev/datadog_checks/dev/tooling/utils.py

Migrates the original timeboard from `dogweb` to `integrations-core` for compatibility.
[dogweb PR](https://github.com/DataDog/dogweb/pull/56434)
[Staging link](https://dd.datad0g.com/screen/integration/29/activemq---overview?from_ts=1613062336154&to_ts=1613062636154&live=true)

Migrate old activemq dashboard

---

cisco_aci/CHANGELOG.md
cisco_aci/datadog_checks/cisco_aci/__about__.py
datadog_checks_base/CHANGELOG.md
datadog_checks_base/datadog_checks/base/__about__.py
http_check/CHANGELOG.md
http_check/datadog_checks/http_check/__about__.py
mysql/CHANGELOG.md
mysql/datadog_checks/mysql/__about__.py
tls/CHANGELOG.md
tls/datadog_checks/tls/__about__.py

Manual release of
* `datadog_checks_base`
* `tls`
* `mysql`
* `http_check`
* `cisco_aci`
Release #8611 for 7.26.0
Note: no further step required after this gets merged (no push to PyPI for `base`, no tagging), since this is a manual release only for the purpose of 7.26.0. See also similar PRs: #8544, #8514

Manually release integrations following cryptography bump

---

cilium/assets/configuration/spec.yaml
couch/assets/configuration/spec.yaml
datadog_checks_dev/tests/tooling/configuration/consumers/test_example.py
mysql/assets/configuration/spec.yaml
varnish/assets/configuration/spec.yaml

Adhere to https://datadoghq.dev/integrations-core/meta/config-specs/#example-file-consumer
Encountered while working on the upcoming data model consumer

Clean up cases where `display_default` should be null

---

yarn/assets/configuration/spec.yaml
yarn/datadog_checks/yarn/data/conf.yaml.example
yarn/datadog_checks/yarn/yarn.py
yarn/tests/common.py
yarn/tests/test_integration.py
yarn/tests/test_yarn.py

This PR introduces a backwards compatible config option disable_legacy_cluster_tag which will stop sending cluster_name tag.
cluster_name tag is also emitted at the hostlevel. Using a service specific tag key will prevent conflicts/confusion.

Rename cluster_name tag to yarn_cluster

---

sqlserver/assets/configuration/spec.yaml
sqlserver/datadog_checks/sqlserver/connection.py
sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
sqlserver/datadog_checks/sqlserver/sqlserver.py
sqlserver/tests/test_connection.py

We add config options to the connection string even if they are already there. This change prevents options to be added twice the connection string

Clarify windows user and validate connection options

---

vault/tox.ini

Avoid:
```
tests/conftest.py:66: in dd_environment
with docker_run(
/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/contextlib.py:113: in __enter__
return next(self.gen)
../datadog_checks_dev/datadog_checks/dev/docker.py:208: in docker_run
with environment_run(
/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/contextlib.py:113: in __enter__
return next(self.gen)
../datadog_checks_dev/datadog_checks/dev/env.py:73: in environment_run
condition()
tests/conftest.py:105: in __call__
raise Exception(result.stderr)
E   Exception: WARNING: Error loading config file: .dockercfg: $HOME is not defined
- generated xml file: /home/vsts/work/1/s/vault/.junit/test-unit-py38-noauth.xml
```

Add HOME env var

---

datadog_checks_dev/datadog_checks/dev/tooling/specs/configuration/consumers/example.py
datadog_checks_dev/datadog_checks/dev/tooling/specs/configuration/spec.py
datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/openmetrics.yaml
datadog_checks_dev/tests/tooling/configuration/consumers/test_example.py
datadog_checks_dev/tests/tooling/configuration/test_load.py

- Semantically, we already use it as `anyOf`. See: https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/
- Overcome https://github.com/koxudaxi/datamodel-code-generator/issues/333

Replace `oneOf` with `anyOf` for multi-type support

---

sap_hana/datadog_checks/sap_hana/sap_hana.py

Handle:
```
datadog_checks/sap_hana/sap_hana.py:102: in check
self._conn.close()
.tox/py38/lib/python3.8/site-packages/pyhdb/connection.py:168: in close
reply = self.send_request(request)
.tox/py38/lib/python3.8/site-packages/pyhdb/connection.py:84: in send_request
return self.__send_message_recv_reply(payload.getvalue())
.tox/py38/lib/python3.8/site-packages/pyhdb/connection.py:121: in __send_message_recv_reply
raise OperationalError("Lost connection to HANA server (%r)" % error)
E   pyhdb.exceptions.OperationalError: Lost connection to HANA server (BrokenPipeError(32, 'Broken pipe'))
```
Related: https://github.com/SAP/PyHDB/issues/68

Catch exception when closing lost connection

---

mysql/assets/monitors/replica_running.json
mysql/assets/monitors/select_query_rate.json
mysql/manifest.json

Added recommended monitors for MySQL
[Staging link](https://dd.datad0g.com/monitors#create/integration?recommendedMonitorID=mysql_select_query_rate)
Recommended monitor coverage
This monitor ("alert in case of SELECT query rate below usual bounds") is inspired by the MySQL blog post and dashboard:
> The current rate of queries will naturally rise and fall, and as such it’s not always an actionable metric based on fixed thresholds. But it is worthwhile to alert on sudden changes in query volume—drastic drops in throughput, especially, can indicate a serious problem.

Add MySQL recommended monitors

---

cisco_aci/assets/dashboards/cisco_aci_dashboard.json
cisco_aci/manifest.json
consul/assets/dashboards/consul_dashboard.json
consul/manifest.json
kubernetes/assets/dashboards/kubernetes_dashboard.json
kubernetes/manifest.json

- cisco_aci [Staging Link](https://dd.datad0g.com/screen/integration/129/cisco-aci-overview?from_ts=1613078418227&to_ts=1613082018227&live=true)
- consul [Staging Link](https://dd.datad0g.com/screen/integration/83/consul---overview?from_ts=1613078015516&to_ts=1613081615516&live=true)
- kubernetes [Staging Link](https://dd.datad0g.com/screen/integration/86/kubernetes-overview?from_ts=1613078403380&live=true&to_ts=1613082003380)
[Dogweb PR](https://github.com/DataDog/dogweb/pull/56445)
Compatibility

Migrate cisco_aci, consul, kubernetes dashboards

---

spark/datadog_checks/spark/spark.py
spark/tests/test_spark.py

Extending https://github.com/DataDog/integrations-core/pull/5552/
Some spark applications can disable the UI explicitly (by setting spark.ui.enabled=false). In such a case, api request for that particular apps are redirected to the master (which doesn't provide the required information).
This PR skips any apps that raises any exception, in order to continue monitoring of valid applications.

Skip apps which have the UI disabled

---

elastic/assets/configuration/spec.yaml
elastic/datadog_checks/elastic/data/conf.yaml.example
vault/assets/configuration/spec.yaml
vault/datadog_checks/vault/data/conf.yaml.example
yarn/assets/configuration/spec.yaml
yarn/datadog_checks/yarn/data/conf.yaml.example

Enable `disable_legacy_cluster_tag` by default
New configurations of the integration will not be using cluster_name tag

Enable disable_legacy_cluster_tag option

---

kafka_consumer/README.md

Add documentation on log collection for the `kafka_consumer` check.
* Log collection coverage
* No log support to add, since `kafka_consumer` does not monitor a separate technology (it only collects metrics about consumer offsets), and `kafka` and `zk` integrations already cover log collection for Kafka and ZooKeeper respectively.
* For some reason link numbers don't start from 1. Will submit a separate PR for this, to keep things cleaner.
* Status will be marked as "done" in [Status](https://datadoghq.dev/integrations-core/meta/status/) thanks to the "Log collection" header (see also `cassandra_nodetool` via #8387).

Add documentation for Kafka Consumer log collection

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/manifest.py

Fixes a bug where the error printing fails if the JSON schema error is about a list object. 
Ensures all elements of the jsonschema path are strings before trying to join them together
Resolves errors like:
```
f'  {"->".join(error.absolute_path)}:{error.message}'
*** TypeError: sequence item 1: expected str instance, int found
```

Fix error printing json errors when error on list object

---

airflow/README.md
airflow/metadata.csv

Fix `aiflow` prefix typo

---

mkdocs.yml
tox.ini

Upgrade `mkdocs-click` to `0.3.*`.
Benefit from improvements to improve https://datadoghq.dev/integrations-core/ddev/cli/, in particular:
* New table format -- https://github.com/DataDog/mkdocs-click/pull/25
* Now headers show full command paths (eg `ddev release make all` instead of `all`) -- https://github.com/DataDog/mkdocs-click/pull/36
(Full `mkdocs-click` changelog: https://github.com/DataDog/mkdocs-click/releases/tag/0.3.0)
Here's what it looks like now :-)

Upgrade mkdocs-click

---

datadog_checks_dev/datadog_checks/dev/tooling/create.py

Removes the `marketplace` type option for `ddev create` command. 
Marketplace integrations are created by setting `repo = "marketplace"` via `ddev config set repo marketplace`. Additionally, the `ddev create -t marketplace` command was not working as expected.

Remove marketplace option for ddev create

---

win32_event_log/assets/configuration/spec.yaml
win32_event_log/datadog_checks/win32_event_log/constants.py
win32_event_log/datadog_checks/win32_event_log/data/conf.yaml.example
win32_event_log/datadog_checks/win32_event_log/filters.py
win32_event_log/tests/test_filters.py

`audit success` and `audit failures` event types cannot be queried using Levels, they have to be queried with "Keywords"

Fix queries for audit success/failure

---

spark/assets/configuration/spec.yaml
spark/datadog_checks/spark/data/conf.yaml.example
spark/datadog_checks/spark/spark.py
spark/tests/common.py
spark/tests/test_e2e.py
spark/tests/test_spark.py

This PR introduces a backwards compatible config option disable_legacy_cluster_tag which will stop sending cluster_name tag.
cluster_name tag is also emitted at the hostlevel. Using a service specific tag key will prevent conflicts/confusion.

Rename cluster_name tag to spark_cluster

---

mapreduce/assets/configuration/spec.yaml
mapreduce/datadog_checks/mapreduce/data/conf.yaml.example
mapreduce/datadog_checks/mapreduce/mapreduce.py
mapreduce/tests/common.py
mapreduce/tests/test_mapreduce.py

This PR introduces a backwards compatible config option disable_legacy_cluster_tag which will stop sending cluster_name tag.
cluster_name tag is also emitted at the hostlevel. Using a service specific tag key will prevent conflicts/confusion.

Rename cluster_name tag to mapreduce_cluster

---

couch/assets/dashboards/overview.json
couch/manifest.json

This PR adds a blog like dashboard for couchdb while also replacing the dogweb equivalent

Add blog like dashboard

---

vsphere/datadog_checks/vsphere/utils.py
vsphere/datadog_checks/vsphere/vsphere.py
vsphere/tests/fixtures/host_tags_values.json
vsphere/tests/fixtures/metrics_realtime_values.json
vsphere/tests/legacy/test_vsphere.py
vsphere/tests/test_check.py

Add `vsphere_cluster` tag from host parent
User request.
Hosts are not considered as `parent` of VMs. To attach the correct `vsphere_cluster` to VMs, we need to get `vsphere_cluster` tags using `runtime.host` (ManagedEntity) property.
Example resource tree:
```
Folder:group-1
|  name: Datacenters
|  parent: null
|
|- Datacenter:datacenter-1
|  name: XXXX
|  parent: Folder:group-1
|
|- Folder:group-2
|  |  name: host
|  |  parent: Datacenter:datacenter-1
|  |
|  |- ClusterComputeResource:domain-1
|     |  name: cluster1
|     |  parent: Folder:group-2
|     |
|     |- HostSystem:host-1
|          name: myhost.com
|          parent: ClusterComputeResource:domain-1
|
|- Folder:group-3
|    name: vm
|    parent: Datacenter:datacenter-1
|
|- Folder:group-4
|     name: FolderX
|     parent: …
```

Add `vsphere_cluster` tag from host parent

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py

Validate that any metric metadata metric name is prefixed with integration name
Ensure that integrations should only emit metrics from with its namespace.

Validate metric prefixes for all metric metadata

---

iis/assets/monitors/err.json
iis/assets/monitors/lock.json
iis/assets/monitors/req.json
iis/manifest.json

Adds a set of recommended monitors for HAProxy, following the recommendation of the blog post:
https://www.datadoghq.com/blog/iis-metrics/
Monitors added leverage mostly anomaly monitors:
* [IIS] Anomalous amount of requests for site: {{site.name}}
* [IIS] Increase of not found error per second for site: {{site.name}}
* [IIS] Increase of locked error per second for site: {{site.name}}
More OOTB recommended monitors

Adding set of recommended monitors

---

snmp/datadog_checks/snmp/snmp.py

Prevent an exception when logging the bulk oid for an Oid with no `parts`, aka for an Oid parsed from a symbol without the `OID` field.
User support

🐛  [snmp] use OIDPrinter to debug oids from bulks

---

redisdb/README.md

Split the instructions from "containerized" into specific containerized environments: Docker, Kubernetes, ECS
For customers setting up their first few integrations, it's difficult to setup an integration without seeing actual examples for their particular containerized environment. In this PR, we'd like to provide an example of how we could add such examples on the RedisDB integration. This was done as part of an embedding with the containers team.
This was discussed in a meeting today with the Documentation Team, Yair of Containers, and Dhruv of Integrations. The PR targets the Redis Integration public doc:
https://docs.datadoghq.com/integrations/redisdb/?tab=host

Docker, Kubernetes, ECS instructions for Redis Integration

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/__init__.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/create_commits.py
datadog_checks_dev/datadog_checks/dev/tooling/git.py

Adds new helper script to ddev to sequentially create commits in a target repo.
Takes a source directory that contains a series of subdirectories, and iterates through them commiting the contents to the  branch on the target repo.
This formalizes the script that created the example commits in `integrations-extras`, as can be seen in the `DASH2020` [branch](https://github.com/DataDog/integrations-extras/commits/DASH2020/GitHub_Repo).
Example output:
```
❯ ddev -e meta create-example-commits ~/dd/integrations-example/github_repo -p "Example commit:"
Using `~/dd/integrations-example/github_repo` as source directory ...
Change to a feature branch on `extras`, and rerun the command.
```
```
❯ ddev -e meta create-example-commits ~/dd/integrations-example/github_repo -p "Example commit:"
Using …
```

Add ddev example committer tool

---

kafka_consumer/assets/configuration/spec.yaml
kafka_consumer/datadog_checks/kafka_consumer/data/conf.yaml.example

Update the option description to specify `kafka_consumer_offsets` and `monitor_unlisted_consumer_groups` can't be used at the same time.
`monitor_unlisted_consumer_groups` get the consumer group list from Zookeeper, so it the Kafka ones are not listed.
`kafka_consumer_offsets` needs the consumer groups to be explicitly listed.
Support case

Update kafka_consumer_offsets option description

---

istio/datadog_checks/istio/legacy_1_4.py

Allow users to add metrics to the metric list of the legacy istio endpoints.
Support case.
The user has untyped metrics on their istio < 1.5, so in order to get them they need to use `type_overrides`, but they also need the metrics to be included in the list.
```
instances:
- istio_mesh_endpoint: http://localhost:12345
type_overrides:
- untyped_metric: gauge
metrics:
- untyped_metric: untyped.metric
```
Since this is about the legacy check, I decided not to update the configuration file.

Allow custom metrics for legacy istio

---

haproxy/metadata.csv

Add a `legacy check only` description for metrics not sent by the prometheus check.
Some of the metrics in the `metadata.csv` are only emitted by the legacy check, other only emitted by the prometheus check, and some are emitted by both check. It can be confusing to know which metric to expect when running the check, so let's be more clear about that

Add legacy check only description

---

postgres/assets/configuration/spec.yaml
postgres/datadog_checks/postgres/config.py
postgres/datadog_checks/postgres/data/conf.yaml.example
postgres/datadog_checks/postgres/statements.py
postgres/tests/test_unit.py

This PR moves from tracking metrics for _all_ statements on every check run to only tracking the top statements across declared metrics. Applying this logic in the agent is a temporary measure to reduce cardinality while we build out a new intake to ingest aggregate payloads and do cardinality control on the backend.
To keep more of the "interesting" queries, this also limits the top queries to some "synthetic" metrics that are not actually emitted to the backend, but should be used to keep the top queries (e.g. average time ).
MySQL PR is here: https://github.com/DataDog/integrations-core/pull/8646
Initially the product requirement for statement metrics was to have no limits, but since then we've received more data and feedback from customers that they really only care about the "top" …

Apply default limits to Postres statement metrics

---

mysql/assets/configuration/spec.yaml
mysql/datadog_checks/mysql/config.py
mysql/datadog_checks/mysql/data/conf.yaml.example
mysql/datadog_checks/mysql/statements.py
mysql/tests/test_mysql.py
mysql/tests/variables.py

This PR moves from tracking metrics for _all_ statements on every check run to only tracking the top statements across declared metrics. Applying this logic in the agent is a temporary measure to reduce cardinality while we build out a new intake to ingest aggregate payloads and do cardinality control on the backend.
To keep more of the "interesting" queries, this also limits the top queries to some "synthetic" metrics that are not actually emitted to the backend, but should be used to keep the top queries (e.g. average time ).
Postgres PR is here: https://github.com/DataDog/integrations-core/pull/8647
Initially the product requirement for statement metrics was to have no limits, but since then we've received more data and feedback from customers that they really only care about the "top" …

Apply default limits to MySQL statement summaries

---

haproxy/assets/monitors/backend_dreq.json
haproxy/assets/monitors/backend_econ.json
haproxy/assets/monitors/backend_queue_time.json
haproxy/assets/monitors/backend_rtime.json
haproxy/assets/monitors/backend_sessions.json
haproxy/assets/monitors/frontend_4xx.json
haproxy/assets/monitors/frontend_5xx.json
haproxy/assets/monitors/frontend_dreq.json
haproxy/assets/monitors/frontend_ereq.json
haproxy/assets/monitors/frontend_sessions.json
haproxy/assets/monitors/request_rate.json
haproxy/manifest.json

Adds a set of recommended monitors for HAProxy, following the recommendation of the blog post:
https://www.datadoghq.com/blog/monitoring-haproxy-performance-metrics/
Since in order to get backend/frontend tagging of those metrics a user should either:
* Use prometheus
* Set manually an option to true in the conf
Those monitors are vanilla in a sense that they only do a break down by host.
Monitors added leverage mostly anomaly monitors:
* [HAProxy] Anomalous number of frontend 4xx HTTP responses for host: {{host.name}}
* [HAProxy] Anomalous number of frontend 5xx HTTP responses for host: {{host.name}}
* [HAProxy] High amount of frontend session usage for host: {{host.name}}
* [HAProxy] High amount of backend session usage for host: {{host.name}}
* [HAProxy] High number of frontend denied …

[HAProxy] Adding recommended monitors

---

sqlserver/datadog_checks/sqlserver/metrics.py

Our test environment reports `resource_group_id` as a readable string, so was used as the identifier string for the tag.  Based on customer reports, this column actually outputs a UUID, while another column `name` provides the human-readable string.
Instead of replacing the tag `availability_group`, this PR adds a new one named `availability_group_name` based on the name column.

Add availability group name tag

---

datadog_checks_base/datadog_checks/base/checks/base.py

This is called by the agent when a check is unscheduled
This is linked to https://github.com/DataDog/datadog-agent/pull/7279

Add cancel method to the AgentCheck base class, allowing cleanup of resources when checks are unscheduled.

---

.azure-pipelines/all_master.yml

On this [PR](https://github.com/DataDog/integrations-core/pull/8443) I accidentally disabled running e2e tests on master https://github.com/DataDog/integrations-core/pull/8443/files#diff-b04da85e43f922caa2a7ca7648f2395f1842aecaf7e4786b0b2b9851b648c415R13
This PR fixes it

Restore running e2e on master branch

---

datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py

Avoid mounting check confd volume if there is no config
Related PR: https://github.com/DataDog/integrations-core/pull/8719
This change is needed for snmp test requiring `/etc/datadog-agent/conf.d/snmp.d/auto_conf.yaml` to be present.
Currently, check confd (e.g. `/etc/datadog-agent/conf.d/snmp.d`) is always mounted and will make `auto_conf.yaml` unavailable.
Right now, `ddev` will mount `confd` even if there is no config.

Avoid mounting check confd volume if there is no config

---

snmp/datadog_checks/snmp/data/conf.yaml.example

Document loader config feature allowing user to switch from different implementations of the same integration

Add loader to snmp config example

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/datadog_checks/base/log.py
datadog_checks_base/datadog_checks/base/stubs/datadog_agent.py
datadog_checks_base/datadog_checks/base/utils/db/sql.py
datadog_checks_base/datadog_checks/base/utils/db/statement_samples.py
datadog_checks_base/datadog_checks/base/utils/db/utils.py
datadog_checks_base/tests/test_serialization.py
postgres/assets/configuration/spec.yaml
postgres/datadog_checks/postgres/config.py
postgres/datadog_checks/postgres/data/conf.yaml.example
postgres/datadog_checks/postgres/postgres.py
postgres/datadog_checks/postgres/statement_samples.py
postgres/requirements.in
postgres/tests/compose/resources/01_postgres.sql
postgres/tests/compose/resources/02_setup.sh
postgres/tests/compose/resources/03_load_data.sh
postgres/tests/test_pg_integration.py

Adds a new feature to "Deep Database Monitoring", enabling collection of statement samples and execution plans. Follow-up to https://github.com/DataDog/integrations-core/pull/7852.
See https://github.com/DataDog/integrations-core/pull/8629 for the corresponding MySQL PR which depends on this PR. 
If enabled, a python thread is launched during a regular check run:
* collects statement samples at the configured rate limit (default 1 collection per second)
* maintains its own `psycopg2` connection to avoid clashing transactions/state with the main thread connection
* collects execution plans through a postgres function that the user must install into each database being monitored (if we wanted the agent to collect execution plans directly by running `EXPLAIN` then it would need full write …

Collect postgres statement samples & execution plans for deep database monitoring

---

.codecov.yml

TokuMX integration is currently at 75%, making the master CI fail.

Decrease TokuMX codecov target

---

datadog_checks_base/datadog_checks/base/checks/kube_leader/__init__.py
datadog_checks_base/datadog_checks/base/checks/kube_leader/mixins.py
datadog_checks_base/datadog_checks/base/checks/kube_leader/record.py
datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/requirements.in
datadog_checks_base/tests/test_kube_leader.py
kube_controller_manager/datadog_checks/kube_controller_manager/data/conf.yaml.example
kube_controller_manager/datadog_checks/kube_controller_manager/kube_controller_manager.py
kube_controller_manager/tests/test_kube_controller_manager.py
kube_scheduler/assets/configuration/spec.yaml
kube_scheduler/datadog_checks/kube_scheduler/data/conf.yaml.example
kube_scheduler/datadog_checks/kube_scheduler/kube_scheduler.py
kube_scheduler/tests/test_kube_scheduler_1_13.py
kube_scheduler/tests/test_kube_scheduler_1_14.py

Add support for Kubernetes leader election based on Lease objects.
Historically, the Kubernetes control plane components were coordinating themselves to elect a leader via annotations on an `EndPoints` object.
There is now a dedicated object for that purpose: the `Lease` object.
The checks that are detecting which pod is a leader need to be adapted accordingly.
This change requires new permissions for the agent:
* DataDog/helm-charts#160
* DataDog/datadog-operator#219

Add support for Kubernetes leader election based on Lease objects

---

istio/datadog_checks/istio/metrics.py
istio/metadata.csv

Include and document sidecar injection failure_total and skipped_total

Add sidecar injection failed and skipped metrics

---

datadog_checks_base/datadog_checks/base/checks/openmetrics/mixins.py

Update process_metrics to look for wildcards in metric transformers.
This will be used to gather additional Vault metrics.

Add ability to look for wildcards in Prometheus metric transformers

---

postgres/setup.py

Bump datadog_checks_base min version for the postgres check. 
Follow-up to https://github.com/DataDog/integrations-core/pull/8627
Depends on https://github.com/DataDog/integrations-core/pull/8759
Fix broken build due to old datadog_checks_base minimum version.
```
E   ImportError: cannot import name 'compute_exec_plan_signature' from 'datadog_checks.base.utils.db.sql' (/home/vsts/work/1/s/postgres/.tox/py38/lib/python3.8/site-packages/datadog_checks/base/utils/db/sql.py)
```

postgres check: bump datadog_checks_base min version

---

kube_controller_manager/setup.py
kube_scheduler/setup.py

Bump base package requirement (failing CI: https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=50064&view=logs&jobId=1b97e13f-8952-5346-8c21-6dbaad23061a).
Related PRs:
* `kube_controller_manager` and `kube_scheduler`: https://github.com/DataDog/integrations-core/pull/8535
* ~`apache`: https://github.com/DataDog/integrations-core/pull/8640 (`assert_metrics_using_metadata`)~
Green pipeline https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=50093&view=results
Oracle and postgres fails are not related to base package requirement.

Bump base package requirement

---

.azure-pipelines/templates/test-all.yml

`parameters.test_e2e` is a string, so it evaluates to true regardless of the content of that string.

Fix passing of the 'test_e2e' var in the CI

---

datadog_checks_base/datadog_checks/base/utils/db/sql.py
datadog_checks_base/datadog_checks/base/utils/db/statement_samples.py
datadog_checks_base/datadog_checks/base/utils/serialization.py
postgres/datadog_checks/postgres/statement_samples.py
postgres/tests/test_pg_integration.py
postgres/tox.ini

* Fixes `AttributeError: module 'orjson' has no attribute 'JSONEncoder'` when importing `datadog_checks.base.utils.db.statement_samples` where `orjson` is installed.
* Add `datadog_checks_base` `json` dependency to postgres tests so we're testing orjson correctly
* Update statement sampler stub to serialize events to/from json to ensure we're testing the json serialization during integration tests.
Fix broken import for DBM in case of `orjson` dependency being installed.

Improve orjson compatibility

---

postfix/README.md

Under log collection here: https://docs.datadoghq.com/integrations/postfix/#log-collection
Hyperlink to sample postfix.d/conf.yaml took you to Agent Command docs
This PR changes the link to the GitHub repo: https://github.com/DataDog/integrations-core/blob/master/postfix/datadog_checks/postfix/data/conf.yaml.example

[doc]erin-leeds/fixed hyperlink under postfix log collection

---

postgres/datadog_checks/postgres/postgres.py
postgres/datadog_checks/postgres/statement_samples.py
postgres/tests/test_pg_integration.py

Use the cancel feature added in https://github.com/DataDog/integrations-core/pull/8463 to ensure the statement sampler thread is stopped when the check is unscheduled.
Follow-up to https://github.com/DataDog/integrations-core/pull/8627
Faster resource cleanup when a check is unscheduled.

Shutdown statement sampler thread on cancel

---

mysql/assets/configuration/spec.yaml
mysql/datadog_checks/mysql/config.py
mysql/datadog_checks/mysql/data/conf.yaml.example
mysql/datadog_checks/mysql/mysql.py
mysql/datadog_checks/mysql/statement_samples.py
mysql/requirements.in
mysql/setup.py
mysql/tests/compose/mariadb.conf
mysql/tests/compose/mysql.conf
mysql/tests/conftest.py
mysql/tests/test_mysql.py
mysql/tox.ini

Adds a new feature to "Deep Database Monitoring", enabling collection of statement samples and execution plans. 
Follow-up to:
*  #7851 - mysql DBM statement metrics
* https://github.com/DataDog/integrations-core/pull/8627 - Collect postgres statement samples & execution plans
If enabled, a python thread is launched during a regular check run:
* collects statement samples at the configured rate limit (default 1 collection per second)
* maintains its own `pymysql` connection as `pymysql` is not thread safe so we can't share with the main check
* collects execution plans through a mysql procedure that the user must install into each database being monitored (if we wanted the agent to collect execution plans directly by running `EXPLAIN` then it would need full write permission to all …

Collect mysql statement samples & execution plans 

---

mysql/tests/test_mysql.py
postgres/tests/test_pg_integration.py

Fix flaky statement samples tests for postgres & mysql: stop waiting on thread start as it's unnecessary since we wait on thread stop anyway.
Fix flaky tests.

postgres & mysql: fix flaky DBM thread tests

---

aspdotnet/assets/configuration/spec.yaml
consul/assets/configuration/spec.yaml
envoy/assets/configuration/spec.yaml
haproxy/assets/configuration/spec.yaml
http_check/assets/configuration/spec.yaml
kube_apiserver_metrics/assets/configuration/spec.yaml
kube_scheduler/assets/configuration/spec.yaml
marklogic/assets/configuration/spec.yaml
mcache/assets/configuration/spec.yaml
mesos_slave/assets/configuration/spec.yaml
pgbouncer/assets/configuration/spec.yaml
php_fpm/assets/configuration/spec.yaml
proxysql/assets/configuration/spec.yaml
supervisord/assets/configuration/spec.yaml
tcp_check/assets/configuration/spec.yaml
tokumx/assets/configuration/spec.yaml

Use `display_default` and remove unused `default` options
Follow up to https://github.com/DataDog/integrations-core/pull/8593

Remove unused default config spec option

---

tomcat/assets/monitors/error_count.json
tomcat/assets/monitors/max_proc_time.json
tomcat/assets/monitors/processing_time.json
tomcat/assets/monitors/req_count.json
tomcat/assets/monitors/thread_busy.json
tomcat/assets/monitors/thread_count_max.json
tomcat/manifest.json

Adds a set of OOTB monitors for the Tomcat integration following recommendation from: 
https://www.datadoghq.com/blog/tomcat-architecture-and-performance/
Monitors added are:
* [Tomcat] Anomalous request rate for host {{host.name}}
* [Tomcat] Anomalous max processing time for host {{host.name}}
* [Tomcat] Anomalous average processing time for host {{host.name}}
* [Tomcat] % of thread count managed by the thread pool is high for host: {{host.name}}
* [Tomcat] % of busy threads is high for host: {{host.name}}
* [Tomcat] Increase of the errors/second rate for host: {{host.name}}
More OOTB monitors.
The article recommends setting JVM monitors as well, but i think this should be addressed in another PR

[AI-1263] [Tomcat] Adding OOTB monitors

---

snmp/datadog_checks/snmp/snmp.py
snmp/datadog_checks/snmp/utils.py
snmp/tests/test_check.py

Fix snmp get bulk log
The OIDPrinter takes a list of ObjectType as input
Related to this fix PR https://github.com/DataDog/integrations-core/pull/8688

Fix snmp get bulk log

---

datadog_checks_dev/datadog_checks/dev/kind.py

For checks with undercores in their names, when creating a kind cluster for e2e tests, replace the undercore with a dash for the cluster name to avoid errors.
Right now, this class creates the kind cluster using the name of the integration, but if the integration has an undercore in its name, it will error, as kubeadm doesn't accept undercores in the cluster names.
When I tried to create an e2e test for `cert_manager`, I got the following error:
```
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged cluster-cert_manager-py38-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
Command Output: I0308 08:35:30.043618     232 initconfiguration.go:201] loading …
```

Make kind cluster name kubeadm compliant

---

mongo/datadog_checks/mongo/mongo.py

1. Better performance
2. For times when Mongo reaches the max connection count, the integration starts failing to report metrics because it can no longer connect

Cache API client connection

---

sonarqube/README.md

Clarifies how to configure SonarQube to collect all metrics available from SonarQube's Web API and JMX beans. 
Had issues with a customer configuring the integration correctly and found the docs to be very opaque about configuration details. After solving their issue, I want to improve our docs so other customers don't run into this issue in the future.
There is a [ticket](https://datadog.zendesk.com/agent/tickets/445200) and [escalation](https://datadoghq.atlassian.net/browse/AGENT-5805) for more context.

Clarify SonarQube integration installation and configuration instructions

---

docs/developer/.scripts/33_render_status.py

Al snmp_* tiles are showing in the dashboard list and they should not

Do not count snmp_ integrations

---

activemq/datadog_checks/activemq/data/metrics.yaml
activemq/metadata.csv

Update new Artemis metrics in ActiveMQ `metadata.csv`:
* More consistent descriptions: always finish with a full stop "`.`".
* Add units.
* Clarify metric descriptions when the name and metric type are confusing (eg `_count` metric being a rate).
Found during QA of #8527 
@mgarabed Did you find these were creating any issues for the dashboard #8690?

Tweak Artemis metrics metadata

---

iis/datadog_checks/iis/iis.py

[This PR](https://github.com/DataDog/integrations-core/commit/98935844e213008827af6390a846ae4b50853275#diff-a37e2f0181d06b4a16041cb2b7232a3d8dbe408d4d0a1f9a22750445a7716666R118) introduced counter refreshing on the base class and[ this pr ](https://github.com/DataDog/integrations-core/pull/3840)copied it over to IIS but it didn't copy it completely. Here we try to better reproduce what the base class is doing

Better recreate base class refreshing strategy

---

ceph/datadog_checks/ceph/ceph.py
ceph/metadata.csv
ceph/tests/common.py
ceph/tests/test_unit.py

Add new metrics for tracking ceph recovery:
- `ceph.misplaced_objects`
- `ceph.misplaced_objects_total`
- `ceph.recovering_objects_per_sec`
- `ceph.recovering_bytes_per_sec`
- `ceph.recovering_keys_per_sec`
We caused a lot of degredation in our ceph cluster between migrating osds to bluestore and replacing hdds with ssds, and we wanted better visibility, so I made some patches for the ceph integration and just got around to reformatting them for PRs now.
I made a dashboard to demo some of what we've been using these metrics for ([here](https://p.datadoghq.com/sb/44f16805b-6c2c986346efa90ccc154519b68ff207)). There are a couple inconsistencies in the data (patches got applied and removed with updates and such), and we aren't causing as much degradation in our cluster at the moment, so it's …

Add Ceph Recovery metrics

---

docs/developer/architecture/snmp.md

Fix snmp listener architecture doc typo
`user` is needed for snmp v3 config

Fix snmp listener architecture doc typo

---

haproxy/metadata.csv
haproxy/tests/legacy/test_haproxy.py

Edits haproxy metric metadata to correctly reflect metric types 
https://datadoghq.atlassian.net/browse/AI-1311
- Edited tests/legacy/test_haproxy.py as metadata will reflect new metrics types over legacy ones, thus causing legacy test to fail

Reflect new metric types in haproxy metadata

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/testable.py

Fix `Infra-Integrations` spelling for `ddev release trello testable`

Fix infra-integrations team for testable

---

sqlserver/datadog_checks/sqlserver/metrics.py
zk/requirements-dev.txt

The column `is_primary_replica` only exists on the table `sys.dm_hadr_database_replica_states` for versions of [SQL Server 2014 and later](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-hadr-database-replica-states-transact-sql?view=sql-server-ver15).  
This PR catches the exception and uses the tag value of `unknown` instead.  
Better compatibility.

Handle availability replica metrics on earlier versions

---

sqlserver/datadog_checks/sqlserver/metrics.py
sqlserver/datadog_checks/sqlserver/utils.py

When collecting example database `9000_foo`:
```
error: sqlserver:894db28bbe138638 | (sqlserver.py:459) | Error running `fetch_all` for metrics SqlDatabaseFileStats - skipping.  Error: ('42000', "[42000] [FreeTDS][SQL Server]Incorrect syntax near '9000'. (102) (SQLExecDirectW)")
```
From https://docs.microsoft.com/en-us/sql/t-sql/language-elements/use-transact-sql:
```
database_name
Is the name of the database or database snapshot to which the user context is switched. Database and database snapshot names must comply with the rules for identifiers.
```
then https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers
```
The first character must be one of the following:
* A letter as defined by the Unicode Standard 3.2. The Unicode definition of letters …
```

Ensure delimited identifiers in USE statements

---

datadog_checks_dev/datadog_checks/dev/tooling/github.py

Update error message to remind people to enable SSO on their token.

Update error message to remind people to enable SSO

---

sqlserver/tests/compose/setup.sql

Updates E2E environment to include databases that would trigger the error fixed with #8832 
Test coverage

Add databases to E2E with non-standard names

---

mysql/datadog_checks/mysql/mysql.py
mysql/tests/test_mysql.py

A host can be running as a source (master) or a replica (slave) or even both (see https://dev.mysql.com/doc/refman/8.0/en/replication-solutions-performance.html and https://severalnines.com/resources/database-management-tutorials/mysql-replication-high-availability-tutorial). We currently do not consider that a host can be both.
Metric concerned: `mysql.replication.slave_running`
Service checks concerned: `mysql.replication.slave_running`, `mysql.replication.replica_running`
This PR adds an additional tag to these metric/service checks named `replication_mode`, and its value depends on the host being considered a source or a replica.
Ex:
* Source-only host: one `mysql.replication.replica_running` with `replication_mode:source`
* Replica-only host: one `mysql.replication.replica_running` …

Add replication_mode tag to replication service check

---

sqlserver/assets/configuration/spec.yaml
sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
sqlserver/datadog_checks/sqlserver/metrics.py
sqlserver/datadog_checks/sqlserver/sqlserver.py
sqlserver/datadog_checks/sqlserver/utils.py

Adds more exception handling for specific queries, and breaks down the `SqlFragmentation` metric class to query on a database by database basis.  Previously, a single database that was in a "non-good" state would cause the whole SELECT to fail, now it will log the error for the specific database and continue.
Also added a note regarding the potential performance impacts of turning on the option `include_fragmentation_metrics`.
Resiliency.
For QAing this change, the following steps were taken:
1. Start E2E env via `ddev env start sqlserver py38-default`
2. Verify metrics report successfully via `ddev env check sqlserver py38-default --table -l debug`
3. Execute the following SQL statements to put a database in a recovering state:
```sql
BACKUP DATABASE AdventureWorks2017
TO DISK = …
```

Improve exception handling for database queries

---

activemq/metadata.csv

PR #8814 addressed several issues with `metadata.csv` but included a metric type change that now causes issues with testing.
This PR reverts that field back to a `rate`.
For some reason, the last commit in that referenced PR passed CI tests, but after the merge it fails, hence this update.

Revert metadata change

---

win32_event_log/assets/configuration/spec.yaml
win32_event_log/datadog_checks/win32_event_log/data/conf.yaml.example

Microsoft docs are incorrect: https://social.msdn.microsoft.com/Forums/sqlserver/en-US/bc3b8642-2573-4481-a1e6-111004edf36e/how-to-use-an-event-log-file-path-in-evtsubscribe?forum=vcgeneral

Fix description of the `path` option

---

databricks/README.md
databricks/assets/dashboards/databricks_overview.json
databricks/manifest.json

Add script suggestions from @levihernandez, thanks!
Clean up and further clarifications and added default dashboard
Scripts now include:
- logs configuration
- host level tags
- clear steps on running the init scripts and setting up clusters

Add default dashboard and additional init script examples

---

postgres/assets/monitors/percent_usage_connections.json
postgres/assets/monitors/replication_delay.json
postgres/manifest.json

Add 2 recommended monitors for Postgres, based on [blog posts](https://www.datadoghq.com/blog/collect-postgresql-data-with-datadog/#alerting):
* Abnormal `replication_delay`
* High `percent_connection_usage`
Staging link: (WIP)
Recommended monitors coverage

Add Postgres recommended monitors

---

active_directory/assets/dashboards/active_directory.json

Adds the logs widget for `active_directory`
[Staging Link](https://dd.datad0g.com/screen/integration/30482/active-directory?from_ts=1615934969333&live=true&to_ts=1615938569333&tv_mode=false)

Add log widget to Active Directory dashboard

---

.github/workflows/release-base.yml
.github/workflows/release-dev.yml
docs/developer/.snippets/links.txt
docs/developer/process/integration-release.md

Add two GitHub Action workflows to automate releasing of `datadog_checks_base` and `datadog_checks_dev`.
* Add workflows YAML files
* Link to `PYPI_TOKEN_(BASE|DEV)` secrets (generated on PyPI and added to repo secrets separately)
Ensure team members do not forget about publishing base and dev (after regular releases, while preparing an Agent release, etc).
Not sure how to test this. We don't have team credentials for test.pypi.org, and `ddev release upload` doesn't support pointing at that yet. I'd suggest we merge if this looks good, and confirm the workflow is fine upon next base or dev release?

Add actions to auto-release base and dev packages

---

databricks/assets/dashboards/databricks_overview.json

Uses the SVG Databricks logo instead of the deprecated PNG version on the new Databricks dashboard.
Thanks to our handy RUM monitor, I got an alert for a new view of a PNG logo 🙂. (We can't remove every PNGs altogether yet, unfortunately, because they're still used in emails 😕.) 
No visual changes.

💄 Use SVG logo for Databricks dash

---

sqlserver/metadata.csv

Update Metadata so the word Custer appropriately states Cluster instance
Typo on Docs page looks unprofessional
https://a.cl.ly/GGu6D19J 
Image of issue, found that the issue is in the metadata.csv that populates the page -> https://docs.datadoghq.com/integrations/sqlserver/?tab=host#setup
Under metric -> sqlserver.fci.status

[us.1 prod] fixed typo for Custer Instance to Cluster Instance

---

postfix/datadog_checks/postfix/postfix.py
postfix/tests/test_unit.py

Fix parsing output when the queue is empty like:
```
bash-5.1# postqueue -p
Mail queue is empty
```
Support case

Fix empty queue parsing

---

.gitlab/tagger/Dockerfile

Found this while monitoring release of #8853 
Old `get-pip.py` started raising this, which breaks the tagger:
```
Step 8/8 : RUN curl -sSL https://raw.githubusercontent.com/pypa/get-pip/master/get-pip.py | python3  && pip3 install --no-cache-dir ${DDEV_ROOT}[cli]  && pip3 install --no-cache-dir awscli==1.16.129
---> Running in c108c7f30607
Hi there!
The URL you are using to fetch this script has changed, and this one will no
longer work. Please use get-pip.py from the following URL instead:
https://bootstrap.pypa.io/get-pip.py
Sorry if this change causes any inconvenience for you!
We don't have a good mechanism to make more gradual changes here, and this
renaming is a part of an effort to make it easier to us to update these
scripts, when there's a pip release. It's also essential for …
```

Update tagger get-pip.py script

---

prometheus/README.md

This PR updates the documentation to inform users how to configure our new alertmanager integration
deployment of our new alertmanager integration into production

update prometheus docs for alertmanager

---

.github/workflows/release-base.yml
.github/workflows/release-dev.yml

Cleanup for #8846 
Had left `-n` (dry run) mode in place. :facepalm:
Tags were created and wheels were signed. Doesn't seem to be a way to "trigger" a workflow manually, which is a pain. Means we can't trigger the Actions again until next release, since we can't remove the tags from GitHub and re-create them (they're already released and in our index), right?

Remove -n option when uploading base and dev

---

vsphere/assets/configuration/spec.yaml
vsphere/datadog_checks/vsphere/api_rest.py
vsphere/datadog_checks/vsphere/data/conf.yaml.example

Tag collection only available from vSphere 6.5
vSphere integration tag collection uses vSphere REST API, and the vSphere REST API is available only [since vSphere 6.5](https://blogs.vmware.com/developer/2016/10/whats-new-developer-automation-interfaces-65.html).
https://blogs.vmware.com/code/2017/02/02/getting-started-vsphere-automation-sdk-rest/

Tag collection only available from vSphere 6.5

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/models.py

`datadog_checks_base` is already included in `get_valid_checks` so we were testing it twice on core.
Also we were testing base on integrations-extras and marketplace which is not possible as the lib is not installed.

Fix models validation

---

.gitlab-ci.yml

Currently, if an unexpected error happen before validating the logs pipeline, the error won't show up on slack.
This PR makes sure that any CI failure will be shown.

Notify slack on ci failure

---

.gitlab-ci.yml
.gitlab/validate-logs-intgs/Dockerfile

I realized that the logs pipeline validation was failing for two reasons:
- `node` now disallows installing libs in the root folder of the container. This means that we were not building new docker images of the validator.
- `web-ui` moved the integrations.ts file from `javascript/datadog/logs/lib/integrations/integrations.ts` to `javascript/datadog/logs/lib/shared/integrations/integrations.ts`
The pipeline was **silently** failing for a separate reason, solved in https://github.com/DataDog/integrations-core/pull/8872/s

Fix logs validation

---

activemq/assets/dashboards/artemis_dashboard.json
activemq/manifest.json

Add additional dashboard to ActiveMQ for Artemis specifically.
[Dashboard on staging](https://dd.datad0g.com/screen/integration/30586/activemq-artemis---overview)
Updated to blog-like style:

Add dashboard for ActiveMQ Artemis

---

.codecov.yml
.coveragerc

There `Sync config models` PRs are adding a folder to every integration. However, this folder is validated the the ddev command, so codecov does not consider it tested.
Having these folders it the code coverage seems irrelevant.

Ignore config models from coverage

---

activemq/manifest.json

Artemis installs look broken since they do not emit the current `metric_to_check` value.  This expands the field to include an Artemis specific metric name as well.

Add additional metric to manifest

---

disk/datadog_checks/disk/disk.py

Add a debug-level log when a device is excluded.
To help distinguish excluded vs not detected.

Log something if a disk is excluded

---

docs/developer/ddev/configuration.md

Remove outdated docs. I will also remove the user list itself after this is merged (if indeed it's not used for anything).
AFAIK, we no longer use that list since https://github.com/DataDog/integrations-core/commit/4fb8404e4ef16ac9b02278d02d9b1f17493004a3

Remove docs about the trello user list

---

amazon_msk/assets/configuration/spec.yaml
amazon_msk/datadog_checks/amazon_msk/amazon_msk.py
amazon_msk/datadog_checks/amazon_msk/data/conf.yaml.example
amazon_msk/tests/test_unit.py

Some amazon msk instances may not expose metrics at `/metrics` path. This PR makes the path configurable.
User req

Allow prometheus metrics path to be configurable

---

sonarqube/README.md
sonarqube/manifest.json

Adds the standard Further Reading section and a blog link to this integration's README.
New blog post: https://www.datadoghq.com/blog/datadog-sonarqube-integration/

(docs) Add link to SonarQube

---

wmi_check/datadog_checks/wmi_check/config_models/__init__.py
wmi_check/datadog_checks/wmi_check/config_models/defaults.py
wmi_check/datadog_checks/wmi_check/config_models/instance.py
wmi_check/datadog_checks/wmi_check/config_models/shared.py
wmi_check/datadog_checks/wmi_check/config_models/validators.py

Adds config models from https://github.com/DataDog/integrations-core/pull/8675

Add runtime configuration validation

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/http.py

New openmetrics config template is also a valid http config support

Include new and legacy openmetrics template in http validation

---

postgres/datadog_checks/postgres/statement_samples.py

The timestamp derived from the last `state_change` was wrong because it didn't take into account the timezone, causing some events to be dropped during intake. Now we do an explicit conversion to a unix timestamp from the UTC Unix epoch date.
Fix wrong timestamps.

Fix wrong timestamp for DBM beta feature

---

datadog_checks_base/datadog_checks/base/checks/kube_leader/mixins.py
datadog_checks_base/tests/test_kube_leader.py

Add a timeout for Kubernetes API calls.
Guarantee that checks cannot remain blocked forever, even in case of network issue blackholing all the packets.
We add the [`_request_timeout` parameter which is documented here](https://github.com/kubernetes-client/python/blob/b79ad6837b2f5326c7dad488a64eed7c3987e856/kubernetes/client/api/coordination_v1_api.py#L1092-L1095).

Add a timeout for Kubernetes API calls

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/all_validations.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/manifest.py

Raises error if `metrics_to_check` is empty when the check actually reports metrics.
Includes fixes to 3 checks to pass validation.

Raise validation error if metadata.csv but no metric_to_check

---

rabbitmq/assets/monitors/disk_usage.json
rabbitmq/assets/monitors/message_unacknowledge_rate_anomaly.json
rabbitmq/manifest.json

Add 2 recommended monitors for RabbitMQ, based on [Monitoring RabbitMQ performance with Datadog](https://www.datadoghq.com/blog/monitoring-rabbitmq-performance-with-datadog/) and [Key metrics for RabbitMQ monitoring](https://www.datadoghq.com/blog/rabbitmq-monitoring/#nodes) blogs.
Staging seems to be broken for collection of metrics, so clicking on the tiles will not render properly. https://dd.datad0g.com/monitors#recommended?q=integration:RabbitMQ&p=1
- Abnormal `message_unacknowledge` rate -- [dddev link](https://dddev.datadoghq.com/monitors/32884265)
- High level of `disk_usage` -- [dddev link](https://dddev.datadoghq.com/monitors/32883966)
Recommended monitors coverage

Add RabbitMQ recommended monitors

---

.azure-pipelines/templates/run-tests.yml
snmp/datadog_checks/snmp/snmp.py
snmp/tests/common.py
snmp/tests/test_check.py
snmp/tests/test_e2e_core.py
snmp/tests/test_e2e_core_vs_python.py

Require this PR + new master docker image for e2e: https://github.com/DataDog/datadog-agent/pull/7742
Demo Test PR based on snmp corecheck with loader tag: https://github.com/DataDog/integrations-core/pull/9039
Add python loader tag
- Help comparing corecheck vs python performance
- Help knowing which loader/implementation is used (core or python)

Add python loader tag to telemetry metrics

---

haproxy/tox.ini

removing: 1.6 and 2.1 support, they are no longer supported, see also
http://www.haproxy.org/
updating minors: 1.7, 1.8, 2.0, 2.2, 2.3, 2.4
keep tests up to date

haproxy: update haproxy versions used for tests

---

coredns/datadog_checks/coredns/data/conf.yaml.example
datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/openmetrics_legacy.yaml
istio/datadog_checks/istio/config_models/defaults.py
istio/datadog_checks/istio/config_models/instance.py
openmetrics/assets/configuration/spec.yaml

https://github.com/DataDog/integrations-core/pull/8883#discussion_r604652583
Integrations set `metrics` and `namespace` themselves

Update defaults for legacy OpenMetrics config spec template

---

vsphere/assets/configuration/spec.yaml
vsphere/datadog_checks/vsphere/api_rest.py
vsphere/datadog_checks/vsphere/config.py
vsphere/datadog_checks/vsphere/data/conf.yaml.example
vsphere/datadog_checks/vsphere/types.py
vsphere/datadog_checks/vsphere/vsphere.py
vsphere/tests/test_api.py
vsphere/tests/test_api_rest.py
vsphere/tests/test_cache.py
vsphere/tests/test_check.py
vsphere/tests/test_filters.py
vsphere/tests/test_lab.py
vsphere/tests/test_utils.py

Add `rest_api_options` to expose all RequestsWrapper options for vSphere REST API client.
Since vSphere uses multiple ways to collect data, the rest api options are namespaced with `init_config.rest_api_options` and `instances[].rest_api_options` to avoid confusion.
vSphere uses:
- REST API for vSphere tags
- pyVmomi (SOAP) for the rest (infrastructure metadata, metrics, etc)
The alternative is to expose the options at the root of `init_config/instancesp[]`, but that might create confusion, since it won't be clear if `instancesp[].timeout` is used for REST API or pyVmomi.
Customer case: user need to configure REST API timeout.

Add rest_api_options to expose all RequestsWrapper options

---

activemq_xml/README.md
activemq_xml/assets/configuration/spec.yaml
activemq_xml/datadog_checks/activemq_xml/data/conf.yaml.example
activemq_xml/manifest.json

ActiveMQ and ActiveMQ_XML share the same tile and the same logs parsing pipeline, so this pr only updates the documentation.

Add logs documentation

---

datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/transform.py
datadog_checks_base/tests/openmetrics/test_transformers/test_native_dynamic.py

(working on `amazon_msk` PR)
For endpoints that emit non-unique metric names https://github.com/OpenObservability/OpenMetrics/blob/v1.0.0/specification/OpenMetrics.md#metricset
> Each MetricFamily name MUST be unique.
The spec/clients strip `_total` from counters, see
- https://github.com/prometheus/client_python/pull/300/commits/a4dd93bcc6a0422e10cfa585048d1813909c6786
- https://prometheus.github.io/client_java/io/prometheus/client/Counter.html

Add `native_dynamic` OpenMetrics transformer

---

tls/assets/configuration/spec.yaml
tls/datadog_checks/tls/data/conf.yaml.example
tls/datadog_checks/tls/tls.py
tls/metadata.csv
tls/tests/conftest.py
tls/tests/test_local.py
tls/tests/test_remote.py

This adds a boolean to the TLS integration to send certificates duration as a metric. 
In order to successfully monitor  certificates expiration it is helpful to compare the certificates expiration in days/seconds against the actual length of time the certificate is issued for. This would allow for percentage based monitoring rather than time based ones.

Add a boolean to send certificate duration

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/dashboard.py

Using the `ddev meta dash export URL INTEGRATION` command with common dash names such as `INTEGRATION - Overview` caused the payload to be saved as such.
```
Successfully wrote dashboard: `-_overview.json` for integration: INTEGRATION
```
This fix removes the additional characters at the front.
```
Successfully wrote dashboard: `overview.json` for integration: INTEGRATION
```

Better support for dashboard filename

---

kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
kafka_consumer/datadog_checks/kafka_consumer/legacy_0_10_2.py

The Kafka client call `self._kafka_client.cluster.partitions_for_topic(topic)` has the possibility to return `None`, which will raise an error when trying to iterate over it.
This protects against that and adds better logging in case that condition occurs.

Handle missing partitions and better logging

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
openstack_controller/requirements.in

Reverts DataDog/integrations-core#9074
This is not required anymore as the decorator maintainer yanked the bad wheels that could not be installed on py2: https://github.com/micheles/decorator/issues/102

Revert "Pin decorator to 4.4.2"

---

kong/setup.py

Bump base package requirement.
#9031 uses the new openmetrics check implementation

Bump minimum base package version

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/manifest.py

PR #9042 added validation for `metric_to_check` in manifest files.  In `integrations-extras` there are quite a few legacy checks which fail this validation so ignore them for now and remove this exemption once they have been fixed at a later date.

Ignore metric_to_check validation for extras

---

aerospike/assets/configuration/spec.yaml
aerospike/datadog_checks/aerospike/aerospike.py
aerospike/datadog_checks/aerospike/data/conf.yaml.example
aerospike/tests/common.py
aerospike/tests/test_unit.py

This PR supports for XDR metrics introduced in Aerospike 5.0+
The `dcs` command was removed along with `xdr_` metrics under the statistics command.
https://www.aerospike.com/docs/operations/configure/cross-datacenter/parameters_and_metrics.html#xdr-metrics-removed-in-version-5-0
These metrics are Aerospike Enterprise only

Support XDR metrics for Aerospike Enterprise 5.0+

---

elastic/assets/configuration/spec.yaml
elastic/datadog_checks/elastic/config.py
elastic/datadog_checks/elastic/data/conf.yaml.example
elastic/datadog_checks/elastic/elastic.py
elastic/datadog_checks/elastic/metrics.py
elastic/metadata.csv
elastic/tests/test_elastic.py

Collects [Elastic Cat Allocations metrics](https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-allocation.htm). The existing instance was initialized in `config.py`. The new metrics were added to `metrics.py`. The function to get the data from `/_cat/allocation` is in `elastic.py`. A boolean was added to `spec.yaml` and `conf.yaml.example` in order to only enable the collection if the user wants to get the data. A test for the `elastic.py` function was added to `test_elastic.py`. The units of the metrics are `shard` and `byte`.
It was required by a customer in [this FR](https://datadoghq.atlassian.net/secure/RapidBoard.jspa?rapidView=610&projectKey=FRAGENT&modal=detail&selectedIssue=FRAGENT-1063&quickFilter=599).
This is how I tested the changed:
1. Set `ddev` following …

Support Cat allocation metrics

---

datadog_checks_dev/datadog_checks/dev/tooling/utils.py

Two ways we decide whether an intg. has log support
1. It has a logs section in the config
2. It has a logs section in the readme
Checking the readme was looking for "# Log collection", but we don't seem to be consistent on the casing. It seems like `# Log collection` is the most popular. 
We can either accept it and use this PR or I can make the change for all intgs. to use the correct casing. WDYT?
```bash
➜ git grep "# Log Collection"
aspdotnet/README.md:#### Log Collection
cassandra/README.md:##### Log Collection
cilium/README.md:##### Log Collection
clickhouse/README.md:##### Log Collection
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/README.md:### Log Collection
ecs_fargate/README.md:### Log Collection
fluentd/README.md:##### Log Collection …
```

Fix integration log checking

---

tokumx/manifest.json

The process signature of `tokumx` contains file path, which caused some problems when Processes team tries to use it to parse the command line. I discussed with @DataDog/agent-integrations they mentioned that this integration is old and deprecating, so we agreed to stop supporting it.
cc: @DataDog/processes

remove process signature from tokumx

---

mesos_master/manifest.json

The process signature of mesos-master contains file path, and this caused some trouble for Processes team to parse command line to match this signature. This PR removed the config flag to relax the condition a bit so we could match it successfully. From my discussion with @DataDog/agent-integrations this seems to be a reasonable change.
@DataDog/processes  team couldn't match this integration successfully due to the complex logic in handling paths in command line.

update mesos-master process signature

---

kubelet/datadog_checks/kubelet/kubelet.py
kubelet/metadata.csv
kubelet/tests/test_kubelet.py

Remove the `kubernetes.storage.operation.*` metrics.
This histogram metric generates a too high cardinality.
This metric was introduced in `7.27.0` by #8562.

Remove the `kubernetes.storage.operation.*` metrics because of a volumetry issue

---

kubelet/datadog_checks/kubelet/kubelet.py
kubelet/metadata.csv
kubelet/tests/test_kubelet.py

Remove the `kubernetes.storage.operation.*` metrics.
This histogram metric generates a too high cardinality.
This metric was introduced in `7.27.0` by #8562.

Backport of #9122: Remove the `kubernetes.storage.operation.*` metrics because of a volumetry issue

---

envoy/assets/configuration/spec.yaml
envoy/datadog_checks/envoy/config_models/defaults.py
envoy/datadog_checks/envoy/config_models/instance.py
envoy/datadog_checks/envoy/data/conf.yaml.example
envoy/datadog_checks/envoy/envoy.py
envoy/datadog_checks/envoy/parser.py
envoy/tests/test_parser.py

Introduces a retry option when a metric is not found in metrics.py. This can happen when a metric name part appears in a tag (e.g internal).
Resolves https://github.com/DataDog/integrations-core/issues/8775

Add retry option when metric is not found

---

iis/README.md

The IIS integration cannot be run in a window's container due to limitations on Microsoft's end. Therefore, we should not have instructions suggesting this is possible. 
Removes the containerized installation tab section
Support Escalation for reference: https://datadoghq.atlassian.net/browse/CONS-3741

[documentation] IIS - Remove Containerized Installation directions

---

datadog_checks_base/tests/test_http.py
datadog_checks_dev/datadog_checks/dev/fs.py

fileutils refactor caused importError in base test, https://github.com/DataDog/integrations-core/pull/9023
```
tests/test_http.py:26: in <module>
from datadog_checks.dev.utils import ON_WINDOWS, read_file, running_on_windows_ci, write_file
E   ImportError: cannot import name 'write_file' from 'datadog_checks.dev.utils' (/home/vsts/work/1/s/datadog_checks_dev/datadog_checks/dev/utils.py)
```

Fix test import

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/manifest.py

All integrations with metrics now define it since https://github.com/DataDog/integrations-extras/pull/837

Enable metric_to_check validation on extras

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/test.py

https://github.com/DataDog/integrations-core/blob/97021c770a5a9661596a0f19265d1828f54d9717/datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py#L45
https://github.com/DataDog/integrations-core/pull/9140

Support the `--changed` flag for E2E testing

---

redisdb/assets/configuration/spec.yaml
redisdb/datadog_checks/redisdb/data/conf.yaml.example

Fixes the config.yaml documentation to correctly show that the default when not specifying `ssl_cert_reqs` is 2 (require)
I was getting SSL errors that I didn't expect when adding a configuration for redis on Heroku, since Heroku requires you not verify the self-signed certificates they use for Redis. After some digging, I realized that the actual default for `ssl_cert_reqs` is to require them: https://redis-py.readthedocs.io/en/stable/#redis.Redis
N/A

redisdb: correct default ssl_cert_reqs

---

mongo/assets/configuration/spec.yaml
mongo/datadog_checks/mongo/config.py
mongo/datadog_checks/mongo/data/conf.yaml.example

After datadog-mongo 2.0.0, the check is not compliant with using mongodb+srv scheme.

Deprecate connection_scheme

---

mongo/datadog_checks/mongo/config.py
mongo/tests/test_unit.py

Address issue #8747. Two places where we used `authsource` instead of `authSource`.
1. Parsing instance configs.
Required change since `authSource` is used by `mongo`. Tests confirm that this field was not being parsed correctly. 
2. Parsing mongo uri.
No change required. Calls `pymongo` method which returns a [`_CaseInsensitiveDictionary`](https://github.com/mongodb/mongo-python-driver/blob/master/pymongo/uri_parser.py#L136).  Tests added to confirm correctness.

Fix authSource config option.

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/config.py

Refactor templates that contain default config template and include openmetrics v2 template.
CI fails for kong despite openmetrics template containing default template.

Fix default config validation to include openmetrics template

---

redisdb/datadog_checks/redisdb/redisdb.py

Mitigates https://github.com/DataDog/integrations-core/issues/8716
Caused by https://github.com/andymccurdy/redis-py/issues/1475

Skip slowlogs if there is an error

---

kubelet/datadog_checks/kubelet/cadvisor.py
kubelet/datadog_checks/kubelet/kubelet.py
kubelet/datadog_checks/kubelet/summary.py
kubelet/tests/test_kubelet.py

In order to best support kubernetes on windows we introduced https://github.com/DataDog/integrations-core/pull/6497 - However, this feature does not honour the configuration available for the cadvisor collector that can be used to disable/enable the collection of certain rates or certain types of metrics (for now, network but easily extnensible).
Customer Feature Req.
I moved around the parameters into the init of the super as we can't have a standalone cadvisor.
- [ x Files changes must correspond to the primary purpose of the PR as described in the title (small unrelated changes should have their own PR)

Add logic to enable/disable metrics collected from the summary endpoint

---

redisdb/datadog_checks/redisdb/redisdb.py
redisdb/metadata.csv
redisdb/tests/test_e2e.py

Since Redis 6 brings support for multi threaded IO, this PR adds support to redisdb to retrieve  `used_cpu_sys_main_thread` and `used_cpu_user_main_thread` from `info` and store them as metrics. These metrics will help determine how much CPU is being used from the main thread rather than the sum of all threads. 
We will be supporting Redis 6 in the near future and will need the new metrics piped to Datadog for evaluation and monitoring.

Support redis 6 cpu metrics

---

kubelet/datadog_checks/kubelet/data/conf.yaml.default
kubelet/datadog_checks/kubelet/kubelet.py
kubelet/tests/test_kubelet.py

The option to ignore metrics from the /metrics/cadvisor endpoint was hardcoded. This PR allows users to extend the list should they choose to not collect a subset of metrics.
Customer FR.

Allow configurability of the ignore_metrics option

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/testable.py

Performs git operations to determine whether a commit in the `target_ref` was cherry picked by the `base_ref` and discards it from the cards to QA. 
There are 2 cases that can happen:
1. Cherry-picked commits have different commit hash values, so we can't compare that.
2. Sometimes teams do not `squash and merge` causing cherry-picked commits to have different messages. Can't compare message either.
We can check via a `git diff`
To test this: I created 3 branches:
- [`lg/trello-target`](https://github.com/DataDog/integrations-core/commits/lg/trello-base)  The target reference. 
- [`lg/trello-base-squash`](https://github.com/DataDog/integrations-core/commits/lg/trello-base-squash) Contains a cherry-picked commit #9118 from `lg/trello-target`. Note that commit hashes are different. 
- …

[ddev] Skip cherry-pick commits in `ddev release trello testable`

---

cisco_aci/README.md
cisco_aci/assets/configuration/spec.yaml
cisco_aci/datadog_checks/cisco_aci/data/conf.yaml.example

Fix the `aci_url` config example to include schema `http://`
Include `tenants` option as part of configuration in the docs. Mention that it needs to be specified for apps/EPG stats.
Resolves https://github.com/DataDog/integrations-core/issues/9061 and https://github.com/DataDog/integrations-core/issues/9073

Clarify configuration and metric collection documentation

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/snmp_tile/snmp_{check_name}/manifest.json
snmp_cisco/manifest.json
snmp_dell/manifest.json
snmp_juniper/manifest.json

Remove `metric_prefix` from `snmp_tile` integrations
We recently added some `tile-only` integrations that do not generate metrics per se, and that are meant to show up in the integrations list so that customers can easily see which vendors we support with `snmp`. 
This was causing issues on the integration monitoring side: having multiple integration definitions with the same metric prefix makes it impossible to define which integration generated a metric. 
As `snmp_tile` integrations are all using metrics generated by `snmp` we decided to remove the `metric_prefix` from these integrations.
This PR updates also the template manifest used to generate new `snmp_tile` integrations in `ddev`

[SNMP] Remove metric_prefix from snmp_tile integrations

---

datadog_checks_base/datadog_checks/base/checks/base.py
datadog_checks_base/datadog_checks/base/stubs/aggregator.py
datadog_checks_base/datadog_checks/base/utils/db/utils.py

Follow-up to https://github.com/DataDog/datadog-agent/pull/7735: add the aggregator `submit_event_platform_event` API as well as two new APIs that build on this to submit `dbm-samples` and `dbm-metrics`.
Also add a new `default_json_event_encoding` to be used for when `datadog_checks/base/utils/db/statement_samples.py` is removed in https://github.com/DataDog/integrations-core/pull/9166
Enable checks to use the new aggregator API to submit event platform events.

Support new aggregator APIs for the event platform

---

datadog_checks_base/datadog_checks/base/utils/db/transform.py
datadog_checks_base/tests/test_db.py

When the returned results from a query gives you a unix timestamp, there is currently no way to get the time elapsed since it.

Add unix_time format to QueryManager time_elapsed transformer

---

datadog_checks_dev/datadog_checks/dev/plugin/tox.py

Part of [Before Freeze checklist](https://datadoghq.dev/integrations-core/process/agent-release/pre-release/#before-freeze)
https://pypi.org/project/isort/
Doesn't seem like the `pyproject` option worked for either version.
```
➜ pip install "isort[pyproject]==5.5.1"     
Collecting isort[pyproject]==5.5.1
Using cached isort-5.5.1-py3-none-any.whl (95 kB)
WARNING: isort 5.5.1 does not provide the extra 'pyproject'
```
```
➜ pip install "isort[pyproject]==5.8.0"
Collecting isort[pyproject]==5.8.0
Using cached isort-5.8.0-py3-none-any.whl (103 kB)
WARNING: isort 5.8.0 does not provide the extra 'pyproject'
```

Upgrade isort

---

clickhouse/tests/common.py
clickhouse/tests/docker/docker-compose.yaml

Port was set to 8126 for one of the instances. I think this port is usually occupied by the agent, so it was causing CI to fail. Hopefully this will fix.

Change Clickhouse port to start at 8127

---

kube_controller_manager/README.md
kube_scheduler/README.md

Clarifies that Kube Controller Manager and Kube Scheduler don't collect EKS data.
support request

DOCS-1879 - clarify EKS data collection in 2 integrations

---

mysql/datadog_checks/mysql/statement_samples.py
mysql/setup.py
mysql/tests/test_mysql.py
postgres/datadog_checks/postgres/statement_samples.py
postgres/setup.py
postgres/tests/test_pg_integration.py

Follow-up to https://github.com/DataDog/integrations-core/pull/9165: Update python & mysql checks to submit DBM events via the new aggregator API. 
Also improves the tests to better handle threads. 
Submit events using the more robust agent go code to with proper batching, buffering, retries, error handling, and tracking of internal statistics.

Submit DBM query samples via new aggregator API

---

apache/README.md
elastic/README.md
postgres/README.md

Adds Docker, Kubernetes, and ECS instructions for configuring Elasticsearch, Apache, and Postgres integrations.
https://docs-staging.datadoghq.com/cswatt/okr-previews-2/integrations/elastic
https://docs-staging.datadoghq.com/cswatt/okr-previews-2/integrations/apache
https://docs-staging.datadoghq.com/cswatt/okr-previews-2/integrations/postgres

Elasticsearch, Apache, Postgres - Docker, Kubernetes, ECS instructions

---

datadog_checks_base/datadog_checks/base/checks/base.py

An upcoming Agent PR will validate integrations that don't have a Python component

Allow the loading of arbitrary configuration models

---

envoy/datadog_checks/envoy/envoy.py
envoy/datadog_checks/envoy/parser.py
envoy/tests/docker/default/front-envoy.yaml
envoy/tests/test_parser.py

Metric containing multiple metric_parts for a metric that doesn't exist causes a loop. This PR tracks skip_parts.

Fix retry parsing when metric has multiple metric parts

---

kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py

If Kafka is not available at the time of agent start the error that shows in the logs is NoBrokerAvailable which is confusing both for users and SEs.
Often times the customer setup can have simultaneous agent+kafka starts and in that case the agent tries to hit kafka too soon. We should make more explicit how to avoid the situation.

Provide better error message when api version cannot be determined

---

kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py
kafka_consumer/datadog_checks/kafka_consumer/legacy_0_10_2.py

From 
`| (kafka_consumer.py:330) | ("Consumer group: my_consumer has offsets for topic: marvel, partition: 0, but that topic partition isn't included in the cluster partitions, so skipping reporting these offsets.",)`
to
`| (kafka_consumer.py:330) | Consumer group: my_consumer has offsets for topic: marvel, partition: 0, but that topic partition isn't included in the cluster partitions, so skipping reporting these offsets.`
qa

Fix warning log format

---

http_check/assets/configuration/spec.yaml
http_check/datadog_checks/http_check/config_models/defaults.py
http_check/datadog_checks/http_check/data/conf.yaml.example

The default value has always been `false` for the http_check. The wrong value is documented since https://github.com/DataDog/integrations-core/pull/7245/

Restore correct default value of tls_verify

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/testable.py

`ddev trello release command` assigns cards at random if you define a user table in `ddev config`. This can produce lop-sided assignments of QA cards:
```
Card assignments using ddev config
- ChristineTChen: 4
- FlorianVeaux: 2
- hithwen: 2
- mgarabed: 1
- ofek: 1
- coignetp: 1
- luisgonzalex: 0
```
This fix implements a different strategy to even out the QA cards while still being random.
1. Shuffle user defined list.
2. Assign card to user with least cards assigned (if there are multiple, will be assigned to first user with that minimum. Since order is shuffled initially, there are no adversarial cases). 
So now we have:
```
Card assignments using ddev config
integrations
- ChristineTChen: 1
- FlorianVeaux: 1
- hithwen: 2
- mgarabed: 2
- ofek: 2
- coignetp: 1
- luisgonzalex: 2
```
``` …
```

Fix QA card assignment to be distributed randomly and equally

---

mongo/assets/configuration/spec.yaml
mongo/datadog_checks/mongo/data/conf.yaml.example

Removes reference to config option deprecated in https://github.com/DataDog/integrations-core/pull/9142

Remove reference to connection_scheme

---

kafka_consumer/datadog_checks/kafka_consumer/legacy_0_10_2.py

Before:
`Identified api_version: True, kafka_consumer_offsets: ...`
After
`Identified api_version: (0, 9), kafka_consumer_offsets: ...`
QA #8795

Fix debug log message

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/readmes.py
datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/schema.py

Removing ascii validation in readmes in favor of https://github.com/DataDog/dogweb/pull/59406
Reducing ascii validation on certain fields in manifest.json (like public title)
Removing

Reduce ascii validation for assets

---

twemproxy/assets/configuration/spec.yaml
twemproxy/datadog_checks/twemproxy/data/conf.yaml.example

The port default is 2222 https://github.com/DataDog/integrations-core/blob/master/twemproxy/datadog_checks/twemproxy/twemproxy.py#L112

Reflect default port in config

---

kube_metrics_server/datadog_checks/kube_metrics_server/kube_metrics_server.py

In metrics server v0.4.0, metric names were renamed. https://github.com/kubernetes-sigs/metrics-server/releases
This PR supports both the new and old metric names.
I upgraded to metrics server 0.4.2 and noticed metrics are not submitted to datadog because of the missing metric names in the check.

Support 0.4.0 metrics server renamed metric names

---

twemproxy/README.md
twemproxy/assets/configuration/spec.yaml
twemproxy/datadog_checks/twemproxy/data/conf.yaml.example
twemproxy/manifest.json
twemproxy/tests/compose/docker-compose.yaml
twemproxy/tests/conftest.py

- Add Twemproxy log documentation
- Update docker configuration to allow logs to be sent via our e2e env. 
web-ui PR: Datadog/web-ui#30664
logs-backend: DataDog/logs-backend#18527

Add log support for Twemproxy

---

coredns/assets/dashboards/coredns.json

updates the layout of the coredns integration dashboard to use the new dashboard layout
https://dd.datad0g.com/dash/integration/30515/CoreDNS?from_ts=1619460465573&live=true&to_ts=1619464065573
new dashboard layout beta

coredns msl

---

mysql/datadog_checks/mysql/const.py
mysql/metadata.csv
mysql/tests/variables.py

When adding support for v8 API in https://github.com/DataDog/integrations-core/pull/8402 I missed this.
The test is not reliable because replication metrics are not always emitted, added a note about that.
Changes included:
* Ensuring seconds_behind_source/master is emited in all mysql versions
* Adding new metric to metadata csv and tests
Followup: https://github.com/DataDog/integrations-core/pull/9245

Account for name change in replica metrics

---

postgres/datadog_checks/postgres/postgres.py
postgres/datadog_checks/postgres/version_utils.py
postgres/tests/test_version_utils.py

The current method we have does not work well for all aurora versions and we were not correctly unsetting it when the exception was captured
We stoped using this query in https://github.com/DataDog/integrations-core/pull/7542 because it was polluting logs although https://github.com/DataDog/integrations-core/pull/7480 made it happen less often
**Best review hiding whitespace changes**
Changes:
* Make VersionUtils a class so it can log messages
* Revert way of checking for aurora
* When FeatureNotSupported is raised aurora is set to False instead of None and replication_metrics are depleted
* We log self.aurora instead of self._aurora

Revert way of checking if it's aurora

---

twemproxy/README.md

The port default is 2222 as of #9217.

Reflect default port in docs

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/status.py

Our old output was not really useful as the data density made it
difficult to quickly parse and as such it made it easy to ignore. The
new output only shows the most relevant datapoint (percentage complete)
which should increase signal-to-noise for this output. The old command
output can still be utilized with the addition of `--verbose` or `-v`
flag.
New Output:
```
Team                 Done
-------------------- ----
Core                  68%
Runtime-Security      70%
Platform              76%
Container App         78%
Networks              91%
Containers            93%
Integrations          97%
Logs                 100%
Processes            100%
Trace                100%
Tools and Libraries  100%
Infra-Integrations   100%
-------------------- ----
TOTAL                 89%
```
Old …

Make trello status command output be more usable

---

datadog_checks_base/datadog_checks/base/utils/db/statement_metrics.py
datadog_checks_base/tests/test_db_statements.py

This PR aims to fix bad query metrics due to duplicate query stat rows. This was first noted as wrong Postgres query trends showing up like this but because the way we determine query identity is based on the agent's normalized query, this is a good candidate for logic to be present in the base _statement_metrics.py_.
Concrete example of duplication resulting in bad query metrics:

Add merging of duplicate rows in statement_metrics

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/__init__.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/env/edit.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py

Add `ddev env edit` command
First, start an env:
```
ddev env start druid py38
```
Use default editor:
```
ddev env edit druid py38
```
Use specific editor:
```
ddev env edit druid py38 -e vim
ddev env edit druid py38 --editor vim
ddev env edit druid py38 --editor my_editor
ddev env edit druid py38 --editor /path/to/my/editor
```
Makes it easier to edit the config file.

Add `ddev env edit` command

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/validate_mib_filenames.py

Silent execution by default, prompt for user input if explicitly chosen
Review of https://github.com/DataDog/integrations-core/pull/9228

[SNMP] Invert interactive logic in validate mib files

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/generate_profile.py

Add interactive option to save generated profile tool to file
Review of https://github.com/DataDog/integrations-core/pull/9228

[snmp] add interactive option to generate profile tool

---

kubernetes/assets/dashboards/kubernetes_jobs.json
kubernetes/manifest.json

Add a default Kubernetes dashboard to monitor jobs & cronjobs.
See it in prod: https://app.datadoghq.com/dashboard/vci-wuu-nhr/kubernetes-jobs--cronjobs-overview-cloned
We are working on adding support for jobs & cronjobs in Kubernetes Resources for Live Containers, adding a dashboard as well makes sens.

[kubernetes] add jobs & cronjobs dashboard

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/stats/common.py

Since in the last few releases, we've had some tags created on the agent
with rc-matching regex pattern, the 'merged-prs' stats were incorrectly
calculating the changes between RCs. This change applies a fix to
exclude these tag patterns from being evaluated by the release stats.
Erroneous output of `ddev release stats merged-prs` command

[release scripting] Fix tag filtering for `ddev release stats` command

---

.azure-pipelines/changes.yml
.azure-pipelines/templates/run-validations.yml
.azure-pipelines/templates/test-all.yml
.azure-pipelines/templates/test-single-linux.yml
.azure-pipelines/templates/test-single-windows.yml

Adds a specific flag to control whether the Azure Template will trigger the `ddev validate codeowners` step. 
Currently, this is only being run if the `repo` parameter is set to `extras`. This lets individual repositories control whether it would like to use this functionality.  This defaults to false. 
If we aren't interested in starting validation_* specific flags, I can change instead to adding to the list of repos that this should trigger for.

Add dedicated validate_codeowners CI flag

---

.azure-pipelines/templates/test-all.yml

Github Actions doesn't allow setting a parameter twice, so remove the hard-coded value here to fix - https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=61089&view=results

Remove second parameter definition

---

datadog_checks_base/datadog_checks/base/utils/db/statement_metrics.py

With https://github.com/DataDog/integrations-core/pull/9227 which performs a merge of rows by key, we should never see any colliding rows when computing derivative rows. Because of this, the log showing the detection of a collision would be much more serious and an indicator of a bug so this increases the logging from `debug` to `error`.

Change 'collision in cached query metrics' log from debug to error

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/codeowners.py

Sqreen is a tile-only intg in `integrations-extra`. This PR is to fix the CI on the codeowners validation.

Add Sqreen to ignored integrations for codeowners validation

---

solr/metadata.csv

Some Solr request_times metrics should be in millisecond (not req/s).
https://solr.apache.org/guide/8_4/performance-statistics-reference.html#commonly-used-stats-for-request-handlers

Fix metric type to match description

---

kafka/datadog_checks/kafka/data/metrics.yaml
kafka/metadata.csv
kafka/tests/common.py

A new metric for the number of kafka sessions has been added.
This metric helps determine large scale of kafka parameters for `max.incremental.fetch.session.cache.slots`
When using kafka with many consumers, some parameters need to optimize performance.
https://cwiki.apache.org/confluence/display/KAFKA/KIP-227%3A+Introduce+Incremental+FetchRequests+to+Increase+Partition+Scalability

Kafka - Added session metrics

---

pgbouncer/README.md

Request user test their connection is setup correctly before adding to datadog agent
The user should test their connection with the datadog user _before_ attempting to connect via the agent.
When the connection fails, the datadog agent status reports an issue with 'show version'. Ensuring that the user can run this command beforehand prevents the user from seeing this vague error.
- [N/A] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [Y] PR title must be written as a CHANGELOG entry [(see why)](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title)
- [Y] Files changes must correspond to the primary purpose of the PR as described in the title (small unrelated changes should have their own PR)
- [Y] PR must have `changelog/` …

Test datadog connection for pgBouncer before connecting via agent

---

kubernetes_state/datadog_checks/kubernetes_state/data/auto_conf.yaml
kubernetes_state/datadog_checks/kubernetes_state/data/conf.yaml.example

Tiny change to the example configuration in the `auto_conf.yaml` for `kubernetes_state`.
I tried copying the example configuration and it didn't work. Had to read the code to figure out the correct value.
No.

update kubernetes_state auto_conf.yaml with valid example configuration

---

snmp/datadog_checks/snmp/data/conf.yaml.example

APC-UPS was referencing the wrong definition file under the profiles dir.
This should be apc_ups.yaml
as per:
https://github.com/DataDog/integrations-core/blob/master/snmp/datadog_checks/snmp/data/profiles/apc_ups.yaml
Changes conf.yaml.example file with correct apcups file definition.
Picked up whilst investigating other snmp config issues for a customer.

Update conf.yaml.example - wrong file name

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/changelog.py

Avoid changelog entries like "`* Some sentence..`" (double stop) when PR title is "`Some sentence.`".
Prompted by https://github.com/DataDog/integrations-core/pull/8441#discussion_r563543391
Prevent unnecessary work when reviewing changelogs, esp during Agent releases.

Avoid double periods at the end of PR titles

---

envoy/datadog_checks/envoy/metrics.py
envoy/metadata.csv

Add a handful of missing Envoy metrics from the HTTP router filter. (https://www.envoyproxy.io/docs/envoy/v1.17.0/configuration/http/http_filters/router_filter.html?highlight=vhost#virtual-clusters)
Using those metrics.

Add missing Envoy HTTP router filter vhost metrics

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/manifest.py
datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/validator.py

Do not share validator instances across checks
Correctly check for exception

Fix validator bugs

---

.gitlab/reminder/Dockerfile
.gitlab/tagger/Dockerfile
.gitlab/validate-logs-intgs/Dockerfile

Pull from an internal repo instead of docker hub to prevent rate limiting

Update base image to internal docker repository

---

.gitlab-ci.yml

Disable these jobs for now.
Unfortunately the `only: changes` keyword always returns `True` on a new branch. Which means any new feature branch is triggering these jobs.

Disable the agent build trigger

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
vsphere/requirements.in

Needed to support vSphere 7
First step for vsphere 7 support
`pyvmomi` is used to communicate with the SOAP API.
As they suggest in their doc https://github.com/vmware/pyvmomi
```
Pyvmomi maintains minimum backward compatibility with the previous _four_ releases of vSphere and it's own previous four releases. Compatibility with much older versions may continue to work but will not be actively supported.
```
So it should work from vSphere 6.0

Upgrade pyvmomi to 7.0.2

---

mysql/datadog_checks/mysql/mysql.py
mysql/datadog_checks/mysql/queries.py
mysql/tests/test_mysql.py

This adds the tag `replication_role` if the check runs against a database running in AWS Aurora. If the database is a "reader" then the tag `replication_role:reader` will be added, and if the database is the writer then the tag `replication_role:writer` will be added.
In a future PR, I can expand this to include non-AWS Aurora databases as well.
This feature was specifically requested by Zendesk so they can filter queries to queries running on a read-only or read-write database. The primary use case is to identify read queries on the primary which could instead be issued on one of the replicas.

Adds a `replication_role` tag to metrics emitted from AWS Aurora instances

---

envoy/assets/configuration/spec.yaml
envoy/datadog_checks/envoy/config_models/defaults.py
envoy/datadog_checks/envoy/config_models/instance.py
envoy/datadog_checks/envoy/data/conf.yaml.example
envoy/datadog_checks/envoy/envoy.py
envoy/tests/common.py
envoy/tests/test_envoy.py

Add a config option to Envoy check to  disable checking the `/server_info` endpoint to collect metadata. This cannot be accessed in some configurations of Envoy, like consul connect or kubernetes deployments that only expose the `/stats` endpoint. 
Users will be spammed with logs otherwise:
```text
2021-04-27 20:44:34 UTC | CORE | INFO | (pkg/collector/python/datadog_agent.go:124 in LogMessage) | envoy:706dc0e2f7ee4a62 | (envoy.py:156) | Envoy endpoint `http://172.17.0.9:90/server_info` responded with HTTP status code 404
```

Add collect_server_info config option

---

otel/metadata.csv

Fix metadata description for `otel.datadog_exporter.*.running`, stating that one metric is sent per instrumented host.
Originally this metric was reported only by the host where the Datadog exporter was running, but this was later extended in open-telemetry/opentelemetry-collector-contrib#2023 to account for situations where a metric was forwarded through multiple OpenTelemetry Collectors, which changed the meaning of the metric. 
The naming is confusing now, but we can't change it for backwards-compatibility reasons :(
Relates to open-telemetry/opentelemetry-collector-contrib#3293.

Update running metrics description

---

vsphere/datadog_checks/vsphere/api_rest.py
vsphere/datadog_checks/vsphere/vsphere.py
vsphere/tests/common.py
vsphere/tests/conftest.py
vsphere/tests/mocked_api.py
vsphere/tests/test_api_rest.py
vsphere/tests/test_cache.py
vsphere/tests/test_check.py
vsphere/tox.ini

https://core.vmware.com/blog/vsphere-7-update-2-rest-api-modernization
A new REST API was introduced in vsphere 7, so we try to use it instead of the deprecated one when possible.
The deprecated API should be maintained in the 2 next vsphere major releases

Use new REST API when possible

---

vsphere/datadog_checks/vsphere/api_rest.py

Fix HTTP config option usage changed in #9293 
`no-changelog` since there was no release in between.

Fix http config use

---

mysql/datadog_checks/mysql/mysql.py
mysql/datadog_checks/mysql/statements.py
mysql/tests/test_mysql.py

Send DBM query metrics via the new aggregator API added in https://github.com/DataDog/integrations-core/pull/9165
Migrate to new DBM metrics intake.

Send database monitoring query metrics to new intake

---

mysql/datadog_checks/mysql/statement_samples.py
postgres/datadog_checks/postgres/statement_samples.py

Deprecate the `service` event facet in favor of sending "service" only as a regular tag.

Remove `service` event facet

---

kubernetes_state/datadog_checks/kubernetes_state/kubernetes_state.py
kubernetes_state/metadata.csv
kubernetes_state/tests/test_kubernetes_state.py

Add `kubernetes_state.node.by_condition` metric to have the conditions of individual nodes.
The current `kubernetes_state.nodes.by_condition` (with an `s`. Plural vs. singular) metric aggregates all nodes by condition.
With this metric, we could know how many nodes were in a given condition, but not more precisely which ones.
The new metric allows to know precisely which nodes are in a given condition.

KSM: add `node.by_condition` to have the conditions of individual nodes

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py

Adds the Synthetics `run` unit, that represents test runs.
We want to add support for this new unit, that will be first used for estimated metrics.
https://datadoghq.atlassian.net/browse/SSV-547
Linked to PR https://github.com/DataDog/dogweb/pull/60065

Support new Synthetics `run` metric unit for validation

---

datadog_checks_base/datadog_checks/base/utils/http.py

Otherwise the ExtensionNotFound is raised by the AttributeError call.
This will also make sure that the cant_connect service check is correctly emitted in case something goes wrong

Fix AttributeError in AIA chasing

---

amazon_msk/datadog_checks/amazon_msk/config_models/instance.py
coredns/datadog_checks/coredns/data/conf.yaml.example
datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/openmetrics_legacy.yaml
istio/datadog_checks/istio/config_models/instance.py
openmetrics/datadog_checks/openmetrics/data/conf.yaml.example

Fix incorrect validation spec for istio integration.
The istio validation spec expects metrics to be a list of strings (Sequence[str]). It is in fact supposed to be a list of maps (Sequence[Mapping[str, str]]).

Fix `metrics` option type for legacy OpenMetrics config spec

---

datadog_checks_dev/setup.py

`click` recently released v8.0.0
For some unknown reason currently, `ddev --version` doesn't work anymore and this breaks our CI.

Pin click to 7.1.2

---

eks_fargate/README.md

Clarifies that it is expected for EKS Fargate containers to not show CPU and Memory metrics on the Live Containers page.

[eks_fargate] small update regarding metrics on live containers page

---

spark/README.md

Removed the below note because there are now 5 Spark Structured Streaming metrics in the metrics section.
**Note**: Spark Structured Streaming metrics are not supported.
Removes **Note**: Spark Structured Streaming metrics are not supported.
Zendesk ticket: https://datadog.zendesk.com/agent/tickets/485593

[doc] Removed  **Note** for Spark Structured Streaming metrics

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in

Reverts DataDog/integrations-core#9348

Revert "Update pycryptodome to 3.10.1"

---

elastic/assets/configuration/spec.yaml
elastic/datadog_checks/elastic/data/conf.yaml.example
elastic/datadog_checks/elastic/elastic.py

Update version supported for Elasticsearch Cat Allocation metrics
`disk.indices` available from 5.0.0
https://www.elastic.co/guide/en/elasticsearch/reference/5.0/cat-allocation.html
AGENT-6188
Oldest es version I was able to test this on is 5.3

Update version supported for Cat Allocation metrics

---

postgres/datadog_checks/postgres/statements.py

Update the collection of postgres query metrics to exclude `EXPLAIN` queries.
If deep database monitoring is enabled and we are collecting execution plans, then there will be at least one tracked EXPLAIN statement for every unique normalized query we encounter. Since these statements are not used in the product we exclude them from collection.
This updates postgres to have the same behavior as mysql, where we do the same exclusion for query metrics.

Exclude `EXPLAIN` queries from `pg_stat_statements`

---

.gitlab-ci.yml
.gitlab/validate-agent-build/Dockerfile
.gitlab/validate-agent-build/trigger_agent_build.py
.gitlab/validate-agent-build/validate_agent_build.py

1. Re-enable the trigger and validate job builds
2. These jobs are now run on every branch but are immediatly skipped unless the agent_requirements.in file has been modified. This comes from a gitlab limitation, we don't have a way to enable a specific job based on whether the branch is modifying a file against master.
3. If the file has been modified, the script triggers a build pipeline, sends a slack message and wait for completion.

Reenable agent build tests

---

activemq/datadog_checks/activemq/data/conf.yaml.example
cassandra/datadog_checks/cassandra/config_models/defaults.py
cassandra/datadog_checks/cassandra/config_models/shared.py
cassandra/datadog_checks/cassandra/data/conf.yaml.example
confluent_platform/datadog_checks/confluent_platform/data/conf.yaml.example
datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/init_config/jmx.yaml
hazelcast/datadog_checks/hazelcast/data/conf.yaml.example
hive/datadog_checks/hive/data/conf.yaml.example
hivemq/datadog_checks/hivemq/data/conf.yaml.example
ignite/datadog_checks/ignite/data/conf.yaml.example
jboss_wildfly/datadog_checks/jboss_wildfly/data/conf.yaml.example
kafka/datadog_checks/kafka/config_models/defaults.py
kafka/datadog_checks/kafka/config_models/shared.py
kafka/datadog_checks/kafka/data/conf.yaml.example
presto/datadog_checks/presto/data/conf.yaml.example
solr/datadog_checks/solr/data/conf.yaml.example
sonarqube/datadog_checks/sonarqube/data/conf.yaml.example
tomcat/datadog_checks/tomcat/config_models/defaults.py
tomcat/datadog_checks/tomcat/config_models/shared.py
tomcat/datadog_checks/tomcat/data/conf.yaml.example

`collect_default_metrics` is optional
need for https://github.com/DataDog/integrations-core/pull/8985

Fix JMX config spec

---

docs/developer/guidelines/dashboards.md

Notable changes:
- Changed numbered items to all `1` to easily show when chains are broken
- Fixed images and notes to align with their respective items
- Replaced macOS single/double quotes with normal ones
- Made image links use relative paths

Fix formatting

---

datadog_checks_dev/datadog_checks/dev/utils.py

After https://github.com/DataDog/integrations-core/pull/9364, if an integration sets `is_jmx` as optional `init_config` will have no fields and thus be `None`.
Need for https://github.com/DataDog/integrations-core/pull/8985

Fix `load_jmx_config` utility

---

kafka_consumer/assets/configuration/spec.yaml
kafka_consumer/datadog_checks/kafka_consumer/config_models/instance.py
kafka_consumer/datadog_checks/kafka_consumer/data/conf.yaml.example
kafka_consumer/tox.ini

`zk_connect_str` was an array of object, but we actually support it as `string` or `array of string` https://github.com/DataDog/integrations-core/blob/4dcb5e6acd2c3607e694f2d45114ef1b07880496/kafka_consumer/datadog_checks/kafka_consumer/legacy_0_10_2.py#L56-L59 
Our default environment configuration does not pass the model validation
It will break some of our customer config that we actually support

Fix zk_connect_str type

---

.gitlab/validate-agent-build/validate_agent_build.py

I realized that when the job was timing out, it was considered a success by gitlab.
This PR adds a log line and exit the script with a non-zero exit code

Notify author on agent build time out

---

datadog_checks_dev/datadog_checks/dev/_env.py

Be more exact
This line https://github.com/DataDog/integrations-core/blob/0009096519d109b8a0dc93e96c170a55c8a82e33/.azure-pipelines/templates/test-single-windows.yml#L31 introduced in https://github.com/DataDog/integrations-core/pull/9140 made it so environments were always spun up on Windows CI
See `sqlserver` https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=60559&view=results

Fix detection of E2E environments

---

redisdb/tests/test_replication.py

With `redis:latest`, there is now different behavior for `master_link_down_since_seconds`: https://github.com/redis/redis/pull/8785
> When replica never successfully connect to master, server.repl_down_since
will be initialized to 0, therefore, the info master_link_down_since_seconds
was showing the current unix timestamp, which does not make much sense.
This commit fixes the issue by showing master_link_down_since_seconds to -1.
means the replica never connect to master before.
So now need to check that the metric value is not equal to zero.

Fix replication link metric test

---

twemproxy/tests/compose/Dockerfile
twemproxy/tox.ini

ubuntu 14 is too old, pip doesn't work anymore on it

Fix twemproxy tests

---

postgres/assets/configuration/spec.yaml
postgres/datadog_checks/postgres/config_models/defaults.py
postgres/datadog_checks/postgres/config_models/instance.py
postgres/datadog_checks/postgres/data/conf.yaml.example

The statement metric limits have been removed in [this commit](https://github.com/DataDog/integrations-core/commit/26d90d6e73c135e3bc0c590ec195d459165dc89f#diff-157c2960ae5c7408275369d11207e5635cb0515cdc0b898396c4d043df08576d) but there were a few leftovers. This PR cleans up the map of default config values as well as the references in the configuration example.
Cleaning up to avoid confusion by users that might see the metric limit configs and try to use them.

Remove unused query metric limit configuration refs in postgres integration

---

mapr/datadog_checks/mapr/mapr.py

`auth_ticket` is not required for all environment, and assigning an environment variable with `None` raises an exception.
Support case

Fix init failure when auth_ticket is not provided

---

wmi_check/README.md

Default WMI dashboard does not fully populate with the sample shown, however, it does when using a sample config (third party) that can be found here:
https://github.com/vagelim/windows-server-2012/blob/master/wmi_check.yaml
Update WMI documentation to include a full example
Customer had issue getting WMI going with all possible metrics, and found this PR linked from an escalation / blog article
This might be formatted in a better way, using this an example.

Update WMI check to include full sample

---

ibm_mq/datadog_checks/ibm_mq/collectors/channel_metric_collector.py
ibm_mq/datadog_checks/ibm_mq/collectors/queue_metric_collector.py
ibm_mq/datadog_checks/ibm_mq/collectors/stats_collector.py

Ignores https://www.ibm.com/docs/en/ibm-mq/9.2?topic=codes-2033-07f1-rc2033-mqrc-no-msg-available as expressed in:
- https://github.com/dsuch/pymqi/blob/v1.12.0/docs/examples.rst#how-to-wait-for-multiple-messages
- https://stackoverflow.com/a/57352594/5854007
Feedback

Don't emit warnings if there are no messages

---

datadog_checks_downloader/datadog_checks/downloader/exceptions.py

Provide a better hint for users.

Better error message if the integration doesn't have the expected type

---

.azure-pipelines/all_master.yml
datadog_checks_base/datadog_checks/base/checks/base.py

some services use the port 8126 we can encounter some checks failing because they are trying to access that port. Fixes CI for statsd.
statsd:
```
---------------------------- Captured stderr setup -----------------------------
Creating network "compose_default" with the default driver
Building statsd
Image for service statsd was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating compose_statsd_1 ... Host is already in use by another container
Creating compose_statsd_1 ... error
ERROR: for compose_statsd_1  
Cannot start service statsd: 
driver failed programming external connectivity on endpoint compose_statsd_1 (50f0c363a38cc6fec9a7cd6379d2b9280e1257a42d0e7e6bda8cda596f2352ad): 
Bind for 0.0.0.0:8126 …
```

Change agent port for ddtrace

---

postgres/datadog_checks/postgres/config.py
postgres/datadog_checks/postgres/statements.py
postgres/tests/test_pg_integration.py

When collecting query metrics, send the full length query text in separate "full query text" events. These events are rate limited to a low default rate limit of one event per hour.
Sending the full query text separately enables us to significantly reduce the size of the query metrics payload by sending only the first 200 characters of each query.
* Enable full text search for all queries including those for which we don't capture any samples
* Reduce size of DBM metrics payload
Follow-up to https://github.com/DataDog/integrations-core/pull/9397

Send database monitoring "full query text" events

---

ibm_mq/datadog_checks/ibm_mq/connection.py
ibm_mq/tests/test_ibm_mq_unit.py

In some cases, pymqi can raise a `MQRC_HOST_NOT_AVAILABLE` exception due to a normal connection instead of an SSL connection.
If the normal connection raises a `MQRC_HOST_NOT_AVAILABLE` exception, we now try an SSL connection before failing (when SSL is configured)
Support case

Try SSL connection when host not found

---

datadog_checks_base/datadog_checks/base/stubs/datadog_agent.py

Update the stub `obfuscate_sql` whitespace trimming behavior to match that of the go implementation.
See also https://github.com/DataDog/datadog-agent/pull/8218
Update the stub behavior to better match the core implementation behavior.

update `DatadogAgentStub.obfuscate_sql` to trim whitespace

---

ibm_mq/README.md

MQ 5, was released on October 1997. The integration was developed in 2018 and version 8 came out in 2014.
Since we depend on IBM provided libraries is not possible for us to support eoled versions

Fix version compatibility

---

glusterfs/datadog_checks/glusterfs/check.py
glusterfs/tests/test_glusterfs.py
glusterfs/tox.ini

A customer is getting this error
```
glusterfs (1.1.2)
-----------------
...
Error: cannot unpack non-iterable NoneType object
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 897, in run
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/glusterfs/check.py", line 82, in check
self.submit_version_metadata(data)
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 696, in entrypoint
method(self, *args, **kwargs)
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/glusterfs/check.py", line 111, in submit_version_metadata
major, minor = self.parse_version(raw_version)
TypeError: …
```

Fix version parsing

---

tls/datadog_checks/tls/tls.py
tls/datadog_checks/tls/tls_local.py
tls/datadog_checks/tls/tls_remote.py
tls/tests/test_local.py
tls/tests/test_remote.py

Having inheritance on a check will cause the agent to not load it properly. The issue presents in this case when there is more than one instance of the check. The first instance will load the child class and the second instance will fail to find the parent class
The fix here (we can think of something more elegant for long term) is to pass the parent class to the now not children classes and explicitly call it instead of using self

Do not use check inheritance

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
supervisord/requirements.in

https://github.com/supervisor/meld3
> No further development of the meld3 package is planned.  The meld3 package
should be considered unmaintained as of April 2020.  Since 2007, meld3
received only minimal updates to keep compatible with newer Python versions.
It was only maintained because it was a dependency of the Supervisor package.
Since Supervisor 4.1.0 (released in October 2019), the meld3 package is
no longer a dependency of Supervisor.

Remove unused dependency

---

elastic/README.md

Change check name in Kubernetes instruction from elasticsearch to elastic
https://docs.datadoghq.com/integrations/elastic/?tab=kubernetes#configuration
It's incorrect. Encountered by customer (ZD Ticket Number 491514)

Change check name in Kubernetes instruction from elasticsearch to elastic

---

sqlserver/datadog_checks/sqlserver/connection.py
sqlserver/tests/test_connection.py

Set correct connector options. Will fix the misleading warning message below.
```
2021-05-25 04:29:40 UTC | CORE | WARN | (pkg/collector/python/datadog_agent.go:122 in LogMessage) | sqlserver:d4e72e3cb271f16d | (connection.py:313) | adoprovider option will be ignored since adodbapi connection is used
2021-05-25 04:29:40 UTC | CORE | DEBUG | (pkg/collector/python/datadog_agent.go:126 in LogMessage) | sqlserver:d4e72e3cb271f16d | (connection.py:252) | Overriding default ADO provider for localhost,1433 with MSOLEDBSQL
2021-05-25 04:29:40 UTC | CORE | DEBUG | (pkg/collector/python/datadog_agent.go:126 in LogMessage) | sqlserver:d4e72e3cb271f16d | (connection.py:373) | Connection string (before password) Provider=MSOLEDBSQL;Data Source=localhost,1433;Initial Catalog=master;
```
AGENT-6278

Fix misleading WARN message regarding adoprovider being ignored when using adodbapi connector

---

activemq/datadog_checks/activemq/data/conf.yaml.example
cassandra/datadog_checks/cassandra/data/conf.yaml.example
confluent_platform/datadog_checks/confluent_platform/data/conf.yaml.example
datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/init_config/jmx.yaml
hazelcast/datadog_checks/hazelcast/data/conf.yaml.example
hive/datadog_checks/hive/data/conf.yaml.example
hivemq/datadog_checks/hivemq/data/conf.yaml.example
ignite/datadog_checks/ignite/data/conf.yaml.example
jboss_wildfly/datadog_checks/jboss_wildfly/data/conf.yaml.example
kafka/datadog_checks/kafka/data/conf.yaml.example
presto/datadog_checks/presto/data/conf.yaml.example
solr/datadog_checks/solr/data/conf.yaml.example
sonarqube/datadog_checks/sonarqube/data/conf.yaml.example
tomcat/datadog_checks/tomcat/data/conf.yaml.example

Fix https://github.com/DataDog/integrations-core/pull/9364
https://github.com/DataDog/datadog-agent/blob/8081b2ba06ac5e4275c1bc0011cfabb19d26053d/pkg/collector/check/jmx.go#L93-L96

Fix defaults for `collect_default_metrics` JMX config option

---

kubelet/datadog_checks/kubelet/data/conf.yaml.default
kubelet/datadog_checks/kubelet/data/conf.yaml.example

Increase Kubelet default scraping time from 15s to 20s to avoid rates with `0` values due to cAdvisor dynamic refresh time which oscillates between 10 and 20s.
Avoid bad data points (see https://github.com/google/cadvisor/blob/master/docs/runtime_options.md#housekeeping)

Increase Kubelet default scraping time from 15s to 20s

---

elastic/README.md

Change Elasticsearch default url protocol to HTTP like in the setting in auto_conf.yaml
https://github.com/DataDog/integrations-core/blob/master/elastic/datadog_checks/elastic/data/auto_conf.yaml
Inconsistent doc
affects https://docs.datadoghq.com/integrations/elastic/?tab=docker#configuration

elasticsearch url default is http, not https

---

sap_hana/datadog_checks/sap_hana/sap_hana.py
sap_hana/metadata.csv
sap_hana/tests/metrics.py
sap_hana/tests/test_unit.py

Resolves following errors:
```
Unexpected error running `query_connection_overview`: 'receiving'
Unexpected error running `query_connection_overview`: 'sending'
```
AGENT-6213
traceback added to the code for troubleshooting. Original error did not mention `KeyError`
```
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/sap_hana/sap_hana.py", line 95, in check
query_method()
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/sap_hana/sap_hana.py", line 191, in query_connection_overview
db_counts[(conn['db_name'], conn['host'], conn['port'])][conn['status'].lower()] += conn['total']
KeyError: 'receiving'
```

Resolve unexpected errors when statuses other than 'running' or 'idle' is received

---

ibm_mq/datadog_checks/ibm_mq/collectors/channel_metric_collector.py
ibm_mq/tests/test_ibm_mq_int.py

Follow up of https://github.com/DataDog/integrations-core/pull/9400/files
There was one place where the warning was still logged incorrectly

Don't emit any warnings if NO_MSG_AVAILABLE is received

---

mysql/setup.py
postgres/setup.py
voltdb/setup.py
win32_event_log/setup.py

Bump minimum base package requirement for integration failing on master CI
`win32_event_log`: failing when adding configuration model
`postgres`, `mysql`: probably failing after `#9227` and `#9253`

Bump minimum base package requirement

---

LICENSE-3rdparty.csv
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/licenses.py

Cryptography license update to fix master CI

Update 3rd party license validation

---

kubernetes_state/datadog_checks/kubernetes_state/kubernetes_state.py
kubernetes_state/tests/test_kubernetes_state.py

Fix the `kubernetes.node.by_condition` metric introduced by #9311 to make it have the same behaviour as the `kubernetes_state_core` check.
* The `host` of the metric were always the host running the agent instead of node concerned by the metric
* Only the “active” (value == 1) metric must be taken into account.

KSM: fix `node.by_condition` metric

---

postgres/datadog_checks/postgres/statements.py
postgres/tests/test_pg_integration.py

Remove the incorrect `db` tag inherited from the check instance tags from postgres DBM statement metrics & FQT events. 
Also improve tests to clarify the expected tags for both metrics and FQT events.
This tag needs to be excluded because statement metrics & FQT events are collected from all databases on the host as of https://github.com/DataDog/integrations-core/pull/9252. DBM statement samples are already doing the right thing here.

Remove instance-level database tag from DBM metrics & events

---

haproxy/assets/configuration/spec.yaml
haproxy/datadog_checks/haproxy/config_models/defaults.py
haproxy/datadog_checks/haproxy/config_models/instance.py
haproxy/datadog_checks/haproxy/data/conf.yaml.example

`collect_aggregates_only` option can be `true`, `false`, or `both`, so it's not a boolean.
QA #8924

Fix collect_aggregates_only option type

---

yarn/assets/configuration/spec.yaml
yarn/datadog_checks/yarn/config_models/defaults.py
yarn/datadog_checks/yarn/config_models/instance.py
yarn/datadog_checks/yarn/data/conf.yaml.example

There are in code default values for these

Remove required when there are default values

---

datadog_checks_dev/datadog_checks/dev/tooling/specs/configuration/spec.py
vertica/assets/configuration/spec.yaml
vertica/datadog_checks/vertica/config_models/defaults.py
vertica/datadog_checks/vertica/config_models/instance.py
vertica/datadog_checks/vertica/data/conf.yaml.example
vertica/datadog_checks/vertica/vertica.py

These values were not actually required before:
* There was no config option thrown
* They were set to '' if missing
* vertica lib assigned them actual default values
So I've updated the check to reflect what vertica is doing in case it changes in an update.

Fix required values in vertica

---

http_check/assets/configuration/spec.yaml
http_check/datadog_checks/http_check/config_models/instance.py
http_check/datadog_checks/http_check/data/conf.yaml.example

We actually support `string` types https://github.com/DataDog/integrations-core/blob/e7c8157ecfd41136939d514d2df986a97015e93c/http_check/datadog_checks/http_check/http_check.py#L129 and we're testing that use case https://github.com/DataDog/integrations-core/blob/e7c8157ecfd41136939d514d2df986a97015e93c/http_check/tests/common.py#L225
Support case

Fix data configuration type

---

mysql/datadog_checks/mysql/mysql.py
mysql/tests/test_mysql.py

Fixes a regression added in https://github.com/DataDog/integrations-core/pull/9223, ensuring that DBM metrics & samples receive the aurora `replication_role` tag.
Fix missing tag.

Fix missing replication_role tag on DBM metrics & events

---

sqlserver/datadog_checks/sqlserver/sqlserver.py

Although these a key error here is probably an indicator of something else going wrong it can cause misleading errors on the logs. This change also lets the check continue if just some things are missing

Do not throw key errors
