cri/README.md

Zendesk ticket:
https://datadog.zendesk.com/agent/tickets/465355
Update the broken link for `sample cri.d/conf.yaml`
https://datadog.zendesk.com/agent/tickets/465355

Update the broken link for sample cri.d/conf.yaml

---

cassandra/assets/dashboards/cassandra_overview_screenboard.json
cassandra/manifest.json

Also add a section for `Cassandra Nodetool`.
[Staging Link](https://dd.datad0g.com/screen/integration/30592/cassandra-overview?from_ts=1616517866880&live=true&to_ts=1616604266880&tv_mode=false)

Revamp Cassandra dashboard to blog-like

---

http_check/datadog_checks/http_check/config_models/__init__.py
http_check/datadog_checks/http_check/config_models/defaults.py
http_check/datadog_checks/http_check/config_models/instance.py
http_check/datadog_checks/http_check/config_models/shared.py
http_check/datadog_checks/http_check/config_models/validators.py

Adds config models from https://github.com/DataDog/integrations-core/pull/8675

Add runtime configuration validation

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/__init__.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/all_validations.py

This mimics the configuration we have in our `run_validations.yml` to limit certain validations to certain repos.

Add command to run all validations at once

---

cloud_foundry_api/manifest.json
jboss_wildfly/manifest.json
nagios/manifest.json

Update check manifests to ensure there is a `metric_to_check` defined.  See validation update in #9042 for more details.

Add metrics to check for validation

---

docs/developer/meta/config-models.md
mkdocs.yml

https://github.com/DataDog/integrations-core/pull/8675

Add dev docs for config models

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py

Add "exception" to the list of units.
This unit is needed for the .NET Runtime Metrics dashboard.

Add "exception" unit to metadata

---

twemproxy/tests/compose/Dockerfile
twemproxy/tests/compose/docker-compose.yaml
twemproxy/tests/compose/resources/confd/conf.d/twemproxy.toml
twemproxy/tests/compose/resources/confd/templates/twemproxy.tmpl
twemproxy/tests/compose/resources/run.sh
twemproxy/tests/compose/resources/supervisord.conf
twemproxy/tox.ini

For testing and better internal use.

Add e2e docker env for twemproxy

---

prometheus/README.md

minor changes to prometheus docs for alertmanager
conversation with Yair

separate alertmanager into its own section

---

aspdotnet/README.md

Add logging documentation for ASP.NET

---

datadog_checks_dev/setup.py

It's been a while https://virtualenv.pypa.io/en/latest/changelog.html

Upgrade virtualenv to 20.4.3

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/manifest.py

Extend PR #9098 to exclude marketplace repo as well.

Ignore validation for marketplace

---

openstack_controller/assets/configuration/spec.yaml
openstack_controller/datadog_checks/openstack_controller/data/conf.yaml.example
openstack_controller/manifest.json

Add config spec for Openstack Controller

---

datadog_checks_dev/datadog_checks/dev/tooling/catalog_const.py

Update won't do logs list

---

pan_firewall/README.md

fix links in PAN

---

activemq_xml/README.md

There was a link that was not being referenced correctly and the numbers did not start from 1.

Fix link numbers in activemq docs

---

vsphere/assets/dashboards/vsphere_overview.json

Template variable had a wrong default

Fix vSphere dash template var

---

snmp/datadog_checks/snmp/data/conf.yaml.example

Add doc for instance batch size config
https://github.com/DataDog/datadog-agent/pull/7818

Add doc for instance batch size config

---

amazon_msk/setup.py
kong/setup.py
vault/setup.py

Nightly CI failing:
* `amazon_msk`: needs #9108 first (for #9077)
* `kong`: because it can't find `OpenmetricsCheckV2`
* `vault`: because it needs #8750

Bump minimum base package

---

openstack/assets/configuration/spec.yaml
openstack/datadog_checks/openstack/data/conf.yaml.example
openstack/manifest.json

Add config spec for Openstack

---

kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py

Fixes a missing `if` clause in #9089 for non-legacy part of the check.

Fix partition check

---

presto/assets/dashboards/overview.json

Update presto dashboard with the new MSL guidelines

Update dashboard MSL

---

datadog_checks_dev/datadog_checks/dev/docker.py
datadog_checks_dev/datadog_checks/dev/tooling/e2e/agent.py
datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py
docs/developer/ddev/plugins.md

Support running the Windows container version of the Agent for E2E
Run Windows E2E tests in CI

Support running Windows containers for E2E

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/requirements.in

Prerequisite for #9124 and #9125 
Latest is not available in on windows py27 env

Upgrade ddtrace

---

datadog_checks_dev/datadog_checks/dev/fs.py

import open from `io` to py2/3 compatibility

Fix open import for fs util

---

datadog_checks_dev/datadog_checks/dev/kind.py
datadog_checks_dev/datadog_checks/dev/kube_port_forward.py
directory/tests/test_directory.py
openldap/tests/conftest.py
openstack_controller/tests/conftest.py
postfix/tests/conftest.py
vault/tests/conftest.py

Fix imports changed due to filesystem util refactor

Fix refactored imports

---

journald/manifest.json

Replace https://github.com/DataDog/documentation/blob/master/content/en/integrations/journald.md

Enable docs for journald integration

---

confluent_platform/README.md

Update Readme
Wrong statement about SQL.
- [X ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [X ] PR title must be written as a CHANGELOG entry [(see why)](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title)
- [X ] Files changes must correspond to the primary purpose of the PR as described in the title (small unrelated changes should have their own PR)

Correct SQL by KSQLDB

---

ibm_mq/assets/configuration/spec.yaml
ibm_mq/datadog_checks/ibm_mq/data/conf.yaml.example

Based on customer issue AGENT-5715

Add a bit more info to ibm mq

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/manifest.py
datadog_checks_dev/datadog_checks/dev/tooling/utils.py

Split of https://github.com/DataDog/integrations-core/pull/9111
Moves a function to common utils as it might be useful for other things

Move function to utils

---

aspdotnet/assets/dashboards/overview.json
aspdotnet/manifest.json

[Staging Link](https://dd.datad0g.com/dash/integration/30596/aspnet---overview?from_ts=1617647187477&live=true&to_ts=1617650787477&tv_mode=false)

Add ASP.NET dashboard

---

prometheus/README.md

minor change to edit bad link
fixes bad link at bottom of page
seeing what the link looks like in prod

update prometheus docs

---

openstack/assets/configuration/spec.yaml
openstack/datadog_checks/openstack/data/conf.yaml.example

Include missing default config templates

---

elastic/datadog_checks/elastic/config_models/defaults.py
elastic/datadog_checks/elastic/config_models/instance.py

https://github.com/DataDog/integrations-core/pull/8861

Sync config models

---

openstack_controller/manifest.json

Fix public title for Openstack Controller

---

eks_fargate/README.md

Document the logs configuration for EKS Fargate as mentioned here:
https://www.datadoghq.com/blog/eks-monitoring-datadog/#collect-and-analyze-eks-logs
https://www.datadoghq.com/blog/eks-monitoring-datadog/#collect-and-analyze-eks-logs
Document logs for intg

Document eks fargate logs

---

openstack/README.md
openstack/assets/configuration/spec.yaml
openstack/datadog_checks/openstack/data/conf.yaml.example
openstack/manifest.json

Openstack log support

---

openstack_controller/README.md
openstack_controller/assets/configuration/spec.yaml
openstack_controller/datadog_checks/openstack_controller/data/conf.yaml.example
openstack_controller/manifest.json

Adds support/instructions for enabling openstack logs.  Fixed an overindent in the config spec so the git diff looks odd.

Openstack controller log support

---

postgres/metadata.csv

Add db.count documentation

---

azure_active_directory/README.md
gke/README.md
go-metro/README.md
jboss_wildfly/README.md
kafka_consumer/README.md
kube_apiserver_metrics/README.md
openshift/README.md
pan_firewall/README.md
powerdns_recursor/README.md
teamcity/README.md
voltdb/README.md

Fixing readmes based off validation: https://github.com/DataDog/integrations-core/pull/9169

Replace nonascii characters

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/manifest.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/readmes.py
datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/schema.py

Ascii validation in README and manifest.json. As well as expanding ascii validation in metadata.csv

Include ascii validation in asset files

---

datadog_checks_dev/datadog_checks/dev/plugin/tox.py

Part of [Before Freeze checklist](https://datadoghq.dev/integrations-core/process/agent-release/pre-release/#before-freeze)
https://pypi.org/project/flake8/
https://pypi.org/project/flake8-bugbear/
Merge once #9176 is merged.

Upgrade flake8

---

ibm_db2/tests/conftest.py
ibm_db2/tests/docker/docker-compose.yaml

Fix ibm db2 e2e environment

---

haproxy/README.md
mongo/README.md

https://docs-staging.datadoghq.com/cswatt/okr-previews-3/integrations/haproxy
https://docs-staging.datadoghq.com/cswatt/okr-previews-3/integrations/mongodb

MongoDB and HAProxy - Containerized instructions

---

.flake8
datadog_checks_base/datadog_checks/base/checks/win/winpdh.py

Fix style rules according to new flake bugbear version

---

vault/README.md

add blog series links to hashicorp vault

---

openshift/README.md

Update log collection link

---

datadog_checks_dev/datadog_checks/dev/tooling/catalog_const.py

As per https://datadoghq.atlassian.net/browse/AI-1268

Add amazon eks exception

---

amazon_msk/datadog_checks/amazon_msk/amazon_msk.py
kong/datadog_checks/kong/kong.py
linkerd/datadog_checks/linkerd/linkerd.py

It's not immediately obvious to contributors which code to look at

Add code comment about legacy implementation

---

jmeter/assets/dashboards/JMeterOverview.json
jmeter/manifest.json

Staging dashboard (scoped to a timeframe with data): https://dd.datad0g.com/dashboard/dek-ckm-y37?from_ts=1618401995000&live=false&to_ts=1618402673046

Add JMeter dashboard

---

fluentd/README.md

Adds the logs `http-intake` shortcode to the FluentD README
Jira request

Flutend shortcode

---

.azure-pipelines/templates/test-all.yml
.azure-pipelines/templates/test-single-windows.yml
disk/tests/common.py
disk/tests/conftest.py
disk/tests/test_e2e.py
disk/tox.ini
pdh_check/tests/conftest.py
pdh_check/tests/test_e2e.py
pdh_check/tox.ini
windows_service/tests/conftest.py
windows_service/tests/test_windows_service.py
windows_service/tox.ini

More will be added from this subset: https://github.com/DataDog/integrations-core/blob/97021c770a5a9661596a0f19265d1828f54d9717/.azure-pipelines/changes.yml#L31

Add Windows E2E tests to CI

---

twemproxy/assets/dashboards/twemproxy_overview.json
twemproxy/manifest.json

Adds Twemproxy dashboard following the new suggested MSL layout. 
[Staging Link](https://dd.datad0g.com/dash/integration/30594/twemproxy---overview?from_ts=1617228269254&live=true&to_ts=1617228569254&tpl_var_scope=%2A&tv_mode=false)

Add Twemproxy dashboard

---

postgres/assets/configuration/spec.yaml
postgres/datadog_checks/postgres/config_models/instance.py
postgres/datadog_checks/postgres/data/conf.yaml.example

Fix config validation for `relations`

---

docs/developer/process/integration-release.md

Add releasers to dev doc

---

tomcat/assets/dashboards/overview.json

updating the layout of the tomcat-overview integration dashboard.
https://dd.datad0g.com/dash/integration/182/tomcat---overview?from_ts=1619458100806&live=true&to_ts=1619461700806
new dashboard layout beta

tomcat - overview msl

---

gitlab_runner/README.md

Some links were not being referenced.

Fix docs links for Gitlab Runner

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
mcache/requirements.in

Stay current https://github.com/jaysonsantos/python-binary-memcached/blob/master/CHANGELOG.rst

Upgrade `python-binary-memcached` dependency

---

kubernetes/assets/dashboards/kubernetes_pods.json

updating the kubernetes pods overview to use the new dashboard layout
https://dd.datad0g.com/dash/integration/30280/Kubernetes%20Pods%20Overview?from_ts=1619458205294&live=true&to_ts=1619461805294
new dashboard layout beta

k8 pods overview msl

---

mysql/datadog_checks/mysql/statements.py
mysql/tests/test_mysql.py

This builds on the merging of duplicate rows introduced in #9227 by changing the mysql integration to define a key function that is now based on the query signature computer from the normalized queries.
The motivation for this change was a [real world use-case with postgres](https://github.com/DataDog/integrations-core/pull/9231) but the same normalization and merge logic should apply for mysql.

Fix potential erroneous mysql statement metrics on duplicate queries

---

postgres/README.md

Correct the permission necessary to querying additional tables.
Encountered while testing.
FAQ to be updated as well: https://github.com/DataDog/documentation/pull/10457

Correct permission needed for custom_queries

---

apache/README.md

Add configuration block to include sourcegategory for http_web_access, and http_web_error.
Update documentation for a new dashboard release to include logs
Updating the apache dashboard

Update apache readme

---

sonarqube/README.md

This doc update is to add some clarification on what metrics will and will not be collected if JMX is not enabled, this is based on customer interaction and the need for some clarification.
A customer interaction
N/A

Sonarqube JMX verbiage update

---

nginx_ingress_controller/README.md

Adding containers tabs for the docs
Looks like it got missed.

[documentation] adding containers tabs

---

datadog_checks_base/datadog_checks/base/utils/db/core.py

The Agent already deduplicates tags:
https://github.com/DataDog/datadog-agent/blob/5fa67bb0678b45bb02303530df3bf6b0454ba3f1/pkg/aggregator/aggregator.go#L354
https://github.com/DataDog/datadog-agent/blob/5fa67bb0678b45bb02303530df3bf6b0454ba3f1/pkg/util/sort_uniq.go#L5-L7

Improve performance of using extra tags when executing a QueryManager

---

snmp/datadog_checks/snmp/parsing/metrics.py

Bump mypy https://github.com/DataDog/integrations-core/pull/9285

Fix mypy lint issue

---

ibm_mq/README.md

Adds a note to say that LD_LIBRARY_PATH must be existing. If not, it must be created.
Ticket 436025.

[IBM MQ] $LD_LIBRARY_PATH variable

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py

Noticed https://github.com/DataDog/integrations-core/pull/9294#issuecomment-832756433

Stop collecting empty coverage reports for non-Python checks

---

amazon_msk/manifest.json

Update tile name

---

mcache/assets/dashboards/memcached_screenboard.json

Update Memcached integration screenboard to multisize layout dashboard.
From reference dashboard here: https://dd.datad0g.com/dash/integration/30555/memcached---overview?from_ts=1620247388344&live=true&to_ts=1620250988344

Enable MSL for Memcached integration dashboard

---

pan_firewall/README.md

Small phrasing update pointed out by the translators.
More clear docs!

[documentation] clarification requested by FR translators

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/all_validations.py

Echo the name of the validation instead of the class. 
Noticed the log line looked a bit weird, details - https://github.com/DataDog/integrations-core/pull/9229#discussion_r628319780

Update validate all log line to use validation name

---

envoy/README.md

for new config option `collect_server_info` #9298 .

Add Envoy troubleshooting

---

datadog_checks_dev/datadog_checks/dev/plugin/tox.py

We need to skip some environments based on the OS
Also fixed the logic to actually apply per-environment

Allow skipping of E2E tests based on environment markers

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/testable.py

New version of https://pypi.org/project/click/, see error https://github.com/DataDog/integrations-core/pull/9336

Fix typing

---

datadog_checks_dev/setup.py
datadog_checks_dev/tests/tooling/configuration/consumers/model/test_object_typed_values.py

Better handling of complex `anyOf` and `additionalProperties`

Upgrade datamodel-code-generator

---

mapr/datadog_checks/mapr/mapr.py

self.auth_ticket is called here: https://github.com/DataDog/integrations-core/blob/af024a898f457bf4714edda3c4de255ebedd3a39/mapr/datadog_checks/mapr/mapr.py#L120

Fixup for an AttributeError

---

clickhouse/requirements.in
datadog_checks_base/datadog_checks/base/data/agent_requirements.in

Bug fixes & features like SNI support https://github.com/mymarilyn/clickhouse-driver/blob/master/CHANGELOG.md

Upgrade ClickHouse dependencies

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in

Update pycryptodome to 3.10.1

---

datadog_checks_dev/datadog_checks/dev/tooling/config.py
datadog_checks_dev/setup.py

Lack of maintenance https://github.com/ActiveState/appdirs/issues/79
Perf boost https://github.com/platformdirs/platformdirs/pull/1

Replace CLI dependency `appdirs` with `platformdirs`

---

datadog_checks_dev/datadog_checks/dev/tooling/specs/configuration/consumers/model.py
datadog_checks_dev/tests/tooling/configuration/consumers/model/test_duplicate_hidden.py

https://github.com/DataDog/integrations-core/pull/8985

Support hidden duplicate options from templates

---

spark/README.md

Fixes malformed links in Spark integration Readme
Report in #documentation channel
docs only change

Fix links in Spark Readme

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
snmp/requirements.in

Update pycryptodomex to 3.10.1

---

jmeter/README.md

Adds a link in the JMeter integration readme to the blog post about monitoring JMeter test results
documentation on-call tasks

Add link to JMeter blog post

---

voltdb/tests/fixtures/generate_data.py

Some mypy error on a test file.

Fix volt style in CI

---

apache/README.md

Clarifies that the log paths provided in the code block are meant to be replaced/customized
DOCS-2042
docs-only change

DOCS-2042 clarify path details

---

mongo/README.md

adds a double quote where it was missing
typo

DOCS-2017 - typo fix

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py

Need to run commands after the check and deps have been updated, see https://github.com/DataDog/integrations-core/pull/9398

Support running post-install commands for E2E

---

.azure-pipelines/all_master.yml

Fix port binding for the agent container on CI
Introduced in #9387

Fix agent port binding

---

.azure-pipelines/templates/run-validations.yml
ibm_mq/datadog_checks/ibm_mq/ibm_mq.py

Fix CI currently validating all models

Validate model for changing integration only

---

snmp/datadog_checks/snmp/data/conf.yaml.example

Motivation: https://github.com/DataDog/datadog-agent/pull/8140

Add collect device metadata config

---

.azure-pipelines/all_master.yml

Master CI was still not reporting to master, this change is fixing the docker port setting

Fix env variable setting

---

clickhouse/tests/common.py
clickhouse/tests/docker/docker-compose.yaml

https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=65209&view=logs&j=8e96ab15-72b0-549c-5ab8-f9fece94b017&t=ec9b40f1-a5eb-523c-a2d7-f48a83ba2f0c&l=755

change port start to 8128

---

airflow/README.md

Some metrics are not reported in the previous versions of Airflow, so their doc should be the source of truth about that.

Add link to airflow metrics

---

snmp/datadog_checks/snmp/data/conf.yaml.example

Reverts DataDog/integrations-core#9393

Revert "Add collect device metadata config"

---

sap_hana/datadog_checks/sap_hana/sap_hana.py
sap_hana/metadata.csv
sap_hana/tests/metrics.py
sap_hana/tests/test_unit.py

Reverts DataDog/integrations-core#9428
We're on a freeze

Revert "Resolve unexpected errors when statuses other than 'running' or 'idle' is received"

---

elastic/CHANGELOG.md

This PR should have been labeled `Added` and not `Changed`. We can't "unbump" the version back to 2.3.0, so we're just fixing the changelog.
QA #9354

Fix changelog entry

---

airflow/README.md

ZT: https://datadog.zendesk.com/agent/tickets/504371
Corrected the value of the instance_config

[doc] Corrected the value of the instance_config

---

datadog_checks_dev/datadog_checks/dev/tooling/specs/configuration/spec.py

Don't override example for `anyOf` spec options.
Allow example in #9473

Allow example for anyOf configuration option

---

oracle/README.md

Add troubleshooting about old java version

Troubleshoot old java version

---

postgres/README.md

Makes the documentation accurate as to what the annotations need to actually be for the check to be picked up and used.
I lost hours thinking I had something else configured incorrectly on my cluster/agent.
Tested on agent v7.27.0

Correct postgres kubernetes annotations

---

snmp/assets/dashboards/datacenter_overview.json

Change SNMP datacenter dashboard name to `Network Devices Monitoring`
JIRA: II-317
On staging

[SNMP] update snmp dahsboard name to Network Device Monitoring

---

kubernetes/assets/monitors/monitor_deployments_replicas.json
kubernetes/assets/monitors/monitor_node_unavailable.json
kubernetes/assets/monitors/monitor_pod_crashloopbackoff.json
kubernetes/assets/monitors/monitor_pod_imagepullbackoff.json
kubernetes/assets/monitors/monitor_pods_failed_state.json
kubernetes/assets/monitors/monitor_statefulset_replicas.json

Update recommended monitors to use officially-supported tags, and fix one metric typo
Better user experience

[kubernetes] Update recommended monitors

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/manifest.py
datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/validator.py

If metric_to_check is a metric listed in manifest.json, then do not fail manifest validation

Add metric_to_check validation in pricing

---

.codecov.yml

Remove files from Codecov pull request comments

---

consul/metadata.csv
consul/tests/test_integration.py

Fix consul tests

---

oracle/README.md

fixing links and other things on the oracle integration readme
flagged by transifex

editing oracle readme

---

cockroachdb/README.md
cockroachdb/assets/configuration/spec.yaml
cockroachdb/datadog_checks/cockroachdb/data/conf.yaml.example
cockroachdb/manifest.json

Updates Readme, adds spec and manifest to support logs for CockroachDB
Logs support for CockroachDB

Andrew hollingworth/add cockroachdb logs conf

---

pdh_check/README.md

Change PHD to PDH
Working with customer

check_pdh - fix typo

---

activemq/tests/common.py
activemq/tests/test_check.py
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/tests/metrics.py
hazelcast/tests/metrics.py
hivemq/tests/test_e2e.py
ignite/tests/common.py
ignite/tests/test_check.py
jboss_wildfly/tests/test_check.py

Fix JMX e2e tests

---

mysql/README.md

[documentation] updating backticks that are breaking the documentation build

---

couch/datadog_checks/couch/couch.py
couch/datadog_checks/couch/errors.py
couch/tests/test_couch.py
couch/tests/test_couchv1.py

Update signature
Refactored tests: Moved bad_config out of v1 because it's not v1 specific and split it into separate tests
Use agent exceptions when possible instead of custom defined or generic ones
Fix minor potential bugs

Use Agent 8 signature

---

docs/dev/python.md

updates link to conda install on macos
looks like conda moved their stuff

updating dead link in python dev doc

---

databricks/README.md
databricks/manifest.json

adds a link to the new blog post

adding link to blog to databricks docs

---

.gitlab-ci.yml

Print the git email if the slack user cannot be found.

---

oracle/README.md

This PR is a minor fix for the tab comment to correct docs rendering of links 
Slack conversation

docs fix link rendering in tab

---

docs/developer/guidelines/dashboards.md

Adds documentation about the internal tooling for generating temporary banners for MSL integration dashboards
Here's what the tool looks like:

📝 Add info about temporary MSL banner images to integration docs

---

docs/developer/process/integration-release.md

Better structure integration releasing documentation and also include clear steps for third party integrations.

Improve integration releasing documentation

---

snowflake/requirements.in

Add note in case of future updates

Make note of patch in omnibus

---

apache/datadog_checks/apache/apache.py

Do not use instance argument on check method

Agent 8 signature

---

LICENSE-3rdparty.csv
datadog_checks_base/datadog_checks/base/data/agent_requirements.in
mongo/requirements.in
mongo/tox.ini

Bump pymongo to 3.8, add support for Mongo 4.2
MongoDB compatibility https://docs.mongodb.com/drivers/pymongo/#compatibility

Bump pymongo to 3.8

---

coredns/README.md
mysql/README.md
nginx/README.md

Adds Docker, Kubernetes, and ECS instructions for the NGINX, MySQL, and CoreDNS integrations.
https://docs-staging.datadoghq.com/cswatt/okr-previews/integrations/nginx/?tab=docker
https://docs-staging.datadoghq.com/cswatt/okr-previews/integrations/mysql/?tab=docker
https://docs-staging.datadoghq.com/cswatt/okr-previews/integrations/coredns/?tab=docker

NGINX, MySQL, CoreDNS - Docker, Kubernetes, ECS instructions

---

datadog_checks_base/tests/test_db_util.py

fix code style in `test_db_util`

---

win32_event_log/README.md
win32_event_log/assets/configuration/spec.yaml
win32_event_log/datadog_checks/win32_event_log/data/conf.yaml.example

[docs 1684] redoing win32 pr

---

docs/developer/.snippets/links.txt
docs/developer/testing.md

Add ddtrace to dev doc

---

vsphere/README.md

FAQ doc about vsphere duplicated hosts: https://docs.datadoghq.com/integrations/faq/troubleshooting-duplicated-hosts-with-vsphere/

Add troubleshooting link for duplicated hosts

---

tls/README.md

Adds a note about `tls_verify:true` to the containerized TLS docs
Jira request

Certs note for TLS docs

---

ecs_fargate/README.md

removing extra space in ecs fargate

---

openldap/README.md

Fixes the stay # that breaks the tabs in the docs - https://docs.datadoghq.com/integrations/openldap/?tab=host#configure-the-openldap-integration

[documentation] fixing the stray #

---

nginx/README.md

Fixes broken markup in Nginx readme
Customer report, via #documentation channel

Fix NGINX readme tab markup

---

docs/dev/README.md
docs/dev/check_references.md
docs/dev/legacy.md
docs/dev/new_check_howto.md
docs/dev/python.md

Lint headings for Developer docs to follow [documentation contributing guidelines](https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#headers)
Hack day project
N/A

DOCS-1636 Lint headings for Developer docs

---

etcd/datadog_checks/etcd/etcd.py

Do not use instance argument on check method
Use base exceptions

etcd signature

---

.azure-pipelines/templates/test-single-linux.yml
.azure-pipelines/templates/test-single-windows.yml

Enable tag check for all repos

Enable tags check for all repos

---

amazon_msk/datadog_checks/amazon_msk/amazon_msk.py
kong/datadog_checks/kong/kong.py
linkerd/datadog_checks/linkerd/linkerd.py

I'm not sure if it's best to raise an ConfigError or log a warning in these cases but we need to communicate something

Raise exception if attempting to use new style openmetrics with py2

---

elastic/datadog_checks/elastic/elastic.py

Fixed a small issue in which a type error was causing an error log to keep getting logged inside the agent logs. 
Escalation
n/a

Fix log line 

---

docs/developer/ddev/plugins.md

Document mock_http_response fixture

---

clickhouse/setup.py
mysql/setup.py
oracle/setup.py
snowflake/setup.py
supervisord/setup.py

Fix nightly base package build
#9340 introduced a config_renamed deprecation log

Bump base package dependency

---

journald/README.md

Fixes tab formatting, which fixes links formatting
#documentation channel report
Docs site only change

JournalD readme: Fix tabs to fix links

---

btrfs/README.md

- Remove confusing sentence from Btrfs docs
- Word / formatting cleanup
Jira request from support
N/A

DOCS-2212 Btrfs docs update

---

mesos_slave/assets/configuration/spec.yaml
mesos_slave/datadog_checks/mesos_slave/data/conf.yaml.example

Small followup improvement for https://github.com/DataDog/integrations-core/pull/9477

Improve cluster_name config option description

---

cacti/assets/configuration/spec.yaml
cacti/datadog_checks/cacti/data/conf.yaml.example

Noticed when QA'ing https://github.com/DataDog/integrations-core/pull/9519

Fix example config

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/ci.py

Add support for the marketplace repo to the `ddev validate ci` command. 
Provide the same validation experience for that repository.

Add marketplace section to CI validation

---

amazon_msk/assets/configuration/spec.yaml
amazon_msk/datadog_checks/amazon_msk/data/conf.yaml.example

Found while QA-ing https://github.com/DataDog/integrations-core/pull/9613/files

Describe py3 requirement of use_openmetrics option

---

datadog_checks_dev/setup.py

https://virtualenv.pypa.io/en/latest/changelog.html#v20-5-0-2021-07-13
https://github.com/pypa/virtualenv/pull/2142 to mirror https://github.com/DataDog/integrations-core/pull/9356

Upgrade `virtualenv`

---

.azure-pipelines/changes.yml
.azure-pipelines/templates/run-validations.yml
.azure-pipelines/templates/test-all.yml
.azure-pipelines/templates/test-single-linux.yml
.azure-pipelines/templates/test-single-windows.yml
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/dep.py
datadog_checks_dev/datadog_checks/dev/tooling/dependencies.py
hdfs_datanode/datadog_checks/hdfs_datanode/hdfs_datanode.py

Run the ddev validations on changed check only when it makes sense.
`validate_changed` can have different values:
* `changed`: only checks having files different from master
* Empty or `all` (**previous behaviour**): all the checks
Example run:
* all pr: https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=69769&view=results
* changes only with an hdfs_datanode change: https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=69768&view=results
`parameters.check` is used to list checks https://github.com/DataDog/integrations-core/blob/master/.azure-pipelines/changes.yml#L32

Validate changed check in ci

---

postgres/datadog_checks/postgres/statements.py
postgres/tests/test_statements.py

This fixes the wrongly reported error when pg_stat_statement has not been created. Prior to this PR, the result would be:
```
2021-07-19 17:04:30 UTC | CORE | WARN | (pkg/collector/python/datadog_agent.go:124 in LogMessage) | postgres:1fb656b373c1a317 | (statements.py:131) | Statement-level metrics are unavailable: relation "pg_stat_statements" does not exist
LINE 3:   FROM pg_stat_statements as pg_stat_statements
^
2021-07-19 17:04:30 UTC | CORE | WARN | (pkg/collector/python/datadog_agent.go:124 in LogMessage) | postgres:1fb656b373c1a317 | (statements.py:200) | Unable to collect statement metrics because required fields are unavailable: calls, rows, query
```
And the metric error tag would be also wrong:
```
error:database-missing_pg_stat_statements_required_columns
```
With the fix, …

Fix wrong errors related to pg_stat_statements setup

---

.azure-pipelines/scripts/cilium/linux/50_increase_docker_memory.sh

Fix cilium CI

---

oom_kill/README.md
tcp_queue_length/README.md

Update supported operating systems for ebpf-based checks
Clearer information

Update notes in ebpf-based checks

---

glusterfs/README.md

Fixes links
Report in documentation slack channel

remove extraneous space

---

consul/README.md

Updates the Consul readme so that the docs match the [config documentation](https://github.com/DataDog/integrations-core/blob/master/consul/datadog_checks/consul/data/conf.yaml.example#L46)
Testing the consul integration

Update consul docs

---

.azure-pipelines/templates/test-single-windows.yml
disk/tox.ini
dns_check/tox.ini
pdh_check/tox.ini
tcp_check/tox.ini
windows_service/tox.ini

Support Windows E2E testing in CI for Python 2

---

oracle/README.md

fix oracle readme

---

postgres/datadog_checks/postgres/relationsmanager.py
postgres/metadata.csv
postgres/tests/test_relations.py

Adds two new relation metrics from `pg_stat_user_tables`

Add new relation metrics

---

.azure-pipelines/changes.yml
.azure-pipelines/templates/run-validations.yml

Enable ispr for .azure-pipelines/changes.yml
We want to have `--require-base-check-version` for integration PR builds:
https://github.com/DataDog/integrations-core/blob/master/.azure-pipelines/templates/run-validations.yml#L49-L58

Enable ispr for changes.yml and remove ispr for run-validations.yml

---

kube_apiserver_metrics/assets/dashboards/overview.json
kube_apiserver_metrics/manifest.json

This PR adds a new dashboard for the Kubernetes API server integration.

Add dashboard for Kubernetes API server

---

vsphere/assets/configuration/spec.yaml
vsphere/datadog_checks/vsphere/config_models/defaults.py
vsphere/datadog_checks/vsphere/config_models/validators.py
vsphere/datadog_checks/vsphere/data/conf.yaml.example

https://github.com/DataDog/integrations-core/pull/9739

Fix config validation

---

oracle/assets/service_checks.json

If there is an issue running a query (core or custom), the service checks is actually CRITICAL. https://github.com/DataDog/integrations-core/blob/b43d9a9c217bd821aff738c53eee335d0197f3d3/oracle/datadog_checks/oracle/oracle.py#L105-L112
Adding a card in the backlog to split this service check into `can_connect` and `can_query`

Update service checks doc

---

couch/tests/test_couchv2.py

Missed assertions on https://github.com/DataDog/integrations-core/pull/9745

Fix couch flake

---

eks_fargate/manifest.json

Removed by mistake by #7075
eks_fargate integration is not shipped.

Fix supported_os for eks_fargate check

---

eks_fargate/manifest.json

[7.30][backport] Fix supported_os for eks_fargate check (#9801)

---

oracle/datadog_checks/oracle/oracle.py

Close the connection after a query failure instead of leaving it pending and opening a new one.
Support case

Explicitly close connection after query error

---

iis/datadog_checks/iis/iis.py
iis/tests/test_iis.py

Fall back to default counter submission if it's an unknown IIS counter
Support

Submit unknown iis counters

---

datadog_cluster_agent/setup.py

This integration needs `labels_to_match` update in #7769
Nightly base CI broken

Bump base package

---

mapr/tests/README.md
mapr/tests/test_unit.py

We were not checking the monotonic type, fixed in  https://github.com/DataDog/integrations-core/pull/9825

Add documentation and fix monotonic check

---

datadog_checks_base/datadog_checks/base/stubs/aggregator.py

Depends on:
* https://github.com/DataDog/integrations-core/pull/9824

Check monotonic type when asserting histograms

---

gke/manifest.json

make gke doc public

---

sonarqube/assets/configuration/spec.yaml
sonarqube/datadog_checks/sonarqube/data/conf.yaml.example

Multiple instances in config example

---

sqlserver/datadog_checks/sqlserver/metrics.py

This way we can see what the actual data was

Capture value error

---

datadog_checks_dev/datadog_checks/dev/tooling/trello.py

Update GitHub `agent-network` team name

---

process/README.md

This PR updates the conf.yaml.example because the docs are outdated
Clarification

Update config example in docs

---

docs/developer/process/agent-release/pre-release.md

Adds docs on how to automatically update dependencies 
https://github.com/DataDog/integrations-core/pull/9811

Add dependency update process to release docs

---

snmp/datadog_checks/snmp/data/profiles/_generic-if.yaml
snmp/tests/metrics.py
snmp/tests/test_check.py
snmp/tests/test_e2e_agent_ad.py
snmp/tests/test_e2e_core_vs_python.py
snmp/tests/test_profiles.py

Add ifNumber to _generic-if.yaml
Useful metric to count # of interfaces

Add `ifNumber` to `_generic-if.yaml`

---

eks_fargate/README.md

[DOCS 2188] - Fix fargate readme link

---

windows_service/README.md

- Remove example configuration in favor of pointing to the `conf.yaml` file (source of the truth).
- Remove examples that may not exist on systems
- Wording cleanup
N/A

DOCS-2266 Windows Service

---

postgres/metadata.csv

* Update metadata for DBM query metrics to remove the Alpha language
* Change wording from "statements" to "queries"

update metric metadata for DBM query metrics

---

go-metro/assets/configuration/spec.yaml
go-metro/datadog_checks/go-metro/data/conf.yaml.example
haproxy/assets/configuration/spec.yaml
haproxy/datadog_checks/haproxy/data/conf.yaml.example
ibm_db2/assets/configuration/spec.yaml
ibm_db2/datadog_checks/ibm_db2/data/conf.yaml.example
kubernetes_state/datadog_checks/kubernetes_state/data/auto_conf.yaml
kubernetes_state/datadog_checks/kubernetes_state/data/conf.yaml.example
process/assets/configuration/spec.yaml
process/datadog_checks/process/data/conf.yaml.example
rabbitmq/assets/configuration/spec.yaml
rabbitmq/datadog_checks/rabbitmq/data/conf.yaml.example

Fix typos in configuration files caught by codespell
#9902

Fix typos in config files

---

cilium/assets/configuration/spec.yaml
cilium/datadog_checks/cilium/data/auto_conf.yaml

Re-reverting change made in https://github.com/DataDog/integrations-core/pull/9683.

Re-revert cilium AD change

---

mysql/README.md
postgres/README.md

Updates the README for Postgres and MySQL to link to DBM.

Update Postgres / MySQL Readmes to link to DBM

---

mongo/datadog_checks/mongo/collectors/custom_queries.py
mongo/tests/common.py
mongo/tests/conftest.py
mongo/tests/test_mongo.py

Support collection-agnostic aggregations for custom queries

---

ibm_mq/assets/configuration/spec.yaml
ibm_mq/datadog_checks/ibm_mq/data/conf.yaml.example

Fix typos found by validation

---

datadog_checks_dev/datadog_checks/dev/tooling/trello.py

Exclude trello cards with `cluster-agent` labels when computing release board status
More accurate stats

Ignore `cluster-agent` trello cards

---

envoy/README.md
istio/README.md

Users monitoring Istio may also want to monitor Envoy, and vice versa. This PR updates the admin port info for Envoy in Istio and links the Envoy docs in the Istio readme.
Users may not be aware there exists dedicated Istio and Envoy integrations.

Update istio and envoy docs with related monitoring

---

http_check/README.md
tcp_check/README.md

Add a note to use Network Monitors in HTTP Check and TCP Check pages.
DOCS-2355

Add a note to HTTP Check and TCP Check pages

---

eks_fargate/README.md

Updated [19] link from /agent/cluster_agent/event_collection/ to tracing/#send-traces-to-datadog.
DOCS-2391

Update Tracing link in Amazon EKS on AWS Fargate

---

ibm_db2/datadog_checks/ibm_db2/ibm_db2.py
ibm_db2/tests/README.md
ibm_db2/tests/test_unit.py

Add more tests for https://github.com/DataDog/integrations-core/pull/9797

Add more unit tests

---

confluent_platform/datadog_checks/confluent_platform/data/metrics.yaml

fix comments with explaining of metric
to make the world better

Fix typo in comments

---

oracle/tests/test_oracle.py

Adds a test for invalid server config
QA for https://github.com/DataDog/integrations-core/pull/9712

Add test for invalid server

---

directory/assets/configuration/spec.yaml
directory/datadog_checks/directory/config.py
directory/datadog_checks/directory/config_models/defaults.py
directory/datadog_checks/directory/config_models/instance.py
directory/datadog_checks/directory/data/conf.yaml.example
directory/datadog_checks/directory/directory.py
directory/tests/test_directory.py

Internal request to allow only the submission of desired samples

Add option to control the submission of histogram metrics

---

datadog_checks_dev/datadog_checks/dev/tooling/constants.py

Update list of beta packages

---

openstack_controller/tests/conftest.py
openstack_controller/tests/test_openstack.py

Add test for no leaked password on logs
Tests https://github.com/DataDog/integrations-core/pull/9637/s

Add test for no leaked password

---

ibm_mq/tests/README.md

Update `ibm_mq` testing docs
the previously documented version does not exist

Update testing docs

---

proxysql/tests/common.py
proxysql/tests/test_unit.py

Add unit tests to verify service check mapping

---

databricks/README.md

Update install script link to current one.
Avoid people using master version.

Update install script link

---

datadog_checks_base/tests/base/utils/test_http.py
datadog_checks_dev/setup.py

Rerun test on PY2

---

datadog_checks_dev/datadog_checks/dev/tooling/utils.py

New check does not have one https://github.com/DataDog/integrations-core/pull/10040

Don't read from nonexistent manifest files

---

postgres/tests/test_statements.py

Skips a flaky test while the team attempts to fix the root cause.

Skip flaky Postgres test for samples cache

---

mongo/tests/test_mongo.py

Make dd.mongodb.custom.queries_slower_than_60sec.secs_running optional

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/test.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py
datadog_checks_dev/datadog_checks/dev/tooling/testing.py

https://github.com/DataDog/integrations-core/pull/9938

Add support for testing new versions of products

---

.azure-pipelines/latest_metrics.yml
.azure-pipelines/templates/run-tests.yml
.azure-pipelines/templates/test-all-checks.yml
.azure-pipelines/templates/test-all.yml
airflow/tests/compose/latest/.gitignore
airflow/tests/compose/latest/Dockerfile
airflow/tests/compose/latest/docker-compose.yaml
airflow/tests/compose/latest/init.sh
airflow/tox.ini
clickhouse/tox.ini
docs/developer/.scripts/33_render_status.py

Begin tracking compatibility with new versions of products
- Depends on https://github.com/DataDog/integrations-core/pull/9945
- Part 1 of 2, next PR will report errors externally

Change weekly CI job to also verify support for new product versions

---

redisdb/tox.ini

https://github.com/DataDog/integrations-core/pull/9938

Add support for `latest` builds

---

consul/README.md

Add text into Further Reading section and a new guide link (not published yet) to the Consul page.
DOCS-2417

DOCS-2417 Consul Further Reading Section Edits

---

.azure-pipelines/latest.yml
.azure-pipelines/templates/run-tests.yml
.azure-pipelines/templates/test-all-checks.yml
.azure-pipelines/templates/test-all.yml
.azure-pipelines/templates/test-single-linux.yml
.azure-pipelines/templates/test-single-windows.yml

It doesn't just scrape for metrics anymore, https://github.com/DataDog/integrations-core/pull/9945#discussion_r701402688

Rename weekly pipeline to `latest`

---

.azure-pipelines/templates/test-all-checks.yml
.azure-pipelines/templates/test-all.yml

Correctly pass all of these https://github.com/DataDog/integrations-core/blob/cdb866c7012e32f005621f087331088b61fca687/.azure-pipelines/latest.yml#L21-L23

Properly allow the skipping of regular tests and benchmarks

---

.azure-pipelines/latest.yml
.azure-pipelines/templates/run-tests.yml

Receive notifications for errors

Add CI App support to `latest` pipeline

---

avi_vantage/manifest.json

Agent 7.31.0 was just released

Make avi_vantage public

---

elastic/datadog_checks/elastic/elastic.py
elastic/tests/common.py
elastic/tests/compose/docker-compose.yaml
elastic/tests/conftest.py
elastic/tests/test_elastic.py
elastic/tox.ini

Support opensearch

---

vsphere/README.md

Update vSphere README to include mention of `collect_per_instance_filters`.
A few support tickets that could've been easily solved using `collect_per_instance_filters`

Update vSphere README

---

eks_fargate/README.md
mongo/README.md
mysql/README.md
nginx/README.md

fixes a bunch of links in readmes

DOCS-2446 fixin borked hashes

---

.github/workflows/validations.yaml
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/agent_reqs.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/eula.py

Add annotations to eula and agent-reqs.
Include agent-reqs in integrations-core repo workflow

Annotate EULA and agent requirements validation

---

ibm_i/datadog_checks/ibm_i/config_models/defaults.py
ibm_i/datadog_checks/ibm_i/config_models/instance.py

Fix master tests, broken because of a race condition between two PRs.
Have CI pass on master
I just ran `ddev validate models -s ibm_i`

Run `ddev validate models -s` on ibm_i

---

.github/workflows/validations.yaml
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/jmx_metrics.py

Annotate jmx metric validation

Annotate jmx metric validation

---

cisco_aci/datadog_checks/cisco_aci/tenant.py

Add more debug lines for `cisco` integration
Support ticket

Add debug lines for support

---

process/datadog_checks/process/process.py

Change back two log lines to their original log level.
Unintended change added in #10109

Undo unintended changes added in #10109

---

.github/workflows/validations.yaml
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/readmes.py
exchange_server/README.md

Add annotations to readme validation

Annotate readme validations

---

vsphere/README.md
vsphere/assets/configuration/spec.yaml
vsphere/datadog_checks/vsphere/data/conf.yaml.example

Make troubleshooting steps more explicit

---

.github/workflows/validations.yaml
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/package.py
exchange_server/setup.py

Add annotation to package validation

Annotate package validation

---

harbor/tox.ini

Harbor 2.3.2 environment is very flaky, let's remove it while trying to fix it

Remove harbor-2.3 environment

---

requirements-agent-release.txt

Add new releases to agent-req
Resolves some of the warnings from `ddev validate agent-reqs`

Add new release to agent-req

---

snmp/assets/configuration/spec.yaml
snmp/datadog_checks/snmp/data/conf.yaml.example

Add snmp corecheck integration configs
https://github.com/DataDog/datadog-agent/pull/8996
Related PRs:
- https://github.com/DataDog/datadog-agent/pull/8996
- https://github.com/DataDog/datadog-agent/pull/8971
- https://github.com/DataDog/integrations-core/pull/10079

Add snmp corecheck autodiscovery integration configs

---

snmp/tests/common.py
snmp/tests/test_e2e_core.py
snmp/tests/test_e2e_core_vs_python.py

Add SNMP Corecheck Autodiscovery e2e tests
https://github.com/DataDog/datadog-agent/pull/8996

Add SNMP Corecheck Autodiscovery e2e tests

---

jboss_wildfly/tests/test_check.py

Update wildfly tests

---

datadog_checks_base/datadog_checks/base/ddyaml.py

This reverts commit e01823a1b996a68ece368b7b666f4f82c2cee770.
The commit increased memory usage of the agent, reverting for now

Revert "Allow non-default yaml loader and dumper (#10032)"

---

airflow/tests/compose/v2/Dockerfile
airflow/tests/conftest.py

Upgrade the test environment from 2.0.0 to 2.14
May fix airflow flakiness

Upgrade airflow test environment

---

elastic/tests/compose/docker-compose.yaml

Opensearch container sometimes crashes at start

Restart container on failures

---

coredns/README.md
supervisord/README.md

Fix doc links
Integration tile sync failing due to missing link references
N/A

Fix doc links

---

elastic/tests/compose/docker-compose.yaml
elastic/tests/conftest.py

Opensearch env is flaky on master, can't reproduce it locally.
With this change, CI was green on 3 different runs

Disable security plugin for opensearch env

---

citrix_hypervisor/datadog_checks/citrix_hypervisor/config_models/defaults.py
citrix_hypervisor/datadog_checks/citrix_hypervisor/config_models/instance.py
citrix_hypervisor/datadog_checks/citrix_hypervisor/data/conf.yaml.example

Sync config from two recent changes https://github.com/DataDog/integrations-core/pull/10160 https://github.com/DataDog/integrations-core/pull/9815

Sync config

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/models.py

Updates validate models message to instruct the user to sync only the check with an error. Running the command without a check creates all models

Update validate models message

---

ecs_fargate/datadog_checks/ecs_fargate/ecs_fargate.py

Add debug log lines for CPU calculation in ECS Fargate, to surface cause of unexpected values 
Ongoing investigation

Add debug log lines for cpu calculation

---

nginx/tests/common.py
nginx/tests/test_nginx.py
nginx/tests/utils.py
nginx/tox.ini

This pr adds the latest nginx to test

Add latest nginx test env

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/README.md

Updates JMX integration template to have more descriptive wording and include another link.

Update JMX integration template

---

haproxy/tests/common.py
haproxy/tests/conftest.py
haproxy/tox.ini

add haproxy:latest test version

add haproxy:latest test version

---

citrix_hypervisor/README.md
citrix_hypervisor/assets/configuration/spec.yaml
citrix_hypervisor/datadog_checks/citrix_hypervisor/data/conf.yaml.example
citrix_hypervisor/manifest.json

Logs parser is already merged and deploy, adding the documentation about the logs collection

Add logs documentation

---

ibm_i/assets/dashboards/ibm_i_overview.json
ibm_i/manifest.json

Add default dashboard for IBM i.
Release of the IBM i integration.

Add default dashboard for IBM i

---

ecs_fargate/datadog_checks/ecs_fargate/ecs_fargate.py

Request from support to include these DEBUG log lines more frequently to ease investigations (follow up to https://github.com/DataDog/integrations-core/pull/10197)

Update condition for displaying debug log

---

cisco_aci/tests/conftest.py
cisco_aci/tests/test_cisco.py
cisco_aci/tox.ini

Add barebones e2e test for cisco_aci

---

docs/developer/process/agent-release/pre-release.md

Document the new agent pipeline use during agent release and QA introduced in #10204

Add agent testing instruction for qa

---

docs/developer/process/integration-release.md

This PR updates the integration release doc with the current devs.
- Remove invalid keys
- Update to Julia's new key
- Add new devs' keys

Update dev keys documentation

---

process/README.md

Previous dead link -> https://docs.datadoghq.com/monitoring/#process
New link -> https://docs.datadoghq.com/monitors/create/types/process_check/?tab=checkalert
Updates dead link 
Fix user navigation issue

Updating Process Check monitors link

---

openmetrics/README.md

Documents default metric limit. 
Support

Document default metric limit

---

requirements-agent-release.txt

Add citrix_hypervisor to agent requirements

---

datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/base.py
datadog_checks_dev/datadog_checks/dev/plugin/tox.py

Update style dependencies 
Release week prep and keeping dependencies up to date

Update style dependencies

---

rabbitmq/datadog_checks/rabbitmq/rabbitmq.py

1. Remove `InsecureRequestWarning` handling that already exists in the HTTP wrapper
2. Remove duplicate call to `/api/overview`

Minor refactor

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/manifest.py

Also, migrate any existing config spec locations from Manifest V1.

Minor update to manifest migrate command

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/readmes.py

Instead of checking the manifests support field, check the repo value directly in the README validation. 
This check doesn't work with the newer manifest version and instead really was checking which repo was being validated.

Update readme validation to check repo over support

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py
datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py
datadog_checks_dev/datadog_checks/dev/tooling/e2e/local.py

Allow setting DD_SITE in org config

---

.gitlab-ci.yml
.gitlab/validate-logs-intgs/validate_log_intgs.py

Fix gitlab job for log validation

Fix logs validation job

---

.github/workflows/validations.yaml
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/ci.py

Add annotations to ci validation

Add annotations for ci

---

sqlserver/setup.py

updates dd base check version to include this change https://github.com/DataDog/integrations-core/pull/10274

Bump sqlserver dd base check version

---

.azure-pipelines/scripts/sqlserver/windows/55_setup_sqlserver.bat

attempt to fix sqlserver int tests with startup script

---

linkerd/datadog_checks/linkerd/__about__.py
linkerd/tests/compose/Dockerfile

Pin tested version
A new version of linkerd was released https://linkerd.io/2021/09/30/announcing-linkerd-2.11/

Pin tested version

---

databricks/README.md
databricks/manifest.json
datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/common/validator.py

Log source should be `spark` as databricks integration is using Spark integration.
fix logs pipeline

Add databricks logs collection and fix init_script log source

---

pgbouncer/tests/compose/docker-compose-old.yml
pgbouncer/tests/compose/docker-compose.yml

Pin postgres version used in e2e
A new version of postgres was released: https://www.postgresql.org/docs/14/release-14.html. 
TODO: investigate compatibility later

Pin tested postgres version

---

.gitlab/validate-logs-intgs/validate_log_intgs.py
activemq_xml/manifest.json
aspdotnet/manifest.json
consul_connect/manifest.json
couchbase/assets/configuration/spec.yaml
couchbase/datadog_checks/couchbase/data/conf.yaml.example
couchbase/manifest.json
databricks/manifest.json
ecs_fargate/manifest.json
teamcity/manifest.json

Update the logs section and description to pass validation
databricks is done in #10297

Update logs sections

---

postgres/setup.py

Bumps the dd checks base version for postgres to include this change https://github.com/DataDog/integrations-core/pull/10223 
needed for this postgres integration PR https://github.com/DataDog/integrations-core/pull/9866

Bump datadog checks base version for postgres

---

couchbase/README.md

Fix logs validation CI
Add couchbase log section back that was removed in #6577
Following up #10289

Add missing couchbase log section

---

active_directory/README.md
activemq/README.md

Add site partials for documentation site
Log collection availability for US3
Related PR: https://github.com/DataDog/documentation/pull/11857

DOCS-2556 US3 site partials test

---

datadog_checks_base/datadog_checks/base/utils/db/core.py

Add warning when no query is configured

---

gitlab/assets/configuration/spec.yaml
gitlab/datadog_checks/gitlab/config_models/defaults.py
gitlab/datadog_checks/gitlab/config_models/instance.py
gitlab/datadog_checks/gitlab/data/conf.yaml.example

`gitlab_url` is not required in the check, making it required could break existing configurations
https://github.com/DataDog/integrations-core/blob/3e7f81b20a2c4d93afea43019ff92aa253bc3242/gitlab/datadog_checks/gitlab/gitlab.py#L47
https://github.com/DataDog/integrations-core/blob/3e7f81b20a2c4d93afea43019ff92aa253bc3242/gitlab/datadog_checks/gitlab/gitlab.py#L141-L144
QA #8918

Fix config example

---

openmetrics/README.md

Add troubleshooting suggestion

Add troubleshooting note on custom metrics

---

nginx/assets/dashboards/NGINX-Overview_dashboard.json

Updated Nginx dashboard
Staging: https://dd.datad0g.com/dash/integration/21/NGINX%20-%20Overview?from_ts=1635527442426&to_ts=1635531042426&live=true
Current:
Updated:

New dashboard for Nginx

---

nginx/assets/dashboards/NGINX-Overview_dashboard.json

Reverts DataDog/integrations-core#10522 since the dashboard type changed and causes issues in the backend.

Revert "New dashboard for Nginx"

---

prometheus/README.md
yarn/README.md

Yarn + Prometheus fix links
Can't sync the tiles due to KeyErrors
N/A

Yarn + Prometheus fix links

---

.azure-pipelines/templates/install-deps.yml
activemq/datadog_checks/__init__.py

Use https when installing a git repo as a package
https://github.blog/2021-09-01-improving-git-protocol-security-github/

Use https when installing codecov

---

datadog_cluster_agent/datadog_checks/datadog_cluster_agent/check.py
datadog_cluster_agent/metadata.csv
datadog_cluster_agent/tests/fixtures/metrics.txt
datadog_cluster_agent/tests/test_datadog_cluster_agent.py

Collect a metric for DatadogMetric external metrics.
To use in creating a dashboard for the DCA.

Collect a metric about valid and invalid DatadogMetrics

---

eks_fargate/README.md

Mention DD Forwarder in log collection docs, so that the section is complete.
Complete docs.
N/A

[eks_fargate] Mention DD Forwarder in log collection docs

---

win32_event_log/manifest.json

Add a log source for windows_event_log
Updated in https://github.com/DataDog/integrations-core/pull/9725

Add log source

---

.gitlab/validate-logs-intgs/validate_log_intgs.py

Removes the expected error for windows_event_log
It now collects logs, see https://github.com/DataDog/integrations-core/pull/9725

Remove windows_event_log expected error

---

zk/tests/README.md

Add ZK test README
Easier for future reference

Add ZK test README

---

hdfs_datanode/assets/dashboards/hdfs_datanode_dashboard.json
hdfs_datanode/manifest.json
hdfs_namenode/assets/dashboards/hdfs_namenode_dashboard.json
hdfs_namenode/manifest.json

Migrate HDFS dashboards to integrations-core

Migrate hdfs dashboards

---

activemq/README.md
aerospike/README.md
airflow/README.md
amazon_eks/README.md
ambari/README.md
apache/README.md
aspdotnet/README.md
azure_iot_edge/README.md
cacti/README.md
cassandra/README.md
ceph/README.md
cilium/README.md

DOCS-2530 Lint Integrations section (part 1)

---

prometheus/manifest.json

Add legacy note on prometheus tile

---

sqlserver/assets/configuration/spec.yaml
sqlserver/datadog_checks/sqlserver/data/conf.yaml.example

update DBM instructions for requesting beta access

---

prometheus/README.md

adds route manager to prometheus alertmanager docs
jira

[DOCS-2262] route information to alertmanager docs

---

docs/developer/process/agent-release/pre-release.md

Adds instructions on code freeze
New mergefreeze tooling https://www.mergefreeze.com/ for `integrations-core`.

Update Agent Release docs with  mergefreeze process

---

citrix_hypervisor/manifest.json

Make citrix_hypervisor public

---

sqlserver/datadog_checks/sqlserver/statements.py
sqlserver/tests/test_statements.py

Fixes DBM for SQL Server 2014 and earlier by querying only for those columns in `sys.dm_exec_query_stats` that actually exist on the table.
Support SQL Server 2014 and earlier.

handle missing DBM metrics columns on older SQL Server versions

---

sqlserver/assets/configuration/spec.yaml
sqlserver/datadog_checks/sqlserver/data/conf.yaml.example

This is a clarification on which check this param works based on a docs request.
Clarity!

Clarify `database_autodiscovery` config

---

docs/developer/process/integration-release.md

Updates the docs
Ran into this issue myself a few times. Documenting it for future occurrences.

Add yubikey troubleshooting to dev release doc

---

singlestore/manifest.json

Singlestore was released in 7.32.0 so it should be made public.

Make singlestore public

---

network/metadata.csv

Adds metadata for system.net.tcp.failed_retransmits.count and system.net.tcp.failed_retransmits
customer request

update metadata.csv for system.net.tcp.failed_retransmits

---

hdfs_datanode/setup.py

Bump datadog_checks_base requirement to 15.7.0
Address missing attribute error

Bump minimum base requirement to 15.7.0

---

disk/README.md

This PR updates the Disk Check documentation with the latest information for Windows.
More accurate documentation of the Disk Check behaviour.

Update Disk Check documentation for Windows

---

ibm_was/metadata.csv

Fix memory units in description from `thread` to `kibibyte`
Support ticket

Fix memory units

---

datadog_checks_dev/datadog_checks/dev/tooling/annotations.py

Explicitly trying to import annotations causes circular import error.

Update annotations util with relative imports

---

kube_proxy/assets/configuration/spec.yaml
kube_proxy/datadog_checks/kube_proxy/data/conf.yaml.example
kube_proxy/manifest.json

Add kube_proxy config spec

---

kube_dns/assets/configuration/spec.yaml
kube_dns/datadog_checks/kube_dns/data/auto_conf.yaml
kube_dns/datadog_checks/kube_dns/data/conf.yaml.example
kube_dns/manifest.json

Add kube_dns config spec

---

kube_metrics_server/assets/configuration/spec.yaml
kube_metrics_server/datadog_checks/kube_metrics_server/data/conf.yaml.example
kube_metrics_server/manifest.json

Add kube_metrics_server config spec

Add kube_metrics_server config spec

---

.azure-pipelines/changes.yml
.azure-pipelines/templates/test-all-checks.yml
.codecov.yml
windows_performance_counters/CHANGELOG.md
windows_performance_counters/MANIFEST.in
windows_performance_counters/README.md
windows_performance_counters/assets/configuration/spec.yaml
windows_performance_counters/assets/service_checks.json
windows_performance_counters/datadog_checks/__init__.py
windows_performance_counters/datadog_checks/windows_performance_counters/__about__.py
windows_performance_counters/datadog_checks/windows_performance_counters/__init__.py
windows_performance_counters/datadog_checks/windows_performance_counters/check.py
windows_performance_counters/datadog_checks/windows_performance_counters/config_models/__init__.py
windows_performance_counters/datadog_checks/windows_performance_counters/config_models/defaults.py
windows_performance_counters/datadog_checks/windows_performance_counters/config_models/instance.py
windows_performance_counters/datadog_checks/windows_performance_counters/config_models/shared.py
windows_performance_counters/datadog_checks/windows_performance_counters/config_models/validators.py
windows_performance_counters/datadog_checks/windows_performance_counters/data/conf.yaml.example
windows_performance_counters/manifest.json
windows_performance_counters/metadata.csv
windows_performance_counters/requirements-dev.txt
windows_performance_counters/setup.py
windows_performance_counters/tests/__init__.py
windows_performance_counters/tests/common.py
windows_performance_counters/tests/conftest.py
windows_performance_counters/tests/test_e2e.py
windows_performance_counters/tests/test_integration.py
windows_performance_counters/tests/test_unit.py
windows_performance_counters/tests/test_windows_performance_counters.py
windows_performance_counters/tox.ini

Follow-up to https://github.com/DataDog/integrations-core/pull/10504

Add new integration for monitoring Windows performance counters

---

gearmand/assets/configuration/spec.yaml
gearmand/datadog_checks/gearmand/config_models/defaults.py
gearmand/datadog_checks/gearmand/data/conf.yaml.example
gearmand/tests/conftest.py
gearmand/tests/test_integration.py
gearmand/tests/test_integration_e2e.py

Updates the example server config to exactly match the implementation `localhost` -> `127.0.0.1` and also reformats tests to run check initializations during tests.
QA for https://github.com/DataDog/integrations-core/pull/8917

Update config example to match implementation and refactor tests

---

datadog_checks_base/datadog_checks/base/checks/windows/perf_counters/base.py
datadog_checks_base/datadog_checks/base/checks/windows/perf_counters/connection.py

The Agent uses the FQDN and that may cause issues

[PerfCountersBaseCheck] Fix default machine connection

---

dns_check/tests/test_integration.py

Use dd_run_check in test

---

couch/tests/test_couchv1.py
couch/tests/test_couchv2.py

Use `dd_check_run` in tests
QA #8901

Use dd_check_run in tests

---

etcd/tests/common.py
etcd/tests/test_e2e.py
etcd/tests/utils.py
etcd/tox.ini

Adds 3.5.1 to tested versions to test the remapped metrics as well as assert debugging metrics in tests
QA for https://github.com/DataDog/integrations-core/pull/10209

Test version 3.5.1

---

aerospike/tests/test_aerospike.py
aerospike/tests/test_unit.py

Use dd_run_check

---

cloud_foundry_api/tests/test_cloud_foundry_api.py

Use dd_run_check in tests

---

sqlserver/tests/common.py
sqlserver/tests/test_unit.py

Adds test for https://github.com/DataDog/integrations-core/pull/10257.
QA

Add test for proper handling of NoneType

---

nginx/datadog_checks/nginx/nginx.py
nginx/tests/common.py
nginx/tests/conftest.py
nginx/tests/test_unit.py

Read all config in init
Do not use instance in check
Some other minor refactors

Refactor nginx: Read all config in init

---

ecs_fargate/README.md

just adds a further reading link

add blog link to ecs fargate docs

---

requirements-agent-release.txt
sqlserver/CHANGELOG.md
sqlserver/datadog_checks/sqlserver/__about__.py

Port version and changelog updates from [7.33.0-rc.4](https://github.com/DataDog/integrations-core/pull/10724/files) to master.

Apply updates from 7.33.0-rc.4

---

.azure-pipelines/all_pr.yml
.azure-pipelines/changes.yml

Porting https://github.com/DataDog/integrations-extras/pull/1088 to core

Don't spin up agent on prs

---

elastic/tests/common.py
elastic/tox.ini

Upgrade opensearch image to use version `1.1.0` which is more stable and does not require https

Upgrade opensearch docker image

---

datadog_checks_dev/datadog_checks/dev/tooling/trello.py

Remote-config team was added to the QA board for agent release testing - proper fields and IDs were added to the trello class
Update to the changes in the agent release process.

Remote-config team added to QA cards

---

cilium/tests/test_cilium.py

QA for https://github.com/DataDog/integrations-core/pull/8893

Use dd_run_check for Cilium

---

cockroachdb/tests/test_cockroachdb.py
cockroachdb/tests/test_e2e.py

QA for https://github.com/DataDog/integrations-core/pull/8897

Use dd_run_check for cockroachdb and reformat code

---

pgbouncer/tests/test_pgbouncer_integration_e2e.py
pgbouncer/tests/test_pgbouncer_unit.py

QA for https://github.com/DataDog/integrations-core/pull/8968

Use dd_run_check for pgbouncer

---

ecs_fargate/README.md

Adds link to new blog post about Windows support

Fargate for Windows - Add blog link to integration readme

---

datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/transform.py
datadog_checks_base/tests/base/checks/openmetrics/test_interface.py

Allows transforming metrics using metric patterns instead of exact metric names.

Support custom transformer

---

postgres/CHANGELOG.md
postgres/datadog_checks/postgres/__about__.py
requirements-agent-release.txt

Applies release updates from https://github.com/DataDog/integrations-core/pull/10761.

Apply release updates from 7.33.0-rc.5

---

.azure-pipelines/templates/install-deps.yml

Let tests run if pip cache fails

Continue on error of pip cache

---

docs/developer/process/agent-release/post-release.md

Make the process of releasing an integration off of the release branch more clear

Update post-release docs

---

postgres/datadog_checks/postgres/util.py

Fixes a typo in the postgres version comment in `util.py`
Removes confusion when working on this part of the code.
No functional changes, just fixing the comment.

Fix postgres version comment in util.py

---

iis/datadog_checks/iis/iis.py
iis/datadog_checks/iis/metrics.py
iis/metadata.csv
iis/tests/common.py
iis/tests/test_unit.py

Add missing metric for the number of PATCH requests per second

---

redisdb/README.md

We actually already support Redis Cloud https://redis.com/redis-enterprise-cloud/overview/
Adding docs to say it explicitly and also precisions to ACL rule needed

Update readme for redis cloud

---

snmp/datadog_checks/snmp/data/profiles/f5-big-ip.yaml
snmp/tests/test_e2e_core_metadata.py

Add profile metadata for f5

---

openstack/tests/conftest.py
openstack/tests/test_e2e.py
openstack/tox.ini

Add minimal e2e test to openstack ; testing that the integration runs and submit critical service checks
Add e2e everywhere

Add minimal e2e

---

cilium/README.md
citrix_hypervisor/README.md
clickhouse/README.md
cloud_foundry_api/README.md
cockroachdb/README.md
consul/README.md
consul_connect/README.md
container/README.md

DOCS-2530 Lint Integrations section (part 2)

---

singlestore/assets/dashboards/overview.json
singlestore/manifest.json

Adds a default dashboard for singlestore

Add singlestore dashboard

---

containerd/README.md
coredns/README.md
couch/README.md
couchbase/README.md
cri/README.md
databricks/README.md
dns_check/README.md
docker_daemon/README.md
ecs_fargate/README.md

DOCS-2530 Lint Integrations section (part 3)

---

eks_fargate/README.md
elastic/README.md
envoy/README.md
etcd/README.md
exchange_server/README.md
flink/README.md
fluentd/README.md
gearmand/README.md
gitlab/README.md
gitlab_runner/README.md
gke/README.md

DOCS-2530 Lint Integrations section (part 4)

---

istio/README.md

From [here](https://github.com/DataDog/integrations-core/blob/503c0a28afb3838c9ce49d2af5bf192ea1a4f7a4/istio/datadog_checks/istio/data/conf.yaml.example#L52), these are supposed to be keys in a dict, not items in an array

Fix README for Istio

---

snmp/assets/configuration/spec.yaml
snmp/datadog_checks/snmp/data/conf.yaml.example

Add use_device_id_as_hostname config

Add use_device_id_as_hostname config

---

elastic/datadog_checks/elastic/elastic.py

Customer request; not all metrics are always expected

Lower log level for expected condition

---

sqlserver/datadog_checks/sqlserver/statements.py

Follow-up to https://github.com/DataDog/integrations-core/pull/10763
Move the filter to the common table expression to avoid temporarily materializing a large result set only to filter out most of it in the following query.
Also add a `TOP {}` safety limit to the query, defaulting to 10k rows to make sure the default behavior is safe and will not cause excessively slow queries in case the database has a large number of plans in the plan cache.
Improve query performance for instances that have a large plan cache (100k+ entries).

improve sqlserver agent query performance for DBM metrics query

---

datadog_checks_base/datadog_checks/base/checks/base.py
datadog_checks_base/datadog_checks/base/utils/agent/common.py
datadog_checks_base/datadog_checks/base/utils/agent/memory.py
datadog_checks_base/datadog_checks/base/utils/limiter.py
datadog_checks_base/tests/base/checks/test_agent_check.py

Add debug metrics for metric context limits

---

agent_metrics/README.md

Fix link reference
Page isn't populating on the documentation site
N/A

DOCS-2915 Fix link reference

---

glusterfs/README.md
go-metro/README.md
go_expvar/README.md
gunicorn/README.md
haproxy/README.md
harbor/README.md
hazelcast/README.md
hive/README.md
hivemq/README.md
http_check/README.md
hudi/README.md
ibm_db2/README.md
ibm_mq/README.md
ibm_was/README.md

DOCS-2530 Lint Integrations section (part 5)

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/service_checks.py
hdfs_datanode/assets/service_checks.json
hdfs_datanode/metadata.csv
hdfs_namenode/assets/service_checks.json
hdfs_namenode/metadata.csv

Update `integration` name attached to service check so it matches with `display_name` in the manifest.json

Update service check and metadata integration name

---

crio/tests/conftest.py
crio/tests/test_crio.py
crio/tox.ini

Add minimal e2e test to the crio check

add e2e test for crio

---

nginx/README.md

ingress-nginx introduced a breaking change in 2019 where you gotta configure this endpoint thing now

DOCS-1323 - clearer configuration instructions for nginx

---

amazon_eks/README.md

this copy had been approved by amazon, we were just waiting to be sure this could be public

[DOCS-2368] add anywhere support to eks docs

---

sqlserver/README.md

Fix readme typo

---

process/README.md

This is a followup to #10834 - doing the same change in the README file.
See #10834.

Make process check configuration note in README clearer

---

sqlserver/assets/configuration/spec.yaml
sqlserver/datadog_checks/sqlserver/config_models/instance.py
sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
sqlserver/datadog_checks/sqlserver/statements.py

Update config spec to include additional statement metrics options

---

rabbitmq/assets/configuration/spec.yaml
rabbitmq/datadog_checks/rabbitmq/data/conf.yaml.example

Update description of config

---

silk/datadog_checks/silk/check.py

Use timestamp instead of datetime

---

datadog_checks_base/CHANGELOG.md

Update changelog on master to include the v23.3.3 release from the 7.33.x branch.

Update changelog to include v23.3.3

---

active_directory/datadog_checks/active_directory/data/conf.yaml.example
aspdotnet/datadog_checks/aspdotnet/data/conf.yaml.example
datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/common/perf_counters.yaml
datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/init_config/perf_counters.yaml
datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/perf_counters.yaml
hyperv/datadog_checks/hyperv/data/conf.yaml.example
iis/datadog_checks/iis/data/conf.yaml.example
windows_performance_counters/datadog_checks/windows_performance_counters/data/conf.yaml.example

https://github.com/DataDog/integrations-core/pull/10863#pullrequestreview-833150530

Update wording of config descriptions

---

snmp/assets/configuration/spec.yaml
snmp/datadog_checks/snmp/data/conf.yaml.example

Update auth and priv protocols

Update auth and priv protocols

---

snowflake/tests/snowflake_connector_patch/pyproject.toml

The interface is stable and old releases are being pruned

Update test dependency

---

dotnetclr/assets/configuration/spec.yaml
dotnetclr/datadog_checks/dotnetclr/check.py
dotnetclr/datadog_checks/dotnetclr/config_models/defaults.py
dotnetclr/datadog_checks/dotnetclr/config_models/instance.py
dotnetclr/datadog_checks/dotnetclr/config_models/shared.py
dotnetclr/datadog_checks/dotnetclr/data/conf.yaml.example
dotnetclr/datadog_checks/dotnetclr/dotnetclr.py
dotnetclr/datadog_checks/dotnetclr/metrics.py
dotnetclr/tests/common.py
dotnetclr/tests/test_dotnetclr.py
dotnetclr/tests/test_unit.py

See https://github.com/DataDog/integrations-core/pull/10504

Support new implementation of Windows performance counters on Python 3

---

docs/developer/process/agent-release/pre-release.md

Update agent release instructions with the docker windows py2 image name.

Update release docs with docker windows py2 image name

---

active_directory/assets/configuration/spec.yaml
active_directory/datadog_checks/active_directory/data/conf.yaml.example

Adds an example value for extra metrics

Add example config for `extra_metrics`

---

active_directory/README.md
aspdotnet/README.md
dotnetclr/README.md
hyperv/README.md
iis/README.md

https://github.com/DataDog/integrations-core/pull/10903#discussion_r773160450

Update docs about the new implementation

---

mesos_slave/manifest.json

Migrate mesos slave `integration_id` to ease mesos slave/master migration

Migrate mesos integration_id

---

eks_fargate/README.md

Changes the link for Live Containers
I used the documentation and was directed to a DogStatsD page

corrected live containers link

---

ibm_was/README.md
ignite/README.md
istio/README.md
jboss_wildfly/README.md
jmeter/README.md
journald/README.md
kafka/README.md
kafka_consumer/README.md
kong/README.md
kube_apiserver_metrics/README.md
kube_dns/README.md

DOCS-2530 Lint Integrations section (part 6)

---

kube_controller_manager/assets/configuration/spec.yaml
kube_controller_manager/datadog_checks/kube_controller_manager/data/auto_conf.yaml
kube_controller_manager/datadog_checks/kube_controller_manager/data/conf.yaml.example
kube_controller_manager/manifest.json

Adds config spec for `kube_controller_manager` integration

Add kube_controller_manager config spec

---

postgres/datadog_checks/postgres/statement_samples.py
postgres/tests/test_statements.py

Update error tags on internal `dd.postgres.statement_samples.error` metrics to all follow the same format. `error:explain-{code}-{message}`, regardless of whether they're a cached or new error. Some errors were failing to report the message when they were cached instead of new.
This ensures we get an accurate representation in the metrics as to which errors are being reported for all the events being ingested.
This also adds a new `dd.postgres.run_explain.error` metric which is only reported when an explain is actually run on the DB and fails. This metric can be compared to the cached explain error metrics to see what fraction of the explain errors are being cached.

improve internal explain error troubleshooting metrics

---

datadog_checks_dev/tests/tooling/configuration/consumers/model/test_all_required.py
datadog_checks_dev/tests/tooling/configuration/consumers/model/test_array.py
datadog_checks_dev/tests/tooling/configuration/consumers/model/test_both_models_basic.py
datadog_checks_dev/tests/tooling/configuration/consumers/model/test_common_validators.py
datadog_checks_dev/tests/tooling/configuration/consumers/model/test_defaults.py
datadog_checks_dev/tests/tooling/configuration/consumers/model/test_duplicate_hidden.py
datadog_checks_dev/tests/tooling/configuration/consumers/model/test_merge_instances.py
datadog_checks_dev/tests/tooling/configuration/consumers/model/test_nested_option.py
datadog_checks_dev/tests/tooling/configuration/consumers/model/test_object_arbitrary_values.py
datadog_checks_dev/tests/tooling/configuration/consumers/model/test_object_model.py
datadog_checks_dev/tests/tooling/configuration/consumers/model/test_object_typed_values.py
datadog_checks_dev/tests/tooling/configuration/consumers/model/test_only_shared.py
datadog_checks_dev/tests/tooling/configuration/consumers/model/test_option_name_normalization.py
datadog_checks_dev/tests/tooling/configuration/consumers/model/test_union_types.py

Tests were failing since #10927
Kube controller manager validation failure fixed in #10938

Fix models tests

---

kube_controller_manager/datadog_checks/kube_controller_manager/data/conf.yaml.example

Sync configuration spec

---

mesos_slave/assets/configuration/spec.yaml

Rename mesos slave spec

---

datadog_checks_base/datadog_checks/base/utils/db/utils.py

If a job is canceled in the middle of a run then it may error out due to trying to use a closed connection. Ensure we handle this gracefully and continue to report it as a cancelled job instead of a crashed job.
Avoid reporting cancelled jobs as failed jobs. This is also useful for integration tests where this race condition sometimes causes flaky tests.

fix incorrect logging in case of exceptions thrown during job cancellation

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/models.py
datadog_checks_dev/datadog_checks/dev/tooling/utils.py

If you sync today it will change all licenses to 2022

Do not regenerate models on new year

---

kube_dns/README.md
kube_metrics_server/README.md
kube_proxy/README.md
kube_scheduler/README.md
kubelet/README.md
kubernetes/README.md
kubernetes_state/README.md

DOCS-2530 Lint Integrations section (part 7)

---

hudi/tests/docker/Dockerfile
hudi/tests/docker/docker-compose.yaml
hudi/tox.ini

Ongoing effort to use newly built images

Upgrade version of Spark used for tests

---

datadog_checks_base/datadog_checks/base/utils/db/utils.py

Small logic fix for `obfuscate_sql_with_metadata`.
The `tables_csv` check is incorrect and does not check for None.

datadog_checks_base: Fix obfuscate_sql wrapper None value

---

LICENSE-3rdparty.csv
datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/licenses.py
php_fpm/datadog_checks/php_fpm/php_fpm.py
php_fpm/datadog_checks/php_fpm/vendor/fcgi_app.py
php_fpm/datadog_checks/php_fpm/vendor/fcgi_app_py2.py

Vendor `flup.client.fcgi_app` `flup-py3` version `1.0.3` and `flup` version `1.0.3.dev-20110405` so we don't explicitly rely on an unmaintained package
Also update the license entry
`flup` and `flup-py3` are not maintained anymore, and the sources were even removed.
There is no easy replacement package for FastCGI clients
* https://github.com/fastai/fastcgi seems to not fit our use case and be for server FCGI
* https://github.com/wuyunfeng/Python-FastCGI-Client is like depending on a unversioned package
We already ship vendored dependencies in `tokumx` integration.
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1828716.html
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=936535

Vendor flup client FCGIApp

---

snmp/assets/monitors/device_down.json

Update device_down.json device link
Make link more explicit to discourage users clicking on non-interpolated link.

Update device_down.json device link

---

mongo/README.md
mysql/README.md
nagios/README.md
network/README.md
nfsstat/README.md
nginx/README.md
nginx_ingress_controller/README.md
ntp/README.md
nvidia_jetson/README.md
openldap/README.md
openmetrics/README.md

DOCS-2530 Lint Integrations section (part 9)

---

lighttpd/README.md
linkerd/README.md
mapr/README.md
mapreduce/README.md
marathon/README.md
marklogic/README.md
mcache/README.md
mesos_master/README.md
mesos_slave/README.md

DOCS-2530 Lint Integrations section (part 8)

---

snmp/tests/compose/data/args_list.txt
snmp/tests/test_e2e_core_vs_python.py

Add more v3 users
Better coverage

Add more v3 users

---

datadog_checks_base/tests/models/data/spec.yaml
datadog_checks_dev/tests/tooling/configuration/consumers/model/test_deprecations.py
datadog_checks_dev/tests/tooling/configuration/consumers/test_example.py
docs/developer/meta/config-specs.md
mongo/assets/configuration/spec.yaml
mongo/datadog_checks/mongo/config_models/deprecations.py
mongo/datadog_checks/mongo/data/conf.yaml.example

Rename the `Release` field so it's more explicit which release it's referring to

Rename release deprecation field to agent version

---

ntp/README.md

Adds note saying NTP requests do not support proxy settings
DOCS-2719

Add note about proxy settings

---

kube_proxy/datadog_checks/kube_proxy/kube_proxy.py
kube_proxy/tests/fixtures/metrics_iptables_1.21.1.txt
kube_proxy/tests/fixtures/metrics_userspace_1.21.1.txt
kube_proxy/tests/test_kube_proxy.py
kube_proxy/tests/test_kube_proxy_1_21_1.py

Update metrics collected by kube_proxy check
Better user experience
A separate PR will be made to update metadata.csv to be merged when the next agent version is released

update kube proxy metrics

---

docs/developer/architecture/snmp.md

Just formatting `docs/developer/architecture/snmp.md`.
No content changes.
Some code block doesn't display correctly.

Format `docs/developer/architecture/snmp.md`

---

sqlserver/README.md

Add FreeTDS as another ODBC SQL Server driver that can be used. Several customers had issues sending over logs and using FreeTDS solved the issue.
DOCS-2881

[Documentation] Add FreeTDS to readme

---

openmetrics/README.md

Corrects Prometheus typo to OpenMetrics
Jira request

Corrects Prometheus typo in OpenMetrics docs

---

.github/codeql_config.yml
.github/workflows/codeql-analysis.yml

Static code analysis on integrations-core using Github's Code Scanning.
This PR has Github workflow configs to trigger the Code Scanning on every PR and on push to master branch. As of now only default security based CodeQL queries are configured. We can gradually add queries for Code Quality later. I have added a few test directories to ignore while code scanning. `paths-ignore` works only for interpreted languages like Python/Javascript. Feel free to keep / add / remove the entries from `codeql_config.yml`.

Setting up codescanning for integrations-core

---

nginx/README.md

This PR improves the documentation on how to set up the NGINX integration in a K8s environment
It took me a while to figure out how to set up NGINX correctly by following the old documentation

Improve nginx docs for K8s

---

snmp/datadog_checks/snmp/data/profiles/idrac.yaml

Failing nightly build due to illegal tab character.

Fix SNMP illegal tab character

---

snmp/datadog_checks/snmp/data/profiles/idrac.yaml

Fix more SNMP illegal tabs

---

elastic/setup.py

https://github.com/DataDog/integrations-core/pull/10894 Adds config validation, which was added in base 18.2.0

Bump base dependency

---

requirements-agent-release.txt

Update requirements-agent-releases.txt file

---

nginx/assets/dashboards/NGINX-Overview_dashboard.json

Updates the NGINX overview dashboard with fixed widget grouping.

Update NGINX overview dashboard

---

confluent_platform/datadog_checks/confluent_platform/data/metrics.yaml

Remove duplicated entries in the metrics.yaml

Remove duplicated entries

---

vault/assets/dashboards/vault_overview.json

Fix missing widgets on the Vault Dashboard.
Jira: https://datadoghq.atlassian.net/browse/SEC-2103
Staging dashboard: https://dd.datad0g.com/dash/integration/30258/vault---overview?from_ts=1641833116407&to_ts=1641836716407&live=true
Fix a broken widget.

Fix Vault dashboard

---

elastic/datadog_checks/elastic/config_models/validators.py

Validate custom query column type is allowed (metric type or tag)
QA #10894

Validate custom query column type

---

mysql/setup.py

Update the mysql check base version.
This is a follow up to: #11094

mysql: Update base version

---

postgres/setup.py

Update the postgres check base version.
This is a follow up to: #11094

postgres: Update base version

---

.gitlab-ci.yml

(cherry picked from commit 01b9aaa746ca94f0b233b41b357cc61b58f3f7ae)

export RELEASE_BRANCH as env var (#11077)

---

couchbase/assets/service_checks.json

Document new service check
QA #10784

Document couchbase.index_stats.can_connect

---

vsphere/README.md
vsphere/manifest.json

- Update vSphere integration to match standard template.
- Add short FAQ info directly to integration README.
Noticed during linting process.
N/A

DOCS-3000 Update vSphere integration

---

sidekiq/README.md
singlestore/README.md
snowflake/README.md
solr/README.md
sonarqube/README.md
spark/README.md
sqlserver/README.md
squid/README.md
ssh_check/README.md
statsd/README.md
supervisord/README.md
system_core/README.md
tcp_check/README.md
tcp_queue_length/README.md

DOCS-2530 Lint Integrations section (part 12)

---

weblogic/README.md
win32_event_log/README.md
wmi_check/README.md
yarn/README.md
zk/README.md

DOCS-2530 Lint Integrations section (part 14)

---

sqlserver/tox.ini

Use `datadog/docker-library` images instead of `djova/docker-library`.

Use `datadog/docker-library` Windows SQL Server images

---

teamcity/README.md
tenable/README.md
terraform/README.md
tokumx/README.md
tomcat/README.md
twemproxy/README.md
twistlock/README.md
varnish/README.md
vault/README.md
vertica/README.md
voltdb/README.md

DOCS-2530 Lint Integrations section (part 13)

---

singlestore/README.md

Removing extraneous tabs that are breaking the links

[documentation] removing tabs

---

oracle/tests/test_config.py

Adds an additional test case for the JDBC config test. 
For QA: https://github.com/DataDog/integrations-core/pull/10591

Add additional JDBC config test case

---

weblogic/tests/README.md

Adds instructions for running the WebLogic E2E.

Add E2E startup instructions

---

envoy/README.md

Add note about the old envoy configuration
QA #10752

Add note about old configuration

---

.gitlab/validate-logs-intgs/validate_log_intgs.py

Add `eks_anywhere` log exception, as it was merged recently and uses the `amazon_eks` pipeline

Add eks_anywhere log validation exception

---

docs/dev/create-an-integration-dashboard.md

Migrates the best practices for integration dashboard doc to the docs site
This is part of OKR 2 for the docs team this quarter.

Create an Integration Dashboard doc

---

mongo/datadog_checks/mongo/api.py
mongo/datadog_checks/mongo/mongo.py

nits for https://github.com/DataDog/integrations-core/pull/10843/

Small code nits

---

ibm_mq/assets/configuration/spec.yaml
ibm_mq/datadog_checks/ibm_mq/connection.py
ibm_mq/datadog_checks/ibm_mq/data/conf.yaml.example
nginx/datadog_checks/nginx/nginx.py

The existing debug message is a bit confusing

improve log message

---

nginx/datadog_checks/nginx/nginx.py

Followup for https://github.com/DataDog/integrations-core/pull/10815

Instruct the user to fix the error

---

amazon_msk/datadog_checks/amazon_msk/data/conf.yaml.example
avi_vantage/datadog_checks/avi_vantage/data/conf.yaml.example
cilium/datadog_checks/cilium/data/conf.yaml.example
cockroachdb/datadog_checks/cockroachdb/data/conf.yaml.example
coredns/datadog_checks/coredns/data/conf.yaml.example
datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/openmetrics.yaml
envoy/datadog_checks/envoy/data/conf.yaml.example
istio/datadog_checks/istio/data/conf.yaml.example
kong/datadog_checks/kong/data/conf.yaml.example
linkerd/datadog_checks/linkerd/data/conf.yaml.example
openmetrics/datadog_checks/openmetrics/data/conf.yaml.example

Make it more explicit that one should use the original label name for the filtering logic

Add note about label filtering order

---

snowflake/datadog_checks/snowflake/check.py

Register private_key_password as secret

---

ibm_mq/README.md

`PCFExecute` currently doesn't support z/OS: https://github.com/dsuch/pymqi/issues/279. 
Support case

Update readme with z/OS note

---

.github/CODEOWNERS

Add `container` integration to the CODEOWNER file and map it to #container-integrations team

Updating CODEOWNER for container integration

---

docs/dev/create-an-integration-dashboard.md

Updates the images paths to match the paths for the images in the docs repo

Updated image paths for create-an-integration-dashboard.md

---

docs/developer/tutorials/snmp/profile-format.md

Add metadata section to profile-format.md
https://github.com/DataDog/datadog-agent/pull/10058
https://github.com/DataDog/datadog-agent/pull/9943

Add metadata section to profile-format.md

---

vsphere/README.md

Adds note about applying permissions to child objects in order for them to get monitored.
Customer support case where VMs and Hosts were not getting monitored.

Clarify read-only user instructions

---

datadog_checks_dev/setup.py

A new version was released during the weekend (https://github.com/psf/black/releases/tag/22.1.0)
Same version pinned in https://github.com/DataDog/integrations-core/blob/cc85885d375e863bbc77d9d9b20aabe717144576/datadog_checks_dev/datadog_checks/dev/plugin/tox.py#L23
`black.find_project_root` changed returned value and is used in `datamodel-code-generator`
`datamodel-code-generator` package pins black to `20.8b0` https://github.com/koxudaxi/datamodel-code-generator/blob/cf4b361b5c2796a46acb88bd30a2377fffe4d22f/poetry.lock#L55

Pin black package

---

datadog_checks_base/CHANGELOG.md
datadog_checks_base/datadog_checks/base/__about__.py
requirements-agent-release.txt

Backport change from https://github.com/DataDog/integrations-core/pull/11257 onto master

[Release] Bumped datadog_checks_base version to 23.7.5 (#11257)

---

ibm_mq/tox.ini

Remove testing of 8.0 as it eoled on April 2021

Remove testing of 8

---

datadog_checks_dev/setup.py

https://github.com/koxudaxi/datamodel-code-generator/issues/700 fixed and released

Unpin black

---

windows_performance_counters/manifest.json

Make `windows_performance_counters` public
It was released in agent `7.33`

Make integration public

---

mysql/setup.py

Follow up to: https://github.com/DataDog/integrations-core/pull/11277

Update base version

---

.github/CODEOWNERS

@anshumgargdd requested to be removed as a code owner of the tenable integration. His work no longer focuses on this repo.

Update code owners for tenable

---

datadog_checks_base/datadog_checks/base/checks/openmetrics/base_check.py

Update error message when unable to connect to any possible prometheus urls

---

datadog_checks_dev/datadog_checks/dev/tooling/dependencies.py

`datadog-checks-base` does this, fixes CI for https://github.com/DataDog/integrations-core/pull/11301
No changelog since tooling update has not been released

Support multiple optional dependencies in `pyproject.toml` files

---

agent_metrics/README.md

Translator flagged some repetitive language in the overview.
Transifex

Agent Metrics Edit

---

datadog_checks_dev/datadog_checks/dev/plugin/tox.py

Fix style check environment to format correct files  
follow up to https://github.com/DataDog/integrations-core/pull/11300

Fix style format for Python checks defined by a pyproject.toml file 

---

terraform/README.md

Updates terraform integration docs with a section that shows how to send events for common terraform operations (apply, destroy).
Closes [this](https://github.com/DataDog/terraform-provider-datadog/issues/1261).

Document sending terraform events

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/datadog_checks/{check_name}/check.py
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/tests/test_{check_name}.py

Updates the new integration template with more up-to-date examples
Creating a new integration based off of the template

Update new check template

---

ibm_mq/README.md

Noticed while fixing up another PR
1. We should add validation for this
2. Is this a macOS thing?

Fix non-ASCII apostrophe

---

cassandra/README.md

Added an extra line for a bit more context and clarity on how to collect metrics from your Cassandra integration to your container - i.e. updating the agent image on your cluster to collect JMX (Cassandra) metrics. 
Add a little more context to how to collect JMX (Cassandra) metrics on the user's containerized environment with Auto-discovery.
https://datadog.zendesk.com/agent/tickets/670540
Not sure if placement of my addition is correct, open to feedback regarding this contribution

Corneille.tshibasu/cassandra jmx img edit

---

docs/dev/new_check_howto.md

Modernize packaging, continues https://github.com/DataDog/integrations-core/pull/11233

Update tutorial for creating a new integration

---

cilium/tests/common.py

Assert at_least 0 for flaky metric. 
Fix CI

Update optional metrics to test

---

.github/workflows/config/labeler.yml

Noticed on https://github.com/DataDog/integrations-core/pull/11555

Update no-changelog label criteria

---

pulsar/pyproject.toml
tokumx/pyproject.toml

Noticed while testing https://github.com/DataDog/integrations-core/pull/11554

Properly indicate Python constraints

---

datadog_checks_downloader/datadog_checks/downloader/cli.py
datadog_checks_downloader/datadog_checks/downloader/download.py
datadog_checks_downloader/tests/test_downloader.py

Add --ignore-python-version flag

---

nginx/datadog_checks/nginx/nginx.py
nginx/tests/test_unit.py

Change logic for printing out a log line from PR #11107 
QA

Adjust endpoint detection logic for warn log

---

silk/assets/configuration/spec.yaml
silk/datadog_checks/silk/data/conf.yaml.example

Updates the example port 
The silk web service typically runs on port 443

Update example port

---

ibm_db2/assets/configuration/spec.yaml
ibm_db2/datadog_checks/ibm_db2/config_models/instance.py

QA for https://github.com/DataDog/integrations-core/pull/11236

Set enum of security option

---

http_check/datadog_checks/http_check/http_check.py

Avoid reading response content unless necessary

---

silk/assets/dashboards/silk_overview.json
silk/manifest.json

Add a default dashboard for Silk:

Add Silk overview dashboard

---

weblogic/assets/dashboards/metrics.json
weblogic/assets/dashboards/overview.json
weblogic/assets/monitors/active_threads.json
weblogic/assets/monitors/stuck_threads.json
weblogic/manifest.json

Adds the following assets:
* WebLogic - Overview dashboard
* WebLogic - Metrics dashboard
* Active Threads monitor
* Stuck Threads monitor
**WebLogic - Overview**
**WebLogic - Metrics**

Add dashboards and recommended monitors

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/changelog.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/release/make.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/release/show/changes.py
datadog_checks_dev/datadog_checks/dev/tooling/git.py
datadog_checks_dev/tests/tooling/test_git.py

Need to break up changes due to a missed tag

Allow limiting released changes up to a specific ref

---

weblogic/manifest.json

Enable public docs
Release WebLogic

Enable public docs

---

yarn/tests/test_unit.py

Adds more tests for splitting application tags 
QA for https://github.com/DataDog/integrations-core/pull/11219/

Add additional tests for splitting tags

---

.gitlab/tagger/tag-release.sh

Part 2 of https://github.com/DataDog/integrations-core/pull/11605

Add skip prerelease flag

---

confluent_platform/datadog_checks/confluent_platform/data/metrics.yaml

Remove a duplicate bean in the bean matching list
Clean up duplicate beans that are already collected

remove duplicate bean

---

eks_fargate/README.md

Clarify adding the `kube_cluster_name` tag depending on the agent version
Apply this https://github.com/DataDog/integrations-core/pull/11041#discussion_r820698376

add note about kube_cluster_name for EKS Fargate

---

kubernetes/assets/dashboards/kubernetes_nodes.json

Replace deprecated metrics:
* `kubernetes_state.nodes.by_condition` by `kubernetes_state.node.by_condition`
keep up to date the dashboard

[kubernetes] Update Nodes dashboard

---

cilium/tests/common.py
cilium/tests/test_cilium.py
cilium/tests/test_e2e.py

Previous builds:
* https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=91385&view=logs&j=910f82a4-622d-5ace-f877-8b75c045486c&t=57642e18-890a-5eef-b695-2b3c448c1261
* https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=91390&view=logs&j=910f82a4-622d-5ace-f877-8b75c045486c&t=57642e18-890a-5eef-b695-2b3c448c1261

Add missing assertion to e2e test

---

oke/README.md
oke/manifest.json

Adding an empty log pipeline to pass validation. Also removes a non ascii character
```
Logs pipelines don't pass validation steps:
- oke: The check does not have a log pipeline but defines 'log collection' in its manifest file.
```

Fix oke log validation

---

iis/assets/service_checks.json

This PR documents the `iis.app_pool_up` service check for IIS.
`iis.app_pool_up` was added back in https://github.com/DataDog/integrations-core/pull/6549.

Document app_pool_up service check

---

envoy/README.md

Markdown syntax was visible on this page where it shouldn't have been. Believe this was due to the indenting.

change spacing so that markdown syntax isn't visible on main page

---

ecs_fargate/README.md

Document out-of-the-box tags on ECS Fargate
Parity with ECS EC2 https://github.com/DataDog/documentation/pull/13307

Document out-of-the-box tags on ECS Fargate

---

sonarqube/README.md

Adds documentation on exactly what sonar properties to modify since Sonarqube's documentation is misleading with regards to what ports to configure
- AGENT-5805
- AGENT-7054
- AGENT-7116

Sonarqube: update readme

---

mysql/datadog_checks/mysql/statements.py
mysql/tests/test_statements.py

Includes extracted SQL metadata in FQT samples for MySQL.

Include SQL metadata in FQT

---

snowflake/assets/configuration/spec.yaml
snowflake/datadog_checks/snowflake/config_models/validators.py
snowflake/datadog_checks/snowflake/data/conf.yaml.example

This reverts commit 70b1b1181e9b09e1c6114a29b47f6e864a53d211.
Accidentally merged to master instead of PR

Revert "Require private_key_password when using key pair auth"

---

weblogic/manifest.json

Fixes the process signature for WebLogic. Allows the integration to be detected when using the process-agent.
Fix

Fix process signature

---

oracle/datadog_checks/oracle/config_models/validators.py

Small fix in the instance validator for the protocol param
Support cases

Fix validation for the `protocol` param

---

eks_fargate/README.md

Add documentation on how to run Cluster Agent in EKS Fargate
Doc

Add documentation on how to deploy DCA on EKS Fargate

---

datadog_checks_base/datadog_checks/base/data/agent_requirements.in
oracle/pyproject.toml
sqlserver/pyproject.toml

https://github.com/DataDog/integrations-core/pull/11720#discussion_r833276220

Normalize dependency definitions

---

datadog_checks_dev/datadog_checks/dev/tooling/commands/dep.py

1. Some packages erroneously release universal wheels
2. Only use stable versions

Fix dependency tooling

---

disk/assets/service_checks.json

The main issue in this ticket is resolved. This cleans up the language
a bit and moves the note to a new line.

[DOCS-3134] Edit disk integration note

---

docs/developer/meta/config-specs.md

Update the description of the `description` key in config specs documentation. 
To provide more clarity to folks writing configuration specs

Update the description for the config spec description field

---

oracle/README.md

The missing line break was breaking links in the host tab.
DOCS-3286

[Documentation] Add line break to fix broken links

---

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/tox.ini
datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/tox.ini

- https://github.com/DataDog/integrations-core/pull/11731
- https://github.com/DataDog/integrations-core/pull/11742

Apply recent fix to new integration templates

---

kubernetes/assets/dashboards/kubernetes_clusters.json

Fix cluster dashboard URLs

---

haproxy/README.md

Remember to use hard brackets instead of soft brackets for links!
GitLab

Fixes Broken Link in HAProxy

---

datadog_checks_base/datadog_checks/base/utils/tracing.py

Enable integration tracing with the hidden `integration_tracing` datadog agent option
https://github.com/DataDog/datadog-agent/pull/11520

Add integration_tracing option

---

datadog_cluster_agent/datadog_checks/datadog_cluster_agent/check.py
datadog_cluster_agent/metadata.csv
datadog_cluster_agent/tests/fixtures/metrics.txt
datadog_cluster_agent/tests/test_datadog_cluster_agent.py

collect `datadog.cluster_agent.cluster_checks.configs_info`
Same as https://github.com/DataDog/datadog-agent/pull/11518
Related to https://github.com/DataDog/datadog-agent/pull/11518

Collect datadog_cluster_agent.cluster_checks.configs_info metric

---

ibm_ace/CHANGELOG.md
requirements-agent-release.txt

Slight adjustment to the changelog and add IBM ACE to agent requirements

Update agent requirement and changelog edits

---

oracle/datadog_checks/oracle/config_models/validators.py

Use `protocol` value for validation error instead of using `values.get('protocol')` since that can be empty.
QA for https://github.com/DataDog/integrations-core/pull/11675

Fix protocol validation

---

silk/manifest.json

Enable the Silk integration. This should be merged once Agent 7.35 is released.

Turn Silk to public

---

snowflake/README.md

Adds info on adding multiple Snowflake instances for the Agent to track.
[DOCS-1811][DOCS-1702]
[DOCS-1811]: https://datadoghq.atlassian.net/browse/DOCS-1811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-1702]: https://datadoghq.atlassian.net/browse/DOCS-1702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-1811][DOCS-1702] Multiple Snowflake instances

---

postgres/assets/configuration/spec.yaml
postgres/datadog_checks/postgres/data/conf.yaml.example

Line #134 had 2 "are"s in the sentence; submitting a PR to correct it and leave one.
Corrects line 34 so there is only one "are" in the sentence.
N/A
N/A

[Prod] ddmclav Correcting Verbiage

---

snmp/README.md

Add https://datadoghq.dev/integrations-core/tutorials/snmp/introduction/ to "Futher Reading" section
https://datadoghq.dev/integrations-core/tutorials/snmp/introduction/ helps to setup SNMP.

[doc] Add Introduction to SNMP

---

sqlserver/pyproject.toml

Related PR: https://github.com/DataDog/integrations-core/pull/11815

sqlserver: Update base version

---

cisco_aci/tests/README.md

This PR updates the `test/README` since the sandbox `pwd` is no longer `ciscopsdt`.

Update test README

---

nginx/assets/dashboards/NGINX-Overview_dashboard.json
nginx/assets/dashboards/plus_overview.json

[nginx] Add watchdog alerts to nginx and nginxplus dashboards

---

oracle/datadog_checks/oracle/config_models/validators.py
oracle/datadog_checks/oracle/oracle.py

If `protocol` is `None`, don't call `protocol.upper()`. Otherwise, it throws an `AttributeError`.
QA https://github.com/DataDog/integrations-core/pull/11791/

Handle NoneType protocol validation

---

rabbitmq/datadog_checks/rabbitmq/const.py
rabbitmq/datadog_checks/rabbitmq/rabbitmq.py

This PR refactors RabbitMQ.
QA

Refactor RabbitMQ

---

win32_event_log/README.md

Improves the events log example. I also made some small style changes.

[DOCS-3373] Update Win32 Event logs docs

---

ibm_mq/README.md

QA for https://github.com/DataDog/integrations-core/pull/11678

Add troubleshooting section to IBM mq readme

---

traffic_server/README.md

Update readme with note about default metrics collected

Update readme with note about default configuration

---

mysql/CHANGELOG.md
mysql/datadog_checks/mysql/__about__.py
postgres/CHANGELOG.md
postgres/datadog_checks/postgres/__about__.py
requirements-agent-release.txt
sqlserver/CHANGELOG.md
sqlserver/datadog_checks/sqlserver/__about__.py
voltdb/CHANGELOG.md
voltdb/datadog_checks/voltdb/__about__.py

Update the check versions for checks released from the 7.36.x branch
https://github.com/DataDog/integrations-core/pull/11838

Update release versions

---

traffic_server/assets/service_checks.json

Removes an incorrect service check group

Remove incorrect service check group

---

traffic_server/assets/monitors/4xx.json
traffic_server/assets/monitors/5xx.json
traffic_server/manifest.json

Adds recommended monitors for traffic server

Add traffic server recommended monitors

---

twistlock/assets/configuration/spec.yaml
twistlock/datadog_checks/twistlock/data/conf.yaml.example

Update for https://github.com/DataDog/integrations-core/issues/11808#issuecomment-1095341172
Prisma Cloud has different authentication mechanisms for their hosted and SaaS versions:
* https://prisma.pan.dev/docs/cloud/cwpp/access-api-self-hosted
* https://prisma.pan.dev/docs/cloud/cwpp/access-api-saas/

Update twistloc documentation

---

apache/README.md

Makes a test change to the Apache README to test push and PR workflow changes made in `nathan.pezzotti/github-validations-push-master-env`
Testing changes to github actions functionality

Test Github Actions Functionality in nathan.pezzotti/github-validations-push-master-env 

---

apache/README.md

Introduces small change to Apache README
Test changes introduced in https://github.com/DataDog/integrations-core/pull/11888

Test github actions changes in #11888

---

snowflake/README.md
snowflake/assets/configuration/spec.yaml
snowflake/datadog_checks/snowflake/data/conf.yaml.example

Adds a section in the readme and config file noting how to monitor snowflake when using a private connection

Add section in docs about private link setup

---

container/assets/dashboards/containers.json
container/manifest.json

* Add new OOTB dasboard for the `container` integration.
Showcase new `container` metrics.

feat(container): add OOTB dashboard

---

http_check/datadog_checks/http_check/http_check.py

QA for https://github.com/DataDog/integrations-core/pull/11590

Add type to response

---

consul/README.md

adds a bunch of further reading links to the blog
new potentially relevant information in blog posts

adding blog links to consul readme

---

eks_fargate/README.md

Fixes a broken link
reported by translator

Fix broken anchor link in EKS Fargate readme

---

eks_fargate/README.md

Makes the token handling note a little more specific and clear
Request from translator

EKS Fargate readme token handling clarification

---

tcp_check/datadog_checks/tcp_check/tcp_check.py
tcp_check/tests/common.py
tcp_check/tests/test_tcp_check.py

Make the `tcp_check` compatible with IPv6.
Support IPv6.

tcp_check: Add IPv6 support

---

oracle/tests/test_custom_queries.py

Followup of https://github.com/DataDog/integrations-core/pull/11875#pullrequestreview-953925903

Merge two tests with parametrize

---

singlestore/assets/dashboards/overview.json

Change the Singlestore widget layout so that it resizes on full screen.
`AI-2096`

Update Singlestore Dashboard Layout

---

docs/developer/tutorials/snmp/profile-format.md

Fix doc payload.go link

---

helm/README.md

Updates the README of the Helm integration. It adds a link to the service checks.
This should have been part of https://github.com/DataDog/integrations-core/pull/11766 , but I forgot to add it.

[helm] Update README with service checks info

---

datadog_checks_base/CHANGELOG.md
datadog_checks_base/datadog_checks/base/__about__.py
requirements-agent-release.txt

Updating master with the changes from a release branch release.

port over changes from last release

---

kafka_consumer/README.md

Adds kerberos authentication troubleshooting
Support case

Add kerberos troubleshooting

---

datadog_checks_dev/datadog_checks/dev/tooling/trello.py

Fixes "Exception: `team_list_map` and `label_team_map` do not have the same size" introduced in #11768

Fix check_map_consistency error

---

cisco_aci/tests/cisco_aci_query.py

Failing CI because style fail.

Fix Cisco ACI style

---

varnish/datadog_checks/varnish/varnish.py

Stop passing tags around as a parameter since it is now a class attribute

Stop passing tags around

---

arangodb/assets/dashboards/arangodb_overview.json
arangodb/manifest.json

This PR adds an OOTB dashboard for ArangoDB.

Add arangodb dashboard

---

postgres/tox.ini

This PR adds support for Postgres v14

Added support for Postgres v14

---

pgbouncer/datadog_checks/pgbouncer/pgbouncer.py

Customer request to prevent failed processing of a single row to halt execution

Handle errors for individual rows

---

sqlserver/pyproject.toml

Use this new version https://github.com/DataDog/integrations-core/pull/11985

Bump datadog_checks_base dep to 25.4.0 to use the QueryExecutor

---

sqlserver/assets/configuration/spec.yaml
sqlserver/datadog_checks/sqlserver/data/conf.yaml.example

As a follow-up to https://github.com/DataDog/integrations-core/pull/10832, clarify the distinction between example options for different connection providers.

Clarify the example configuration documentation for the MultiSubnetFailover option

---

ibm_ace/tests/README.md
ibm_ace/tests/conftest.py
ibm_ace/tests/test_config.py
ibm_ace/tests/test_unit.py

Adds config and unit tests
QA https://github.com/DataDog/integrations-core/pull/11654

Add additional tests to ibm_ace

---

datadog_checks_dev/datadog_checks/dev/plugin/hatch/environment_collector.py
datadog_checks_dev/datadog_checks/dev/tooling/testing.py
datadog_checks_dev/hatch.toml
datadog_checks_dev/pyproject.toml

- https://hatch.pypa.io/latest/config/environment/#context-formatting
- Better output

Upgrade Hatch to latest version

---

.github/workflows/validations.yaml

https://github.com/DataDog/integrations-core/runs/6473009367?check_suite_focus=true

Set dd_url for v2 manifest validation

---

requirements-agent-release.txt

Updates agent requirements file with new integrations for 7.37

Update agent requirements file

---

ibm_ace/manifest.json
traffic_server/manifest.json

Enable both Traffic Server and IBM Ace integration

Enable ibm ace and traffic server

---

arangodb/README.md

QA for https://github.com/DataDog/integrations-core/pull/11292

Update README to include log config

---

calico/README.md

[documentation] fixing a tab that is borking the docs build

---

eks_fargate/README.md

Fixes a blog post link in the Further Reading section.
#documentation Slack

Updates Further Reading Section in Amazon EKS on AWS Fargate

---

arangodb/tests/test_arangodb.py

Add unit tests
QA https://github.com/DataDog/integrations-core/pull/11292

Add unit tests

---

oracle/tests/test_custom_queries.py

Fix typo in test name

---

helm/assets/dashboards/overview.json
helm/manifest.json

Adds a dashboard for the Helm integration.

[helm] Add dashboard

---

teradata/tests/test_config.py

Adds a test for TD2 auth when username and password are not supplied and when they are
QA for https://github.com/DataDog/integrations-core/pull/11701/files

Add tests for TD2 auth

---

ibm_mq/tests/common.py
ibm_mq/tests/test_ibm_mq_int.py

Parameterizes ibm mq reset queues test
QA for https://github.com/DataDog/integrations-core/pull/11818/files

Parameterize ibm mq reset queues test

---

arangodb/README.md

Fixes broken link to the example config file. 
QA https://github.com/DataDog/integrations-core/pull/11292

Fix example config file link

---

active_directory/datadog_checks/active_directory/data/conf.yaml.example
aspdotnet/datadog_checks/aspdotnet/data/conf.yaml.example
datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/common/perf_counters.yaml
dotnetclr/datadog_checks/dotnetclr/data/conf.yaml.example
exchange_server/datadog_checks/exchange_server/data/conf.yaml.example
hyperv/datadog_checks/hyperv/data/conf.yaml.example
iis/datadog_checks/iis/data/conf.yaml.example
windows_performance_counters/datadog_checks/windows_performance_counters/data/conf.yaml.example

This PR clarifies the description of `metrics` for windows performance counters.
Support case

Update description of windows performance counters metrics

---

tox.ini

Docs build is broken with 0.19 release

Pin mkdocstrings

---

kafka/README.md

Fixes borked link (FAQ is now a guide).
GitLab

Updates FAQ to Guide Link in Kafka Integration

---

kafka_consumer/README.md

Fixes borked link (FAQ is now a guide).
GitLab

Updates FAQ to Guide Link in Kafka Consumer Integration

---

kafka/README.md

Update language in the readme

---

datadog_checks_dev/datadog_checks/dev/tooling/utils.py
docs/developer/.scripts/33_render_status.py

Track manifest V2 migration for this repo through the docs dev page
Keep track of migration progress and which folders are left

Include information about the manifest migration in the docs build

---

datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/v2/migration.py

https://en.wikipedia.org/wiki/MacOS#macOS

Fix manifest migration of macOS tag

---

weblogic/README.md

Adds an overview to the WebLogic integration README.

Add overview for WebLogic integration

---

teradata/datadog_checks/teradata/check.py
teradata/datadog_checks/teradata/utils.py
teradata/tests/test_utils.py

Refactors util method signatures to not take in a check
QA for teradata

Refactor util method signatures

---

ibm_mq/tests/README.md

Add more detailed testing instructions for running the check in a virtual environment when having import issues

Add more detailed testing instructions

---

datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/v2/validator.py

Adjust description length constraints to handle different in-app experiences while integrations in core/extras get migrated to V2

Adjust description character limits in manifest

---

databricks/README.md

Add information regarding DD_SITE for databricks integration
Several support cases for databricks are missing this parameter (EU customers)

[us-prod]-update-databricks-doc

---

envoy/assets/dashboards/envoy_overview.json

Improves existing OOTB dashboard

Improve OOTB dashboard

---

traffic_server/assets/dashboards/overview.json
traffic_server/manifest.json

Adds a default dashboard for traffic server

Add dashboard for traffic server

---

teamcity/manifest.json
teamcity/metadata.csv

Move everything to new pipelines

Update manifest to version 2.0.0

---

arangodb/manifest.json
teradata/manifest.json

Makes teradata and arangodb public
7.37.0 release

Make teradata and arangodb public

---

datadog_checks_dev/datadog_checks/dev/tooling/release.py

Copies https://github.com/DataDog/datadog-agent/pull/12535

Fix tooling to support v2 manifests

---

docs/developer/.scripts/33_render_status.py

Sort the integration in the manifest migration status docs section when rendering
Orders the integrations so its easier to read through

Sort integrations when rendering

---

tenable/manifest.json
tenable/metadata.csv

Reverts DataDog/integrations-core#12315

Revert "Update manifest to version 2.0.0"

---

mysql/README.md

Fix a bad link in the MySQL docs
Documentation build link checker is broken

Fix WMI link in MySQL docs

---

helm/README.md

adds link to recent blog post
Docs maintenance

Helm: Add link to blog post

---

vault/datadog_checks/vault/check.py
vault/datadog_checks/vault/vault.py
vault/tests/test_vault.py

Uses is_affirmative for collect_secondary_dr to cover more inputs, and improves code readability by renaming a variable that did not make sense after https://github.com/DataDog/integrations-core/pull/12099
QA for https://github.com/DataDog/integrations-core/pull/12099

Properly read `collect_secondary_dr` and improve code readability

---

datadog_checks_dev/datadog_checks/dev/tooling/create.py

traceback on Windows, no readme for integrations-extras

Fix new integration creation on Windows and for integrations-extras

---

datadog_checks_base/CHANGELOG.md
datadog_checks_base/datadog_checks/base/__about__.py
requirements-agent-release.txt

https://github.com/DataDog/integrations-core/pull/12482

backport release

---

redisdb/README.md

Removes a link to a deleted FAQ
DOCS-3484
Depends on the following PR being merged in first:
https://github.com/DataDog/documentation/pull/14539

(DOCS-3484) Remove outdated link

---

couchbase/tests/test_couchbase.py

This test is flaking, on this PR I'm relaxing the requirement and improving the error message. I've opened https://datadoghq.atlassian.net/browse/AI-2561 internally to improve the testing and documentation of this.

Improve assertion error message, soften requirement

---

snmp/assets/configuration/spec.yaml
snmp/datadog_checks/snmp/data/conf.yaml.example

Remove namespace from doc
We should use `network_devices.namespace` from datadog.yaml instead.

Remove namespace from doc

---

ibm_ace/datadog_checks/ibm_ace/subscription.py

Tests for IBM ACE failed on https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=104905&view=logs&j=dd4b56be-071e-57b4-2a5e-8eda93907f10&t=de2bf97c-09ab-578d-74d6-50a77c38a36d&l=48
And I notice we don't emit a message in case of warning or critical service check. These messages can appear in monitor triggers.
```
_____________________________________ test _____________________________________
tests/test_integration.py:25: in test
aggregator.assert_service_check('ibm_ace.mq.subscription', ServiceCheck.OK, tags=tags)
../datadog_checks_base/datadog_checks/base/stubs/aggregator.py:399: in assert_service_check
self._assert(
../datadog_checks_base/datadog_checks/base/stubs/aggregator.py:408: in …
```

Add error message in case of service checks not ok

---

datadog_checks_dev/datadog_checks/dev/conditions.py

Add method parameters documentation

Document docker logs and checkcommandoutput

---

datadog_checks_dev/datadog_checks/dev/plugin/hatch/environment_collector.py

https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=105183&view=logs&j=70a237a0-2c52-52f8-23f1-657d682c7ecf&t=d85edea3-9fa0-5bee-ebb0-f3a77200749a&l=53

Fix nightly base package builds that use Hatch

---

datadog_cluster_agent/datadog_checks/datadog_cluster_agent/check.py
datadog_cluster_agent/metadata.csv
datadog_cluster_agent/tests/fixtures/metrics.txt
datadog_cluster_agent/tests/test_datadog_cluster_agent.py

Collect `datadog.cluster_agent.admission_webhooks.library_injection_attempts` and `datadog.cluster_agent.admission_webhooks.library_injection_errors`
Keep the integration up-to-date and collect new metrics
Related to https://github.com/DataDog/datadog-agent/pull/12621

Collect lib injection metrics

---

avi_vantage/tests/conftest.py

Environment failed to start on CI

Add attempts

---

windows_service/datadog_checks/windows_service/windows_service.py

NO code change.
Update the MS document link in the comment.
https://docs.microsoft.com/en-us/windows/desktop/api/winsvc/ns-winsvc-_service_status returns 404, so replace it with https://docs.microsoft.com/en-us/windows/win32/api/winsvc/ns-winsvc-service_status_process

windows_service: update link to ms doc in the comment

---

postgres/tests/compose/resources/02_setup.sh
postgres/tests/test_statements.py

[Database Monitoring] update tests with new function

---

mysql/datadog_checks/mysql/mysql.py

Just cleaning comment
Removing useless comment (code is about *perf* metrics, comment talks about *size of schemas*)

Remove un-related comment

---

snowflake/README.md

Fixes the formatting of the code example in the snowflake readme

Fix yaml formatting in readme

---

linkerd/tests/conftest.py

docker-compose failed on https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=105820&view=logs&j=519bd84d-28fd-598c-db49-0d219af79ef0&t=8d8170c7-f175-5c28-3510-d1de6e6f4791&l=274

Add attempts to linkerd

---

weblogic/tests/conftest.py

Docker compose failed on https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=106029&view=logs&j=96b895a2-fce6-59ba-503d-dd55ff027b2d&t=e3169927-c0e8-54d6-1576-3f9f1b9d1aaf&l=187
Adding a second attempts

[Weblogic] Add attempts to docker_run

---

tls/tox.ini

Remove legacy compose from E2E environment

---

datadog_checks_base/tox.ini

Remove legacy compose from E2E

Remove legacy compose from E2E

---

vertica/datadog_checks/vertica/queries.py
vertica/datadog_checks/vertica/vertica.py
vertica/tests/common.py
vertica/tests/conftest.py
vertica/tests/db.py
vertica/tests/docker/docker-compose.yaml
vertica/tests/test_queries.py
vertica/tests/test_unit.py
vertica/tests/test_vertica.py

- Refactors code to make it a bit easier to test.
- Adds test fixtures to facilitate testing of queries. The queries are tested on ad-hoc tables that imitate system tables that the check would actually query but which are obviously not modifiable.
- Adds tests for queries that include any sort of logic / computation / aggregation in it.
- Adds a few more tests to achieve full coverage.
Follow up to #12542, where Python logic was replaced by the use of queries. I wanted to have more confidence about the correctness of the queries I added.

Add tests for DB queries and complete remaining test coverage

---

kube_proxy/README.md

Update kube proxy readme to have the required sections

Add required sections to readme

---

kube_proxy/manifest.json

Adds a description for kube proxy

Add minimal description for kube proxy

---

snowflake/assets/dashboards/organization_metrics.json
snowflake/manifest.json

Adds a new dashboard highlighting all the organization usage metrics available in snowflake.

Add snowflake organization usage dashboard

---

directory/datadog_checks/directory/directory.py

This PR adds debug logging to the directory check.
Support escalations

Add debug logging to directory check

---

kube_apiserver_metrics/README.md

Remove note about lack of tile
We are creating a tile for this integration

Remove note about lack of tile

---

vsphere/README.md

Adds a section in the vsphere readme for monitoring TKG

Add docs section for monitoring TKG

---

datadog_checks_base/tests/base/utils/test_http.py
datadog_checks_base/tests/compose/socks5-proxy.yaml
datadog_checks_base/tests/conftest.py

1. Fix typo from https://github.com/DataDog/integrations-core/pull/12650
2. Ensure server waits on proxy
3. Skip Kerberos tests on Windows always

Fix socks5 tests

---

databricks/assets/dashboards/databricks_overview.json
helm/assets/dashboards/overview.json
kubernetes/assets/dashboards/kubernetes_clusters.json
kubernetes/assets/dashboards/kubernetes_dashboard.json
kubernetes/assets/dashboards/kubernetes_nodes.json
nginx/assets/dashboards/NGINX-Overview_dashboard.json
nginx/assets/dashboards/plus_overview.json
silk/assets/dashboards/silk_overview.json
spark/assets/dashboards/spark_dashboard.json
twistlock/assets/dashboards/overview.json
vsphere/assets/dashboards/vsphere_overview.json
yarn/assets/dashboards/hadoop_dashboard.json

Update event widgets queries to v2
Events migration

Update event widgets queries to v2

---

tenable/manifest.json
tenable/metadata.csv

Reverts DataDog/integrations-core#12422

Revert "Revert "Update manifest to version 2.0.0""

---

redisdb/CHANGELOG.md

Add missing info in the changelog.
QA for https://github.com/DataDog/integrations-core/pull/12505

Update the 4.5.2 changelog

---

ecs_fargate/README.md

Fixes tab coding showing up on in-app integration tile
DOCS-3931
There are still some region-param coding showing up, will fix that next.

DOCS-3931 ECS Fargate readme/docs: fix tabs and some regions in-app

---

datadog_checks_dev/datadog_checks/dev/tooling/testing.py

Exclude ddev from minimum base dependency tests
Fix CI

Exclude ddev from minimum base dependency tests

---

teradata/README.md
teradata/tests/README.md

Fix broken links in the teradata README files.

Fix links in the README files

---

arangodb/README.md

Fix broken links in the arangodb README file.

Fix links in the README

---

dns_check/tests/common.py

Validate the metrics gathered using the `metadata.csv` file.
Spotted while investigating a support case.
No need to include this in the current release, we can wait for the next one.

Validate the metrics using metadata

---

sonarqube/README.md

Add a subheader to clarify the docs a bit.

Add a subheader for the search server note

---

datadog_checks_dev/datadog_checks/dev/tooling/constants.py
datadog_checks_dev/datadog_checks/dev/tooling/create.py

Templatize the README links for the `ddev create` command
- https://github.com/DataDog/integrations-core/pull/12740
- https://github.com/DataDog/integrations-core/pull/12741
Ran it and it worked well:
```
╰─❯ ddev --here create Test                                                                                                                                                                                                                                                                                             
Created in `/Users/florent.clarret/go/src/github.com/DataDog/integrations-core`:
test
├── assets
│   └── configuration
│       └── spec.yaml
│   └── dashboards
│       └── test_overview.json
│   └── service_checks.json
├── datadog_checks
│   └── test
│       └── config_models
│ …
```

Templatize the README links

---

datadog_checks_dev/pyproject.toml

New features https://hatch.pypa.io/latest/history/#hatch-v1.4.0

Upgrade dependencies for environment management

---

kong/datadog_checks/kong/kong.py

Accidentally pushed a commit to master, this PR reverts that change.
https://github.com/DataDog/integrations-core/commit/02849885765b8d171a646fbd8e53325ac2ab7437
😿

Revert change to Kong integration

---

datadog_checks_base/datadog_checks/base/stubs/aggregator.py

We were not printing which metric or which tag was being problematic

Fix formatting of message

---

vault/README.md

Removes a sentence that could be misleading.
DOCS-3941

[DOCS-3941] Remove potentially misleading sentence

---

datadog_checks_dev/tests/tooling/commands/validate/data/my_check/manifest.json

Update a manifest file in the unit tests.
Migration done

Migrate manifest file to v2 in tests

---

datadog_checks_base/tests/compose/socks5-proxy.yaml

Attempt to fix socks5 environment

Bump docker compose version

---

datadog_checks_base/tests/base/utils/http/test_socks5_proxy.py

After skipping the first test the second started flaking with the same error

Skip all sock5 tests on ci

---

mongo/datadog_checks/mongo/api.py

After upgrading to pymongo 4 we are experiencing some issues related to connecting to mongo hosts.
Explained [here](https://pymongo.readthedocs.io/en/stable/migrate-to-pymongo4.html#pymongo4-migration-direct-connection)

Solve issue after migration to pymongo 4

---

snowflake/README.md

Add a `Further Reading` section with a link to the recent Snowflake Blog:
https://www.datadoghq.com/blog/snowflake-monitoring-datadog/
Spread knowledge of Datadog's integration with Snowflake
Preview link:
https://docs-staging.datadoghq.com/bryce/update-pull-config-preview-for-blog-link/integrations/snowflake/#further-reading

(DOCS) Add further reading section and blog link

---

amazon_eks/README.md
eks_anywhere/README.md

Fixes two broken links.
Documentation build link checker found the broken links

Fix EKS Fargate link

---

kubernetes/assets/service_checks.json

Fixes a couple of Kubernetes service checks.

Fix service checks

---

kong/assets/dashboards/kong_api.json
kong/manifest.json

Add a new dashboard created by Kong.

Add new Kong API dashboard

---

datadog_checks_dev/datadog_checks/dev/tooling/testing.py
datadog_checks_dev/pyproject.toml

Necessary for https://github.com/DataDog/integrations-core/pull/12766

Upgrade Hatch

---

LICENSE-3rdparty.csv
datadog_checks_base/datadog_checks/base/data/agent_requirements.in
datadog_checks_base/datadog_checks/base/utils/http.py
datadog_checks_base/pyproject.toml
datadog_checks_base/tests/base/utils/http/test_authtoken.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/licenses.py

Needed for multiple integrations now
Config spec update will be a separate PR

Add OAuth functionality to the HTTP util

---

snowflake/README.md

Adds section in the snowflake readme about collecting all organization metrics
Ensure users know how to collect all metrics from the readme

Add section in readme about collecting all organization metrics

---

kafka_consumer/assets/configuration/spec.yaml
kafka_consumer/datadog_checks/kafka_consumer/config_models/defaults.py
kafka_consumer/datadog_checks/kafka_consumer/config_models/instance.py
kafka_consumer/datadog_checks/kafka_consumer/data/conf.yaml.example
kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py

Customer request, see [KIP-255](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=75968876)

Fix support for OAUTHBEARER SASL mechanism

---

azure_iot_edge/tests/compose/docker-compose.yaml
azure_iot_edge/tests/compose/mock_server/docker-compose.yaml
azure_iot_edge/tests/conftest.py
azure_iot_edge/tox.ini

Remove legacy compose

---

impala/assets/configuration/spec.yaml
impala/assets/dashboards/impala_catalog_overview.json
impala/assets/dashboards/impala_daemon_overview.json
impala/assets/dashboards/impala_statestore_overview.json
impala/datadog_checks/impala/data/conf.yaml.example
impala/manifest.json

Add the logs section in the configuration.
https://github.com/DataDog/integrations-core/pull/12548

Add the logs

---

sap_hana/tests/conftest.py

Reverts DataDog/integrations-core#12878

Revert "Add sleep after hana environment set up"

---

datadog_checks_dev/datadog_checks/dev/ci.py
datadog_checks_dev/datadog_checks/dev/docker.py
datadog_checks_dev/datadog_checks/dev/env.py
datadog_checks_dev/tests/test__env.py
datadog_checks_dev/tests/test_docker.py

Default to two attempts when running environments on CI

Attempts default to 2 on ci

---

mongo/assets/dashboards/overview.json

Refresh dashboards with new latencies and correct errors for MongoDB

---

.github/workflows/labeler-reusable.yml

Disable PR labels sync

---

sap_hana/tests/conftest.py

Merged by mistake Reverts DataDog/integrations-core#12900

Revert "Revert "Add sleep after hana environment set up""

---

databricks/README.md

Adjusts script to no start on install. Adds sleep before a restart.
Escalation. Not having a sleep could sometimes cause the job driver to hang up

Adjust script based on escalation

---

vertica/assets/dashboards/overview.json

Updates the dashboard of the Vertica integration to make it follow current guidelines.
AI-2670

Update Vertica dashboard

---

singlestore/README.md

removed a note that was not relevant to containers
hotjar

DOCS-3612 - remove redundant/irrelevant note about metrics collection in Singlestore integration

---

activemq/hatch.toml
activemq_xml/hatch.toml
ambari/hatch.toml
avi_vantage/hatch.toml
gitlab_runner/hatch.toml
openmetrics/hatch.toml

Remove the bench environments.
When I migrated those migrations to hatch, I added the bench envs but they were not defined in the `tox.ini` file. They are not needed here and only slow down the CI.

Remove bench environments

---

cilium/tests/conftest.py
datadog_checks_dev/datadog_checks/dev/kind.py
datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py
datadog_checks_dev/datadog_checks/dev/tooling/testing.py
datadog_checks_dev/datadog_checks/dev/utils.py
foundationdb/tests/common.py
foundationdb/tests/conftest.py
foundationdb/tests/test_foundationdb.py
snmp/tests/common.py
snmp/tests/conftest.py
teradata/tests/common.py
teradata/tests/test_e2e.py
windows_performance_counters/tests/test_e2e.py

Support Hatch, see https://github.com/DataDog/integrations-core/pull/12938#discussion_r972121004

Refactor tooling for getting the current env name

---

.gitlab-ci.yml

Pin tagger image

---

datadog_checks_base/datadog_checks/base/checks/windows/perf_counters/base.py
datadog_checks_base/datadog_checks/base/checks/windows/perf_counters/refresh.py

Add a param to the agent to control how often window counters should be refreshed.
Linked PR:
https://github.com/DataDog/datadog-agent/pull/13273

Add agent config option to control Window Counter refresh rate
