DataDog/integrations-core

mysql/datadog_checks/mysql/mysql.py, mysql/tests/test_connection.py
This PR enables autocommit on connections to ensure each query is executed as a separate transaction. The current behavior is to disable autocommit, which requires a `COMMIT` or `ROLLBACK` to be executed on connection close. But that cannot be guaranteed (network disruptions, hard shutdowns, etc.).
In the worst case, a transaction can remain open with uncommitted undo log actions on the InnoDB history. Since the agent does not require transaction isolation for any of its functionality, enabling autocommit should be the safest option.
=> Enable autocommit on all connections

apache/assets/dashboards/apache_dashboard.json, apache/datadog_checks/apache/apache.py, apache/metadata.csv, apache/tests/common.py, apache/tests/compose/httpd.conf, apache/tests/test_apache.py
The PR adds metrics that can be derived from the Apache scoreboard. Mainly the maximum of workers available and a count of workers for each state a worker can be in. This is an expansion on the existing `idle_workers` and `busy_workers` metrics that are currently available. 
Currently datadog reports the busy and idle workers but those metrics are most usefull in the context of the maximum workers that can be started on a server. For example, you could have 100 Busy workers but if you have a heavy webserver that can easily handle 500 workers you are fine. But when you run with 100 max workers your apache is full and putting requests in a queue or maybe even dropping requests. The idle workers will then be 0 and you can set-up an alert on that but there are cases where the idle_workers …
=> Added metrics from the apache scoreboard

redisdb/datadog_checks/redisdb/redisdb.py
This fixes a bug where old slowlog entries could continually contribute to slowlog metrics.
If there were no new slowlog entries seen by the check, it would
reset the last seen timestamp to 0. This would cause the next run
to see all of the slowlog entries as new again. The next run after
that would find nothing new and again reset last seen to 0, etc.
Note that this doesn't prevent us from reparsing old slowlog entries if datadog agent restarts, but this should still be an improvement.
=> Fix Redis slowlog parsing when no new slowlog entries

redisdb/datadog_checks/redisdb/redisdb.py
Overrides 'SLOWLOG GET' response callback with fixed/upstream version of `parse_slowlog_get`
- fixed version not going to make it to redis==3.x.x
- https://github.com/andymccurdy/redis-py/blob/master/README.rst#response-callbacks
=> Overrides 'SLOWLOG GET' response callback with fixed/upstream version of `parse_slowlog_get`

redisdb/datadog_checks/redisdb/redisdb.py
Refactored service checks to submit OK in `else` clause. Add error message to critical service checks.
Improve usability
=> Make critical service checks more verbose

ibm_mq/datadog_checks/ibm_mq/collectors/queue_metric_collector.py
Close internal reply queue when collecting queue stats.
We tried to fix this in #8349 , but customer didn't test the beta release. Here is the original explaination of the fix:
A customer reported that the Agent writes to a dead-letter queue (DLQ) associated to `PYMQPCF.*`. `PYMQPCF.*` is the prefix of internal queues (known as "reply queues") used by pymqi when executing a command. 
* Under normal conditions, the command succeeds and pymqi pops messages from those queues to form the final response, leaving no undelivered messages and nothing in the DLQ.
* But if an exception occurs, some messages may be left in the reply queue, and because we don't dispose it explicitly they will be left hanging there, marked as "undelivered", and moved to a DLQ. By calling `pcf.disconnect()`, the reply …
=> Properly close internal reply queues

mesos_slave/assets/configuration/spec.yaml, mesos_slave/datadog_checks/mesos_slave/data/conf.yaml.example, mesos_slave/datadog_checks/mesos_slave/mesos_slave.py, mesos_slave/tests/conftest.py, mesos_slave/tests/fixtures/state-summary.json, mesos_slave/tests/test_unit.py
This PR mitigates the mesos_slave integration DDOSing the mesos master. 
When we tried adding in the mesos_slave integration into our system, the agents DDOS'd the master, by sending hundreds of requests every minute to the masters `/state` endpoint, all to get one piece of static information (the cluster name). That particular endpoint, `/state`, returned a JSON object around `85MB`, as it returned the entire history of the entire cluster to the agents, all to get one very small piece of static configuration - the `cluster_name`. 
This fix mitigates that in 3 ways:
1. It directs the master traffic to `/state-summary`, rather than `/state`, to get a significantly smaller response
2. It caches the `cluster_name` on the agent, assuming that in most cases the cluster name doesn't change, and …
=> Add instance option for cluster_name in mesos_slave integration

tox.ini
The base package has strict pins which breaks the current version of pip's resolver so we should force those in a final install step
=> Fix docs build

consul/datadog_checks/consul/metrics.py, consul/tests/common.py
Adding prometheus support for some metrics available through dogstatsd
Metadata update in #9388
=> Add missing prometheus metrics

activemq/datadog_checks/activemq/data/conf.yaml.example, cassandra/datadog_checks/cassandra/config_models/defaults.py, cassandra/datadog_checks/cassandra/data/conf.yaml.example, confluent_platform/datadog_checks/confluent_platform/data/conf.yaml.example, datadog_checks_dev/datadog_checks/dev/jmx.py, datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/init_config/jmx.yaml, hazelcast/datadog_checks/hazelcast/data/conf.yaml.example, hive/datadog_checks/hive/data/conf.yaml.example, hivemq/datadog_checks/hivemq/data/conf.yaml.example, ignite/datadog_checks/ignite/data/conf.yaml.example, jboss_wildfly/datadog_checks/jboss_wildfly/data/conf.yaml.example, kafka/datadog_checks/kafka/config_models/defaults.py, kafka/datadog_checks/kafka/data/conf.yaml.example, kafka/tests/test_check.py, presto/datadog_checks/presto/data/conf.yaml.example, presto/tests/test_presto.py, solr/datadog_checks/solr/data/conf.yaml.example, solr/tests/test_check.py, sonarqube/datadog_checks/sonarqube/config_models/defaults.py, sonarqube/datadog_checks/sonarqube/data/conf.yaml.example, sonarqube/tests/metrics.py, tomcat/datadog_checks/tomcat/config_models/defaults.py, tomcat/datadog_checks/tomcat/data/conf.yaml.example, tomcat/tests/common.py, tomcat/tests/test_check.py
Match behavior of `collect_default_metrics` (see https://github.com/DataDog/integrations-core/pull/9441) as we plan on changing the default value of both to `true` in a major version update
=> Enable `new_gc_metrics` JMX config option for new installations

mesos_master/assets/service_checks.json, mesos_master/datadog_checks/mesos_master/mesos_master.py, mesos_master/tests/test_check.py
http://mesos.apache.org/documentation/latest/endpoints/master/state/
According to the doc, the `/state` endpoint returns `307` when the master is not the current leader, and redirect to the current leader. However, the `Authorization` headers are not passed after a 307 redirection, so we end up with a 401 for example.
If we fail to get the master state with both the legacy and the new method, we make sure there was no `307` in the history before failing.
Support case
=> Fix master leader detection after 307

.gitlab/validate-agent-build/trigger_agent_build.py
Replace `master` reference on Gitlab validator to `main`
Upcoming change from `master` to `main` on the `datadog-agent` repository.
- **This should be merged only after the renaming.**
- PRs need to be rebased to include this commit, otherwise they will point to the old `master` branch
- Reviewers should check that there are not other references to the `master` branch of the `datadog-agent` repository on this repository (links are okay; they will be redirected automatically).
=> [Gitlab] Replace `master` reference to `main`

envoy/assets/configuration/spec.yaml, envoy/datadog_checks/envoy/config_models/defaults.py, envoy/datadog_checks/envoy/config_models/instance.py, envoy/datadog_checks/envoy/data/conf.yaml.example, envoy/datadog_checks/envoy/envoy.py, envoy/datadog_checks/envoy/metrics.py, envoy/datadog_checks/envoy/parser.py, envoy/tests/test_parser.py
Rename tags:
* `cluster_name` -> `envoy_cluster`
* `virtual_cluster_name` -> `virtual_envoy_cluster`
with a configuration option for backward compatibility.
Same name as in spark config https://github.com/DataDog/integrations-core/blob/51a570ae9f8824f1e53911e7bc01bf84a2f00094/spark/datadog_checks/spark/data/conf.yaml.example#L138
=> Rename cluster_name tag to envoy_cluster

cilium/assets/configuration/spec.yaml, cilium/datadog_checks/cilium/data/auto_conf.yaml
Cilium container updated https://hub.docker.com/r/cilium/cilium
Fix autodiscovery
=> Update container identifier

cilium/assets/configuration/spec.yaml, cilium/datadog_checks/cilium/data/auto_conf.yaml
Uses both identifiers to ensure compatibility.
https://github.com/DataDog/integrations-core/pull/9512#discussion_r651526461
=> Use cilium-agent and cilium as autodiscover identifiers

consul/datadog_checks/consul/consul.py, consul/tests/test_unit.py
Cases involving thousands of services/API calls
=> Improve performance of loading JSON responses on Python 3

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/requirements.in
https://nvd.nist.gov/vuln/detail/CVE-2021-29510
> In affected versions passing either `'infinity'`, `'inf'` or `float('inf')` (or their negatives) to `datetime` or `date` fields causes validation to run forever with 100% CPU usage (on one CPU). Pydantic has been patched with fixes available in the following versions: v1.8.2, v1.7.4, v1.6.2.
=> Upgrade pydantic to 1.8.2

consul/datadog_checks/consul/consul.py, consul/tests/consul_mocks.py, consul/tests/test_bench.py, consul/tox.ini
Customer noticed that the method is slow b/c we perform redundant computation
This introduces caching to reduce the constant factor
=> Improve performance of latency metric computation

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, pgbouncer/requirements.in, postgres/requirements.in
Upgrade psycopg2-binary to 2.8.6
This version adds support for Python 3.9.
=> Upgrade psycopg2-binary to 2.8.6

.gitlab-ci.yml
Didn't realize we could do it per-job like this. This job is usually times out too often
=> Set validate-agent-build job timeout to 2h

sqlserver/tests/common.py
- Checks for duplicate metrics in the SQL Server integration tests.
- Catch potential issues arising when duplicate metrics are submitted, which can result in unexpected values or the agent resetting the counter (AGENT-6021)
=> Check for duplicate metrics in common metric assertion

datadog_checks_base/datadog_checks/base/stubs/aggregator.py, datadog_checks_base/tests/stubs/test_aggregator_no_duplicate.py
- Updates the the aggregator's no duplicates assertion to check for duplicate monotonic count types
- Explores options for failing aggregator when duplicate metrics are submitted for metric types which should have one context per run, such as rate
- `AI-1553`
- Submitting duplicate rates or monotonic counts (when new sample is less than previous) can lead to unexpected values or the agent resetting the counter
Ideas explored to fail aggregator when this occurs:
1. Initial idea for catching the issue at metric submission:
```
NON_DUPLICATE_TYPES = [RATE, MONOTONIC_COUNT]
...    
def submit_metric(self, check, check_id, mtype, name, value, tags, hostname, flush_first_value):
if mtype in self.NON_DUPLICATE_TYPES and self.is_duplicate_context(MetricStub(name, mtype, value, tags, hostname, …
```
=> Remove monotonic count from ignored types in no duplicate assertion

mysql/tests/compose/mariadb.conf
Remove unused `performance-schema-instrument='stage/%=ON'` parameter from `mariadb.conf`.
Remove potentially confusing parameters from the test configuration. If we don't need it then it shouldn't be in there.
=> remove unused mariadb parameter from test config

mysql/tests/conftest.py
Update the mysql test grant permission statement to use one grant to grant the agent full execute permissions within the `datadog` schema. This matches instructions the will be in the setup documentation.
Make tests match docs.
=> update mysql test grant permission

cacti/datadog_checks/cacti/cacti.py, ceph/datadog_checks/ceph/ceph.py, ceph/tests/test_integration.py, ceph/tests/test_unit.py
Update to use agent 8 signature (do not use instance in check method) and throws agent exceptions instead of a generic one
=> ceph agent 8 signature

postgres/datadog_checks/postgres/statement_samples.py
Execution plans collection is expected to fail in many cases, like if a client is using the extended query protocol meaning we won't get the original parameters from `pg_stat_activity`. To avoid spamming the logs, update this message to be logged only at the debug level.
This now matches what we do for mysql.
Reduce spammy logging.
=> log execution plan collection failure at debug level

aerospike/requirements.in, datadog_checks_base/datadog_checks/base/data/agent_requirements.in
=> Upgrade `aerospike` dependency on Python 3

.github/CODEOWNERS
Fix codeowner pattern for `database-monitoring` team. 
Follow-up to https://github.com/DataDog/integrations-core/pull/9511
=> Fix codeowner for database-monitoring

redisdb/datadog_checks/redisdb/redisdb.py, redisdb/tests/test_default.py, redisdb/tests/test_e2e.py
This is a breaking change.
The PR removes the redis_role tag from service checks and updates tests accordingly. 
`redis_role` is only successfully tagged when the connection is successful. This results in a context mismatch between `OK` and `CRITICAL`.
=> Remove redis_role tag from service check

istio/assets/dashboards/istio_1_5_overview.json
The percent calculation was wrong, so users had percentage > 100% heap memory used.
https://golang.org/pkg/runtime/#MemStats
See `HeapAlloc` and `HeapInuse`
Other widgets using `*alloc_bytes*` or `*inuse_bytes*` are correct
All the widgets are using a `top( ..., 10, 'mean', 'desc')` query, so i'm keeping it for consistency
=> Fix dashboard query

aerospike/datadog_checks/aerospike/aerospike.py, aerospike/metadata.csv, aerospike/tests/common.py
For such commands, we would silently ignore the last result https://github.com/DataDog/integrations-core/blob/21a90b00f603b00250c4baa6534e47ee5529ed3c/aerospike/datadog_checks/aerospike/aerospike.py#L519-L521
See e.g. `sets/NAMESPACE/SET` of https://docs.aerospike.com/docs/reference/info#sets
=> Handle command output with erroneous trailing separators

aerospike/datadog_checks/aerospike/aerospike.py, aerospike/metadata.csv, aerospike/tests/common.py, aerospike/tests/test_aerospike.py, aerospike/tests/test_unit.py, aerospike/tox.ini
- https://docs.aerospike.com/apidocs/python/client.html#aerospike.Client.info_node
- https://docs.aerospike.com/docs/client/python/usage/incompatible.html#version-6-0-0
> Because of changes in client authentication internals in C client 5.2.0, info_node() will fail if used when authentication is enabled. Checkout info_single_node() for a replacement.
=> Stop using a deprecated method to support newer versions of Aerospike

datadog_checks_base/datadog_checks/base/utils/db/utils.py, datadog_checks_base/requirements.in, datadog_checks_base/tests/test_db_util.py
Add a new `RateLimitingTTLCache` for rate limiting by key during collection of statement samples and execution plans.
This ensures correct usage of the underlying `TTLCache` for the purpose of rate limiting.
Add a util for usage within the `postgres` and `mysql` checks to ensure they do rate limiting correctly. 
See example usage in https://github.com/DataDog/integrations-core/pull/9581
=> Add `RateLimitingTTLCache` to `db.utils`

datadog_checks_base/datadog_checks/base/utils/db/utils.py, datadog_checks_base/tests/test_db_util.py
Explicitly do float division so the sleep duration is correctly calculated in python2.
Fix broken behavior.
=> Fix Python 2 integer division bug in db.util `ConstantRateLimiter`

mysql/datadog_checks/mysql/statement_samples.py, mysql/setup.py, mysql/tests/test_mysql.py
Fixes the previously incorrect rate limiting behavior which would allow ingestion of extra statement samples beyond the `maxsize` limit. The same problem existed for the `explained_statements` rate limit.
Depends on https://github.com/DataDog/integrations-core/pull/9582
=> Fix insufficient rate limiting of statement samples 

amazon_msk/tox.ini, azure_iot_edge/tox.ini, cilium/tox.ini, confluent_platform/tox.ini, consul/tests/test_unit.py, coredns/tox.ini, datadog_checks_base/datadog_checks/base/stubs/aggregator.py, datadog_checks_base/tox.ini, etcd/tox.ini, gitlab_runner/tox.ini, hdfs_namenode/tests/common.py, hdfs_namenode/tox.ini, kong/tox.ini, kubernetes_state/tox.ini, marathon/tox.ini, php_fpm/tests/test_e2e.py, php_fpm/tests/test_php_fpm.py, php_fpm/tox.ini, process/tests/common.py, rethinkdb/tests/common.py, rethinkdb/tests/unit/test_config.py, rethinkdb/tox.ini, scylla/tox.ini, snowflake/tox.ini, varnish/tests/common.py, varnish/tests/test_e2e.py, varnish/tests/test_unit.py, varnish/tests/test_varnish.py, varnish/tox.ini
Extend the forbidden generic tag list introduced in #9431  with https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes as suggested here https://github.com/DataDog/integrations-core/pull/9431#discussion_r651921032
Non-openmetrics/jmx integration to fix:
* Apache (`host`)
* Consul (`service`)
* Lighttpd (`host`)
* Mapr (`clustername`)
* Marathon (`version`)
* Mongo (at least `host`)
* Nginx (`host` in service_check)
* pgbouncer (`host` in service_check)
* postgres (at least `host`)
* rethinkdb (`host` in service_check)
* Snowflake (`service`)
* Sqlserver (at least `host` in service checks)
* Tokumx (at least `host` in service checks)
* Twemproxy (at least `host` in service checks)
* vertica (`host_name`)
* Voltdb (at least `host` in service checks)
* zk …
=> Extend forbidden generic tag list

datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/openmetrics.yaml, kong/datadog_checks/kong/data/conf.yaml.example
Add a brief example to the openmetrics.yaml file to show how to exclude all metrics but the one matching a filter.
=> Add negative-lookahead example for `exclude_metrics` OpenMetrics option

coredns/assets/dashboards/coredns.json, kube_controller_manager/assets/dashboards/overview.json, kube_scheduler/assets/dashboards/overview.json, kubernetes/assets/dashboards/kubernetes_dashboard.json, kubernetes/assets/dashboards/kubernetes_nodes.json, kubernetes/assets/dashboards/kubernetes_pods.json
Update several kubernetes related integrations to use `kube_cluster_name` instead
of `cluster_name`.
Several integrations already use `kube_cluster_name` tags. To be more align between
the different integrations, this PR update the remaining reference to `cluster_name`
in favour of `kube_cluster_name`.
N/A
=> Update k8s dashboards to use `kube_cluster_name` tags instead of `cluster_name`

eks_fargate/README.md
Update fluentbit configuration doc link on the `eks_fargate` README.md. 
the previous link in that section: https://docs.datadoghq.com/integrations/eks_fargate/#collecting-logs-from-eks-on-fargate-with-fluent-bit was pointing to the "cluster-agent" configuration.
=> Fix Fluentbit documentation link in eks_fargate integration

postgres/datadog_checks/postgres/statement_samples.py, postgres/tests/test_pg_integration.py
Provides a reason for not having a PostgreSQL execution plan.
Currently in Database Monitoring, the UX is lacking when it comes to execution plans. There are cases where it's impossible to collect or something failed, so we should indicate the reason it could not be collected and actions to fix it, if any.
=> Provide a reason for not having an execution plan (Postgres)

mysql/datadog_checks/mysql/statement_samples.py, mysql/tests/test_mysql.py
Provides a reason for not having a MySQL execution plan.
Currently in Database Monitoring, the UX is lacking when it comes to execution plans. There are cases where it's impossible to collect or something failed, so we should indicate the reason it could not be collected and actions to fix it, if any.
=> Provide a reason for not having an execution plan (MySQL)

mysql/datadog_checks/mysql/mysql.py, mysql/tests/conftest.py, mysql/tox.ini
Looks for `mariadbd` process instead of `mysqld` for MariaDB 10.5+
AGENT-6383
Missing mysql.performance.cpu_time metric for MariaDB 10.5 hosts, though is is working for MariaDB 5.5 hosts.
It appears in version 10.4 the executable name was changed from mysql to mariadb. 
- https://mariadb.com/docs/features/whats-new/whats-new-in-community-server-105/
=> Look for mariadbd process for MariaDB 10.5+

kube_scheduler/assets/configuration/spec.yaml, kube_scheduler/datadog_checks/kube_scheduler/data/auto_conf.yaml
Leverages the `possible_prometheus_urls` parameter introduced by #9573 in the auto-discovery configuration file.
Make the agent able to automatically monitor the Kube scheduler on most recent versions of Kubernetes without requiring too much user setup.
The goad is to simplify the Kubernetes control plane monitoring setup described in DataDog/documentation#10828.
On older versions of Kubernetes, the Kube scheduler metrics were available at `http://%%host%%:10251/metrics` where `%%host%%` is the node IP.
On most recent version of Kubernetes,
* only the secure `https` endpoint is available by default. The plain `http` endpoint is disabled by default.
* the port is bound on the loopback interface on `127.0.0.1` instead of being remotely available.
The new auto-discovery configuration will …
=> Fix auto-discovery for latest versions on Kubernetes

mysql/assets/configuration/spec.yaml, mysql/datadog_checks/mysql/config.py, mysql/datadog_checks/mysql/config_models/defaults.py, mysql/datadog_checks/mysql/config_models/instance.py, mysql/datadog_checks/mysql/data/conf.yaml.example, mysql/datadog_checks/mysql/mysql.py, mysql/datadog_checks/mysql/statement_samples.py, mysql/tests/test_mysql.py
* `statement_samples.enabled` now defaults to `true`
* `deep_database_monitoring` renamed to `dbm` (while still supporting the old key)
=> DBM statement_samples enabled by default, rename DBM-enabled key

postgres/datadog_checks/postgres/statements.py, postgres/tests/test_pg_integration.py
This adds better error handling of the case where `pg_stat_statements` isn't enabled as well as implement some generic handling for other errors. It does so by catching the error and logging a message as well as incrementing a counter tagged with the reason. 
Improve logging to help users diagnose misconfigurations as well as improve visibility on the setup error via metrics.
=> Add better error handling/reporting for database errors when querying pg_stat_statements

tcp_check/datadog_checks/tcp_check/tcp_check.py, tcp_check/tests/test_tcp_check.py
If IP resolution fails on check `__init__` it will never be reattempted. This PR makes IP resolution lazy so it happens on `check` run instead of ` __init__`. Upon connection failure it now forces a reevaluation on next `check` run instead of straight away.
=> Do not resolve IP on __init__

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/dashboard.py
Need to be less restrictive to support new routes e.g.
```
$ ddev meta dash export https://app.datadoghq.com/dashboard/znc-pbv-mny amazon_msk
Invalid `url`
```
=> Fix `meta dash export`

oom_kill/README.md
Document the fact that the `oom_kill` check requires a kernel 4.9 or more recent.
People might be tempted to try the `oom_kill` check on old Linux versions. Let’s document when it’s not even worth trying !
=> Document the minimum kernel version needed by the `oom_kill` check

datadog_checks_dev/datadog_checks/dev/tooling/specs/configuration/consumers/example.py, datadog_checks_dev/datadog_checks/dev/tooling/specs/configuration/consumers/model.py, datadog_checks_dev/datadog_checks/dev/tooling/specs/configuration/spec.py, datadog_checks_dev/tests/tooling/configuration/consumers/model/test_merge_instances.py, datadog_checks_dev/tests/tooling/configuration/consumers/test_example.py, docs/developer/meta/config-specs.md
The goal of this PR is to be able to have multiple instances in a single `conf.yaml.example`.
This PR respects the following constraints:
- Every existing `spec.yaml` generating `conf.yaml.example` is still correct, pass validation, and don't need a new sync
- Every existing `spec.yaml` generating `config_models/*` files is still correct, pass validation and don't need a new sync
- When a `spec.yaml` has multiple instances defined:
- Each instance has its own description
- A configuration option can appear in as many instances as we want
- A configuration option appearing in more than one instance must have the same `required`, `deprecation`, `metadata_tags` and `value.type` values across all the instances, but can have different descriptions or example
- The `conf.yaml.example` generated …
=> Support multiple instances in config specs

postgres/datadog_checks/postgres/statement_samples.py, postgres/tests/test_pg_integration.py
This adds a boolean field to postgres query sample events so we can later surface this to users. 
We'd like to be able to surface when a statement has been truncated so we can advise uses on how to proceed to prevent truncation (which would be increasing `track_activity_query_size`).
The detection of a truncated statement is done by reading the `track_activity_query_size` postgres setting and checking the size of the query. Note that the length of queries is actually 1 less than the value of the setting as illustrated by this example below where the configuration was set to `100`:
```
select length(query), query from pg_stat_activity;
length |                                                query
--------+-------------------------------------------------------------------------------------- …
```
=> Add truncated statement indicator to postgres query sample events

mysql/datadog_checks/mysql/statement_samples.py, mysql/tests/test_mysql.py
This adds a boolean field to mysql query sample events so we can later surface this to users.
We'd like to be able to surface when a statement has been truncated so we can advise uses on how to proceed to prevent truncation (which would be increasing `performance_schema_max_sql_text_length`).
The detection of a truncated statement is done by checking for the presence of `...` at the end of a statement. This works for all supported versions (as the tests show).
=> Add truncated statement indicator to mysql query sample events

datadog_checks_base/datadog_checks/base/utils/db/utils.py, datadog_checks_base/tests/test_db_util.py
Adds a new `DBMAsyncJob` class which will be used by the `postgres` and `mysql` checks to schedule asynchronous tasks that need to run independently of the main check.
Follow-up PRs:
* postgres: https://github.com/DataDog/integrations-core/pull/9657
* mysql: https://github.com/DataDog/integrations-core/pull/9658 
Standardize approach for doing work asynchronously using threads for DBM.
=> Add `db.utils.DBMAsyncJob`

datadog_checks_base/datadog_checks/base/stubs/datadog_agent.py
Updates the `obfuscate_sql` method stub in the agent to support a new `options` argument.
For more context as to why this argument was introduced, refer to one of these PRs:
- [PostgreSQL](https://github.com/DataDog/integrations-core/pull/9640)
- [MySQL](https://github.com/DataDog/integrations-core/pull/9639)
=> Update obfuscator stub in agent

mysql/assets/configuration/spec.yaml, mysql/datadog_checks/mysql/config.py, mysql/datadog_checks/mysql/config_models/defaults.py, mysql/datadog_checks/mysql/config_models/instance.py, mysql/datadog_checks/mysql/data/conf.yaml.example, mysql/datadog_checks/mysql/mysql.py, mysql/datadog_checks/mysql/statement_samples.py, mysql/datadog_checks/mysql/statements.py, mysql/setup.py, mysql/tests/test_mysql.py
* decouple the DBM metrics collection interval from the check run interval
* set default DBM metrics collection interval to 10s 
* change `statement_samples.collections_per_second` to `statement_samples.collection_interval` so it matches the new `statement_metrics.collection_interval` key 
Depends on https://github.com/DataDog/integrations-core/pull/9656
Being able to configure the DBM metrics collection interval separately from the check run interval enables us to use a 10 second interval (by default) for the query metrics. There are various difficulties when querying metrics that have a 15 second interval (i.e. ensuring a correct rollup window for varying time ranges) that don't exist with a 10 second interval.
=> decouple DBM query metrics interval from check run interval

mysql/datadog_checks/mysql/statement_samples.py
Extraction of cost from execution plans is now being done during ingestion.
=> remove execution plan cost extraction

postgres/assets/configuration/spec.yaml, postgres/datadog_checks/postgres/config.py, postgres/datadog_checks/postgres/config_models/defaults.py, postgres/datadog_checks/postgres/config_models/instance.py, postgres/datadog_checks/postgres/data/conf.yaml.example, postgres/datadog_checks/postgres/statement_samples.py, postgres/datadog_checks/postgres/statements.py, postgres/tests/test_pg_integration.py
Adjust terminology in config keys & related metrics to replace `statement` with `query`.
=> Change DBM `statement` config keys and metric terminology to `query`

postgres/datadog_checks/postgres/postgres.py, postgres/tests/compose/resources/01_postgres.sql, postgres/tests/test_pg_integration.py
Fix broken error handling introduced by a refactor of `load_query_max_text_size` in https://github.com/DataDog/integrations-core/pull/9657
=> fix broken error handling in reading of pg_settings

postgres/datadog_checks/postgres/statement_samples.py, postgres/datadog_checks/postgres/statements.py
Fixes obfuscator options being converted into bytes rather than string. Error found (MySQL, but Postgres still applies):
```
2021-07-12 17:14:20 UTC | CORE | WARN | (pkg/collector/python/datadog_agent.go:124 in LogMessage) | mysql:c94166e47fbb1ecc | (statements.py:190) | Failed to obfuscate query 'SELECT ?': argument 2 must be str, not bytes
```
=> Fix obfuscator options being converted into bytes rather than string

cilium/assets/configuration/spec.yaml, cilium/datadog_checks/cilium/data/auto_conf.yaml
Reverts the addition of `cilium` as an AD identifier from that PR: https://github.com/DataDog/integrations-core/pull/9512
The change is valid but triggers a bug with the agent and the default helm chart of cilium. The init container images are named "cilium" and the agent tries to monitor them indefinitely.
Revert this PR once the previously mentioned bug is fixed.
=> Revert cilium AD change

postgres/datadog_checks/postgres/statements.py, postgres/tests/test_pg_integration.py
Fix crash caused by `None` version, which was introduced during a refactor in https://github.com/DataDog/integrations-core/pull/9657. Should have accessed `check.version` not `check._version`.
```
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/postgres/statements.py", line 182, in collect_per_statement_metrics
major=self._check._version.major, minor=self._check._version.minor, patch=self._check._version.patch
AttributeError: 'NoneType' object has no attribute 'major'
```
=> fix None-version crash for DBM statement metrics

postgres/datadog_checks/postgres/statement_samples.py, postgres/tests/test_pg_integration.py
Updates the `collection_errors` type to match MySQL to keep it consistent.
=> Update Postgres collection error type to match MySQL

postgres/datadog_checks/postgres/statements.py, postgres/tests/test_pg_integration.py
As of https://github.com/DataDog/integrations-core/pull/9657 the DBM metrics interval is decoupled from the check's `min_collection_interval`. This new DBM-metrics-specific value needs to be set in the DBM metrics payloads.
=> fix incorrect `min_collection_interval` on DBM metrics payload

ibm_mq/datadog_checks/ibm_mq/collectors/channel_metric_collector.py, ibm_mq/datadog_checks/ibm_mq/collectors/queue_metric_collector.py, ibm_mq/datadog_checks/ibm_mq/collectors/stats_collector.py
When there were no messages on a channel we were incorrectly logging a warning. That was solved in:
* https://github.com/DataDog/integrations-core/pull/9400
* https://github.com/DataDog/integrations-core/pull/9452
This PR adds logging back as debug
=> Add debug line when there are no messages available

.azure-pipelines/templates/run-validations.yml
* Profile validation does not work on "integrations-extras" yet. 
* Let's put a condition in the Azure CI so that it runs only for "core", for now.
* We have blocked PR on integrtations-extra
=> SNMP profile validation is run only for 'core'

statsd/assets/configuration/spec.yaml, statsd/datadog_checks/statsd/config_models/instance.py, statsd/datadog_checks/statsd/data/conf.yaml.example
We allow `float` values for timeout in code https://github.com/DataDog/integrations-core/blob/4b7527e9d4ae909ee9a777cb0d6d16e5b335d0a0/statsd/datadog_checks/statsd/statsd.py#L23
But we converted it to `int` anyway with the config models https://pydantic-docs.helpmanual.io/usage/types/
QA #8990
=> Allow float value for timeout

datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/schema.py
For the author homepage, enforce a full absolute URL structure
If the URL is relative, or just missing the protocol or `www.` it's possible the frontend will try to redirect to `app.datadoghq.com/<author_homepage>` instead. 
There isn't a URL format in jsonschema, so you have to use a combination of the `uri` format and a pattern including the protocols accepted.
=> Use pattern for enforcing a URL structure for author->homepage in manifest

mysql/datadog_checks/mysql/mysql.py
Old executable name is still supported, so we should still look for it https://mariadb.com/docs/whats-new/prior-series/whats-new-in-community-server-105/
QA #9543
=> Support old executable names

mysql/setup.py
Fixes broken nightly builds that were using an older version causing error `obfuscate_sql() takes 2 positional arguments but 3 were given`.
=> Bump `datadog-checks-base` version requirement

airflow/README.md
Update the containerized instructions and make a clearer distinction between the two forms of this integration (standard vs statsd)
Clarify setup steps with respect to a containerized setup after a couple customer issues
Original Docs: https://docs.datadoghq.com/integrations/airflow/?tab=containerized#configuration
Wasn't sure if I should explicitly list in the docs that `airflow.can_connect` and `airflow.healthy` are emitted from the base integration, while everything is relative to StatsD. But felt like the following under `Configuration` was sufficient:
> There are two forms of the Airflow integration. There is the Datadog Agent integration which will make requests to a provided endpoint for Airflow to report whether it can connect and is healthy. Then there is the Airflow StatsD …
=> [Airflow] update containerized setup instructions

ibm_mq/datadog_checks/ibm_mq/collectors/channel_metric_collector.py
On https://github.com/DataDog/integrations-core/pull/9400 we stopped emitting misleading warning messages but we were still emitting a critical service check that is also misleading
=> Do not submit critical service check when there are no messages

vault/datadog_checks/vault/metrics.py, vault/datadog_checks/vault/vault.py, vault/tests/test_vault.py
Vault route metrics had a function for transforming them and a `METRIC_ROLLBACK_COMPAT_MAP` existed to capture pre-defined metrics for specific Vault mounts that are common in getting started with Vault but did not capture all the Vault route metrics from any Vault mount.
Relates to https://github.com/DataDog/integrations-core/pull/8761
There is a need to see these per mount metrics to better understand our systems.
Also fixed the LDAP metric defined in `METRIC_ROLLBACK_COMPAT_MAP`.
=> Add Vault route metrics to be fetched from the Prometheus endpoint

apache/tests/test_apache.py
Followup of https://github.com/DataDog/integrations-core/pull/9355
Asserts metrics using metadata and asserts no duplicate metrics are emitted
=> apache add missing assertions

amazon_msk/datadog_checks/amazon_msk/data/conf.yaml.example, azure_iot_edge/datadog_checks/azure_iot_edge/data/conf.yaml.example, cilium/datadog_checks/cilium/data/conf.yaml.example, cockroachdb/datadog_checks/cockroachdb/data/conf.yaml.example, coredns/datadog_checks/coredns/data/conf.yaml.example, crio/datadog_checks/crio/data/conf.yaml.example, datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/openmetrics_legacy.yaml, etcd/datadog_checks/etcd/data/conf.yaml.example, external_dns/datadog_checks/external_dns/data/conf.yaml.example, gitlab/datadog_checks/gitlab/data/conf.yaml.example, gitlab_runner/datadog_checks/gitlab_runner/data/conf.yaml.example, haproxy/datadog_checks/haproxy/data/conf.yaml.example, istio/datadog_checks/istio/data/conf.yaml.example, kube_apiserver_metrics/datadog_checks/kube_apiserver_metrics/data/conf.yaml.example, kube_scheduler/datadog_checks/kube_scheduler/data/conf.yaml.example, linkerd/datadog_checks/linkerd/data/conf.yaml.example, nginx_ingress_controller/datadog_checks/nginx_ingress_controller/data/conf.yaml.example, openmetrics/datadog_checks/openmetrics/data/conf.yaml.example, scylla/datadog_checks/scylla/data/conf.yaml.example
Clarify the behaviour of `ignore_metrics` and fix the config examples
fixes: https://github.com/DataDog/integrations-core/issues/9721/
=> Fix `ignore_metrics` documentation

.azure-pipelines/templates/run-validations.yml
Enable `ddev validate ci` for all repos.  Makes the variable True by default since it seems all existing repositories were running this check. 
Support for the marketplace repository for `ddev validate ci` was released today. This enabled the validation to run in that CI
=> Enable CI validation for all repos

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/ci.py
Support an empty string option for the jobs and/or codecov part of `ddev validate ci`
Not all repositories may have codecov setup but still use the AZP templates. This ensures you can choose one or the other to have validated
=> Support empty config options for job or codecov

kubernetes/assets/monitors/monitor_statefulset_replicas.json
Revert one change from https://github.com/DataDog/integrations-core/pull/9485/ that does not seem to work
Fix
=> [kubernetes][monitors] Fix statefulset monitor

redisdb/metadata.csv, redisdb/tests/test_e2e.py
cannot include checking for duplicates because there are duplicates
Test flaked on https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=70750&view=logs&j=28d964ed-ced8-53cb-c786-cadbc5b4e9d8&t=01f908e0-b712-54ab-b4e6-5b3231df2d3c&l=225
=> Fix flaky test, add more assertions and missing metric

couch/tests/test_couchv2.py
Add missing optional metrics
Test flaked on https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=70820&view=logs&j=c73aedc7-d1f1-5bee-93b6-629007590bd5&t=622fd669-15c6-58d9-3442-b4f44bd24cfb&l=697
Also add missing metadata assertions
=> Fix flake & add missing assertions

proxysql/datadog_checks/proxysql/queries.py
Add a new service check mapping for `SHUNNED_REPLICATION_LAG` to `CRITICAL` for `proxysql.backend.status`. Current behavior maps it to `UNKNOWN`
Escalation/FR from a ticket
Link to proxysql statuses:
https://github.com/sysown/proxysql/blob/bd3e96a015da802320beb2ba96b0270cf00cb28e/include/proxysql_structs.h#L18
Sample output from proxysql:
```
MySQL [(none)]> SELECT status FROM stats_mysql_connection_pool\G
status: SHUNNED_REPLICATION_LAG
```
=> Support `SHUNNED_REPLICATION_LAG` status for `proxysql.backend.status` service check

mysql/datadog_checks/mysql/config_models/validators.py, mysql/tests/test_mysql.py, mysql/tests/test_statements.py, oracle/datadog_checks/oracle/config_models/validators.py, supervisord/datadog_checks/supervisord/config_models/validators.py
https://github.com/DataDog/integrations-core/pull/9340
Config validation would fail if e.g. `username` is required & `user` is being used
=> Properly allow deprecated required config

cassandra/assets/configuration/spec.yaml, cassandra/datadog_checks/cassandra/config_models/defaults.py, cassandra/datadog_checks/cassandra/config_models/instance.py, datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/jmx.yaml, kafka/assets/configuration/spec.yaml, kafka/datadog_checks/kafka/config_models/defaults.py, kafka/datadog_checks/kafka/config_models/instance.py, sonarqube/assets/configuration/spec.yaml, sonarqube/datadog_checks/sonarqube/config_models/defaults.py, sonarqube/datadog_checks/sonarqube/config_models/instance.py, sonarqube/datadog_checks/sonarqube/data/conf.yaml.example, tomcat/assets/configuration/spec.yaml, tomcat/datadog_checks/tomcat/config_models/defaults.py, tomcat/datadog_checks/tomcat/config_models/instance.py
Setting `is_jmx` at instance level is supported since https://github.com/DataDog/datadog-agent/pull/5141.
Having `is_jmx: true` at instance level is useful in a few set of JMX integration only, such as `sonarqube` which is both a JMX and a Python integration.
=> Add is_jmx instance flag documentation

postgres/datadog_checks/postgres/metrics_cache.py
Fix string formatting in debug log for Postgres check
This causes the postgres check to fail when running with debug logs
Check fails with the following error:  
```
=========
Collector
=========
Running Checks
==============
postgres (7.0.2)
----------------
Instance ID: postgres:c37d7deba49bb494 [ERROR]
Configuration Source: file:/etc/datadog-agent/conf.d/postgres.d/conf_postgres.yaml
Total Runs: 1
Service Checks: Last Run: 1, Total: 1
Average Execution Time : 41ms
Last Execution Date : 2021-07-12 09:11:18 UTC (1626081078000)
Last Successful Execution Date : Never
metadata:
version.major: 10
version.minor: 14
version.patch: 0
version.raw: 10.14
version.scheme: semver
Error: not all arguments converted during string …
```
=> Fix debug log formating

snmp/datadog_checks/snmp/data/conf.yaml.example
Enclose community string using single quote
If community string contain special character the actual community string being use to reach the device might be wrong.
=> Enclose community string using single quote

win32_event_log/assets/configuration/spec.yaml, win32_event_log/datadog_checks/win32_event_log/data/conf.yaml.example
Added a small note in the template conf.yaml to document that event filtering based on id can only be up to 20 ids long. If it's any longer, the API we query will return an error and therefore cause the check to also report and error.
Escalation
Didn't see any mention of this option in the main docs, so decided not to make any changes there.
=> Document the max number of IDs that can be used for filtering per instance

cassandra/datadog_checks/cassandra/config_models/defaults.py, datadog_checks_dev/datadog_checks/dev/tooling/specs/configuration/consumers/model.py, datadog_checks_dev/tests/tooling/configuration/consumers/model/test_defaults.py, elastic/datadog_checks/elastic/config_models/defaults.py, envoy/datadog_checks/envoy/config_models/defaults.py, go_expvar/datadog_checks/go_expvar/config_models/defaults.py, haproxy/datadog_checks/haproxy/config_models/defaults.py, istio/datadog_checks/istio/config_models/defaults.py, kafka/datadog_checks/kafka/config_models/defaults.py, kafka_consumer/datadog_checks/kafka_consumer/config_models/defaults.py, mysql/datadog_checks/mysql/config_models/defaults.py, network/datadog_checks/network/config_models/defaults.py, nfsstat/datadog_checks/nfsstat/config_models/defaults.py, nginx/datadog_checks/nginx/config_models/defaults.py, postgres/datadog_checks/postgres/config_models/defaults.py, riakcs/datadog_checks/riakcs/config_models/defaults.py, sap_hana/datadog_checks/sap_hana/config_models/defaults.py, sonarqube/datadog_checks/sonarqube/config_models/defaults.py, spark/datadog_checks/spark/config_models/defaults.py, tomcat/datadog_checks/tomcat/config_models/defaults.py, varnish/datadog_checks/varnish/config_models/defaults.py, vault/datadog_checks/vault/config_models/defaults.py, vsphere/datadog_checks/vsphere/config_models/defaults.py, win32_event_log/assets/configuration/spec.yaml, win32_event_log/datadog_checks/win32_event_log/config_models/defaults.py, win32_event_log/datadog_checks/win32_event_log/data/conf.yaml.example, wmi_check/datadog_checks/wmi_check/config_models/defaults.py, yarn/datadog_checks/yarn/config_models/defaults.py
Use `display_default` instead of `default` when validating models.
In kafka_consumer check, default for the optional `kafka_client_api_version` is `None` but an example value is shown as `2.3.0`. However, the generated `defaults.py` currently takes the value from `default` > then `example` > then falls back to NO_DEFAULT aka `<KAFKA_CLIENT_API_VERSION>`
- `spec.yaml` - https://github.com/DataDog/integrations-core/blob/7.30.x/kafka_consumer/assets/configuration/spec.yaml
```
- name: kafka_client_api_version
...
value:
type: string
example: "2.3.0"
display_default: null
```
- `conf.yaml.example` - https://github.com/DataDog/integrations-core/blob/7.30.x/kafka_consumer/datadog_checks/kafka_consumer/data/conf.yaml.example#L56-L65
```
...
```
- `defaults.py`
- Expected: 
```
def …
```
=> Use `display_default` as a fallback for `default` when validating config models

win32_event_log/datadog_checks/win32_event_log/config_models/validators.py
Fixes `AttributeError: 'NoneType' object has no attribute 'dict'` when no `filters:` are set.
AGENT-6573
Workaround is to set `filters: {}` in the config file
=> Fix AttributeError when filters are not set

php_fpm/datadog_checks/php_fpm/php_fpm.py
Sets the `timeout` for socket-based connections.
Otherwise, the check will run for a very long timeout seemingly hung.
AGENT-6435
- `DEFAULT_TIMEOUT` was not being used and should actually default to 10 based on the config_models
=> Set timeout for socket connection

kubernetes_state/datadog_checks/kubernetes_state/kubernetes_state.py, kubernetes_state/tests/test_kubernetes_state.py
Adds `kube_job` tag, it takes the value of `job_name`.
Match what the tag key used by the tagger
fixes: https://github.com/DataDog/helm-charts/issues/327
=> Add kube_job tag to job metrics

iis/assets/dashboards/iis_overview.json
Changes the query of the Log Stream widget on the iis overview dashboard from "iis" to source:iis.
The log stream widget on this dashboard currently queries "iis" but it should query source:iis. Since there is an OOTB integration pipeline for IIS, any formally recognized IIS logs will have the source:iis facet and will not necessarily have "iis" free text in the message attribute of the log. source:iis is a better query.
=> changelog/no-changelog log stream widget on iis overview dashboard should query source:iis

snmp/tests/test_e2e_core.py
Requires agent image with https://github.com/DataDog/datadog-agent/pull/8613 for tests to pass
Add test for SNMP v1 with oid batch size of 1
https://github.com/DataDog/datadog-agent/pull/8613
=> Add test for SNMP v1 with oid batch size of 1

snmp/tests/test_e2e_core.py
Fix lint issue with assert_apc_ups_metrics
The issue has been cause by the merge of those two PR at same moment:
- https://github.com/DataDog/integrations-core/pull/9765
- https://github.com/DataDog/integrations-core/pull/9687
Leading to a merged state with lint error and duplicate code. This PR is fixing that.
=> Fix merge issue with assert_apc_ups_metrics

datadog_checks_base/datadog_checks/base/utils/db/query.py, datadog_checks_base/tests/test_db.py, ibm_i/assets/configuration/spec.yaml, ibm_i/datadog_checks/ibm_i/check.py, ibm_i/datadog_checks/ibm_i/config_models/defaults.py, ibm_i/datadog_checks/ibm_i/config_models/instance.py, ibm_i/datadog_checks/ibm_i/config_models/validators.py, ibm_i/datadog_checks/ibm_i/data/conf.yaml.example, ibm_i/datadog_checks/ibm_i/queries.py, ibm_i/datadog_checks/ibm_i/query_script.py, ibm_i/tests/test_ibm_i.py
Use a long-running script that performs queries on the IBM i system on behalf of the IBM i check.
The check communicates with the process through its `stdin`, `stdout` and `stderr` file descriptors.
Prevent the check from hanging if the IBM i driver hangs.
- Originally, I wanted to have a query script that would initialize the connection, do one query then terminate. However, that’s not possible because some of the metrics we get are statistics IBM i gives us as a diff between two queries (within the same connection). Resetting the connection after each query leads IBM i to return 0 or None for these stats. This is why I opted for a long-running script that would maintain the connection, and which would communicate with the Agent check to get queries and return results.
- I tested this …
=> Work around timeout issues in IBM i driver

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/config.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/dep.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/models.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/readmes.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/recommended_monitors.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/saved_views.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/service_checks.py, datadog_checks_dev/datadog_checks/dev/tooling/testing.py
Changing `datadog_checks_dev` or `datadog_checks_base` can affect other integration, like config spec.
This PR updates the `changed` behaviour for some validation command, to validate every check when `datadog_checks_base` or `datadog_checks_dev` is changed.
=> Validate all integrations for base and dev updates

vsphere/datadog_checks/vsphere/config.py, vsphere/tests/conftest.py
By default, `rest_api_options` is uncommented with no option in the configuration example file, so it's parsed as `rest_api_options: None`, and fails when updating the default dict.
Support
=> Check if rest_api_options is empty

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/licenses.py, datadog_checks_dev/datadog_checks/dev/tooling/utils.py, postgres/LICENSE-3rdparty-extra.csv
Updates the `validate license` command to add the ability for integrations to have 3rd party licenses which are not pulled directly from the requirements file and the origin is not PyPI.
https://github.com/DataDog/integrations-core/pull/9786
To test, add a `LICENSE-3rdparty-extra.csv` to the directory of any check. See https://github.com/DataDog/integrations-core/pull/9786 for an example.
=> Allow extra 3rd party licenses 

postgres/assets/configuration/spec.yaml, postgres/datadog_checks/postgres/config.py, postgres/datadog_checks/postgres/config_models/defaults.py, postgres/datadog_checks/postgres/config_models/instance.py, postgres/datadog_checks/postgres/config_models/validators.py, postgres/datadog_checks/postgres/data/conf.yaml.example, postgres/datadog_checks/postgres/postgres.py, postgres/metadata.csv, postgres/tests/test_unit.py
Adds a metric that reports the WAL file age in seconds
You can test in the E2E env by adding the following block to dd environment:
```
E2E_METADATA = {
'docker_volumes': ['{}/test_data_dir:/test_data_dir/data'.format(os.path.join(HERE, 'compose'))],
}
...
with docker_run(os.path.join(HERE, 'compose', 'docker-compose.yaml'), conditions=[WaitFor(connect_to_pg)]):
yield e2e_instance, E2E_METADATA
```
and adding a corresponding volume in docker-compose.yaml:
`- ./test_data_dir:/var/lib/postgresql/data/
`
=> Collect WAL file age metric

ibm_db2/datadog_checks/ibm_db2/ibm_db2.py, ibm_db2/tests/test_unit.py
Certain queries are not available on IBM Db2 versions <11.1. This PR makes sure to log a warning message but continue running other queries. This behavior is similar to the DB manager.
=> Log message for invalid queries

datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/labels.py, datadog_checks_base/tests/openmetrics/test_options.py, datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/openmetrics.yaml, kong/datadog_checks/kong/data/conf.yaml.example
1. Change default behavior of `share_labels` to v1 `label_joins` i.e. cache previous payloads
2. Add option `cache_shared_labels` to prevent inconsistences at the risk of potentially increased memory usage
Potential inconsistences are preferred over dependence on the order in which metrics are exposed in a payload
=> [OpenMetricsV2] Improve label sharing behavior

kube_controller_manager/assets/service_checks.json, kube_controller_manager/datadog_checks/kube_controller_manager/data/conf.yaml.example, kube_controller_manager/datadog_checks/kube_controller_manager/kube_controller_manager.py, kube_controller_manager/tests/test_kube_controller_manager.py, kube_scheduler/assets/configuration/spec.yaml, kube_scheduler/assets/service_checks.json, kube_scheduler/datadog_checks/kube_scheduler/data/conf.yaml.example, kube_scheduler/datadog_checks/kube_scheduler/kube_scheduler.py, kube_scheduler/tests/test_kube_scheduler_1_14.py
Adds `kube_scheduler.up` and `kube_controller_manager.up` service checks
for the Kube Scheduler and Kube Controller Manager, respectively. This
is to support the deprecation of some of the
`kube_apiserver_controlplane.up` service checks backed by the
ComponentStatus API. See
https://github.com/DataDog/datadog-agent/pull/8577 for more context.
=> Add service check for K8s API Server components

LICENSE-3rdparty.csv, postgres/LICENSE-3rdparty-extra.csv, postgres/datadog_checks/postgres/relationsmanager.py, postgres/metadata.csv, postgres/tests/test_relations.py
Adds a new postgres metric for estimated table bloat percentage 
https://wiki.postgresql.org/wiki/Show_database_bloat and https://github.com/bucardo/check_postgres/
=> Add metric for estimated table bloat percentage 

datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py
Some times builds fail because of networking issues, this adds a bit of resilience to that
```
Captured Output: master-py2: Pulling from datadog/agent-dev
5494627ba1b6: Pulling fs layer
5494627ba1b6: Download complete
5494627ba1b6: Pull complete
error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/83/83aa360a39522336a3c3c3be7e96e4f6508525589605e45782374fbb6b135c1a/data?verify=1627982392-gwat0LEHC9EDkruf6TQh87VCw8k%3D: dial tcp 104.18.124.25:443: i/o timeout
```
This does not help with the similar failures we get on `docker-compose` commands
=> Reattempt to download pull docker image

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, postgres/requirements.in
Ensure pin for continued Python 2 support
=> Upgrade `psycopg2` on Python 3

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, postgres/requirements.in
Reverts DataDog/integrations-core#9590.
It is breaking the datadog-agent build because of the missing `pg_config`
=> Revert "Upgrade `psycopg2` on Python 3"

tcp_check/assets/configuration/spec.yaml, tcp_check/datadog_checks/tcp_check/config_models/defaults.py, tcp_check/datadog_checks/tcp_check/config_models/instance.py, tcp_check/datadog_checks/tcp_check/data/conf.yaml.example, tcp_check/datadog_checks/tcp_check/tcp_check.py, tcp_check/tests/test_tcp_check.py
Re-resolves the IP address of a given host after a set duration regardless if the previous IP still works.
AGENT-6539
=> Re-resolve IP after a set duration

.github/workflows/release-hash-check.yml
Previously the `git diff` command was used to list all modified files between a PR and origin/master.
The issue with that approach is if another releaser releases something in between, his .in-toto file will show up in the diff as well.
To fix, we use `git merge-base` to find the last common ancestor between the tested branch and master, in order to only list `.in-toto` files **modified** by that PR.
Successfully tested here: https://github.com/DataDog/integrations-core/pull/9851
=> Improve release-hash-check modified files detection

postgres/assets/configuration/spec.yaml, postgres/datadog_checks/postgres/config.py, postgres/datadog_checks/postgres/config_models/defaults.py, postgres/datadog_checks/postgres/data/conf.yaml.example
This PR updates the Postgres integration to set a default timeout of 5s on queries. Based on internal benchmarking, this should be a wide margin to ensure we mitigate performance impact in the worst case scenarios, while still ensuring customers have metrics.
Datadog strives to provide high fidelity telemetry while guaranteeing the lowest possible performance impact by the agent. While the integrations do not run any queries that should exceed a 5s execution time, there are certain failure scenarios on databases that could result in all queries being slow and consuming more resources than a monitoring tool should–especially on a loaded database.
I believe the biggest risk in changing this behavior is the impact on long-running custom queries. However the benefit to risk ratio is very …
=> Set a default statement timeout for postgres to 5s

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/validate_snmp_profiles.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/validators/__init__.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/validators/utils.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/validators/validator.py
Adds a Validator to validate that there are no sysobjectids duplicates in the profiles.
To not have multiple sysobjectid defined in different profiles
=> [NDM] Validate SysObjectID Consistency

amazon_msk/assets/dashboards/overview.json, databricks/assets/dashboards/databricks_overview.json, elastic/assets/dashboards/overview.json, jmeter/assets/dashboards/JMeterOverview.json, kubernetes/assets/dashboards/kubernetes_jobs.json, kubernetes/assets/dashboards/kubernetes_pods.json, mcache/assets/dashboards/memcached_screenboard.json, mysql/assets/dashboards/overview-screenboard.json, nginx/assets/dashboards/plus_overview.json, openldap/assets/dashboards/openldap_overview.json, postgres/assets/dashboards/postgresql_screenboard_dashboard.json, presto/assets/dashboards/overview.json, redisdb/assets/dashboards/overview.json, tomcat/assets/dashboards/overview.json
Update the json of integration dashboards with the proper is_column_break layout properties
layout validation for dashboard widgets and groups have changed such that just `{is_column_break: true}` is no longer considered a valid layout. this is adding full layout properties for widgets with this.
=> [dashboard] update integration json with is_column_break properties

gitlab/assets/service_checks.json
Readiness check returns CRITICAL if gitlab instance is _unable_ to accept traffic
Fixes a typo in the readme, reflecting that check will return CRITICAL if instance is _unable_ to accept traffic
Readme's should be accurate
=> fix Readiness check's description

datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/validator.py
Adds a `manifest.json` ddev validator to check whether the `supported_os` field is present for 
python checks or checks that have a logs integration.
=> Add manifest validator for `supported_os` field

rabbitmq/assets/configuration/spec.yaml, rabbitmq/datadog_checks/rabbitmq/config_models/defaults.py, rabbitmq/datadog_checks/rabbitmq/data/conf.yaml.example
https://github.com/DataDog/integrations-core/pull/7451
=> Fix documented default value of `use_legacy_auth_encoding`

datadog_checks_base/datadog_checks/base/stubs/datadog_agent.py, datadog_checks_base/datadog_checks/base/utils/db/utils.py, datadog_checks_base/tests/base/utils/db/test_util.py
If a hostname is greater than or equal to 64 characters, `socket.gethostbyname()` raises UnicodeError and fails to initialize the mysql check. 
Therefore, in `datadog_checks.base.utils.db.utils resolve_db_host` has been changed to handle UnicodeError as an exception.
To fixes #9776
=> Fix database checks' failure caused by a hostname that is too long

ibm_mq/datadog_checks/ibm_mq/connection.py, ibm_mq/datadog_checks/ibm_mq/ibm_mq.py, ibm_mq/tests/test_ibm_mq_unit.py
Add ability to disambiguate, see:
```
2021-08-11 10:29:17 UTC | CORE | DEBUG | (pkg/collector/python/datadog_agent.go:126 in LogMessage) | - | (connection.py:53) | connecting without a username and password
```
vs:
```
2021-08-11 10:29:23 UTC | CORE | DEBUG | (pkg/collector/python/datadog_agent.go:126 in LogMessage) | ibm_mq:f53004b96cb7511a | (ibm_mq.py:86) | Could not retrieve ibm_mq version info
```
=> Use dedicated instance logger for connection messages

datadog_checks_base/datadog_checks/base/utils/db/utils.py, postgres/datadog_checks/postgres/config.py, postgres/datadog_checks/postgres/postgres.py, postgres/datadog_checks/postgres/statement_samples.py, postgres/datadog_checks/postgres/statements.py, postgres/tests/test_pg_integration.py, postgres/tests/test_statements.py
This change adds the correct resolved hostname to metrics and the service check when DBM is enabled. At some point, we should apply this change to all installations (not just when dbm is enabled), but that will require a more detailed rollout plan since that is potentially breaking to a small number of customers.
Currently if an agent is monitoring a remote host such as an Aurora, RDS, or CloudSQL host, only the agent hostname is available as the `host:` tag. The agent host tag has limited usefulness as an identifier because a single agent is often used to monitor many remote hosts. This change replaces the agent hostname with the remote host (such as `mydb.cfxxae8cilce.us-east-1.rds.amazonaws.com`).
=> Send the correct hostname with postgres metrics when DBM is enabled

datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/openmetrics_legacy.yaml, openmetrics/datadog_checks/openmetrics/data/conf.yaml.example
The example we share for the metrics: parameter is currently configured wrong. There needs to be a space between the original metric name, and the renamed version or the agent will skip collection.
=> Update `metrics` param in OpenMetrics's conf.yaml

datadog_checks_base/datadog_checks/base/utils/db/query.py, datadog_checks_base/tests/base/utils/db/test_query_manager.py
Extends `QueryManager` query type to allow mappings.
Needed for IBM i integration, see #9720.
As of now it should be a no-op.
=> Extend `QueryManager` query type

mysql/datadog_checks/mysql/mysql.py, mysql/datadog_checks/mysql/statement_samples.py, mysql/datadog_checks/mysql/statements.py, mysql/tests/test_mysql.py
Postgres version of the PR: https://github.com/DataDog/integrations-core/pull/9865
This change adds the correct resolved hostname to metrics and the service check when DBM is enabled. At some point, we should apply this change to all installations (not just when dbm is enabled), but that will require a more detailed rollout plan since that is potentially breaking to a small number of customers.
Currently if an agent is monitoring a remote host such as an Aurora, RDS, or CloudSQL host, only the agent hostname is available as the `host:` tag. The agent host tag has limited usefulness as an identifier because a single agent is often used to monitor many remote hosts. This change replaces the agent hostname with the remote host (such as `mydb.cfxxae8cilce.us-east-1.rds.amazonaws.com`).
=> Send the correct hostname with metrics when DBM is enabled

mysql/datadog_checks/mysql/statements.py, mysql/tests/test_statements.py
This update adds fetching of the special row in `events_statements_by_digest` that has null `digest_text` (and `digest`, `schema`). This [happens when the table is full](https://dev.mysql.com/doc/refman/5.7/en/performance-schema-statement-summary-tables.html#statement-summary-tables-aggregation) and has reached the limit set in [performance_schema_digests_size](https://dev.mysql.com/doc/refman/5.7/en/performance-schema-system-variables.html#sysvar_performance_schema_digests_size). 
We'd like to provide visibility on when `events_statements_by_digest` and enable users to know that they might be losing queries. 
I added unit testing of the normalization that validates that we handle a `None` digest_text correctly. The test that validates we actually fetch the null row was done manually by …
=> Add fetching of null row in events_statements_by_digest

ibm_mq/assets/configuration/spec.yaml, ibm_mq/datadog_checks/ibm_mq/collectors/channel_metric_collector.py, ibm_mq/datadog_checks/ibm_mq/collectors/metadata_collector.py, ibm_mq/datadog_checks/ibm_mq/collectors/queue_metric_collector.py, ibm_mq/datadog_checks/ibm_mq/config.py, ibm_mq/datadog_checks/ibm_mq/config_models/defaults.py, ibm_mq/datadog_checks/ibm_mq/config_models/instance.py, ibm_mq/datadog_checks/ibm_mq/data/conf.yaml.example, ibm_mq/datadog_checks/ibm_mq/ibm_mq.py
Some network topologies may require longer waits
- setting https://github.com/dsuch/pymqi/blob/084ab0b2638f9d27303a2844badc76635c4ad6de/code/pymqi/__init__.py#L2799
- another example of adding such an option https://github.com/DataDog/integrations-core/pull/8601/files
=> Add `timeout` option

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, openstack_controller/datadog_checks/openstack_controller/api.py, openstack_controller/datadog_checks/openstack_controller/openstack_controller.py, openstack_controller/requirements.in, openstack_controller/tests/terraform/main.tf, openstack_controller/tests/test_simple_api.py
Bumping the openstacksdk dependencies to the latest on py2 and py3.
By bumping to 0.25.0+, the openstacksdk added the `get_server_diagnostics` method, we take that opportunity to fill the "NotImplementedException".
By bumping to 0.50.+ (py3 only), the openstacksdk added the `get_hypervisor_uptime` method. We take that opportunity to update the "NotImplementedException" only on py3.
=> Bump openstacksdk and add missing metrics

.github/workflows/validations.yaml, couchbase/datadog_checks/couchbase/couchbase.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/agent_signature.py, datadog_checks_dev/datadog_checks/dev/tooling/utils.py
This PR continues to add validations to Github actions workflow. This PR adds `ddev validate legacy-signature` validation.
This PR is a follow up to https://github.com/DataDog/integrations-core/pull/9868
When a PR contains a check using an outdated agent signature, the validations workflow should annotate the line with an error message and suggestion.
=> Add annotations to legacy agent signature

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/requirements.in, snowflake/requirements.in
Pin snowflake connector and requests. `requests==2.25.1` is not compatible with `snowflake==2.1.3,` and `snowflake >2.1.3` is not compatible with Python 2.
https://github.com/snowflakedb/snowflake-connector-python/issues/324
https://github.com/DataDog/datadog-agent/issues/8895
=> Pin snowflake-connector and requests

cisco_aci/datadog_checks/cisco_aci/api.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/validate_snmp_profiles.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/fixed_cards_mover.py, harbor/datadog_checks/harbor/harbor.py, ibm_mq/datadog_checks/ibm_mq/collectors/metadata_collector.py, ibm_mq/datadog_checks/ibm_mq/config.py, mapr/datadog_checks/mapr/mapr.py, ssh_check/datadog_checks/ssh_check/ssh_check.py, vsphere/datadog_checks/vsphere/legacy/vsphere_legacy.py
This PR fixes typos in code caught by codespell
https://github.com/DataDog/integrations-core/pull/9902
=> Fix typos in log lines

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/requirements.in, snowflake/requirements.in
The snowflake bump does not build easily on SUSE, it requires additional dependencies for building the library.
For the time being we revert the snowflake bump and we set the requests version back to what it was on 7.29.0
=> Revert request bump

snowflake/tests/common.py, snowflake/tests/conftest.py, snowflake/tests/mock_snowflake_connector_python/setup.py, snowflake/tests/mock_snowflake_connector_python/snowflake/__init__.py, snowflake/tests/mock_snowflake_connector_python/snowflake/connector.py, snowflake/tests/mock_snowflake_connector_python/snowflake/tables.py, snowflake/tests/test_e2e.py, snowflake/tests/test_snowflake.py, snowflake/tests/test_unit.py, snowflake/tox.ini
Add mocks similar to https://github.com/DataDog/integrations-core/pull/9398
This is part 1 of 2, in near future monkeypatch methods of the `snowflake-connector-python` library rather than shadowing the entire library
=> Add E2E tests with fixture data

kubernetes/assets/dashboards/kubernetes_statefulsets.json, kubernetes/manifest.json
Add OOTB dashboard for sts, which is mostly based on the daemonsets one.
The dashboard can be seen at: https://app.datadoghq.com/dashboard/ky3-64z-ww8/kubernetes-statefulsets-overview?from_ts=1628062894113&to_ts=1628066494113&live=true
**Steps I did**
```
ddev meta dash export "https://app.datadoghq.com/dashboard/ky3-64z-ww8/kubernetes-statefulsets-overview" kubernetes
```
Adding support to sts for orchestrator-explorer
Right now it misses `statefulset.count`, the metric currently does not exist.
The plan is to release this OOTB without and return and add this again after the new agent release containing the count:
https://github.com/DataDog/integrations-core/pull/9813
=> Add StatefulSets OOTB dashboard

ibm_mq/assets/configuration/spec.yaml, ibm_mq/datadog_checks/ibm_mq/collectors/queue_metric_collector.py, ibm_mq/datadog_checks/ibm_mq/config.py, ibm_mq/datadog_checks/ibm_mq/data/conf.yaml.example, ibm_mq/datadog_checks/ibm_mq/ibm_mq.py
Autodiscovery can autodiscover dynamic queues that may disappear on later runs causing errors on the check.
Also because we were just adding discovered queues without removing deleted ones this also fixes a memory leak
=> Do not store previously discovered queues

oracle/metadata.csv
Updates `oracle.tablespace.in_use,gauge` to percent instead of fraction.
The value is a percentage, not a fraction:
https://docs.oracle.com/database/121/REFRN/GUID-FE479528-BB37-4B55-92CF-9EC19EDF4F46.htm#REFRN23496
=> Fix `oracle.tablespace.in_use` metric unit

process/README.md
This is causing the code example in step 1 to be broken on the docs site: https://docs.datadoghq.com/integrations/process/#configuration
=> [documentation] fixes broken spacing in the conf.yaml example

postgres/datadog_checks/postgres/statement_samples.py, postgres/datadog_checks/postgres/statements.py, postgres/tests/test_statements.py
This adds the agent version to postgres database monitoring payloads (query metrics, query samples and full query text events).
Including the agent version in the database monitoring payloads will be useful information to improve visibility when looking at behavior of database monitoring features related to agent functionality.
=> Add agent version to postgres database monitoring payloads

mysql/datadog_checks/mysql/statement_samples.py, mysql/datadog_checks/mysql/statements.py, mysql/tests/test_statements.py
This adds the agent version to mysql database monitoring payloads (query metrics, query samples and full query text events). 
Including the agent version in the database monitoring payloads will be useful information to improve visibility when looking at behavior of database monitoring features related to agent functionality.
=> Add agent version to mysql database monitoring payloads

datadog_checks_base/tests/fixtures/prometheus/ksm.txt, kubernetes_state/CHANGELOG.md, kubernetes_state/datadog_checks/kubernetes_state/kubernetes_state.py, kubernetes_state/metadata.csv, kubernetes_state/tests/fixtures/prometheus.txt, kubernetes_state/tests/test_kubernetes_state.py
Adds `kubernetes_state.statefulset.count` based on generations, which is based on the same code and methods that `deployment.count` is using 
OOTB sts dashboard
=> Add `kubernetes_state.statefulset.count` metric

datadog_checks_base/datadog_checks/base/stubs/aggregator.py
This PR is Part 2 of 2. See Part 1: https://github.com/DataDog/integrations-core/pull/9888
Service checks with status OK should no longer report any messages. This PR adds a check in the aggregator to throw an exception for future integrations.
This PR will be merged in once the first part PR is merged in.
=> Raise exception during tests for OK service checks sent with messages

postgres/assets/configuration/spec.yaml, postgres/datadog_checks/postgres/config.py, postgres/datadog_checks/postgres/config_models/instance.py, postgres/datadog_checks/postgres/data/conf.yaml.example, postgres/datadog_checks/postgres/statement_samples.py, postgres/datadog_checks/postgres/statements.py
Updates the Postgres integration config field `quantize_sql_tables` to `replace_digits` to reflect the changes being made in the datadog-agent. More information can be found in this PR: https://github.com/DataDog/datadog-agent/pull/8860
=> Update postgres obfuscator options config

mysql/assets/configuration/spec.yaml, mysql/datadog_checks/mysql/config.py, mysql/datadog_checks/mysql/config_models/instance.py, mysql/datadog_checks/mysql/data/conf.yaml.example, mysql/datadog_checks/mysql/statement_samples.py, mysql/datadog_checks/mysql/statements.py
Updates the MySQL integration config field `quantize_sql_tables` to `replace_digits` to reflect the changes being made in the datadog-agent. More information can be found in this PR: https://github.com/DataDog/datadog-agent/pull/8860
=> Update mysql obfuscator options config

marklogic/datadog_checks/marklogic/constants.py, marklogic/tests/fixtures/cluster-query.yaml, marklogic/tests/test_parsers.py
Supports parsing the resource type `clusters`
A Marklogic instance can have foreign clusters, and the integration breaks when you have them
https://docs.marklogic.com/REST/GET/manage/v2/clusters
We currently don't provide any metrics for clusters, so this is to prevent the parser from breaking, not to enable more metrics.
=> Support clusters resource type

datadog_checks_dev/datadog_checks/dev/kind.py
Adds support for passing in a configuration file when creating a kind cluster in E2E.
=> Add support for kind config

datadog_checks_dev/datadog_checks/dev/kind.py
Fix kind_config FR. `--config` should not be included in create command if it's None.
CI failures seem to be related https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=73010&view=logs&j=519bd84d-28fd-598c-db49-0d219af79ef0&t=8d8170c7-f175-5c28-3510-d1de6e6f4791&l=82
=> Do not to pass kind config if it's None

datadog_checks_base/datadog_checks/base/stubs/aggregator.py
Reverts DataDog/integrations-core#9898 until https://github.com/DataDog/jmxfetch/pull/369 is merged, otherwise CI keeps failing for Hazelcast and Ignite.
=> Revert "Raise exception during tests for OK service checks sent with messages"

tomcat/tests/compose/docker-compose.yml
Image for 9.0 has been recently updated to 9.0.52 which breaks e2e due to configuration issues. This PR pins it to the previously passing version
=> Pin tomcat docker version

tcp_check/datadog_checks/tcp_check/tcp_check.py
Introduced in https://github.com/DataDog/integrations-core/pull/9644
Not a serious concern since there is still an exception being raised & logged
=> Elevate log level for failed connections

ibm_mq/datadog_checks/ibm_mq/collectors/stats_collector.py
Prevents:
```
During handling of the above exception, another exception occurred:
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 996, in run
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/ibm_mq/ibm_mq.py", line 67, in check
self.stats_collector.collect(queue_manager)
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/ibm_mq/collectors/stats_collector.py", line 76, in collect
queue.close()
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/pymqi/__init__.py", line 2079, in close
raise PYIFError('not open')
pymqi.PYIFError: PYMQI Error: not open
```
=> Add try-catch on queue closure

vsphere/datadog_checks/vsphere/vsphere.py, vsphere/tests/fixtures/host_tags_values.json, vsphere/tests/fixtures/topology.json, vsphere/tests/mocked_api.py
The runtime host on which a VM is running might not be monitorable in some cases, in particular when permissions are missing. This PR gracefully handles such cases.
=> Fix crash when some permissions are missing

ibm_mq/tests/test_ibm_mq_int.py, ibm_mq/tests/test_ibm_mq_unit.py
Adds a service check test for when there are no messages available, see https://www.ibm.com/docs/en/ibm-mq/9.2?topic=codes-2033-07f1-rc2033-mqrc-no-msg-available
QA for https://github.com/DataDog/integrations-core/pull/9703
=> Add test for unknown service check status

vsphere/tests/common.py
Adds the config option `empty_default_hostname: True` to the `dd_environment`
`empty_default_hostname` is a required config option now
=> Add empty_default_hostname to dd_environment

mysql/datadog_checks/mysql/statement_samples.py, mysql/tests/test_statements.py
Cache explain failures for queries that fail to be explained via any explain strategy (i.e. if the query is invalid or has incorrect syntax) in order to ensure we don't keep trying to re-explain them and generate unnecessary database error logs in the process.
Other minor changes:
* simplify reporting of the `dd.mysql.query_samples.error` debug metric by moving it to a single spot and reporting directly from all of the `collection_errors` that get sent with the intake
* new `dd.mysql.db.error` debug metric to clearly distinguish real database errors from cached errors. If the caching is working correctly then real database errors should stay low even if the cached errors are high.
* remove `DBExplainError.procedure_strategy_requires_default_schema` as it's not a real error since it's not …
=> Avoid re-explaining queries that cannot be explained

datadog_checks_dev/datadog_checks/dev/plugin/tox.py
Reverts DataDog/integrations-core#10005 as the issue has been fixed in the latest release
=> Revert "Pin regex"

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/testable.py
This PR fixes a bug where the command fails when the PR body is empty.
The DMB team wasn't included in the team options for assigning cards.
Be sure to
=> Fix bug when PR body is empty and include DBM team to selector

openstack_controller/datadog_checks/openstack_controller/openstack_controller.py
Fixes log message to refer to openstack_controller instead of openstack
next we can do runtime config validation
=> Update log message

datadog_checks_dev/datadog_checks/dev/tooling/templates/terraform/gke_config.tf, datadog_checks_dev/datadog_checks/dev/tooling/templates/terraform/providers.tf
Removes unneeded lines from the terraform templates 
- `openstack_controller` is the only check that uses terraform for testing now, and it does not contain the `google_container_cluster.gke_cluster` resource so it breaks with this line
- Version constraints inside provider configuration blocks are deprecated now
=> Fix terraform templates

.github/workflows/validations.yaml, crio/assets/service_checks.json, datadog_checks_dev/datadog_checks/dev/tooling/annotations.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/service_checks.py
Instead of repeating multiple annotations, annotate messages gathered in display_queue.
Simplify annotations and avoid repetitive code
=> Annotating display_queue

ibm_mq/datadog_checks/ibm_mq/collectors/queue_metric_collector.py
When discovering queues of types LOCAL and MODEL, the check was emitting a warning if there was no LOCAL queue while it should wait for MODEL queues first and only emit a warning once we're sure that no queue at all matches the given pattern.
=> Stop emitting incorrect queue warning

gitlab_runner/tests/compose/docker-compose.yml, gitlab_runner/tox.ini
Use same version as gitlab runner
Updates testing version as current version is too old
=> gitlab-runner bump image for testing

consul/tests/common.py
adds back assertion for `consul.raft.leader.lastContact.count`
https://github.com/DataDog/integrations-core/pull/9382/files#diff-2518f4bfe13b0ca6ea42e590472f9242a1be5682fb47beb908ad10eecd995785L41 removed it
=> Assert raft metric

datadog_checks_base/datadog_checks/base/stubs/datadog_agent.py
Set default value of `disable_unsafe_yaml` of the stub datadog agent, so it's the same default value as in the real agent https://github.com/DataDog/datadog-agent/blob/4452508ba1985be3a01320ded1faccb11dc33991/pkg/config/config.go#L296
=> Set disable_unsafe_yaml default value

avi_vantage/tests/conftest.py
Make `check` command work OOTB
=> Fix E2E environment to start with the proper instance

tomcat/assets/dashboards/overview.json
- Fix note widget order for the tomcat dashboard
=> Fix note widget order for the tomcat dashboard

snmp/tests/conftest.py, snmp/tests/test_check.py, snmp/tests/test_unit.py
Fix unit tests that are failing since this commit: https://github.com/DataDog/integrations-core/commit/b1b9ace9099569a5217e6d509152965b052ab723
This PR will make sure to open files in "wb" mode so that the yaml lib can serialize Yaml even if we use the C safeloader in tests.
Repair failing tests.
=> [SNMP][tests] open files in 'wb' mode when serialising yaml

datadog_checks_base/datadog_checks/base/ddyaml.py
Allow integrations to use a non-default YAML loader and dumper
Inside an integration
```python
import yaml
...
class CustomCheck(AgentCheck):
...
def func(self):
yaml.load(mystring, Loader=yaml.SafeLoader)
```
Needed for #9815 to use the python safe loader instead of the C one.
This is changing the behaviour of the undocumented `disable_unsafe_yaml` agent option (which is true by default).
Before:
* If true, monkey patching, change default loader to CSafeLoader or SafeLoader (same with dumper)  and forbid non-default loader/dumper use
* If false, no monkey patch
After:
* If true, monkey patching, change default loader to CSafeLoader or SafeLoader (same with dumper) and print a debug log line if using a different loader/dumper
* If false no monkey patch
=> Allow non-default yaml loader and dumper

datadog_checks_dependency_provider/CHANGELOG.md, datadog_checks_dependency_provider/MANIFEST.in, datadog_checks_dependency_provider/README.md, datadog_checks_dependency_provider/datadog_checks/__init__.py, datadog_checks_dependency_provider/datadog_checks/datadog_checks_dependency_provider/__about__.py, datadog_checks_dependency_provider/datadog_checks/datadog_checks_dependency_provider/__init__.py, datadog_checks_dependency_provider/datadog_checks/datadog_checks_dependency_provider/data/conf.yaml.example, datadog_checks_dependency_provider/setup.py
Adds a check that exists solely to provide a place to define dependencies for integrations that do not reside in `integrations-core`.
We have need to ship dependencies for select third party integrations, starting with [foundationdb](https://github.com/DataDog/integrations-extras/pull/950).
We could add dependencies within our builds like we do for [snowflake-connector-python](https://github.com/DataDog/datadog-agent/blob/main/omnibus/config/software/snowflake-connector-python-py3.rb).
Cons:
- Another instance where we have to specially handle transient dependencies
- If another integration starts depending on it there is no CI validation for version mismatches
- Ruby code is generally more difficult to work with for contributors
We could add dependencies directly to the [frozen …
=> Add `datadog_checks_dependency_provider` check

datadog_checks_dev/datadog_checks/dev/tooling/release.py
```
Updating the Agent requirements file... Traceback (most recent call last):
File "C:\Users\ofek\AppData\Local\Programs\Python\Python38\Scripts\ddev-script.py", line 30, in <module>
sys.exit(load_entry_point('datadog-checks-dev', 'console_scripts', 'ddev')())
File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1137, in __call__
return self.main(*args, **kwargs)
File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1062, in main
rv = self.invoke(ctx)
File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1668, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "c:\users\ofek\appdata\local\programs\python\python38\lib\site-packages\click\c …
```
=> Update release tooling to support `datadog_checks_dependency_provider`

zk/datadog_checks/zk/zk.py, zk/tests/conftest.py, zk/tests/test_zk.py
Fixes an issue: https://github.com/DataDog/integrations-core/issues/9998 where base tags are not included with `zookeeper.instances.*` metrics.
=> Add base tags to `zookeeper.instances.*`

LICENSE-3rdparty.csv, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_dependency_provider/requirements.in
Required for https://github.com/DataDog/integrations-extras/pull/950
=> Add dependency `foundationdb` version `6.3.18`

pgbouncer/datadog_checks/pgbouncer/metrics.py, pgbouncer/datadog_checks/pgbouncer/pgbouncer.py, pgbouncer/metadata.csv, pgbouncer/tests/test_pgbouncer_integration_e2e.py
Add a new PGBouncer metric: max_client_conn
So we can compute a percent of client conn used:
(cl_active + cl_waiting) / max_client_conn
=> Add max_client_conn metric

datadog_checks_dev/datadog_checks/dev/tooling/dependencies.py
Currently this passes validation
```
CHECKS_BASE_REQ = 'datadog-checks-base>=4.2.0'
```
but this doesnt
```
CHECKS_BASE_REQ = "datadog-checks-base>=4.2.0"
```
This PR allows the second case to pass validation
=> Allow double quote on requirement

snowflake/datadog_checks/snowflake/check.py, snowflake/tests/test_snowflake.py
Added a test for critical service check when the service is down
Found we were appending snowflake prefix twice
=> Add test for critical service check and fix namespace

kubernetes/assets/dashboards/kubernetes_nodes.json
Fixes the "Memory utilization % per node" and "Memory utilization per node" widgets in the "Kubernetes Nodes Overview" dashboard.
Those widgets were using the metric `kubernetes.memory.usage_pct` to calculate the mem utilization % of a node. The formula was: `avg:kubernetes.memory.usage_pct{$cluster,$host} by {host}*100`. That's not correct because `memory_usage_pct` is calculated dividing the mem a pod is using by its memory limits. The memory limits are different for every pod, so we can't just average them.
This PR changes the formula and uses `system.mem.pct_usable` instead.
=> Fix mem usage % in Kubernetes nodes dashboard

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/requirements.in, snowflake/requirements.in
We are on the latest supported version for py2 so we can only bump on py3
=> Bump snowflake and requests for Py3

ecs_fargate/README.md
Update our recommended container image tag for `amazon/aws-for-fluent-bit` from `latest` to `stable`. 
Issue with the `latest` release
https://datadoghq.atlassian.net/browse/CONS-4175
=> Update fluent image tag recommendation to stable

datadog_checks_dev/datadog_checks/dev/tooling/testing.py
Fix https://github.com/DataDog/integrations-core/pull/9945 causing CI failures https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=74263&view=logs&j=b9b61b1e-e7ad-5a75-8bb3-f1445ef55317&t=f78518e6-9c2d-541b-f94c-8183303ec0e1
=> Add `latest` to the list of known environments to skip for default E2E

php_fpm/manifest.json
Adds a process signature for `php-fpm:` to the php-fpm integration per so we can autodetect this process.
Motivation
We want to update the integrations signature for php-fpm so we'd be able to autodetect them by matching a process command line.
=> [proc] add 'php-fpm:' to process signature

rabbitmq/manifest.json
Adds a process signature for `rabbitmq-server` to the `rabbitmq` integration per https://www.rabbitmq.com/rabbitmq-server.8.html so we can autodetect this process.
We want to update the integrations signature `rabbitmq` so we'd be able to autodetect them by matching a process command line.
@DataDog/processes
=> Add 'rabbitmq-server'  to process signature

snmp/datadog_checks/snmp/snmp.py, snmp/tests/test_check.py
Add autodiscovery_subnet tag to discovered_devices_count metric
- It's preferred to use autodiscovery_subnet instead of network tag since the later is used in some profiles
- Align with SNMP Corecheck autodiscovery impl (https://github.com/DataDog/datadog-agent/pull/8996)
Use autodiscovery config and check that the new tags is present.
=> Add autodiscovery_subnet tag to discovered_devices_count metric

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/generate_profile.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/translate_profile.py, datadog_checks_dev/datadog_checks/dev/tooling/constants.py
- Updates the `mib_source_url` to https://github.com/DataDog/mibs.snmplabs.com - which is our own fork of https://github.com/cisco-kusanagi/mibs.snmplabs.com
- https://github.com/etingof/pysnmp/issues/376
- https://github.com/inexio/mibs.snmplabs.com aka `http://mibs.thola.io/asn1/` also works but is also a fork of cisco-kusanagi/mibs.snmplabs.com
- https://github.com/projx/snmp-mibs (one we used after the down http://mibs.snmplabs.com)  has also been disabled
=> Update mib_source_url to our own fork of mibs.snmplabs.com

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/test.py
Support CI App product for E2E tests, like https://github.com/DataDog/integrations-core/pull/9124
=> Allow the use of ddtrace for E2E tests

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/constants.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/generate_profile.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/translate_profile.py
* Enable pysmi debug logs when debug logs are enabled
* Add `borrowers` to pysmi compiler, to let it fetch already compiled mibs when available in our repo 🎉 
This PR is based on https://github.com/DataDog/integrations-core/pull/9952
Some MIBs fail compilation because of bad formatting / values duplication. Already compiled MIBs are a safe way to let any customer create their profile from them
=> Add borrower and pysmi logs to MIB compiler

datadog_checks_base/datadog_checks/base/stubs/aggregator.py
This PR adds an exception when service checks output `OK` but also has a message. 
Do not merge this PR until https://github.com/DataDog/jmxfetch/pull/369 is merged.
=> Raise exception for OK service checks with messages

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/generate_profile.py
Fixing snmp profile generator, broken by my previous PR
* Download https://github.com/DataDog/mibs.snmplabs.com/blob/master/asn1/CISCO-UNIFIED-COMPUTING-TC-MIB
* Launch the generator on this file using 
```sh
ddev meta snmp generate-profile-from-mibs -i <path/to/CISCO-UNIFIED-COMPUTING-TC-MIB>
```
* Verify metrics are detected
* Launch the generator on this file using 
```sh
ddev meta snmp generate-profile-from-mibs -i -d <path/to/CISCO-UNIFIED-COMPUTING-TC-MIB>
```
* Verify logs from `pysmi` are in output
* Locally clone https://github.com/DataDog/mibs.snmplabs.com
* Launch the generator on this file using 
```sh
ddev meta snmp generate-profile-from-mibs -i <path/to/CISCO-UNIFIED-COMPUTING-TC-MIB> -s <path/to/mibs.snmplabs.com repo/asn1> -c <path/to/mibs.snmplabs.com repo/json>
```
* …
=> [ddev] instantiate borrowers in snmp profile generator

go_expvar/datadog_checks/go_expvar/go_expvar.py, go_expvar/tests/test_unit.py
Adds a more descriptive warning message when a path that is a dictionary such as memstats is provided
=> Add more descriptive warning message 

cloud_foundry_api/datadog_checks/cloud_foundry_api/cloud_foundry_api.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/http.py, voltdb/datadog_checks/voltdb/client.py
This PR warns on usage of `auth` or `header` in http wrapper. These are already handled and is redundant
Instead of iterating each line of a python file, perhaps we can just regex search?
=> Echo warning for unnecessary params used

datadog_checks_base/datadog_checks/base/utils/tls.py, datadog_checks_base/tests/base/utils/test_tls.py
Previously, the `TLSContextWrapper` was overriding the configured `tls_verify` value and forcing it to `True` if any of these configs were present, `tls_ca_cert`, `tls_cert`, `tls_private_key`, `tls_private_key_password` even if `tls_verify: false` is configured. This PR updates the override to only force `tls_verify: true` if `tls_ca_cert` is configured.
Customer support case
=> Fix TLSContextWrapper to not override tls_verify

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/changelog.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/release/show/changes.py, datadog_checks_dev/datadog_checks/dev/tooling/git.py
Adds `--exclude-branch` option for generating changelogs.
Generated API clients contain subtree from openapi-generator with full history.
=> Allow exclusion of specific branch for changelog generation

ambari/datadog_checks/ambari/ambari.py, ambari/tests/conftest.py, ambari/tests/test_ambari.py, ambari/tox.ini
Add barebones e2e test for ambari
=> Add e2e test for ambari

aerospike/tox.ini, azure_iot_edge/tox.ini, cloud_foundry_api/tox.ini, datadog_checks_base/tox.ini, datadog_checks_dev/datadog_checks/dev/plugin/tox.py, glusterfs/tox.ini, ibm_mq/tox.ini, marklogic/tox.ini, mysql/tox.ini, postgres/tox.ini, rethinkdb/tox.ini, snmp/tox.ini, snowflake/tox.ini, voltdb/tox.ini, vsphere/tox.ini
With mypy's bump, stubs for third-party libraries are not included anymore. They can be installed automatically by using `--install-types` and `--non-interactive` flags but unfortunately some stubs are now py3 only while we use mypy in `--py2` mode.
To workaround the issue, this PR gives check the ability to pass additional style dependencies in each check tox.ini file.
=> Fix mypy tests

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/agent_reqs.py
The unreleased checks warning annotation is loud and unneeded. The integrations should be released as part of the release process and doesn't need to be warned.
=> Remove annotation for unnecessary warning

network/metadata.csv
Adds bunch of metrics that were missing from network check `metadata.csv` file even though they're actually submitted when `combine_connection_states` is set to `false`.
=> Add missing metrics to network check metatada file

kubernetes/assets/dashboards/kubernetes_dashboard.json, kubernetes/assets/dashboards/kubernetes_deployments.json, kubernetes/assets/dashboards/kubernetes_pods.json, kubernetes/assets/dashboards/kubernetes_statefulsets.json, kubernetes/assets/monitors/monitor_deployments_replicas.json, kubernetes/assets/monitors/monitor_statefulset_replicas.json
* use `kube_deployment` tag instead of `deployment`
* use `kube_stateful_set` tag instead of `statefulset`
* use `kube_daemon_set` tag instead of `daemonset`
* use `kube_replica_set` tag instead of `replicaset`
Remove the usage of depreacted tags in our official dashboards.
=> [kubernetes] Fix OOTB dashboards

.github/workflows/validations.yaml, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py
This PR refactors the `echo_failure` lines to use the display_queue to simplify the annotation.
=> Annotate metadata validation

containerd/metadata.csv, docker_daemon/metadata.csv
Document `docker.uptime` and `containerd.uptime` in the checks' metadata.
User noticed the docker uptime metric missing in our public docs.
=> Document containerd and docker uptime metrics in metadata

cri/metadata.csv
Adds cri.uptime metric (added several months ago) to the metadata.csv
=> [cri] Add cri uptime metric to metadata

kubernetes/assets/dashboards/kubernetes_daemonsets.json
In the Dashboard "Kubernetes DaemonSets Overview" the "Ready" query value widget was querying for the metric `kubernetes_state.daemonset.desired` rather than `kubernetes_state.daemonset.ready`. For reference too there is a "Desired" query value widget right next to it that is correctly querying for `kubernetes_state.daemonset.desired`.
This just fixes that metric in the query.
Wrong metric used in widget CONS-4201
=> Fix metric used in "Ready" query value widget

cilium/tests/conftest.py, datadog_checks_dev/datadog_checks/dev/kube_port_forward.py, istio/tests/conftest.py, linkerd/tests/conftest.py
Previously the port_forward by default support deployment only. This PR allows users to set a resource and resource name (e.g support service/pod/replicaset)
Supports collecting metrics from services (contributor use case)
=> Allow kube port forwarding to support any resource

snmp/tests/common.py, snmp/tests/conftest.py, snmp/tests/test_check.py, snmp/tests/test_e2e_agent_ad.py, snmp/tests/test_e2e_core.py, snmp/tests/test_e2e_core_vs_python.py, snmp/tests/test_e2e_python.py, snmp/tests/test_e2e_snmp_listener.py, snmp/tests/test_parsing.py, snmp/tests/test_profiles.py, snmp/tests/test_unit.py, snmp/tests/test_utils.py, snmp/tox.ini
Better naming for snmp envs
Previously called agent_ad env is related to snmp_listener, which is not suitable anymore since the previously called `python_ad` env is now also running SNMP corecheck e2e tests.
=> Better naming for snmp envs

kafka_consumer/assets/configuration/spec.yaml, kafka_consumer/datadog_checks/kafka_consumer/config_models/defaults.py, kafka_consumer/datadog_checks/kafka_consumer/config_models/instance.py, kafka_consumer/datadog_checks/kafka_consumer/data/conf.yaml.example
`ssl_context` is not used in the `kafka_consumer` integration.
According to the doc https://kafka-python.readthedocs.io/en/master/apidoc/KafkaClient.html it's a wrapper around options we already support, so we should remove it.
This option does not exist in `TlsContextWrapper` too, we have a card in the backlog to switch to this wrapper
=> Remove unused ssl_context documentation

datadog_checks_base/datadog_checks/base/checks/base.py
If a tag value such as a hostname includes ':' it will crash
=> Add limit to tag split

avi_vantage/assets/configuration/spec.yaml, avi_vantage/datadog_checks/avi_vantage/check.py, avi_vantage/datadog_checks/avi_vantage/config_models/defaults.py, avi_vantage/datadog_checks/avi_vantage/data/conf.yaml.example, avi_vantage/setup.py, avi_vantage/tests/conftest.py, avi_vantage/tox.ini, datadog_checks_base/datadog_checks/base/checks/base.py
This is a breaking change but since AVI is so new I think it's ok
Depends on https://github.com/DataDog/integrations-core/pull/10165
=> Add disable_generic tag to AVI

datadog_checks_dev/tests/tooling/manifest_validator/input_constants.py, datadog_checks_dev/tests/tooling/manifest_validator/test_v2_validator.py
This PR adds various tests to test the new manifest V2 validators. 
We need tests to support the new manifest V2 validators especially as we are about to be migrating manifests from V1 to V2 before Dash.
N/A
=> Create tests for new V2 manifest validators

process/datadog_checks/process/process.py, process/tests/test_integration.py, process/tests/test_process.py
This PR updates the `process` integration code by removing `try_sudo` as a parameter, since it is already an instance variable. This also sets a default value for  `accessors` as most uses of it are `None`.
=> Refactor `process` integration

.gitlab-ci.yml
Slack notifications are sometimes not sent to the user because `slack-notifier` is a bit flaky.
Adding a cache dir (like other repo do) allows us to workaround the flakiness by storing previous email <-> slack mapping
=> Fix slack-notifier flakiness

.github/CODEOWNERS
Adds the Documentation team as codeowners of the `md` and `manifest.json` files in the Agent Platform check folders.
Have the same codeowners structure as other checks.
=> Fixed Agent Platform checks documentation codeowners

datadog_checks_dev/datadog_checks/dev/http.py
https://github.com/DataDog/integrations-core/pull/10183 is replacing many custom mock objects and a few need more features
also added condition to `normalize_content` in order to reduce the need to set it to `False`
=> Add more functionality to `MockResponse` testing utility

kubelet/datadog_checks/kubelet/common.py, kubelet/datadog_checks/kubelet/summary.py, kubelet/tests/fixtures/pods_list_1.2.json, kubelet/tests/fixtures/stats_summary.json, kubelet/tests/test_kubelet.py
Calling the tagger when an entity does not exist in its store is an
expensive operation, since it'll cause all of its collectors to perform
a remote fetch. Since we know that the tagger does not store pods that
aren't running, calling it for pods that we know not to be running
yet/anymore is waste.
This change stores all pods in PodListUtils, and the summary (that
otherwise has no way of knowing a pod's status) checks to see if the pod
is present and its phase is "Running".
=> kubelet: don't call the tagger for pods not running

.github/workflows/validations.yaml, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/licenses.py
This PR catches the exception when the requirements file syntax is wrong. It previously crashed the licenses validation, this PR catches and prints fail message/annotate.
=> Catch exception for malformed requirement syntax

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/manifest.py
Adds a new `app_uuid` field to the migrated manifest when going from v1 -> v2
The architecture of the backend now requires a UUID to be tied to the App. This is a new field that we can generate for users, but must be part of the V2 manifest.
=> Add app_uuid to manifest migrator

datadog_checks_dev/datadog_checks/dev/tooling/catalog_const.py
Add an exception for logs support on IBM i, which can't collect logs because it's a remote check.
=> Add exception for IBM i logs collection

.azure-pipelines/all_master.yml, .azure-pipelines/latest.yml
Decrease dependence on Docker Hub
=> Use GCR for accessing Agent Docker images

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/requirements.in, twistlock/requirements.in
Stay up-to-date, esp. for latest tz database https://github.com/dateutil/dateutil/blob/master/NEWS
=> Upgrade python-dateutil to 2.8.2

datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/common/validator.py, datadog_checks_dev/tests/tooling/manifest_validator/input_constants.py, datadog_checks_dev/tests/tooling/manifest_validator/test_v2_validator.py, datadog_checks_dev/tests/tooling/manifest_validator/test_validator.py
This PR refactors the manifest ImmutableAttributesValidator to do a more extensive check of immutable attributes. Specifically, this strengthens the validation to check if asset short names were changed. Also, the validator's tests were expanded to more extensively test the strengthened functionality.
When the short_name of integration assets change (like the short_name of a dashboard) it gets propagated to the integration_dashboard table as a new row. This causes some different types of issues like 5xx on dashboard list pages. It would then take a considerable amount of manual dev work to resolve the issue. This PR eliminates that issue.
In datadog_checks_dev/tests/tooling/manifest_validator/test_validator.py, I had to add comments for the flake8 and black style validators to ignore the …
=> Strengthen ImmutableAttributesValidator to check for manifest changes in asset short names

aerospike/README.md
The agent ships with Aerospike client v6.0.0 which is only compatible with Aerospike server 4.9 or above.
See https://github.com/DataDog/integrations-core/issues/10190
=> docs - Add note about aerospike min version

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py
Consider `DDEV_E2E_AGENT_PY2` environment variable when starting python 2 environment with `ddev env start` or `ddev env test`
Pre-requisite to add a new pipeline to tests integration against specific agent builds #10204 
Test example: `DDEV_E2E_AGENT=datadog/agent:7.31.0-rc.10 DDEV_E2E_AGENT_PY2=datadog/agent:6.31.0-rc.11 ddev env test --base -ne --junit citrix_hypervisor`
=> Add DDEV_E2E_AGENT_PY2 env option

datadog_checks_base/datadog_checks/base/checks/base.py
This adds the ability for us to report dbm-activity events to the aggregator, which will forward them to the DBM backend  
related PRs
https://github.com/DataDog/datadog-agent/pull/9112 (already merged)
https://github.com/DataDog/integrations-core/pull/9866
=> Add new function to report dbm-activity events

haproxy/tox.ini, nginx/tox.ini
Example without use of factors: https://github.com/DataDog/integrations-core/blob/2f7a618e826da1babccf4ed49695b86c785ed361/redisdb/tox.ini#L34-L37
Simplify config
=> Remove factors from `latest` env vars definition

.azure-pipelines/agent.yml, .azure-pipelines/templates/run-tests.yml, .azure-pipelines/templates/test-all-checks.yml, .azure-pipelines/templates/test-all.yml, .azure-pipelines/templates/test-single-linux.yml, .azure-pipelines/templates/test-single-windows.yml
Add a pipeline that can be manually triggered against a specific datadog agent image.
The goal is to run that at least against all RC during QA
Example of parameters for a pipeline run:
Check/uncheck a `Python 2 tests` and `Python 3 tests` boxes to enable/disable Python2 or Python3 testing.
`Agent Docker Image`: docker image for python3-linux e2e tests (if `Python 3 tests` is checked)
`Windows Agent Docker Image`: docker image for python3-windows e2e (if `Python 3 tests` is checked)
`Agent Docker Image for Python 2`: docker image for python2-linux e2e tests (if `Python 2 tests` is checked)
`Windows Agent Docker Image for Python 2`: docker image for python2-windows e2e (if `Python 2 tests` is checked)
=> Add agent pipeline

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py
`time_unit/time_unit` (e.g. `ms/s`) is forbidden in the backend, let's raise an error with `ddev validate metadata`.
=> Forbid time_unit/time_unit metric metadata type

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/manifest.py
Don't set the empty underlying asset fields on migration
These fields should be non existant, not empty
=> Don't set empty asset values on migration

.azure-pipelines/templates/install-deps.yml, .azure-pipelines/templates/test-all.yml, .azure-pipelines/templates/test-single-linux.yml, .azure-pipelines/templates/test-single-windows.yml, datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/v2/validator.py
* Fail fast and return if we don't have the proper config to run the v2 validation. (Each check requires the previous to be true, so we should return quick if there are issues)
* Remove API/APP key from being required 
* Add dd_url to the Azure templates so that we can pass in a URL to use to run the validation against
We're working on fixing the Marketplace CI and beginning to validate V2 manifests
=> Update AZP templates to take in a dd_url and small fixes to validator

snmp/tests/test_e2e_core.py, snmp/tests/test_e2e_core_vs_python.py, snmp/tests/test_e2e_snmp_listener.py
Update e2e tests to support changes in core configuration 
* collecting metadata by default
* namespace tag
https://github.com/DataDog/datadog-agent/pull/9225
https://github.com/DataDog/datadog-agent/pull/9231
=> [snmp] update e2e test default metadata namespace

amazon_msk/assets/configuration/spec.yaml, amazon_msk/datadog_checks/amazon_msk/amazon_msk.py, amazon_msk/datadog_checks/amazon_msk/check.py, amazon_msk/datadog_checks/amazon_msk/config_models/defaults.py, amazon_msk/datadog_checks/amazon_msk/config_models/instance.py, amazon_msk/datadog_checks/amazon_msk/data/conf.yaml.example, amazon_msk/datadog_checks/amazon_msk/utils.py, amazon_msk/tests/test_unit.py
This PR adds proxy support.
Currently, users can only configure proxy settings by using environment variables.
The source states that proxy support via configuration files is not yet available
https://github.com/boto/botocore/blob/6a0f13261b3ecaf4e2cebbf134c3b3c7005a3c78/botocore/endpoint.py#L311-L314
Support case
=> Add proxy support in client initialization

datadog_checks_dev/datadog_checks/dev/tooling/utils.py
Fixes the processing of the context's `repo_name` when using the `--here\-x` flag
There's a lot of ddev tooling that checks the context objects `repo_name` to know to perform certain actions. 
However previously, we were only updating the `repo_choice` setting. This caused some weird inconsistencies when running the tooling. 
For example, the `get_root` method lets the `--here` flag take precedence, so when you pass a check_name, it can find it in that folder. However, any logic checking for `repo_name` would take the config value directly.
=> Set repo name after we process the `--here` flag

haproxy/tests/common.py
Make sure the version is always the same type, for the **latest** version it would be the max integer available
=> fix latest haproxy version handling

kubelet/manifest.json
Fix the manifest version for the kubelet check to properly be 1.0.0
The only valid value of the manifest version at this time is 1.0.0 (We didn't strictly validate against non 1.0.0 values, but as we're looking to support more, we need to have these properly set)
This should have 0 impact on any running part of this integration and only impact the validations and readers of the manifest file.
=> Fix the manifest version for the kubelet check

datadog_checks_base/datadog_checks/base/utils/db/utils.py
Send internal debug metrics with `raw=True` to ensure the check's standard namespace is not added as a prefix.
The upcoming SQL Server DBM integration uses the `__NAMESPACE__` setting so these metrics must be "raw" to ensure they're not prefixed the same way.
=> DBMAsyncJob send internal metrics as raw

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/manifest.py
Avoid having null values be added to the classifier tags list when migrating a manifest to v2
The migrator does a lookup of each category to see what the coresponding enum value is. There are some cases where categories is `[""]`, which causes a `null` value to be added to the final migrated manifest. This avoids that scenario and skips any classifier_tags we can't use.
=> Don't add null values to classifier tags

ibm_was/datadog_checks/ibm_was/ibm_was.py, ibm_was/tests/test_unit.py
If XML output does not contain the path, the error is too generic. This PR includes the xml_data name so it's easier to debug.
This PR also logs in the agent.log instead of the status collector output (if the missing metric category is actually not available, it can be spammy and generic)
```
Warning: Error finding JDBC Connection Pools stats in XML output.
Warning: Error finding Servlet Session Manager stats in XML output.
Warning: Error finding JDBC Connection Pools stats in XML output.
Warning: Error finding Servlet Session Manager stats in XML output.
Warning: Error finding JDBC Connection Pools stats in XML output.
Warning: Error finding Servlet Session Manager stats in XML output.
Warning: Error finding JDBC Connection Pools stats in XML output.
Warning: Error finding Servlet …
```
=> Change status warning to debug log

snmp/assets/configuration/spec.yaml, snmp/datadog_checks/snmp/data/conf.yaml.example
Add config for enabling NDM metadata collection.
We have added this option to enable/disable device metadata collection. It needs to be documented.
* Check the file `datadog.yaml` does contain the lines describing the configuration.
=> [NDM] Add config for enabling NDM metadata collection

snmp/assets/configuration/spec.yaml, snmp/datadog_checks/snmp/data/conf.yaml.example
Add documentation in snmp spec for `namespace` option. Related to https://github.com/DataDog/datadog-agent/pull/9303
Avoid ambiguity between devices with the same IP address within the same organisation
=> [snmp] add namespace doc

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/start.py, docs/developer/ddev/test.md
=> Enable E2E logs agent by default if environments mount logs

kubelet/README.md, kubelet/datadog_checks/kubelet/common.py, kubelet/datadog_checks/kubelet/prometheus.py, kubelet/tests/test_common.py
Fixes a bug in the Kubelet check. Now the check verifies if a Kubernetes namespace should be excluded before reporting `network.*` metrics.
Users can exclude metrics from certain containers using the `DD_CONTAINER_EXCLUDE` env ([docs](https://docs.datadoghq.com/agent/guide/autodiscovery-management/?tab=containerizedagent)). The Kubelet check applied those exclusion rules in most cases, but not for the network metrics at the pod level. So, when a user specified something like: `kube_namespace:my_namespace`, the Kubelet check still reported network metrics of pods deployed in `my_namespace`. This PR fixes the issue.
=> Apply namespace exclusion rules before reporting network metrics

ecs_fargate/datadog_checks/ecs_fargate/ecs_fargate.py
Adds a fallback calculation for ECS Fargate CPU percentage in the case that the API returns non-sensical values
Better user experience
=> Add fallback calculation for CPU percentage

docs/developer/process/agent-release/pre-release.md
Updates release docs to remove mention of trello/github users map
The trello script no longer needs this map
=> Update release docs

datadog_checks_dev/datadog_checks/dev/plugin/pytest.py
Necessary for use within `dd_environment` fixture
=> Fix scope of E2E state management fixtures

datadog_checks_base/datadog_checks/base/utils/db/core.py, datadog_checks_base/tests/base/utils/db/test_custom_queries.py
This PR introduces `only_custom_queries` option (Oracle had a version of this), which allows users to confgure instances to only collect custom queries. 
Support case, if a customer wants to specify a db-level connection (Snowflake), they don't want multiple instances attempting to run default queries. This is especially erroneous if the custom queries use a different set of credentials (results in error logs).
=> Add only_custom_queries option to database utils

hudi/tests/docker/Dockerfile
Rely on a stable version of maven that won't be replaced by new versions
Tests failing due to removal of hosted 3.8.2
=> Don't use latest maven version in tests

postfix/assets/configuration/spec.yaml, postfix/datadog_checks/postfix/config_models/defaults.py, postfix/datadog_checks/postfix/config_models/instance.py, postfix/datadog_checks/postfix/data/conf.yaml.example
`queues` and `directory` are optional if `postqueue: true` in the init_config, but they don't have a default value.
https://github.com/DataDog/integrations-core/blob/3e7f81b20a2c4d93afea43019ff92aa253bc3242/postfix/datadog_checks/postfix/postfix.py#L95-L108
QA #10051
=> Fix config example

ibm_db2/requirements-dev.txt, ibm_db2/tests/common.py, ibm_db2/tests/docker/requirements.txt, ibm_db2/tox.ini
Bumps ibm_db dependency for python 3
a new version that is compatible with python 3 was released: https://github.com/ibmdb/python-ibmdb/pull/661
=> Bump version of ibm_db in python 3 tests

disk/README.md
The agent user requires Administrator permissions to collect mount point metrics on Windows hosts. Many customers will not want to give the Agent user these permissions, so as a workaround they can use the PDH check.
Customer request -
=> Recommend PDH check for mount point metrics

avi_vantage/assets/configuration/spec.yaml, avi_vantage/datadog_checks/avi_vantage/check.py, avi_vantage/datadog_checks/avi_vantage/config_models/defaults.py, avi_vantage/datadog_checks/avi_vantage/data/conf.yaml.example, avi_vantage/tests/conftest.py, clickhouse/tox.ini, datadog_checks_base/datadog_checks/base/utils/tagging.py, gearmand/tox.ini, ibm_was/tox.ini, jboss_wildfly/tox.ini, openstack/tox.ini, oracle/tox.ini, sap_hana/tox.ini, tls/tox.ini
This reverts commit f03660cb45487242e5aa399d33b8cc75ffe580c1, so only reserved tags are considered generic.
We have an RFC to decide how to handle such tagging in the future so we should avoid any premature implementation of such enforcement.
The 2 integrations where we didn't want a `server` tag are unaffected by this change:
- https://github.com/DataDog/integrations-core/blob/7.32.x/mysql/datadog_checks/mysql/mysql.py#L223-L224
- https://github.com/DataDog/integrations-core/blob/7.32.x/postgres/datadog_checks/postgres/config.py#L103-L104
=> Remove `server` from the list of generic tags

snmp/assets/configuration/spec.yaml, snmp/datadog_checks/snmp/data/conf.yaml.example
Fixes bug II-557
As network discovery is available in 7.32 with core check, remove `python only` mention from related props
II-557
=> Remove python only mention from check discovery props

snmp/assets/configuration/spec.yaml, snmp/datadog_checks/snmp/data/conf.yaml.example
This config is true by default and doesn't need to be visible to the user.
=> Hide collect_device_metadata by default

ceph/tests/conftest.py, couchbase/tests/conftest.py, datadog_checks_base/tests/conftest.py
All these have failed on build https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=79896&view=results on docker-compose step because of networking issues. Two due to cloudflare issues, the other one due to a handshake timeout.
=> Add docker-compose attempts

hdfs_datanode/README.md, hdfs_datanode/assets/configuration/spec.yaml, hdfs_datanode/datadog_checks/hdfs_datanode/data/conf.yaml.example, hdfs_datanode/datadog_checks/hdfs_datanode/hdfs_datanode.py, hdfs_datanode/tests/common.py, hdfs_datanode/tests/compose/docker-compose.yaml, hdfs_datanode/tests/conftest.py, hdfs_datanode/tests/fixtures/hdfs_datanode_info_jmx.json, hdfs_datanode/tests/test_hdfs_datanode.py, hdfs_datanode/tests/test_integration.py, hdfs_datanode/tox.ini, hdfs_namenode/README.md, hdfs_namenode/assets/configuration/spec.yaml, hdfs_namenode/datadog_checks/hdfs_namenode/data/conf.yaml.example, hdfs_namenode/datadog_checks/hdfs_namenode/hdfs_namenode.py, hdfs_namenode/tests/common.py, hdfs_namenode/tests/compose/docker-compose.yaml, hdfs_namenode/tests/conftest.py, hdfs_namenode/tests/fixtures/hdfs_namesystem_info.json, hdfs_namenode/tests/test_hdfs_namenode.py, hdfs_namenode/tests/test_integration.py, hdfs_namenode/tox.ini
1. Updated default port numbers, e.g. see https://github.com/big-data-europe/docker-hadoop/pull/26
2. Fixed version metadata submission for `hdfs_datanode` so it handles build data
3. Changed version metadata for `hdfs_namenode` so it submits build data
Customer inquiry
=> Support newer versions of Hadoop

datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/v2/validator.py, datadog_checks_dev/tests/tooling/manifest_validator/input_constants.py, datadog_checks_dev/tests/tooling/manifest_validator/test_v2_validator.py
This PR adds a validator to ensure tile descriptions are a maximum 70 characters for V2 manifests.
Descriptions over 70 characters are cut off in the UI.
No
=> Add TileDescriptionValidator for V2 manifests

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/make.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/release/show/changes.py
Add some debug lines and small refactor
=> Add some debug messages to release make command and some refactor

datadog_checks_dev/datadog_checks/dev/tooling/commands/dep.py
Add option to include security dependencies when updating dependencies, and ignore by default.
Additionally changes the short name of `check-python-classifiers` so it does not clash with `sync`
Reduce number of dependencies updated at once, and encourage more testing for those dependencies in particular
=> Add option to include security deps in dep command

postgres/README.md, postgres/metadata.csv
Adds documentation for 4 new postgres metrics that DBM customers will get in the next agent release 
```
postgresql.transactions.duration.max
postgresql.transactions.duration.sum
postgresql.queries.duration.max
postgresql.queries.duration.sum
```
Collection for these metrics were added as part of this change https://github.com/DataDog/integrations-core/pull/9866 and the metrics are being reported in our backend now 
In addition to this, I also updated documentation for the other DBM only related metrics to include the actual tag names and not the full "english translation" for what they are. This should make it easier for customers to figure out what these metrics are tagged by.
=> Add documentation for new DBM only postgres metrics

dns_check/datadog_checks/dns_check/dns_check.py, dns_check/tox.ini
* Config is fetched and stored in init rather than on each check run
* All non dynamic tags are calculated on init rather than on each check run
* _load_conf has been replaced with _get_resolver, it still runs on each check run
* Added some types
=> Move config fetching to init and add types

datadog_checks_base/tests/base/utils/db/test_util.py
Fixes a rare race condition in running the async job loop rate limiter. I believe what's happening is that because there is no wait in the run_job function, there is one extra execution of the job slipping in after the 1s wait period before the call to cancel the job.
As long as the test job continues to have no waits, this should still be a valid test with deterministic results.
```
________________________ test_dbm_async_job_rate_limit _________________________
tests/base/utils/db/test_util.py:153: in test_dbm_async_job_rate_limit
assert max_collections / 2.0 <= len(metrics) <= max_collections
E   AssertionError: assert 12 <= 11
```
=> Fix a race in a test for running async jobs

mongo/tox.ini
Mongo 3.5 is eol https://www.mongodb.com/support-policy/lifecycles
=> Change mongo tested versions

hdfs_datanode/tests/common.py, hdfs_datanode/tests/test_integration.py
It is better to optionally assert than to ignore because that way when the metric is present we can ensure it has the right type and it let us assert that all metrics are present in metadata
=> Add optional assertion and assert all metrics

mysql/README.md
Autodiscovery example included "nginx" instead of "mysql" in the annotations. This is a quick fix to those typos.  
Annotations as they currently exist will not allow someone to enable the integration successfully.
=> fix autodiscovery typos

containerd/metadata.csv
Provide better metrics description for `containerd.blkio.*` metrics.
It use description provided by the linux kernel documentation instead of
the containred prometheus metrics documentation.
Better documentation
=> Docs: update containerd metrics description

kube_apiserver_metrics/datadog_checks/kube_apiserver_metrics/kube_apiserver_metrics.py, kube_apiserver_metrics/metadata.csv, kube_apiserver_metrics/tests/test_kube_apiserver_metrics_1_19.py
the `kube_apiserver.etcd.db.total_size` metric is a gauge representing
the total size of the etcd database file physically allocated in bytes.
Refs: #10472
Implement the feature request: #10472
=> feat: add kube_apiserver.etcd.db.total_size metric

ibm_i/manifest.json
Updates the ibm_i check metadata so documentation is made public.
Doing this ahead of the 7.32 release, which is the first one to include this check.
=> Set is_public to true in the IBM i check metadata

ibm_mq/tests/conftest.py
https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=80310&view=logs&j=f3774450-0a68-5b0d-a279-93c033634772&t=ed7988d9-71e7-5489-6209-e013d128d1ff
```
Creating network "compose_ibm-net" with the default driver
Pulling ibm_mq1 (ibmcom/mq:9)...
Head "https://registry-1.docker.io/v2/ibmcom/mq/manifests/9": unknown: unable to scan account service account row from query: context deadline exceeded
Removing network compose_ibm-net
```
=> Add docker-compose attempts to IBM mq

clickhouse/tests/test_clickhouse.py, clickhouse/tox.ini
A new version of clickhouse was released that introduced a flakey metric: https://github.com/ClickHouse/ClickHouse/releases/tag/v21.11.2.2-stable
The `latest` image is also currently the same as `21`, so testing the `21` is unnecessary.
We want to test a stable version for now, and investigate the differences of the new version later.
=> Pin tested clickhouse 21 version

datadog_checks_dev/datadog_checks/dev/tooling/config.py
Newer versions require explicit `False` https://github.com/platformdirs/platformdirs/blob/7b7852128dd6f07511b618d6edea35046bd0c6ff/src/platformdirs/windows.py#L33
```pycon
>>> from platformdirs import user_data_dir
>>>
>>> user_data_dir('dd-checks-dev', '')
'C:\\Users\\ofek\\AppData\\Local\\dd-checks-dev\\dd-checks-dev'
>>> user_data_dir('dd-checks-dev', False)
'C:\\Users\\ofek\\AppData\\Local\\dd-checks-dev'
```
=> Fix location of config

sqlserver/datadog_checks/sqlserver/sqlserver.py, sqlserver/tests/test_integration.py
Fixes the incorrect `resolved_hostname` which was falling back to the agent hostname due to failed DNS resolution when using SQL Server DBM. Now it correctly parses out the host when the host connection has the `{host},{port}` connection format.
=> fix sqlserver resolved_hostname by handling comma correctly

mysql/tox.ini, singlestore/tox.ini
Pin mypy `types-PyMySQL` to 1.0.4 because the latest v1.0.5 release was breaking py27 style checks for singlestore and mysql
Broken CI
`types-PyMySQL` v1.0.5 dropped support for python 2: https://github.com/python/typeshed/pull/6267/files#diff-8c6a665db0a06e7c5108bc93201f557aeb15ea7ef0819569bf445e4ed36cf803L2
=> Pin mypy types-PyMySQL to 1.0.4

harbor/tests/conftest.py, sqlserver/tests/conftest.py
SQL Server failed on docker-compose
```
________________ ERROR at setup of test_async_job_cancel_cancel ________________
tests/conftest.py:169: in dd_environment
with docker_run(compose_file=compose_file, conditions=conditions, mount_logs=True, build=True):
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/contextlib.py:113: in __enter__
return next(self.gen)
../datadog_checks_dev/datadog_checks/dev/docker.py:217: in docker_run
with environment_run(
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/contextlib.py:113: in __enter__
return next(self.gen)
../datadog_checks_dev/datadog_checks/dev/env.py:73: in environment_run
condition()
../datadog_checks_dev/datadog_checks/dev/conditions.py:159: in __call__
raise RetryError(
E   datadog_checks.dev.errors.RetryError: Command: …
```
=> Add attempts to SQLServer docker run

redisdb/tests/test_e2e.py
These metrics occasionally apear and make the test fail
=> Assert optional slowlog metrics

hudi/assets/dashboards/overview.json, hudi/manifest.json
Adds a default dashboard for the Hudi integration
=> Add Hudi default dashboard 

mysql/datadog_checks/mysql/mysql.py
Changes the default behavior when DBM is enabled so that the innodb status metrics and replication metrics are automatically collected.
These extra settings provide richer data so we should be sure to collect them for DBM insights.
=> Enable `extra_status_metrics` and `replication` metrics by default when DBM is enabled

containerd/README.md, containerd/metadata.csv
Adds the Windows metrics in the containerd check.
The new metrics were added in https://github.com/DataDog/datadog-agent/pull/9296
=> Add Windows metrics in containerd integration

.gitlab-ci.yml
Changes order of gitlab stages so releases off of the release branch are not blocked by agent build and logs validation
Release PRs never change log assets or the agent requirements file so this should have no effect besides not blocking releases off of the release branch when the agent pipeline runs when it shouldn't
Alternative ideas: 
- Create a new stage and put jobs that are independent of each other all in one stage so they run at once
- Keep the same ordering of stages but set `allow_failure` to true on validate-agent-build so it still runs before release but doesn't block it
- add a `needs: []` clause to release_manual so that it is not blocked by other stages
=> Change order of gitlab pipeline stages

istio/README.md
This PR adds a note to the troubleshooting section. Sometimes users configure generic metric collection with the Openmetrics integration which results in duplicate metrics from the istio-proxy sidecars. This PR includes examples to exclude metrics in their openmetrics configuration to prevent this.
Troubleshooting note
=> Add troubleshooting note for high custom metric billings when enabling openmetrics

mysql/assets/configuration/spec.yaml, mysql/datadog_checks/mysql/config.py, mysql/datadog_checks/mysql/config_models/defaults.py, mysql/datadog_checks/mysql/config_models/instance.py, mysql/datadog_checks/mysql/data/conf.yaml.example, mysql/datadog_checks/mysql/mysql.py, mysql/tests/conftest.py, mysql/tests/test_mysql.py
Sometimes the result of "SHOW VARIABLE" or "SHOW STATUS" is not in const. 
Since using a custom query is considered an unnecessary process, we are going to send the result value using yaml as needed.
As i am monitoring, i need to collect more parameters.
- [v] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [v] PR title must be written as a CHANGELOG entry [(see why)](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title)
- [v] Files changes must correspond to the primary purpose of the PR as described in the title (small unrelated changes should have their own PR)
- [v] PR must have `changelog/` and `integration/` labels attached
=> Mysql additional vars

.github/CODEOWNERS
This will make sure the database team is added to every PR on postgres and mysql.
Plan:
* Beginning of Q1: Make them first owners and start being added to SQLServer and oracle PRs: https://github.com/DataDog/integrations-core/pull/10603
* Once Oracle and SQLServer QA make them first owners on those too
=> Add database team as co-owners of postgres and mysql

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/integration_style.py
Update the warning message to say that the instance argument will be deprecated in agent 8 
https://datadoghq.dev/integrations-core/meta/status/#agent-8-check-signatures
=> Update warning message about agent signature

redisdb/datadog_checks/redisdb/redisdb.py, redisdb/tests/test_default.py
This uses XLEN to get the length of a stream.
=> Add support for monitoring Redis stream keys

nginx/metadata.csv, nginx/tests/test_unit.py
some metrics were missing or inaccurate in nginx's metadata.csv
found when running `aggregator.assert_metrics_using_metadata(get_metadata_metrics(), check_submission_type=True)`
Improving the check overall
=> Add missing NGINX plus metrics to metadata and assert metadata in tests

datadog_cluster_agent/datadog_checks/datadog_cluster_agent/check.py, datadog_cluster_agent/metadata.csv, datadog_cluster_agent/tests/fixtures/metrics.txt, datadog_cluster_agent/tests/test_datadog_cluster_agent.py
Add missing metric `secret_backend__elapsed_ms -> secret_backend.elapsed` to the `datadog_cluster_agent` check.
=> fix: Add missing metric to datadog_cluster_agent

sap_hana/README.md, sap_hana/assets/configuration/spec.yaml, sap_hana/datadog_checks/sap_hana/config_models/defaults.py, sap_hana/datadog_checks/sap_hana/config_models/instance.py, sap_hana/datadog_checks/sap_hana/connection.py, sap_hana/datadog_checks/sap_hana/data/conf.yaml.example, sap_hana/datadog_checks/sap_hana/exceptions.py, sap_hana/datadog_checks/sap_hana/sap_hana.py, sap_hana/tests/common.py, sap_hana/tests/test_unit.py, sap_hana/tox.ini
https://github.com/SAP-archive/PyHDB
> This public repository is read-only and no longer maintained.
> The active maintained alternative is SAP HANA Python Client: https://pypi.org/project/hdbcli/
=> Support the `hdbcli` client library

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/integration_style.py
Don't warn on hostname parameter used in service check or metric submission. 
Datadog documentation supports these features so we shouldn't warn against them
=> Remove integration style hostname submission validation

go_expvar/datadog_checks/go_expvar/go_expvar.py, go_expvar/tests/test_unit.py
follow up to https://github.com/DataDog/integrations-core/pull/10089/s, sets log level to debug on mappings (`"memstats"`) that are collected by default. Also sends more descriptive warning message for arrays. Future work can include refactoring the check to send debug messages when default paths are specified such as `"memstats/TotalAlloc"`
Lower log level for unnecessary config
=> Set log level to debug for memstats

datadog_cluster_agent/assets/dashboards/datadog_cluster_agent_overview.json, datadog_cluster_agent/manifest.json
Adds a default dashboard for the `datadog_cluster_agent` check
Staging Link: https://dd.datad0g.com/dash/integration/30706/datadog-cluster-agent---overview
=> Add default datadog_cluster_agent dashboard

postgres/datadog_checks/postgres/statement_samples.py, postgres/tests/test_statements.py
Tracking the gauge as an internal debug metric will help in troubleshooting failed explain error rates.
=> add internal debug metric for explain error cache length

.azure-pipelines/templates/test-single-windows.yml, datadog_checks_base/datadog_checks/base/__about__.py
Windows e2e is pinned to py2 by accident in ci
=> Fix Windows E2E on Python 3

aspdotnet/assets/configuration/spec.yaml, aspdotnet/datadog_checks/aspdotnet/config_models/defaults.py, aspdotnet/datadog_checks/aspdotnet/config_models/instance.py, aspdotnet/datadog_checks/aspdotnet/data/conf.yaml.example
`host` is not required
`port` is not used
aspdotnet integration is using PDHBaseCheck, so we should use `pdh_legacy` spec
QA #8886
=> Fix config spec options

linkerd/assets/configuration/spec.yaml, linkerd/datadog_checks/linkerd/config_models/defaults.py, linkerd/datadog_checks/linkerd/config_models/instance.py, linkerd/tests/test_linkerd.py
Adds a hidden config spec template so that if a user is using the openmetrics v1 spec, then those options will be validated. Additionally adds dd_run_check in tests to catch config errors
QA for https://github.com/DataDog/integrations-core/pull/8948
=> Validate use of legacy openmetrics config

cacti/assets/configuration/spec.yaml, cacti/datadog_checks/cacti/config_models/defaults.py, cacti/datadog_checks/cacti/config_models/instance.py, cacti/datadog_checks/cacti/data/conf.yaml.example, cacti/tests/test_cacti.py
- Adds `mysql_db` to the config spec, as it is a valid option in the check implementation
- Removes `ifIndex` from `field_names` example since it is not a default option
- Updates field_names documentation to fix typo and show default values
- Uses `dd_run_check` in tests to run check initializations in tests
QA for https://github.com/DataDog/integrations-core/pull/8889
=> Add missing config option to spec and update examples to match implementation

disk/assets/configuration/spec.yaml, disk/datadog_checks/disk/config_models/defaults.py, disk/datadog_checks/disk/config_models/instance.py, disk/datadog_checks/disk/data/conf.yaml.default, disk/tests/test_check.py, disk/tests/test_unit.py
use_mount defaults to False, adding the required field makes the tests fail when use_mount is not explicitly defined in conf.yaml
Fix behavior
=> Fix use_mount required field 

kubernetes/assets/dashboards/kubernetes_clusters.json, kubernetes/assets/dashboards/kubernetes_dashboard.json, kubernetes/assets/dashboards/kubernetes_pods.json, kubernetes/assets/monitors/monitor_pods_failed_state.json
* Replace `replicaset` by `kube_replica_set` tag on pod metrics.
* Replace `phase` by `pod_phase` tag on pod metrics.
OOTB Kubernetes Dashboards and monitors should be compatible with
`kubernetes_state` and `kubernetes_state_core` integration, and so
they should only use none deprecated tags.
=> Fix kubernetes OOTB dashboard and monitors

datadog_checks_dev/datadog_checks/dev/tooling/commands/ci/setup.py
If a file in the pipeline setup scripts directory starts with an underscore, then it is treated as a "non-executable" file and it will not be executed.
This is required for https://github.com/DataDog/integrations-core/pull/10637 where a large SQL setup script is needed to be referenced by one of the other scripts, but the SQL script itself must not be executed.
=> support non-executable files during pipeline setup

datadog_checks_base/datadog_checks/base/utils/db/sql.py, datadog_checks_base/tests/base/utils/db/test_db_sql.py
Fixes `mmh3.hash64` UnicodeEncodeError when the query contained non-ascii characters in python2. 
```
datadog_checks/base/utils/db/sql.py:27: in compute_sql_signature
return format(mmh3.hash64(normalized_query, signed=False)[0], 'x')
E   UnicodeEncodeError: 'ascii' codec can't encode character u'\xd2' in position 15: ordinal not in range(128)
```
Fix bug originally surfaced while working on https://github.com/DataDog/integrations-core/pull/10637
=> fix `mmh3.hash64` unicode exception with python2

kong/datadog_checks/kong/kong.py, kong/tests/test_integration_e2e.py
Refactor test so it does not use instance on check method
Use dd_run_check on integration tests
QA for https://github.com/DataDog/integrations-core/pull/8943
=> Refactor check to be able to use dd_run_check in tests

redisdb/tests/test_e2e.py
Add optional metrics assertions to tests to prevent the test from flaking
```
________________________________ test_e2e_v_3_2 ________________________________
tests/test_e2e.py:81: in test_e2e_v_3_2
assert_all(aggregator)
tests/test_e2e.py:147: in assert_all
aggregator.assert_all_metrics_covered()
../datadog_checks_base/datadog_checks/base/stubs/aggregator.py:419: in assert_all_metrics_covered
assert condition, msg
E   AssertionError: Some metrics are missing:
E     Asserted Metrics:
...
E     Missing Metrics:
E     	- redis.slowlog.micros.95percentile
E     	- redis.slowlog.micros.avg
E     	- redis.slowlog.micros.count
E     	- redis.slowlog.micros.max
E     	- redis.slowlog.micros.median
E   assert False
```
=> Add missing assertion

http_check/tests/test_http_integration.py
- Update test to run check twice to properly catch when `Authorization` was getting removed from the request headers 
- Add more tests for when headers are set in different ways
QA for https://github.com/DataDog/integrations-core/pull/10388
=> Update `test_instance_auth_token` to run check twice and add more header tests

datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/v1/schema.py
Don't allow use of author, pricing, and terms fields for extras integrations since they are only for marketplace
=> Don't allow use of author, pricing, and terms fields for extras integrations

snowflake/tests/snowflake_connector_patch/pyproject.toml
Build is failing with the following error:
```
Processing /home/snowflake_connector_patch
Installing build dependencies: started
Installing build dependencies: finished with status 'error'
ERROR: Command errored out with exit status 1:
command: /opt/datadog-agent/embedded/bin/python3 /tmp/pip-standalone-pip-a3frtscc/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-jqnh44pq/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- hatchling==0.0.41
cwd: None
Complete output (2 lines):
ERROR: Could not find a version that satisfies the requirement hatchling==0.0.41 (from versions: 0.0.45)
ERROR: No matching distribution found for hatchling==0.0.41
----------------------------------------
```
=> Bump hatchling to 0.0.45

datadog_checks_dev/datadog_checks/dev/tooling/configuration/consumers/model.py
- Allows BaseModel keywords as option names
- needed for https://github.com/DataDog/integrations-core/pull/10714/files to pass validation as schema is a attribute of BaseModel
=> Allow BaseModel keywords as option names

snowflake/datadog_checks/snowflake/config_models/defaults.py, snowflake/tests/test_snowflake.py
- Fixes the field name for `schema`
- Allows users to optionally set the `schema` config option
- Currently, if `schema` is not specified, an error is thrown when it should not: 
`AttributeError: module 'datadog_checks.snowflake.config_models.defaults' has no attribute 'instance_schema_'`
=> Fix default field name of schema

sqlserver/datadog_checks/sqlserver/connection.py
Autocommit is already enabled for `adodbapi` so this ensures pyodbc matches that setting. We noticed this while testing https://github.com/DataDog/integrations-core/pull/10610 and seeing elevated transaction durations for the many queries run sequentially by the agent while collecting query metrics and execution plans.
=> enable autocommit for pyodbc in sqlserver

.azure-pipelines/scripts/sqlserver/windows/55_setup_sqlserver.bat, .azure-pipelines/scripts/sqlserver/windows/_sqlserver_setup.sql, sqlserver/datadog_checks/sqlserver/statements.py, sqlserver/requirements.in, sqlserver/tests/compose-ha/sql/aoag_primary.sql, sqlserver/tests/compose/setup.sql, sqlserver/tests/test_statements.py
* add a unicode character to the test schema to ensure we're testing the full statements flow to ensure unicode characters are properly supported.
* switch from the built-in XML library to `lxml` as the built-in one was not correctly able to encode utf-8 even when the encoding was specified.
=> fix broken unicode support for sqlserver

sap_hana/datadog_checks/sap_hana/sap_hana.py, sap_hana/tests/conftest.py, sap_hana/tests/test_integration.py, sap_hana/tests/test_unit.py
The sap_hana configuration spec was updated with the new `QueryManager` option, `only_custom_queries` via the db config templates, however the integration doesn't use the QueryManager, it only shares common configuration specs. This PR adds support for filtering out the default collected queries. 
Support case
=> Add support for only_custom_queries

.azure-pipelines/all_pr.yml, .azure-pipelines/changes.yml
We removed the CI App product in #10732 because it was also running on fork PRs, which doesn't have access to the datadog api key
This PR enables the CI App product back on non-fork PRs relying on `System.PullRequest.IsFork` (see doc https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
Example of what would happen on a fork PR (commit https://github.com/DataDog/integrations-core/commit/93518225199ead5bf4b2189f7f71897ffdfcbf9c): https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=82250&view=results
=> Enable CI App on non-fork PRs

datadog_checks_base/datadog_checks/base/checks/windows/perf_counters/base.py, datadog_checks_base/datadog_checks/base/checks/windows/perf_counters/connection.py, datadog_checks_base/datadog_checks/base/checks/windows/perf_counters/counter.py, datadog_checks_base/datadog_checks/base/checks/windows/perf_counters/utils.py, win32_event_log/datadog_checks/win32_event_log/check.py, win32_event_log/datadog_checks/win32_event_log/utils.py, win32_event_log/tests/conftest.py
- https://github.com/mhammond/pywin32#docs
- https://github.com/mhammond/pywin32/pull/1774
=> Update pywin32 links to point to the new official documentation

sqlserver/tests/test_activity.py
The table name `things` was changed in in this PR https://github.com/DataDog/integrations-core/pull/10713, which caused the activity tests to fail with `E   pyodbc.ProgrammingError: ('42S02', "[42S02] [FreeTDS][SQL Server]Invalid object name 'things'. (208) (SQLExecDirectW)")`
updating the table name should fix the issue
=> Fix active sessions sqlserver tests

postgres/datadog_checks/postgres/statement_samples.py, postgres/tests/test_statements.py
Reported as an issue by a DBM customer after they upgraded their agent from 7.31 to 7.32. Updating this query is required to getting the `db` tag to work properly for this metric. Related Zendesk ticket. This is a regression only for customers who have DBM enabled. 
https://datadog.zendesk.com/agent/tickets/594763
=> Add datname to connections query for postgresql.connections

sqlserver/datadog_checks/sqlserver/connection.py
Add `ConnectRetryCount=2` to the default connection string.
It automatically retries the connection when it fails during a check run (https://docs.microsoft.com/en-us/sql/connect/odbc/connection-resiliency?view=sql-server-ver15).
It should fix error like below without customer needing to restart the agent manually
```
The connection is broken and recovery is not possible. The client driver attempted to recover the connection one or more times and all attempts failed. Increase the value of ConnectRetryCount to increase the number of recovery attempts.
```
`tests/test_activity.py::test_collect_activity` has been failing since https://github.com/DataDog/integrations-core/commit/5a006c40551741c73a7a1a7c63fd2a13406eb7d3
=> Add ConnectRetryCount to connection string

datadog_checks_dev/datadog_checks/dev/_env.py
Support event platform events for e2e testing
See related PR requiring/using this change: https://github.com/DataDog/integrations-core/pull/10664
=> Support event platform events for e2e testing

hudi/tests/docker/Dockerfile, hudi/tests/docker/build.sbt, hudi/tests/docker/docker-compose.yaml
The build depended on a moving target (the master branch of hudi repo).
This change makes it depend on a release tag.
=> Fix hudi build

spark/assets/configuration/spec.yaml, spark/datadog_checks/spark/config_models/defaults.py, spark/datadog_checks/spark/config_models/instance.py, spark/datadog_checks/spark/data/conf.yaml.example, spark/datadog_checks/spark/spark.py, spark/tests/docker/spark-apps/app2.py, spark/tests/fixtures/metrics_json, spark/tests/test_spark.py
Adds a `query_name` tag for Spark Structured Streaming metrics.  
Part of the implementation for Structured Streams added in #8078 included a regex pattern to capture and validate the `metric_name`s related to structured streaming, but didn't capture the stream's `query_name`, which is also a provided component within the metric key.
This is a necessary tag to have if a cluster is running more than 1 stream! Without the query_name tag there is no way to disambiguate which stream is producing the structured_streaming metrics for that cluster.
A query name is optionally set on the Structured Stream when [writing to a sink](https://spark.apache.org/docs/latest/structured-streaming-programming-guide.html#starting-streaming-queries).  If the queryName param is not supplied, you will see a UUID …
=> add `query_name` as tag from Spark Structured Streaming metrics

hyperv/assets/configuration/spec.yaml, hyperv/datadog_checks/hyperv/check.py, hyperv/datadog_checks/hyperv/config_models/defaults.py, hyperv/datadog_checks/hyperv/config_models/instance.py, hyperv/datadog_checks/hyperv/config_models/shared.py, hyperv/datadog_checks/hyperv/data/conf.yaml.example, hyperv/datadog_checks/hyperv/hyperv.py, hyperv/datadog_checks/hyperv/metrics.py, hyperv/tests/test_hyperv.py
See https://github.com/DataDog/integrations-core/pull/10504
=> Support new implementation of Windows performance counters on Python 3

kafka/datadog_checks/kafka/data/metrics.yaml, kafka/metadata.csv, kafka/tests/common.py
Add a metric about the number of currently open connections to the broker, per listener. 
We'd need to monitor the number of clients connected per listener, for instance in order to disable the plain text listener we need to ensure that no client is connected.
Since the cardinality is very low, it shouldn't be a problem regarding the number of metrics collected by the check.
=> Kafka check - add listeners metric

sqlserver/datadog_checks/sqlserver/statements.py
This adds a filter on the statement metrics query to only capture rows that have a `last_execution_time` more recent than the `collection interval * 2`. This helps performance dramatically on larger databases with a big plan cache size. 
Slow performance of the query metrics collection.
=> Update SQLServer Query Metrics Collection Query to Improve Performance

azure_iot_edge/tests/test_check.py
Updates integration tests with `dd_run_check`.
=> Use dd_run_check for azure_iot_edge

sqlserver/datadog_checks/sqlserver/activity.py, sqlserver/tests/test_activity.py
SQLServer timestamps by default are of the `datetime` type, which does not include a timezone. This is problematic because when we need to know the timezone to correctly calculate the query/transaction duration on the backend. 
This update relies on the use of [CONVERT](https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver15#date-and-time-styles) to convert the `DATETIMEOFFSET` to a string (necessary for python to properly parse it) and also get the ISO 8601 format of the timestamp. 
Result of this query gives us timestamps with the proper formatting e.g.:
`2021-12-02T18:13:50.723+00:00` -> UTC 
`2021-12-02T18:13:50.740-08:00` -> PDT (Got this via `SYSDATETIMEOFFSET() AT TIME ZONE 'Pacific Standard Time'`)
DBM SQLServer Active Sessions beta …
=> Update SQLServer activity query to get timestamps with the timezone

docs/developer/process/integration-release.md
This PR refactors the troubleshooting section into 2 subsections (signing issues and build failure issues). I also added another case of release build failure that isn't covered.
Update docs
=> Refactor release troubleshooting section and add another case

iis/assets/configuration/spec.yaml, iis/datadog_checks/iis/check.py, iis/datadog_checks/iis/config_models/instance.py, iis/datadog_checks/iis/data/conf.yaml.example, iis/tests/test_unit.py
=> Add better filtering options

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/translate_profile.py
`ddev meta snmp translate-profile` migrates legacy MIB based profiles to the current OID based format. The tool was triggering exceptions when executed over OID based format, as it was expecting string values but was getting dictionaries.
This PR skips OID based format metrics.
Exceptions triggered when QAing https://github.com/DataDog/integrations-core/pull/10353
Testing:
Running `ddev meta snmp translate-profile snmp/datadog_checks/snmp/data/profiles/cisco-nexus.yaml` should not trigger any error.
Running `ddev meta snmp translate-profile snmp/datadog_checks/snmp/data/profiles/cisco-asa.yaml` should not trigger any error.
=> [snmp] Support new profiles without throwing errors in translate-profiles

elastic/assets/dashboards/overview.json
Fix widgets that return number of nodes by grouping by host as there can be multiple instances per node
AGENT-7152
=> Group by host to return number of nodes

.azure-pipelines/changes.yml
The Validations github actions has been running for awhile now. This PR initiates the disabling of Azure validation on Changed/PRs.
Allows tests (on azure) and validations (on github actions w/ annotations) to run in parallel. Previously, if validations failed, the tests never run. This allows two separate jobs to run on the PR.
=> Disable validations in Azure pipelines on PRs

mysql/tests/conftest.py, mysql/tests/test_mysql.py
=> Skip the test, not the fixture

mysql/datadog_checks/mysql/const.py, mysql/metadata.csv
This PR add more useful Galera metrics:
`wsrep_local_state`
`wsrep_replicated_bytes`
`wsrep_received_bytes`
`wsrep_received`
`wsrep_local_cert_failures`
`wsrep_local_state` to determine the Galera state (Synced,Joined,Donor/Desynced,Joining)
`wsrep_received`, `wsrep_replicated_bytes` and `wsrep_received_bytes`  to estimate the gcache size we need to know the amount of data transiting
`wsrep_local_cert_failures` to monitor the "conflicts" that we never want to have (because it refuses commits) on a production cluster
=> add more galera useful metrics for mysql

postgres/datadog_checks/postgres/util.py, postgres/metadata.csv, postgres/tests/test_pg_integration.py
Add a new `postgresql.active_waiting_queries` metric.
`postgresql.waiting_queries` isn't especially useful to track because it includes `idle` backends waiting on client input, thus giving an artificially high number of waiting queries.
Added a new metric instead of changing `waiting_queries` so as not to affect anyone with existing dashboards.
=> Add new metric for waiting queries where state is active

nginx/metadata.csv
Added note for the description of the metric nginx.net.request_per_s. Measure both successful and failed requests.
Adds addition description for the metric nginx.net.request_per_s
Saying that the metric value will include successful and failed requests. As a request doesn't have to be successful in order to be processed.
A customer on a support ticket asked for clarification on the metric description. Wondering if the metric looks at all requests, including failed ones. I reached out to Nginx for support and ended up calling them to clarify the information.
An Nginx request does not have to be successful in order to be processed.
=> Update metadata.csv for nginx.net.request_per_s

nginx/tests/test_unit.py
Adds another test to nginx for when stream metrics are disabled on nginx v7
More testing related to: https://github.com/DataDog/integrations-core/pull/10750
=> Add a test for when stream metrics are disabled on nginx v7

mysql/datadog_checks/mysql/statements.py
This fixes an issue where the query metrics collection would never recover when a monitored mysql instance would be restarted. This would manifest itself by repeated logging of
```
2021-12-07 22:47:52 UTC | CORE | ERROR | (pkg/collector/python/datadog_agent.go:122 in LogMessage) | mysql:e40c6a86aebc5d6f | (statements.py:134) | Unable to collect statement metrics due to an error
File "/~/dd/integrations-core/mysql/datadog_checks/mysql/statements.py", line 113, in collect_per_statement_metrics
rows = self._collect_per_statement_metrics()
File "/~/dd/integrations-core/mysql/datadog_checks/mysql/statements.py", line 138, in _collect_per_statement_metrics
monotonic_rows = self._query_summary_per_statement()
File …
```
=> Fix mysql query metric collection not recovering after database restarts

kubernetes/assets/dashboards/kubernetes_dashboard.json
This removes the kubernetes_state.replicaset.replicas_ready from the IO by node widgets in the Kubernetes Dashboard because this metric is not tagged by host. In the widgets, this metric is averaged by host, which doesn't make sense.
This metric is tagged only by replicaset.
Only the host where the KSM pod runs will show up as a host. If KSM core or a cluster check is used, there will be no host.
A customer reported the widgets are broken when moving to KSM core, because of the reason explained above.
=> Remove kubernetes_state.replicaset.replicas_ready from the IO by node widgets in the Kubernetes Dashboard

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/stats/stats.py
This PR modifies the ddev command `merged-prs`, so in addition to previous PR data, it also gathers information about `category` label and whether the `bugfix\regression` label is present on the PR. It adds that information to the output csv file.
Merged-prs tool is a convenient way to grab information about the merged PRs during the release cycle. New labels are an addition for analysis and it would be good to have them gathered automatically as well.
=> Category and bugfix label gathered with merged-prs stats ddev command

sqlserver/assets/configuration/spec.yaml, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
`MultiSubnetFailover=True` causes a failure on startup because it's an invalid value for that connection string parameter. This updates the example for `connection_string` to use the correct value which is `yes`. 
Customer having issues trying to use `MultiSubnetFailover=true`.
=> Fix wrong example for MultiSubnetFailover in connection_string example

sqlserver/datadog_checks/sqlserver/connection.py
If DSN is set then we need to append to the existing connection string instead of reassigning it.
Follow-up to https://github.com/DataDog/integrations-core/pull/10738
=> fix missing ConnectionRetryCount when DSN set

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/service_checks.py
Added logic to detect invalid characters and sequence to the CI pipeline.
To prevent service names containing invalid characters and sequences from being sync to our backend
Test cases sequences:
```
a_.
a__.
a__..
a__.._
a__..__
b._
b.__
b..__
b_..__
c__
d_
_e
```
Invalid characters on anything that isn't `a-z`, `A-Z`, `0-9`, `_` and `.` 
Validated against integrations-core, extras and marketplace
=> Add validation for invalid characters and sequences for service names

process/assets/configuration/spec.yaml, process/datadog_checks/process/data/conf.yaml.example
Improves notes on the process check configuration to make it clearer that exactly one of `search_string`, `pid` or `pid_file` must be specified.
User confusion.
=> Make process check configuration notes clearer

snmp/assets/monitors/device_down.json, snmp/manifest.json
This recommended monitor is a very basic one that:
- Triggers when an snmp device is down (uniquely identified by `snmp_device` (the ip) and `snmp_namespace`
- Provides a link to the NDM page scoped on this device.
Monitor can be seen [here](https://dd.datad0g.com/monitors/6523705).
Note that the link unfortunately doesn't work on slack, but does on email and events
=> Add SNMP recommended monitor

hyperv/assets/configuration/spec.yaml, hyperv/datadog_checks/hyperv/config_models/defaults.py, hyperv/datadog_checks/hyperv/config_models/instance.py, iis/assets/configuration/spec.yaml, iis/datadog_checks/iis/config_models/defaults.py, iis/datadog_checks/iis/config_models/instance.py
=> Properly hide legacy PDH config

twistlock/tests/conftest.py, twistlock/tests/test_twistlock.py, twistlock/tox.ini
Add a minimal twistlock e2e test to ensure the check is able to run. 
Only testing for one service check(`twistlock.license_ok`) since the check seems to stop after trying to get the license due to the [this line](https://github.com/DataDog/integrations-core/blob/master/twistlock/datadog_checks/twistlock/twistlock.py#L84).
=> Add minimal twistlock e2e test

datadog_cluster_agent/tests/conftest.py, datadog_cluster_agent/tests/test_datadog_cluster_agent.py, datadog_cluster_agent/tox.ini
Add a minimal e2e test for datadog_cluster_agent check
=> Add a minimal e2e test for datadog_cluster_agent check

hudi/manifest.json
Makes the hudi integration public
A new version of hudi was released that supports JMX: https://hudi.apache.org/
=> Make hudi public

sqlserver/datadog_checks/sqlserver/connection.py, sqlserver/datadog_checks/sqlserver/statements.py, sqlserver/tests/conftest.py, sqlserver/tests/test_activity.py, sqlserver/tests/test_connection.py, sqlserver/tests/test_statements.py
Update the `dm_exec_query_stats` query interval (how far we look back for recently executed queries) to be dynamic based on the last time the check ran (Follow-up to https://github.com/DataDog/integrations-core/pull/10810 and https://github.com/DataDog/integrations-core/pull/10763.). Benefits:
* if in production the check is delayed for any reason (i.e. slow query, network slowness, slow host, agent overload), then the query interval may expand beyond the collection interval, which ensures that the query metrics counts are still correct and we don't lose any stats
* integration tests where the collection interval is small (i.e. 100ms) were flaky as they would look back only 100ms, but sometimes the interval between queries was much larger than that, meaning the tests would fail as they'd …
=> use dynamic query stats interval and set common request timeout 

tcp_check/assets/configuration/spec.yaml, tcp_check/assets/service_checks.json, tcp_check/datadog_checks/tcp_check/config_models/defaults.py, tcp_check/datadog_checks/tcp_check/config_models/instance.py, tcp_check/datadog_checks/tcp_check/data/conf.yaml.example, tcp_check/datadog_checks/tcp_check/tcp_check.py, tcp_check/tests/common.py, tcp_check/tests/test_e2e.py, tcp_check/tests/test_integration.py, tcp_check/tests/test_tcp_check.py
Add `multiple_ips` configuration option
When enabled, integration calls `gethostbyname_ex` (https://docs.python.org/3/library/socket.html#socket.gethostbyname_ex) instead of `gethostbyname` (https://docs.python.org/3/library/socket.html#socket.gethostbyname)
A domain can have multiple IPs attached, and `gethostbyname` returns only one of the IPs, whereas `gethostbyname_ex` returns all of them.
So when `multiple_ips` is enabled, we run the check against all the IPs attached to the domain instead of one
Support case
=> Add multiple_ips option and address tag

datadog_checks_base/datadog_checks/base/stubs/aggregator.py
Check that `tags` is not `None` or empty before iterating on it
Caused CI to fail https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=84162&view=logs&j=155efd4a-3db6-57a2-0ce3-7e8c157a4e0a&t=4ad84dea-efb9-5139-10ad-4c7a65d30c32&l=57
=> Don't check empty tag list

sqlserver/tests/conftest.py, sqlserver/tests/test_statements.py, sqlserver/tox.ini
Use a new "self-healing connection" (instead of a raw pyodbc connection) for statement metrics & plans tests. There is some inexplicable flakiness that happens during these tests that causes a connection to enter a bad state and no longer be able to make queries reliably. This ensures the connection can be recreated automatically in order to allow the test to proceed.
Also pin the sql server docker versions instead of allowing them to use latest. The latest image that came out was also causing failures. 
Flaky tests!!!
=> use self healing connection in tests

sqlserver/assets/configuration/spec.yaml, sqlserver/datadog_checks/sqlserver/config_models/instance.py, sqlserver/datadog_checks/sqlserver/statements.py, sqlserver/tests/test_statements.py
Set a collection deadline to make sure we stop collecting plans when it's time for the next collection.
If we find a large number of plans during a single collection run and the loading of those plans takes longer than usual, the total time required to collect all of the plans can take longer than the collection interval, which means the following run of the interval will be delayed. 
This ensures we stop collecting plans in time for the next collection run.
=> Add `enforce_collection_interval_deadline` option to set plan collection deadline

sqlserver/datadog_checks/sqlserver/statements.py
Improves the performance of plans by looking up by the plan handle. This is a more efficient lookup which will cut down the lookup time of each plan by extracting the first plan handle from `dm_exec_query_stats`.
It also raises the TTL of plan caches, since these are identical plans and plan flips will be automatically detected due to the new plans being uncached.
Some high-cardinality workloads have long-running check run times. We were able to identify the plan lookup as the bottleneck.
=> Improve plan lookup performance

kube_apiserver_metrics/metadata.csv
Update metadata.csv for the `kube_apiserver_metrics` check:
- indicate `kube_apiserver.etcd_*` metrics are in alpha
- be consistent in how we report alpha and deprecated metrics
- use articles consistently
Better information for user
=> [kube_apiserver_metrics] Make alpha and deprecated metrics comments consistent

external_dns/tests/conftest.py, external_dns/tests/test_external_dns.py, external_dns/tox.ini
Add a minimal external_dns e2e test to ensure the check is able to run
=> add minimal e2e for external_dns check

vsphere/tests/test_e2e.py, vsphere/tox.ini
Add a minimal vsphere e2e test to ensure the check is able to run
=> add minimal e2e test for vsphere

sqlserver/datadog_checks/sqlserver/connection.py
Apply `SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED` to all agent connections to SQL Server by default to mitigate risk of blocking others or being blocked by others.
From [the docs](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-transaction-isolation-level-transact-sql): *Transactions running at the READ UNCOMMITTED level do not issue shared locks to prevent other transactions from modifying data read by the current transaction. READ UNCOMMITTED transactions are also not blocked by exclusive locks that would prevent the current transaction from reading rows that have been modified but not committed by other transactions.*
=> use read uncommitted isolation level to remove blocking risk

datadog_checks_base/CHANGELOG.md, datadog_checks_base/datadog_checks/base/__about__.py, ibm_was/CHANGELOG.md, ibm_was/datadog_checks/ibm_was/__about__.py, requirements-agent-release.txt, sqlserver/CHANGELOG.md, sqlserver/datadog_checks/sqlserver/__about__.py
Updates the check versions for datadog_checks_base, ibm_was, and sqlserver, which were released from the `7.33.x` release branch. 
https://github.com/DataDog/integrations-core/pull/10905
https://github.com/DataDog/integrations-core/pull/10908
=> Update check versions from release 7.33.x

datadog_checks_dev/datadog_checks/dev/tooling/configuration/spec.py
Handle nested overrides in config specs where the template is renamed
We want to override the `extra_metrics` field in IIS and other windows integrations
Tested new behavior on windows_performance_counters and iis
=> Handle nested template name overrides in config specs

mysql/datadog_checks/mysql/statements.py, mysql/tests/test_statements.py
This adds mysql_version to the query metrics payloads. 
Having the mysql version with query metrics is useful and it's more consistent with how we also have it for sqlserver and postgres.
=> Add mysql_version and mysql_flavor to dbm query metrics payloads

datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/setup.py
This is the version that will ship on 7.33 so it's the first one we can guarantee not to have the log4j issue.
Checks updated on: https://github.com/DataDog/integrations-core/pull/10926
=> Bump base check requirement for JMX template

mysql/README.md
Replace `localhost` with `%`.
**Describe what happened:**
I've tried Agent based MySQL integration according to this [setup guide](https://docs.datadoghq.com/integrations/mysql/?tab=host#setup).
I could not create the connection between Agent and MySQL when I use `'datadog'@'localhost'` or `'datadog'@'127.0.0.1'`.
Therefore, I want to suggest to use `'datadog'@'%'` to prevent the connection error.
**Describe what you expected:**
No one faces the connection error when reading the [setup guide](https://docs.datadoghq.com/integrations/mysql/?tab=host#setup).
**Steps to reproduce the issue:**
Execute `docker compose up` after preparing following files.
`docker-compose.yaml`
```yaml
version: "3.8"
services:
agent:
image: gcr.io/datadoghq/agent:7
environment:
DD_API_KEY: "" # TODO: set your api …
```
=> Use `%` for MySQL integration setup document

active_directory/setup.py, aspdotnet/setup.py, dotnetclr/setup.py, elastic/setup.py, exchange_server/setup.py, nginx/setup.py
Bump base package for integration broken in the nightly base CI
* Windows integration bumping to `23.3.2` for windows performance counter
* `elastic` to `15.0.0` for `assert_metrics_using_metadata`
* `nginx` to `23.1.1` for `remove server from generic tag list`
=> Bump base package dependency

mysql/README.md
Follow-up to https://github.com/DataDog/integrations-core/pull/10861
Update to match what we say in https://docs.datadoghq.com/database_monitoring/setup_mysql/selfhosted/
=> add a note on how to restrict datadog user login to specific hosts

sqlserver/datadog_checks/sqlserver/connection.py, sqlserver/tests/test_connection.py
Wrap `yield` with try/finally in connection & cursor context manager to avoid leaving a dangling open connection in case of a database or application exception getting thrown.
=> fix dangling connection on unhandled exception bug

container/metadata.csv
Remove `cpu.shares` from doc as removed from check: [#9969](https://github.com/DataDog/datadog-agent/pull/9969)
Align doc
=> Remove `cpu.shares` from documentation as removed from check

.azure-pipelines/templates/test-all.yml
- Don't validate on CI on PRs to the base check
- We removed validation on Azure pipelines in most places but not in the specific case of making a PR to the base check
- Validation failures for other checks shouldn't block merging changes to the base check
Later investigate removing this entire block
```
${{ if eq(check.checkName, 'datadog_checks_base') }}:
validate: false
validate_changed: all
```
=> Don't run validations on CI on PRs to the base check

postgres/assets/configuration/spec.yaml, postgres/datadog_checks/postgres/config.py, postgres/datadog_checks/postgres/config_models/defaults.py, postgres/datadog_checks/postgres/config_models/instance.py, postgres/datadog_checks/postgres/data/conf.yaml.example, postgres/datadog_checks/postgres/postgres.py, postgres/tests/test_pg_integration.py
Adds a new optional config (`display_hostname`) to set the displayed hostname in Postgres. This mechanism overrides the resolved db hostname.
There are some unique cases where the resolved hostname does not (or should not) match the desired hostname.
e.g A local proxy proxying ports to multiple instances or the host is an IP address.
=> Add the option to set a reported hostname (Postgres)

eks_fargate/README.md
Provide instructions on how to get the `kube_cluster_name` tag set on the K8s metrics when in EKS Fargate. As these metrics won't come in with that set otherwise. The normal `DD_CLUSTER_NAME` strategy does not currently work as this is a "host" tag but Fargate is a "hostless" setup.
Additionally fixed two links going to the wrong page. As for reference links 17-19
```
[17]: https://docs.datadoghq.com/developers/dogstatsd/
[18]: http://docs.datadoghq.com/tracing/setup
[19]: https://app.datadoghq.com/containers
```
https://datadoghq.atlassian.net/browse/CONS-4391
=> Add DD_TAGS section for cluster name, fix links

datadog_checks_base/datadog_checks/base/utils/db/utils.py, datadog_checks_base/datadog_checks/base/utils/tracing.py, datadog_checks_base/tests/base/utils/test_tracing.py
* set `service` to be `{integration name}-integration` (i.e. `sqlserver-integration`). Previously the service name was left empty meaning we would get default service names like `unnamed-python-service`.
* add tracing for `DBMAsyncJob.run_job`. It uses the same `run` operation name as the main check run method, meaning when that operation name is selected, the list of resources will show `run` with an additional entry for each `DBMAsyncJob`.
Improve APM instrumentation for integrations.
=> improve common tracing instrumentation

datadog_checks_base/datadog_checks/base/checks/openmetrics/mixins.py, datadog_checks_base/tests/base/checks/openmetrics/test_openmetrics_base_check.py
Change the meaning of the default value of the `bearer_token` parameter of the OpenMetrics based checks.
The default behaviour if not set is now to send the bearer token to secure `https` endpoints and not to clear text `http` endpoints.
This is useful for all the checks that are leveraging the `possible_prometheus_urls` to try to autodetect what is the usable endpoint url based on a list of commonly used ones.
This is the case for the Kubernetes control plane components checks.
* `kube_controller_manager`: #10708
* `kube_scheduler`: #10709
* `kube_apiserver_metrics`: #10772
=> Add new `tls_only` choice to the `bearer_token` parameter that sends the bearer token only to secure HTTPS endpoints

kube_controller_manager/assets/configuration/spec.yaml, kube_controller_manager/datadog_checks/kube_controller_manager/data/auto_conf.yaml
Change the default behaviour of the auto-configuration of the `kube_controller_manager` check.
By default, when trying all the possible endpoints, the bearer token will be sent only to secure `https` endpoints.
Make the check work out of the box without leaking the token on an insecure connection on both clusters where only the insecure `http` endpoint is available and on clusters where only the secure `https` endpoint is available.
Leverages #10706
=> Update the default value of the `bearer_token` parameter to send the bearer token only to secure https endpoints by default

kafka_consumer/datadog_checks/kafka_consumer/legacy_0_10_2.py, kafka_consumer/datadog_checks/kafka_consumer/new_kafka_consumer.py, kafka_consumer/tests/test_kafka_consumer.py
Call correct method when sending events
It was renamed in https://github.com/DataDog/integrations-core/pull/9626/s but the usages were not updated
Investigate checking for this in style validation
=> Call correct method when sending events

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/config.py
Make the CI print its expectation when an example file isn’t in sync with the spec.
[Before](https://github.com/DataDog/integrations-core/runs/4648947989?check_suite_focus=true):
[After](https://github.com/DataDog/integrations-core/runs/4649184862?check_suite_focus=true):
=> Print the diff when the example file isn’t in sync with the spec

sqlserver/datadog_checks/sqlserver/statements.py
Adds the query plan handle to the plan event.
This will allow users to use the plan outside of Datadog by looking it up directly in the DB.
=> Add plan handle to the plan event 

.azure-pipelines/scripts/sqlserver/windows/40_install_sqlserver.py, .azure-pipelines/scripts/sqlserver/windows/55_setup_sqlserver.bat, sqlserver/tests/common.py, sqlserver/tests/compose-windows/Dockerfile, sqlserver/tests/compose-windows/docker-compose.yaml, sqlserver/tests/compose-windows/setup.sql, sqlserver/tests/compose-windows/sqlserver-entrypoint.ps1, sqlserver/tests/compose-windows/sqlserver-setup.ps1, sqlserver/tests/compose/setup.sh, sqlserver/tests/conftest.py, sqlserver/tests/test_activity.py, sqlserver/tests/test_connection.py, sqlserver/tests/test_integration.py, sqlserver/tests/test_statements.py, sqlserver/tests/test_unit.py, sqlserver/tests/utils.py, sqlserver/tox.ini
Stop running SQL Server directly on the Azure Test VM in favor of running it in Windows docker containers (see DataDog/docker-library#76). We now test on SQL Server Windows Versions 2016, 2017, and 2019.
Update all integration tests (except for those that are truly platform specific) to now run on all docker containers, both linux and windows. Previously only a small set of integration tests were being run on Windows.
Improve Windows test coverage.
=> run SQL Server in docker for windows integration tests

docker_daemon/metadata.csv
Adds documentation for the `docker.cpu.limit` metric that was introduced in https://github.com/DataDog/datadog-agent/pull/5716
When monitoring CPU usage in ECS the `docker.cpu.usage` metric can be nonsense unless it's combined with `docker.cpu.limit`, but that metric isn't documented anywhere, so I only figured it out by reading the docker check implementation.
=> Document docker.cpu.limit metric

openmetrics/README.md
Fix the documentation of the `metrics` parameter of the Openmetrics v2 check.
It’s a regular expression and not a glob pattern as it used to be with the the Prometheus v1 check.
With the Prometheus v1 check, `metrics` seemed to be a glob pattern and this configuration was working:
```
=== openmetrics check ===
Configuration provider: kubernetes
Configuration source: kubelet:containerd://543f4a8a2170333ca3efcd9fbb20c41f9ace1ea9e793925fb44a60ce71579265
Instance ID: openmetrics:openmetrics_gen:8329dd0b4377b5be
metrics:
- '*'
namespace: openmetrics_gen
prometheus_url: http://10.248.7.124:8080/metrics
```
But this Openmetrics v2 configuration produces the following error while trying to compile the regular expression:
```
=== openmetrics check ===
Configuration provider: kubernetes …
```
=> Fix the documentation of the `metrics` setting

eks_fargate/README.md
Fixes the `auto_create_group` value from `On` to `true`. See [docs](https://docs.fluentbit.io/manual/pipeline/outputs/cloudwatch)
Working to get EKS Fargate logs into DD. Having copy/pasted this ConfigMap, kubectl wouldn't apply it, responding with an error like "auto_create_group value invalid"
To truly get  EKS Fargate logs working, I had to do a bit more, mostly outlined in the [EKS Fargate Logging docs](https://docs.aws.amazon.com/eks/latest/userguide/fargate-logging.html). Most specifically, I needed to create a policy giving the pod execution role abilities to deal with Cloudwatch (write entries, create log groups/streams, etc). I'm happy to write these steps down in this PR if y'all feel it's necessary to improve the documentation.
=> [docs] EKS Fargate Logging Documentation: Fix `auto_create_group` value in FluentBit ConfigMap

apache/assets/service_checks.json, elastic/assets/service_checks.json, lighttpd/assets/service_checks.json, mcache/assets/service_checks.json, mongo/assets/service_checks.json, mysql/assets/service_checks.json, nginx/assets/service_checks.json, pgbouncer/assets/service_checks.json, sqlserver/assets/service_checks.json, tokumx/assets/service_checks.json, windows_service/assets/service_checks.json, zk/assets/service_checks.json
The `groups` field is used as default grouping in service checks monitors. For some specific integrations we add the `server` tag in this grouping in the backend code to tackle edge cases where the `host` tag is replaced by `server`.
This PR is meant to reflect these edge cases in the configuration of the integration, in order to deprecate this in the backend.
Remove some edge cases in the backend code, and simplify the evaluator code.
=> Add `server` default group for all monitor special cases

lighttpd/assets/service_checks.json
The lighttpd service check name is currently `lighttpd.can_connect` but the one use for monitor configuration is `lighthttpd.can_connect`. This means the default grouping is not correct right now.
Currently, this impacts 1 monitor.
Keep the codebase sane
=> Fix lighttpd service check name for monitors

activemq/setup.py, cassandra/setup.py, confluent_platform/setup.py, hazelcast/setup.py, hive/setup.py, hivemq/setup.py, hudi/setup.py, ignite/setup.py, jboss_wildfly/setup.py, kafka/setup.py, presto/setup.py, solr/setup.py, sonarqube/setup.py, tomcat/setup.py, weblogic/setup.py
This is the version that will ship on 7.33 so it's the first one we can guarantee not to have the log4j issue.
Template updated on:
https://github.com/DataDog/integrations-core/pull/10925
=> Bump base check dependency

sqlserver/datadog_checks/sqlserver/statements.py
Avoid accidental mutation of the set of plan obfuscation parameters.
=> Use a frozenset for plan obfuscation parameters

snmp/datadog_checks/snmp/data/profiles/f5-big-ip.yaml, snmp/tests/test_e2e_core_metadata.py
Remove `os_hostname` from f5 profile it is usually redundant with device name
TODO: REMOVE https://github.com/DataDog/integrations-core/blob/f152035cc90e98c1245a61cc786d9d814685e8e5/snmp/tests/test_e2e_core_metadata.py#L82
=> Remove `os_hostname` from f5 profile since redundant with device name

snmp/tests/conftest.py
Disable check runners when running SNMP Listener e2e tests
When running agent check command, in addition of the [check.Check.Run()](https://github.com/DataDog/datadog-agent/blob/582e59337b8d3bc5716171f3a5fea6cf250499be/cmd/agent/common/commands/check.go#L454) call made by agent check, it seems check runners workers (default 4) are added ([common.LoadComponents()](https://github.com/DataDog/datadog-agent/blob/582e59337b8d3bc5716171f3a5fea6cf250499be/cmd/agent/common/commands/check.go#L143)) and run in background.
Looks like this can cause checks being run more times than expected (direct call to check.Check.Run() is expected, but checks being run in background might not be expected)
=> Disable check runners when running SNMP Listener e2e tests

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/models.py, datadog_checks_dev/datadog_checks/dev/tooling/utils.py
- Don't add new line to license header
- Check for equality of generated files regardless of generation of new lines
ddev tests are failing because new files with only the header failed style- they had an extra new line
Tested a few cases where adding a new line to a generated file still fails validation
=> Don't add new line to license header

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/service_checks.py, mesos_master/assets/service_checks.json
Attach `mesos_master.can_connect` service check to `Mesos Master` instead of `Mesos` (== `Mesos Slave`)
=> Migrate mesos master service check

datadog_checks_dev/datadog_checks/dev/tooling/commands/create.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/manifest.py, datadog_checks_dev/datadog_checks/dev/tooling/create.py, datadog_checks_dev/datadog_checks/dev/tooling/manifest_validator/v2/migration.py
Adds support for creating new checks with Manifest V2 for Marketplace and other apps via CLI option `--manifest-v2`.
This takes the module previously created to migrate from V1 to V2, and uses that as part of the creation process.  This should help keep the migration code in sync as changes occur over time.
With ManifestV2 now the default (and only) option for Marketplace integrations, this will streamline the process and avoid the need for manual migrations afterwards.
Adding the additional optional argument, should make it easier for tile-only creations to be made on integrations-extras as well.
=> Add support for manifest V2 to "ddev create"

spark/datadog_checks/spark/spark.py, spark/tests/fixtures/metrics_json, spark/tests/test_spark.py
Ensures that we don't submit query name tag if query is a uuid
QA for the addition of the `query_name` tag
=> Don't submit query name tag if query is a uuid

kubernetes/assets/dashboards/kubernetes_dashboard.json
* Add `kube_stateful_set` and `kube_replica_set` filtering variable.
* remove useless filter variables from queries.
* add missing filter variables on queries.
* improve OOTB Kubernetes dashboard
=> fix(kubernetes): OOTB dashboard metrics filtering improvement

ecs_fargate/README.md
Changes the formatting for the instruction to set the ECS Fargate working directory on Windows. It currently shows up in the public docs as `“C:"` when it should be `C:\`. Using `C:` will result in an entrypoint error:
```
[ENTRYPOINT][ERROR] directory_iterator::directory_iterator: The system cannot find the path specified.: "entrypoint-ps1"
```
Support ticket
=> [docs] Fix ECS Fargate Windows working directory format

mesos_slave/assets/service_checks.json
Updates the deprecated `mesos.can_connect` service check name to avoid conflicting with the current service check name.
Fix CI
=> Update deprecated can_connect service check name

kubelet/datadog_checks/kubelet/kubelet.py
Do not drop the first kubelet eviction event.
When the kubelet performs its first eviction, it creates a new time series to count the total number of eviction performed since the kubelet start:
```
kubelet_evictions{eviction_signal="nodefs.available"} 1
```
But before this first eviction, the Openmetrics endpoint of the kubelet didn’t show the time serie.
As a consequence, the counter aggregator has no previous value to compare with this new value and it doesn’t emit a counter of `1` to represent this first eviction.
This issue can be fixed thanks to the `flush_first_value` parameter.
But if we were unconditionally setting `flush_first_value` to `True`, we would have an issue when the agent is rolled out.
If the eviction kubelet counter is non-null when an agent restart, the agent mustn’t …
=> Do not drop the first kubelet eviction event

datadog_checks_base/datadog_checks/base/utils/db/utils.py, datadog_checks_base/tests/base/utils/db/test_util.py
We found that the json decoder (`json.loads()`) does not throw an error for a string integer (e.g. '1'). This causes unwanted behavior and this PR aims to fix that.
How?
Because we know we only want to load json when a particular option is enabled, we use that to determine the action rather than always decoding.
=> datadog_checks_base: Fix obfuscate_sql_with_metadata wrapper not handling json.loads() edge case

.azure-pipelines/templates/run-tests.yml, datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py
Marketplace CI will check for code coverage, but it doesn't use codecov. This PR allows codecov report to be generated only on core integrations. 
Add coverage for marketplace PRs.
See https://github.com/DataDog/marketplace/pull/262
=> Set coverage report to only core checks

sqlserver/datadog_checks/sqlserver/sqlserver.py
Include the SQL Server DBMS type for the obfuscator.
Relevant PR: https://github.com/DataDog/datadog-agent/pull/10440
Why is the type for SQL Server not "sqlserver"?
- Some of our tracer clients report the type based off the [open-telemetry ](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#connection-level-attributes) specifications, so to have the obfuscator be compatible with most of our stuff, we should follow it.
=> sqlserver: Indicate DBMS type in obfuscator

postgres/datadog_checks/postgres/config.py
Include the Postgres DBMS type for the obfuscator.
Relevant PR: DataDog/datadog-agent#10440
=> postgres: Indicate DBMS type in obfuscator

mysql/datadog_checks/mysql/config.py
Include the MySQL DBMS type for the obfuscator.
Relevant PR: DataDog/datadog-agent#10440
=> mysql: Indicate DBMS type in obfuscator

datadog_checks_dev/datadog_checks/dev/tooling/commands/env/check.py, datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py, datadog_checks_dev/datadog_checks/dev/tooling/e2e/local.py
Add discovery options to check command
Needed for e2e testing listeners (snmp listener) that schedules multiple check instances.
Needed for https://github.com/DataDog/integrations-core/pull/11055
Agent PR: https://github.com/DataDog/datadog-agent/pull/10448
=> Add discovery options to ddev check command

snmp/tests/test_e2e_snmp_listener.py
Add discovery_min_instances to SNMP Listener test
More reliable test.
Fix e2e failures like this:
https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=86177&view=logs&jobId=475ea3e3-a9fc-55a6-2e22-b5a67273560a&j=475ea3e3-a9fc-55a6-2e22-b5a67273560a&t=1a1f47dd-bcf6-5ffb-3d85-8c5dbec3db65
More info about discovery_min_instances: https://github.com/DataDog/datadog-agent/pull/10448
=> Add discovery_min_instances to SNMP Listener test

iis/README.md
Provide additional information for user to add ddagentuser permissions for logs files and link to the [Permission issues tailing log files](https://docs.datadoghq.com/logs/guide/log-collection-troubleshooting-guide/#permission-issues-tailing-log-files) page
https://datadog.zendesk.com/agent/tickets/582878
https://datadog.zendesk.com/agent/tickets/594740
https://datadog.zendesk.com/agent/tickets/606490
=> CHANGELOG entry: Added a note on IIS Logs Permissions

snmp/datadog_checks/snmp/data/profiles/f5-big-ip.yaml, snmp/metadata.csv, snmp/tests/test_e2e_core_vs_python.py, snmp/tests/test_profiles.py
Add `sysMultiHostCpuUsageRatio` to BIG-IP profile.
I think Getting CPU usage metric is common use case,
so adding `sysMultiHostCpuUsageRatio` to the example would be useful.
https://oidref.com/1.3.6.1.4.1.3375.2.1.7.5.2.1.11
=> Add `sysMultiHostCpuUsageRatio` to BIG-IP profile

network/datadog_checks/network/network.py, network/metadata.csv, network/tests/common.py
Add saturation metrics for network.
We currently gather utilization and error metrics of network (bytes received and sent, number of packets) but not the saturation metrics (number of dropped packets).
Having this additional data is needed to apply the USE Method [1] for system performance analysis.
[1] https://www.brendangregg.com/usemethod.html
=> Add saturation metrics for network

datadog_checks_base/datadog_checks/base/utils/tracing.py
Remove the explicit `self` argument of the tracing wrapper method ; and manually check if it's here
Kubernetes_state failing since #10947 ; as we explicitly expect a self argument in the wrapped method
=> Fix tracing_method using self argument

.azure-pipelines/templates/run-tests.yml, snmp/tests/common.py, snmp/tests/test_e2e_core.py, snmp/tests/test_e2e_core_metadata.py, snmp/tests/test_e2e_core_vs_python.py, snmp/tests/test_e2e_snmp_listener.py
Fix tests by excluding `agent_version` tag
`agent_version` might have different value in e2e depending on the agent version
An alternative is to fetch the Agent Version from the docker agent and assert agent_version, but there is not that much value to test the agent version (we already have some unit tests in agent-core testing the agent_version tags).
=> Fix tests by excluding `agent_version` tag

coredns/README.md, coredns/assets/configuration/spec.yaml, coredns/datadog_checks/coredns/check.py, coredns/datadog_checks/coredns/common.py, coredns/datadog_checks/coredns/config_models/defaults.py, coredns/datadog_checks/coredns/config_models/instance.py, coredns/datadog_checks/coredns/coredns.py, coredns/datadog_checks/coredns/data/auto_conf.yaml, coredns/datadog_checks/coredns/data/conf.yaml.example, coredns/datadog_checks/coredns/metrics.py, coredns/metadata.csv, coredns/tests/common.py, coredns/tests/conftest.py, coredns/tests/fixtures/metrics_12.txt, coredns/tests/fixtures/metrics_18.txt, coredns/tests/test_check.py, coredns/tests/test_e2e.py, coredns/tox.ini
This change adds support for OpenMetricsBaseCheckV2 and enables the check to use it by default. OpenMetrics V1 and V2 can be switched by using either `prometheus_url` for OpenMetrics V1 or `openmetrics_endpoint` for OpenMetrics V2.
OpenMetrics V2 collects different metrics compared to OpenMetrics V1.
Here's what changes between OpenMetrics V1 and OpenMetrics V2:
* All `*.sum` and `*.count` metrics have been changed from gauge to monotonic_count (except for `coredns.cache_size.count`)
* New metrics are added
=> Add support for OpenMetricsBaseCheckV2

sqlserver/datadog_checks/sqlserver/const.py, sqlserver/datadog_checks/sqlserver/metrics.py, sqlserver/datadog_checks/sqlserver/sqlserver.py, sqlserver/metadata.csv, sqlserver/tests/common.py
This change adds file IO metrics for all files on the system. 
There are already a few different metrics which track files, but these are either tagged by things which are not super useful or only available as custom metrics.
* Custom metrics only exposing file I/O stats: https://github.com/DataDog/integrations-core/blob/master/sqlserver/datadog_checks/sqlserver/metrics.py#L261-L268. These do not contain the logical or physical name, however, and they require manual configuration by the customer.
* Master files are the most useful because they are cross-database views: https://github.com/DataDog/integrations-core/blob/master/sqlserver/datadog_checks/sqlserver/metrics.py#L414-L424, but tags are `database`, `file_id` (not super useful), `type`, `file_location`, `database_files_state_desc`. …
=> Add improved database file IO metrics and tags

http_check/datadog_checks/http_check/adapters.py
This change adds a try/except block to the urllib3 import statement for the `match_hostname` method to account for the package location change in [urllib3 v1.26.8](https://github.com/urllib3/urllib3/blob/1.26.8/CHANGES.rst#1268-2022-01-07). 
> Changed location of the vendored ssl.match_hostname function from urllib3.packages.ssl_match_hostname to urllib3.util.ssl_match_hostname to ensure Python 3.10+ compatibility after being repackaged by downstream distributors.
It first tries to import from the new location and falls back on the old location if urllib3 < v1.26.8 is being used.
Fix broken CI.
=> Fix urllib3 import statement

LICENSE-3rdparty.csv, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, http_check/datadog_checks/http_check/adapters.py, http_check/requirements.in
Adds urllib3 as a dependency and pins version to 1.26.8
=> Add urllib3 as dependency

cockroachdb/setup.py
CockroachDB recently added OpenMetrics V2 support and uses [custom transformers](https://github.com/DataDog/integrations-core/pull/10753), which requires base package 23.4.0
=> Bump base package

LICENSE-3rdparty.csv, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, http_check/datadog_checks/http_check/adapters.py, http_check/requirements.in
Backports PR #11069 to 7.33.x for rc14.
**Add urllib3 as dependency (#11069)**
* add urllib3 as dependency, remove try/catch
* sync deps
* sync licenses
(cherry picked from commit 3ef05627440c4a4977d9402f22eef7fb3090752d)
=> Backport (#11069) to rc14

.gitlab-ci.yml
Exports `RELEASE_BRANCH` as an environment variable so that it is accessible in the `trigger_agent_build.py` gitlab CI script. 
This should fix this error:
```
File "/trigger_agent_build.py", line 7, in <module>
RELEASE_BRANCH = os.environ['RELEASE_BRANCH']
File "/usr/lib/python3.9/os.py", line 679, in __getitem__
raise KeyError(key) from None
KeyError: 'RELEASE_BRANCH'
```
Fix broken manual integration release from the release branch.
I'm not sure if any additional variables should be exported as env variables. I'm assuming the other the env variables referenced in the scripts are already available as secrets in the gitlab CI.
=> Export release_branch as an env variable

datadog_checks_base/datadog_checks/base/utils/db/utils.py, datadog_checks_base/tests/base/utils/db/test_util.py
Fixes a bug where the SQL obfuscator attempts to obfuscate a None value.
Came across a scenario where this could happen.
Log: `Failed to obfuscate query 'None': argument 1 must be str, not None`
This will require a new base version and three follow up PRs to update the following integrations:
- MySQL
- SQL Server
- Postgres
=> datadog_checks_base: Fix obfuscate_sql_with_metadata query being None

coredns/assets/configuration/spec.yaml, coredns/datadog_checks/coredns/config_models/validators.py, coredns/datadog_checks/coredns/data/auto_conf.yaml, coredns/datadog_checks/coredns/data/conf.yaml.example
https://github.com/DataDog/integrations-core/pull/11024
1. `metrics` is used by the v2 check itself
2. no indication of required fields at runtime
3. `tags` previously had no special placement
=> Fix example config

.gitlab-ci.yml
Ensure `RELEASE_BRANCH` env variable is defined in `.gitlab-ci.yml` prior to running `trigger_agent_build.py` script.
Fix the key error in `trigger_agent_build.py` script to allow the release manual job to proceed
=> Ensure RELEASE_BRANCH env variable is defined

coredns/assets/configuration/spec.yaml, coredns/datadog_checks/coredns/data/auto_conf.yaml
Fixes bug where `openmetrics_endpoint` was disabled in the auto_conf.yaml
QA for https://github.com/DataDog/integrations-core/pull/11024
=> Enable openmetrics_endpoint in auto_conf.yaml

weblogic/datadog_checks/weblogic/data/metrics.yaml, weblogic/metadata.csv
- Changes the type of some weblogic metrics to `monotonic_count`
- These metrics are always increasing
QA for weblogic
This is a breaking change, but weblogic has not been officially released with an agent yet, so the impact is minimal.
=> Change submission type of some metrics to `monotonic_count`

.github/workflows/changelog-label-check.yml
Using `changelog/Changed` label on a pull request will bump major version of the integration in the next release, and it usually means it introduces a breaking change.
Sometimes people are using `changelog/Changed` when they should be using `changelog/Fixed` (bumping patch version).
Comment is only posted when `Changed` is added and it's the only one attached to the PR.
=> Comment on changelog/changed label

datadog_checks_base/datadog_checks/base/checks/openmetrics/base_check.py
Provide a better user feedback when an `openmetrics`-based check leveraging the `possible_prometheus_urls` parameter fails to connect to all the possible endpoints.
Kubernetes components used to expose an unauthenticated plain http openmetrics endpoint in oldest versions.
They now expose an authenticated secure https endpoint in more recent versions.
By default, now, they only bind the loopback interface on `127.0.0.1` which is not accessible from an agent pod not started with `hostNetwork: true`. But they can be explicitly configured to bind `0.0.0.0` to be visible from non-`hostNetwork: true` agent pods.
Because of this variety of setups, in order to work out-of-the-box on as much setups as possible, the Kubernetes control-plane components checks are trying several possible endpoints at …
=> openmetrics/base: provide a better user feedback in case of connectivity issue

azure_iot_edge/tests/test_e2e.py, spark/tests/test_spark.py
Migrates spark integration tests to use `dd_run_check`.
QA for https://github.com/DataDog/integrations-core/pull/11015
=> Use dd_run_check for tests

snowflake/README.md, snowflake/assets/configuration/spec.yaml, snowflake/datadog_checks/snowflake/data/conf.yaml.example
Snowflake integration does not currently include details that explain what specific metrics are collected by default. This information is not clearly defined in our docs or the example `conf.yaml` file today. 
I was able to find the correct set of default metrics in the check code: https://github.com/DataDog/integrations-core/blob/master/snowflake/datadog_checks/snowflake/config.py#L15-L20
To add additional clarity and prevent confusion during setup.
=> Improve documentation for metric groups

kube_scheduler/assets/configuration/spec.yaml, kube_scheduler/datadog_checks/kube_scheduler/data/auto_conf.yaml
Set `ssl_verify: false` in `conf.d/kube_scheduler.d/auto_conf.yaml`.
The goal of the default configuration in `auto_conf.yaml` files is to make as much checks as possible work out of the box.
With Kubernetes, it’s not uncommon to have setups using self-signed certificates or certificates signed by CA the cert of which is not available inside the datadog agent container. In order to show as much value as possible with the minimum of user configuration, we can disable ssl certificate validation.
That’s already what we do for the checks of other Kubernetes control plane components. Ex for `kube_controller_manager`: https://github.com/DataDog/integrations-core/blob/3616496318dae81470aa66a6c5e2c822a1a1b88e/kube_controller_manager/datadog_checks/kube_controller_manager/data/auto_conf.yaml#L43 …
=> kube_scheduler: do not validate ssl certificate by default with auto-conf

mysql/tests/test_statements.py
8.0.28 released a new consumer for CPU time: 
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-28.html
This PR addresses the tests where it is expected but not available on newer versions.
=> Fix test to add events_statements_cpu consumer for the correct MySQL versions

kube_proxy/datadog_checks/kube_proxy/kube_proxy.py, kube_proxy/tests/test_kube_proxy_1_21_1.py
Removes network_programming metric for now as it results in a high number of tags.
Related to https://github.com/DataDog/integrations-core/pull/11052
=> Remove new kube proxy metric with high cardinality

mysql/datadog_checks/mysql/const.py, mysql/metadata.csv, mysql/tests/variables.py
Add following metrics:
- `mysql.performance.prepared_stmt_count`
- `mysql.performance.max_prepared_stmt_count`
`mysql.performance.prepared_stmt_count` is to get the current number of prepared statements.
https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Prepared_stmt_count 
`mysql.performance.prepared_stmt_count` is to get the total number of prepared statements in the server.
https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_max_prepared_stmt_count
=> Add prepared_stmt_count metrics to mysql integration

snowflake/assets/configuration/spec.yaml, snowflake/datadog_checks/snowflake/check.py, snowflake/datadog_checks/snowflake/config.py, snowflake/datadog_checks/snowflake/config_models/defaults.py, snowflake/datadog_checks/snowflake/config_models/instance.py, snowflake/datadog_checks/snowflake/data/conf.yaml.example, snowflake/tests/test_snowflake.py, snowflake/tests/test_unit.py
Add `token_path` config option so the token can be refreshed at each check run
Feature request to be able to rotate tokens, vault integration does something similar https://github.com/DataDog/integrations-core/blob/3616496318dae81470aa66a6c5e2c822a1a1b88e/vault/datadog_checks/vault/vault.py#L320
Password is actually not required
=> Add token_path config option

snowflake/datadog_checks/snowflake/check.py, snowflake/datadog_checks/snowflake/config.py, snowflake/tests/test_unit.py
An instance can be configured to run custom queries only, so `metric_groups` can be set as empty
=> Fix configuration error for custom queries

.github/CODEOWNERS
@djmitche pointed out on [this PR](https://github.com/DataDog/integrations-core/pull/11046) that agent-core should not be flagged for review on dbm owned files in the `datadog_checks_base`. In reviewing the `CODEOWNERS`, it looks like this was already the intention but that wasn't done correctly. I used [codeowners](https://github.com/hmarr/codeowners) to evaluate the codeowner rules and figured out that the problem was the ordering. Since the last matching rule wins, we need to have the defaults/fallbacks earlier and the more specific rules lower down. 
Taking the files modified in https://github.com/DataDog/integrations-core/pull/11046 as a test, I previously got:
```
codeowners datadog_checks_base/tests/base/utils/db/test_db_statements.py …
```
=> Fix CODEOWNERS Rules not attributing correct ownership of base dbm files

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/models.py
Don't overwrite year in license header when generating files
Follow up to https://github.com/DataDog/integrations-core/pull/11003, we also don't want to update the year when the config has changed
=> Don't overwrite year in license header when generating files

haproxy/tests/conftest.py, haproxy/tox.ini
QA for https://github.com/DataDog/integrations-core/pull/10796
The change has been introduced in 2.4.9
Also removing EOLed version from tox
=> Be more precise with version testing

confluent_platform/datadog_checks/confluent_platform/data/metrics.yaml, confluent_platform/metadata.csv, confluent_platform/tests/metrics.py
Adds an extra metric to the Confluent Platform Integration
This metric will help measure latencies between brokers and zookeepers
=> Add Broker-Zookeeper latency metric

iis/tests/conftest.py, iis/tests/test_e2e.py, iis/tests/test_iis.py, iis/tox.ini
Add barebones E2E testing for IIS integration
https://datadoghq.atlassian.net/browse/AI-1760
David's project for Agent Integrations Team embed
Please note that IIS v1 will not support an E2E test. There are unhandled errors on startup of the check when IIS is not running, and this causes the check to not start. This E2E test is only for v2 with py3.
=> Add minimal e2e test for iis

postgres/tests/conftest.py
Enable DBM by default for the E2E env to ensure DBM data is always flowing whenever anyone starts up a local env.
=> postgres enable dbm by default for E2E

nginx/assets/dashboards/plus_overview.json
Update NGINX Plus dashboard to replace NGINX open source metrics with Plus metrics.
https://github.com/DataDog/integrations-core/issues/10895
=> Update dashboard to use Plus metrics

mysql/tests/conftest.py
Enable DBM by default for the E2E env to ensure DBM data is always flowing whenever anyone starts up a local env.
=> mysql enable dbm by default for E2E

postgres/datadog_checks/postgres/relationsmanager.py, postgres/tests/test_relationsmanager.py
Fixes a bug in Postgres relations config that only takes the last value of the relations list. The bug was introduced in Agent version 7.29.
For instance, the example config here: https://github.com/DataDog/integrations-core/blob/master/postgres/datadog_checks/postgres/data/conf.yaml.example#L151-L158 will actually not work correctly:
```yaml
relations:
- relation_name: <TABLE_NAME>  # <- will be ignored
schemas:
- <SCHEMA_NAME1>
- relation_regex: <TABLE_PATTERN>. # <- will be used
relkind:
- r
- p
```
=> Fix relations config parsing when multiple relations are specified

snowflake/assets/configuration/spec.yaml, snowflake/datadog_checks/snowflake/config_models/validators.py, snowflake/datadog_checks/snowflake/data/conf.yaml.example, snowflake/tests/test_config.py
Refactor `snowflake` validators so most of the issue are caught during initialization. We currently support 3 authentications:
* Password authentication
* Oauth token authentication
* Key pair authentication
Validation clarification
=> Refactor snowflake validators

snowflake/datadog_checks/snowflake/check.py
`read_token` now return the token value, so it has a similar behaviour as `read_key`.
=> Standardize key and token options behaviour

sqlserver/datadog_checks/sqlserver/metrics.py
Fixes #11082 by adding a tag for the value of recovery_model_desc to database metrics.
Adding more useful tags to filter off of.
=> Add recovery_model_desc tag for sqlserver database metrics

.azure-pipelines/scripts/sqlserver/windows/40_install_sqlserver.py, .azure-pipelines/scripts/sqlserver/windows/41_stop_sqlserver.bat, sqlserver/tests/common.py, sqlserver/tests/conftest.py, sqlserver/tests/test_activity.py, sqlserver/tests/test_connection.py, sqlserver/tests/test_e2e.py, sqlserver/tests/test_integration.py, sqlserver/tests/test_statements.py, sqlserver/tests/test_unit.py, sqlserver/tests/utils.py, sqlserver/tox.ini
Remove the limited _"can we connect to SQL Server using all supported drivers?"_ test in favor of running the full Windows test suite once per supported driver: SQLOLEDB, SQLNCLI11, MSOLEDBSQL, odbc.
We've had bugs in the past that are specific to a single driver and this will ensure that all supported drivers are fully tested.
Also cleanup instance configuration to ensure all instances are derived from the same base "default" instance, which is where we are varying the driver based on the current env. 
Improve Windows test coverage.
=> run full test suite for every supported Windows SQL Server driver

kubernetes_state/datadog_checks/kubernetes_state/kubernetes_state.py, kubernetes_state/tests/fixtures/prometheus.txt, kubernetes_state/tests/test_kubernetes_state.py
Remaps the value of the KSM `node.ready` service check from 'unknown' to 'warning' when a node enters an unknown state.
=> Remap value 'unknown' to 'warning' for KSM 'node.ready' service check

tls/datadog_checks/tls/tls.py, tls/datadog_checks/tls/tls_remote.py
Check for protocol version when fetching intermediate certificate
Not failing so it's not a breaking change for customer
=> Check intermediate certificate protocol version

network/metadata.csv
Small PR updating metadata.csv to note that saturation metrics are only available on Linux or Windows.
https://github.com/DataDog/integrations-core/pull/10551
=> Update metadata for platform-specific metrics

postgres/datadog_checks/postgres/postgres.py, postgres/datadog_checks/postgres/statement_samples.py, postgres/datadog_checks/postgres/statements.py, postgres/datadog_checks/postgres/util.py, postgres/tests/test_statements.py
This sends warnings in well-known database configuration errors to improve customers' visibility into issues due to missing or wrong database configuration required by the integration to work properly. Those warnings will appear in the agent status like this:
```
postgres (12.0.1)
-----------------
Instance ID: postgres:cc8c74ba7766a003 [WARNING]
Configuration Source: file:/etc/datadog-agent/conf.d/postgres.d/conf.yaml
Total Runs: 71
Metric Samples: Last Run: 143, Total: 10,169
Database Monitoring Activity Samples: Last Run: 1, Total: 102
Service Checks: Last Run: 1, Total: 71
Average Execution Time : 46ms
Last Execution Date : 2022-01-25 17:40:09 UTC (1643132409000)
Last Successful Execution Date : 2022-01-25 17:40:09 UTC (1643132409000)
metadata: …
```
=> Report known postgres database configuration errors as warnings

mysql/datadog_checks/mysql/mysql.py, mysql/datadog_checks/mysql/statement_samples.py, mysql/datadog_checks/mysql/statements.py, mysql/datadog_checks/mysql/util.py, mysql/tests/conftest.py, mysql/tests/test_statements.py
This sends warnings in well-known database configuration errors to improve customers' visibility into issues due to missing or wrong database configuration required by the integration to work properly. Those warnings will appear in the agent status like this:
```
mysql (8.0.2)
-------------
Instance ID: mysql:d790abe8c7b4512b [WARNING]
Configuration Source: file:/etc/datadog-agent/conf.d/mysql.d/conf.yaml
Total Runs: 22
Metric Samples: Last Run: 135, Total: 2,495
Database Monitoring Query Metrics: Last Run: 2, Total: 32
Database Monitoring Query Samples: Last Run: 6, Total: 65
Service Checks: Last Run: 3, Total: 66
Average Execution Time : 138ms
Last Execution Date : 2022-01-27 01:54:29 UTC (1643248469000)
Last Successful Execution Date : 2022-01-27 01:54:29 …
```
=> Report known mysql database configuration errors as warnings

.azure-pipelines/templates/test-single-windows.yml, sqlserver/datadog_checks/sqlserver/statements.py, sqlserver/tests/test_statements.py
Add `ddagenthostname` to the dbm-metrics payloads.
We already have the agent version sent as a field with metrics payloads but we'd like to have an easy way to know which agent is monitoring a database host.
=> Add ddagenthostname to dbm-metrics payloads

yarn/datadog_checks/yarn/yarn.py, yarn/tests/test_unit.py, yarn/tests/test_yarn.py
Currently the yarn integration will skip parsing application tags if they're not in `key:value` form. 
Value tags are technically valid tags and should be collected: see [docs](https://docs.datadoghq.com/getting_started/tagging/)
Currently the logs are getting skipped and submitted as a long string
```
2022-01-26 16:02:51 UTC | CORE | WARN | (pkg/collector/python/datadog_agent.go:124 in LogMessage) | yarn:c21bd3c1c88284c2 | (yarn.py:279) | Unable to split string luigiscript_name:dash_monitor_edge,livy-batch-0-5hmfsykz,user_email:data-science-eng with YARN application tags
```
=> Collect value-only application tags

kube_dns/assets/configuration/spec.yaml, kube_dns/datadog_checks/kube_dns/data/auto_conf.yaml
Adds `k8s-dns-kube-dns` to the default `ad_identifiers` list for `kube_dns`.
Recent GKE clusters use the `k8s-dns-kube-dns` image.
This is a customer feature request
=> Add k8s-dns-kube-dns as default AD identifier

weblogic/datadog_checks/weblogic/data/metrics.yaml, weblogic/tests/metrics.py
`weblogic.servlet_runtime.exec_time_total` is [found](https://github.com/DataDog/integrations-core/blob/master/weblogic/metadata.csv#L37) in `metadata.csv` but is missing in `metrics.yaml`.
QA
=> Add `weblogic.servlet_runtime.exec_time_total`

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/config.py
A recent validation error returned this message to the user: `File `conf.yaml.example` is not in sync, run "ddev validate config -s"`
When the user followed the suggestion, several other files outside their specific PR got changed as well, causing cascading validation failures due to other issues in those checks.
This PR adjusts the error message to just the check that's being validated to better target remediation actions.
Better user experience.
=> More specific config validation error message

ecs_fargate/README.md
the example cloudformation template sets up log configuration, but the template was in the setup section (and didn't mention the agent.)
now, there is an example cloudformation template that configures the agent in the setup section. there is also an example cloudformation template that configures fluent bit at the bottom of the log collection page (same instructions can be applied to firelens i believe)
@kaitlavs
=> [DOCS2917] updating ecs fargate cloudformation stuff

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py
Followup for this [pr](https://github.com/DataDog/integrations-core/pull/11168/files), the 'curated_metric' check in `validate/metadata.py` needs to be moved inside of the read_metadata_rows for loop to prevent an `UnboundLocalError`
=> Validate all `curated_metric` rows and properly validate empty `metadata.csv` files

datadog_checks_base/datadog_checks/base/utils/db/utils.py, datadog_checks_base/tests/base/utils/db/test_util.py
There is a bug in SQL Server where we try to truncate query text of type `None`.
```
packages/datadog_checks/sqlserver/statements.py", line 286, in _to_metrics_payload_row
row['text'] = row['text'][0:200]
TypeError: 'NoneType' object is not subscriptable
```
The root cause of this error occurs upstream and is caused by SQL Server potentially returning query metrics for a query without text. This causes the wrapper in this PR to return `None`, causing this particular error above. We decided to not filter queries like this out because the behavior we are seeking is to continue sending metrics even in the case of no query text. This will give us more control over how we handle a scenario like this in our back-end.
=> datadog_checks_base: Update obfuscator wrapper to return empty string 

datadog_checks_dev/datadog_checks/dev/tooling/manifest_utils.py
Updates the `add_dashboard` helper utility to safely initialize an empty dictionary if the key does not yet exist in the manifest when you try to add to it
There are some cases in the migration to Manifest V2 where you do not yet have a `dashboards` key under the `assets` section of a manifest. This is OK as not all integrations will have `dashboards`. 
Though currently, if you migrate to Manifest V2 and try to later add a dashboard through the `ddev meta dash export` command, it'd fail since the `dashboards` key does not yet exist.
=> Safely check the dashboards key exists before trying to write to it

datadog_checks_dev/datadog_checks/dev/plugin/tox.py
Part of https://github.com/DataDog/integrations-core/pull/11233
The new file would take precedence by default
=> Fix style check environment for Python checks defined by a `pyproject.toml` file

datadog_checks_dev/datadog_checks/dev/tooling/constants.py, datadog_checks_dev/datadog_checks/dev/tooling/dependencies.py
1. Run tests for `pyproject.toml` changes
2. Skip dependency validation for non-checks (this was always broken by only looking for a `requirements.in`)
Fix CI for https://github.com/DataDog/integrations-core/pull/11303
=> Final fix for dependency tooling

ibm_i/assets/dashboards/ibm_i_overview.json
Updates the LPAR CPU widget of the default IBM i dashboard to use the new and more accurate `ibm_i.system.normalized_cpu_usage` metric.
Use new CPU metrics added in #11081.
Switching to the new metric is fine, the integration is currently only used by one customer that is using a version of the integration that produces the metric.
=> Update default dashboard CPU metric

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/generate_traps_db.py, datadog_checks_dev/setup.py
I noticed `ddev` started failing imports for me after pulling https://github.com/DataDog/integrations-core/pull/11235
The `meta` commands provide no stability guarantees (https://datadoghq.dev/integrations-core/ddev/cli/#ddev-meta) and should not define dependencies but rather lazily import and require manual installation if necessary, see:
- https://github.com/DataDog/integrations-core/blob/9cb47fde4b8dce2521e7712125800d12aad84428/datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/translate_profile.py#L51-L56
- https://github.com/DataDog/integrations-core/blob/9cb47fde4b8dce2521e7712125800d12aad84428/datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/windows/pdh.py#L98-L101
- https://github.com/DataDog/integrations-core/blob/9cb47fde4b8dce2521e7712125800d12aad84428/ …
=> Remove `pysmi` from required dependencies

LICENSE-3rdparty.csv, datadog_checks_base/datadog_checks/base/checks/base.py, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/requirements.in, datadog_checks_base/tests/base/checks/openmetrics/test_options.py, datadog_checks_base/tests/base/checks/test_agent_check.py
Adds the ability to detects and warn the user on typos in configuration options. We calculate the jaro distance of undocumented configuration options and each documented configuration option, and if they are similar enough, warn the user they could have made a typo. 
We want to give better feedback on typos in configuration options
It's following up and based on the work from https://github.com/DataDog/integrations-core/pull/10438/, yet only warning on typos, not all unknown options.
Logs will be in the form of:
```
2022-01-26 16:07:25 UTC | CORE | WARN | (pkg/collector/python/datadog_agent.go:124 in LogMessage) | openmetrics:openmetrics:4f4b8d8a05846ec | (base.py:425) | Detected potential typo in configuration option in openmetrics/instances section: prometheus_ur. Did you mean …
```
=> Detect and warn on potential typos in configuration options

clickhouse/assets/configuration/spec.yaml, clickhouse/datadog_checks/clickhouse/data/conf.yaml.example, mysql/assets/configuration/spec.yaml, mysql/datadog_checks/mysql/data/conf.yaml.example, vertica/assets/configuration/spec.yaml, vertica/datadog_checks/vertica/data/conf.yaml.example
https://github.com/DataDog/integrations-core/pull/7583 removed the default `metric_prefix` in init_config since it was deprecated, but some db integrations that didn't previously implement `metric_prefix` still have the option. This is causing confusing since the option is not used in those integrations.
This PR removes the `metric_prefix` option in init_config/db for mysql, clickhouse, and vertica since those integrations don't use `metric_prefix`.
https://github.com/DataDog/integrations-core/issues/11030
=> Remove unused `metric_prefix` in init_config

datadog_checks_dev/MANIFEST.in, datadog_checks_dev/pyproject.toml, datadog_checks_dev/setup.py
Modernize packaging, continues https://github.com/DataDog/integrations-core/pull/11233
The `setup.py` file will be removed when we drop Python 2 since new-style editable installations require versions of `pip` that are Python 3-only
=> Add `pyproject.toml` file

datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/base.py, datadog_checks_base/tests/base/checks/openmetrics/test_options.py
When scraping an endpoint, if its not available the check submits a critical service check but still propagates the exception, causing a big stacktrace to appear on the logs. In this change the exception is captured and logged as a single line.
Sample exception trace:
```
E             File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 1033, in run
E               self.check(instance)
E             File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/openmetrics/v2/base.py", line 60, in check
E               scraper.scrape()
E             File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/openmetrics/v2/scraper.py", line 238, in …
```
=> Fail gracefully when scraping OpenMetrics endpoints

datadog_checks_dev/datadog_checks/dev/tooling/constants.py, datadog_checks_dev/datadog_checks/dev/tooling/e2e/docker.py, datadog_checks_dev/datadog_checks/dev/tooling/e2e/local.py, datadog_checks_dev/datadog_checks/dev/tooling/signing.py, datadog_checks_dev/datadog_checks/dev/utils.py
```
datadog_checks.dev.errors.SubprocessError: Command: ['docker', 'exec', 'dd_activemq_xml_py38', '/opt/datadog-agent/embedded/bin/pip3', 'install', '-e', '/home/datadog_checks_base', '-r', '/home/datadog_checks_base/requirements.in']
Captured Output: ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/home/datadog_checks_base/requirements.in'
```
=> Fix E2E for new base package versions

datadog_checks_dev/datadog_checks/dev/plugin/pytest.py, datadog_checks_dev/datadog_checks/dev/plugin/tox.py
Fix CI for https://github.com/DataDog/integrations-core/pull/11459
=> Fix `pytest` and `tox` plugins for checks with only a `pyproject.toml`

confluent_platform/tests/conftest.py
Confluent platform environment fails to start (kafka throws exceptions) so let's add a retry
=> Add attempts

datadog_checks_base/datadog_checks/base/checks/base.py, datadog_checks_base/tests/base/checks/test_agent_check.py
Properly create list of known options when validating typos
Fixes: https://github.com/DataDog/integrations-core/pull/11211
Redis tests were failing with:
```
tests/test_slowlog.py:56: in test_custom_slowlog
dd_run_check(redis_check)
../datadog_checks_dev/datadog_checks/dev/plugin/pytest.py:219: in run_check
raise Exception('\n'.join(exc_lines))
E   Exception: 
E     File "/home/vsts/work/1/s/datadog_checks_base/datadog_checks/base/checks/base.py", line 1041, in run
E       initialization()
E     File "/home/vsts/work/1/s/datadog_checks_base/datadog_checks/base/utils/tracing.py", line 77, in wrapper
E       return f(self, *args, **kwargs)
E     File "/home/vsts/work/1/s/datadog_checks_base/datadog_checks/base/checks/base.py", line 455, in …
```
=> Properly create list of known options when detecting typos

vault/assets/configuration/spec.yaml, vault/datadog_checks/vault/check.py, vault/datadog_checks/vault/common.py, vault/datadog_checks/vault/config_models/defaults.py, vault/datadog_checks/vault/config_models/instance.py, vault/datadog_checks/vault/data/conf.yaml.example, vault/datadog_checks/vault/metrics.py, vault/datadog_checks/vault/vault.py, vault/tests/conftest.py, vault/tests/metrics.py, vault/tests/test_integration.py, vault/tests/test_vault.py
Also took the liberty of not supporting legacy behavior when enabled:
- `disable_legacy_cluster_tag` option
- `vault.route.<API>.<MOUNTPOINT>` metrics (new is `vault.route.<API>` with `mountpoint:<MOUNTPOINT>` tag)
- `ssl_*` options
=> Add support for OpenMetrics v2

sqlserver/datadog_checks/sqlserver/connection.py, sqlserver/datadog_checks/sqlserver/sqlserver.py, sqlserver/tests/common.py, sqlserver/tests/compose-ha/sql/aoag_primary.sql, sqlserver/tests/compose-high-cardinality-windows/setup.sql, sqlserver/tests/compose-high-cardinality/setup.sql, sqlserver/tests/compose-windows/setup.sql, sqlserver/tests/compose/setup.sql, sqlserver/tests/test_integration.py
If a stored procedure uses a temporary table then it will, by default, return the number of rows affected as part of the result set. If such a procedure is called (i.e. as part of `custom_queries`) then the query will fail because neither the `pyodbc` nor `adodbapi` libraries are able to deal with this correctly.
For example, adodbapi throws the following error: `fetch() on closed connection or empty query set`
If the procedure sets `SET NOCOUNT ON` internally then the query will succeed. To ensure the agent is able to call all procedures regardless of whether this has been set in the procedure or not, we'll now set `SET NOCOUNT ON` when we're running custom queries.
Fix failed `custom_queries` when calling stored procedures that use temporary tables.
=> disable modified rowcounts in result sets for all connections

disk/assets/service_checks.json
Service check for `disk.read_write` is not enabled by default. This updates the `service_checks.json` file to mention this more explicitly.
Docs didn't mention that this attribute wasn't enabled by default.
=> update service_checks.json to point out service checks

istio/README.md
Fix indent in istio doc.
There are broken indents in this doc.
https://docs.datadoghq.com/integrations/istio/#metric-collection
https://docs.datadoghq.com/integrations/istio/#invalid-chunk-length-error
=> Fix indent in istio doc

databricks/assets/dashboards/databricks_overview.json
Update databricks dashboard widget to display the average of CPU percent Utilization, not the sum
The widget is currently reporting unreasonable values
=> Update cpu utilization query in default dashboard

docs/developer/process/agent-release/pre-release.md
Adds step about assigning agent release category labels to PRs for release candidates.
=> Update release docs with release category label process

kubelet/datadog_checks/kubelet/kubelet.py, kubelet/tests/test_kubelet.py
Filters `kubernetes.kubelet.volume.*` metrics according to `DD_CONTAINER_EXCLUDE` ([docs](https://docs.datadoghq.com/agent/guide/autodiscovery-management/?tab=containerizedagent))
=> Apply namespace exclusion rules for volume metrics

datadog_checks_base/datadog_checks/base/utils/tracing.py
https://github.com/DataDog/integrations-extras/pull/1193
```
datadog_checks/storm/storm.py:397: in process_cluster_stats
return StormCheck.StormVersion.from_string(version)
E   TypeError: 'classmethod' object is not callable
```
=> Fix edge case in tracing utils

kubelet/assets/configuration/spec.yaml, kubelet/datadog_checks/kubelet/data/conf.yaml.example, kubelet/manifest.json, kubernetes_state/assets/configuration/spec.yaml, kubernetes_state/datadog_checks/kubernetes_state/data/auto_conf.yaml, kubernetes_state/datadog_checks/kubernetes_state/data/conf.yaml.example, kubernetes_state/manifest.json
- Add spec.yaml files for kubernetes_state and kubelet checks
- Update conf files accordingly
=> Update example config

datadog_checks_base/datadog_checks/base/checks/base.py
Add more error handling when detecting typos
Avoid issues like https://github.com/DataDog/integrations-core/pull/11482 addressed where checks can't properly load when detecting typos. Since the function is only logging a warning it's not essential and ok to swallow the exception
=> Add more error handling when detecting typos

mysql/datadog_checks/mysql/config.py, mysql/datadog_checks/mysql/mysql.py, mysql/tests/test_mysql.py
This fixes support for the [only_custom_queries](https://github.com/DataDog/integrations-core/blob/master/mysql/datadog_checks/mysql/data/conf.yaml.example#L95). Prior to this change, all core mysql metrics were still emitted even with `only_custom_queries` set to `true`.
A customer report.
`performance_schema` is being used by the statement metrics job loop when dbm is enabled. Previously, this was gathered with other global status variables in the main metric collection but this had to be extracted now to always be initialized regardless of whether the core integration metrics were collected or not.
=> Fix only_custom_queries configuration not honored

sqlserver/datadog_checks/sqlserver/statements.py, sqlserver/tests/test_statements.py
In some situations there can be many unique query texts per `query_hash, query_plan_hash, ...`. They often differ only by their parameters (i.e. `select * from foo where id=1` and `select *f rom foo where id=2`) so there is no reason to be aggregating by text when in the agent code we'll be normalizing the text and aggregating it together anyway. Not only is this unnecessary but it can also be very expensive, causing the latency of the query to increase by several times when there are many unique query texts.
Now we update to first do the aggregation only by `query_hash, query_plan_hash` (and optionally `user` and `database`) and then look up the sql text by `plan_handle`.
Improve query performance.
=> remove aggregation by SQL text from query stats query

ibm_db2/README.md
Updates the docs to instruct users to install `ibm_db` version `3.1.0` for  python3 
Follow up to https://github.com/DataDog/integrations-core/pull/10331, `ibm_db` `3.0.1` is not compatible with python3. We are now using version `3.0.1` in our testing environment.
=> Update documented library version to install

istio/README.md
Adds updated configuration instructions for disabling sidecar injection in Istio versions 1.10+. Since Istio version 1.10, `sidecar.istio.io/inject` should be configured as a label, not an annotation. 
It is still supported as an [annotation](https://istio.io/latest/docs/reference/config/annotations/), but the behavior has changed:
https://istio.io/latest/news/releases/1.10.x/announcing-1.10/upgrade-notes/#sidecar-injector-changes
https://github.com/DataDog/integrations-core/issues/11501
=> Update disabling sidecar injection instructions

postgres/datadog_checks/postgres/statement_samples.py, postgres/tests/test_statements.py
Updates the pg_stat_activity query that the agent runs to also collect the blocking pids for a query. Will be an empty `{}` set if there are no pids blocking the query. 
More documentation on this function [exists here](https://pgpedia.info/p/pg_blocking_pids.html#:~:text=pg_blocking_pids()%20is%20a%20system,was%20added%20in%20PostgreSQL%209.6.)
From the docs:
```
Note the following caveats:
1. For parallel queries, the session PID where the query was executed is listed, not that of the parallel worker, meaning there may be duplicate PIDs
2. When a prepared transaction holds a conflicting lock, it will be represented by PID 0
Note that execution of pg_blocking_pids() requires exclusive access to the lock manager's shared state for a short period, which may have performance implications, …
```
=> Add ability to collect blocking pids for queries run on postgres dbs

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/models.py
In `ddev validate models -s`, handle the case where a generated file does not have a license file
We saw this happen with foundationdb
=> Handle the case in models sync where a file does not have a license header

ibm_db2/assets/configuration/spec.yaml, ibm_db2/datadog_checks/ibm_db2/config_models/defaults.py, ibm_db2/datadog_checks/ibm_db2/config_models/instance.py, ibm_db2/datadog_checks/ibm_db2/data/conf.yaml.example, ibm_db2/datadog_checks/ibm_db2/ibm_db2.py, ibm_db2/tests/conftest.py, ibm_db2/tests/test_unit.py
This PR adds the parameter ```security``` to the Db2 integration.
Currently the integration only supports SSL when also a client-side certificate is defined. But Db2 also supports SSL without explicitely specifying a certificate (see https://www.ibm.com/docs/en/db2/11.5?topic=keywords-security for more information on that). Db2 on Cloud (IBM Cloud) only allows SSL-enabled connections (without the need to mention a certificate because it is already bundled into the driver package). Currently this is only possible by adding the ```Security``` paramater to one of the other options, e.g.:
```yaml
- db: <database name>
username: <username>
password: <password>
host: <hostname>;Security=ssl
port: <port>
```
This PR enables users to use the following:
```yaml
- db: <database name>
username: …
```
=> Add Security parameter

win32_event_log/README.md
Fixes 404 URL (https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc722404(v=ws.11) to https://docs.microsoft.com/en-us/windows/win32/eventlog/event-logging.
Slack
=> Updates Broken Doc Link in Win 32 event log

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/trello/tester_selector/tester_selector_team.py
This PR fixes the fallback case in the trello card assignment algorithm.
The function passed to `__select_testers` is an exclusion filter and we used to pass a function that excluded everyone except the author.
=> Fix fallback case in trello card assignment algorithm

datadog_checks_downloader/tests/test_downloader.py
Expected situation now that we properly indicate Python constraints: https://github.com/DataDog/integrations-core/blob/9027bd465978ddd437e093feaeaaa4095605bbef/avi_vantage/pyproject.toml#L13
=> Ignore errors from unmet Python version requirements

kubelet/datadog_checks/kubelet/cadvisor.py, kubelet/datadog_checks/kubelet/summary.py, kubelet/tests/test_kubelet.py
This PR filters kubelet metrics according to the `DD_CONTAINER_EXCLUDE` option.
This is similar to my previous PR https://github.com/DataDog/integrations-core/pull/11512
In this PR, we make sure that metrics coming from the cadvisor and the summary endpoint are also correctly filtered when `DD_CONTAINER_EXCLUDE` references a kubernetes namespace.
Using the default configuration, `kubernetes.ephemental.storage.usage`, `kubernetes.filesystem.usage`, and `kubernetes.filesystem.usage_pct` were not correctly filtered. With this change, they should be.
After this change, the only metrics not filtered according to `DD_CONTAINER_EXCLUDE` should be the ones about containers/pods running, stopped, etc. As mentioned in [the docs](https://docs.datadoghq.com/agent/docker/?tab=standard#ignore-containers …
=> Apply namespace exclusion rules in cadvisor and summary metrics

datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/base.py, datadog_checks_base/tests/base/checks/openmetrics/test_options.py
This [fix](https://github.com/DataDog/integrations-core/pull/11281) added an improvement to the error logging. The scraper error was logged and the service check was submitted as CRITICAL, however, the agent status was still reporting the check as OK:
```
error: openmetrics:openmetrics:a601c57cd02b9742 | (base.py:65) | There was an error scraping endpoint http://localhost:9099/metrics: HTTPConnectionPool(host='localhost', port=9099): Max retries exceeded with url: /metrics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0dd442dd90>: Failed to establish a new connection: [Errno 111] Connection refused'))
=== Service Checks ===
[
{
"check": "openmetrics.openmetrics.health",
"host_name": "docker-desktop",
"timestamp": 1645656011,
"status": 2,
"message": …
```
=> Properly raise scraper error in OpenMetrics v2

pulsar/README.md
Adds a logs section to the pulsar readme 
It has a logs integration but it is not documented.
=> Add logs section to pulsar readme

silk/datadog_checks/silk/check.py, silk/tests/test_silk.py
- Update the wording of a log line regarding failure to collect system state.
- Also adds a test for this scenario, as well as updates the other system state test to assert the tags returned
More clear instructions to users, QA
=> Update system state log line wording 

silk/tests/test_silk.py
- Adds test for metrics_to_collection creation per different params
- Adds ids to the other test to make it more readable
QA for silk
=> Add test for metrics_to_collect creation

sqlserver/datadog_checks/sqlserver/connection.py, sqlserver/datadog_checks/sqlserver/sqlserver.py, sqlserver/tests/compose-ha/sql/aoag_primary.sql, sqlserver/tests/compose-high-cardinality-windows/setup.sql, sqlserver/tests/compose-high-cardinality/setup.sql, sqlserver/tests/compose-windows/setup.sql, sqlserver/tests/compose/setup.sql, sqlserver/tests/test_integration.py
When we added the execution of the service check on auto discovered databases (https://github.com/DataDog/integrations-core/pull/9900), we opened the door to the integration check failing when one of the auto discovered databases couldn't be connected to. A more sensible behavior is to report a auto discovered database's service check status correctly but still proceed with the metrics collection and the rest of the check's execution.
Before this change, the integration would fail with:
```
______________________________________________________________________ test_autodiscovery_db_service_checks[True-4-1] ______________________________________________________________________
tests/test_integration.py:161: in test_autodiscovery_db_service_checks
dd_run_check(check) …
```
=> Fix service check failures on auto discovered dbs failing full check execution

datadog_checks_dev/datadog_checks/dev/tooling/configuration/constants.py
* `uniqueItems` for constrained lists are not currently supported in `datamodel-code-generator`: https://github.com/koxudaxi/datamodel-code-generator/issues/719
* `condict` and `minProperties` are not currently supported in pydantic: https://github.com/samuelcolvin/pydantic/issues/1277#issuecomment-939633650. Suggestion is to use validators.
=> Remove unsupported schema properties

silk/assets/service_checks.json, silk/datadog_checks/silk/check.py
Add debug logging for unknown server statuses reported from the servers endpoint `system/servers`. Non-`ok` statuses are not currently documented. If a user encounters any UNKNOWN `server.state` service check status, they may want to check the debug logs for the returned status.
=> Add debug logging for unknown server statuses

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/readmes.py
Don't ignore the last character of lines when validating ASCII
QA week
Before it didn't catch ascii characters at the end of the line, and removing this line doesn't cause false positives with new lines
=> Don't ignore the last character of lines when validating ASCII

mysql/assets/configuration/spec.yaml, mysql/datadog_checks/mysql/config.py, mysql/datadog_checks/mysql/data/conf.yaml.example, mysql/tests/test_statements.py
Enables the collection of SQL metadata by default for MySQL.
=> Enable SQL metadata collection by default

.gitlab/tagger/tag-release.sh, datadog_checks_dev/datadog_checks/dev/tooling/commands/release/tag.py
New integrations cause CI to trigger the release pipeline, which shouldn't occur until integrations are officially signed and released.
This PR skips tagging v0.0.1 integrations to prevent the release pipeline from running.
https://github.com/DataDog/integrations-core/pull/11610 adds the flag the shell script.
CI pipeline bug - CI looks for most recent .tag file, but since the integration isn't released yet the file is incorrect.
=> Prevent tags for unreleased integrations

eks_fargate/README.md
Reverts DataDog/integrations-core#10909
https://github.com/DataDog/datadog-agent/pull/10449 fixes the bug.
=> Revert "Add DD_TAGS section for cluster name, fix links"

airflow/README.md
Add a sentence describing what the `url` should be, referencing the Airflow docs for webserver/base_url. If this is changed from the default `http://localhost:8080` to something like `http://localhost:80/server` the Agent's URL needs to be updated accordingly.
Clear up steps and support cases, ex: CONS-4574
=> [DOCS] Update URL steps to reference webserver base_url

sqlserver/datadog_checks/sqlserver/metrics.py, sqlserver/datadog_checks/sqlserver/sqlserver.py, sqlserver/tests/common.py, sqlserver/tests/test_integration.py, sqlserver/tests/test_unit.py
When DBM is enabled we want all telemetry, both standard metrics as well as DBM events, to have the hostname set to the resolved hostname. This ensures that when an agent is monitoring a remote host (i.e. RDS or Azure managed) all SQL Server telemetry is tagged with the hostname of the remote host and not the agent's hostname.
Fix inconsistent hostname tagging when using DBM.
=> Use remote hostname on all metrics when DBM is enabled

datadog_cluster_agent/assets/dashboards/datadog_cluster_agent_overview.json
Use `sum by` instead of `avg by` to show the total number of external metrics per namespace
Total count is more meaningful than an avg value in this case
Staging link: [External metrics by namespace](https://dd.datad0g.com/dash/integration/30706/datadog-cluster-agent-overview) graph under `Autoscaling`
=> Use sum by in datadog_cluster_agent external metrics by namespace graph

sqlserver/datadog_checks/sqlserver/activity.py
SQLServer [dm_exec_requests](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql?view=sql-server-ver15) table has a `wait_resource` column, which we should show when we display blocking query trees
Follow up from https://github.com/DataDog/integrations-core/pull/11629
=> Add missing wait_resource column for activity collections

snowflake/datadog_checks/snowflake/check.py, snowflake/datadog_checks/snowflake/config.py
This PR changes Snowflake's `private_key_password` to a string instead of a byte, and casts it as a byte once it is used for loading the PEM key.
Support and QA
=> Convert private key password into string instead of byte

datadog_checks_base/datadog_checks/base/checks/base.py, datadog_checks_base/tests/base/checks/test_agent_check.py
Adds instance-level options to the base check to filter all metric submission with a regex. The main option is `metric_patterns` with two sub-options are `exclude` and `include`. 
Allow users to have more control over what metrics are submitted for each integration
- These behave very similarly to `exclude_labels` and `include_labels`, where `exclude` takes precedence over `include`  
- These can either be strings or regexes.
- They also use the same regex construction as `exclude_metrics`
- The namespace is included in the regex
- I could add a debug log line if a metric is skipped, but that would be noisy
=> Add `metric_patterns` options to filter all metric submission with a list of regexes

http_check/assets/configuration/spec.yaml, http_check/datadog_checks/http_check/data/conf.yaml.example
After adding TLSContextWrapper support in https://github.com/DataDog/integrations-core/pull/8268, the value of `context.verify_mode` is affected by `tls_verify` rather than hardcoded to `ssl.CERT_REQUIRED`. 
This PR removes references to the hardcoded `ssl.CERT_REQUIRED` value from the config description.
=> Remove outdated config description

kafka/README.md
It corrects the link to the kafka_consumer check set up, previously, it would render the same exact page (https://docs.datadoghq.com/integrations/kafka/?tab=host#agent-check-kafka-consumer)
I am investigating on a ticket and found out that the link was not relevant
I hope this is accurate!
=> [doc] corrected link for Kafka_consumer check

datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/recommended_monitors.py
Add more allowed monitors to the "recommended monitors" validation. Monitor types can be validated here - https://docs.datadoghq.com/api/latest/monitors/#create-a-monitor
These monitor types are now supported with recommended monitors
=> Add more allowed recommended monitor types

cilium/README.md
FIxing the `instance_config` definition should be string instead of Boolean:
`"use_openmetrics": "true"`
Also added separate metrics/logs collection for Agent and Operator containerised
Prevent any misunderstanding when setting up and configuring the integration.
=> [Cilium] Fix containerised configuration doc

istio/datadog_checks/istio/data/auto_conf.yaml
Add the image `proxyv2-rhel8` to the list of `ad_identifiers` of the `istio/auto_conf.yaml`. In OpenShift Service Mesh it utilizes a custom Istio container image named `proxyv2-rhel8` instead of just `proxyv2`. So adding in this extra image to account for that. 
The actual integration will still run the same way, this is just to trigger on those Istio sidecar containers too.
Allow this portion of the integration to get setup automatically for OpenShift Service Mesh. This can be covered by a custom `istio.d/conf.yaml` configuration as a workaround, but this would just simplify that step.
[CONS-4516](https://datadoghq.atlassian.net/browse/CONS-4516)
Redhat registry for this image:
- https://catalog.redhat.com/software/containers/openshift-service-mesh/proxyv2-rhel8/5d2cda455a134672890f640a …
=> Add image for OpenShift Service Mesh Proxy to ad_identifiers

cilium/README.md
Reverts DataDog/integrations-core#11656 - broke the docs build. Will add it back when I figure out why
=> Revert "[Cilium] Fix containerised configuration doc"

cilium/README.md
Original PR #11656 broke the documentation build. Retrying (do not merge until we're sure this works)
FIxing the `instance_config` definition should be string instead of Boolean:
`"use_openmetrics": "true"`
Also added separate metrics/logs collection for Agent and Operator containerised
=> REDO: [Cilium] Fix containerised configuration doc

ibm_mq/datadog_checks/ibm_mq/collectors/channel_metric_collector.py, ibm_mq/datadog_checks/ibm_mq/collectors/metadata_collector.py, ibm_mq/datadog_checks/ibm_mq/collectors/stats_collector.py
This PR adds [`disconnect()`](https://github.com/dsuch/pymqi/blob/v1.12.0/code/pymqi/__init__.py#L2894) to all `PCFExecute` initializations to ensure that they are closed.
Reduce memory leak possibility.
=> Ensure PCFExecute disconnects

sqlserver/tests/test_activity.py
Attempt to fix these errors:
```3221225477 is 0xC0000005 which is NTSTATUS STATUS_ACCESS_VIOLATION; the corresponsing error message is The instruction at 0x%08lx referenced memory at 0x%08lx. The memory could not be %s..```
we are seeing intermittently in the test runs on windows machines
=> Fix flakey sqlserver activity test

ibm_mq/assets/configuration/spec.yaml, ibm_mq/datadog_checks/ibm_mq/collectors/channel_metric_collector.py, ibm_mq/datadog_checks/ibm_mq/config.py, ibm_mq/datadog_checks/ibm_mq/config_models/defaults.py, ibm_mq/datadog_checks/ibm_mq/config_models/instance.py, ibm_mq/datadog_checks/ibm_mq/data/conf.yaml.example
This PR adds a new `auto_discover_channels` option to disable automatically submitting channel status for `'*'` channels.
Reduce memory leak possibility
=> Add `auto_discover_channels` option

kubernetes_state/datadog_checks/kubernetes_state/kubernetes_state.py, kubernetes_state/tests/test_kubernetes_state.py
Add kube_cronjob tag to job metrics when applicable
Better UX + ease the migration to ksm core
=> Add `kube_cronjob` tag to job metrics when applicable

container/metadata.csv
Remove incorrect unit that caused some confusion
=> [container] rm incorrect unit for container.memory.oom_events

sqlserver/datadog_checks/sqlserver/activity.py, sqlserver/tests/test_activity.py
Right now we only send the status from the `dm_exec_sessions` dmv table, which can be different than the status in the `dm_exec_requests` view.
This information is important for customers to be able to distinguish between queries that are active, but blocked and queries that are active and executing 
more information documented here https://www.sqlshack.com/monitoring-sql-server-with-dynamic-management-objects-requests/
=> Add request_status in sqlserver activity query

datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/default.yaml, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/pyproject.toml, datadog_checks_dev/tests/tooling/configuration/consumers/test_example.py
Adds `metric_patterns` to the base template
https://github.com/DataDog/integrations-core/pull/11508
Will fail validation until https://github.com/DataDog/integrations-core/pull/11695 is merged
=> Add `metric_patterns` to base template

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/snmp/generate_traps_db.py
To be merged after the freeze.
Improves the generate-traps-db command with:
- Clearer error messages that better reference the real issue.
- Prevent some edge case failures when handling conflicting variable OIDs
- Adding the MIB name to the generated db to better reference the source of each trap
=> Better logging and usability of ddev 'generate-traps-db'

postgres/README.md
Corrects a link to Tracing Docker Applications in the README. It previously referenced link 12, about ECS tracing.
I was surprised that the link for Tracing Docker Applications took me to a page about ECS tracing.
Link 12 is still valid; it is referenced correctly elsewhere in the page
=> Corrects link to Tracing Docker Applications

kubernetes_state/assets/configuration/spec.yaml, kubernetes_state/datadog_checks/kubernetes_state/data/conf.yaml.example
Add back params that were inadvertently removed from the Kubernetes State conf.yaml.example file in https://github.com/DataDog/integrations-core/pull/11515
=> [kubernetes_state] re-add missing params in conf.yaml.example

oracle/datadog_checks/oracle/oracle.py, oracle/tests/conftest.py, oracle/tests/test_e2e.py
Added logic to submit a critical status for the service check if the connection being made using the instance client fails. Currently when using the instant client the service check will only return critical if there's a parsing issue in creating the dsn, but the service check will return `OK` regardless if we're able to connect or not.
The check at the current state will continue running even if the connection fails. Is it better to raise an exception if the connection fails? 
Support case
=> Properly report a critical service check status if connection to database fails using the Oracle client

http_check/assets/configuration/spec.yaml, http_check/datadog_checks/http_check/config_models/defaults.py, http_check/datadog_checks/http_check/config_models/instance.py, http_check/datadog_checks/http_check/data/conf.yaml.example
Adds the TLS Wrapper config spec to http_check to document all options
https://github.com/DataDog/integrations-core/pull/11706 and we currently aren't documenting all options
Note: the http spec and tls spec share  some common options now. Their documentation is currently similar enough that it is fine to keep one (http) and hide the tls options
=> Document TLS options

datadog_checks_dev/datadog_checks/dev/tooling/commands/dep.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/dep.py, datadog_checks_dev/datadog_checks/dev/tooling/dependencies.py, datadog_checks_dev/datadog_checks/dev/tooling/utils.py
Simplified dependency logic to act upon the full definition + supported Python version, changing the allowed arguments for the `dep pin` command
The `dep updates` and `dep sync` commands could not properly handle different versions per Python version
=> Refactor dependency tooling

tox.ini
jinja2 v3.1.0 was released today and included the removal of some deprecated code: https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0
Fix CI
mkdocs fix is in the works: https://github.com/mkdocs/mkdocs/pull/2795
=> Pin Jinja2 version to 3.0.3

sqlserver/README.md
Fix example SQL highlighting in docs by setting the right type.
=> fix SQL highlighting in readme

datadog_checks_dev/datadog_checks/dev/tooling/commands/release/tag.py
Properly tag all integration versions
Before, we would stop checking for new integration versions to tag once any pre-release integration was found. This is because we have a `None` check for version in the loop, but if we discover a pre-release integration, we didn't reset version to `None` so version will be `0.0.1` for the rest of the loop https://github.com/DataDog/integrations-core/pull/11736/files#diff-f0591d2ad7a83220593faa96c6a481a295b0e0d45af286c0ad5d07832bd1b502L53
=> Properly tag all integration versions 

datadog_checks_base/datadog_checks/base/__about__.py, datadog_checks_dev/pyproject.toml
https://virtualenv.pypa.io/en/20.14.0/changelog.html#bugfixes-20-14-0
tox uses `setup.py` if it exists and latest `setuptools` supports PEP 621 but not PEP 639
=> Cap the version of virtualenv

clickhouse/pyproject.toml, datadog_checks_base/datadog_checks/base/data/agent_requirements.in
Revert lz4 bump
python-lz4/python-lz4#244, which breaks our Omnibus build
=> Revert lz4 bump

sqlserver/datadog_checks/sqlserver/activity.py, sqlserver/tests/test_activity.py, sqlserver/tests/test_statements.py
Adds SQL metadata to SQL Server activity.
=> Add SQL metadata to SQL Server activity events

aerospike/datadog_checks/aerospike/aerospike.py, aerospike/tests/test_unit.py
Fixes broken latency and latencies metric connection. Previously, the `collect_latency` and `collect_latencies` methods exited before the last row of output could be processed due to an unneeded `break` statement. The existing tests did not catch this because the mocked data returned either no data or empty data as the last row. This PR removes the unneeded break statements and adds additional test cases.
Support case
=> Fix broken latency metric collection

haproxy/README.md
This PR makes the README more clear that the current docs reflect Agent 7.35+.
https://github.com/DataDog/integrations-core/pull/11693 added back 7.34 docs due to a support case, so I wanted to make it more clear that the current docs are 7.35+.
=> Update Haproxy README to be clearer on legacy docs

ibm_mq/datadog_checks/ibm_mq/ibm_mq.py, ibm_mq/tests/test_ibm_mq_int.py
Report critical queue manager check when connection fails 
More service check coverage
TODO: also report when connection succeeds but other operations do not
=> Report critical queue manager service check when connection fails

kubernetes_state/datadog_checks/kubernetes_state/kubernetes_state.py, kubernetes_state/tests/test_kubernetes_state.py
`<object>.count` metrics do not use the default `kube_labels_mapper` as opposed to the other metrics, it's why the `kube_namespace` tag was missing. This PR fixes this.
Bug fix.
The label mapper override is inspired by what we do in the ksm core check https://github.com/DataDog/datadog-agent/blob/main/pkg/collector/corechecks/cluster/ksm/kubernetes_state.go#L717-L729
=> Add `kube_namespace` tag to object count metrics

kubernetes_state/assets/service_checks.json
Add missing `kubernetes_state.job.complete` service check to the `kubernetes` integration.
the `kubernetes_state.job.complete` [service check](https://docs.datadoghq.com/integrations/kubernetes_state_core/?tab=helm#service-checks) was missing from the `kubernetes` integration
=> [kubernetes] Add missing 'job.complete' service check

.github/CODEOWNERS
Assigns `helm` to container-integrations in `.github/codeowners`.
=> [github/codeowners] Assign helm to container-integrations

postgres/datadog_checks/postgres/statement_samples.py, postgres/tests/test_statements.py
Adds a new column to activity queries for postgres, `now`, which is collected by calling the `clock_timestamp()` function. This will allow us to ingest the current time as seen by the database itself, and use that for our duration calculations for active queries in the backend. 
For the postgres integration, we're setting duration as `payloadTimestamp - query_start`, but payloadTimestamp is now() as calculated by the agent. It should instead be clock_timestamp() as reported by the database when the activity query is made.
This is likely adding 10-20 ms to our Postgres activity query durations.
=> Bug fix: fix postgres activity inflated query durations

gitlab_runner/README.md
Update the GitLab Runner documentation URL.
The old url is broken.
```
$ curl -I https://docs.gitlab.com/runner/monitoring/README.html
HTTP/2 404
$ curl -I https://docs.gitlab.com/runner/monitoring/
HTTP/2 200
```
=> Update GitLab Runner documentation URL

datadog_checks_dev/datadog_checks/dev/tooling/commands/test.py
Fix logic used to determine the minimum version of the base check needed for testing. 
Base package CI was failing with:
```
spec_set = list(check_base_dependencies['datadog-checks-base'].keys())[0]
KeyError: 'datadog-checks-base'
```
`check_base_dependencies` returns a simple dictionary structure now. I.e.:
`{'amazon_msk': 'datadog-checks-base>=25.1.0'}`
=> Fix logic for loading minimum base package dependency for tests

mysql/metadata.csv
The unit of the following three metrics is pages, but bytes is correct.
- mysql.innodb.buffer_pool_free
- mysql.innodb.buffer_pool_total
- mysql.innodb.buffer_pool_used
So in this PR, change unit from pages to bytes.
The following setting confirms that these metrics are in bytes:
https://github.com/DataDog/integrations-core/blob/70701cd978356fa8c8110df945dfe8120ab5ad9a/mysql/datadog_checks/mysql/const.py#L89-L91
Documentation is incorrect.
=> [mysql] fix documentation: change mysql.innodb.buffer_pool_* from pages to bytes

http_check/datadog_checks/http_check/http_check.py, http_check/tests/test_http_integration.py
Improves the service check message when a cert is not found such as when `tls_verify` is false. Currently the error is just `'notAfter'` which is confusing. Now it returns `'KeyError(\'notAfter\')'` which is slightly better, this could be improved more.
QA for https://github.com/DataDog/integrations-core/pull/11615
Alternative approaches are to make a better error message for this specific case
=> Improve service check message when cert is not found

datadog_checks_base/datadog_checks/base/checks/base.py, datadog_checks_base/tests/base/checks/test_agent_check.py
https://github.com/DataDog/integrations-core/pull/11508
Also put filtering before tag logic for performance
=> Fix `metric_patterns` option to support namespaces

ecs_fargate/assets/configuration/spec.yaml, ecs_fargate/datadog_checks/ecs_fargate/data/conf.yaml.default, vsphere/assets/configuration/spec.yaml, vsphere/datadog_checks/vsphere/data/conf.yaml.example
Removes the outdated warning in the `tls_ignore_warning` description for vsphere (does not use the http spec template) and ecs_fargate (has a `conf.yaml.default` file). 
QA for https://github.com/DataDog/integrations-core/pull/11591
=> Remove outdated warning in the description for the `tls_ignore_warning` option

kubelet/datadog_checks/kubelet/kubelet.py, kubelet/datadog_checks/kubelet/probes.py, kubelet/tests/test_kubelet.py
Add a detection check before collecting probe metrics introduced in https://github.com/DataDog/integrations-core/pull/11682
Avoid this
```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://<ip>:10250/metrics/probes
```
=> Handle probe metrics when the endpoint is not available (k8s < 1.15)

datadog_checks_base/datadog_checks/base/utils/db/utils.py, datadog_checks_base/tests/base/utils/db/test_util.py
Updates the `obfuscate_sql_with_metadata` wrapper to prevent unnecessarily throwing exceptions from decoding attempts. We found that `orjson` leaks memory when failing to parse these strings which are not valid json.
Note, this change is only relevant when integrations are running on an agent before 7.34.
Relevant PR: https://github.com/DataDog/datadog-agent/pull/10042
Before
After
=> Fix obfuscate_sql_with_metadata wrapper memory usage

datadog_checks_base/tests/base/utils/db/test_util.py
A previous PR attempted to fix this race condition: https://github.com/DataDog/integrations-core/pull/10563
While the theory of the fix was valid, the implementation missed an important change: the sleep time should have been decreased but the rate limit time should have remained at 1s. This change should properly fix the race.
=> Fix race condition in test for async jobs

ecs_fargate/README.md
ECS Fargate platform version 1.4.0 has been out since Nov 2020, so specify 1.4.0 as the platform version in your run-task example.
In `aws ecs run-task ...` command specify v1.4.0 instead of v1.1.0.
Help customers who copy/paste the example `aws ecs run-task ...` command to use the current version of Fargate.
=> Specify ECS Fargate platform-version 1.4.0 in run-task command

datadog_checks_dev/datadog_checks/dev/tooling/configuration/spec.py, datadog_checks_dev/tests/tooling/configuration/test_load.py, docs/developer/meta/config-specs.md
Add note in the config spec docs about `conf.yaml.default` files.
=> Add conf.yaml.default as a default config example_name

ibm_i/assets/configuration/spec.yaml, ibm_i/datadog_checks/ibm_i/check.py, ibm_i/datadog_checks/ibm_i/config_models/defaults.py, ibm_i/datadog_checks/ibm_i/config_models/instance.py, ibm_i/datadog_checks/ibm_i/data/conf.yaml.example, ibm_i/datadog_checks/ibm_i/queries.py, ibm_i/tests/test_ibm_i.py
Add `queries` option to be able to declare which queries are run against the IBM i machine.
Each query has a `name` field for now, so that we can introduce further properties in the future.
Same as #11805, but against master branch
=> Add option to select which queries to run

cockroachdb/assets/dashboards/overview.json
This PR fixes the cockroachDB dashboard to use `$scope` instead of hardcoded `*`.
Support case.
=> Update dashboard to use `scope`

iis/datadog_checks/iis/iis.py, iis/datadog_checks/iis/metrics.py, iis/metadata.csv, iis/tests/common.py
The counter for this metric doesn't exist and has been causing a lot of logs from being generated.
Support cases.
=> Remove http patch requests per second metric

datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/prometheus.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/meta/scripts/metrics2md.py, datadog_checks_dev/datadog_checks/dev/tooling/commands/validate/metadata.py, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/check/{check_name}/metadata.csv, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/jmx/{check_name}/metadata.csv, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/logs/{check_name}/metadata.csv, datadog_checks_dev/datadog_checks/dev/tooling/templates/integration/tile/{check_name}/metadata.csv, openshift/gen_clusterquota_metadata.py
This pr is the last step of migrating all metadata.csv files in all repos to add the new `curated_metric` column. In this step we are requiring `curated_metric` to be a column (though can be empty) now that all new metadata.csv files generated should include this column.
Previous pr that allowed `curated_metric` to be optional - https://github.com/DataDog/integrations-core/pull/11168
We want to allow defining metrics for a given integration as a 'curated' metric. A metric selected here can be given a type (starting with 'cpu' or 'memory') to group metrics by when users are investigating issues based on that type. We will give these metrics more emphasis in the UI of our products (Live Processes to start) relative to other metrics.
=> Update metadata.csv to require curated_metric column

snmp/assets/configuration/spec.yaml, snmp/datadog_checks/snmp/data/conf.yaml.example
Updating comments for parameters timeout and retries to accurately reflect what our go corecheck sets defaults to. The default value of timeout is 2 and the default value of retries is 3 according to [config.go](https://github.com/DataDog/datadog-agent/blob/main/pkg/collector/corechecks/snmp/internal/checkconfig/config.go)
Keeping our documentation up to date so customers don't get confused here
N/A
=> updating snmp check documentation for timeout and retries

snmp/datadog_checks/snmp/data/profiles/_aruba-switch-cpu-memory.yaml, snmp/datadog_checks/snmp/data/profiles/_checkpoint-firewall-cpu-memory.yaml, snmp/datadog_checks/snmp/data/profiles/_cisco-cpu-memory.yaml, snmp/datadog_checks/snmp/data/profiles/_cisco-generic.yaml, snmp/datadog_checks/snmp/data/profiles/_f5-big-ip-cpu-memory.yaml, snmp/datadog_checks/snmp/data/profiles/_fortinet-fortigate-cpu-memory.yaml, snmp/datadog_checks/snmp/data/profiles/_generic-host-cpu-memory.yaml, snmp/datadog_checks/snmp/data/profiles/_generic-host-resources.yaml, snmp/datadog_checks/snmp/data/profiles/aruba-switch.yaml, snmp/datadog_checks/snmp/data/profiles/checkpoint-firewall.yaml, snmp/datadog_checks/snmp/data/profiles/f5-big-ip.yaml, snmp/datadog_checks/snmp/data/profiles/fortinet-fortigate.yaml, snmp/tests/test_e2e_core.py, snmp/tests/test_e2e_core_vs_python.py, snmp/tests/test_profiles.py
Add abstract memory and cpu usage metrics to snmp profiles, with `scale_factor` when needed. `scale_factor` is implemented only in `core` check in PR https://github.com/DataDog/datadog-agent/pull/11438. As `scale_factor` is not supported as of today, I will add a dedicated test in a follow up PR once https://github.com/DataDog/datadog-agent/pull/11438 is merged.
When part of a table, cpu metrics are tagged by `cpu` and memory metrics are tagged by `mem`.
I added an e2e test based on a profile that is exposing cpu and memory usage metrics for core check.
We are adding support for cross-profile metrics: we want to provide with generic information about devices, as we are doing for interface level metrics. While interface metrics have a standard across vendors, cpu and memory are exposed in …
=> [snmp] add memory and cpu abstract metrics

mysql/README.md
Changes the `password` parameter in the `Metric collection` section for all tabs -- Host, Docker, Kubernetes, and ECS. Specifically, it updates the parameter from `pass` to `password`, in order to make the doc consistent with the example YAML file linked here:
https://github.com/DataDog/integrations-core/blob/master/mysql/datadog_checks/mysql/data/conf.yaml.example#L42
DOCS-3394
=> DOCS-3394 Update password parameter in Metric collection section

mysql/datadog_checks/mysql/activity.py, mysql/datadog_checks/mysql/statement_samples.py, mysql/datadog_checks/mysql/statements.py, mysql/tests/test_mysql.py, mysql/tests/test_query_activity.py, mysql/tests/test_statements.py
Fixes the `host` reported on the activity payloads for MySQL.
If a user configures the integration's `reported_hostname` option, the activity payload will not contain the configured hostname.
=> mysql: Fix activity host reporting

sqlserver/datadog_checks/sqlserver/activity.py, sqlserver/datadog_checks/sqlserver/statements.py, sqlserver/tests/test_activity.py, sqlserver/tests/test_statements.py
Fixes the `host` reported on the activity and plan payloads for SQL Server.
If a user configures the integration's `reported_hostname` option, these payloads will not contain the configured hostname.
=> sqlserver: Fix activity and plan host reporting

traffic_server/assets/configuration/spec.yaml, traffic_server/datadog_checks/traffic_server/data/conf.yaml.example
Add more traffic_server metrics to be collected by default 
Traffic Server differentiates some of the same metrics by http2/http and http/https, and we want to collect all these metrics in the default config file.
=> Add more default metrics

traffic_server/assets/service_checks.json, traffic_server/datadog_checks/traffic_server/check.py, traffic_server/tests/test_traffic_server.py
Adds a traffic_server_url tag to all metrics and service checks
Most checks send a basic endpoint tag, and there are cases when a traffic server host can be monitored remotely.
=> Add `traffic_server_url` tag

datadog_checks_base/datadog_checks/base/stubs/aggregator.py
Use sorted tags for expected metric in aggregator stub
Having sorted expected metric tags makes it easier to compare when reading test assertion failures. 
For example in the example before, the actual metric contain `device_namespace:default` but it's not present in expected tags. When the tags are sorted, it's easier to spot that `device_namespace:default` is not present in expected metrics tag.
Before:
```
E   AssertionError: Needed at least 1 candidates for 'datadog.snmp.check_duration', got 0
E   Expected:
E           MetricStub(name='datadog.snmp.check_duration', type=0, value=None, tags=['snmp_profile:apc_ups', 'model:APC Smart-UPS 600', 'firmware_version:2.0.3-test', 'serial_num:test_serial', 'ups_name:testIdentName', 'device_vendor:apc', 'snmp_device:172.18.0.2', 'loader:core'], …
```
=> Use sorted tags for expected metric in aggregator stub

postgres/datadog_checks/postgres/statement_samples.py, postgres/tests/test_statements.py
This adds the `query_truncated` field that we have on query samples to the activity rows returned during activity collection. 
The `query_truncated` field can be used to determine if a query was truncated or not which can then be used to explain why a query statement might been missing for having failed to obfuscate.
=> Add query_truncated field on activity rows

eks_fargate/README.md
Fixes hyperlink for https://docs.datadoghq.com/integrations/eks_fargate/#running-the-cluster-agent-or-the-cluster-checks-runner in https://docs.datadoghq.com/integrations/eks_fargate/#events-collection
Broken link in the documentation
N/A
=> Fix hyperlink for running the cluster agent in EKS Fargate

mongo/datadog_checks/mongo/utils.py, mongo/tests/test_integration.py
Allow passing in username and password as options 
Some authentication methods require a username and/or password when initializing the client in pymongo.
https://github.com/mongodb/mongo-python-driver/blob/master/pymongo/auth.py#L105
=> Fix passing in username and password as options

proxysql/assets/configuration/spec.yaml, proxysql/datadog_checks/proxysql/data/conf.yaml.example, proxysql/datadog_checks/proxysql/proxysql.py, proxysql/datadog_checks/proxysql/queries.py, proxysql/metadata.csv, proxysql/tests/common.py, proxysql/tests/test_integration.py
This PR add a new additional metric to know the numbers of mysql backends and their status (as tags of the metric)
Currently there is a service check on backend status but no metrics.
The service check does not meet our needs as it does not allow to customize queries (ex: no custom time range evaluation)
Despite there is already a service check `proxysql.backend.status`. This PR seems the only way to correctly monitor and alert on mysql backends count/status
=> add a new metric on backends count and status for proxysql

docs/developer/process/agent-release/post-release.md
Step 2 was a bit unclear. The instructions made it seem like the integration release pipeline triggering can be done in parallel with the creation of the PR. I moved it to its own step to hopefully make it clearer that the release pipeline should be triggered after the PR has been merged in.
=> Clarify the instructions releasing integration

amazon_eks_blueprints/README.md, amazon_eks_blueprints/manifest.json, oke/README.md, oke/manifest.json
Removes mention of log collection from the docs and removes the `log collection` category from manifest.json. 
There isn't a default logs pipeline for kubernetes logs and the presence of the `log collection` category causes the weekly integrations logs pipeline CI to fail. 
Other K8s orchestration integration tiles do not have the `log collection` category, such as [gke](https://github.com/DataDog/integrations-core/blob/ebb8e70be0d8301172a0432b6c8e6a354852f555/gke/manifest.json#L18-L21).
=> Remove log collection from docs

.github/workflows/validations.yaml, apache/README.md
Adds a step to set a `changed` env variable in the validations workflow in order to set format `ddev` command dynamically depending on github event.
Currently, `ddev validate` is not run on push to master, as the validations workflow has `ddev validate <COMMAND> changed` and no integrations are changed.
`AI-2263`
=> Run validations on master

datadog_checks_dev/datadog_checks/dev/plugin/tox.py
Latest release 3.17.6, from April 27 causes the following error on glusterfs:
`datadog_checks/glusterfs/check.py:9:1: error: Library stubs not installed for "simplejson" (or incompatible with Python 2.7)`
=> Pin types-simplejson==3.17.5

varnish/datadog_checks/varnish/varnish.py
Avoid getting this stacktrace:
```
Error: get_subprocess_output expected output but had none.
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 1071, in run
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/varnish/varnish.py", line 157, in check
output, err, _ = get_subprocess_output(cmd, self.log)
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/utils/subprocess_output.py", line 56, in get_subprocess_output
out, err, returncode = subprocess_output(cmd_args, raise_on_empty_output, env=env)
_util.SubprocessOutputEmptyError: get_subprocess_output expected output but had none.
```
=> Do not raise exeptions on empty outout of varnishadm

.gitlab-ci.yml
Fix the gitlab jobs to trigger on changes in all subdirectories of the given directories.
We noticed the tagger job did not run on every change to `datadog_checks_dev`, and realized it was an issue with the pattern for `only` `changes`. This PR is updating all stages in the pipeline to trigger on changes to any subdirectories. 
https://gitlab.com/gitlab-org/gitlab-foss/-/issues/59540
=> Fix glob pattern for gitlab changes

tcp_check/tests/common.py, tcp_check/tests/test_tcp_check.py
Fix the flakiness of the `test_ipv6` test of the `tcp_check` check. 
The `app.datadoghq.com` DNS name that was previously used had more than 8 IPv4/IPv6 behind. But the python DNS API returns only a subset of 8 of them.
The fact that the subset can be different between calls leaded to test flakiness.
`app.datad0g.com` on the other hand resolves only to 3 IPv4/IPv6. So, the DNS query python API will consistently always return the same 3 values.
=> Fix `tcp_check` check `test_ipv6` test flakiness

datadog_checks_base/datadog_checks/base/data/agent_requirements.in, datadog_checks_base/pyproject.toml
In latest versions a check has been added on the values read from POD `status` sub-resource.
It can prevent some checks from running if a controller is setting non-standard conditions in status, with error like:
```
Error: Invalid value for `condition_type` (xxxx), must be one of ['ContainersReady', 'Initialized', 'PodScheduled', 'Ready']
```
Bugfix.
=> Fallback Kubernetes client version to 22.6 to avoid failures on non-standard POD conditions

haproxy/manifest.json
in_rate is marked as Legacy and  in_total is only available if using V1 of the check so the tile does not detect the integration when running v2
=> Add newer metric to check

LICENSE-3rdparty.csv, datadog_checks_base/datadog_checks/base/data/agent_requirements.in, http_check/pyproject.toml
Unpins urllib3
The code that originally sparked the addition of it is now deleted: https://github.com/DataDog/integrations-core/pull/11926 https://github.com/DataDog/integrations-core/pull/11069
=> Don't pin urllib3

snowflake/tests/common.py, snowflake/tests/test_snowflake.py, snowflake/tests/test_unit.py
Don't use the deprecated parameter `user` in tests
clean up, stop logging a deprecation warning in tests
=> Don't use deprecated param in tests

cisco_aci/README.md, cisco_aci/tests/cisco_aci_query.py
This PR adds a troubleshooting section in the README of `cisco_aci` for missing `tenant` metrics. This also adds a script that `curl`s the tenant endpoint to verify if there are tenant metrics to collect.
Many support cases.
=> Add troubleshooting notes and script

cilium/README.md
This PR fixes a README error: `default: true` should be `default: false` for `use_openmetrics` to match actual implementation: https://github.com/DataDog/integrations-core/blob/master/cilium/assets/configuration/spec.yaml#L19-L20
=> Update cilium README

datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/scraper.py, datadog_checks_base/tests/base/checks/openmetrics/test_interface.py, datadog_checks_base/tests/models/test_interface.py
We should have the ability to ignore the endpoint tag. This should be with ignore_tags and not exclude_labels (see https://github.com/DataDog/integrations-core/pull/11955)
=> Add the ability to exclude endpoint tag

oracle/tests/scripts/install_instant_client.sh
In https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=98800&view=logs&j=c3a06451-088b-587c-b2b9-012b146267bb&t=8b8da6bd-8c7d-5c16-284a-eb82cfe91ae0&l=147
Environment set up failed with:
```
Setting up unzip (6.0-26ubuntu1) ...
Archive:  /opt/oracle/instantclient.zip
inflating: /opt/oracle/instantclient_19_3/adrci  
...
mkdir: cannot create directory '/opt/oracle': File exists
debconf: delaying package configuration, since apt-utils is not installed
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
11 35.0M   11 4112k    0     0  4412k      0  0:00:08 --:--:--  0:00:08 4407k
100 35.0M  100 35.0M    0     0  19.8M      0 …
```
=> Oracle to not fail to create directory

kafka_consumer/datadog_checks/kafka_consumer/datadog_agent.py, kafka_consumer/datadog_checks/kafka_consumer/new_kafka_consumer.py, kafka_consumer/metadata.csv, kafka_consumer/tests/test_kafka_consumer.py, kafka_consumer/tox.ini
Adds a new metric for the kafka_consumer integration: lag in seconds.
It's a best effort metric, but I think it's still really valuable. Lag in seconds is much more usable than lag in messages (currently available metric).
=> Add new lag in seconds metric

openmetrics/tests/conftest.py, openmetrics/tests/test_openmetrics.py
Adds test to assert counters with `_total` suffix. 
Support case
=> Add test asserting _total suffix counters

datadog_checks_base/datadog_checks/base/checks/openmetrics/v2/scraper.py, datadog_checks_base/tests/base/checks/openmetrics/test_config.py, openmetrics/tests/conftest.py, openmetrics/tests/test_openmetrics_strict.py
With this change, the openmetrics check should request the appropriate
exposition format fixing "Clashing name" errors.
The exposition format to request is set via the "Accept" header. Despite
the OpenMetricsScraper appearing to set the correct header when
`use_latest_spec` is enabled, it is actually a no-op due to the default
HTTP headers including `Accept: */*` and the use of `setdefault`.
Tests incoming. It appears that there were no existing tests of `use_latest_spec` or the new exposition format.
=> Fix incorrect OpenMetrics V2 check exposition format HTTP header

ibm_was/tests/docker/scripts/9.0.5.5/init.jython, ibm_was/tests/docker/scripts/9.0.5.9/init.jython, ibm_was/tox.ini
Fix broken ibm_was e2e by bumping the ibm_was docker image version. 
Broken CI
=> Bump e2e docker image version

kubelet/datadog_checks/kubelet/kubelet.py, kubelet/tests/test_kubelet.py
Apply container filter to `kubernetes.kubelet.container.log_filesystem.used_bytes`
Bug fix
=> Apply container filter to `kubernetes.kubelet.container.log_filesystem.used_bytes`

kubelet/datadog_checks/kubelet/kubelet.py, kubelet/tests/test_kubelet.py
Sanitise the `url` tag of the `kubernetes.rest.client.latency` metric of the `kubelet` check.
The `url` tag of the `kubernetes.rest.client.latency` metric is causing some high cardinality issue.
In order to reduce the cardinality, we strip the `url` tag to keep only the path.
The `url` tag contains all the possible values for the Kubernetes API server calls made by the kubelet.
Ex.: `https://35.242.243.158/api/v1/namespaces/%7Bnamespace%7D/configmaps?fieldSelector=%7Bvalue%7D&limit=%7Bvalue%7D&resourceVersion=%7Bvalue%7D`
The host of the url is the Kubernetes API server.
Whereas it is the same for all the kubelet inside a cluster, it will be different in two different clusters.
Dropping the host part of the url will ease the comparison of `kubernetes.rest.client.latency` between different …
=> [kubelet] Sanitize the `url` tag

sqlserver/datadog_checks/sqlserver/metrics.py, sqlserver/tests/test_integration.py
Explicitly specify `database_id` when calling `OBJECT_NAME` when collecting fragmentation metrics. 
Also fix python2 unicode handling. 
When `database_autodiscovery: True` then `object_name` was always `none` for any objects that came from a database other than the default database.
This is because [object_name](https://docs.microsoft.com/en-us/sql/t-sql/functions/object-name-transact-sql?view=sql-server-ver15) defaults to assuming it's in the current database context if not specified.
The broken unicode handling was revealed only when this query was changed to start including some DB objects with non-ascii characters in them which were not included previously.
=> Fix missing object_name for index fragmentation metrics

nginx_ingress_controller/README.md
Added clarification that this integration currently only supports the Kubernetes distribution of NGINX Ingress Controller, while the F5 distribution needs to be configured separately using Prometheus for now.
Clarification on out of scope use case, and workaround.
https://datadoghq.atlassian.net/browse/CONS-4307
=> Add clarification on supported NGINX Ingress distros

etcd/README.md
Adding a secondary reference to Further Reading in case the user is deploying etcd on a Kubernetes cluster.
Adding a secondary reference to Further Reading in case the user is deploying etcd on a Kubernetes cluster.
Multiple hours of trying to figure out why the etcd integration was running into internal certificate issues on a standard kubernetes cluster. Ultimately, found the solution on this secondary page. Pages should be linked.
=> Adding secondary link

windows_service/README.md
Some users will find that the service name includes a special character - MSSQL$CRMAWS - in this instance when they enter this into the configuration file just as it is, the windows service check will return unknown. What's happening is that the $ gets turned into an underscore and the agent can't find it since that isn't its name. They need to escape special characters like this - MSSQL\$CRMAWS for the service name to be properly found. Since this isn't mentioned anywhere in this doc, there only option is to ask support why its messed up.
=> Add note about special characters in property name

calico/tests/conftest.py
Pins the version of calico to 3.22. Between 3.23 and 3.22, one of the metric we assert got deprecated:
`felix_active_local_tags`:
https://projectcalico.docs.tigera.io/archive/v3.22/reference/felix/prometheus
Versus:
https://projectcalico.docs.tigera.io/reference/felix/prometheus
=> Pin Calico test env to v3.22

snowflake/datadog_checks/snowflake/config_models/validators.py, snowflake/tests/test_config.py
Properly validate metric groups and `only_custom_queries`
previously when `only_custom_queries` was enabled, it errored:
```
__root__
'dict' object is not callable
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 1095, in run
initialization()
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 489, in load_configuration_models
instance_config = self.load_configuration_model(package_path, 'InstanceConfig', raw_instance_config)
File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 533, in load_configuration_model
raise_from(ConfigurationError('\n'.join(message_lines)), None)
File "<string>", line 3, in …
```
=> Properly validate `only_custom_queries`

kong/README.md
I worked with a customer recently who copied the value in the instance config section. He then followed the auto-discovery integration template [5] to find how he should setup the config file. The extra : that he had copied was causing his configuration not to function. After removing the : he stopped receiving errors. I'm not sure if removing the : is the best approach to avoid any confusion like this but wanted to bring it your attention just to get the ball rolling.
https://datadog.zendesk.com/agent/tickets/783413
I'm open to suggestions regarding how to approach this.
=> remove extra : in the value field for `<INSTANCE_CONFIG>`

calico/metadata.csv
Document that the metric for `felix_active_local_tags` is deprecated in ver. 3.23 of Calico
=> document metric deprecation

datadog_checks_dev/datadog_checks/dev/tooling/configuration/consumers/example.py, datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/init_config.yaml, datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances.yaml, datadog_checks_dev/tests/tooling/configuration/consumers/test_example.py
Fixes the `enabled` option for parent config options. Previously, `enabled: false` was not getting taken into account. 
Bug
The `enabled` option value does not propagate to the nested options. `enabled` would still need to be configured for the nested options, if applicable.
=> Fix `enabled` for parent options

aerospike/datadog_checks/aerospike/data/conf.yaml.example, amazon_msk/datadog_checks/amazon_msk/data/conf.yaml.example, arangodb/datadog_checks/arangodb/data/conf.yaml.example, avi_vantage/datadog_checks/avi_vantage/data/conf.yaml.example, calico/datadog_checks/calico/data/conf.yaml.example, cilium/datadog_checks/cilium/data/conf.yaml.example, cockroachdb/datadog_checks/cockroachdb/data/conf.yaml.example, coredns/datadog_checks/coredns/data/conf.yaml.example, envoy/datadog_checks/envoy/data/conf.yaml.example, haproxy/datadog_checks/haproxy/data/conf.yaml.example, istio/datadog_checks/istio/data/conf.yaml.example, kong/datadog_checks/kong/data/conf.yaml.example, linkerd/datadog_checks/linkerd/data/conf.yaml.example, pulsar/datadog_checks/pulsar/data/conf.yaml.example, vault/datadog_checks/vault/data/conf.yaml.example
Sync config files 
https://github.com/DataDog/integrations-core/pull/11981/s
=> Add OM v2 counters note to `extra_metrics` config example

calico/requirements-dev.txt, foundationdb/requirements-dev.txt
Installs the correct dev package in tests
Calico e2e is failing even when a [fix](https://github.com/DataDog/integrations-core/pull/12004) is implemented in ddev. These two checks were previously in integrations-extras and their `requirements-dev.txt` were not updated after the move. Foundationdb does not currently have an e2e test but could in the future
=> Install latest dev package

mysql/datadog_checks/mysql/data/conf.yaml.example, postgres/datadog_checks/postgres/data/conf.yaml.example, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example, vsphere/datadog_checks/vsphere/data/conf.yaml.example
Fixes uncommented parent config options that should be commented out (these options are disabled by default in their respective spec.yaml).
https://github.com/DataDog/integrations-core/pull/11707
=> Fix uncommented parent options

mysql/CHANGELOG.md, mysql/datadog_checks/mysql/__about__.py, postgres/CHANGELOG.md, postgres/datadog_checks/postgres/__about__.py, requirements-agent-release.txt, sqlserver/CHANGELOG.md, sqlserver/datadog_checks/sqlserver/__about__.py, traffic_server/CHANGELOG.md, traffic_server/datadog_checks/traffic_server/__about__.py
Metadata ports from the releases off of 7.36.x. Duplicate of #11868.
=> Metadata updates from releases off of 7.36.x branch

sqlserver/assets/configuration/spec.yaml, sqlserver/datadog_checks/sqlserver/config_models/defaults.py, sqlserver/datadog_checks/sqlserver/config_models/instance.py, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example, sqlserver/datadog_checks/sqlserver/sqlserver.py, sqlserver/datadog_checks/sqlserver/statements.py, sqlserver/tests/test_statements.py
Adds three new fields associated with the database-monitoring product in order to help support the new (beta) DB List feature. Ingesting this extra cloud related metadata will allow for us to link managed cloud resource metrics emitted by Datadog cloud crawlers to database-monitoring reported hosts.
=> Add support to ingest cloud_metadata for DBM host linking

sqlserver/datadog_checks/sqlserver/statements.py, sqlserver/tests/test_statements.py
Remove the `user_name` attribute from query metrics and execution plans.
This user attribute has turned out to be confusing to use because it doesn't represent the user that actually executed the query. Instead, it represents the following (from [the docs](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-plan-attributes-transact-sql)): *Value of -2 indicates that the batch submitted does not depend on implicit name resolution and can be shared among different users. This is the preferred method. Any other value represents the user ID of the user submitting the query in the database*.
To remove the confusion we are removing this attribute.
By removing the plan user attribute the statement metrics query also becomes less expensive because …
=> Remove execution plan `user_name` attribute

postgres/metadata.csv
`postgresql.deadlocks` is currently implemented as a rate (long-term this should be added as a count). This PR fixes the metadata and documentation for the metric.
=> Fix the units of postgresql.deadlocks

oracle/README.md
Fix shell command to escape nested double quotes- currently this will throw the following error:
```
File "<string>", line 1
import os; print(JAVA_HOME:{}.format(os.environ.get(JAVA_HOME)))
^
SyntaxError: invalid syntax
```
Support ticket
=> Fix python command

sqlserver/assets/configuration/spec.yaml, sqlserver/datadog_checks/sqlserver/config_models/instance.py, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example, sqlserver/datadog_checks/sqlserver/sqlserver.py
Adds configuration options for parsing dollar quoted functions and for keeping sql aliases to sql server.
The obfuscator has options to enable parsing for dollar quoted functions and keeping sql aliases, however these options are not currently configurable from DBM.
=> sqlserver: Add option to keep aliases in sql server (`keep_sql_alias`)

postgres/assets/configuration/spec.yaml, postgres/datadog_checks/postgres/config.py, postgres/datadog_checks/postgres/config_models/instance.py, postgres/datadog_checks/postgres/data/conf.yaml.example
Adds configuration options for parsing dollar quoted functions and for keeping sql aliases to postgres.
The obfuscator has options to enable parsing for dollar quoted functions and keeping sql aliases, however these options are not currently configurable from DBM.
=> postgres: Add option to keep alias and dollar quote functions in postgres (`keep_sql_alias` and `keep_dollar_quoted_func`)

mysql/assets/configuration/spec.yaml, mysql/datadog_checks/mysql/config.py, mysql/datadog_checks/mysql/config_models/defaults.py, mysql/datadog_checks/mysql/config_models/instance.py, mysql/datadog_checks/mysql/data/conf.yaml.example
Adds configuration options for parsing dollar quoted functions and for keeping sql aliases to mysql.
The obfuscator has options to enable parsing for dollar quoted functions and keeping sql aliases, however these options are not currently configurable from DBM.
=> mysql: Add option to keep aliases in mysql (`keep_sql_alias`)

.azure-pipelines/templates/test-single-windows.yml, sqlserver/assets/configuration/spec.yaml, sqlserver/datadog_checks/sqlserver/config_models/defaults.py, sqlserver/datadog_checks/sqlserver/config_models/instance.py, sqlserver/datadog_checks/sqlserver/connection.py, sqlserver/datadog_checks/sqlserver/data/conf.yaml.example
Fixes bug where `ConnectRetryCount` was being set by default for all SQLServer connection strings. This feature is only available for server versions 2014, and newer.  See these [docs](https://docs.microsoft.com/en-us/sql/connect/odbc/connection-resiliency?view=sql-server-ver15) on the connection resiliency feature for more information. 
Also adds `MSOLEDBSQL19` to the list of valid `adoproviders` drivers. The latest versions of the driver for SQLServer 2018+ were renamed. See this [documentation](https://docs.microsoft.com/en-us/sql/connect/oledb/oledb-driver-for-sql-server?view=sql-server-ver15#3-microsoft-ole-db-driver-for-sql-server-msoledbsql) for more details. This was causing the following error: 
```
MSOLEDBSQL 'Provider cannot be found. It may not be properly installed.' error …
```
=> Don't use connection resiliency for older versions of sqlserver and update valid driver list

aerospike/datadog_checks/aerospike/data/conf.yaml.example, amazon_msk/datadog_checks/amazon_msk/data/conf.yaml.example, arangodb/datadog_checks/arangodb/data/conf.yaml.example, avi_vantage/datadog_checks/avi_vantage/data/conf.yaml.example, calico/datadog_checks/calico/data/conf.yaml.example, cilium/datadog_checks/cilium/data/conf.yaml.example, cockroachdb/datadog_checks/cockroachdb/data/conf.yaml.example, coredns/datadog_checks/coredns/data/conf.yaml.example, datadog_checks_dev/datadog_checks/dev/tooling/templates/configuration/instances/openmetrics.yaml, envoy/datadog_checks/envoy/data/conf.yaml.example, haproxy/datadog_checks/haproxy/data/conf.yaml.example, istio/datadog_checks/istio/data/conf.yaml.example, kong/datadog_checks/kong/data/conf.yaml.example, linkerd/datadog_checks/linkerd/data/conf.yaml.example, openmetrics/datadog_checks/openmetrics/data/conf.yaml.example, pulsar/datadog_checks/pulsar/data/conf.yaml.example, vault/datadog_checks/vault/data/conf.yaml.example
Fixes the example in the description of extra_metrics
QA for https://github.com/DataDog/integrations-core/pull/12012/s
=> Fix extra metrics description example

teradata/datadog_checks/teradata/check.py, teradata/datadog_checks/teradata/utils.py, teradata/tests/test_utils.py
Adds error handling when collecting teradata version
If the version query in teradata returns nothing, then the check will fail. Version collection should not block the check run, so we should handle this error, log it, and continue.
QA for: https://github.com/DataDog/integrations-core/pull/11701/files
=> Add error handling when collecting version

teradata/manifest.json
Excludes mac as a supported platform for teradata 
QA for https://github.com/DataDog/integrations-core/pull/11701, teradatasql  is not properly signed for mac. see https://github.com/DataDog/datadog-agent/pull/12119
=> Remove mac support docs

http_check/datadog_checks/http_check/http_check.py, http_check/tests/test_http_integration.py
This PR checks whether there is a cert returned from `getpeercert()` before getting the expiration date from the cert and logs a more straight-forward message when there is no cert. This prevents the `KeyError` that would otherwise return when attempting to retrieve the expiration date from a non-existent cert. 
QA https://github.com/DataDog/integrations-core/pull/11793
There seem to be some differences in how `ssl.SSLSocket.getpeercert()` handles empty/no certificates between py27 and py38. The `getpeercert` method matches hostname in both python versions, but py27 uses the `match_hostname()` method (which returns the `ValueError` when there is no [cert](https://github.com/python/cpython/blob/8d21aa21f2cbc6d50aab3f420bb23be1d081dac4/Lib/ssl.py#L263-L266)) and it was changed in python 3.7 …
=> Clarify no cert service check message

arangodb/tests/docker/arangodb3/arangod.conf, arangodb/tests/docker/docker-compose.yaml
This PR overrides the default `arangod.conf` to output logs to a file. By default, ArangoDB does not output logs to a file.
QA for https://github.com/DataDog/integrations-core/pull/11292
=> Modify test env to output logs to a file

mysql/datadog_checks/mysql/const.py, mysql/datadog_checks/mysql/mysql.py
Re: https://github.com/DataDog/integrations-core/issues/12074
This PR reverts the change in metric_type for the mysql.net.connections metric. Originally, the python code had the metric_type as a RATE, but was later changed due to confusion from the metadata.csv file where it's declared as GAUGE. The reason why the python code declares this as RATE type is because this informs the agent on how to handle/compute the value of the metric, but it's later mapped to a gauge type when sent to our back-end. This is why the metadata file declares this as a GAUGE.
This PR reverts the migration of the metric `mysql.net.connections` from DBM's back-end. This metric was migrated to DBM (if dbm was enabled for this integration) for a few reasons, but to list the main points:
- This metric was supposed …
=> Revert mysql.net.connections metric type

datadog_checks_base/datadog_checks/base/checks/windows/perf_counters/base.py
Client feels as though events related to performance counters ("Refreshing counters for performance object..." and "Collecting query data for performance object...") are filling up their INFO level logs too quickly. They would like for us to downgrade performance counter events to DEBUG level.
=> Change refreshing counters log level to debug

helm/README.md, helm/manifest.json
Set "creates_events" to true in the Helm integration.
The integration didn't create events in the first release, but it does starting from agent v7.36.0.
Merge after agent 7.36.0 is released.
=> [helm] Set "creates_events" to true

helm/assets/monitors/monitor_failed_releases.json, helm/manifest.json
Adds a monitor for the Helm integration. It's a monitor that triggers when there are Helm releases marked as "failed".
This monitor is based on the `helm.release_state` service check (ref: https://github.com/DataDog/integrations-core/pull/11766)
This needs to be merged after 7.36.0 is released.
=> [helm] Add monitor for failed releases

etcd/assets/configuration/spec.yaml, etcd/assets/service_checks.json, etcd/datadog_checks/etcd/data/conf.yaml.example
This PR updates the etcd service check docs to include `etcd.prometheus.health`.
The etcd check has a Prometheus and non-Prometheus check depending on `use_preview`. The service checks emitted by the two versions are different, although this isn't documented.
=> Update etcd service check documentation

mongo/assets/configuration/spec.yaml, mongo/datadog_checks/mongo/config.py, mongo/datadog_checks/mongo/config_models/instance.py, mongo/datadog_checks/mongo/config_models/validators.py, mongo/datadog_checks/mongo/data/conf.yaml.example, mongo/tests/test_config.py
Most integrations only take a single host as input, this one requires a list. This is confusing to customers and we've had support cases where they've set a string instead of a list.
This PR allows to pass in a single host as a string and converts it to a list
=> [Mongo] Allow hosts to be a singular value

airflow/README.md
The airflow integration `dogstatsd_mapper_profiles` example was missing the "airflow" prefix in the match strings for a few entries. This PR fixes those instances.
The incorrect matches caused all of the metrics to be ingested without mapping, causing them not to be  considered part of the airflow integration in datadog.
n/a
=> Update airflow integration dogstatsd_mapper_profiles example
